### PR TITLE
[PD] moves Extrude code to FeatureExtrude

### PR DESCRIPTION
**Pull request by donovaly**
- since the Extrude code is only used by Pocket/pad, it should better in FeatureExtrude

was already suggested by @jbaehr in https://github.com/FreeCAD/FreeCAD/pull/5357#issuecomment-1025629327

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5500">pipeline status</a> for feature branch [PR_5500](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5500). Pipeline [464176196](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464176196) was triggered at [c7718e6](https://github.com/FreeCAD/FreeCAD/pull/5500/commits/c7718e6541dd1363ec91591d5a85dbb1379dbe79). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5500">pipeline status</a> for feature branch [PR_5500](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5500). Pipeline [464178231](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464178231) was triggered at [b696070](https://github.com/FreeCAD/FreeCAD/pull/5500/commits/b696070e809f18dd088ca4ae252fb6e049f781c5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5500">pipeline status</a> for feature branch [PR_5500](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5500). Pipeline [464282519](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464282519) was triggered at [4dbb643](https://github.com/FreeCAD/FreeCAD/pull/5500/commits/4dbb643adc1fd6b0e39947ebc1f078ba35b470ed). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5500">pipeline status</a> for feature branch [PR_5500](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5500). Pipeline [464340041](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464340041) was triggered at [15bb9c7](https://github.com/FreeCAD/FreeCAD/pull/5500/commits/15bb9c73be0c0aff7ca413e77c7641e85edaec89). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
The CI succeeds now and I think the PR is ready to be merged. @wwmayer can you please have a look ad when it is fine with you merge?

**Comment by donovaly** [comment]
Since actually no code is changed but only moved according to our new file infrastructure, it should be safe. Also the CI succeeds. -> merging hoping everything works fine.

**Pull request merged**
