### PR TITLE
[Draft] Do not merge, Draft edit improvements and split of Bezcurve code

### PR DESCRIPTION
**Pull request by carlopav**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by carlopav** [comment]
@vocx-fc Can you give a look when you have time?

**Comment by vocx-fc** [comment]
Wau! So you are moving the BezCurve to it's own module?! The way you are doing it is the "proper" way, I think. However, that will create an object with a Proxy class that is `draftobjects.bezcurve.BezCurve`. This is a new object, it is not the old one. The old object expects a Proxy class called `Draft.BezCurve`.

Therefore, your code will work to create new bezier curves, but it won't be able to open old bezier curves previously created. This is the problem that I don't understand exactly how to solve.

Basically, what we would need is that the class `Draft.BezCurve` is redirected to the new class `draftobjects.bezcurve.BezCurve`.

This may be possible to do with the `onDocumentRestored` function. See here [Migrating and upgrading old scripted objects](https://forum.freecadweb.org/viewtopic.php?f=10&t=42948).

---

I'm not sure about the DraftEdit changes, since I've never really delved into that code. I suspect it is fine, but now you are calling the command from the Proxy instead of the DraftEdit class, right?

---

My suggestion was to keep the old `Draft.Bezier` for now, but the editing functions are externalized, that is, something like
```py
# Inside Draft.Bezier
class Bezier(DraftObject):
    ...
    import draftedit.bezier
    smoothBezPoint = draftedit.bezier.smooth_bez_point
```

And inside DraftEdit
```py

elif action_label == "make tangent":
    self.obj.Proxy.smoothBezPoint(obj, idx, 'Tangent')
```

That is, you don't have to move the entire class, because doing this breaks old objects. We just move the editing functions to separate modules.

**Comment by carlopav** [comment]
> Basically, what we would need is that the class `Draft.BezCurve` is redirected to the new class `draftobjects.bezcurve.BezCurve`.
Sure, I was forgetting the changes I made in Draft.py. perhaps it could work like this?

**Comment by vocx-fc** [comment]
To test this use the master branch, then create a single bezier curve. Save the file `bez_master.FCstd`. Then apply your branch, and try opening the same file. If it shows some errors then you can investigate why it didn't work.

Ideally, we want the new module, that is, `draftobjects/bezier.py` to be independent of `Draft.py`. Otherwise we have a circular dependency in which `Draft` imports `bezier`, and `bezier` imports `Draft`. This is the reason I separated some functions into utilities, so that they can be imported by the different objects independently of Draft.

**Comment by carlopav** [comment]
I'll give it a try! I dont think the proposed changes can break backward compatibility, since the code remains exactly the same.
As for circular dependency, this is needed just until we separate the _viewProviderWire from Draft.py. It's the only reason Draft is imported in new module. Anyway, work for next weekend!

**Comment by carlopav** [comment]
@vocx-fc Tryed to save a bezcurve with a version without the patch and open it with a version with the patch. Works ok as expected. No errors:
- with master branch draft edit contains the needed code
- with this patch, draft edit looks for the code in the bezcurve object proxy, and it's there.
What do we need more for merging?
BTW I can go on helping with splitting if you want

**Comment by vocx-fc** [comment]
When you inspect the class of the Proxy object you should have something like this.
```py
App.ActiveDocument.BezCurve.Proxy.__class__
<class 'Draft._BezCurve'>
```

With the new code, do you have the same, or do you have something like this?
```py
App.ActiveDocument.BezCurve.Proxy.__class__
<class 'draftobjects.bezier.BezCurve'>
```
You need to create a document, save it, and try opening it again. Sometimes opening it once works well, but once you save it, you realize the proxy class is not found.

Also, I would suggest using proper Python nomenclature for the new objects, meaning `BezCurve` not `_BezCurve`, and `DraftObject` not `_DraftObject`.

Did you try the unit tests?
```
freecad -t TestDraft
freecadcmd -t TestDraft
```

Ideally, you should also test this from the terminal, so just running `freecadcmd`, importing `Draft`, and testing that `makeBezier` works. As I tell you, I'm worried about circular dependencies. Testing with the entire interface up sometimes masks errors because many modules are pre-imported that setup things that aren't when using a command line session.

I'd also rename the function to `make_bezier` to use Python PEP8 convention. Of course, an alias to the old name should be provided.

I would also change the way we import things. I realize when I refactored the code I didn't do it in this way, but I want to change it.
```py
# old
import something.something2
bla = something.something2.bla

# new
from something.something2 import bla
```

This works the same, but certain editors are able to recognize the imports better in the second way, and show you help about that module.

I mentioned it in the forum, but you should really try using Spyder as editor to develop Python code. In Ubuntu, Spyder3 is available, but if you can install Spyder4 through `pip` that should be better. It's really great, it has many nice features that help you improve your Python code.

About merging this, maybe we can wait until #3012 is merged. That pull request introduces a script to produce an example file of most objects in Draft. This test file can be saved with the master version, and whenever you apply changes to Draft, you can open it to test for any regression.

The script essentially works right now if you comment out a couple of functions that I added in other pull requests that aren't merged yet.

But good job. I'm sure there are other objects that can be re-organized without too much problems. At the moment I'm doing that with GuiCommands, but the object code is also very important because that makes `Draft.py` very big.

**Comment by carlopav** [comment]
For App.ActiveDocument.BezCurve.Proxy.__class__ i get this:
`<class 'draftobjects.bezcurve._BezCurve'>`

I'm on windows. If I run the tests from Test workbech. UnitTests and TestDraft run smoothly without errors.

Ok for rename the function to make_bezier to use Python PEP8 convention and to provide an alias.

Ok also to wait for #3012 to be merged.

I'll try spider.

**Pull request closed without merging**
