### PR TITLE
Stylesheet fixes part trois.

### PR DESCRIPTION
**Pull request by MisterMakerNL**
So now it is hopefully only tiny fixes and then ready for 1.0
Hope this is the last pr for 1.0 for the stylesheets!
https://github.com/FreeCAD/FreeCAD/issues/14745#issuecomment-2231031485

### CODE REVIEW

**Comment by maxwxyz** [comment]
fixes https://github.com/FreeCAD/FreeCAD/issues/14745 ?

**Comment by Syres916** [comment]
Checkboxes on Linux still not functioning, examples from both Preferences and TechDraw Proj Group task panel:

Checkboxes_ChecksNotDisplayed

Three checkboxes are actually `setChecked = true` in the above screenshot and four in the below screenshot. Case-sensitivity must be the root cause if they show up fine in Windows.

TechDrawChecksNotDisplayed


```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38275 (Git)
Build type: Release
Branch: main
Hash: 41d67f8e108a77ec0b98a9ca47d85575eb43476c
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Behave-Dark-Colors 0.1.1
  * FreeCAD-themes 2024.7.24
  * CfdOF 1.27.4

```

**Comment by MisterMakerNL** [comment]
@Syres916 I changed the size of the icons changed the name, Because it maybe a scaling issue, but I do agree with you the most logical thing would be the caps or no caps. But I couldn't find any typo's in the name.

**Comment by Syres916** [comment]
Thanks, checkboxes look fine now, I'll give Qt6.7.2 a spin with it in the morning.

**Comment by Syres916** [comment]
One minor glitch only in FreeCAD Light and seems more pronounced in overlay mode is when the user applies an Expression to a property, the name of the property has what appears to be a white fill block over it, so instead of seeing Length as per example:

ExpressionLinkBehavedark

the user in FreeCAD Light gets:

ExpressionLinkFreeCAD Light

**Comment by MisterMakerNL** [comment]
@Syres916 I think I fixed it, the main preference menu now looks different too as it makes the complete row the selection color.

**Comment by Syres916** [comment]
Yep, works here as well, thanks.

**Pull request merged**
