### PR TITLE
FEM: Add cylinder filter function

### PR DESCRIPTION
**Pull request by marioalexis84**
it is now possible to work with a cylindrical filter function.

image

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8735">pipeline status</a> for feature branch [PR_8735](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8735). Pipeline [796041266](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/796041266) was triggered at [63522ef](https://github.com/FreeCAD/FreeCAD/pull/8735/commits/63522ef455f7c85d614e24b93d3b77bb0ac1d74a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@berndhahnebach do you have a moment to take a look at this PR ?

**Comment by wwmayer** [comment]
From my point of view the code looks all good.

**Comment by donovaly** [comment]
Nice! Looks good to me. As also approved by @wwmayer -> merging.

I see here and there some inconsistencies in the formatting (can be neglected) and will have a look.

@marioalexis84 : I have ta similar thing on my ToDo list: a box (cube) as filter function to have section views in two planes. Since you are already at it, do you think you can implement a box filter as well?

**Comment by donovaly** [comment]
OK, the fix is just to initialize a vector properly: #8784

**Comment by donovaly** [comment]
> @donovaly Yes, we can use two planes with variable angle to each other. I'll work on it.

Cool. However, instead of using two planes, I thought we can use the vtkCubeSource class:
https://kitware.github.io/vtk-examples/site/Cxx/GeometricObjects/Cube1/
and the SoHandleBoxDragger class manipulator
https://www.openinventor.com/reference-manuals/NewRefMan9912/RefManJava/com/openinventor/inventor/draggers/SoHandleBoxDragger.html

For the cylinder function you use the SoJackManip class as manipulator. This is a manipulator for a plane. What is the reason?
I think we should use the SoHandleBoxDragger class.

**Comment by donovaly** [comment]
> For the cylinder function you use the SoJackManip class as manipulator. This is a manipulator for a plane. What is the reason?
I think we should use the SoHandleBoxDragger class.

OK, I see now that the SoHandleBoxManip would be better for the cylinder function. But with this oval cylinders are possible:
FreeCAD_FCHvljR2ng
which is not possible with VTK. The the SoJackManip is no bad choice. However, the initial cylinder is too large and the initial center is not in the center of the object.

**Comment by marioalexis84** [comment]
>This is a manipulator for a plane. What is the reason?

I choose the SoJackDragger since is possible change the orientation of the cylinder. At first I also think on the SoHandleBoxDragger
>However, the initial cylinder is too large and the initial center is not in the center of the object.

Feel free to optimize these values.

> However, instead of using two planes, I thought we can use the vtkCubeSource class

Ok, we can use vtkBox (which inherits from vtkImplicitFunction) any time soon.
With the planes I meant to use 3 planes to obtain a more versatile implicit function by adding the possibility of changing the normal of each plane and obtain this type of implicit function:
image

**Comment by donovaly** [comment]
> I choose the SoJackDragger since is possible change the orientation of the cylinder.

This is also possible with the SoTransformBoxManip, and meanwhile I think we should ise SoTransformBoxManip instead of SoJackDragger because with SoJackDragger you always jet a plane larger than the cylinder. This is misleading for the user.

> > However, the initial cylinder is too large and the initial center is not in the center of the object.
> Feel free to optimize these values.

I give it a try but failed. The problem is this:
FreeCAD_x3DtJq1pVN

So the center is not at the center of the object. This is however the case for a plane function.
The initial radius is OK, but the height of the cylinder should not be twice as large as the object. The same size as the object would look way more nice.
If you have an idea how to achieve this, please make a PR. (I tried 2 hours now and don't get it properly to work.)

> Ok, we can use vtkBox (which inherits from vtkImplicitFunction) any time soon. With the planes I meant to use 3 planes to obtain a more versatile implicit function by adding the possibility of changing the normal of each plane and obtain this type of implicit function: image

Hmm, isn't this overkill? I mean analyses are usually done in Cartesian, cylindrical or spherical coordinates. For the last 2 we have now a function. For Cartesian you need a cube whose faces are perpendicular to each other. I cannot imagine when trapezoidal cubes would be necessary. Can you?

**Comment by donovaly** [comment]
OK, forget what I wrote about SoHandleBoxManip. SoJackDragger is OK. Only the initial position and size should be adjusted.

**Comment by donovaly** [comment]
OK, here is a PR that improves the initial cylinder: #8789

This is better as in master but the optimum would be that the radius of the cylinder would be independent on the drawn height (the blue lines)

**Comment by marioalexis84** [comment]
I will do a pull request with the Cube function and then work on the size of the cylinder.

**Comment by donovaly** [comment]
> I will do a pull request with the Cube function and then work on the size of the cylinder.

Thanks. But note that I already made a PR for the Cylinder height: #8789
With this the height is a bit larger than the object by default to assure the cylinder borders are always visible.

**Pull request merged**
