### PR TITLE
Part: better quantity values handling for primitives

### PR DESCRIPTION
**Pull request by 0penBrain**
Following PR #7219

[Bugfix] : fixes bug declared here : https://forum.freecadweb.org/viewtopic.php?f=3&t=73321

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255">pipeline status</a> for feature branch [PR_7255](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255). Pipeline [600449030](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600449030) was triggered at [c694602](https://github.com/FreeCAD/FreeCAD/pull/7255/commits/c694602c7b06bd56a963d50ac0d531f556afebfd). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255">pipeline status</a> for feature branch [PR_7255](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255). Pipeline [600843223](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600843223) was triggered at [39f1638](https://github.com/FreeCAD/FreeCAD/pull/7255/commits/39f16387362c63f6185c92ae2565a1c4239e91e6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@donovaly It's done. May you give a test and feedback ?
Should we ask community its feedback too ?

* 1st commit is for Part primitives
* 2nd commit is for PartDesign primitives
* 3rd commit add a new function ensuring a fallback to internal precision+unit in case the user unit schema would zero a non-zero value
For example, if your unit preference is 'Imperial decimal', using a quantity of '1 mil' would be converted to '0.00 in', that gives an invalid object. In this case, the new behavior falls back to '0.0254 mm' to ensure a valid solid is created. Notice that for values correctly handles by user unit schema, it still rounds to user selected precision. Eg. '0.12345 in' will be converted to '0.12 in' if you're using a precision of 2 decimals.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255">pipeline status</a> for feature branch [PR_7255](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255). Pipeline [600861629](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600861629) was triggered at [83ad24d](https://github.com/FreeCAD/FreeCAD/pull/7255/commits/83ad24dde28d75df6a96c18b0a8f6ffadfc29f06). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Looks good and reasonable. I would like if @wwmayer could have a quick look, that we don't miss anything.

Concerning asking the community, i think the best in this case it to merge then much more people will test it using the weekly builds and we have plenty of time that people can test it properly.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255">pipeline status</a> for feature branch [PR_7255](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255). Pipeline [691422627](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/691422627) was triggered at [4aeaacd](https://github.com/FreeCAD/FreeCAD/pull/7255/commits/4aeaacdfa697cde19f2b9624df804743dc9ea8eb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@FreeCAD/maintainers please tell me when one is thinking about merging this. I will rebase and fix conflicts then.

**Comment by donovaly** [comment]
Looks good. As stable maintainer, I would like to backport the fix for FC 0.20.3. Is it therefore possible to plit the PR in two PRs, one that fixes the bug at least and the second one that introduces the new `getSafeUserUnit` method? Or do you think the `getSafeUserUnit` is also safe to be backported? (Files created with 0.20.3 can be handled by 0.20.2 without problems)
I am aware that because of the bug, fractional numbers will be rounded in FC 0.20.2.

**Comment by 0penBrain** [comment]
> Or do you think the `getSafeUserUnit` is also safe to be backported? (Files created with 0.20.3 can be handled by 0.20.2 without problems)

This shouldn't be a problem to be backported too.
Anyway as backporting is done with cherry-picking commits (AFAIK), as long as it is a different commit, you can choose to backport it or not. ;)

**Comment by donovaly** [comment]
> > Or do you think the `getSafeUserUnit` is also safe to be backported? (Files created with 0.20.3 can be handled by 0.20.2 without problems)
> 
> This shouldn't be a problem to be backported too. Anyway as backporting is done with cherry-picking commits (AFAIK), as long as it is a different commit, you can choose to backport it or not. ;)

I hope so despite I sometimes got difficulties. I therefore had in mind you merge the first 2 commits as separate PR and the third one as separate too.

So please merge it (there is a merge conflict by the way) and then I will try the backport and report in case I have issues.

**Comment by 0penBrain** [comment]
> So please merge it (there is a merge conflict by the way) and then I will try the backport and report in case I have issues.

@donovaly Hmmm. There an issue here. :) Actually the merge conflict is massive. Commit 589bcd16 destroyed the whole file "DlgPrimitives.cpp". I had to reapply all changes manually.
I'm now ready to push the update to the PR, but the problem is once I'll do that, you hardly can backport the changes because that will be another massive conflict. Your chance is to cherry-pick as they are now: IIRC there is just one reasonable conflict to be solved.
Waiting your decision before pushing the update to the PR.

**Comment by donovaly** [comment]
> I'm now ready to push the update to the PR, but the problem is once I'll do that, you hardly can backport the changes because that will be another massive conflict. Your chance is to cherry-pick as they are now: IIRC there is just one reasonable conflict to be solved. Waiting your decision before pushing the update to the PR.

I did now backport the complete 589bcd16 commit since it has no user-visible changes not does it add new features (When I did not make a mistake.)
This works on my PC but I will wait for the CIs.
When they run fine, I should be able to backport your PR. In every case, please continue your work.

**Comment by donovaly** [comment]
> but I will wait for the CIs. 

they succeeded.

**Comment by 0penBrain** [comment]
> When they run fine, I should be able to backport your PR. In every case, please continue your work.

Here it is. :)

**Comment by donovaly** [comment]
Looks good to me. 
@wwmayer do you might have a final look?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255">pipeline status</a> for feature branch [PR_7255](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255). Pipeline [761010429](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761010429) was triggered at [838be8d](https://github.com/FreeCAD/FreeCAD/pull/7255/commits/838be8d856f7d71b6d494f0355e45ddbe62e2ac9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@wwmayer do you want to have a look or may I merge ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255">pipeline status</a> for feature branch [PR_7255](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7255). Pipeline [786858999](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/786858999) was triggered at [831f385](https://github.com/FreeCAD/FreeCAD/pull/7255/commits/831f385b97680acd6abf3d5fd4738dbc27821eee). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks, I backported this now.

However this breaks the part WB:
- new file
- insert Part cylinder
- in the primitives dialog set do nothing, just press OK

result:
```
02:15:18  <class 'SyntaxError'>: ("(unicode error) 'utf-8' codec can't decode byte 0xb0 in position 7: invalid start byte", ('<string>', 3, 43, None))
02:15:18  Unhandled Base::Exception caught in GUIApplication::notify.
The error message is: ("(unicode error) 'utf-8' codec can't decode byte 0xb0 in position 7: invalid start byte", ('<string>', 3, 43, None))
```

**Comment by donovaly** [comment]
The problem is the degree signs in the strings.

**Comment by donovaly** [comment]
> The problem is the degree signs in the strings.

I applied this as hotfix: #8616 also to the 0-20 branch

**Pull request merged**
