### PR TITLE
Add SVG workbench icons

### PR DESCRIPTION
**Pull request by triplus**

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Hmm I don't like much having a double system, with some icons using the Qt Resource, and others being copied to the install dir... It is a bit messy. Have you checked if it is not possible to place the new icons inside the Qt Resource files and use them from there (with ":/icons/SomeIcon.svg") instead?

**Comment by triplus** [comment]
Icons from all workbenches should be available as internal/external resource:

http://forum.freecadweb.org/viewtopic.php?f=17&t=14426&p=115732#p115732

**Comment by triplus** [comment]
Hi.

If you copy/paste this into python console does it change anything?

```
from PySide import QtGui
from PySide import QtCore

mw = FreeCADGui.getMainWindow()

for i in mw.findChildren(QtGui.QComboBox):
    i.setIconSize(QtCore.QSize(16, 16))
```

**Comment by bblacey** [comment]
Worked like a champ!  Results in the screenshots below.

screen shot 2016-02-29 at 10 15 20 am

screen shot 2016-02-29 at 10 15 29 am

**Comment by triplus** [comment]
OK i created new pull request that should hopefully resolve the issue:

https://github.com/FreeCAD/FreeCAD/pull/107

**Pull request merged**
