### PR TITLE
BIM: update Glue icon

### PR DESCRIPTION
**Pull request by marcuspollio**
As noted in #13895
Now uses a yellow "glue bottle" and two blue parts to indicate it's gluing/fusing them.

BIM-Glue

### CODE REVIEW

**Comment by Roy-043** [comment]
The design does not work well at 16px.

BIM_Glue-at-16px

**Comment by marcuspollio** [comment]
Hi @Roy-043 thank you for having a look.
Indeed, it was not great =D
Now it should be a bit better :

Glue

**Comment by yorikvanhavre** [comment]
Just a small thing, that operation removes the original shapes, it's not parametric, that's why I did a red icon at first. Should that be something we take in to consideration?

**Comment by marcuspollio** [comment]
Hi @yorikvanhavre 
IMHO, it's a bit unfortunate that red is used for so many different purposes (undoing an operation, subtraction, closing a hole, cutting, highlighting a special feature, not to mention other WBs with constraints).
It's really up to you, I have no firm position on the matter. Your choice =D

Glue

**Comment by yorikvanhavre** [comment]
I have no strong idea either :sweat_smile: Any opinion there, @FreeCAD/design-working-group ?

**Comment by MisterMakerNL** [comment]
You add "glue" so I'd make the glue yellow. 
Maybe only the drop of the complete bottle and keep the drop white.

**Comment by maxwxyz** [comment]
white bottle is a good idea!

**Comment by MisterMakerNL** [comment]
> white bottle is a good idea!

Nonono :P , this causes contrast issues with light themes!

**Comment by yorikvanhavre** [comment]
I'd go with 1 or 3

**Comment by MisterMakerNL** [comment]
3 looks the best in my opinion.

**Comment by maxwxyz** [comment]
3

**Comment by kadet1090** [comment]
3

**Comment by marcuspollio** [comment]
Thank you all for the feedback.
I've updated the first post.

Can you please merge  --squash as keeping previous commits is useless for this PR. Thanks =D

**Pull request merged**
