### PR TITLE
TD: Section from Multi and PDN compat.

### PR DESCRIPTION
**Pull request by WandererFan**
Some updates for TechDraw. Please merge.

Thanks,
wf

- Fix XXX is still touched after recompute in DPG
- Allow Views of App::Parts
- Change links to Global scope
- add missing logic for "true" dimensions
- change isDeleting to isUnsetting
  - DocumentObject::isDeleting was changed to isRemoving.
    This commit just prevents future confusion.
- Allow Section based on ViewMulti

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by WandererFan** [comment]
Is there a problem with this PR? (other than being out of date now)

**Comment by yorikvanhavre** [comment]
Sorry, just lack of time these days... It's merged now

**Comment by WandererFan** [comment]
No worries.  Just checking I didn't mess up.

**Comment by wwmayer** [comment]
But there is actually one issue left: backward compatibility
The link properties that have changed their types to ***Global won't be read in when loading an old project file. There are three options:
1. If it's not important nothing needs to be done
2. Revert the changes to replace the link class and use the setScope method in the constructor of the feature class setting it to "Global" (recommended alternative)
3. Overwrite the method handleChangedPropertyType

**Comment by WandererFan** [comment]
Yes that's right. [https://www.forum.freecadweb.org/viewtopic.php?f=35&t=24722](url)
The links are all inside TD which didn't exist before 0.17,  so I decided not to do anything for backwards compatibility.

**Pull request closed without merging**
