### PR TITLE
Use xrange instead of range when exporting to collada.

### PR DESCRIPTION
**Pull request by jterrace**
This avoids creating a giant temporary list for large meshes.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by looooo** [comment]
as far as I know xrange is not available in python3.

**Comment by jterrace** [comment]
I see xrange being used in a bunch of other places though. Is this repo python3 compatible?

**Comment by ianrrees** [comment]
range() in Python3 is like xrange() in Python2.

@looooo - that approach is a bit sneaky, as there are legitimate reasons to use both range and xrange in Python 2.  Though, all the situations I can think of offhand will throw errors, so maybe this won't make bugs that are hard to find?

As for this change, I think a better approach is to not index in to the structure at all, which is probably faster than xrange and is inherently Python 2 and 3 compatible - something like this (untested):

```
i=0
for f in m.Topology[1]:
    findex.extend([f[0], i, f[1], i, f[2], i])
    i += 1
```

**Comment by jterrace** [comment]
See some dicsussion here:
https://github.com/pycollada/pycollada/issues/64

I think you can probably do it without a loop at all. Is m.Topology[1] a numpy array?

**Comment by looooo** [comment]
> I see xrange being used in a bunch of other places though. Is this repo python3 compatible?

Not yet, but hopefully soon. New python code should definitely work with both (py2 and py3)

> @looooo - that approach is a bit sneaky, as there are legitimate reasons to use both range and xrange in Python 2. Though, all the situations I can think of offhand will throw errors, so maybe this won't make bugs that are hard to find?

I don't see a reason why we shouldn't define xrange to range in python3. It doesn't change anything in python3...
Ahh, now I see, my code example was wrong:
```python
import sys
if sys.version_info.major >= 3:
    xrange = range
```

**Comment by triplus** [comment]
I would do it like this:

```python
try:
    xrange
except NameError:
    range
```

**Comment by looooo** [comment]
I will try to have the suggestion from @ianrrees included in the next py3 pull-requests.

**Pull request merged**
