### PR TITLE
Mod: Call PyMem_Free() to free allocated buffer

### PR DESCRIPTION
**Pull request by marioalexis84**
In the Cloud module, due to the author's intention to always return `None`, the code is also restructured by adding `PyErr_Clear` to avoid throwing an exception if argument parsing fails. 

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5514">pipeline status</a> for feature branch [PR_5514](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5514). Pipeline [464826179](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464826179) was triggered at [34b53f4](https://github.com/FreeCAD/FreeCAD/pull/5514/commits/34b53f47fd4e478341d231013e0fbb1130af1423). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@vejmarie ping

**Comment by wwmayer** [comment]
> In the Cloud module, due to the author's intention to always return None, ...

I am not sure if this was really intended. I rather assume he didn't know how to do it right.

**Comment by vejmarie** [comment]
Yep, I agree, I didn't really know how to do it properly. Seems good to clean up that part of the code. By the way CADCloud is going to progress pretty soon

**Comment by marioalexis84** [comment]
Ok, code changed to raise an exception.

**Comment by wwmayer** [comment]
Be careful: here the PyCXX API is used and if parsing the argument list failed returning nullptr might be problematic. Older PyCXX implementations converted them to Py::None and thus the interpreter may complain about being an exception set but null is not returned.

So, the preferred way is to explicitly throw a Py::Exception() that will be handled by the calling function method_varargs_call_handler()

I will quickly fix the code...

**Comment by wwmayer** [comment]
Merged as: 30cb87a 7895af182 efe0a39d3

**Comment by marioalexis84** [comment]
> Be careful: here the PyCXX API is used

I overlooked that.

**Pull request closed without merging**
