### PR TITLE
Part: Cross-section, fix issue with using Links that have been scaled…

### PR DESCRIPTION
**Pull request by mwganson**
… and/or transformed

https://forum.freecadweb.org/viewtopic.php?f=3&t=67961

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6740">pipeline status</a> for feature branch [PR_6740](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6740). Pipeline [515515261](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/515515261) was triggered at [32fff59](https://github.com/FreeCAD/FreeCAD/pull/6740/commits/32fff59e4f11fc09e200124d514721a5c1290936). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@realthunder , could you please also review this PR? If OK, it can go in for FC 0.20

**Comment by realthunder** [comment]
It's good.

**Comment by mwganson** [comment]
> It's good.

Can you take a look at this thread?

https://forum.freecadweb.org/viewtopic.php?f=3&t=67960

What is the best way to get the subshape when the document object is app link sublink?

**Comment by realthunder** [comment]
You can use `Part::Feature::getTopoShape(obj, subname, /*needSubElement*/ true)` to obtain the sub shape from a sub link. It works on all types of objects, and can be used as a general replacement for `TopoShape::getSubShape()`. Note that the `GUIApplication::notify` error reported in the thread indicates a leaked exception that needs to be addressed, as `TopoShape::getSubShape()` may throw exception. There maybe other places in `Part` that calls this function without catching exception or passing the `silent` option. `Part::Feature::getTopoShape()` does not throw exception, but return null shape if failed.

**Pull request merged**
