### PR TITLE
Core: Move LCS migration warning to Std_Open command

### PR DESCRIPTION
**Pull request by wwmayer**
https://github.com/FreeCAD/FreeCAD/pull/18332/files#r1885663470

### CODE REVIEW

**Comment by maxwxyz** [comment]
@PaddleStroke FYI

**Comment by PaddleStroke** [comment]
Nice.
Small question : If you double click on a file which launches FreeCAD, the command is used to open the file? ie will the warning show ?

**Comment by wwmayer** [comment]
No, it won't because internally it doesn't call the open command to load the file.

On the other hand showing the dialog in a lower-level function (like Application::open) will cause problems when running a Python script using FreeCADGui.openFile() because it may block the application.

It's possible to make all this working as expected but that should be addressed in a separate PR, then.

**Comment by PaddleStroke** [comment]
Alternatively we could perhaps drop the showing of a QMessageBox and only show a Console().Warning() ?

**Comment by wwmayer** [comment]
Yes, that's an option.

**Comment by chennes** [comment]
We've merged this one so we get working CI again.

**Pull request merged**
