### PR TITLE
Added python virtual environment initialization, if present.

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [n/a] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Do you mind explaining a bit what it's supposed to do? Also, the R in front of the strings makes to fail with gcc.

**Comment by ezzieyguywuf** [comment]
Per the [python virtualenv documentation](https://virtualenv.pypa.io/en/latest/userguide/#using-virtualenv-without-bin-python), this is how one must honor a users existing virtual environment when using an embedded python interpreter.

The "R" is a [c++11 string literal](https://en.cppreference.com/w/cpp/language/string_literal). I think I have be missing a delimeter before/after the opening/closing parentheses. I will look into this.

**Comment by wwmayer** [comment]
https://stackoverflow.com/questions/49416631/escape-r-in-a-raw-string-in-c

**Comment by wwmayer** [comment]
Fixed & merged.

**Comment by looooo** [comment]
@ezzieyguywuf Does this make much sense? For conda freecad is part of the virtual env and therefore no activation is necessary. 

I guess also for virtual-env it's necessary to have matching python version. So a virtual env will only work if no conflicting dependencies are used for freecad and the virtual env.

**Comment by ezzieyguywuf** [comment]
@looooo This should work in conda the same way it works outside of conda (I use virtualenvwrapper but the concept is the same).

It is easy to test: in conda, install a python package in the same env as freecad - maybe numpy or pandas. 

Now, when you run freecad, you should be able to access this module from the freecad interpreter. This was not previously the case. 

I see what you are saying regarding python versions: if freecad is compiled with python 2.7 and finds itself in a python 3 virtual environment.... what happens? I don't know - however, as my patch relies entirely on the virtualenv framework (using activate_this.py) I would expect it to fail gracefully. In other words, I would expect that the expected modules would simply be unavailable in the freecad interpreter.

**Comment by looooo** [comment]
< It is easy to test: in conda, install a python package in the same env as freecad - maybe numpy or pandas.

Yes, I see this is interesting if FreeCAD is used as a bundle.

> Now, when you run freecad, you should be able to access this module from the freecad interpreter. This was not previously the case.

This is only true for bundles, but I am talking about freecad installed via conda. Actually I tested a recent build and there are no conflicts if freecad is started in a conda-env.

> I would expect it to fail gracefully. In other words, I would expect that the expected modules would simply be unavailable in the freecad interpreter.

More likely this will lead to crashes when an incompatible library is imported. In the activation only some environment variables are modified and paths from virtual-env are prepended. We also ship some python libraries with freecad to enable binary-compatibility with freecad. Therefor it's possible some libraries are hidden by virtual-env which can lead to additional problems. But anyway if used by python-developers this is a nice addition. We will see how good it works...

**Pull request closed without merging**
