### PR TITLE
Fix and add menu accelerators

### PR DESCRIPTION
**Pull request by snow-faerie**
I use menu accelerators fairly often, so I find it very frustrating when they are missing, or worse, they don't work due to the same letter being assigned to several commands.

I don't mind making a patch like this fixing lots of them, and more to come... but I worry about the impact of this on UI translations.

Do we have a way to update them so that translations don't break? Or should I just not touch the .cpp files at all and instead fix the accelerators in the English translation files, leaving the mistakes frozen forever in the C++ strings?

### CODE REVIEW

**Comment by chennes** [comment]
This is the correct way to address this problem: that said, you are right that it will break the translations, so we will wait until after we've branched for the next release to merge it.

**Comment by snow-faerie** [comment]
I made a little macro to help myself find conflicts, as they're all too easy to introduce.

https://gist.github.com/snow-faerie/c0819ba10e17d36b445d284c8cc5f5e4

It outputs things like this:
```
Menu issues
===========
/&File:
 * Ambiguous accelerator 'N': ['&New', 'Document i&nformation...']
 * Ambiguous accelerator 'O': ['&Open...', 'Cl&ose']
 * Ambiguous accelerator 'R': ['Open &Recent', '&Revert']
 * Ambiguous accelerator 'V': ['Sa&ve All', 'Print pre&view...']
/&File/Open &Recent:
 * No accelerator: '1 Drawer.FCStd'
/&Edit:
 * No accelerator: 'Duplicate selected object'
 * No accelerator: 'Box selection'
 * No accelerator: 'Box element selection'
 * No accelerator: 'Placement...'
 * No accelerator: 'Transform'
 * No accelerator: 'Alignment...'
 * No accelerator: 'Properties'
 * No accelerator: 'Edit mode'
 * Ambiguous accelerator 'R': ['&Redo', '&Refresh']
```

**Comment by snow-faerie** [comment]
Finished with the File and Help menus, with the help of the macro I posted earlier.

**Comment by snow-faerie** [comment]
Finished the **Edit** menu. Added support for accelerator letters in the Recent File and Recent Macro menus, so if the user sets them to have a large number of items, they will still get accelerators until item number 36 inclusive.

Screenshot of a Recent files menu with 20 items

**Comment by luzpaz** [comment]
> I made a little macro to help myself find conflicts, as they're all too easy to introduce.  

This would be a great macro for the UI/UX team (CC @obelisk79)

**Comment by obelisk79** [comment]
Thanks for the tag.

**Comment by snow-faerie** [comment]
Added accelerators for the items in the view menu... that one was a very long one with not enough letters for everything, so I had to prioritize some over other.

The submenus for *Workbenches* doesn't have accelerators. I'd like it to, but it requires a bit too many changes for this patch. *Toolbars* and *Panels* may be similarly tricky, but I haven't checked them yet.

At one point FreeCAD crashed. You know what that means: I added a missing accelerator to the *Document recovery* dialog.

**Comment by snow-faerie** [comment]
Finished with accelerators for the general menus (those that are present regardless of workbench).

From here on, fixes for specific workbenches can have their own commits, so they can be a bit more self-contained.

**Comment by maxwxyz** [comment]
@snow-faerie could you please resolve the conflicts? TIA

**Comment by maxwxyz** [comment]
Looked at this at the merge meeting but it still has conflicts. Could you please resolve them?

**Comment by maxwxyz** [comment]
@snow-faerie CI builds for Ubunto and Windows seem to fail, could you please take a look at them?

**Comment by maxwxyz** [comment]
@snow-faerie ping

**Pull request merged**
