### PR TITLE
[Fem] rigid body constraints

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Current status: https://forum.freecadweb.org/viewtopic.php?f=18&t=60892&start=20#p638085.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [686439684](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686439684) was triggered at [9a05b2d](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/9a05b2d8051c0ab4abd380ae36b9b4df55e9389d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [686473835](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686473835) was triggered at [4f3551a](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/4f3551a00a0ccb585c258b7a39117926c93cdb68). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
you will need more than one change in the unit test file ... see https://github.com/FreeCAD/FreeCAD/commit/27f50ad13188faff#diff-8a32794d9e360477423fcc21102d6ee3a5188f726a4d96ad8d651a45db118e4d

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [686500665](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686500665) was triggered at [662c249](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/662c2496241ac4897ffed627fcc002d8ecaf1ecb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [686510492](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686510492) was triggered at [869c523](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/869c52390b4ff4d36bee87d309470c4e1d7732ff). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [686538031](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686538031) was triggered at [13b3404](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/13b3404ce4b00d6d5fc18d79753c38b6ec573396). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
It isn't necessary to add [DO NOT MERGE] to title of a PR if it is a 'Draft' PR

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [699141957](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/699141957) was triggered at [126ed8f](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/126ed8f8f9e96c5f3c5fa677ede311af460902f6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [715093272](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/715093272) was triggered at [ead30c1](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/ead30c1446295608f9542bb15f10d58795ceb9a8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [761010430](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761010430) was triggered at [7804596](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/78045961279422646bc0e3ed0419c93e1318b977). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
What's left to do here ?

**Comment by AjinkyaDahale** [comment]
> What's left to do here ?

Been a while so I don't recall exactly, but some issues from the forum post I linked in OP still remain.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [818329894](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818329894) was triggered at [7804596](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/78045961279422646bc0e3ed0419c93e1318b977). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by AjinkyaDahale** [comment]
What triggered a rebuild?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716">pipeline status</a> for feature branch [PR_7716](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7716). Pipeline [818716896](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818716896) was triggered at [2f43ce5](https://github.com/FreeCAD/FreeCAD/pull/7716/commits/2f43ce5db375bf7cb4e5f547f0a5575f43231bf5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by FEA-eng** [comment]
@AjinkyaDahale Can you still go back to this ? I've finally managed to build FreeCAD from the source code (on a virtual Ubuntu machine) so I could test this.

**Comment by AjinkyaDahale** [comment]
@FEA-eng I can rebase this if you can't build as is. But if I recall correctly there were some things where I needed Bernd or someone else's expertise on how to add the "reference" node at the stage in FreeCAD where the rigid body lines are added.

**Comment by FEA-eng** [comment]
> @FEA-eng I can rebase this if you can't build as is. But if I recall correctly there were some things where I needed Bernd or someone else's expertise on how to add the "reference" node at the stage in FreeCAD where the rigid body lines are added.

I built it from your branch (in FreeCAD 0.21) so I can test this and I already have some feedback. But unfortunately, Bernd is still unavailable and currently, we don't have anyone else familiar with the FEM source code on board. There's even an issue for this: #10705

**Comment by AjinkyaDahale** [comment]
@FEA-eng let's start with the feedback.

**Comment by AjinkyaDahale** [comment]
> Sure. Here's what I've noticed (some points will be obvious to you but I prefer to write it all down for reference):

@FEA-eng sorry for the delay in response. I'm afraid I'm rarely working on FEM so this could take a whole lot longer. As you might see from my responses, I am the one with the limited knowledge right now.

>     * *CLOAD is added right below the rigid body definition, not within the analysis step (that's the biggest issue at the moment since the analysis doesn't run with it)

OK I need to understand this better before I can change anything. Right now I'm adding things in the order they are presently added, but this particular tool needs to add things in a very distributed manner. This was incidentally the reason I ended up tabling the entire tool for this long.

>     * when a moment is defined, REF NODE is not added and vice versa

Could you elaborate?

>     * REF and ROT NODE have negative numbers

That is intentional for now. It is intended that the user (or rather tester) create the ref and rot nodes. With a negative number, this is enforced so that ccx complains heavily before this goes forward.

>     * REF and ROT NODE are not defined using *NODE so their coordinates are irrelevant

I'm not certain of support for adding nodes after meshing. If we can add a node in the INP _while_ adding rigid bodies this may be easier.

As far as I recall, they need a dummy value still. Or maybe I'm wrong thoroughly.

>     * load (should be named "force") on ref node has mN unit

Force because it is a point force?

>     * boundary conditions can't be applied (only loads are supported)

OK that's a TODO then.

>     * it can be applied only to faces

I'm not sure of the interface to add to solids, especially when there is limited geometry support for non-manifold objects.

>     * there's no icon

Of course, this can't be merged without the icon. But this is better handled by a better artist :-D

**Comment by FEA-eng** [comment]
> @FEA-eng sorry for the delay in response.

No problem, I'm glad you're still interested in this topic.

> OK I need to understand this better before I can change anything. Right now I'm adding things in the order they are presently added, but this particular tool needs to add things in a very distributed manner. This was incidentally the reason I ended up tabling the entire tool for this long.

Loads (like *CLOAD) must always be added under:

```
*STEP
*STATIC (or other type of step)
```

Boundary conditions are different. Those that only fix degrees of freedom can be added before *STEP but those that impose values to degrees of freedom (zero or non-zero) must be added below *STEP.

> Could you elaborate?

CalculiX documentation allows for some flexibility when it comes to REF NODE and ROT NODE but I think that a good implementation should always include both of them with some node numbers and coordinates (more below).

> That is intentional for now. It is intended that the user (or rather tester) create the ref and rot nodes. With a negative number, this is enforced so that ccx complains heavily before this goes forward.

I think that they should always have positive numbers and just be created at (0,0,0) if a user doesn't change the coordinates. When it comes to the node numbers, I suggest setting it to last node number in the model plus 1 for REF NODE and last node number plus 2 for ROT NODE. Or using very large numbers, as explained below.

> I'm not certain of support for adding nodes after meshing. If we can add a node in the INP _while_ adding rigid bodies this may be easier.

Those would be additional nodes added after the ones belonging to the mesh, I think that this is needed. I'll sum it all up below.

> Force because it is a point force?

Because it's load in Newtons and a point force, yes. So there should be force [N] and moment [Nmm].

> I'm not sure of the interface to add to solids, especially when there is limited geometry support for non-manifold objects.

It can be based on the existing interface used to add solids to material definitions, for instance. It's already available in GUI. But support for solids is less important since rigid body constraint is mostly needed to apply loads to faces (and sometimes edges/vertices).

> Of course, this can't be merged without the icon. But this is better handled by a better artist :-D

I'll try to handle this or ask someone for help.

**SUMMARY:**

In my opinion, it should be implemented this way (it's also how it works in other CalculiX preprocessors):
- by default, when rigid body constraint is used, this keyword is added to the input file:

`*RIGID BODY, NSET=..., REF NODE=X, ROT NODE=Y`

where X=N+1 and Y=N+2 (N is the total number of nodes in the mesh). It could be also preset to very large values (such that there are never so many nodes in the model) to avoid counting nodes. Maybe that's a better idea.

Then this is also added by default under the existing *NODE keyword:

```
*NODE
...
** mesh node definitions
...
X, 0.0, 0.0, 0.0
Y, 0.0, 0.0, 0.0
```

It can be also added under a separate *NODE keyword, no problem.

- if the user changes the coordinates of the REF NODE (ROT NODE inherits them), they are changed in the input file from the default (0,0,0)

- now either *CLOAD is added below the step definition:

force:
```
*CLOAD
X, DOF, value
```

moment:
```
*CLOAD
Y, DOF, value
```

where X and Y are still REF and ROT NODE numbers, respectively and DOF ranges from 1 to 3.

or *BOUNDARY is added there:

prescribed displacement:

```
*BOUNDARY
X, first DOF, last DOF, value
...
```

prescribed rotation:

```
*BOUNDARY
Y, first DOF, last DOF, value
...
```

The rest is the same as for loads. Of course, there can be multiple data lines for different DOFs each time. For instance:

```
*CLOAD
X, 1, 12
X, 2, 15
Y, 1, 20
```

```
*BOUNDARY
X, 1, 1, 0
X, 2, 2, 0
X, 3, 3, 0
Y, 1, 1, 0
Y, 2, 2, 0
Y, 3, 3, 0.15
```

Is it all clear ? Please let me know if you need additional explanations or some examples.

**Comment by FEA-eng** [comment]
I would propose an icon like this:

Rigid body icon 2

**Comment by FEA-eng** [comment]
@AjinkyaDahale Would you be able to find some time to go back to this before the next release? Good news is that I started working on the FEM workbench so now I know something about its code. I doubt I can finish this myself but hopefully I could at least help more than by just clarifying the CalculiX syntax aspects. For example, I am familiar with Python files responsible for writing different sections of the input file (this could matter e.g. to correct the location of the *CLOAD keyword). Maybe we could collaborate somehow if you have enough time. Unless you have to postpone it due to other obligations, then just let me know and I’ll probably leave this for now too.

**Comment by AjinkyaDahale** [comment]
@FEA-eng I do/will have some downtime this month for sure, in which I can at least share where I had been stuck. IIRC, it seemed there needed to be some deep changes in the structure of the writer, but I might be wrong.

**Comment by FEA-eng** [comment]
> @FEA-eng I do/will have some downtime this month for sure, in which I can at least share where I had been stuck. IIRC, it seemed there needed to be some deep changes in the structure of the writer, but I might be wrong.

Great. This is IMO the most missing FEM feature ATM. I have some ideas how to make this implementations easier so maybe we could finalize it together. You would have to update the branch and we would think how to collaborate. Maybe @marioalexis84 could provide some advice too.

**Comment by FEA-eng** [comment]
@AjinkyaDahale I fixed most issues (including the blocking one with *CLOAD in the wrong place). When you have some time, please let me know how I can share the updated files with you and where and when we can talk about what's left to do.

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale I fixed most issues (including the blocking one with *CLOAD in the wrong place). When you have some time, please let me know how I can share the updated files with you and where and when we can talk about what's left to do.

You can make a PR to this branch (https://github.com/AjinkyaDahale/FreeCAD/tree/fem-rigid-body-constraints), or just share your branch.

**Comment by FEA-eng** [comment]
> You can make a PR to this branch (https://github.com/AjinkyaDahale/FreeCAD/tree/fem-rigid-body-constraints).

Ok, I'll do it this way then. I just wonder if it's better if you update your branch (it's still 0.21, not 0.22) first or if we merge my changes and then update the branch.

**Comment by AjinkyaDahale** [comment]
> I just wonder if it's better if you update your branch (it's still 0.21, not 0.22) first or if we merge my changes and then update the branch.

Oops. I forgot that's needed too!

**Comment by FEA-eng** [comment]
> Oops. I forgot that's needed too!

Yeah, I made the changes in your 0.21 files. Perhaps it would be better to update the branch first but it's up to you. On the GitHub website (I don't use git locally), it should be just a matter of clicking the _Update branch_ button. Hopefully, it works smoothly.

**Comment by AjinkyaDahale** [comment]
> On the GitHub website (I don't use git locally), it should be just a matter of clicking the _Update branch_ button. Hopefully, it works smoothly.

It's the conflicts that are best handled locally, which can get pretty bothersome. Fortunately, it wasn't the case this time.

**Comment by FEA-eng** [comment]
@AjinkyaDahale I sent a PR and listed all the changes in its description. I'll only repeat here what's still left to do:
- Force unit still has to be fixed because it's shown as mN but written to the input file as N without conversion
- Moment unit is displayed incorrectly as "eV" even though I've tried to define a new "Moment" unit in the Base and App folder files
- the current approach to REF and ROT NODE numbering makes it impossible to define multiple rigid body constraints - we could either increment the fixed numbers in such cases, let the user specify them or vary them depending on the number of mesh nodes
- support for boundary conditions (*BOUNDARY) still needs to be added in a similar way as for loads (*CLOAD) but with zero values only when specified by the user (it should be possible to leave the degrees of freedom unconstrained)
- support for solid (volume) object selection would be nice but it's not necessary for now

Of course, we can discuss this at any time. Please let me know if you have any questions.

**Comment by maxwxyz** [comment]
any news on this PR?

**Comment by FEA-eng** [comment]
> any news on this PR?

It's my priority and I'll try to have it ready for the upcoming release. I'm talking with a new potential contributor who may help me correct the remaining issues.

**Comment by maxwxyz** [comment]
can I test something or help otherwise to get this ready?

**Comment by FEA-eng** [comment]
> can I test something or help otherwise to get this ready?

Unfortunately, help is needed only from the coding side to resolve a few remaining issues. And someone should fork the Ajinkya’s branch (if possible), merge my PR to it and send a PR to master so that further changes can be easily applied anytime. Perhaps you could do that if you know how to do it easily on GitHub? Your availability here would help.

**Comment by AjinkyaDahale** [comment]
> And someone should fork the Ajinkya’s branch (if possible), merge my PR to it and send a PR to master so that further changes can be easily applied anytime.

If you have a PR on this branch don't you already have such a branch?

As such sorry for not being available for these changes, and at this point I won't make any further promises.

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale Thanks for the reply and no problem. To be honest, I’m not very familiar with GitHub and I don’t use git locally (I just do everything on the website).

I would definitely suggest getting acquainted with this as far as possible. After all, this is one of the more "straightforward" parts of the whole work. You have already done the hard part of making the changes :)

> Can you merge my PR (link below) to your branch? This would make the future works easier.

This I think I can do. It will still need rebase and conflict resolution, but from what I recall that didn't take too long.

**Comment by marioalexis84** [comment]
@AjinkyaDahale I will rebase your branch, so together with @FEA-eng we can finalize your proposal.

**Comment by AjinkyaDahale** [comment]
@marioalexis84 you got me wrong: we need to rebase @FEA-eng's branch from https://github.com/AjinkyaDahale/FreeCAD/pull/5.

**Comment by marioalexis84** [comment]
Thanks for the clarification.

**Comment by FEA-eng** [comment]
> @AjinkyaDahale I will rebase your branch, so together with @FEA-eng we can finalize your proposal.

I’m really glad that you want to help with this. What’s left to do is pretty much only fixing the units, adding proper numbering for REF and ROT nodes and supporting boundary conditions in the same way as loads (but with an option to leave the degrees of freedom free like in the displacement constraint). Please let me know if you want to discuss this, I can definitely help with the CalculiX syntax side, explain how it should work and what the code currently does.

**Comment by marioalexis84** [comment]
> Please let me know if you want to discuss this

Of course.

I have already rebased your branch on my local machine.

To add to your comments, a few things I noticed in the current code:
* Properties such as Force, torque and position of the reference node should be moved to vector properties.
* Just set the reference and rotational nodes to maximum node id +1  and maximum node id + 2, respectively.
* Property `DefineRefNode` could be replaced by an enumeration property with values `Reference`, `Rotational`, and `Both` (or something similar).
* An asterisk is missing in the writer for the `NODE` keyword.
* Support for solids.
* According to some tests I did, in the rotational node, for the `BOUNDARY` keyword, we need to pass the rotation as the tangent of the angle and not the angle itself. The displacement constraint writes the rotations in degrees, so there is an bug there.
* `Fem::ConstraintRigidBody` and its view provider must adapt to the code merged with #13274.
* Squash several current commits.

**Comment by FEA-eng** [comment]
> Just set the reference and rotational nodes to maximum node id +1  and maximum node id + 2, respectively.

Yes, that's the best approach but I didn't know how to do that so I used 2 fixed large numbers (of course, this way it wouldn't be possible to have multiple rigid body constraints so it was just temporary).

> Property DefineRefNode could be replaced by an enumeration property with values Reference, Rotational, and Both (or something similar).

Ok, but it would be just internal, right? Because the user shouldn't define those points separately. He should only enter the REF NODE coordinates and then the ROT NODE with the same coordinates should be defined internally.

> An asterisk is missing in the writer for the NODE keyword.

Right, I haven't noticed that. Surprisingly, the solver didn't complain about the syntax issue.

> Support for solids.

Great, I skipped that too but it's also an important feature.

> According to some tests I did, in the rotational node, for the BOUNDARY keyword, we need to pass the rotation as the tangent of the angle and not the angle itself. The displacement constraint writes the rotations in degrees, so there is an bug there.

Strange. CalculiX uses some workarounds to handle rotational DOFs with rigid body constraints - moment loads and rotational boundary conditions have to be applied to the ROT NODE and use 1, 2 and 3 DOFs for X, Y and Z rotation respectively. I haven't noticed anything unusual regarding the unit though - it always seemed to work well with angles in radians. But maybe there's some misunderstanding or a bug in a specific CalculiX version here. Can you share the files used for those tests?

**Comment by marioalexis84** [comment]
I have repeated my tests. Indeed, the angles are in radians. What led me to wrongly conclude that the tangent of the angles should be used is the result obtained if the `STEP` card lacks the `NLGEOM` parameter which, as seen in the image, it does not correspond to a rigid body.
Therefore, we also need to add the nonlinear parameter to the `STEP` card.

The image shows a result with and without the `NLGEOM` parameter.
Boundary conditions:
   90 degree rotation along the Y axis.
  Reference node at origin with null displacement.

with `NLGEOM` parameter:
with_NLGEOM

Without `NLGEOM` parameter:
without_NLGEOM

**Comment by FEA-eng** [comment]
@marioalexis84 NLGEOM should be used for large displacements and rotations but it’s not necessary for the small ones. Most cases when rigid body constraint is used (like torque application) don’t require NLGEOM. I would definitely not force it and leave it as the user’s responsibility. Especially since NLGEOM often causes convergence issues, particularly with 1D and 2D elements (e.g. NLGEOM + shells + rigid body pretty much guarantees non-convergence: https://calculix.discourse.group/t/rigid-body-constraint-convergance-problems/369/25).

**Comment by marioalexis84** [comment]
Thanks for the information. Ok, for small angles we are on the safe side.
Should be good add this to the docs once the rigid body constraint is added.

**Comment by FEA-eng** [comment]
Basically, the observed effect doesn’t occur only when using rigid body constraints. Enforcing large rotations in other ways should cause it too as the stiffness matrix is not updated during multiple increments and the results are just estimated linearly. This is also what causes the spurious swelling of models subjected to large torsion.

**Comment by AjinkyaDahale** [comment]
> I have already rebased your branch on my local machine.

@marioalexis84 you might want to create a fresh PR after this to avoid having to ask me to rebase or such. I'd still be happy to help out with tech issues if needed.

**Comment by marioalexis84** [comment]
Yes @AjinkyaDahale, I will create a new pull request.

**Comment by maxwxyz** [comment]
@AjinkyaDahale can this PR be closed then?

**Comment by FEA-eng** [comment]
> @AjinkyaDahale can this PR be closed then?

I guess (and mine in his branch) but maybe let's wait for the new PR to merge just in case?

**Comment by maxwxyz** [comment]
@AjinkyaDahale @marioalexis84 I guess a closed PR could be reopened again if needed

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale can this PR be closed then?

Yes. Replaced with #13900. If necessary this branch will stay anyway.

**Pull request closed without merging**
