### PR TITLE
FIXES: minor bug in custom spacing of rebar object

### PR DESCRIPTION
**Pull request by amrit3701**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Github says this PR cannot be merged @amrit3701 I think one of the commits in this branch has already been merged, no?

**Comment by amrit3701** [comment]
@yorikvanhavre Yes, one commit from amrit/FreeCAD has already been merged. Can you tell me a reason that why this PR conflict with FreeCAD master?

**Comment by yorikvanhavre** [comment]
this PR should contain only commit d68b54d I think...

**Comment by yorikvanhavre** [comment]
closed as asked by @amrit3701

**Pull request closed without merging**
