### PR TITLE
[0.20] History storage framework  and options for select methods in TopoShapePy

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [X] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

Some testing required. Works well enough for my test cases, but they are fairly naive. 

Supported methods (all booleans, `extrude`, `mirror`, `makeFillet2`, `makeChamfer2`) now come with an optional `withHistory` parameter that can be set to `True` if you want to store history. The development of the sub-shapes from the sub-shapes of the base(s) can be studied by using `shapeName.History.modified`, `shapeName.History.generated`, `shapeName.History.isDeleted`.

### CODE REVIEW

**Comment by ezzieyguywuf** [comment]
I believe there is a typo on [Line 72 in TopoHistory.cpp](https://github.com/AjinkyaDahale/FreeCAD/blob/tnaming-pr/src/Mod/Part/App/TopoHistory.cpp#L72). Notice that this line refers to the `shapeMaker->Generated` method rather than the `shapeMaker->Modified` method as expected

**Comment by AjinkyaDahale** [comment]
You're right! wonder how that mistake got there, since I'm sure I had tested it.

**Comment by DeepSOIC** [comment]
ezziey's thread, relevant to this PR. Just for record.
https://forum.freecadweb.org/viewtopic.php?p=183060&sid=25ffc700d68c60bf02d213366a9811a5#p183060

**Comment by luzpaz** [comment]
How is this GSOC project doing so far? Haven't seen any dialogue discussing integration.

**Comment by PrzemoF** [comment]
Should we keep it here? It's 3 years old and even if the original idea worked it definitely needs rework. I suggest to add a tag "rework needed" and close.

**Comment by luzpaz** [comment]
Sort of relevant. We could start [labeling](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/managing-labels) PRs

**Comment by DeepSOIC** [comment]
I'm pretty sure it should be closed. Ajinkya is unlikely to return, and i'm not planning to advance it either. And we have a proven-to-work realthunder's implementation.

**Comment by AjinkyaDahale** [comment]
Unfortunately, DeepSOIC is kinda correct. I did intend to get back to this but things got far too busy. I will have some time now, but I might not be able to be directly involved because reasons.

**Comment by AjinkyaDahale** [comment]
I think this can be closed since it's long been replaced by @realthunder's work.

**Pull request closed without merging**
