### PR TITLE
Mesh: Allow to measure distances with a mesh

### PR DESCRIPTION
**Pull request by wwmayer**
Replacement for the removed old distance tool

### CODE REVIEW

**Comment by chennes** [comment]
Can you explain how it's supposed to work? I thought I'd be able to just click on two points of a mesh with the measure tool active, but that doesn't seem to do anything.

**Comment by wwmayer** [comment]
The TaskMeasure dialog only checks if for a given geometry type a callback function is registered without ever calling it:
https://github.com/FreeCAD/FreeCAD/blob/f28394a376c285725abdacee3d72bd57a8b196aa/src/Gui/TaskMeasure.cpp#L161

Then further down in TaskMeasure::update() it checks the current selection and if the current measurement mode can be performed.

> I thought I'd be able to just click on two points of a mesh with the measure tool active, but that doesn't seem to do anything.

That's not possible at the moment because of a limitation of the measurement mechanism. It relies on the general selection and if you click the same object/sub-element twice while the measurement dialog is open the object will be de-selected and thus the measurement will be aborted.

Currently, you can do a free distance measurement only between two objects or two sub-elements of one object.

This is already reported in https://github.com/FreeCAD/FreeCAD/issues/14845

**Comment by maxwxyz** [comment]
Does this solve 
- https://github.com/FreeCAD/FreeCAD/issues/13709

@hlorus FYI

**Comment by FEA-eng** [comment]
> Does this solve
> 
> * [Measurement: Support measuring / picking points of meshes #13709](https://github.com/FreeCAD/FreeCAD/issues/13709)

Sounds more like a fix for #14845. Am I right?

**Comment by maxwxyz** [comment]
Why is Mesh mentioned then?

**Comment by hlorus** [comment]
It just adds support for mesh geometry to the MeasureDistanceFree measure type. MeasureArea and MeasureCOM still won't be supported with meshes.

**Comment by chennes** [comment]
> Sounds more like a fix for #14845. Am I right?

No, as @wwmayer points out above, the reason my attempts to test it failed was because it specifically does *not* solve #14845, but the test I was doing would have required a solution to that bug in order to work. So, a different test (on my part) was needed.

**Review by hlorus — APPROVED** [review]

**Pull request merged**
