### PR TITLE
Draft: Improve makeWires in upgrade function

### PR DESCRIPTION
**Pull request by marioalexis84**
With these changes, a list of objects conformed by edges (without faces) will be sorted and converted to wires.
Objects with dependencies will not be removed, only visibility will be changed to false.
For a eclectic example, see https://forum.freecadweb.org/viewtopic.php?f=8&t=52583

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
The Travis build fails:
```
======================================================================
ERROR: test_upgrade (drafttests.test_modification.DraftModification)
Upgrade two Draft Lines into a closed Draft Wire.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Draft/drafttests/test_modification.py", line 257, in test_upgrade
    s2 = obj2[0][0]
IndexError: list index out of range
```

**Comment by marioalexis84** [comment]
The error in Travis occurred because when Draft.upgrade uses draftify or uses closeWire on a Draft Wire, no element is returned,
so test_upgrade is modified use another workflow.

**Comment by marioalexis84** [comment]
ok, more errors in test_modification... I will correct them

**Comment by marioalexis84** [comment]
@yorikvanhavre now the test was passed correctly

**Comment by yorikvanhavre** [comment]
Thanks for the fix! Merging now

**Pull request merged**
