### PR TITLE
Fix can't pad a sketch on datum plane

### LINKED ISSUE #14390: Part Design: can't pad a sketch on datum plane "Pad: Null shape"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I use the latest weekly build (37543) and I can't extrude simple sketches if they are attached to datum planes. The padding fails with the error "Pad: Null shape"

If the same sketch is attached to the XY plane it works

image

Steps to reproduce:

* create new file
* create PD body
* create a Datum plane, attach it to XY, move it up by a few mm and rotate it a bit around the x axis
* create a new sketch on the datum plane and draw a circle
* pad the sketch

Here is a sample file from the screenshot:

[pad fail on datum plane.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/15499837/pad.fail.on.datum.plane.FCStd.zip)

Just try to pad the sketch and you'll see the error

### Full version info

```shell
OS: KDE neon 5.27 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37543 (Git) AppImage
Build type: Release
Branch: main
Hash: 3eb45b045cdda9d5bfe11baba2567a1df90f064c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * CurvedShapes 1.0.5
  * Defeaturing 1.2.2
  * QuickMeasure 2022.10.28
  * fasteners 0.5.14
  * Curves 0.6.24
  * MeshRemodel 1.9.22
  * Manipulator 1.5.7
  * kicadStepUpMod 11.1.0
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix #14390

### CODE REVIEW

**Comment by FlachyJoe** [comment]
@janjan @macdroid53 FYI

**Comment by wwmayer** [comment]
The PR should include a unit test.

**Comment by FlachyJoe** [comment]
@wwmayer done!

**Comment by macdroid53** [comment]
37669

Screenshot_20240610_130435

**Comment by FlachyJoe** [comment]
@macdroid53 If I'm not mistaken, the fix has been merged as #36701.

**Comment by macdroid53** [comment]
Yeah, after I hit send on that comment I realized I should have checked the merge. Sorry.

**Comment by maxwxyz** [comment]
It seems to be broken in the current weekly again: #16010

**Pull request merged**
