### PR TITLE
Part: Move Part_SectionCut command to Part menu item list

### PR DESCRIPTION
**Pull request by marioalexis84**
Since the command alters the document, `AlterDoc`is masked to 1.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6213">pipeline status</a> for feature branch [PR_6213](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6213). Pipeline [465494754](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/465494754) was triggered at [5cd76d8](https://github.com/FreeCAD/FreeCAD/pull/6213/commits/5cd76d8823e59d5d110f90a4aeac0c2f58457b57). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
I cannot compile right now but it seem that this PR is not doing the right thing:

The main idea of the section cut feature is that it is always in the View menu, no matter in what WB you are. This is because the main usage would be assemblies, and when assembling, you switch WBs all the time and of course when e.g. being in Assembly4, you must be able to start the section cut feature from the view menu, otherwise it won't work as it is designed.

Therefore please bring it back the View menu for all WBs,

**Comment by donovaly** [comment]
> The menu bar is recreated every time a workbench is activated, so a command added to the StdWorkbench menu bar (similar to Part_ColorPerFace, for example) will be lost with every workbench change.

Yes, and this must in this case NOT happen, otherwise the concept of the Section cut  will fail. It will only work in a useful way when you can start it from the View menu, no matter in what WB you are in.

> If the command needs to be accessed from workbenches other than Part, the easiest way is to add the command to these specific cases. For example, for Python-based workbenches: `import PartGui` --> add `"Part_SectionCut"` to workbench command list.

Since I am away and cannot do coding, could you please make such a PR that bring the Section cut feature back to all WBs? Thanks in advance.

**Comment by marioalexis84** [comment]
I understand the idea of making the command visible to other workbenches, but as I say in the other comment, other modules should import PartGui and add Part_SectionCut to their list of commands.

**Comment by wwmayer** [comment]
> but it seem that this PR is not doing the right thing:

It does the right thing but I already assumed you are not happy with the result. :)

> Therefore please bring it back the View menu for all WBs,

In order to do so it requires some little redesign of the core Workbench class. The way you did it was definitely wrong because it violated the design principle that the core system shouldn't know anything about implementation details of extension modules.

People who has set a start up workbench that doesn't automatically load PartGui always see an annoying error message that Part_SectionCut couldn't be found.

As a workaround for the time being you can add a "Global" toolbar and add there the command. This toolbar will be then visible for all workbenches.

**Comment by donovaly** [comment]
> As a workaround for the time being you can add a "Global" toolbar and add there the command. This toolbar will be then visible for all workbenches.

How is this done?
However, this is not what I want. I don't want to bother every user with an icon that he might not want to use ever. I want it therefore to have it in the View menu for all WBs.

**Comment by donovaly** [comment]
Until there is a way to bring it to the View menu for all WBs, I at least brought it back for PD and Part:
https://github.com/FreeCAD/FreeCAD/commit/68a5c7e438d

**Pull request merged**
