### PR TITLE
Part: start to expose ShapeFix framework to Python

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [525883960](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/525883960) was triggered at [26c160b](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/26c160b305185e2ffe830a92caa67bfdb4011872). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
If you like, this could go in for 0.20. It is in my opinion not a real new feature, just makes existing features accessible. It adds new strings to be translated but since the release is delayed by 2 weeks, I think this Is no problem. @yorikvanhavre , do you agree?

**Comment by donovaly** [comment]
> So, because of its limited functionality it's better to wait for v0.21.

OK.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [528892475](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/528892475) was triggered at [420c5e1](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/420c5e10dea29ce872a409c59ff5136a4b2e787c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531013847](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531013847) was triggered at [b82e397](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/b82e3972b8a22b5adeb27556e923cf77f5065c14). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531105719](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531105719) was triggered at [6c3fe5a](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/6c3fe5a5f5adeb19375ea9ae4536c530d5e19db6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531150023](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531150023) was triggered at [f135c22](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/f135c2253175b2fd1e5161facbd668489fbf65ba). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531155402](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531155402) was triggered at [cfcb60b](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/cfcb60b13e19fd1b44f102d03684fbfe9e2d553b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531164720](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531164720) was triggered at [55b48f6](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/55b48f696d6e3501c341dea21da209305e450172). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531310183](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531310183) was triggered at [34b6b4d](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/34b6b4dd6e3036f33801965d6e73253e8c067504). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531323105](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531323105) was triggered at [990a3be](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/990a3be8d469399b435c2803561775518e126e11). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531342686](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531342686) was triggered at [9871334](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/9871334d0d30ff6b92a20a0297bf5540525fcf15). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531381850](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531381850) was triggered at [ae0ea89](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/ae0ea89f11faf4d382dd79ba6ba0f5cf2a24f42d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531480275](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531480275) was triggered at [0473409](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/0473409df3f03b9fcd14bcd95db35668d04c0f0d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531508472](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531508472) was triggered at [2a9e6bf](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/2a9e6bfd5a7f1ed6b62d47cf7c9c858e07ee3248). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [531525332](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531525332) was triggered at [7b587ca](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/7b587ca35b21b38f82f976ea91dffb2d33f6c423). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [532145750](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/532145750) was triggered at [f146fba](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/f146fbaac51a1eb480df8d52de2cab52d88c87fd). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800">pipeline status</a> for feature branch [PR_6800](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6800). Pipeline [532191314](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/532191314) was triggered at [7765799](https://github.com/FreeCAD/FreeCAD/pull/6800/commits/77657995c53794da7ef3b5e959d14ee51a4d7e0a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Thanks for the fix.

**Pull request closed without merging**
