### PR TITLE
FEM: small fixes

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

bernd

### CODE REVIEW

**Comment by wwmayer** [comment]
FYI, replacing "solid" with "Solid" is wrong.

**Comment by luzpaz** [comment]
@wmayer the reason why I changed it was in comparison to the next icon
`Create a FEM material for Fluid`  
whereby fluid is capitalized.   
See screenshot:  
solid-vs-solid

**Comment by berndhahnebach** [comment]
Werner: FYI in this context the word solid means in German Festkörpermaterial. 
Actually I do not know what is best in English.

**Comment by berndhahnebach** [comment]
How about:

Tool tip
Creates a FEM solid material
Creates a FEM fluid material

Tool name
FEM solid material
FEM fluid material

But I am not native English ...

**Comment by wwmayer** [comment]
See here: https://www.lern-online.net/englisch/schreiben/rechtschreibung/gross-und-kleinschreibung/

In general nouns are lower case but there are some exceptions. However, I don't see that one of the listed exceptions would apply here.

**Comment by berndhahnebach** [comment]
means we go the other way around and make Fluid small too?!

**Comment by wwmayer** [comment]
Yes, when changing things then this is what I would suggest.

**Comment by luzpaz** [comment]
2 more places need changes then:

fem-fixes

**Comment by wwmayer** [comment]
Partially merged and added 12893d3 and 5f7576c

**Pull request closed without merging**
