### PR TITLE
Gui: Move texture handling to ViewProviderTextureExtension

### PR DESCRIPTION
**Pull request by wwmayer**
It should be avoided to add all stuff to the ViewProviderGeometryObject base class when it's only needed in one or more sub-classes

### CODE REVIEW

**Review by davesrocketshop — APPROVED** [review]
I don't have time for a full review, but at a glance it looks like a simple code reorg. I'm OK with these changes.

**Comment by wwmayer** [comment]
> I don't have time for a full review, but at a glance it looks like a simple code reorg. I'm OK with these changes.

The basic idea of the restructure is to have classes with higher cohesion.

Currently, I am going through your merged PR and fix bugs or regressions. Although not directly related to the goal of this PR I will put these changes here because it will be easier to avoid merge conflicts.

**Comment by davesrocketshop** [comment]
> > I don't have time for a full review, but at a glance it looks like a simple code reorg. I'm OK with these changes.
> 
> The basic idea of the restructure is to have classes with higher cohesion.
> 
> Currently, I am going through your merged PR and fix bugs or regressions. Although not directly related to the goal of this PR I will put these changes here because it will be easier to avoid merge conflicts.

Ok. I'm going to be offline until Monday, but I trust your judgement.

**Comment by wwmayer** [comment]
Finished.

**Pull request merged**
