### PR TITLE
Draft: Fix inconsistent properties of Draft annotations

### LINKED ISSUE #7861: [Issue] [Draft] Fix inconsistent properties of Draft annotations
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=23&t=73370

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.21.31058 (Git)
Build type: Release
Branch: master
Hash: e6c53d8642af36ce7d738ab6058b063ec58e0859
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Draft

### Issue description

There are some inconsistenties in the View properties of Draft annotations. This is confusing for both end users and programmers. IMO this should be improved.

#### Current situation

[Draft_Text](https://wiki.freecadweb.org/Draft_Text):
DisplayMode: 3D text/2D text ("2D text" means the text faces the camera)
FontName
FontSize
LineColor (not used)
TextColor

[Draft_Dimension](https://wiki.freecadweb.org/Draft_Dimension):
DisplayMode: 2D/3D ("3D" means the text faces the camera)
FontName
FontSize
LineColor (also used for the text)

[Draft_Label](https://wiki.freecadweb.org/Draft_Label):
DisplayMode: 3D text/2D text ("2D text" means the text faces the camera)
TextFont
TextSize
LineColor (used for leader, arrow and frame)
TextColor

#### Proposed solution for all objects

DisplayMode: Screen/World (same as used for 'yellow' labels)
FontName
FontSize
LineColor
TextColor

'Yellow' labels: `obj = App.ActiveDocument.addObject("App::Annotation", "Label")`

There is some history here and I am not sure why different property names were introduced for Draft_Label objects. I do not have a personal preference for "FontName" and "FontSize", I am proposing them because 2 out of 3 Draft annotation objects (as well as the 'yellow' labels) already use them. "TextFont" and "TextSize" would work just as well.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Roy-043**
Fixes #7861.

This is a somewhat involved PR as it touches multiple files. Also while working I discovered some problems with how the viewprovider classes were organized. Code related to the setting of properties would be called up to 6 times when an object was created.

When dimension text was aligned with the screen it was handled differently (a factor 10 was applied to the FontSize) from Draft_Text and Draft_Label objects. I have removed that (and the related extra font node). There are still other things that seem inconsistent to me, but that may also be due to my lack of coin knowledge.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8081">pipeline status</a> for feature branch [PR_8081](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8081). Pipeline [731025064](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/731025064) was triggered at [34f43a2](https://github.com/FreeCAD/FreeCAD/pull/8081/commits/34f43a245cfbb95c53d266e6accd4f40b23d57c7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
This looks good to me, and indeed unifying everything is a good thing. However:
- Are "screen" and "world" the best words? they seem a bit unclear to me for a new user... what about camera and world? i cant make my mind
- I couldn't check thoroughly (i'm not on my computer), but objects coming from older files should be supported, and probably still open on older versions? not sure about this...

**Comment by Roy-043** [comment]
In [this forum post](https://forum.freecadweb.org/viewtopic.php?p=641312#p641312) you also mention 'View' as an alternative for 'Screen'. So we have 3 options: Screen, Camera and View.

I would prefer not to use 'View' mainly because in TechDraw we have drawing views. And the texts in annotations are not aligned with TD views.

'Camera' and 'Screen' can both work IMO. My main reason for choosing 'Screen' is that this is also used for the yellow labels:
`obj = App.ActiveDocument.addObject("App::Annotation", "Label")`
If 'Camera' is chosen here then the yellow labels should perhaps be updated to match?

Note that the Render workbench has camera objects.

Changing 'Screen' to 'Camera' would not be a problem.

Regarding your 2nd remark:

Objects from older files are of course converted. But once converted, files cannot be opened in older FreeCAD versions without issues. For example a Draft_Label in a converted file will not show its text when opened in an older FreeCAD version. I see no way to solve this.

**Comment by yorikvanhavre** [comment]
Yes I think we can live with these objects not opening on older FreeCAD versions. This can as you say be worked around with a macro, etc.
The "screen" vs "view" vs "camera" question is complicated... I'm thinking, what would make the most sense for a new user. Maybe "view" indeed? Aligned with the world, vs aligned with the view. Aligned with the screen makes less sense maybe..

**Comment by Roy-043** [comment]
My CAD background is AutoCAD and Arkey (a Dutch CAD program). In AutoCAD when talking about Coordinate Systems, the terms 'World', 'Object' and 'Display' are used: WCS, OCS and DCS. This may explain why 'Screen' makes sense to me.

What makes sense to a new user would of course also depend on their (CAD) experience as well as their native language.

I am OK with 'View' if you prefer that. We can also ask others to pitch in, or may do a forum poll?

**Comment by Roy-043** [comment]
@yorikvanhavre I'd like to see this PR merged. Can you look it again please. Thanks.

**Review by carlopav — COMMENTED** [review]
I browsed the code and it looks good to me, but i don't have the time to test it at the moment, i'm sorry

**Comment by yorikvanhavre** [comment]
Sorry for the delay :sweat_smile: Ok let's do it... Unification is better than no unification. We can still talk more about proper wording later on.

**Pull request merged**
