### PR TITLE
[Sketcher] Add missing newline

### PR DESCRIPTION
**Pull request by AjinkyaDahale**

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6964">pipeline status</a> for feature branch [PR_6964](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6964). Pipeline [555783953](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/555783953) was triggered at [3f05808](https://github.com/FreeCAD/FreeCAD/pull/6964/commits/3f05808f81026571dc378fd8596b706f991f3cc7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Should this string be translated?

**Comment by AjinkyaDahale** [comment]
> Should this string be translated?

It appears yes. Maybe take a look at similar strings.

**Comment by donovaly** [comment]
Searching the code for
`Base::Console().Warning(`
I see that we in general don't translate console warnings.

**Pull request merged**
