### PR TITLE
cMake: Clean up old Mac Python search

### PR DESCRIPTION
**Pull request by chennes**
This code does not appear to do anything anymore, and in my testing the Mac builds work better without it than with it.

---

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by chennes** [comment]
@ipatch can you give this a spin and make sure I'm not overlooking something?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8400">pipeline status</a> for feature branch [PR_8400](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8400). Pipeline [771960359](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/771960359) was triggered at [35dbfa3](https://github.com/FreeCAD/FreeCAD/pull/8400/commits/35dbfa3a4ee325ed99075bcd7efd11529cc3b686). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by ipatch** [comment]
it might take me a day or two test on one of the virtual machines, but i'll try and get to it. i only build freecad on mac using homebrew, and it's something i haven't done in a while.

@chennes are you able to build on your m1 using homebrew and with PR?

**Comment by chennes** [comment]
I have a new M2 😀 - and yes, this builds fine with homebrew, with the usual homebrew caveats re: PySide and Boost-Python.

**Pull request merged**
