### PR TITLE
[For 0.19] Unicode fixes for Python3

### PR DESCRIPTION
**Pull request by cclauss**
Leverage six.PY2, six.PY3, six.builtins, six.text_type, six.string_types, and six.unichr() to avoid using the Python2-only builtins unicode and unichr.  Discovered via #1883

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Good question. I first thought it's part of Python directly but it is not. At least on Windows it's part of the Libpack and is available there since FreeCAD v0.15.
When checking on Ubuntu there are almost 100 packages that offer a file six.py but don't know if it's the same file everywhere.

**Comment by cclauss** [comment]
__pip install six__  # on all platforms

**Comment by yorikvanhavre** [comment]
Ok that means we are basically introducing a new runtime dependency. Before merging this, I would make sure the important places (debian, the ubuntu ppa, fedora...) are properly notified otherwise we'll get a hell of a screaming :)

**Comment by wwmayer** [comment]
The six module doesn't depend on any external module so we can also add it to the FreeCAD sources to guarantee it's available on all platforms.

**Comment by efferre79** [comment]
it would be better to update the documentation with the new requirements rather than including other external packages. The package maintainers of downstream distributions will add external requirements instead of removing duplicate modules from freecad sources

**Comment by cclauss** [comment]
Actually, the best approach would be to put our pip requirements into __requirements.txt__ or __setup.py__ like the rest of the world does...

**Comment by sgrogan** [comment]
I thought six was already a dependency of a dependency? It's already available from the Libpacks (VS2013 and Conda), it's in the .dmg (OSX .app). I'll check the PPA.

As wmayer has mentioned, it's a dependency for a lot of stuff.
It's pure Python, and PY2/PY3 compatible.

pip, however is not yet reliable on win.

**Comment by efferre79** [comment]
> I thought six was already a dependency of a dependency?

You cannot make that kind of assumption

**Comment by cclauss** [comment]
> pip is not reliable on Windows

What does that mean?!?

**Comment by yorikvanhavre** [comment]
If it is already bundled on windows and mac, that's fine. On linux since the travis builds all work, I believe the six package is already pushed by something else and there is nothing to do. The question is, do we merge this now, and wait/look for possible problems in distros/PPA, or do we do something before?

**Comment by cclauss** [comment]
I would like to see #1900 merged so that we have a standard response if anyone complains...
1. __pip install -r requirements.txt__
2. If you get a message that __pip__ is not installed then:
    * __python -m ensurepip --upgrade__
    * Redo step 1 above.

**Comment by efferre79** [comment]
A Linux distribution may install python packages using its own package manager and not using pip. But I agree with @cclauss, I would go for a suggestion of using pip to be indicated in the documentation together with an explicit list of dependencies (as already done on the wiki for 3rd part libs). I would avoid automatic procedures when freecad is built and installed from source, it's a task of the package maintainer to be sure every required dependency is already installed.

**Comment by efferre79** [comment]
I would use both solutions, if requirements.txt is buried in the distribution archive and pip is not used, none would notice it unless cited in the docs :-)

**Comment by cclauss** [comment]
@efferre79 [__requirements.txt__](requirements.txt) is now in place.  How should we proceed?

**Comment by berndhahnebach** [comment]
> 
> 
> I did not think this was a new dependency because two files in **src/Mod/Fem/femsolver** are already importing **six**... https://github.com/FreeCAD/FreeCAD/search?l=Python&q=six

That was me, some month ago. But it was done without any information to others. I even did not think about if it was a depency. Luckily six was installed on my machine so I had no problems. Since noone complained this was never dissussed. 

Ahh when I reinstalled Debian and compiled FreeCAD six was not installed proper, means it could be a clean ubuntu with a FreeCAD ppa does not have it installed by default. 

Next time I import a new module I will check FreeCAD depencies or ask in the forum.

Bernd

BTW: Is there may be a better solution than six, and we could remove the depency in femsolver?

**Comment by sgrogan** [comment]
> What does that mean?!?
See here: https://forum.freecadweb.org/viewtopic.php?f=22&t=29584

**Comment by cclauss** [comment]
This is not how it works on Mac or Linux but __on Windows...__
* __python -m pip__ should get you to pip running on Python 2
* __py -m pip__ should get you to pip running on Python 3.

See https://docs.python.org/3/faq/windows.html

**Comment by efferre79** [comment]
I am not using the binary package and I am playing on Linux so probably I don't have the full picture. Moreover my experience with pip is limited to installing a few binary packages on Windows.

There are two problems, the first is providing deps when building from source and the second one when installing a binary.

In the second case, usually on Windows, the deps are included in a single-file installer together with the main application. This solution provides a smoother user experience but eventually may create other problems (archives bigger and bigger, multiple copies of the same dependencies installed on the system if not managed correctly, etc.). On Linux, instead, the deps are typically provided by distributions, each one with its package manager (there are even distributions like Gentoo that have a package manager which install the binaries compiling them from sources on-the-fly). I am speaking about all kind of deps, not only python packages. Furthermore I don't have experience at all with building installers on Windows.

The requirements.txt recently committed might be related to both problems. When starting from sources, we can offer an additional solution to install the dependencies to the user by using pip but he/she must still be free to choose another way. When building an installer, it could be used to prepare all the dependencies to be shipped together with the main application. Or it could be used also at runtime by the installer itself to automatically install the dependencies.

**Comment by sgrogan** [comment]
> If it is already bundled on windows and mac, that's fine. On linux since the travis builds all work, I believe the six package is already pushed by something else and there is nothing to do. The question is, do we merge this now, and wait/look for possible problems in distros/PPA, or do we do something before?

I vote merge. I can't find six in the AppImage (built from the 14.04 PPA) if it does cause a problem it is easily fixed.

**Comment by yorikvanhavre** [comment]
I'm ok to merge this, but maybe not just before the release.. Let's wait until 0.18 is out, okay?

**Comment by sgrogan** [comment]
> I'm ok to merge this, but maybe not just before the release.. Let's wait until 0.18 is out, okay?
Fine with me.

@cclauss , @efferre79 , I would like to continue this conversation in the forum. Maybe we could make some progress on these issues.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
