### PR TITLE
App: fix memory leaks in Enumeration class and simplify code

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6861">pipeline status</a> for feature branch [PR_6861](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6861). Pipeline [535762098](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/535762098) was triggered at [9c3e195](https://github.com/FreeCAD/FreeCAD/pull/6861/commits/9c3e195ceb9132a0aa65fc0c27811db28a82eab0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Since it fixes a memory leak, it should go in for 0.20 if possible.

(For info: I am now back home and will push the release, however I will for sure need some days.)

**Comment by wwmayer** [comment]
> Since it fixes a memory leak, it should go in for 0.20 if possible.

The memory leak is only minor and because the changes are huge I don't want it to merge with v0.20.

**Comment by donovaly** [comment]
Thanks, then 0.21 stuff. (The description just attracted my attention.)

**Pull request merged**
