### PR TITLE
remove gitlab ci leftover files

### PR DESCRIPTION
**Pull request by adrianinsaval**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

somewhat related to #9791

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9793">pipeline status</a> for feature branch [PR_9793](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9793). Pipeline [903738916](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903738916) was triggered at [59a464d](https://github.com/FreeCAD/FreeCAD/pull/9793/commits/59a464d7adee721766eebb91c0e5a7862b3d6926). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
This will cut off gitlab-CI. Means gitlab-CI will no longer continue to run. Is there any forum topic about this?

cheers bernd

**Comment by adrianinsaval** [comment]
We had intentionally disabled this since it's redundant to what we are doing with GitHub already and the bot comments add noise. See the above mentioned GitHub discussion and #9535
Was it you that enabled it again?

**Comment by chennes** [comment]
We also discussed it here: https://forum.freecad.org/viewtopic.php?p=663606#p663606 -- the upshot is that the Gitlab CI does not mesh well with our GitHub workflow, and is noisy. It was a great stopgap solution that was great to have at the time, but has been superseded by @0penBrain's recent work with the built-in GH stuff.

**Comment by 0penBrain** [comment]
> This will cut off gitlab-CI. Means gitlab-CI will no longer continue to run. Is there any forum topic about this?

Ultimately decision to unplug Gitlab CI was taken during a monthly developer meeting. IIRC here are the notes : https://forum.freecad.org/viewtopic.php?t=78191

BTW @berndhahnebach , did you re-enabled the webhook recently?

**Comment by berndhahnebach** [comment]
Thanks for all the information.

I fixed a problem the machine had because one of the PR branches needed a login. This broke all the workflow. Since the problem was fixed the machine started to work again and got very hot ... 20 house compiling one PR by another ... 

I missed the decision, thus the comments came back. Just disabled the gitlab CI for PRs. No more noise anymore. Ohh yes it was a great stop gap between travis and github ... But ATM it is far behind the github ones.

cheers bernd

**Comment by adrianinsaval** [comment]
I think gitlab ci is disabled again, is it ok to merge this then?

**Pull request merged**
