### PR TITLE
More Qt 5 related changes

### PR DESCRIPTION
**Pull request by maurerpe**
Another batch of trivial Qt 5 changes.  Most of these use #if QT_VERSION >= 0x050000 to ensure Qt 4 build is unaffected.

### CODE REVIEW

**Comment by wwmayer** [comment]
Postponed until after version 0.16 is released.

**Comment by bblacey** [comment]
It seems that the communication between GitHub and Travis-CI was intermittent when this pull request was updated with commit 2d1e2bd hence the continuous-integration check will not change status unless another commit is added.  I have submitted an issue to the Travis Team but this PR will most likely require a new commit at some point to perform the CI checks.  Perhaps just another merge with master as it has changed since the last commit.

**Comment by maurerpe** [comment]
Pulling from freecad master worked.  All checks pass now.

**Comment by bblacey** [comment]
The NewPartDesign pull request is a large change set that was merged into master so there are new conflicts that need to be resolved. It would be great if you can rebase this QT5 PR with master again when you have a chance.  Once you have done so, I will take your PR for a spin on OS X ;)

**Comment by maurerpe** [comment]
Okay.  Everything looks good.  @bblacey: ready for you to check it out.

**Comment by wwmayer** [comment]
Not longer needed.

**Pull request closed without merging**
