### PR TITLE
CI: Fix MacBuild

### PR DESCRIPTION
**Pull request by vejmarie**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vejmarie** [comment]
Can you please promote the cache built on MacOS from that PR check as the standard MacOS cache for master. This will accelerate drastically the build time which will run in about 1h15 min without timeout.

**Comment by sgrogan** [comment]
@vejmarie  I can not find a way to promote a cache. I think the only way is to merge the pull request. We may have to restart the build if it doesn't complete.

**Comment by vejmarie** [comment]
Ok, so then let's merge and see if we have to restart the build. The thing is I can't do it by myself as soon as it is in master. So can you just have a look to it. It shall go up to the end by saving a cache at each steps now. Hopefully it will work and MacOS will be back ;)

**Comment by sgrogan** [comment]
I can restart the build if necessary after merge.
@wwmayer 
@yorikvanhavre

**Pull request merged**
