### PR TITLE
Draft: Some fixes in upgrade function

### PR DESCRIPTION
**Pull request by marioalexis84**
Related to [0004460: Draft Upgrade - Incorrect result](https://tracker.freecadweb.org/view.php?id=4460)
The reported bug is due a error in isCoplanar function, which is now fixed. For a more detailed explanation, see https://forum.freecadweb.org/viewtopic.php?f=23&t=51200&p=440821#p440821
The expected functionality in the report is out of the scope of current implementations of joinFaces and concatenate functions, which only work on flat shapes.
The bug [0004462: Upgrade from shell to solid failed - UnboundLocalError](https://tracker.freecadweb.org/view.php?id=4462) is fixed.
The bug [0004080: Draft upgrade make face fails with a sketch contatining multiple closed loops](https://tracker.freecadweb.org/view.php?id=4080) is fixed.
Now, joinFaces can deal with faces which generates internal holes when are joined.  
There is a change in the Update workflow:
If multiple faces are selected, the update function converts it to a shell or compound. On the next call, if all the faces are coplanar, a single refined face is created, or, if the shell is closed, a solid is created.

There is a possible limited functionality to refine faces created on planes other than xy, yz, xz due the precision of the shapes needed in Part.makeFace 

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@marioalexis84 thank you for the PR.  
An aside: please consider using the [webhook triggers that auto-reference our bugtracker](https://wiki.freecadweb.org/Tracker#GitHub_and_MantisBT) to help the devs save time.

**Comment by marioalexis84** [comment]
thanks @luzpaz , I have already modified the commit message.

**Comment by marioalexis84** [comment]
@luzpaz [0004462: Upgrade from shell to solid failed - UnboundLocalError](https://tracker.freecadweb.org/view.php?id=4462) was closed in the bug tracker, but in this PR there is a change in the makeSolid function that prevents the reported error message.

**Comment by luzpaz** [comment]
Thanks, I think the webhooks may still work on a closed ticket. But JIC, i reopened 4462 on the tracker.  
Note: JFYI, by writing
`Draft: Some fixes in upgrade function. bugs #0004460, #0004462`  
you know you are simply notating the tickets instead of closing them, right?

**Comment by marioalexis84** [comment]
> Thanks, I think the webhooks may still work on a closed ticket. But JIC, i reopened 4462 on the tracker.
> Note: JFYI, by writing
> `Draft: Some fixes in upgrade function. bugs #0004460, #0004462`
> you know you are simply notating the tickets instead of closing them, right?

Yes, it is clarified in the link that you gave me

**Comment by luzpaz** [comment]
> Yes, it is clarified in the link that you gave me

Then in that case what is left for 4462 beside this commit ?

**Comment by marioalexis84** [comment]
I am sorry, I mistook.
Would you rather I change the commit message to something like "bugs #0004460, fixes #0004462"?
there is also another commit to resolve the bug #0004080. Do you want me to add it to this PR?

**Comment by luzpaz** [comment]
Whatever is relevant, sure. Just remember every code push triggers TravisCI.

**Comment by yorikvanhavre** [comment]
Thanks! Merging. In case the "automatic" bug closing doens't work, it's no big deal... Just close them manually ;)

**Pull request merged**
