### PR TITLE
Gui: Use FreeCAD supplied icons by default

### PR DESCRIPTION
**Pull request by kadet1090**
This PR uses proper structure required by the XDG Icon Theme specification: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html like described in: https://medium.com/@yakupcengiz/exploring-qt-icon-themes-and-customization-8debfadf1580. It is semi optimal as it creates duplicates of icons using QT resources. I don't want however to cleanup and potentially break icon references before 1.0. This should be done after release.

Before:
image

After:
image

Fixes: #14968

### CODE REVIEW

**Comment by chennes** [comment]
Why just Linux? Under Qt6 Windows 11 icons look pretty terrible.

**Comment by kadet1090** [comment]
Hmmmm, looking at the code it should already behave that way on Windows:
https://github.com/FreeCAD/FreeCAD/pull/14970/files#diff-1fde83bf12f7bde0aa892591a29dad0564b3e2a4ccd8be96ac6371f0beac270fL168-L171

**Comment by chennes** [comment]
Here's what I see when compiled on Windows 11 with Qt6 --  
Screenshot 2024-06-26 181621

**Comment by adrianinsaval** [comment]
needs to be tested on our minimum supported verion of qt6 and on qt5, if nobody gets around to it I might do it in a few days on an ubuntu VM

**Comment by kadet1090** [comment]
I updated the PR to be properly utilize Icon Theme spec. Should now work fine both on Windows and Linux.

**Comment by chennes** [comment]
I can confirm that this works with Qt6 on Win11.

**Comment by MisterMakerNL** [comment]
image
Seems to work!

**Comment by yorikvanhavre** [comment]
Needs a rebase

**Comment by kadet1090** [comment]
@chennes @yorikvanhavre rebased - can be merged after CI

**Comment by berberic2** [comment]
This PR breaks my file-dialog appearance
`bool themePaths = hTheme->GetBool("ThemeSearchPaths", false);`
‣ Toolbar-icons have been replaced by text, taking far too much space
‣ Places Icons are gone or replaced by wrong ones.

Left old, right new.
Screenshot_20240719_134651

**Comment by kadet1090** [comment]
Hmm, that is pretty strange - can you make issue? I'll look for another way to fix it as it clearly impacts default dialogs while it should not...

**Comment by berberic2** [comment]
Made a new issue: #15540

**Pull request merged**
