### PR TITLE
 Draft: new command Draft_CircularArray

### PR DESCRIPTION
**Pull request by vocx-fc**
The [Draft_Array](https://www.freecadweb.org/wiki/Draft_Array) command has three modes, rectangular, polar and circular. However, currently they are launched from a single button. Further modification needs to be done in the property editor. This works but it isn't very user friendly. Therefore, this pull request introduces a new button to create the [Draft_CircularArray](https://www.freecadweb.org/wiki/Draft_CircularArray) directly. Further changes can still be done in the property editor.

The circular mode is completely new in 0.19. It was introduced in #2585. See [[Draft] circular array](https://forum.freecadweb.org/viewtopic.php?f=13&t=39726) for more information.

This pull request uses the new Gui Command structure described in #2823, and thus this request should be merged after that request. Visit that link for more information. In fact it should be merged after #2824, which introduces first the [Draft_PolarArray](https://www.freecadweb.org/wiki/Draft_PolarArray) command.

See also [Making the creation of arrays more user friendly](https://forum.freecadweb.org/viewtopic.php?f=23&t=41816), for further discussion on improving the [Draft_Array](https://www.freecadweb.org/wiki/Draft_Array) tools.

---

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by vocx-fc** [comment]
Due to the new structure of the files, #2844 needs to be merged first, before merging this pull request.

**Comment by vocx-fc** [comment]
I rebased and forced pushed everything. The branches have to be merged in this order: #2824, #2825, #2829, #2830, #2831, #2832.

More details in [this post](https://forum.freecadweb.org/viewtopic.php?f=23&t=38593&p=356476#p356476).

There will still be an unrelated Travis error. See the post and #2848 for more information.

**Comment by yorikvanhavre** [comment]
Merged #2824 but there are now merge conflicts. Can you have a look @vocx-fc ?

**Comment by vocx-fc** [comment]
Okay, it's done. I rebased also the other branches, otherwise we will have conflicts again.

**Comment by yorikvanhavre** [comment]
thanks!

**Pull request merged**
