### PR TITLE
UI: replace selection filter icon with no filter icon

### PR DESCRIPTION
**Pull request by maxwxyz**
Getting rid of the filter icon which is only visible before clicking on the group. Replaces the filter icon with the `clear-selection` icon which is used for no active selection filter - which is the default state anyways.

Currently: 
grafik

This PR:
grafik

@FreeCAD/design-working-group FYI

### CODE REVIEW

**Comment by obelisk79** [comment]
I agree that this is a logical change.

**Comment by maxwxyz** [comment]
@FEA-eng stop commenting on my PRs on Mondays 😄 You move them back to the bottom of the list for merging. Every week the same 🤣

**Comment by FEA-eng** [comment]
@maxwxyz I’m not commenting just your PRs. On Mondays, I have some time to look at the open PRs before the meeting - test them (5th compilation running now), ask for changes or approve them. Of course, I’m just a regular user, not a maintainer but the first question for each PR during the merge meeting is whether someone tested a given PR or accepted the changes. This one is also quite important for me because the selection filters were implemented on my request. Besides, the PR was far in the queue and it will be merged sooner or later anyway despite the upcoming freeze.

**Comment by maxwxyz** [comment]
@FEA-eng yes, no worries, just joking

**Comment by FEA-eng** [comment]
> @FEA-eng yes, no worries, just joking

I’m just a fan of your UI/icon improvements ;-) Seriously, you are doing awesome work with that.

**Pull request merged**
