### PR TITLE
[App] Document: remove unused includes

### PR DESCRIPTION
**Pull request by donovaly**

### CODE REVIEW

**Comment by chennes** [comment]
DocumentObserver.h appears to be missing an include of <string>

**Comment by donovaly** [comment]
> DocumentObserver.h appears to be missing an include of `<string>`

What is the compilation error message you get? In this file I have not removed anything regarding string. Also the removed BaseClass include does not define <string>.

**Comment by chennes** [comment]
The first error is:
```
Error	C2039	'string': is not a member of 'std' (compiling source file E:\FreeCAD\FreeCAD\src\Mod\Spreadsheet\App\SheetObserver.cpp)	Spreadsheet	E:\FreeCAD\FreeCAD\src\App\DocumentObserver.h	52	
```
Right now this file only includes `<memory>` and `<set>`, even though it clearly uses `std::string`. Presumably `string` was included by one of the includes that got removed, so it's breaking now.

**Comment by donovaly** [comment]
Thanks.
I only want to understand why this happens. Because the include <Base/BaseClass.h> does not define string and <boost_signals2.hpp> also not. Hmm.

However, I added this include now.

**Comment by donovaly** [comment]
OK, I compile now with PCH and then I see the compilation issue. So the boost include must stay. I force-pushed the fix now.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6425">pipeline status</a> for feature branch [PR_6425](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6425). Pipeline [476343779](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/476343779) was triggered at [439393b](https://github.com/FreeCAD/FreeCAD/pull/6425/commits/439393be3627d6d6087be8735e79a9ee5ca6cf8d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
The current build failure on linux is:
```
2761In file included from ../../../../../src/Mod/Spreadsheet/App/PropertySheet.h:27,
[2762](https://gitlab.com/freecad/FreeCAD-CI/-/jobs/2120674709#L2762)                 from ../../../../../src/Mod/Spreadsheet/App/PropertySheetPyImp.cpp:26:
[2763](https://gitlab.com/freecad/FreeCAD-CI/-/jobs/2120674709#L2763)../../../../../src/App/DocumentObserver.h: In member function 'T* App::DocumentObjectT::getObjectAs() const':
[2764](https://gitlab.com/freecad/FreeCAD-CI/-/jobs/2120674709#L2764)../../../../../src/App/DocumentObserver.h:145:16: error: 'Base' has not been declared
[2765](https://gitlab.com/freecad/FreeCAD-CI/-/jobs/2120674709#L2765)  145 |         return Base::freecad_dynamic_cast<T>(getObject());
[2766](https://gitlab.com/freecad/FreeCAD-CI/-/jobs/2120674709#L2766)      |                ^~~~
```

**Comment by wwmayer** [comment]
> I only want to understand why this happens. Because the include <Base/BaseClass.h> does not define string

You cannot remove Base/BaseClass.h from DocumentObserver.h because this provides the template function freecad_dynamic_cast that is used in DocumentObjectT and DocumentObjectWeakPtrT. BaseClass.h includes Type.h that includes string

**Comment by donovaly** [comment]
Fixed now.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6425">pipeline status</a> for feature branch [PR_6425](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6425). Pipeline [477358231](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/477358231) was triggered at [4adabe3](https://github.com/FreeCAD/FreeCAD/pull/6425/commits/4adabe3de8127c38f570509a2b0fa06e56fc61e3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
