### PR TITLE
Assembly: Fix regressions of #16726

### PR DESCRIPTION
**Pull request by PaddleStroke**
See problem description in https://github.com/FreeCAD/FreeCAD/pull/16726#issuecomment-2414166608

This fixes it. @maxwxyz could you give this a go?

### CODE REVIEW

**Comment by maxwxyz** [comment]
seems to fix the described issue

**Comment by CalligaroV** [comment]
@PaddleStroke, for now I have only one comment, while I go back to the code of #16726.

Before merging it I would suggest to check it against the examples shared in #16207 to avoid opening again that issue or similar ones.
You can also consider, as reference, the results of my tests I shared in https://github.com/FreeCAD/FreeCAD/pull/16726#pullrequestreview-2336029847

Memories are coming back while I write this comment and I remember that while reviewing that I tried also some modified version of the logic that trims the names of the geometrical objects, to make it "smarter" and avoid trimming useful parts (as, for example, the origin Axes/Planes).

However ATM I don't remember that code :confounded:

As for other PRs, I don't want to slow down the merge, therefor don't wait too much for my comments, but if possible please at least perform again some of the tests I did for #16726 (in case you haven't already done them)

Thanks!

**Comment by PaddleStroke** [comment]
I have tested the files and they work.
This should go in asap @chennes , 16726 introduced a lot of regressions but most importantly its migrationScript4 is corrupting good existing files.

**Comment by chennes** [comment]
Backported to 1.0

**Pull request merged**
