### PR TITLE
Port to new QOpenGL classes in Qt5

### PR DESCRIPTION
**Pull request by wwmayer**
Port from deprecated QGL* classes to new QOpenGL* classes of Qt5.

For more information see: https://forum.freecadweb.org/viewtopic.php?f=10&t=20105&start=10#p163950
This fixes issues: #0002952, #0001401 and apparently #0002953 and #0002942

Open issues are still:
* multi-sampling is automatically disabled when un-docking a 3d view
* sometimes the lighting is disabled or the whole scene disappears when un-docking/re-docking a 3d view

### CODE REVIEW

**Comment by bblacey** [comment]
@wwmayer - thanks for pushing hard on the QtOpenGLWidget port!  That said, unless this PR includes a change to define `FREECAD_USE_QTOPENGL_WIDGET` for the macOS Qt5 build, which I think it should, Travis will not test QtOpenGLWidget on macOS.  It would probably be best to change CMakeList.txt to default to `FREECAD_USE_QTOPENGL_WIDGET` when building with `BUILD_QT5=ON` on macOS.

In the interim, I have pulled a local copy of your PR and am building locally to verify.  I would wait to merge until at least one of these is complete, but ideally both.

**Comment by bblacey** [comment]
Ok, clang on macOS fails with forward declaration errors unless you add the following patch:

```
diff --git a/src/Gui/View3DInventor.cpp b/src/Gui/View3DInventor.cpp
index 9e1f84a..1cf6ac1 100644
--- a/src/Gui/View3DInventor.cpp
+++ b/src/Gui/View3DInventor.cpp
@@ -58,6 +58,7 @@
 
 #if defined(HAVE_QT5_OPENGL)
 # include <QWindow>
+# include <QMdiSubWindow>
 #endif
 
 #include <Base/Exception.h>
```

**Comment by wwmayer** [comment]
I pushed a further commit to enable the use of QOpenGL*
Can you verify that this also fixes #0002953 and #0002942

**Comment by bblacey** [comment]
Sure, I will confirm those two issues once my build finishes.

**Comment by bblacey** [comment]
Just found another forward declaration issue (QLayout):
```
diff --git a/src/Gui/View3DInventor.cpp b/src/Gui/View3DInventor.cpp
index 9e1f84a..c26a6a0 100644
--- a/src/Gui/View3DInventor.cpp
+++ b/src/Gui/View3DInventor.cpp
@@ -58,6 +58,8 @@
 
 #if defined(HAVE_QT5_OPENGL)
 # include <QWindow>
+# include <QMdiSubWindow>^M
+# include <QLayout>^M
 #endif
 
 #include <Base/Exception.h>
```

Sorry, but a clean build takes a while on my system but I think this is it.

**Comment by ianrrees** [comment]
Nice work, thanks!  I noticed a couple bits of dead code like `#if defined (_DEBUG) && 0` - is the intent to leave those in, or would you like a hand with finding and removing them?

**Comment by wwmayer** [comment]
> Nice work, thanks! I noticed a couple bits of dead code like #if defined (_DEBUG) && 0 - is the intent to leave those in, or would you like a hand with finding and removing them?

Yes, this is intended. When I used the OpenGL debug logger I was able to locate the exact line of code that caused OpenGL errors.

However, since the synchronous logging is very expensive (and only needed in debug) I disabled the whole block with #if defined (_DEBUG) && 0. Whenever I run into new OpenGL issues I can simply replace the 0 with 1. And I don't want to remove the block because it took me a while to figure out how to use the class.

**Comment by bblacey** [comment]
I have confirmed that this PR resolves Mantis issues #0002953 and #0002942.

**Comment by bblacey** [comment]
@wwmayer - Docking and un-docking no longer causes an OpenGL exception on macOS 👍 Previously I could reliably crash the app with a bad access exception...  When you re-dock the view on Linux, does it re-dock expanded to the full quarter view or does it dock adjacent to other windows (e.g. Start Page)?

**Comment by wwmayer** [comment]
> When you re-dock the view on Linux, does it re-dock expanded to the full quarter view or does it dock adjacent to other windows (e.g. Start Page)?

I don't know. At the moment I don't have a Linux setup with Qt5 on it.

**Comment by bblacey** [comment]
> I don't know. At the moment I don't have a Linux setup with Qt5 on it.

How about Windows?  I'm just curious if what I am seeing is the expected behavior or unique to macOS?

**Comment by wwmayer** [comment]
> How about Windows? I'm just curious if what I am seeing is the expected behavior or unique to macOS?

On Windows it behaves like this:
* when only one mdi view is there then undock => redock shows the mdi maximized independent if the mdi was maximized before or not
* when there are two windows and they are not maximized then undock => redock makes it again not maximized

This is the same behaviour as before with the old OpenGL API. Actually, the new OpenGL doesn't have any influence on this behaviour.

**Comment by bblacey** [comment]
@wwmayer - thanks for the explanation.  Honestly, I never really used undock so I wasn't familiar with the existing behavior.  The impetus for my question was that from a user-experience perspective, I assumed the window would be restored to its original docked position but that seems not to be the case and I am seeing the behavior you described on macOS.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
