### PR TITLE
[TD]prevent loop with AutoScale

### PR DESCRIPTION
**Pull request by WandererFan**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by donovaly** [comment]
I don't understand. How can I get an infinite loop? As testcase would be helpful that I can understand in what cases a loop is triggered. I tested a lot but never got an infinite loop.

This PR seems to me as if you just forbid the immediate apply of a changed scale, but this was the feature I need and thus made the change.

**Comment by WandererFan** [comment]
The loop isn't within 1 program.

User has a DrawViewPart with ScaleType = Automatic.  The DrawViewPart executes and marks Scale as changed.  Then DrawView::onChanged executes and tells DVP to execute again which touches Scale which invokes DrawView::onChanged until you run out of memory and the program crashes.

**Comment by donovaly** [comment]
Thanks, I understand now. But is there then no other way to apply scalings directly. ScaleType change is not necessary in my opinion but changing the scale should be directly visible. In my real-life document I change the scale in steps of 0.1 to see when it looks "neat".

**Comment by WandererFan** [comment]
We can probably figure out how to do it.   Maybe something with tweaking the "touched" status of the object or the property.  Maybe doing something different if scale type is automatic.  Needs some thought.

**Pull request merged**
