### PR TITLE
TechDraw: add unit for rotation

### PR DESCRIPTION
**Pull request by donovaly**
use PropertyAngle for rotations
to be merged after PR #2734

### CODE REVIEW

**Comment by WandererFan** [comment]
Linux gcc build failed.  Looks like time out.

**Comment by donovaly** [comment]
>  Looks like time out.

Yes,, this happens for other commits too. The other builds succeeded.

I merged now with master and also changed the tab indentations as requested to spaces.

**Comment by WandererFan** [comment]
your branch has merge conflicts with master.

**Comment by donovaly** [comment]
> your branch has merge conflicts with master.

Must be one of your other TD commits. I am away and cannot have a look before weekend.

**Comment by WandererFan** [comment]
resolve merge conflicts

**Comment by donovaly** [comment]
Toady I got again merge conflicts. I resolved them.
Please commit it before making the next big TD change because I fear getting merge error again.

**Comment by WandererFan** [comment]
in Annotation linespace property needs to be able to be > 100 - ie 200% for double space.   PropertyPercent is 0-100 unless you override the constraints.

MaxWidth property has to be able to be < 0.  -1 is the default value in QGraphicsTextItem meaning don't break lines. 

I have a branch with just the Rotation property change - "AngleUnitsReadyForMerge".  I'm going to merge that and close this PR.

**Comment by donovaly** [comment]
> in Annotation linespace property needs to be able to be > 100 - ie 200% for double space. PropertyPercent is 0-100 unless you override the constraints.

I am confused now because my initial PR only changed the angle:
https://github.com/FreeCAD/FreeCAD/pull/2747/commits/5bf8a3da53d14e0ad7179b35ead70690e0d6d8b5
nothing else.

**Pull request closed without merging**
