### PR TITLE
Arch artwork alignment

### PR DESCRIPTION
**Pull request by agryson**
[Forum Pull Request](http://forum.freecadweb.org/viewtopic.php?f=17&t=19801)
[Forum Discussion](http://forum.freecadweb.org/viewtopic.php?p=151832#p151832)

### CODE REVIEW

**Comment by agryson** [comment]
This build failed for the following reason 
```
FAIL: testSlotCase (TestSketcherApp.SketcherSolverTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/FreeCAD.app/Contents/Mod/Sketcher/TestSketcherApp.py", line 112, in testSlotCase
    self.failUnless(len(self.Slot.Shape.Edges) == 4)
AssertionError: False is not true
```
I don't understand how svgs could cause this and it's the second time the third taxis build fails while the other two pass... Could someone who knows more about the build explain the issue to me ?

**Comment by agryson** [comment]
wtf? Now all checks say they've passed, but as you can see, the clang xCode one most definitely hadn't... and I didn't add any commits to run the tests again... does anyone know what's going on?

**Comment by sgrogan** [comment]
I re-started the build and it passed this time. The error was strange. There was a similar error in master yesterday but only on 64 bit Windows? https://ci.appveyor.com/project/yorikvanhavre/freecad/build/1.0.1013/job/7l5ovgeirj22pkaw#L9598

**Comment by agryson** [comment]
Ah, thanks for the clarification and restart. [Pull request 398](https://github.com/FreeCAD/FreeCAD/pull/398) had a similar issue which @yorikvanhavre bypassed manually, but obviously the issue has been around for a while... 😟

**Pull request merged**
