### PR TITLE
[FEM] add new constraint for magnetization 

### PR DESCRIPTION
**Pull request by donovaly**
- needed for electromagnetic simulations

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393">pipeline status</a> for feature branch [PR_8393](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393). Pipeline [770670922](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770670922) was triggered at [57e11e5](https://github.com/FreeCAD/FreeCAD/pull/8393/commits/57e11e50ac28b0227b23b3ece680e0f0883a640e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393">pipeline status</a> for feature branch [PR_8393](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393). Pipeline [770696355](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770696355) was triggered at [c5d8c9b](https://github.com/FreeCAD/FreeCAD/pull/8393/commits/c5d8c9bdccdf0112bf1882e0a124b9130d65267d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393">pipeline status</a> for feature branch [PR_8393](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393). Pipeline [771691703](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/771691703) was triggered at [b63f376](https://github.com/FreeCAD/FreeCAD/pull/8393/commits/b63f37669fdfa309c13f00f4ef8eae59ad122ccb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393">pipeline status</a> for feature branch [PR_8393](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393). Pipeline [771720212](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/771720212) was triggered at [e61ecec](https://github.com/FreeCAD/FreeCAD/pull/8393/commits/e61ecec73db6c75d71c6c7faae22c376d9d15c9e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
The PR is ready to be merged, but it is not yet clear if this is really necessary. Magnetization is a material property, to my knowledge not also an external force. Let's wait what the outcome is: https://www.elmerfem.org/forum/viewtopic.php?t=7904

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393">pipeline status</a> for feature branch [PR_8393](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393). Pipeline [772091959](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/772091959) was triggered at [b23c671](https://github.com/FreeCAD/FreeCAD/pull/8393/commits/b23c6713ff3681209cffde1ee296e93924139931). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393">pipeline status</a> for feature branch [PR_8393](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8393). Pipeline [772158289](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/772158289) was triggered at [deac302](https://github.com/FreeCAD/FreeCAD/pull/8393/commits/deac3024ee9c8b5e9e37b6bb49b631257fe195a9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
