### PR TITLE
path: Correct feedrate unit in linuxcnc post processor

### PR DESCRIPTION
**Pull request by gdoffe**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [OK ] Branch rebased on latest master `git pull --rebase upstream master`
- [ N/A] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ OK] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ N/A] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---
The unit format is wrong for linuxcnc post processor, thanks to dlhenke who gave the solution on freecad forum.

### CODE REVIEW

**Comment by GeneGH** [comment]
The change of feedrate units simply replaces one hard-coded mistake with another. The proper solution would be to allow a choice of units, not simply force everything to the metric system.

**Comment by gdoffe** [comment]
The mistake is in the following incoherence:
- G21 is for metric system.
- 'in/min' is imperial system.

To correct this, we need to change:
- G21 to G20
or:
- imperial to metrics

I agree it is still hard coded, but there is no more mistake. ;)

I agree the best solution is to rely on unit choice but this pull request is just a hard coded solution to an hard coded problem.

**Comment by GeneGH** [comment]
My comment was only partly serious, since I already need to use a private copy of LinuxCNC for my needs.

However, your proposed solution is incorrect, at least according to the LinuxCNC current documentation and my own observation.

Quoting: _Feed rates are expressed in current length units per minute_

Using mm/sec is incorrect for LinuxCNC, at least in general. Special versions of the LCNC GUI could be made for lots of changes, but adjusting FC for those specials would be a mistake.

**Comment by dlhenke** [comment]
I do not know if i am right but GRBL over Arduino is mm/s

i have one and it needs mm/s
Also HeeksCNC is mm/s
who is wrong ?

**Comment by gdoffe** [comment]
GeneGH is right about units, it should be 'mm/min'.
This one is a real mistake ! ;)

I will have a look tonight as the gcode generated seems good even with 'mm/s'...

Thx

**Comment by dlhenke** [comment]
Ok I’ve tried to use mm/min
But the result is something strange when you post process .
Thx

**Comment by GeneGH** [comment]
There is no "right" or "wrong". We just need to follow the conventions for the machine controller we use. 

I agree that the original error was real. It is simply nonsense to talk about G21 and inches per minute.

The bigger issue is more complicated, as this discussion shows. There are at least three conventions needed in a postprocessor, perhaps four. 

I will stop at this point. As noted above, I need a special postprocessor in any case.

**Comment by yorikvanhavre** [comment]
@sliptonic?

**Comment by m0n5t3r** [comment]
um, grbl definitely works in mm/min, just like every other gcode-consuming machine I've seen (not many, mind you, just 3d printers and a few other arduino thingies); however, as long as there is no change in units between the tool controller and the output everything should work (roll eyes, put mm/min value in there even if it says mm/s, it should come out just fine in the final gcode)

I would guess it's fine to set the defaults to metric and set `UNIT_FORMAT` in https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Path/PathScripts/linuxcnc_post.py#L121 

However, freecad-daily doesn't seem to pass those along any more, or they are hidden somewhere, and the `import ipdb; ipdb.set_trace()` trick doesn't work for some reason (looks like there is no sys.stdin), so I can't poke around.

**Comment by ianrrees** [comment]
Just for another couple datapoints: Mitsubishi MELDAS 60/60S and Mach3 use unit/min where unit is mm or inch for linear speed.

**Comment by gdoffe** [comment]
The main problem here was not about the unit itself, but about the unit system. G21 is for metrics not imperial. So G21 code should be changed to G20 OR 'in/min' should be changed to 'mm/min'.

As we are in the linuxcnc postprocessor, linuxcnc uses <choosen_unit>/min as @GeneGH pointed it before.
So @m0n5t3r, your commit seems good to me, except for the time unit that should be minutes according to linuxcnc expectations. I did the same mistake in my PR.

I found (a bite late :D ) a post about that on the FreeCAD forum where @sliptonic resume well the situation:
https://forum.freecadweb.org/viewtopic.php?f=15&t=20497&start=20

**Comment by m0n5t3r** [comment]
well, I left it in mm/s because that's used in freecad, so the value would pass unchanged; I changed it now to mm/min as it should be, going to open a new pull request

**Comment by gdoffe** [comment]
Ok thank you !

I close this one as there is nothing more to pull from it.

**Pull request closed without merging**
