### PR TITLE
PATH: Bugfix/vcarve c++ exception

### PR DESCRIPTION
**Pull request by mlampert**
This fixes the behaviour noted in https://forum.freecadweb.org/viewtopic.php?f=15&t=70208.
boost::polygon::voronoi generates some edges that don't make a lot of sense to process - I called them "borderline", for lack of a better name.

Also, "Voronoi" is now a module underneath "Path" and the object names are simplified accordingly ("Path.VoronoiEdge" -> "Path.Voronoi.Edge", ....)

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7278">pipeline status</a> for feature branch [PR_7278](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7278). Pipeline [600698013](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600698013) was triggered at [24a36f1](https://github.com/FreeCAD/FreeCAD/pull/7278/commits/24a36f192dad6c934bee032405150d004d1fe906). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7278">pipeline status</a> for feature branch [PR_7278](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7278). Pipeline [600909127](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600909127) was triggered at [234ecad](https://github.com/FreeCAD/FreeCAD/pull/7278/commits/234ecadc4770fd0ce9c8ac0a8bd2ccb4c9c7bcd2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7278">pipeline status</a> for feature branch [PR_7278](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7278). Pipeline [603226260](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/603226260) was triggered at [3408d7c](https://github.com/FreeCAD/FreeCAD/pull/7278/commits/3408d7c2ca33fead90418347fbde9ced9ca394d8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7278">pipeline status</a> for feature branch [PR_7278](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7278). Pipeline [603400056](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/603400056) was triggered at [79a9b29](https://github.com/FreeCAD/FreeCAD/pull/7278/commits/79a9b29304794b214d9ddb0e2473c5b4c85e8beb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Is this something to be backported to FC 0.20.1?

**Comment by sliptonic** [comment]
Yes

**Comment by donovaly** [comment]
Backported

**Pull request merged**
