### PR TITLE
Repair XML Files - fixes #10730

### LINKED ISSUE #10730: [Problem] Whitespace/Indentation uniformity issues in `src/Mod/Part/App/Geom2d` XML (API) files
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The XML files in https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/Part/App/Geom2d have non-uniform whitespace.

### 4 spaced indentation 
https://github.com/FreeCAD/FreeCAD/blob/4293c4a65b0e69975dcdbbf68c80d8019a4f850d/src/Mod/Part/App/Geom2d/ArcOfCircle2dPy.xml#L1-L31

* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/ArcOfConic2dPy.xml  
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/ArcOfEllipse2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/ArcOfHyperbola2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/ArcOfParabola2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/Circle2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/Conic2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/Geometry2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/Line2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/Line2dSegmentPy.xml

-----

### Tabbed space (or 8 spaced) indentation example
https://github.com/FreeCAD/FreeCAD/blob/4293c4a65b0e69975dcdbbf68c80d8019a4f850d/src/Mod/Part/App/Geom2d/Parabola2dPy.xml#L1-L42

* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/BSplineCurve2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/BezierCurve2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/Curve2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/Ellipse2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/Hyperbola2dPy.xml
* https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/Geom2d/OffsetCurve2dPy.xml

### Full version info

```shell
Current v0.22 master
```

### Subproject(s) affected?

Part

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by KimK**
In ../src/Mod/Part/App/Geom2d/ I found 17 XML files, 16 of which needed repair as per the GitHub issue. I repaired the tabbing on those 16 files to the 4-spaces no-tab-chars method. Also other minor changes as needed.

### CODE REVIEW

**Comment by 3x380V** [comment]
@KimK, as it seems this is a kind of a learning PR, here are some nitpicks:
- commit messages are normally written using imperatives, so "fix indentation to 4-spaces, no tabs" or something like that.
- developer itself does not enter to the scene, so no "I found 17 files", etc...
Patch itself looks good.

**Comment by KimK** [comment]
Yes, learning. OK, thanks, I'll amend the message. Back soon.

**Comment by KimK** [comment]
OK, I think I've screwed things up again. What's the best way to get out of this mess?

**Comment by 3x380V** [comment]
Let's assume you have your `10730` branch checked out somewhere on your development machine and commits you want to merge here are part of this branch. Now it seems you did some mistake while rebasing... So `git rebase -i main` will open editor of your choice where you'll see your commits. Use `r` to change their commit message. After rebasing, force push your branch again.

Questions: What OS are you using? Are you using any graphical interface to git? (if second answer is 'yes' I cannot help much, there are dozens of them and I'm still using cli)

**Comment by KimK** [comment]
@3x380V: Thanks! I think that worked. (Did it? Is it acceptable now?) My OS is Linux Mint 21.3 Cinnamon. For git I use (variously, at different times) CLI (for complex situations, fetching/merging, and pushing from branches), git-gui (AKA git gui) for staging and commits, and gitk (for browsing a branch/repo), although I sometimes have to use git log to be able to copy a hash.

**Comment by 3x380V** [comment]
@KimK, it worked in terms there is single commit you want to merge again, but commit message is still worth polishing.

**Comment by KimK** [comment]
Oh! I didn't notice that it went back to what it was. I did update it, though. I have to leave now, I'll fix it a second time when I return. Thanks for your help.

**Comment by 3x380V** [comment]
@KimK, you might want to run `gitk` before pushing to see changes you made.

**Comment by KimK** [comment]
Oh! I didn't notice that it went back to what it was. I did update it, though. I have to leave now, I'll fix it a second time when I return. Thanks for your help. [Left without clicking "Save", back now.] Ha, yes, I _should_ look before pushing (with gitk _or_ git log), I just never anticipated that any kind of rebase or merge would change the commit message, so I didn't look at all. Message fixed now, and force-pushed. Is it OK now?

**Comment by 3x380V** [comment]
@KimK, neither merge nor rebase changes a commit message. There had to be some other problem.
Message changed, how much okay or acceptable this patch is depends on maintainers now... At least you know how to proceed when they eventually request other changes :)

**Comment by chennes** [comment]
@wwmayer was there a reason for a 2-space indent? This predates me. We also have to decide if we want to add XML files to our pre-commit auto-formatting setup.

**Comment by wwmayer** [comment]
> was there a reason for a 2-space indent?

No, I don't think so.

> We also have to decide if we want to add XML files to our pre-commit auto-formatting setup.

pre-commit changes them to 4 spaces which is OK IMO.

**Pull request merged**
