### PR TITLE
Add new draft join and split tool

### PR DESCRIPTION
**Pull request by Moult**
Basically takes two wires which have a coincident start / end and joins them together. I think it's pretty useful. Doesn't yet have its own fancy icon though.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Nice addition! Should we wait to add a specific icon?

**Comment by Moult** [comment]
Yeah definitely! Otherwise it will confuse people. Is there a place I can request an icon? Is there a guy who likes to create icons for FreeCAD? Maybe we should request a "split" icon too because that is the logical next step.

**Comment by Moult** [comment]
Now you can bulk select a bunch of lines and join them all at once. I think this is more convenient.

**Comment by yorikvanhavre** [comment]
Yes, just ask on the forum, usually someone will make one...

**Comment by Moult** [comment]
Requested! https://forum.freecadweb.org/viewtopic.php?f=34&t=33829 Thanks for the tip. I'll get around to implementing splitting tomorrow.

**Comment by Moult** [comment]
Icons added and split tool added. Ready for review :)

**Comment by yorikvanhavre** [comment]
Looks perfect! Waiting for the CI tests to finish and I'll merge. Please consider adding doc pages on the wiki! ;)

**Comment by chopinregis** [comment]
I hope that this in the future will be able to work on the main bim objects like walls aswell.

**Pull request merged**
