### PR TITLE
Fix MED Reader

### PR DESCRIPTION
**Pull request by vejmarie**

### CODE REVIEW

**Comment by wwmayer** [comment]
This doesn't work for me, neither under Linux nor under Windows.

**Comment by vejmarie** [comment]
Agree, this still doesn't work with your example file 👎  but there is something that I do not understand if I export a MED file from FreeCAD and re-import it it does work for me on Linux (Xenial), same thing with Code_Aster. Can u tell me with which version of HDF5 and MED you compile ? What does your mesh geometry contain (A cube, a sphere, anything else ?).

**Comment by vejmarie** [comment]
Ok, I know from where the issue comes. Did you saved your MED mesh with FreeCAD ? The name of the mesh into the MED file is mesh, while I was looking for something like FreeCADmesh. There is a comparaison done into SMESH to check Mesh name into MED which is acting like an archive.
This is done into FemMesh.cpp (and pointed me out to a misspelling)

myMesh->ExportMED(File.filePath().c_str(),"FreeCADMesg",false,2); // 2 means MED_V2_2 version 

The second string is the "default" name of the save Meshed into the MED archive while the Read call is myMesh->MEDToMesh(File.filePath().c_str(),File.fileNamePure().c_str());

By the way your mesh is a single face square shape (I have been able to read it, by adapting naming). If yes I will propose as a first time to use fileNamePure as default mesh name for saving operation. This will allow FreeCAD to save in MED and import MED file saved by FreeCAD the time to implement a "select" popup windows when opening a MED file to read the content wished or just read everything (which might be even simpler)

**Comment by vejmarie** [comment]
@wwmayer with this additionnal patch into Fem_Mesh.cpp it seems to work. Sorry for the inconvenience.

**Comment by wwmayer** [comment]
Just to answer your questions (even if not needed any more):
HDF5: 1.8.16
MED: 3.0.7
Mesh is a cube and a sphere and was saved inside FreeCAD. Will try your new patch ASAP.

**Comment by vejmarie** [comment]
I probably still have some issues as i do not see the sphere let me recheck did u merged them before exporting ? Did They were a single solid ?

**Comment by wwmayer** [comment]
Now the export & import (a single solid) works like a charm. Thanks.
I have already merged the PR. For more bug-fixes open a new PR, please.

**Comment by wwmayer** [comment]
FYI, a med file with two solids still works
Steps:
Go to Part workbench
Create torus
Create sphere
Create a compound containing the two shapes.
Go to FEM workbench
Create mesh from compound gives a mesh with two solids
Export as med & Import as med and the mesh is still intact.

**Comment by vejmarie** [comment]
good thanks for the update !

**Comment by vejmarie** [comment]
Are you sure to have merged the PR ? I just rebased on master my tree and didn't got the update ;)

**Comment by vejmarie** [comment]
I am not awake, forgot my latest post, I have merged the proper fixes into my local master, thanks !

**Pull request closed without merging**
