### PR TITLE
cmake: enable BUILD_FLAT_MESH by default

### PR DESCRIPTION
**Pull request by adrianinsaval**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

https://github.com/FreeCAD/FreeCAD/pull/9663#issuecomment-1565420374

it would seem it's not necessary to keep this off by default anymore

@wwmayer do we need to change something else? is pybind something that is not normally used? would it be ok to use it by default?

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9773">pipeline status</a> for feature branch [PR_9773](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9773). Pipeline [903572416](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903572416) was triggered at [93f9a34](https://github.com/FreeCAD/FreeCAD/pull/9773/commits/93f9a34b408a8c595cd49483ea42f8a0784ff90c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
> do we need to change something else?

Should be fine.

> is pybind something that is not normally used?

pybind usually isn't installed on a user's machine.

The user has two options for the Python binding: pybind or boost.python and what is used depends on the option FREECAD_USE_PYSIDE

> would it be ok to use it by default?

pybind is more powerful and has less overhead than boost.python. So, for me it's fine to prefer pybind over boost.python by default. In this case FREECAD_USE_PYSIDE should then be set to ON by default.

**Comment by adrianinsaval** [comment]
perhaps you meant to say `FREECAD_USE_PYBIND11`?

**Comment by wwmayer** [comment]
> perhaps you meant to say FREECAD_USE_PYBIND11?

Thanks for the correction. Yes, I meant FREECAD_USE_PYBIND11

**Pull request merged**
