### PR TITLE
[Path WB] Removing the check for parallel edges

### PR DESCRIPTION
**Pull request by machste**
In order to realise my project, I had to remove the check whether the two selected edges were parallel.

Could it be possible to remove this check?

I know, my commit is not the final solution. However, I use the pull request to point to the code that prevents my project from succeeding.

Regards,
Stefan

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@machste have you discussed this with the Path devs on the forum at all ? If so please link to the thread. If not, please open one and do so. Thx.

**Comment by machste** [comment]
@luzpaz I'll do so as soon as I got the time. I'll also provide an example to illustrate the problem I came across.

**Comment by luzpaz** [comment]
@machste thanks. Please link to the ticket when you do. Cheers

**Comment by Russ4262** [comment]
What is the purpose of the changes in this PR?  What bug does it fix?  What new capability is it targeting?  Does it remove, replace, or maintain and improve an existing capability?

**Comment by machste** [comment]
Hi @Russ4262, as @luzpaz requested I'm going to open a new topic in the FreeCAD forum (Path/CAM). I will explain why I want to get rid of the parallel check there. Cheers

**Comment by machste** [comment]
I've just opened a [new topic](https://forum.freecadweb.org/viewtopic.php?f=15&t=53317) on the FreeCAD forum. I hope that helps to understand my problem.

**Comment by machste** [comment]
Since the commit of this pull request isn't fit for pulling anyway I will close it for good.

**Pull request closed without merging**
