### PR TITLE
Techdraw: finish Qt6 port

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by chennes** [comment]
Was this the last thing that we were waiting on for full Qt6 support?

**Comment by wwmayer** [comment]
Yes, I think so.

However, we still have tons of slot functions of this form `on_objectname_signalname`  that are automatically connected with QMetaObject::connectSlotsByName. Since several signals have been renamed in Qt6 some automatic connections may fail.

**Comment by wwmayer** [comment]
BTW, the algorithm for Qt6 can be easily tested with Qt5. Therefore replace `#if QT_VERSION < QT_VERSION_CHECK(6,0,0)` with `#if 0` in XMLQuery.cpp. When creating a TD page you will see the green bullets where you can change the editable fields.

Now if you comment out the line `processElements` inside `processItems` you will realize that the green bullets are missing.

**Comment by wwmayer** [comment]
> Should we be eliminating the automatic connections and doing it manually?

This is what clazy recommends. I don't have a commit right now that shows the warning but you have already seen it for sure that clazy says that the automatic connections are error-prone. IMO, it's similar to the old-style connect with SIGNAL and SLOT which has raised many issues with the Qt6 port.

So, as a long-term goal we should migrate to the manual connection but this is not of high priority.

**Pull request merged**
