### PR TITLE
add a python method to cut holes in a Part.Face

### PR DESCRIPTION
**Pull request by tomate44**
In fact, this is yet another signature of the Part.Face constructor : 
(face, list_of_inner_wires)
But I think it is more intuitive if exposed as a method (Part.Face constructor is pretty crowded already).

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@tomate44 is there any place we're documenting this ?

**Comment by tomate44** [comment]
What ? This new method ? The Part.Face constructor ?
If this PR is merged, I'll add a note on 0.19 release notes.
For the python API, I don't know if there is a place where we can document it on the wiki.

**Comment by yorikvanhavre** [comment]
Looks good! The docstring you added seems sufficient (although we should take the habit of writing more extent docstrings, say what the method will return, etc). We still have an old, manual python API at https://www.freecadweb.org/wiki/Part_API but I don't think it's worth being updated.. We should concentrate on making the doxygen output at https://www.freecadweb.org/api/ better...

**Comment by tomate44** [comment]
Thanks Yorik.
Concerning the docstring, I am often unsure how much concise / verbose to be.
If the docstring is the only up-to-date API documentation source, I guess we can be verbose when needed.

**Pull request merged**
