### PR TITLE
[Everywhere] Remove Inkscape metadata

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by benj5378** [comment]
Well, now I am the one creating lots of noise.

Do you have any opinions of the sanitations @chennes? This is far from all files... some files are exported as optimized SVG others as plain SVG, we should probably have a guideline in the handbook

**Comment by yorikvanhavre** [comment]
Thinking out loud here, honestly, I am wondering if this is a good move, in theory. 

This is source code, right? The files here are meant to be easily editable by others. By suppressing inkscape properties, we turn these files less easily editable. This is I guess not really a problem for our icons, but in more general meaning, is that a good move?

This inkscape stuff is not really heavy, and it's transparent to other apps too. So it's not really an issue that we're having and solving here. Plus, each time someone will update icons, there is a good chance the inkscape stuff will be in again. Will we each time go there and tell people to change their PR? Again, why would we do so if it does not really cause a problem...

If it is a file size problem, I'm not sure this really makes a big difference, but shouldn't it then be some script that runs at build time?

**Comment by chennes** [comment]
Wasn't there some kind of issue with some part of FreeCAD not liking the Inkscape stuff? That may be in the distant past now, I don't remember exactly what it was.

**Comment by yorikvanhavre** [comment]
Indeed we should turn this into some kind of official policy to avoid unnecessary work like this (sorry @benj5378 !) Not sure where, though...

**Pull request closed without merging**
