### PR TITLE
Adding info to hand over the copyright to the FPA

### PR DESCRIPTION
**Pull request by yorikvanhavre**
Addition to the contribute guide to explain how to attribute copyright to the FPA

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8095">pipeline status</a> for feature branch [PR_8095](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8095). Pipeline [732913922](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/732913922) was triggered at [cc6ad7b](https://github.com/FreeCAD/FreeCAD/pull/8095/commits/cc6ad7b9e17fd3d8491374c81c816a21041bb4a9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by sliptonic — APPROVED** [review]

**Comment by adrianinsaval** [comment]
that works for entirely new files, but what about modifications to a file?

**Comment by mlampert** [comment]
Thanks, this is great!

**Comment by WandererFan** [comment]
> that works for entirely new files, but what about modifications to a file?

Modification of a copyright work creates a "derivative work", and the rights to the mods belong to the modifier, with the original author retaining the rights to the base work.  If you create substantial changes to a file, you should add an additional entry in the copyright notice, as 
copyright 2010 Werner
copyright 2015 Yorik
copyright 2020 Wandererfan

Technically, the additional entries should describe the modifications, but we have the git history for that.

So you could assign the rights to your modifications to the FPA.

**Pull request merged**
