### PR TITLE
Allow progress meter to finish. http instead of https for github.com

### PR DESCRIPTION
**Pull request by sgrogan**
This is only a partial solution as the commits are still not loaded on the StartPage but at least the progress meter doesn't hang. I tried allowing FreeCAD through the firewall and disable the firewall with no difference.

### CODE REVIEW

**Comment by ianrrees** [comment]
I haven't followed this issue in the forum, but just wanted to mention that MacOS 10.11 won't let applications fetch data over HTTP unless there's some security setting changed in one of the application bundle's plist (perhaps we're already using that setting in FreeCAD).  So, it seems that as far as Apple is concerned, HTTPS is the way to go moving forward.  Sorry I can't remember details right now, but could look in to this more in a few days.

**Comment by wwmayer** [comment]
Does this issue then only happen on systems (only Windows?) where Python is built without https support, i.e. the _ssl.pyd module is missing?

**Comment by wwmayer** [comment]
Ah, no it's not related to Python but Qt. Actually it only happens when Qt was built without OpenSSL support so that the https protocol is not supported. The only proper solution is to rebuild Qt with ssl support., therefore I think it's sufficient to rebuild the QtNetwork module.

**Comment by sgrogan** [comment]
Thanks for the info. I'll see what I can due with the QtNetwork module.

**Pull request closed without merging**
