### PR TITLE
[Spreadsheet] Prevent infinite loop when copy/paste of non-rectangula…

### PR DESCRIPTION
**Pull request by mwganson**
…r selection

https://forum.freecadweb.org/viewtopic.php?f=3&t=62207&start=10

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by chennes** [comment]
Isn't this equivalent to removing the single calls to `range.next()` and shifting them into the while loop?
```
while(range.next() && src!=*range) {
```

**Comment by 0penBrain** [comment]
@mwganson Indeed that would not be the same. Could you add the curly braces for the 'else' statement ? Despite the indentation, I find it hard to read. ;)

**Comment by chennes** [comment]
> Could you add the curly braces for the 'else' statement ? Despite the indentation, I find it hard to read. ;)

Oh good grief, you're right, I was reading it completely wrong! +1 on the curly braces.

**Comment by mwganson** [comment]
I don't think it is good practice to mix this usage in the same document.  I personally prefer using the curly braces in all cases, but if the previous code doesn't use them then I don't.

**Comment by chennes** [comment]
IMO the ultimate criteria is to write the clearest code possible -- "style" should be secondary. That said, I'm happy to merge as-is and then add the curlies in a separate commit so that later readers know who to blame for the style faux pas 😄. No sense holding things up over this.

**Comment by mwganson** [comment]
There was a forum discussion on this, but I don't have a link to it.  It was generally agreed not to mix them on the same page or at least not in the same block.  Consider adding the curly braces everywhere if they are to be added anywhere, or at least at a minimum for code in the same function/method.

**Comment by chennes** [comment]
https://wiki.qt.io/Qt_Coding_Style is often suggested: in this particular case, by my read it recommends (but does not require) adding the curly braces to the "else if", since the "if" has them. Then again, it also supports the `} else if () {` on a single line, which we typically don't do. YMMV...

**Comment by donovaly** [comment]
I think this should be backported to FC 0.19 since this fixes a crash. I've put it now to our list: https://forum.freecadweb.org/viewtopic.php?f=10&t=57659

**Pull request merged**
