### PR TITLE
AddonManager: add icon for the Cfd module in addon manager

### PR DESCRIPTION
**Pull request by qingfengxia**
A very simple PR, add icon for my Cfd module in Addon Manager

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
This icon looks like it was created with Inkscape 0.91. In this version of the program the pixel density is 90 dots per inch. However, starting from Inkscape 0.92 the resolution is 96 dots per inch, as this complies with newer Internet standards.

I attach your same icon converted to 96 dpi. This conversion is automatic, I just opened it with Inkscape 0.92 and it asked me to convert it, so the file should be the same. So take this icon, commit and push again.

[CFD.zip](https://github.com/FreeCAD/FreeCAD/files/4079488/CFD.zip)

**Comment by qingfengxia** [comment]
thank you will do next monday,nice weekend



Sent from my Mi phone
On vocx-fc <notifications@github.com>, Jan 17, 2020 22:57 wrote:

This icon looks like it was created with Inkscape 0.91. In this version of the program the pixel density is 90 dots per inch. However, starting from Inkscape 0.92 the resolution is 96 dots per inch, as this complies with newer Internet standards.

I attach your same icon converted to 96 dpi. This conversion is automatic, I just opened it with Inkscape 0.92 and it asked me to convert it, so the file should be the same. So take this icon, commit and push again.

CFD.zip<https://github.com/FreeCAD/FreeCAD/files/4079488/CFD.zip>

**Comment by vocx-fc** [comment]
Okay. Just a suggestion. I'm not saying the icon is bad, but it looks a bit plain. I would not add the text. I think a more colorful icon would look better. If you need help, post in the UI/UX subforum for help creating a nice icon. See also [Artwork Guidelines](https://www.freecadweb.org/wiki/Artwork_Guidelines).

**Comment by qingfengxia** [comment]
I will send another PR, thank you

**Comment by vocx-fc** [comment]
Just for reference. You don't need to close this pull request and open a new pull request, you can just update the icon in this pull request, squash, and then force push.

**Pull request closed without merging**
