### PR TITLE
Remove 2 deprecated PyCFunction

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7167">pipeline status</a> for feature branch [PR_7167](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7167). Pipeline [585323599](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/585323599) was triggered at [bb9cc12](https://github.com/FreeCAD/FreeCAD/pull/7167/commits/bb9cc1220d782a5be0eb191c92f1ea8a154a3043). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@chennes , this looks correct to me, but can you please have a look too? Please merge if OK for you as well.

**Comment by luzpaz** [comment]
Eventually we should make some sort of list (or bot trigger) that lists what parts of the python (or cpp) API we've deprecated. Then we can display such list in the Changelog.

**Comment by chennes** [comment]
How long ago were these deprecated? Have we given Addon developers sufficient notice that they shouldn't be using them anymore?

**Comment by donovaly** [comment]
> How long ago were these deprecated? Have we given Addon developers sufficient notice that they shouldn't be using them anymore?

Looking at the log it is marked deprecated since more than 6 years now.
Also I think better do these changes now in master. Active addons still using these functions have then plenty of time react before the next release..

**Comment by donovaly** [comment]
After such a long time of deprecation, it is time to make a move -> merging

I listed them in the release notes: https://wiki.freecadweb.org/Release_notes_1.0#Removed_Python_API

**Pull request merged**
