### PR TITLE
FEM: improvement in unittest  and Fenics mesh

### PR DESCRIPTION
**Pull request by berndhahnebach**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

- make some improvements to FEM unit tests. It's much more easier to add new tests. I'd like to add some more ...
- improvements to Fenics import 
- small fixes and code formating

cheers bernd

### CODE REVIEW

**Comment by berndhahnebach** [comment]
Mhh I had a look at the problem, but I can not find the culprit ... just checked again on my local machin a debian jessie. The tests run fine from command line (suggested command on every PR) and from UnitTest workbench. 

Does anyone has an idea?

cheers bernd

**Comment by PrzemoF** [comment]
Looks like file location problem after FreeCAD is installed. It works on your PC because the files are already somewhere else?

**Comment by berndhahnebach** [comment]
>  after FreeCAD is installed

thats the point I did not install it. If I install FreeCAD I can confirm the problem. Still I do not know yet how to solve it but I can at least reproduce it. 

Seams I do not need to hurry, there are nearly 20 PRs, FreeCAD is growing, and growing and growing. Where do I buy FreeCAD shares ?

**Comment by berndhahnebach** [comment]
I solved it the easy way ... I just deleted the problem commit for now. I will try to tackle it down and include it in one of my next PR. Means this could be merged from my point of view.

bernd

**Comment by berndhahnebach** [comment]
Damn, failing again ... but on Windows. I do not compile on windows and do not understand the AppVeyor output. Is there someone out there who could point me to the reason why AppVeyor  failed?

cheers bernd

**Comment by bblacey** [comment]
It looks like the 64-bit Windows build failed because it exceeded the allotted 60 minutes of build time.  @sgrogan or @saso are the best guys to advise on AppVeyor but given that the 32-bit Windows passed, perhaps @wwmayer will test locally and merge.  

@sgrogan, has anyone graveled with the AppVeyor team to allot FreeCAD more build time?

**Comment by luzpaz** [comment]
@berndhahnebach FYI don't mean to be nit picky but the PR title has a typo in it:
Should be Fenics and not Fenincs ;)

**Comment by berndhahnebach** [comment]
Thanks for your answers, ok. 

BTW added another commit in the regard of https://forum.freecadweb.org/viewtopic.php?f=18&t=12212&p=175777#p175777

**Comment by yorikvanhavre** [comment]
merged

**Pull request closed without merging**
