### PR TITLE
rebase removed files

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by donovaly** [comment]
You also need to update the unit tests: https://github.com/FreeCAD/FreeCAD/actions/runs/4441102614/jobs/7795757611
The Draft tests fail.

**Comment by donovaly** [comment]
Can you please provide a proper description for the PR and the commit message?

**Comment by wwmayer** [comment]
It's not enough to simply remove the Python modules. You must also change the modules where they are included, i.e. Draft.py and DraftTools.py

However, the actual question is whether it's a good idea to do that because these modules might be used in client code.

@yorikvanhavre please have a look at this PR and decide how to proceed

**Comment by donovaly** [comment]
@mosfet80 , would you please communicate with us? I often asked you questions but you never write back, just do some actions. You work is very good, this is not the point, but the communication should be improved.
If you have problems with English, I can recommend DeepL: https://www.deepl.com/translator Its results are so good that you can just paste them here (This way I can for example participate on Italian-speaking forums, works well.)

**Comment by adrianinsaval** [comment]
> However, the actual question is whether it's a good idea to do that because these modules might be used in client code.

we don't provide drawing wb by default anymore, anyone still using it is better off using an old version of freecad

**Comment by luzpaz** [comment]
CC @Roy-043

**Comment by luzpaz** [comment]
@mosfet80 it really helps to name PRs better, can you please try to do so moving forward?

**Comment by Roy-043** [comment]
As @wwmayer already mentioned DraftTools.py has to be updated as well.

This line should be removed:
https://github.com/FreeCAD/FreeCAD/blob/0e64e76514b66262af636cb533e9a01445b98880/src/Mod/Draft/DraftTools.py#L187

I expect that is the cause of the CI issues.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8918">pipeline status</a> for feature branch [PR_8918](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8918). Pipeline [812838367](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/812838367) was triggered at [705da06](https://github.com/FreeCAD/FreeCAD/pull/8918/commits/705da0694f619de00b4dd81263a962a4678d0fd4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
bump

**Comment by Roy-043** [comment]
Note that there are still references to the Drawing WB in DXF related code. Will do that in a separate PR.

**Comment by Roy-043** [comment]
Also the Arch WB must be checked...

**Comment by Roy-043** [comment]
I don't understand why `CI / Ubuntu_22-04` fails here.

**Comment by chennes** [comment]
> I don't understand why `CI / Ubuntu_22-04` fails here.

Might just be a temporary fluke, I think I've seen that "invalid revision" error before. I just gave the job a kick to see if rerunning fixes it.

**Comment by wwmayer** [comment]
> RCC: Error in '/home/runner/work/FreeCAD/FreeCAD/src/Mod/Draft/Resources/Draft.qrc': Cannot find file 'icons/Draft_Drawing.svg'

Draft_Drawing.svg has been removed but it's still listed in the qrc file.

**Comment by Roy-043** [comment]
> Draft_Drawing.svg has been removed but it's still listed in the qrc file.

Thanks, I see the error now in the CI output. Before I was focusing on the last lines of the output.

**Pull request merged**
