### PR TITLE
[Bugfix] PartDesign: Fix sanity check on countersink angle

### PR DESCRIPTION
**Pull request by stefanklug**
As countersinkAngle is the value of HoleCutCountersinkAngle divided by two, the limit is only 90 degrees

@donovaly: Second tiny bugfix for https://forum.freecadweb.org/viewtopic.php?f=8&t=72404

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7627">pipeline status</a> for feature branch [PR_7627](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7627). Pipeline [673899255](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/673899255) was triggered at [1619a15](https://github.com/FreeCAD/FreeCAD/pull/7627/commits/1619a15d03be54d7b6e0d0de162a510c071ff3f5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> As countersinkAngle is the value of HoleCutCountersinkAngle divided by two, the limit is only 90 degrees

Thanks for the PR.
However, I cannot reproduce the bug. Do you have a recipe for me to reproduce please?

Here is a hole with a custom angle of 120°:
[hole-test.zip](https://github.com/FreeCAD/FreeCAD/files/9844529/hole-test.zip)

It looks correct. Since it is a custom hole, it must not follow the norm which all define 90° as angle. I can also not use an invalid angle of >=180°, neither in the dialog nor in the property editor.

**Comment by stefanklug** [comment]
To be honest, I never saw the error message "Hole error: Invalid countersink angle" and have no Idea how to force it. 
In FreeCAD 0.19 I'm able to set invalid values using the python console. But in 0.20 the angle gets clamped to 179.999°.

The thought for my patch was that:
If it somehow is possible to set HoleCutCountersinkAngle to > 180° this error should appear. But two lines above there is
`countersinkAngle = HoleCutCountersinkAngle.getValue() / 2.0`
So the error check should be for 90°

I just stumbled upon this when I tried to hardcode countersinkAngle = 180° for the counterbore case and found out that I had to set it to 90°.

Nevermind, feel free to reject the change. It is not necessary for the other PR to work.

**Comment by donovaly** [comment]
> If it somehow is possible to set HoleCutCountersinkAngle to > 180° this error should appear. But two lines above there is
countersinkAngle = HoleCutCountersinkAngle.getValue() / 2.0

Good catch.
We can now to either merge this PR or kick out the error since it is already assured that angles >= 180° cannot be entered, even not by a Python script.
I would do the latter. What is your opinion?

> In FreeCAD 0.19 I'm able...

There was much work done for 0.20, therefore only 0.20 is our development base.

**Comment by stefanklug** [comment]
In that case, I'd suggest to drop this PR. 
I can drop the sanity check in the counterdrill PR.

**Comment by donovaly** [comment]
> In that case, I'd suggest to drop this PR. I can drop the sanity check in the counterdrill PR.

Please make a separate PR for this. We have already the problem that new feature PRs also make other changes. Therefore we try now harder to separate feature additions from improvements, bugfixes, feature removals etc.

**Comment by donovaly** [comment]
Closing this PR as discussed in favor of a PR that removed the error check.

**Pull request closed without merging**
