### PR TITLE
[PATH] solver proof v-bit tooltip

### PR DESCRIPTION
**Pull request by J-Dunn**
This fcstd uses small, fixed additions to the propertyBag values used in the sketch constraints to ensure that the solver does not barf when user enters zero tip diam or cutting edge height. It also removes unnecessary construction geometry, simplifying the sketch. 
https://forum.freecadweb.org/viewtopic.php?f=15&t=54880&p=479739#p479739

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by hyarion** [comment]
@J-Dunn the PR doesn't seem to contain any changes. The only commit contains 0 changed lines in 0 files.
Did you forget to include your changes maybe?

**Comment by J-Dunn** [comment]
Thanks. you had me worried. There are no files modified but one file is replaced: see commits(1). 
In my repo:
_This branch is 1 commit ahead, 18 commits behind FreeCAD:master._

**Comment by hyarion** [comment]
I do see one commit, but it doesn't show any changes either *in* files or changes *of* files. It's just a commit message.. without diff.

If files are moved or replaced it shows up both in github's "Files changed" tab and in the commit with the change, but in this case these are empty.
I've also fetched your branch to my computer and it looks the same for me locally, in both gitk and on the command line - no content, just a commit message.

**Comment by J-Dunn** [comment]
I'll have to look into this again. Maybe something did not work with the file upload and I didn't notice. Thanks for the heads up.

**Comment by sliptonic** [comment]
No changes in the PR since mid february.  PR contains no changes.  Closing.  Please resubmit if there's legit intended changes.

**Pull request closed without merging**
