### PR TITLE
[Draft] add font path relative

### PR DESCRIPTION
**Pull request by fra589**
Permit a font file path relative to the FreeCAD file for the shapestring object.

In reply to the issue #5746

Enter a font filename which begin with a './' or '../', then the font file will be relative to the FreeCAD model file.
For example enter "./LiberationSans-Regular.ttf" and copy the font file to the FreeCAD file directory, it will work like this on any computer.

### CODE REVIEW

**Comment by Roy-043** [comment]
My explanation (https://github.com/FreeCAD/FreeCAD/issues/5746#issuecomment-2468487993) about using `filename =` was perhaps a bit too cryptic. What I meant was:
```python
            if obj.FontFile[0] == ".":
                # FontFile path relative to the FreeCAD file directory.
                filename = os.path.join(os.path.dirname(obj.Document.FileName), obj.FontFile)
            else:
                filename = obj.FontFile
```
This is a little more efficient. You only have to use `os.path.join` once and can just use `filename` 3x in the rest of the code.

Note: we use 4 spaces for each indentation level.

**Comment by fra589** [comment]
Pull request updated based on your [latest comment](https://github.com/FreeCAD/FreeCAD/pull/17819#issuecomment-2471467538)

**Comment by Roy-043** [comment]
Thanks for this PR. It is a welcome addition to the Draft code.

**Comment by rubienr** [comment]
Unfortunately it does not work:

image
left: FreeCad, right: bash showing project structure
 <br />
 <br />

**Version**

OS: Ubuntu 25.04 (KDE/plasmax11/xcb)
Architecture: x86_64
Version: 1.0.0.
Build type: Release
Python 3.13.2, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * ExplodedAssembly
  * FreeGrid 2.2.0
  * FusedFilamentDesign 0.25.220
  * Manipulator 1.6.0
  * STEMFIE 0.3.1
  * SvgWorkbench 1.0.0.dev6
  * fasteners 0.5.38
  * freecad.gears 1.3.0

**Comment by luzpaz** [comment]
~lets re-open https://github.com/FreeCAD/FreeCAD/issues/5746~

~Can you comment on there please ?~

Edit: lets open a regression bug instead.

**Comment by fra589** [comment]
Hi @rubienr,

The pull request have only be merged in the v1.1 dev branch.
The 1.0 branch haven't this patch, so, it's normal the relative font patch doesn't work on it.

@luzpaz, perhaps will it be interesting to also merge this in the 1.0 branch?
But I'm not Git fluently enough to do it...

@++;
Gauthier.

**Comment by Roy-043** [comment]
This is a feature, not a bug fix. It should therefore not be backported.

**Pull request merged**
