### PR TITLE
Path: 3D Surface fix to apply `CutMode` when `CutPattern = Offset`; and LGTM cleanup

### PR DESCRIPTION
**Pull request by Russ4262**
Issue reported in forum at, [Re: Separate 3D Surface and Waterline (new feature) [Merged]](https://forum.freecadweb.org/viewtopic.php?f=15&t=44473&p=441615#p412303)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Review by sliptonic — COMMENTED** [review]
There's a few more minor cleanups that can be addressed here too.

35 col 1| F401 'Path' imported but unused
1322 col 17| F841 local variable 'closedGap' is assigned to but never used
1423 col 17| F841 local variable 'closedGap' is assigned to but never used
1654 col 25| F841 local variable 'closedGap' is assigned to but never used
1921 col 21| F841 local variable 'noMatch' is assigned to but never used
2081 col 21| F841 local variable 'lastLoop' is assigned to but never used

**Comment by sliptonic** [comment]
Passing variables by reference and modifying them in the function like that is ugly.  It makes the code more brittle and hard to understand.  Since the function is only receiving the argument so it can return it, why not just modify the functions to return the closedGap variable and then modify the calling functions to use it?  like:

data, closedGap = pathGeomToCircularPointSet(obj, compGeoShp, cutClimb, toolDiam, gaps, COM)

This has the added advantage of removing one argument you have to pass in.

**Comment by Russ4262** [comment]
@sliptonic 
Went with an alternate solution for the `closedGap` variable issue.  During the fix, I found two additional problems related to circular `CutPattern` usage.  One was a cut direction reversal that I fixed in this PR. 

The second problem is more complex and I have not found where the error is occurring.  It was pre-existing to the fixes in this PR.  The cut order of the arcs is incorrect with certain settings when using the circular cut pattern.  I don't have any clues or solutions yet.  It will likely be a separate PR when I get time.

Thanks for reviewing, Sir.

**Comment by Russ4262** [comment]
@sliptonic 
Found solution for second issue mentioned above: arc order error.  Fixed with a sort algorithm.  Should be good in good order per the focus of this PR.

**Pull request merged**
