### PR TITLE
Draft: Fix near snap (issue #6613)

### PR DESCRIPTION
**Pull request by Roy-043**
This PR fixes the inaccuracy of [Draft Snap Near](https://wiki.freecadweb.org/Draft_Snap_Near).

Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=67289

Issue:
https://github.com/FreeCAD/FreeCAD/issues/6613

Additionally:
* Snap Perpendicular now also works for faces.
* Snap Perpendicular can now find multiple points. For example two points on a circular edge.
* For clarity the `snapToFace` function was renamed to `snapToCenterFace`.
* To snap to a vertex (f.e. a [Draft Point](https://wiki.freecadweb.org/Draft_Point)) Snap Endpoint must now be used. This makes more sense IMO and is also consistent with snapping to points in a point cloud.

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

---

### CODE REVIEW

**Comment by Roy-043** [comment]
It is possible to snap to the edge of a face by just making sure it is highlighted. In rare cases the user can the [DrawStyle](https://wiki.freecadweb.org/Std_DrawStyle), although using Wireframe can be confusing in a crowded scene.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7132">pipeline status</a> for feature branch [PR_7132](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7132). Pipeline [579744256](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/579744256) was triggered at [e6e2104](https://github.com/FreeCAD/FreeCAD/pull/7132/commits/e6e210467e5026279189830cdc8f4f7e36df4b7b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Okay just tested, alll works fine and it seems like the problem is solved! Thanks @Roy-043 !

**Comment by yorikvanhavre** [comment]
(BTW you can write "issue #XXXX" in your commit message to auto relate it to an issue, or "fixes #XXXX" to autoclose related issues)

**Pull request merged**
