### PR TITLE
CI: allow manual launch of CI

### PR DESCRIPTION
**Pull request by 0penBrain**
This PR allows manual launch of CI workflow.
This allows any contributor working on its fork to manually launch the CI workflow at any time during development without need to do a PR.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7500">pipeline status</a> for feature branch [PR_7500](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7500). Pipeline [641467346](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/641467346) was triggered at [01cfeef](https://github.com/FreeCAD/FreeCAD/pull/7500/commits/01cfeef30576abc22220ee3a51989664481bcf7f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
How can a rebuild be triggered then? Where can we document this for dev to see ?

**Comment by luzpaz** [comment]
Thanks @adrianinsaval  
Lets document this somewhere and open a ticket to make it more streamlined then manually needing to click on it?

**Comment by 0penBrain** [comment]
> Where can we document this for dev to see ?

I planned to place a topic into the forum about this. No time yet.

> open a ticket to make it more streamlined then manually needing to click on it?

What would you expect instead of the manual launch ? I just did it so the possibility is offered to contributor to have a "pre-run" of CI before submitting PR. The API to launch is somewhere in the code of my old PR about CI if it can help. ;)

**Comment by adrianinsaval** [comment]
You can also do a PR against your own repo or push to one of the defined branches, we could add a generic "development" or "CI" branch or the developer can also just add his own branch in his fork so that it runs anytime they push. I don't remember if it was necessary to first enable actions in your repo or if it works out of the box.
Anyways, I think manually clicking is fine for this usecase, you mostly only want automation for PRs and we already have that.

**Comment by 0penBrain** [comment]
The actions will work as soon as placed in the default branch of the repo.
Another way to trigger for a contributor is indeed to create a PR against its own master. But IMO not easier than 2 or 3 clicks. :)
We could also add some triggering rule such as all branches named "contrib_*" but then have to educate the user, etc...
Eventually add a script in the "Tools" to launch from the API, but I guess we'll encounter issue with an OS or another. And any developer should be able to write a one-liner running on his/her system. ;)

**Pull request merged**
