### PR TITLE
AddonManager cannot download anything if working dir is on ecryptfs (aka ubuntu's encrypted home)

### PR DESCRIPTION
**Pull request by SniperCZE**
This pull request fixes AddonManager to work with encrypted Ubuntu home dir with ecryptfs. Ecryptfs has internal limitation of path lenght to 140 characters only, but AddonManager respects only 260 chars limitation of normal filesystems.

### CODE REVIEW

**Comment by luzpaz** [comment]
Hi @SniperCZE can you explain to the uninformed how this circumvents the char limit ?

**Comment by SniperCZE** [comment]
AddonManager, when trying to download new workbench, generates filename with path to Images. When this generated path is longer than 260 chars, it is trunked to 260 chars. This behavior works perfectly on filesystems with path length limit of 260 or more. If this is used on ecryptfs (aka encrypted home on Ubuntu, with max lenght of 143 chars), open() will throw OSError exception. This patch handles OSError exception in this part of code and assume "if there is OSError, we should use shortes filename/path", so it cuts filepath to 140 chars and try to open that shorter version. It is not a perfect solution (this would be something like FS detection), but good enaugh.

**Comment by luzpaz** [comment]
Cool, follow-up question: so what would a truncated path look like? Would the addon (Workbench/macro) work if the paths have now changed ?

**Comment by SniperCZE** [comment]
Yep, it is fully working. Path for AddonManager includes prefix of working dir (on Ubuntu it is /home/user/.FreeCAD/AddonManager/Images) and some long string looking like workbenchNameabc158ffedd5496add549bb946... Working dir will probably never longer than 140 chars, so only that long string is truncated. I tried it on several workbenches and everything was working without any issue. When I looked into that long-name files, those are some svgs or jpegs.

**Comment by yorikvanhavre** [comment]
There are spaces/tabs mismatches in your code that render it both unreadable here on github and can cause errors when running. In FreeCAD code we use strictly 4-spaces for indentation (no tabs). Could you fix the code? Thanks!!

**Comment by yorikvanhavre** [comment]
Ok should be safe enough indeed. Better fix later would be to pinpoint the exception better than using an OSError (which could be issued for other causes)

**Pull request merged**
