### PR TITLE
First attempt at support for CSG text command

### PR DESCRIPTION
**Pull request by KeithSloan**

### CODE REVIEW

**Comment by PrzemoF** [comment]
You should not merge master into your branch. Use git rebase master first to have your commits on top of latest master. Ask on FreeCAD forum if you need more help and see my post here: http://forum.freecadweb.org/viewtopic.php?f=27&t=17336&p=136722&hilit=git+merge+core#p136665

**Comment by KeithSloan** [comment]
Przemo

Thanks

Have now done so

Keith

**Comment by yorikvanhavre** [comment]
@KeithSloan there are several problems in your pull request that make it impossible to merge, it included many commits that are already in master, and it also includes some files that shouldn't be there like .OpenSCAD2Dgeom.py.swp . If you want, I can pick your changes and add them manually. Otherwise, if you prefer take the opportunity to try to redo a clean pull request, just close this one and do a new one, as you prefer. Don't worry, once you get the hand on it it will seem easy, I swear ;)

**Comment by KeithSloan** [comment]
Hi Yorik

Think cleaning up is beyond me.

I tried again to do

git checkout master
git pull official master
git push

# My understanding is this should sync my version of FreeCAD with the 
official

git checkout textcmd
Got ride of swp files
git add ...
git commit -a
git push

# My understanding is the should fix my textcmd branch on my repository 
version of FreeCAD

git rebase master textcmd
git push

If I then got to online github, I don't seem to be able to create a new 
pull request

Keith

**Comment by KeithSloan** [comment]
Yorik

Okay worked out how to close and create a new pull request

Take a look at pull request 289 and let me know how I fix

Keith

**Pull request closed without merging**
