### PR TITLE
CMake - Windows: Add libpack dependency install support

### PR DESCRIPTION
**Pull request by Russ4262**
Add options to copy dependencies from libpack to build directories
Add option to create install commands for INSTALL project in FreeCAD solution
Add additional code comments for clarity
Cleaned up some indent inconsistencies

Discussion on FC forum at: [Windows Builders: Cmake build improvements](https://forum.freecadweb.org/viewtopic.php?f=4&t=36225)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by 7ofNine** [comment]
Sent from my BlackBerry 10 not so smartphone.                                                                                                                                                                                                                From: Russell JohnsonSent: Saturday, May 11, 2019 14:48To: FreeCAD/FreeCADReply To: FreeCAD/FreeCADCc: SubscribedSubject: [FreeCAD/FreeCAD] Windows: Add libpack dependency install support (#2160)Add options to copy dependencies from libpack to build directories
Add option to create install commands for INSTALL project in FreeCAD solution
Add additional code comments for clarity
Cleaned up some indent inconsistencies
Discussion at: Windows Builders: Cmake build improvements
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

 Branch rebased on latest master git pull --rebase upstream master
 Unit tests confirmed to pass by running ./bin/FreeCAD --run-test 0
 Commit message is well-written
 Commit message includes issue #<id> or fixes #<id> where <id> is the associated MantisBT issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.
Note: If you don't have wiki access, then please mention your contribution on the 0.19 Changelog Forum Thread.




You can view, comment on, or merge this pull request online at:
  https://github.com/FreeCAD/FreeCAD/pull/2160

Commit Summary

  Windows: Add libpack dependency install support


File Changes

  
    M
    CMakeLists.txt
    (145)
  


Patch Links:

  https://github.com/FreeCAD/FreeCAD/pull/2160.patch
  https://github.com/FreeCAD/FreeCAD/pull/2160.diff


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FreeCAD/FreeCAD/pull/2160",
"url": "https://github.com/FreeCAD/FreeCAD/pull/2160",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Russ4262** [comment]
@7ofNine 
I could not make out any clear message with that last "comment." Please try again, Sir.

**Comment by 7ofNine** [comment]
Sorry that was completely unintended and is not a comment. I don't even know how how I managed to do it. I deleted it. Sorry for the confusion

**Comment by Russ4262** [comment]
I would ask that our 'resident' CMake expert for Windows review this PR when they have time.
Thanks.
For those that compile from source on Linux or Mac, if you have time, please substitute this CMakeLists.txt file for the current in your FreeCAD source directory and verify it has no negative impact on your non-Windows build.
Thanks.

**Comment by Russ4262** [comment]
@yorikvanhavre Thank you Sir for the review request.

**Comment by wwmayer** [comment]
See my comments here: https://forum.freecadweb.org/viewtopic.php?f=4&t=36225&p=310250#p310250

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
