### PR TITLE
[Draft] Eliminate unused imports

### PR DESCRIPTION
**Pull request by chennes**
As is common in FreeCAD, Draft has two files whose sole purpose is to import the workbench -- the files do not, in general, use anything they have imported. Static analyzers such as Flake and LGTM complain about these imports, so this commit adds fake "use" of each of those imports. It also includes a comment to silence the Pylint warning about code that does nothing on those lines.

As an aside, I hate adding hundreds of lines of "code" to appease the analyzers here, so if there is another way to handle this I'd love to hear it.

---

- [X]  Your pull request is confined strictly to a single module.
- [X]  Small change
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [X]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  No tracker ticket

### CODE REVIEW

**Comment by hyarion** [comment]
I don't like how these files looks (not your fault). Maybe we could clean it up a bit and solve this in a cleaner way?

How about creating a helper function to preload modules and attributes and called that with a series of lists with strings instead?

The helper function could look something like this:
```python
from importlib import import_module
def preload(entries):
    for entry in entries:
        module = import_module(entry[0])
        for attr in entry[1]:
            getattr(module, attr)
```

And then call it this way:
```python
preload_modules([
    ['draftutils.utils', [
        'type_check', 'typecheck', 'get_param_type', 'getParamType', 'get_param', 'getParam', 'set_param',
        'setParam', 'precision', 'tolerance', 'epsilon'  # , ...
    ],['draftfunctions.svg', [
        'get_svg', 'getSVG'
    ]]
])
```
The code above hasn't been tested, but I think something like that should work :tm:

**Comment by chennes** [comment]
Since this would represent a fairly large departure from the norm, we should probably move the discussion to the forums:
https://forum.freecadweb.org/viewtopic.php?f=10&t=56311

**Comment by yorikvanhavre** [comment]
In any case, it's probably better to leave this discussion to after the 0.19 release is done and consumed...

**Comment by yorikvanhavre** [comment]
Marking as "on hold" while the discussion is on...

**Comment by chennes** [comment]
Following the forums discussion, I'm going to rework this PR to use an alternate strategy.

**Pull request closed without merging**
