### PR TITLE
[TechDraw] Adding ISO line option to LineFormat

### PR DESCRIPTION
**Pull request by benj5378**
https://github.com/FreeCAD/FreeCAD/issues/9230

### CODE REVIEW

**Comment by benj5378** [comment]
Is meant to add ISO line style option at some point... so far I just had to tweak and refactor some datamember handling, estimated takin 1-2 hours... I ended up using 12 hours on fixing very very weird bugs.

**Bug 1**
function 1:
```
m_brush.setStyle(x);  // previously m_fillStyleCurrent = x;
m_brush.setTexture(QPixmap());
```
paint function:
```
// previously m_brush.setStyle(m_fillStyleCurrent);
setBrush(m_brush);
paint();
```
After doing this change, that should do literally the same, the m_brush.style() literally changed from when I set it to it reaching the paint function. Being a QT noob, I had no idea that m_brush.setTexture() would indirectly also set the m_brush.style(); Like I used 6 hours straight trying to figure out what was going on before finding the bug... I don't get why `.setTexture()` was even set in the first place, it should never have been there.

**Bug 2**
parentClass::setFillStyle(Qt::BrushStyle style):
`m_brush.setStyle(style);`

childClass::function 1:
`m_brush.setStyle(Qt::SolidPattern);  // previously setFillStyle(Qt::SolidPattern);`

But after this change, the object wasn't solid anymore. But the change would literally calling the same function. WHAT WAS GOING ON?!?!? I learned gdb and set break points for function1 to see if m_brush.setStyle would be called again before painting... it showed nothing. I then set a breakpoint for m_brush.setStyle itself to see when it was called with the wrong value... I stepped through the scripts forever, and it showed no changes?!?!?!? WHAT WAS GOING ON

Okay, new plan, do a shit ton of console prints to figure out where it was changed... after a lot of going back and forth, I narrowed it down to this

```
childClass::paint (...) {
    print(m_brush.style());  // evaluates to Qt::SolidPattern
    parentClass::paint(...);  // last line of function
}

parentClass::paint (...) {
    print(m_brush.style());  // evaluates to Qt::NoPattern, LITERALLY LINE 1 OF THE FUNCTION!?!? WHAT IS GOING ON?!??!
    [...]
}
```

It should show, that the childClass had it's own declaration of `m_brush`, making `childClass.m_brush` and `parentClass.m_brush` referring to two seperate objects... after 6 hours of debugging. childClass would never even `m_brush`, so why was it redeclarated here? I had even checked in the start of the debugging process but missed it somehow.

This code is haunted. I paid with my soul to find these bugs. Never again.

image

**Comment by WandererFan** [comment]
"I don't get why .setTexture()"
IIRC, if a texture was previously set, you need to set a null pixmap as texture in order to use a non-textured fill.

**Comment by WandererFan** [comment]
I don't understand most of this what this PR is trying to accomplish.  There doesn't seem to be any relationship to ISO line option.

Why are you fixing "bugs" in working code?

**Comment by benj5378** [comment]
> IIRC, if a texture was previously set, you need to set a null pixmap as texture in order to use a non-textured fill.
Nope. Not setting a null pixmap is not needed for showing a solid color.

> There doesn't seem to be any relationship to ISO line option.
No, not currently. It's draft. Features upcoming.

> Why are you fixing "bugs" in working code?
Because of these very goofy things, that made it harder to make new features. Also, you requested that refactorings were done in connection with new features/bug fixes, to lower the reviews and testing needed.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9787">pipeline status</a> for feature branch [PR_9787](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9787). Pipeline [903566391](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903566391) was triggered at [4282e71](https://github.com/FreeCAD/FreeCAD/pull/9787/commits/4282e71f17b60550238edbff71e1f16c96fc03cc). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by benj5378** [comment]
Screenshot from 2023-07-05 20-02-01

**Comment by benj5378** [comment]
@WandererFan So finally got all the stuff working, now only saving the chosen line style is needed. But this means changing LineFormat and it might cause merge conflicts with #9499. When can we expect the 0.21 release to be over and move forward with the PR?

**Comment by WandererFan** [comment]
"When can we expect the 0.21 release to be over and move forward with both PRs?"

As I understand it, we are waiting on TopoNaming preliminary PRs to be merged.  

Release dashboard is here: https://github.com/orgs/FreeCAD/projects/4

**Comment by WandererFan** [comment]
Overtaken by events.

**Pull request closed without merging**
