### PR TITLE
FEM: Fix cxx typo and remove calculix from solvers tab in examples

### LINKED ISSUE #11057: [Problem] FEM Examples are unnecessarily duplicated as calculix and ccxtools
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FEM Examples grouped by the solver are unnecessarily duplicated as calculix and ccxtools while this is essentially the same:

examples

What's more, sometimes it's called "ccxtools" while sometimes it's called "cxxtools":

ccxtools

https://wiki.freecad.org/FEM_SolverCalculixCxxtools

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34667 (Git)
Build type: Release
Branch: main
Hash: af5b8714a8371162addb97dd25c29250fcecf7ad
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lyphrowny**
closes #11057 

- "calculix" was removed from the "solvers" tab in examples
image
- "cxx" typo was fixed in GUI, in a class name
image
- convert every "FEM_SolverCalculixCcxtools" and its variations to CamelCase: "FEM_SolverCalculiXCcxTools"

Needs recompilation to work

Compiled and tested on WIndows
`run FEM TestSolverCalculix tests` shows `Unknown or unsupported solver type: calculix. No solver object was created.`, which is expected, see https://github.com/FreeCAD/FreeCAD/blob/9099d7588491aed417a2796ec5cfa7cd98a48a88/src/Mod/Fem/femexamples/ccx_cantilever_base_edge.py#L77-L81

### CODE REVIEW

**Comment by chennes** [comment]
@FEA-eng and @marioalexis84 please review. Thanks!

**Comment by FEA-eng** [comment]
@chennes I compiled it, looks good. But I guess that the failing FEM tests can't be ignored and have to be updated, right?

**Comment by chennes** [comment]
Yes, that's right -- we can't merge failing tests, so they need to be changed to match the new expected output.

**Comment by lyphrowny** [comment]
@chennes I've updated the tests, could you please approve the CI workflow building?

**Comment by FEA-eng** [comment]
@lyphrowny Now the checks are failing due to this:

```
CMake Error at src/Mod/Fem/CMakeLists.txt:519 (ADD_CUSTOM_TARGET):
  Cannot find source file:

    D:/a/FreeCAD/FreeCAD/src/Mod/Fem/femtest/app/test_solver_calculix.py
```

So the FEM tests should be either updated (normally the best approach) or removed also from CMakeLists. @chennes Is the latter acceptable or is it always necessary to update the tests ?

**Comment by chennes** [comment]
It's hard to make a blanket statement about it: in general, you want to keep the tests unless your code change has somehow made the test in question unnecessary (such as when removing a feature, etc.).

**Comment by lyphrowny** [comment]
@FEA-eng To remove or to update ~~this is the question~~ is not a simple question in this case: most of the CalculiX testing is in the `test_solver_calculix` - 54 tests vs. 3 in `test_ccxtools`. So it's a good thing the build failed, otherwise we might've not noticed this

I'd like to keep `test_solver_calculix` removed, and to add the test cases from it to `test_ccxtools`

**Comment by FEA-eng** [comment]
> I'd like to keep `test_solver_calculix` removed, and to add the test cases from it to `test_ccxtools`

That seems to be the best approach after the removal of the "new framework" solver. Just another part of the clean-up. But keep in mind that you have to update CMakeLists too.

**Comment by FEA-eng** [comment]
The checks are still failing with:

```
CMake Error at src/Mod/Fem/CMakeLists.txt:519 (ADD_CUSTOM_TARGET):
  Cannot find source file:

    D:/a/FreeCAD/FreeCAD/src/Mod/Fem/femtest/app/test_solver_calculix.py
```

Maybe removing line 324:

`    femtest/app/test_solver_calculix.py`

from src/Mod/Fem/CMakeLists.txt would be sufficient. Then this could be merged.

**Comment by lyphrowny** [comment]
@FEA-eng sorry for taking so long to remove one line. I was planning to migrate the test cases from the removed `test_solver_calculix` to `test_ccxtools` but had to put it off because I suddenly got really busy

The reason I want such a migration is because `test_solver_calculix` did all the work on behalf of `test_ccxtools`, since they use the same solver internally. Try running `./bin/FreeCADCmd --run-test "test_ccxtools"` and `./bin/FreeCADCmd --run-test "test_solver_calculix"` (please, refer to [test_information.md](https://github.com/FreeCAD/FreeCAD/blob/5264d6cc1f6050720850d4c6e2bed505abe13dfb/src/Mod/Fem/femtest/test_information.md)) to compare at least the number of tests each of them has

We can merge this as it is and create an issue, that tests should be added to the `test_ccxtools`, what do you think? I believe, that's more than a fair compromise :)

**Comment by FEA-eng** [comment]
> @FEA-eng sorry for taking so long to remove one line. I was planning to migrate the test cases from the removed `test_solver_calculix` to `test_ccxtools` but had to put it off because I suddenly got really busy

Sure, there's no hurry.

> We can merge this as it is and create an issue, that tests should be added to the `test_ccxtools`, what do you think? I believe, that's more than a fair compromise :)

Yes, that seems to be the best way.

**Comment by lyphrowny** [comment]
@FEA-eng submitted an issue regarding the tests migration #12965
@chennes could you please start the workflow? Should be ok to merge

**Comment by lyphrowny** [comment]
Some of the tests are falling probably because of differences in `.gitmodules` (see https://github.com/FreeCAD/FreeCAD/commit/93d58802aab4aef89607e80112b420e591848321 and https://stackoverflow.com/a/76166387)
The changes introduced by this branch shouldn't be the cause of the tests failing

I could've rebased my branch on top of main, but that would've required the workflow restarting afterwards, which I believe would not happen with merging into main

**Comment by lyphrowny** [comment]
Yay, rebasing onto `main` (9 commits and force push) did indeed made the workflow not to fail

**Comment by yorikvanhavre** [comment]
@lyphrowny in your PR all the translated .ts files are changed. This is superfluous as they are regenerated automatically when we merge the crowdin translations. Do you mind removing them from your PR?

**Comment by lyphrowny** [comment]
@yorikvanhavre 
1. do I need to remove all the Fem_*.ts files? 
2. or just the translation lines (like [here](https://github.com/FreeCAD/FreeCAD/pull/12876/files#diff-f888f2052d60dee924900ce72361274aa8f32c73b7efe22593c69e646a419f78L825-R825) and [here](https://github.com/FreeCAD/FreeCAD/pull/12876/files#diff-cb4886fc47f1d6b06e8e49dce020b9edfaadccee329419e20f52560b6dc521e6L5737-R5737))? 
3. or do I need to remove all the *ts files?

If it's 1., then will the [fixed typo](https://github.com/FreeCAD/FreeCAD/pull/12876/files#diff-27582b6e8c4367332735c5f06eae3090de3aa1472e769db3496509f371353c74L5658-R5658) in the Fem.ts file be propogated to all the generated ones? If it's 3., then the typo won't be fixed

**Comment by lyphrowny** [comment]
Found some more occurences of `CalculiXccxTools` and changed them to `CalculiXCxxTools`; occurences of `Ccxtools` and changed to `CcxTools`
Removed all the *_*.ts files, except for Fem.ts, in which the typo was fixed

Rebased onto main, hence new commits and force push

**Comment by chennes** [comment]
I'm going to merge this, but for the record it is never necessary to change TS files, those are autogenerated by the translation process.

**Pull request merged**
