### PR TITLE
[For 0.19] BeamCut Toolpath

### PR DESCRIPTION
**Pull request by pauluzs**
Created new BeamCut Toolpath 
Quickly creates a Toolpath for Laser, Plasma or Waterjet Cutting
Has options for Offset and Tool Compensation
Located in the Engraving Group

Passes ./bin/FreeCAD  --run-test 0
Based on latest master

### CODE REVIEW

**Comment by luzpaz** [comment]
@pauluzs is there a specific forum discussion associated with this PR ?

**Comment by pauluzs** [comment]
> @pauluzs is there a specific forum discussion associated with this PR ?

Still typing , wait some minutes

**Comment by pauluzs** [comment]
@luzpaz 

https://forum.freecadweb.org/viewtopic.php?f=17&t=34790

**Comment by pauluzs** [comment]
Please Put on Hold
Doesn't work for python3 yet.
For the python 2 branch checkout https://github.com/pauluzs/FreeCAD/tree/beamcutPY2

**Comment by yorikvanhavre** [comment]
Scheduled for post-0.1 release

**Comment by pauluzs** [comment]
PR Closed as intended in the first please read https://forum.freecadweb.org/viewtopic.php?f=17&t=34790

**Pull request closed without merging**
