### PR TITLE
TechDraw: Fix drag&drop of views. Add auto-switch to techdraw on double click.

### LINKED ISSUE #12375: [Problem] TechDraw Move view should be done by drag and drop in the tree.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Move View tool should be removed and moving should be done by drag and drop in the tree.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #12379: [Problem] TechDraw : "Add view to clip group" should not be a tool.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

"Add/Remove view to clip group" should not be a tool. It should be done by drag and drop.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #13061: TechDraw: Double clicking on a page does not switch workbench to TechDraw
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In sketcher double clicking on a sketch changes the active workbench to sketcher.
Similarly double clicking on an assembly switch active workbench to assembly.
Double clicking a body opens PD.

For consistency we could have the same behavior when double clicking on a page, switch to techdraw.
Thoughts on this?

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
This PR address 3 low hanging fruits in techdraw : 
- Fixes #13061
In sketcher double clicking on a sketch changes the active workbench to sketcher.
Similarly double clicking on an assembly switch to assembly.
For consistency, I offer to implement the same behavior when double clicking on a page, switch to techdraw.

- Fixes #12375 :
Techdraw has a 'move view' tool that is pointless. Moving views should be done by drag and drop. It actually was supported before but got broken with the introduction of `canDropObjectEx

- Fixes #12379:
Remove add/remove from clip. It is now possible to drag and drop between page and clip groups. It is even possible to drag and drop between different pages pages/clip groups.
Remove the Clip toolbar as it now has a single entry, and put the clip button to the view toolbar.
image

@WandererFan

### CODE REVIEW

**Comment by WandererFan** [comment]
par moi, les trois semble bon.  j'ai demande mes power-users de dit quelque choise apropos clip group.

en anglais: LGTM

**Review by WandererFan — APPROVED** [review]

**Comment by maxwxyz** [comment]
ça marche pour moi aussi. J'ai dû faire appel à un traducteur parce que cela faisait trop longtemps depuis mes années d'école.

**Comment by WandererFan** [comment]
forum topic re clip groups: https://forum.freecad.org/viewtopic.php?t=86362

**Comment by PaddleStroke** [comment]
@WandererFan I don't see anything relevant preventing this merge. User1234 is describing a potential tool that 'add to clip group' could be. But : 
- The tool is not what he describe. Currently it's function is completely replaced by drag and drop.
- Second the tool that he describes is actually not clear and very vague.

If someone comes along and make a proper tool as user1234 mention, then put the tool back on the toolbar. For now the tool is completely useless and bad UI.

**Comment by WandererFan** [comment]
The wiki will need changes to reflect the move view and clip group changes.

**Comment by PaddleStroke** [comment]
I have updated the wiki

**Comment by FEA-eng** [comment]
I'm testing this in the newest weekly - trying to drag a view to a clip group but nothing happens. Am I doing something wrong?

drag to clip group

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36596 (Git)
Build type: Release
Branch: main
Hash: 380d452adb5da85f47543a316b6b533f84e829c7
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

**Comment by PaddleStroke** [comment]
@FEA-eng it's drag and drop in the tree, like you would for App::Part or Groups.

**Comment by FEA-eng** [comment]
> @FEA-eng it's drag and drop in the tree, like you would for App::Part or Groups.

Thanks, it's clear now. I will mention this in the documentation (especially in the release notes that I'm updating now).

**Pull request merged**
