### PR TITLE
fem: use time.process_time instead of removed time.clock()

### PR DESCRIPTION
**Pull request by looooo**
@berndhahnebach time.clock() is removed in python3.8.
https://forum.freecadweb.org/viewtopic.php?f=42&t=40625&p=345087#p359910

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
Is this backward compatible with Python 2.7.x 

With leads to the question do I still need to have a look for Python 2 compatibility in FreeCAD coding?

bernd

**Comment by berndhahnebach** [comment]
merged

**Comment by looooo** [comment]
I assumed it's python2 compatible but actually seems not to be.

**Comment by berndhahnebach** [comment]
> 
> With leads to the question do I still need to have a look for Python 2 compatibility in FreeCAD coding?
> 

The answer is easy. As long as travis for 2.7.x is active we need to be Python 2.7.x compatible. I am not on my computer right now.

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=10&p=361292#p361292

**Pull request merged**
