### PR TITLE
fix problem that too large splash image make dialog too large

### PR DESCRIPTION
**Pull request by donovaly**
avoid problem that too large splash image make the dialog too large as discussed here:
https://forum.freecadweb.org/viewtopic.php?f=3&t=34656&start=10#p291867

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
This change doesn't seem to work very well. Without the change the FreeCAD name and version is correctly shown inside the image but with the change this information is missing.

**Comment by donovaly** [comment]
> 
> 
> This change doesn't seem to work very well. Without the change the FreeCAD name and version is correctly shown inside the image but with the change this information is missing.

Yes, this is correct. The Qt dialogs are not designed to have objects overlapping (as a Qt developer once explained me), despite this is possible.
My patch is for the About dialog and it already states the version and that it is FreeCAD. Therefore it is not necessary to have this info again within the area of the image.

**Comment by donovaly** [comment]
I have apologize. I am no real developer and I therefore cannot say my patch is the best solution.
I only wanted to point out that I know that setting size policies make overlaps hard to achieve and that in the About dialog the overlap with the version and the image is not really necessary.

So if you reject the patch as not applicable, that's no problem for me.

**Comment by wwmayer** [comment]
IMO it's the wrong way to hard-code a fix limit inside the AboutDialog. Instead it should check the available space of the desktop and then let's say the image shouldn't occupy more than 50% in width and height. If the image exceeds the size than it should be resized to a smaller size.

FYI, FreeCAD implements many options for branding and the About dialog can look quite differently.

**Comment by donovaly** [comment]
> IMO it's the wrong way to hard-code a fix limit inside the AboutDialog. Instead it should check the available space of the desktop...

I don't understand that this must be so complicated. For every button, spacer etc. one hardcodes the size, no matter what the screen resolution is because Qt takes care for e.g. HiDPI.
Here we just have an about dialog that is there to display what the program is about. Thus I don't see why it must support an unscaled splash screen image. Scaling the image to a fixed maximal width or height is therefore acceptable. (Even if there is no splash image in the dialog it would be OK.)

**Comment by donovaly** [comment]
Closing since you have fixed it: commit 51b6a0952516110ab029ed60e857253db8ccd249

**Comment by wwmayer** [comment]
> I don't understand that this must be so complicated. For every button, spacer etc. one hardcodes the size, no matter what the screen resolution is because Qt takes care for e.g. HiDPI.

But the size that is set for a ui form is not necessarily the size that is used at runtime. If needed and if a correct layout is made Qt might make a widget larger.
And the actual problem with your suggestion is that it doesn't resize the image but it clips it. You just cannot easily see this with the example image given in the forum thread. The QLabel class has a property to scale the image to avoid the above problem but in most cases the image will have a different aspect ratio and thus might look weird.

Anyway, 51b6a0952 scales the image keeping its aspect ratio to the maximum allowed size.

**Pull request closed without merging**
