### PR TITLE
fix(PD): size should be enabled if profile is not none

### PR DESCRIPTION
**Pull request by alfrix**
ThreadSize can be enabled when Threaded and when not threaded(clearance hole)

### CODE REVIEW

**Comment by luzpaz** [comment]
Does this address any open preexisting PD tickets  ?

**Comment by alfrix** [comment]
> Does this address any open preexisting PD tickets ?

idk if it was reported already, jbaehr found this issue when reviewing #15744

**Comment by jbaehr** [comment]
Code looks good to me, though I haven't found time to actually test it yet.

It seems like the now fixed line was introduced with PR #16522, and that one was backported with commit 411b6cf. So I guess this fix should also get backported for a potential v1.0.1, right? @maxwxyz

**Comment by jbaehr** [comment]
I can confirm that the fix works as intended.
Thank you for the quick action.

**Comment by adrianinsaval** [comment]
backported as aaf2b6ed10720acce181e65420e3fad1ef9cee2c

**Comment by jbaehr** [comment]
> backported as aaf2b6e

the backport is actually commit 4edb2e3; I guess you still had the wrong one in your clipboard ;-)

**Comment by adrianinsaval** [comment]
Oh yeah that was another backport!

**Pull request merged**
