### PR TITLE
Cleanup repository root directory

### PR DESCRIPTION
**Pull request by Pesc0**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

I thought the root folder could be organized better, so i moved some files around. Nothing was deleted, all paths referencing said files have been updated. Builds fine just like before these changes. 

Since this is such a simple change i did not bother creating an issue or forum post, let me know if that's ok. Also, since this is my first pr, let me know if there's anything i can improve.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376">pipeline status</a> for feature branch [PR_8376](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376). Pipeline [769281817](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769281817) was triggered at [41a428c](https://github.com/FreeCAD/FreeCAD/pull/8376/commits/41a428c8ad4b8396b6a5aa9ca41ce7409073a99a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Pesc0** [comment]
Addressing your points:
- You are right: code of conduct and contributing are hidden away and very hard to find. I thought it was fine moving them since there are links pointing to them, and readme is the first thing you read anyway. I think readme could be updated to make the link stand out more, perhaps with a dedicated "contributing" section under "reporting issues". Or i can simply revert the change, that's fine too.
- Regarding the files under `tools/build/` i could not find any mention of them in the wiki pages, but perhaps i've missed something.
- I could not find anything regarding the fedora package, neither on the wiki or on google.

Also while reading the wiki i found [this page](https://wiki.freecad.org/Continuous_Integration) about CI which looks outdated. So i think `lgtm.yml` and `appveyor.yml` could be deleted as well. Is that correct?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376">pipeline status</a> for feature branch [PR_8376](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376). Pipeline [770258587](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770258587) was triggered at [f9fd563](https://github.com/FreeCAD/FreeCAD/pull/8376/commits/f9fd56370b0a37a5f767d355ce9a0464f24d8cde). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
Yes I think appveyor is not in use for a long time and I think lgtm went offline not too long ago
The fedora stuff I think is used for the copr repo, and maybe for the official fedora packages too, not sure, I'll PM the fedora guy in the forum for comment

About the docker stuff, the documentation on the wiki is already outdated pointing to obsolete resources so renaming is not a problem, I think some of the docker images are outdated anyways which is what I expected would happen when a PR for them was made

**Comment by Pesc0** [comment]
https://github.com/FreeCAD/FreeCAD/blob/master/BUILD_OSX.md

https://wiki.freecad.org/Compile_on_MacOS

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376">pipeline status</a> for feature branch [PR_8376](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376). Pipeline [770363050](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770363050) was triggered at [cbcd94c](https://github.com/FreeCAD/FreeCAD/pull/8376/commits/cbcd94cdacd2f220bc061b70d781666a900b7b69). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376">pipeline status</a> for feature branch [PR_8376](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376). Pipeline [771814883](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/771814883) was triggered at [1179f08](https://github.com/FreeCAD/FreeCAD/pull/8376/commits/1179f08bb9f6bdc1d35ed217f8b3288649685c58). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
@luzpaz who's in charge of the Docker stuff? Anyone else who needs to look at this before it goes in?

**Comment by chennes** [comment]
We probably shouldn't just sit on this forever -- my inclination is to merge and see if anyone starts shouting. Any objections, now is the time...

**Comment by Pesc0** [comment]
Sounds good to me, thank you Chris!

**Comment by adrianinsaval** [comment]
I suggest skipping the fedora stuff, the copr package maintainer had said he didn't have the time to look into it and the build was already broken in master too, I don't think giving him even more work would be very nice.

**Comment by chennes** [comment]
Seems reasonable. @Pesc0 can you roll back the Fedora changes and squash everything else?

**Comment by Pesc0** [comment]
I'm afraid i can't. I am away from home and will be for the next two weeks, possibly more. If its fine for you waiting that long I'll get to it eventually, it's just that this will sit here for a while.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376">pipeline status</a> for feature branch [PR_8376](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8376). Pipeline [782117062](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/782117062) was triggered at [2074545](https://github.com/FreeCAD/FreeCAD/pull/8376/commits/2074545fa0f41338e66937cc905b0635a8fbe4db). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Did you mean to close this? I think the rest of the changes are ready to go (I can squash on merge if you like).

**Comment by Pesc0** [comment]
No I did not mean to, I messed up. I made a new pr identical to this one

**Pull request closed without merging**
