### PR TITLE
fix for the FeatureLoft compile issue

### PR DESCRIPTION
**Pull request by MisterMakerNL**
https://forum.freecad.org/viewtopic.php?p=775565#p775565

### CODE REVIEW

**Comment by luzpaz** [comment]
@MisterMakerNL can you squash and `git commit --amend "PartDesign: fix for FeatureLoft compile issue" -m "https://forum.freecad.org/viewtopic.php?p=775565#p775565"` please? TIA

**Comment by MisterMakerNL** [comment]
@luzpaz 
image

**Comment by chennes** [comment]
Needs another -m `git commit --amend -m "PartDesign: fix for FeatureLoft compile issue" -m "https://forum.freecad.org/viewtopic.php?p=775565#p775565"`

**Comment by MisterMakerNL** [comment]
I did the thing.

**Comment by luzpaz** [comment]
Screenshot_20240811_194448

@chennes lol

**Pull request merged**
