### PR TITLE
BIM: fix Wiki links in BIM Tutorial

### PR DESCRIPTION
**Pull request by Roy-043**

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I'll have a quick test

**Review by yorikvanhavre — APPROVED** [review]
Ok everything seems good!

**Comment by Roy-043** [comment]
Backported to V1.0.1.

**Comment by Mafketel** [comment]
just adding extra error message that made me think it was another problem but it turned out to be this.

QTextBrowser: No document for /File:BIM_Tutorial_title.jpg

still fixed

**Pull request merged**
