### PR TITLE
Revert "[Core] (Partially?) Fix data loss on dir rename (#4996)"

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
This reverts commit 820e88f95b5c6d34da09d2152fc3aa3b268e7a95.

Commits from PR #4996 were squashed without saving the texts of individual
commits. Additionally, the single commit affects both `App` and `Gui` modules.

Separate PR's with changes in `App` and `Gui` to follow.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
TODO: If/when this is merged, make PRs for https://github.com/AjinkyaDahale/FreeCAD/tree/app-fix-data-loss-on-dir-rename and https://github.com/AjinkyaDahale/FreeCAD/tree/gui-fix-data-loss-on-dir-rename

**Comment by yorikvanhavre** [comment]
There is a file conflict.. Can you have a look @AjinkyaDahale ?
I don't understand the idea here, is there a probiem with the original PR that needs to be reverted? Or is it optional?

**Comment by chennes** [comment]
It's my fault - when I squashed the commits for merging I deleted part of the commit message.

**Comment by AjinkyaDahale** [comment]
> There is a file conflict.. Can you have a look @AjinkyaDahale ?

That would be because of https://github.com/FreeCAD/FreeCAD/commit/54700faad831ee0850d73e2830e08844db87922d which fixed a typo in a message. Guess its an indication to let it be as it is for now, or we can have more conflicts as we try to resolve one.

> I don't understand the idea here, is there a probiem with the original PR that needs to be reverted? Or is it optional?

The problem is just with the squashed message. I guess we could let sleeping dogs lie here, so to say. If in the future the commit shows up in a `git blame`, we'll have the PR and the comments around it to help (so long as github allows :D).

**Pull request closed without merging**
