### PR TITLE
App::Link: fix crash with Draft Array

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fix https://github.com/FreeCAD/FreeCAD/issues/16232

### CODE REVIEW

**Comment by furgo16** [comment]
This branch fixes the crash for me with the test file from #16247 and another file that previousy crashed.

Given that:
- The issue is understood and the fix is fairly contained
- The issue blocks users from working with files containing Draft arrays and there is no workaround

Would it be possible to merge this PR to be included in the upcoming 1.0 RC?

```
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38624 +1 (Git)
Build type: Unknown
Branch: core_link_crash
Hash: aaf70d775984ed88de35e46c815e618d737ed66f
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.8.1
```

**Comment by PaddleStroke** [comment]
@chennes small crash fix here

**Comment by furgo16** [comment]
Reading the announcement at https://forum.freecad.org/viewtopic.php?p=780093#p780093 does this need an additional PR to be included in 1.0?

**Comment by mdrost** [comment]
Hi, no crashes after applying this change.
The only issue is that I don't like missing curly brackets :P

**Comment by chennes** [comment]
Also added to releases/FreeCAD-1-0 via `git cherry-pick 858ae45`.

**Pull request merged**
