### PR TITLE
port to smesh 8.3

### PR DESCRIPTION
**Pull request by looooo**
This is the dirty diff to make FreeCAD work with external smesh:
https://github.com/LaughlinResearch/SMESH

The question is how to make this work for the internal- and external smesh...

### CODE REVIEW

**Comment by looooo** [comment]
any idea why this fails?
```
[ 74%] Linking CXX shared library ../../../../Mod/MeshPart/MeshPart.so
/usr/bin/ld: cannot find -lSMDS,
```

**Comment by hobbes1069** [comment]
On Fedora we use the smesh fork maintained by the OCE (OpenCascasde Community Edition) which does not currently provide cmake configuration files so requiring them broke the cmake config for me. I'll check to see if that's an option I can enable for the future.

**Comment by looooo** [comment]
@hobbes1069 
ah I see. I am trying to get https://github.com/LaughlinResearch/SMESH working with freecad.
The cmake-config is minimal: https://github.com/LaughlinResearch/SMESH/blob/master/cmake/SMESHConfig.cmake.in

**Comment by hobbes1069** [comment]
The last commit does not apply cleanly to 0.17... When I have time I'll see if it's a simple fix or not.

**Comment by looooo** [comment]
@hobbes1069 the last commit belongs to another project. I will move the commit to a sepperated PR...

**Comment by wwmayer** [comment]
Has anybody tried to successfully build smesh on Windows (VS2013)? I pulled the repo and there are a few things I had to fix to get it working:
* In the cmake file I had to add the SMESHTrace and TKernel libs for the Mefisto target
target_link_libraries(MEFISTO2 SMESHTrace TKernel)
* The type vtkMTimeType isn't defined on Windows either so I had to comment out the #ifndef WIN32/#endif in the file SMDS_UnstructuredGrid.hxx

Then I ran into a nasty boost linking issue. The system always wanted to link against libboost_filesystem-vc120-mt-gd-1_55.lib and libboost_system-vc120-mt-gd-1_55.lib but I have only these files without the lib prefix. So, in order to continue I renamed the files. But I have no idea where the issue comes from.

I only built the bare smesh without med and netgen support for now.

**Comment by wwmayer** [comment]
Found the answer here: https://cmake.org/pipermail/cmake/2008-July/022740.html

Another thing for MSVC is to have different file names for debug builds. To achieve this set(CMAKE_DEBUG_POSTFIX d) can be used.

So the two changes are:

if (MSVC)
    # find the shared boost libs
    add_definitions(-DBOOST_ALL_DYN_LINK)
    # set postfix for debug libs
    if(NOT CMAKE_DEBUG_POSTFIX)
        set(CMAKE_DEBUG_POSTFIX d)
    endif()
endif()

**Comment by wwmayer** [comment]
oops, close it by accident

**Comment by hobbes1069** [comment]
Tried using -DSMESH_VERSION_MAJOR=7 but looking at the build log SMESH_VERSION_MAJOR=5 snuck in there somewhere...

The only place it seems to be referenced is:
```
$ grep -r SMESH_VERSION_MAJOR
src/3rdParty/salomesmesh/CMakeLists.txt:SET(SMESH_VERSION_MAJOR 5)
```

But I'm removing that in %prep during build to use the system smesh...

Still getting the error:
```
BUILDSTDERR: In file included from /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:69:
BUILDSTDERR: /usr/include/smesh/NETGENPlugin_SimpleHypothesis_2D.hxx:50:36: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
BUILDSTDERR:    void SetNumberOfSegments(int nb) throw (SALOME_Exception);
BUILDSTDERR:                                     ^~~~~
BUILDSTDERR: /usr/include/smesh/NETGENPlugin_SimpleHypothesis_2D.hxx:60:45: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
BUILDSTDERR:    void SetLocalLength(double segmentLength) throw (SALOME_Exception);
BUILDSTDERR:                                              ^~~~~
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp: In member function 'Mesh::MeshObject* MeshPart::Mesher::createMesh() const':
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:327:37: error: 'get' is not a member of 'SMESH_Gen'
BUILDSTDERR:      SMESH_Gen* meshgen = SMESH_Gen::get();
BUILDSTDERR:                                      ^~~
```

**Comment by hobbes1069** [comment]
Found it, it wasn't in the sources but in your patch :) Probably should conditionalize that somehow.

**Comment by hobbes1069** [comment]
Ok, next error:

```
BUILDSTDERR: CMakeFiles/MeshPart.dir/Mesher.cpp.o: In function `MeshPart::Mesher::createMesh() const':
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:342: undefined reference to `NETGENPlugin_Hypothesis_2D::NETGENPlugin_Hypothesis_2D(int, int, SMESH_Gen*)'
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:357: undefined reference to `NETGENPlugin_Hypothesis_2D::SetQuadAllowed(bool)'
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:358: undefined reference to `NETGENPlugin_Hypothesis::SetOptimize(bool)'
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:359: undefined reference to `NETGENPlugin_Hypothesis::SetSecondOrder(bool)'
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:362: undefined reference to `NETGENPlugin_NETGEN_2D::NETGENPlugin_NETGEN_2D(int, int, SMESH_Gen*)'
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:345: undefined reference to `NETGENPlugin_Hypothesis::SetFineness(NETGENPlugin_Hypothesis::Fineness)'
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:354: undefined reference to `NETGENPlugin_Hypothesis::SetNbSegPerRadius(double)'
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:352: undefined reference to `NETGENPlugin_Hypothesis::SetNbSegPerEdge(double)'
BUILDSTDERR: /builddir/build/BUILD/FreeCAD-0.17/src/Mod/MeshPart/App/Mesher.cpp:350: undefined reference to `NETGENPlugin_Hypothesis::SetGrowthRate(double)'
BUILDSTDERR: collect2: error: ld returned 1 exit status
```

I'm using Netgen Mesher 6.2...

**Comment by wwmayer** [comment]
Here are a few things that should be fixed:
* The external smesh uses SMESH_INCLUDE_PATH but for the internal SMESH_INCLUDE_DIR is used which will then be empty. So the call of include_directories(${SMESH_INCLUDE_DIR}) has no effect.
Here it suffices to set SMESH_INCLUDE_DIR with set (SMESH_INCLUDE_DIR ${SMESH_INCLUDE_PATH}).
We could think about changing the variable name to use that of the external smesh.

* To avoid to clutter all modules with too much stuff don't add the include path in the top-level cmake file. The modules that need smesh (Fem and MeshPart) already set the paths.

* add_definitions(-DHAVE_NETGEN) must be removed. netgen support is still handled by the BUILD_FEM_NETGEN option. I have intentionally built my external smesh without netgen support so the above define will cause a linking error.

* add_definitions(-DSMESH_VERSION_MAJOR=${SMESH_VERSION_MAJOR}) is quite inelegant and as said above clutters the vast majority of modules with unneeded defines. A nicer solution could be to create a file SMESHVersion.h.cmake and build SMESHVersion.h at configure time which contains major, minor and build version numbers.

@looooo If you like I can make the needed changes.

**Comment by wwmayer** [comment]
I have and improved the mentioned issues and will push them later today...

**Comment by wwmayer** [comment]
Merged.

**Comment by hobbes1069** [comment]
I went and pulled the commits as patches but something still isn't quite right... I can't use find_package(...) because my smesh doesn't provide a config file. Working on a patch to work around it, but which smesh libraries does FreeCAD actually care about?

**Comment by hobbes1069** [comment]
Still having issues, the new SMESH_Version.h uses the versioning from the bundled smesh...

**Comment by hobbes1069** [comment]
Until I get everything working I don't want to create a pull request but here's some cmake updates so the https://github.com/tpaviot/smesh fork of smesh, which doesn't provide a cmake config, can be found.

https://github.com/hobbes1069/FreeCAD_sf_master/commit/26d238b520e80581f4cda373f1ad91fe95120112

**Comment by looooo** [comment]
>@looooo If you like I can make the needed changes.

@wmayer 
sry, I had no access to a fc-build over the we...

thanks for cleaning and merging this PR. For conda, the current master is building fine with external smesh. Actually we can enable conda-builds again to test the external smesh with a ci. I guess @yorik can re-enable the circle-ci builds.

>Has anybody tried to successfully build smesh on Windows (VS2013)? I pulled the repo and there are a few things I had to fix to get it working

we build the smesh library for linux and windows (vs15). For this configuration we included all changes. But I guess some fixes for older configurations will be accepted. So either create a PR directly or place the diff in the FreeCAD-forum and I can have a look at it.

**Comment by hobbes1069** [comment]
Guys, is there anything to be done here? I really wanted to get FreeCAD 0.17 built for the Fedora 28 release but that's passed at this point. I can try for a bundling exception from the packaging committee but it could be denied.

**Comment by looooo** [comment]
Sry, we couldn't solve all problems for smesh8.3 yet. Older versions of smesh should work, but we can't test as nobody is currently running such a configuration. So if you want to use external smesh, feel free to open a topic on the FreeCAD forum and report your problems.

the findPackage for smesh shouldn't be mandatory any more. So maybe it's already working for you.

**Comment by hobbes1069** [comment]
I don't think it's a cmake config problem any more, more code related. I get different errors, but errors nonetheless whether I force SMESH_VERSION_MAJOR whether it's at 5 or 7...

**Comment by hobbes1069** [comment]
Ok, I think I'm getting closer but still don't have a solution... 

This is the part causing the issue... If I use SMESH_VERISON_MAJOR=7 it isn't compatible with the newer smesh, but if I use 5, it uses the "get" method which is a customization[1] of the bundled smesh that loos like it was done after 0.16 release. So either way it doesn't work for me.

https://github.com/FreeCAD/FreeCAD/blob/c36026358222da48a1a8ab3eec87a4a4a5166b7e/src/Mod/MeshPart/App/Mesher.cpp#L326-L332

[1] https://github.com/FreeCAD/FreeCAD/commit/55534e98d40ce477eb1bab3202b1514429c8ba29#diff-e0c93fb3fb937daa73dca9e1b7f55fd9

**Pull request closed without merging**
