### PR TITLE
Draft: fix regression draftlink.py

### PR DESCRIPTION
**Pull request by Roy-043**
This PR fixes a regression introduces with #5180.

See forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=64246

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by Roy-043** [comment]
Sorry for the two updates. I find that using `transformShape` is the solution that works in all reported cases. No need for `if shape.Placement == place`.

The reported cases:
https://forum.freecadweb.org/viewtopic.php?f=3&t=63591
https://forum.freecadweb.org/viewtopic.php?f=3&t=64246
https://forum.freecadweb.org/viewtopic.php?f=13&t=64259

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5220">pipeline status</a> for feature branch [PR_5220](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5220). Pipeline [423701038](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/423701038) was triggered at [4cd494b](https://github.com/FreeCAD/FreeCAD/pull/5220/commits/4cd494b917266eae0772d63261e030d254201a12). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
This final solution looks fine to me: I'd like to squash it to a single commit, though. I can do that while merging, or if you'd prefer control over the exact wording of the commit message, you can squash and force-push. Let me know which you'd prefer.

**Comment by Roy-043** [comment]
> I can do that while merging

Please do. I am still a Git noob and work mostly in the https://github.com browser interface. I do not see a 'Squash' feature/button there.

**Comment by chennes** [comment]
I don't think there's an easy way to do a squash on GitHub.com except when merging a PR: in my own work I use the command line for it (the command is actually part of an "interactive rebase" that lets you edit and rearrange commits and commit messages: it's very useful. A web interface to it would be pretty awesome!)

**Pull request merged**
