### PR TITLE
Fix various typos [skip-ci]

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell` v2.0.dev0
```
codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,ba,beginn,behaviour,bloaded,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,orgin,orginx,orginy,ot,pard,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/Mod/Robot/App/kdl_cp,./src/Mod/Import/App/SCL,./src/WindowsInstaller,./src/Doc/FreeCAD.uml
```

### CODE REVIEW

**Comment by luzpaz** [comment]
@carlopav care to double check 574f33d  
It looked like a harmless change (couldn't find any code that would be impacted by it)

**Comment by carlopav** [comment]
> It looked like a harmless change (couldn't find any code that would be impacted by it)

Yes, seems harmless to me too!

**Comment by luzpaz** [comment]
@carlopav do you mind green-lighting this PR as a reviewer ?

**Review by carlopav — APPROVED** [review]
ok to me!

**Comment by vocx-fc** [comment]
By the way, I don't think you need anything special to "review" pull requests. In the past, I remember reviewing pull requests whenever I wanted, even before Yorik added me to the "FreeCAD" group, so I really don't know if this membership changes anything in this aspect.

**Comment by carlopav** [comment]
I also think this doesn't change much :)

**Comment by luzpaz** [comment]
> By the way, I don't think you need anything special to "review" pull requests. In the past, I remember reviewing pull requests whenever I wanted, even before Yorik added me to the "FreeCAD" group, so I really don't know if this membership changes anything in this aspect.

@vocx-fc if anything <s>it gives a visual cue on the https://github.com/FreeCAD/FreeCAD/pulls page showing progress of the review process (besides the amount of replies the discussion generates)</s> 
...You're right. I was under the impression that maintainers could see the amount of reviews and if they were green or red. But maybe that was something I imagined? :confused:

**Comment by carlopav** [comment]
I think it's just on this page :)
immagine

**Comment by luzpaz** [comment]
I imaged it to look something like this... wishful thinking on my part? (or perhaps there is a browser extension that makes this possible? https://github.com/collections/github-browser-extensions ?? )

Github-PR-UI-FeatureRequest

**Comment by luzpaz** [comment]
@WandererFan do you mind merging this?

**Pull request merged**
