### PR TITLE
Core: escape filepath characters in FreeCAD.loadFile

### PR DESCRIPTION
**Pull request by bdieterm**
Currently, executing the Python command `FreeCAD.loadFile("/tmp/let's go.FCStd")` will fail because of the single quote sign in the path.

This pull request fixes the problem by properly escaping the special characters in the string.

The error was described in #10264 as happening when "opening from recent history". The root cause lies in function `FreeCAD.loadFile` and therefore the error also happens on FreeCAD version 0.20.2 when calling that function directly instead of via the history action.

### CODE REVIEW

**Comment by luzpaz** [comment]
Warrants a backport ?

**Comment by bdieterm** [comment]
I recommend a backport.

There is the possibility to run arbitrary Python code when someone opens your file a second time via the Start Page history, or when someone opens your file via `FreeCAD.loadFile`.

Example:

Create a FreeCAD file and give it this name:
`aa'+exec(bytes.fromhex('4775692e6765744d61696e57696e646f7728292e73657457696e646f775469746c652827434f44452045584543555445442729')))#'.FCStd`
This will execute `Gui.getMainWindow().setWindowTitle('CODE EXECUTED')`

**Comment by luzpaz** [comment]
@bdieterm please open a PR against `releases/FreeCAD-0-21` for backport

**Comment by luzpaz** [comment]
> There is the possibility to run arbitrary Python code when someone opens your file a second time via the Start Page history, or when someone opens your file via FreeCAD.loadFile.

How do you propose to avoid this ?

**Comment by bdieterm** [comment]
> How do you propose to avoid this ?

This PR is already the fix, so the code execution vulnerability does not exist anymore in FreeCAD:master.

**Pull request merged**
