### PR TITLE
Fix #4453: Error when trying to clear property by Link dialog

### PR DESCRIPTION
**Pull request by chennes**
When converting links to Python in DlgPropertyLink, an empty list was converted to None, rather than to []. This caused the value update to fail when there was no selection, e.g. when "Clear" was clicked.

### CODE REVIEW

**Comment by luzpaz** [comment]
Forum thread: https://forum.freecadweb.org/viewtopic.php?p=446610#p437445

**Comment by yorikvanhavre** [comment]
This change affects PropertyLink, not PropertyLinkList... I think PropertyLink accepts (or at least should accept) None as an argument. However, indeed I see the problem too with PropertyLinkList. Is this a mistake?
Perhaps would be handier to make PropertyLinkList accept None too, actually...

**Comment by chennes** [comment]
Sorry, I'm still learning the codebase here: given the test object in the bug report, `FreeCAD.getDocument('Unnamed').getObject('test').OperatesOn = None` 
gives me the error reported in the original bug report, 
`TypeError: type must be 'DocumentObject' or list of 'DocumentObject', not NoneType`. 

In the Python that creates that object, the code is:
`obj.addProperty("App::PropertyLinkListGlobal", "OperatesOn", "Relations", "")`

Can you explain to me what you mean by "This change affects PropertyLink, not PropertyLinkList"? The code I changed is in the dialog that opens when you try to edit the OperatesOn property in the GUI, so I don't understand what it means that it affects `PropertyLink` and not `PropertyLinkList`.

**Comment by chennes** [comment]
Making the following change to PropertyLinks.cpp will allow "None" as a possible value here, but I don't know if there are other consequences to returning a null pointer from that function. Before I add it to the PR, can someone more familiar with the situation sanity check it?
```
DocumentObject *PropertyLinkList::getPyValue(PyObject *item) const {
    // Potential additional condition:
    if (item == Py_None) {
        return nullptr;
    } 
// After this is the original code (with an "else" added)
else if (!PyObject_TypeCheck(item, &(DocumentObjectPy::Type))) {
        std::string error = std::string("type must be 'DocumentObject', 'NoneType', or list of 'DocumentObject', not ");
        error += item->ob_type->tp_name;
        throw Base::TypeError(error);
    }
    return static_cast<DocumentObjectPy*>(item)->getDocumentObjectPtr();
}
```

**Comment by yorikvanhavre** [comment]
Basically you have two base link property types (there are actually more than two, derived from these two), PropertyLink and PropertyLinkList. PropertyLink accepts just one object, while PropertyLinkList (and its derived like PropertyLinkListGlobal) accepts a single object or a list of objects. Currently the way to "empty" a PropertyLink is None, while for PropertyLinkList it's only by passing it an empty list. Both should also accept None as an argument I think. That would be convenient for python coders.

But looking better at your original code from the PR, it actually only changes the return value for lists, so it actually should be safe (sorry about the noise)... So if you prefer we can merge it as is, and we can take care of adding None as a valid argument later. In any case, I suppose your assumption is right, it should return a null pointer.

**Comment by chennes** [comment]
Thank you for the explanation. It seems to me that it is best to just fix it all at once, so I will modify the PR to include the change to `getPyValue()`.

**Comment by donovaly** [comment]
I guess @realthunder might be interested in this PR.

**Comment by wwmayer** [comment]
Yorik is right that None should be used to clear the list. While for a PropertyLinkList it's also valid to pass [] this won't work for a PropertyLink.

This means that your changes on `PropertyLinkList::getPyValue(PyObject *item)`  is exactly what we need. However, the change on `DlgPropertyLink::linksToPython`is bad and must be reverted. You can easily test it by slightly modifying the Python test script:

You you replace
```
obj.addProperty("App::PropertyLinkListGlobal", "OperatesOn", "Relations", "")
```
with
```
obj.addProperty("App::PropertyLinkGlobal", "OperatesOn", "Relations", "")
```
and follow the procedure to clear the link you will get this error message:
> <Exception> type must be 'DocumentObject' or 'NoneType', not list

**Comment by wwmayer** [comment]
Btw, no further action needed from your side. I will checkout the branch and make the needed changes.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
