### PR TITLE
Travis upgrade to GCC 10 and Clang 10

### PR DESCRIPTION
**Pull request by triplus**
Upgrade to latest and greatest toolchains.

### CODE REVIEW

**Comment by vocx-fc** [comment]
It generates way too many warnings and notes with Clang10, that the log doesn't show everything.

```
The job exceeded the maximum log length, and has been terminated.
```

**Comment by triplus** [comment]
Yep. Usually when touching the toolchain, you get to fix some unexpected issues.

P.S. Hopefully the latest set of changes will do.

**Comment by wwmayer** [comment]
The problem is that the majority of warnings is caused by 3rd party libraries -- mainly Eigen3. Is there a chance that these warnings are fixed in a newer Eigen3 version and if yes to update to this version?

**Comment by triplus** [comment]
I took a look and this is the current situation regarding Clang.

> -Wextra now enables -Wdeprecated-copy. The warning deprecates move and copy constructors in classes where an explicit destructor is declared. This is for compatibility with GCC 9, and forward looking for a change that’s being considered for C++23. You can disable it with -Wno-deprecated-copy.

https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html

And as for Eigen, currently Clang 10 warnings are not addressed yet, and currently they are suppressing such warnings, when it comes to GCC 9+:

```
#if defined(__GNUC__) && (__GNUC__ >=9)
  #pragma GCC diagnostic ignored "-Wdeprecated-copy"
#endif
```

https://gitlab.com/libeigen/eigen/-/issues/1788

All in all i feel that it makes the most sense to suppress such warnings for Clang 10, for now. If somebody would introduce such warning in FreeCAD code, GCC should still be able to detect it.

**Comment by triplus** [comment]
Actually i now read Clang tends to pretend to be __GNUC__, hence the above approach, used on Eigen side, might suppress such warnings for Clang 10 too. As the changes were backported to Ubuntu 20.04 i will create an additional commit latter today and lets see how that goes.

**Comment by triplus** [comment]
Yes, that did it. Now therefore the latest version of Eigen with patches is being used and -Wdeprecated-copy warning being suppressed on Eigen side.

P.S. I see that now some 3rd party libraries, such as KDL, produces a few of them. If there is desire to suppress them globally, i can reintroduce the flag. If not this is i guess it.

**Comment by yorikvanhavre** [comment]
In any case it doesn't make much sense to print warnings in an automatic CI build probably... Nobody will use that to fix warnings
Let's merge this one already, if needed I guess we can remove warnings further later on

**Comment by triplus** [comment]
Thanks for merging.

Note that Werner usually fixes such warnings, and i suspect he occasionally checks the Travis logs too. That is one of the main motivations on my side, to upgrade the toolchains. As you get some head start and in release notes, there is usually a lot of talk about improved code diagnostics.

Just seen:

https://github.com/FreeCAD/FreeCAD/commit/300e887480fa8e5ddbaa02ca4aec4ebf92095c08
https://github.com/FreeCAD/FreeCAD/commit/078432af459afd2426e44cf5e6422cf91c55d2d7
https://github.com/FreeCAD/FreeCAD/commit/3233dc1f47aa6748552c5d5f2fe3ec17c9e4c393

**Pull request merged**
