### PR TITLE
Dark Theme

### PR DESCRIPTION
**Pull request by sushanth7781**
This pull request introduces a new dark mode theme to FreeCAD, providing users with an alternative interface that is easier on the eyes, especially in low-light environments. The changes include the addition of a QSS file defining the dark theme styles and modifications to InitGui.py to apply the dark theme on startup.

Changes Include:
Dark Theme QSS File:

Path: data/themes/DarkTheme.qss
Content: Defines the styles for the dark theme, including background colors, text colors, and other UI elements.
Modifications to InitGui.py:

Path: src/Mod/Start/InitGui.py
Functionality: Adds a function to apply the dark theme by setting the stylesheet from the QSS file.

### CODE REVIEW

**Comment by maxwxyz** [comment]
I think additional themes should be in the FreeCAD Themes repository. FreeCAD will ship with Classic, FreeCAD Light and FreeCAD Dark themes.
There are some more open issues for the current themes, if your PR fixes some, please split it.
@MisterMakerNL FYI

**Comment by MisterMakerNL** [comment]
This is the beginning of AI generated spam:
afbeelding

**Comment by luzpaz** [comment]
Is this related to FOSSHack ? @yorikvanhavre @AjinkyaDahale  ?

**Comment by AjinkyaDahale** [comment]
> Is this related to FOSSHack ? @yorikvanhavre @AjinkyaDahale ?

Very likely, but this person has never contacted us about contributing earlier (as the rules stipulated).

Hopefully there are not too many of these. I'll have more to say about the whole event once we've gathered enough information.

**Comment by obelisk79** [comment]
There are several issues with this PR. It isn't clear in scope. It affects the interface and offers no screenshots to preview the effects. It doesn't appear to address overlay mode. It introduces an initgui.py, macro script, and unrelated markdown documents of dubious quality regarding their actual content.

I appreciate the effort, but this seems ill-planned and misplaced. Can this at least be marked as Draft status for now?

**Comment by chennes** [comment]
I'm actually just going to close it -- there's little point in keeping it open, the OP did not work with the Design Working Group at all, or reach out to any of the available mentors for the FOSSHACK program.

**Comment by MisterMakerNL** [comment]
The whole layout of the tutorials and the very basic/default qss file combined with a username with random digits screams AI generated.
Bit scary it was able to get thus far.

**Pull request closed without merging**
