### PR TITLE
Add a new DocumentObject class FemSolver to Fem module

### PR DESCRIPTION
**Pull request by qingfengxia**
Test passed, it contains some properties which can be used by any the specific external solver. 
It could avoid to new FemTools() instance each time for retrieving info about solver in the future. 
This new class does not affect existent code, so it is safe to merge.

### CODE REVIEW

**Comment by PrzemoF** [comment]
Hi,
I'd suggest to merge commits and force push to get rid of "commit modified data forget to add in the last commit". Also "FemSolver test passed" doesn't really tell what's inside the commit. I use that type of commit messages myself, but in my private repo and they are not supposed to land in the master branch. The code looks nice and clean - I'll be testing it.

**Comment by PrzemoF** [comment]
The code compiles and it doesn't break any existing tests. Compilation with BUILD_FEM_NETGEN is required. I can create a Solver object with empty Display Mode property and Visibility [True/False]. There is a new GUI command "Add a Solver to the Analysis" that adds a Solver object, but I don't know how I could use the Solver object.

**Comment by qingfengxia** [comment]
I did not touch any thing in "MechanicalMaterial.py",  I just rebase to master. 

The Solver class provide information for QProcess to start external solver. It is mainly design for any solver like Fem, CFD. Another commandline property could be added, or built from current property,so  JobControlTaskPanel will be reused by  renaming Calculix (QProcess Object) -> SolverProcessObject or like name.  Although ccx works perfect now, we are not locked to only one Fem solver. 

 The git commands almost kill me, I want to got one submit, but it does not do what I expect even got modified lost on my local. I still have not got it work, merge commits. 

Thanks

**Comment by qingfengxia** [comment]
I have not finish all my functions, which may be half year work. I want to merge step by step. It seems not a good idea. Then I may request test to my fork's branch instead.

**Comment by PrzemoF** [comment]
Just in case I confused you with my previous comments: steb-by-step merging is the way to go, but you have to carefully prepare small functional pieces of code. Functional is the key word. For example if you want to have a new solver object that would allow to start different solvers for me the first logical step would be to port existing ccx solver to that new workflow. I also recommend reading "Git from bottom up" if you have problems with git.

**Comment by qingfengxia** [comment]
I will ask testers to test my fork instead of pull request. 

I am trying to make ccx and foam works together, but ccx change very quick. While I have not learned to merge conflict in command line, I need to merge manually each time. 

Thanks.

**Pull request closed without merging**
