### PR TITLE
[TechDraw] CenterLine should use enums

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by WandererFan** [comment]
Is this change included in #9499?  If so, we  can probably delete this PR.

**Comment by benj5378** [comment]
@WandererFan It is not included in #9499

**Comment by luzpaz** [comment]
What should the merge order be in that case ?

**Comment by WandererFan** [comment]
The PRs that depend on #9499 should probably be marked "draft" while I work through them.  Plan is still to merge them, but they will need work w/o 9499.

**Pull request merged**
