### PR TITLE
[Path] Added new feed rate (Ramp Feed Rate) option in PathDressupRampEntry.py

### PR DESCRIPTION
**Pull request by Schildkroet**
Added new option for ramp feedrate.
Line: 59 and 590f

### CODE REVIEW

**Comment by vocx-fc** [comment]
The entire file looks like it is modified. This could mean that your text editor is changing the line endings of every line. The line endings should stay LF (Unix). Please check that they aren't changed to CR LF (Windows).

**Comment by vocx-fc** [comment]
You should squash your two commits so that there is only one, because the change of line endings shouldn't be its own commit.

**Comment by Schildkroet** [comment]
This will get only worse.... I'm not an expert with git

**Comment by vocx-fc** [comment]
It's not too hard. Have no fear.

```
git rebase -i HEAD~2
```

There is a squash section in [Source code management](https://www.freecadweb.org/wiki/Source_code_management).

**Comment by vocx-fc** [comment]
Good job Schildkroet.

**Pull request merged**
