### PR TITLE
CAM: Fix Helix Defaults in Setup Sheet

### PR DESCRIPTION
**Pull request by jbaehr**
This is yet another complement to PR #17655 (commit 1027926), where the property "Direction" was changed from being an input to an output and the new "Cut Mode" took over (to implement #14314). Unfortunately, this change was not reflected in the Setup Sheet (or "Op Defaults" as it's called on the Job panel).
Luckily this oversight did not cause issues like #17871, so pressure to put it into v1.0 is not that high. Should land in a potential v1.0.1, though, so I still target the FreeCAD-1-0 branch here.

Without this, the setup panel still offers "Direction" (CW/CCW) and this default is ignored when creating a new helical drill operation.

There is no attempt to translate the previous op defaults written by over versions of FreeCAD. Any potential Direction-setting is just be ignored and the new CutMode default is unset.

### CODE REVIEW

**Comment by jbaehr** [comment]
Same procedure as with #17894 -- the pre-commit hook committed tons of unrelated white-space changes in the translation files, which should not be part of this PR.

@yorikvanhavre it looks like the pre-commit hook did not run on your latest translation update, commit 5b00d7f1f23c844be8c82ed5d05826b7695f53db. Would you mind running it again (or cherry-picking its commit  37058fc01eb1ff0c950e98e9413218403e6bcb38 from here) -- right now my very tiny, and completely unrelated, changes are barely visible. I'm then happy to rebase.

**Comment by maxwxyz** [comment]
Is it intended that you've created the PR against the 1.0 branch instead of main?

**Comment by jbaehr** [comment]
> Is it intended that you've created the PR against the 1.0 branch instead of main?

Yes, as per description:
> Luckily this oversight did not cause issues like https://github.com/FreeCAD/FreeCAD/issues/17871, so pressure to put it into v1.0 is not that high. Should land in a potential v1.0.1, though, so I still target the FreeCAD-1-0 branch here.

I'll pull this commit into #17826 for the main line.

**Comment by chennes** [comment]
Cherry-picked without the formatting change.

**Pull request closed without merging**
