### PR TITLE
Correct PartDesign Helix feature negative angles

### LINKED ISSUE #10284: [Problem] PartDesign Helix negative cone angle reverses the coil
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * MeshRemodel 1.8919.0
  * Launcher
  * InventorLoader 1.4.0
  * Render 2023.2.6
  * Silk 0.1.3
  * Defeaturing 1.2.0
  * A2plus 0.4.60n
  * Manipulator 1.5.0
  * fasteners 0.4.59
  * lattice2 1.0.0
  * sheetmetal 0.2.63
  * toSketch 1.0.1
  * Curves 0.6.13
  * Assembly4 0.50.2
  * Assembly3 0.12.0
```

### Subproject(s) affected?

PartDesign

### Problem description

When creating an additive coil in PartDesign, If I set the cone angle to a negative number it reverses the coil.
I expected the diameter of the coil to decrease, but instead it reverses the coil and increases it's diameter.

Coil with positive cone angle value:
Screenshot 2023-08-20 at 21 07 00

Coil with negative cone angle value:
Screenshot 2023-08-20 at 21 07 27

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bgbsww**
Fix #10284.

### CODE REVIEW

**Comment by chennes** [comment]
Can you explain a little more about what this fix is doing? I'm not that familiar with the code here.

**Comment by bgbsww** [comment]
Well, I certainly can't claim any expertise, but TopoShape::MakeSpiralHelix takes a 0 parameter to mean maximum number of breakperiods ( 1000 ) instead of 1, and that causes an increase in resolution that seems to solve this bug.  Also, the other two uses of this method also used this parameter value.

I'll freely admit that I just tested to make sure I didn't break anything obvious without fully understanding why this change is required to fix the situation.

**Comment by wwmayer** [comment]
Do you have a test file? I tried to reproduce this issue and if I set a negative angle then I get the same output that was considered incorrect.

**Comment by bgbsww** [comment]
[NegativeHelix.zip](https://github.com/FreeCAD/FreeCAD/files/13502688/NegativeHelix.zip)

Hmm, I think I may have spotted the discrepancy:  If the underlying sketch is on the origin, it doesn't look like it is reversed.  But does this make geometric sense?  @wwmayer

**Comment by wwmayer** [comment]
As a test create a sketch with a circle on the X axis at (-50, 0) and set its radius to 5.0.
If you create a PD helix set pitch = 40, height = 80 and angle = 30. If you change angle to -30 the behaviour is like before.

**Comment by bgbsww** [comment]
Confirmed.  Same circle at (50,0) works correctly.  I've got some digging to do.  Thanks!

**Comment by bgbsww** [comment]
I think #11598 cleans this up too.

[NegativeHelix.zip](https://github.com/FreeCAD/FreeCAD/files/13520236/NegativeHelix.zip)

**Comment by maxwxyz** [comment]
@FlachyJoe this was the PR for the previous fix

**Pull request merged**
