### PR TITLE
Draft: Improve In-Command-shortcut Undo implementation

### PR DESCRIPTION
**Pull request by Roy-043**
This PR improves https://github.com/FreeCAD/FreeCAD/commit/5a9201d2c591bb658975fc46fc61cbbc2b5ce622

The `inCommandShortcutNearSnap` shortcut did not work and was removed. Using Near snap should be discouraged anyway.

Additionally:
To improve the layout spacers were added to the ui file.
Preferences_Draft_Tab_User_interface_settings_new

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7359">pipeline status</a> for feature branch [PR_7359](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7359). Pipeline [612682471](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/612682471) was triggered at [2ca31f5](https://github.com/FreeCAD/FreeCAD/pull/7359/commits/2ca31f5c1d96c336b917fad1e593775febb58997). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
> Using Near snap should be discouraged anyway

It still has its uses... I use it now and there.

**Comment by Roy-043** [comment]
Yes [Draft Snap Near](https://wiki.freecadweb.org/Draft_Snap_Near) certainly has its purposes. But it does not deserve an In-Command shortcut IMO (and the existing shortcut did not work anyway).

**Comment by Roy-043** [comment]
Are the failed checks blocking this PR? The checks seem old and to be caused by other PRs AFAICT. Is there a way to trigger updated checks?

**Comment by luzpaz** [comment]
Can you rebase in order to re-trigger CI. But you may want to wait until #7469 is merged

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7359">pipeline status</a> for feature branch [PR_7359](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7359). Pipeline [636918424](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/636918424) was triggered at [6da561e](https://github.com/FreeCAD/FreeCAD/pull/7359/commits/6da561e995b13a108c1640dfa64cfabf93e81817). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Roy-043** [comment]
@yorikvanhavre IMO this PR can be merged. Please let me know if there are any issues.

**Comment by yorikvanhavre** [comment]
Sorry guys, this one fell out of my radar. Ok, let's merge this, we see about fixing the snap near shortcut later on...

**Comment by Roy-043** [comment]
@donovaly Since this PR improves a PR that was backported, it would make sense to also backport this one. Thanks.

**Comment by donovaly** [comment]
> @donovaly Since this PR improves a PR that was backported, it would make sense to also backport this one. Thanks.

Thank you. I backported it now.

**Pull request merged**
