### PR TITLE
[FEM] Elmer: add support for 2D magnetodynamics

### PR DESCRIPTION
**Pull request by donovaly**
- adds the corresponding Elmer equation (it is now possible to do Elmer's tutorial example no. 16)

### CODE REVIEW

**Comment by donovaly** [comment]
Here is e FreeCAD file that is basically Elmer's tutorial no. 16: 
[Crucible-heating.zip](https://github.com/FreeCAD/FreeCAD/files/10610121/Crucible-heating.zip)

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [767736444](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/767736444) was triggered at [4244c52](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/4244c520772813a92a30f9f339b38825c32f4d6d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [767803376](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/767803376) was triggered at [995660f](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/995660faf140bc7c37f641950c41e0bf1d3d41d4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [767946681](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/767946681) was triggered at [ed30852](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/ed308523f06852e763a4f07c01c842f240c44998). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
This PR will be changed further once #8362 because this allows a better to read writer.py file

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [767993410](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/767993410) was triggered at [ee989cd](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/ee989cdcc8fa81cce91238be64852ed07c95ab71). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768008640](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768008640) was triggered at [a0ba9d7](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/a0ba9d733583cbe6545d39133b3d63ccd631db07). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768019078](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768019078) was triggered at [db9d65b](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/db9d65b2dbc441c76b5dac2df487162975aa4e60). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768019702](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768019702) was triggered at [e737cd5](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/e737cd5228d8eee68752eeac5974a9caa0a830d2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768024324](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768024324) was triggered at [b440796](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/b44079636ae0c39d3dd0e681691cc42174ff566e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768038677](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768038677) was triggered at [1d6fa0f](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/1d6fa0f7303ce79041352671d4ac20b2e22f6abb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768040063](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768040063) was triggered at [51bb47f](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/51bb47fba81e74a5032586f9efa7b496782e8374). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768043164](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768043164) was triggered at [effccfe](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/effccfe2a919dfc92d939044a9d3ebecef073ce9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768179686](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768179686) was triggered at [6c4a7ee](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/6c4a7ee27d99b1ee807c33a9399ab9c128825d3a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768180560](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768180560) was triggered at [d2c42af](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/d2c42af1886f46f8824ca64f8b8a8f5c1fe5a855). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [768194923](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768194923) was triggered at [e637b33](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/e637b3367ff950d81f5275bef7987d2b431c4e4b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [769201614](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769201614) was triggered at [8060ee3](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/8060ee31b798f838e7734be38e246e124ba735c1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [769228489](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769228489) was triggered at [61366ca](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/61366ca459fcce18b390695452b0271f4c08eed8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [769268994](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769268994) was triggered at [3940d92](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/3940d9273009ae54516201018f98aec743865772). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [769326098](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769326098) was triggered at [e86baf3](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/e86baf37c2aad45b7e24492fdf20c512864b3917). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355">pipeline status</a> for feature branch [PR_8355](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8355). Pipeline [769333862](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769333862) was triggered at [7a25204](https://github.com/FreeCAD/FreeCAD/pull/8355/commits/7a252043486647c15f481b359b77c0d1e511b026). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
