### PR TITLE
Path: Path unit test fixes issue #2870

### PR DESCRIPTION
**Pull request by mlampert**

### CODE REVIEW

**Comment by wwmayer** [comment]
Unit test failure:
failed_to_load_TestPathApp (TestApp.LoadFailed) ... FAIL

======================================================================

FAIL: failed_to_load_TestPathApp (TestApp.LoadFailed)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/FreeCAD.app/Contents/Mod/Test/TestApp.py", line 52, in _runTest

    self.fail("Couldn't load " + self.testName)

AssertionError: Couldn't load TestPathApp

**Comment by mlampert** [comment]
Ooops -this one fell through the cracks. Fixed, afaict, although I never saw the error messages you noted.

**Comment by wwmayer** [comment]
The error is still there. The point is not that the unit test is wrong but the CMakeLists.txt file doesn't include the Python file in the INSTALL target.

**Comment by mlampert** [comment]
I never encountered that error - I changed the CMakeList.txt and at least now I get the same error in my builds. Will figure out what needs to be done.

**Comment by mlampert** [comment]
Found the issue - the file itself was properly installed, but it imports another file which was not in the source list. Due to the exception mapping TestApp.py it was hiding the real issue.

**Comment by mlampert** [comment]
this is killing me

**Comment by mlampert** [comment]
Hopefully got the cmake stuff right for all platforms this time. There was also the issue of including coin from pivy, which doesn't seem to be a  problem for the windows builds but was one for (some of) the linux builds.

**Comment by sasobadovinac** [comment]
before 85 test from from the cl, now 132, awesome! :) did you try if they run ok also from gui? and can we do something about this warning:

`DeprecationWarning: For future usage 'Curve' will return 'Line' which is infinite instead of the limited 'LineSegment'.
If you need a line segment then use this:
Part.LineSegment(edge.Curve,edge.FirstParameter,edge.LastParameter)
To suppress the warning set BaseApp/Preferences/Mod/Part/General/LineOld to false`

**Comment by wwmayer** [comment]
@sasobadovinac The last part of the warning says it all. You have to make a change in your user.cfg to suppress it.

**Comment by sasobadovinac** [comment]
@wwmayer Localy yes, but I meant for Travis / AppVeyor, unit test logs are now full of this warning

**Comment by wwmayer** [comment]
The easiest would be to make the new behaviour the default.

**Comment by mlampert** [comment]
That actually brings up an interesting question - should the unit tests be run with both settings? In this case only the unit tests were affected but there's a fair chance that some code won't work, depending on LineOld being set or not.

Given that "LineOld=false" is "the future", it might make more sense to make that the default and run the unit tests with that setting.

**Pull request merged**
