### PR TITLE
Measure: When measuring the distance between circles then use the cen…

### PR DESCRIPTION
**Pull request by wwmayer**
…ter points as reference

See forum: https://forum.freecad.org/viewtopic.php?t=91570

### CODE REVIEW

**Comment by FEA-eng** [comment]
Awesome. Can it go for 1.0? We would avoid a huge number of complaints.

**Comment by chennes** [comment]
The MacOS Conda failure appears to be a false one, I am ignoring it.

**Comment by chennes** [comment]
Backported to 1.0

**Comment by hlorus** [comment]
Thanks for looking into this! I'm aware that measuring center to center is more frequently used than min. distance between the circles. Yet i guess that users would want control over what to measure exactly, which should be resolved with a snapping functionality (#13708). So is this PR meant as a temporary solution to fit the most frequent use-case or does this this aim to solve #13708?

**Comment by FEA-eng** [comment]
Could it be easily extended to circular and cylindrical faces (in addition to circular edges)?

**Comment by wwmayer** [comment]
Detecting circular faces with all its corner cases is possible but way more complicated than circular edges.

And it can cause some ambiguities because if two parallel circular faces are selected one could be interested in the distance of the two center points of the circles or in the distance between the faces.

To avoid this I recommend that the user has to click the circular edge of the face.

**Comment by ToniTen** [comment]
> Detecting circular faces with all its corner cases is possible but way more complicated than circular edges.
> 
> And it can cause some ambiguities because if two parallel circular faces are selected one could be interested in the distance of the two center points of the circles or in the distance between the faces.
> 
> To avoid this I recommend that the user has to click the circular edge of the face.

I see that this has landed on 
```
OS: Ubuntu Core 22 (XFCE/xubuntu/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39062 (Git) Snap 1175
Build type: Release
Branch: main
Hash: c5c64a9c70f21c4c4c2ad294645993f9a60342d8
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: C/Default (C) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.29
  * Assembly3 0.12.2
  * lattice2 1.0.0
  * Manipulator 1.5.7
```
The way I would approach (and that I suggested in the forum post, though I will say it was buried at the end of the post and not too well explained) is to have a new measurement mode called **Distance between Centers**, that if one of the elements selected is a flat circular face, the side of a cylinder, a spherical surface, or an arc of a circle, it measures from the center of said circular object (We will use this name from now on). This mode is selected by default if the first selected item is such a circular object. Keep the current distance measurement mode to be the nearest distance. If anything other than a circular object is selected first, then the measurement is the current nearest distance.

Let's go case by case, initial mode is set to auto:

1. A circular object is selected first, and a second circular object is selected second. Mode is automatically changed to **Distance between Centers**. Distance is measured between centers
2. A circular object is selected first, and a second circular object is selected second. Mode is automatically changed to **Distance between Centers**. User changes to **Distance**. Distance is measured between nearest points
3. A circular object is selected first, and a non circular object (flat face, straight or curved but non circular edge, vertex, etc) is selected second. Mode is automatically changed to **Distance between Centers**. Distance is measured between the center of the circular object and the nearest point of the non circular object
4. A circular object is selected first, and a non circular object (flat face, straight or curved but non circular edge, vertex, etc) is selected second. Mode is automatically changed to **Distance between Centers**. User changes to **Distance**. Distance is measured between nearest points
5. A non circular object is selected first, and then a circular object is selected second. Mode is automatically changed to **Distance**. Distance is measured between the nearest points
6. A non circular object is selected first, and then a circular object is selected second. Mode is automatically changed to **Distance**. User manually changes to **Distance between Centers**. Distance is measured between the center of the circular object and the nearest point of the non circular object
7. A non circular object is selected first, and then a non circular object is selected second. Mode is automatically changed to **Distance**. User manually changes to **Distance between Centers**. Distance is measured as if the **Distance** mode was selected

I feel this makes intuitive sense, allows to check for clearance between circular objects and other objects (say you have an assembly where two wheels at the end of articulated arms need to remain a certain safe distance between them, or when you need to ensure that there's enough clearance around a circular hole to put a washer and fit a hex key to tighten the bolt), is fully flexible, and should not really involve much extra coding

**Comment by maxwxyz** [comment]
Is there a way to disable the center mode and measure the distance between the circles again?
In this case I wanted to measure the distance between the hole and the outer edge:
grafik

The measure tool now results to this what is not ideal:
grafik

**Comment by FEA-eng** [comment]
> Is there a way to disable the center mode and measure the distance between the circles again? In this case I wanted to measure the distance between the hole and the outer edge:

The center mode is only activated for edges so you could select the cylindrical face of the hole instead.

**Comment by maxwxyz** [comment]
Thanks, fortunately I have two parallel faces in this example. I thought otherwise it would make more sense: select the cylindrical face to get the axis and the circle for dimension.

**Pull request merged**
