### PR TITLE
Draft: Fix merge layers

### PR DESCRIPTION
**Pull request by Roy-043**
The "Merge layer duplicates" Tree view context menu option for LayerContainers did not work.

Additionally:
- Using `openTransaction` and `commitTransaction` is required for the `merge_by_name` function but also for the `add_layer` function. Otherwise undo-redo does not work properly.
- Have replaced `translate("Draft", ...)` with `_tr(...)`.

Forum topic: https://forum.freecadweb.org/viewtopic.php?f=23&t=60843

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by chennes** [comment]
Thanks, looks good!

**Comment by wwmayer** [comment]
> Have replaced translate("Draft", ...) with _tr(...).

@Roy-043  Note, that translate("Draft", ...) is not the same as _tr(...) because pyside2-lupdate won't add the strings to the .ts files any more.
As a quick test run `pyside2-lupdate view_layer.py -ts test.ts` and open the file in a text editor. None of the strings with _tr(...) are listed there. Insofar a clear regression.

I wonder what the function _tr() is good for as it only translates text but can't be used to pick them up. The same applies to the _qstr() function.

What seems to work is to rename _tr() to tr() and use `@default` as context string:
```
def tr(text):
    return translate("@default", text)
```

**Comment by Roy-043** [comment]
I do not fully understand how `lupdate` should work. I am testing it now with an old version of `view_layer.py` and the produced TS file contains zero source texts.

See forum topic: https://forum.freecadweb.org/viewtopic.php?f=10&t=63456

Regarding the `_tr()` function: It is used elsewhere in the Draft code, and it seemed a more efficient way of doing things. If it does not work properly we must of course remove it from all Draft code.

**Comment by wwmayer** [comment]
Have a look at https://doc.qt.io/qt-5/i18n-source-translation.html
Basically Qt offers these functions for translations:
* tr() : this marks strings for lupdate and translates them immediately. In C++ the context is the class name but in Python it seems to use the string `@default`
* QApplication::translate() : does the same as above but you must explicitly set the context
* QT_TR_NOOP : only marks the string for lupdate but doesn't translate it.
* QT_TRANSLATE_NOOP : does the same as above but you must explicitly set the context

The _tr() function is only able to translate strings but it doesn't mark them for lupdate. So, as soon as a string will be changed we won't be able any more to add them to the .ts files.

**Comment by luzpaz** [comment]
CC @yorikvanhavre :point_up:

**Comment by yorikvanhavre** [comment]
We should basically remove all _tr from Draft... I think the best strategy is to remove it from Draftutils so we make sure anything that still uses it fails. I'll take care of this

**Pull request merged**
