### PR TITLE
Path: prevent added paths creating tool crash: fixed #4260 

### PR DESCRIPTION
**Pull request by J-Dunn**
In this path dressup a bogus machine position is used to get an initial edge, this results in a path element which does reflect the input path data and can lead to a tool crash. This PR checks whether X and Y actually come from the input path data and prevent new path elements being added until true machine position has been set. 
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=15&t=42820

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
Please rebase instead of merging, so the merge doesn't show up as a commit in itself. This keeps the git commit history clean. Thank you.

**Comment by luzpaz** [comment]
* Note to fix or address a ticket in our bugtracker please follow https://wiki.freecadweb.org/Tracker#GitHub_and_MantisBT  
* when modifying checkboxes in github markdown correctly the `x` in between square brackets shouldn't have a whitespace around it. 
>     * [x ] Branch rebased on latest master `git pull --rebase upstream master`
>     * [ ]  Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
>     * [ x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
>     * [x ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

`- [x] Example of correct formatting`
- [x] Example of correct formatting

**Comment by J-Dunn** [comment]
> Please rebase instead of merging, so the merge doesn't show up as a commit in itself. This keeps the git commit history clean. Thank you.

I used a brand new fork and by the time I'd uploaded the one file for the PR it was "out of date".  

I have had similar comments in the past but no one is capable of telling me how to rebase a github fork. 

Maybe you can explain how to do that. 

I thought the [x] marks were there to inform reviewers and assumed they would have the intelligence to parse spaces. In fact I probably did not even notice, since I do have that capacity.  If you are using software to read that, maybe you need to improve that software to cope with or remove spaces if that is an issue. If you are really unable to do that, put an explicit warning in the boilerplate text so that contributors are aware that the lame automated feature has "special needs". 

To be honest all this jumping through hoops makes submitting a PR more work that fixing the code base in the first place. It would be helpful not to double the workload for those who find the time to contribute.

**Comment by luzpaz** [comment]
@J-Dunn yea.. there is a learning curve but it's to promote uniformity, and respect for everyone's time/energy invested. As a project in comparison to other bigger projects we are less stringent (see contribution guidelines for projects like numpy or scipy, we're a walk in the park by comparison). To address your points:  
* Knowing markdown is helpful when working on Github. Eventually you would of heard about the [checkbox syntax](https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/) from someone else if you contribute code on github or other platforms that support markdown.  
* Formatting the commit text of the PR so it triggers a response on our bugtracker is considerate of our time as maintainers/developers. It saves waiting time and several clicks. FYI, the edit that you made to the title of the PR won't trigger the webhook (the trigger needs to be written in to the original commit title or body). But lets not keep 'kicking a dead horse' and move on. Hopefully next time you can remember to do this. 
* [Rebasing](https://wiki.freecadweb.org/Developing_FreeCAD_with_GitKraken#Rebasing) was a little tricky to understand for me originally until I saw what it does visually. I use a GUI git client and git has become way more manageable for me. Essentially, rebasing keeps your branch commit history clean of any commits that you used to keep your branch up to date with master. Hope the wiki page helps. If not please post on the forum and we'll be happy to help you understand it better.

**Comment by J-Dunn** [comment]
I've corrected the markdown thing but it is irrelevant. It was legible to maintainers as it was and wasting everyone's time with such nitpicking pedantics is not productive. 

I know what rebasing is about but it does not seem possible on github. It seems you don't know either. 

I will bear in mind your comments about the webhook feature next time I make a PR, and try to include it in the commit comment. Thanks for explanation on how that works.

**Comment by sliptonic** [comment]
I'm merging this.  
FYI. I don't think you can rebase on github directly but you can rebase the branch the PR is created from and push/force it to github.  The PR will automatically update and restart the checks.

Also, in the future, please run a de-linter on your code.  Something like flake8.   There are a handful of pep8 violations here but they're almost all whitespace errors so I'm not worried.

**Comment by J-Dunn** [comment]
Thanks for the recommendation. I thought all the lint comments came from maintainer level checks. I've installed flake8. I'll have to see what it's all about. 

I could not get a working connection to github on Fedora and gave up trying after banging my head against the wall for a bit too long. I just delete my fork on github, do a clean fork and then upload by files ( usually only one or two with the simply mods I'm submitting ). The trouble is if someone merges something to master in the few minutes that takes.

**Comment by sliptonic** [comment]
My view of a pull request distinguishes between a PR that has merge conflicts and one that is out of date with the master branch but does not have conflicts.  If it has conflicts or is really old, I'll ask the developer to manually rebase it.  But as you point out, it's just not possible to keep a PR at the tip of master with so many developers submitting PRs.  Don't worry about it.

Flake8 just scans your code for compliance with pep8.  It's much more important to understand pep8.  Code consistency is a big deal in python and pep8 is the bible.   Our code base is pretty consistent but there are always a few exceptions.  Line length, for one, I'll always let slip.  80 columns is ridiculous.

**Pull request merged**
