### PR TITLE
Gui: propertyeditor: minor cleanup

### PR DESCRIPTION
**Pull request by 3x380V**
Avoid back and forth conversion between std::string and QString

### CODE REVIEW

**Comment by wwmayer** [comment]
In how far does this PR collide with https://github.com/FreeCAD/FreeCAD/pull/15276? In the latter you also made many changes to PropertyItem.cpp

**Comment by 3x380V** [comment]
I have not found a way how to do a dependent pull request. This one is meant to be merged first so after rebase of #15276 these patches vanishes. If you know how to do a better way, please let me know.

Anyway, I took opportunity and run clang-format first instead of just whitespace cleanup, so I'm polishing this PR and will update it.

**Comment by 3x380V** [comment]
@wwmayer, reformatted. At downside patch is impossible to read. Alternatively we might leave DOS line endings hardcoded as they are.

**Comment by wwmayer** [comment]
If a merge this PR is it then easy for you to update the other PR with the units code simplification?

**Comment by 3x380V** [comment]
Yes, commits present here will be automagically dropped on rebase.

(To the educated public: I would appreciate information if it is even possible to open chained pull requests. I haven't figure how, but that does not mean much. Even explicit information it is impossible would be useful)

**Comment by wwmayer** [comment]
> Yes, commits present here will be automagically dropped on rebase.

OK, but I have seen a few places in the code where clang-format off/on is needed. But this could also be changed after merging the other PR.

**Comment by 3x380V** [comment]
Could you spot such places? While I do not have time for any systematic work atm, changes like this are easy enough, so I'll happily make them.

**Comment by wwmayer** [comment]
Thanks!

**Pull request merged**
