### PR TITLE
Part: ruled surface, address issue with link support where link was t…

### PR DESCRIPTION
**Pull request by mwganson**
…ransformed

https://forum.freecadweb.org/viewtopic.php?f=3&t=67961&p=588230#p588230

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6742">pipeline status</a> for feature branch [PR_6742](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6742). Pipeline [515529715](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/515529715) was triggered at [f7838fe](https://github.com/FreeCAD/FreeCAD/pull/6742/commits/f7838fec84a846e2722fdace4d2bfbeccf6c5c03). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@realthunder , could you please review also this PR too? If OK, it can go in for FC 0.20

**Comment by realthunder** [comment]
It's good.

**Comment by donovaly** [comment]
Thanks for the review. Merging

**Pull request merged**
