### PR TITLE
Ship: Remove Ship module

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [X]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

Remove Ship module. None other module depends on Ship, so I think is safe to do that.

I am waiting this to be merged before creating the PR to remove the Plot workbench while keeping the module (see https://github.com/FreeCAD/FreeCAD/pull/4890). Otherwise ugly conflicts will arise.

---

2 tests failed... Apparently nothing related with this:

```
======================================================================
FAIL: test_box_frequency (femtest.app.test_ccxtools.TestCcxTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_ccxtools.py", line 102, in test_box_frequency
    self.result_reading_test(
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_ccxtools.py", line 323, in result_reading_test
    self.assertFalse(
AssertionError: True is not false : Invalid results read from .frd file

======================================================================
FAIL: test_thermomech_flow1D (femtest.app.test_ccxtools.TestCcxTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_ccxtools.py", line 158, in test_thermomech_flow1D
    self.result_reading_test(
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_ccxtools.py", line 323, in result_reading_test
    self.assertFalse(
AssertionError: True is not false : Invalid results read from .frd file

----------------------------------------------------------------------
```

### CODE REVIEW

**Comment by luzpaz** [comment]
@berndhahnebach see above for the 2 failed FEM tests

**Comment by berndhahnebach** [comment]
db9850008fdf2b48244b2373d0056be8598b6bc6

**Comment by sanguinariojoe** [comment]
> [db98500](https://github.com/FreeCAD/FreeCAD/commit/db9850008fdf2b48244b2373d0056be8598b6bc6)

Rebased!

**Comment by luzpaz** [comment]
@yorikvanhavre are we green light on this?

**Comment by yorikvanhavre** [comment]
Since this is a huge PR, while the travis CI is unavailable, I'd like to have another person compile and confirm if all works OK before merging (it's easy toforget some little cmake thingy)... I'll do it when I have a minute, but if anyone else does it before me...  :innocent:

**Comment by Syres916** [comment]
Compiled the PR, ran the TestApp.All, 595 tests ran, 0 failures, 0 errors. Used the build for some simple Sketcher, Part, Part Design and CfdOF work and nothing unexpected occurred.
OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.20.25181 (Git)
Build type: Release
Branch: del_ship
Hash: 63c9e7ee72b6f41cafec16531bf5f1a01d158119
Python version: 3.6.9
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

**Comment by chennes** [comment]
Compiled and tested on Windows 10 with no problems:
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.25180 +1 (Git)
Build type: Release
Branch: pr/4900
Hash: 63c9e7ee72b6f41cafec16531bf5f1a01d158119
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by luzpaz** [comment]
@yorikvanhavre is that enough testers for merge?

**Comment by luzpaz** [comment]
@yorikvanhavre follow-up ping

**Comment by yorikvanhavre** [comment]
sorry, i was also on holiday 😅 i'll merge! i can't build right now, so as it moves some cmake stuff, please can you build and check everything still works ok? i'll do the same tomorrow

**Comment by chennes** [comment]
@yorikvanhavre I just tested HEAD on Windows 10 and it compiles fine.

**Comment by AjinkyaDahale** [comment]
May want to remove the "Testers Needed" label.

**Comment by yorikvanhavre** [comment]
thanks @chennes !i built it today too and all looks fine.

**Pull request merged**
