### PR TITLE
[OpenSCAD] Fixes cut color while importing CSG

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Fixes #4684.
For some reason colors of "base" and "tool" need to be set in order for the cut
to have colors as well, just like fuse and multifuse.
Also tidied up the relevant code portions a little.
Some testing might be needed.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by KeithSloan** [comment]
Not a good sign when people starting fixing code without understanding underlying concepts.
CSG is NOT a file format it is scripting for creating graphics objects as such it needs to be parsed rather than treated as a file format. importCSG parses the CSG file with a python version of lex, when objects such as cube etc are encountered they are placed on a stack, that is the way a parser works. When the parser encounters a boolean the objects it is to operate on are already on the stack. Colour is set in the ViewProvider ( Parts do not contain colour information ). There is currently no stacking of colour information so importCSG has to make a decision based on the objects being operated on. i.e. the objects that the boolean has tool and base set. There was a bug in that only Fuse was being handled a Cut request showed up the error and this fix now has code for Part::Cut but there are other booleans that also need dealing with i.e Part::Common, Part::MultiCommon

**Comment by AjinkyaDahale** [comment]
@KeithSloan's comment addressed in forum: https://forum.freecadweb.org/viewtopic.php?p=516912#p516862.

**Comment by luzpaz** [comment]
@KeithSloan what say you on this PR ?

**Comment by KeithSloan** [comment]
Luzpaz - Looks fine to me

**Review by chennes — APPROVED** [review]
This compiles, runs, and fixes the issue reported in the topic. It passes all OpenSCAD unit tests.

**Comment by luzpaz** [comment]
@kkremitzki ready for merge

**Comment by luzpaz** [comment]
@AjinkyaDahale please rebase

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale please rebase

Done. Did you change something recently?

**Pull request merged**
