### PR TITLE
CMake: fix installation path for Mod/Material

### PR DESCRIPTION
**Pull request by pinkavaj**
This fixes issue with Arch linux packaging, the file materials-editor.ui is installed into build directory instead of installation directory.

Install the UI file the same way as done in src/Mod/Fem/Gui/CMakeLists.txt

NOTE: Pls double-check, this was kind of cargo-cult programing (my first contribution into this project).

### CODE REVIEW

**Comment by maxwxyz** [comment]
@davesrocketshop could you check this?

**Comment by davesrocketshop** [comment]
This is the third PR I've seen on this that hasn't been tested properly because the coder doesn't understand the problem. What I have yet to see is an issue describing the problem, which I don't understand. Until I see an issue properly describing the problem, I won't add much in terms of comment here other than to say it breaks stuff

**Comment by davesrocketshop** [comment]
See PR #15565

**Comment by pinkavaj** [comment]
Related to (duplicated) #15713

**Comment by chennes** [comment]
I believe #15571 is the original issue.

**Comment by pinkavaj** [comment]
Closing in favour of #16105

**Pull request closed without merging**
