### PR TITLE
circle-ci + conda-build

### PR DESCRIPTION
**Pull request by looooo**
This enables the possibility to build FreeCAD with conda-packages on linux with cirle-ci

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Merged.

**Comment by looooo** [comment]
would it be possible to run this ci once a week? Maybe it's possible to upload the result to the github release-page? @sgrogan

**Comment by sasobadovinac** [comment]
yorik will probably first have to setup an circle-ci account connected to the freecad master?

**Comment by looooo** [comment]
yes, you are right.
@yorikvanhavre  would it be possible to set up a circle-ci account for FreeCAD?

**Comment by sgrogan** [comment]
What do I need to do?

**Comment by yorikvanhavre** [comment]
I just created a circle-ci account, it says:

1. Create a folder named .circleci and add a fileconfig.yml (so that the filepath be in .circleci/config.yml).
2. Populate the config.yml with the contents of the sample .yml (shown below).
3. Update the sample .yml to reflect your project's configuration.
4. Push this change up to GitHub.
5. Start building! This will launch your project on CircleCI and make our webhooks listen for updates to your work.

Sample config file:
```

# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
```

**Comment by yorikvanhavre** [comment]
Ah forget this... It seems to be building already
https://circleci.com/gh/FreeCAD/FreeCAD/

**Comment by looooo** [comment]
@yorikvanhavre thanks! I think everything should be there. It is mostly a copy of a conda-forge feedstock.
@sgrogan can you give some quick hints how to upload builds to the release github page? If I have understood correctly this is already done with travis builds.

**Comment by sgrogan** [comment]
@bblacey did the heavy lifting here. @sasobadovinac has prototyped this with AppVeyor. For the Win snaphots i still upload them manually.

**Comment by sasobadovinac** [comment]
check if the last few lines in this can help you further
- for mac https://github.com/FreeCAD/FreeCAD/blob/master/.travis.yml
- for appimage https://github.com/FreeCAD/FreeCAD-AppImage/blob/master/.travis.yml
- for windows https://github.com/sasobadovinac/FreeCAD/blob/test_appveyor_2/appveyor.yml

**Comment by looooo** [comment]
thanks for the references. I hope I have some time to look at this in the next days.

**Pull request closed without merging**
