### PR TITLE
new Windows installer for FC

### PR DESCRIPTION
**Pull request by donovaly**
Final PR for the installer discussed and developed in this forum thread:
https://forum.freecadweb.org/viewtopic.php?f=4&t=35038

The wix installer in src have apparently not been used for years thus this PR removes it.

### CODE REVIEW

**Comment by wwmayer** [comment]
From the ReadMe.md file it's not clear where to find the file FC-standard-installer.zip. A hint to find it at https://github.com/donovaly/FreeCADInstProj/releases/tag/0.3 would be good.

The installer uses the script nsProcess.nsh but the default installation of NSIS lacks of this and some plugins. A hint that it can be found here  https://nsis.sourceforge.io/mediawiki/images/1/18/NsProcess.zip would be good.

The installer reintroduces the LGPL text. But according to commit 0274e73a8d9 the GPL/LGPL is not an EULA.

**Comment by donovaly** [comment]
> From the ReadMe.md file it's not clear where to find the file FC-standard-installer.zip. 
> A hint that nsprocess it can be found here

many thanks for your review. These issues are now fixed:
https://github.com/FreeCAD/FreeCAD/pull/2054/commits/b55c242e733cf9535c7c752f7d7c14f3257a82e3

> The installer reintroduces the LGPL text. But according to commit [0274e73](https://github.com/FreeCAD/FreeCAD/commit/0274e73a8d928fc8a8c88aa283096201ea73ec22) the GPL/LGPL is not an EULA.

I am reluctant here. This commit only change the button from "Accept" to "Next" and it tells the user that he is now informed about the GPL. But in the page header there is still the info twice that there is a license one must agree to. I could change this text too but then we will have 3 new strings to translate to all languages. This is a problem because not all users understands English that well. They will then get an English text they don't understand and just lick "Next". But in this case it doesn't matter if we name it "agreement" or "information".
I thought about the issue and I think we should just rename the button "Accept" to "Next" but keep the license description text as it is. Frankly speaking discussions about the wording is quite nitpicking in this respect since as user you have to fulfill the GPL in every case so in fact it doesn't matter if call it info or agreement. A nitpicker might say you agree to fulfill law which is your duty anyway.

Please think about this and decide if I either should
- only rename the button (NSIS takes care of its translation)
- change all strings on the license page (we need to translate them to all 24 languages we currently support with the installer)

**Comment by wwmayer** [comment]
> I am reluctant here. This commit only change the button from "Accept" to "Next" and it tells the user that he is now informed about the GPL.

The contributor of the patch gave a hint how it's done in vlc. Maybe we should have a look how this installer behaves. The source code can be found here: https://git.videolan.org/?p=vlc.git;a=blob;f=extras/package/win32/NSIS/vlc.win32.nsi.in;h=b5e0e1af01340b54898d89b67e0e507faa1b6556;hb=HEAD

> Frankly speaking discussions about the wording is quite nitpicking in this respect since as user you have to fulfill the GPL in every case so in fact it doesn't matter if call it info or agreement. 

Really? Look here: https://en.wikipedia.org/wiki/End-user_license_agreement#Comparison_with_free_software_licenses

> Unlike EULAs, free software licenses do not work as contractual extensions to existing legislation. No agreement between parties is ever held, because a copyright license is simply a declaration of permissions on something that otherwise would be disallowed by default under copyright law.

For more information also have a look here: https://opensource.stackexchange.com/questions/2865/does-open-source-software-need-an-eula-to-protect-the-developer
https://drj11.wordpress.com/2008/02/25/the-gnu-gpl-is-not-an-eula/


> Please think about this and decide if I either should

I don't mind. Just do it the way how it's easy for you.

**Comment by donovaly** [comment]
> The contributor of the patch gave a hint how it's done in vlc. Maybe we should have a look how this installer behaves. The source code can be found here: https://git.videolan.org/?p=vlc.git;a=blob;f=extras/package/win32/NSIS/vlc.win32.nsi.in;h=b5e0e1af01340b54898d89b67e0e507faa1b6556;hb=HEAD

But this is what I said. The VLC installer still states in the 2 header texts of the license page of the installer that it is a license agreement.

The problem is that to change the first license page header text one would have to change the translations of NSIS and this is nothing we can do. The only thing is to ask the NSIS people to offer 2 different license pages, one for EULA, one for License info for future NSIS releases.

> > Please think about this and decide if I either should
> 
> I don't mind. Just do it the way how it's easy for you.

I changed now the button from "Agree" to "Next" and I removed the license page bottom text that stated one has to agree to something.

**Comment by wwmayer** [comment]
Merged.

**Comment by sgrogan** [comment]
Thanks!

**Pull request closed without merging**
