### PR TITLE
Part: extend command Part_PointsFromMesh to support any geometric type

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8730">pipeline status</a> for feature branch [PR_8730](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8730). Pipeline [795644830](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/795644830) was triggered at [d72a322](https://github.com/FreeCAD/FreeCAD/pull/8730/commits/d72a3229fd407445ec4ad15b55179fce529baba9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8730">pipeline status</a> for feature branch [PR_8730](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8730). Pipeline [795787806](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/795787806) was triggered at [0721ba0](https://github.com/FreeCAD/FreeCAD/pull/8730/commits/0721ba07f0105de45bd2611db665e6bf10bdbdd2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by utkarshraj779 — APPROVED** [review]

**Comment by Roy-043** [comment]
I am not a native speaker, not do I want to be a language purist, but shouldn't the name of the command be changed in this case?

And why does the command not create a Points object?

**Comment by wwmayer** [comment]
> I am not a native speaker, not do I want to be a language purist, but shouldn't the name of the command be changed in this case?

I have thought about this too. But it's always problematic to rename existing commands because it's not clear how people use them and when used in scripts, custom toolbars, ...  they will break.

> And why does the command not create a Points object?

Because it never did. The original command used the points of a selected mesh and created a compound of vertexes.

It only supported meshes and not any other geometric type.  But recently somebody on the forum had a point cloud and wanted to convert them into a compound of vertexes. Adding a further command for points doesn't make sense to me as it's 90% pure code duplication the right approach to me is making the existing command more flexible.

**Comment by Roy-043** [comment]
Thanks for your answers.

> But it's always problematic to rename existing commands

I understand, but you could still support the old name be creating some sort of wrapper that calls the new command. It should be possible to rename a command.

**Pull request merged**
