### PR TITLE
Fix various typos and whitespace issues

### PR DESCRIPTION
**Pull request by luzpaz**
* Various typo fixes  
* Trivial whitespace fixes for `ArchStructure.py`

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8210">pipeline status</a> for feature branch [PR_8210](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8210). Pipeline [752653643](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/752653643) was triggered at [ce55f05](https://github.com/FreeCAD/FreeCAD/pull/8210/commits/ce55f05468f146135577a90b3fff60ed7966f0e4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8210">pipeline status</a> for feature branch [PR_8210](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8210). Pipeline [753122856](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/753122856) was triggered at [77fec18](https://github.com/FreeCAD/FreeCAD/pull/8210/commits/77fec184bee90944588fb52b9f7ff1106305ab82). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Sorry, trying to use Github's codespaces to add to this commit and squash the last 2 commits but it didn't take. Can a merge dev squash: https://github.com/FreeCAD/FreeCAD/pull/8210/commits/b1976e7415d457decb11add9849f1f22442acb9f  + https://github.com/FreeCAD/FreeCAD/pull/8210/commits/10d64f357535af2c44f44cf5a2b062c450731548  → https://github.com/FreeCAD/FreeCAD/pull/8210/commits/77fec184bee90944588fb52b9f7ff1106305ab82 please? TIA

**Comment by chennes** [comment]
Are you looking for this to be one commit, or two?

**Comment by luzpaz** [comment]
@chennes 2 commits please :pray:

**Comment by chennes** [comment]
OK, should be merged as edfc993b7f914562cc82f0fe5075f3d1913de3ab and a42c526eecf4bcc00defeb7bc1f449428e3e95f4

**Pull request closed without merging**
