### PR TITLE
cMake: Add manual find_package() for fmt

### PR DESCRIPTION
**Pull request by chennes**
Manually call find_package(fmt) before attempting to download the sources.

---

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8568">pipeline status</a> for feature branch [PR_8568](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8568). Pipeline [783758648](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/783758648) was triggered at [b3766e5](https://github.com/FreeCAD/FreeCAD/pull/8568/commits/b3766e5c42af8e2decd7cce6cb1474b1809d6f50). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
Thanks, this is working for me on archlinux, libfmt is recognized when installed and downloaded when not installed

**Comment by adrianinsaval** [comment]
Is there a way I can point cmake to an already downloaded copy of fmt source code for flatpak or should I compile it, install it and then let find_package use that?

**Comment by chennes** [comment]
There's probably a way, but you will have to place the download wherever cMake tries to look for it. Then as long as the MD5 matches the one I specify, I think it won't try to download it again.

**Comment by adrianinsaval** [comment]
please so I can test it on flatpak, I'll probably just build and give cmake the install location

**Pull request merged**
