### PR TITLE
Fix some Quarter High DPI Display issues.

### PR DESCRIPTION
**Pull request by f3nix**
Tested on Mac Retina by @bblacey 

Cheers,
Mateusz

### CODE REVIEW

**Comment by bblacey** [comment]
@wwmayer, @yorikvanhavre - this is needed to make Qt5 somewhat usable of macOS.  Any idea on the timeframe for merge to master?

**Comment by wwmayer** [comment]
Merged.

**Comment by bblacey** [comment]
Thanks!

**Comment by f3nix** [comment]
Thanks! :)

**Pull request closed without merging**
