### PR TITLE
PATH Dressupleadinout arc fix pep8 conform

### PR DESCRIPTION
**Pull request by IchGucksLive**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x ] Branch rebased on latest master `git pull --rebase upstream master`
- [x ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

Here is a Fix for the pep8 conform dresssup as many claimd to be conform 
also a Fix to get it working on Round edges 
@luzpaz  @sliptonic  @realthunder @wwmayer 
I hope i did now do all you wantred me to fix it

### CODE REVIEW

**Comment by IchGucksLive** [comment]
@sliptonic  You dident folow your own rule 
DELETE the dressup and apply it again then you willl see the effect //NEW Regenerate 
Dressups are since OP changes not renewed on reload   
Workflow open the OLD Fcad file
Delete Dressup
Apply dressup again to the Operation 
@luzpaz its a simple letter fault no need fro renew the system ROFL 
if you only find one keep it ,it may boost your life someday.((46School years))

**Comment by sliptonic** [comment]
@IchGucksLive:  I AM testing with a new operation.  When I apply the dressup, it changes the join type to square.  When I set it back to round, it gouges.  Since the join type property is for the entire operation, the change affects the ENTIRE path and not just the start point.  Every corner becomes a square.  This might not be a big deal but it's certainly surprising to the user who has no reason to expect it.

**Comment by sliptonic** [comment]
On further reflection it's actually a pretty big deal.  Your dressup changes the property of the base path.  If the dressup is deleted, the base path isn't even restored to its original condition.  It doesn't even make the change in the context of a transaction.  So if the user hits undo, the base path is not restored.

I don't think Dressups should ever modify the properties of the base path but if there was a legitimate reason to do so, deleting or undoing should absolutely restore the original.

**Comment by IchGucksLive** [comment]
@sliptonic  The Base operation is moving around a Sharp edge in free AIR 
The intirer dressup is not designed for ZERO Path operation its for CRC use BUT it workes on Zero
THE Base operation graps a point not in the Middle of the generated Extra Arc 
So it is realy hard to find the edge angle to deal with 
and This Then will only work at closed Contours as you need the end to get to all thepoints 
So it is best to get a non radial move to the edges and move in out there 

I agree on setting Back the edge mode on deleting the dressup

**Comment by mlampert** [comment]
A dressup MUST NOT modify the base op, under no circumstances. In fact nothing can modify an op (base or not) other than the op itself.

**Comment by IchGucksLive** [comment]
@mlampert @sliptonic @luzpaz  @realthunder 
OK Agree 
BUT Why is the BASE at all SET to Round not to Square 
Allmost every Beond operation having problems to handle a Round edge in 
Cpoudent that be changed to the oposit  " Square" in the First place 
WE are Off Contour talking on a "Free Air Move " inside or outside the user needs to care 
Giving it a Warning and nothing  to see will end up in a non using Function 
Most willl see nothing  on first enter or Mashine will Fail or Gauging 
THE Problem is the System Startpoint is only NEAR and in line from 0,0,0 to Boundingbox
NOT the Midpoint of the System created  non edge related ARC 
This point is very hard to handle especial on non closed edges

**Comment by IchGucksLive** [comment]
non working User Commit

**Pull request closed without merging**
