### PR TITLE
BIM: Move urls outside translated strings

### PR DESCRIPTION
**Pull request by 3x380V**
Leaving urls outside translated strings prevents translations from being updated on url change.
[Python F-strings](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals) suggested by @furgo16

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Are you sure these f strings are correctly picked by lupdate? That might be worth checking... Lupdate is very picky :/

**Comment by furgo16** [comment]
Good point. I've not found a definitive answer in the Qt documentation, but a quick search returns hints (e.g. [this comment](https://github.com/Slicer/SlicerLanguagePacks/issues/8#issuecomment-1076849866)) that `lupdate` unfortunately does not yet support Python F-strings.

**Comment by 3x380V** [comment]
Ah, there is an answer already. I could save myself some time spent with testing. Anyway `src/Tools/updatets.py` seems to list `Arch` only as a context and running that script produces quite large diff. I'll revert to replace and remove Draft status.

**Comment by yorikvanhavre** [comment]
Super! Thanks!

**Pull request merged**
