### PR TITLE
[Bugfix]Spreadsheet: fix multi-screen management of QtColorPicker

### PR DESCRIPTION
**Pull request by 0penBrain**
+ set parent when instantiating

https://forum.freecadweb.org/viewtopic.php?f=3&t=72547

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7604">pipeline status</a> for feature branch [PR_7604](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7604). Pipeline [666153918](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/666153918) was triggered at [f1178a2](https://github.com/FreeCAD/FreeCAD/pull/7604/commits/f1178a2fb4d661e9095f4f9c111458554a8d46ae). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
I think according the GPL/LGPL, we should warn the owner of the code.
But I have no clue who it can be today (Qt Solutions should be from the days of Trolltech...). @chennes @wwmayer any idea ?

**Comment by chennes** [comment]
I think the relevant section of the LGPL 2.1 is Section 2, relating to our obligations if we make modification to the file:

> b) You must cause the files modified to carry prominent notices stating that you changed the files and the date of any change.

> c) You must cause the whole of the work to be licensed at no charge to all third parties under the terms of this License.

It is my understanding of the license that we don't have to actively push code out to the copyright owner (or anyone else), but must provide it under the same license.

**Comment by 0penBrain** [comment]
@chennes thanks. So from this, should I add something in the file header explicitly saying the file has been modified ?

**Comment by chennes** [comment]
Yes, that's my read of the LGPL.

**Comment by 0penBrain** [comment]
@chennes Well, I'm not a wording expert. Is that OK ?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7604">pipeline status</a> for feature branch [PR_7604](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7604). Pipeline [667943598](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/667943598) was triggered at [d858565](https://github.com/FreeCAD/FreeCAD/pull/7604/commits/d858565327d110938afa17a1c1f8df502df24713). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Yeah, I think that note is clear.

**Comment by 0penBrain** [comment]
@chennes @donovaly how about backporting this one?

**Comment by chennes** [comment]
Yeah, good idea -- do you want to submit a separate PR, or do you want me to cherry-pick the commit?

**Comment by 0penBrain** [comment]
If you have a local checkout of the 0.20 branch already, please do. :)

**Pull request merged**
