### PR TITLE
Fix #10545 #11200 by using position of array members

### LINKED ISSUE #10545: [Problem] Exporting a link array object gives an incorrect result
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When exporting a part made with the draft array tool to either stl or 3mf format, upon importing the object into another tool it's as if the array tool was not applied at all. 

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.2
[/code]
```

### Subproject(s) affected?

Core

### Anything else?

Applying a compound or connect operation after the array tool then exporting gives the result I would expect from just exporting the array object. Importing an exported 3mf of an array object into prusa slicer shows the array subelements are placed directly on top of each other, so possibly the array intervals are not being applied on export to the subelements?

Test case of a 3x3 array of cubes, exporting the part called "failure" gives an incorrect result, the two "success" parts work as expected.
[arrayexportbug.zip](https://github.com/FreeCAD/FreeCAD/files/12517045/arrayexportbug.zip)

Result of importing the failure and success parts exported as 3mf into prusa slicer, with the 9 stacked failure subelements selected.
image

Result when importing exported stl's for the same parts.
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bgbsww**
Fix #10545

### CODE REVIEW

**Comment by bgbsww** [comment]
Looks like #11200 might also be related?

**Comment by bgbsww** [comment]
Fix #11200

**Comment by adrianinsaval** [comment]
@wwmayer could you check this? if the PR is right then I'd like to merge and backport before the point release

**Comment by wwmayer** [comment]
I can confirm that it fixes the issue.

**Comment by luzpaz** [comment]
Thank you @bgbsww !

**Comment by bjnobre** [comment]
What version will the fix be available in?

**Pull request merged**
