### PR TITLE
Replace FC_CONSOLE_FMT macro with concrete code.

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- n/a Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Unfortunately this PR copies many changes of PR 2545 and thus creates many file conflicts. Besides this there are a few issues (look at the travis build log):
* for Qt4 the build stops because QByteArray has no member toStdString
* Console.h:854:17: warning: format not a string literal and no format arguments [-Wformat-security]
* Console.cpp:588:11: warning: ‘check’ may be used uninitialized in this function [-Wmaybe-uninitialized]

**Comment by ezzieyguywuf** [comment]
I will look at these conflicts and issues. Previously, Travis build we’re
failing for unrelated reasons so I did not have this feedback

**Comment by ezzieyguywuf** [comment]
I bet I screwed up the rebase. This is intended to use the PR you reference as a starting point, so there shouldn’t be file conflicts

**Comment by ezzieyguywuf** [comment]
I bet I screwed up the rebase. This is intended to use the PR you reference as a starting point, so there shouldn’t be file conflicts

**Comment by ezzieyguywuf** [comment]
@wwmayer thanks again for the comments - I've addressed all of them except one (waiting for the compile to finish to run unit tests before pushing).

Regarding "Console.h:854:17: warning: format not a string literal and no format arguments [-Wformat-security]" - according to my research, this warning is raised due to printf (and snprintf, sprintf) expecting the first argument to be a string literal. While this is not a requirement enforced in the function signatures, it seems in general to be a "good idea" due to issues that may arise from accepting a variable instead of a char constant.

[This SO questio](https://stackoverflow.com/questions/9707569/c-array-warning-format-not-a-string-literal) addresses the topic a bit, as does [this SO answer](https://stackoverflow.com/a/32362969/4608626) and it's discussed at length [here](https://www.owasp.org/index.php/Format_string_attack).

I should point out - my code does not introduce this vulnerability. This is inherent in the original design decision to try and emulate the sprintf-style string formatting (as opposed to utilizing sprintf directly). I guess, for whatever reason, the original implementation somehow masked the warning.

Therefore, I can think of two potential fixes for this warning. I'm open to doing either:

1) Do nothing - keep the code-base as is, and use a macro around the code in question to eliminate the warning.
2) Get rid of the need for the sprintf and snprintf call that raises the warning. This would require replacing all uses of "Message", "Log" etc...that use the string formatting with code that calls sprintf directly.

Do you have any thoughts on this?

**Comment by ezzieyguywuf** [comment]
@wmayer all tests pass, only outstanding issue is the -Wformat-security I mentioned in my previous comment

**Comment by wwmayer** [comment]
> I should point out - my code does not introduce this vulnerability.

True. It's still up to the client code that it uses these methods like printf() correctly.

> Do you have any thoughts on this?

What do you think about something like Qt's QByteArray class with its arg() methods? An easy way for now could be to additionally offer the methods Message(const QByteArray&) and friends and in client code the QByteArray must be created with QByteArray("...").arg(....).arg(...). Here we have the safety that the compiler will detect invalid/unsupported arguments. (I did something similar for the Command::doCommand with Command::runCommand that accepts a QByteArray.)

In the second step the code will be moved to the QByteArray version and once finished the old variadic versions will be removed. This of course will be a long-term goal, then.

Another alternative is to use stringstream but IMO its usage is quite inconvenient.

**Comment by ezzieyguywuf** [comment]
I think it's [QString](https://doc.qt.io/archives/qt-4.8/qstring.html) that has the [arg method](https://doc.qt.io/archives/qt-4.8/qstring.html#arg), I didn't see any in [QByteArray's documentation](https://doc.qt.io/archives/qt-4.8/qbytearray.html).

That being said, this is definitely an option. I've seen a design pattern that goes something like this:

```template<type T>
void add(T a, T b)
{
    return a + b;
}

template<type T, type U, type...Args>
void add(T a, U b, Args&&... args)
{
    return a + add(b, std::forward<Args>(args)...);
}
```

(untested, consider it pseudocode) whereby the overloaded variadic template ultimately terminates in a base case. We could do something similar to process all the arguments passed using QString::arg.

In terms of eliminating the variadic code altogether, I am very much in favour of this. In fact, I was already considering this for my next Console update pull-request.

The plan was essentially to convert all the code which uses the sprintf-style formatting with the streaming-style.

You say, however, that you think the streaming syntax is inconvenient: do you think, then, that we must somehow maintain support for sprintf-style formatting? Personally, I don't find the streaming syntax all that cumbersome:

```std::cout << "Loc(" << pnt.X() << "," << pnt.Y() << "," << pnt.Z() <<")" << std::endl;
// compared to
printf("Loc(%s,%s,%s)\n", pnt.x(), pnt.Y(), pnt.Z());
```

Sure, it is a bit more verbose, but in my opinion it is also less error-prone, easier to debug, etc...

**Comment by wwmayer** [comment]
> I think it's QString that has the arg method, I didn't see any in QByteArray's documentation.

Yes, you're right. Actually I first wrote QString but replaced it with QByteArray because it's closer to a C string and thought that QByteArray has these methods too but obviously I was wrong.

**Comment by ezzieyguywuf** [comment]
Fair enough - I can definitely see an argument for keeping the sprintf-style syntax around.

Do you want me to update this PR with the QString mentioned, or include it in my next Console update?

**Comment by ezzieyguywuf** [comment]
Here’s another thought:

```cpp
#define FC_ERR(msg, ...) Base::Console::NotifyError(sprintf(msg, ##__VA_ARGS_));
```

This way, the ConsoleSingleton methods don’t need to be variadic , we simply use sprintf directly

**Comment by wwmayer** [comment]
> This way, the ConsoleSingleton methods don’t need to be variadic , we simply use sprintf directly

But that's very similar to what we have now and doesn't help to reduce the amount of C macros. Besides that this example is not correct strict ISO C++11 code because for a variadic macro you have to pass at least one argument for the __VA_ARGS_ because otherwise the compiler prints a warning with the option -Wpedantic

It's one of my long-term goals to improve the code quality that with -Wpedantic no warning is generated any more. With the current code because it fails because of the macros in Link.h, in DocumentObserverPython.h and the macro FCMD_OBJ_CMD2

**Comment by ezzieyguywuf** [comment]
> But that's very similar to what we have now and doesn't help to reduce the amount of C macros

While it is similar, it does improve somewhat by utilizing sprintf directly rather than trying to duplicate the effect of sprintf in ConsoleSingleton. the `FC_ERR` macro in my example expands to `Base::Console::NotifyError(sprintf("my error is %s", "--an error--"));`, which is (in my opinion) preferable.

> Besides that this example is not correct strict ISO C++11 code

This is a very good point. My first thought would be to overload the macro with something like `#FC_ERR(_msg) Base::ConsoleSingleton::NotifyError(_msg)` but this too I think poses problems, as I don't believe it is possible to overload macros like this. Maybe simply changing

```cpp
//from this
#define FC_ERR(msg, ...) Base::Console::NotifyError(sprintf(msg, ##__VA_ARGS_));
//to this 
#define FC_ERR(msg, ...) Base::Console::NotifyError(sprintf(msg, __VA_ARGS_));
```

Is enough? By eliminating the `##`', the trailing comma remains when `__VA_ARGS__` is empty, thus resulting in a syntax error that is caught by the compiler. In this case, the user would be expected to call `Base::Console::NotifyError` directly

> It's one of my long-term goals to improve the code quality that with -Wpedantic

A worthy goal indeed, I fully support such an effort.

Given the issues you've brought up, what about a compromise: what if we replace every instance of:

```cpp
Base::Console().NotifyError("sprintf-substitution %s", "rocks");
```

with:

```cpp
Base::Console().NotifyError(sprintf("sprintf-substitution %s", "rocks"));
```

This is slightly more verbose, but makes it very clear what is going on, and only adds minimal overhead to the developer that prefers to use the sprintf-style syntax rather than the more modern c++ streaming syntax.

Another alternative (which again resorts back to macros) would be to create something like:

**Comment by wwmayer** [comment]
> Base::Console().NotifyError("sprintf-substitution %s", "rocks");

This isn't possible anyway because the Notify* methods accept a single C string and are not variadic.. I guess you meant the methods Log(), Message(), Warning(), Error() instead.

> Base::Console().Error(sprintf("sprintf-substitution %s", "rocks"));

But I don't see a benefit of this. I don't think that the implementation of Log(), Message(), Warning(), Error() is wrong. And when using sprintf() then the first argument must be a string buffer and it's up to client code to make this buffer big enough. So, IMO it's more typing work and more error-prone.

**Comment by wwmayer** [comment]
An alternative could be boost's format class which can be conveniently used:
https://www.boost.org/doc/libs/1_66_0/libs/format/doc/format.html

**Comment by ezzieyguywuf** [comment]
Typically i'm averse to using boost, however as FreeCAD already has it as a dependency this may be a valid option.

Generally I think the two best options are the two ideas you proposed:

1. Using `QString.arg()`
2. Using `boost::format`

I'm willing to put together a PR using the `QString` approach - I'm already [working on a large Console update PR](https://gitlab.com/ezzieyguywuf/FreeCAD-1/tree/pull_request_nosquash/console_updates_v2), and I can include this in there.

**Comment by wwmayer** [comment]
> I'm willing to put together a PR using the QString approach

Please wait! I will play a bit with boost::format, first.

**Comment by wwmayer** [comment]
Look here:
```cpp
#include <type_traits>
#include <boost/format.hpp>

std::string toStr(boost::format& f) {
    return f.str();
}

template<typename T, typename... Args>
std::string toStr(boost::format& f, T&& t, Args&&... args) {
    return toStr(f % std::forward<T>(t), std::forward<Args>(args)...);
}

template<typename... Args>
std::string print(std::string s, Args&&... args) {
    boost::format f(s);
    return toStr(f, std::forward<Args>(args)...);
}


int main( int argc, char ** argv )
{
    try {
        std::string five("5");
        std::cout << print("%1%+%2%+%3%+%4%+%5%", 2, "3", five, "7.0", 0.1) << std::endl;
        std::cout << print("%d+%s+%s+%s+%f", 2, "3", five, "7.0", 0.1) << std::endl;
    }
    catch (const std::exception& e) {
        std::cout << e.what() << std::endl;
    }
}

```
The only downside is that the format specifiers must start and end with a % when using a number which might be a bit unexpected for Qt users. But it also supports the old C-style format strings.

Here the same with Qt:
Or with Qt:
```cpp
#include <type_traits>
// This is required
#undef QT_NO_CAST_FROM_ASCII
#include <QString>


std::string toStr(QString& f) {
    return f.toStdString();
}

template<typename T, typename... Args>
std::string toStr(QString& f, T&& t, Args&&... args) {
    return toStr(f.arg(std::forward<T>(t)), std::forward<Args>(args)...);
}

template<typename... Args>
std::string printQStr(std::string s, Args&&... args) {
    QString f(QString::fromStdString(s));
    return toStr(f, std::forward<Args>(args)...);
}


int main( int argc, char ** argv )
{
    std::string five("5");
    std::cout << printQStr("%1+%2+%3+%4+%5", 2, "3", five.c_str(), "7.0", 0.1) << std::endl;
}

```
For the QString approach the define QT_NO_CAST_FROM_ASCII must be unset but this is a bit tricky when pre-compiled headers are activated (on Windows) and you have almost no control over the conversion from float or double to a string because QString may limit the number of decimals.
Also you cannot directly convert from std::string to QString.

IMO, the boost approach is more powerful and it may even work without changing any client code. Also boost raises an exception if the number of format specifiers doesn't match with the number of arguments.

**Comment by ezzieyguywuf** [comment]
> IMO, the boost approach is more powerful and it may even work without changing any client code.

Yes, I agree this does seem like the best approach. Although, I would prefer something like this:

```cpp
// This is the current implementation - we could leave this unchanged if we 
// re-implemented ConsoleSingleton::Error and friends using the approach 
// you showed above
Base::Console().Error("A message from %s with %d entries", "tag", 10);

// I would prefer to leave the implementation as you've shown it and require
// the client code to explicitly call the `print` method. This makes it clear what
// is happening and simplifies maintenance.
Base::Console().Error(Base::print("A message from %s with %d entries", "tag", 0));

// For example, we can now easily convert to something like this
Logging::Error("tag") << Logging::print("A message from %s with %d entries", "tag", 0);
```

**Comment by wwmayer** [comment]
> Base::Console().Error("A message from %s with %d entries", "tag", 10);

As shown above this syntax is also supported.

**Comment by ezzieyguywuf** [comment]
So what's the next step?

**Comment by wwmayer** [comment]
What about this?
```cpp
class ConsoleSingleton
{
...
    template<typename ...Args>
    void Message(const std::string& message, Args&&... args) {
        this->DelegateMessage(LogStyle::Message, message, std::forward<Args>(args)...);
    }
...
    std::string toStr(boost::format& f) {
        return f.str();
    }

    template<typename T, typename... Args>
    std::string toStr(boost::format& f, T&& t, Args&&... args) {
        return toStr(f % std::forward<T>(t), std::forward<Args>(args)...);
    }

    template<typename...Args>
    void DelegateMessage(LogStyle level, const std::string& message, Args&&... args) {
        try {
            boost::format fmt(message);
            std::string msg = toStr(fmt, std::forward<Args>(args)...);
            
            // call the observers
            ...
        }
        catch (const std::exception&) {
            // a broken string but better than nothing
            // call the observers with message
            ...
        }
    }


```
You only have to fix DelegateMessage and add the functions toStr()

**Comment by ezzieyguywuf** [comment]
Well, I was leaning more towards a solution [like this](https://gitlab.com/ezzieyguywuf/FreeCAD-1/blob/pull_request_nosquash/console_updates_v2/src/Base/Logging.h#L54), where we get rid of the singleton altogether. Instead, we use [an anonymous namespace](https://gitlab.com/ezzieyguywuf/FreeCAD-1/blob/pull_request_nosquash/console_updates_v2/src/Base/Logging.cpp#L11) to keep track of the static data. From my research, it seems this is a more "c++ style" solution.

The main "issue" (and notice I'm putting this in quotes on purpose - it's not really a problem in the current logging implementation) is with tag-based logging.

You'll notice in my implementation, there is a [single SendLog](https://gitlab.com/ezzieyguywuf/FreeCAD-1/blob/pull_request_nosquash/console_updates_v2/src/Base/Logging.h#L54) function that accepts a `std::string` as a source "tag".

This becomes difficult to implement with a variadic `SendLog` (or `Message` and friends in your example). The reason it is difficult is because how do you know if the user has passed an (optional) source "tag" or if they are providing an argument for the string formatting?

```cpp
Message("a message, %s", "my tag", "hello"); // prints: [my tag] a message, hello
Message("another message, %s", "good bye"); // what does this mean? [good bye] another message, or [default] another message, good bye
```
This is why I prefer to have a separate `format` (or `print` in your example) function, specifically meant to process the string.

**Comment by wwmayer** [comment]
> Well, I was leaning more towards a solution like this, where we get rid of the singleton altogether.

Actually, you don't. The ILogger class is just a wrapper around Base::Console() so that in client code you don't have to use the latter directly. But what is the advantage?

> This becomes difficult to implement with a variadic SendLog (or Message and friends in your example). 

Can't really follow what you want to achieve here.

> Message("a message, %s", "my tag", "hello"); // prints: [my tag] a message, hello
Message("another message, %s", "good bye"); // what does this mean? [good bye] another message, or [default] another message, good bye

At least in this example you can count the number of format specifiers in the first string and the number of additional arguments. If the latter is greater by one then you know the second argument is the tag. If they are equal you know there is no tag at all.
In all other cases the input can be considered as invalid.

**Comment by ezzieyguywuf** [comment]
> Actually, you don't. The ILogger class is just a wrapper around Base::Console() so that in client code you don't have to use the latter directly. But what is the advantage?

The advantage is reducing the burden on the developer for adding logs.

```cpp
// This long form
Base::Console().NotifyError("my message", "MyTag");
// Turns into this short form
Logging::Error("MyTag") << "my message";
// In order to avoid macros
FC_ERROR("my message", "MyTag")
```
If the payoff isn't worth it then I'm OK with getting rid of `ILogger` altogether.

> Can't really follow what you want to achieve here

How about I put together a clean, working example of what I have in mind. Once that is ready I will present it and we can discuss.

> ...you can count the number of format specifiers in the first string...

Yes, this is definitely an option, but this starts to turn a bit "hackey" in my opinion.

Again, how about I put together a clean working proposal and we can go from there.

**Comment by wwmayer** [comment]
> If the payoff isn't worth it then I'm OK with getting rid of ILogger altogether.

The idea looks good to me. The class can be implemented to support the << operators but should also support the variadic template function as shown in my example (this is similar to Qt's qDebug function which supports both ways too). As I understand the string passed to the constructor is the tag name so you shouldn't run into any ambiguities with the variadic template function.

> How about I put together a clean, working example of what I have in mind. Once that is ready I will present it and we can discuss.

That would be best! If you look at the original intention of this PR and what we discuss now are two different topics, actually.
 
> Yes, this is definitely an option, but this starts to turn a bit "hackey" in my opinion.

Yes, I know. It was a suggestion for this concrete example but there might some more tricky situations that cannot be solved so easily. And when re-designing the whole logging concept we should go for an implementation that doesn't cause new problems.

> Again, how about I put together a clean working proposal and we can go from there.

Yes, go ahead! Should we close this PR now?

**Comment by ezzieyguywuf** [comment]
Yes, let’s close the PR: I originally intended it to be a step towards the Logging rewrite , but as you have astutely discovered many of the shortcomings, let’s pick up the conversation when I have a full rewrite complete to discuss

**Comment by wwmayer** [comment]
Closing PR...

**Comment by ezzieyguywuf** [comment]
See forum thread [here](https://forum.freecadweb.org/viewtopic.php?f=10&t=40496&sid=63a4d9b45220fffbdc1556d4064c9bca)

**Pull request closed without merging**
