### PR TITLE
Draft: Change Snap toolbar to standard toolbar

### PR DESCRIPTION
**Pull request by Roy-043**
This PR changes the Draft snap toolbar to a standard toolbar.

Many thanks to @carlopav for all his work on the gui_snaps.py file. I have basically adopted his solution. See https://github.com/carlopav/FreeCAD/tree/Draft_SnapToolbarToStandard.

The code has been tested with the BIM Workbench, for which a standard toolbar cannot be introduced just yet as it still has to work with FC0.20. For the BIM Workbench the snap toolbar is built by reusing the GUI actions that are available because of its Snapping menu. Reusing the available actions is the key to keeping the buttons synchronized. This solution is also used for the updated statusbar snap widget.

The new version of the statusbar snap widget behaves slightly differently. If the Lock button is clicked (short click) snapping is enabled/disabled. A long click on the button will open the menu.

Additionally:
* Some unnecessary imports were removed from gui_snapper.py.
* Renamed the toolbar from "Draft Snap" to "Draft snap". One cap for consistency with other toolbar names.
* Updated PersistentToolbarsGui.py: there now is only one Python toolbar: the BIM Snap toolbar.
* Changed "custom" to "Custom" in the scale widget menu.

Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=61715

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7656">pipeline status</a> for feature branch [PR_7656](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7656). Pipeline [678489238](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/678489238) was triggered at [1eee16e](https://github.com/FreeCAD/FreeCAD/pull/7656/commits/1eee16e9f3cc1e2159eb02ddb09985872925285c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by carlopav** [comment]
kudos @Roy-043 for completing the job i left unfinished! Did you test if everything is fine with Arch module?

**Comment by Roy-043** [comment]
> Did you test if everything is fine with Arch module?

Yes, of course.

**Comment by carlopav** [comment]
Tested, works very well for me. everything is correctly in sync, even the statusbar widget. Great work!

```

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.30694 (Git)
Build type: Release
Branch: master
Hash: 16c52bb18c233a4ed79ac250433327999c8c6a9b
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Italian/Italy (it_IT)
Installed mods: 
  * 3D_Printing_Tools
  * A2plus 0.4.59e
  * ArchDesign
  * bimtester
  * BIM_Workbench 2021.12.0
  * BOLTSFC
  * Curves 0.5.11
  * Defeaturing 1.2.0
  * Design456
  * DynamicData 2.46.0
  * fasteners 0.4.16
  * FreeCAD-BlenderBIM 2022.10.20
  * freecad.archdesign
  * FreeCAD_Assembly4
  * FreeCAD_SketchArch-master
  * IconThemes
  * Manipulator 1.4.9
  * parts_library
  * sheetmetal 0.2.58
  * TabBar
  * trails
```

**Review by carlopav — APPROVED** [review]
Tested, works good here!

**Comment by Roy-043** [comment]
Thanks for testing.

**Comment by yorikvanhavre** [comment]
This is a huge annoying thing that is now solved, kudos @Roy-043 !

**Comment by Roy-043** [comment]
@donovaly This PR should not be backported.

**Pull request merged**
