### PR TITLE
Update org.freecadweb.FreeCAD.desktop with Korean localisation

### PR DESCRIPTION
**Pull request by MarongHappy**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7649">pipeline status</a> for feature branch [PR_7649](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7649). Pipeline [677713781](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/677713781) was triggered at [ea06b26](https://github.com/FreeCAD/FreeCAD/pull/7649/commits/ea06b26a5187bcf3e17086d5e7d759cbf2befb15). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@MarongHappy thanks!
Do you mind re-writing the commit:
`Update org.freecadweb.FreeCAD.desktop with Korean localisation [skip ci]` 
and rebasing ?

**Review by luzpaz — COMMENTED** [review]
:point_up:

**Comment by luzpaz** [comment]
Renamed commit + rebased with [skip ci] enabled since it's not necessary to run CI just for this trivial commit.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7649">pipeline status</a> for feature branch [PR_7649](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7649). Pipeline [680955768](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/680955768) was triggered at [65fb5cd](https://github.com/FreeCAD/FreeCAD/pull/7649/commits/65fb5cd827a07a45e5e26d89e99aa9c93b5e1dd6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7649">pipeline status</a> for feature branch [PR_7649](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7649). Pipeline [680956287](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/680956287) was triggered at [42ced23](https://github.com/FreeCAD/FreeCAD/pull/7649/commits/42ced231851f57d3d1cecbf8a2f8b2b56c725ae7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by luzpaz — APPROVED** [review]

**Comment by chennes** [comment]
@luzpaz it doesn't look to me like the XDG specification requires us to localize `name` just because we are localizing `comment` and `genericname` -- is my reading incorrect?

**Comment by chennes** [comment]
(I'm going to merge this as-is, but we should try to figure out if we can basically remove all of the "name" localizations).

**Pull request merged**
