### PR TITLE
[FEM] Elmer: add support for 3D magnetodynamics

### PR DESCRIPTION
**Pull request by donovaly**
- adds the corresponding Elmer equation (it is now possible to do Elmer's tutorial example no. 14)

### CODE REVIEW

**Comment by donovaly** [comment]
Here is a FreeCAD file that is basically Elmer's tutorial no. 14: 
[MagneticFieldWire.zip](https://github.com/FreeCAD/FreeCAD/files/10671447/MagneticFieldWire.zip)

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [769347816](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769347816) was triggered at [2cb9a77](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/2cb9a774156d574e826184b692200577bc6e0ab4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [769352949](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769352949) was triggered at [8babca8](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/8babca8f9cb5c174128401d072d618fff1dca152). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [769653432](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769653432) was triggered at [b358131](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/b358131c4c8fbb8621304d2f484b135e3d4bb1c8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [769659494](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769659494) was triggered at [f800a68](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/f800a68104909eb2188c026729dc1710e2d9d14a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [769694944](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769694944) was triggered at [86e0af7](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/86e0af7af8f473790230057e8c6dd97dad77dae8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [769700350](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769700350) was triggered at [c15cabb](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/c15cabb2554964965c2ac1355a9c43c78bcd75b4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [769889242](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/769889242) was triggered at [a3dc8e2](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/a3dc8e2c65d7a4f57691d55ecebb1dd13037921b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [770055163](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770055163) was triggered at [ffd88f0](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/ffd88f07b2f14e812db144524122b1257b83219d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [770515195](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770515195) was triggered at [e4d72c6](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/e4d72c6d113f8696c68f157d99e4d6cf732f339f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [770666851](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770666851) was triggered at [59f03c8](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/59f03c803b459030eddcaddc457d2aaf4be3ee99). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [770668884](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770668884) was triggered at [2b4e516](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/2b4e51637c2ac1414f838b225a035a7aed90980c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [770683574](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770683574) was triggered at [73d0abc](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/73d0abcd41c0ee8e96853a62d9468cb3658cc362). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [770699470](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/770699470) was triggered at [61c6128](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/61c6128ebe480dff3e8a75ba6728e50ee5deb38a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [771317440](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/771317440) was triggered at [356bc58](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/356bc58acf71c6f4b8c15ed42479bfc4e5b3553f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [771481937](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/771481937) was triggered at [9f3e50e](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/9f3e50e5279f8476fe07ff51885674981ef56df4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [771698024](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/771698024) was triggered at [8f64857](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/8f6485743bc698c7edce235e81aa141d7a5b564e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [771997382](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/771997382) was triggered at [5f65bf9](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/5f65bf9bab6c1d6fbebb531813a3a8b213b400dc). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [772132603](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/772132603) was triggered at [670e205](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/670e205e58292f94f15bdaade4b87c8ea45c17a8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Minor fix: Add missing opening square bracket to commit title

Screenshot_20230209_091209

`git commit --amend -m "[FEM] Elmer: add support for 3D magnetodynamics" -m "- adds the corresponding Elmer equation (it is now possible to do Elmer's tutorial example no. 14)"`

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [772724188](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/772724188) was triggered at [6d9d771](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/6d9d771d7da1d87fe0aa940644df794a0bf95224). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [773279725](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/773279725) was triggered at [2d0d353](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/2d0d35325cc68cff84ca297b1590bc3dc633090c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [773281646](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/773281646) was triggered at [c5364e6](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/c5364e6f83972e2cfc7dd73cc78ded391d28623c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [774209845](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774209845) was triggered at [754d28e](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/754d28e45a92b7dfbe8a3e149902662469b2ec7c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [774261731](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774261731) was triggered at [ae3e29e](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/ae3e29eacfb8a22b8dcd0fe3a79e809dfc25c6c0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380">pipeline status</a> for feature branch [PR_8380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8380). Pipeline [774268025](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774268025) was triggered at [59279dc](https://github.com/FreeCAD/FreeCAD/pull/8380/commits/59279dc1aee3cb7294993198fc8911f40fdf980e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
