### PR TITLE
[TD] more preferences work

### PR DESCRIPTION
**Pull request by donovaly**
- General: add missing tooltips, rearrange 2 color entries, uniform wording
- all tabs: uniform right-alignment for spin boxes
- Dimensions: add icons and clarify option name

### CODE REVIEW

**Comment by WandererFan** [comment]
resolved conflicts in 2 ui files.

**Comment by WandererFan** [comment]
Hmmm.  Won't let me merge.  Trying "update branch".

**Comment by donovaly** [comment]
Damn, it is still fishy. I'll work to get a mergeable PR.

**Comment by donovaly** [comment]
Now it is OK, ready to be merged.

**Comment by WandererFan** [comment]
Still won't let me merge.  I'll try updating it once more.  If that doesn't work, I'll pull & push.  Maybe that will help.

**Comment by donovaly** [comment]
> If that doesn't work

Than give me a go to close this PR and create a new one. This fiddling with UI files is too time consuming.

**Comment by donovaly** [comment]
> 
> 
> > If that doesn't work
> Than give me a go to close this PR and create a new one.

here it is: #3196

**Pull request closed without merging**
