### PR TITLE
[020] [Expressions] auto-completion fixes

### PR DESCRIPTION
**Pull request by Syres916**
Thanks to @acpopescu for the help on this regression

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9123">pipeline status</a> for feature branch [PR_9123](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9123). Pipeline [822980185](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/822980185) was triggered at [0575bcc](https://github.com/FreeCAD/FreeCAD/pull/9123/commits/0575bcc826ad510c26d44e4c2b2d3503eda9ab2c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Syres916** [comment]
I tried integrating the master commits into my 0.20 branch but there were some subtle differences which I wasn't happy with hence having to create a specific PR for this tested on my own system.

**Comment by Syres916** [comment]
This PR is ready to merge IMHO, please advise if it's unacceptable.

**Comment by adrianinsaval** [comment]
@donovaly consider including this backport before 0.20.3 if it's still happening

**Comment by Syres916** [comment]
I really do not understand why only one member of the merging team can merge this PR. Surely @wwmayer , @chennes or @0penBrain are perfectly capable of reviewing this PR. There have been other recent commits to the 020 branch in the last few days so I don't think we can class it as redundant.

**Comment by 0penBrain** [comment]
Is is so critical a bug that it needs a backport (dummy question) ?

**Comment by Syres916** [comment]
For me this has been the one of the longest regressions from the 0.19 Dev cycle, that's 4 years so I'd say it's very important.

**Pull request merged**
