### PR TITLE
[Notif area] Fixes and disable for 0.21

### PR DESCRIPTION
**Pull request by PaddleStroke**
This does : 
- Fix a ui bug, if area disabled when you open the pref page, the rest of the parameters are not disabled. 
- remove unecessary qmessagebox
- Disable area by default for 0.21 bacause it is not polished enough yet.

I have no strong feeling for the disabling, someone told me that it's not polished enough yet to the point of being very annoying. So I suggest disabling it for the 0.21 release and re-enable it in next development cycle to enable polishing it.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by sliptonic** [comment]
I concur.  The youtube video by Mango Jelly (Linked at the end of the release notes) praises the feature.  Many people like it because it permits turning off the report view and not having it repeatedly re-enabled. 
Other people dislike it and find it overly intrusive.  
I use i3 window manager and it doesn't behave well there.  
I have no strong feelings about enabling or disabling for 0.21.  All things being equal, I agree with @PaddleStroke and think it should be off for 0.21 and then re-enabled for further polishing.

**Comment by PaddleStroke** [comment]
To the maintainer, if you decide not to disable it, the 3 first commits are still worth making it.

**Comment by PaddleStroke** [comment]
Just clicked on the wrong button

**Comment by FEA-eng** [comment]
I definitely agree that the new "notification area" feature still needs some polish and should be deactivated by default for now. I disabled it in weekly builds because I found it to be actually more intrusive than the standard notification system.

**Comment by chennes** [comment]
Thanks for the PR. I don't mind the notification area, and as a developer it does make me consider more carefully that sorts of things I make "error" vs. "warning" vs. "message", which I think is a good thing in the long term. That said, I am OK with setting it to default to off in the 0.21 release. It feels a bit "untidy" to me to have a PR to disable it, and then basically another that immediately re-enables it. Maybe it would make more sense to take that commit and only apply it to the release branch (once it's been created) -- that way it's explicit that the change is only intended to apply to the release, and not to the development (master) branch. @sliptonic, @adrianinsaval, what do you think of that strategy?

**Comment by adrianinsaval** [comment]
Sounds good!

**Comment by chennes** [comment]
OK, the first three commits have been cherry-picked and pushed to master.

**Comment by chennes** [comment]
I've created releases/0.21 and cherry-picked the last commit into it. Closing now.

**Pull request closed without merging**
