### PR TITLE
DO NOT MERGE, CI improvement test

### PR DESCRIPTION
**Pull request by berndhahnebach**
test to automatically start CI for PRs ... 

cheers bernd

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685">pipeline status</a> for feature branch [PR_6685](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685). Pipeline [504679539](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/504679539) was triggered at [8a3d983](https://github.com/FreeCAD/FreeCAD/pull/6685/commits/8a3d983b191c5f4b5a3990b8aefcd6cfe6d0ff1b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685">pipeline status</a> for feature branch [PR_6685](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685). Pipeline [504686791](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/504686791) was triggered at [f821339](https://github.com/FreeCAD/FreeCAD/pull/6685/commits/f821339aad10446706507fff30317d8c037731e9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685">pipeline status</a> for feature branch [PR_6685](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685). Pipeline [504698261](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/504698261) was triggered at [855292a](https://github.com/FreeCAD/FreeCAD/pull/6685/commits/855292a9bba05b078b84507a2e61737a997a34cb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685">pipeline status</a> for feature branch [PR_6685](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685). Pipeline [504712109](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/504712109) was triggered at [d8a0624](https://github.com/FreeCAD/FreeCAD/pull/6685/commits/d8a06246e4fd02911b503eafb9319be7fc30e0b9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
works :-)
The CI for new PRs or updated PRs should start in less than 5 minutes.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685">pipeline status</a> for feature branch [PR_6685](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6685). Pipeline [504771178](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/504771178) was triggered at [a87c49e](https://github.com/FreeCAD/FreeCAD/pull/6685/commits/a87c49ef3d89eb4925fbde0d2e94ba6cb729516c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
reopentest

**Comment by freecadci** [comment]
> If I'm not mistaken the status of the build is also shown as one of the checks of the PR, and it's a little annoying to get emails for bot comments on PRs I have commented

should be discussed with all others too.

**Pull request closed without merging**
