### PR TITLE
Part/Toponaming: test for makeElementWires

### PR DESCRIPTION
**Pull request by CalligaroV**

### CODE REVIEW

**Comment by CalligaroV** [comment]
Opened in draft status until all the tests for makeElementWires have been added

**Comment by maxwxyz** [comment]
@CalligaroV not sure if relevant for feature freeze on 2024-06-03 but also a heads up on this PR

**Comment by chennes** [comment]
I'm going to close this one as no longer relevante - @CalligaroV if that's wrong please go ahead and re-open.

**Comment by CalligaroV** [comment]
Hi @chennes!

I agree. Most of the new methods added for `makeElementWires` are already tested (directly or indirectly) with tests added in other PRs.

If in the future we'll open issues caused by those methods we may add specific tests.

**Pull request closed without merging**
