### PR TITLE
[Icons]Revision of TechDraw Icons(Dimension_Pointer)

### PR DESCRIPTION
**Pull request by Reqrefusion**
#14145
Solve: https://github.com/FreeCAD/FreeCAD/issues/14203
TechDraw_Dimension_PointerTechDraw_Dimension_Pointer

### CODE REVIEW

**Review by kadet1090 — CHANGES_REQUESTED** [review]
This icon should be consistent in terms of stroke with one in the sketcher: https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Sketcher/Gui/Resources/icons/constraints/Constraint_Dimension.svg 

It should be only recolored from red to yellow while keeping the slight gradient / double stroke. 

Additional stroke for the crosshair is OK.

**Comment by Reqrefusion** [comment]
It's a nice icon, but I think the icon I proposed is more readable. And readability is more important in my opinion. So I won't be able to make any changes.

**Comment by maxwxyz** [comment]
There were some concerns in the closed PR about this one so we should hold it back until resolved.

**Comment by Reqrefusion** [comment]
> There were some concerns in the closed PR about this one so we should hold it back until resolved.

These problems were also mentioned in the related issue.  You were there too. I don't understand why you keep repeating these. Please see the relevant issue.

**Comment by maxwxyz** [comment]
Like here from yesterday: https://github.com/FreeCAD/FreeCAD/pull/14145/files#r1649621525

**Review by kadet1090 — APPROVED** [review]

**Comment by Reqrefusion** [comment]
The desired icon has been switched. However, I have to say that the desired icon is not suitable for the guide. But it doesn't matter.

**Review by maxwxyz — APPROVED** [review]

**Pull request merged**
