### PR TITLE
Tests: Demonstrating a failed test

### PR DESCRIPTION
**Pull request by chennes**
This is a PR with a failing GTest for debugging Issue #9170.

ETA: Actually, it's demonstrating two problems! The first is that I recently added a new test target but didn't add it to the CI, and the second is the problem I meant to demo, a failing gTest.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9367">pipeline status</a> for feature branch [PR_9367](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9367). Pipeline [845798938](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/845798938) was triggered at [a305f6b](https://github.com/FreeCAD/FreeCAD/pull/9367/commits/a305f6bd3f273ba931972488fc1f212886026068). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9367">pipeline status</a> for feature branch [PR_9367](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9367). Pipeline [845800036](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/845800036) was triggered at [c60a451](https://github.com/FreeCAD/FreeCAD/pull/9367/commits/c60a4512dff0979dc7c3a27bc1f926728f7294f7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
I've got a PR in process to add the Sketcher unit tests to the CI: #9368. @0penBrain do you want me to refactor that now so that all the C++ unit tests are grouped together into a single workflow, or ca/should that wait until there are more than two? In the long run every Mod with C++ code should have an entry.

**Comment by 0penBrain** [comment]
> @0penBrain do you want me to refactor that now so that all the C++ unit tests are grouped together into a single workflow, or ca/should that wait until there are more than two?

I think you can start refactoring right now. 😉 You probably can't use a reusable workflow for this, but I think a "master" composite action that in turns calls a generic composite action several times with appropriate parameters should be possible.

**Comment by berniev** [comment]
Please consider that many so-called "unit tests" are in fact "integration tests". I ask the two be kept separate.
Even the simplest search, wikipedia, will explain the difference. Unfortunately this is not yet well understood at FreeCAD but if not kept separate will lead to problems later.

**Comment by adrianinsaval** [comment]
> but if not kept separate will lead to problems later.

what would those problems be?

**Comment by berniev** [comment]
`Unit tests` come into their own when a large body of same are developed, each targeting a very small, isolated, "unit" of code. They run VERY fast. Because of the speed, a developer can run unit tests very frequently. This leads to the concept of TDD (Test Driven Development).

The problem though, is getting the code into so-called `testable` state. That is to say in a form where unit tests can be applied, which is dictated by dependencies, statics, singletons, complexity. Basically much of the stuff espoused by the likes of Uncle Bob Martin and others over the last 20 + years. FreeCAD is large, old legacy code, and in the main not `testable`.

As FreeCAD has not been written with unit tests in mind, the alternative is to perform so-called integration tests. These each encompass a range of classes, files etc in each test. Typically, due to the many dependencies, they run much, much slower.

FreeCAD has say 5000 classes etc. If each has say 20 tests, and they each take 20mS that is 33 minutes run time. They will not be run very frequently!

I have had well over 100 unit tests and cannot get the run time to register 1 mS. 

A **_single_** integration test introduced for metadata took variously from 8 to 120 mS.

Integration tests aare terrific, just keep them separate.

**Comment by chennes** [comment]
I'm not sure why during development you'd ever run the full test suite -- why not run just the tests for the code you're working on?

**Comment by berniev** [comment]
Google: "why unit tests must be fast". 137,000,000 answers. I politely suggest you study the subject a bit more.

You are not alone. Stating last year that FreeCAD is largely legacy code brought howls of derision from a senior FC person. Similarly, my suggestion last year that FreeCAD should have unit testing brought stern admonition from a different senior FC person "we already do unit testing". Old attitudes die hard.

The things that make unit testing possible (SOLID etc etc) are not generally understood or practised at FreeCAD, so understandably unit testing and its benefits are similarly difficult to absorb.

One of my aims in introducing unit testing was not only for new work, but to begin converting legacy code to the newer style demanded by unit tests.

OTOH, once code is testable the benefits of that, including unit testing, become apparent. It just may take a while.

**Comment by chennes** [comment]
Feathers suggests a good target is 1/10th second per unit test max: that seems reasonable. In C++, compilation and linking time still dwarfs runtime for the tests for us, and will for quite some time. And if you're doing TDD, you're only running the tests on your units, so it will remain so. When you run the whole suite things like DLL load time can be amortized: for example, loading Xerces-C into memory does take a comparatively long time, something like 10ms, but it only has to happen once per executable.

**Comment by berniev** [comment]
Feathers was written in 2005. He also makes a point of expecting all tests to go MUCH faster in future. He is also targeting unit tests.

For someone who is not literate in modern software design principles (SOLID etc --remember I've looked at your code), just started writing some integration tests which to this day you stilll call unit tests, never done TDD, you sure are determined to be the expert.

Again, I suggest you study the subject matter in much more detail.

**Comment by 0penBrain** [comment]
@berniev I'm gonna be honest. Your recurrent pedantic blabla looking like a schoolteacher having a superiority complex isn't going to help in any way.
As well for repeating the same again and again in any forum thread / issue / PR that has some direct or indirect concern with unit tests. It just clutters other's work.
I'd advise you place your efforts in improving things for real.

**Comment by sliptonic** [comment]
> For someone who is not literate in modern software design principles (SOLID etc --remember I've looked at your code), just started writing some integration tests which to this day you stilll call unit tests, never done TDD, you sure are determined to be the expert.
> 

This comment is inappropriate.  It's rude, doesn't assume the best intentions of people, and is counterproductive. Consider yourself warned.  Future comments like this will receive formal reporting.

**Pull request closed without merging**
