### PR TITLE
[TD]fix scaling of large hatch tiles (fix #17276)

### LINKED ISSUE #17276: TechDraw: Svg Hatch not shown for Large Hatch Scales
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If the HatchScale is set to a large value (20x in the sample file) the hatch pattern does not appear.

Forum post: [13832](https://forum.freecad.org/viewtopic.php?t=91218)

### Full version info

```shell
OS: Linux Mint 21.2 (X-Cinnamon/cinnamon/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38977 +1 (Git)
Build type: debug
Branch: fixLargeHatchTiles
Hash: b56f3dd42300dc34884e7bca0fa34a6a67b7d1c3
Python 3.10.12, Qt 5.15.2, Coin 4.0.0, Vtk , OCC 7.8.0
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.21
```

### Subproject(s) affected?

TechDraw

### Anything else?

an example file is attached to the forum discussion.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for #17276.

### CODE REVIEW

**Comment by maxwxyz** [comment]
Is this fixing a regression?

**Comment by PaddleStroke** [comment]
Is this fixing the CI failing? I rebased some PR and they are failing CI on some TD tests.

**Comment by WandererFan** [comment]
CI has the same failure in FEM and CAM. something to do with zipios??

**Comment by WandererFan** [comment]
Not a regression.  Don't think it ever worked.  Not many people scale the hatches to 20:1

**Pull request merged**
