### PR TITLE
Sketcher: Change rendering colors of points.

### PR DESCRIPTION
**Pull request by PaddleStroke**
This PR changes the color of points in sketcher following DWG discussion.

image

1- edges (Line/arcs...) end/start points : Normal geo color (white)
2- Conic centers : construction geo color (blue)
3- Construction point : construction geo color (blue)
4- normal point : normal geo color (white)
5- When a point is coincident to another point : Constraint color (red) (other points colors render on top).
6 - Point tool now creates point that reflect construction mode. ie real point or construction point.
7 - Remove Vertex color from preferences as vertexes now use the geometry colors

Fixes https://github.com/FreeCAD/FreeCAD/issues/12582

@pierreporte let me know if you think it closes https://github.com/FreeCAD/FreeCAD/issues/11919

Partial fix of https://github.com/FreeCAD/FreeCAD/issues/11799, island would still be interesting.

### CODE REVIEW

**Comment by maxwxyz** [comment]
nice! Is it also switching default behavior (defaul point is normal point, toggle to construction geo is construction point)? 
https://github.com/FreeCAD/FreeCAD/issues/12582

**Comment by PaddleStroke** [comment]
Yes Fixes https://github.com/FreeCAD/FreeCAD/issues/12582
I have not changed the icons. I will let you see if it's needed.

**Comment by AjinkyaDahale** [comment]
External geometry from outside the sketch as well as geometry internal to other geometry (focus, center, etc) are treated differently within sketcher. Do you plan to have different colors for both, or just construction?

**Comment by maxwxyz** [comment]
I don't need another one. It's great how its implemented, but the two issues behave differently. Should be treated like the rest.

**Comment by PaddleStroke** [comment]
Can you try again @maxwxyz please?

**Comment by maxwxyz** [comment]
@PaddleStroke yes.
Internal still is blue: 
grafik
External still same behavior:
grafik

**Comment by PaddleStroke** [comment]
image
works on my side

**Comment by maxwxyz** [comment]
ah that was my issue. Yes on external it should be red too otherwise perfect!

**Comment by pierreporte** [comment]
It doesn’t fix #11919. It’s even worse IMO because now there are construction points that appear white, and fully-constrained points will still appear green.

Though I do like the red points for the coincidence constrain but I have no idea about how it’s going to feel for actual work. In any case, turning construction points in blue is good: they should be the same color as construction geometry.

**Comment by maxwxyz** [comment]
@pierreporte have you build it? Construction points are never white. Points are same as the line type (real/constr) and only change when constrained.

**Comment by pierreporte** [comment]
@maxwxyz I never succeeded to build FreeCAD, even using Conda with help.

It was never clear that points at the end of geometry was of the same type of the geometry. It could explains #11920 and I think that it is a bug in itself, or more precisely that it would block resolving #6884.

Also, I find strange that vertex of rectangles and shapes in general are red, that is there is actually two coincident points, when they were not created explicitly. When creating a polyline, rectangle, or other closed shapes, the same point should be reused. There shouldn’t be several points. It would make the coincident constrain stand out more. Actually, in this case, real coincident constrains could be indicated by an icon like other constrains because it will be much less common (similar to Catia).

**Comment by pierreporte** [comment]
By the way, #11919 is still in the list of issues closed by this PR. How to remove it?

**Comment by maxwxyz** [comment]
@pierreporte the are real coincident constraint in all 4 edges of a rectangle. You can delete them and then move all lines individually, so the behavior is correct.
I think it solves #11919 Colors are same as the lines (so all geometry is represented the same way) and can be set with the geometry color in the preferences. Vertex display size outside of the sketch can also be individually set, so there is no need to fix something.
For selecting outside the sketch there is the general problem: https://github.com/FreeCAD/FreeCAD/issues/9205
The visibility with dimension lines on top is another issue which was also brought up here: https://github.com/FreeCAD/FreeCAD/issues/12756#issuecomment-1981648341 so maybe this needs an own issue for the rendering order.
Then regarding color is still this issue open: https://github.com/FreeCAD/FreeCAD/issues/10100

**Comment by pierreporte** [comment]
> @pierreporte the are real coincident constraint in all 4 edges of a rectangle. You can delete them and then move all lines individually, so the behavior is correct.

I get the idea. Maybe there should be a tool to transform a point that is common to two entities into two separate points. It exists in other CAD programs so it wouldn’t be entirely new.

> I think it solves https://github.com/FreeCAD/FreeCAD/issues/11919 Colors are same as the lines (so all geometry is represented the same way) and can be set with the geometry color in the preferences.

We agree that the color should be the same for everything that has the same type. This is precisely why points styles are needed.

> Vertex display size outside of the sketch can also be individually set, so there is no need to fix something.

But then the points between lines can be too big. Their size is good at the moment. The problem is only for normal points.

> For selecting outside the sketch there is the general problem: https://github.com/FreeCAD/FreeCAD/issues/9205
The visibility with dimension lines on top is another issue which was also brought up here: https://github.com/FreeCAD/FreeCAD/issues/12756#issuecomment-1981648341 so maybe this needs an own issue for the rendering order.

This is unrelated. To select something, you have to see it first, which is difficult for normal points.

> Then regarding color is still this issue open: https://github.com/FreeCAD/FreeCAD/issues/10100

I created #11919 to propose a partial solution to #10100. The complete solution is in 3 steps:

1. implement line styles (done)
2. implement point styles (in discussion): this is #11919
3. improve dimensions (in discussion): this is #12036

As explained in other issues, color is not sufficient to distinguish type and constrain status. They are orthogonal things and as such should be displayed by two different visual variations. Currently, there is still a problem of colors being too similar when points of different types are fully constrained, even more in not-so-complex sketches. If you add colored error hints (like for overconstrained geometry), points styles are a need.

If points 2 and 3 are implemented, you can have just two colors: green for fully-constrained geometry and dimensions, and while for everything else. (Personally I wouldn’t be against a slightly muted color for construction geometry but it would be a bonus not a necessity.)

**Comment by maxwxyz** [comment]
> > @pierreporte the are real coincident constraint in all 4 edges of a rectangle. You can delete them and then move all lines individually, so the behavior is correct.
> 
> I get the idea. Maybe there should be a tool to transform a point that is common to two entities into two separate points. It exists in other CAD programs so it wouldn’t be entirely new.

There is, just delete the coincident constraint.

> > Vertex display size outside of the sketch can also be individually set, so there is no need to fix something.
> 
> But then the points between lines can be too big. Their size is good at the moment. The problem is only for normal points.

I'm not sure if they are different.

> > The visibility with dimension lines on top is another issue which was also brought up here: [#12756 (comment)](https://github.com/FreeCAD/FreeCAD/issues/12756#issuecomment-1981648341) so maybe this needs an own issue for the rendering order.
> 
> This is unrelated. To select something, you have to see it first, which is difficult for normal points.

That's what was mentioned there. I'll add it as comment to the next issue:

> 3. improve dimensions (in discussion): this is [[Feature request] Sketcher: more visual differences for dimensions #12036](https://github.com/FreeCAD/FreeCAD/issues/12036)

**Comment by pierreporte** [comment]
> > > Vertex display size outside of the sketch can also be individually set, so there is no need to fix something.
> > 
> > 
> > But then the points between lines can be too big. Their size is good at the moment. The problem is only for normal points.
> 
> I'm not sure if they are different.

It’s rather semantic. My point of view is that normal points are closer to datum points than to construction points. From outside the sketch, construction points are only helper and users should avoid attaching things to them. It it why I believe that normal points should look identical to datum points, and that construction points should remain small.

> > > The visibility with dimension lines on top is another issue which was also brought up here: [#12756 (comment)](https://github.com/FreeCAD/FreeCAD/issues/12756#issuecomment-1981648341) so maybe this needs an own issue for the rendering order.
> > 
> > 
> > This is unrelated. To select something, you have to see it first, which is difficult for normal points.
> 
> That's what was mentioned there. I'll add it as comment to the next issue:

It’s still only one part of the issue. The screenshot in #6884 shows the problem better: the points are barely visible already. This is because the situation is good: the contrast is large enough and the picture was taken so that they should be quite obvious. In real live, they could blend in the shading of the part, be nearly hidden or just viewed from a bad angle. A more obvious shape and size, just for them, would improve the ability of the user to spot them at first sight.

**Comment by PaddleStroke** [comment]
I fixed the external point color when coincident @maxwxyz.

https://github.com/FreeCAD/FreeCAD/issues/11920 is going to be very hard to implement. I cannot handle it now.

**Comment by maxwxyz** [comment]
@PaddleStroke nice, looks good now!

**Comment by chennes** [comment]
@obelisk79 there seems to be some dissent here about the result here: can you give us the "official" read from the DWG?

**Comment by PaddleStroke** [comment]
@chennes I've asked validation of DWG before starting the PR : https://github.com/FreeCAD/FreeCAD/issues/12582#issuecomment-2004761414
So unless opinion shifted since (as not everyone is on discord all the time I guess) it was approved first.

**Comment by obelisk79** [comment]
I am one of the dissenters about this. But the majority liked the idea. I don't think it's an improvement. But I haven't compiled this to test it.

**Comment by yorikvanhavre** [comment]
Merging by consensus during M3 meeting

**Comment by maxwxyz** [comment]
@PaddleStroke not sure if related to this but in the weekly build from today with this included, FreeCAD needs to load 5 sec. after each point I place. Drawing a line, poly line,... After each geometry creation it takes several seconds to be responsive again.

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git)
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * BIM 2021.12.0
  * Curves 0.6.29
  * fasteners 0.5.16
  * OpenDark 2023.12.17
  * sheetmetal 0.4.11

```

**Comment by FEA-eng** [comment]
> Let's see what people think of it...

I think that it's a great improvement. Much better than having all points in red. Now the color actually gives you information, especially about missing coincidences. Creating non-construction points by default also makes sense.

**Comment by pierreporte** [comment]
@yorikvanhavre As said earlier, I’m still convinced that #11919 is not resolved. I already asked to reopen it.

**Comment by maxwxyz** [comment]
So the idea of #11919 is to have additionally a different shape and color switch between 

- normal points, normal constrained points
-  construction points, constrained construction points
- internal points, constrained internal points
- external points
- and coincident variations for all of these incl. different combinations

For the situation in the edit mode I think this is solved by this PR. 
The issue also mentions that points outside of a sketch are not visible enough, this can be set in the preferences for the point size, I think also in the property view of the sketch.
I'm not sure about additional color and shapes introduced in a sketch and outside of it as I think this is a lot of visual distraction and there are some issues about this already. This would definitely need more discussion. 
Also the idea of a different display of points outside of a sketch whether they are constrained or not as mentioned in the other issue needs more discussion as this can go on for each geometry then. I think either the sketch is fully constrained or not and this is displayed in the tree view. In general, your sketches should always be fully constrained.

**Comment by pierreporte** [comment]
@maxwxyz This is the idea:

* Inside edit mode:
  * construction points are round like today,
  * normal points have a different shape,
  * unconstrained construction geometry is blue, including construction points,
  * constrained construction geometry is green, including construction points,
  * unconstrained normal geometry is white, including normal points,
  * constrained normal geometry is green, including normal points,
  * external construction points have the same shape as other construction point,
  * external normal points have the same shape as other normal points.
* Outside edit mode:
  * lines are the same as today,
  * construction points, including external points, between segments are the same as today,
  * normal points, including external points, have a different shape,
  * color is white for everything like today.

This PR implements the constraints color for points that are coincident, which doesn’t fit nicely into this proposition. It is why I asked for the ability to have points that are common for multiple segments, which allow to have a small icon near the geometry, which should be rare enough.

It would be like Catia with the circle icon. By the way, both Catia and Solidworks work like this. Sketches in these programs are not too crowded by constraints and there are not a lot of distractions.

I will put the above list in #11919 for reference.

**Comment by FlachyJoe** [comment]
Hi, when 2 segments ends are made coincident with a perpendicularity they are white, shouldn't they be red?

**Comment by maxwxyz** [comment]
@FlachyJoe you have a screenshot? Red is when they are coincident.

**Comment by FlachyJoe** [comment]
Select 2 ends
image
Click constraint perpendicular
image

**Comment by pierreporte** [comment]
This shouldn’t be working.

**Comment by maxwxyz** [comment]
yes, should be red. You can do the same with tangent I guess.
@PaddleStroke FYI.

**Comment by obelisk79** [comment]
I'm losing track at this point.

How many visual states are possible for points now? How many is reasonable to expect a user to recognize and remember? Again, I do not like the trend this is going. It is beginning to seem like a good idea gone bad.

**Comment by FlachyJoe** [comment]
@obelisk79 

- construction → blue
- normal w/o coincidence → white
- normal with coincidence → red
- highlight (mouse over) → blue
- selected → green
- end of a constrained segment → light green
- fully constrained sketch → green
😰

**Comment by pierreporte** [comment]
> end of a constrained segment → light green

Should be white or blue.

**Comment by DrD4ffy** [comment]
Two lines can be perpendicular without being connected. It’s a coincidence that the two points ended up in the same place. They are not constrained and not red. Should be correct.

**Comment by obelisk79** [comment]
I think this feature has grown in complexity too much. There are too many states.

It should be something more along these rules:
1. Points should match the same coloring rules as lines.

Done. That's it.

Anything else and things get overly complicated with edge cases and the users will have to bear the cognitive burden of learning, remembering and processing the various conditions.

**Comment by FlachyJoe** [comment]
@pierreporte the points are constrained if the segment is.

**Comment by pierreporte** [comment]
@FlachyJoe Yes but actually I messed up. What I wanted to say is that a fully-constrained vertex of a line never turns green if the whole line isn’t fully constrained. Similarly, you can’t have a fully-defined orientation and position with white or blue points at the end of a line. It’s a different subject.

**Comment by PaddleStroke** [comment]
Tangent is red already. We need to add the special perpendicular to be red
then.

**Comment by DrD4ffy** [comment]
@maxwxyz Oh sorry, I am too new at FreeCAD! I didn’t expect that you can use point for a perpendicular constraint, since points can not be perpendicular - only the lines they belong to. So the perpendicular constraint is in fact a “perpendicular and sometimes also coincidence” constraint. Confusing. Who can predict what will happen in this case? Which lines will be perpendicular to the left one? The lower or the upper?
image
For me the issue right now is not the wrong color of the dot but the unexpected implicit coincidence constraint. But OK, now I know.

**Comment by PaddleStroke** [comment]
@obelisk79 removing the red color is possible, the view is indeed simpler without it. But they provide information that could prevent many open wire situations.
I'm ok with both situations, I just implemented what was validated when I asked on the issue. If majority changes and want to remove the red then we can simply remove it.

Perhaps I would suggest trying it out for a few days to see how you guys feel about it. Then rediscuss it.

**Comment by FEA-eng** [comment]
If the red color is to be removed then it should be replaced with another way of showing whether there is a coincidence or not. Why would we want to lose this feature?

**Comment by obelisk79** [comment]
What happens when 4 or 5 points are on the same spot but only 3 are constrained coincident? But drawn red?

**Comment by maxwxyz** [comment]
White is always on top to see unconnected / open profiles

**Comment by obelisk79** [comment]
Well, that is at least better behaved than I expected ;)

**Comment by obelisk79** [comment]
Ok, so theorizing problems aside, things seem to behave rather well for the most part, which is good.

Something I noticed also, is that points actually have a bit of a snap to each other effect that I never noticed before when just moving things around. Was that part of this PR @PaddleStroke or have I just never noticed it before? Either way, bravo.

What I was eventually trying to drive the conversation towards is that drawing coincident with colors wouldn't be necessary if point-coincident was made more reliably with the auto-constraints (ie snapping). Because I run linux, my options for native software I can compare against are limited. However, when compared against OnShape, sketching never has an overt indication if points are coincident. When I was using that software regularly I never felt the need, or experienced issues due to missed coincidence constraints.

Improved auto-constraining would better address the underlying problem rather than needing color or symbol to inform the user that the software didn't meet their expectations. Both features may coexist, but my gut feeling about the red points strikes me as a small bandage applied to a larger wound.

In any case, I commend the quality of this functionality. It works well as it was intended!

**Comment by PaddleStroke** [comment]
@obelisk79 the snap functionality has been introduced some time ago (maybe about 1 year).

I see what you mean. Maybe red points are superfluous. With snapping I think open wires are less frequent already.
Anyhow this feature can be disabled pretty easily (or put under a preference). Perhaps we can wait a little bit to see how people like it or not and act accordingly.

**Comment by FEA-eng** [comment]
I think that red color for constrained points is a good idea. Missing coincidences are still very common, especially when sketches are obtained from drafts (e.g. imported dwg/dxf files - [example](https://forum.freecad.org/viewtopic.php?t=67351)) or even subjected to small modifications like trimming which can lead to the loss of coincident constraints. We've seen lots of forum threads about open wires that could be quickly solved without having to use the Validate Sketch tool if there was some visual feedback about coincidences.

However, I'm also a fan of customizability and I think that the best way would be to offer an option to disable this or change the colors as desired.

**Comment by obelisk79** [comment]
@FEA-eng that all seems fine but let's not overlook the underlying issue that it is too easy to get an open wire in the first place. Fix that, and support requests will dramatically drop even without color states.

**Comment by Roy-043** [comment]
There is an issue when you hide a coincident constraint. The color of the constrained point then stays red.

**Comment by maxwxyz** [comment]
@PaddleStroke when creating geometry using the symmetry tool and creating symmetry constraints the new points are white, not red, although the wire is closed:
grafik

should I create a new issue?

**Comment by PaddleStroke** [comment]
Well yes it is because the shape is actually not constrained with coincidence but with symmetries. Which kind of sucks I agree. But it was a bit difficult to add coincidences and symmetric and not have the sketch overconstrained.
But now that I think about it, I think I see a way to handle this. We can create the coincidences then remove duplicated symmetries. I can feel it's going to be painful to get it right, with closed wires and tangencies there are going to be a lot of overconstraining edge cases.
It's closely related to https://github.com/FreeCAD/FreeCAD/issues/13551

**Pull request merged**
