### PR TITLE
BIM: BimViews upgrade

### PR DESCRIPTION
**Pull request by yorikvanhavre**
General upgrade of the BIM views dialog:

* The dialog gains a second panel that includes 2D views
* Double-clicking a level or Draft view or TD view  activates that item
* Double-clicking a level hides all other levels
* Double-clicking a building shows all levels inside
* A new preferences allows to change the 3D view background to plain color when working on a 2D view

Additional changes in other objects/tools:

* A new "Create 2D Drawing" tool is added to the BIM annotation tools. BuildingParts are now used as 2D drawing containers. Their IFC type is set to IfcAnnotation with Object Type as DRAWING, as BlenderBIM does
* If a section plane is selected when creating a 2D Drawing, one or two shape2D views are created automatically
* "Shape-based view" is renamed to "Section view"
* "View" is renamed to "Insert view"
* A new "Section cut" tool should is added
* Sequence of the annotations menu becomes: Section plane -> Create 2D drawing -> Section view -> Section cut -> Page -> Insert view

This should be merged after 1.0

### CODE REVIEW

**Comment by maxwxyz** [comment]
@yorikvanhavre what is left to do here before being able to mark the PR as ready for review?

**Comment by yorikvanhavre** [comment]
I will check, but IIRC it's finished, just had set it to Draft to get it out of the queue...

**Comment by yorikvanhavre** [comment]
Ok this should be good to merge!

**Comment by marcuspollio** [comment]
Hi !
I'd like to test and provide feedback in the coming days.
Mind waiting a bit before merging ? Thanks =D

**Comment by maxwxyz** [comment]
waiting for @marcuspollio

**Comment by maxwxyz** [comment]
@marcuspollio any news?

**Comment by yorikvanhavre** [comment]
Thanks for the comments @marcuspollio !
I think I could add a few of those to this PR. Let's switch it back to draft...

The only thing I don't know how to achieve is overlay. Not sure if it can easily be done in Python... Don't remember who would be our overlay expert now?

**Comment by yorikvanhavre** [comment]
@tritao yes it could... Then, would you be kind enough to create a new issue with @marcuspollio 's comments above, so we don't forget about them after this one is merged?

**Comment by yorikvanhavre** [comment]
Ok thanks! Merging this then.

**Comment by maxwxyz** [comment]
@yorikvanhavre not sure if related to this PR but in the past I could double click on the workingplane in the BIM Views panel and activate it.
Now I get an error:
grafik

Also, what could/should be displayed in the lower half of the new view?
grafik

**Comment by maxwxyz** [comment]
Also double clicking on a level does not hide the other levels

**Comment by maxwxyz** [comment]
Also, right clicking in the top view and creating a new prox WP results in an error:
grafik


```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39646 (Git) Conda
Build type: Release
Branch: main
Hash: b25b83c1a58bf0ae95cbd502d0ccae27e8127cad
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * CfdOF 1.29.3
  * CurvedShapes 1.0.13
  * Curves 0.6.51
  * dodo 1.0.1
  * fasteners 0.5.33
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.26
  * Rocket 4.0.1
  * sheetmetal 0.6.1
  * Ship 2024.11.26
  * Silk 0.1.5

```

**Comment by maxwxyz** [comment]
@yorikvanhavre also the bottom part stays active, even when the file was closed and another (non-BIM file) is opened:
grafik

**Comment by yorikvanhavre** [comment]
Further problems to be treated in #18559

**Pull request merged**
