### PR TITLE
Console: add support for tag based log helper macros

### PR DESCRIPTION
**Pull request by realthunder**
FC currently lacks a set of easy to use log macros. This patch adds a set of simple tag based log helper macros. The supported log levels can be set using python `App.setLogLevel(tag, level)`, which means the log message can be turned on and off dynamically, as well as controlling the details of log output. The string `tag` is any string the developer choose, so that he can control his own log without affecting the others. Supported `level` are string `Error`, `Warning`, `Message`, `Log`, and `Trace`, corresponding to FC Console's existing output function (Trace uses Log). 

The usage is simple.
```c
#include <Base/Console.h>
FC_LOG_LEVEL_INIT("my tag")

void function(int arg) {
    FC_MSG("starting with arg=" << arg);
    ....
    FC_MSG("done")
}
```
In debug build, the default log level is `Message`, while release build, it is `Warning`. `FC_LOG_LEVEL_INIT` accept other parameters to customize log output 
```c
FC_LOG_LEVEL_INIT(tag, print_tag=true, print_src=false, print_time=false, add_eol=true,refresh=false)
```

There are also macros to help timing your operation
```c
void operation() {
    FC_TIME_INIT2(t,t1);
    
    //do stage 1

    FC_TIME_LOG(t1,"stage1");

    //do stage 2

    FC_TIME_LOG(t1,"stage2");

    // do other stuff

    FC_TIME_LOG(t,"total");
}
```
will output something like these,
```
stage1 time: 1.2s
stage2 time: 2.3s
total time: 4.0s
```
You can find detailed documentation inside `Base/Console.h`

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I don't really understand what changes (from a python point of view) after you set a log level for a given tag... Let's say I'm issuing `App.setLogLevel("my Workbench", "Error")`, what will happen then? I'll still be using App.Console.PrintMessage, App.Console.PrintError, etc...right?

**Comment by realthunder** [comment]
When a C++ application initialize log level using `FC_LOG_LEVEL_INIT`, it will retrieve an integer reference to the log level stored in Console. `setLogLevel` let user dynamically change that integer log level. Various log printing macros, FC_TRACE, FC_LOG, FC_MSG, etc will check for the log level, and only output log if the log level integer value is equal or greater than its corresponding level. The end result is that, for example, when you issue `App.setLogLevel("my Workbench", "Error")` in python console, any log printing (with tag 'my Workbench') NOT using `FC_ERR` will be silenced.  If you issue `App.setLogLevel("my Workbench", "Message")`, then log output with `FC_ERR, FC_WARN, FC_MSG` will show, and the others silenced.

The most obvious use case is that if a user encounters a problem, he can now have more informal reports by turning up the log level attach the report with log output in the python console.

There is also `App.getLogLevel`, so python code that needs logging can actually do similar thing. 
```python
import FreeCAD
import FreeCADGui

class FCADLogger:
    def __init__(self, tag):
        self.tag = tag

    def isEnabledFor(self,level):
        return FreeCAD.getLogLevel(self.tag) >= level

    def trace(self,msg):
        if self.isEnabledFor(4):
            FreeCAD.Console.PrintLog(msg+'\n')
            self.updateGui()

    def log(self,msg):
        if self.isEnabledFor(3):
            FreeCAD.Console.PrintLog(msg+'\n')
            self.updateGui()

    def message(self,msg):
        if self.isEnabledFor(2):
            FreeCAD.Console.PrintMessage(msg+'\n')
            self.updateGui()

    def warning(self,msg):
        if self.isEnabledFor(1):
            FreeCAD.Console.PrintWarning(msg+'\n')
            self.updateGui()

    def error(self,msg):
        if self.isEnabledFor(0):
            FreeCAD.Console.PrintError(msg+'\n')
            self.updateGui()

    def updateGui(self):
        try:
            FreeCADGui.updateGui()
        except Exception:
            pass

logger = FCADLogger('myTag')

# either show or not depending on last setLogLevel
logger.trace('you see me?')

FreeCAD.setLogLevel('myTag','Trace')

# will show
logger.trace('now you see me')

FreeCAD.setLogLevel('myTag','Message')

# won't show
logger.trace('bye bye')
```
The actual log level is stored in `Parameters->BaseApp->LogLevels`. Edit those parameters manually will only take effect on restart. Use `App.setLogLevel` instead.

**Comment by yorikvanhavre** [comment]
Oh I see... pretty flexible system. Thanks for the explanation!

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
