### PR TITLE
[Sketcher] planegcs: Fix issue in arc-B-spline tangent test

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Correct the size of the knot vector used (described here with knots and multiplicities).

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
@adrianinsaval draw a  B-spline with say, 5 control points and count the number of knots (also include the end points). There should be 3 for a cubic: (degree -1) less than the number of control points. I had mistakenly added too many there. It worked but it could very well have failed.

**Comment by chennes** [comment]
Could you please edit the first line of the commit message? There's no sense in saying "updated file x"... it's a git commit, we know it updates the file.

**Comment by AjinkyaDahale** [comment]
> Could you please edit the first line of the commit message? There's no sense in saying "updated file x"... it's a git commit, we know it updates the file.

Is it possible to do this from within github? If not I'll havr to do it through a worktree on my local machine.

**Comment by adrianinsaval** [comment]
A maintainer can eddit the commit message if they do a squash merge

**Pull request merged**
