### PR TITLE
Path: some bugfixes for qt5 and py3 support

### PR DESCRIPTION
**Pull request by mlampert**
Fixing some blatant errors in Path when compiled against qt5 and/or py3.

### CODE REVIEW

**Comment by PrzemoF** [comment]
Might be worth to post it here [1] if it's not already there.

[1] https://forum.freecadweb.org/viewtopic.php?f=10&t=12534

**Comment by mlampert** [comment]
I'm not too familiar with the Windows build and can't figure out why it failed. Did it get killed at the mark of the hour? If anybody could give me a clue I would much appreciate that.

**Comment by mlampert** [comment]
As for throwing an exception when loading doesn't work - I'm not sure I'm in favour of that. First off all other places use the pattern I've copied and second it totally obfuscates the intent/logic.

**Comment by wwmayer** [comment]
Merged & applied the feature detection fix as suggested by cclauss

**Pull request closed without merging**
