### PR TITLE
Added Path.Area and Path::FeatureArea

### PR DESCRIPTION
**Pull request by realthunder**
Path.Area is aimed to fully expose the power of libarea/ClipperLib. It is a python scriptable object, which is backed by Path::Area c++ class. Path::FeatureArea is the companion document object. This single feature is capable of doing:

- Boolean operation on planar shapes (Union, Difference, Intersection, Xor)
- Multi-pass 2D offset
- Generating pocketing tool path
- Multi-slicing of solid shapes
- Stroke of generated path
- Any combination of the above steps within one feature, with linked children Part.Feature derived objects
- Exposed many libarea and ClipperLib internal settings for fine tuning

I'll post on the forum for picture demonstration soon.

Forum link: 
http://forum.freecadweb.org/viewtopic.php?f=17&t=20083&p=154723#p154723
https://forum.freecadweb.org/viewtopic.php?f=15&t=20152
https://forum.freecadweb.org/viewtopic.php?f=15&t=20273

### CODE REVIEW

**Comment by sliptonic** [comment]
Wow!  This looks really really interesting.  Can't wait to see pictures.  I'm pulling and building now.
With a change this large and significant, perhaps this should be marked WIP and thoroughly tested before merging.

**Comment by sliptonic** [comment]
I was able to build and I'm working through the forum demo now.  This is really cool and adds some amazing tools to our toolbox.

However, it's definitely Work in Progress and merging it will confuse a lot of people.  For example, (unless I'm misunderstanding)  the Path.FeatureArea does not produce a Path object with Path.Commands so it can't be postprocessed to generate gcode.  I think this is really good stuff but it represents a set of tools that devs can use to expand the Path workbench and add capability.  I don't think it's a finished feature for end-users.

Amazing work realthunder!

**Comment by realthunder** [comment]
This is intentional. I intend this feature to only produce wires and stuff, and to be the interface between gcode generating Path features and object model Part features. This is why I put the icons in the Useful tools group, and those icons are the few without the Drill if you get what I mean.

**Comment by yorikvanhavre** [comment]
Pretty impressive work @realthunder ! This pull request is already much easier to handle than your other one, thanks for the effort.

I have two things to say on this PR:

1. The libarea changes are big, and might break something. Since I don't use libarea I cannot judge. It would be good if other Path/libarea users could test this before this is merged.
2. Your "Part-based" Path feature is a bit strange. Of course the ease of using Part Shapes is understandable, but the whole idea of how Path works, is that the objects already have to produce their gcode-like output, so all the conversion from shapes to gcode is done right there, as soon as possible, and the user can always see the result at all steps of the process. Your features leave the "problem" for later, which is what we tried to avoid in Path. Of course I would prefer to have these features produce their gcode, but as you say we could maybe consider these like "intermediate tools". 

In any case, I propose we wait for @sliptonic @mlampert and other Path warriors to give it a good testing to see if the libarea changes don't break anything...

**Comment by mlampert** [comment]
I haven't looked at the code yet, just played around with the actual functionality. Interesting indeed ...

My notes in random order:
* It seems features are left behind when deleted. I had significant problems setting the "workplane" once I had the WorkArea, so I deleted several attempts, some of which reappeared later on again. Not in the tree, but in the 3d view.
* Section planes have to align exactly with the model height levels. In other words the algorithm only sees what falls on one of those section planes. Nothing inbetween, no angled surfaces ...
* I don't understand the "thicken", I see a lot of potential there but I'm not sure what it actually shows me since I'm not looking at the actual path
* UX is - I'm not saying it's bad but it goes very heavily against the FC grain. You have to think and process differently than in any other aspect of FC.

All in all I think there's a lot of potential. From a UX perspective I would prefer to find an approach that matches/fits into FC and more specifically into Path. I haven't figured out how to get from here (the tutorial) to g-code.

From a stability perspective I currently don't think it's ready to be pulled into master. I think it is a great prototype and we should figure out what works and what doesn't.

Personally I very much like the approach of starting with the Stock object and not the part itself. Something we've been talking about in the past but haven't gotten around to addressing - and now we actually see it ;)

I am looking forward to go through the code now to see how you actually pulled this off, very impressive!

**Comment by realthunder** [comment]
Thanks for the appreciation, everyone. I really loved how FC is going these days. And I firmly believe in its potential to be the ultimate CAD/CAM for everything. On the other hand, I am just an amature in the CAD/CAM/CNC world. My motivation is to try to find a reliable way to construct 2D shapes in FC, and then generate gcode from it (which I still haven't got to yet).

As for the pull request here, FeatureArea comes very handy to construct 2D shapes, much reliable than OCC in this regard. And I think there is a missing link between the CAD model and CAM toolpath. Say the user already have a model built in FC, he still needs to perform various steps before being able to use Path.Feature to generate gcode (really, what are the recommended steps in Path mod? Can someone kindly point me to some links please? I haven't got time to search for instructions yet:).

And let's not forget about Path.Area, FeatureArea is good for hands on testing of various librea capabilities. But, Path.Area, I think is the one more suitable for Path developers here. It is essentially a FC specific python wrapper for libarea, I can expose more function if necessary. Eventually, I think we can just get rid of area python module, and directly use Path.Area here.

**Comment by realthunder** [comment]
Oh, forgot to mention this. Path.Area abstracts the actual 2D library from the code that's using it. What it does right now is to iterate through OCC shapes, convert each edge to libarea vertex, call libarea function to perform operation like Union, Difference, Offset, Pocket etc, then convert the result back to OCC shapes. With this pattern, it is not that difficult to switch to a different 2D library, say, [GEOS](https://trac.osgeo.org/geos/) anyone?

**Comment by realthunder** [comment]
@mlampert, the workplane doesn't have to be any shape belonging to the children of the FeatureArea. It can be any other planar shape. The UI needs some work. The key is to realize that two mode of selection is required. 1) Select the hosting FeatureArea by clicking the item in treeview. 2) Select workplane, holding the CTRL and click a face or wire in the 3D viewer. The workplane is internally used by BRepAlgoAPI_Section to perform section.

**Comment by wwmayer** [comment]
From functionality point of view can this branch be merged?
@realthunder is the branch a replacement for PR414? And have you seen the build failures for clang under Linux? Obviously the builds with clang under OSX and gcc under Linux succeeded.

**Comment by realthunder** [comment]
@wwmayer Yes, this PR shall obsolete PR414. But I think the discussion in the forum about how to incorporate the new feature hasn't reached any consensus yet. May be wait till I can get some actual Path out. I'm working on it.

And I also saw the build failure. It is caused by my use of Boost.Preprocessor. Probably because the clang used is too old? Do I need to make an effort to fix this?

**Comment by wwmayer** [comment]
I guess this is the link: https://forum.freecadweb.org/viewtopic.php?f=15&t=20152
> Yes, this PR shall obsolete PR414.

OK, then I close it because I don't see a reason to leave it open.

> It is caused by my use of Boost.Preprocessor. Probably because the clang used is too old? Do I need to make an effort to fix this?

If you know the exact reason it would be good. But if not then we still have to find a solution sooner or later.

**Comment by realthunder** [comment]
@wwmayer I successfully built the project with clang 3.8.0 on linux. Do we still insist on supporting clang 3.5.0?

**Comment by wwmayer** [comment]
Ubuntu 14.04 is an LTS and gets support until 2019. Since it offers clang 3.3-3.5 it would be good to make the code working there, too.

I didn't have a close look at the problem. Do you know the reason? Is it because of some new C++ features or is there another reason?

**Comment by realthunder** [comment]
OK, I'll try to fix it then. It probably has something to do with clang 3.5's inadequate support of variadic macro feature required by Boost.Preprocessor.

**Comment by realthunder** [comment]
Err... something wrong with travis? Why apple build is canceled. I've fixed linux clang issue, and the build passed. I was eager to see the long missed green tick, then this happened.

**Comment by bblacey** [comment]
Yes, the Travis folks have been struggling with mac infrastructure issues for the last day or so - https://www.traviscistatus.com/incidents/k79mjcv403c4.  Once Travis recovers, we can restart this PR job...

**Comment by bblacey** [comment]
Travis is slowly recovering from their infrastructure issue.  I restarted the macOS sub-job for this PR but it will probably take a while to clear.

**Comment by realthunder** [comment]
Finally... Thanks for the effort.

**Pull request merged**
