### PR TITLE
UI : Task panels cleanup - Sketcher and Part Design headers

### PR DESCRIPTION
**Pull request by marcuspollio**
Some Sketcher and Part Design Task panels headers use inconsistent terminology and icons.
This change hopes to better the current situation in reusing icons belonging to the appropriate Workbench and naming matching other UI uses (such as Property View) or the documentation.

Feedback most welcome.
Only English user-facing strings have been changed. If this PR is accepted, translations will have to be updated.

TaskPanelsCleanup

TaskPanelsCleanup2

### CODE REVIEW

**Comment by FEA-eng** [comment]
Nice improvement. Would be good to also update the icons and descriptions in the task panels of the PD subtractive operations other than Pocket. Currently, they are the same as for their additive counterparts. Groove, for example:

groove

**Comment by chennes** [comment]
@FreeCAD/design-working-group any comments?

**Comment by pierreporte** [comment]
@chennes OK for me.

**Comment by MisterMakerNL** [comment]
This is nice, all these little things add up.

**Comment by obelisk79** [comment]
I still argue that the icons in the headers offer nothing of value to the user, but this is an improvement over the current state regardless.

**Comment by adrianinsaval** [comment]
what's the point of the header text changes? How is "Part Design Helper Tools" better than what's currently there?

**Comment by obelisk79** [comment]
> what's the point of the header text changes? How is "Part Design Helper Tools" better than what's currently there?

The way I see it, it makes the naming convention consistent across the workbench, as well as corrects some unusual naming. ie 'Sketch Tools' but the listed options are Part Design features.

**Comment by marcuspollio** [comment]
Thanks all for the feedback.
@FEA-eng I'll have a look at the others and tweak them if needed. Please do suggest if you find some more.
@obelisk79 Yeah, I looked to remove them after our discussion on Discord, but the function excepts 4 arguments (removing the icon would leave only 3) so it wasn't compiling. A bigger refactor of that would be needed (out of my scope for the moment).
@adrianinsaval Yeah indeed, "Part Design Helper Tools" is a bit verbose, but it's use in the [wiki](https://wiki.freecad.org/PartDesign_Workbench) (that can be changed tough). "Helper Tools" would suffice maybe, or any other suggestion ?

**Comment by marcuspollio** [comment]
@FEA-eng Sadly I could only improve one more tiny header.

All Revolution/Groove, AdditiveLoft/SubtractiveLoft, AdditivePipe/SubtractivePipe, AdditiveHelix/SubtractiveHelix and AdditivePrimitive/SubtractivePrimitive share a common TaskFeatureParameters function between the additive and subtractive ones. This would need a bigger refactor I'm currently unable of.

Unfortunately many tasks/menu/toolbar interaction in Part Design are broken, as it shows impossible features with your selection or document content and does not show some useful ones. This stuff should be a lot more contextual, but that's for another time.

**Comment by FEA-eng** [comment]
@marcuspollio Thanks. Good to know, I'll create an issue for this since IMO it should be fixed at some point in the future.

**Comment by chennes** [comment]
@marcuspollio can you have a look at that conflict?

**Pull request merged**
