### PR TITLE
Occt7

### PR DESCRIPTION
**Pull request by vejmarie**
This Pull request intend to port FreeCAD to OCCT7 and support new SMESH with VTK data structure. This is a hard dependency and it does include a vagrant directory into which FreeCAD.sh provisioning script is used to help compilation and adaptation

Port_Modification.changlog contains major changes required to make FreeCAD works with OCCT 7, VTK 7 and Salome 7.7.1.

### CODE REVIEW

**Comment by bblacey** [comment]
@vejmarie - great work porting to OCCT7!  To support your efforts, I have worked on the OS X packaging to provide better support.  You can read about the details [in this forum post](http://forum.freecadweb.org/viewtopic.php?f=10&t=15663&p=125748#p125748) but you already know most of it because much was done for the Salome MESH effort.

I was not able to create a pull request against your repo for some reason so here is [a patch](https://github.com/bblacey/FreeCAD-MacOS-CI/commit/4b6e33ae8da8983b734919c8c049771cd43a2a42.patch) that you can apply with `git apply` to incorporate the changes I mentioned in the post to ensure Travis uses OCCT7 instead of OCE6.

Finally, here is the [Travis log](https://travis-ci.org/bblacey/FreeCAD-MacOS-CI/jobs/131754099) for the build on the fork of your occt7 branch.

Thanks again for pushing OCCT7!

**Comment by vejmarie** [comment]
Hi Bruce, I just have applied the patch, thanks a lot for it !. Let me check if I can provide you access to the repo.

**Comment by vejmarie** [comment]
@bblacey @ickby I added you as a collaborator on the repo. The branch is occt7

**Comment by bblacey** [comment]
@vejmarie - Thanks.  Right now, this PR is a fairly benign change for OS X because we have implemented proper package support.  We need to do the same for Linux because most devs use Linux but that is a bit out of my sweet spot - is that something that you are going to tackle as part of this?

**Comment by vejmarie** [comment]
I made some deb files for linux (have a look inside vagrant/FreeCAD.sh). I am using vagrant to generate them on trusty and put them on our community website through echo "deb http://ruggedpod.qyshare.com/Webdav/Public/deb trusty universe" >> /etc/apt/sources.list
I tried to use launchpad, but either I am too old for it (41), or it is too far from travis for me, I never had been able to make work my first PPA. The linux command to do it is a pain. The current deb are not stripped that is why they are huge, but as this is development files, I thought it might be usefull to keep symbol tables with demangling capabilities. I am ready to help improving the packaging.

**Comment by bblacey** [comment]
I'm headed to the [MakerFaire](http://makerfaire.com) for the rest of the day so I will have to look at it either tonight or first thing tomorrow PST.

**Comment by vejmarie** [comment]
Enjoy the MakerFaire, I couldn't do it this year. I'll be in Texas next week. Anyway I am in the bay area really often, (next trip second half of june), might be great to share a coffee if you are there.

**Comment by bblacey** [comment]
So how about installing open cascade from the .deb files instead of building from source? 

Coffee second half of June sounds great!  I'm in the San Mateo area - where will you be?

**Comment by sgrogan** [comment]
> So how about installing open cascade from the .deb files instead of building from source? 
This is what we need to do. No Debian Folder exists to build this (at least I haven't found one) We'll need to create it ourselves. May plan is to try to modifiy the oce one from debian, but NormandC has warned me I may be living in fantasy land.
I'll start some topics in the forum soon. @f3nix is also knowledgeable about this stuff, and I think @jean.thil has build a Debian package on OBS successfully. OBS has broad support Debian, Ubuntu, Fedora, and OpenSuse.
Is VTK 7 a hard dependency? I've added VTK6 to the daily PPA to build ickby's post processing already in master. I'm using VTK7 on Win because I have to build it anyway.
This future stuff should move to the forum though.
GREAT JOB GUYS, I love this team approach! 1+1+1=7

**Comment by vejmarie** [comment]
@sgrogan this what I do within the build currently. I am not sure about the process of creating the deb file, but they work currently. My travis build download them from a repo I setup on my own server (they are not signed). I tried to setup a PPA, but have never been able to launch a compile.

**Comment by bblacey** [comment]
> May plan is to try to modifiy the oce one from debian, but NormandC has warned me I may be living in fantasy land.

@sgrogan, I effectively did the same with the opencascade home-brew formula.  The material "build" changes between OCCT 6.9.1 and OCCT 7.0 were very small...  Basically, added vtk as a dependency, changed some CMAKE defs (mostly rename) and removed options that no longer exist like OpenCL on  OS X.  Perhaps [these diffs](https://github.com/bblacey/homebrew-science/commit/24338806071b730bf9178f3b3b09f323034ff379) will help.

**Comment by andrewanswer** [comment]
Hi, I'm interested in merging OCCT7 with FreeCad main branch. I have several complex 3d-models which break FreeCad completely with OCCT exceptions (in modeling process). Hope what your update will fix these problems. When this merge will be done? Want to test these changes immediately.

**Comment by vejmarie** [comment]
Hi Andrew, which O/S r u running ? I might be able to provide you a temporary version compiled for it to check if it fix your issues

**Comment by andrewanswer** [comment]
I currently working on Ubuntu 14.04 LTS.

**Comment by ianrrees** [comment]
Probably a dumb question (I've been out of the FreeCAD loop lately), but what are all these changes actually meant to fix?  I ask because I've been using OCC7 for a while now no problem - had been thinking that you guys merged in the OCC7 changes already, and this PR was either stale or about SMESH.

OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.7689 +83 (Git)
Build type: Debug
Branch: 20160605-techdraw
Hash: 61310cf7b2fc2e3a9d0e06e4d1cf84473b11530a
Python version: 2.7.11
Qt version: 4.8.7
Coin version: 3.1.3
OCC version: 7.0.0

**Comment by bblacey** [comment]
@ianrrees, @vejmarie is the author and best person to respond but I understand this PR is a blend of SMESH, OCCT7 and some linux packaging improvements.  @ickby's SMESH branch that includes OCCT6 compatibility and was merged into master probably obviates much of this PR.

That said, @vejmarie found that he had to patch netgen/nglib in order to build OCCT7.  I forked homebrew/science and modified your nglib formula to apply his patches - did you have to modify nglib to build with OCCT7?

Finally, while OCCT7 is smooth sailing on OS X, I think @sgrogan is still wrestling with some Windows build issues that may also be holding OCCT7 back.

@vejmarie, are you thinking about rebasing this PR or closing it and opening another OCCT7 only PR?  It is probably best to keep the scope limited in a PR to a specific objective/goal such as OCCT7 only.

**Comment by ianrrees** [comment]
Sorry about the slow response!

I didn't think to try building with nglib and OCC7, so there may well be some work to do there.  Main goal was switching my system over to Homebrew.  I'll try to figure it out sometime in the next few days.

**Comment by bblacey** [comment]
@vejmarie has already done the work.  Given you have switched to home-brew, you can do the following to install nglib and occt7.

brew untap homebrew/science && brew tap bblacey/science
brew install occt7
brew install glib --with-opencascade

[See this forum post for additional details](http://forum.freecadweb.org/viewtopic.php?f=10&t=15663&p=125748&hilit=bblacey%2Fscience#p125748)

**Comment by ianrrees** [comment]
Apologies for another slow response.  Do you guys have any plans to clean up and then submit a PR for those nglib changes?

**Comment by vejmarie** [comment]
Hi Ian, all,
Sorry for my long delay, I had been busy handling some situation at work. ian, if you clone master currently it should be working straight forward with bblacey repo.

**Comment by bblacey** [comment]
Jean Marie!  Welcome back!  Anyway, about a week ago I had setup a [Travis job](https://travis-ci.org/bblacey/FreeCAD-MacOS-CI) to build FreeCAD master against OCCT7 using the bblacey repo but it failed with some SMESH compilation issues.  The goal was to produce OCCT7 builds on my repo until such time that we can officially support OCCT7 on the FreeCAD master.  So, it seems that some of your SMESH changes may not have made it into @ickby's OCCT6-compatibile SMESH PR?  Sounds like you are swamped but perhaps you can take a look at the [Travis log](https://travis-ci.org/bblacey/FreeCAD-MacOS-CI/jobs/139037618#L1715-L1759) when you get a chance to see if you see something obvious that I am doing wrong...

**Comment by ickby** [comment]
I did check the compilation with occ7 once, but not after the latest changes. Could have happend that something went wrong. I add to my list of things to investigate, it should definitely work out with occ7, that is very important. Together with the FEM mesh issues there is quite some clean up still needed after the transition.

**Comment by sgrogan** [comment]
If it adds any insight, I get very similar errors on win
[http://forum.freecadweb.org/viewtopic.php?f=4&t=16288](url)

**Comment by vejmarie** [comment]
Hi bblacey, this issue is "simple" to fix. This is coming from the lack of TKCDF library during the link phase. So within FindOpenCascade.cmake just be sure that TKCDF is referenced and you should be good to go. This probably needs an quick update through a PR. can you request for it ?


if(OCC_FOUND)
  set(OCC_LIBRARIES
    TKFillet
    TKMesh
    TKernel
    TKG2d
    TKG3d
    TKMath
    TKIGES
    TKSTL
    TKShHealing
    TKXSBase
    TKBin
    TKBool
    TKBO
    TKCDF
    TKBRep
    TKTopAlgo
    TKGeomAlgo
    TKGeomBase
    TKOffset
    TKPrim
    TKSTEP
    TKSTEPBase
    TKSTEPAttr
    TKHLR
    TKFeat
  )

**Comment by bblacey** [comment]
I have added the TKCDF library, regressed it on OCCT6 & 7 and submitted it as a pull request that @wwmayer has already merged it into master.  While this PR served as the foundational work for SMESH & OCCT7, it looks like we can abandon this PR, right?  Jean Marie, it is your call however we will ultimately need an OCCT7 PR that modifies .travis.yml to pull in the correct dependencies once the OCCT7 build issues are resolved across platforms.

Finally, as an FYI, I am going to re-enable integration builds on my [personal repo](https://github.com/bblacey/FreeCAD-MacOS-CI/tree/occt7) that will provide [macOS builds with OCCT7](https://github.com/bblacey/FreeCAD-MacOS-CI/releases/tag/v0.17) until such time OCCT7 becomes the default on FreeCAD master.  This is just an FYI in case any of you would like to grab a latest and greatest macOS build against OCCT7.

**Comment by vejmarie** [comment]
hi bblacey, yes I am closing it now. It is becoming useless, congrats to the team for the integration !

**Comment by sgrogan** [comment]
@bblacey 
I think there is no reason to wait. If you can pack the OSX bundle just go for it. I'm gonna distribute win with OCCT7 as soon as it works. I'm just working on the packaging for x64. Having and older occ on linux and a newer on OSX on Travis is a good thing.

**Comment by bblacey** [comment]
@sgrogan I like your thinking.  I will look into that sometime before the end of the week because I need to ensure the pull request and ports-cache are time-congruent.  For now, here are the details from a Travis OCCT 7 build on my repo against the latest master.

```
OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.7802 (Git)
Build type: Release
Branch: (detached from 30b279f)
Hash: 30b279fa0ad25eda5883a0db3afc78b6c8d102c8
Python version: 2.7.11
Qt version: 4.8.7
Coin version: 3.1.3
OCC version: 7.0.0
```

**Comment by andrewanswer** [comment]
Hello,

please tell how I can compile freecad under linux with OCCT 7.0? I currently working on Ubuntu 14.04 LTS. As  I wrote here https://github.com/FreeCAD/FreeCAD/pull/158#issuecomment-226315928 I want to check some 3d-models with OCCT 7.0.

**Comment by vejmarie** [comment]
Sorry I didn't had seen your comment. If you clone the latest master, you will find a directory called vagrant, within that directory you will find a script called FreeCAD.sh which contains "automatic" procedure to compile FreeCAD. It makes some times that I didn't tested it on Trusty, but it is working on Xenial. Normally it should be working on Trusty. Just ping me if you have issues with that. We shall probably switch this to FreeCAD forum.

**Comment by andrewanswer** [comment]
I successfully compile and install freecad on Ubuntu 14.04 LTS with only one thing: it inform me about "broken" package:

```
Lintian check results for /home/andrewanswer/freecad_deb/freecad-0.17_trusty-amd64.deb:
E: FreeCAD: bad-package-name
E: FreeCAD: package-not-lowercase
E: FreeCAD: maintainer-name-missing vejmarie@ruggedpod.qyshare.com
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203.
```
Some 3d-models was built successfully, but others are not. I use Rhino 5 for NURBS modeling, as alternative, and it helps. I think what some geometry just too complex for BREP OCCT...

**Comment by normandc** [comment]
The error message doesn't say broken package, but bad name. Debian rules
only accepts hyphen in package name, not underscore, and only lowercase
letters.
Le 1 juil. 2016 2:47 PM, "Andrew Answer" <notifications@github.com> a
écrit :

**Pull request closed without merging**
