### PR TITLE
Misc changes for Qt5

### PR DESCRIPTION
**Pull request by maurerpe**
The following changes are needed for Qt5 and still work with Qt4.  I have freecad (mostly) working with Qt5.  If these patches are accepted, I have more to follow.

### CODE REVIEW

**Comment by f3nix** [comment]
Hi @maurerpe,
if You want You can join my Qt5 porting effort here:
https://github.com/f3nix/FreeCAD/tree/qt5-transition-3

Some discussion:
http://forum.freecadweb.org/viewtopic.php?f=17&t=13742

Cheers,
Mateusz

**Comment by maurerpe** [comment]
@f3nix I saw your branch and fully intend to join you.  I was hoping my "no-brainer" qt4/qt5 neutral fixes could be merged directly into the main tree.  The further the Qt5 branch is from the master the harder it will be to maintain.

**Comment by f3nix** [comment]
Great @maurerpe! :)

+1 for your reasons. These are my thoughts too.

To speed up the PR you could create a topic in the forum here:
http://forum.freecadweb.org/viewforum.php?f=17

Cheers,
Mateusz

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
