### PR TITLE
Path: Apply Placement to simulated/exported GCode

### PR DESCRIPTION
**Pull request by cam72cam**
This changed is inspired by (and slightly refactors) the Array Path modifier.

It currently takes the Placement XYZ and Z Angle into consideration. Future work could also implement rotating the path around the X and Y axes.

image

---

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by cam72cam** [comment]
There's a related discussion on at least one forum topic that has use cases for these changes:
https://forum.freecad.org/viewtopic.php?p=659966&hilit=gcode+placement#p659966

**Comment by cam72cam** [comment]
This is my main use case:
image


I import previously exported paths and need to arrange them on a larger piece of stock, sometimes cutting the same part out multiple times.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459">pipeline status</a> for feature branch [PR_8459](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459). Pipeline [775276164](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/775276164) was triggered at [b668f7c](https://github.com/FreeCAD/FreeCAD/pull/8459/commits/b668f7cfdef561d913e7de2e37ce63f17549a79f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459">pipeline status</a> for feature branch [PR_8459](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459). Pipeline [776106986](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/776106986) was triggered at [99f8d7f](https://github.com/FreeCAD/FreeCAD/pull/8459/commits/99f8d7f1258cbc25744f8c1e6f5b7911025433d6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459">pipeline status</a> for feature branch [PR_8459](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459). Pipeline [776179554](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/776179554) was triggered at [e745590](https://github.com/FreeCAD/FreeCAD/pull/8459/commits/e74559097b4f25fbb497526e5de703ace092b6e3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by cam72cam** [comment]
Some examples of using the Array Modifier which has been refactored to use this new code.

4x 360 degree array with X offset
array_orig
array_new

4x 360 degree array with X+Y offset
array_xy_orig
array_xy_new

The rapid paths are more straightforward in the new code since it does not override X or Y when it's not needed.

The original code would turn `G0 0.005Z` into `G0 0.0X 0.0Y 0.005Z` which was unnecessary and technically incorrect.  I ended up "fixing" that when using the same code for gcode post processing which showed up in some existing tests.

**Comment by morganrallen** [comment]
I've built and tested this code and it works for my basic use-case described in the forum post above.

One issue I see;
If I make an CustomOp with non-zero Placement, then make an array of that it does not carry the previous placement. I would expect this to cascade but maybe there's specific reasons not to.
Additionally, for machines that support it , could `G52 (Local Coordinate Offset)` be used?

**Comment by cam72cam** [comment]
Thanks for giving it a try!

I noticed that as well.  There's a few operations like Copy, Array, and Simple Copy where I was unsure what default behavior would make sense.  My guess:
* Copy: Should copy the Placement into the cloned object
* Array: I think it could make sense to use getPathWithPlacement to get the path of the referenced object, not sure if that would be more confusing or less
* Simple Copy: I'm pretty sure it should use getPathWithPlacement when generating the gcode to inject into the custom block

I'm also working on a followup PR that would allow you to "embed" one job into another.  This would be really helpful for me where I've got multiple jobs based on a single complex model which are all cut out of a single piece of plywood.

I'm unfamiliar with G52 (and similar work offset commands) and can do some research into them.  At first glance, I'm not sure G52 allows for the same sort of rotations that are allowed in this PR.  On a code cleanliness note, all of the manipulation is centralized so an additional defaulted parameter could be added to specify a work offset to use in the future?

**Comment by morganrallen** [comment]
> I'm also working on a followup PR that would allow you to "embed" one job into another. This would be really helpful for me where I've got multiple jobs based on a single complex model which are all cut out of a single piece of plywood.

Chatting with sliptonic this afternoon I suggested another feature I'd like to work on, adding multiple options to the CustomOp. They could be...

* Text (as it is now)
* File
* Job

This inline with what you are thinking?

**Comment by cam72cam** [comment]
Yeah, that's a good way of looking at it.  I'm not sure if it makes sense to extend CustomOp or create new operations for File + Job instead.

**Comment by cam72cam** [comment]
Another idea I've just had is to support embedding a job inside another job using links.  It's definitely outside the scope of this work.  @morganrallen would you like to chat somewhere else?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459">pipeline status</a> for feature branch [PR_8459](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459). Pipeline [781021679](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/781021679) was triggered at [be6bd4c](https://github.com/FreeCAD/FreeCAD/pull/8459/commits/be6bd4c95dd0b3a584b847759e3f1eda1982400e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by morganrallen** [comment]
Seems there is an intermittent bug with this, I have not found what triggers it yet but have confirmed if I restart FC and post-process right away this bug will not occur.

```
12:28:31  Running the Python command 'Path_Post' failed:
Traceback (most recent call last):
  File "/home/morgan/devel/FreeCAD-build/Mod/Path/Path/Post/Command.py", line 589, in Activated
    result, gcode, name = self.exportObjectsWith(sublist, partname, job, idx)
  File "/home/morgan/devel/FreeCAD-build/Mod/Path/Path/Post/Command.py", line 524, in exportObjectsWith
    gcode = processor.export(objs, filename, postArgs)
  File "/home/morgan/devel/FreeCAD-build/Mod/Path/Path/Post/Processor.py", line 80, in export
    return self.script.export(obj, filename, args)
  File "/home/morgan/devel/FreeCAD-build/Mod/Path/Path/Post/scripts/linuxcnc_post.py", line 258, in export
    gcode += parse(obj)
  File "/home/morgan/devel/FreeCAD-build/Mod/Path/Path/Post/scripts/linuxcnc_post.py", line 371, in parse
    if c.Name[0] == "(" and not OUTPUT_COMMENTS:  # command is a comment

string index out of range
```

**Comment by cam72cam** [comment]
I'm having a hard time finding any changes to the code that I made which would cause that.  All of the command manipulation I've done does not change the Name of the command at all.  Could you confirm that this does not happen on master?  I have a suspicion that it's an issue with custom gcode processing outside of the work that I've done.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459">pipeline status</a> for feature branch [PR_8459](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459). Pipeline [789314943](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789314943) was triggered at [feea134](https://github.com/FreeCAD/FreeCAD/pull/8459/commits/feea1340f50a23c51efb3fffb861945049ff3183). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by morganrallen** [comment]
OK I'll take some time this afternoon to see if I can track this down further

**Comment by morganrallen** [comment]
So for me, yes it does make sense that copies and arrays will be based off the Placement of the Base Op. Particularly around arrays this will allow for more complex layouts.

I've checked this around the current main branch and everything still looks good.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459">pipeline status</a> for feature branch [PR_8459](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8459). Pipeline [804380750](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/804380750) was triggered at [dd31b7f](https://github.com/FreeCAD/FreeCAD/pull/8459/commits/dd31b7f0db67cee57bb5cb1cef19166b04bdaff4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by morganrallen** [comment]
ok this is looking good to me, assuming all other checks are good I'd say this is ready for merging @sliptonic

**Pull request merged**
