### PR TITLE
FEM: Fix for write to io stream in Python 2. It needs byte string to unicode string conversion

### PR DESCRIPTION
**Pull request by Russ4262**
Testing fix for incorrect string type in Python 2 usage

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by Russ4262** [comment]
Well, as suspected, it appears every instance of the `f.write()` will have to have the Unicode conversion.

**Comment by Russ4262** [comment]
It might be as easy as defining the coding for the module as `utf-8`, which is the second test I'm running.  It is easier than modifying the 300+ instances of `f.write()`.  Defining the coding should tell Python two that all the string literals are Unicode.  Correct?

**Comment by Russ4262** [comment]
Plan C, if Plan B fails, is to create a small intermediary conversion method in the class that is called instead of writing to the open stream directly with the current `f.write()` method.  Perhaps `self.writeAsUnicode()` would receive the input data, make the Unicode conversion, then pass it on to the open stream pointer saved as a class attribute.  This plan would add less bulk to the code by limiting the repetitions of `.decode('utf8')` and `u'<str>'`, as well as make for easy fixing throughout the module with a simple function call replacement.

**Comment by Russ4262** [comment]
Okay, so Plan B failed.  On to Plan C.

**Comment by Russ4262** [comment]
Plan C fix passes both the TestApp.All and TestFem only tests run within the Test framework workbench on my Windows 10 machine.

Is it possible this failure is unique to Linux, and perhaps MacOS?  Or, perhaps a Python-related issue?  My Windows machine is using the libpack with Python 3.6.8

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.20980 (Git)
Build type: Release
Branch: master
Hash: c2818d9159385d23b182dc7167af2d4bacbee94c
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

Another issue on the Python topic.  Looking at the Travis CI build log and config reports, I see references to Python 3.7.  I see a python.exe is found in the libpack 12.2.4, and I see the following in the [log.txt](https://api.travis-ci.org/v3/job/684546225/log.txt) that suggests Python 2.7.
==============
Summary report
==============

-- Build type:          Release
-- Compiler:            /usr/bin/c++ (7.5.0)
-- Flags:               -Wall -Wextra -Wno-write-strings 
-- Standard:            Requires C++11
-- Python:              [/opt/pyenv/shims/python2.7] [-python2.7]
-- PCL:                 not enabled
-- pybind11:            not enabled
-- Boost:               106501
-- XercesC:             [/usr/lib/x86_64-linux-gnu/libxerces-c.so] [/usr/include]
-- ZLIB:                1.2.11
-- PyCXX:               [/home/travis/build/FreeCAD/FreeCAD/src]
-- OCC:                 7.3.0 [TKFillet;TKMesh;TKernel;TKG2d;TKG3d;TKMath;TKIGES;TKSTL;TKShHealing;TKXSBase;TKBin;TKBool;TKBO;TKCDF;TKBRep;TKTopAlgo;TKGeomAlgo;TKGeomBase;TKOffset;TKPrim;TKSTEP;TKSTEPBase;TKSTEPAttr;TKHLR;TKFeat]
-- SMESH:               build internal
--  MEDFile:            [/usr/lib/x86_64-linux-gnu/libmedC.so] [/usr/include]
--  HDF5:               1.8.13
--  VTK:                7.1.1
-- NETGEN:              not enabled
-- SWIG:                3.0.12
-- Eigen3               3.3.4
-- Qt4:                 4.8.7
-- QtWebKit:            found
-- Shiboken:            1.2.2 [/usr/include/shiboken]
-- PySide:              1.2.2 [/usr/include/PySide]
-- PySideTools:         [/usr/bin/pyside-uic] [/usr/bin/pyside-rcc]
-- Freetype:            2.8.1
-- OpenGLU:             /usr/lib/x86_64-linux-gnu/libGLU.so [/usr/lib/x86_64-linux-gnu/libGLU.so][/usr/include]
-- Coin3D:              [/usr/lib/x86_64-linux-gnu/libCoin.so] [/usr/include]
-- SPNAV:               [/usr/lib/libspnav.so] [/usr/include]
-- Matplotlib:          2.1.1
-- Rift:                not enabled (BUILD_VR)
-- Doxygen:             not found
=================================================
Now run 'cmake --build /home/travis/build/FreeCAD/FreeCAD/build' to build FreeCAD

So, is the Travis build that is failing, running python 2.7 ??  If so, where did I miss this simple fact?

**Comment by vocx-fc** [comment]
> So, is the Travis build that is failing, running python 2.7 ?? If so, where did I miss this simple fact?

Yes. This problem with the strings only occurs in Python 2.

We test two configurations for Linux with Py3/Qt5, one configuration for Linux Py2/Qt4, and one configuration for Windows Py3/Qt5. Only the Py2/Qt4 fails.

**Comment by sgrogan** [comment]
Is it possible to disable the test for PY2? PY2 is EOL and FreeCAD PY2 support is ending soon anyway.
@bernd is working on this, but...

**Comment by vocx-fc** [comment]
Well, we said we were going to disable the tests for Python 2 as soon as v0.19 was released as stable, but since that hasn't happened yet, we still keep the test. All in all, it isn't an extremely big issue. It would be easier to just disable the particular unit test of FEM that fail, and re-enable them after the issue is solved.

**Comment by Russ4262** [comment]
I think this last fix stands a chance, as it tests for Py2 vs. Py3 and applies fix only for Py2.
 
The problem I am seeing for the past four or five PRs is a problem with the build cache, or the Part WB build...  See the error report.  The gcc-7 build is failing about 16 minutes in at Part-related build error
```
[ 53%] [32m[1mLinking CXX shared library ../../../../Mod/Part/Part.so[0m
[ 55%] Built target Part
```
Any ideas how to fix this problem?  I can't get the gcc-7 over this Part failure issue to test the latest commit in this PR.

Also, thanks for chiming in and providing some feedback.  Much appreciated, gentlemen.

**Comment by vocx-fc** [comment]
This new error is this
```
/home/travis/build/FreeCAD/FreeCAD/src/Gui/DlgExpressionInput.cpp:67:47: error: no matching function for call to ‘QVariant::canConvert(QMetaType::Type)’

         if (text.canConvert(QMetaType::QString)) {
```

This was recently introduced by Werner, in 8c9cdef2a9. I guess it doesn't work on Qt4.

**Comment by Russ4262** [comment]
@WandererFan has PR #3454 that fixes error  in 8c9cdef.   I commited WanderFan's fix to this PR so testing of this fix can move forward.

Thanks for the help, @vocx-fc .

**Comment by Russ4262** [comment]
**HALLELUJAH**!  It passed!  The gcc-7 build passed !!  I'm doing a happy dance, kissing my wife!  
 
… Waiting for the last C++ build to finish and see a wonderful green checkmark by the PR!  So excited!

**Comment by vocx-fc** [comment]
LOL. Don't call it the gcc-7 build, call it the Python 2 build, because that was the problem.

If I'm correct, you essentially changed all calls that do the writing in FEM. While that is probably okay, I think Bernd still has to verify that the code produces the expected output file, and doesn't just pass the test for the sake of passing.

**Comment by Russ4262** [comment]
> If I'm correct, you essentially changed all calls that do the writing in FEM.
Yes, although I'd like to clean up the fix a bit.  Looking at the source file, my code is like a peasant in the presence of the royal family.

> While that is probably okay, I think Bernd still has to verify that the code produces the expected output file, and doesn't just pass the test for the sake of passing. 
Agreed with no arguments whatsoever.  I wouldn't even be offended if this fix is tossed into the local dump and another put in its place.

In the meantime, I'll clean up the fix a little and squash commits.

Thanks for the oversight.

**Comment by Russ4262** [comment]
@vocx-fc 
How do you suggest I handle WandererFan's #3454 fix in this PR? 
1. remove it from this PR altogether,
2. leave it as is in separate commit in this PR,
3. squash it into the single desired commit for this PR?

I suggest #3454 be reviewed and merged before this one. Doing so would answer my question and handle the matter.

Thanks

**Comment by vocx-fc** [comment]
I would have gone with number 2, leave it as a separate commit.

Wandererfan has merge powers, so he can merge his own pull request. Once that happens, you can rebase this branch on the master branch, and Wandererfan's commit will dissapear from your branch. But if your branch is merged first, his commit will also be included, and he will be shown as the author, which is nice. It's nice when everybody is credited in their own commit.

**Comment by Russ4262** [comment]
**_To whomever reviews this PR:_**
Please ensure this PR is merged AFTER #3454 .  And, should there be changes to 3454 with its merger, I will need to rebase this PR prior to final review.  

I do not wish to take credit for @WandererFan 's work, nor is it my intention.  
 
My only intent is to use his fix as a means to reach the necessary build stage in order to test the fixes attempted in this PR.  
Perhaps I went about this incorrectly. My apologies.

**Comment by WandererFan** [comment]
no worries.

**Comment by WandererFan** [comment]
#3454 is merged.

**Comment by Russ4262** [comment]
> #3454 is merged.

Thanks.  I saw and have since rebased this PR.  The fourth build in the Travis CI set should finish in about 10-15 minutes.  Thank you for letting me know and providing that fix.

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/commit/f54eba784b
https://travis-ci.org/github/FreeCAD/FreeCAD/builds/685392758

**Pull request closed without merging**
