### PR TITLE
Path: marlin_post.py

### PR DESCRIPTION
**Pull request by ByronMontgomerie**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
Feedback: the commit titles are unhelpful (their summaries are though).

**Comment by luzpaz** [comment]
@ByronMontgomerie perhaps make this PR a Draft PR until you're ready for it to be merged?

**Comment by sliptonic** [comment]
Please rebase the PR and squash the commits down to just one.  Thanks

**Comment by ByronMontgomerie** [comment]
> Please rebase the PR and squash the commits down to just one. Thanks

I am currently on a chromebook, is it something that can be done on the web page?

**Comment by luzpaz** [comment]
@ByronMontgomerie you should be able to use the command line interface to do that.  
@sliptonic OP didn't separate in to a new branch but worked on master. Do you want me to help out here?

**Comment by luzpaz** [comment]
@sliptonic looks like it can be rebased, squashed, and merged pretty easily. Is there anything else that needs to be done here?

Note: once this post-processor is merged, will the wiki docs need to be updated?

**Comment by berndhahnebach** [comment]
would you rebase the PR to make it run on CI?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by sliptonic** [comment]
The pull request is a request to pull from the submitters repo into the target.  Therefore only the submitter can rebase and squash his commits.  It's a pretty easy operation but they need to do it since we can't do it for them.

**Comment by luzpaz** [comment]
@berndhahnebach care to rebase again?

**Comment by luzpaz** [comment]
@berndhahnebach ping

**Comment by sliptonic** [comment]
This is silly.  I'm closing this pull request.  Original submitter isn't interested in getting it merged.  I've tried diffing it with the current marlin post and there are massive changes but I can't see what specifically they address.
This version appears to be based on a very old version of the post and much has already been done on it.
  In other words, what problems with the current marlin post are fixed by this version?  I don't know.
We aren't getting complaints about the marlin post so I'm closing for now.  If OP wants to reopen it, that's fine.  Please reconcile your work with the current version of marlin in master branch.

**Pull request closed without merging**
