### PR TITLE
Revision of some icons that are incompatible in terms of palette and size

### PR DESCRIPTION
**Pull request by Reqrefusion**
accessories-calculator and accessories-text-editor were 48x48 and incompatible with the palette. They were rebuilt in accordance with the current design guide, reminiscent of their former appearance. I noticed that these icons are not #13769. I'm not entirely sure if these are still used, but I did them anyway. application-exit and camera-photo too.

Actually, I could change an icon like this to take a camera-photo screenshot, but I'll leave those for later. Little steps at a time.

In umf-measurement, some colors that were not in the design guide were replaced with ones that were in the design guide, and icon lines were made better. Some annoying dings have been fixed. Positioning corrected.

### CODE REVIEW

**Comment by maxwxyz** [comment]
@Reqrefusion I like to unify them but they are less polished than before.
It seems the resizing destroyed the stroke width on those icons, it should be 2px for outline and highlight acc. to the artwork guidelines.
Also some icons are not that polished, just a few remarks (different stroke sizes, weird corners,...): 
image
image
image

**Comment by maxwxyz** [comment]
last "fix" has made it worse: 
grafik

I'll mark the PR as draft. If you are ready, squash your commits and mark as ready please.

**Comment by Reqrefusion** [comment]
> last "fix" has made it worse: grafik
> 
> I'll mark the PR as draft. If you are ready, squash your commits and mark as ready please.

Something happened in umf-measurement that was not caused by me, I don't fully understand. I fixed it in general. Is there a problem? Or will I take him out of the draft?

**Comment by Reqrefusion** [comment]
resim
resim
These are the things I wanted to fix in umf-measurement and I fixed it, it's not clear from the small preview.

**Comment by maxwxyz** [comment]
Stroke size on latest commit is still off and the right part doesn't use colors of the palette but the current one does, so in my opinion not an improvement.
image

**Comment by Reqrefusion** [comment]
> Stroke size on latest commit is still off and the right part doesn't use colors of the palette but the current one does, so in my opinion not an improvement. image

I think the distance to the corners is more important in line thickness, but I corrected it as you said.

**Comment by maxwxyz** [comment]
latest commit has still different border appearances as they are not properly aligned. What was you complaint on the original icon, maybe it is easy to fix as stoke width, colors and alignment were good. The changes in this PR are making it not better in my opinion.
image

Also the other icons have all different stroke widths, e.g. this one even in the same shape:
image


@obelisk79 what is your opinion, maybe we should discuss them first instead of directly creating PRs for some icons?

**Comment by obelisk79** [comment]
These look like several simple vector mistakes have been made in the revised icons. I have a bit of a backlog of things right now to get through but we could discuss directly later today if you like.

**Comment by Reqrefusion** [comment]
@maxwxyz My complaints with the original icon were that it did not have equal padding values and the bumps it included were not large enough. Obviously closer to the right. I guess you got it so close to the correct line thickness that you couldn't see that the icon was misaligned. I also want you to look at the mistakes in the picture I posted. Please don't make fun of my mind by saying there is no improvement.
I corrected the stroke value for other icons.
You didn't ask me, but I'll give you an answer anyway. Aren't we already discussing the change made in PR? Isn't it easier to argue about something that already exists?

**Comment by maxwxyz** [comment]
I'm not making fun of anyone but the overhaul should be at least be an improvement and be ready to merge without the need of redoing them again to match the artwork guidelines.
Maybe there are better places to discuss but with each commit you try to fix something but it seems to break something else.
In your latest commit you've replaces the arrow shape highlight outline with a hacked mix of rectangles. Some of them aren't even aligned. This icon would be hard to edit later on.
If you are on discord we can easily discuss and share/optimize them together instead of you fixing comment by comment, committing and pushing to GitHub.
image

**Comment by Reqrefusion** [comment]
I hope it happened this time. I even revised another icon.

**Comment by Reqrefusion** [comment]
@maxwxyz I'm sorry, I thought you knew. That's why I took it a little harshly when you said you didn't see the difference. The overall area covered is very important in icon design. In order for the icons to attract the eye correctly, the total area they cover must be the same or similar. Keylines are used for this purpose. The most commonly used ones are circle, square, vertical rectangle, and horizontal rectangle. A square becomes 18x18, a circle becomes 20x16 in 20 rectangles. When this is adapted to our system, the square should be 54x54 and the circle becomes 60x48 in 60 rectangles. Although the boundaries for squares are not strictly followed, it can be said that the icons for rectangles are generally compatible. This makes square icons more annoying.

**Comment by maxwxyz** [comment]
Last commit seems to destroy the icon even further. Some items remain a stroke with different widths (varying between1,9 px - 2 px), some strokes were replaced with boxes of different widths (between 2,1 - 2,4 px). It is very hard to scale an icon which is made up using strokes and boxes to resemble a stroke.
Also the alignment is off at various locations where stroke and the boxes used as strokes meet. SVG should be saved as plain .svg. Your hacks with boxes and new elements increased the file size to more than double than before.
As previously mentioned, please discuss the changes beforehand instead of creating commit after commit (16 commits for 5 icons). The comment section becomes a chat like this. 
Could you please convert the PR to draft until it is sorted out?

image

image
image

**Comment by maxwxyz** [comment]
@Reqrefusion what software are you using to create the .svg icons? In Inkscape you can use the offset path effect to offset the outer shape for the inner highlight stroke.

**Comment by obelisk79** [comment]
@Reqrefusion, it would probably be better if you collaborated with us on discord on your revisions to get your updated icons smoothed out and production ready rather than repeated back and forth updates here. As it stands right now these have several issues. Please mark this PR in Draft status until everything is ready.

**Comment by Reqrefusion** [comment]
As a result of @maxwxyz tip, I reconsidered and edited the things I changed. The other things I added are mostly trivial. All icons have been resized to ensure that their footprint is similar. They look much better when placed side by side. Stroke values have been changed to those stated in the guide.

Since most icons are only resized, there is no problem, but among them there were icons made to be used on Tango desktop. I remade these to remind them of their old appearance. These are debatable. I might even take it back. But what I have done is compatible with the guide, what exists now is not.

I don't really like Discord. As a rule, there is no obligation. However, if you want to discuss these topics, please tag me on Discord. Why do I make an offer and discuss instead of discussing first and then making an offer? Because that's how I like it and there is no rule that prohibits it.I will make changes collectively based on the feedback, there are a few things I missed. He can see things that I don't see when he's actually here.

I hope I succeeded. Accordingly, I am reopening PR.

**Comment by FEA-eng** [comment]
I'm glad those too detailed icons are simplified in this PR. Little details just don't look good in most setups. Maybe some other icons (like Scene inspector and Macros) could have a similar overhaul.

**Comment by Reqrefusion** [comment]
> I'm glad those too detailed icons are simplified in this PR. Little details just don't look good in most setups. Maybe some other icons (like Scene inspector and Macros) could have a similar overhaul.

Actually I'm doing it right now. But I didn't want to make PR any bigger. I will continue once the PR is approved. Also, there are other PRs sent for similar purposes, so I do not add an icon.

**Comment by maxwxyz** [comment]
I think the bottom right part of the caliper is still too dark on dark themes and should use the highlight color (as is).
The camera icon looks also not pleasant in my opinion.
[clear-selection.svg](https://github.com/FreeCAD/FreeCAD/pull/13840/files#diff-426db3fb555dc9cbde99f896245ad7cae77e937ad728dfd9668c89ca486adc4b) is now the only one in the command group which is scaled down. either all or none. And I wouldn't scale down the cursor icon on it as it is barely visible today.
Terminal icon could be simpler just a black background.
Otherwise I am ok with this change.

**Comment by Reqrefusion** [comment]
> I think the bottom right part of the caliper is still too dark on dark themes and should use the highlight color (as is). The camera icon looks also not pleasant in my opinion. [clear-selection.svg](https://github.com/FreeCAD/FreeCAD/pull/13840/files#diff-426db3fb555dc9cbde99f896245ad7cae77e937ad728dfd9668c89ca486adc4b) is now the only one in the command group which is scaled down. either all or none. And I wouldn't scale down the cursor icon on it as it is barely visible today. Terminal icon could be simpler just a black background. Otherwise I am ok with this change.

I corrected it according to umf-measurement.
The camera received more love. But it's still your say.
Siblings of clear-selection are edited. I didn't touch the cursor in the beginning, anyway, with this arrangement the cursor became more visible.
When you say background for the terminal, do you mean the green part or the white part? I made the terminal icon reminiscent of the old icon. He also used green. I think it's nice that the old icon is kept alive in some way.
By the way, there was a problem with colors.svg, what I did is much better. When it is replaced, the existing icon is turned upside down, making it more incomprehensible.

**Comment by maxwxyz** [comment]
I meant the green part, the flickering screen.
The icon src/Gui/Icons/DrawStyleHiddenLine.svg now looks the same as the wireframe icon, which is not ideal as the display style is very different. Maybe it needs to reflect the triangulation? You can play with the view styles, maybe you have a better idea.

**Comment by Reqrefusion** [comment]
> I meant the green part, the flickering screen. The icon src/Gui/Icons/DrawStyleHiddenLine.svg now looks the same as the wireframe icon, which is not ideal as the display style is very different. Maybe it needs to reflect the triangulation? You can play with the view styles, maybe you have a better idea.

I think that green part looks very nice. Also, I recommend keeping it similar to the old one. Of course, you have the final say.
DrawStyleHiddenLine always looked similar to wireframe. By changing it this way, I tried to ensure similarity between themes. Those white faces only worked in the light theme, but now you can notice that there is nothing there in all themes and can be distinguished more easily from the wire frame. Of course, ultimately the final say is yours.

**Comment by marcuspollio** [comment]
Hi @Reqrefusion 
Thanks for improving the icons too !

A few suggestions for this PR :
- accessories-calculator : I would keep the 9 grey buttons like you had in a previous version (no need for the +-x: operators if lacking space)
- application-exit : have you tried on light and dark theme, is the door panel readable ? If needed, an inner highlight can help.
- camera-photo : the overall shape is better than the original Tango one, but it's too dark and the lens is barely visible. Maybe [some references here](https://icon-icons.com/search/icons/?filtro=camera) can help ?
- cursor-through : the arrow looks skewed
- dagViewPending : what's the purpose of making the hourglass fatter ? Your yellow tint in the original one would suffice IMHO

In a following PR :
- applications-accessories : would be great to browse through all icons with scissors and use the updated ones
- selection-filter : I've always found this icon too busy. Maybe open a topic on the Forum or Discord so more people can have their say (if the current one is good, or what needs changing)

**Comment by Reqrefusion** [comment]
> Hi @Reqrefusion Thanks for improving the icons too !
> 
> A few suggestions for this PR :
> 
>     * accessories-calculator : I would keep the 9 grey buttons like you had in a previous version (no need for the +-x: operators if lacking space)
> 
>     * application-exit : have you tried on light and dark theme, is the door panel readable ? If needed, an inner highlight can help.
> 
>     * camera-photo : the overall shape is better than the original Tango one, but it's too dark and the lens is barely visible. Maybe [some references here](https://icon-icons.com/search/icons/?filtro=camera) can help ?
> 
>     * cursor-through : the arrow looks skewed
> 
>     * dagViewPending : what's the purpose of making the hourglass fatter ? Your yellow tint in the original one would suffice IMHO
> 
> 
> In a following PR :
> 
>     * applications-accessories : would be great to browse through all icons with scissors and use the updated ones
> 
>     * selection-filter : I've always found this icon too busy. Maybe open a topic on the Forum or Discord so more people can have their say (if the current one is good, or what needs changing)

At first I thought of keeping the other keys for **accessories-calculator**, but Windows' calculator was open and I saw its icon. I thought that style would be better, more buttons make it more confusing.

There is already a highlight for **application-exit**. I don't think there will be any problems in either theme. Contrast balance is quite good.

I gave a little too much love to the **camera-photo**, while I was trying to make the lens beautiful, there was a problem with the contrast, so I will correct the parts I went further.

For the **cursor-through**, yes it was a bit skewed as a result of my obsession with sizing. It's a problem with my priorities. But I will size it more properly.

Yes, I want to make changes to other icons for **applications-accessories**, but I am going in alphabetical order. If this pull request is accepted I will continue with the others. If you give the file name, I will add it to this PR.

Yes, it is definitely a complex icon for **selection-filter**. And until I fixed it, the stroke thicknesses were also wrong. The rules were correct, but it still doesn't look very good. I'm standardizing some icons. Remaking this icon, and perhaps the entire selection family, requires some discussion. There's not much need for argument for what I'm doing here.

**Comment by maxwxyz** [comment]
The camera icon: it looks as if it just has a hole with glass behind it, not a forward facing lens. I'm not sure how to convey the depth better...

**Comment by Reqrefusion** [comment]
> The camera icon: it looks as if it just has a hole with glass behind it, not a forward facing lens. I'm not sure how to convey the depth better...

It's always fun to experiment artistically. I experimented some more.

**Comment by maxwxyz** [comment]
In my opinion:
Calculator should not have these scewed / squished strokes at the corners and I would remove the gradients on these small elements as they are not visible at small scale and decrease their visibility:
grafik
Camera still needs some revision, its too crowded and the different elements and gradients make it more complex. Also the lens still seems to go inwards, like a hole:
grafik
In this icon I would also drop the gradients for these small elements and the elements are very thin so the red parts of the scissors don't allow for a highlight so this is not very legible on dark themes:
grafik
Still the icons for wireframe and hidden lines is too similar in my opinion and doesn't reflect their behavior correctly:
grafik
grafik
 
Anyone else wants to weigh in @FreeCAD/design-working-group

**Comment by Reqrefusion** [comment]
> In my opinion: Calculator should not have these scewed / squished strokes at the corners and I would remove the gradients on these small elements as they are not visible at small scale and decrease their visibility: grafik Camera still needs some revision, its too crowded and the different elements and gradients make it more complex. Also the lens still seems to go inwards, like a hole: grafik In this icon I would also drop the gradients for these small elements and the elements are very thin so the red parts of the scissors don't allow for a highlight so this is not very legible on dark themes: grafik Still the icons for wireframe and hidden lines is too similar in my opinion and doesn't reflect their behavior correctly: grafik grafik
> 
> Anyone else wants to weigh in @FreeCAD/design-working-group

I didn't notice the calculator so I corrected them. I also corrected the colors etc.
I tried again for the camera, but the other things are okay, if that is missing, we can remove it from this PR.
I made the corresponding change for the scissors and used tonal differences to add some dimension. It was pretty nice.
The reason why the difference in the DrawStyle group cannot be understood is that the perspective of the cube is bad. This is not a problem caused by me, but I solved it anyway and the whole group is now better understood. It was also compatible with the cubes in other icons. It was a problem that I avoided because it was necessary to replace the entire group.

**Comment by Reqrefusion** [comment]
Ready to merge.

**Comment by maxwxyz** [comment]
Thank you. Could you squash your 30 commits into one?

**Comment by Reqrefusion** [comment]
Unfortunately I received various errors. It's a general problem with my way of working, unfortunately. That's why I opened a clean PR. It's very sad, it's always happy to see something that has lasted such a long time finally come to an end. Unfortunately, I will not be able to fully experience that happiness.

New PR: #14154

**Pull request closed without merging**
