### PR TITLE
[Gui] - Fix Part Design issues with arbitrary tree ordering

### PR DESCRIPTION
**Pull request by pavltom**
This PR aims to fix problems caused by newly available arbitrary tree item ordering, discussed in this forum topic:

https://forum.freecadweb.org/viewtopic.php?f=3&t=63744

### CODE REVIEW

**Comment by mwganson** [comment]
I built and tested.  It works to resolve the issues as far as I can tell.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5195">pipeline status</a> for feature branch [PR_5195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5195). Pipeline [414385004](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/414385004) was triggered at [c78c02f](https://github.com/FreeCAD/FreeCAD/pull/5195/commits/c78c02f45144edf87ece4ffc7d5a8feb27a8dbd9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5195">pipeline status</a> for feature branch [PR_5195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5195). Pipeline [414385508](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/414385508) was triggered at [00fc60b](https://github.com/FreeCAD/FreeCAD/pull/5195/commits/00fc60b584dd118146d343f61f42072a67f8a41c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
As there are still some more issues identified in that forums discussion, I've reverted the original merge in commit c9a74d4 -- I'm going to close this PR since it doesn't make sense now, but once you've worked out the issues in that discussion, please resubmit the whole thing again. Thanks!

**Pull request closed without merging**
