### PR TITLE
Global: apply guidelines

### PR DESCRIPTION
**Pull request by 0penBrain**
```
find ./ -iname "*.cpp" -not -path "./src/3rdParty/*" \( -exec perl -p -e 's/(^[[:space:]]*)(if[\ \(](?:(?!\/[\/\*]).)*?)[[:space:]]*(return(?:\;(?!\\)|\ .*?(?!\\)\;(?!\\)))((?:(?!\\)[[:space:]]*\/[\/\*].*))?/\1\2\4\n\1    \3/g' -i {} \; -exec perl -p -e 's/^([[:space:]]*?)([[:space:]]{4})(return[\ \;][^\{]*?(?:\/\*.*\*\/)?[^\{]*?)[[:space:]]*(\}.*)/\1\2\3\n\1\4/g' -i {} \; \)
```

Only applied on cpp files excluding 3rd party

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6497">pipeline status</a> for feature branch [PR_6497](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6497). Pipeline [483331890](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/483331890) was triggered at [84e8d9c](https://github.com/FreeCAD/FreeCAD/pull/6497/commits/84e8d9c889e038426ad980f437d0a8d4aa072c4f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
IMHO this kind of large cleaning operation should be postponed to after the 0.20 release...

**Comment by 0penBrain** [comment]
Up to you. But that's at no risk as it's easy to check that compiled binaries are same before and after. ;)

**Comment by luzpaz** [comment]
When the time does come and if this approach is approved, IMHO consider breaking the PR up in to several commits categorized by the directory tree where each commit addresses a different part of the `./src/` hierarchy.

**Comment by chennes** [comment]
The only downside to this type of cleanup is that it's going to introduce a bunch of conflicts for anyone working on these chunks of code. They are trivial to resolve, but still some work for authors. I propose that we do this for 0.20, but do it _last_, after reviewing all of the other PRs we intend to merge. As @0penBrain mentions, we can easily verify that the compiled binaries are identical, so there is no danger of introducing regressions. And the provided shell script can simply be run anew by one of us, without actually having to rebase this PR (that is, we technically ignore the PR itself, but directly apply the script).

**Comment by donovaly** [comment]
> I propose that we do this for 0.20, but do it last

I agree. This is the same as with PR #4556

@chennes , can I give this task in your hands?

**Comment by chennes** [comment]
Yes, I can do both this and #4556 when you give me the go-ahead that we are ready for it.

**Comment by luzpaz** [comment]
Since we're about to run the code over with a tractor, might as well do #5578 as well ?

**Comment by donovaly** [comment]
> Since we're about to run the code over with a tractor 😜 might as well do https://github.com/FreeCAD/FreeCAD/issues/5578 as well ?

This needs to be discussed first. Can you please open a thread in the developer's forum?

**Comment by luzpaz** [comment]
@donovaly here's the original thread https://forum.freecadweb.org/viewtopic.php?t=19866

**Comment by donovaly** [comment]
> @donovaly here's the original thread https://forum.freecadweb.org/viewtopic.php?t=19866

Thanks. The question if this is still relevant. The thread is 5 years old and meanwhile Git's standard is to commit as is. I am on Windows and here I only get issues when a file has mixed line endings. Bit by bit there files go away.
You can open a new thread to discuss if handling the line endings is still an issue.

**Comment by adrianinsaval** [comment]
Aren't the mixed line endings exactly what is trying to be solved? Anyways, would it be a good idea to include this PR's commit in the .git-blame-ignore-revs file? As it doesn't really change the intent of any of the code, just the formatting.

**Comment by chennes** [comment]
> would it be a good idea to include this PR's commit in the .git-blame-ignore-revs file? As it doesn't really change the intent of any of the code, just the formatting.

Yes, IMO -- it is my intention to do so.

**Comment by donovaly** [comment]
@chennes , will you do this today or later?

**Comment by chennes** [comment]
I'll take care of it later this evening, things got busy at work.

**Comment by chennes** [comment]
@0penBrain when I run your script, I am not seeing proper indentation on the `return` lines -- they are only indented a single space more than the `if`, rather than four. This happens whether I run it on Windows or Linux. Can you investigate?

**Comment by 0penBrain** [comment]
@chennes we'll look at this. Maybe it has to wait for tomorrow. :)

**Comment by 0penBrain** [comment]
OK, see the problem. The snippet is correct when I edit it in the PR description, but isn't when it's displayed or quoted.
There shall be 4 spaces between '\1' and '\3' (there is only one place where those 2 follow each hand other -- with space in between --, tell me if you can't find it).

**Comment by chennes** [comment]
Applied as:
70488c8f26 Git: PR6497 Ignore commits in git blame
3ef6811dae Web: PR6497 move return statement to new line
c44ccc0ff2 TD: PR6497 move return statement to new line
cb21ac7bf8 Spreadsheet: PR6497 move return statement to new line
1ee046788d Sketcher: PR6497 move return statement to new line
190d64bdae Sandbox: PR6497 move return statement to new line
ec74d351f0 Robot: PR6497 move return statement to new line
1e9236abd4 Raytracing: PR6497 move return statement to new line
bac451cc53 Points: PR6497 move return statement to new line
5f31fb74f6 Path: PR6497 move return statement to new line
6f230d7404 PD: PR6497 move return statement to new line
0a65575c2c Part: PR6497 move return statement to new line
702238a99c Mesh: PR6497 move return statement to new line
35156cdce3 Import: PR6497 move return statement to new line
bb0e2f1c51 FEM: PR6497 move return statement to new line
b13088664f Draft: PR6497 move return statement to new line
1ea364379f Tools: PR6497 move return statement to new line
3b42d4afac Base: PR6497 move return statement to new line
bedf920702 Gui: PR6497 move return statement to new line

**Pull request closed without merging**
