### PR TITLE
Tools: Add workaround for lupdate missing source

### PR DESCRIPTION
**Pull request by chennes**
`lupdate` requires at least one C++ source file to be present in order to process the project file. In cases where a workbench is Python-only, this resulted in incorrect or missing extraction of strings in ui files. Those files should have been processed by `lupdate`, but were not. `pyludate` was not configured to process them. To work around this, the `updatets.py` script is modified to create a dummy `*.cpp` file before running `qmake`.

### CODE REVIEW

**Comment by chennes** [comment]
@yorikvanhavre can you test this out and make sure it doesn't result in any catastrophes? I discovered this issue while trying to figure out why addon manager's dialogs weren't being translated correctly, despite having available translations.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5318">pipeline status</a> for feature branch [PR_5318](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5318). Pipeline [439975721](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/439975721) was triggered at [3e75db0](https://github.com/FreeCAD/FreeCAD/pull/5318/commits/3e75db0d58caeb8f0ec4e58c63cdae0c41e381f7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5318">pipeline status</a> for feature branch [PR_5318](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5318). Pipeline [440102854](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/440102854) was triggered at [d6ad9f5](https://github.com/FreeCAD/FreeCAD/pull/5318/commits/d6ad9f50bc67a028f460ed1c378e3550730357bb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
I tested this. The only anomalies I found is that the Draft wb had a lot of file changes and I wasn't sure if that was just normal Draft workbench weekly code changes by Roy or something that was done by this PR.

**Comment by luzpaz** [comment]
@chennes this looks pretty straight-forward to merge, IMHO

**Comment by chennes** [comment]
Since we need @yorikvanhavre to run it even once it's merged, I'll just leave it here on his "To-Do" list 😎.

**Comment by yorikvanhavre** [comment]
Sorry guys, got a bit overwhelmed here. Running and testing right now!

**Comment by yorikvanhavre** [comment]
Ok I just tested and I only see additions, basically no subtractions. Seems good to go!

**Comment by yorikvanhavre** [comment]
Doing a crowdin merge cycle too now...

**Pull request merged**
