### PR TITLE
Added RevitNavigationStyle

### PR DESCRIPTION
**Pull request by Eneen**
I've added RevitNavigationStyle based directly on BlenderNavigationStyle.

### CODE REVIEW

**Comment by wwmayer** [comment]
Merged.

**Comment by luzpaz** [comment]
@Eneen thanks for this PR. Could you please update our mouse style docs at  https://freecadweb.org/wiki/Mouse_Model with this new Revit style?
If you need wiki access let me know what user and email address you'd like to use and I'll set you up with an account. Thanks!

**Comment by Eneen** [comment]
Sure I'll do this. One thing I have to wait for is ALT key addition, but can't do this myself. After this I will be able to create all key combos.

**Comment by luzpaz** [comment]
@eneen please ask on the FC forum for some help..better to integrate functionality while you're on a roll instead of it remaining incomplete.

**Comment by Eneen** [comment]
@luzpaz I'll do this, thx.

**Pull request closed without merging**
