### PR TITLE
FEM Netgen Min. Size

### LINKED ISSUE #12716: [Problem] Missing min element size setting for Netgen FEM mesher
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

[FEM MeshNetgenFromShape](https://wiki.freecad.org/FEM_MeshNetgenFromShape) is currently missing an important setting in FreeCAD FEM - **Min. Size**. Netgen itselfs supports it so it shouldn’t be a problem to add it.

Old forum discussion: https://forum.freecad.org/viewtopic.php?t=12304

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36082 (Git)
Build type: Release
Branch: main
Hash: 7a025e4e60a607bdbdd1599627ce13bb8eeda071
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
fixes #12716

@marioalexis84 Can you test this later? It looks ok on Ubuntu but there are known issues when compiling with Netgen (not only on my side) so it would be good if you could confirm that it works properly - actually affects the mesh.

Perhaps someone could also compile on Windows? It seems that Netgen works much better there and maybe doesn't cause those compilation issues (btw. I wonder if they are fixable).

### CODE REVIEW

**Comment by marioalexis84** [comment]
The last time I tried I had compilation problems with Netgen. I'll try again.

**Comment by FEA-eng** [comment]
> The last time I tried I had compilation problems with Netgen. I'll try again.

Thanks. I'm afraid those issues are persistent but it would be good to finally get rid of them, if possible. [Werner's reply](https://forum.freecad.org/viewtopic.php?t=85829#p744778) doesn't fill me with optimism though. Fortunately, Netgen works very well on Windows. Perhaps I should create another GitHub issue about those problems on Ubuntu but if they are as deep as they appear to be then it might be better to leave them for now so that we don't waste our time on this and focus on other FEM issues instead.

**Comment by yorikvanhavre** [comment]
@marioalexis84 can you look again?

**Comment by marioalexis84** [comment]
The new property is added correctly and the task dialog is fine too.
Unfortunately I can't test the mesher properly as it crashes when the object is executed.

**Comment by FEA-eng** [comment]
> Unfortunately I can't test the mesher properly as it crashes when the object is executed.

Yeah, I had the same and user1234 confirmed that it happens even without those changes: https://forum.freecad.org/viewtopic.php?t=85829#p744851

It would be great if someone could check this on Windows.

**Comment by chennes** [comment]
I tested this on Windows today and it appears to work -- at least, I got no errors, and when I changed the minSize the number of cells in the mesh changed. Is that evidence enough that it is working properly?

**Review by chennes — COMMENTED** [review]
I tested this on Windows today and it appears to work -- at least, I got no errors, and when I changed the minSize the number of cells in the mesh changed. Is that evidence enough that it is working properly?

**Comment by marioalexis84** [comment]
Should be enough. Once in main, @FEA-eng can also test on Windows.

**Comment by FEA-eng** [comment]
> I tested this on Windows today and it appears to work -- at least, I got no errors, and when I changed the minSize the number of cells in the mesh changed. Is that evidence enough that it is working properly?

Yes, I tested this in the newest weekly and it's working. Thanks.

**Pull request merged**
