### PR TITLE
App: Modernisation #1

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---
First PR tackling the easiest targets for updating. Hopefully not controversial.
[https://forum.freecadweb.org/viewtopic.php?f=10&t=68041&sid=ccefd2574b95fb67dfc502484ea3b5fa](url)
berniev aka FreddyFreddy in fc forum.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6794">pipeline status</a> for feature branch [PR_6794](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6794). Pipeline [524417078](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/524417078) was triggered at [c3cfd5b](https://github.com/FreeCAD/FreeCAD/pull/6794/commits/c3cfd5b3a0198f7c92231afa9a56e6ea7fa24413). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Overall this looks good, but it appears that in several places a `const_iterator` has been replaced with a non-const `auto &` in a ranged `for` loop -- I'd prefer to retain the `const` whenever it's possible, which at a quick glance appears to be all of these cases.

**Comment by wwmayer** [comment]
There are a couple of blocks like
```
#ifdef __GNUC__
...
#else
...
#endif
```
where the else branch hasn't been updated which will cause a build failure

**Comment by berniev** [comment]
@wwmayer Interesting. It did build and install ok (tested). The first half has been updated, not the else half. I will investigate!!

**Comment by berniev** [comment]
@chennes Does the const_iterator offer a technical advantage in any way? Is there a downside you are willing to carry to maintain a preference? No offence: I don't know. Why did format advise the change?

**Comment by luzpaz** [comment]
CC @realthunder just wanted you to be aware about this PR (if it has implications for downstream Link branch breakage)

**Comment by berniev** [comment]
@wwmayer if the else part were formatted like the if part would that satisfy you for this question? Has it ever been a consideration to move compiler-conditional functions out into a e.g. compat file?

**Comment by berniev** [comment]
@chennes I see most, but not all, all const_iterator became const auto &. Trying to figure out why. Will be a pain to have to tickle these manually.

**Comment by berniev** [comment]
@chennes at Application.cpp line 2825 is `std::map<std::string,std::string>::iterator It =` (not a `const_iterator`) which became `for (auto & It`. Is the type of iterator sufficient to decide const?

**Comment by wwmayer** [comment]
> at Application.cpp line 2825 is `std::map<std::string,std::string>::iterator It =` (not a `const_iterator`)

No, it's not. But it would be good to use a const iterator here. So the new code should become:
`for (const auto & It : mConfig)`

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6794">pipeline status</a> for feature branch [PR_6794](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6794). Pipeline [526967695](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/526967695) was triggered at [3cab9a3](https://github.com/FreeCAD/FreeCAD/pull/6794/commits/3cab9a3b858223cb2743c7c42477f3d9a5070ab7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request closed without merging**
