### PR TITLE
Bug fix for ID#0002453

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
Note that the version of Bison and Flex used to generate the two .c files are newer than
in the last commit from 2010. Also,for anyine working on tbis in the future, dont forget
to run flex and bison on the .l and .y files respectively.

Edit: added updated for bug ID#0002513. For future pull requests I'll do this in separate branches, sorry.

### CODE REVIEW

**Comment by ezzieyguywuf** [comment]
wwmayer - I've added commit 7608609 which fixed that typo.

**Comment by ezzieyguywuf** [comment]
Merged another commit, I did not realize that the code was not compiling.

**Comment by wwmayer** [comment]
Now things got messed up a bit. This branch includes the changes of the quantity parser of your other branch. I will have a look at it the next days...

**Comment by ezzieyguywuf** [comment]
yes, I foolishly put my changes for both fixes on my 'main' branch. moving
forward I will create a new branch for each pull request. sorry for the mix
up, and thank you for taking the time to review.

**Comment by wwmayer** [comment]
Merged and reworked.

**Pull request closed without merging**
