### PR TITLE
source typo fixes pt4 (only on py3 merged code)

### PR DESCRIPTION
**Pull request by luzpaz**
issue 2914
ref: https://github.com/looooo/FreeCAD/issues/8

### CODE REVIEW

**Comment by rautamiekka** [comment]
Would be great if you referenced the issue numbers with a working link instead of just 'issue 2914' which is achieved with the leading hash in the number.

**Comment by wwmayer** [comment]
Merged.

**Comment by luzpaz** [comment]
> Would be great if you referenced the issue numbers with a working link instead of just 'issue 2914' which is achieved with the leading hash in the number.  
@rautamiekka that would be ideal, wouldn't it? Though by using a hash it will reference a **github** issue and not **mantisbt** which is the framework that FC uses as their tracker. The issue I'm referring to is: https://freecadweb.org/tracker/view.php?id=2914
...which reminds me, @wwmayer why isn't mantisbt referencing the changeset when i write 'issue 2914' must it be in the github issue title ?

**Comment by wwmayer** [comment]
You must write issue #2914 in your log message.

**Comment by luzpaz** [comment]
@wwmayer right now we're OK since we're under 560 issues on github...but when we get to a point of parity with github and mantisbt... will it still work ?

**Comment by bblacey** [comment]
>Commit Messages
>
>In addition to the changesets showing up in MantisBT you can add information to your commit >message to automatically resolve the bugs related to the commit.
>
>Just include `fixed #101` in the commit message and issue 101 will be marked as fixed and resolved. >You can include multiple issues separated by commas – `Fixed #101,#123`

So you just want to add something like `fixes 2914` and when Werner merges the PR, Mantis will close it.  Here is a recent example:

PR: https://github.com/FreeCAD/FreeCAD/pull/571
Mantis issue: https://freecadweb.org/tracker/view.php?id=2928

Notice the `Fixes #2928` in the PR resulting in the Mantis issue being closed upon merge.

**Pull request closed without merging**
