### PR TITLE
[FEM] improve cylinder function

### PR DESCRIPTION
**Pull request by donovaly**
- set better initial position and size
- add misting triggering of ViewProvider
- some code style improvements (fix too long lines, consistency etc.)

### CODE REVIEW

**Comment by donovaly** [comment]
Current master:
FreeCAD_x3DtJq1pVN

with this PR:
FreeCAD_2vSkZGAtf7

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8789">pipeline status</a> for feature branch [PR_8789](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8789). Pipeline [800610399](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/800610399) was triggered at [f5c12a9](https://github.com/FreeCAD/FreeCAD/pull/8789/commits/f5c12a964b055864842d4241423307348e38598b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by marioalexis84** [comment]
Ok to me.
`ViewProviderFemPostFunction::onChanged` is already called by inheritance, if `ViewProviderFemPostCylinderFunction::onChanged` only call it, there is no need to override.

**Comment by donovaly** [comment]
>`ViewProviderFemPostFunction::onChanged` is already called by inheritance, if `ViewProviderFemPostCylinderFunction::onChanged` only call it, there is no need to override.

Thanks. This was a leftover from my attempts to scale the jack manipulator but keeping the blue lines of the cylinder independent. I removed `ViewProviderFemPostFunction::onChanged` now.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8789">pipeline status</a> for feature branch [PR_8789](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8789). Pipeline [801452950](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/801452950) was triggered at [6807c76](https://github.com/FreeCAD/FreeCAD/pull/8789/commits/6807c766e7e007c33e5914e8b707c6657cc34531). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by marioalexis84** [comment]
Ideally, in your opinion, what would be the scaling behavior of the manipulator in relation to the size of the cylinder? change the radius but leave the height constant?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8789">pipeline status</a> for feature branch [PR_8789](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8789). Pipeline [801463331](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/801463331) was triggered at [34fed12](https://github.com/FreeCAD/FreeCAD/pull/8789/commits/34fed121429e06e77de8bb54aa4b6a4af27555a7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> Ideally, in your opinion, what would be the scaling behavior of the manipulator in relation to the size of the cylinder? change the radius but leave the height constant?

I tried to make the "plate" of the jack manipulator smaller than the cylinder but this is not possible it seems.
For the initial view i also tried to make the radius larger but keeping the height of the blue cylinder preview lines constant. I failed to do this.
But I think as it is now it is better as before and in reality the users adapt the radius anyway to their special use case.

**Comment by marioalexis84** [comment]
Ok, I did something like that when writing the code. You need to change the parts of the dragger and add another SoSeparator to the node. I will try again after write the cube function.

**Review by marioalexis84 — APPROVED** [review]

**Pull request merged**
