### PR TITLE
i18n: Manually update language files from Crowdin

### PR DESCRIPTION
**Pull request by PushKK**
Update Russian language from Crowdin for Mods:
- AddonManager,
- Image.

Last update - 4 months ago.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7540">pipeline status</a> for feature branch [PR_7540](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7540). Pipeline [655575118](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/655575118) was triggered at [927bbd8](https://github.com/FreeCAD/FreeCAD/pull/7540/commits/927bbd8eff8d7dcae8e4e7d6d35752a9f5b687e1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@yorikvanhavre , can you please have a look or maybe update from Crowdin for all languages?

**Comment by yorikvanhavre** [comment]
Weecan already merge those... @PushKK these changes are on crowdin too, right? BtW @donovaly I'll start merging crowdin translations again ok? Uhey will therefore not be compatible anymore with bugfix releases, but i think by now we can bear with it..

**Review by yorikvanhavre — APPROVED** [review]

**Comment by PushKK** [comment]
@PushKK these changes are on crowdin too, right?

Yes, it's from Crowdin.

**Comment by donovaly** [comment]
>  @donovaly I'll start merging crowdin translations again ok? 

Yes, please.
Toponaming makes some progress so I think we can start with focus on a new major release in some months. (not sure yet if 0.21 or a 1.0 though)

**Comment by donovaly** [comment]
I tried if I can backport and it worked. So the changes here will be in FreeCAD 0.20.2

**Pull request merged**
