### PR TITLE
Path: mediate JobEdit tool name truncation

### PR DESCRIPTION
**Pull request by J-Dunn**
Reducing feed-rate column headers to V and H to reduce truncation of tool names to a uninformative "TC:... "  due to  (Qt.ElideMode) bugginess.
Adds "feed-rate"+vUnit to hover hint. 

https://forum.freecad.org/viewtopic.php?p=676248

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9295">pipeline status</a> for feature branch [PR_9295](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9295). Pipeline [839167915](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/839167915) was triggered at [a009da1](https://github.com/FreeCAD/FreeCAD/pull/9295/commits/a009da1af1a627c8b4a1eb82ac8ffc6f792c81db). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Looks good! Hopefully the translators will understand it ? 

For convenience (copied from the forum thread)

## Before 
image

## After
image

**Comment by luzpaz** [comment]
Just a minor tweek: please modify the git commit title of  the whitespace between `Path` and `:` in the commit title by amending the commit  

```git 
git commit -amend -m "Path: mediate JobEdit tool name truncation" -m "reducing feed-rate column headers to V and H to reduce truncation due to  (Qt.ElideMode) bugginess."
git push --force
```

TIA!

**Comment by sliptonic** [comment]
I like it.  If you're concerned about the translators being confused, why not add 'horizontal' and 'vertical' to the tooltips?
"Horizontal Feedrate "+vUnit

**Comment by J-Dunn** [comment]
That may have been a good idea for the tool tips but translators have to look at the context, not just an isolated word in order to do a translation.  Imagine trying to translate the word "right" without knowing the context .  It's not really a problem.

**Comment by chennes** [comment]
You can add a comment to translations: we don't do it very often, but for example:
```
translate("Path", "V", "V is short for 'Vertical feed rate')
```

**Comment by luzpaz** [comment]
@chennes TIL! we should add this as standard procedure. It could help translators with units and weird translation quirks like #8046

Edit: I'm assuming crowdin picks up on this 3rd field ?

**Comment by J-Dunn** [comment]
I have found the real root cause of all this silliness:  the table cells are getting word-wrapped and it sees the colon as a breakable character. 
`
        self.form.toolControllerList.setWordWrap(False)`

The concise H and V are still beneficial but the reason it breaks on words and not chars is because of word wrap. Then obviously the wrapped bit is invisible because the rows only display one line. 

Once WordWrap is false you get character based eliding and a much more sensible and useful display. 

I have a modified Job.py , if I upload it to my repo in place of the current one, will it get integrated into this PR ?

**Comment by sliptonic** [comment]
> I have a modified Job.py , if I upload it to my repo in place of the current one, will it get integrated into this PR ?

Yes.  The PR just references your repo and branch so you can add an additional commit and push/force to your repo/branch.  It will trigger the CI to rerun

**Comment by J-Dunn** [comment]
Thanks. This turns off WordWrap and fixes the underlying issue. 
 I've added translate() to the new tooltip texts and  translation comments as suggested above.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9295">pipeline status</a> for feature branch [PR_9295](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9295). Pipeline [842688301](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/842688301) was triggered at [da7607f](https://github.com/FreeCAD/FreeCAD/pull/9295/commits/da7607fc2dbbf7fcbbd169a04b0177141ada1441). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9295">pipeline status</a> for feature branch [PR_9295](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9295). Pipeline [842917680](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/842917680) was triggered at [f95b832](https://github.com/FreeCAD/FreeCAD/pull/9295/commits/f95b832efabad11d5255223d4fe9831838f22bd4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
