### PR TITLE
ArchWall : Bug Fix Length Property Accuracy Problem

### PR DESCRIPTION
**Pull request by paullee0**
Fix https://github.com/FreeCAD/FreeCAD/issues/15794

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Will look at it after M3

**Comment by yorikvanhavre** [comment]
I swear I will look at it :)

**Comment by yorikvanhavre** [comment]
This PR causes CI errors that need to be fixed...

**Comment by paullee0** [comment]
Thanks for checking, anything I need to do (I have no idea what is cl error)

**Comment by paullee0** [comment]
OK, I was curious how to use the TestArch.py, checking around and it seems the Test Framework wb runs it, right?

It seems it runs and nothing wrong here, in Fedora 40...


Screenshot from 2024-11-08 06-59-59

Screenshot from 2024-11-08 07-00-14

**Comment by paullee0** [comment]
OK, I should have found where it failed, I will try editing the files on github, it works?

```

                            elif curAligns == "Center":
                                if layers:
                                    totalwidth=sum([abs(l) for l in layers])
                                    curWidth = abs(layers[i])
                                    off = totalwidth/2-layeroffset
                                    d1 = Vector(dvec).multiply(off)
                                    wNe1 = DraftGeomUtils.offsetWire(wire, d1,
                                                                     wireNedge=True)
                                    layeroffset += curWidth
                                    off = totalwidth/2-layeroffset
                                    d1 = Vector(dvec).multiply(off)
                                    wNe2 = DraftGeomUtils.offsetWire(wire, d1,
                                                                     wireNedge=True)

```


Screenshot from 2024-11-08 23-45-51

**Comment by paullee0** [comment]
I  have another look at your previous comment and wonder why it passes on Windows?  It shouldn't.

Some problem with the Test framework?


> In this case:
> 
> ```
>  Traceback (most recent call last):
>   File "/usr/local/Mod/BIM/TestArch.py", line 432, in testWallMultiMatAlign
>     self.assertTrue(ptMin.isEqual(checkLst[i][0], 1e-8),
>   File "/usr/lib/python3.8/unittest/case.py", line 765, in assertTrue
>     raise self.failureException(msg)
> AssertionError: False is not true : Arch Wall with MultiMaterial and 3 alignments failed
> ```
> 
> Basically this testWallMultiMatAlign does not pass anymore with this PR. The strange thing is, it only fails on Linux, but still passes on Windows...
> 
> Anyway, I suggest you try reproducing the steps in the test, see what can have failed... `ptMin.isEqual(checkLst[i][0], 1e-8)` makes me think it might be a question of precision, and raising that value a bit might solve the issue while still making the test meaningful...

Precision is definitely something else.

**Comment by yorikvanhavre** [comment]
O thanks! I'll give it a test spin and merge

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
