### PR TITLE
Group fixes

### PR DESCRIPTION
**Pull request by ickby**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

This pull request adds many useful things for handling Groups and GeoFeatureGroups. It improves object adding, Drag'n'Drop, undo/redo, DependencyGraph visualisation, Placement calculation and dependency tracking.

The changes do not add support for forbidding cross coordinate system links or new link properties to handle that as initially discussed. This will be part of another pull request, as it requires more research.

### CODE REVIEW

**Comment by luzpaz** [comment]
BTW, @ickby does this PR address any open mantis tickets ?

**Comment by ickby** [comment]
@lupaz I don't know. Most of this code is already a bit older, I did some cherry picking and updating now to submit the PR.  There have been a few forum topics about issues that are going to be solved with this code, but tracker issues I don't know anymore. I can have a look through the tracker later, need to tackle that build failure anyway...

**Comment by luzpaz** [comment]
Possible tickets:
https://freecadweb.org/tracker/view.php?id=2142
https://freecadweb.org/tracker/view.php?id=2567
https://freecadweb.org/tracker/view.php?id=2871

**Comment by ickby** [comment]
@luzpaz thanks for looking those up. I think those three are fixed:

https://freecadweb.org/tracker/view.php?id=2142
https://freecadweb.org/tracker/view.php?id=2835
https://freecadweb.org/tracker/view.php?id=2835

**Comment by ickby** [comment]
Rebased to current master

**Comment by wwmayer** [comment]
Merged.

**Comment by sasobadovinac** [comment]
Go Werner! 👍 :)

**Pull request closed without merging**
