### PR TITLE
UI: update assembly icons to be consistent with main updates

### PR DESCRIPTION
**Pull request by maxwxyz**
Consistency following https://github.com/FreeCAD/FreeCAD/pull/13865
- update assembly icons to be consistent with main updates
- add commands to menu/toolbar.

### CODE REVIEW

**Comment by Reqrefusion** [comment]
resim
The previous icon has the same problem, and this one also has the same problem. It would be much better if the total area covered by the icon was the same, with different distances to the sides.

**Comment by maxwxyz** [comment]
Adjusted to match icon in main.

**Comment by Reqrefusion** [comment]
@maxwxyz As I said in the other PR, 60x60 icons should be 54x54. Assembly_ExplodedViewGroup.svg, Assembly_JointGroup.svg, Assembly_SolveAssembly.svg these should definitely be reviewed. Adjustments to the size of other icons can be made, it is completely optional. Since the purpose of these PRs is unification, I think the sizing rules should be taken into consideration.

**Comment by chennes** [comment]
@PaddleStroke these features are ready to be out of "experimental stage"?

**Comment by PaddleStroke** [comment]
I would recommend that the features are left in experimental stage for about 2-3 months so that they can be tested by power users to make sure we iron out any outstanding issues.

**Comment by FEA-eng** [comment]
> I would recommend that the features are left in experimental stage for about 2-3 months so that they can be tested by power users to make sure we iron out any outstanding issues.

But this means that they will be available but not visible in the next stable release the whole time so most regular users (who often discover bugs thanks to extensive usage) won't have a chance to test them. Maybe at least add an easier way to activate them (like a preference) for those users?

**Comment by chennes** [comment]
Considering that Ondsel has these enabled in their recent release, it seems like that are stable enough for general use (or if they are not, then we do need to get them in front of users ASAP if we hope to have them in the 1.0 release)

**Pull request merged**
