### PR TITLE
OpenSCAD: Get rid of SCAD-Import error in importCSG.py

### PR DESCRIPTION
**Pull request by gneiss15**
Get rid of SCAD-Import error in importCSG.py:
`<class 'KeyError'>: 'center'`
This Error will be raised when using newer versions of OpenSCAD,
that don't store the default (false) value for 'center'

Signed-off-by: Günter Neiß <gneiss@web.de>

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7301">pipeline status</a> for feature branch [PR_7301](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7301). Pipeline [603788658](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/603788658) was triggered at [560b142](https://github.com/FreeCAD/FreeCAD/pull/7301/commits/560b142f594985b355fb38eedaaa9c46f796874d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by gneiss15** [comment]
More infos, see: [https://forum.freecadweb.org/viewtopic.php?f=10&t=70761&p=614795#p614795](url)

**Comment by luzpaz** [comment]
Please add OpenSCAD to the commit title:  
`git commit --ammend --signoff -m "OpenSCAD: remove SCAD-Import error in importCSG.py"`

**Comment by gneiss15** [comment]
Sorry, the command given "git commit --ammend ..." fails here with "error: unknown option `ammend'"
Because You already changed the title, is it still necessary to use this command ?
(I am not so familiar with git, I use subversion most of the time)

**Comment by luzpaz** [comment]
Sorry here you go:  
```shell
git commit --amend --signoff -m "OpenSCAD: remove SCAD-Import error in importCSG.py"
git push --force
```

Note: use `git rebase` over `git merge` (as the former doesn't pollute the git history). Also always make a branch off of master instead of directly modifying master. `git checkout -b my-branch` (this create the branch and switches you right in to it)

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7301">pipeline status</a> for feature branch [PR_7301](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7301). Pipeline [604012072](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/604012072) was triggered at [404a6e7](https://github.com/FreeCAD/FreeCAD/pull/7301/commits/404a6e7f7df59a294bddf346188bb91837036dd2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by gneiss15** [comment]
OK, I had done as directed.
The first command I had done already (as mentioned)
The second one is running right now (it writes a lot of files ???)
For me it's not clear what You mean with Your note.
I had made a fork into my account, modify the files there and made a PR from my "master" branch.
This is the way I had done already some times on other repos (mostly Arduino) and the maintainers there request this way, so did I understood You right, that I should:
- fork
- create a branch inside my repro
- make my changes inside this branch
- make the PR from this branch

**Comment by chennes** [comment]
The purpose of @luzpaz 's suggestion is to amend your actual commit message, so that when viewed in this list:
https://github.com/FreeCAD/FreeCAD/commits/master
it will have "OpenSCAD" at the beginning. That helps devs see what parts of FreeCAD are changing at a quick glance. So when you are making a commit, just make sure it's `git commit -m "OpenSCAD: Did the thing to the other thing"` or whatever.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7301">pipeline status</a> for feature branch [PR_7301](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7301). Pipeline [604062993](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/604062993) was triggered at [32b5274](https://github.com/FreeCAD/FreeCAD/pull/7301/commits/32b52742c7be85fbb1f009075e0f69902ca0b714). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by gneiss15** [comment]
Thanks, very fast commit

**Pull request merged**
