### PR TITLE
Gui: Add missing close paren in PythonWrapper.cpp

### PR DESCRIPTION
**Pull request by chennes**
Fix compilation problem.

### CODE REVIEW

**Comment by 3x380V** [comment]
This makes obvious  #else branch after [commit 9759da82e4b3](https://github.com/FreeCAD/FreeCAD/commit/9759da82e4b330c40883a2b4681fa6f1a65c497a) was not tested at all. Additionally:
`src/Gui/PythonWrapper.cpp:603:66: warning: implicitly-declared ‘Py::Long& Py::Long::operator=(const Py::Long&)’ is deprecated [-Wdeprecated-copy]
  603 |             ret = Py::Long(pyobject.getAttr(std::string("value")));
`
Also, whole concept seems [a bit screwed](https://github.com/FreeCAD/FreeCAD/commit/9759da82e4b330c40883a2b4681fa6f1a65c497a#diff-2a76849341710e006cb74ca6793e94f069b6caff8e58786a6db6c7dfee954300). I would expect wrapper template here.

@chennes, what about just reverting broken commit and waiting for better fix? (QT6 builds are broken anyway elsewhere, so no rush. I'll eventually fix that after returning home tomorrow (wtitten in hope someone else would be faster ;-)))

**Comment by chennes** [comment]
@yorikvanhavre since you merged #13611, what are your feelings on reverting it?

**Comment by yorikvanhavre** [comment]
I have no strong opinion... I merged it basically because everybody agreed during M3. But yes, if there are concerns I think it's sensible to revert and fix.

**Comment by adrianinsaval** [comment]
Agree on reverting

**Comment by chennes** [comment]
Closing in favor of reversion.

**Comment by wwmayer** [comment]
May I ask what exactly is the problem of  #13611 besides the build failure and the warning?

**Pull request closed without merging**
