### PR TITLE
Fix #2561 - crash while moving features

### PR DESCRIPTION
**Pull request by usakhelo**
Hi,
this PR fixes the bug and also fixes moving sketches, profiles and other dependencies of the selected features.
It also adds a simple test which creates two bodies, adds Sketch and Pad to one body and then moves Pad to second body.

PR topic link on forum - http://forum.freecadweb.org/viewtopic.php?f=17&t=16939

### CODE REVIEW

**Comment by usakhelo** [comment]
Hi,
Updates include checks if features are movable according to ickby's comment. Datum objects and Sketches get their new origins when moved. Info dialog box is also added to inform the user that feature can not be moved. Test case added with the attempt to move non-movable feature.

**Comment by ickby** [comment]
Thanks for the continuis updates on that code. I have found a few additional issues. I know this is much more than the original bug report, mostly because that tool was broken very much, but I hope making this working correctly is OK for you!

- relinkToOrigin: This currently handles sketches, but it also receives CoordinateSystems which could be linked to origins. They need to be handled too. Maybe make it work with Attachables instead of sketches? Also all features which can use reference axes/planes like revolution and groove must be handled here.
- From the list to choose the body to move to remove the source body
- In an empty Body creating a default Primitive Box: it cannot be moved to annother body but should be possible, as the CS can be moved too
- Moving a Pad and then using "undo" moves the pad outside of any body

**Comment by usakhelo** [comment]
Hi,
It's not just OK, it's perfect. I wish I can do more and faster.

 - relinkToObjects is fixed, it supports attachableobject-s and ProfileBased-s with ReferenceAxis property.
 - source bodies are removed from list
 - moving "default" box is fixed but I have a question on that: "default" box was not movable because by default (when you hit enter without picking anything in coordinatesystem parameters) it didn't have anything in Support. I fixed moving such primitives by ignoring empty Support property, but is it ok to have such objects?
 - Undo puts object outside the body and makes Recompute button active, so after I press Recompute objects go into their bodies. I'm not sure if something should be fixed in Undo system or in PartDesign or if it's totally ok.

**Comment by ickby** [comment]
Hello,
I think the non-attached CS for primitive is ok, as long as a valid placement is achieved, which is the case. For the undo, there i'm not sure whos responsibility the recompute is. Most likely it should be part of the transaction system . So I think this could stay at is in your code. 

All in all I think this code can be merged now, I will leave a little note on the forum.

**Comment by usakhelo** [comment]
I could added couple of tests and do rebase, but later during the day.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
