### PR TITLE
[Part Design] allow for preselecting loft sections and pipe spines pr…

### PR DESCRIPTION
**Pull request by mwganson**
…ior to invoking command

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by mwganson** [comment]
https://forum.freecadweb.org/viewtopic.php?f=17&t=49082

**Comment by mwganson** [comment]
I've discovered a bug after additional testing.  Preview during the dialog isn't working as expected for subtractive pipes and after completion the previous tip is still visible.

**Comment by mwganson** [comment]
I think I have all the bugs fixed now.

**Comment by mwganson** [comment]
I tried looking through the travis build failure, but I don't see why it failed or even that it failed, much less how to fix.

**Comment by Jee-Bee** [comment]
good to see that there is some work regarding selection methods in PD!!

**Comment by donovaly** [comment]
Can you please merge master to this PR because I get a merge conflict?

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
