### PR TITLE
src/App/Application: Improve FC CLI help output

### PR DESCRIPTION
**Pull request by luzpaz**
Help the user find more details info by directing them to the exact wiki page needed instead of the front page of the official site.

### CODE REVIEW

**Comment by luzpaz** [comment]
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=22&t=39053&p=331552#p331552

**Comment by luzpaz** [comment]
Devs, I've prepended the PR with [WIP] because the wiki page may need a re-write https://forum.freecadweb.org/viewtopic.php?f=21&t=39066 
So please do not merge. Thanks.

**Comment by luzpaz** [comment]
Wiki page rewrite may take longer than thought. Please merge this PR as is for now. The details of this topic will get more fleshed out in the forum before a legit PR will be made.

**Comment by luzpaz** [comment]
@berndhahnebach care to merge this ?

**Comment by luzpaz** [comment]
CI was complaining about an unrelated error:  
```
src/Mod/PartDesign/Gui/CMakeFiles/PartDesignGui.dir/build.make:568: recipe for target 'src/Mod/PartDesign/Gui/CMakeFiles/PartDesignGui.dir/TaskFilletParameters.cpp.o' failed
make[2]: *** [src/Mod/PartDesign/Gui/CMakeFiles/PartDesignGui.dir/TaskFilletParameters.cpp.o] Terminated
CMakeFiles/Makefile2:2377: recipe for target 'src/Mod/PartDesign/Gui/CMakeFiles/PartDesignGui.dir/all' failed
make[1]: *** [src/Mod/PartDesign/Gui/CMakeFiles/PartDesignGui.dir/all] Terminated
Makefile:129: recipe for target 'all' failed
make: *** [all] Terminated
/home/travis/.travis/functions: line 128: /usr/local/bin/FreeCAD: No such file or directory
/home/travis/.travis/functions: line 129: /usr/local/bin/FreeCAD: No such file or directory
cat: /tmp/FreeCAD_installed.log: No such file or directory
grep: /tmp/FreeCAD_installed.log: No such file or directory
Error from .log_errors found!
```

Rebased nonetheless

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
