### PR TITLE
[GUI] Add Improved 3Dconnexion Logo to src/Gui/Icons

### PR DESCRIPTION
**Pull request by KimK**
The original icon (3dx_pivot.png) is 12x13, fuzzy, and one color. Maybe this improved SVG will help in the future.
Traced from their logo, which is included in the Inkscape file. Done in their official colors, by color picker.

### CODE REVIEW

**Comment by oursland** [comment]
@pskowronskiTDx Does 3Dconnexion have an official style/branding guide, and if so is this consistent with the guide?

**Comment by pskowronskiTDx** [comment]
@KimK Thank you for the suggestion. Unfortunately, design of the proposed icon is outdated and cannot be used anymore.

**Comment by oursland** [comment]
@pskowronskiTDx Does 3Dconnexion have a larger icon, preferably in SVG format, that could be used in the future?

**Comment by pskowronskiTDx** [comment]
@oursland Not at the moment.

**Comment by maxwxyz** [comment]
@KimK @@pskowronskiTDx  is this PR still relevant? What is left to do?

**Comment by pskowronskiTDx** [comment]
@maxwxyz This can be dropped for now.

**Pull request closed without merging**
