### PR TITLE
[Plot] Remove the workbench, leave the module

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

Following the plan discussed in https://github.com/FreeCAD/FreeCAD/pull/4890#issuecomment-868694008, I am removing the plot workbench shipped within the core (which was utterly broken and disabled), letting just the module (`from FreeCAD.Plot import Plot`)

The module is quite simple, requiring very little maintenance. Besides matplotlib is automatically providing handful tools to make some basic operations with the plot (Zoom, Save, ...). For more complex operations we still offer the Plot addon (https://github.com/FreeCAD/freecad.plot)

3 tests failed, but again they seem to be unrelated with this PR:

```
======================================================================
FAIL: test_ccx_cantilever_prescribeddisplacement (femtest.app.test_solver_calculix.TestSolverCalculix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_solver_calculix.py", line 208, in test_ccx_cantilever_prescribeddisplacement
    self.input_file_writing_test(get_namefromdef("test_"))
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_solver_calculix.py", line 397, in input_file_writing_test
    self.assertFalse(
AssertionError: 'Comparing /home/pepe/freecad/build/Mod/Fem/femtest/data/calculix/ccx_cantilever_prescribeddisplacement.inp to /tmp/FEM_unittests/solver_calculix_ccx_cantilever_prescribeddisplacement_53f0156aa1ca/Mesh.inp failed!\n--- \n+++ \n@@ -410 +410 @@\n-** reaction forces for Constraint displacement constraining translation\n+** reaction forces for Constraint displacement constraining translations\n' is not false : CalculiX write_inp_file for ccx_cantilever_prescribeddisplacement test failed.
Comparing /home/pepe/freecad/build/Mod/Fem/femtest/data/calculix/ccx_cantilever_prescribeddisplacement.inp to /tmp/FEM_unittests/solver_calculix_ccx_cantilever_prescribeddisplacement_53f0156aa1ca/Mesh.inp failed!
--- 
+++ 
@@ -410 +410 @@
-** reaction forces for Constraint displacement constraining translation
+** reaction forces for Constraint displacement constraining translations


======================================================================
FAIL: test_constraint_transform_beam_hinged (femtest.app.test_solver_calculix.TestSolverCalculix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_solver_calculix.py", line 270, in test_constraint_transform_beam_hinged
    self.input_file_writing_test(get_namefromdef("test_"))
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_solver_calculix.py", line 397, in input_file_writing_test
    self.assertFalse(
AssertionError: 'Comparing /home/pepe/freecad/build/Mod/Fem/femtest/data/calculix/constraint_transform_beam_hinged.inp to /tmp/FEM_unittests/solver_calculix_constraint_transform_beam_hinged_2f74d94be950/Mesh.inp failed!\n--- \n+++ \n@@ -3782,0 +3783,5 @@\n+** outputs --> dat file\n+** reaction forces for Constraint displacement constraining translations\n+*NODE PRINT, NSET=FemConstraintDisplacment, TOTALS=ONLY\n+RF\n+\n' is not false : CalculiX write_inp_file for constraint_transform_beam_hinged test failed.
Comparing /home/pepe/freecad/build/Mod/Fem/femtest/data/calculix/constraint_transform_beam_hinged.inp to /tmp/FEM_unittests/solver_calculix_constraint_transform_beam_hinged_2f74d94be950/Mesh.inp failed!
--- 
+++ 
@@ -3782,0 +3783,5 @@
+** outputs --> dat file
+** reaction forces for Constraint displacement constraining translations
+*NODE PRINT, NSET=FemConstraintDisplacment, TOTALS=ONLY
+RF
+


======================================================================
FAIL: test_frequency_beamsimple (femtest.app.test_solver_calculix.TestSolverCalculix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_solver_calculix.py", line 286, in test_frequency_beamsimple
    self.input_file_writing_test(get_namefromdef("test_"))
  File "/home/pepe/freecad/build/Mod/Fem/femtest/app/test_solver_calculix.py", line 397, in input_file_writing_test
    self.assertFalse(
AssertionError: 'Comparing /home/pepe/freecad/build/Mod/Fem/femtest/data/calculix/frequency_beamsimple.inp to /tmp/FEM_unittests/solver_calculix_frequency_beamsimple_e703765b20a3/Mesh.inp failed!\n--- \n+++ \n@@ -17066 +17066 @@\n-** reaction forces for Constraint displacement constraining translation\n+** reaction forces for Constraint displacement constraining translations\n' is not false : CalculiX write_inp_file for frequency_beamsimple test failed.
Comparing /home/pepe/freecad/build/Mod/Fem/femtest/data/calculix/frequency_beamsimple.inp to /tmp/FEM_unittests/solver_calculix_frequency_beamsimple_e703765b20a3/Mesh.inp failed!
--- 
+++ 
@@ -17066 +17066 @@
-** reaction forces for Constraint displacement constraining translation
+** reaction forces for Constraint displacement constraining translations


----------------------------------------------------------------------
```

### CODE REVIEW

**Review by chennes — APPROVED** [review]
This compiles, runs, and the unit tests pass (except the three FEM tests that have been failing for a while). Tested on Windows 10:

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.25505 +3 (Git)
Build type: Release
Branch: pr/4971
Hash: b2910f19138551e1ef40af41e6fc52ce0b586443
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by yorikvanhavre** [comment]
Will that strategy not be confusing? There is now a minimal Plot module still in the FreeCAD core source code, and a more complete one available as an addon... Maybe users will be confused? How will they know they need to install the addon?
Wouldn't be better to either rename the "old" Plot or, for example, since it is only one file, why not integrate it to the ShaftWizard? So it becomes independent of Plot?

**Comment by sanguinariojoe** [comment]
> Will that strategy not be confusing? There is now a minimal Plot module still in the FreeCAD core source code, and a more complete one available as an addon... Maybe users will be confused? How will they know they need to install the addon?

They don't need to install the addon, that's the whole point. Herein we only have the module, i.e. the core component which allows every other module/workbench make plots, which already have the minimum matplotlib tools (see https://user-images.githubusercontent.com/1828501/123444869-a81ba100-d5d7-11eb-9bf3-8169108bf484.png).

The external addon is just providing a workbench to play with the plot styling. It is also offering a little bit more complete saving tool. For backward compatibility the addon is still deploying the Plot module, but it will be removed in the future (see https://github.com/FreeCAD/freecad.plot/pull/16)

> Wouldn't be better to either rename the "old" Plot or, for example, since it is only one file, why not integrate it to the ShaftWizard? So it becomes independent of Plot?

I consider this acceptable. However, I still prefer importing Plot with

`from FreeCAD.Plot import Plot`

rather than

`from FreeCAD.PartDesign.WizardShaft import Plot`

It is up to you guys

**Comment by luzpaz** [comment]
Do the CFDoF folks know about this proposed change?  
CC @oliveroxtoby

**Comment by oliveroxtoby** [comment]
> Do the CFDoF folks know about this proposed change?
> CC @oliveroxtoby

Thanks for the heads up! Good to know.

> They don't need to install the addon, that's the whole point. Herein we only have the module, i.e. the core component which allows every other module/workbench make plots, which already have the minimum matplotlib tools (see https://user-images.githubusercontent.com/1828501/123444869-a81ba100-d5d7-11eb-9bf3-8169108bf484.png).

This would be great from the CfdOF point of view :)

**Comment by oliveroxtoby** [comment]
I was testing this with CfdOF and just had one issue - it was a recurrence of a previous issue I had on my system that was fixed in the plot workbench. I have submitted a pull request on top of this branch to apply the same fix here (https://github.com/sanguinariojoe/FreeCAD/pull/1). Other than that it is working great for me.
image

**Comment by sanguinariojoe** [comment]
Merged!

**Comment by yorikvanhavre** [comment]
Okay then, indeed normal users will simply not see anything about Plot and install the WB if needed. But developers might still be confused. But OK, let's merge this and see how it goes. But let's keep an eye for confusion in people's minds, and think of a strategy if needed

**Pull request merged**
