### PR TITLE
AddonManager: Add gmsh-dev to ALLOWED_PYTHON_PACKAGES

### PR DESCRIPTION
**Pull request by luzpaz**
Fixes https://github.com/KeithSloan/GDML/issues/92

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
---

### CODE REVIEW

**Comment by luzpaz** [comment]
@chennes Just realized I'mnot sure if this conflicts with a preinstalled `gmsh` package.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6723">pipeline status</a> for feature branch [PR_6723](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6723). Pipeline [511645797](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/511645797) was triggered at [bd5d66b](https://github.com/FreeCAD/FreeCAD/pull/6723/commits/bd5d66b1dd8fc3bb6cdc16c392ddca3487636234). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by KeithSloan** [comment]
Info in this link https://gitlab.onelab.info/gmsh/gmsh/-/tree/quadqs/utils/pypi/gmsh-dev would indicate that gmsh should be uninstalled if gmsh-dev is being installed.

**Comment by luzpaz** [comment]
@KeithSloan then we need to specify a `<replace>` tag in the GDML `package.xml` file that replaces a previously installed `gmsh` with `gmsh-dev`. See https://wiki.freecadweb.org/Package_Metadata#.3Creplace.3E

**Comment by KeithSloan** [comment]
Don't understand the documentation [https://wiki.freecadweb.org/Package_Metadata#.3Creplace.3E](url)

So it should contain ? 
````
<depend  gmsh-dev>
<replace gmsh>
````
Thought dependencies where in metadata.txt

Signed confussed.com

**Comment by KeithSloan** [comment]
<replace>Metadata Creation Workbench Beta</replace>
      
 But how does the user know where the python package is installed?
 
 Thought FreeCAD installed in non standard python paths i.e on install python3 pip -m install -t<path>
 So how does one determine which path to use for the uninstall?
 
 Which begs the question why is there not one standard path for FreeCAD python libraries rather than having to do
 import sys
 print(sys.path)
 
 And it could be any one of the listed path.
 
 In the west country they have an expression for this sort of thing.

**Comment by adrianinsaval** [comment]
we're talking a pip package here I assume? would it conflict with gmsh from a package manager?

**Comment by chennes** [comment]
There is no mechanism in the Addon Manager to ask it to uninstall a previously-installed package (that's not what the `<replaces>` tag does), and I of course won't add such a thing, since it would make it much easier for installing one Addon to break the installation of another. If gmesh-dev is needed you can specify it, but if it conflicts pip is going to throw an error, just like in the case of any other conflict, and it's going to be up to the user to resolve that issue. I don't believe we have the resources (or desire) to write a full-blown GUI frontend to pip from within FreeCAD.

**Comment by KeithSloan** [comment]
````
<!--` If this package is installed, the Addon Manager may warn the user to remove it -->
      <replace>Metadata Creation Workbench Beta</replace>
````
Well if Addon Manager is going to issue a warning message it could at least try and be helpful by
````
import <package>
and obtaining the installation path with
package.__path___

and including that information in the message.

Still of the opinion that life could be made a lot simpler if FreeCAD installed required python libraries to one directory and maybe a second directory for those required for workbenches

**Comment by chennes** [comment]
I'm sorry for the confusion -- that's just not what `<replace>` is for. It's designed for an Addon to indicate that it's the replacement for an earlier Addon: e.g. "Dodo" replaces "Flamingo". So if the user has Flamingo installed, and they try to install Dodo, eventually the AM will warn that they should remove Flamingo, since it's superseded by Dodo. It doesn't have anything to do with Python dependencies at all.

The Addon Manager does install required Python dependencies for workbenches to one directory, so I'm not sure what your suggestion is in that regard.

**Comment by donovaly** [comment]
@chennes, what do we do with this PR, for 0.20 or for 0.21?

**Comment by chennes** [comment]
Since it is very minor and can't really break anything, I think it is OK to merge, if it's OK with you.

**Comment by donovaly** [comment]
Fine, please merge it.

**Pull request merged**
