### PR TITLE
Draft: DraftEdit.py now gets PickRadius from user preferences

### PR DESCRIPTION
**Pull request by luzpaz**
...instead of being hardcoded.  
Note: PickRadius is the proximity in pixels for picking elements in the 3D view  

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=10&t=39203

### CODE REVIEW

**Comment by luzpaz** [comment]
Not sure why Travis is complaining. Not sure if it has to do with my code at all.

**Comment by carlopav** [comment]
Thanks for the fix! really appreciated. Maybe in the future we could evaluate the idea of having a larger pick radius for editing compared to the one that is used for selection and store it in a different user setting in draft preferences.

**Comment by luzpaz** [comment]
@carlopav makes sense to me. Why don't you start a conversation about it? Also, speaking of convenience, have you seen the thread: "[is there a way to magnify a point or node when the crosshair is in it's vicinity?](https://forum.freecadweb.org/viewtopic.php?p=333531)".

**Comment by carlopav** [comment]
@luzpaz yes, I saw the thread, but i think the edit tracker is already in its bigger available size since it's based on coin class SoMarkerSet SQUARE_FILLED_9_9.
Ok for the thread, i'll use the old draft edit improvements topic.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
