### PR TITLE
Remove unused mod complete

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8881">pipeline status</a> for feature branch [PR_8881](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8881). Pipeline [805447469](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/805447469) was triggered at [be2b816](https://github.com/FreeCAD/FreeCAD/pull/8881/commits/be2b816cad6e75882ef4a5fa4d8d0abcbd274a4d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
Hmm. What will happen if a user used this workbench to create its own custom workbench by setting custom toolbars and commands?

**Comment by wwmayer** [comment]
Inside the InitGui.py module the line to add the workbench is commented out. So, even if the module is installed you won't see an entry in the workbench selector.

Since the Complete workbench has lost any functionality I don't see a reason to still keep it around.  But in order to fully remove the module this PR is not yet complete:
* in Mod/CMakeLists.txt this block must be removed:
```
if(BUILD_COMPLETE)
  add_subdirectory(Complete)
endif(BUILD_COMPLETE)
```
* in cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake this line must be removed:
`option(BUILD_COMPLETE "Build the FreeCAD complete module" OFF)`

**Comment by wwmayer** [comment]
Replaced with https://github.com/FreeCAD/FreeCAD/pull/9085

**Pull request closed without merging**
