### PR TITLE
[Icons]Revision of TechDraw Icons(symbol)

### PR DESCRIPTION
**Pull request by Reqrefusion**
#14145

### CODE REVIEW

**Review by kadet1090 — CHANGES_REQUESTED** [review]
image

Please ensure that all lines are at least as thick as the annotation arrow in weld symbol. in other cases it is not readable.

**Review by kadet1090 — APPROVED** [review]
image

Fine enogugh I think?

**Comment by Reqrefusion** [comment]
> image
> 
> Fine enogugh I think?

As you make it thicker, it becomes harder to control the area it covers. I barely got enough thickness for the letter "a". Letters are really challenging.

**Comment by Reqrefusion** [comment]
@chennes It can be merged. It needs to be merged today.

**Pull request merged**
