### PR TITLE
[Path] Adaptive: Correct the processing of selected edges

### PR DESCRIPTION
**Pull request by Russ4262**
The recent Extensions upgrade for Adaptive disabled the processing of selected edges.  This commit re-enables that capability.  Issue raised in forum at,  [Adaptive clearing on multiple faces (re-opened / freecad git bug)](https://forum.freecadweb.org/viewtopic.php?f=15&t=60037).

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Review by sundtek — COMMENTED** [review]
Confirmed, generating adaptive paths by selecting wires works again. Thanks!

**Review by sundtek — APPROVED** [review]
That fixes the issue mentioned in the post by better use of the freecad api:
https://forum.freecadweb.org/viewtopic.php?f=15&t=59289&start=20#p516783

tested and confirmed that this change is okay.

**Comment by Russ4262** [comment]
Added a commit containing some basic unit tests all focused on selection capability of the Adaptive op.  PR #4388 that added Extensions to Adaptive introduced a regression related to edge usage.  Edges are still selectable, but they are not processed. This is the regression.  This PR re-introduces edge processing, but not in the full manner as before the regression - this PR does not properly relate inner edge loops to their outer parent edge loops.  I believe @sundtek has been working on a more capable solution.

**Comment by sundtek** [comment]
Hi,

once your part is merged I'll submit my patches on top of that. My follow up patches are rather large and should have some discussion since it adds more support for edge based selections (based on that I'll do some more investigation in the near future how to speed it up).

Markus / MRx

**Pull request merged**
