### PR TITLE
[PD] fixes for padding along edge

### PR DESCRIPTION
**Pull request by donovaly**
- handle custom direction like all other directions
- allow to view the direction vector for all directions, but only to edit for custom
- fix enabling of the length alongNormal option
- also fix a translation issue

### CODE REVIEW

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5071

pipeline for commit f2b9170079c491:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/378348544

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by chennes** [comment]
@donovaly Do you want to address @wwmayer's comments on your last commits from PR #4685 in this PR, or are you addressing those separately?

**Comment by donovaly** [comment]
> 
> 
> @donovaly Do you want to address @wwmayer's comments on your last commits from PR #4685 in this PR, or are you addressing those separately?

Werner was faster and already fixed this in master. This PR here should merge seamlessly I think since it does not touch the code Werner touched. It not I will have a look later.

**Comment by freecadci** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5071

pipeline for commit fb49450c626f82:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/379195940

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by chennes** [comment]
This looks good to me -- I think there's maybe some room for improvement in the logic about whether to show or hide the direction which switching between the various options, but let's let users get their hands on it for a while and see what people think.

**Pull request merged**
