### PR TITLE
Path: showed stock size

### PR DESCRIPTION
**Pull request by torsw**
When a path stock is "extend model's bound box" the stock size is showed.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7533">pipeline status</a> for feature branch [PR_7533](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7533). Pipeline [651961358](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/651961358) was triggered at [5ce1696](https://github.com/FreeCAD/FreeCAD/pull/7533/commits/5ce169619d213f8abd415d534aa8c2d65c056be5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Syres916** [comment]
Line 176 spelling of `length` especially as it's to be translated

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7533">pipeline status</a> for feature branch [PR_7533](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7533). Pipeline [652251826](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/652251826) was triggered at [28b0ba4](https://github.com/FreeCAD/FreeCAD/pull/7533/commits/28b0ba499138253780c9e4e6d4223fd680d968e1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7533">pipeline status</a> for feature branch [PR_7533](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7533). Pipeline [652253898](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/652253898) was triggered at [04fb739](https://github.com/FreeCAD/FreeCAD/pull/7533/commits/04fb739bfbad07ba2c5d327e28e2e28a0f9e0bc3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7533">pipeline status</a> for feature branch [PR_7533](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7533). Pipeline [653923512](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/653923512) was triggered at [0e9bcbb](https://github.com/FreeCAD/FreeCAD/pull/7533/commits/0e9bcbb05e18b1c15a6f423ddc22101a87efeaef). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
A couple of problems.  This solution adds properties to the stock object.  However, it doesn't add them to existing stock objects when the document is restored.  So if any future functionality actually relies on reading those properties, it will fail for jobs created before this was implemented.  

I assume the intent is to easily get to the stock size so the machine operator can rough-cut material to load in the machine.  The existing functionality of PathSanity provides this information for exactly this reason but doesn't require us to add properties.  Can you please comment on the use-case you have in mind that isn't met already?  In other words, what is the 'problem' being solved by this change?

**Comment by torsw** [comment]
Sometimes i create small and simple models, like toys for my children. After creating the part and the cnc paths, usually for me the most interested information are the cycle time (already present) and the size of rough stock to mounting in the machine. For the "extended model's bound box" are only available the extensions but not the real size. I used the "measure distance" on the stock but it is not easy and fast. It seems useful to know these dimensions immediately. That is all. Thanks.

**Comment by sliptonic** [comment]
Since the functionality is available already via the PathSanity command without the need for the added properties,  I'm declining the PR.  Please resubmit if there's a use-case that I missed.

**Pull request closed without merging**
