### PR TITLE
Modified FEM tie constraint icon

### LINKED ISSUE #13113: FEM Contact and tie constraint icons are too similar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The icons used for tie and contact constraints are too similar - the only difference is the highlight color.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
fixes #13113

the modified icon highlights the key difference between contact and tie constraint - the latter doesn't allow for separation and creates a fully bonded/glued connection

@marioalexis84 FYI

### CODE REVIEW

**Comment by maxwxyz** [comment]
@FEA-eng if you need other icons overhauled let me know, I've redone Sketcher and SheetMetal recently.

**Comment by FEA-eng** [comment]
> @FEA-eng if you need other icons overhauled let me know, I've redone Sketcher and SheetMetal recently.

Thanks, I would probably leave most of them as they are but some may require improvements for clarity. I would appreciate your help because I know what they should represent but my artistic skills are even worse than programming ones ;-)

P.S. Some time ago I was trying to improve the "Fit all" icon but couldn’t find good enough design: https://forum.freecad.org/viewtopic.php?t=83097

**Comment by maxwxyz** [comment]
@FEA-eng I've seen that post. So just let me know which icons need improvement and what they should represent better.

**Comment by maxwxyz** [comment]
@FEA-eng I have this in my PR as well #13130

**Comment by FEA-eng** [comment]
Closed in favor of https://github.com/FreeCAD/FreeCAD/pull/13130

**Pull request closed without merging**
