### PR TITLE
Spreadsheet: Move spreadsheet python functions from ViewProvider to SheetView

### PR DESCRIPTION
**Pull request by chennes**
Now that we have access to Spreadsheet's SheeetView object from the Python, move the functions from ViewProvider to SheetView (where they are a better fit). Also clean up the old, unneeded Python wrapper code for the SheetView.

### CODE REVIEW

**Comment by chennes** [comment]
@wwmayer could you please take a look at this when you have a chance, to make sure I have understood our discussion correctly, and haven't screwed up the PyCXX implementation?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5175">pipeline status</a> for feature branch [PR_5175](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5175). Pipeline [409255322](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/409255322) was triggered at [3dd16c4](https://github.com/FreeCAD/FreeCAD/pull/5175/commits/3dd16c442dc3b89112f172cee860bcf94ef6c72b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5175">pipeline status</a> for feature branch [PR_5175](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5175). Pipeline [411472370](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/411472370) was triggered at [948b725](https://github.com/FreeCAD/FreeCAD/pull/5175/commits/948b72528d7a6feef7b6841144db7c447095b3f5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
The code is fine. Only one tiny thing: functions that return nothing should use Py::None() instead of Py::Object().

I have merged the PR:
d60a0fb760a692
79a0c6b54c572b

**Pull request closed without merging**
