### PR TITLE
Path: fix compiler warnings

### PR DESCRIPTION
**Pull request by wwmayer**
* fix -Wunused-parameter
* fix -Wunused-but-set-variable

### CODE REVIEW

**Comment by 0penBrain** [comment]
I tried to re-run CI (once only failed test, once completely) but this PR seems to very reliably trigger the segfault that shew quite a lot since 4435a3974f64dd52829c0c24d1be0f14405d5218 :confused:

**Comment by wwmayer** [comment]
I guess the crash came rather from this PR: https://github.com/FreeCAD/FreeCAD/pull/9446

**Comment by wwmayer** [comment]
Rebased and force pushed.

**Comment by 0penBrain** [comment]
> I guess the crash came rather from this PR: #9446

It has been reverted here with ffd66cf
So with rebate should go well. We'll see

**Comment by wwmayer** [comment]
> It has been reverted here with

Sure, but when you only trigger a rebuild without rebasing the branch is it then supposed to work?

Now there is no segfault any more but one of the tests fails: TimeInfo.TestDiffTime

**Comment by 0penBrain** [comment]
> Sure, but when you only trigger a rebuild without rebasing the branch is it then supposed to work?

It may if the problem is randomly appearing. But sure it compiles the exact same tree.

> Now there is no segfault any more but one of the tests fails: TimeInfo.TestDiffTime

Maybe another unlucky merge. Didn't look at it yet.

> But nevertheless, this PR only fixes some compiler warnings and doesn't break anything.

Exactly. Why it was interesting to use it to analyze an eventual random bug. ;)

**Comment by 0penBrain** [comment]
> Now there is no segfault any more but one of the tests fails: TimeInfo.TestDiffTime

Well, it's gone after re-running the CI. Hopefully it was just a glitch.

**Pull request merged**
