### PR TITLE
Assembly: JCS selection: cones surfaces offers the cone's apex.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Cone offers the apex for JCS selection : Fixes https://github.com/FreeCAD/FreeCAD/issues/13958
image

### CODE REVIEW

**Comment by pierreporte** [comment]
Will you implement the distance parameter for this?

**Comment by PaddleStroke** [comment]
I'm not sure because the distance you want is a very special case. I see no way to add it cleanly.
It would be when making a distance joint between 2 cones sharing the same angle? Then it would effectively acts as a revolute joint with an offset = distance * sin(angle)

**Comment by pierreporte** [comment]
I was referring to the situation where the two angles are identical, so only the simplest case.

**Comment by maxwxyz** [comment]
How will it snap the JCS to this place where nothing is? Or is it still possible to select the surface for other joints?

**Comment by PaddleStroke** [comment]
The apex point is aligned with the center of mass (which was the selected position initially).
But the center of mass has no usecase. I used it because it was more or less in the center of the shape.
So switching to the apex point, I don't think we loose anything.

**Pull request merged**
