### PR TITLE
Spreadsheet fixes 20161213

### PR DESCRIPTION
**Pull request by eivindkv**
This pull request fixes issue #2766, #2647, and #2646. Is also fixes some Coverity issues.

### CODE REVIEW

**Comment by eivindkv** [comment]
Fixed commit message and rebased on current master.

**Comment by wwmayer** [comment]
Merged.

**Comment by wwmayer** [comment]
In the summary you wrote that this fixes issue 2766. Unfortunately, this isn't the case.

**Comment by eivindkv** [comment]
I rebased it and fixed the commit message just an hour ago...

**Comment by sasobadovinac** [comment]
I have marked 128977 in Coverity as Action:	Fix Submitted... And congratulations it looks like there are no more issues in Coverity under /Mod/Spreadsheet 👍

**Pull request closed without merging**
