### PR TITLE
Introduce object freeze

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix  **#5545  Switch on and off parametric behaviour of document objects**

### CODE REVIEW

**Comment by chennes** [comment]
@obelisk79 can the DWG take a look at this?

**Comment by obelisk79** [comment]
I am somewhat confused what the purpose of this PR/Feature is. 

Is the intent to 'freeze' an object to save resources on recomputes?
Is it related, or necessary to implement a proper 'suppress feature' functionality?

The referenced issue was closed as 'not planned'. The original mantis ticket referenced some forum posts where the issue wasn't 100% clear to me.

**Comment by yorikvanhavre** [comment]
I like this feature. Many objects (TechDraw views, Draft Shape2DViews...) have introduced their own "turn off recomputing" system over time. This is an excellent FreeCAD-wide system IMHO.

@obelisk79 indeed some features, such as those I mentioned here, often depend on a lot more objects (half of your model usually...) and they are slow to recompute. So it turns your workflow VERY slow, like, each time you move something there is a big recompute, and it's a common thing to "turn them off" while you're not using them actively.

With a FreeCAD-wide system I can imagine much better tools and workflows to for ex automatically freeze/unfreeze series of objects, add this to Draft layers, etc...

**Comment by wwmayer** [comment]
The question is whether there is a need to only temporarily switch off the parametric behaviour of an object. If the removal of the parametric behaviour is permanent then a simple copy will do it but if it should be enabled again then a simple copy is not sufficient.

About the recently added suppress feature function I don't know what the exact difference should be. At least compared to the suppress feature function the method of this PR has no extra memory costs.

**Comment by yorikvanhavre** [comment]
Merging it as we feel the questions are responded and we're happy with the feature.

**Comment by FEA-eng** [comment]
@FlachyJoe Is it normal that I can find the Toggle freeze option in the context menu only when I'm in the Part workbench, not in Part Design ? Interestingly, it can be applied from Part to PD features.

**Comment by maxwxyz** [comment]
@FlachyJoe to add to @FEA-eng comment I've added more problems to this issue: https://github.com/FreeCAD/FreeCAD/issues/12829

**Comment by maxwxyz** [comment]
@FlachyJoe @yorikvanhavre not sure if this as merged functions as intended. 
Objects can be manipulated although they are frozen and if they unfreeze the change is done irreversible. So it actually does change the object but the user does not get info about the change. As I understood, its intended to freeze the current state of an object and allow no modifications.

If the intention is just temporarily disable recompute but do whatever you want with the object than it should be renamed but than it does not resolve the issue from the linked forum discussion as I understand.

https://github.com/FreeCAD/FreeCAD/issues/12829

**Pull request merged**
