### PR TITLE
[WIP]update macos build doc to include using homebrew to build freecad fro…

### PR DESCRIPTION
**Pull request by ipatch**
…m source

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

i checked ✅ the four above boxes due to the nature of this commit. this commit only updates the macos build instructions contained within the `BUILD_OSX.md` doc

### CODE REVIEW

**Comment by hyarion** [comment]
As a macOS and FreeCAD user, I like that the mac side of the project gets some love, but I think this PR can be improved.

**Wall of text**
The document is _really_ verbose. Some times it's good to explain information in great detail, but in technical documents I tend to like when information is as short and concise as possible as this makes them easier and faster to read.

Most of the new additions could be reduced in length and I think it could be reduced to the point that there is no need for a TOC.

**Writing style**
The additions feels more like a blog/forum post than a readme for how to build the project. It gives a lot of insight in how you built it and your thought process behind those choices and it would be a great complement to have posted somewhere.

As an example:

> While going through the process of getting FreeCAD to compile on macOS using brew with a formula file and without a formula file I ran into several issues along the way, and I'll document them here in case anyone else is run into such error and may have a frame of reference why such error happens. All that said, I can not list every possible eror that could arrise, but hopefully these can help guide will troubleshooting a problematic build.

Who is the "I" in this text block? If another person wants to continue on this document, should this person also write "I"? Do we now have two first persons?

I think this text block could be replaced with the following:
`Some common pitfalls are listed in this section.`

**Use of emojis**
1. The warning emoji used in the text was a good way to draw attention, good job there 👍.
2. However, the use of ⚙️, 🍺 and ⌘ made the text harder to read. I think "Building using homebrew" would a better choice of wording.

**Some miss understandings**
1. It is stated that `cmake` must be run inside the src directory. This is not the case. The recommended way is to create a build directory a side of the cloned FreeCAD directory and run `cmake` with `../FreeCAD-git` as last argument (`FreeCAD-git` should be replaced with the name of the directory you cloned the repo into)
2. The build system does not require freecad to be placed in a lowercase directory, you do need to write it correctly when you run `cmake` though (I have it placed in `~/FreeCAD/FreeCAD-git` and it works for me on a non case sensitive APFS drive)
3. You don't need to run `git fetch --unshallow` if you clone it without `--depth [depth]` parameter. I think the reason behind this misunderstanding is that homebrew used to use shallow clones, but they have since stopped. More about this can be read here: https://github.com/Homebrew/brew/pull/8883 and here: https://github.com/Homebrew/brew/pull/9383 .

**Keeping it simple**
I understand that you've put down a lot of work in writing this so I feel a bit bad to suggest this, but...
I think I would actually prefer if there was just a new section added to the original document called "Building using homebrew" which had a line like this:

> FreeCAD can also be compiled using homebrew, for more information go to: https://wiki.freecadweb.org/Compile_on_MacOS

This way there wouldn't be multiple documents trying to solve the same thing.

The wiki-document mentioned above is a bit outdated though, as some instructions needs tweaks to work. For example, the lcu4c workaround to add a path to CMAKE_PREFIX_PATH env would be a great addition.

**Comment by ipatch** [comment]
@hyarion 

> It is stated that cmake must be run inside the src directory. This is not the case. The recommended way is to create a build directory a side of the cloned FreeCAD directory and run cmake with ../FreeCAD-git as last argument (FreeCAD-git should be replaced with the name of the directory you cloned the repo into)

That's how i've traditionally built apps that use cmake as it's build system, however the build would fail due to not being able to locate certain files as I discussed in this [forum post][lnk1] Maybe I'm doing something wrong, but that is only way FreeCAD would compile using homebrew infrastructure without a formula file.

> The build system does not require freecad to be placed in a lowercase directory, you do need to write it correctly when you run cmake though (I have it placed in ~/FreeCAD/FreeCAD-git and it works for me on a non case sensitive APFS drive)

I believe i didn't say it required to be in lowercase but recommend it due to compiler warnings, and how the include files are written in lowercase.

> You don't need to run git fetch --unshallow if you clone it without --depth [depth] parameter. I think the reason behind this misunderstanding is that homebrew used to use shallow clones, but they have since stopped. More about this can be read here: Homebrew/brew#8883 and here: Homebrew/brew#9383 .

that's fair, feel free (whomever) to make the document more terse.

> However, the use of ⚙️, 🍺 and ⌘ made the text harder to read. I think "Building using homebrew" would a better choice of wording.

and yes i am aware i can be a bit on the verbose side of things, so feel free to amend the PR to make things more terse, and if you find the use emojis distracting remove them. for me personally their not so distracting but rather work as a reference guide for quickly scanning through the document, and that reference point also works when i come back to the document and want to reread something IMHO.

Overall, PR is on the verbose side, and I probably made it that way because helping some people on the freecad forum to get the latest freecad working on macOS from the git source became a lengthy process of, `C` comes after `B`, and `B` comes after `A`. Not to say all mac users are unexperienced in compiling / building programs from source, but the additional verbosity (hand holding) seemed like it would be better than assuming too much and expecting the user to have prior experience.  So I definitely wrote this for the person who has little to know experience using cmake and is trying to build freecad from git source.

[lnk1]: <https://forum.freecadweb.org/viewtopic.php?f=4&t=53662#p461438>

**Comment by hyarion** [comment]
You do have some good points. I think the content is great and I'm sure it will help people, wherever it get posted. I'm just wondering if this is the best place for this type of in-depth compile guide.

As I'm not a maintainer I cannot make any additions/changes to other users pull requests, I can only comment and give suggestions. I can assist with the wiki though.

**Comment by luzpaz** [comment]
Question, why use html anchors? Doesn't markdown create implicit anchors from the headers? https://stackoverflow.com/a/25502416

**Comment by ipatch** [comment]
did not know that was a thing. i've always just used the `name` or `id` html attributes.

feel free to adjust the document to use the markdown equivalent.

**Comment by luzpaz** [comment]
What's the standing on this?

**Comment by chennes** [comment]
I agree with @hyarion's comments overall, but I hate to let "perfect be the enemy of good." I think this version of BUILD_OSX.md is a clear improvement on the old version, even if it still needs some work. If we merge it, then others can even do that work, instead of being limited to commenting on the PR. My vote is that we merge as-is and then continue to tweak.

**Comment by ipatch** [comment]
ohhh the parallels. 

https://youtu.be/l23_-1v__Fg?t=40

**Pull request merged**
