### PR TITLE
Path: refactor Utils imports in estlcam_post.py

### LINKED ISSUE #10396: [Path] estlcam post processor broken
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Path

### Problem description

Opening the preferences for the Path -> Job Preferences -> Post Processor and moving the mouse over the estlcam entry in the "Post Processor" list produces the following error:
```
Traceback (most recent call last):                                                                 
  File "/home/markus/projects/FreeCAD/mlampert/build/Mod/Path/Path/Main/Gui/PreferencesJob.py", line 346, in setProcessorListTooltip                                                                  
    self.setPostProcessorTooltip(self.form.postProcessorList, item.text(), "")                     
  File "/home/markus/projects/FreeCAD/mlampert/build/Mod/Path/Path/Main/Gui/PreferencesJob.py", line 339, in setPostProcessorTooltip                                                                  
    processor = self.getPostProcessor(name)                                                        
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        
  File "/home/markus/projects/FreeCAD/mlampert/build/Mod/Path/Path/Main/Gui/PreferencesJob.py", line 333, in getPostProcessor                                                                         
    processor = PostProcessor.load(name)                                                           
                ^^^^^^^^^^^^^^^^^^^^^^^^                                                           
  File "/home/markus/projects/FreeCAD/mlampert/build/Mod/Path/Path/Post/Processor.py", line 47, in load                                                                                               
    exec("import %s as current_post" % postname, namespace)                                        
  File "<string>", line 1, in <module>                                                             
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import                                                                                          
    return original_import(name, *args, **kwargs)                                                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                  
  File "/home/markus/projects/FreeCAD/mlampert/build/Mod/Path/Path/Post/scripts/estlcam_post.py", line 30, in <module>                                                                                
    import PathScripts.PostUtils as PostUtils                                                      
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import                                                                                          
    return original_import(name, *args, **kwargs)                                                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                  
ModuleNotFoundError: No module named 'PathScripts.PostUtils' 
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by haraldhartmann**
fix #10396

### CODE REVIEW

**Comment by luzpaz** [comment]
```bash
git commit --amend -m "Path: refactor Utils imports in estlcam_post.py" -m "Fixes #10396"
git push --force
```

**Review by LarryWoestman — COMMENTED** [review]
There are several lines that are longer than the current Path convention (88 characters) or the future overall convention (100 characters).  It would be nice if you could run the file through the "black" formatter to produce a more uniform result.  We normally do that with all of the Path code when we make changes.

Other than that the changes appear reasonable to me.

**Comment by haraldhartmann** [comment]
@luzpaz @sliptonic How can i backport this to the 0.21 branch? 0.21.2 is out, but this fix isn't there

**Comment by darthjoda** [comment]
> @luzpaz @sliptonic How can i backport this to the 0.21 branch? 0.21.2 is out, but this fix isn't there

I have a question, becouse i have exact this problem and the changes which will fix the problem are still not in the actual release, when it is planned?

**Comment by sliptonic** [comment]
Other than the minor reformatting to imports, this was a one-line fix.  The line is in the current master branch which means it is in the weekly builds.
https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/CAM/Path/Post/scripts/estlcam_post.py#L417

Are you sure you're using the system postprocessors and not an older version?

Postprocessors are entirely stand-alone pieces of code.  So you can always download the whole file and replace your current version.  You don't even have to restart FreeCAD because it will reimport the post.

**Comment by sliptonic** [comment]
> @sliptonic I think most users out there don't stick to weekly builds or replace some files, but instead use the last release build from the official FreeCAD download page ... and this is still 0.21.2

Agreed.  But that's the nature of open source. 
We're trying to keep the stable version of Ondsel closer to current.  You might want to try that.

**Pull request merged**
