### PR TITLE
Addon Welcome Screen Updated as per #17317

### PR DESCRIPTION
**Pull request by JamesHodgkins**
UI updates to Addon 'Welcome Screen' as per #17317

### CODE REVIEW

**Comment by 3x380V** [comment]
Could this change be properly formatted, so that pre-commit.ci does not kick in and also squashed and rebased? If I understand it correctly, this is just one logical change, so there should be single commit to merge.

**Comment by JamesHodgkins** [comment]
> Could this change be properly formatted, so that pre-commit.ci does not kick in and also squashed and rebased? If I understand it correctly, this is just one logical change, so there should be single commit to merge.

I'll take another look. I'm not sure why it's happened in all honesty

**Comment by 3x380V** [comment]
No need to close this, you could just fix it and force push.

**Comment by luzpaz** [comment]
Learning git is helpful in general this is a good way to start :+1:

**Review by JamesHodgkins — COMMENTED** [review]
Format changes as requested

**Comment by JamesHodgkins** [comment]
I don't understand, sorry

**Comment by chennes** [comment]
Thanks for the PR -- the main point of the above discussion is that you should configure your local repo so that pre-commit is run. You can find the docs for that here: https://freecad.github.io/DevelopersHandbook/gettingstarted/#setting-up-for-development

No need to worry about it for this PR, we have a backup process for devs who can't install the hook that adds an autoformatting commit if it is necessary. We'll squash that commit with yours when we merge.

**Comment by JamesHodgkins** [comment]
Thanks all, sorry for any additional work caused. I'll try and learn for future.

**Comment by 3x380V** [comment]
@luzpaz, I would wish that it was always the case...
@JamesHodgkins, you can still take an opportunity and save others some work. Any search engine would return useful articles when asked "git rebasing and squashing commits". Choice is your, of course. If you'll came across some specific (not general git related) question, feel free to ask.
For a start I noticed you are working on main branch. That's a bit inconvenient. Let me show how to use feature branch. Suppose you created welcome branch in your [fork](https://github.com/JamesHodgkins/FreeCAD/). All commits are there and you are on that branch. `git rebase -i main` will open `git-rebase-todo` for you in your favorite editor. You instruct git what to do there, save and exit. Git does the job. You verify and `git push --force origin HEAD`. Done, your PR is updated. In case you are using some king of GUI, well, depends on GUI. There is a lot of information online on the subject, so not worth to repeat it here. Happy hacking!

**Pull request closed without merging**
