### PR TITLE
[TD] wording improvements

### PR DESCRIPTION
**Pull request by donovaly**
- includes also the requested tab name change:  https://forum.freecadweb.org/viewtopic.php?p=367952#p367952

### CODE REVIEW

**Comment by WandererFan** [comment]
Travis Win fail.

**Comment by WandererFan** [comment]
Next time, squash your revert commit into the main commit.  Keep the master history tidy.

**Comment by donovaly** [comment]
> Next time, squash your revert commit into the main commit. Keep the master history tidy.

How can I achieve this? (I tried to do this since it annoyed me as well but could not find out how.)

**Comment by WandererFan** [comment]
- git rebase -i HEAD~2
- first screen: squash newer commit into older.  Cntl-o, enter, cntl-x to exit
- second screen: adjust commit messages.  cntl-o, enter, cntl-x
-

**Comment by donovaly** [comment]
>     * git rebase -i HEAD~2
>     * first screen: squash newer commit into older. 

Thanks.
I don't know command lines (I am a Windows guy ;-) ) so I will have to read how it is done the GUI-way (I use TortoiseGit).

**Pull request merged**
