### PR TITLE
Draft: improvements on the viewproviders for Dimension objects

### PR DESCRIPTION
**Pull request by vocx-fc**
Various improvements in style, PEP8, spacing, docstrings.

The functions `getDefaultUnit`, `makeFormatSpec`, `displayExternal` are used to get the default unit schema for lengths and angles, and display a string with a particular format.

They aren't used in `DraftGui.py`, but are used by the viewprovider of the Dimension objects. Therefore, they are moved into a separate module, `draftutils/units.py`, so that they can be imported without using the entire `DraftGui` module.

In `ViewProviderDimensionBase` use methods to set up the properties. As the dimension object has 16 properties, these properties are assigned using three methods corresponding to text, units, and graphics properties.

In `ViewProviderLinearDimension` various improvements in style, PEP8, spacing, docstrings. In particular use more readable variable names.

The modules `Part` and `DraftGeomUtils` have been delayed in import.

The `updataData` method is modified to return immediately if the Proxy property modified is different from `Start`, `End`, `Dimline` or `Direction`.

In `ViewProviderAngularDimension` the `updateData` method is modified to return immediately if the `arc` attribute does not exist. This is better to reduce the level of indentation of the code.

In all viewproviders we comment out the `touch` call, as the modifications only affect the viewprovider properties, not the real Proxy properties. If this causes problems with updating of the object, the changes can be reverted.

This follows after #3654.

Forum thread: [Annotation styles for Draft](https://forum.freecadweb.org/viewtopic.php?f=23&t=44051&start=80#p409630)

---

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by Russ4262** [comment]
Unrelated to PR:
Do you have any information about Travis CI failure to report situation? 

Thanks,
Russ

**Comment by vocx-fc** [comment]
Things fail. That's it.

I mean, I remember reading a couple of months ago that GitHub experienced a few database problems because they were overloaded. So it wouldn't surprise me if the same thing is happening now. Server overloads, the US collapsing, new coronavirus outbreaks, dogs and cats living together, you know, the usual. Maybe Forbes will come out with another article about it.

**Comment by sgrogan** [comment]
@Russ4262 you can use this link https://travis-ci.org/github/FreeCAD/FreeCAD/pull_requests in the interim.

**Comment by abdullahtahiriyo** [comment]
Closed and reopened to trigger travis CI.

**Pull request merged**
