### PR TITLE
[PD] Do both fuse and cut in `FeatureTransformed` if applicable

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Sometimes both fuse and cut need to be applied for features to work properly, for example:
1. https://forum.freecad.org/viewtopic.php?t=67716
2. https://forum.freecadweb.org/viewtopic.php?t=59260

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738">pipeline status</a> for feature branch [PR_6738](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738). Pipeline [515155505](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/515155505) was triggered at [12cca01](https://github.com/FreeCAD/FreeCAD/pull/6738/commits/12cca01e9f5f984f189d4d900f8f875886f987f7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738">pipeline status</a> for feature branch [PR_6738](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738). Pipeline [515175417](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/515175417) was triggered at [2871aa3](https://github.com/FreeCAD/FreeCAD/pull/6738/commits/2871aa3823f1b49039f83b92a2102a030f99c317). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738">pipeline status</a> for feature branch [PR_6738](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738). Pipeline [515567705](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/515567705) was triggered at [3c298bf](https://github.com/FreeCAD/FreeCAD/pull/6738/commits/3c298bf488de9f5be72a105d0ce722b1039b59c9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738">pipeline status</a> for feature branch [PR_6738](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738). Pipeline [516076523](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/516076523) was triggered at [9174c56](https://github.com/FreeCAD/FreeCAD/pull/6738/commits/9174c56afa904d9964256299cf5527c014b11661). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@wwmayer , I think this can go in for 0.20 since it polishes your recent work. Right?

**Comment by adrianinsaval** [comment]
where are the corresponding shapes for cut and fusion for fillets obtained?

**Comment by AjinkyaDahale** [comment]
@adrianinsaval you're probably looking for this: https://github.com/FreeCAD/FreeCAD/blob/2066946c2983a495b70a5ebd221888eb89e32d74/src/Mod/PartDesign/App/FeatureDressUp.cpp#L227.
There the shapes are made. Then they are "returned" here (by which I mean assigned to parameters passed by reference):
https://github.com/FreeCAD/FreeCAD/blob/2066946c2983a495b70a5ebd221888eb89e32d74/src/Mod/PartDesign/App/FeatureDressUp.cpp#L268

**Comment by adrianinsaval** [comment]
Haven't got a chance to look at all the code yet, but I'm confused, both the additive and the substractive parts are saved to the addsubshape, how does the transform then know which to cut and which to add? Also there is a conditional for `base->getAddSubType() == Additive` in `DressUp::getAddSubShap`e how is a fillet determined to be additive or substractive?

**Comment by AjinkyaDahale** [comment]
> Haven't got a chance to look at all the code yet, but I'm confused, both the additive and the substractive parts are saved to the addsubshape, how does the transform then know which to cut and which to add?

For dressup this the `AddSubShape` is a compound whose first shape is the add shape and second is subtract shape.

> Also there is a conditional for `base->getAddSubType() == Additive` in `DressUp::getAddSubShap`e how is a fillet determined to be additive or substractive?

I believe here the `addsubType` then kind of becomes irrelevant. Though this might be a culprit for [this particular issue](https://forum.freecadweb.org/viewtopic.php?f=19&p=588346#p588222) which I haven't explored.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738">pipeline status</a> for feature branch [PR_6738](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738). Pipeline [523058602](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/523058602) was triggered at [226f25b](https://github.com/FreeCAD/FreeCAD/pull/6738/commits/226f25b63b707479e3ac106feda8360f83ffa3a7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738">pipeline status</a> for feature branch [PR_6738](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6738). Pipeline [523059734](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/523059734) was triggered at [780772f](https://github.com/FreeCAD/FreeCAD/pull/6738/commits/780772fb11ca599b3366f454a7f175675e4ff5c9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Have just tested the code and it looks good to me. And I can confirm that the reported issue is fixed.

**Pull request merged**
