### PR TITLE
[BUGFIX] Sketcher: fix icon normal/construction toggling...

### LINKED ISSUE #7064: [Bug] RE: The "Toggle Construction Geometry Button" is not working in "Custom Workbenches".
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=8&t=69651#p604104
https://forum.freecadweb.org/viewtopic.php?f=3&t=5236

### Version

0.20 (Release)

### Full version info

```shell
Word size of FreeCAD: 64-bit
Version: 0.20.29192 (Git) AppImage
Build type: Release
Locale: English/United States (en_US)
```

### Subproject(s) affected?

_No response_

### Issue description

Foreword:

The "Toggle Construction Geometry" Button is located in the "Sketcher Workbench Toolbar".

When pressed, the "Toggle Construction Geometry Button" changes the colors of certain Buttons shown in the "Sketcher Workbench Toolbar" from "White" to "Blue", such as:
"Create Line" Button
"Create Arc" Button
"Create Circle" Button
"Create a Conic" Button
"Create a B-Spline" Button
"Create Polyline" Button
"Create Rectangles" Button
"Create Regular Polygon" Button
"Create Slot" Button
"Carbon Copy" Button
Et Cetera.

BUG:

This Bug can be duplicated by putting the "Toggle Construction Geometry Button" into a "Custom Workbench Toolbar", with all of the other Buttons that are suppose to change from "White" to "Blue".

As the image below indicates, when the "Toggle Construction Geometry Button" is put into a "Custom Workbench Toolbar", along with all of the other Buttons that are suppose to change from "White" to "Blue", the only Buttons that changes from "White" to "Blue" are the following:
"Create Line" Button
"Create Polyline" Button
"Create Slot" Button
"Carbon Copy" Button

-------

Another Good Day With GOD

-------

### Anything else?

FreeCAD Bug, Toggle Construction Geometry Button

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0penBrain**
...when commands used in custom toolbar

 Fixes #7064

https://forum.freecadweb.org/viewtopic.php?f=8&t=69651

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7072">pipeline status</a> for feature branch [PR_7072](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7072). Pipeline [570136160](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/570136160) was triggered at [1e7e3e0](https://github.com/FreeCAD/FreeCAD/pull/7072/commits/1e7e3e0694589ca1f874704a6a557bfa74cb1f62). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7072">pipeline status</a> for feature branch [PR_7072](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7072). Pipeline [570165983](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/570165983) was triggered at [b5e68cd](https://github.com/FreeCAD/FreeCAD/pull/7072/commits/b5e68cd953f52a14a66b532ead18cc162743ca1b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by abdullahtahiriyo** [comment]
Looked at the code. I need to synchronise this with other development. Will come back.

**Comment by donovaly** [comment]
Since it fixes a known bug and since I would like to make a bugfix release soon, it would be good, if this could be merged the next days if possible.

**Comment by 0penBrain** [comment]
@donovaly I think @abdullahtahiriyo plan was to "merge" these changes in the big work being currently in Sketcher.
I don't think this plan would allow you to easily backport the changes.

This said, abdullah hasn't been active for a couple of weeks. If you want to backport this, the best is probably to merge this PR as is without more waiting. If it's too much a pain for abdullah to solve merge conflicts then, he can had a reverting commit in his branch and port the changes from scratch. ;)

**Comment by donovaly** [comment]
Thanks. And you are right, in order to backport I need a single commit (is much easier).

Therefore I would merge it now.
Looking at the diff, I also think there won't be too many merge conflicts and if, the should be easy to resolve (fingers crossed). Moreover Werner's current code changes will inflict more merge conflicts.

However, to merge now, can you please rebase and fix the existing merge conflict?

**Comment by 0penBrain** [comment]
@donovaly give me a couple of days to rebase. ;)

**Comment by donovaly** [comment]
> @donovaly give me a couple of days to rebase. ;)

OK, I would like to make the next bugfix release in about 2 weeks and have this in.

**Comment by 0penBrain** [comment]
@donovaly It's rebased. Honestly this was a mess and I finally skipped my commit at rebase and redo everything with copy-pasting. Hopefully I have to do it only once. :)

**Comment by donovaly** [comment]
Thanks!

**Comment by donovaly** [comment]
Wow, backporting was tough. If you have the next days a minute, can you please take the 0-20 branch and check if everything is as it should be?

Concerning your new FIXME, the icon "Sketcher_CreateEllipse" shows already what the function Sketcher_CreateEllipseByCenter does. So I think I can just add this icon under the name "Sketcher_CreateEllipseByCenter", right?

**Comment by 0penBrain** [comment]
> Wow, backporting was tough. If you have the next days a minute, can you please take the 0-20 branch and check if everything is as it should be?

Yes. Obviously you had the same mess I got when rebasing. ;) 
> Concerning your new FIXME, the icon "Sketcher_CreateEllipse" shows already what the function Sketcher_CreateEllipseByCenter does. So I think I can just add this icon under the name "Sketcher_CreateEllipseByCenter", right?

Yes,  but also need to copy Sketcher_CreateEllipse_Cons as Sketcher_CreateEllipseByCenter_Cons so the construction mode works. Then you can fix the FIXME. ;)

**Comment by donovaly** [comment]
> Yes, but also need to copy Sketcher_CreateEllipse_Cons as Sketcher_CreateEllipseByCenter_Cons so the construction mode works. Then you can fix the FIXME. ;)

Here is the PR: #7265
OK?

**Pull request merged**
