### PR TITLE
Update PROBLEM_REPORT.yml

### PR DESCRIPTION
**Pull request by maxwxyz**
change title of issue report

### CODE REVIEW

**Comment by NomAnor** [comment]
The template is currently broken and no new problem reports can be created. This fixes it, please merge

**Comment by furgo16** [comment]
@maxwxyz Great to see the `[Problem]` prefix go away and labels being used. Regarding this fix, would it not be simpler to remove the [optional](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax) `title` key from the issue template? This would have at least two benefits:

1. Fix the inconsistency in having a template that refers to the submission as a "Problem" and the description referring to it as an "Issue". E.g. `name: Report a Problem` (used also in the template chooser), `title: "Replace with a concise issue title"`
2. Save the reporters the step of selecting the string and deleting it before writing their issue title. If it were selected by default it'd make it easier, but it's not, as far as I can tell.

Thanks!

**Comment by maxwxyz** [comment]
@furgo16 I've tried with a blank title but then the issue template was broken. Are you sure that if we remove the title keyword entirely, that the user is able to input a title? Then I'm ok with that.

**Comment by furgo16** [comment]
@maxwxyz thanks. See https://github.com/FreeCAD/FreeCAD/pull/12863 for details and a working test on a fork.

**Pull request merged**
