### PR TITLE
FEM unit test

### PR DESCRIPTION
**Pull request by berndhahnebach**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

hopefully unit test on windows passes :-)

https://forum.freecadweb.org/viewtopic.php?f=18&t=23170

### CODE REVIEW

**Comment by berndhahnebach** [comment]
on Linux everything runs smooth on Windows I get the following error messag at home, thus one line is still different in input file unit test 

`
Traceback (most recent call last):
  File "C:\Daten\FreeCAD_0.17.11472_x64_dev_win\bin\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Daten\FreeCAD_0.17.11472_x64_dev_win\Mod\Fem\TestFem.py", line 593, in test_Flow1D_thermomech_analysis
    Flow1d_enlargement1.EnlargeArea2 = 1000000000000
AttributeError: Attribute (Name: EnlargeArea2) error: 'wrong type as quantity: long' 

`

**Comment by berndhahnebach** [comment]
the line which creates the error ... 
https://github.com/berndhahnebach/FreeCAD_bhb/blob/a2f66a1db3522e2780a63f75929b7d86f46cbd8f/src/Mod/Fem/TestFem.py#L593

**Comment by berndhahnebach** [comment]
ok on my local windows unit test runs smooth now. Let's see what AppVeyor says ... https://github.com/berndhahnebach/FreeCAD_bhb/commit/0b86a2c57b734fb9fb15e805d1bca92c0d82013f

bernd

**Comment by wwmayer** [comment]
> Flow1d_enlargement1.EnlargeArea2 = 1000000000000

Is this still happening with the latest master? I pushed a fix a few days ago where assigning a "long" number to a quantity property wasn't handled. 

About nullifying the numbers in the inp files I don't think this is the right way to go. For me the question is if both numbers formats (1.110223024625e-014 <=> 1.110223024625e-14) are allowed in an inp file then the comparison function must be improved. Furthermore I wonder which previous change caused the failure.

**Comment by berndhahnebach** [comment]
> About nullifying the numbers in the inp files I don't think this is the right way to go. For me the question is if both numbers formats (1.110223024625e-014 <=> 1.110223024625e-14) are allowed in an inp file then the comparison function must be improved. 

My idea was to make this unit test simpler to fail by use a cleaner input with 0 and make a separat unit test just for the writeAbaqus which than uses such numbes like  (1.110223024625e-014 <=> 1.110223024625e-14)  From my point of view both are allowed but I have not found a proof in the ccx manual yet. 


> Furthermore I wonder which previous change caused the failure.

https://github.com/FreeCAD/FreeCAD/commit/9fd673851ca936c68fc741e4785243b1298e6309

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/849/commits/c4024143f3c3331076a92d694aa9fb157a28af09

add a unit test just for this character problem we are facing.

**Comment by berndhahnebach** [comment]
Again changed the unit test for writeABAQUS slightly. Added some helpful comments ... 

In the regard of 
> For me the question is if both numbers formats (1.110223024625e-014 <=> 1.110223024625e-14) 

99.9% yes. To get to 100% some Fortran guy should say yes it is allowed. But more important is that we do not export more than 20 character for each number. See comments in my last commit https://github.com/FreeCAD/FreeCAD/pull/849/commits/840a3baf4815b5113593ae59e8ea718790c30e11

bernd

**Comment by berndhahnebach** [comment]
changed the writeABAQUS test another time, to have more different numbers https://github.com/FreeCAD/FreeCAD/pull/849/commits/c806e4529e54b93cb22b1ed096c1d8cb37aa00ff#diff-3e3abd32a5c61ba7a5c7283988b9d904R107

**Comment by wwmayer** [comment]
> What's your opinion about moving all writeABAQUS precision tests in a separate small test def?

+1 The more explicit tests we have the better it is because then it's also easier to find out the reason of a failure.

**Pull request merged**
