### PR TITLE
Adjust Startpage version info to new format

### PR DESCRIPTION
**Pull request by adrianinsaval**
due to the changes from #7955

reported in https://forum.freecadweb.org/viewtopic.php?p=649107#p649107

should also be backported IMO, this is how it's currently shown in stable release
image

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8085">pipeline status</a> for feature branch [PR_8085](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8085). Pipeline [731217931](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/731217931) was triggered at [eceb790](https://github.com/FreeCAD/FreeCAD/pull/8085/commits/eceb79096453ffc60543fc06b81c074fc5053fc1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
@donovaly IMO this should be backported too

**Comment by donovaly** [comment]
> @donovaly IMO this should be backported too

Why? I mean #7955 was not backported.

**Comment by adrianinsaval** [comment]
Yeah but this is introduced by ddbcc0b3d58db90b9217ed3b8e2781338184646a (this is from 0.20 branch) which I cherry picked in that PR. This is how 0.20.2 shows this:
image

**Comment by donovaly** [comment]
OK then. Done.

**Pull request merged**
