### PR TITLE
[PD] allow to change feature order in patterns

### PR DESCRIPTION
**Pull request by donovaly**
As discussed here: https://forum.freecadweb.org/viewtopic.php?f=27&t=48998#p420352
The pattern dialogs need a feature to change the order of the features to be patterned

### CODE REVIEW

**Comment by wwmayer** [comment]
Two remarks:
Don't you get a compiler warning when writing: for (unsigned i = 0; i < ui->listWidgetFeatures->count(); i++) ?
count() returns an int but as variable you use an unsigned. With clang and gcc this correctly raises a warning because signed and unsigned are compared

There is some code duplication. The function indexesMoved() is the exact same code in all four implementations. So, the code should be moved to the base class. Of course the ui->listWidgetFeatures is defined in the sub-classes but there is a trick to indirectly access it from the base class. In a slot function one can access the sender of a signal (here QAbstractItemModel)

**Comment by wwmayer** [comment]
a9af41869

**Comment by donovaly** [comment]
> Don't you get a compiler warning when writing: for (unsigned i = 0; i < ui->listWidgetFeatures->count(); i++) ?

That is funny because I never used an unsigned before in for loops. While searching yesterday in Qt forums I found a statement that an unsigned is sufficient. so I tried it out, got no compiler warning and thus committed it.

> the ui->listWidgetFeatures is defined in the sub-classes but there is a trick to indirectly access it from the base class. In a slot function one can access the sender of a signal (here QAbstractItemModel)

Many thanks. I did not know this.

**Comment by wwmayer** [comment]
> That is funny because I never used an unsigned before in for loops. While searching yesterday in Qt forums I found a statement that an unsigned is sufficient. so I tried it out, got no compiler warning and thus committed it.

The chance that this causes some harm is zero but IMO it's still bad practice (especially when the compiler raises a warning). If you are unsure what type to use then use: auto

**Pull request merged**
