### PR TITLE
Assembly: Insert new part

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fix https://github.com/FreeCAD/FreeCAD/issues/14464

Video demo : 

https://github.com/user-attachments/assets/60472d64-06ab-47a8-a0ab-2092eea6c39e

### CODE REVIEW

**Comment by maxwxyz** [comment]
@pierreporte FYI

**Comment by PaddleStroke** [comment]
Doing this PR I found many issues on the road to top down workflow:
- editing a sketch from the assembly file, after finishing the edit, the solids do not go back to "As Is" but stay in "no shadow". As you may see in the video. @maxwxyz do you know if we have an open issue for this?
- doing a pad operation from the assembly file is changing the active view to go to the body's document.
- editing a sketch remove the edit from the assembly. Which also collapse the assembly. Which is annoying. We need a way to automatically re-activate the assembly when closing the sketch.
- we can't use the rest of assembly as external geos 

Do you see further issues?

**Comment by maxwxyz** [comment]
@PaddleStroke I guess https://github.com/FreeCAD/FreeCAD/issues/16885

**Comment by pierreporte** [comment]
Looks good!

There should be an easy way to select the assembly origin as the part origin (not just the point but axis orientation as well). Maybe a checkbox would be enough.

There should be the same thing for creating a sub-assembly.

**Comment by luisDias89** [comment]
@chennes This commit shouldn't be possible to test in the latest weekly build, should it?
I was expecting to be able to test it in the one released yesterday.

**Comment by maxwxyz** [comment]
No, it's not merged yet. We sort the PRs by last recently updated for the merge meetings. So this is at the bottom of the queue again 😄

**Pull request merged**
