### PR TITLE
added CAM to precommit

### PR DESCRIPTION
**Pull request by sliptonic**

### CODE REVIEW

**Comment by chennes** [comment]
You need to either run pre-commit manually on all your files, or allow maintainers to edit your PR so the CI does it for you. Ping me if you need help running manually.

**Comment by adrianinsaval** [comment]
is it supposed to touch .ts files?

**Comment by sliptonic** [comment]
This file is causing me some headache:  /src/Mod/CAM/libarea/kurve/geometry.h

I run the pre-commit locally and it modifies many files including geometry.h
I stage all the changed files to a commit and try to commit.  I get this message from precommit:

```
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check for added large files..............................................Passed
mixed line ending........................................................Passed
black................................................(no files to check)Skipped
clang-format.............................................................Failed
- hook id: clang-format
- files were modified by this hook
```

I rescan and that file has been changed again but the diff appears the same.

I add it to the staged files and try again.  Same error.  The file has changed again and it's the same diff again.  

If I try committing without that file I get this error 

[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/brad/.cache/pre-commit/patch1715963902-219549.
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check for added large files..............................................Passed
mixed line ending........................................................Passed
black................................................(no files to check)Skipped
clang-format.............................................................Failed
- hook id: clang-format
- files were modified by this hook
[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
[INFO] Restored changes from /home/brad/.cache/pre-commit/patch1715963902-219549.

**Comment by sliptonic** [comment]
FWIW, the diff is strange too.
image

**Comment by sliptonic** [comment]
still working on it

**Comment by sliptonic** [comment]
Will try on another machine

**Comment by sliptonic** [comment]
*bump*

**Comment by adrianinsaval** [comment]
I had to manually edit the comments on some files so please check carefully that nothing's really changed

**Comment by sliptonic** [comment]
Holding until some developers submit outstanding work

**Comment by adrianinsaval** [comment]
@sliptonic this should now be ready

**Comment by adrianinsaval** [comment]
these changes have been pushed to main

**Pull request closed without merging**
