### PR TITLE
Override warning cleanup

### PR DESCRIPTION
**Pull request by ianrrees**
This gets rid of ~5k warnings when building on MacOS.

### CODE REVIEW

**Comment by wwmayer** [comment]
Hi Ian,

I have two questions:
How comes that for the macOS build on travis we don't get any of these warnings?
What is the reason to add a bunch of new macros instead of modifying the existing ones? For me it's not clear when to use which one when creating a new class.

**Comment by ianrrees** [comment]
Good questions!  I should mention the other option is to just mute all the override warnings - I don't get the impression that this is a useful enough C++11 feature to justify too much work.

I think the Travis builds use an older clang.  I've got XCode 8.2.1 (LLVM 8.0.0, clang-800.0.42.1) on my computer where I was seeing the warnings.

The macros are because the warnings only show when a class is declared that uses override at least once, for every method that is overridden but doesn't declare that it is an override.  So, if the regular macros are changed to get overrides, then we need to put the override keyword on every overridden method in classes that use those macros.  AFAIK, there's no problem with using the "wrong" macro, except that you'll get these warnings again.

**Comment by wwmayer** [comment]
OK I see. Thanks for the answer.

**Comment by wwmayer** [comment]
Merged.

**Comment by ianrrees** [comment]
Thanks!  If you think it's worthwhile, I could look at moving the rest of the project to using the override keyword.

**Comment by wwmayer** [comment]
Yes, if you still get warnings it would be good to properly fix them.

**Pull request closed without merging**
