### PR TITLE
[Arch] fix Arch_Stairs recompute issue

### LINKED ISSUE #7050: [Bug] Stairs number of steps & still touched...
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=23&t=68424
some parts of the issue found in:
https://forum.freecadweb.org/viewtopic.php?f=23&t=56466
### Version

0.20 (Development)

### Full version info

```shell
[code]
OS: Windows 7 SP 1 (6.1)
Word size of FreeCAD: 64-bit
Version: 0.20.29182 (Git)
Build type: Release
Branch: master
Hash: e89ebba7369dca5775fd8aa878a0d3c494e6b2ac
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Swedish/Sweden (sv_SE)
[/code]
```

### Subproject(s) affected?

Arch

### Issue description

I've seen some issues with ArchWB / BIM: Stairs
When I enter ex. 11 steps are created 10 steps.  and railings
When I enter 2 steps, no steps are created and railings
When I enter 1 step, no steps are created but a plate with "Structure Thickness" and railings

16:31:47  0 <App> Document.cpp(3546): Unnamed#Rail still touched after recompute
16:31:47  3.0343e-05 <App> Document.cpp(3546): Unnamed#Rail001 still touched after recompute

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Roy-043**
Fixes #7050.

The recompute issue was due to the inclusion of the railings in the `Additions` property of the stairs object. The `RailingLeft` and `RailingRight` properties now have the `"App::PropertyLinkHidden"` type and the referenced objects are claimed as children.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8444">pipeline status</a> for feature branch [PR_8444](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8444). Pipeline [774972651](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774972651) was triggered at [50d5fc4](https://github.com/FreeCAD/FreeCAD/pull/8444/commits/50d5fc42017af39678f1ed4b9fe8dd5d38ac8950). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8444">pipeline status</a> for feature branch [PR_8444](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8444). Pipeline [774980657](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774980657) was triggered at [e1b8851](https://github.com/FreeCAD/FreeCAD/pull/8444/commits/e1b885106af51beb20125e7048f2bf13e46a3b1f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Roy-043** [comment]
To make this PR backportable I'll change '0v21' to '0v20'. I will also add some warnings. Changing PR status to Draft.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8444">pipeline status</a> for feature branch [PR_8444](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8444). Pipeline [776361173](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/776361173) was triggered at [72acf87](https://github.com/FreeCAD/FreeCAD/pull/8444/commits/72acf8798daa569c2078c3c5caa65db5dda3879e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8444">pipeline status</a> for feature branch [PR_8444](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8444). Pipeline [776368598](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/776368598) was triggered at [d22db45](https://github.com/FreeCAD/FreeCAD/pull/8444/commits/d22db45c46c3fbd90a6433c4f29146ae06a1b1ba). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
