### PR TITLE
[TD]allow loading SVG item from file

### PR DESCRIPTION
**Pull request by WandererFan**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8865">pipeline status</a> for feature branch [PR_8865](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8865). Pipeline [803900022](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/803900022) was triggered at [c1b4090](https://github.com/FreeCAD/FreeCAD/pull/8865/commits/c1b40908a72239e4331dfc9daee6959ffb56152b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by aapo-aapo** [comment]
Hi,

Are you sure it's not problematic that the two [virtual bool load()](https://github.com/FreeCAD/FreeCAD/commit/5462c9de6fdc34b211d58d90b9fe4d79ac3503c1#diff-bf888c6fffea106d57417a20dde7b40668728229989f5676e065cb33c86d0d46) functions only differ by their argument?  I mean if you pass a QString it uses it as a filename to load an SVG; and if you pass a QByteArray * it renders the SVG within the underlying string data.  Given that they both represent string data (although not automatically casted into each other), I think it'd probably be safer to rename load(QByteArray *) to embed(QByteArray *)

**Comment by WandererFan** [comment]
This mimics QSvgRenderer which has overloaded load() methods for QByteArray (load from bytes) and QString (load from file).  

It also has an overload for a stream, but I don't know if we need that.

**Comment by aapo-aapo** [comment]
Ah, I see.  Then it's probably good enough, thanks!

**Pull request merged**
