### PR TITLE
Issues 8884, 8806. Change readDXF settings handling

### PR DESCRIPTION
**Pull request by kpemartin**
This PR is offered as a correction for issues #8884 and #8806

The change leaves loading the regular import options to the `ImpExpDXFRead` class object's ctor (where the code already existed). If the caller to `readDXF` passes a fourth argument specifying another options location, this will be given to the `ImpExpDXFRead` object to load from, but otherwise `readDXF` does not initiate any options loading.

The documentation string for readDXF has been updated to include the options_source argument, which was already in the code.

Because the removed code was causing the `ImpExpDXFRead` to load settings from a location where no settings had been stored, the settings from the dialog were being ignored, so no text was being imported, layers were never grouped into blocks, and the scaling factor was always 1.

- [X ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I am not sure I would do this...
Originally, this C++ dxf importer/exporter was part of Draft. Then it has been moved to Import because it was more logical, made Draft again 100% python,  and also so it could be shared with other modules. TechDraw uses it already.
But since at the moment only Draft has preferences options implemented, all the pref settings have been kept within Draft.
But in the future this could (and maybe should, not sure) change. So I would think it makes sense to still default to read options from User parameter:BaseApp/Preferences/Mod/Import, even if it's currently unused. Be it only to not have to redo later something that was undone now...

**Comment by kpemartin** [comment]
My feeling is somewhat opposite this.

There are several things to do to move the options to the new storage location, and the existing support code for the new location is the only part implemented. And a tiny part it is, changing one path string relating to the options storage location. If this were changed back to use the old location, in the future when a shift to the new location were done fully, it would be trivial to find and change back.

Right now it is just an impediment to other development, an unused stub of code that nevertheless needs to be maintained. If the change were harmless it would not be a problem, but right now the change breaks DXF import.

I would feel quite differently about this if there were a well laid-out plan in place to migrate the options location, with a list of where changes were required and what the changes might be, both in terms of code changes and UI changes. Would Import work differently depending on which workbench is active? What about "Open file"? Would there be separate options for Draft import and TechDraw import? Perhaps such a plan exists and I just haven't found it.

That being said, I do have a different fix for the problem, which changes `ImpExpDxfRead.setOptions` so that, when it is called, the settings that exist in the new options container will be loaded, but settings that do not exist in the new options container are left unchanged. The current behaviour is that settings that do not exist int the container revert to their hard-coded defaults. Because the current code is passing an empty container (`Mod/Import`), this forces all options to their hard-coded defaults. With this alternative proposed change, the options not in the passed container would stay at the settings read by the `ImpExpDxfRead` ctor from the `Mod/Draft` location.

**Comment by yorikvanhavre** [comment]
Hmm you have a point there indeed. It may actually be good to force it that way: The import/exporter has no preferences on their own. It's the responsibility of the module using it to provide the UI and preferences. That turns it even more generic, actually...

Ideally then, the module should not provide a preferences path, but rather already all the needed values. So the UI/preferences could be arranged really as the module prefers. But that's a discussion for later :)

Ok I'm convinced. But before merging, I'd like to check to make sure TechDraw or OpenSCAD are not using or setting anything in User `parameter:BaseApp/Preferences/Mod/Import` 

@WandererFan please shout if I forgot something ;)

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8959">pipeline status</a> for feature branch [PR_8959](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8959). Pipeline [815710882](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/815710882) was triggered at [62f2683](https://github.com/FreeCAD/FreeCAD/pull/8959/commits/62f26835801ce95b1932513af767bcb0a959f08c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8959">pipeline status</a> for feature branch [PR_8959](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8959). Pipeline [817382499](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/817382499) was triggered at [20ab1f8](https://github.com/FreeCAD/FreeCAD/pull/8959/commits/20ab1f8eff62bf7fba7ce44de710d83f169a9497). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8959">pipeline status</a> for feature branch [PR_8959](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8959). Pipeline [817390153](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/817390153) was triggered at [09f1458](https://github.com/FreeCAD/FreeCAD/pull/8959/commits/09f145819509a114e0667c59a7015f6752a374f2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8959">pipeline status</a> for feature branch [PR_8959](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8959). Pipeline [817392570](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/817392570) was triggered at [cd9ca44](https://github.com/FreeCAD/FreeCAD/pull/8959/commits/cd9ca4496a6f33a5a6d756285c96f71186221735). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks, merging

**Pull request merged**
