### PR TITLE
Python3 Arch

### PR DESCRIPTION
**Pull request by looooo**
cherry picking commits of the python3-branch relevant for the arch module + resolving the diff with difftool.

### CODE REVIEW

**Comment by wwmayer** [comment]
In cleanArchSplitter the invalid argument "objets" is replaced by another invalid argument "objecs". It should be "objects".
Then in ArchProfile.py  opening a csv file has changed from 
with open(profilefile, 'rb') as csvfile:
to
with open(profilefile, 'r') as csvfile:

Is the indented and does it also work?

**Comment by looooo** [comment]
This was done by @yorikvanhavre, so I thought it's intentional. But I make another commit to fix it.

**Comment by looooo** [comment]
I think there were some commits more relevant to the arch workbench. I will try again later.

**Comment by looooo** [comment]
ok I checked it again. It will introduce two easier conflicts so not a too big problem. If you are ok with the current state, I think this can be merged.

**Pull request merged**
