### PR TITLE
Fix backwards-compatible Qt6 warnings

### PR DESCRIPTION
**Pull request by jwueller**
Nothing fancy, just some cleanup:
- `qAsConst` → `std::as_const`
- `QLocale::languageToString` instance → `QLocale::languageToString` static
- `QLocale::countryToString` instance → `QLocale::countryToString` static
- `QApplication::setActiveWindow` → `MainWindow::activateWindow`

### CODE REVIEW

**Comment by oursland** [comment]
To get this to compile with both Qt5 and Qt6, the incompatible changes should be wrapped in version checks, such as:

    #if QT_VERSION < QT_VERSION_CHECK(6, 5, 0)
        // Qt5-compatible code
    #elif QT_VERSION >= QT_VERSION_CHECK(6, 5, 0)
        // Qt6-compatible code
    #endif

**Comment by jwueller** [comment]
Ah, sure. I'll add that.

**Comment by 3x380V** [comment]
> To get this to compile with both Qt5 and Qt6, the incompatible changes should be wrapped in version checks, such as:
> 
> ```
> #if QT_VERSION < QT_VERSION_CHECK(6, 5, 0)
>     // Qt5-compatible code
> #elif QT_VERSION >= QT_VERSION_CHECK(6, 5, 0)
>     // Qt6-compatible code
> #endif
> ```

Please don't. This is just adding noise to the code. Just drop all changes incompatible with both Qt5 and Qt6.

**Comment by wwmayer** [comment]
The PR makes all builds using Qt5 to fail. The problematic changes are:
```
QColor::fromString() since Qt 6.4
QLocale::territoryToString since Qt 6.2
QLocale::territory() since Qt 6.2
```
In src/Gui/Tools there is a convenience class QtTools to wrap Qt5 / Qt6 incompatible changes.

**Comment by jwueller** [comment]
As you can see, it all builds now, I'm just rebasing onto the current main.

**Comment by chennes** [comment]
@kadet1090 is going to test.

**Comment by kadet1090** [comment]
Builds fine on Qt6, not seeing any obvious problems - can be merged.

**Pull request merged**
