### PR TITLE
Materials: UI updates for transparency

### PR DESCRIPTION
**Pull request by davesrocketshop**
Add missing UI elements to support per face transparencies:
- Setting per face transparencies
- show transparency information in the appearance inspector
- expose alpha channel in color selector dialog

### CODE REVIEW

**Comment by davesrocketshop** [comment]
Setting per face transparencies. Old:

MaterialPropertiesOld

New:

MaterialPropertiesNew
 
Per face information in Appearance inspector. Old:
Screenshot 2024-09-05 133722

New:
AppearanceInspector

Expose alpha channel in color selector. Old:
Screenshot 2024-09-05 133807

New:
ColorSelectorQT6

**Comment by davesrocketshop** [comment]
@chennes some updates for transparency. There is a new translation for this PR as the word 'Transparency' is new occurrring twice.  Not sure what you want to do with that. Also not sure if there's an issue associated with this

**Comment by maxwxyz** [comment]
does this fix https://github.com/FreeCAD/FreeCAD/issues/14938 or https://github.com/FreeCAD/FreeCAD/issues/14414 ?
@Roy-043

**Comment by davesrocketshop** [comment]
> does this fix #14938 or #14414 ? @Roy-043

No. In those it expects diffuse color alpha channel to set transparency, which it should never do

**Comment by furgo16** [comment]
And does it address https://github.com/FreeCAD/FreeCAD/issues/14939?

**Comment by davesrocketshop** [comment]
> And does it address #14939?

Yes. It adds a field to set the transparency.

**Pull request merged**
