### PR TITLE
Fix some GCC warnings.

### PR DESCRIPTION
**Pull request by f3nix**
This fixes 90 out of 92 warnings that are polluting the console with GCC.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This build fails for me:

```
[ 49%] Building CXX object src/Mod/Part/Gui/CMakeFiles/PartGui.dir/TaskCheckGeometry.cpp.o
/home/yorik/Sources/FreeCAD/src/Mod/Part/Gui/TaskCheckGeometry.cpp: In member function ‘int PartGui::TaskCheckGeometryResults::goBOPSingleCheck(const TopoDS_Shape&, PartGui::ResultEntry*, const QString&)’:
/home/yorik/Sources/FreeCAD/src/Mod/Part/Gui/TaskCheckGeometry.cpp:619:2: error: ‘bopAlgoTime’ was not declared in this scope
   Q_UNUSED(bopAlgoTime);
  ^
src/Mod/Part/Gui/CMakeFiles/PartGui.dir/build.make:1762: recipe for target 'src/Mod/Part/Gui/CMakeFiles/PartGui.dir/TaskCheckGeometry.cpp.o' failed
make[2]: *** [src/Mod/Part/Gui/CMakeFiles/PartGui.dir/TaskCheckGeometry.cpp.o] Error 1
CMakeFiles/Makefile2:1793: recipe for target 'src/Mod/Part/Gui/CMakeFiles/PartGui.dir/all' failed
make[1]: *** [src/Mod/Part/Gui/CMakeFiles/PartGui.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by f3nix** [comment]
Hi,
yes. This is because of 8a30ac74b0715c361d1912d332d5ffc9649d30cb

Maybe @wwmayer could shed some light on this.

As far as I can tell bopAlgoTime is only used here: https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/Gui/TaskCheckGeometry.cpp#L617

And this is the line from my PR: https://github.com/FreeCAD/FreeCAD/pull/197/commits/67e9868e7c6dd2b7261af308b587d8743d1e75fb#diff-a2fdb3520e74255a3915cf5bb5c851e0L615

Cheers,
Mateusz

**Comment by wwmayer** [comment]
Here two ways to fix the warning in TaskCheckGeometryResults::goBOPSingleCheck collide.
In my method I used Qt'S Q_UNUSED which basically means "void". This way the compiler no longer complains it's an unused variable

In your method you moved the 'bopAlgoTime' inside the FC_DEBUG define so that outside, this variable is no longer visible, hence the build failure. However, with your way "start_time" is now unused and with a different compiler or a higher warn level you will get the same warning again, for sure.

**Comment by f3nix** [comment]
Thanks @wwmayer for the explanation. I have not thought about "start_time".

Cheers,
Mateusz

**Comment by wwmayer** [comment]
Merged.

**Comment by f3nix** [comment]
Thanks @wwmayer for fixing the build failure! :)

Cheers,
Mateusz

**Pull request closed without merging**
