### PR TITLE
[Start] [Post 1.0] give better contrast for the AddonManager Link Color...

### PR DESCRIPTION
**Pull request by Syres916**
... in Dark themes

Currently:

Dark_AddonManager_Link

this PR allows ThemeAccent1 to be used in order to be acceptable across all themes.

This is Post 1.0 as it affects translations

### CODE REVIEW

**Comment by kadet1090** [comment]
I wonder if there is a better way to achieve it, maybe by changing the palette - https://stackoverflow.com/questions/5497799/how-do-i-customise-the-appearance-of-links-in-qlabels-using-style-sheets?

Another possibility Instead of concatenating HTML inside QLabel you could also just place `color: @ThemeColor1` and then replace it with actual color over translated string.

**Comment by Syres916** [comment]
Thanks for the feedback @kadet1090 so far everything I've tried including the really simple use of the themecolor doesn't work but I'll give it a fresh look in 10 days time.

**Comment by MisterMakerNL** [comment]
```
QLabel[haslink="true"] {
  color: #71b6fb;
}
```
Is normally used for this.,

**Comment by maxwxyz** [comment]
@Syres916 will you move forward with this PR?

**Comment by Syres916** [comment]
I can't find another way to achieve the goal so if it's not good enough I'll close it but every suggestion made I can't seem to get to work.

**Comment by MisterMakerNL** [comment]
It would be nice to use the haslink option from the stylesheet. But otherwise it would be better to make a new element in the stylesheet. It will be confusing if we have 2 link colors.

**Comment by Syres916** [comment]
> It will be confusing if we have 2 link colors.

So you want it to be 1907817471 (#71b6fb) ?

**Comment by MisterMakerNL** [comment]
> > It will be confusing if we have 2 link colors.
> 
> So you want it to be 1907817471 (#71b6fb) ?

The best way to do this is too do it true the stylesheet where we can link the 2.

**Comment by Syres916** [comment]
I'll leave it with you then as I've wasted so much time trying and failing to get anything working in the Start module that works fine elsewhere in the code.

**Pull request closed without merging**
