### PR TITLE
Fem: Use expressions in fem task panels

### PR DESCRIPTION
**Pull request by marioalexis84**
Fixes https://github.com/FreeCAD/FreeCAD/issues/5655
The only object left pending is ElementFluid1D which will be updated in a separate pull request.

Note:
The modifications are not very big, but there are changes in the code style to move from camel case to snake case in Python files.

@FEA-eng

### CODE REVIEW

**Comment by maxwxyz** [comment]
@FEA-eng 1.0?

**Comment by FEA-eng** [comment]
> @FEA-eng 1.0?

Possibly yes - it fixes quite important inconsistency.

**Comment by marioalexis84** [comment]
This also fixes a bug in the heat flow constraint: If the task panel is reopened and the constraint type is not changed, the original values of the properties associated with the unused constraint type are lost.

Properties change from float to corresponding property units.

**Comment by chennes** [comment]
Backported to 1.0

**Pull request merged**
