### PR TITLE
FEM: Show displacement magnitude contour plot by default in FEM

### LINKED ISSUE #9477: [Feature Request] Displacement magnitude activated by default in the default results pipeline in FEM
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=77149

### Subproject(s) affected?

FEM

### Idea description

With the new improvements introduced by @donovaly, the results pipeline is automatically created after running an analysis which is great. However, what is shown is a confusing legend with no color map displayed on the model. Thus, I would suggest making the following small change - setting Field in that automatically created results pipeline settings to Displacement (Vector: Magnitude) or Displacement Magnitude (that's what that sole legend shows) instead of None by default. This way the user would see the results right after solving an analysis which is much less confusing than what is currently displayed.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
resolves #9477 (contour plot of the displacement magnitude is displayed by default in addition to the corresponding color legend)

### CODE REVIEW

**Comment by Syres916** [comment]
@FEA-eng I'm quite certain it's not your PR, I've had 3 separate extreme slow or complete failures this week. One I've reported because it involves _fmt_ being downloaded each time which is a little bizarre. I've been stewing on whether to raise an Issue for the CI becoming unreliable, it's felt on the cusp this week. I'll hang fire for now but certainly newer developers will be getting concerned if every time they submit a simple PR it comes up with a red cross.

The easy way to prove it is to hit the **Update Branch** button next to _This branch is out-of-date with base branch_ which will give it a kick to start the Checks again. In my experience as long as it's quietened down they tend to complete properly.

**Comment by Syres916** [comment]
@FEA-eng I might have spoke too soon, when you ran the tests on the AppImage, did you do it with clean config files. This is something I'd never experienced before this weekend but only after a PR author who had asked me to test something did we conclude that my 6 week old config files were having an adverse effect on the Unit Tests.

I'll copy the portent parts of the test output here shortly.

**Comment by Syres916** [comment]
Well the fact that the Windows Build was successful and I can't get the thing to pass no matter whether I try with a space, without a space and with an underscore between Displacement and Magnitude is a mystery. As a complete vtk no knowledge person, is this something that might only be available in very specific versions of vtk or am I talking garbage?

Error output on my box:

```
****************************************************************************************************
********** run FEM TestObjectCreate tests **********************************************************
**************************************************************************************************** 
22:59:14  
22:59:14  ======================================================================
ERROR: test_femobjects_make (femtest.app.test_object.TestObjectCreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/john/freecad-daily-build763/Mod/Fem/femtest/app/test_object.py", line 75, in test_femobjects_make
    doc = create_all_fem_objects_doc(self.document)
  File "/home/john/freecad-daily-build763/Mod/Fem/femtest/app/test_object.py", line 1887, in create_all_fem_objects_doc
    vres = analysis.addObject(ObjectsFem.makePostVtkResult(doc, res))[0]
  File "/home/john/freecad-daily-build763/Mod/Fem/ObjectsFem.py", line 752, in makePostVtkResult
    obj.ViewObject.Field = "Displacement Magnitude"
ValueError: {'sclassname': 'N4Base10ValueErrorE', 'sErrMsg': "'Displacement Magnitude' is not part of the enumeration in TestObjectCreate#Pipeline_VtkResult.ViewObject.Field", 'sfile': '/home/john/freecad-daily-source/src/App/PropertyStandard.cpp', 'iline': 463, 'sfunction': 'virtual void App::PropertyEnumeration::setPyObject(PyObject*)', 'swhat': "'Displacement Magnitude' is not part of the enumeration in TestObjectCreate#Pipeline_VtkResult.ViewObject.Field", 'btranslatable': False, 'breported': False}
```

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34197 (Git)
Build type: Release
Branch: master
Hash: 80a54d51c1c212477a116f70e6bdbeb70e7628a7
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 


```

**Comment by FEA-eng** [comment]
Branch updated, let's see if this helps. I tested it on a fresh virtual Ubuntu machine (using Oracle VirtualBox). The host machine (Windows) has FreeCAD installed but not the virtual machine.

**Comment by Syres916** [comment]
Can you give your FC full info for the Ubuntu VM please.

**Comment by FEA-eng** [comment]
> Can you give your FC full info for the Ubuntu VM please.

```
OS: Ubuntu 22.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34137 (Git)
Build type: Release
Branch: master
Hash: 7ca834acc58841dcf2d66d186db818c8f35f359d
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
```

**Comment by Syres916** [comment]
@FEA-eng I'm going to have to bow out, I can't even see how this works in the Windows build. In your position it maybe best to put a step-by-step Gui Interactive method with a base file for someone like @0penBrain who maybe is a non-FEM expert but knows the CI well to review and maybe can advise of a special method in order to get the CI to allow it. I'm currently having my own nightmare creating some (what should be simple) tests because of the CI file permissions.

**Comment by FEA-eng** [comment]
I would appreciate anyone's help with this. It's a very simple but useful change. Basically, after running the analysis, the user sees the color legend corresponding to the Displacement Magnitude field but that field is not automatically selected in the results pipeline so there's no contour plot related to that color legend by default and the user has to enable it manually. Here's what has to be done in GUI after running the analysis (and what should be done automatically):

Effect

**Comment by 0penBrain** [comment]
@FEA-eng could you please create another temporary commit where you:

1) Add this line before the one you already added
`App.Console.PrintError(str(obj.ViewObject.getEnumerationsOfProperty('Field'))+'\n')`

2) Change this line (https://github.com/FreeCAD/FreeCAD/blob/686618411f452718abd056d7a55629a81f9965b4/.github/workflows/sub_buildUbuntu2204.yml#L35) to
`        default: true`

We'll see. :)

**Comment by FEA-eng** [comment]
@0penBrain Sure, it's done. Let's see what happens.

**Comment by 0penBrain** [comment]
> @0penBrain Sure, it's done. Let's see what happens.

Spoiler : same thing will happen. But we'll have more clues. :smile:

**Comment by 0penBrain** [comment]
Sorry, will be dry run because of my mistake.
You have to use `FreeCAD.` instead of `App.`.
:disappointed:

**Comment by FEA-eng** [comment]
> Sorry, will be dry run because of my mistake. You have to use `FreeCAD.` instead of `App.`. 😞

Ok, corrected

**Comment by 0penBrain** [comment]
Well, so as you can see here for example : https://github.com/FreeCAD/FreeCAD/actions/runs/6130459982/job/16639569911?pr=10569#step:12:3599
The only accepted value for `Field` at the time you try to set it is `None`.
Then I really don't know much about FEM, so I can try to investigate but maybe better to find a FEM WB expert. :wink:

**Comment by 0penBrain** [comment]
OK, my best guess ATM is that when `DisplayMode` is set to `Surface` just above, either this change isn't propagated when you try to set `Field`, or the change is propagated but the `Field` enum hasn't been updated yet (as it depends on `DisplayMode` and is updated when this latter changes).

**Comment by Syres916** [comment]
I take it @berndhahnebach is still rather busy with personal duties?

**Comment by FEA-eng** [comment]
@donovaly Also seems to be unavailable. I'm afraid there are no people familiar with the FEM workbench source code around.

It's just strange that it worked as expected when I tested this on Ubuntu.

**Comment by yorikvanhavre** [comment]
The problem is indeed that you are trying to set an enum property (`obj.ViewObject.Field`) a value that is not in its enum values. You'll need to debug why it is so, and indeed the fact that it behaves differently on different platforms. You should track where that enum is set. The PrintError line that you added before shows: `['None']` so that enum has not been populated for some reason.

One thing you could always do is:
```python
if  "Displacement Magnitude" in obj.ViewObject.getEnumerationsOfProperty('Field'):
            obj.ViewObject.Field = "Displacement Magnitude"
```
but it's of course best to solve the cause of the problem.

**Comment by chennes** [comment]
Heads up for those of you working on FEM: we will be adding FEM to our pre-commit scripts soon, @wwmayer has submitted a PR with the required formatting changes: https://github.com/FreeCAD/FreeCAD/pull/10771. Once that PR is merged you will want to make sure you have pre-commit installed locally (to avoid extra commits from the CI system changing your formatting). See Item 3 in the developer handbook Getting Started page for info: https://freecad.github.io/DevelopersHandbook/gettingstarted/

**Comment by marioalexis84** [comment]
The `makePostVtkResult` function should not refer to a specific mechanical analysis value such as `"Displacement Magnitude"`.
The class `Fem::FemPostPipeline` used inside the function is more general and valid for other types of analysis.

**Comment by FEA-eng** [comment]
> The `makePostVtkResult` function should not refer to a specific mechanical analysis value such as `"Displacement Magnitude"`. The class `Fem::FemPostPipeline` used inside the function is more general and valid for other types of analysis.

Right, it might be necessary to prepare such default contour plot variable settings for different types of analyses as well. CalculiX in FreeCAD FEM supports mechanical simulations solely so I guess that only electromagnetic, thermal and flow analyses in Elmer are left. Would you be able to code this ?

**Comment by luzpaz** [comment]
@marioalexis84 any progress here ?

**Comment by marioalexis84** [comment]
Not yet.
For thermomechanical analysis with `CalculiX`, the pipeline is added in the `importCcxFrdResults.importFrd` function. At the moment, it's safe to set the view provider `Field` property to `"Displacement Magnitude"` there.
But this will only work with `CalculiX`, since the pipeline is created automatically from a `FemResultObject` object and the `Field` values are defined in the FreeCAD source code.
With the `Z88` solver, the pipeline is not created automatically, so create the pipeline from the `Z88` `FemResultObject` object by clicking the pipeline icon, will still have the `Field` property set to `None`.
With `Elmer`,  there is no Result object and `Field` values are read directly from the files generated by the solver and passed to the VTK objects. So, if tomorrow `Elmer` changes the names from "displacement" to "Displacement" for mechanical analysis, the code will fail.

**Comment by yorikvanhavre** [comment]
I think this should simply be solved (for now) with my above suggestion: 
```python
if  "Displacement Magnitude" in obj.ViewObject.getEnumerationsOfProperty('Field'):
    obj.ViewObject.Field = "Displacement Magnitude"
```
so the code does not stop if the enum is correctly set. At least if the enum stays on "None" the user knows something went wrong?

**Comment by marioalexis84** [comment]
But that will only work for CalculiX. Not for Elmer and not even for Z88.
Therefore, it is preferable to set the value of the Field property in the specific place where this pipeline is added for the CalculiX results.

**Comment by maxwxyz** [comment]
@FEA-eng 
Is it possible to hide the automatically created Result Pipelines by default? When multiple results are expected (e.g. Eigenmodes, multiple timesteps) 10+ Pipeline results are created and activated by default. I now have to manually select each pipeline in the tree and hide it.
Also, when I delete a pipeline before hiding it, the pipeline is gone but visible in the 3D view and cannot be hidden again.

**Comment by luzpaz** [comment]
@maxwxyz please add your full [About](https://wiki.freecad.org/About) info when you comment on other tickets to avoid confusion etc... TIA!

**Comment by marioalexis84** [comment]
>Also, when I delete a pipeline before hiding it, the pipeline is gone but visible in the 3D view and cannot be hidden again.

 Can you create a new issue? this is a bug.

**Comment by maxwxyz** [comment]
> > Also, when I delete a pipeline before hiding it, the pipeline is gone but visible in the 3D view and cannot be hidden again.
> 
> Can you create a new issue? this is a bug.

Done: https://github.com/FreeCAD/FreeCAD/issues/11175

**Comment by sliptonic** [comment]
Moving this back to draft.  We need an answer to @marioalexis84's comment.

**Comment by maxwxyz** [comment]
@FEA-eng any news on this PR?

**Comment by FEA-eng** [comment]
> @FEA-eng any news on this PR?

Not yet, it turned out to be much bigger issue, mainly because we need different defaults for Elmer analyses and newly added CalculiX heat transfer ones.

**Comment by maxwxyz** [comment]
@FEA-eng @marioalexis84 also on this PR the heads up for the feature freeze, if this is to be considered for a version 1.0 release, it should be marked _ready for review_ by **Monday, 2024-06-03**

**Comment by maxwxyz** [comment]
@FEA-eng will you continue to work on this PR?

**Comment by marioalexis84** [comment]
This issue will have to wait a while to be properly resolved. In the current state of the code, only some workaround is possible. I have some modifications planned that will consequently resolve this.

**Comment by FEA-eng** [comment]
Closing this PR since, as Mario said, it will need a much more comprehensive solution.

**Pull request closed without merging**
