### PR TITLE
Fix of untranslated first document's name

### PR DESCRIPTION
**Pull request by Kuzma30**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by Kuzma30** [comment]
This is last variant to fix problem
Discussion here https://forum.freecadweb.org/viewtopic.php?f=10&t=69859&start=10
https://github.com/FreeCAD/FreeCAD/pull/7119
and here https://github.com/FreeCAD/FreeCAD/pull/6825 (this PR will be closed).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7156">pipeline status</a> for feature branch [PR_7156](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7156). Pipeline [584229415](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584229415) was triggered at [5d90ed9](https://github.com/FreeCAD/FreeCAD/pull/7156/commits/5d90ed9236c3c751b8a1ad27d81a80f9d2fc2bcf). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
See https://forum.freecadweb.org/viewtopic.php?p=609235#p609235

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7156">pipeline status</a> for feature branch [PR_7156](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7156). Pipeline [585272114](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/585272114) was triggered at [634f96e](https://github.com/FreeCAD/FreeCAD/pull/7156/commits/634f96e2192e81c6e9f727b686e5229b2c93ae48). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Kuzma30** [comment]
@wwmayer Please review with latest commit. Here I check how command run: simple newDocument(), newDocument("with some name"). Thus we have translation in one place. I think it's better than translate document name in all place where newDocument("Unnamed") used.

**Comment by wwmayer** [comment]
Looks basically OK to me now. But I have to think about some code simplifications in newDocument().

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7156">pipeline status</a> for feature branch [PR_7156](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7156). Pipeline [672835931](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/672835931) was triggered at [9f4b076](https://github.com/FreeCAD/FreeCAD/pull/7156/commits/9f4b07629fa8acc67b8f85da5b2a583f3827113b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7156">pipeline status</a> for feature branch [PR_7156](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7156). Pipeline [672839324](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/672839324) was triggered at [bb15e50](https://github.com/FreeCAD/FreeCAD/pull/7156/commits/bb15e5097bd31d8648a43169133001f2a57f5f71). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
