### PR TITLE
Base: Add ASCIIInputStream

### PR DESCRIPTION
**Pull request by chennes**
Based on the modifications to InputStream from the LinkStage3 fork. Needed for correct restoration of StringHasher.

### CODE REVIEW

**Comment by wwmayer** [comment]
IMO, the class name ASCIIInputStream (mainly the triple 'I') is a awful. The name TextInputStream would be nicer.

**Comment by chennes** [comment]
Works for me, I'll update it.

**Comment by wwmayer** [comment]
Thanks!

**Comment by bambukouk** [comment]
just tested again, using:

```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git) AppImage
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
```

and I still cannot open any files created in Link branch, using:

```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 2024.409.0.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at 20240407stable)
Hash: 973e4821bcd19a5a1af9ae3e1d2ed961aad0a8ab
Python 3.11.6, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: English/United Kingdom (en_GB)
```

without error message:
`12:41:50  Invalid Document.xml: recursive character stream`

so I don't know whether it never worked,
or something has changed?
or I am doing something wrong?

**Comment by rmu75** [comment]
have the same problem opening files created with link branch

`15:02:02  Invalid Document.xml: recursive character stream
`
```
OS: KDE neon 6.1 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38742 (Git)
Build type: Unknown
Branch: (HEAD losgelöst bei upstream/main)
Hash: b6599c5315ba557371dbdacca0b9cf35f5b7f7f2
Python 3.10.12, Qt 5.15.14, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Austria (de_AT)
```

(KDE neon is currently based on ubuntu 22.04)

**Pull request merged**
