### PR TITLE
[Sketcher] Only move one piece of B-spline when dragging

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
This is useful since splines can get very long.

fc-sketcher-move-piece

Not yet complete. Next steps include:
1. ~This currently doesn't work well with periodic B-splines.~ This is potentially fixed now. Could use more testing.
2. There should be options for both moving the entire B-spline or just one piece.

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
Marked as ready for review since it is working for periodic b-splines now.

**Comment by abdullahtahiriyo** [comment]
It looks really nice!! 

I hope to have some time over the weekend to review the code.

**Comment by abdullahtahiriyo** [comment]
Very nice. Thank you. Merged.

**Comment by AjinkyaDahale** [comment]
> Very nice. Thank you. Merged.

Glad you liked it. Please take a look at [the forum post on this](https://forum.freecadweb.org/viewtopic.php?f=9&t=69882&p=606360#p606360), because I suspect there would be people who would want it the old way.

**Comment by abdullahtahiriyo** [comment]
@AjinkyaDahale 

I am not sure if this renders impossible block dragging (by selection the poles). But, we could think of having both, maybe with a modifier key. 

Honestly, the functionality was so nice and useful that it is a clear improvement. If there is something we left behind, then we ask users for ideas on how to best get it back.

**Comment by AjinkyaDahale** [comment]
> I am not sure if this renders impossible block dragging (by selection the poles).

What is "block dragging"? I tried to select multiple elements and drag them together, but that didn't do anything.

**Comment by abdullahtahiriyo** [comment]
> What is "block dragging"? I tried to select multiple elements and drag them together, but that didn't do anything.

You are right. It is not possible anymore. 

We should probably have a way to drag as before ("as a block"). You may want to open a discussion on this topic in the forum. Let's see which ideas pop up.

**Comment by AjinkyaDahale** [comment]
> > What is "block dragging"? I tried to select multiple elements and drag them together, but that didn't do anything.
> 
> You are right. It is not possible anymore.

So was this possible before? Looking at the code, it doesn't look as straightforward to make multi-item drag possible. I may be wrong here.

> We should probably have a way to drag as before ("as a block"). You may want to open a discussion on this topic in the forum. Let's see which ideas pop up.

I had mentioned it in the forum post, but it appears it didn't have much traction. Probably something specific for multi-drag would help.

**Comment by AjinkyaDahale** [comment]
@abdullahtahiriyo 

> You may want to open a discussion on this topic in the forum. Let's see which ideas pop up.

See https://forum.freecadweb.org/viewtopic.php?f=8&t=70046.

**Pull request merged**
