### PR TITLE
FEM: make vtk objects

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

the one I had problems with in last PR in unit tests. Did not know I would fix it that fast :-)

cheers bernd

### CODE REVIEW

**Comment by wwmayer** [comment]
Apparently the travis builds for Linux doesn't have installed VTK which makes your unit tests to fail because types like Fem::FemPostPipeline are not available. So, it's best to move them into a try/except block.

**Comment by berndhahnebach** [comment]
Ahh didn't know about this. I will find some solution, but it will take some days since I'm on holidays for this week and the next week.

bernd

**Comment by sgrogan** [comment]
VTK is installed but the 14.04 version is too old (VTK 6.0)
See Here: https://github.com/FreeCAD/FreeCAD/blob/master/CMakeLists.txt#L702

**Comment by berndhahnebach** [comment]
I will remove the [on hold] if I have a solution I'm happy with. 

bernd

**Comment by wwmayer** [comment]
Any news?

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=10&t=32811&sid=831e6c2b5cc5f8d08c914e2626228401#p274430 and https://github.com/FreeCAD/FreeCAD/pull/1846  If 1846 is merged I will use the same code here to.

**Comment by berndhahnebach** [comment]
can be merged IMHO

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/1848

**Pull request closed without merging**
