### PR TITLE
Add pixi package manager support.

### PR DESCRIPTION
**Pull request by oursland**
[`pixi`](https://prefix.dev/) is a modern Python package manager that uses the `conda-forge` and PyPI packages.  Unlike similar previous package managers such as `conda` and `mamba`, `pixi` maintains a lock file to ensure version consistency. 
 In addition, `pixi` supports multiple environments, multiple OS and CPU architectures, and custom tasks similar to `npm` for NodeJS JavaScript.

Future work will extend this to support developers to build packages (`AppImage`, `.dmg`, and `.exe` installers) and eventually package version consistency between `FreeCAD-Bundle` packages and their development sources.

To build:

1. Install [`pixi`](https://prefix.dev/)
2. `pixi run configure`
3. `pixi run build -- -j 4` # where 4 is the number of parallel jobs.  Omit to set number of jobs equal to number of CPU cores.

To test:

1. `pixi run install`
2. `pixi run test` (does not fully work on Windows yet)

To run:

1. `pixi run freecad`

### CODE REVIEW

**Comment by oursland** [comment]
@looooo I have fixed the builds and submitted this PR.  As shown in the commits, you are attributed as the author and I as the committer.  Thanks for starting the work on the `pixi` PR!

**Comment by oursland** [comment]
Some aspects of test and run behave differently on Windows and may require additional work.  Of note, the binaries in `build/` do not seem to work correctly, but after they are installed with `pixi run -e qt6 install` the will work in the target environment.

**Comment by hyarion** [comment]
I tried it the other day on mac to test out qt6 and it worked flawlessly, great job!

I would like to suggest that this PR is split up into two though:
1. Adding pixi
2. Changing CI to use pixi

This way we can add support for pixi in trunk to allow people can test it out more easily, then change CI to use it (~week later?)

**Comment by mnesarco** [comment]
I am very optimistic about this, it can make the build process easier. I have tried it on Linux Mint 21.3 but unfortunately it put all my cores (12) to 100% and eats all memory (16GB + 2GB Swap) freezing the PC. I don't have this problem building in a Docker container.

**Comment by oursland** [comment]
@mnesarco In your case I would run the build command as: `pixi run -e qt6 build -- -j 4` to reduce the number of jobs to 4.  

Arguments following `--` are passed to the underlying `cmd`.  In this case the `cmd` is `cmake --build build`, so the resulting command is `cmake --build build -j 4`.

**Comment by oursland** [comment]
Qt5 support has been dropped.   There is only the default environment, which is Qt6.

I would prefer to keep the CI included here.  The existing Conda CI tasks are unstable, which is why Windows Conda has been disabled.  `pixi` is a statically linked Rust binary that replaces the clunky, error-prone C++ and Python `mamba` that often breaks when updating a dependency on Windows and may also be the source of the spurious macOS errors.

**Comment by oursland** [comment]
That's a strange error that seems to suggest a file was somehow deleted.  Try `rm -rf .pixi` and re-running the build command, which will re-install the environment.

**Comment by mnesarco** [comment]
build worked:

```
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.39420 (Git) Conda
Build type: Release
Branch: pixi
Hash: a88aee02429ce535a17d52750a8a9b52f6b463f5
Python 3.12.0, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * DynamicData 2.62.0
  * MnesarcoUtils 0.2.14
  * sheetmetal 0.4.25
  * A2plus 0.4.67
  * fcscript 0.0.1
  * asm4 0.50.7
  * ProDarkThemePreferencePack 1.0.0
  * Marz 0.1.15
  * OpenTheme 2024.9.1

```

But:
- No thumbnails for some reason

image


Empty 3D View, i have tried opening old files and creating new ones, nothing works, 3D view is always empty

image

**Comment by oursland** [comment]
Hi @mnesarco 

1. The thumbnail issue was a bug on `main` from which this PR was branched.  The fix was [merged today](https://github.com/FreeCAD/FreeCAD/pull/18270).  I'll push a rebased commit.
2. I am unsure what would be causing the 3D view to not render properly.  It is working for me.  I'll try a build on a Mint 21.3 VM.

**Comment by mnesarco** [comment]
Is it possible that the thumbnail bug have corrupted the thumbnails? the buggy code opened the file stream for output instead of input, maybe it truncated the files. I pulled your latest and rebuild and no thumbnails.

In my machine, the pixi build task takes a huge amount of RAM, not like my normal build env. In my normal env I use clang instead of gcc, do you think that it could be the cause?

**Comment by oursland** [comment]
I am unsure what the cause of high memory usage may be.  Have you identified which processes are consuming the RAM?

On my VM with 8 cores and 16 GiB of RAM, my RAM utilization is under 8 GiB during full compilation:

image

**Comment by oursland** [comment]
The Mint 21.3 build completed.  The thumbnails load correctly, which is expected as the fix is in this build.  The 3D window is also rendering correctly:

image

**Comment by mnesarco** [comment]
There must be something in my environment then. I have tried 5 times.... First 3 crashed my PC, then something was corrupted in .pixi, then everything compiled but no thumbnails and no 3D View.... My Docker based env, has no issues so it may be something in my non containerized host.

**Comment by mnesarco** [comment]
There is another difference, my docker build env uses qt5 not qt6.

**Pull request merged**
