### PR TITLE
[0.17 bugfix] Fix Surface.Filling crashing on bad boundary edges input

### PR DESCRIPTION
**Pull request by tomate44**
As stated in the [OCCT BRepFill_Filling doc](https://www.opencascade.com/doc/occt-7.2.0/refman/html/class_b_rep_fill___filling.html) : 
"The constraints defining the bound of the face have to be entered in order to have a continuous wire."

This was not checked and leaded to FC crashing on bad boundary edges order.
This fix prevents it by trying to add the edges to a test wire before to add them to the filling algo.

Nothing is done in the GUI side, however.
It would be good to be able to filter the selection of the boundary edges directly in the GUI, in the future.

Also, I didn't destroy the test wire, as I don't know if it is needed.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by tomate44** [comment]
Really ?
Anytime I try to select a boundary edge that is not connected to the previous ones, I get a crash.
This has always happened to me, from the very beginning I used this tool.
For example : 
- draw 2 UNCONNECTED arc-of-circle in Draft
- SurfaceWB / Filling tool
- Add edges
- first arc : OK
- second arc -> crash
I attach my FreeCAD.log
Maybe this is a local problem with my own OCC / FC builds ?

OS: Ubuntu 17.10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13491 (Git)
Build type: Unknown
Branch: master
Hash: ba3fb75b48962f4b78c6e3ebdebf3965e35aa1e4
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: French/France (fr_FR)

[FreeCAD.log](https://github.com/FreeCAD/FreeCAD/files/1868426/FreeCAD.log)

**Comment by wwmayer** [comment]
> Really ?

Yes. My OCC version is 7.0.0.

**Comment by normandc** [comment]
I confirm the crash with OCCT 7.2.0. I built FreeCAD using OCCT deb packages I compiled to be used for the Ubuntu freecad-stable PPA when 0.17 is officially released. https://launchpad.net/~gemnoc/+archive/ubuntu/ppa

Will test next with OCCT 7.1.0.

OS: Ubuntu 16.04.4 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13487 (Git)
Build type: Unknown
Branch: master
Hash: 63e8b134ac8536b60784863ccbbca25d3cc7a3e1
Python version: 2.7.12
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: French/Canada (fr_CA)

**Comment by normandc** [comment]
Also getting a crash with the freecad-daily package.

OS: Ubuntu 16.04.4 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13483 (Git)
Build type: None
Branch: master
Hash: 0ac32464e45fa9648cdaf702ebda06650dabe9dc
Python version: 2.7.12
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: French/Canada (fr_CA)

**Comment by wwmayer** [comment]
OK, merged.

**Comment by tomate44** [comment]
Thanks.

**Pull request closed without merging**
