### PR TITLE
TechDraw: Smart dimension tool

### PR DESCRIPTION
**Pull request by PaddleStroke**
Implement a smart dimension tool similar to Sketcher_Dimension. Fixes https://github.com/FreeCAD/FreeCAD/issues/12370
Please test and feedback.

By default it is set to both smart dimension + old tools. See preference in TechDraw/Dimension. If you select 'single tool' then it looks like this : 
image

- also improve the 'arc length' tool so that it works with any kind of geometries : Arc of ellipse / bspline ... making ExtensionArcLengthAnnotation kind of useless. Though that tool works with multiple edges but as it does not show where it starts and end that wouldn't be very helpful.

- Implement Area dimension. (current tool is balloon not a real dimension)

### CODE REVIEW

**Comment by luzpaz** [comment]
Trailing whitespace lint issues: 

```
Warning: src/Mod/TechDraw/Gui/CommandCreateDims.cpp:359:                    // if sel face and not allowed, then a dimension is being created <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/CommandCreateDims.cpp:466:    <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/CommandCreateDims.cpp:512:    } <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/CommandCreateDims.cpp:522:        <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/CommandCreateDims.cpp:588:    <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/CommandCreateDims.cpp:908:        <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/CommandCreateDims.cpp:2323:}   <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui:527:           <string>Controls the size of gap between dimension point and start of extension line for ISO dimensions. <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui:528:Value * linewidth is the gap. <-- trailing whitespace
Warning: src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui:548:           <string>Controls the size of gap between dimension point and start of extension line for ASME dimensions. Value * linewidth is the gap. <-- trailing whitespace
```

**Comment by maxwxyz** [comment]
Does it need a preselection?
You could use the dimension icon from sketcher in yellow for this tool.

**Comment by PaddleStroke** [comment]
It actually currently do not work with preselection. Let me fix that.
And yes good idea for the icon I'll do that.

**Comment by PaddleStroke** [comment]
I have also integrated arc length now.
Next on my list : 
- Land mark dimension
- Area
- Edge length
- Cascade maybe.

**Comment by WandererFan** [comment]
If you mean "landmark dimension", I'm not sure if that is widely used.  It was an early attempt to mitigate TNP for dimensions.  I'd leave it out for now.

Would like a proper Area Dimension.  The one in the Extension tools is a static annotation that doesn't get updated when the face changes.  I don't think it handles holes properly either.

I don't have a need for edge length, but some might.

**Comment by WandererFan** [comment]
Note that the chain & ordinate dimensions in the  Extension tools (red icons) have issues with proper alignment and updating.  Making a proper "dimension group" for related dims is on my todo list and has been for a long time.

**Comment by PaddleStroke** [comment]
Ok, I'm creating an area dimension now then.

**Comment by PaddleStroke** [comment]
image

**Comment by pierreporte** [comment]
@PaddleStroke Arrows pointing in an area should end by a bullet by default. Pointed arrows are only for lines and points.

**Comment by WandererFan** [comment]
Missing an include for QTimer?  Also some warnings about unused variables.

**Comment by PaddleStroke** [comment]
@WandererFan thanks I fixed those. I'll check the CI when its done to make sure there are no more things.

@pierreporte that would need (potentially) a substantial amount of additional work. So can you discuss with DWG to make sure every one agree and offer a mockup for the shape. Thanks

**Comment by pierreporte** [comment]
@PaddleStroke This is standard drawing practice, not UI/UX. In *Guide du dessinateur industriel* (A. Chevalier), there is the following example in the common mistakes section. TechDraw already has an acceptable dot terminal available (it could be a bit smaller though to match arrow heads width).

image

**Comment by maxwxyz** [comment]
can confirm @pierreporte

**Comment by maxwxyz** [comment]
@PaddleStroke Point and arrow are defined in ISO 129-1
grafik

**Comment by PaddleStroke** [comment]
Got it its clear enough. Well I'll try to pack this in this PR then.

**Comment by PaddleStroke** [comment]
Ok it was not too hard to change to point actually.
I also fixed an issue with the US units that were wrong (see above screenshow showing 145 in² instead of 5)
image

**Comment by maxwxyz** [comment]
@PaddleStroke I think default to single tool as it is also in sketcher is good, if all tools in the group are possible with the new tool. Saves a lot of toolbar space and you still have all tools in the dropdown.

**Comment by PaddleStroke** [comment]
The default is very easy to change, it's like 2 lines of code to change. And for early stage of the tool I prefer to let as separate to avoid having to deal with haters. When its confirmed to be stable anyone can change the default by a tiny PR.

**Comment by maxwxyz** [comment]
I'm fine with that but should be set as default for the 1.0 IMO

**Comment by PaddleStroke** [comment]
Conflicts solved @yorikvanhavre

**Comment by yorikvanhavre** [comment]
I'll let @WandererFan press the button ;)

**Comment by FEA-eng** [comment]
It's a great tool. Will it support thickness in the future (when I press M when adding area annotation, nothing happens)?

**Comment by PaddleStroke** [comment]
What is thickness? Is there already a thickness dimension tool?
Is it extent? Should a face selection offer the extent as a mode?

**Comment by FEA-eng** [comment]
> What is thickness? Is there already a thickness dimension tool? Is it extent? Should a face selection offer the extent as a mode?

I mean what pierreporte showed here: https://github.com/FreeCAD/FreeCAD/pull/13525#issuecomment-2072878133

Currently, it has to be added manually as an annotation. It would be nice to have it as a mode for face selection (in addition to area) but the problem is that the value may vary even for a single face and it might be difficult to compute it. But the mode could only consider faces with constant thickness (3rd dimension).

Perhaps I should create a feature request for this.

**Comment by pierreporte** [comment]
@FEA-eng I think it should show the distance at the selected point. This kind of dimension shouldn’t be used for variable thicknesses anyway. It could change value when the point is modified. The point could be attached to a cosmetic point if a precise location is needed.

**Comment by FEA-eng** [comment]
> @FEA-eng I think it should show the distance at the selected point. This kind of dimension shouldn’t be used for variable thicknesses anyway. It could change value when the point is modified. The point could be attached to a cosmetic point if a precise location is needed.

Right, the thickness where the user clicks will be sufficient. I made a new request to document this: #14012

**Comment by belinski-roman** [comment]
> Теперь я также интегрировал длину дуги. Также можно добавить:
> 
> * ориентир?
> * Площадь?
> * Длина кромки ?

elevation marks for architectural drawings
image021

**Comment by belinski-roman** [comment]
The default hotkey for this tool should be assigned the same as in Sketcher - "D"

**Comment by maxwxyz** [comment]
please create new issues and describe the problem there. TIA

**Comment by Reqrefusion** [comment]
@PaddleStroke [TechDraw_Dimension_Pointer.svg](https://github.com/FreeCAD/FreeCAD/pull/13525/files#diff-077bf0f5b587694b754a6b1c548179d3ab3c28df729f6bd3bde9471f03b61201) and [TechDraw_Dimension_Pointer.svg](https://github.com/FreeCAD/FreeCAD/pull/13525/files#diff-077bf0f5b587694b754a6b1c548179d3ab3c28df729f6bd3bde9471f03b61201) What is the difference? Same icons but sized differently. Is this nuance difference meaningful?

**Comment by maxwxyz** [comment]
@Reqrefusion pointer is the cursor icon which is shown when the tool is active.

**Comment by PaddleStroke** [comment]
The cursor has a small white cross that acts as the mouse pointer.

**Comment by maxwxyz** [comment]
@Cobras62 did you test this, it's fine?
https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by Cobras62** [comment]
@maxwxyz : yes it is this version that I tested.  But the white cross on the white background is difficult to see.  Just look at the animation that presents this tool in the 1.0 releases notes and we realize that the white cross is not obvious :)

**Comment by PaddleStroke** [comment]
It's true the cross is white as in sketcher.
Actually it's set by a preference I seem to recall.
But yes it should not be white but black as techdraw is white background

**Comment by maxwxyz** [comment]
Ob my system it looks dark gray.

**Comment by Cobras62** [comment]
@PaddleStroke : ok thanks for this info :)
In any case, this future v1.0 and these new tools are a great piece of work !
Well done to everyone !

**Comment by Cobras62** [comment]
@maxwxyz : A friend who works in a design office has tested it and it's white for him too. We're both running Windows 11.

**Comment by PaddleStroke** [comment]
I just checked and the color is indeed a preference.
```
    ParameterGrp::handle hGrp =
        App::GetApplication().GetParameterGroupByPath("User parameter:BaseApp/Preferences/View");
    color = hGrp->GetUnsigned("CursorCrosshairColor", color);
```

It is currently defined in the shared class ToolHandler, which is shared between sketcher and techdraw. So we need to change this to have separate colors. Please open an issue I'll do this later.

**Comment by Cobras62** [comment]
@PaddleStroke : I've just opened an issue. It's the first time I've done it, I hope I haven't done anything wrong ^^.

**Pull request merged**
