### PR TITLE
FEM-ResultShow (task panel) saves and restores user defined equations…

### PR DESCRIPTION
**Pull request by UR-0**
… into/from result object

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by UR-0** [comment]
forums discussion: https://forum.freecadweb.org/viewtopic.php?f=18&t=42425&p=367390#p367390

**Comment by berndhahnebach** [comment]
Werner, would you have a view on this from security point of view. We would save python code in an attribute which will be evaluated with eval. But only on user action. AFAIK the code will not be evaluated just because the file is  opened. 

How it works ... Open and run the Standard FEM 3D example by 

`
from femexamples.manager import *
doc = run_ccx_cantileverfaceload()
`

double click on the result obj. and add something inside the User defined equation, calculate the plot and  close the dialog. The evaluated code will be saved in the new attribute. Inside this user diefined equation could be any valid Python code. 

cheers bernd

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=13&t=41072&start=10
similar problem disscussed in German.

**Comment by wwmayer** [comment]
> https://forum.freecadweb.org/viewtopic.php?f=13&t=41072&start=10
similar problem disscussed in German.

This is not an issue because just saving Python code inside a project is not per-se bad. It can be a security problem when it gets executed without the user's knowledge.

Now, the code of this PR is indeed problematic because combining arbitrary Python code with eval is a bad thing.

In the text field I could enter this:
__import__('PySide').QtGui.QMessageBox.warning(None, 'Security issue', 'Security issue')

and when pressing the Calculate & Plot button the message popped up. Afterwards eval() raises an exception because its content is of the wrong type but that's irrelevant because the code is already executed and then it's too late.
Imagine that here you can add really dangerous stuff like deleting files. For example:
https://stackoverflow.com/questions/9383740/what-does-pythons-eval-do
=> eval("__import__('os').remove('file')")

**Pull request closed without merging**
