### PR TITLE
Part: Fix getIcon() of several view providers to return full path nam…

### LINKED ISSUE #18595: Feature icons show generic cube after restarting FreeCAD
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When creating a new file in 1.0 with features from the Part WB, most of the icons in the treeview are replaced by a generic cube when restarting FreeCAD again.

Example (Check Slice or Compound filter icons):
grafik

When saving the file, closing FreeCAD and opening FreeCAD again, those icons are gone:
grafik

So it is really hard to quickly glance what object is which feature.
This also happens when files are opened across different computer and OS, verified on macOS too.

@FreeCAD/design-working-group FYI

Here is the file:

[part-features.zip](https://github.com/user-attachments/files/18180900/part-features.zip)

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * CfdOF 1.29.4
  * CurvedShapes 1.0.13
  * Curves 0.6.52
  * dodo 1.0.1
  * fasteners 0.5.33
  * freecad.gears 1.3.0
  * FreeCAD_SketchArch
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.26
  * Rocket 4.0.1
  * sheetmetal 0.6.2
  * Silk 0.1.5
```

### Subproject(s) affected?

Part

### Anything else?

Happening also in weekly:

```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39673 (Git) Conda
Build type: Release
Branch: main
Hash: 1289997dfd604cb24f060f905f04ec3728d964e4
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * CfdOF 1.29.4
  * CurvedShapes 1.0.13
  * Curves 0.6.52
  * dodo 1.0.1
  * fasteners 0.5.33
  * freecad.gears 1.3.0
  * FreeCAD_SketchArch
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.26
  * Rocket 4.0.1
  * sheetmetal 0.6.2
  * Silk 0.1.5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wwmayer**
…e of the icon file

Fixes #18595

### CODE REVIEW

**Comment by maxwxyz** [comment]
CI seems to fail on most OS.

**Comment by wwmayer** [comment]
Should be fixed now.

**Comment by adrianinsaval** [comment]
This is ok to backport right?

**Comment by adrianinsaval** [comment]
cherry-pick 9040a14d7b068ed42b404e4700cb9a8579629159

**Pull request merged**
