### PR TITLE
Assembly: Add 'Angle', 'Perpendicular' and 'Parallel' joints.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Add 'Angle', 'Perpendicular' and 'Parallel' joints.
image

### CODE REVIEW

**Comment by qewer33** [comment]
Shouldn't the distance joint also be grouped together (the separators) with these in the toolbar?

**Comment by maxwxyz** [comment]
> Shouldn't the distance joint also be grouped together (the separators) with these in the toolbar?

Agreed, they seem so similar, maybe even group them in a command group?

**Comment by PaddleStroke** [comment]
Moving the separator is ok I guess. I wouldn't group them though.
I thought about grouping perpendicular and parallel under angle. But then thought otherwise. If we have them at all then it doesn't make much sense to group them.

**Comment by PaddleStroke** [comment]
@chennes rebased conflict solved

**Comment by FEA-eng** [comment]
Since the previous experimental features are now exposed (which is IMO very good), will those new constraints be exposed as well? I hope so because they are essential, should be normally available in 1.0 and are working well (I tested them yesterday).

P.S. Is the pre-commit.ci failure a bad sign or nothing special?

**Comment by chennes** [comment]
This is ready for merge pending pre-commit fix.

**Comment by PaddleStroke** [comment]
Precommit fixed. Apparantly black missed an extra empty line last time. Now it picked it up. Dunno why

**Pull request merged**
