### PR TITLE
Correct usage of SOURCE_DATE_EPOCH

### PR DESCRIPTION
**Pull request by kkremitzki**
Followup from #3190. I had checked that the previous change was making the package reproducible, but it was actually because the date was getting set to the string `ENV{SOURCE_DATE_EPOCH}` instead of the value as expected.

### CODE REVIEW

**Comment by eszlari** [comment]
I still question the original change. Why should `file(TIMESTAMP ...` not be reproducible?

**Comment by eszlari** [comment]
And if you don't think that `file(TIMESTAMP ...`, you can set the date yourself:
```
$ cmake -DAPPDATA_RELEASE_DATE=YYY-MM-DD ...
```

**Comment by kkremitzki** [comment]
> Why should file(TIMESTAMP ... not be reproducible?

Because it depends on the modification time of `CMakeLists.txt` which can change when patched as part of the package build process.

**Comment by wwmayer** [comment]
Ready to merge?

**Comment by kkremitzki** [comment]
Yes, please go ahead and merge, as without this change we have a bad appdata XML for the freecad-daily PPA.

**Comment by eszlari** [comment]
> > Why should `file(TIMESTAMP ...` not be reproducible?
> 
> Because it depends on the modification time of `CMakeLists.txt` which can change when patched as part of the package build process.

Then I would remove the `file(TIMESTAMP ...)` else-branch completely.

**Comment by kkremitzki** [comment]
The only reason I didn't was that we have CMake 3.3 as a minimum version here:
https://github.com/FreeCAD/FreeCAD/blob/master/CMakeLists.txt#L1

That might be able to be updated, I just checked Ubuntu 16.04 for example and that provides CMake 3.5, but still not enough to fully remove the old branch as far as I can tell.

**Comment by eszlari** [comment]
If you consider `file()` to be non-deterministic anyway, then what the difference to using a non-deterministic, pre-3.8 `string()`?

**Comment by kkremitzki** [comment]
The thing that gives me pause is this snippet from the CMake < 3.8 `string(TIMESTAMP ...)` docs:

> Should the command be unable to obtain a timestamp the output variable will be set to the empty string “”.

which seems worse. With the `file(TIMESTAMP ...)` section we are at least guaranteed to get a timestamp, which, while not necessarily reproducible, will still be a relevant/non-garbage piece of data.

**Pull request merged**
