### PR TITLE
Cond parens

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
This PR replaces https://github.com/FreeCAD/FreeCAD/pull/4740

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9054">pipeline status</a> for feature branch [PR_9054](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9054). Pipeline [817953752](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/817953752) was triggered at [ee34c6d](https://github.com/FreeCAD/FreeCAD/pull/9054/commits/ee34c6d7110e60d92cb6b96bc737074ed250374e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Ubuntu 22.04 build fails with
```
[  1%] Linking CXX static library libfmt.a
fatal: Invalid revision range 7d8e53aaab17961d85c5009de34f69f2af084e8b..HEAD
git
/home/runner/work/FreeCAD/FreeCAD/build/src/Build/Version.h.out written
```

**Comment by 0penBrain** [comment]
> Ubuntu 22.04 build fails with
> 
> ```
> [  1%] Linking CXX static library libfmt.a
> fatal: Invalid revision range 7d8e53aaab17961d85c5009de34f69f2af084e8b..HEAD
> git
> /home/runner/work/FreeCAD/FreeCAD/build/src/Build/Version.h.out written
> ```

Nope this wasn't the error. :smile: This one is always here, it is triggered by the Python script that tries to get the revision (something like `SubWCrev.py`). I have to tackle this later, but it's not a problem for building.
The error (pretty weird) is this:
```
[ 37%] Copying /home/runner/work/FreeCAD/FreeCAD/src/Mod/Start/InitGui.py to /home/runner/work/FreeCAD/FreeCAD/build/Mod/Start/InitGui.py
Error copying file "/home/runner/work/FreeCAD/FreeCAD/src/Mod/Start/InitGui.py" to "/home/runner/work/FreeCAD/FreeCAD/build/Mod/Start/InitGui.py".
gmake[2]: *** [src/Mod/Start/CMakeFiles/StartTests.dir/build.make:87: Mod/Start/InitGui.py] Error 1
gmake[2]: *** Deleting file 'Mod/Start/InitGui.py'
gmake[1]: *** [CMakeFiles/Makefile2:6027: src/Mod/Start/CMakeFiles/StartTests.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```
I re-run the failed job. We'll see.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9054">pipeline status</a> for feature branch [PR_9054](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9054). Pipeline [818247155](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818247155) was triggered at [8a91418](https://github.com/FreeCAD/FreeCAD/pull/9054/commits/8a914182236f3b88aaf16057843036afb54a7fb1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
It makes sure that the expressions are identical: `=(1 == 1) ? 1 : 0'` and `=1 == 1 ? 1 : 0'`

**Pull request merged**
