### PR TITLE
Qt6 port

### PR DESCRIPTION
**Pull request by wwmayer**
Fix deprecation warnings with version 6.3 or 6.4

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by chennes** [comment]
This PR resolves those deprecation warnings for me. FYI, when compiling against 6.6.0a1 I get a new deprecation. Here is an example:
```
/home/chennes/FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherElements.cpp:1083:13: warning: ‘constexpr typename std::add_const<_Tp>::type& qAsConst(T&) [with T = QToolButton*; typename std::add_const<_Tp>::type = QToolButton* const]’ is deprecated: Use std::as_const() instead. [-Wdeprecated-declarations]
 1083 |     qAsConst(ui->filterButton)->addAction(action);
      |     ~~~~~~~~^~~~~~~~~~~~~~~~~~
/media/chennes/Qt/qt6-install/include/QtCore/qttypetraits.h:50:45: note: declared here
   50 | constexpr typename std::add_const<T>::type &qAsConst(T &t) noexcept { return t; }
      |                                             ^~~~~~~~
```

**Comment by wwmayer** [comment]
TBH I don't understand the use of qAsConst in this context which was added with 15dd77512eb582.
IMO, it should be removed here.

**Comment by wwmayer** [comment]
@chennes 
What about the line: `qAsConst(ui->filterButton)->addAction(action);` ? Shouldn't we replace it with `ui->filterButton->addAction(action);`

Btw, the same line occurs in TaskSketcherConstraints::TaskSketcherConstraints

**Comment by chennes** [comment]
Yes, I figured we'd do the forward-looking deprecations in a separate PR -- what we have now should work fine with Qt 6.4, I was testing on a version of 6.6 from git in my comment above.

**Pull request merged**
