### PR TITLE
Fix #3477 Unintended Delete (revised)

### PR DESCRIPTION
**Pull request by WandererFan**
This is a revision of the previous PR.  Messages for inactive and linked objects at delete time are now presented together, once per document.
----------------------------------------------------------------------------------------------------------------
This PR is a fix for  [issue #3477](https://www.freecadweb.org/tracker/view.php?id=3477) which involves an unintended DocumentObject deletion when multiple documents are open.  Please merge.
Thanks,
wf

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
This PR shows one annoying behaviour. In case you have selected many objects in a non-active document and press Del then the message box appears for every single object.
IMO, it suffices to show the message box only once asking the user to either delete all objects of all non-active documents or nothing.

**Comment by WandererFan** [comment]
The check for "Object dependencies" is document by document.  Do you want that changed to only once for all documents too?   Best to have both checks the same.

**Comment by wwmayer** [comment]
> The check for "Object dependencies" is document by document.

The current behaviour of this PR is that if you have e.g. two documents and selected 10 objects of the inactive document the message box appears 10 times.

> Do you want that changed to only once for all documents too?

I don't mind if showing the message box only once or per document. The likelihood that a user has selected 10 objects in 10 different documents is extremely low.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
