### PR TITLE
Trailing comments will mess up format if extend beyond 100 columns

### PR DESCRIPTION
**Pull request by berniev**
https://forum.freecad.org/viewtopic.php?t=72183&start=60

An issue has been identified that long lines with trailing comments will get messed up with format. They still work ok - just look wrong.

This is an experiment to move comments that extend beyond 100 columns back to the previous line.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8790">pipeline status</a> for feature branch [PR_8790](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8790). Pipeline [800737476](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/800737476) was triggered at [cdd06af](https://github.com/FreeCAD/FreeCAD/pull/8790/commits/cdd06af30cd3370ec0772d33e2a7d6366e5f565a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Also the commit title doesn't represent the sweeping changes this PR makes + has a typo (s/commits/comments)

Screenshot_20230309_080532

**Comment by berniev** [comment]
No it doesn't make sense to change 3rd party stuff. They should have been skipped!

Main point was to see if it could be done to discover/fix those lines and to get a handle on the scale of the problem. 

I could get regex working to locate those lines but then it was a long manual process going through several thousand candidates. There must be a better way!

I'll mark this Draft to avoid confusion. Should likely have done that in the first place.

The edit to the title of this PR shows the editor doesn't understand the problem originally described, and I am reverting. And I cannot get excited about the odd spelling mistake when there is serious work to be done.

**Comment by luzpaz** [comment]
> And I cannot get excited about the odd spelling mistake when there is serious work to be done.

It's a little bit more nuanced then that. An enormous collaborative multifaceted projects such as freecad, maintaining a certain order and coherence is important. That is serious, maybe not on the immediate short term but big picture for sure especially as more people get involved. Your work is appreciated, please don't take offense. The request is to be mindful.

**Comment by berniev** [comment]
Claeaning up ...

**Pull request closed without merging**
