### PR TITLE
Codespell: skip *.svg + add more ignored words

### PR DESCRIPTION
**Pull request by Floriansimmer**
@luzpaz after this pr these errors remain over in the whole sourcecode. To me it looks like real spelling mistakes. Should I also put these spelling mistakes on the ignore list or do we correct them? 
In the second commit are all possible words that can be removed because they don't report an misspelling 

 ```
~/Git-Projekte/FreeCAD/FreeCAD codespell --check-filenames --skip './.git,*.po,*.ts,*.svg,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/Mod/Robot/App/kdl_cp,./src/Mod/Import/App/SCL,./src/WindowsInstaller,.src/Doc/FreeCAD.uml,./build' --ignore-words .github/codespellignore -s
./src/Tools/wiki2qhelp.py:82: convertor ==> converter
./src/Tools/wiki2qhelp.py:82: convertor ==> converter
./src/Tools/wiki2qhelp.py:82: Convertor ==> Converter
./src/Tools/wiki2qhelp.py:221: convertor ==> converter
./src/Tools/wiki2qhelp.py:229: convertor ==> converter
./src/Mod/Cloud/App/AppCloud.h:73: paramters ==> parameters
./src/Mod/Arch/ArchWall.py:905: entires ==> entries
./src/Mod/Arch/ArchWall.py:906: entires ==> entries
./src/Mod/Arch/ArchWall.py:907: entires ==> entries
./src/Mod/Arch/ArchWall.py:918: entires ==> entries
./src/Mod/Arch/ArchWall.py:921: entires ==> entries
./src/Mod/Arch/ArchWall.py:926: entires ==> entries
./src/Mod/Arch/Presets/pset_definitions.csv:26: Impedence ==> Impedance
./src/Mod/Fem/femsolver/z88/tasks.py:110: Vektor ==> Vector
./src/Mod/Fem/femsolver/z88/tasks.py:110: Vektor ==> Vector
./src/Mod/TechDraw/App/AppTechDrawPy.cpp:898: detet ==> detect, delete
./src/Mod/Robot/App/TrajectoryDressUpObject.cpp:88: Accelaration ==> Acceleration
./src/Mod/Robot/App/Trajectory.cpp:187: Accelaration ==> Acceleration
./src/Mod/Robot/App/Trajectory.cpp:215: Accelaration ==> Acceleration
./src/Mod/Robot/App/Robot6Axis.h:85: Actuall ==> Actually, actual
./src/Mod/Robot/App/Waypoint.h:57: accelaration ==> acceleration
./src/Mod/Robot/App/Waypoint.h:73: Accelaration ==> Acceleration
./src/Mod/Robot/App/TrajectoryObject.cpp:42: Actuall ==> Actually, actual
./src/Mod/Robot/App/WaypointPyImp.cpp:137: Accelaration ==> Acceleration
./src/Mod/Robot/App/WaypointPyImp.cpp:139: Accelaration ==> Acceleration
./src/Mod/Robot/App/Waypoint.cpp:63: accelaration ==> acceleration
./src/Mod/Robot/App/Waypoint.cpp:71: Accelaration ==> Acceleration
./src/Mod/Robot/App/Waypoint.cpp:71: accelaration ==> acceleration
./src/Mod/Robot/App/Waypoint.cpp:82: Accelaration ==> Acceleration
./src/Mod/Robot/App/Waypoint.cpp:110: Accelaration ==> Acceleration
./src/Mod/Robot/App/Waypoint.cpp:142: Accelaration ==> Acceleration
./src/Mod/Robot/App/Robot6Axis.cpp:79: Actuall ==> Actually, actual
./src/Mod/Robot/App/Robot6Axis.cpp:187: Actuall ==> Actually, actual
./src/Mod/Robot/App/Robot6Axis.cpp:222: Actuall ==> Actually, actual
./src/Mod/Robot/App/Robot6Axis.cpp:243: Actuall ==> Actually, actual
./src/Mod/Robot/App/Robot6Axis.cpp:247: Actuall ==> Actually, actual
./src/Mod/Robot/App/Robot6Axis.cpp:270: Actuall ==> Actually, actual
./src/Mod/Robot/App/Robot6Axis.cpp:282: Actuall ==> Actually, actual
./src/Mod/Robot/App/Robot6Axis.cpp:288: Actuall ==> Actually, actual
./src/Mod/Robot/Gui/TaskTrajectory.cpp:84: Accelaration ==> Acceleration
./src/Mod/Robot/Gui/TrajectorySimulate.cpp:82: Accelaration ==> Acceleration
./src/Doc/Document.mm:37: wile ==> while
./src/Gui/Application.h:227: singelton ==> singleton
./src/Base/PyExport.h:216: handels ==> handles
./src/Base/PyExport.h:221: handels ==> handles
./src/Base/StackWalker.cpp:308: archtitecture ==> architecture
./src/Base/Interpreter.cpp:592: Singelton ==> Singleton

-------8<-------
SUMMARY:
accelaration 15
archtitecture 1
convertor     5
entires       6
handels       2
impedence     1
paramters     1
singelton     2
vektor        2
wile          1
```

### CODE REVIEW

**Comment by chennes** [comment]
Is there a better codespell action we can use? I don't know about on GitHub, but the one I use in Vim recognizes camelcase, for example, which would eliminate a lot of these inclusions. If the exclude dictionary gets too long we'll start missing real misspellings because they overlap with some random variable name.

**Comment by Floriansimmer** [comment]
One possible program I know of would be https://github.com/marketplace/actions/check-spelling (Microsoft Powertoys uses it), but I haven't tried it yet, but it looks promising. I will give it a try.

I have used Codespell in the past, and in my private repo its working well, that's why I used it as an action.

**Comment by luzpaz** [comment]
We could also improve codespell :blush:  
https://github.com/codespell-project/codespell/issues/196

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5338">pipeline status</a> for feature branch [PR_5338](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5338). Pipeline [443189944](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/443189944) was triggered at [d864681](https://github.com/FreeCAD/FreeCAD/pull/5338/commits/d8646819038622698b052d5a4bba43b6cb3cd2e4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Please merge this regardless of the false positives ?

**Comment by chennes** [comment]
It is still marked as a draft, I can merge it when it is marked ready.

**Comment by Floriansimmer** [comment]
I tested the github action i mentioned above, at 2nd glance it is not as promising as i thought after all. 
2 reasons: 
- codespell uses a dictionary of misspelled words and the possible corrections. This means that there are inherently few false positives.
Check-spelling uses a dictionary with correct words, which means that all special words, abbreviations, etc. would have to be included in a list of allowed words. In the case of FreeCAD this is about 10000 different words with several regex, which is hard to do, because CamelCase etc. is not everywhere.
- codespell is a command line program. Anyone can use it locally.

**Pull request merged**
