### PR TITLE
Add uncoupled temp-disp and heat transfer CalculiX FEM analysis types

### LINKED ISSUE #11646: [Feature Request] Support for pure heat transfer analyses in FEM with CalculiX
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FEM workbench currently supports thermo-mechanical analyses with CalculiX. In most cases, they are sufficient even if only the thermal part is of interest. But sometimes this approach may lead to issues: https://forum.freecad.org/viewtopic.php?f=18&t=66259

Thus, it would be good to support pure heat transfer simulations with CalculiX as well.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35274 (Git)
Build type: Release
Branch: main
Hash: dc063eabec61bffc72c92595c66a4649f25fe381
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
fixes #11646 and also adds uncoupled temp-disp analysis type

a new property `Thermo Mech Type` is added; by default, it's set to `coupled` - nothing changes, but it can be also set to `uncoupled` (then the analysis type is uncoupled temperature-displacement) or `pure heat transfer` (then the analysis type is heat transfer)

### CODE REVIEW

**Comment by FEA-eng** [comment]
@marioalexis84 Could you take a look at this? The input file is written properly and the analysis is submitted but when it's set to `pure heat transfer`, there's an error on reading results:

```
15:29:39  Running the Python command 'FEM_SolverRun' failed:
Traceback (most recent call last):
  File "/home/ubuntu/Documents/squashfs-root/usr/Mod/Fem/femcommands/commands.py", line 1174, in Activated
    run_fem_solver(self.selobj)
  File "/home/ubuntu/Documents/squashfs-root/usr/Mod/Fem/femsolver/run.py", line 108, in run_fem_solver
    fea.run()  # standard, no working dir is given in solver
    ^^^^^^^^^
  File "/home/ubuntu/Documents/squashfs-root/usr/Mod/Fem/femtools/ccxtools.py", line 688, in run
    self.load_results()
  File "/home/ubuntu/Documents/squashfs-root/usr/Mod/Fem/femtools/ccxtools.py", line 808, in load_results
    self.load_results_ccxfrd()
  File "/home/ubuntu/Documents/squashfs-root/usr/Mod/Fem/femtools/ccxtools.py", line 818, in load_results_ccxfrd
    importCcxFrdResults.importFrd(
  File "/home/ubuntu/Documents/squashfs-root/usr/Mod/Fem/feminout/importCcxFrdResults.py", line 154, in importFrd
    res_obj = resulttools.compact_result(res_obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/squashfs-root/usr/Mod/Fem/femresult/resulttools.py", line 663, in compact_result
    new_node_numbers.append(node_map[old_node_id])
                            ~~~~~~~~^^^^^^^^^^^^^

(0,)
```

I would expect it to fail because there are no mechanical results in this analysis (only temperature) but the errors suggest issues with node numbering for some reason.

The generated .frd file is correct, I can open it with other postprocessors.

**Comment by FEA-eng** [comment]
> can you share your test file?

Sure, here's the file:

[Cube heat.zip](https://github.com/FreeCAD/FreeCAD/files/14874801/Cube.heat.zip)

**Comment by marioalexis84** [comment]
I only get the `loading result failed` error after writing and running, but not the stack trace that you share.

**Comment by marioalexis84** [comment]
I didn't mean to avoid the loading error, just reproduce the one reported by @FEA-eng .

**Comment by lyphrowny** [comment]
You won't avoid it, on the contrary, you will get the stack trace, since you would no longer catch the exception

By removing `try except` block I meant to leave bare `self.fea.load_results()`

**Comment by marioalexis84** [comment]
Now I understand. I misunderstood your comment before being edited.

**Comment by lyphrowny** [comment]
Sorry for the confusion, glad it's been cleared up

**Comment by lyphrowny** [comment]
@FEA-eng, I guess, I tracked it down to this code https://github.com/FreeCAD/FreeCAD/blob/7a44179529920e79d40a7f4fe3dd49a48072363f/src/Mod/Fem/feminout/importToolsFem.py#L433-L452

This is what I get, when running `result_set.keys()` inside the above mentioned function. And there are no "disp" results indeed
```
dict_keys(['number', 'time', 'temp'])
```

If we had "disp" in result_set, we would've set `res_obj.NodeNumbers`. Since we don't have "disp", the `NodeNumbers` are the default ones - `[0]` https://github.com/FreeCAD/FreeCAD/blob/7a44179529920e79d40a7f4fe3dd49a48072363f/src/Mod/Fem/feminout/importToolsFem.py#L356-L359

In other two modes, we have "disp" in `result_set.keys()`

I did as it was written in the comments for the above mentioned function and made a PR (https://github.com/FEA-eng/FreeCAD/pull/1) to your repo. With these changes I managed to get a result:
image
However, if I try to move the "displacement" slider, I get the following error
```
Traceback (most recent call last):
File "..\Mod\Fem\femtaskpanels\task_result_mechanical.py", line 612, in show_displacement
    self.mesh_obj.ViewObject.setNodeDisplacementByVectors(
IndexError: list index out of range
```

So I guess, a user shouldn't be able to activate the displacement slider, if there are no displacements

**Comment by FEA-eng** [comment]
> I did as it was written in the comments for the above mentioned function and made a PR ([FEA-eng#1](https://github.com/FEA-eng/FreeCAD/pull/1)) to your repo. With these changes I managed to get a result:

Thanks a lot, PR merged. The issue with the slider is not that bad, maybe we could even fix it separately if it's hard to do now. @marioalexis84 What do you think?

**Comment by marioalexis84** [comment]
Ok to me.

In a next PR we can add the heat flow variable to the .inp writer and to the .frd reader.

**Comment by FEA-eng** [comment]
> In a next PR we can add the heat flow variable to the .inp writer and to the .frd reader.

Do you mean #12117 ? Yes, that could be the next step. I've tried to add this some time ago but I've only managed to prepare a code that will write HFL to the input file:

HFL

but supporting it in results objects will be more tricky. Especially since it's a vector quantity.

**Comment by marioalexis84** [comment]
> Do you mean https://github.com/FreeCAD/FreeCAD/issues/12117 ?

I will work on it as soon as possible.

**Review by marioalexis84 — APPROVED** [review]

**Pull request merged**
