### PR TITLE
FEM: replace UTF8 en-dash with simple ASCII hyphen

### PR DESCRIPTION
**Pull request by vocx-fc**
The en-dash added in the URL in the `femtools.constants` module (8d8a8dd87d) makes the parsing fail with Python 2 if `utf8` encoding is not specified at the beginning of the file.

---

I'm testing different things with this branch to help the unit tests pass.

---

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by berndhahnebach** [comment]
I missed this PR. In commit 8cec4c044445 I just exchanged with a normal - The link still works. In this case it is solved. 

Are you going to close it if  your tests are finished?

cheers bernd

**Comment by vocx-fc** [comment]
Yes, I saw that you fixed the issue and deactivated the unit tests. If you are going to look into this, then this pull request is no longer needed.

I don't know why the tests failed. I tried different things, but I am not entirely sure how Elmer writes its file. The error was that a float was printed with a different style; the `.sif` file had `21000000.0` but the unit test would print `2e+11` so the comparison would not work.

**Comment by berndhahnebach** [comment]
To be honest. In the regard fo FEM writer unit tests ATM I comment Python2 unit tests if they fail and the culprit is just some different formated number.  see 75387cf4b1e082d  Otherwise I try to fix it.

**Comment by vocx-fc** [comment]
Yeah, that's what I said.

**Pull request closed without merging**
