### PR TITLE
Add version info to window title

### PR DESCRIPTION
**Pull request by victorffs**
Fix issue 3499
Add comment to clarify why replace() is used
by The Wikilab Team (wikilab.blog.br)

### CODE REVIEW

**Comment by ianrrees** [comment]
Hi @victorffs, thanks for the contribution!  I'm wondering why the version needs to be in the window title - looking at other programs on my computer, not many of them do that.

I think the main point of the window title is to allow the person using their computer to identify running programs.

**Comment by yorikvanhavre** [comment]
This has been discussed for some time on the forum @ianrrees ... Basically we thought it would be a good idea because the FreeCAD version would appear in screenshots.

However we could easily introduce a preference setting to disable this, if someone feels the need for it.

**Comment by yorikvanhavre** [comment]
this is now merged

**Comment by ianrrees** [comment]
Thanks @yorikvanhavre, and sorry I haven't been able to keep up with the forum lately and completely missed the discussion.

I think the argument for not putting the version info in the title bar is basically that it adds noise, so putting in a setting to disable it would be throwing the baby out with the bathwater.  No big deal anyway.

**Comment by yorikvanhavre** [comment]
With 0ff2c72ab it is now possible to disable this easily for who doesn't want it, just add a boolean value named "ShowVersionInTitle" in Tools->Edit PArameters->Preferences->General and set it to False

**Pull request closed without merging**
