### PR TITLE
[FEM] force constraint overhaul

### PR DESCRIPTION
**Pull request by donovaly**
- fix warning about local scope
- add missing binding to force value in dialog
- don't immediately save on every change, first on accept()
- simplify constructor code logic
- make force a force property with unit (thus the many changes to the *.inp files
- also fix some too long code lines

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9096">pipeline status</a> for feature branch [PR_9096](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9096). Pipeline [819786315](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/819786315) was triggered at [9d40aa0](https://github.com/FreeCAD/FreeCAD/pull/9096/commits/9d40aa00f1ad629152676578b1db4d2d03d18e48). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9096">pipeline status</a> for feature branch [PR_9096](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9096). Pipeline [819834463](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/819834463) was triggered at [5bd188a](https://github.com/FreeCAD/FreeCAD/pull/9096/commits/5bd188a4a9e2a25b797998a82265a65b9a09cc8f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9096">pipeline status</a> for feature branch [PR_9096](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9096). Pipeline [820499106](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/820499106) was triggered at [4863b5f](https://github.com/FreeCAD/FreeCAD/pull/9096/commits/4863b5f859db7f75732ef7a762e9e7cfe338d182). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
Because this changes many file IMHO it should be splitted into multiple commits for a better overview and better review

- implementation 
- update of the examples with unit tests and the unit tests
- update of the examples without unit tests

BTW great addition 👍

**Comment by berndhahnebach** [comment]
same as #9097

Because this changes many file IMHO it should be splitted into multiple commits for a better overview and better review

- implementation 
- update of the examples with unit tests and the unit tests
- update of the examples without unit tests

BTW great addition 👍

**Comment by sliptonic** [comment]
@berndhahnebach  Can you take a closer look at this?

**Comment by sliptonic** [comment]
Also #9097

**Comment by yorikvanhavre** [comment]
I think there is nothing preventing to merge this... @FEA-eng @donovaly any of you would mind looking at the conflicts?

**Comment by FEA-eng** [comment]
> I think there is nothing preventing to merge this... @FEA-eng @donovaly any of you would mind looking at the conflicts?

I can build and test this on Ubuntu but I'm not familiar with the source code so I won't be able to help if there are coding issues.

**Comment by luzpaz** [comment]
Trying to assign this to @marioalexis84 but not able to? (even though i was able to assign #9097)

**Comment by marioalexis84** [comment]
This can be closed in favor of #10935

**Pull request closed without merging**
