### PR TITLE
Spreadsheet: export CSV file extension by default

### LINKED ISSUE #10829: [Problem] Spreadsheet Workbench export does not have an associated filetype
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When a Spreadsheet object is created in a Project, the "Export Spreadsheet to CSV' function does not save the file with a filetype. The .CSV filetype must be manually added on the exported file.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3D_Printing_Tools
  * Assembly4 0.50.2
  * CommandPanel
  * fasteners 0.4.66
  * Manipulator 1.5.0
  * slic3r-tools
[/code]
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Predko**
Fixes #10829

This pull request replaces #10853 as a rebased branch instead

Compiled and tested.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Very good fix, thanks for this first contribution! Hope you'll stick around ;)

**Comment by Predko** [comment]
Thank you all for your advice, help and criticism.
I'll try not to cause any more chaos ;)

**Comment by luzpaz** [comment]
@Predko that's just the learning process. No worries at all. The most important aspect is the contribution and the sweet success of getting it merged! Congrats and we hope to see more contributions from you. Don't worry about the git learning curve

**Comment by Predko** [comment]
@luzpaz ,
Thank you!

**Pull request merged**
