### PR TITLE
A set of ISO 7200/ISO 5457 templates for TechDraw

### PR DESCRIPTION
**Pull request by HowThatWorks**
Also removed the non-conformant ISO7200_Pep series and the ISO7200TD series of templates.

This should complete one of the tasks in #11671

### CODE REVIEW

**Comment by furgo16** [comment]
@HowThatWorks thanks! - what are the `TD` templates in the list? E.g. for A3 or A4 landscape there are 3 template types:

1. `*_ISO5457_minimal` => self-explanatory
2. `*_ISO5457_advanced` => self-explanatory
3. `*TD` => ??

**Comment by HowThatWorks** [comment]
I don't know what they are or who made them. Since they don't claim to be ISO-conformant templates I just ignored them. Are they useful to anyone? Should they be removed? Probably not and probably yes, but I felt that's a bit outside the scope of this PR.

**Comment by tobiasfalk** [comment]
The TD stand for TechDraw and are all in the "standard" style

**Comment by HowThatWorks** [comment]
Ah, yes, that nebulous "standard" standard ;)

**Comment by furgo16** [comment]
Thanks everyone. I agree that it's outside of the scope of this PR, I just thought I'd use the opportunity to ask here quickly. I can also open a topic on the forum.

> The TD stand for TechDraw and are all in the "standard" style

Indeed, what's the "standard" style in this context? I'll happily update https://wiki.freecad.org/TechDraw_Templates to remove uncertainty.

**Comment by HowThatWorks** [comment]
m52 and TD both have metric refence graduations, which is a thing from ISO 5457:1980 (now withdrawn), so I'm guessing these are reproductions of some pretty old templates that were once "standard".

Moving this discussion to the forums is probably a good idea.

**Pull request merged**
