### PR TITLE
Spreadsheet: Add Python API for getUsedCells

### LINKED ISSUE #7587: [Feature] [Spreadsheet] API function to access number of cols and rows
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?t=50259

### Subproject(s) affected?

Other (specify in description)

### Idea description

Munther Hindi a co-developer of the GDML workbench has added functionality to import/export GDML Matrix properties to spreadsheets, his code needs to be able to determine the current number of cols and rows in a spreadsheet.
The number of cols/rows is not available via the API and he has had to resort to the work around as per the FreeCAD forum discussion, which it has to be said is a real Kludge of a solution. Please can we have a API facility to access the current number of cols and rows in a spreadsheet.

Thanks  

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chennes**
Also adds access to `getNonEmptyCells()`, and unit tests for both. In a second commit, two new C++ functions are introduced to get the range of non-empty and used cells, `getNonEmptyRange()` and `getUsedRange()`. These functions return a pair of cell addresses representing the bounding box of the data in the sheet. Python wrappers and unit tests are also provided.

Designed to fix #7587.

### CODE REVIEW

**Comment by chennes** [comment]
@wwmayer did I do that `Py::new_reference_to` bit correctly in the PyImpl file?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7697">pipeline status</a> for feature branch [PR_7697](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7697). Pipeline [685343322](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/685343322) was triggered at [360f516](https://github.com/FreeCAD/FreeCAD/pull/7697/commits/360f5163fec5266ab0daa6a41c2f40adc7181be1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7697">pipeline status</a> for feature branch [PR_7697](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7697). Pipeline [686190097](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686190097) was triggered at [5394923](https://github.com/FreeCAD/FreeCAD/pull/7697/commits/5394923ad1157a48c57434db8218de326141cc3f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7697">pipeline status</a> for feature branch [PR_7697](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7697). Pipeline [686193268](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686193268) was triggered at [8a71110](https://github.com/FreeCAD/FreeCAD/pull/7697/commits/8a7111056bcdd46fd9ef941fc4dfa0acbc0b0ef1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by marioalexis84** [comment]
@chennes `PyArg_ParseTuple` should be used to restrict the number of function arguments to zero.
On the other hand, reference incrementing using `Py::new_reference_to` is correct.

**Comment by chennes** [comment]
@marioalexis84 thanks for the review. I've made the change you suggested.

**Comment by chennes** [comment]
@marioalexis84 thanks for the review. I've made the change you suggested.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7697">pipeline status</a> for feature branch [PR_7697](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7697). Pipeline [686499201](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686499201) was triggered at [e83be0f](https://github.com/FreeCAD/FreeCAD/pull/7697/commits/e83be0fe3e3a6213c708ebb4ea1631f05c05ee5b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
