### PR TITLE
[Gui] Transform Tool, save Translation...

### PR DESCRIPTION
**Pull request by Syres916**
..and Rotation Increments in user config file.
See discussion https://forum.freecadweb.org/viewtopic.php?f=8&t=60195

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by 0penBrain** [comment]
@Syres916 : only a quick look but I find some weird things : 
- The 'lastXXXIncrement' values are set in 'open()' then overwritten just after in 'setupGui()'. Why not just change the way they are initialized ?
- Why save the values in 'open()' method rather than in 'accept()' one ?
- If these values are 'memory' and not made for user change, it could be better to store them in BaseApp/History

**Comment by Syres916** [comment]
@0penBrain : I've tried numerous different ways to initialise the two values and every time the splashscreen doesn't load so if this is unacceptable I'll close it.

**Comment by 0penBrain** [comment]
@Syres916 : was just to know if there were reasons for this. ;) Will have a look
I don't think it's a problem, but also similar values are defined at https://github.com/FreeCAD/FreeCAD/blob/166f5e7a4b76c6a1de7e9fe2ddcbde169339c34b/src/Gui/SoFCCSysDragger.cpp#L103 and https://github.com/FreeCAD/FreeCAD/blob/166f5e7a4b76c6a1de7e9fe2ddcbde169339c34b/src/Gui/SoFCCSysDragger.cpp#L378

**Comment by 0penBrain** [comment]
@Syres916 : what would you think of something simple : https://github.com/0penBrain/FreeCAD/commit/262dcc2cbe8f4dce9646d278c152edc527b21f05
Feel free to cherry pick. ;)

**Review by 0penBrain — APPROVED** [review]
Looks good to me.
Eventually all commits could be squashed together to get a cleaner history when merged.

**Pull request merged**
