### PR TITLE
XDGData: misc fixes

### PR DESCRIPTION
**Pull request by eszlari**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@eszlari interesting. Do you mind opening forum thread to discuss your PR?

**Comment by eszlari** [comment]
I don't think there is anything controversial about these changes. These are just some minor cleanups.

**Comment by luzpaz** [comment]
why rename appdata to metainfo?

**Comment by eszlari** [comment]
> why rename appdata to metainfo?

The link to the spec is in the commit message:
https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html
This was changed some months ago.

**Comment by yorikvanhavre** [comment]
This might potentially affect older distributions... Need to have a better look

**Comment by luzpaz** [comment]
I took a cursory look at all the https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html documentation and I couldn't find clear instructions on how to manage backward compatibility.

**Comment by eszlari** [comment]
According to GNOME developers, this is supported since 2014:

https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1110

**Comment by wwmayer** [comment]
When using the package search engine of Ubuntu then none of the packages of Xenial (2016) have their metainfo.xml file in the metainfo directory, it's still appdata:
https://packages.ubuntu.com/search?searchon=contents&keywords=metainfo.xml&mode=&suite=xenial&arch=any

With Bionic the majority of packages have moved these files to metainfo now:
https://packages.ubuntu.com/search?searchon=contents&keywords=metainfo.xml&mode=&suite=bionic&arch=any

When searching files of the form appdata.xml then they are still used a lot:
https://packages.ubuntu.com/search?searchon=contents&keywords=appdata.xml&mode=&suite=groovy&arch=any

When I got the package instructions of e.g. Fedora right then an appdata.xml is used for the main application and metainfo.xml is used for add-ons: https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/

So, this means that our appdata.xml file shouldn't be renamed but installed to a different directory on newer systems.

Now we can ignore the default install location for Xenial and thus have the risk that the meta information won't be shown (any more) because it will expire in a few months anyway or we can add a new CMake variable called CMAKE_INSTALL_METAINFO whose default value is "metainfo" but can be overridden by package maintainers of Xenial to be "appdata".

This PR must then be adjusted accordingly:
* it should use the variable CMAKE_INSTALL_METAINFO
* It should revert the change to rename to appdata.xml file (if I got things right)

**Comment by wwmayer** [comment]
Here is how KDE handles it:
https://community.kde.org/Guidelines_and_HOWTOs/AppStream

**Comment by luzpaz** [comment]
In a lot of way we aren't fully leveraging the AppData/MetaInfo aspect of FC. Should I open a ticket to explore this?

**Comment by eszlari** [comment]
> When I got the package instructions of e.g. Fedora right then an appdata.xml is used for the main application and metainfo.xml is used for add-ons: https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/

This documentation is out of date, please refer to the official specification:
https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html

**Comment by eszlari** [comment]
https://github.com/ximion/appstream/issues/294

Quote from the author of the spec:

> Jup, since AppStream 0.9.4 (since 2016-04-18).
> Every LTS distribution, including Debian, Ubuntu (including older ones like18.04 LTS) and AFAIK even RHEL via updates supports this, so it's pretty much safe to be used unconditionally.
> In fact, if the AppStream 1.0 release plans had worked out for this year, the support for the old location would have been dropped already.
> On my Debian system, /usr/share/appdata is empty (only Chrome puts its file in there for some reason), and last time I looked in all of Debian only 42 components of 2262 were using the old location.
> So yeah, it's safe to switch. The .metainfo.xml suffix is ancient too, but you can stick with the appdata one, most apps did that for desktop-application components anyway, as the "you can use .metainfo.xml for any metadata" recommendation was done later. Also, we'll never deprecate the .appdata.xml suffix, unlike the old metadata location.
>

**Comment by luzpaz** [comment]
I wonder how this impacts snap packages + other ecosystems like  Arch Linux and it's derivatives?

**Comment by luzpaz** [comment]
CC Linux distro package managers  
@PrzemoF  
@hobbes1069  
@jsoo1

**Comment by hobbes1069** [comment]
Overall I agree with the changes. The icon names must match the desktop file name to be compliant. I don't know that the desktop file name needs to match the metainfo naming scheme but it doesn't hurt. 

It looks like the appdata.xml extension is still supported so that would be "safe" unless there was a good mechanism to know what kind of system is being installed to OR a CMake option for the packager to specify manually.

**Comment by eszlari** [comment]
I have reverted the rename to `*.metainfo.xml`.

**Comment by eszlari** [comment]
ping @wwmayer

**Comment by eszlari** [comment]
I would really like to get this in 0.19. If there is something else left to do, please let me know.

**Comment by wwmayer** [comment]
> I would really like to get this in 0.19. If there is something else left to do, please let me know.

Although it's marked with "For 0.20" now I will have a look before the freeze.

**Comment by yorikvanhavre** [comment]
(Sorry I had marked it automatically for 0.20 without looking well... Sorry about that!)

**Comment by yorikvanhavre** [comment]
Leaving for you @wwmayer as you said you would have a look, but this looks good to merge to me

**Review by yorikvanhavre — APPROVED** [review]

**Comment by yorikvanhavre** [comment]
The internet domain of FreeCAD might change soon, so I think it's best to not use org.freecadweb anymore...

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by luzpaz** [comment]
Related: 2cc570757144422a189b9881e650c3878ec58b13 and 5ad8bed9c479246058a9df48a16899bd903fc265

**Comment by donovaly** [comment]
> The internet domain of FreeCAD might change soon, so I think it's best to not use org.freecadweb anymore...

@eszlari can you please do so and use "freecad.org". Then the PR can be merged.

**Comment by donovaly** [comment]
@eszlari , if you don't reply this week, the PR cannot be merged for FC 0.20

**Comment by donovaly** [comment]
No reply for more than year. Closing for now. Please reopen when the PR could be merged and is updated.
In every case it cannot be merged for FreeCAD 0.20

**Pull request closed without merging**
