### PR TITLE
Fix compilation failures in TopoShapeExpansion and TopoShapeMapper.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Main does not build following #12237
Please be careful about precompiled includes @chennes @bgbsww

### CODE REVIEW

**Comment by chennes** [comment]
The modelRefine.h fix is good. The mapper file needs the #ifndef around the OCCT headers. Thanks for the catch. @adrianinsaval is it possible to set one of our CI platforms to use precompiled headers?

**Comment by adrianinsaval** [comment]
I have to experiment with it, I'm not sure if ccache can work with precompiled headers

**Comment by bgbsww** [comment]
Yikes.  Many apologies.  ~~Looking for PCH info on FreeCAD has come up empty.  Appears to be the FREECAD_USE_PCH cmake option, I can certainly test build this locally if that's all it takes.  Unfortunately, I didn't see much change other that notable slowness and no breakage trying a build with that option in an Ubuntu environment; is this only testable in an MSVC setup?~~

 I found https://forum.freecad.org/viewtopic.php?t=70796

Should info on using/not using PCH be added to dev documentation somewhere?  Maybe the developer's handbook?  I can do that.

**Comment by PaddleStroke** [comment]
I have added the ifndef . Is that ok like this? If so let's get this in asap if possible

**Comment by chennes** [comment]
> I have added the ifndef . Is that ok like this? If so let's get this in asap if possible

If it compiles on your system, then it's OK -- I can't check MSVC myself right now.

**Comment by PaddleStroke** [comment]
Yes it works like this

**Pull request merged**
