### PR TITLE
Multi-thread support for Calculix taskpanel

### PR DESCRIPTION
**Pull request by atorger**
issue #6371

Apply multi-thread configuration when Calculix is started via the task panel.

### CODE REVIEW

**Comment by luzpaz** [comment]
Depends on the outcome of #6370

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6374">pipeline status</a> for feature branch [PR_6374](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6374). Pipeline [471760428](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/471760428) was triggered at [f6f5d4a](https://github.com/FreeCAD/FreeCAD/pull/6374/commits/f6f5d4a63bbba082bc3a0e45c5b2431ae1c1a9b7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Looks good. I will test it tomorrow. Can you please rebase it and merge it to a single commit?

**Comment by atorger** [comment]
done!

**Comment by donovaly** [comment]
Many thanks. It works nicely. Merging.

**Pull request merged**
