### PR TITLE
Travis - fixes for Windows build

### PR DESCRIPTION
**Pull request by triplus**
https://forum.freecadweb.org/viewtopic.php?f=10&t=42615&p=367579#p367579

### CODE REVIEW

**Comment by triplus** [comment]
Don't merge for now. Will use this PR for testing purposes, Windows builds. Once we figure the issue out i will add a comment.

**Comment by triplus** [comment]
I fixed some detected issues, like error due to trailing slash in a variable, new LibPack path related issues and an issue with mv command. Hence now the whole download procedure and CMake phase should work. But for now i have disabled Windows builds, due to an issue on Travis side. Using cmd.exe /C will hang the Windows build and as a result the build will time out. 

This PR is ready to be merged. Tomorrow i will prepare a special Windows tailored PR that we can use, press on a rebuild button from time to time, to detect when the upstream issue will get fixed.

**Comment by triplus** [comment]
As advised by Travis people i have added the fixes for the cmd.exe issue and now Windows builds should be back.

https://travis-ci.community/t/vcvarsall-bat-freezes-on-new-1809-based-windows-images/7098/6

P.S. In addition i replaced/removed some depreciated aliases and keys.

**Comment by yorikvanhavre** [comment]
This seems to be working. Ok to merge?

**Comment by triplus** [comment]
As far as i am concerned this PR is ready to be merged. It should fix the Windows builds. Once that happens i will rebase (to include this changes):

https://github.com/FreeCAD/FreeCAD/pull/2930

**Pull request merged**
