### PR TITLE
[Gui] remove iisTaskPanel

### PR DESCRIPTION
**Pull request by donovaly**
as discussed here, it can be removed: https://forum.freecadweb.org/viewtopic.php?p=577413#p577413

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6573">pipeline status</a> for feature branch [PR_6573](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6573). Pipeline [490848656](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/490848656) was triggered at [43b2ce4](https://github.com/FreeCAD/FreeCAD/pull/6573/commits/43b2ce4278d25f0313ef114024e7e60ff6ff95de). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Is this scheduled for pre- or post- release ?

**Comment by donovaly** [comment]
This should be removed now as also @wwmayer agreed to in the forum thread I linked. If there are no objections, I will merge this later today.

**Comment by donovaly** [comment]
Merging hoping I don't break anything.

**Pull request merged**
