### PR TITLE
Assembly: Flexible sub-assemblies.

### PR DESCRIPTION
**Pull request by PaddleStroke**
This introduce 'AssemblyLink' document object. These are not deriving from App::Link, but in fact deriving from App::Part.
Instead of linking to an assembly like a link would do, it is populating itself with links to the various components. Enabling to have different component placements between each instance of AssemblyLink.

Fix https://github.com/FreeCAD/FreeCAD/issues/15208
Fix https://github.com/FreeCAD/FreeCAD/issues/16436

builds on top of https://github.com/FreeCAD/FreeCAD/pull/16317 so that one needs to merge first.

### CODE REVIEW

**Comment by 3x380V** [comment]
What prevents you from using variant links? Introducing another new object should be considered the last resort option.

**Comment by PaddleStroke** [comment]
Nothing but my own misunderstanding of these. I thought that would not work
but according to Zolko it would.
So I will need to revisit this PR.
If variant links can work then it's better than implementing this new class.

**Comment by PaddleStroke** [comment]
Cleaning commits as to isolate the changes that were made during this PR that do not rely on those new AssemblyLink. So that if this PR is dropped the useful changes can be ported.

**Comment by PaddleStroke** [comment]
@3x380V Do you per chance have a minimal example of variant link where you can have 2 links to an assembly and have the subelements with different placement?
I find little information about these 'variant links'.

**Comment by 3x380V** [comment]
@PaddleStroke I tried few times to create example but FreeCAD segfaults for me even when creating new file (_Std_New_). Time to time it works, but then it fails assigning Variable to the Link placement. I need either fix that first or find a version which works. But assuming you want to try it yourself, fix is preferred. I will look at this again in the evening.

**Comment by PaddleStroke** [comment]
@3x380V I finally could find the example file of the Variant Link, and found out that VariantLink are actually not giving different placement to different parts. They are actually a similar concept as I am making here with AssemblyLinks but with an additional layer of complexity as it seems he is storing them in hidden documents, and overall it seems rather buggy.

So anyway I will resume work on this PR since there're no way to use App::Links and VariantLinks are not in core.

**Comment by 3x380V** [comment]
@PaddleStroke I'm sorry for the delay. Interestingly enough Qt5 based build is stable while Qt6 one segfaults randomly. Nevermind, back to question. First of all I've never tried integrated Assembly WB which is a shame here and also just read #15208 comments, which would save me some time. Perhaps I now better understand this issue.
Hopefully [asm.zip](https://github.com/user-attachments/files/16510714/asm.zip) resembles czinehuba's problem. Second link group is just another link to first one with offset. Now expression parser could be extended to do something like `VarSet.%s_P1 % _parent.Label` so result depends on subassembly (link group) it is embedded. Whenever it is more suitable solution I cannot judge. The position is then expression controlled like everything else, so user can for example simulate gear clearances, etc.

**Comment by maxwxyz** [comment]
@PaddleStroke will this be ready for 1.0?

**Comment by DerAndere1** [comment]
Maybe compare variant links and AssemblyLinks in terms of performance and RAM usage when working with 
a) very large assemblies of large sub-assemblies (e.g. a car)
b) assemblies with a very large number of simple objects (e.g. fasteners)

**Comment by PaddleStroke** [comment]
TODO : @prokoudine repported that the 'rigid' checkbox is reversed.

**Comment by 3x380V** [comment]
@PaddleStroke, that hidden document is quite powerful. Given there is also https://github.com/FreeCAD/FPA-grant-proposals/issues/10 could anyone elaborate a bit how this all is supposed to work together? A lot entered in the core and still it does not implement what's already in external workbench.

For a reference [here's](https://github.com/user-attachments/files/17161615/asm.zip) Asm4 way.

[Screencast from 2024-09-27 10-43-32.webm](https://github.com/user-attachments/assets/bb73b881-6d47-4762-94a2-13381e7990fb)

**Comment by PaddleStroke** [comment]
@3x380V This was discussed extensively with Pieter actually (the one behind the grant proposal on variant link). And variant link are not adapted for this.
As for A4 implementation, first A4 owner made it extremely clear that he does not want his code to be used (he even made a formal complain about a useless 4 line helper function). On top of that it's not really 'compatible' or at least would be extremely tedious to adapt, and for no benefits. His solution is close to the AssemblyLink one, but with an unecessary layer of additional hidden documents that would make things difficult.

**Comment by 3x380V** [comment]
My concern is to be able to still use `Asm_variantLink` as many designs depend on that. The question was more about Variant Parts than Flexible sub-assemblies (in your terms, in A4 these are the same) and I consider that answered. More questions will probably come to appropriate place. Thanks, @PaddleStroke.

**Comment by chennes** [comment]
We marked this for the 1.0 milestone back in July -- at this late date this is likely too much code to pull in to the release. I propose moving the milestone to 1.1. We can discuss at the PR Review Meeting on Monday, but please feel free to leave your comments here, particularly if you cannot attend that meeting.

**Comment by furgo16** [comment]
That's unfortunate, but understandable. If this ends up not being merged, please consider addressing the related issues (e.g. https://github.com/FreeCAD/FreeCAD/issues/17208, there might be more). Even if there aren't flexible sub-assemblies in 1.0, perhaps there's a middle ground to make them behave as single components with locked joints?

**Comment by 3x380V** [comment]
@chennes, so far Assembly sees one commit per day till the last week and I presume nothing happened during last few day only because @PaddleStroke was busy with this PR. It does not affect anything outside Assembly and Ondsel is promoting Assembly as major improvement, so it would be fair to let it in for 1.0. There are 5 blockers and 17 confirmed crashes, so no rush ;-)

**Comment by PaddleStroke** [comment]
As you guys prefer.
If this go in, there may be issues appearing. But current sub-assemblies are full of issues apparently. (I think there're at least 3 in the tracker now). Also I can most likely fix any arising issue pretty quickly.

If this does not go in, then we probably need to deactivate the current "kind of flexible" behavior of nested assemblyobjects. Though that will generate a lot of conflicts with all my current branches so this is not my prefered solution

**Comment by PaddleStroke** [comment]
Besides assembly links have been available in Ondsel ES for at least 1month and no issue reported yet.

**Comment by maxwxyz** [comment]
I'm also in favor of merging this to 1.0. There are currently issues with sub assemblies and it is already in the Ondsel release.

**Comment by yorikvanhavre** [comment]
merge by decision of M3 and backported

**Comment by Zolko-123** [comment]
> first A4 owner made it extremely clear that he does not want his code to be used 

no : I made it extremely clear that Ondsel cannot take my code and replace my copyright notice with Ondsel's. My code is **used** by many many FreeCAD users, but what Ondsel did was to nick it and pretend they invented it. You don't seem to understand what open-source is about : it's not open-bar to help yourself for free.

**Comment by furgo16** [comment]
Will existing files with assemblies be migrated to the new flexible sub-assembly construct, or will they need to be recreated from scratch?

**Comment by MiqCG** [comment]
> builds on top of https://github.com/FreeCAD/FreeCAD/pull/16317 so that one needs to merge first.

What about this comment from @PaddleStroke about the order of merging? 
Will this, still not merged PR make any trouble in the flexible sub-assemblies feature?

**Comment by PaddleStroke** [comment]
@furgo16 no migration script. Nested assembly should now be considered solid. Links to sub assemblies as well.

@MiqCG the other PR was included in this one actually. So merging this first is same as merging both. I just need to double check the commits are actually the same.

**Comment by furgo16** [comment]
@PaddleStroke I've found that linked sub-assemblies added to a parent assembly before this PR was merged do NOT have the "Rigid" property. Instead, they have the regular properties of a link. If I delete the sub-assembly and then I re-add it, it then has the "Rigid" property.

So if I understand it correctly, there is manual work required to update sub-assemblies added to an assembly before this PR was merged to the new format.

**Comment by PaddleStroke** [comment]
Indeed, App::Links to assemblies are not converted. The introduced object type is a new type of object.

**Comment by MiqCG** [comment]
I am using the flexible (non-rigid) sub-assemblies and I am encountering problems and crashes when moving trying to move a component. 
Before opening issues with very few knowledge, @PaddleStroke can you confirm that the expected behaviour is that:

1. you can link an assembly to another subassembly using the "insert component" tool.
2. When selecting the Rigid property on the linked subassembly and choose "false", the subassembly will be able to move in accordance to their "internal" joints and in accordance to the joint that links it to the parent assembly.

Thanks

**Pull request merged**
