### PR TITLE
Re-arrange Start Page template buttons

### PR DESCRIPTION
**Pull request by qewer33**
See: https://github.com/FreeCAD/FreeCAD/issues/12989

Also changed the name of PD template from "Standard Part" to "Parametric Part" and tweaked the assembly template description.

Old:

image

New:

image

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I liked it! Now, is the "blank" icon still interesting to have?

**Comment by FEA-eng** [comment]
> I liked it! Now, is the "blank" icon still interesting to have?

Do you mean the "Empty file" one? I use it a lot. It takes you from the Start page to an empty page from which you can go to any workbench and it doesn't add anything to the tree.

**Comment by yorikvanhavre** [comment]
Interesting... Which workbench do you use immediately after? I guess you don't stay on the start WB... :)

**Comment by FEA-eng** [comment]
> Interesting... Which workbench do you use immediately after? I guess you don't stay on the start WB... :)

The thing is that it really depends. I often go straight to the Sketcher and then to Part (maybe a button for a pure sketch would make sense). Or to Part and then FEM. Or to Part Design (then the first button is helpful).

**Comment by yorikvanhavre** [comment]
The thing I'm mostly annoyed with, is that creating a new document but staying on Start is mostly useless. Nobody will stay on Start, everybody will need to switch to another workbench.

Maybe the "blank" one should load Part?

**Comment by FEA-eng** [comment]
> Maybe the "blank" one should load Part?

Then it should be a button for Part wb (which IMO can makes some sense and was proposed initially). It would be nice to have an option to configure where that "Empty file" button takes you. I don't mind Start since I just switch to the desired location but what about this idea - you select "Empty file" and you are taken to a nice modern list with large buttons for various workbenches to choose as the first one. Maybe it could be implemented as part of the ongoing Start page overhaul.

**Pull request merged**
