### PR TITLE
Issue 3325 2a

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
Integration notes: 
- The first commit is to be ignored. It is to fix master, but a fix was committed in the meantime.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Merged.

**Comment by wwmayer** [comment]
Not merged! The last commit seems to create a dependency loop.
For testing:
1. Create a body, box and cylinder
2. Double click the box and cancel
3. Check the dependency graph, box and cylinder depend on each other

**Comment by abdullahtahiriyo** [comment]
I have tracked it down to the restoring of the tip, but just moving the code down to ViewProviderPrimitive. This code generates the same cyclic dependency:


`void ViewProviderPrimitive::unsetEdit(int ModNum)
{
    Q_UNUSED(ModNum);
    setPreviewDisplayMode(false);
    
    if (ModNum == ViewProvider::Default) {
        // when pressing ESC make sure to close the dialog
        PartDesign::Body* activeBody = PartDesign::Body::findBodyOf(this->getObject());
        Gui::Control().closeDialog();
        if ((activeBody != NULL) && (oldTip != NULL)) {
            Gui::Selection().clearSelection();
            Gui::Selection().addSelection(oldTip->getDocument()->getName(), oldTip->getNameInDocument());
            Gui::Command::doCommand(Gui::Command::Gui,"FreeCADGui.runCommand('PartDesign_MoveTip')");
        }
        oldTip = NULL;
    }
}
`

**Comment by abdullahtahiriyo** [comment]
This is the minimal modification that resolves the cyclic dependency:
https://github.com/abdullahtahiriyo/FreeCAD_sf_master/tree/issue_3325_2a_modif

So it is basically bringing the commands from the Tip move from the Gui/CommandBody to the ViewProvider. It has a problem, the new tip is not shown (the command is there, it is executed in the python console, but no effect is shown).

I cannot understand why this fixes the issue at all. But I think it may help you out know.

**Comment by abdullahtahiriyo** [comment]
https://forum.freecadweb.org/viewtopic.php?f=10&t=26727&p=213314#p213314

**Comment by abdullahtahiriyo** [comment]
https://github.com/FreeCAD/FreeCAD/pull/1294

**Pull request closed without merging**
