### PR TITLE
[TechDraw] Changes to Geometry.cpp

### PR DESCRIPTION
**Pull request by benj5378**
### Changes to Geometry.cpp for maintenance
I am a total noob, so please look through the code carefully and build it to test its functions. I suggest splitting Command.cpp up, as it is a mix of different classes over 1800 lines.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7145">pipeline status</a> for feature branch [PR_7145](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7145). Pipeline [582867923](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/582867923) was triggered at [7beca49](https://github.com/FreeCAD/FreeCAD/pull/7145/commits/7beca4983015d334c28efb0fa7908707777b5a88). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
Is this really "refactoring Geometry.cpp"?  Unless I miss something, it looks like we're changing the names of 2 setters and 2 getters so the names start with set/get.  

No problem with changing the names.   OCC often usessetter/getter pairs like this -  function(value); and value = function(); - maybe they are a bad influence on me.

**Comment by benj5378** [comment]
> Is this really "refactoring Geometry.cpp"? Unless I miss something, it looks like we're changing the names of 2 setters and 2 getters so the names start with set/get.
> 
> No problem with changing the names. OCC often usessetter/getter pairs like this - function(value); and value = function(); - maybe they are a bad influence on me.

I think you missed the collapse of Geometry.cpp? Anyways, call it what you want.
The reason for the name change is that before, source() could both set and get the variable to confusion when reading code.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7145">pipeline status</a> for feature branch [PR_7145](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7145). Pipeline [582881661](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/582881661) was triggered at [e95a2df](https://github.com/FreeCAD/FreeCAD/pull/7145/commits/e95a2df17732671591b3899e5f784c7b6063e87e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@benj5378 thank you for the PR and contribution! JFTR, the `geometry.cpp` changes could have been further split in to separate commits for easier review since you tackled multiple issues at one including whitespace, formatting and typos.

**Comment by WandererFan** [comment]
I don't want to merge this PR.  It is mostly style changes. It touches lots of code and everything it touches needs to be QA'd.  That's a big job, and I just don't see the payback.  Maybe I'm missing the point.

From LLVM coding standards:
"If you are extending, enhancing, or bug fixing already implemented code, use the style that is already being used so that the source is uniform and easy to follow."
But you can probably find similar guidelines elsewhere.  

If you don't like the code's formatting, first read these posts,
Coding style (1): https://forum.freecadweb.org/viewtopic.php?p=588957#p588957
Coding style (2): https://forum.freecadweb.org/viewtopic.php?p=421276#p421276

Then use an automatic formatter like ClangFormat with FreeCAD/.clang-format rather than reformatting manually. The formatter will do a better job, and won't miss anything.

Adding comments is good if they add something that isn't obvious from the code. 
Using #defines instead of magic numbers is good.
Moving braces around is style, not substance. 
Adding set/get to method names is not really worth the trouble since we use OCC 
setters and getters that don't follow this convention all the time.
Multiple exit points are fine for guard clauses and when they simplify code, but
(IMO) single exit points are preferable unless they make for convoluted code.
An optimizing compiler will generate the same code for "temp = foo(); return temp;"
 and "return foo();",  There is no good reason to
switch one to the other.

IMO, this
`    ss << geomType << "," << extractType << "," << classOfEdge << "," << hlrVisible << "," << reversed << "," << ref3D << "," << cosmetic << "," << m_source << "," << m_sourceIndex;
`
is not more clear than
```
 ss << geomType << "," <<
          extractType << "," <<
          classOfEdge << "," <<
          hlrVisible << "," <<
          reversed << "," <<
          ref3D << "," <<
          cosmetic << "," <<
          m_source << "," <<
          m_sourceIndex;


```Again IMO, this
`    if (this->geomType == TechDraw::CIRCLE || this->geomType == TechDraw::ARCOFCIRCLE)
`is not more clear than
```
    if (this->geomType == TechDraw::CIRCLE ||
        this->geomType == TechDraw::ARCOFCIRCLE)

```

**Comment by benj5378** [comment]
@WandererFan I agree, that the code formatting is no good. (I used an automatic formatter and didn't pay enough attention.) Let's close this PR

**Pull request closed without merging**
