### PR TITLE
Gui: Hack to get Windows 11 version

### PR DESCRIPTION
**Pull request by chennes**
As promised in #9596, here's the equivalent hack to get the proper Windows 11 version based on the current build number.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by adrianinsaval** [comment]
is this also fixed in qt6 then?

**Comment by adrianinsaval** [comment]
Also looking at the upstream issue I think the fix for mac is in qt 6.5 not 6.0, I didn't see anything about windows
https://bugreports.qt.io/browse/QTBUG-111114
https://codereview.qt-project.org/c/qt/qtbase/+/460158

Would windows 7 still be reported correctly with this method?

**Comment by chennes** [comment]
This should only affect 64 bit Windows, so I think Win7 will be unaffected.

**Comment by adrianinsaval** [comment]
Windows 7 64bit is widely used, possibly more so than the 32bit version. Not that I think anyone should use windows 7 but people do it

**Comment by chennes** [comment]
OK, I pushed a more thorough hack that should get us back to Win7.

**Comment by adrianinsaval** [comment]
unless we have reason to believe that this issue has been fixed in qt6 wouldn't it be better to put the windows if outside the qt6 if?

**Pull request merged**
