### PR TITLE
add test to check python compatibility

### PR DESCRIPTION
**Pull request by looooo**
a simple check to find files which are not parse-able with the used python interpreter.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I wonder if it is necessary to make each and every person who compiles FreeCAD run this test at each build? Seems unnecessary build time to me... Wouldn't it be enough for the developers and some kind testers to run it from time to time and make sure everything stays compatible?

**Comment by looooo** [comment]
it is quite fast and is only run in the cmake step. Looking at the timings of the ci's (cmake step ~15 sec) it doesn't differ very much from a build without the checks. I guess it's about 3 sec.
For me adding this would be a great achievement as this checks all python3 print errors.

**Comment by looooo** [comment]
I moved the tests to the Test module. With gui the test runs fine but with FreeCADCMD -t 0 the test is not triggerd. Any idea what's missing there?

**Comment by wwmayer** [comment]
On Windows calling FreeCADCmd.exe -t 0 works for me. The output is:
...
testAll (TestPythonSyntax.PythonSyntaxTestCase) ... ERROR

======================================================================
ERROR: testAll (TestPythonSyntax.PythonSyntaxTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Projects\FreeCAD-git\ReleaseOCC\Mod\Test\TestPythonSyntax.py", line 37, in testAll
    test_python_syntax(App.getHomePath())
  File "C:\Projects\FreeCAD-git\ReleaseOCC\Mod\Test\TestPythonSyntax.py", line 24, in test_python_syntax
    raise RuntimeError("there are are files not parse-able with the used python-interpreter" + message)
RuntimeError: there are are files not parse-able with the used python-interpreter

##############################
4 python files are not parseable:

automotive_design.py
ifc2x3.py
ifc4.py
AddNewCommand.py
##############################

This is tested for FreeCAD linked with Py2. With Py3 it doesn't work at the moment because PySide2 for Py3 is not yet built. To test the module here I have to run it as:
FreeCADCmd.exe -t TestPythonSyntax
However, it aborts immediately with this error:
testAll (TestPythonSyntax.PythonSyntaxTestCase) ... ERROR

======================================================================
ERROR: testAll (TestPythonSyntax.PythonSyntaxTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Projects\FreeCAD-git\Py3\Mod\Test\TestPythonSyntax.py", line 37, in testAll
    test_python_syntax(App.getHomePath())
  File "C:\Projects\FreeCAD-git\Py3\Mod\Test\TestPythonSyntax.py", line 15, in test_python_syntax
    ast.parse(py_file.read())
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 30760: character maps to <undefined>

----------------------------------------------------------------------
Ran 1 test in 0.437s

FAILED (errors=1)

Any idea what's wrong here?

**Comment by wwmayer** [comment]
There is also a bug in the script. The travis builds fail with this error:
Traceback (most recent call last):
  File "/usr/local/Mod/Test/TestPythonSyntax.py", line 37, in testAll
    test_python_syntax(App.getHomePath())
  File "/usr/local/Mod/Test/TestPythonSyntax.py", line 23, in test_python_syntax
    if i:
UnboundLocalError: local variable 'i' referenced before assignment

This is because the script didn't find and invalid Py files and thus log is an empty list. But this means that "for i in log" won't be executed hence the failure because "i" is not defined. I think you better use "if len(log) > 0" as criterion.

**Comment by wwmayer** [comment]
The culprit is not ast.parse but the file read() function. In the file there is a strange symbol (line 525) which is outside the ASCII range. However, the file is explicitly coded as utf-8 and the file open function should respect this.
So you should write: with open(os.path.join(sub_dir, fn), encoding='utf-8') as py_file:

**Comment by looooo** [comment]
thanks for having a look. I added the fixes and cleaned the commits. 
- [x] `if i: UnboundLocalError: local variable 'i' referenced before assignment`
- [x] `So you should write: with open(os.path.join(sub_dir, fn), encoding='utf-8') as py_file`

**Comment by looooo** [comment]
Seems this doesn't work in python2:
` with open(os.path.join(sub_dir, fn), encoding='utf-8') as py_file`


are we trying to parse the whole system??? ; )
```
/usr/local/clang-5.0.0/share/clang/clang-rename.py
/usr/local/clang-5.0.0/share/clang/run-find-all-symbols.py
/usr/local/clang-5.0.0/share/clang/clang-format-diff.py
/usr/local/clang-5.0.0/share/clang/clang-include-fixer.py
/usr/local/clang-5.0.0/share/scan-view/ScanView.py
/usr/local/heroku/node_modules/node-gyp/gyp/gyptest.py
/usr/local/heroku/node_modules/node-gyp/gyp/buildbot/buildbot_run.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/input.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/win_tool.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/MSVSVersion.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/flock_tool.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/__init__.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/xcode_ninja.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/common.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/generator/android.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/generator/analyzer.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/generator/cmake.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py
/usr/local/heroku/node_modules/node-gyp/gyp/pylib/gyp/generator/dump_dependency_json.py
/usr/local/heroku/node_modules/node-gyp/gyp/tools/pretty_gyp.py
/usr/local/heroku/node_modules/node-gyp/gyp/tools/graphviz.py
/usr/local/heroku/node_modules/node-gyp/gyp/tools/pretty_sln.py
/usr/local/heroku/node_modules/node-gyp/gyp/tools/pretty_vcproj.py
```

**Comment by looooo** [comment]
there are still two files not parseable on windows:

```
##############################
2 python files are not parseable:
1 invalid syntax (C:/projects/freecad/build/Mod\Import\SCL\Part21.py, line 127)
2 invalid syntax (C:/projects/freecad/build/Mod\Import\SCL\SimpleReader.py, line 80)

```

**Comment by looooo** [comment]
> This depends on what App.getHomePath() delivers.

I think the windows check differs a bit from osx/linux. Maybe this is because on windows no `make install` is called.

**Comment by looooo** [comment]
i think this is ready.

**Comment by wwmayer** [comment]
Merged.

**Comment by looooo** [comment]
@wwmayer I still have to failing tests in windows. I don't know why it works for linux and not for windows...:

##############################
2 python files are not parseable:

1 'charmap' codec can't decode byte 0x81 in position 30236: character maps to <undefined>
 in file: C:/Users/katja/Miniconda3/envs/freecad/Library/Mod\PartDesign\WizardShaft\Shaft.py
2 'charmap' codec can't decode byte 0x8d in position 625: character maps to <undefined>
 in file: C:/Users/katja/Miniconda3/envs/freecad/Library/Mod\Test\UnicodeTests.py

**Comment by wwmayer** [comment]
For Py2 I don't get any failures and with Py3 it works as long as encoding is set to utf-8. When I omit the encoding parameter then it fails for me too with similar error messages that you get.

**Pull request closed without merging**
