### PR TITLE
Gui: Revert PR #4626 (c62239d0b) Tree View Reorder

### PR DESCRIPTION
**Pull request by chennes**
Users on the forums have identified some serious issues with PR #4626: this commit comments out the key changes so that the original author can look into the issues. When necessary the original code is also restored. Note that a standard `git revert` was unsuccessful due to intervening changes to the codebase, so this was created manually.

See https://forum.freecadweb.org/viewtopic.php?p=548606

### CODE REVIEW

**Comment by chennes** [comment]
See #5195

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5192">pipeline status</a> for feature branch [PR_5192](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5192). Pipeline [414384470](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/414384470) was triggered at [bc17027](https://github.com/FreeCAD/FreeCAD/pull/5192/commits/bc17027234fe0a6f30e7d861a806be2e79ab6bc7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@looooo perhaps if/after this PR is merged, we should push a new batch of Weekly bundle builds ?

**Comment by chennes** [comment]
Rather than merge this PR, I figured out the conflict in `git revert` and did that instead. So PR #4626 has been reverted by commit c9a74d4. @looooo if you feel it's appropriate, we could issue a new Weekly now so the issue introduced does not propagate any further.

**Pull request closed without merging**
