### PR TITLE
FEM: raise an exception if no valid object is selected

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by chennes** [comment]
This CI failure looks like a temporary glitch, right? @0penBrain ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8421">pipeline status</a> for feature branch [PR_8421](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8421). Pipeline [774318549](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774318549) was triggered at [4315b21](https://github.com/FreeCAD/FreeCAD/pull/8421/commits/4315b214507757c0adaf4e94f8962eae7f140b5a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@chennes Guess so. :) Feel free to re-run. ;)

**Comment by wwmayer** [comment]
That installing the packages fails we have sometimes seen in the past.

**Pull request merged**
