### PR TITLE
 BOM generation bugfix: Columns are persistent and .doCommandEval dependency circumvented backport as per #18615

### PR DESCRIPTION
**Pull request by Demolux**
See #18615

### CODE REVIEW

**Comment by maxwxyz** [comment]
This is https://github.com/FreeCAD/FreeCAD/pull/18615 against 1.0 branch

**Comment by chennes** [comment]
This needs to be cherry-picked -- we should consider cherry-picking the pre-commit fix to the translation as well. @yorikvanhavre what do you think about doing that?

**Comment by maxwxyz** [comment]
@adrianinsaval already cherry picked `8a7397cfbde68b5d29a7e04ddb7c4f2d12c94506`, in discussion is the pre-commit update of the translation files.

**Comment by adrianinsaval** [comment]
d1707fdf10e0468155bf57ace64e219e2ab17b7e

**Comment by maxwxyz** [comment]
@yorikvanhavre what is the verdict here?

**Comment by adrianinsaval** [comment]
precommit is backported too now d9e8fe0d7d99fd48fdeb5a0f6da5790ae3f54b69

**Pull request closed without merging**
