### PR TITLE
Sketcher: Changes override draw style when entering sketch edit mode.

### PR DESCRIPTION
**Pull request by maxwxyz**
Fixes https://github.com/FreeCAD/FreeCAD/issues/13989
And reverts changes from https://github.com/FreeCAD/FreeCAD/pull/14013 as this did not solve https://github.com/FreeCAD/FreeCAD/issues/13989 This solution works in all themes and with all colors and shininess values without making the document darker or changing light direction.

The idea is:
- change to the override draw style `No Shading` when entering a sketch. Therefore, no light needs to be changed and the sketch is always visible
- change back to the previous override draw style when leaving the sketch

A new preference is introduced: `Disable shading in edit mode`, default activated.
If this setting is checked, the override draw style switches to `No Shading` when entering the sketch edit mode.
The previous override draw style is stored and applied when leaving the sketch edit mode.

Demo:

https://github.com/FreeCAD/FreeCAD/assets/6246609/b82f8f62-b75c-466d-bbc0-2ea5533d7937

@FreeCAD/design-working-group FYI

### CODE REVIEW

**Comment by Syres916** [comment]
@maxwxyz to fix the crash on Linux I changed line 3230 in _src/Mod/Sketcher/Gui/ViewProviderSketch.cpp_ from:

`        Gui::MDIView* mdi = Gui::Application::Instance->editViewOfNode(editCoinManager->getRootEditNode());`

to:

```
        Gui::Document* doc = Gui::Application::Instance->activeDocument();
        Gui::MDIView* mdi = doc->getActiveView();
```

Now whether that's the correct way to fix it is another story.

The only downside to your fix is when using OVP to create say a rectangle I loose the visibility of the actual lines during the creation phase, the dimensional guides are visible but not the by default white geometry lines so we'll see what the other feedback is.

**Comment by maxwxyz** [comment]
@Syres916 thanks this seems to fix it. What do you mean with OVP visibility? 
It looks like this on my system:
grafik

**Comment by Syres916** [comment]
All my testing is only done using new user default settings, the last screenshot in your last post looks close to default but my default geometry colour is white and the face of my solid behind is very light so I can't see the geometry, it feels like a guess as to where it is. Once the geometry is created it's appears which is bizarre because they are supposed to be the same colour to the best of my knowledge.

**Comment by maxwxyz** [comment]
Changed it to use a preference `Disable shading in edit mode`, default activated.
If this setting is checked, the override draw style switched to `No Shading` when entering the sketch edit mode.
The previous override mode is stored and applied when leaving the sketch edit mode.

Please test. The line color is a different topic and should be set to a better default, as it's done in the themes.

**Comment by Syres916** [comment]
> Please test. 

The check box is working as expected but obviously the usability from the point of view of not seeing the geometry during creation is still an issue for me. Could @FEA-eng @0penBrain please test, some other users input really would be useful at this stage.

**Comment by 0penBrain** [comment]
I may eventually test later.
Anyway, I had a quick look at the code and:
 * It uses parameter to store a temp value. This isn't purpose of parameters and should be avoided.
 * I don't understand why it plays with `OverrideMode` at Viewer level while it seems more appropriate to do it at ViewProvider level.

**Comment by maxwxyz** [comment]
@0penBrain thank for the feedback. I'm no expert so help is welcomed. How could I store the last override mode so I could access it when leaving the sketch? I've looked at how the toolbar button works, if it's better at ViewProvider level, it can be changed.

**Comment by 0penBrain** [comment]
@maxwxyz ,as you can see here, VP has functions to manage the display modes at object level (never used them though) : https://github.com/FreeCAD/FreeCAD/blob/958d83ed06ca32294227b4e1270cf41c838962e5/src/Gui/ViewProvider.h#L407-L408
Maybe it's even possible that a sketch only has one display mode and so you don't need to temporarily store another one.
And if you need it, you can use a private variable of the VP.

**Comment by maxwxyz** [comment]
@0penBrain I don't want to alter the individual objects at their level but use the overall override mode (as if you switch the toolbar button for override to `No shading` when the sketch is active, and back to the last state when leaving the sketch). 
I'm not sure how to get the sketch to have it's own display mode. The current code also uses a parameter for storing the previous state so I thought that's the way to go.

**Comment by 0penBrain** [comment]
> @0penBrain I don't want to alter the individual objects at their level but use the overall override mode (as if you switch the toolbar button for override to `No shading` when the sketch is active, and back to the last state when leaving the sketch). I'm not sure how to get the sketch to have it's own display mode. The current code also uses a parameter for storing the previous state so I thought that's the way to go.

Ok, that's a bit different behavior. But anyway you can use a private VP variable to temporarily store the current mode. ;)

**Comment by FEA-eng** [comment]
Nice, for me (Ubuntu, classic theme) it works as expected.

**Comment by Syres916** [comment]
> Ok, that's a bit different behavior. But anyway you can use a private VP variable to temporarily store the current mode. ;)

Surely that wouldn't work if there was a crash in Edit Mode. New users with iffy graphics cards/drivers tend to be able to create some geometry before Coin causes a crash.

**Comment by Syres916** [comment]
> Nice, for me (Ubuntu, classic theme) it works as expected.

Cheers, I'll try Fedora and Linux Mint 21.3 tomorrow, I've been using Debian 12.4 so far.

**Comment by 0penBrain** [comment]
OK, I don't know exactly how I'm supposed to test (probably because I'm not clear about the problem being solved and how the PR tries to handle it), but what I can say is that when sketching with an object in the background, the preview geometries are almost invisible :confused

image

**Comment by 0penBrain** [comment]
BTW, isn't that a bit weird that not always the same colors are used ?

image

**Comment by maxwxyz** [comment]
I did not change colors, that's an OVP issue then. Can you ry with a different theme, it looks like it's only a problem in classic, my Screenshots are above.

**Comment by 0penBrain** [comment]
> I did not change colors, that's an OVP issue then. Can you ry with a different theme, it looks like it's only a problem in classic, my Screenshots are above.

Same with all themes.

**Comment by 0penBrain** [comment]
> Surely that wouldn't work if there was a crash in Edit Mode.

Not sure what you expect not to work :confused:

**Comment by Syres916** [comment]
Probably best for me to just wait for the final code and test it on my faithful old Tosh laptop which usually misbehaves in Edit Mode.

**Comment by maxwxyz** [comment]
> OK, I don't know exactly how I'm supposed to test (probably because I'm not clear about the problem being solved and how the PR tries to handle it), but what I can say is that when sketching with an object in the background, the preview geometries are almost invisible 😕
> 
> image

could you please post a screenshot how it looks on your system with the current main or last weekly? It looks do different on mine.

**Comment by maxwxyz** [comment]
so your demo wasn't with this PR?

**Comment by 0penBrain** [comment]
Oh yes, sorry it was. Wasn't it rebased ?

**Comment by maxwxyz** [comment]
So the issue with the dimmed lines / OVP is resolved by https://github.com/FreeCAD/FreeCAD/pull/14496 so this PR is ready from my side.

**Comment by 0penBrain** [comment]
I'm still not sure why to use a parameter to store a temporary value. But anyhow I'm not strongly opposed to merge.

**Comment by Syres916** [comment]
I updated to Git Revision 37817 and then applied the PR changes to that, deleted my config files and started FC. I only changed nav mode to TouchPad and created a Part>Cube. Created a sketch on the top plane face of the cube and the invisible geometry creation lines is still an issue for me. So whether myself and 0penBrain are the exceptions to the norm I can't say but we've given our feedback.

```
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37817 (Git)
Build type: Release
Branch: main
Hash: 4a11652263c8635da0be55e41c0a5a9d04767dcf
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Curves 0.6.37
  * SheetMetal 0.4.15
```

**Comment by maxwxyz** [comment]
the lines should be fixed by @PaddleStroke in https://github.com/FreeCAD/FreeCAD/pull/14496 
Maybe the themes need a different default colors for sketch lines if they are too similar to the geometry shape color @MisterMakerNL ?

**Comment by PaddleStroke** [comment]
When I fixed the 2 default colors for OVP, I used the light gray not the dark gray (I had to choose one so I used the one most widely used). But from the screenshot of this PR it seems that I might have had to choose the dark gray?

Perhaps the issue I fixed came from someone previously trying to change the default value of the gray to a darker gray, but this person failed to modify the light gray in other places.

If we need to change to the darker gray please let me know and I'll update the color.

**Comment by Syres916** [comment]
> If we need to change to the darker gray please let me know and I'll update the color.

Done, https://github.com/FreeCAD/FreeCAD/pull/14763

**Comment by FEA-eng** [comment]
Was this change reverted by some of the recent PRs? Maybe Materials stuff? The geometry is almost invisible for me again.

geom

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38375 (Git)
Build type: Release
Branch: main
Hash: fe702349e848571802c01659668cc4bee519f4c6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

**Comment by maxwxyz** [comment]
@FEA-eng in this one it was fixed: https://github.com/FreeCAD/FreeCAD/pull/14763
but it was reported again in https://github.com/FreeCAD/FreeCAD/issues/15667

**Comment by FEA-eng** [comment]
> @FEA-eng in this one it was fixed: #14763 but it was reported again in #15667

Ok, but #15687 which will close #15667 doesn’t seem to fix it as it only mentions switching from non-default themes, not the default behavior in the Classic theme. So maybe #13989 should be reopened or #15667 kept open even after the aforementioned PR is merged.

**Comment by Syres916** [comment]
There is no mention of non-default theme, it states from another theme which includes the two other core themes. Test/developers are a special case at the moment so the advice will be to change to FreeCAD Light and then back to FreeCAD Classic.

**Pull request merged**
