### PR TITLE
Topo Naming PR 2

### PR DESCRIPTION
**Pull request by realthunder**
This is the second batch of patches for the new Topo Naming of geometry elements. It adds code to the features from Part workbench for generating Topo Naming using the new APIs. At this stage, the end-user can see the new Topo Naming in action by testing various features from Part workbench. Only features from Part workbench are supported. And if sketch is involved (e.g. Extrusion from a sketch), then try not to modify the sketch for the purpose of Topo Naming testing until the next batch of patches is in.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7435">pipeline status</a> for feature branch [PR_7435](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7435). Pipeline [630379532](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/630379532) was triggered at [7851fcc](https://github.com/FreeCAD/FreeCAD/pull/7435/commits/7851fcc1bbda5fdea274b0f44be02d670b3fc959). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7435">pipeline status</a> for feature branch [PR_7435](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7435). Pipeline [630680901](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/630680901) was triggered at [54411f3](https://github.com/FreeCAD/FreeCAD/pull/7435/commits/54411f3661ac18e911c8f734c04304b1e63201d2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
I will merge now and make the announcement hopefully next Sunday when am back home.

**Comment by donovaly** [comment]
The CI reports some things that might be of interest, see section "Unchanged files with check annotations":
`https://github.com/FreeCAD/FreeCAD/pull/7435/commits/54411f3661ac18e911c8f734c04304b1e63201d2`
Can you please have a look if some of them should be addressed?

**Comment by realthunder** [comment]
Not sure about the relationship of that specific commit with this `Unchanged files with check annotations`. That commit is a quick fix of a compilation error [reported](https://forum.freecadweb.org/viewtopic.php?f=44&t=71601) by a user. But it seems @wwmayer has a better fix, but still waiting for user response.

**Comment by luzpaz** [comment]
For those on Linux who are OK with using Snap packages, it's possible to test @realthunder's toponaming patches via:
`snap refresh freecad --channel='latest/edge/toponaming'`  
When you want to switch back to 'edge' you can utilize `snap refresh freecad --channel='latest/edge'`

**Pull request merged**
