### PR TITLE
Core: Fix searching model tree does not work for numbers #12723

### PR DESCRIPTION
**Pull request by farleyrunkel**
As discussed in #12723, the issue of searching for numeric strings in the document tree not working is caused by **ExpressionTokenizer::perform**, which trims the trailing integer from input string.

### CODE REVIEW

**Review by maxwxyz — CHANGES_REQUESTED** [review]
It accepts integers now but the search is not perfect.
only a "0" has no results, "01" also no results. "00" works but typing "001" entirely also has no results.
It's better than before but not fully functional.
grafik

**Comment by FarleyRunkel** [comment]
Ok, I'll fix it more comprehensively.

**Comment by FarleyRunkel** [comment]
Hello, @maxwxyz, I retested your example on my computer, and everything seems to be working fine. Could you please test it again and see what happens?
幻灯片1

**Review by maxwxyz — APPROVED** [review]
Works great, thanks!

**Pull request merged**
