### PR TITLE
Attacher11 - numerous changes to datum feature attachment

### PR DESCRIPTION
**Pull request by DeepSOIC**
* display attachment modes that can accept or need more references, together with hints
* change the way reference selection buttons behave (they now reflect the geometry type, and say "Selecting..." when reference is being selected in 3d view.
* expose full superPlacement instead of a limited set of offsets in UI
* add inertial attachment modes (center of mass, and principal axes)
* make read-onlyness of Placement and superPlacement in property editor
* other changes, mostly internal. See commits.

### CODE REVIEW

**Comment by DeepSOIC** [comment]
Bug detected: read-only status of Placement and superPlacement is incorrectly updated upon changes of unrelated properties.

**Comment by DeepSOIC** [comment]
fixed and rebased, forced update

**Comment by DeepSOIC** [comment]
Looks like cherry-pick went wrong... fixing...

**Comment by DeepSOIC** [comment]
OK, now it built fine on Travis. It failed some tests in FEM, which master fails too.

**Comment by wwmayer** [comment]
Merged.

**Comment by DeepSOIC** [comment]
Thanks!!

**Pull request closed without merging**
