### PR TITLE
Fix conversion of StandardButton enum and int

### LINKED ISSUE #14156: Possible regression in enum handling with pyside2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With the current set of packages on Arch Linux I get a SIGABRT when calling the "Involute Gear" command from PartDesign.

```
#0  0x00007ffff09c0e44 in ??? () at /usr/lib/libc.so.6
#1  0x00007ffff0968a30 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff09504c3 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff09503df in ??? () at /usr/lib/libc.so.6
#4  0x00007ffff0960c67 in __assert_fail () at /usr/lib/libc.so.6
#5  0x00007ffff0ed6734 in Shiboken::Enum::getValue(_object*) () at /usr/lib/libshiboken2.cpython-312-x86_64-linux-gnu.so.5.15
#6  0x00007ffff6bae0a4 in Gui::PythonWrapper::toEnum (this=0x7fffffff961b, pyPtr=0x7fff3c4d2610) at ../../src/Gui/PythonWrapper.cpp:592
#7  0x00007ffff6bae0d6 in Gui::PythonWrapper::toEnum (this=0x7fffffff961b, pyobject=...) at ../../src/Gui/PythonWrapper.cpp:601
#8  0x00007ffff699007b in Gui::TaskView::TaskDialogPython::getStandardButtons (this=0x55555a83aff0) at ../../src/Gui/TaskView/TaskDialogPython.cpp:739
#9  0x00007ffff6982922 in Gui::TaskView::TaskView::showDialog (this=0x555555f1db70, dlg=0x55555a83aff0) at ../../src/Gui/TaskView/TaskView.cpp:518
#10 0x00007ffff64aed84 in Gui::ControlSingleton::showDialog (this=0x555555dd6800, dlg=0x55555a83aff0) at ../../src/Gui/Control.cpp:170
#11 0x00007ffff6989aee in Gui::TaskView::ControlPy::showDialog (this=0x555555d3fd30, args=...) at ../../src/Gui/TaskView/TaskDialogPython.cpp:122
#12 0x00007ffff6992972 in Py::PythonExtension<Gui::TaskView::ControlPy>::method_varargs_call_handler (_self_and_name_tuple=0x7fff3c538200, _args=0x7fffeb6a5cf0) at ../../src/CXX/Python3/ExtensionOldType.hxx:309
#13 0x00007ffff30bd2ed in ??? () at /usr/lib/libpython3.12.so.1.0
#14 0x00007ffff309d50b in _PyObject_MakeTpCall () at /usr/lib/libpython3.12.so.1.0
#15 0x00007ffff2fa3dfa in ??? () at /usr/lib/libpython3.12.so.1.0
#16 0x00007ffff30ece06 in ??? () at /usr/lib/libpython3.12.so.1.0
#17 0x00007ffff6463d5b in Base::pyCall (callable=0x7fff3c5327c0, args=0x7fff3c531a00) at ../../src/Base/Interpreter.h:137
#18 0x00007ffff6ac65f4 in Gui::ViewProviderPythonFeatureImp::setEdit (this=0x55555a701100, ModNum=0) at ../../src/Gui/ViewProviderPythonFeature.cpp:371
#19 0x00007fff38fb5e9f in Gui::ViewProviderPythonFeatureT<PartGui::ViewProvider2DObject>::setEdit (this=0x55555a731d00, ModNum=0) at ../../src/Gui/ViewProviderPythonFeature.h:524
#20 0x00007ffff6a72951 in Gui::ViewProvider::startEditing (this=0x55555a731d00, ModNum=0) at ../../src/Gui/ViewProvider.cpp:134
#21 0x00007ffff6aa26e3 in Gui::ViewProviderDragger::startEditing (this=0x55555a731d00, mode=0) at ../../src/Gui/ViewProviderDragger.cpp:92
#22 0x00007ffff63d5c9e in Gui::Document::setEdit (this=0x5555584b1630, p=0x55555a731d00, ModNum=0, subname=0x0) at ../../src/Gui/Document.cpp:429
#23 0x00007ffff6455c1a in Gui::DocumentPy::setEdit (this=0x5555585b7820, args=0x7fff3c5318c0) at ../../src/Gui/DocumentPyImp.cpp:147
#24 0x00007ffff6451135 in Gui::DocumentPy::staticCallback_setEdit (self=0x5555585b7828, args=0x7fff3c5318c0) at src/Gui/DocumentPy.cpp:525
...
```

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37330 +20 (Git)
Build type: Debug
Branch: integration
Hash: 6af3ce7cabae0c114039c94219259017db042d04
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.3.0, OCC 7.3.0
Locale: German/Germany (de_DE)
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.62.0
  * Assembly3.backup1715897154.0970206 0.11.3 (Disabled)
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.2.0
  * fasteners 0.4.21
```

### Subproject(s) affected?

PartDesign

### Anything else?

The last Arch Linux updates to python 3.12 caused some problems with pyside2 because it's not officially supported. With some patches it works, but something has changed with the enum handling. 

This could be a regression from #13611. The `getStandardButtons` now returns a `QFlags<QMessageBox::StandardButton>` aka `QMessageBox::StandardButtons`, but the `Shiboken::Enum::check()` function returns false, triggering an assert in `Shiboken::Enum::getValue()`.

If I compile against Qt6 with pyside6, the assert is not triggered.

I haven't figured out who really caused this. It could be libshiboken, python 3.12, #13611 or a combination of those.

If I patch the `PythonWrapper::toEnum()`  function to
```
qsizetype PythonWrapper::toEnum(PyObject* pyPtr)
{
#if defined (HAVE_SHIBOKEN) && defined(HAVE_PYSIDE)
    auto longObj = PyNumber_Long(pyPtr);
    if (longObj) {
        long result = PyLong_AsLong(longObj);
        Py_DECREF(longObj);
        return result;
    }
    return Shiboken::Enum::getValue(pyPtr);
#else
    return toEnum(Py::Object(pyPtr));
#endif
}
```
it will work because flags are convertable to a number by `PyNumber_Long()`. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #14639: Comparison between integers and StandardButton fails for Python task dialogs with PySide6
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With PySide6, comparison between integers and StandardButton fails for Python task dialogs.
For example, in the Gmsh task panel, to make the button ` Apply` works again, I need to change:
```
 def clicked(self, button):
 if button == QtGui.QDialogButtonBox.Apply:
 ...
```
to:
```
 def clicked(self, button):
 if button == QtGui.QDialogButtonBox.Apply.value:
 ```

@wwmayer, maybe some relation with https://github.com/FreeCAD/FreeCAD/pull/13902? 

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37710 (Git)
Build type: Unknown
Branch: (HEAD detached at a6937d8d26)
Hash: a6937d8d2677594f548af218cc92f797d9a475d9
Python 3.12.3, Qt 6.7.1, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.5.17
  * OpenTheme 2024.4.20
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wwmayer**
* Fixes #14639
* Fixes #14156

### CODE REVIEW

**Comment by marioalexis84** [comment]
There is a crash in `tryFromEnum` function. Specifically in:
`return type.callMemberFunction("StandardButton", args);`

**Comment by wwmayer** [comment]
Hmm, do you have any more details about this crash?

**Comment by marioalexis84** [comment]
It seems even worse:
In Python task panels that have the `Apply` button, when I click any button (Apply, Close, or OK), the program crashes.
Here is the stack trace.
```
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3cae0) [0x7398b8e50ae0]
#1  /usr/lib/libpython3.12.so.1.0(PyFrame_GetCode+0x4) [0x7398bb06ec14]
#2  /usr/lib/libshiboken6.cpython-312-x86_64-linux-gnu.so.6.7(+0x33f98) [0x7398ba1fef98]
#3  /usr/lib/libshiboken6.cpython-312-x86_64-linux-gnu.so.6.7(mangled_type_getattro+0x139) [0x7398ba1ff369]
#4  /usr/lib/libpython3.12.so.1.0(_PyObject_LookupAttr+0x19c) [0x7398baf9abdc]
#5  /usr/lib/libpython3.12.so.1.0(PyObject_HasAttr+0x20) [0x7398baf48cf4]
#6  /usr/lib/libpython3.12.so.1.0(PyObject_HasAttrString+0x5b) [0x7398baf48d9f]
#7  0x7398be78891e in Py::Object::hasAttr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
#8  0x7398bf0d77ea in Gui::PythonWrapper::tryToStandardButton(long long) 
#9  0x7398bf0d7ac1 in Gui::PythonWrapper::toStandardButton(long long) f
#10  0x7398bee9c7c4 in Gui::TaskView::TaskDialogPython::clicked(int) 
#11  0x7398bee8f77a in Gui::TaskView::TaskView::clicked(QAbstractButton*)
```
As you can see, for any button, the method `clicked` is called (not `reject` `or accept`). Task panels without `Apply` button works normally (they call `reject` and `accept`).

The stack trace shows `Py::Object::hasAttr` in 7th line because I added it before `type.callMemberFunction("StandardButton", args)` to check if the attribute is ok.
With your original code, `Py::Object::callMemberFunction` is in the stack trace.
```
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3cae0) [0x7c5197250ae0]
#1  /usr/lib/libpython3.12.so.1.0(PyFrame_GetCode+0x4) [0x7c519946ec14]
#2  /usr/lib/libshiboken6.cpython-312-x86_64-linux-gnu.so.6.7(+0x33f98) [0x7c51991c0f98]
#3  /usr/lib/libshiboken6.cpython-312-x86_64-linux-gnu.so.6.7(mangled_type_getattro+0x139) [0x7c51991c1369]
#4  /usr/lib/libpython3.12.so.1.0(PyObject_GetAttrString+0xb3) [0x7c51993ad623]
#5  0x7c519cb8895c in Py::Object::getAttr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const from /home/mario/Downloads/FreeCAD-test/lib/libFreeCADGui.so+0x36
#6  0x7c519d17e287 in Py::Object::callMemberFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Py::Tuple const&) const
#7  0x7c519d4d781e in Gui::PythonWrapper::tryToStandardButton(long long) 
#8  0x7c519d4d7a1b in Gui::PythonWrapper::toStandardButton(long long) 
#9  0x7c519d29c7c4 in Gui::TaskView::TaskDialogPython::clicked(int) f
#10  0x7c519d28f77a in Gui::TaskView::TaskView::clicked(QAbstractButton*)
```
Also, if close panels from command line with `Gui.Dialog.closeDialog` and try to open a new panel, an error occurs:
`Active Task Dialog found! Please close this one before opening  a new one!`

Maybe undefined behavior?

**Comment by wwmayer** [comment]
IMO there is something wrong with shiboken or PySide for newer versions. With the shiboken/PySide wrappers for Qt5 and Qt 6.2 everything works perfectly for me.

However, my MSYS2 environment offers Qt 6.7 with the corresponding shiboken/PySide versions and for them I also do get these crashes.

Now I was able to implement a solution by avoiding the Python C API but using Python code and there I got it working.

**Comment by marioalexis84** [comment]
It works for me too.
Why does it work by passing the code to the interpreter? I would have assumed that in the background the same functions are executed

**Comment by wwmayer** [comment]
> Why does it work by passing the code to the interpreter? I would have assumed that in the background the same functions are executed

I don't know. A debug version of the libs is needed to figure that out.

**Comment by chennes** [comment]
Would you prefer to hold merge on this PR until that is figured out, or should we merge the current workaround?

**Comment by wwmayer** [comment]
> Would you prefer to hold merge on this PR until that is figured out

What for? The crash above most likely is related to some quirks in the shiboken code.

The first commit of this PR fixes a possible crash in https://github.com/FreeCAD/FreeCAD/issues/14156 that happened due to the failing `assert(Shiboken::Enum::check(obj))` inside `Shiboken::Enum::getValue`. For me it worked correctly but only because shiboken wasn't built with debug information (which turns the assert into a NOP). When I changed the code to
```
if (Shiboken::Enum::check(obj)) {
    return Shiboken::Enum::getValue(obj);
}
```
it didn't work any more because check() returns false. So, it means that getValue() does the right thing but check() claims it's of the wrong type.

This means there are inconsistencies in the shiboken implementation and I assume that's also the case for the crash of the 2nd part of this PR.

**Pull request merged**
