### PR TITLE
[TD]fix face colour preference ignored issue #9976

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for issue #9976 

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by benj5378** [comment]
@WandererFan I have a better fix for this upcoming also simplifying stuff in Preferences. Just ran into some issues with base functionality

**Comment by benj5378** [comment]
#9979

**Comment by WandererFan** [comment]
So why is #9979 better?  

It brings in 2 changes that aren't related to issue #9976
- changing App::Color interpretation of transparency, which potentially affects everywhere App::Color is used, and 
- removes the ability to specify see-through faces (at least I don't see how to specify it) by removing the "transparent faces" option.

**Comment by benj5378** [comment]
@WandererFan Transparency is now an alpha value inside the color picker. That IMO simplifies color handling in code.

> changing App::Color interpretation of transparency, which potentially affects everywhere App::Color is used, and

This change would have to be done anyway at some point.

**Comment by WandererFan** [comment]
see comments about transparency in PR9979.  In this case,  transparency refers to an empty fill,  rather than a shaded colour.

**Pull request merged**
