### PR TITLE
Update of PLY to 3.11

### PR DESCRIPTION
**Pull request by KeithSloan**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
I don't understand why Ply is included in the source of FreeCAD. Shouldn't it be an external dependency?

**Comment by KeithSloan** [comment]
importCSG.py uses PLY  as it needs to parse CSG files. Before it was even part of FreeCAD (many many years ago)as a result an early version was supplied as part of the Mod/OpenSCAD directory. 

As you say it should be an external dependency. 

If I look at the OpenSCAD directory in
freecad OS: Ubuntu 18.04.3 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.3.
Build type: Release
Python version: 3.6.8
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

It is not there and yet it works so I can only assume that somehow it installed on my system at least.

This is the reported bug that I was attempting to resolve by supplying an updated version of PLY
https://freecadweb.org/tracker/view.php?id=4228

**Comment by vocx-fc** [comment]
Honestly, this sounds like the wrong approach to solve this issue. This is a Python dependency that should be provided by the operating system, not by FreeCAD itself. It may be necessary to include it in a distribution package if it's not easily installable, maybe in Windows and the AppImage, but regular Linux distributions should have it in their repositories.

I remember the case in the forum that somebody was getting a report view message about a missing `ply` package. I just told them to install `python3-ply`, and that made it work. I had no idea it was supposed to be included in FreeCAD itself.

If you do a reverse lookup for the `python3-ply` package, you can see which packages depend on this one.
```bash
apt-cache rdepends python3-ply

python3-ply
Reverse Depends:
  bind9utils
  bind9utils
  xonsh
  python3-yaql
  python3-thriftpy
  python3-slimit
  python3-pysmi
  python3-phply
  python3-lesscpy
  python3-jsonpath-rw
  python3-dolfin
  nml
  gitsome
```

If you have installed any of these packages, you already have `ply`. Also, these packages may have been installed as part of another package.

Can you open a thread in the forum to discuss this? I would propose to remove the `ply` directory inside OpenSCAD, and instead direct the users to install it themselves in their system.

**Comment by KeithSloan** [comment]
"Honestly, this sounds like the wrong approach to solve this issue"

I am getting P**SED off with this attitude.

OpenSCAD was developed years ago as something that could be added to FreeCAD before ply could be installed as a linux package and that is how it got included in the OpenSCAD directory. On the basis that if it ain't broke don't fix that is where it stayed. We

I agree that it should not be supplied and should be installed as a FreeCAD prereq. As OpenSCAD has been part of FreeCAD since 0.13. So who ever maintains the prereq's should be adding ply and then it can be removed. It should NOT be the case that people are told to install ply separately it should be included when they install using any of the standard install procedures.

**Comment by vocx-fc** [comment]
>On the basis that if it ain't broke don't fix that is where it stayed.

This isn't the basis to develop things properly.

>So who ever maintains the prereq's should be adding ply and then it can be removed. It should NOT be the case that people are told to install ply separately

Well, obviously. The software doesn't tell people to install Qt, but whichever package of FreeCAD you install will automatically include it. This is no different. Of course `ply` will be added as a dependency. That's exactly what I'm saying.

But in the case FreeCAD is installed from source, obviously the user has to install this dependency first. As a matter of fact, this is already considered in the [CompileOnUnix](https://www.freecadweb.org/wiki/CompileOnUnix#Python_3_and_Qt5) instructions, at least for the Debian/Ubuntu section.

Still, the OpenSCAD workbench could check that `ply` is present, and if it's not, it could warn the user about installing it. This isn't hard to do, and it's something other Python workbenches do as well.

I don't understand why you get pissed off so easily. It's like you don't understand what I am telling you and you decide to interpret things in a strange way.

**Comment by yorikvanhavre** [comment]
In any case, PLY was already part of FreeCAD so this PR makes sense as it only updates it. Indeed at some point it would be good to remove it...

**Comment by KeithSloan** [comment]
Okay if PLY is already part of FreeCAD I will remove it. I agree that is the way it should be. The only reason it was in OpenSCAD directory was historical and dates back to before OpenSCAD was made part of FreeCAD 0.13

**Comment by vocx-fc** [comment]
Forum thread: [Discussion: removing Ply from FreeCAD's source code](https://forum.freecadweb.org/viewtopic.php?f=10&t=42476)

**Pull request merged**
