### PR TITLE
Feature/tree document view configuration

### PR DESCRIPTION
**Pull request by mlampert**
This change adds a submenu to the "View" menu which provides 3 options for the document tree widget:
- only show the currently active document (the default - see below)
- show all documents (what it used to be)
- expand the currently active document and collapse all others

There have been several discussions in the forum around this topic the latest comment from sliptonic pointing out that the multi document view is rather confusing to novices. I'm very wary of changing existing behaviour but it is less likely for a novice to find the setting in the View menu than it is for power users.

Additionally - I will give heads up in the forum once the change is merged (and the single document default is still in place).

### CODE REVIEW

**Comment by triplus** [comment]
I am not against or for this change. Just one opinion i feel i should share.

This likely could be a bit premature. As basically as soon as the Link functionality is made available. End users will for sure start to do more Drag&Drop actions in the tree view. Between features available in the different documents. And if by default this experience won't be possible (end user will need to enable it). That could make things confusing for new users too.

Said that i am OK with whatever happens next.

**Comment by Jee-Bee** [comment]
Since drag and drop == ctrl+c and ctrl+v there shouldn't be a difference  with whatever preference is choosen

**Comment by triplus** [comment]
Well you have to be able to select it first. To do Drag&Drop, Ctrl+C, Ctrl+V. And for being able to select it in tree view you will now need to enable support for that first by right clicking to open a menu, going in View and selecting the show all documents option.

**Comment by mlampert** [comment]
So you think finding a first level menu item is a more advanced user skill than using multiple documents?

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
