### PR TITLE
source typo fixes pt6

### PR DESCRIPTION
**Pull request by luzpaz**
issue #2914

### CODE REVIEW

**Comment by luzpaz** [comment]
Please wait on merging this commit.

**Comment by luzpaz** [comment]
Good to go. Note: I accidentally fixed a typo in a 3rd party file but that is really a non issue. Our you prefer I can resubmit PR without it.

**Comment by luzpaz** [comment]
Ok forced push without 3rd party typo fix.

**Comment by yorikvanhavre** [comment]
merged

**Pull request closed without merging**
