### PR TITLE
FEM: Fix color legend range bug

### LINKED ISSUE #15013: FEM: Manual range specification for the color legend stopped working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I've noticed the following regression (it works in 0.21.2) - it's not possible to manually specify the range for the color legend anymore - just nothing happens and the values are reset.

0.21.2:
legend range 0 21 2

0.22:
legend range 0 22

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
Fixes #15013

@marioalexis84 FYI

### CODE REVIEW

**Comment by FEA-eng** [comment]
@FreeCAD/maintainers This is good to go and fixes a nasty FEM bug, please merge it.

**Comment by marioalexis84** [comment]
@FEA-eng I have not yet approved this change because it introduces a regression with this issue https://github.com/FreeCAD/FreeCAD/issues/13695.
I will try to fix both in the next few days.

**Comment by yorikvanhavre** [comment]
Waiting for @marioalexis84 's further fix

**Comment by FEA-eng** [comment]
Closing in favor of #15476

**Pull request closed without merging**
