### PR TITLE
[PD] Fixes related to additive loft

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
See https://forum.freecadweb.org/viewtopic.php?f=3&p=542808&t=63252.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
Currently only fixes the temporary preview while in the task. Everything becomes invisible after clicking OK.

**Comment by donovaly** [comment]
This change seems reasonable, however it does not fix the bug completely as you wrote: https://forum.freecadweb.org/viewtopic.php?f=3&t=63252&p=544848#p544655

However, there is a general visibility issue with lofts we need to fix:
https://forum.freecadweb.org/viewtopic.php?f=3&t=63252&p=544860#p544860

Then maybe this PR is not necessary.

**Comment by AjinkyaDahale** [comment]
> Then maybe this PR is not necessary.

Possibly. But it does fix a particular issue, and I plan to add more commits to fix visibility. I'm having a hard time finding the exact place that handles the 3d view however, particularly for loft.

**Comment by donovaly** [comment]
Many thanks. For the backportability, can you please open a separate PR for the new feature and one for the pure bugfix?

Besides this, before adding new issues, I think the not yet understood problems with the visibility should be resolved. I opened therefore this thread: https://forum.freecadweb.org/viewtopic.php?f=10&t=63531

I like you feature addition but I think loft and pipe should get it too via a further separate PR.

**Comment by donovaly** [comment]
PR #5149 supersedes in my opinion the first commit to this PR since it fixes both reported issues in this thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=63252

When you can confirm, let's open a new PR for the Loft-from-Solid-Face issue of your second commit.

**Comment by AjinkyaDahale** [comment]
> Many thanks. For the backportability, can you please open a separate PR for the new feature and one for the pure bugfix?
> 

I was thinking these fixes might be related to one another. So I wanted to keep the commits together for until the picture is clearer. Appears you fixed the visibility issues however, so I'll change accordingly.

> Besides this, before adding new issues, I think the not yet understood problems with the visibility should be resolved. I opened therefore this thread: https://forum.freecadweb.org/viewtopic.php?f=10&t=63531
> 
> I like you feature addition but I think loft and pipe should get it too via a further separate PR.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5147">pipeline status</a> for feature branch [PR_5147](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5147). Pipeline [403877051](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/403877051) was triggered at [2d02cdf](https://github.com/FreeCAD/FreeCAD/pull/5147/commits/2d02cdf7f6aa300439165a6ed57c840beac56866). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by AjinkyaDahale** [comment]
Closing since it is superseded by #5149 and a future PR for supporting solid faces.

**Pull request closed without merging**
