### PR TITLE
Addon Manager: Show involved branches' names on branch change operation

### LINKED ISSUE #12969: [Feature] Addon Manager: Experimental 'Change branch' dialog could report what branch checking out and which one we're migrating away from
**Is your feature request related to a problem? Please describe.**
The experimental 'change branch' functionality could be a little more UX friendly by letting us know what it specifically did

**Describe the solution you'd like**
```
Branch change succeeded
Moved from <branch> to <new_branch>
Please restart to use the new version
```

**Additional context**

https://github.com/FreeCAD/FreeCAD/blob/c2055689a593347c507101e9daf31be760abd2a9/src/Mod/AddonManager/package_details.py#L644

### PR DESCRIPTION
**Pull request by hasecilu**
Screenshot_2024-09-18_12-30-12

Edit: want html tags to show branches on _italic_?

Fix #12969

### CODE REVIEW

**Comment by chennes** [comment]
> Edit: want html tags to show branches on _italic_?

Many of our translators hate HTML tags, so I wouldn't. I think it's fine as-is.

**Comment by luzpaz** [comment]
Instead of emphasis, perhaps something like: 
>...
Moved
from: <master>
to: <other-branch>
branch

**Comment by hasecilu** [comment]
> Instead of emphasis, perhaps something like:
> 
> > ...
> > Moved
> > from: <master>
> > to: <other-branch>
> > branch

The lines separation seems fine. Doy you agree @chennes?

**Comment by luzpaz** [comment]
@kaktusus can you weigh-in regarding from a translators POV ?

**Comment by luzpaz** [comment]
I don't want to block the PR due to cosmetic issues. Feel free to merge as it is and we can discuss modifications later.

**Comment by hasecilu** [comment]
As translator I prefer a single multi-line string, I don't like when multi-line dialogs are split on several lines. Some branch names could be somewhat long so I think using break lines goes fine.

**Comment by hasecilu** [comment]
Now requires re-translation.

**Comment by chennes** [comment]
> I don't want to block the PR due to cosmetic issues. Feel free to merge as it is and we can discuss modifications later.

There is no rush, we haven't really started merging post-1.0 PRs, we've all got our hands full doing the 1.0 release.

**Comment by kaktusus** [comment]
> @kaktusus can you weigh-in regarding a translators perspective ?

Less skilled translators have a big problem with this. :smirk:
Extraneous code makes readability worse especially if there is a lot of it.

I know that some of you _( developers)_ get around this problem by providing html photmatting without tags in the translation string.
The only thing I can think of now is to exclude html tags from the extraction string.

**Pull request merged**
