### PR TITLE
Path: Avoid unnecessary returns to origin mid-Op and Make Valid Holes Drillable

### PR DESCRIPTION
**Pull request by jimzim111**
This changes Path.Op.Area:_buildPathArea to update its endVector only if the current toolpath segment produced any movement.  If it didn't produce any movement, then the end_vector defaults to (0,0,0) which would cause the next segment to move to (0,0,0) unnecessarily.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8846">pipeline status</a> for feature branch [PR_8846](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8846). Pipeline [803418418](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/803418418) was triggered at [4fa60c6](https://github.com/FreeCAD/FreeCAD/pull/8846/commits/4fa60c69d245c7f1812fb304496f00c440184a54). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
Is there an existing issue?  If not, please link to a forum post where this was discussed.

**Comment by jimzim111** [comment]
Sure, this is to address the symptoms described in https://forum.freecad.org/viewtopic.php?style=5&p=666869#p666869.  I just added a more detailed explanation there of what I think is going on and this proposed fix, along with screenshots of before/after.  Let me know anything else that'd be helpful.  Thanks!

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8846">pipeline status</a> for feature branch [PR_8846](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8846). Pipeline [815134507](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/815134507) was triggered at [2caa270](https://github.com/FreeCAD/FreeCAD/pull/8846/commits/2caa270b017b70d6512699b8dc2935adaa34fbf2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8846">pipeline status</a> for feature branch [PR_8846](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8846). Pipeline [816470410](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/816470410) was triggered at [18d5a11](https://github.com/FreeCAD/FreeCAD/pull/8846/commits/18d5a11d293a174627f5e7e1ac91dc9beb82c778). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by jimzim111** [comment]
Added a commit to fix some valid holes not being included in Drill/Helix Ops.  Detailed explanation at https://forum.freecad.org/viewtopic.php?style=5&t=77055.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8846">pipeline status</a> for feature branch [PR_8846](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8846). Pipeline [816494521](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/816494521) was triggered at [c07dfea](https://github.com/FreeCAD/FreeCAD/pull/8846/commits/c07dfea470dfcc248c76461126b1c1194ee1a885). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by jimzim111** [comment]
Closing this PR since it's gotten another change mixed in.  Will reopen as separate PRs...

**Pull request closed without merging**
