### PR TITLE
PartDesign: change default behavior of Thickness tool to inwards

### PR DESCRIPTION
**Pull request by FEA-eng**
https://forum.freecadweb.org/viewtopic.php?f=8&t=71856

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7488">pipeline status</a> for feature branch [PR_7488](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7488). Pipeline [639894748](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/639894748) was triggered at [5be90fa](https://github.com/FreeCAD/FreeCAD/pull/7488/commits/5be90fa67d41bdf531db1918e9627aad9713918b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Amended summary. Forced pushed changes.

**Comment by donovaly** [comment]
Thanks. However this does not fit then with the Part WB. In the part WB the default is outwards. So to make the change to inwards by default (which I support), we must adapt the Part WB at first.

**Comment by adrianinsaval** [comment]
Part WB is a little more complicated to do because it just does it with positive/negative values for the thickness, not a boolean property. We could have a hidden "reversed" that will be made true for old documents that are missing the property so they don't break and new it would be created as false for new ones.

**Comment by donovaly** [comment]
See https://forum.freecadweb.org/viewtopic.php?p=627063#p627063 and following. So let's take the opportunity and uniform the thickness too in part and PartDesign WB.

**Comment by sliptonic** [comment]
This has a minor merge conflict.  Please resolve it and we'll move ahead with merging.

**Comment by FEA-eng** [comment]
> I think the failure was introduced by another PR. Checking on it.

Right, checks passed now :-)

**Pull request merged**
