### PR TITLE
Add a new mode to PD patterns that will transform the base feature's shape instead of the tool shapes

### LINKED ISSUE #5678: Add Mirror body feature to PartDesign
Issue imported from https://tracker.freecad.org/view.php?id=2863

* **Reporter:** normandc
* **Date submitted:** 1/15/2017
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

The current ParDesign Mirrored feature only mirrors selected feature(s).

A new mirror feature that mirrors the whole body would be really useful in the design of symmetrical parts. At this time the Part Mirror tool can be used but it forces the user to leave the PartDesign workflow, requires an additional step of creating a Part Fuse, then having to import the resulting Fusion as a base feature inside a new Body.

The new "Mirror body" feature should automatically fuse the mirror copy to the main body to follow the single body rule.

# Additional information

I think this tool should not require a selection before launching it. It would simply take the active body, mirror it and fuse the copy, then add a "Mirror body" feature to the Body tree.

Maybe the existing "Mirrored" feature will need to be renamed to avoid confusion...

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by ickby 2017-01-16 09:58
I thought of extending the current transformation tools like mirror a bit. By default they would use the whole body instead to the selected features as currently. Than the feature list in the task dialog would be called "Restrict to following features:". 

Would you think this is intuitive, or is this too much functionality in the tools and would become confusing? I personally like having one tool for a operation and this tool to support specific subtasks, and "mirror" I would use for both, mirroring the whole part as well as individual features.

---

### Comment by thor 2017-01-16 16:48
Separate "mirror feature(s)" and "mirror body" would be OK, though increasing the number of menu and toolbar items is a drawback.

If it becomes integrated, I think it should be radio buttons for "Body" and "Feature(s)", the later followed by a list of the features. This way, it is spelled out what either does and it stays in line with how a user would likely describe the intention: either "I want to mirror the body", or "I want to mirror a feature (or features)", rather NOT "I want to restrict mirroring to the following feature(s)".

---

### Comment by Kunda1 2017-05-02 21:31
I asked Abdullah if
**can some of the mirroring code that you've implemented recently be leveraged against this feature (#2863) and also #2235 ?**

Abdullah's response:
**Not really. The mirror code I wrote is for sketcher geometry. This is the mirror of a part design feature. Has to be tackled in the Part Design WB.**

---

### Comment by abdullah 2017-06-02 13:55
Maybe also another related "feature option" (in addition to the ticket): Do a separate body that is symmetric to the original body and depending on it, so that the second can have some extra features but still change with the original one. In this case an automatic fuse is not desired, as they are intended as separate parts of an assembly.

---

### Comment by Kunda1 2017-06-02 14:03
Abdullah shall I open a new Feature Request then ?

---

### Comment by abdullah 2017-06-02 17:28
kunda1

I was weighting it, it that it is different, but unsure because it may be implemented together. Some hours later and after some sunshine I would say that: yes, please, open a new feature request and link it to this one as related. Thanks for keeping an eye ;)

---

### Comment by Kunda1 2017-06-02 17:41
Created  and linked #3067

---

### Comment by normandc 2017-06-17 23:33
Setting target version to 0.17 to make it appear in the roadmap, if it proves impractical we can always bump the target version.

---

### Comment by normandc 2018-11-17 20:25
ickby if you do not expect to return to PartDesign workbench development for the foreseeable future, wouldn't it be relevant to unassign this report and other PartDesign reports that were assigned to you?

### LINKED ISSUE #8439: [Problem] PartDesign: Mirror doesn't fail when Originals is emptied
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?p=660038#p660038

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Debian GNU/Linux bookworm/sid (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.21.0.15162 (Git shallow at #8430)
Build type: Unknown
Branch: master
Hash: c437b79adabb6a91e8fb6dc46729cb720ba16a5f
Python 3.11.1, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * sheetmetal 0.2.49
  * fc_nodes
  * A2plus 0.4.56
  * CurvedShapes 1.0.4
  * Curves 0.6.5
  * mooc-workbench
  * Render 2022.1.0
  * Plot 2022.4.17
  * lattice2 1.0.0
  * fcpd-workbench 0.2.0
  * Silk
  * Wood-Frame
  * Assembly4 0.11.12
  * fasteners 0.3.41
  * BIM 2021.12.0
  * Nodes 0.1.36
  * MeshRemodel 1.8919.0
  * ExtremeProLight 1.4.3
  * fcgear 1.0.0
  * SelectorToolbar
[/code]
```

### Subproject(s) affected?

PartDesign

### Issue description

When removing the Originals reference of a Mirror it still shows the previous computed shape without error.
Deleting the operation on which Mirror is based results in this case.

A "fail to recompute" message is expected.

### Anything else?

[mirror_issue.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/10714342/mirror_issue.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #11947: [Problem] PartDesign Mirrored should mirror everything given an empty .Originals
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Starting with the [box_pad_pocket.zip](https://github.com/FreeCAD/FreeCAD/files/13890630/box_pad_pocket.zip), the result depends on the order of the selection.

```
>>> # Gui.Selection.clearSelection()
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Box.')
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Pad.')
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Pocket.')
>>> ### Begin command PartDesign_Mirrored
```
image

```
>>> # Gui.Selection.clearSelection()
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Pocket.')
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Box.')
>>> # Gui.Selection.addSelection('box_pad_pocket','Body','Pad.')
>>> ### Begin command PartDesign_Mirrored
```

image

When the PartDesign_Mirrored Originals attribute is empty, it adds nothing due to [this](https://github.com/FreeCAD/FreeCAD/blob/d3049deaa9786817b829733fff1dddcf02675b06/src/Mod/PartDesign/App/FeatureTransformed.cpp#L169) (?). When Originals happens to be empty, Mirrored should instead behave as if `obj.Originals = obj.OutList[:-1][1:]` ie `obj.Originals = [<PartDesign::AdditiveBox>, <PartDesign::Pad>, <PartDesign::Pocket>]` for the box_pad_pocket example. This would be consistent with the other tools that have no Originals and transform the result of the prior tools. #8900 is due to `.Originals` being Fillet001 instead of everything (` [Pad ... Fillet001]`). With other PartDesign tools, "Pocket" refers to the result whereas for Originals, "Pocket" is the operation. If an empty `obj.Originals` was interpreted as `obj.OutList[:-1][1:]`, Mirrored would usually be easier to understand and use.

Screenshot from 2024-01-10 12-50-43

### Full version info

```shell
See screenshot above because the "Copy to Clipboard" button doesn't work.
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #12489: [Problem] Creating a symmetric Body in PartDesign is cumbersome or even impossible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When designing a symmetric part it is often advantageous to only model the symmetric half and then use a pattern to create
the final shape. After that non-symmetric features can be added.

Using the existing pattern tools makes this problematic or even impossible because they only work with additive/subtractive features and then pattern the tool shape (the shape that is added/subtracted). Having a long list of features it is cumbersome to select, esentially, all previous features. If some non additive/subtractive features are used (e.g. a pattern) that becomes then impossible.

Currently its possible to use the Part WB features to pattern the whole Body and then fuse it and use the result as a base feature
for a new Body. Then other features can be added. This results in lots of intermediary objects in the document and is not easy to use.

Let the pattern tools be able to pattern a whole shape not only a tool shape and the workflow becomes easier and more streamlined.

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36005 (Git)
Build type: Unknown
Branch: main
Hash: c4daf256b2eb41fd75f8344d27890c14e1bcae08
Python 3.11.7, Qt 5.15.12, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.60.0
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.0.0
  * Assembly3 0.11.3
  * fasteners 0.4.21
```

### Subproject(s) affected?

PartDesign

#### Related issues
There are multiple issues referencing the same problem but only for mirroring:
- #11947
- #8439 
- #5678
- #5705 

#### Example
@realthunder LinkMerge has a simmilar feature, a checkbox called "Transform sub-feature"
pd_transform

#### Solution
I have a working patch that adds a TransformMode property that allows switching between transforming the tool shapes and the normal shapes. I can create a PR after a bit of tweaking.

#### Points for discussion
In italic are my opinions.

- Implement new tools for this instead of changing the existing ones? _No, it will only confuse users what the differences between the tools are. This hurts discoverability_
- How to switch between the two modes?
   - A checkbox (LinkMerge)
   - A combobox (my TransformMode property)
   - An empty feature list (proposed in the above issues) _This is hidden to new users who don't already know about it_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NomAnor**
This allows applying the patterns to the whole base feature's shape. 
This makes it easier to design symmetric Bodies, especially if the feature list contains non-additive/subtractive features.

As mentioned in the issue, I think this requires some help on the UI side to make this new mode discoverable for the user.
Does someone have an idea for this?

This would resolve the following issues:
- fixes #12489
- fixes #11947
- fixes #8439
- fixes #5678

This is based on my refactoring PRs, so I will keep it a draft until those are merged.

### CODE REVIEW

**Comment by NomAnor** [comment]
The changes are now based on main. 
I added an explicit =TransformMode= property, which makes the different behaviours more obvious. Additionally it can be extended in the future to implement #5568.
I named the current behaviour "Transform tool shapes" because "Transform features" will be in conflict with the requested behaviour in #5568 and the patterns currently work on tool shapes.

**Comment by chennes** [comment]
@obelisk79 what does the DWG think about UI discoverability for this?

**Comment by NomAnor** [comment]
I ran into a problem with how the detection of a `MultiTransform` child is implemented. This detection is necessary to allow `Body` to see children as non-solids and not run certain action (e.g. setting BaseFeature).

https://github.com/FreeCAD/FreeCAD/blob/d92267c6a7b4dff2716180698eaea1dfb8f594ae/src/Mod/PartDesign/App/Body.cpp#L176-L207

The comment already hints at the problem. Because standalone `Transformed` features and children of `MultiTransform` are the same object/use the same class, immediatly after creating the object, when additional initialization is run in `Body`, but before the object gets finalized by the command, they are indistinguishable. 

My new method of looking at the in-list fails. The old method of looking for an empty `Originals` property worked by accident, but technically mislabeld newly added features even when they were standalone. Adding a check for default property values in my `Transformed::isMultiTransformChild()` functions restores the old behaviour, but this also mislabels newly created features.

I can't see a proper way to distinguish between standalone and child features. Because children don't need the `Originals` or other normal feature properties, I would implement them as a different class. But this needs a rewrite because otherwise there is a lot of code duplication.

Does anyone have an idea how this could be handled?

**Comment by obelisk79** [comment]
I'll have to build this PR and test it out to provide viable feedback on the UX/UI aspect of it. Will try to do that in the next day or two.

**Comment by FlachyJoe** [comment]
Hi, I don''t read the code yet but I think a full transform can use the Shape of the last feature (instead of the AddSubShape of the Originals)

**Comment by maxwxyz** [comment]
Does this also close: https://github.com/FreeCAD/FreeCAD/issues/5705 ?

**Comment by NomAnor** [comment]
No, #5705 wants to create a new Body object. 
This will just change the shape that is used by the existing transform features.

**Comment by NomAnor** [comment]
I changed the ```isMultiTransformChild()``` detection back to the old method. This will give false results during initialization but will not create problems with the non-solid detection of body.

**Comment by sliptonic** [comment]
@obelisk79  Did DWG ever comment on the discoverability of the feature?

**Comment by NomAnor** [comment]
Any news? I would like this to get into 1.0

**Comment by obelisk79** [comment]
I just linked this PR in Discord for the DWG to review. If I can make time this evening, I'll try and conduct a complete review of the UI/UX of this tonight on my PC.

**Comment by maxwxyz** [comment]
@NomAnor sensible changes, do you have a screenshot of the UI?

**Comment by NomAnor** [comment]
Yes, it is available for all tansform features. The UI is centrally defined which makes it easy to change. The feature selection UI is disabled when "Transform Body" is selected.

transform-body

The combo box was chosen to allow for additional modes (#5568). The feature selection UI could also be hidden as is the case for different modes with other features.

**Comment by maxwxyz** [comment]
I like it!
@kadet1090 mentioned on discord regarding the mode: "Apply the transform to the body" or something like that. It should be checked automatically if no tool is selected.

**Comment by NomAnor** [comment]
> I like it! @kadet1090 mentioned on discord regarding the mode: "Apply the transform to the body" or something like that. It should be checked automatically if no tool is selected.

I changed the transform feature commands. When no features are selected, the feature selection Dialog is still shown, but you can just press Ok without selecting anything. Then the transform feature will be created with the "Transform body" mode active.

I had to change how the pattern directions are pre-selected when the features are empty but it should behave as before.

Is the feature selection Dialog still necessary or should the features automatically created in "Transform body" mode when the selection is empty?

**Comment by maxwxyz** [comment]
does it work with a preselection? Then I'd say the select feature dialog is not necessary anymore.
@kadet1090 @obelisk79 opinion?

**Comment by kadet1090** [comment]
I'm not sure about the context but I'd say that it is necessary as it shows what is selected (or in that case - there is no selection at all) and allows to change that if user clicked it by mistake. Changing it would introduce unnecessary confusion in my opinion.

**Comment by maxwxyz** [comment]
@kadet1090 no it's about this dialog which is presented when you have no selection and click mirror:
grafik

The normal dialog still shows all features:
grafik

So I would skip the first one and default to mirror / pattern the entire body and there features could be picked afterwards and also work with a preselection (this currently also skips the first dialog)

**Comment by NomAnor** [comment]
> does it work with a preselection? Then I'd say the select feature dialog is not necessary anymore. @kadet1090 @obelisk79 opinion?

If you activate the command while one or more PD features are selected, they are used for the feature list without the dialog. And the mode will be "Transform tool shapes".

> I'm not sure about the context but I'd say that it is necessary as it shows what is selected (or in that case - there is no selection at all) and allows to change that if user clicked it by mistake. Changing it would introduce unnecessary confusion in my opinion.

The dialog is not shown when there is a selection. Being able to hit Ok without selecting anything in the Dialog is a new feature (before Ok did nothing without a selection) that is not discoverable.

It depends on how we want to guide users. I'm not sure how consistent this is across other features. 
I think if a user accidentally hits the command without a selection he can easily change the mode and then select the neccesarry features.

**Comment by adrianinsaval** [comment]
I'd like the design working group's opinion on entirely skipping that dialog, it seems unnecessary now that the tool works properly without selection.

The feature itself I love and I want to merge this however I would also like to hear some opinions on the property that controls this, why an enum and not a boolean? are we expecting more modes in the future? This also affects the UI, does this need to be a dropdown or should it just be a checkbox?

Is "Transform body" the term we want to stick with? should it be something like transform shape instead?

**Comment by maxwxyz** [comment]
@FreeCAD/design-working-group opinions?
I'm in favor of this change.

**Comment by NomAnor** [comment]
> I'd like the design working group's opinion on entirely skipping that dialog, it seems unnecessary now that the tool works properly without selection.

I agree, I will remove the dialog.

> The feature itself I love and I want to merge this however I would also like to hear some opinions on the property that controls this, why an enum and not a boolean? are we expecting more modes in the future? This also affects the UI, does this need to be a dropdown or should it just be a checkbox?

I would definitely keep the property as an enum, even if there are only two choices (similar recommendations/guidelines exist for function parameters in programming). This is not an option that can be turned on or off, but a different way to apply the transformations.
For the UI I anticipated a third mode (#5568), thats why I chose a dropdown. Giving only two choices for now, a pair of radio buttons would also be appropiate.
Should the feature selection UI always be visible or should it be hidden when "Transform body" is selected?

> Is "Transform body" the term we want to stick with? should it be something like transform shape instead?

I'm open to any term suggestions, that was just my initial choice.

**Comment by marcuspollio** [comment]
Hi @NomAnor 
In case you change other files in PartDesign/Gui, please have a look if [PR 13968](https://github.com/FreeCAD/FreeCAD/pull/13968/files) is merged. I would prefer not to resolve conflicts a second time. Thank you =D

**Comment by NomAnor** [comment]
I removed the dialog. I also tested radio buttons instead of a dropdown, but this is not yet commited.

radio

**Comment by sliptonic** [comment]
Discussed at Merge Meeting.  Agree that radio buttons are the way to go.  Please add that change.
@adrianinsaval, unless you have other concerns, please merge when it is ready to go.

**Comment by NomAnor** [comment]
I added the radio buttons

**Pull request merged**
