### PR TITLE
Update libmamba [fix conda fails]

### PR DESCRIPTION
**Pull request by mosfet80**
Bug fixes
Use Solver instance configuration to initialize the libmamba context without implicitly relying on the conda context settings. 
 Fix conda-build compatibility regression where arch-specific outputs can't be found in the test phase if a noarch output was built first.

### CODE REVIEW

**Comment by luzpaz** [comment]
cc @adrianinsaval

**Comment by adrianinsaval** [comment]
probably should update https://github.com/FreeCAD/FreeCAD/blob/facd8ca6e0303cf96297a7a7398185770c1a1e0b/conda/environment-qt6.devenv.yml#L6 too

@oursland could you remind me why we have this so specifically? is it ok to update?

**Comment by oursland** [comment]
The GitHub action to install mamba is broken and updates it to major revision version change that is incompatible, causing breakage.

**Comment by mosfet80** [comment]
Before this commit conda tests were failing.

es:
https://github.com/FreeCAD/FreeCAD/commit/d2637ec88117dc1c13d7d21d1860ba67ea6e39e6
https://github.com/FreeCAD/FreeCAD/commit/28b111245192b6c5ea01b150a50c24a6e19b3a5b
https://github.com/FreeCAD/FreeCAD/commit/1f2cdbc0469e6852dd9c9e8786ab980bab2290c7

Also the number of warings decreased 40 vs ~52 last higlided  commit.

I think the problem was temporarily solved by changing the cached version of the test that was reused in subsequent commits.

**Comment by oursland** [comment]
The failures are unrelated.  There was an upstream version of `openexr` that incorrectly packaged the `libdeflate` libraries.  Upon loading these libraries, there was symbol conflicts.  It was caught shortly after the release by the `conda-forge` team and a fix was made, resolving the issue.

**Pull request closed without merging**
