### PR TITLE
[GUI] don't show by default report view for warnings

### PR DESCRIPTION
**Pull request by donovaly**
don't show by default report view for warnings, see this forum thread: 
https://forum.freecadweb.org/viewtopic.php?f=17&t=48962

### CODE REVIEW

**Comment by donovaly** [comment]
>     * https://github.com/FreeCAD/FreeCAD/blob/8fc8a949c9436633602b589133450926f75fa961/src/Gui/ReportView.cpp#L272

Done. Thanks.

>     * https://github.com/FreeCAD/FreeCAD/blob/8fc8a949c9436633602b589133450926f75fa961/src/Gui/ReportView.cpp#L566

Why this too? checkShowReportViewOnLogMessage is be default also false and in
https://github.com/FreeCAD/FreeCAD/blob/8fc8a949c9436633602b589133450926f75fa961/src/Gui/ReportView.cpp#L581
it is true nevertheless.

**Comment by 0penBrain** [comment]
> > * https://github.com/FreeCAD/FreeCAD/blob/8fc8a949c9436633602b589133450926f75fa961/src/Gui/ReportView.cpp#L566
> > ```
> 
> Why this too? checkShowReportViewOnLogMessage is be default also false and in
> 
> https://github.com/FreeCAD/FreeCAD/blob/8fc8a949c9436633602b589133450926f75fa961/src/Gui/ReportView.cpp#L581
> 
> it is true nevertheless.

The one you pointed is also a mistake (probably copy-paste typo). What will happen is that with a stock installation, if user changes setting from the report view, the 1st time it will toggle from 'false' to 'false' ! After 1st attempt, everything will be fine as parameter will be set. That's only a one-shot annoyance, but why not preventing it if we can ?
Also would you be able to squash the commits of this PR ?

**Comment by donovaly** [comment]
> The one you pointed is also a mistake

I corrected this one as well now.

**Comment by 0penBrain** [comment]
@donovaly : :+1: Could you squash and force push the commits so it's merged in only one ?

**Comment by donovaly** [comment]
> Could you squash and force push the commits so it's merged in only one ?

How is that done with Git?

**Comment by donovaly** [comment]
> How is that done with Git?

OK, I found it: https://stackoverflow.com/questions/12528854/how-to-perform-rebase-squash-using-tortoisegit

And it worked: https://github.com/FreeCAD/FreeCAD/pull/3737/commits

However, @mwganson made a better proposal and it already went in. Therefore I close this PR.

**Comment by adrianinsaval** [comment]
> > > 
> The one you pointed is also a mistake (probably copy-paste typo).

https://github.com/FreeCAD/FreeCAD/blob/4ce85d39d394abf7844754e839631e3c8308ac7d/src/Gui/ReportView.cpp#L641

So shouldn't this be fixed anyway? maybe @wwmayer could commit directly so no PR is needed?

**Comment by 0penBrain** [comment]
> So shouldn't this be fixed anyway? maybe @wwmayer could commit directly so no PR is needed?

Indeed. Looks like @mwganson didn't fix in the PR #3754. Mark, could you do a global check about the default values of these options ? Thx

**Comment by mwganson** [comment]
https://github.com/FreeCAD/FreeCAD/pull/3786

**Comment by 0penBrain** [comment]
@mwganson :+1:

**Pull request closed without merging**
