### PR TITLE
Update FindPySide2Tools.cmake

### PR DESCRIPTION
**Pull request by mosfet80**
fix else option when qt >=5.14

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
Please explain the logic

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5482">pipeline status</a> for feature branch [PR_5482](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5482). Pipeline [462151183](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/462151183) was triggered at [66c0738](https://github.com/FreeCAD/FreeCAD/pull/5482/commits/66c073858df92706728de231db251c18a3e7b10b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
The change is not needed to fix anything. It just removes the redundant text inside `else()`. But why so in-consequently and not removing every redundant text inside every `else()` and `endif()` ?

**Review by mosfet80 — COMMENTED** [review]
pyside2-uic and pyside2-rcc  are replaced by uic and rcc in 5.14.0 QT 5.14.0

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5482">pipeline status</a> for feature branch [PR_5482](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5482). Pipeline [464221976](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464221976) was triggered at [975c302](https://github.com/FreeCAD/FreeCAD/pull/5482/commits/975c3023049702d474b7b133b75cbae24f0d5561). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5482">pipeline status</a> for feature branch [PR_5482](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5482). Pipeline [464340038](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464340038) was triggered at [87bd7b8](https://github.com/FreeCAD/FreeCAD/pull/5482/commits/87bd7b843c126cc4f06288aecbb20a7287a42eea). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
downstream fedora reporting breakage https://forum.freecadweb.org/viewtopic.php?f=4&t=66312

**Pull request merged**
