### PR TITLE
Fix searching for pip installed packages

### PR DESCRIPTION
**Pull request by 3x380V**
Since #10337 we lost ability to look for pip installed packages. Attempt to fix that.

### CODE REVIEW

**Comment by 3x380V** [comment]
@chennes While moving `find_pip_package` macro a few changes were made. Low hanging fruit is solved by the first patch in this PR, but there is also:
https://github.com/FreeCAD/FreeCAD/blob/c141cb3141605a15d0513c5c4f46e22044c80503/cMake/FreeCadMacros.cmake#L299-L307
This is quite different from original macro and returns empty libraries string on Linux. Could you explain intended purpose a bit?

**Comment by 3x380V** [comment]
I do not see a robust way to make globbing work. It is case sensitive, so `libpyside6.abi3.so.6.4` won't easily match `PySide6` unless we introduce additional logic. But we also have `Shiboken.abi3.so` and `libshiboken6.abi3.so.6.4`...

**Comment by 3x380V** [comment]
@chennes This one works, but I'm considering it pretty fragile. Lets see if someone comes with better solution.

**Comment by chennes** [comment]
I just confirmed that this still works with Windows LibPack 3 -- when the specific need arises for a more sophisticated glob (or when we have to move beyond globbing) we will have to revisit this, as you note, but I think this is OK to go in for now.

**Comment by 3x380V** [comment]
@chennes, just rebased to current main, tested again and pushed.

**Pull request merged**
