### PR TITLE
TechDraw: Enable App::Links to work with view.

### LINKED ISSUE #12374: [Problem] TechDraw 'share view' is a duplication of App::Link
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Why do we have a 'share view' tool that creates what looks like Links ?
On the other hands, links of views cannot be used / put inside pages.

Suggestion is that 'share view' is killed and Link is made to work in pages.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Techdraw

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
Enable App::Links of views to work. So that it is more consistent with the rest of the application than current 'Share Views' (fixes #12374).

Remove Share View from toolbar.

image

### CODE REVIEW

**Comment by PaddleStroke** [comment]
@WandererFan this is now working and ready for review.

**Comment by WandererFan** [comment]
Pierre, the CI failures are not related to this PR, correct?

**Comment by PaddleStroke** [comment]
@WandererFan no they are not. They are about some test failing in Part Design apparantly : 

>   File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/PartDesign/TestPartDesignGui.py", line 339, in testDefaultColor
>     self.assertEqual(packed_color, color)
> AssertionError: 4292280473 != 0

**Comment by WandererFan** [comment]
- if you drag a view with dimensions or balloons (and probably other children like leaders) to another page, the graphic for 
  the dimension remains on the source page but the dimension document object moves with the view onto target.  The dimension  needs to be removed from the source page QGraphicsScene (QGSPage) and added in the scene for the target page.
This needs fixing.

- view position in source page is not retained in target page.  this one isn't a big deal.

**Comment by PaddleStroke** [comment]
Just finished compiling and tested, there are also problems with this PR with childs of views. The dimensions do not appear in the page with the link.

**Comment by PaddleStroke** [comment]
@WandererFan I have just pushed a fix for the bug you describe, introduced by #13063, ie sub-views not being transfered when drag&droping a view between pages.

I am currently looking at the issue that also happens with child views in this PR: ie if you create a link to a view and put this link into another page. Then children do not appear.

I think there is here a design issue. Why are children views stored in the Page 'Views' property? It would make more sense that they are stored in the View 'Views' property. Then when the page populates it just take childrens recursively. But this seems like a big change. I'll try to fix Links without changing that.

**Comment by PaddleStroke** [comment]
After some more testing it does not work as expected yet.

The fact that child views are stored in the page Views property is very inconvenient. It would make much more sense that they are stored in the view itself, like the collections do.

**Comment by PaddleStroke** [comment]
@WandererFan ok now the bugs are fixed.
I also fixed the second bug you mention about X,Y reseting when dropping a view into another page.

**Comment by WandererFan** [comment]
Dimension moves to the new page along with its parent.  Views are still positioned at the center of the new page after move.  That could be sorted out in a follow on PR.

**Comment by WandererFan** [comment]
<<I think there is here a design issue. Why are children views stored in the Page 'Views' property? It would make more sense that they are stored in the View 'Views' property like collections do. Then when the page populates it just take childrens recursively. But this seems like a big change. I'll try to fix Links without changing that.>>

More of a history problem.  Collection was originally used only for ProjectionGroup and regular views with children didn't exist.  Now we have balloons, leaders, richAnnos, etc, but that assumption has never been revisited.  Every view should probably be a collection now.  But, as you say, that's a major overhaul.

**Pull request merged**
