### PR TITLE
Prescribed deformation boundary condition for FEM analysis

### PR DESCRIPTION
**Pull request by makkemal**
Prescribed deformation boundary condition for FEM analysis. This version has file names according to python coding procedure. It is also modified to work the same as other boundary conditions

### CODE REVIEW

**Comment by f3nix** [comment]
Hi,
there is something wrong with this pull request.
It adds some files it shouldn't.
It changes some files it shouldn't.

Cheers,
Mateusz

**Comment by makkemal** [comment]
In the first version I changed files I should not. Brend helped me fix that
then I had to update the python again. The last version is correct it
basically adds 3 python files and just some references to the files from
C++.  So just look at last version it works correctly.

Regards
Michael

**Comment by f3nix** [comment]
Hi,
image

Cheers,
Mateusz

**Comment by makkemal** [comment]
Ah I see
Yes I did mess up. It seems I submitted the entire directory in which I
compiled and tested (on ubuntu) and not just the changes.
Any advice On how I fix this now ?

**Comment by f3nix** [comment]
I'm still learning git but here is how I would do it:

```
$ git checkout predeformation2
$ git rebase -i 9dc13ef48c6d80811857c831d36bddc4ef7fd101^
```
Then an editor pops up. Change the word "pick" to "edit" in the first line.
Save the file and exit the editor.

```
$ git reset HEAD^
$ git status
```

This should show something like this.

```
interactive rebase in progress; onto 1507ef2
Last command done (1 command done):
   edit 9dc13ef Prescribed displacement working the same as other boundary conditions
No commands remaining.
You are currently splitting a commit while rebasing branch 'predeformation2' on '1507ef2'.
  (Once your working directory is clean, run "git rebase --continue")

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/Mod/Fem/FemPrescribedDisplacement.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .excludes
        CMakeLists.txt.user
        FreeCAD_trunk.cbp
        data/Mod/
        deformationdec.json

        ....
```    
If only the FemPrescribedDisplacement.py should have been modified in this commit then:

```
$ git add src/Mod/Fem/FemPrescribedDisplacement.py
$ git commit --amend
$ git rebase --continue
```

And this will push to and overwrite the online repo.
```
$ git push -f
```

That is all.

You should also sync your feature branch with upstream.

Thanks for you contribution to FreeCAD.

Happy New Year! :smile:

Cheers,
Mateusz

**Comment by makkemal** [comment]
Thanks for the help Matueusz
I am finding Git a steep learning curve.
Before I create the pull request did I get this correct now.
https://github.com/FreeCAD/FreeCAD/compare/master...makkemal:predeformation3?expand=1

Thanks for the help
Regards
Michael

**Comment by f3nix** [comment]
Hi,
please check PM on FC forum.

Cheers,
Mateusz

**Pull request closed without merging**
