### PR TITLE
Gui: Fix use of undocumented init() function

### LINKED ISSUE #8598: [Issue] Build failure
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

_No response_

### Version

0.21 (Development)

### Full version info

```shell
macOS, Qt6
```

### Subproject(s) affected?

None

### Issue description

```
[3158/3866] Building CXX object src/Gui/CMakeFiles/FreeCADGui.dir/NotificationBox.cpp.o
FAILED: src/Gui/CMakeFiles/FreeCADGui.dir/NotificationBox.cpp.o 

/Users/bernie/CLionProjects/FreeCAD/src/Gui/NotificationBox.cpp:183:9: error: no member named 'init' in 'QStyleOptionFrame'
    opt.init(this);
/Users/bernie/CLionProjects/FreeCAD/src/Gui/NotificationBox.cpp:194:12: error: no member named 'init' in 'QStyleOption'
    option.init(this);
    ~~~~~~ ^
/Users/bernie/CLionProjects/FreeCAD/src/Gui/NotificationBox.cpp:339:50: warning: must specify at least one argument for '...' parameter of variadic macro [-Wgnu-zero-variadic-macro-arguments]
Q_GLOBAL_STATIC(QPalette, notificationbox_palette)
                                                 ^
/usr/local/lib/QtCore.framework/Headers/qglobalstatic.h:115:9: note: macro 'Q_GLOBAL_STATIC' defined here
#define Q_GLOBAL_STATIC(TYPE, NAME, ...)                                    \
        ^
1 warning and 2 errors generated.

```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chennes**
Fixes #8598.

---

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by berniev** [comment]
That was fast! Thank you.
Re title: "Undocumented"? Or "Changed"?

**Comment by berniev** [comment]
Wait, there's more:

FAILED: src/Gui/CMakeFiles/FreeCADGui.dir/NotificationBox.cpp.o 
..
/Users/bernie/CLionProjects/FreeCAD/src/Gui/NotificationBox.cpp:183:9: error: no member named 'init' in 'QStyleOptionFrame'
    opt.init(this);
    ~~~ ^
/Users/bernie/CLionProjects/FreeCAD/src/Gui/NotificationBox.cpp:194:12: error: no member named 'init' in 'QStyleOption'
    option.init(this);
    ~~~~~~ ^

**Comment by chennes** [comment]
> Wait, there's more:

Those are the two lines I changed -- double-check that you changed branches after fetching this PR.

**Comment by berniev** [comment]
Ah, I see, this hasn't been merged yet. Thought I was going nuts.

**Comment by wwmayer** [comment]
In Qt5 the function init() is marked as deprecated and in Qt6 it has been removed.

**Pull request merged**
