### PR TITLE
Gui: Fix VarSet dialog 2 digit problem

### LINKED ISSUE #17873: Varset: PropertyInteger entry limited to 2 digits
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In build 39176.

Create a new Varset PropertyInteger the enter field is restricted to 2 digits.
If the Fx is selected more digits are allowed but closing the Fx popup results in '99' being entered.

### Full version info

```shell
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu-xorg/xcb)
Architecture: x86_64
Version: 1.1.0dev.39176 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 45d3864942c6928cec7dc18f95b1f222485756e5
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenDark/Qt default
Installed mods: 
  * freecad.gears.backup1728167078.8916416 1.3.0 (Disabled)
  * OpenTheme 2024.9.1
  * Manipulator 1.5.7
  * Defeaturing 1.2.2
  * Help 1.0.3
  * kicadStepUpMod 11.4.1
  * Curves 0.6.51
  * DynamicData 2.69.0
  * freecad.gears 1.3.0
  * fasteners 0.5.29
  * sheetmetal 0.5.3
  * freecad.gears.backup1730806425.7568283 1.3.0 (Disabled)
  * CurvedShapes 1.0.12
  * lattice2 1.0.0
  * QuickMeasure 2022.10.28
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pieterhijma**
Fixes #17873.

It has been tested on all property types.

### CODE REVIEW

**Comment by chennes** [comment]
@pieterhijma can you explain why this fixes the issue? The code is simple enough, but I don't have the context here.

**Comment by pieterhijma** [comment]
Hi @chennes, sure! First a bit of context: The property items are associated with properties and the editors for these properties. The property editors are essentially designed for the property view specifically, but I want to use them in a dialog to get the "native" experience. So, I'm trying to make the most out of the code that is already there, but the code did not have my use case in mind. Because of this, the varset dialog has some workarounds and some quirks also arise, such as the one described in the issue.

In an earlier implementation I didn't set the editor data at all and that worked fine for most property types, except for the font property type that did not load the fonts (if I remember correctly). I solved that by setting the editor data explicitly with an "empty" value (the QVariant). At the time, I didn't realize that some properties were initialized with a spinbox that had limitations for the number of digits.

With this change, I verified that I can set the editor data to an empty value for each property type (at least it gives the same behavior as in the property view).

To give an example for what this does, for example the integer property type, it calls [this function](https://github.com/pieterhijma/FreeCAD/blob/7e82874e0b19879777a6261fae0dabe1ca5720ae/src/Gui/propertyeditor/PropertyItem.cpp#L988) where you can see that it sets the range. For floats [this function](https://github.com/pieterhijma/FreeCAD/blob/7e82874e0b19879777a6261fae0dabe1ca5720ae/src/Gui/propertyeditor/PropertyItem.cpp#L1153) is called.
For reference, `setEditorData()` on the font property type indeed [loads the fonts](https://github.com/pieterhijma/FreeCAD/blob/7e82874e0b19879777a6261fae0dabe1ca5720ae/src/Gui/propertyeditor/PropertyItem.cpp#L916).

By the way, a next step is to [include units as well](https://github.com/FreeCAD/FreeCAD/issues/15557) as the property view editors do. A solution to that will be along the same lines, but more complicated.

**Comment by kaiwas** [comment]
> By the way, a next step is to [include units as well](https://github.com/FreeCAD/FreeCAD/issues/15557) as the property view editors do. A solution to that will be along the same lines, but more complicated.

I don't even know whether to be happy or upset about this fact. The system of units causes difficulties in many places.
At the very least, you constantly have to deal with their screening (/).
I guess I'll be upset.
It's a pity that there is no separate option that would turn off units and use a conventional "unit" (like in blender).

**Comment by adrianinsaval** [comment]
backported 5d4587cfb3c2b24d4b97cd06c62af3c67732fd9d

**Pull request merged**
