### PR TITLE
FEM: file headers and code formating

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT]

cheers bernd

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
The py2 builds are failing I think.

**Comment by berndhahnebach** [comment]
> The py2 builds are failing I think.

fixed with https://github.com/FreeCAD/FreeCAD/pull/1799/commits/d05adfad78bac0746e587e57047e448d0a829810

**Comment by berndhahnebach** [comment]
> > The py2 builds are failing I think.
> 
> fixed with [d05adfa](https://github.com/FreeCAD/FreeCAD/commit/d05adfad78bac0746e587e57047e448d0a829810)

ok with this its fixed. ... https://github.com/FreeCAD/FreeCAD/pull/1799/commits/86455527ddb9eea15f5ae562c2f02b921d4c1a11

**Comment by yorikvanhavre** [comment]
thanks!

**Pull request merged**
