### PR TITLE
Change default preference to not include the FreeCAD icon to the file thumbnail / Update example files

### PR DESCRIPTION
**Pull request by maxwxyz**
Fixes https://github.com/FreeCAD/FreeCAD/issues/14533

Change default preference to not include the FreeCAD icon to the file thumbnail.
Windows renders the application image on top so it appears twice. Update example file thumbnails on start page to have a consistent background (classic theme) and remove the old FreeCAD logos.

Previously:
Bildschirmfoto 2024-08-04 um 18 15 17

PR:
Bildschirmfoto 2024-08-04 um 17 47 23

### CODE REVIEW

**Comment by furgo16** [comment]
Thank you. This may or may not be relevant to this PR, but might be worth considering https://forum.freecad.org/viewtopic.php?p=535941#p535941

> FEM 2D and 3D new solver can be deleted. FEM 3D should be replaced by the one from FreeCAD FEM examples gui.

**Comment by maxwxyz** [comment]
I'll leave FEM to @FEA-eng

**Comment by chennes** [comment]
@FreeCAD/design-working-group is this change OK with you?

**Comment by obelisk79** [comment]
I think this is a good change. It's surely a matter of opinion, but I'm of a mind that extra branding via logo in thumbnails was superfluous and unnecessary.

**Comment by pierreporte** [comment]
I fully agree with this PR.

**Pull request merged**
