### PR TITLE
PATH:  add option to suppress preamble for each command

### PR DESCRIPTION
**Pull request by mlampert**
Adding a preamble before each command breaks some dressups and also the path optimizer of some controllers. This patch adds an option to Path.fromShapes to suppress preamble generation and uses that option for Path ops.

It also adds a full unit test to dogbones to hopefully catch future breakages.

### CODE REVIEW

**Comment by wwmayer** [comment]
According to travis your code isn't Py3 conform. In line 129 of the module TestPathDressupDogbone.py you have `locs = sorted([bone[1] for bone in dog.bones], key=lambda (x,y): x * 1000 + y)` that raises a syntax error.

**Comment by mlampert** [comment]
Indeed - it seems python3 doesn't like the tuple as lambda argument.

**Comment by mlampert** [comment]
And searching for "python3 lambda" lacking support for unrolling tuples is the #1 issue

**Comment by wwmayer** [comment]
How comes that this PR again fails? When looking yesterday I saw that all builds succeeded. But anyway the Py3 works and it's only the Qt5 version that failed because it exceeded the time limit.

**Comment by wwmayer** [comment]
Merged.

**Pull request merged**
