### PR TITLE
Gui: Move Python functions from Application to ApplicationPy

### PR DESCRIPTION
**Pull request by wwmayer**
This reduces build time when adding new Python functions because only one file must be compiled. Handles also many linter warnings.

### CODE REVIEW

**Comment by wwmayer** [comment]
How?

**Comment by 3x380V** [comment]
Actually it makes sense only for ApplicationPy.h as it is a new file as shown in 4bfda1bd1758. [dos2unix](https://dos2unix.sourceforge.io/) was used to convert line endings.
Git can be configured to handle line endings correctly from Windows, but I never verified that myself (not a Windows user).

**Comment by wwmayer** [comment]
OK, then I will use dos2unix, too.

**Comment by 3x380V** [comment]
Thank you.
Btw, that [[pre-commit.ci]](https://github.com/FreeCAD/FreeCAD/pull/18579/commits/6fdddac20c34b3c73f29cb720a89547ee58f19a7) above is fixing change introduced by 8e0bf192df2e which is #18591. It's a bit confusing.

**Pull request merged**
