### PR TITLE
cppcheck: (performance) Prefer prefix ++/-- operators for non-primitive ...

### PR DESCRIPTION
**Pull request by serval2412**
...types

### CODE REVIEW

**Comment by serval2412** [comment]
The only places where I hesitate are these:
[Mod/Part/App/modelRefine.cpp:623]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[Mod/Part/App/modelRefine.cpp:653]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[Mod/Part/App/modelRefine.cpp:891]: (performance) Prefer prefix ++/-- operators for non-primitive types.

Indeed, I also used prefix for init iterator but I think there might be a problem here since this first iteration isn't checked.
However, I'm afraid that even with postfix increment, the problem remains the same.

**Comment by yorikvanhavre** [comment]
Should this still be merged? I cannot judge of the validity of the proposed changes...

**Comment by wwmayer** [comment]
Yes, but not as it is. I will go through the list and do the changes manually where it makes sense.

**Comment by wwmayer** [comment]
Merged the relevant parts

**Pull request closed without merging**
