### PR TITLE
Materials: New Glass Materials

### PR DESCRIPTION
**Pull request by DaviKaur**

### CODE REVIEW

**Comment by PrzemoF** [comment]
First of all: thank you for working on the new material fiiles and thank you for fixing the typos! Some minor comments:
1. Can you remove all material files generated by script that are in: src/Mod/Material/StandardMaterial/Tools/FCMats/ ? This is only working directory and all material files should be in  src/Mod/Material/StandardMaterial/ If there are any new materials please move them to src/Mod/Material/StandardMaterial/
2. Please remove this file:  src/Mod/Material/StandardMaterial/Tools/Materials.csv It's generated by script and there is no need to keep it. All information is in Materials.ods anyway.

Other than that the pull request is good and it's ready to go into the master branch :-)

**Comment by DaviKaur** [comment]
Done.

**Comment by PrzemoF** [comment]
Thank you!
Werner/Yorik - can you pull it and squash into one commit?

**Comment by wwmayer** [comment]
OK, I will have a look at it later.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
