### PR TITLE
Gui: Add ScrollArea to Preferences and auto expand groups

### LINKED ISSUE #11004: [Problem] Huge size of the preferences dialog
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With the merge of the PR https://github.com/FreeCAD/FreeCAD/pull/7888 the preferences dialog now occupies almost the full height of the screen. This is caused by the DlgSettingsUI because it contains more than 30 controls in a vertical layout.

This huge height affects all other preference pages and for most of them there is now a blank area and at the bottom are standard buttons. This leads to a pure usability because one has to move the mouse like crazy in order to accept the changes.

Either the UI tab should be split into two tabs or the whole page should be embedded into a scroll area.

### Full version info

```shell
OS: Ubuntu 22.04.3 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34633 +4 (Git)
Build type: debug
Branch: overlay_fixes
Hash: 31e8c2c80b01b17f9a55a06dd20b9c5d0e14d7ad
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #11511: [Problem] Preferences dialog too large and not resizable - disappears from screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The preferences dialog is too large on my screen, so it is not possible to click "OK" or "CANCEL" nor reach the "Reset..." group.
The dialog cannot be resized, when I try to scale it vertically, the dialog moves quickly out of the screen (into the bottom) and is unable to reach again. I can only close it with ESC.

Quick Demo:

https://github.com/FreeCAD/FreeCAD/assets/6246609/0d61ff61-bbc0-4821-b548-e3745183523d

### Full version info

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35176 (Git)
Build type: Release
Branch: main
Hash: dcd533af4bf0cb3dbc50c7d0e2fb579cad168819
Python 3.10.13, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.24.8
  * CurvedShapes 1.0.5
  * Curves 0.6.14
  * Defeaturing 1.2.1
  * fasteners 0.4.70
  * FEMbyGEN 2.0.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.10.30
  * sheetmetal 0.3.12
  * woodworking 0.21.30486
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #11530: [Problem] Standard buttons of preferences dialog are not accessible any more
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

On several systems the standard buttons of the preferences dialog are not accessible any more. The reported issue #11004 creates a huge page and the dialog expands to a height that make the standard button to move outside the visible area of the desktop. See: https://github.com/FreeCAD/FreeCAD/issues/11004#issuecomment-1825880450

However, the actual regression is caused by this PR: https://github.com/FreeCAD/FreeCAD/pull/11018
because it has entirely removed the scroll area that was responsible to show scroll bars if a page was too big

### Full version info

```shell
OS: Ubuntu 22.04.3 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35202 (Git)
Build type: debug
Branch: marker_sizes
Hash: 7561b90eb8bdbb0e692651d98d853da605e4deef
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kadet1090**
This adds QScrollArea widget to DlgPreferences which in turn allows preference pages to be scrollable. Stacked widget sizes are forced to selected widget so scroll area should appear when it is needed.

Second commit ensures that after selecting item the group is automatically expanded. User can force expansion by explcitly clicking expand button, groups expanded that way will stay expanded unless user collapses them. Otherwise non-active group will be collapsed automatically.

This PR also changes default size of the dialog to 1000x900 - for pages that are larger it results in vertical scroll.

Fixes #11511
Fixes #11530
Fixes #11004

### CODE REVIEW

**Comment by luzpaz** [comment]
Any implication for #11004 ?

**Comment by kadet1090** [comment]
I did not touched this page at all, so it still has too much options. It should however no longer resize the preferences dialog, instead it simply is scrollable now and does not impact height of the preferences dialog which now defaults to 900px. 

image

**Comment by kadet1090** [comment]
I'm not sure how this will behave on screens that has height less than 900px. Can someone test that?

**Comment by obelisk79** [comment]
I have tested this on 720p resolution. Window fits, was resizable and the auto-collapse/expand appears to work as one would expect.

```
OS: EndeavourOS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35206 +2 (Git)
Build type: Unknown
Branch: preferences-scroll
Hash: 1225987be4c8cbf1e37179db95a8c9037fbf0c7a
Python 3.11.6, Qt 5.15.11, Coin 4.0.1, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * IconThemes
  * OpenDark 2023.10.30
  * freecad.gears 1.0.0
  * Curves 0.6.14
  * TabBar
```

**Pull request merged**
