### PR TITLE
Exception: FUNCSIG instead of PRETTY_FUNCTION for Microsoft compiler

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
@DeepSOIC 

Please do not merge until a Microsoft Visual Studio user tests it.

### CODE REVIEW

**Comment by DeepSOIC** [comment]
```
__FUNCSIG__: __cdecl App::Application::Application(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > &)
```

I didn't try using THROWM yet.

**Comment by DeepSOIC** [comment]
Added THROWM's all over Container.cpp. Compiles fine and works. Now I need to figure out how to make the information reach Python.

**Comment by abdullahtahiriyo** [comment]
@DeepSOIC 

It is the two of us ;)

I think one option could be to use setObject instead of setString.
https://docs.python.org/2/c-api/exceptions.html

Then the object can have any number of parameters inside...

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
