### PR TITLE
[CONTRIBUTING.md] Mention english as communication language

### PR DESCRIPTION
**Pull request by FlachyJoe**
Mentions the requested english language knowledge to contribute.

This fact could now be discussed.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7883">pipeline status</a> for feature branch [PR_7883](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7883). Pipeline [705862074](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/705862074) was triggered at [b77f5de](https://github.com/FreeCAD/FreeCAD/pull/7883/commits/b77f5de228184f0e9c18e89e5417bc92708c694d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
perhaps this should be put in the Contribution Requirements section, as it is the word contributors is being used before being defined, plus it might be a good idea to use terminology like SHALL and MUST.
I suggest

- The PR message and all comments in the submitted code MUST be written in english

And in the Process section

- Issue descriptions and subsequent discussions SHALL be written in english, if the user or contributor does not know the english language they MAY use translation software and post both the original and translated text.

**Comment by FlachyJoe** [comment]
> post both the original and translated text.

But what about code comments ?

**Comment by adrianinsaval** [comment]
meant code comments in the first requirement but since it's not clear I'll rephrase 
* The PR message, commit messages and all code comments in the submission MUST be written in English

**Comment by FlachyJoe** [comment]
> * The PR message, commit messages and all code comments in the submission MUST be written in English

Should we write :
* Non English writer MUSTN'T publish PR message, commit messages or code comments

**Comment by adrianinsaval** [comment]
Not IMO, must be written in English implies that they can't do it in another language already, adding explicit exclusion just looks aggressive and uninviting, plus if they don't understand English they can't read this document anyways

**Comment by FlachyJoe** [comment]
Lire et écrire sont deux choses différentes et j'ai justement lancé cette discussion pour mettre en évidence l’exclusion actuelle d'une partie de la communauté. Si nous choisissons de travailler sur l'inclusion, ce qui me semble être le cas par le choix de ce contrat de contribution, il est important de prendre en compte la barrière de la langue et de chercher à la minimiser.
Je pense qu'il n'est pas soutenable de limiter les contributions aux "anglographes" et qu'il faut mettre en place un mécanisme pour permettre à tous de participer au code.

_Autotranslated : 
Reading and writing are two different things and I just started this discussion to highlight the current exclusion of part of the community. If we choose to work on inclusion, which seems to me to be the case with the choice of this contribution contract, it is important to take into account the language barrier and seek to minimize it.
I think it is not sustainable to limit contributions to "Anglographers" and that a mechanism must be put in place to allow everyone to participate in the code._

**Comment by adrianinsaval** [comment]
My native language is Spanish so I empathize, however I just don't see how this could be done for coding, good communication is important for development so if the person cannot understand the language review and feedback would be very hard, and the code comments are there to be read and understood by others, it simply cannot be in other languages, I do not say that the person has to have perfect English and no typos are allowed, hopefully if code comments aren't redacted correctly reviewers will ask for clarification or changes.
If you have a another proposal for the policy please make it, I have an open mind and I believe the people who can actually merge these things too. About your current proposal IMO that line is pointless as its just mentioning that we use English, and this is painfully obvious already by the fact that everything here is written in English, but sets no rules or guidelines for what to do with people that only speak other languages (or rather what should they do).

> I just started this discussion to highlight the current exclusion of part of the community

please be straightforward with things like this then, there's no need to play games and go "I'll propose to make English the official language then will make an unclear passive aggressive comment about exclusion and _only then_ will I actually get to my point", inclusion is an important topic that IMO can and should be discussed directly and out in the open. If I were a more emotional or unreasonable person you would have made an enemy for no reason, and there's plenty of emotional and/or unreasonable people out there.

**Comment by FlachyJoe** [comment]
@adrianinsaval Je te prie de m'excuser, j'ai pensé ma PR comme une invitation à la discussion en pensant qu'on ne pouvait parler que d'un fait avéré donc inscrit dans le document. J'ai ensuite été entraîné par tes réactions et par manque de réflexion dans un chemin que je n'avais pas prévu.
Je ne vois pas non plus de solution immédiate au problème de la compréhension des commentaires et de l'explication du code source de la part d'un non anglophone. Il conviendrait sans doute de lancer le sujet dans les différents sous-forums régionaux et d'effectuer des recherches approfondies. Cela ferait certainement un bon sujet d'étude pour un·e sociologue.

I beg your pardon, I thunk my PR as an invitation to discuss and thunk it requests the fact to be written first. I next was driven in an unexpected path as by your reaction as by lack of reflection.
I can't see immediate solution for a non english speaker to understand comments and talk about code. This subject could be discussed in localized sub-forum and a deeper search start. It's certainly a good study case for a sociologist.

**Comment by chennes** [comment]
I think @adrianinsaval is right: it may be that this is an Issue (or a Problem) to be discussed, but I don't think it's quite ready for a PR yet, according to our _current_ CONTRIBUTING.md. See problem report https://github.com/FreeCAD/FreeCAD/issues/7893.

**Pull request closed without merging**
