### PR TITLE
[Gui] Add style, theme and qtstyle info to clipboard about info

### LINKED ISSUE #16272: Triage: Add Stylesheet and Qt theme being used to About info
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Given the:  
1. amount of [Stylesheet](https://github.com/FreeCAD/FreeCAD/issues?q=is%3Aopen+is%3Aissue+label%3A%22Topic%3A+Stylesheets%22) bugs there are 
2. confusion around Qt's internal themes (https://github.com/FreeCAD/FreeCAD/issues/15868)

It would be helpful for bug triagers to have the option to see what stylesheet and Qt theme are being used. The proposal is that when one copy/pastes their [About](https://wiki.freecad.org/About) info there could be a line that shows both of these as consolidated: 

`Stylesheet/Qt theme: OpenTheme vX.Y.Z/Fusion`  

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38622 (Git)
Build type: Release
Branch: main
Hash: ed97f3c4591303ee3b54906768f8f4eba5211265
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Qt theme: OpenTheme vX.Y.Z/Fusion
```

### Full version info

```shell
n/a
```

### Subproject(s) affected?

Core

### Anything else?

Originally discussed in https://github.com/FreeCAD/FreeCAD/issues/16262#issuecomment-2327131495

Other Triage related tickets: #15710 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by benj5378**
Fixes #16272

```
Stylesheet/Theme/QtStyle: Behave-dark.qss/FreeCAD Classic/Fusion
```

For testing, you might have to manually copy the changed preference packs

### CODE REVIEW

**Comment by kadet1090** [comment]
@obelisk79 You'd need to move QtStyle parameter after this is merged

**Comment by Syres916** [comment]
@benj5378 please update https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/PreferencePacks/FreeCAD%20Classic/post.FCMacro#L7 to the new QtStyle location.

**Comment by benj5378** [comment]
@Syres916 done

**Comment by chennes** [comment]
Cherry-picked to releases/FreeCAD-1-0 with `git cherry-pick e7f6aa1 33e8bf6 50863c7`.

**Comment by luzpaz** [comment]
Screenshot_20240910_134916

Looks like there is a usecase when Classic theme is enabled and Qt theme isn't either ?

**Pull request merged**
