### PR TITLE
Gui: Expose the upDirection vector to Python

### PR DESCRIPTION
**Pull request by pieterhijma**
Expose the up direction vector to Python

For workbenches or FreeCAD Python code in general, it is useful to have access to the up-direction vector. It is discussed in this [forum post and earlier](https://forum.freecad.org/viewtopic.php?p=693542#p693542)

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by marioalexis84** [comment]
If `getUpDirection` takes no arguments, you can use the PyCXX function `add_noargs_method` instead of `add_varargs_method` and remove the check with `PyArg_ParseTuple`.

**Comment by marioalexis84** [comment]
There is no such convention. We can change to `add_noargs_method` for all those functions with no arguments here or in a later commit.

**Comment by WandererFan** [comment]
Compile error.  "_view" is not defined.  I think the fix is to change
SbVec3f dvec = _view->getViewer()->getUpDirection();
 - to -
SbVec3f dvec = getView3DIventorPtr()->getViewer()->getUpDirection();

Note the wonky spelling of getView3DIventorPtr

**Comment by pieterhijma** [comment]
> There is no such convention. We can change to `add_noargs_method` for all those functions with no arguments here or in a later commit.

If you want, I can make the necessary changes. Having just read the contributor guidelines, I think it is preferred to create a new issue and pull request for this change. Please let me know what you prefer.

**Comment by pieterhijma** [comment]
> Compile error. "_view" is not defined. I think the fix is to change
> 
> SbVec3f dvec = _view->getViewer()->getUpDirection(); to SbVec3f dvec = getView3DIventorPtr()->getViewer()->getUpDirection();
> 
> Note the wonky spelling of getView3DIventorPtr

Oops, you're right. I forgot a commit when cherry-picking. I've included that one and one which fixes the indentation. This time I didn't forget to check whether it compiles.

**Comment by chennes** [comment]
> Having just read the contributor guidelines, I think it is preferred to create a new issue and pull request for this change.

Exactly right -- let's keep this PR clean and simple. But a follow-up that makes the suggested change would certainly be appreciated.

**Comment by marioalexis84** [comment]
Code tested and working fine.
@pieterhijma can you crush all three commitments into one?

**Comment by pieterhijma** [comment]
> > Having just read the contributor guidelines, I think it is preferred to create a new issue and pull request for this change.
> 
> Exactly right -- let's keep this PR clean and simple. But a follow-up that makes the suggested change would certainly be appreciated.

Ok, see the issue above. I will create a merge request for this as well.

**Comment by pieterhijma** [comment]
> Code tested and working fine. @pieterhijma can you crush all three commitments into one?

Yes, will do.

**Comment by pieterhijma** [comment]
> > Code tested and working fine. @pieterhijma can you crush all three commitments into one?
> 
> Yes, will do.

Squashed and rebased onto `master` again. Also compiled again locally just to be sure ;-)

**Pull request merged**
