### PR TITLE
OpenSCAD: pep8-ified + removed superfluous whitespace + uniform headers

### PR DESCRIPTION
**Pull request by luzpaz**
This PR is *slightly* less cumbersome :sweat_smile:  if you hide whitespace via the Github UI

image

### CODE REVIEW

**Comment by chennes** [comment]
I propose that we start a .git-blame-ignore-revs file, even though GitHub doesn't support it yet. That support is coming, I'd bet, and this is exactly the sort of change that should be in there. Then let's just run Black on the OpenSCAD mod.

**Comment by luzpaz** [comment]
`.git-blame-ignore-revs` which does what? Ignore certain commits in a blame?

**Comment by chennes** [comment]
Yes - you can pass it as an argument to `git blame` and then blame won't show the changes from those revs, but will look to the previous change. So inconsequential changes don't mess up the "who changed this code" function of blame. It's supported on the command line now, but both GitHub and GitLab have a lot of upvotes on a feature request to add it to their online platforms, and have indicated their intention to do so.

**Comment by luzpaz** [comment]
That sounds like an awesome feature. Are there any downsides to it?

**Comment by chennes** [comment]
Well, it is another file to maintain, and you can't really update it in the same PR that makes the formatting change because you don't know how the format change will get merged (so you don't know the commit hash to add to the file). Our commit messages are usually pretty good, though, so it as long as we have good commit discipline and keep the format changes separate, it should be straightforward to keep the file more or less updated.

**Comment by luzpaz** [comment]
IMHO, i'm all for it then. We just make some good documentation around this so merge devs can be aware of it and keep it up to date. Perhaps even having a bot automate appending the hash to the file at a given time?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5380">pipeline status</a> for feature branch [PR_5380](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5380). Pipeline [447916855](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/447916855) was triggered at [441856e](https://github.com/FreeCAD/FreeCAD/pull/5380/commits/441856e8ef465734a9849dfb439a60d1d38d2569). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@wmayer care to weigh in on https://github.com/FreeCAD/FreeCAD/pull/5380#issuecomment-1012779050 ? Thanks!

**Comment by luzpaz** [comment]
Should I open a forum thread to discuss?

**Comment by chennes** [comment]
Nah, I just went ahead with it, no need to talk this one to death. If you are feeling motivated feel free to track down other large formatting-only commits that should be ignored.

**Pull request merged**
