### PR TITLE
Macro: Ability to conviently 'send selection to console' from the Macro Editor context menu.

### PR DESCRIPTION
**Pull request by Jonezzzzz**
Adds a feature requested on issue #18422

Adds an ability to execute selected line(s) directly from Macro Editor's (Python Editor) context menu or with keyboard shortcut: `Ctrl+Shift+E`
Executes the line that the cursor is on, if there is no selection (for speed).

Uses
`Base::Interpreter().runInteractiveString();`
for single-line selection, to get interactive messages such as:

> AttributeError: module 'FreeCADGui' has no attribute 'getWindow'. Did you mean: 'getMainWindow'?

and
`Base::Interpreter().runString();`
for the ability to run multiline selections (multiple statements).

The output (print messages, errors, etc.) goes to the Report View. Therefore, the following settings need to be enabled:
### Record View
Output
- [x] Record normal messages
- [x] Record log messages
- [x] Record warnings
- [x]  Record error messages

Python interpreter
- [x] Redirect internal Python output to report view
- [x] Redirect internal Python errors to report view

### Update

Fixed indentation issue and and added `printStatement` to print the executed code in the console.
Credits to @mwganson  for providing the solution for handling indentation. PR #18716

> Often there is an issue with indentation, for example, if we wish to execute a block of code that is within a function definition or class definition. This PR will attempt to normalize the indentation level so that it can be executed in the console. The method used is to find the leading whitespace of the first selected line, and then remove that leading whitespace from all the lines in the selected block, thus preserving the indentation relative to the first selected line.

### CODE REVIEW

**Comment by mwganson** [comment]
Sorry, I didn't see this PR before submitting a similar one.  https://github.com/FreeCAD/FreeCAD/pull/18716

**Comment by Jonezzzzz** [comment]
> Sorry, I didn't see this PR before submitting a similar one. #18716

The way you solved the indentation issue is great – I completely overlooked that!

I believe my solution handles running the selected code a bit better. When using the `doCommand` method, the Python console gets cluttered, and interactive messages are lost, which I find useful for scripting macros.

I suggest that we combine the best of both solutions. What do you think? @mwganson

**Comment by mwganson** [comment]
I won't have much computer time today.  I haven't looked at your code yet.  You may feel free to incorporate what I have done into yours as you see fit.  I suggest making both options available in the context menu.  Then the user can decide which is better for a given situation, whether that is Execute in console or Execute with runString() or whatever option you have. 

There are some advantages to doing it in the console.  You can get better feedback on what is happening by looking at the error messages in the console and report view the way I have implemented it.  Also, the console maintains the context, allowing to interactively experiment with identifiers defined in the executed code.  For example, you can execute a function by selecting it and executing, then in the console you can call the function and inspect its return value.  You can execute the block of imports, and then later execute some code that depends on those imports.  I don't think that's possible with runString() because it most likely creates a new context each time.  You also have the calltips (code completion) in the console that can be better leveraged in this manner by executing the code in the console.  I would like to at some point try to make the calltips available in the editor, and this would most likely use the console context since the editor, being just some static code, would not have its own context.  My idea is if you want the calltips for some imported package, then the way to do it is to select the import lines, execute them in the console, and now the calltips would be available in the editor.

If you are creating a popup dialog where the user can edit the code before executing it, then that is a great way to do it, too, and that code could be executed either in the console or how you are doing it.

**Comment by FlachyJoe** [comment]
IMHO it's better to run the lines in the console.

About the editor calltips, the `import` lines could be detected and a small button could be added in the margin to allow the user to load the module in the editor context.

**Comment by Jonezzzzz** [comment]
The python console runs an instance of the python interpreter. Its a user interface for the interpreter.

The `_doCommand` method is really meant for buttons or other UI elements.

Internally the `_doCommand` method uses the `runString` method to execute code in the interpreter. It also supports macro recording for the command, though this functionality is unnecessary for this application.

Additionally,` _doCommand` prints the executed code to the Python console and adds it to the command history without invoking it. If this is a desired feature, it can be easily implemented—potentially with a setting that allows users to enable or disable this behavior.


So all this:

> There are some advantages to doing it in the console. You can get better feedback on what is happening by looking at the error messages in the console and report view the way I have implemented it. Also, the console maintains the context, allowing to interactively experiment with identifiers defined in the executed code. For example, you can execute a function by selecting it and executing, then in the console you can call the function and inspect its return value. You can execute the block of imports, and then later execute some code that depends on those imports.

works just the same with my solution. However with `runString` if you run
`FreeCADGui.getWindow()`
You get this error message:
`AttributeError: module 'FreeCADGui' has no attribute 'getWindow'.`
but with `runInteractiveString` you get this error message:
`AttributeError: module 'FreeCADGui' has no attribute 'getWindow'. Did you mean: 'getMainWindow'?`
You can't get the interactive error messages with `_doCommand` method, because it uses just the `runString` method.

Why not use only the `runInteractiveString` method? Because you can run only one statement with it.

I hope this clarifies things. @mwganson

> I would like to at some point try to make the calltips available in the editor

That would be a great feature!

**Comment by mwganson** [comment]
I built and tested the PR.  It does indeed make the variables defined in the selected and executed block available in the python console.  But I still would prefer to have it in the console.  Then I can see exactly what was pasted in and executed in case I get an error or just to verify that I selected what I thought I was selecting.  It's a better visual feedback rather than executing it invisibly.  I say offer both options.

Your shortcut does not work unless the context menu is active.  Should be able to simply select and press Ctrl+Shift+E.  Mine does work, so probably I added something that you left out when setting up the shortcut.

The indentation issue you already know about.

I can close my PR at some point since yours was first.

**Comment by FlachyJoe** [comment]
> I still would prefer to have it in the console. Then I can see exactly what was pasted in and executed in case I get an error or just to verify that I selected what I thought I was selecting. It's a better visual feedback rather than executing it invisibly.

:+1:

**Comment by Jonezzzzz** [comment]
I'v updated the code and added your solution to solve the indentation issue. I also added `printStatement` to print the executed code in the console. I changed my mind and agree with you, it's a good feature for debugging code.

> Your shortcut does not work .....

I haven't had that issue. I checked the code and couldn't find any reason for that.
@mwganson

**Comment by mwganson** [comment]
This works well, including the shortcut.  I think what happened in my previous test is the python editor wasn't the active window when I tried it.  It's good that it doesn't work if the python editor is not the active window as this minimizes the risk of a shortcut conflict.

But I don't think it's necessary to call either of the runString methods, just use doCommand() unless you want also the option to not have the statements show up in the console.

**Comment by Jonezzzzz** [comment]
I agree with you, the statements are very useful for debugging. And since you're planning on making the calltips avaible in the editor, the `runInteractiveString` is not needed.

I'll close this PR, since your's allready uses the `doCommand`.

**Comment by mwganson** [comment]
I took my PR out of draft mode since you are closing this one.  No promises on calltips.  I will look into it after my PR is closed.

**Pull request closed without merging**
