### PR TITLE
[For 0.19] support QWebEngine and QWebKit refs

### PR DESCRIPTION
**Pull request by mumme74**
This pull request implements building against QWebEngine if Qt is >= 5.7
I fallbacks to QWebkit if qt is <= 5.6 

You can configure to force use QWebKit with: **cmake ... -DFREECAD_USE_QWEBKIT=ON ...**

This was discussed here [https://forum.freecadweb.org/viewtopic.php?f=10&t=26834#p279083](https://forum.freecadweb.org/viewtopic.php?f=10&t=26834#p279083)

I have tested it on linux Qt4.8, Qt5.12 WebEngine and Webkit
I havent tested the QWebkit part on windows or macOS, just the QWebEngine part.
(I have not yet succeded building QWebKit with Msvc2017..)

References: issue #3774, issue #2986

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Maybe best to keep this for after the release... Not sure about this

**Comment by mumme74** [comment]
Yes it should probably wait until after release.
I did a pull request as suggested by wmayer in his response in the forum thread.

Should I have waited with PR until after 0.18? 
If so I didn't get that, english is not my native language...

**Comment by apeltauer** [comment]
@mumme74 thanks for your patch. I just tried your fix on windows with qt5.12. But I got an exception. Do your have the ability to test your fix on a windows machine? I could provide a Libpack for visual studio 2017 and qt5.12. Or maybe we could debug the code together? Br Manuel

**Comment by mumme74** [comment]
> @mumme74 thanks for your patch. I just tried your fix on windows with qt5.12. But I got an exception. Do your have the ability to test your fix on a windows machine? I could provide a Libpack for visual studio 2017 and qt5.12. Or maybe we could debug the code together? Br Manuel

Thank you for testing.
Yes I can build on windows, Yes I would very much like to test with your libpack.
What does the Exception say?

**Comment by apeltauer** [comment]
We started a topic in Fc Forum See 
https://forum.freecadweb.org/viewtopic.php?f=4&t=34708

Maybe you can try it with the Libpack. I got an exception when running the start workbench.
Ich will test again on Monday and will tell you the exact location...

**Comment by apeltauer** [comment]
Your modifications works with Qt5.12 on windows 10. In my case it was not working during missing files from Qt.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
