### PR TITLE
Base/App/Gui: force using Base::Handle for ParameterManager

### PR DESCRIPTION
**Pull request by realthunder**
@chennes This fixes crash when loading preference pack.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8135">pipeline status</a> for feature branch [PR_8135](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8135). Pipeline [739810410](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/739810410) was triggered at [0185bb5](https://github.com/FreeCAD/FreeCAD/pull/8135/commits/0185bb5b491588f3239b9ca04d4c203438601045). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by luzpaz — CHANGES_REQUESTED** [review]
Not sure why I can't review the code on github (maybe browser or permission issues) but there is a  typo: (should be `custom`)

https://github.com/FreeCAD/FreeCAD/blob/9869a2c3d7bdacdfac605db318c73e3b2d71245c/src/App/Application.cpp#L350

**Comment by realthunder** [comment]
That typo is not from my code change. So I think better use a separate PR for the fix.

**Comment by chennes** [comment]
Thanks!

**Comment by wwmayer** [comment]
Fix typos: 5995556b08

**Pull request merged**
