### PR TITLE
[Path] Fix import error if camotics not installed.

### PR DESCRIPTION
**Pull request by sliptonic**
The camotics python module is provided when the camotics application is installed.  This is not a dependency for FreeCAD, just another applicaiton that the user can install. If it's installed (and recent enough), Path can use it for simulation.
There was already a test in place when the Path workbench loaded which determined whether to enable the button.  But the camotics gui was being imported anyway and was, in turn, trying to import the python module.  this would throw an error.

Commit wraps the import in another test to avoid the error.

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by agren** [comment]
Might be an idea to also check that the camotics module exists.
I can see a case where:
A user who use camotics but does not care about camotics integration cannot run Path because FreeCAD can't find the camotics module.

Something like:
```python
try:
    import camotics
    r = subprocess.run(
    ...
except (FileNotFoundError, ImportError):
    pass
```

Might even be an idea to import and check the module version. But i guess there were no python module available before 1.2.2?
```python
    from camotics import VERSION as CAMOTICS_VERSION
```

**Comment by sliptonic** [comment]
I think I see your point.  I'm assuming that if Camotics 1.2.2 is installed that the python module is also available.  I'll make the suggested change.

Yes, the python module is new.  There was an earlier version with camsim but I'm avoiding that.

**Comment by Russ4262** [comment]
I did not see this PR until now, I can close #7104 if you like, since these two PRs address the same problem.  #7104 might be a little simpler, though it likely needs the dual error type catch as suggested here by @agren .

**Comment by fra589** [comment]
Hi @sliptonic 
  
There is another error with this functionality, when the `camotics --version` don't give the 3 numbers major, minor and patch.

In my Debian, camotics is installed in v1.2.0 and the result of version give only `1.2`
So, the Path module don't load with the error: `not enough values to unpack (expected 3, got 2)`  

You should also add:
```
            except ValueError:
                pass
```
to the PathWorkbench Initialize()
  
Regards,
@++;
Gauthier

**Comment by sliptonic** [comment]
> 
> There is another error with this functionality, when the `camotics --version` don't give the 3 numbers major, minor and patch.
> 


Hmm.  Third time's the charm?   Can you try this: https://github.com/FreeCAD/FreeCAD/pull/7111   
Thanks Gauthier.

**Pull request merged**
