### PR TITLE
[ArchStructure] Variant PropertrySet Support in ArchSketch

### PR DESCRIPTION
**Pull request by paullee0**
[ Similar to https://github.com/FreeCAD/FreeCAD/pull/18057 ]

Now, user can create :

- Variant Layout / combination of ArchStructure (Slab) in addition to ArchWall and CurtainWall based on same ArchSketch, with another PropertySet
- Variant Properties / layer of ArchWall on same ArchSketch with different Width, Offset, Material, Height etc. to create Layers, Composite walls etc. (Layout, Layer, Combination, Composite, Elemented etc.)

FreeCAD Forum Discussion:

- https://forum.freecad.org/viewtopic.php?t=87721&start=130#p794785

### CODE REVIEW

**Comment by maxwxyz** [comment]
@paullee0 there a two small linter warnings

**Comment by paullee0** [comment]
> @paullee0 there a two small linter warnings

Thanks, where can I find the 2 warnings?

**Comment by maxwxyz** [comment]
This is the linter action: https://github.com/FreeCAD/FreeCAD/actions/runs/12211117592/job/34067976613?pr=18336 you can download the artifacts for the log.

Also when clicking on `Files changed` on the top of the PR on GitHub:
Bildschirmfoto 2024-12-07 um 08 52 37

Then you see the comments in the code:
Bildschirmfoto 2024-12-07 um 08 55 00

**Comment by paullee0** [comment]
I see, thanks for the pointer :)

**Pull request merged**
