### PR TITLE
remove personal git-blame-ignore-revs 

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7352">pipeline status</a> for feature branch [PR_7352](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7352). Pipeline [609665716](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/609665716) was triggered at [86b4260](https://github.com/FreeCAD/FreeCAD/pull/7352/commits/86b4260ec3a51bd1b7b918ff7b9db51f6e6126d0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Why? Is this obsolete for some reason?

**Comment by chennes** [comment]
Not as far as I know -- we've been pretty careful about only adding formatting-only commits to it, and its whole purpose is really for use on GitHub.

**Comment by luzpaz** [comment]
@mosfet80 this file is still in use. This PR is invalid.

**Comment by mosfet80** [comment]
I thought the change is better for developers who want to have their own git-blame without worrying about the file being synced to git.
In this way the local configurations are not deleted because their synchronization is ignored.
I close the PR

**Comment by luzpaz** [comment]
Oh I see, I didn't understand the motivation.

**Comment by chennes** [comment]
Developers can still maintain their own ignore files: git itself is not hardcoded to use this filename, you have to set it on the command line. So devs can just create a custom version with a different name and pass it to their local copy of git.

**Pull request closed without merging**
