### PR TITLE
[PD] fixes loft visibility on creation and modification

### PR DESCRIPTION
**Pull request by donovaly**
- the PR fixes the issue reported here: https://forum.freecadweb.org/viewtopic.php?f=3&t=63252
- (also a MSVC code formatting fix)

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
Thanks for the fix. I'm compiling to do the tests. You might want to run `updateUI` in `indexesMoved` as well.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5149">pipeline status</a> for feature branch [PR_5149](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5149). Pipeline [403877052](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/403877052) was triggered at [fc608c1](https://github.com/FreeCAD/FreeCAD/pull/5149/commits/fc608c12acc27451960f00f3cb6f91da0b07df76). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> Thanks for the fix. I'm compiling to do the tests. You might want to run `updateUI` in `indexesMoved` as well.

thanks. I also found another issue and updated the PR now.

**Comment by AjinkyaDahale** [comment]
Looks like it works: now the preview is visible and so is the final product after ending. Do you want to see if sweep also needs this fix. Once incorporated I can work on supporting faces for sections.

**Comment by donovaly** [comment]
> Looks like it works: now the preview is visible and so is the final product after ending. Do you want to see if sweep also needs this fix. Once incorporated I can work on supporting faces for sections.

I started with the sweep/pipe since it worked there. So the fix is only necessary for lofts.

**Comment by AjinkyaDahale** [comment]
> I started with the sweep/pipe since it worked there. So the fix is only necessary for lofts.

Okay then I'll go ahead with the face support.

**Comment by AjinkyaDahale** [comment]
> I started with the sweep/pipe since it worked there. So the fix is only necessary for lofts.

There do appear to be some issues with the sweep:
1. Subsequent sections after first are always visible.
2. After undoing sweep or deleting it, the path sketch is still not visible.

**Comment by donovaly** [comment]
> There do appear to be some issues with the sweep:
> 
>     1. Subsequent sections after first are always visible.
>     2. After undoing sweep or deleting it, the path sketch is still not visible.

This is an undo issue. I don't think this is worth a fix. The sweep path (spine) is purposely made invisible. So when you open a file containing a sweep and delete it, you get a sketch back that is invisible since it was also invisible inside the sweep.

I don't understand your point 1.

However, I think this PR fixes the loft as it should and we should start a new forum thread and later PR for sweep issues.

**Comment by AjinkyaDahale** [comment]
> > There do appear to be some issues with the sweep:
> > ```
> > 1. Subsequent sections after first are always visible.
> > 2. After undoing sweep or deleting it, the path sketch is still not visible.
> > ```
> 
> This is an undo issue. I don't think this is worth a fix. The sweep path (spine) is purposely made invisible. So when you open a file containing a sweep and delete it, you get a sketch back that is invisible since it was also invisible inside the sweep.
> 
> I don't understand your point 1.
> 
> However, I think this PR fixes the loft as it should and we should start a new forum thread and later PR for sweep issues.

OK new forum thread it is. By "subsequent sections" I meant the sections we provide when the section transform mode is "Multisection".

**Comment by donovaly** [comment]
> OK new forum thread it is. By "subsequent sections"

Where is the new forum thread?

> I meant the sections we provide when the section transform mode is "Multisection".

I cannot see an issue with my test file. Can you please attach an example file to your forum post or describe how to reproduce?

**Comment by AjinkyaDahale** [comment]
> > OK new forum thread it is. By "subsequent sections"
> 
> Where is the new forum thread?
> 
> > I meant the sections we provide when the section transform mode is "Multisection".
> 
> I cannot see an issue with my test file. Can you please attach an example file to your forum post or describe how to reproduce?

I meant to keep it as a todo for later tonight or morning.

**Comment by AjinkyaDahale** [comment]
@donovaly see https://forum.freecadweb.org/viewtopic.php?f=19&t=63544&p=545078#p545078.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5149">pipeline status</a> for feature branch [PR_5149](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5149). Pipeline [404206865](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/404206865) was triggered at [0b77c2b](https://github.com/FreeCAD/FreeCAD/pull/5149/commits/0b77c2b2b5e2117ae6ebe61bccd2743748dc0e27). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@chennes , can you please verify this PR and put it in? From our perspective it works and @AjinkyaDahale needs this to be in to work on further loft fixes.

**Comment by chennes** [comment]
Sure, it all looks fine to me, and the CI passed.

**Pull request merged**
