### PR TITLE
TechDraw: Svg export refactoring

### PR DESCRIPTION
**Pull request by pavltom**
Rather larger SVG export refactorization. For detailed description please see TechDraw Development forum topic [SVG export improvements](https://forum.freecadweb.org/viewtopic.php?f=35&t=36909).

### CODE REVIEW

**Comment by WandererFan** [comment]
Tests failed in Windows, but not in Linux.   Don't know why yet.

**Comment by WandererFan** [comment]
My idea in [PR 2238](https://github.com/FreeCAD/FreeCAD/pull/2243) didn't work. 

I've asked for help [on the forum](https://www.forum.freecadweb.org/viewtopic.php?f=4&t=36930)

**Comment by pavltom** [comment]
Finally successful - the failing tests are not related to TechDraw! I am sorry for the problems, unfortunately I do not have a Windows machine with VS 2017, so I have to relay on Travis to debug the Windows build.

**Comment by WandererFan** [comment]
Only FEM failures.  Ready to squash commits after License change.

**Comment by pavltom** [comment]
Perfect, please include also the fixed russian SVG templates, which were added yesterday and the xml:space was used quite extensively. Thanks a lot!

**Comment by WandererFan** [comment]
Still sorting out templates.   Will finish tomorrow.

**Comment by WandererFan** [comment]
Replaced by 2256 (clean history).  will re-apply latest GOSS template fix (69546d2 ) when this 2256 finishes. 

wf

**Comment by pavltom** [comment]
Hi, so [ANSIB issue](https://forum.freecadweb.org/viewtopic.php?f=35&t=36909&p=313710#p313710) fixed, [RU templates handling](https://forum.freecadweb.org/viewtopic.php?f=35&t=36957&p=313706#p313706) as well, details in replies to the topics. I hope nothing more emerges :-)

**Pull request closed without merging**
