### PR TITLE
App: Use auto and incidental bits

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7413">pipeline status</a> for feature branch [PR_7413](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7413). Pipeline [625185385](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/625185385) was triggered at [c748df0](https://github.com/FreeCAD/FreeCAD/pull/7413/commits/c748df0f77953e568ba90c1fdb4a35a6be206151). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
@marioalexis84 Thank you for raising this. I tried it as part of the modernization effort. Both are legal so it becomes a question of local coding guidelines (which we do not have here).

if(ptr) relies on implicit conversion from the type of ptr to boolean which does save some typing and arguably is easier to read. 

OTOH it is a relic of C, which doesn't have bool types. Current tools (e.g. cmake-tidy) and the language itself (e.g. explicit keyword) reflect a trend to making everything explicit. Fewer surprises. Less hidden bugs.

See also: [https://releases.llvm.org/13.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/readability-implicit-bool-conversion.html](url)

**Comment by wwmayer** [comment]
The documentation to [c.PyArg_ParseTuple](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTuple) says:
> Parse the parameters of a function that takes only positional parameters into local variables. Returns true on success; on failure, it returns false and raises the appropriate exception.

Although technically it returns an int semantically it's considered a boolean. If clang-tidy raises a warning then we should think about setting AllowIntegerConditions to true.

**Comment by berniev** [comment]
`semantically it's considered a boolean`

Yes, in the context of **C**  that is correct. The python API code is for C. But in C++ context it clearly returns an int.

Setting cmake-tidy AllowIntegerConditions to true would apply indiscriminately, and hide C style relics which we should be striving to replace.

**Pull request closed without merging**
