### PR TITLE
[FEM] improve new default solver setting

### PR DESCRIPTION
**Pull request by donovaly**
- fix bug if no solver should be default
- only provide solvers that are available to be the default
- also add commit opened transactions
- also remove unused include and correct an include

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9031">pipeline status</a> for feature branch [PR_9031](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9031). Pipeline [817296109](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/817296109) was triggered at [8e692a3](https://github.com/FreeCAD/FreeCAD/pull/9031/commits/8e692a33f0142b51903db7402f6135673f1439af). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by marioalexis84** [comment]
With these changes, on Linux, installed solvers no longer appear in the list of default solvers in preferences if the "Search known binary directories" checkbox is checked: It is necessary to add the path to the solver explicitly.
Even in that case, the resolver selected as default is not used, for example currently on my system only the Elmer resolver is shown in the preferences list (because I type the path manually in the Elmer's preferences) and if I select this as default, when creating the Analysis container, the CalculiX solver is added to the analysis.

**Comment by marioalexis84** [comment]
Also the icons no longer appear despite having the solvers installed and must be selected from the menu bar

**Comment by donovaly** [comment]
Thanks for the report. Can you please have a look and fix this since I only have windows and here I must always explicitly set the path to the binary. Therefore I cannot test well how the binaries are found.

But OK, the Python part of FEM detects the solvers via known paths, so the C++ part must be able to do so as well. I think the fix is simply to take the Python part's solution via a doCommand instead of checking the preferences property.

If you won't have time, please tell me and I will try to to have a look tomorrow.

**Comment by marioalexis84** [comment]
Later I will create a PR with the fix.

**Comment by donovaly** [comment]
Thanks.
Meanwhile I checked that the Python part's FEM binary check does it all right. The "search in known places" feature is in the Python part.

It was a big mistake that I did not realize this earlier, sorry.

**Comment by donovaly** [comment]
I have a PR read, just doing tests. The idea is that QFileInfo does the job since it also checks the system variables of every OS.

**Comment by marioalexis84** [comment]
since you asked me if I could correct it. I'm working on a PR for this.
Can you wait for me to finish it?

**Comment by donovaly** [comment]
I am finished already. So let's both make the PR and then discuss what to use.

**Comment by donovaly** [comment]
Here is my PR: #9051

it was surprisingly easy to code. I think with this we have nice C++ version of the binary_check we ave in Python.

**Pull request merged**
