### PR TITLE
Start: Allow dynamic translation of start page

### LINKED ISSUE #9996: [Problem] Language change doesn't work properly in start page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Finnish/Finland (fi_FI)
[/code]
```

### Subproject(s) affected?

None

### Problem description

Test case:

1. Open freeCAD
2. Go to Edit > Preferences ... > Change language
3. Change language to different one
4. Press OK

Now the language should be changed, but actually some of the text (Start page) are written still in the previous language. 

To get the Start page texts also in the right language you must restart freeCAD.

### Anything else?

BugFreeCAD

Here is example picture where the language has been changed from Finnish to English.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yorikvanhavre**
- reloading the start page now retranslates all the texts
- extend the observer to watch language changes

Fixes #9996

### CODE REVIEW

**Comment by luzpaz** [comment]
How does the pre-commit get solved? Is a merge needed and rebase ?

**Comment by yorikvanhavre** [comment]
AFAICS it passes all the tests? Normally if all goes well I understand we don't need to care about the precommit  commit...

**Comment by Syres916** [comment]
@yorikvanhavre I believe this may have caused a regression, steps to reproduce:

On user being presented with Start Wb, click Empty File button. Edit > Preferences, change Size of recent file list such as increase by one and click OK

Error is generated in Report View:

```
01:10:43  Traceback (most recent call last):
01:10:43    File "<string>", line 16, in reload
01:10:43  RuntimeError: Cannot access attribute 'setHtml' of deleted object
01:10:43  Traceback (most recent call last):
01:10:43    File "<string>", line 16, in reload
01:10:43  RuntimeError: Cannot access attribute 'setHtml' of deleted object
```

Appears as though there should be a `hasattr` condition beforehand??

```
OS: Debian GNU/Linux 12 (bookworm) (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35270 (Git)
Build type: Release
Branch: main
Hash: 1245c3f3b2c18edf505d01036ecdae3f22d349b2
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Assembly3 0.12.0
  * freecad.gears 1.1.0
```

**Comment by bgbsww** [comment]
Something has broken the TestStartGui test in the HTML validation at https://github.com/FreeCAD/FreeCAD/blob/e3b1fe5829c168b26b91555f02c5a036c3841f25/src/Mod/Start/TestStart/TestStartPage.py#L138 and I suspect it is this as the only commit I see in the area.

As this is obviously a work in progress, you can probably ignore this note, but I figured I'd flag that I saw it.

```
/git/freecad-build$ ~/Software/FreeCAD_weekly-builds-35274-2023-12-03-conda-Linux-x86_64-py310.AppImage 
FreeCAD 0.22.0, Libs: 0.22.0devR35274 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Loading Assembly workbench...
During initialization the error "'seaborn-colorblind' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)" occurred in freecad.plot
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/site-packages/matplotlib/style/core.py", line 137, in use
    style = _rc_params_in_file(style)
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 866, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 843, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn-colorblind'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 235, in InitApplications
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/brad/.local/share/FreeCAD/Mod/Plot/./freecad/plot/init_gui.py", line 42, in <module>
    matplotlib.style.use('seaborn-colorblind')
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/site-packages/matplotlib/style/core.py", line 139, in use
    raise OSError(
OSError: 'seaborn-colorblind' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
--------------------------------------------------------------------------------
Cannot find icon: /home/brad/.local/share/FreeCAD/Macro/LasercutterSVGExport.svg
HTML validation failed: Start page source written to your home directory for analysis.FAILED: test_html_validates (TestStart.TestStartPage.TestStartPage)
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/tmp/.mount_FreeCAt8eIzq/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/tmp/.mount_FreeCAt8eIzq/usr/Mod/Start/TestStart/TestStartPage.py", line 203, in test_html_validates
    self.fail(
AssertionError: W3C Validator analysis shows the Start page has 493 errors and 0 warnings:

```

Test run:
```
INFO: 'Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.'
INFO: 'The \u201ctype\u201d attribute for the \u201cstyle\u201d element is not needed and should be omitted.'
ERROR: "CSS: \u201cselection-color\u201d: Property \u201cselection-color\u201d doesn't exist."
ERROR: "CSS: \u201cselection-background-color\u201d: Property \u201cselection-background-color\u201d doesn't exist."
ERROR: 'CSS: \u201cbackground-color\u201d: Parse Error.'
ERROR: 'CSS: \u201cbackground-image\u201d: \u201curl(qss:images_dark-light/background_freecad_dark.svg)\u201d is an incorrect URL.'

... much more of the same ...

INFO: 'Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.'

----------------------------------------------------------------------
Ran 5 tests in 1.23s

FAILED (failures=1)

```

```
OS: Ubuntu 22.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35274 (Git) AppImage
Build type: Release
Branch: main
Hash: dc063eabec61bffc72c92595c66a4649f25fe381
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * FreeCAD_BearingsWB 0.0.2
  * Assembly4 0.50.4
  * fcgear 1.0.0
  * Plot 2022.4.17
  * DynamicData 2.54.0
  * BIM 2021.12.0
  * parts_library
```

**Comment by yorikvanhavre** [comment]
I just checked byexporting the page with

```python
from StartPage import StartPage
StartPage.exportTestFile()
```
and passed it in the W3C validator, but it only gives me trivial warnings:
image
number 2 is specific to my current config and won't happen on a typical build, the others can be safely ignored...

So not sure what is causing that error there, even more 493 errors??

**Comment by bgbsww** [comment]
Right you are!  First try I duplicated this using your export, and then the light bulb went on:  Switching my preference from 'Dark' back to 'Classic' caused the test to pass.  'Light', 'Light Modern', 'ProDark' - everything I tried other than classic will break the test.  So I see a bug here, but I don't think it's related to the translation work.  Apologies for the false alert.

**Comment by bgbsww** [comment]
Probably going to end up creating a bug for this, but noting information as I discover it.  The different between Classic and all the other themes is that classic does not add a MainWindow Stylesheet, and the others do ( which also contains the `selection-color` that validation trips on.

```
        <FCParamGroup Name="MainWindow">
          <FCBool Name="TiledBackground" Value="0"/>
          <FCText Name="StyleSheet">Light.qss</FCText>
          <FCText Name="OverlayActiveStyleSheet">Light_overlay.qss</FCText>
        </FCParamGroup>
```

Bet there's a glitch here...

**Comment by yorikvanhavre** [comment]
#11720

**Pull request merged**
