### PR TITLE
Sketcher task constraint :  fix some issues introduced by PR #7566

### PR DESCRIPTION
**Pull request by 0penBrain**
This PR fixes most (if not all) the issues introduced by #7566 

@abdullahtahiriyo May you be kind to review ? These are quite massive changes at the end. Some changes are almost certainly suboptimal but may be reverted when we decide which parameters to keep as sketch-specific and which as global.
Also it would deserve to be refactored in a more elegant way, probably having the settings enclosed in a class inherited from QMenu. Again, I can probably tackle this when parameter owners are decided.

There are still things to see:
* Constraints hidden because "Show only filtered constraints" is set aren't correctly restored visible when same setting is disabled. Then they stay in virtual space even if filter is disabled completely
* Settings aren't translated directly when you change language. You have to exit+re-enter edit mode
Both looks minor to me (compared to other fixes) and I didn't check if they were introduced by #7566 or were already there before.

**The most important point now**  if you think, having seen this PR, that this isn't the proper way and it's better to cancel all changed and rethink it completely, then please reject this PR and revert PR #7566 -- we have to do it quickly enough so that there is no merge conflicts --.

@adrianinsaval May you be able to give it a functional testing ?

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7886">pipeline status</a> for feature branch [PR_7886](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7886). Pipeline [706319413](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/706319413) was triggered at [2335fa9](https://github.com/FreeCAD/FreeCAD/pull/7886/commits/2335fa99630319dde47a279a565ed39a13acd209). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7886">pipeline status</a> for feature branch [PR_7886](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7886). Pipeline [706320174](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/706320174) was triggered at [b96e55a](https://github.com/FreeCAD/FreeCAD/pull/7886/commits/b96e55a37e941935858153512ddd6d18b85146d3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
the checkboxes are now working correctly within the same session, but it seems the state is not saved to the config file, any time you close and restart freecad everything is back to where it was, including active filters and the filter checkbox.
I guess this could be because now the menu is using a generic checkbox while the widget was using a PrefCheckBox?

**Comment by luzpaz** [comment]
Needs rebase

**Comment by PaddleStroke** [comment]
Sorry about this situation. I said that Abdullah visually approved the constraint widget, and Uwe must have misread and thought that Abdullah reviewed the code.
And sorry I didn't fix the checkboxes issue reported by adrianisaval when you raised them.

You may be right adrianisaval, prefcheckbox check state is handled automatically I think. So what is missing might just be the initialisation of the checkboxes in the ctor (in the createAction of setting button function). Though I can't jump in the code right now. Will be back after new year.

**Comment by PaddleStroke** [comment]
Forget what I said before its inaccurate. The checkboxes state are being initialized. https://github.com/FreeCAD/FreeCAD/blob/b96e55a37e941935858153512ddd6d18b85146d3/src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp#L776
So this needs further testing which I can't do now. Do you see the same bug in master?

The checkbox of element widget are working, so I guess it just needs to compare them. There's one thing you added 0penBrain which I don't understand the use it's `hGrp->Attach(this);` Maybe it has something to do.

Btw why did you removed the createSettingButtonActions and connectSignals function and put back everything in ctor? Not that I'm specially against, just curious.

**Comment by 0penBrain** [comment]
> the checkboxes are now working correctly within the same session, but it seems the state is not saved to the config file, any time you close and restart freecad everything is back to where it was, including active filters and the filter checkbox. I guess this could be because now the menu is using a generic checkbox while the widget was using a PrefCheckBox?

Thanks for testing. Could you more precise about the not working checkboxes ? The only issue I found is the 2 latest filters ('Selected' and 'Associated') that aren't saved. The other checkboxes (being it settings or filter) seem to be saved & restored correctly.

**Comment by PaddleStroke** [comment]
> The only issue I found is the 2 latest filters ('Selected' and 'Associated') that aren't saved.

This was done on purpose actually. Originally I thought it best to save only the 'normal filter' and not these special filters.
But if you feel it's confusing and would be best to save as others it should be easy to include them in the preference int.

**Comment by 0penBrain** [comment]
> This was done on purpose actually.

Indeed. I check sooner and saw this is wanted behavior. Not a strong opinion but think saving also these 2 filters is more natural.

**Comment by adrianinsaval** [comment]
the advanced filters are correctly restored in the filter list now, but are not applied until you uncheck and check again. Same situation with the "Show only filtered" checkbox. The rest of the checkboxes seem to work and get restored correctly.

Even if you don't manage to fix those it's probably best to merge as it is an improvement, you can always make a follow up PR.

**Comment by 0penBrain** [comment]
> the advanced filters are correctly restored in the filter list now, but are not applied until you uncheck and check again.
> 
> Similar situation with the "Show only filtered" checkbox, it doesn't take effect until you trigger an update of the filters.

Thanks for clarifying. I didn't catch this. I pushed a commit to fix. I think I will merge in some hours.
To me the only minor problem remaining is visibility management when playing with "Show only filtered constraints" in combination with enabling/disabling filter. Will log an issue and process later.
However if you find other bugs, feel free to report in this conversation even after merge.
Thanks for helping.

**Comment by donovaly** [comment]
> Sorry about this situation. I said that Abdullah visually approved the constraint widget, and Uwe must have misread and thought that Abdullah reviewed the code.

No, I was aware that there was no code review. But
- the PR was open for a while and received tests from several persons
- in our meeting you said we should trust you more ;-)
- I had no time for the code review as well as Abdullah 
- our policy is to allow to break things in master

The latter is important because we are all volunteers, Abdullah is sometimes off for weeks, now you will be off. When we are out of a freeze, we can handle this by pushing in then someone who has time can review, people test the weekly and so on. That's the idea of the "allow to break" policy. Which does not mean we purposely break things, the policy was once setup (before I joined FC) for cases like this here.

I am happy that 0penbrain found time to review and Adrian for more testing.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7886">pipeline status</a> for feature branch [PR_7886](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7886). Pipeline [710513860](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/710513860) was triggered at [824712f](https://github.com/FreeCAD/FreeCAD/pull/7886/commits/824712f87169724a61c37d5680471236395b88c7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
> * the PR was open for a while and received tests from several persons

I will tell it again :yum: but this is where the problem was hiding in the original PR. While the PR was open for a sufficient time and has been tested, extra commits were added to the PR that added other code modifications and unfortunately introduced bugs. These later changes didn't get time neither to be reviewed nor to be tested before being merged.

We should not hide behind some "allow to break" policy to encourage such things to happen. We should altogether learn from this to adapt.
To me such "this can break" merge are acceptable, but one (I think contributor or maintainer) shall commit enough availability in near future to fix found problems.

**Comment by 0penBrain** [comment]
> Btw why did you removed the createSettingButtonActions and connectSignals function and put back everything in ctor? Not that I'm specially against, just curious.

I did it because it makes the code clearer to me to have this in a sequential way (these functions were called only once in the ctor) and so safer to provide quick patch that I didn't really have time for. ;)

> I understand now, `hGrp->Attach(this);` is to catch if the settings are modified somewhere else and update the checkboxes statuses. I understand it's to keep checkboxes between solver message and here in sync.

Actually, `Attach` registers you as an observer of a parameter group (you can search the web for "observer pattern" for more complete information). This indeed allows to be in sync, but not just only with the solver message. Actually with virtually any event changing the settings (user in preferences, user in parameter editor, macro through Python, ...).

**Comment by abdullahtahiriyo** [comment]
Thanks @0penBrain.

**Comment by abdullahtahiriyo** [comment]
> That's the idea of the "allow to break" policy. Which does not mean we purposely break things, the policy was once setup (before I joined FC) for cases like this here.

As I said, I do take the blame. It has not been critical this time. @0penBrain did great.

As I see it, the Sketcher is a critical component of FreeCAD with a certain level of maturity in terms of functionality, with some people relying on master for their daily job (I make no judgement of how sound such policy may be). We also take good advantage of this people for early discovering bugs that may have gone unnoticed during testing and review. 

This is why, personally, I strive to distance myself from the "allow to break" policy and try to provide a higher level of review for the Sketcher WB. My contract with the users of the sketcher is that they should reasonably expect I will do my best so that master is working. I only ask in exchange early report of anything that has slip through.  In my good times I could commit to fast bug-fixing too. At least for the time being this is not always possible for me.

Now that @0penBrain has joined as maintainer, I hope we will be able to make it work.

**Comment by donovaly** [comment]
> I will tell it again 😋 but this is where the problem was hiding in the original PR. While the PR was open for a sufficient time and has been tested, extra commits were added to the PR that added other code modifications and unfortunately introduced bugs. These later changes didn't get time neither to be reviewed nor to be tested before being merged.

Yes, this was a bad move. At the time I merged, I was not aware of these last-minute changes.
However, the next time we will do it better.

@abdullahtahiriyo , when you are currently working on Sketcher, can you please have a look at this PR: #7688
This fixes a bug and I would like to release FC 0.20.2 this Sunday and have the fix in if possible.

**Comment by 0penBrain** [comment]
> @abdullahtahiriyo , when you are currently working on Sketcher, can you please have a look at this PR: #7688

I will test and merge if OK today.

**Comment by 0penBrain** [comment]
@PaddleStroke Are you planning to solve the 2 remaining bugs mentioned in this PR description ?

**Comment by PaddleStroke** [comment]
Yes I will have a look

**Pull request merged**
