### PR TITLE
FEM: [Crowdin] fix typo in ElectrostaticPotential.ui tooltip

### PR DESCRIPTION
**Pull request by luzpaz**
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/143
[skip ci]

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6863">pipeline status</a> for feature branch [PR_6863](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6863). Pipeline [535904155](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/535904155) was triggered at [646dc90](https://github.com/FreeCAD/FreeCAD/pull/6863/commits/646dc903b70616979b859888ecae4f8488b4882d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6863">pipeline status</a> for feature branch [PR_6863](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6863). Pipeline [535907862](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/535907862) was triggered at [b5f8e30](https://github.com/FreeCAD/FreeCAD/pull/6863/commits/b5f8e307f22ccb83c9703bb564861687a8a3b810). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
dang, i included a code change I didn't intend to. My GUI git client isn't working and I need to figure out how to do a simple operation of reverting the change and cherrypicking the correct commit instead. lol  
Sorry for the noise

**Comment by luzpaz** [comment]
Closing in favor of https://github.com/FreeCAD/FreeCAD/pull/6866 (cop out, i know)

**Pull request closed without merging**
