### PR TITLE
Add Control Landing Depth

### PR DESCRIPTION
**Pull request by paullee0**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
There is some problem with the first line that has been replaced in your commit, if you look at the Travis details, apparently some unprintable character has been added there that make the python3 test fail. I'll try to replace it here myself...

**Comment by paullee0** [comment]
Thanks taking so much time and guideline.

I guess I need to avoid using LibreWriter for comparing difference.

**Comment by yorikvanhavre** [comment]
The best is to use a pure text-based editor like notepad++ on win or geany/gedit/kate on linux (there must be some equivalent on mac too), so you see the bare text and not a rendered version of it. These tools also have better tools too for diffing/comparing files...

**Comment by paullee0** [comment]
Yes, I use gedit on Fedora.  Now, checking diff command! :) 

The key I learn is to use/rebase latest remote - otherwise got so much difference I try to see / edit in LibreWriter trackchange mode leads to other problems.

Thanks again for the tips.

**Comment by yorikvanhavre** [comment]
And git diff itself also has a lot of possibilities... So you can basically always know "what did I change in such file since such version" (a commit,a branch, whatever)

**Pull request merged**
