### PR TITLE
fix Qt4 build

### PR DESCRIPTION
**Pull request by donovaly**
should fix three Qt4 build, see #2975 and https://forum.freecadweb.org/viewtopic.php?f=35&t=42414&start=10#p365414

### CODE REVIEW

**Comment by donovaly** [comment]
OK, Travis says Qt4 bulds now. Please merge since this should enable the Qt4/Py2 build for all pending PRs

**Comment by vocx-fc** [comment]
Awesome job!

**Comment by WandererFan** [comment]
included in #2986

**Comment by wwmayer** [comment]
Remark:
User visible text should be added to translation system and thus QString::fromLatin1() or QString::fromUtf8() must be avoided. Instead use tr().
See e4be9e43d

**Comment by donovaly** [comment]
> User visible text should be added to translation system and thus QString::fromLatin1() or QString::fromUtf8() must be avoided. Instead use tr().

Thanks.

**Pull request closed without merging**
