### PR TITLE
[AddonManager] Fix missing string for translation in python messages 

### PR DESCRIPTION
**Pull request by Kuzma30**
[AddonManager] Make all translate() strings in python in one style, that recognized by
updatets.py  script.
More info here https://github.com/FreeCAD/FreeCAD-translations/issues/133
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6853">pipeline status</a> for feature branch [PR_6853](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6853). Pipeline [534190675](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/534190675) was triggered at [355485b](https://github.com/FreeCAD/FreeCAD/pull/6853/commits/355485b290b09afa0cc69545ee2a528abfb11965). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
nice catch

**Comment by Kuzma30** [comment]
This is final version. Please review.

**Comment by yorikvanhavre** [comment]
In any case, are you sure this solves any issue?

**Comment by yorikvanhavre** [comment]
beware that that version of pylupdate didn't encode properly. that's why i switched to pylupdate5

**Comment by chennes** [comment]
Oh, I thought this *was* the version you are using. Do you have a link to the source of the actual code you are running? That's what I need to apply the patch to.

**Comment by yorikvanhavre** [comment]
Crazy, those ar 2 completely different programs... No wonder there is so much difference
This one is python. Should be MUCH easier to tweak

**Comment by chennes** [comment]
The actual extraction isn't Python, that script is just a wrapper around some C functions (`fetchtr_py` in this case).

**Comment by chennes** [comment]
A diff between the versions of fetchtr.cpp between pylupdate and pylupdate5 shows pretty significant deviations -- my read is that the one in pylupdate is quite a bit newer. It does have a few chunks of code related to the encoding -- I wonder if switching the default in that file from ISO-8859-1 to UTF-8 would be enough to fix that encoding problem we were having.

**Comment by Kuzma30** [comment]
@chennes I am trying to build your debian fork (https://github.com/chennes/pyside2-debian) on Ubuntu 22.
```
python3 setup.py install --qmake=/usr/bin/qmake 
Unsupported python version detected. Only these python versions are supported: [(2, 7), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9)]
```
I have
```
python3 --version
Python 3.10.4
```

**Comment by yorikvanhavre** [comment]
> See in particular: https://salsa.debian.org/python-team/packages/pyqt5/-/blob/debian/master/qpy/pylupdate/fetchtr.cpp#L201
> 
> versus https://salsa.debian.org/qt-kde-team/qt/pyside2/-/blob/master/sources/pyside2-tools/pylupdate/fetchtr.cpp#L160

Ooh good catch... I think that might be it indeed.

**Comment by donovaly** [comment]
I prefer to make a decision this week before the 0.20 release. If this PR is not merged, please close it. If there is something to merge in future, please open a new PR.

**Comment by Kuzma30** [comment]
Ok, I close this PR. Waiting for another way fix.

**Comment by Kuzma30** [comment]
https://github.com/FreeCAD/FreeCAD-translations/issues/151

**Pull request closed without merging**
