### PR TITLE
Implemented #3204

### PR DESCRIPTION
**Pull request by SparkyCola**
Hi, I implemented my own request [#3204](https://www.freecadweb.org/tracker/view.php?id=3204) with some limitations for arcs, circles and ellipses as well as a pretty big limitation for b-splines.

### CODE REVIEW

**Comment by wwmayer** [comment]
Forum link: https://forum.freecadweb.org/viewtopic.php?f=17&t=24748

**Comment by luzpaz** [comment]
@SparkyCola if you're submitting a fix (aa26b0020864f8759a497eff699d1cacebe67f53) for another ticket then open a separate PR for it.

**Comment by SparkyCola** [comment]
@luzpaz I'm was not trying to submit it yet, I'll put the new work onto a new branch.

**Comment by SparkyCola** [comment]
sorry for the delay, but travis and appveyor don't seems to realize that the code didn't change just the commit message (to work better with mantis).

**Comment by SparkyCola** [comment]
I can't always have the merge the changes of FreeCADs master into mine because Travis CI and Appveyor will then never be finished compiling the changes. Please tell me what to to do in order to accept my request.

**Comment by wwmayer** [comment]
When opening a PR then just leave it as is afterwards. Do not merge back FreeCAD master to your branch as it only complicates things.

**Comment by wwmayer** [comment]
There is some strange behaviour:
for circle and ellipse:
1. make box that it intersects shape but doesn't include center => selects shape and center
2. make box that it doesn't intersect shape but includes center => nothing selected

for arcs of circle and ellipse
make box that it intersects shape but doesn't include center => selects shape and center and both end points

for arcs of parabola and hyperbola
make box that it intersects shape but doesn't include end points => selects shape and end points

=> Elements that are not intersected by the box or isn't inside it should not be selected.

**Comment by SparkyCola** [comment]
> Elements that are not intersected by the box or isn't inside it should not be selected.
What about the center-point of circles and such, I thought it would kinda belong to the circle?

**Comment by SparkyCola** [comment]
I'm wondering what the standard behaviour of other CAD-programs as it makes sense to have the same implicit rules unless there are good reasons to not have them

**Comment by wwmayer** [comment]
I don't see any use case where it would be helpful to have selected the shape and center of a circle or arc, ...
1. When deleting an object it suffices to select the shape as it also deletes the center. And if both are selected then it even creates an error message that it could not delete the constraint on a point
2. When moving an object nothing needs to be selected. Instead you pick the center and drag it to the new location. When doing this for the shape then it doesn't move the object but changes its radius

**Comment by SparkyCola** [comment]
Ok you're right so I'll change that. Maybe the multi-move would be a cool feature, but for now there are enough more important things to do.

**Comment by SparkyCola** [comment]
done

**Comment by wwmayer** [comment]
Merged.

**Comment by RaNo99** [comment]
Hey guys. Is it only me, or this new feature is cumbersome? When selecting, oftentimes it is more convenient to start dragging from the right rather than from the left. For instance if there are many other objects to the right, I would drag from the left, because by dragging from the right I could accidentally move those other objects.

I was used to the flexibility of the previous solution where I didn't have to think which side to drag from, and where I had the choice to drag from any side I want.

How about incorporating some option button, like "Ctrl", "Shift", or "Alt" to toggle the behavior of box selection, rather than relying on which side you start dragging from?

**Comment by luzpaz** [comment]
@RaNo99 the more appropriate place to discuss this is in the dedicated forum thread associated with this PR: https://forum.freecadweb.org/viewtopic.php?f=17&t=24748

**Pull request closed without merging**
