### PR TITLE
[Gui] Allow dot as decimal separator for locales not using it as thousand separator

### PR DESCRIPTION
**Pull request by 0penBrain**
- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [X] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

More details in the commit message

### CODE REVIEW

**Comment by 0penBrain** [comment]
Don't merge now. Porting same modification to PrefDoubleSpinBox. :)

**Comment by donovaly** [comment]
Wouldn't this contradict the outcome if this discussion?: https://tracker.freecadweb.org/view.php?id=3795

**Comment by donovaly** [comment]
We are already feature frozen and this change would have massive influences on many Workbenches. Therefore I am opposed to these last minute changes for FC 0.19.
Instead of changing the framework we should now concentrate on updating the docs, testing, bug fixing, tooltips etc.

Let's discuss the technical things of this PR in this forum thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=35927

**Comment by 0penBrain** [comment]
@donovaly : I updated the PR with a new solution that should be fair for everybody. Could you please test again ? Typically with German locale, you should see no difference.
@wwmayer : I know from the forum discussion you seemed quite opposed to this solution. However this is both the best I found and (from my researches) how other Qt software handle that. If you're definitely opposed to this, please reject the PR or tell me and I'll kill it.

**Comment by donovaly** [comment]
> @donovaly : I updated the PR with a new solution that should be fair for everybody. Could you please test again ? Typically with German locale, you should see no difference.

Looks good. However, I am still reluctant if such a change should go in for FC 0.19 or better for the next version.
I think @wwmayer will decide this.

**Comment by yorikvanhavre** [comment]
My opinion is that this is a good addition, but should be optional. Some people might specifically WANT to use the dot as a thousands separator. For example when copy/pasting from other applications.

**Comment by 0penBrain** [comment]
@yorikvanhavre : actually shouldn't be a problem (even this should better with PR merged). ATM if you copy a value with period as decimal separator, and try to paste in a QDoubleSpinBox while your locale is comma decimal separator, this will just not paste correctly. With PR merged, period will be replaced by locale decimal separator (if the period isn't used as thousands separator in your locale too) which will allow for correct pasting.
Briefly said, this PR will not add any regression from user perspective.

**Comment by chennes** [comment]
I've read through https://forum.freecadweb.org/viewtopic.php?f=3&t=35927 and I still don't have a sense of whether we've arrived at a consensus on this. It's an optional feature, which seems to address @yorikvanhavre's concern, and my read is that @donovaly is happy with this as well. But if @wmayer thinks this isn't the right path we should close it rather than just letting it sit here.

**Comment by 0penBrain** [comment]
Indeed the current (I can't say "new" anymore :yum: ) implementation makes the function totally optional. If the switch isn't set, there is strictly no overhead added in the application.
Also this isn't an intrusive PR, so reverting it would be more than easy.
Just so everybody has the context, be aware that for French people (and all other using same keyboard style), we have a boring inconsistency as we can use our numpad decimal separator on quantity spinboxes, but not on standard "unitless" spinboxes.
Anyway, good if we can close this PR (with or without it to be merged). I can rebase to latest master if needed.

**Comment by yorikvanhavre** [comment]
For me, now that it's optional, everything is basically ok to merge ( @0penBrain please remember to update https://wiki.freecadweb.org/Fine-tuning afterwards? ). However, I feel the general opinion is that this is a hack basically for your own use case (" i will enter my numbers as 1000000.0 on a french locale"), and people would prefer a more universal solution that use locales properly. For ex, @wwmayer suggested allowing to change the locale for input (the C locale allows to write 100000.0). but that's of course more wor, i'm not sure how to do that. But maybe that would be a more interesting path?

**Comment by 0penBrain** [comment]
@yorikvanhavre the problem isn't exactly this (and sure not my special use case). The fact is that Qt (in QSpinBox in this case) handles locale. So when you work with a French locale, it expects the decimal separator to be a comma, and it actually rejects entering a dot. The problem is that (and here probably is the stupid thing, but I can't leverage this) the French keyboards on the numpad come with a dot (!!!) -- Belgian keyboards too, if you have one -- and the emitted charcode is really a dot. Hence my PR.

**Comment by adrianinsaval** [comment]
same thing with spanish keyboards, they come with a dot. In spanish the dot should be used as a thousand separator, does that mean that I won't be able to use the numpad to input a decimal separator? Could this be generalized to use the dot key as decimal separator always by checking Qt::KeypadModifier?

**Comment by 0penBrain** [comment]
@adrianinsaval OK, Spanish is worse then French. :rofl: Indeed in the current implementation, it won't work for you as dot is your thousand separator. It could be possible to use Qt::KeypadModifier to enforce decimal separator when using the numpad. I unfortunately have seen keyboards where it wasn't implemented, and even keyboards where modifier was reversed !!! -- KeypadModifier was emitted from alphapad, and not from numpad --.
I eventually can update the PR to some compromise : "dot is converted to local decimal separator if (it comes from the numpad) or (local thousand separator is not dot)". Of course it will make the conversion only for spin boxes, will stay an option (off by default) and will be easy to disable if problem arises after activation.

**Comment by yorikvanhavre** [comment]
In any case, indeed the problem is tricky, and poorly supported everywhere (keyboards, qt...) so i'm not against a hack that works :) and as i said, since it's optional, i'm fine with merging it as is. Tell me if you want to work further on it or not, @0penBrain

**Comment by 0penBrain** [comment]
@yorikvanhavre I'll do according @adrianinsaval regarding Spanish case (which indeed is very special). In any case I'll rebase against master and ping you in this conversation when done.

**Comment by 0penBrain** [comment]
@adrianinsaval : could you please give output of this macro https://forum.freecadweb.org/viewtopic.php?f=3&t=35927&start=40#p380255 ?

**Comment by adrianinsaval** [comment]
Qt 5.15.2 / Locale ('Spanish_Paraguay', '1252')
Alpha : 0x34 // 0xbe // 0x2e // 0x0
Numpad : 0x53 // 0x6e // 0x2e // 0x20000000

**Comment by 0penBrain** [comment]
@adrianinsaval Thx. Will update the PR so it will hopefully do the trick for Spanish fellows too. :)

**Comment by 0penBrain** [comment]
@yorikvanhavre I'm ready now. I tested with different keyboard configuration but not necessarily different locales, si I think better if some different foreign users could test. Maybe you can do for Belgian layout. :) 

@adrianinsaval : could you test expected improvement is achieved for Spanish layout ?
@donovaly @chennes : may you test there is no regression for DE+US layouts ?

**Comment by adrianinsaval** [comment]
I won't be able to until tomorrow, can you remind in what input fields specifically I have to test?

**Comment by adrianinsaval** [comment]
scratch that, I won't be able to test, I tested at my work computer before but my own computer doesn't have a keypad :(

**Comment by 0penBrain** [comment]
OK. So @yorikvanhavre maybe the best is to merge to get user feedback. As it is fully optional, I guess it cannot really harm.

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_3256

pipeline for commit 510cbf523aaa0c:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/377906367

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by chennes** [comment]
I'll go ahead and merge as per @yorikvanhavre's suggestion, since that's really the only way to get adequate testing for something as finicky and location-specific as this.

**Comment by 0penBrain** [comment]
@chennes Thx. What would you think if I open a new topic on the forum to raise the attention there so we have some testers? I'm afraid almost nobody will notice this option availability if we don't do this.

**Comment by chennes** [comment]
Yes, definitely do that (and make sure to update the wiki, too).

**Comment by 0penBrain** [comment]
@chennes I never forgot wiki :rofl:

**Pull request merged**
