### PR TITLE
Draft: various fixes in code, style, spaces, and organization

### PR DESCRIPTION
**Pull request by vocx-fc**
This pull request includes many commits that are meant to be small fixes in the code style, to better organize it, and to comply with PEP8.
* It moves the header comments at the beginning of the file so that the LGPL2 license is the first element. Then it arranges the import of modules immediately after.
* It adds various `"""documentation strings"""` to many functions and classes.
* It adds many spaces after commas, particularly in lists, tuples, and argument functions: `(0,1,2)` becomes `(0, 1, 2)`.
* It adds spaces when necessary and removes trailing spaces in other cases.
* It shortens lines so that they are shorter than 80 characters per line.
* It does not introduce new functions or major changes that could disrupt the workbench.

For this pull request I don't want to squash the commits into a smaller number of commits; ideally each commit modifies a single file, so it is easy to review the changes. Only a few commits modify more than one file.

This request needs to be merged after #3097 because it builds after it. When that one is merged, this one should be rebased.

Since this request touches many files, it may also cause a conflict with other requests like #2985, #3023, #3102, and #3137, so these will have to be rebased.

Forum thread: [[Discussion] Splitting Draft tools into their own modules](https://forum.freecadweb.org/viewtopic.php?f=23&t=38593&p=375838#p375838)

---

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
needs conflict solving

**Comment by vocx-fc** [comment]
This cannot be merged right now. It has a low number, but it actually has to be merged after #3017, #3091, #3092, #3093, #3094, #3095, #3096, and #3097.

Then, if #3102 is merged first, this will have to be rebased, otherwise it can follow right after #3097.

**Comment by yorikvanhavre** [comment]
All these PRs now have a merge conflict to solve... I still try to go from the older to the newer, unless you say otherwise in the comments

**Comment by vocx-fc** [comment]
> All these PRs now have a merge conflict to solve... I still try to go from the older to the newer, unless you say otherwise in the comments

@yorikvanhavre please read my comments. This should not be merged right now, it has to come after these #3091, #3092, #3093, #3094, #3095, #3096, and #3097.

**Comment by yorikvanhavre** [comment]
Okay finally all the other prerequisites have been merged. So now it's this one's turn right?

**Comment by vocx-fc** [comment]
Yes. This is now rebased onto the master branch. It can now be merged cleanly, and then #3106 and #3156 can follow.

**Comment by vocx-fc** [comment]
Awesome.

@carlopav heads up, small fixes were merged, so now I'm afraid that you have to rebase a lot of your code in DraftGui, DraftTools, Draft_Edit, etc.

**Comment by carlopav** [comment]
Wow! Well, congratulations @vocx-fc @yorikvanhavre! This is a big step forward !

I'm planning to rebase the modification I made to the snapper and to the snaps commands, since I think that is an obvious improvement over the current situation. 
Don't know instead about https://forum.freecadweb.org/viewtopic.php?f=23&t=44051&p=383386#p383386 : should I rebase it to let yorik review it?

**Comment by vocx-fc** [comment]
Yes, you should rebase your branches to make sure there aren't serious conflicts. As I can see from my side, I don't think I will touch the files that you are working on.

In #3157 I move the plane proxy from the current `gui_selectplane` to `gui_planeproxy`, but I'm not sure if you need that file at all.

**Comment by carlopav** [comment]
Ok! Let's do it so!

**Pull request merged**
