### PR TITLE
Fix tab order in Add Property Dialog (VarSets)

### LINKED ISSUE #17067: VarSet: add property dialog needs better accessibility, cannot use keyboard to navigate through fields
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Start FreeCAD; create new document
2. Create a new VarSet, as described in https://wiki.freecad.org/Std_VarSet
3. On the Add property dialog, enter a name on the first field (`Name`)
4. Press the <kbd>Tab</kbd> key on the keyboard to navigate to the next field (`Group`)
4. Press the <kbd>Tab</kbd> key on the keyboard to navigate to the next field (`Type`)
5. **Expected**: focus is on the _next_ field (`Type`)
5. **Actual**: focus is on the _previous_ field (`Name`)

The effect is that repeatedly pressing the <kbd>Tab</kbd> key simply alternates between the `Name` and `Group` field in a loop. The rest of fields cannot be accessed via keyboard alone.

It would seem that the tab order needs to be defined on that dialog.

https://github.com/user-attachments/assets/3fa2ad5f-ca7d-4805-a602-fd1c1f6cfb16

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38898 (Git) Snap 1157
Build type: Release
Branch: main
Hash: 32e09d9554db26414697ed19e0189ccab4ea9029
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * ezydxf
  * Ondsel-Lens 2024.9.13.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Core

### Anything else?

1. Seeing the [number of issues](https://github.com/orgs/FreeCAD/projects/30) this dialog has, I wonder if it would not be best to start using the original "add property" dialog and simply adding the extended functionality to it (https://github.com/FreeCAD/FreeCAD/issues/14633).
1. When the `Type` field is clicked, the tab order works correctly from there (from `Type` to `OK` and back only).
1. I could not figure out how to fix the tab order, but while looking at it, I also noticed that the dialog title ("Add a property to ") needs to be internationalized, as it looks like it's not translatable. I might file a follow up issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kriswilk**
Fixes #17067

Tested/compiled on Windows 11 23H2.

### CODE REVIEW

**Comment by kriswilk** [comment]
> Thanks, looks good! I had problems with getting the same behavior on both Qt 5 and Qt 6, but this seems to work properly on Qt 6 now. Just to be sure, someone could check with Qt 5?

I'd certainly welcome anyone else to verify. I'm still very new here... 👍

**Comment by furgo16** [comment]
Thank you. I've just tested it by applying the patch on a local build (Qt 5) and rebuilding. It did not seem to fix the issue.

I'll build the proper branch next and report back.

```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38896 +1 (Git)
Build type: Debug
Branch: offset-rotation-tooltips
Hash: 8c34e374cf96b235fc6f9a649d54015960bae54d
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * WikiPropertiesGenerator.FCMacro
```

**Comment by furgo16** [comment]
Unfortunately, it doesn't work here. I did a fresh checkout and clean build.

```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38898 +1 (Git)
Build type: Debug
Branch: fix-varset-dialog-tabstops
Hash: 1e774c444662c1754d0a9de546d81265d5c27ed0
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * WikiPropertiesGenerator.FCMacro
```

**Comment by furgo16** [comment]
> can you describe what behaviour you're observing after the fresh build? Is it still just alternating between Name and Group?

@kriswilk yes. I followed the steps to reproduce and I'm seeing the same behavior as described on https://github.com/FreeCAD/FreeCAD/issues/17067. Up to the point of then clicking on the `Type` cell and the tab order working between `Type` to `OK` and `Name` to `Group`. But these two sets of tabstops appear to be disconnected, as one can never switch from `Group` to `Type`.

This screencast running this branch illustrates this behavior. I'll include it on the original issue as well:

https://github.com/user-attachments/assets/3fa2ad5f-ca7d-4805-a602-fd1c1f6cfb16

**Comment by kriswilk** [comment]
I took another look at this and discovered that even unpatched, the tab order is fine in the latest 1.1.0 dev branch... when compiled with Qt 6. I had reproduced the problem in 1.0RC2 which is built with... Qt 5.

So really, my change does not address the issue. I will look at the code in more detail tomorrow, including the segment that you referenced, @furgo16.

**Comment by furgo16** [comment]
Thanks. Some quick testing, picking up from my last comment:

1. Remove the `QWidget::setTabOrder()` lines,
   - That did not quite work. The tab order is then `1. Name` > `2. Type` > `3. Value` > `4. Add another` > `5. Tooltip` > `6. Cancel` > `7. OK` > `8. Group` > `1. Name`. Notice `8. Group` being out of sequence. It should be `2. Group`
1. or continue defining the `QWidget::setTabOrder()` calls for each widget.
   - I've not tested this yet. I'll try it next.

**Comment by kriswilk** [comment]
The [Qt 5 documentation](https://doc.qt.io/qt-5/qwidget.html#setTabOrder) for `setTabOrder()` notes that "_it effectively removes the second widget from its focus chain and inserts it after the first widget_".

The calls to `setTabOrder()` create the truncated focus chain. Not sure yet why it doesn't reach the Type box, though.

Nor do I know (yet) why Qt 6 seems unaffected.

**Comment by pieterhijma** [comment]
Great you're taking a good look at this! Indeed, I've been trying to fix this while developing and couldn't get it to work properly. Indeed, `DlgAddPropertyVarSet.cpp` has debugging code in the comments that shows you the focus chain. I couldn't find a solution that would work for both Qt 5 and 6. 

Perhaps a suggestion to simply leave it if it works in Qt 6. If I'm correct, we're dropping Qt 5 in Feb/March or so.

**Comment by furgo16** [comment]
> Perhaps a suggestion to simply leave it if it works in Qt 6. If I'm correct, we're dropping Qt 5 in Feb/March or so.

Other than the fact that dates in development should not be trusted :-), that would still leave 1.0 users with suboptimal accessibility (assuming that 1.0 will be shipped with Qt 5, which I do not know).

**Comment by kriswilk** [comment]
I'd also like to understand this discrepancy, even if it may ultimately be irrelevant in a few months.

@furgo16, @pieterhijma or anyone... can you explain how to compile against Qt 5 on Windows? I've just been using the wiki instructions and the prebuilt LibPack 3.0.0. Do I need to build a different LibPack? Download Qt separately? I see cmake options related to Qt 5 but am not sure how to get that going.

Once I can compile patches against either Qt version I can study this further.

**Comment by pieterhijma** [comment]
> I'd also like to understand this discrepancy, even if it may ultimately be irrelevant in a few months.
> 
> @furgo16, @pieterhijma or anyone... can you explain how to compile against Qt 5 on Windows? I've just been using the wiki instructions and the prebuilt LibPack 3.0.0. Do I need to build a different LibPack? Download Qt separately? I see cmake options related to Qt 5 but am not sure how to get that going.
> 
> Once I can compile patches against either Qt version I can study this further.

Hm, that would be difficult I think. You could try to compile against https://github.com/FreeCAD/FreeCAD-LibPack/releases/tag/2.11 and hope that works, but that one is very old.

**Comment by kriswilk** [comment]
> Hm, that would be difficult I think. You could try to compile against https://github.com/FreeCAD/FreeCAD-LibPack/releases/tag/2.11 and hope that works, but that one is very old.

I'll give it a try. I just assumed there was a "standard" way to do it since the public release of 1.0RC2 is built using Qt 5. I simply want to "do what they did", since presumably it's how 1.0 will be compiled.

**Comment by furgo16** [comment]
I'm not a Windows user, and it's been quite a while since I used it to be able to help. I would have directed you to the forum, but I see that there is already a post about it at https://forum.freecad.org/viewtopic.php?t=91243. I hope someone can help there!

**Comment by yorikvanhavre** [comment]
Merged and NOT backported to not hinder the release 1.0 wich will be Qt5

**Pull request merged**
