### PR TITLE
Update copyright information [skip ci]

### PR DESCRIPTION
**Pull request by triplus**
https://forum.freecadweb.org/viewtopic.php?f=8&t=42125

### CODE REVIEW

**Comment by WandererFan** [comment]
@wwmayer , @yorikvanhavre:
As long as you 2 are OK with this, I'll merge it to end the debate in the forum.

**Comment by wwmayer** [comment]
For me it's fine.

**Comment by WandererFan** [comment]
C'est fin.

**Comment by triplus** [comment]
For reference i am adding my opinion here:

https://forum.freecadweb.org/viewtopic.php?f=8&t=36177&start=10#p365965

**Pull request merged**
