### PR TITLE
Fixes #17553

### LINKED ISSUE #17553: Gui: Transaction interaction
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Based on what I learned from @wwmayer and #17475, I noticed that it is quite easy to cause interactions between transactions that result in problems. One example is the following:

1. Create a new document.
2. Switch to Part and create a cube.
3. Move to Part Design and press the "Create Sketch" button, but don't proceed any further. 

At this point, a task is opened that has a pending transaction. This can be verified with:

``` python
App.ActiveDocument.HasPendingTransaction
```

4. Rename the label of the cube.

This rename adds a transaction as well and now if you execute the above, the active document has no pending transaction anymore.

5. Choose a plane in the 3D view (you may need to zoom out) or select a plane in "Select attachment" (for exampe the XY plane) and close the task.
6. Undo the rename.
7. Undo creating a new sketch.

Notice that the sketch is not deleted, probably because of the interfering transaction.

8. Undo the cube creation.
9. Delete the Sketch.
10. Undo deleting the sketch.

We now have a segfault:

<details>
<summary>stacktrace:</summary>
<pre>
#0  0x0000007800700030 in ?? ()
#1  0x00007ffff3e82589 in App::PropertyLinkSubList::verifyObject (this=0x55555df569e0, obj=0x55555ed10130, parent=0x55555df55ff0) at /home/pieter/current/fpa/freecad-main/src/App/PropertyLinks.cpp:1970
#2  0x00007ffff3e82f28 in App::PropertyLinkSubList::setValues (this=0x55555df569e0, lValue=..., lSubNames=..., ShadowSubList=...) at /home/pieter/current/fpa/freecad-main/src/App/PropertyLinks.cpp:2085
#3  0x00007ffff3e82e1e in App::PropertyLinkSubList::setValues (this=0x55555df569e0, lValue=std::vector of length 1, capacity 1 = {...}, lSubNames=std::vector of length 1, capacity 1 = {...}, ShadowSubList=...) at /home/pieter/current/fpa/freecad-main/src/App/PropertyLinks.cpp:2076
#4  0x00007ffff3e88715 in App::PropertyLinkSubList::Paste (this=0x55555df569e0, from=...) at /home/pieter/current/fpa/freecad-main/src/App/PropertyLinks.cpp:2788
#5  0x00007ffff3dcb8ec in App::TransactionObject::applyChn (this=0x55555aac6ee0, pcObj=0x55555df55ff0) at /home/pieter/current/fpa/freecad-main/src/App/Transactions.cpp:351
#6  0x00007ffff3dcaace in App::Transaction::apply (this=0x55555dd80990, Doc=..., forward=false) at /home/pieter/current/fpa/freecad-main/src/App/Transactions.cpp:176
#7  0x00007ffff3b38ba8 in App::Document::undo (this=0x55555bd2c7f0, id=0) at /home/pieter/current/fpa/freecad-main/src/App/Document.cpp:231
#8  0x00007ffff58dfa13 in Gui::Document::undo (this=0x55555d2224f0, iSteps=1) at /home/pieter/current/fpa/freecad-main/src/Gui/Document.cpp:2590
#9  0x00007ffff5fa2b71 in Gui::View3DInventor::onMsg (this=0x7fffdc008590, pMsg=0x7ffff6274434 "Undo", ppReturn=0x0) at /home/pieter/current/fpa/freecad-main/src/Gui/View3DInventor.cpp:392
#10 0x00007ffff57ed64f in Gui::Application::sendMsgToActiveView (this=0x7fffffffccc0, pMsg=0x7ffff6274434 "Undo", ppReturn=0x0) at /home/pieter/current/fpa/freecad-main/src/Gui/Application.cpp:1141
#11 0x00007ffff5a30e56 in StdCmdUndo::activated (this=0x555555d4ab10, iMsg=0) at /home/pieter/current/fpa/freecad-main/src/Gui/CommandDoc.cpp:1023
#12 0x00007ffff5a11257 in Gui::Command::_invoke (this=0x555555d4ab10, id=0, disablelog=true) at /home/pieter/current/fpa/freecad-main/src/Gui/Command.cpp:444
#13 0x00007ffff5a10f71 in Gui::Command::invoke (this=0x555555d4ab10, i=0, trigger=Gui::Command::TriggerAction) at /home/pieter/current/fpa/freecad-main/src/Gui/Command.cpp:408
#14 0x00007ffff59edcfa in Gui::Action::onActivated (this=0x555558ca72f0) at /home/pieter/current/fpa/freecad-main/src/Gui/Action.cpp:111
#15 0x00007ffff5a03ab1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**)::{lambda()#1}::operator()() const (__closure=0x7fffffffb260) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:152
#16 0x00007ffff5a04eeb in QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**)::{lambda()#1}>(void**, QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**)::{lambda()#1}&&) (args=0x7fffffffb410, fn=...) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:65
#17 0x00007ffff5a03b23 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**) (f=&virtual Gui::Action::onActivated(), o=0x555558ca72f0, arg=0x7fffffffb410) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:151
#18 0x00007ffff5a02412 in QtPrivate::FunctionPointer<void (Gui::Action::*)()>::call<QtPrivate::List<>, void>(void (Gui::Action::*)(), Gui::Action*, void**) (f=&virtual Gui::Action::onActivated(), o=0x555558ca72f0, arg=0x7fffffffb410) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:199
#19 0x00007ffff5a004f7 in QtPrivate::QCallableObject<void (Gui::Action::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x55555a5f3db0, r=0x555558ca72f0, a=0x7fffffffb410, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:570
#20 0x00007fffefbb2229 in QtPrivate::QSlotObjectBase::call (this=<optimized out>, r=<optimized out>, a=<optimized out>, this=<optimized out>, r=<optimized out>, a=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobjectdefs_impl.h:486
#21 doActivate<false> (sender=<optimized out>, signal_index=<optimized out>, argv=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:4120
#22 0x00007ffff0566524 in QAction::triggered (this=<optimized out>, _t1=<optimized out>) at /usr/src/debug/qt6-base/build/src/gui/Gui_autogen/include/moc_qaction.cpp:480
#23 QAction::activate (this=0x55555a5bca80, event=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qaction.cpp:1104
#24 0x00007ffff0c1ea75 in QAbstractButtonPrivate::click (this=0x555558ca6e50) at /usr/src/debug/qt6-base/qtbase/src/widgets/widgets/qabstractbutton.cpp:364
#25 0x00007ffff0c2c15e in QAbstractButton::mouseReleaseEvent (this=0x55555d6df560, e=0x7fffffffbcb0) at /usr/src/debug/qt6-base/qtbase/src/widgets/widgets/qabstractbutton.cpp:976
#26 0x00007ffff0d5729d in QToolButton::mouseReleaseEvent (this=0x55555d6df560, e=0x7fffffffbcb0) at /usr/src/debug/qt6-base/qtbase/src/widgets/widgets/qtoolbutton.cpp:588
#27 0x00007ffff0b51276 in QWidget::event (this=0x55555d6df560, event=0x7fffffffbcb0) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidget.cpp:8963
#28 0x00007ffff0afe31a in QApplicationPrivate::notify_helper (this=this@entry=0x5555556168e0, receiver=receiver@entry=0x55555d6df560, e=e@entry=0x7fffffffbcb0) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3294
#29 0x00007ffff0b028d1 in QApplication::notify (this=<optimized out>, receiver=<optimized out>, e=0x7fffffffbcb0) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:2772
#30 0x00007ffff5998f0a in Gui::GUIApplication::notify (this=0x7fffffffcc80, receiver=0x55555d6df560, event=0x7fffffffbcb0) at /home/pieter/current/fpa/freecad-main/src/Gui/GuiApplication.cpp:93
#31 0x00007fffefb585a8 in QCoreApplication::notifyInternal2 (receiver=0x55555d6df560, event=0x7fffffffbcb0) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1165
#32 0x00007fffefb585fd in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1623
#33 0x00007ffff0af61bd in QApplicationPrivate::sendMouseEvent (receiver=0x55555d6df560, event=0x7fffffffbcb0, alienWidget=<optimized out>, nativeWidget=0x7fffffffcc50, buttonDown=<optimized out>, lastMouseReceiver=..., spontaneous=true, onlyDispatchEnterLeave=false) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:2353
#34 0x00007ffff0b6a768 in QWidgetWindow::handleMouseEvent (this=0x555559f779f0, event=0x7fffffffc230) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidgetwindow.cpp:632
#35 QWidgetWindow::event (this=0x555559f779f0, event=0x7fffffffc230) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidgetwindow.cpp:298
#36 0x00007ffff0afe31a in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555559f779f0, e=0x7fffffffc230) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3294
#37 0x00007ffff5998f0a in Gui::GUIApplication::notify (this=0x7fffffffcc80, receiver=0x555559f779f0, event=0x7fffffffc230) at /home/pieter/current/fpa/freecad-main/src/Gui/GuiApplication.cpp:93
#38 0x00007fffefb585a8 in QCoreApplication::notifyInternal2 (receiver=0x555559f779f0, event=0x7fffffffc230) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1165
#39 0x00007fffefb585fd in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1623
#40 0x00007ffff0185d4b in QGuiApplicationPrivate::processMouseEvent (e=0x55555a3128a0) at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qguiapplication.cpp:2461
#41 0x00007ffff0201284 in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...) at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qwindowsysteminterface.cpp:1114
#42 0x00007fffeb17ab87 in xcbSourceDispatch (source=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:57
#43 0x00007fffecd76559 in g_main_dispatch (context=0x7fffe4000f30) at ../glib/glib/gmain.c:3357
#44 0x00007fffecdd9157 in g_main_context_dispatch_unlocked (context=0x7fffe4000f30) at ../glib/glib/gmain.c:4208
#45 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffe4000f30, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4273
#46 0x00007fffecd75a55 in g_main_context_iteration (context=0x7fffe4000f30, may_block=1) at ../glib/glib/gmain.c:4338
#47 0x00007fffefdbf71d in QEventDispatcherGlib::processEvents (this=0x55555581e0d0, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:396
#48 0x00007fffefb64566 in QEventLoop::processEvents (this=0x7fffffffc700, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:100
#49 QEventLoop::exec (this=0x7fffffffc700, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:191
#50 0x00007fffefb59a2f in QCoreApplication::exec () at /usr/src/debug/qt6-base/qtbase/src/corelib/global/qflags.h:74
#51 0x00007ffff57f37a9 in (anonymous namespace)::tryRunEventLoop (mainApp=...) at /home/pieter/current/fpa/freecad-main/src/Gui/Application.cpp:2195
#52 0x00007ffff57f3af4 in (anonymous namespace)::runEventLoop (mainApp=...) at /home/pieter/current/fpa/freecad-main/src/Gui/Application.cpp:2215
#53 0x00007ffff57f3eac in Gui::Application::runApplication () at /home/pieter/current/fpa/freecad-main/src/Gui/Application.cpp:2292
#54 0x00005555555795eb in main (argc=1, argv=0x7fffffffd478) at /home/pieter/current/fpa/freecad-main/src/Main/MainGui.cpp:295
</pre>
</details>

``` c++
void PropertyLinkSubList::verifyObject(App::DocumentObject* obj, App::DocumentObject* parent)
{
    if (obj) {
--->    if (!obj->isAttachedToDocument())
            throw Base::ValueError("PropertyLinkSubList: invalid document object");
        if (!testFlag(LinkAllowExternal) && parent && parent->getDocument() != obj->getDocument())
            throw Base::ValueError("PropertyLinkSubList does not support external object");
    }
}
```

I haven't checked, but I guess `obj` has been deleted at this point.

### Full version info

```shell
OS: Arch Linux (xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39092 (Git)
Build type: Release
Branch: main
Hash: a65d05c6e495038168eefcba6a1e43218fbb3a20
Python 3.12.7, Qt 6.8.0, Coin 4.0.3, Vtk , OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * OpenTheme 2024.5.16
  * osh-autodoc-workbench 0.2.3
  * Ondsel-Lens 2024.10.21.01
  * fasteners 0.5.29
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wwmayer**
* Tests: Add unit test to demonstrate failure of #17553
* Fixes #17553
* If needed open another transaction for sketch creation

### CODE REVIEW

**Comment by pieterhijma** [comment]
@wwmayer, great fix! But as I eluded to in the issue, it seems to be a general problem. Although I didn't recognize the pattern when creating the issue, now that I see this PR and think that I understand the changes, I believe the pattern is the following: 

When a transaction opens that doesn't immediately add a new document object to the tree (one example is creating a sketch that first asks you to select an attachment, compared to the counter example of creating a pad that *does* add a document object immediately), the transaction is prone to being closed by for example a rename of an object.

Within these kinds of transactions, it is necessary to check whether there is a pending transaction before you add a new document object. If not, then open a new transaction.

I don't know how common transactions are that don't immediately add a new document object, but in Part Design, multi-transform at the least also fits the pattern.

And indeed, if you create a multi-transform and force to close the transaction by means of a rename, then add a particular transform, undoing the transform leaves the user with the transform object at the root of the document. Deleting the document objects doesn't result in segfaults anymore, though.

I don't know how serious this is, perhaps not so serious.

**Comment by yorikvanhavre** [comment]
backported

**Comment by pieterhijma** [comment]
Ok, it's not only the rename command, it is also the VarSet dialog that creates transactions and is available.

**Comment by wwmayer** [comment]
> it is also the VarSet dialog that creates transactions and is available.

Is it? If I open a task dialog then the VarSet command is disabled.

**Comment by pieterhijma** [comment]
Hm, interesting. Well, if you create a VarSet before and then open a task dialog, you can double click the VarSet view provider to get the dialog that creates transactions. 

So, perhaps we should disallow viewprovider interactions, such as rename, double click?

**Comment by wwmayer** [comment]
Disabling renaming should be fine but I would not disable double-clicks as this is too restrictive.

**Pull request merged**
