### PR TITLE
Path:  Fixes #6629 - Add missing Job for import G-code [Bug]

### LINKED ISSUE #6629: [Bug] Gcode import fails if body or job objects are missing.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=15&t=47352&e=1&view=unread#p580582

### Version

0.20 (Development)

### Full version info

```shell
[code]
OS: Fedora 34 (Thirty Four) (LXQt//usr/share/xsessions/lxqt)
Word size of FreeCAD: 64-bit
Version: 0.20.28213 (Git)
Build type: Release
Branch: master
Hash: 1db77d367c5485bac9b10a6b07a0478c7bd8ea0a
Python 3.9.10, Qt 5.15.2, Coin 4.0.0a, OCC 7.5.0
Locale: C/Default (C)
Installed mods: 
  * FreeCAD_Assembly4 0.11.10
  * FreeCAD_assembly3
[/code]
```

### Subproject(s) affected?

Path WB

### Issue description

Gcode import fails if body or job objects are missing. 

With no body it produces traceback dump in report view.
With no job it silently fails after creating a misplaced job object. 

Details in linked forum discussion. 

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Russ4262**
Check if Job object exists in active document.  If not, then add a Job object GUI support, but without a base model.

Fixes #6629 

Recent forum mention begins at [Re: import gCode](https://forum.freecadweb.org/viewtopic.php?f=15&t=47352&p=581585#p580528).

Steps to reproduce:
* Create new document.
* From `File` menu, select `Import`.
* Select a g-code file in the File Explorer window that is presented, and click `Open`.
* In the `Choose a processor` popup window, select the `gcode_pre` option for the Processor, and click `OK'.
* Error should occur.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6662">pipeline status</a> for feature branch [PR_6662](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6662). Pipeline [500934965](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/500934965) was triggered at [d902d83](https://github.com/FreeCAD/FreeCAD/pull/6662/commits/d902d83a35957e142a1b4fff6ac5d44e7c9ea852). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
I like this approach.
The add job function should be removed from the preprocessor so it can be reused.
It's also a great candidate for some unit tests.

**Comment by Russ4262** [comment]
Went a different route.  Fixed some Job object issues further upstream to allow a simpler fix to be applied for the import g-code module issue.  These upstream fixes will also simplify scripting in Path as it pertains to Job creations, but GUI enabled and non-GUI.

Also fixed the module for usage for headless scripting, applying separation of GUI and non-GUI command usage.

Threw in a rebase also.

**Comment by Russ4262** [comment]
@sliptonic 
Just added some commits, including some unit tests as you suggested.  Due to current Path code, it is better to add a temporary base model to the missing Job object to allow for g-code inspection and path simulation.  Having a model also makes things easier in a few other ways for the Job object.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6662">pipeline status</a> for feature branch [PR_6662](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6662). Pipeline [502142080](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/502142080) was triggered at [50f1ec4](https://github.com/FreeCAD/FreeCAD/pull/6662/commits/50f1ec4b2f196ac6d01307ef5ff1e68f495383d4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
Thanks for the unit tests.  Actually MORE than I was looking for!   Writing tests for end-user facing functionality is hard so I've been focusing on writing tests for individual functions so the assumptions we make are tested.

Philosophically, I think this preprocessor is doing too much.  Its job is to import a chunk of gcode and create an appropriate custom object.  But with this approach it's encapsulating logic to resolve problems preventing that.  

IMHO, there should be a function like _verify()  that tests if the current environment has everything the preprocessor needs.  That function should return a bool but not change anything.  If it returns False, the preprocessor can raise an appropriate exception or notify the user.  

In my opinion, it's perfectly acceptable for the preprocessor to stop there and let the user do what is needed to make the environment acceptable.  However,  I understand if you want the preprocessor to actually resolve the problems for the user so the worflow is smoother.  In that case, I would suggest it ask the user to proceed and use one or more helper functions to do the work.  This action would only apply if GUI is up.  

If the user is trying to import from a script and the environment isn't right, it should just raise an exception.  The script writer should be responsible for generating a valid environment first.  We want the scripting environment to be modular and we don't duplicate job creation logic in many places. So raise a good exception and exit gracefully.

**Comment by Russ4262** [comment]
@sliptonic 
Made some changes per your comments.  Squashed some commits.  Rebased.

**Comment by Russ4262** [comment]
Wait a moment... Trying to remove a specific commit, and I seem to just be making a mess.  Working on it.

**Comment by Russ4262** [comment]
@sliptonic 
Okay.  Done.  Removed commit to allow creation of baseless Job object.  Squashed two commits because older had remnants of first and second version of this PR.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6662">pipeline status</a> for feature branch [PR_6662](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6662). Pipeline [504494912](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/504494912) was triggered at [df9d984](https://github.com/FreeCAD/FreeCAD/pull/6662/commits/df9d9843c378068c020ceaca64778ae9bfd52cdf). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
