### PR TITLE
Unit is too complex

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

A rather chunky refactor (possible only due to unit tests!).

The commit message has detailed report.

There is still plenty of room for improvement, but hopefully this is a good first step.

Note: Bit fields have been replaced with ints.
Note: Range errors no longer report source but IMHO a very small price to pay for simplicity.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8726">pipeline status</a> for feature branch [PR_8726](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8726). Pipeline [794977808](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/794977808) was triggered at [43f9133](https://github.com/FreeCAD/FreeCAD/pull/8726/commits/43f9133046ccba8316e5cd345ae5c3ad5a9cd89d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8726">pipeline status</a> for feature branch [PR_8726](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8726). Pipeline [795794456](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/795794456) was triggered at [bddb25c](https://github.com/FreeCAD/FreeCAD/pull/8726/commits/bddb25c2bf502bd288b742ba1cfd2515c9cb0962). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8726">pipeline status</a> for feature branch [PR_8726](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8726). Pipeline [795858565](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/795858565) was triggered at [2d12585](https://github.com/FreeCAD/FreeCAD/pull/8726/commits/2d125854f9360f0b29753877edec444ccee38022). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
I have another rcommit ready which takes advantage of this work and makes major reduction to repetition.
Should I (or not ) drop it into this existing PR?

**Pull request closed without merging**
