### PR TITLE
Path: [re-submission] add support for spot drilling (on different Z coordinates)

### PR DESCRIPTION
**Pull request by noahwilliamsson**
This is a re-submission of PR #4933 since the original author stated that he couldn't afford to spend more time on it.

I've cleaned up the commits, fixed a merge conflict that was caused by the recent purge of archpanel support and rebased the code on the latest master branch.  I'm hoping that this will make things easier to review.

In addition to spot drilling support, this PR contains two bug fixes from the original author:

- Path: fix for selecting fillet edges (https://forum.freecadweb.org/viewtopic.php?f=15&t=59289&start=20#p516939)
- Path: fix edge selection (https://forum.freecadweb.org/viewtopic.php?f=15&t=59289&start=20#p516416)

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5061

pipeline:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/377138869

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by sliptonic** [comment]
This PR works as described.  
The work that @noahwilliamsson did improves the code.  That said, I'm not a fan of the overall solution.  It's a band-aid on the more fundamental limitation of drilling (and all operations) that they have a 2.5D bias built into them.

A proper solution is more complicated but would allow every hole to be independently processed for start and end depth.  It would work with 4th and 5th axis rotations as well.

I'm inviting comment.  Is this functionality in demand enough to warrant this partial fix or should we wait in favor of a more complete solution?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5061">pipeline status</a> for feature branch [PR_5061](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5061). Pipeline [#384015064 ](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/384015064) was triggered at [1ac68f0](https://github.com/FreeCAD/FreeCAD/pull/5061/commits/1ac68f0c1211a5ee4a2b64b463b2f3a70f5cdfb0). All CI branch [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by globalcitizen** [comment]
Since you invited comment: Don't wait. Extra axes are rare. 2.5D is the norm. Let's get it merged.

**Comment by sundtek** [comment]
I need this for my object since I have plenty of holes there and need to do spot drilling.

**Comment by sliptonic** [comment]
I noted in my first comment that I don't like this direction.  It is increasing our technical debt with regard to 2.5D bias.  Right now, the bias is minimal in drilling but it only gets harder to remove with more features.  I know people want features but the fastest way to get new features is with maintainable and well designed code.  I suggest this PR should be closed in favor of a more intentional and long-term design.  Here's what I propose:

I've started the process of refactoring the circular hole processing architecture.  The first step is to abstract out the logic of producing drilling and helical gcode into a 'generators' and make it testable.  The first one for drilling is done and merged with PR 5154.

The next step will be to make the drilling operation use the new generator in the conventional way.  I have a feature branch in process and invite testers: https://github.com/sliptonic/freecad/tree/feature/drill-refactor  This will add no new functionality.

After that, the next step will be to similarly abstract and remove the shape generation logic. The drilling operation will only be responsible for moving from target to target and calling the generator for each.  When that is done, the drilling operation will be able to process each shape independently at any Z level (and at any orientation).

**Comment by sundtek** [comment]
I don't mind, please also add direct hole selection. 
It was removed from someone in the past and I don't think it's useful to remove it, it always selects all holes at once here (which is also relatively slow with the model I'm working on).

**Comment by sliptonic** [comment]
> I don't mind, please also add direct hole selection. 

Please clarify what you mean by 'direct hole selection'.  I think in the current design, if you have nothing selected, it detects all possible drilling targets in the bases.  If  you select a feature that is drillable, only that feature is added.

**Comment by sundtek** [comment]
> If you select a feature that is drillable, only that feature is added.

I'm not sure about that if it's still like that (I added this explicitly to my patch before I remember). The version which I am using here had it removed for sure and it used to select all holes automatically.

Aside of that sometimes it would also be useful to select half circles (I have some metal sheet here where I use a half circle for alignment. First I'd like to drill the hole afterwards mill the contours.

**Comment by sundtek** [comment]
ok I'd like to update this it should be merged, the patch is only exposing the Z axis of the actual drilling script.
Certainly it can be refactored another time this entire modification is small and simple.
The patch was written several months ago it has its use case (I just need it again now - but due to all issues with FC I'm using a custom version at the moment).

Aside of that the patch adds support for custom circle selection, which has been removed at some point and is very inconvenient in the upstream version. Currently drilling holes with multiple diameters might lead to selection errors (yes it happened to me!) since the selection has been done via the drill menu rather than via mouse click on the object.

The exposure to the user certainly can be changed. It does not add any new functionality that wasn't there before it's just using the existing infrastructure and exposing some more options.

**Comment by sundtek** [comment]
One more recommended update:
    def addSelectedHoles(self, obj, selection):
...
                   # is drillable also allow partially closed circles
                   if PathUtils.isDrillable(shape, e, tooldiameter, True):

the last flag will allow partial circles to be drilled.
eg.
https://snipboard.io/zG5b62.jpg

**Comment by noahwilliamsson** [comment]
@sundtek I rebased the changes on the latest upstream master branch and invited you as a collaborator to the PR's source repo in case you want to do more work on this.

**Comment by sundtek** [comment]
@noahwilliamsson thanks, I'm adding features here on the go while working on my object, first I integrate it then test it and see if it's worth it.

The spot drilling has another advantage which I have seen yesterday. lately I added a sheet metal cover on my object but that one is also on different Z planes. With that feature we can just combine spot drilling with peck drilling. I wanted to drill 5mm holes with a very thin drill -- and it worked just perfectly.

On the other side I also need the option to drill holes from various milled Z planes (actual milled object surface) down to a fixed point (this is not covered by this patch yet but should be added in another patch), otherwise a lot air milling is happening.

This certainly depends what the user wants to do, does he want to start from stock or does he want to start from the actual milled object surface.

As mentioned the actual modification is based on existing functionality that's why this patch should be merged now, it just re-adds some functions that got stripped away during the time (direct circle selection), and exposes Z from the existing drilling functions.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5061">pipeline status</a> for feature branch [PR_5061](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5061). Pipeline [417423094](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/417423094) was triggered at [035c200](https://github.com/FreeCAD/FreeCAD/pull/5061/commits/035c20024165d395862bf42326741056e9b89475). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by noahwilliamsson** [comment]
Closing due to inactivity.

**Pull request closed without merging**
