### PR TITLE
src: Add helper function to check Python types.

### PR DESCRIPTION
**Pull request by marioalexis84**
Occasionally, a Python function argument may expect a specific type or `None`, by using the corresponding format unit in the parse function. The helper function `Base::PyTypeCheck` generates similar functionality to those format units, setting the `PyObject` pointer to `nullptr` in case the passed value is `None` and throwing an exception if the type is not correct.
In the ViewProvider Python implementation is restored the posibility to pass `None` to some arguments of the drag and drop functions to fix some regressions reported in the aseembly forum: https://forum.freecadweb.org/viewtopic.php?f=20&t=69777

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7236">pipeline status</a> for feature branch [PR_7236](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7236). Pipeline [600445253](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600445253) was triggered at [12756f9](https://github.com/FreeCAD/FreeCAD/pull/7236/commits/12756f9670c567006074f8e77d6a15f95d48649f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks for the fix and also the backport commit.

**Comment by donovaly** [comment]
I cannot checkout and merge because of a merge conflict. Can you please rebase your PR to current master?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7236">pipeline status</a> for feature branch [PR_7236](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7236). Pipeline [645538951](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/645538951) was triggered at [e3b1292](https://github.com/FreeCAD/FreeCAD/pull/7236/commits/e3b12926fef4f71d65c4aa8257d2be6848baea16). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> @donovaly rebased. I added an overloaded PyTypeCheck method for use with the python/C API functions to check specific types (like PyTuple_Check, PySequence_Check, etc). The idea is to use it in future pull requests.

Thanks. I will merge now.
Please add this new code feature to https://wiki.freecadweb.org/Release_notes_1.0#Core_system_and_API

**Pull request merged**
