### PR TITLE
[FEM] Elmer: refactor writer

### PR DESCRIPTION
**Pull request by donovaly**
- the writer.py is to large to keep the overview, thus sort out the handling of the different equations (also since more equations will be added)
- This PR sorts out the electrostatic equation handling is the test balloon if this works well (local tests are all OK)

### CODE REVIEW

**Comment by chennes** [comment]
There will be a short delay before I can look at this, I spend tomorrow on airplanes. I will look when I am able, but if other reviewers approve don't wait for me :) .

**Comment by donovaly** [comment]
> There will be a short delay before I can look at this, I spend tomorrow on airplanes. I will look when I am able, but if other reviewers approve don't wait for me :) .

No problem. If you could tell me if I did it right with the underscore naming of the defs this PR should be a no-brainer since no code is actually changes, just moved around and the CI tests assure that everything works.

**Comment by donovaly** [comment]
Here is an electrostatics test file to check the PR: 
[Electrostatics3.zip](https://github.com/FreeCAD/FreeCAD/files/10611776/Electrostatics3.zip)

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362">pipeline status</a> for feature branch [PR_8362](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362). Pipeline [767982997](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/767982997) was triggered at [da13170](https://github.com/FreeCAD/FreeCAD/pull/8362/commits/da13170e50ee4cc92805497906052a583dac8302). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@chennes , I wish you a good flight back home. Many thanks for all your great work for FreeCAD! I hope we once meet in person (my plan is since a while to organize a full FC conference - one weekend just for FC)

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362">pipeline status</a> for feature branch [PR_8362](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362). Pipeline [768025713](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768025713) was triggered at [b7a02f0](https://github.com/FreeCAD/FreeCAD/pull/8362/commits/b7a02f0f8c4faffab71bd4332c41ce85b4d6192d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
JFYI, Some trailing whitespace introduced in this PR: https://github.com/FreeCAD/FreeCAD/actions/runs/4098361865/jobs/7067414783

**Comment by donovaly** [comment]
> JFYI, Some trailing whitespace introduced in this PR: https://github.com/FreeCAD/FreeCAD/actions/runs/4098361865/jobs/7067414783

Where do you see this? I only got one reported. This is now fixed together with other things noted by Pylint.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362">pipeline status</a> for feature branch [PR_8362](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362). Pipeline [768038005](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768038005) was triggered at [9312ee4](https://github.com/FreeCAD/FreeCAD/pull/8362/commits/9312ee4cb0b2a8dadbc905aea8e8837b5bbd0ba0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362">pipeline status</a> for feature branch [PR_8362](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362). Pipeline [768193350](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768193350) was triggered at [00f4e9c](https://github.com/FreeCAD/FreeCAD/pull/8362/commits/00f4e9cd90f9b5f684b3e01f55445a38fbc1d4d7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362">pipeline status</a> for feature branch [PR_8362](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8362). Pipeline [768199011](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/768199011) was triggered at [76695aa](https://github.com/FreeCAD/FreeCAD/pull/8362/commits/76695aaceb477aca31974b7899217bfceb081b7d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Side note: we should have a discussion, maybe in a GitHub issue, about the Pylint config file. If you and I are both using it, and the CI runs it, I feel like it could use some fine-tuning so it does not actually encourage _worse_ code.

That said, one way of checking that you have the correct functions underscored or not is to underscore all of them, and then run pylint and see which calls it yells at you about: it should complain about any non-self-prefixed calls to underscored methods. That's useful when refactoring big code where you don't know exactly what needs to be public.

**Comment by donovaly** [comment]
> then run pylint and see which calls it yells at you about

This is what I already did - I checked the Pylint output of the CI and apply fixed accordingly. I think I caught all underscores now.

In General, since I am no Pythionist, call myself "just a user" ;-), I cannot state about how Pylint is configured.

**Comment by donovaly** [comment]
OK, I think this PR is a safe code refactoring. I used it a lot the last day and since no code was actually changed, I need to merge it in order to get other PRs ready.

I will continue the sortout in further PRs.

**Pull request merged**
