### PR TITLE
Draft: add support for point link array

### PR DESCRIPTION
**Pull request by realthunder**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
I just tested the code; creating the Link array works without issues, but creating the older array causes an error.

Test with the make function, as described in the wiki [Draft_PointArray](https://wiki.freecadweb.org/Draft_PointArray).

Correct.
```py
_obj_ = Draft.make_point_array(Rectangle, Compound, extra=None, use_link=True)
```

Error.
```py
_obj_ = Draft.make_point_array(Rectangle, Compound, extra=None, use_link=False)
```

The message is the following.
```
File "/opt/freecad-build-debug-vocx/Mod/Draft/draftmake/make_pointarray.py", line 165, in make_point_array
    PointArray(new_obj)
  File "/opt/freecad-build-debug-vocx/Mod/Draft/draftobjects/pointarray.py", line 61, in __init__
    super(PointArray, self).__init__(obj, "PointArray")
  File "/opt/freecad-build-debug-vocx/Mod/Draft/draftobjects/draftlink.py", line 65, in __init__
    self.attach(obj)
  File "/opt/freecad-build-debug-vocx/Mod/Draft/draftobjects/pointarray.py", line 67, in attach
    obj.configLinkProperty(ElementCount='Count')
AttributeError: 'FeaturePython' object has no attribute 'configLinkProperty'
```

I think the `configLinkProperty` shouldn't run in the original array?

**Comment by realthunder** [comment]
Right, it should be in `linkSetup()` instead.

**Review by vocx-fc — APPROVED** [review]

**Comment by vocx-fc** [comment]
Please rebase.

**Comment by yorikvanhavre** [comment]
Merge conflicts are solved, but I cannot merge while travis hasn't finished... Never understood why github does that sometimes and sometimes not

**Comment by yorikvanhavre** [comment]
Github never let me merge this :) Did it manually with 31e8bb27a6

**Pull request closed without merging**
