### PR TITLE
[Part] Tweak mesh generation

### PR DESCRIPTION
**Pull request by pmjdebruijn**
Mesh generation parameters are taken from PrusaSlicer's STEP importer, which does a just-in-time STEP->STL conversion in memory.

Resulting meshes have better geometry, but are a little larger as a result.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8304">pipeline status</a> for feature branch [PR_8304](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8304). Pipeline [761961360](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761961360) was triggered at [8fc0fc4](https://github.com/FreeCAD/FreeCAD/pull/8304/commits/8fc0fc4b1848c0b11f09ecf465b3fc869f710a9c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
Instead of harcoding that value isn't it better to use a config parameter? We a default part deviation parameter, should that be used or is this parameter something else?

**Comment by pmjdebruijn** [comment]
In my fairly simple designs I've seen an increase of roughly 5%

**Comment by chennes** [comment]
Thanks -- in general I think that people who care a great deal about this are going to be using the Mesh workbench and specifying the parameters carefully themselves. To me, 5% is not a big deal. I'm going to leave this open a while longer in case anyone else wants to discuss it, but otherwise I'm inclined to merge as-is (with the caveat that if you're looking for a project, making this a "hidden" parameter would be a pretty easy modification).

**Comment by pmjdebruijn** [comment]
I've also been experimenting with:

-    BRepMesh_IncrementalMesh(shape, 0.1);
+    BRepMesh_IncrementalMesh(shape, 0.005, false, 0.1, true);

This results in even better geometry in somecases, with a filesize increase of about 10% in my fairly simple models.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8304">pipeline status</a> for feature branch [PR_8304](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8304). Pipeline [763309957](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/763309957) was triggered at [6ff03ad](https://github.com/FreeCAD/FreeCAD/pull/8304/commits/6ff03ad143b1fb896d67c5c4e5ea522b943379b4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
This problem actually came up in the discussions at FreeCAD Day today -- so thanks for preemptively fixing it so I could say that a PR was in the works already! I'm going to merge this updated parameter set now.

**Comment by donovaly** [comment]
> This results in even better geometry in somecases, with a filesize increase of about 10% in my fairly simple models.

But only in simple ones. I totally agree that the next PR should be to add a parameter that users can change the preset. Could you make such a PR?
If not, @adrianinsaval , are you interested? I think it could be a small and nice project for you.

**Pull request merged**
