### PR TITLE
Finish renaming desktop filename to org.freecad.FreeCAD

### PR DESCRIPTION
**Pull request by cjmayo**
The QGuiApplication::setDesktopFileName() call was changed in [1] but the desktop file and other files that reference it were not.

As shown by Looking Glass [2] on X11 updating these files is still not enough for GNOME to associate the process with the desktop file, a StartupWMClass entry is added to the desktop file to fix this.

[1]
129d5882a7 ("Migrate domain name from freecadweb to freecad (#9352)", 2023-04-24)

[2]
https://blogs.gnome.org/mclasen/2016/11/15/help-my-app-icon-is-missing/

---

A second related commit, and once using org.freecad that follows on from the first commit (will split this if preferred):

Fix hicolor theme application icon names

Fixed-size icons were not available as org.freecad.FreeCAD and
XDGData/org.freecad.FreeCAD.svg was a duplicate of Gui/Icons/freecad.svg.

---
- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
---

### CODE REVIEW

**Comment by chennes** [comment]
Thanks for the PR: I'll ask a couple of our full-time-Linux devs to verify on their systems before merging. This also looks like a candidate for backporting to 0.21.1. @yorikvanhavre @sliptonic can you take a look?

**Comment by yorikvanhavre** [comment]
Looks good to me! Not sure it's a good thing to backport, though... It might change a person's setup (files, icons,...) abruptly when they are not expecting it

**Comment by luzpaz** [comment]
I wonder if this has repercussions for downstream package repos... ?

**Comment by chennes** [comment]
Thanks for that snap PR, it's merged now.

**Comment by luzpaz** [comment]
RE flatpak:

Relevant discussion on domain change is in https://github.com/flathub/org.freecadweb.FreeCAD/issues/107

**Comment by adrianinsaval** [comment]
> Looks good to me! Not sure it's a good thing to backport, though... It might change a person's setup (files, icons,...) abruptly when they are not expecting it

for flatpak I think it would be useful to get this backported.

**Comment by luzpaz** [comment]
Does anything need to change in the AppImage ?

**Comment by adrianinsaval** [comment]
Yes, but it's done: https://github.com/FreeCAD/FreeCAD-Bundle/commit/1bbed5bd103e237fdda74ec332399bf70d5fa052

also the next mac bundle should now use the org.freecad.FreeCAD identifier too: https://github.com/FreeCAD/FreeCAD-Bundle/commit/8801eb1aa4d3f39110723686a278ef9f713ba0c9, not sure if that is really relevant for macOS

**Comment by darkblaze69** [comment]
It's still not in 0.21. Can it be backported please ? Missing icon on Wayland

**Pull request merged**
