### PR TITLE
Fix ProgressBar rendering following STEP reader enhancement

### PR DESCRIPTION
**Pull request by vejmarie**
This patch is fixing the ProgressBar display issue that we faced during reading STEP files.

### CODE REVIEW

**Comment by luzpaz** [comment]
Will this fix https://freecadweb.org/tracker/view.php?id=2901 ?

**Comment by vejmarie** [comment]
Yes

**Comment by luzpaz** [comment]
@vejmarie FYI i think if you write: 
Fixes 2901 
that it will automagically do that for on the tracker.

**Comment by vejmarie** [comment]
Hi luzpaz, I was not aware that a bug had been filled on the tracker for this issue ;). I am not sure to understand what you wanted me to do ? Put Fixes 2901 into the PR subect ? Or elsewhere ?

**Comment by luzpaz** [comment]
devs could correct me if I'm wrong but if you include 
`issue 2901` or `fixes 2901` 
somewhere in the PR subject it will auto-register in the FC bugtracker at freecadweb.org/tracker

**Comment by wwmayer** [comment]
Works great again. Thanks!

**Pull request closed without merging**
