### PR TITLE
Path: Adaptive Operation 

### PR DESCRIPTION
**Pull request by kreso-t**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
@sliptonic or @mlampert please have a look if this PR is OK for you.

**Comment by mlampert** [comment]
I had a look at it and it looks good - can be merged.

**Comment by wwmayer** [comment]
Merged.

**Comment by kreso-t** [comment]
Thanks for the corrections and merge. I definitely need to see how to get those more verbose compiler warnings when compiling on linux (one of those was pointing to actual problem in the code).

**Comment by wwmayer** [comment]
For gcc and clang we already use -Wall and -Wextra which should detect most problems. But in this case gcc didn't find anything and clang only found the superfluous member and the check Orientation(...) < 0.

gcc/clang didn't complain about the missing long casts but this is probably because long is 8 bytes on a 64-bit Linux or macOS system while on a 64-bit Windows it's only 4 bytes and std::size_t apparently is 8 bytes on all 64-bit systems. So, only msvc found them due to a conversion from a 8 byte to a 4 byte type.

The easiest way to get the compiler warnings is to look at the output of Travis-Ci and AppVeyor

**Comment by kreso-t** [comment]
Thanks again.
At first I thought it's warning about std::size_t vs long because of unsigned vs signed  mismatch - but I think there is a different warning message in this case (likely also depends on compiler being used). Your explanation makes much more sense.

**Pull request closed without merging**
