### PR TITLE
Remove PLY from OpenSCAD as installed as FreeCAD prereq

### PR DESCRIPTION
**Pull request by KeithSloan**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
Forum thread: [Discussion: removing Ply from FreeCAD's source code](https://forum.freecadweb.org/viewtopic.php?f=10&t=42476)

**Comment by yorikvanhavre** [comment]
I think just removing ply will likely make OpenSCAD not work anymore for the majority of users, no? Shouldn't we also add a message to inform the user of the need to install ply separately? @KeithSloan can you tell if ply is used only to import ply files, or in any other way inside openscad?

**Comment by vocx-fc** [comment]
Removing `ply` won't break OpenSCAD for the majority of users. I suspect most users are using Linux. In Linux it is easy to install `python3-ply`. As far as I can tell, the `ply` package is already removed from the Debian/Ubuntu package precisely because of this. Is this right, @kkremitzki?

As for the Windows, AppImage and DMG packages, @looooo says it's no problem to add it to the [conda dependencies](https://forum.freecadweb.org/viewtopic.php?f=10&t=42476&p=360992#p360868). I think this should take care of the rest of the users that use a conda-generated package. @sgrogan 

Removing `ply` would only "break" those who compile from source. However, our [CompileOnUnix](https://www.freecadweb.org/wiki/CompileOnUnix#Python_3_and_Qt5) instructions (Debian/Ubuntu) already mention that you should install `python3-ply` as a dependency.

So this is a situation like Pivy. It's only really used by one workbench; without it, the rest of the system should work fine.

**Comment by KeithSloan** [comment]
The CSG importer importCSG.py uses ply to parse the CSG file ( The importing of scad files is achieved by the OpenSCAD module calling openscad to produce a CSG file under the covers i.e. in a temp file that is then processed. 

The importer has the following lines
`import ply.lex as lex
import ply.yacc as yacc
`
I recently did a reinstall of freecad and freecad-daily and  neither of which now has a ply subdirectory
( As mentioned before Not something that I removed)

I have never install any version of ply via apt-get so assume the freecad installs must have done so. 
The importer works on Linux.

I assumed that if FreeCAD is installing ply as prereq it would do it for all platforms.

**Comment by vocx-fc** [comment]
> I have never install any version of ply via apt-get so assume the freecad installs must have done so.
> The importer works on Linux.

This was not done automatically so far. But as I mention in the previous #2890, many Python packages depend on `ply`, so probably one of them installed it without you doing it manually.

> I assumed that if FreeCAD is installing ply as prereq it would do it for all platforms.

This was not true until now.

Recent developments in the thread suggests that now `ply` will be included in all platforms as a dependency.

[Looo will add it to conda](https://forum.freecadweb.org/viewtopic.php?f=10&t=42476#p360889)

[And sgrogan will add it to the Windows builds and to the LibPack](https://forum.freecadweb.org/viewtopic.php?f=10&p=361447#p361447)

As far as I can tell, removing `ply` from the OpenSCAD subdirectory can proceed.

**Comment by yorikvanhavre** [comment]
Ok so probably the best path here is to place the "`import ply`" line inside a try...except block, and print a message tot he user if the ply package is not installed, and bail out. I can do that here I guess. Ok with you guys?

**Comment by KeithSloan** [comment]
Find with me, but is a print out enough? Will just print in report view which user can miss.

Would ideally be QT dialog prompt -  mini window popup.
Ideally I would like to see FreeCAD have a simple dialog prompt. I know one can do things with Qt
which gives maximum flexibility, but a simple prompt would be good. Maybe FC has one and I have yet to discover it.

**Comment by vocx-fc** [comment]
It is possible to add a Qt prompt of course, however, please notice that FreeCAD is not only a GUI program. It can be used in console mode, in which case there is no graphical user interface to display popups.

There are already tests like these in different parts of the code. They test for a module, and if not found, they print a message and `return`.

**Comment by KeithSloan** [comment]
Okay how about print warning message and also test if running under GUI and only put out prompt if under GUI. I know myself I have often missed things in report view.

**Comment by vocx-fc** [comment]
It can be done, but I think it's overthinking this. I prefer the simplest solution which is just printing the warning, like Yorik suggested.

**Comment by vocx-fc** [comment]
Did you do a `git merge`? Don't do that. This pull request now has 83 commits with all the accumulated commits for a few days.

Use `git pull --rebase upstream master` or `git rebase master` to rebase your branch into the latest code.

**Comment by KeithSloan** [comment]
As far as I remember I did git pull --rebase official master.

Never heard of git merge ( Dont be so aggressive with your orders )

**Comment by yorikvanhavre** [comment]
There is something wrong now with this PR, it wants to change back 113 files...
Are you able to do something @KeithSloan ? Otherwise it might be easier to close it and do it again...
About the message, there is something like you suggest in src/Draft/importDXF.py - if the GUI is up, a Qt infobox is displayed, otherwise only a console message. But that could be called refinement, I think we can start making something simple then we can improve it along the way...

**Comment by KeithSloan** [comment]
I to am very confused about how things got into this state.

Do I have to delete and recreate my copy of the FreeCAD repro to sort this?
My repro is https://github.com/KeithSloan/FreeCAD_sf_master

**Comment by KeithSloan** [comment]
Advised problems - Closing and will try again

**Comment by vocx-fc** [comment]
I can't say why those commits are there, but my advice would be to read [Source code management](https://www.freecadweb.org/wiki/Source_code_management). I rewrote it some months ago, and I think right now it explains much better how to use Git for FreeCAD development. I don't think you need to outright re-create the entire repository, but if you want to do it, it wouldn't hurt either.

**Pull request closed without merging**
