### PR TITLE
[skip ci] Add getShortcut(string) command to Gui, returns string valu…

### PR DESCRIPTION
**Pull request by mwganson**
…e representing shortcut key accelerator for this command

I'm not sure what [skip ci] does, but I see a lot of commits with that in it, so I put it.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by HakanSeven12** [comment]
https://semaphoreci.com/docs/how-to-skip-building-for-some-commits-with-ci-skip.html

**Comment by yorikvanhavre** [comment]
Curiously [skip ci] doesn't seem to have any effect...
Basically you use it if you made a change that doesn't modify the code itself (for ex. you fix the contents of a string or a comment), so there is no use to try to compile your commits...

**Comment by mwganson** [comment]
I see.  Thanks for the replies.  I thought there must be some issue with the continuous-integration not working or something.

Here is a link to the board discussion related to this PR:

https://forum.freecadweb.org/viewtopic.php?f=8&t=44973

Perhaps it should be getShorcutByCommand?  There is a request for similar options, such as to get text, icon, tooltip, etc.  I'm thinking it might be better to return a list of all of these properties, such as getCommandInfo(string command_name).

**Comment by HakanSeven12** [comment]
That would be great.

**Comment by yorikvanhavre** [comment]
I think it doesn't harm having many methods (getShortcut, getCommandInfo, etc...). If you really want to rename getShortcut, I would suggest getCommandShortcut, but there are no other ways the word "shortcut" is used in FreeCAD, so for me getShortcut is fine...

**Comment by mwganson** [comment]
Okay.  I will add getCommandInfo to this then.

**Comment by yorikvanhavre** [comment]
Good job! Merging

**Pull request merged**
