### PR TITLE
[Mod]  Clean AssemblyObject.cpp

### PR DESCRIPTION
**Pull request by mosfet80**
Removed dead code

### CODE REVIEW

**Comment by PaddleStroke** [comment]
Please don't merge this. There is already 3 large PR opened on assembly, merging this will only make unecessary conflicts. Besides some of these comments I have left on purpose.

**Comment by maxwxyz** [comment]
@mosfet80 this PR has some conflicts, can you resolve them?

**Comment by maxwxyz** [comment]
@mosfet80 any feedback?

**Comment by maxwxyz** [comment]
@mosfet80 ping for feedback

**Comment by maxwxyz** [comment]
@mosfet80 still some conflicts

**Comment by chennes** [comment]
@PaddleStroke can we just uncomment that `printPlacement` method, rather than removing it?

**Pull request merged**
