### PR TITLE
Draft: add proper Doxygen groups for Draft documentation

### PR DESCRIPTION
**Pull request by vocx-fc**
After the re-organization of the Draft modules, the Doxygen documentation placed each module in the `DRAFT` group. This pull request adds proper groups under this main group so that each module is correctly categorized, and it's easier to find the documentation for all functions and classes.

This pull request essentially modifies all modules in the workbench so it will probably cause conflicts with other pull requests; they will need to be resolved before merging.

---

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by maidenone** [comment]
the travis build fail is:

```
======================================================================
ERROR: test_pyimport_all_FEM_modules (femtest.app.test_common.TestFemCommon)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\travis\build\FreeCAD\FreeCAD\build\Mod\Fem\femtest\app\test_com
mon.py", line 147, in test_pyimport_all_FEM_modules
    __import__("{0}".format(mod))
  File "C:\Users\travis\build\FreeCAD\FreeCAD\build\Mod\Fem\femexamples\examples
gui.py", line 32, in <module>
    import FreeCADGui
ImportError: DLL load failed: The specified module could not be found.
```

The travis build works fine on linux, but fails on windows.
is this related to this pull request or is it a issue in travis?

**Comment by vocx-fc** [comment]
> is this related to this pull request or is it a issue in travis?

This error was already solved in #3679, however I still haven't rebased this branch. I will do it now, and there shouldn't be an error any more.

However, the link between GitHub and Travis is still sketchy, it occasionally fails and doesn't report the status of the tests.

**Comment by yorikvanhavre** [comment]
Travis problems seem solved, but this PR now has merge conflicts...

**Comment by vocx-fc** [comment]
Yep, I'm making final adjustments.

**Pull request merged**
