### PR TITLE
Update icons for Sketcher_ToggleConstruction & Sketcher_ToggleConstru…

### PR DESCRIPTION
**Pull request by czinehuba**
…ction_Constr

### CODE REVIEW

**Comment by pierreporte** [comment]
I can barely see the difference with the github graphical diff and they appear bigger than in the toolbars. I think that the gap between dashes should be way larger, bigger than the line width actually.

**Comment by chennes** [comment]
@obelisk79 , for DWG review when you all have time.

**Comment by pierreporte** [comment]
@czinehuba It’s much better.

**Comment by pierreporte** [comment]
@maxwxyz should they, though? If the toggle status is made more obvious, way more than it is now, it wouldn’t be necessary to have two sets of icons in the first place and it would be independent to the construction lines style. Something like the pictures below but with “normal” or “construction” written on it instead of on/off. Sure it takes more room.

image

image

**Comment by obelisk79** [comment]
@pierreporte then we will run into translation concerns. I think keeping the control information purely visual is the best course of action and remains consistent within the context of the rest of FreeCAD. However, we still have the conundrum of the other icons which represent construction geometry, and I agree that there needs to be consideration that representation in icons should also be uniform.

I think converting everything to a dashed line style is probably best here, if the default presented to users will be patterned. So, this PR should expand in scope significantly.

**Comment by MisterMakerNL** [comment]
What if we just make it a single line.
Like it would be clear it's not a line function as it would be the only non-construction line or the only construction-line icon.
If a user thinks you can draw a construction line with it, and clicks it. Then it doesn't get the line but it does shows the user it is a toggle that they need to press the line icon to get the construction line.
Maybe we can add a little switch icon in the corner.

**Comment by czinehuba** [comment]
@obelisk79 I am not sure if we need to convert all to dashed lines. Firstly, I'm not sure how they would look like on more complex icons. Second, none of the other software even go through the trouble of creating different colour icons when in construction mode. It's just a toggle. 

PS: @MisterMakerNL suggestion does make sense to me.

**Comment by obelisk79** [comment]
> @obelisk79 I am not sure if we need to convert all to dashed lines. Firstly, I'm not sure how they would look like on more complex icons. Second, none of the other software even go through the trouble of creating different colour icons when in construction mode. It's just a toggle.

Well, there is that as a problem as well. Also, it would probably be worthwhile to explore what should the standard pattern look like to represent construction geometry. Admittedly, I like that the icons change to represent construction mode. There is also the issue of switching to static icons with just a toggle and how that would affect the existing user-base of the last 20 years who are used to all of the icons switching with construction.

Some things are worth pushing a change forward, and others are not. I'm not sure I would feel comfortable going too far with changing the existing paradigm on this.

**Comment by czinehuba** [comment]
@obelisk79 That's why I tough just a quick change to reflect that the construction lines are dashed without upsetting old users or changing things drastically. 
Then, if it needs further changes to the construction icons, that should have another discussion and further consideration...

**Comment by obelisk79** [comment]
Well, I'm not against the change, I would just prefer we define the parameters for illustrating the pattern in icons.

**Comment by yorikvanhavre** [comment]
I'll merge this so we get a chance to test "in real life" :)

**Pull request merged**
