### PR TITLE
Path.Area: fix for coverity issue

### PR DESCRIPTION
**Pull request by realthunder**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Merged.

**Comment by sasobadovinac** [comment]
Are this CID 168950 and 168995 ?

**Comment by realthunder** [comment]
Commit ccd3fbd is aimed for 168950. The code does indeed have problem when the list is empty, but I am not sure this is actually the reason why coverity complains. For 168995, I can't seem to find any problem there.

**Comment by sasobadovinac** [comment]
Ok, I will just mark it in Coverity, thanks!

**Pull request closed without merging**
