### PR TITLE
CI: various improvements

### PR DESCRIPTION
**Pull request by 0penBrain**
This PR offers a new bunch of improvements to CI:

* Customized timeouts for tests so if goes stuck, we don't have to wait for 6h to have the fail report
* Improve reporting in configure and build steps by providing (only) useful information for 1st level analysis
* Use 'continue-on-error' for silent failing of steps, so they will still be easy to catch through notifications and step exit codes
* Upload crash dumps in artifacts in case there was a core dump
* Improve test reporting by providing:
  * A summary of failed tests
  * A summary of tracebacks that appeared out of failing tests

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8516">pipeline status</a> for feature branch [PR_8516](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8516). Pipeline [780204600](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/780204600) was triggered at [ee8a221](https://github.com/FreeCAD/FreeCAD/pull/8516/commits/ee8a2216ca19db5c1db44b38070d717dbe313e52). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Do you mind if I squash this when merging? I'm not sure in the final merge it makes sense to keep the eleven commits separate.

**Comment by 0penBrain** [comment]
@chennes I prefer to have them separated. They all are touching different points, and if one is causing trouble in the future, that will ease rollback.

**Comment by chennes** [comment]
Fair enough. Let's merge it then...

**Pull request merged**
