### PR TITLE
Get Plot and Ship back to life! (but not here!)

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Woha, they really were rusty! I tested them a bit and it seems everything works just fine.

It would be nice to get closer more standard modules (like Draft), as well as optimizing it, but this shall be enough to let someone else take care on the modules from now on (of course I am always willing to help new contributors)

Let me know!

### CODE REVIEW

**Comment by luzpaz** [comment]
JFYI, Plot and Ship were moved into their own workbenches:  
https://github.com/FreeCAD/freecad.ship  
https://github.com/FreeCAD/freecad.plot

**Comment by sanguinariojoe** [comment]
OK! Now I submitted PRs to https://github.com/FreeCAD/freecad.ship and https://github.com/FreeCAD/freecad.plot, and removed all the traces of both modules from here.

I am checking that all is compiling and working as expected

**Comment by sanguinariojoe** [comment]
It seems to works just fine!

**Comment by luzpaz** [comment]
Are there any core dependencies on plot or ship ? I know for example that external cfdof workbench utilizes Plot but i think they are specifically using the external freecad.plot workbench (right @oliveroxtoby ?)

**Comment by oliveroxtoby** [comment]
@luzpaz That's right, using the external one.

**Comment by sanguinariojoe** [comment]
> Are there any core dependencies on plot or ship ? I know for example that external [cfdof](https://github.com/jaheyns/CfdOF) workbench utilizes Plot but i think they are specifically using the external freecad.plot workbench (right @oliveroxtoby ?)

I have been taking a look and it seems they can be safely remove. Some modules rely on matplotlib (e.g. FEM), but not on Plot module

**Comment by luzpaz** [comment]
@wwmayer Is it time to remove these workbenches from master?

@sanguinariojoe do you mind dropping these unnecessary commits from the PR? 
3638022
9a8e723
a6a3876

**Comment by sanguinariojoe** [comment]
> @sanguinariojoe do you mind dropping these unnecessary commits from the PR?

Is it not easier to just squash and merge?

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/4890

**Pull request closed without merging**
