### PR TITLE
PATH: change holding tags to not generate the PATH each time a new tag is added or one is modified

### PR DESCRIPTION
**Pull request by mlampert**
Currently adding tags is a painful exercise because each addition causes a complete recompute of the new path. The more tags there are, the longer it'll take.

With this change the UI lets the user add tags and they are just visualized, but not actually generated. Only if the user presses OK or Apply is the actual path recomputed.

### CODE REVIEW

**Comment by mlampert** [comment]
For build failure issue see https://github.com/FreeCAD/FreeCAD/pull/903

**Comment by wwmayer** [comment]
In commit 8857de4e0c9 you added this line: 
`if (!Cur || !isIn(Cur)) continue;`

Do you have an example where things crashed with current master?

**Comment by mlampert** [comment]
I don't have an example that works for master.

I looked into it in the debugger and the vertexMap included 3 entries (in my example) with 0x0 being the value pointer. I could not root cause the issue but saw the same guard in line 2057, similar for loop - so I figured the missing guard was an oversight.

If this is a major concern I can try and reproduce with a minimal code example.

**Comment by wwmayer** [comment]
> If this is a major concern I can try and reproduce with a minimal code example.

Well, it actually shouldn't happen that  vertexMap contains invalid elements. Recently, I encountered exactly this problem where a feature in its onChanged method triggered a nested recompute() and this cleared the vertexMap while the the first recompute() was expecting valid data.

So, now nested recomputes are not possible any more and I wonder if there is still a way to invalidate vertexMap.

**Comment by mlampert** [comment]
OK, let me see if I can isolate it and come up with small test for it.

**Comment by wwmayer** [comment]
For now I have merged your branch as the extra check at least is harmless. The vertexMap currently is only used in two methods and I plan to make it a local variable inside the recompute() method, furthermore I check if there are other ways to cause nested calls of recompute().

So, if you can bring an example where vertexMap has invalid elements that would be fine but don't waste too much time on it, please. Therefore I leave this PR open for another couple of days...

**Comment by mlampert** [comment]
I've done several experiments, including reverting everything back to where it was when I ran into the segfault (rebased on the current master). And I could not reproduce the segfault. I think the changes you made successfully prevent this situation from happening and the guard I added has become obsolete.

**Comment by wwmayer** [comment]
OK, so then this PR can be closed. Thanks!

**Pull request closed without merging**
