### PR TITLE
Deletes GCS::Constraint directly instead of calling GCS::free().

### PR DESCRIPTION
**Pull request by andre-caldas**
As requested by @abdullahtahiriyo. See https://forum.freecad.org/viewtopic.php?t=76724#p673116.

Still needs to eliminate the switch/case from `GCS::free(std::vector<Constraint*>)`, to simply [delete the constraint instead of `static_casting` the many possible derived classes](https://github.com/FreeCAD/FreeCAD/blob/84808ef7bd0752e60e8050b3f8e5edef2afa5e29/src/Mod/Sketcher/App/planegcs/GCS.cpp#L5590).

---

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

It does not. Sorry!
Tests did not pass clean, but they did not pass clean using the code form FreeCAD/master, either. I get:
```
Activate workbench 'ImageWorkbench'
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3bf90) [0x7f6cba45af90]
#1  0x7f6cbc853820 in typeinfo for Base::ConsoleOutput from /home/andre/repositorios/FreeCAD_stable/build/build-FreeCAD_stable-Imported_Kit_temporary-Debug/lib/libFreeCADBase.so+0
Abortado
```

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9184">pipeline status</a> for feature branch [PR_9184](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9184). Pipeline [828507552](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/828507552) was triggered at [048f84f](https://github.com/FreeCAD/FreeCAD/pull/9184/commits/048f84f1568f3dfbe50537e16e244fd5023352e1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by andre-caldas** [comment]
I am very sorry... I thought it was a good idea to keep merging "master" into the PR. Now, I realize it only makes the review process more complicated. :-(

**Comment by wwmayer** [comment]
> Activate workbench 'ImageWorkbench'

Check your **build** directory if under Mod you still have a directory Image. If yes remove it and retest. Report back if you still encounter this crash.

**Comment by wwmayer** [comment]
> But three errors are reported with or without the PR:

TechDraw works fine for me -- in App and Gui version. Maybe report this into the forum to wandererfan.

Nevertheless, this PR is not responsible for the failure and sine the change was requested I am going to merge it.

**Pull request merged**
