### PR TITLE
[Gui] Send 'mainWindowClosed' signal before window settings are saved

### PR DESCRIPTION
**Pull request by 0penBrain**
So macros/add-ons can eventually restore things

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

### CODE REVIEW

**Comment by chennes** [comment]
Is there a forums discussion about this? The change looks fine, but I don't really know how to test it.

**Comment by 0penBrain** [comment]
@chennes : no forum discussion. Generally core changes lack of interest. :) 
The context is that if a script connects to this signal, it can change window settings before they are saved (my use case is a macro that modifies things when run, and that shall restore them before exit).
You can simply test it with below snippet : 
```from PySide import QtGui
mw = Gui.getMainWindow() # Main window
cv = mw.findChild(QtGui.QDockWidget, 'Combo View') # Combo view pane
cv.hide() # Hide combo view
def showCV():
    global cv
    cv.show() # Show combo view
mw.mainWindowClosed.connect(showCV) # Connect to closing signal
mw.close() # Close FreeCAD
```
When reopening FreeCAD, the combo view will be hidden without this PR, shown with.

**Comment by yorikvanhavre** [comment]
This requires testing i guess, just to see if it doesn't break anything, but otherwise it looks ok to me

**Comment by 0penBrain** [comment]
> This requires testing i guess, just to see if it doesn't break anything, but otherwise it looks ok to me

@yorikvanhavre it shouldn't break anything as the signal isn't used inside FreeCAD except for Tux mod where it only deletes a parameter group. ;)

**Review by chennes — APPROVED** [review]
This compiles, runs, and has the effect described by @0penBrain above. This doesn't appear to cause any regressions, and it seems unlikely that emitting this signal earlier than before will introduce any problems. Probably the only way to find out for sure is to merge it and wait 😀.

**Comment by yorikvanhavre** [comment]
mergeeand wait it is, then :) thanks guys!

**Pull request merged**
