### PR TITLE
Use Python 3 as interpreter for fcinfo

### PR DESCRIPTION
**Pull request by sirhcel**
Since Python 2 support has been dropped with #6143, let's have Python 3
as default interpreter on the platforms caring for it.

--- 

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by benj5378** [comment]
I don't know anything about this interpreter information... but is it even relevant to have inside FreeCAD?

**Comment by sirhcel** [comment]
Yes, this information is relevant for running the `fcinfo` script from within a shell which is the case when using it as a diff helper for Git as described at [Enabling human-readable diffs for FCStd files with the fcinfo utility](https://wiki.freecad.org/WebTools_Git#Enabling_human-readable_diffs_for_FCStd_files_with_the_fcinfo_utility).

The line changed in this PR is the so-called [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) line is used by Unix shells (Linux, macOS, ...) to select the program for executing this script. It's common practice to have shell scripts are marked as executable (as `fcinfo` is) and start with such a line. So after checking out the FreeCAD repo you could directly execute `fcinfo` from your favorite shell and Git.

On Linux and macOS, and Windows the Python 3 interpreter is called `python3` in contrast to Python 2 which was just called `python`. Python 2 has been deprecated a while ago and #6143 removed the compatibility support for it. So we should consequently use the actual Python 3 interpreter `python3` for running the `fcinfo` script.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7372">pipeline status</a> for feature branch [PR_7372](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7372). Pipeline [616380662](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/616380662) was triggered at [9e7bf31](https://github.com/FreeCAD/FreeCAD/pull/7372/commits/9e7bf3133191011c1c81c1044e0e8059e26d7ebd). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
does the script work correctly with python3? If yes this should be merged.

**Review by benj5378 — APPROVED** [review]

**Comment by donovaly** [comment]
Thanks fr the PR. Does it need to be backported to FreeCAD 0.20 as well?

**Comment by sirhcel** [comment]
Including this change in a future maintenance release of FreeCAD 0.20 looks to me like nice-to-have.

**Comment by donovaly** [comment]
OK, I will backport it then

**Pull request merged**
