### PR TITLE
Restore QTabWidget shape style in PropertyView.cpp to default style.

### PR DESCRIPTION
**Pull request by luciocorrea**
QTabWidget::Triangular is used only in src/Gui/PropertyView.cpp. It looks like it was planned to be used in src/Gui/CombiView.cpp too, but the code was commented out. 

It's a simple modification, but IMHO, it looks better now. 

Before:
freecad_tabs_before

After:
freecad_tabs_after

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I agree. No objections, anyone?

**Comment by luzpaz** [comment]
makes sense since the rest of the GUI is squared tabs:
image

**Comment by Patola** [comment]
I wholeheartedly agree.

**Comment by wwmayer** [comment]
Under Windows the triangular tabs looks better than the rectangular one, IMO. In the past under Linux it also looked good but then several Ubuntu/Qt versions ago it started to look less good.

So, if you don't mind then I will make it OS-dependent.

**Comment by wwmayer** [comment]
git show 7756c27

**Comment by luciocorrea** [comment]
Ok, but there are several tabs in FreeCAD. So, why apply Triangular style only to PropertyView?

**Pull request closed without merging**
