### PR TITLE
[Path] Added GUI support to PathDeburrOp for direction selection

### PR DESCRIPTION
**Pull request by Schildkroet**
Added GUI support to PathDeburr Operation to select direction (CW, CCW)

### CODE REVIEW

**Comment by Schildkroet** [comment]
pathdeburr

**Comment by dubstar-04** [comment]
It would be more consistant if the direction dropdown was located in the same place as other ops. 

image

**Comment by Schildkroet** [comment]
Rearranged GUI
pathdeburr2

**Comment by sliptonic** [comment]
Was there some discussion about a standard for metadata?  We've used __author__ __title__ and __url__ for a long time.  I've seen a few of the others from time to time but not consistently.  

Lately I'm seeing more pull requests with __scriptVersion__ and __lastModified__.   I don't understand the use of these since it's obvious from git.   

Did I miss a discussion?  If not, what's the reason for using these tags?

**Comment by Schildkroet** [comment]
Well, i just added it because others were doing the same. No particular reason from my side.
I will remove it then.

**Comment by Schildkroet** [comment]
Comments removed

**Comment by vocx-fc** [comment]
> Lately I'm seeing more pull requests with **scriptVersion** and **lastModified**. I don't understand the use of these since it's obvious from git.

@Russ4262 has been adding those. See https://github.com/FreeCAD/FreeCAD/pull/3068#discussion_r380942590.

**Pull request merged**
