### PR TITLE
Addon Manager: Handle UTF-8 decode failures

### PR DESCRIPTION
**Pull request by chennes**
When processing downloaded text-based metadata files, catch any decode exceptions that get thrown and translate them into a useful error message for developers.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7711">pipeline status</a> for feature branch [PR_7711](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7711). Pipeline [686295015](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/686295015) was triggered at [80d103a](https://github.com/FreeCAD/FreeCAD/pull/7711/commits/80d103afb39155cc9b3d543b7a022fabf0004b17). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
I can verify that the PR fixes the issue.

**Review by donovaly — APPROVED** [review]

**Comment by donovaly** [comment]
I assume this fix also needs to be backported, right? If so, can you please do this?

**Comment by chennes** [comment]
Yes, I will do so.

**Comment by chennes** [comment]
Backported in 83f4b2c293966962d87f64070d7a5d2d9c162a9f

**Pull request merged**
