### PR TITLE
[Gui] Add FirstStartWizard

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by benj5378** [comment]
https://forum.freecad.org/viewtopic.php?p=674568&hilit=wizard#p674568

**Comment by benj5378** [comment]
image
image
image
image

Awaiting fixes for #10015, then themes selector can be finished.

**Comment by PaddleStroke** [comment]
Ah nice to see this moving forward. I'm glad I have not jumped on this yet as I was planing to give it a go 2 weeks ago 😄 

Some remarks : 
1 - The CI is not building : 

> /home/runner/work/FreeCAD/FreeCAD/src/Gui/DlgFirstStart.cpp:40:31: error: ‘MarkdownText’ is not a member of ‘Qt’
>    40 |     label2->setTextFormat(Qt::MarkdownText);
>       |                               ^~~~~~~~~~~~
> /home/runner/work/FreeCAD/FreeCAD/src/Gui/DlgFirstStart.cpp:44:30: error: ‘MarkdownText’ is not a member of ‘Qt’
>    44 |     label->setTextFormat(Qt::MarkdownText);
>       |                              ^~~~~~~~~~~~

2 - For the workflow section, ordering the workbench in terms of importance rather than alphabetically ?

3 - Adding a 'Mechanical Part CSG' where partDesign is not activated.

4 - Adding a QLabel between the radio buttons and the list that gives a short description of the workflow : 

> "Design parts in Part Design by drawing sketches with Sketcher, then extruding/pocketing them in Part Design. Make organic shapes with Surface. Your technical drawings with TechDraw. Your thermal and mechanical analysis with FEM. And your CNC jobs with Path."

> "Design parts in Part by adding and removing primitives. Make organic shapes with Surface. Your technical drawings with TechDraw. Your thermal and mechanical analysis with FEM. And your CNC jobs with Path."

5 - Add a combobox in the Visual step called 'Interface type' with 'Simplified' and 'Advanced' where in simplified some toolbars are hidden by default.

**Comment by sliptonic** [comment]
It's good to see this moving forward.  I'm going to be a stickler for process on this one?  Where's the original issue in the tracker?   Can we have some conversation about exactly what a 'First Run Wizard' is and does before we implement it?

**Comment by benj5378** [comment]
> 1 - The CI is not building

I have no idea why it's only failing on 20-04. Are the CI running on Qt version lower than 5.15?

> 2 - For the workflow section, ordering the workbench in terms of importance rather than alphabetically?

What is important and what is not? The list isn't that long anyway, so not important IMO. What would users gain anything from it being sorted by importance?

> 3 - Adding a 'Mechanical Part CSG' where PartDesign is not activated.

We should have pre-sets for the the general categories - and not too many as it would make confusion. If the only difference between "Mechanical Part CSG" and "Mechanical part design" (that I already added) is the Part Design workbench, it would be adding a new very specific category. People should choose "Mechanical part design" then and just not use Part Design, would probably also be better for the UX and avoid confusion on whether they need Part Design or not.

> 4 - Adding a QLabel between the radio buttons and the list that gives a short description of the workflow

I see your point. Hmmm... maybe? I see your point but also want to keep it simple. If others want it too, let's add it.

> Maybe put a link to : https://wiki.freecad.org/Which_workbench_should_I_choose or use its information.

Idk, if this would be too much? Like, I see the idea, but it's a quick first start wizard. I don't think we want users to stay there spend long on their choice and having them read up on all the workbenches first. I guess more smooth user flow would be users just choosing a pre-set (or all) and then go watch a tutorial to find out, which workbench to begin in. Hmmm

> 5 - Add a combobox in the Visual step called 'Interface type' with 'Simplified' and 'Advanced' where in simplified some toolbars are hidden by default.

We should avoid confusion to why some toolbars don't exist on their computers, so the ones we hide away should be those very rarely used by the "simple" user. But I think it could be a good idea. Do we already have preference functionality for this? If not, I see the following needed tasks:
- Add functionality for only showing some preferences
- Add preference to preference page and first start wizard that triggers this functionality
- Make pre-sets (a list) of what workbenches should only be shown in "Simple" mode.

@qewer33 and @macdroid53 helped make the workbenches list. What do you guys think?

@PaddleStroke Thanks for the feedback, great to hear some ideas.

**Comment by benj5378** [comment]
> It's good to see this moving forward. I'm going to be a stickler for process on this one?

@sliptonic And we should be, as this is the first anyone would meet in FreeCAD. Should be simple, easy to use and relevant for the users.

> Where's the original issue in the tracker? Can we have some conversation about exactly what a 'First Run Wizard' is and does before we implement it?

#5772. Yes, let's have a conversation of what we want to achieve with it and what should be included in it. So far, I have worked out from @MisterMakerNL's mock up, that was based on the forum discussion I linked.

**Comment by macdroid53** [comment]
"Can we have some conversation about exactly what a 'First Run Wizard' is and does before we implement it?"

TBH, the reason this has not been done, to date, is that it has been lost in the "conversation" for a LONG time.

This has drawn a line in the sand and is a very good starting point.

I think it would be best to put it out there and see what actually usage feedback comes in. Then adjust accordingly going forward.

IMO, this covers much of "what a 'First Run Wizard' is and does", so go live and see what happens. (obviously after it passes the coding standards.)

**Comment by qewer33** [comment]
I also have a few suggestions to make but mainly agree with PaddleStroke's points (other than point 3).

1 - More information could be added to the last page such as linkts to the FreeCAD wiki, forum and Discord server along with a paragraph that reads along the lines of "If you need any help, the FreeCAD wiki is your friend. You can also asks sign up and asks questions in the FreeCAD forum or join the FreeCAD Discord server."

2 - About the "Simplified" and "Advanced" interface suggestion. The advanced preset could have the Report View and Python Console enabled and the simplified interface could have those along with the File and Edit toolbars hidden.

3 - Putting the splashscreen image as a banner to the welcome wizard dialog would look really cool. Could you attempt that @benj5378?

4 - Maybe 3D view background color configuration could be added to the Visual page? not really sure if this is a good idea but it can be discussed ig.

**Comment by sliptonic** [comment]
I'm glad you found an original issue to attach this to.  That's a good starting point.  
The issue is weak though.  It doesn't describe what the actual problem is that we're trying to solve.  It's a feature request.  Actually, to be honest, it's a collection of feature requests.  

> I think it would be best to put it out there and see what actually usage feedback comes in. Then adjust accordingly going forward.

That's the development approach we're trying to discourage.  We're trying to be more focused on identifying the actual problem BEFORE we put stuff out there.  Iterating is good.  You just have to iterate on a solution not randomly walk around trying to figure out the problem.

**Comment by sliptonic** [comment]
I may not be making myself clear so let me point out some problems I'm seeing with the proposed flow:

The first page asks for language, units, and mouse style.  Language makes sense, but why are you asking units?  A logical guess could be taken from locale but it would still be wrong.  If the user is intending to do CNC/CAM work, they MUST have a unit schema that uses minutes as a time unit.  So it would make more sense to understand what the user intends to do with the software before you fine tune the unit setting.

How will the user know what the mouse model does?  A simple combo box doesn't tell them enough to make a reasonable selection.   Ideally, they would be able to try them out in a little window.

Next is the visuals.  Will selecting these things in the combo boxes make realtime change to the UI so the user can see the result or is this just collecting choices to apply en masse at the end?   If it's just that one, it isn't any better than the existing preference panel.

The workflow panel is an interesting start.  The limitation is that it doesn't go far enough.  How do I (the path developer) let the user customize options for the Path workbench?  How does the user set up their tool collection?  Configure their machine?  

People have suggested in the past that the first run wizard (FRW) should help configure these things and also educate the user a bit along the way.   In other words, let them pick a user schema and also draw their attention to the schema selector in the bottom right.   Let them customize the list of workbenches and also educate them about what a workbench is.

What about explaining some of the other important concepts in FreeCAD like Addons?

Sorry.  I don't mean to be nay-sayer.  I'm trying to illustrate that the FRW isn't well understood yet and we're rushing to a solution.

**Comment by MisterMakerNL** [comment]
Realy nice too that this get some more traction.

My first setup was made so we only needed one page so I thought about what is necessary and stuffed that on one page.

I  didn't think users would like to go true pages of settings especially if this all could be one page.

**Comment by benj5378** [comment]
> The first page asks for language, units, and mouse style. Language makes sense, but why are you asking units? A logical guess could be taken from locale but it would still be wrong. If the user is intending to do CNC/CAM work, they MUST have a unit schema that uses minutes as a time unit. So it would make more sense to understand what the user intends to do with the software before you fine tune the unit setting.

This is a very valid point, for instance the one with CNC/CAM. But can we really trust the locale? I'm from Europe and my locale is US, that just happened to be selected when I wanted English to be the standard language on my computer. I know this isn't that uncommon.

> How will the user know what the mouse model does? A simple combo box doesn't tell them enough to make a reasonable selection. Ideally, they would be able to try them out in a little window.

IMO this is out of scope for the first start wizard. The idea behind the first start wizard is to let the user do some quick configuration, not to fine tune every setting. With the mouse model specifically, me and @qewer33 included it in case people came from another CAD.

The user isn't meant to know _everything_ when they are running the first start wizard; it has already been proposed that the user should be able to to test all mouse models and have descriptions of all the workbenches - they aren't meant to know everything. That would be the opposite of improving the UX IMO. Then it wouldn't be a first start wizard anymore. It's for new users, let's not ask them to go through loads of stuff before they can even use FreeCAD.

> Next is the visuals. Will selecting these things in the combo boxes make realtime change to the UI so the user can see the result or is this just collecting choices to apply en masse at the end? If it's just that one, it isn't any better than the existing preference panel.

They are real time changes, so they immediately see the effects they have. 

> The workflow panel is an interesting start. The limitation is that it doesn't go far enough. How do I (the path developer) let the user customize options for the Path workbench? How does the user set up their tool collection? Configure their machine?

Again, now you are asking the new user to know everything. Do they need to set up all their tools for CNC as the first thing when opening FreeCAD for the first time? Should we ask the user for setting up every workbench before they have barely opened FreeCAD? Then it's not a quick first start wizard anymore, but a Path workbench configuration wizard. This is _very_ out of scope for a first start wizard.

> People have suggested in the past that the first run wizard (FRW) should help configure these things and also educate the user a bit along the way.

Could you send some links to such suggestions? My goal was making a first start wizard for _configuration_ - not getting start guide. I mentioned this on the last dev meetings, no disagreed with that.

> In other words, let them pick a unit schema and also draw their attention to the schema selector in the bottom right. Let them customize the list of workbenches and also educate them about what a workbench is.

Once again, this is a first start configuration wizard. Do people want it to be a getting started guide instead?

> > I think it would be best to put it out there and see what actually usage feedback comes in. Then adjust accordingly going forward. - @macdroid53 
>
> That's the development approach we're trying to discourage. We're trying to be more focused on identifying the actual problem BEFORE we put stuff out there.

We want to identify and solve the issue before publishing a solution, that helps actually achieving what we are trying to achieve. I think what @macdroid53 means is, that we shouldn't use ages discussing fine polishing. We should identify the issue before putting stuff out - but we should not use ages discussing disagreements that no one will ever agree on. Then we should just publish a _valid_ solution _to the problem_, and then adapt the solution on the feedback that comes in.

Right now, the opposite is happening. Now, there have been raised so many questions and issues around my candidate to a first start wizard, that it is becoming unreachable to achieve. While discussions questions are nice, these should be raised as a long term discussion for a first start wizard - in a forum thread or issue.

Not on the PR unless it has content that doesn't help accommodate the issue. Are there any content in this PR that doesn't help accommodate the issue? This PR helps accommodate the issue partially, not fully, but asking that together with long-term ideas make the PR unreachable and thereby also the solving the issue unreachable, just as @macdroid53 described. Remember that for exception of a very few, this isn't our full time job.

I feel like there are raised more questions here (some of them out of scope) than we can possibly handle at once.

Long-term ideas and issues raised here that makes the PR unreachable (despite if I agree with them or not):
- Stating that it doesn't go far enough and should cover workbenches
- Asking for a 3D view inside the wizard to try out mouse models

Tweaks that's relevant to make to the PR
- Suggesting simple explanation of workbenches/addons
- Asking if the changes made are shown real-time to the user (so user actually can try out different ones)

>  I'm trying to illustrate that the FRW isn't well understood yet and we're rushing to a solution.

I don't recognize this at all? Multiple of points you are raising are long-term suggestions and not related to understanding workflow. This has been discussed on the forum with lots of mock-ups where it seems everyone has agreed upon it to be a configuration wizard, not a getting started guide, and highly supported @MisterMakerNL's mock-up. I don't see anywhere that it was asked to be a getting started guide as you're stating.

It seems like you have some personal opinions on this, which is fine - but you're being late to the party and believes everyone else missed the issue. While you on the forum thread and issue asked for narrowing down the issue, I don't see you raising any of the issues you just mentioned despite all the mock ups that you have seemingly seen. Suddenly raising all these worries on the PR is too late man.

> Sorry. I don't mean to be nay-sayer.

Sorry man, but when all this suddenly comes of out of the blue, you kinda are.

**Comment by sliptonic** [comment]
> I don't really get this, the unit system is an essential part of any CAD app.

Yes, absolutely.  I'm saying at this stage you don't have enough info to help the user make the right choice.


> , welcome screens shouldn't be too exhaustive,

Says who?  It doesn't have to be onerous.  A well-designed FRW would give the user the option to configure what they need and ignore the rest.

> IMO this is out of scope for the first start wizard.

Where is the scope defined?    


> My goal was making a first start wizard for _configuration_ - not getting start guide.

_your_ goal.   The point I was making was that the the PR should be solving a problem that _we_ agree to.  That very important work hasn't been done.  It won't take long to do it.  I suggest we make this a major point of the vancouver meetup.  Let's schedule a zoom or voice call and get everyone with an opinion on line.  Let's talk about what the scope is and then design a really great and flexible solution.


> we should just publish a _valid_ solution _to the problem_, and then adapt the solution on the feedback that comes in.

Right.  Still have to agree on the problem first.


> While discussions questions are nice, these should be raised as a long term discussion for a first start wizard - in a forum thread or issue.

Couldn't agree more.


> I feel like there are raised more questions here (some of them out of scope) than we can possibly handle at once.

Where's the scope defined?


> I don't see anywhere that it was asked to be a getting started guide as you're stating.

It came up at Fosdem last year.  It has been discussed in YouTube comments.  Telegram discussions,  Reddit threads and host of other places.   It's all over the map.  Exactly why I'm saying the design process needs more rigor before implementation.  IIRC Gimp implemented a FRW a few years ago then ditched it and are trying to do it again.  

You are right that this is a really critical feature.  I don't understand why you guys want to rush to a weak solution rather than designing a great one

**Comment by benj5378** [comment]
>> My goal was making a first start wizard for configuration - not getting start guide.
>
> _your_ goal.

Right, so none of the 6 pages of [forum discussion](https://forum.freecad.org/viewtopic.php?t=71277) about _configuration_ wizard ever happened. Okay.

> You are right that this is a really critical feature. I don't understand why you guys want to rush to a weak solution rather than designing a great one

Because it already was discussed on the forum. I make a PR from the forum thread, and suddenly, there is all kind of issues with it. I think there are three possible rationales here:

- There was already agreed on a great one on the forum discussion, that you missed out to elaborate your opinions to.
- There aren't the resources (or encouragement) in an open-source community to make so much happen at once.
- The people wanting a thorough discussion didn't elaborate on the forum discussion.

> It came up at Fosdem last year. It has been discussed in YouTube comments. Telegram discussions, Reddit threads and host of other places. It's all over the map.

Okay, yeah, then I have completely missed it. I go look on forum discussion and GitHub issue about a first start wizard, to figure out what people would like it to contain. I didn't go to Fosdem, YouTube, Telegram or Reddit to see any of this. Still wondering why you never raised this on the forum discussions, despite all the mock ups, if it was this all over the map.

**Comment by prokoudine** [comment]
> IIRC Gimp implemented a FRW a few years ago then ditched it and are trying to do it again.

Just to clarify.

GIMP used to have a first-run wizard a _long_ time ago. Users hated it, because they wanted to get on with their work, not tell the program what density their screen has. The team ended up ditching it in favor of figuring things out from screen info, locale settings etc.

The reason they are thinking of bringing it back is because they started changed the defaults to something people are 50/50 split over. As a former team member, I used to tell people on a very nearly daily basis that they could bring back the old way of doing things in under a minute by going to the Preferences dialog. And then I listened to fading muttering in return :)

More on the topic of the PR, I've done some actual research on this (and will submit it in time for the beginning of the hackathon), and many, many programs that are complex and require a lot of time to become proficient with (think SW, Revit, Ableton Live, Photoshop etc. — across many industries) do not have a first-run wizard.

The few ones that do have the wizard, follow a particular pattern. It's either about things related to storage of data and the way saving a project is organized (think recording gigabytes of audio to the wrong disk) or it's the GIMP-like situation where developers want to provide an alternative UX/UI solution. An example of that would be Blender's first-run wizard where you can e.g. choose between left-click selection vs right-click selection (something Blender users feel particularly strong about).

Something I will definitely recommend to people attending the hackathon IRL or remotely via a Zoom call is paying close attention to providing sensible defaults rather than exposing a setting in the first-run wizard.

**Comment by prokoudine** [comment]
> I go look on forum discussion and GitHub issue about a first start wizard, to figure out what people would like it to contain. I didn't go to Fosdem, YouTube, Telegram or Reddit to see any of this. Still wondering why you never raised this on the forum discussions, despite all the _configuration_ mock ups, if it was this all over the map.

This has been raised on the forum many times. The thing about the forum is that it's a messy medium. You can easily locate threads where people suggest a solution, and then the discussion goes somewhere else entirely right up to the point where a moderator has to lock it, because people start getting nasty. That and, well, FreeCAD users themselves are all over the interwebz, for better of worse :)

The larger point @sliptonic is (maybe not so obviously) making here is that FreeCAD has been under extremely chaotic development for two decades and has a really messy UX/UI as a consequence of that. The project needs to change its approach to developing interfaces and workflows. This means certain changes need to go through a proper research phase, otherwise you end up with multiple sides shouting at each other about opinions.

**Comment by benj5378** [comment]
@prokoudine Thanks for sharing the background behind the GIMP's first start wizard. It helps to give information about why someone would (not) like a first start wizard.

> This means certain changes need to go through a proper research phase, otherwise you end up with multiple sides shouting at each other about opinions.

The issue isn't different opinions, the issue is suddenly coming with them _after_ forum discussion has already been done and a PR has been made - and then suddenly saying that I am rushing to a solution. So what do you (and @sliptonic) should have been done in addition to the already present forum thread?

**Comment by MisterMakerNL** [comment]
I was more fan of the Blender first start screen:
afbeelding
Simple clean and fast.

**Comment by benj5378** [comment]
> > So what do you (and @sliptonic) should have been done in addition to the already present forum thread?
>
> Assuming your question is what I think we should do next

@prokoudine, no, was asking what should have been done. There was a forum thread running for 7-8 months, 6 pages long of various developers agreeing to a _configuraton_ wizard. Then suddenly, I am accused for having decided this all on my own and rushing to a solution, despite the accuser to have seen this forum thread and not said a word.

So what should I have been done - prior to making a PR - to not get accused for deciding this all on my own and rushing to a solution?

**Comment by prokoudine** [comment]
Another example is the styling of FreeCAD. If you build this with new users in mind, you'd have to make sure that the changes will apply immediately so that the user could do a quick evaluation and decide whether the UI theme is ok for them. If, due to some toolkit-level specifics, FreeCAD would require restarting for styling to apply, this is not going to be a great UX. So you also have to consider possible technical limitations.

**Comment by prokoudine** [comment]
> @prokoudine, no, was asking what should have been done. There was a forum thread running for 7-8 months, 6 pages long of various developers agreeing to a _configuraton_ wizard and some Discord discussion.
> 
> The issue is that despite a forum discussion and Discord discussion being having run prior to the PR, I am accused for having decided this all on my own and rushing to a solution, despite the accuser to have seen this forum thread and not elaborated at all with his disagreements.

I don't think anyone's accusing you of anything. Au contraire, actually caring enough to do the work is highly appreciated here, I can guarantee that. The suggestion is to not treat that thread as a definitive answer to what the first-run wizard should do or be. It might very well be the case that we will end up with a very similar set of things to configure, or even with a very similar design. But we need a proper discussion.

**Comment by benj5378** [comment]
> I don't think anyone's accusing you of anything

> _your_ goal. [...] _we_ agree to.

> FRW isn't well understood yet and we're rushing to a solution

There must be some culture difference between our countries.


> But we need a proper discussion.

So how could I have started a proper discussion _prior_ to the making a PR. Why wasn't various developers agreeing in a forum thread enough? What could I have done to make people state their opinions prior to making a PR, so they wouldn't suddenly come out of the blue after making a PR? (which is my biggest problem)

**Comment by prokoudine** [comment]
@benj5378 I believe the generally accepted way these days is to either join an existing discussion in a GitHub issue (if there is one) or starting a new one with a proposal, then working on patch. @chennes might want to correct me on that.

**Comment by benj5378** [comment]
@prokoudine So the issue here was, that the mutual agreement was reached on the forum, and not on the GitHub issue? Is that really the issue here? Despite the disagree'r having seen the forum thread?

So if the agreement is made on the forum  - _instead_ of on GitHub - one doesn't need to elaborate with any of their opinions, but are then allowed to suddenly raise them all after a PR with an implementation is made.

@prokoudine Did you actually see the forum thread with sliptonic's posts where he doesn't mention any of his disagreements? You're saying, if this had all happened on GitHub issue instead, he would suddenly have posted them all? And that the fault is that it wasn't made on GitHub, because sliptonic isn't allowed to raise his worries in a forum thread?

I think I must vastly have misunderstood how FreeCAD dev agreement works then.

**Comment by sliptonic** [comment]
> @prokoudine So the issue here was, that the mutual agreement was reached on the forum, and not on the GitHub issue? Is that really the issue here? Despite the disagree'r having seen the forum thread?

In part, yes. 
You say there was mutual agreement reached but that isn't accurate.  The forum doesn't constitute any formal consensus.  Did the maintainers weigh in?  Did they even see it?  The forum discussion was fine with some decent ideas suggested but there's no reason to consider consensus to exist.

As I said when I first weighed in,  I'm going to be a stickler on the process for this one.   Specifically this issue because the problem is poorly defined and opinions vary wildly on what a mimimum and accurate solution is.

Just to remind:  The process is very well spelled out in the [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) file which is included in the root of the source tree.

[It starts with a well defined problem](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md?plain=1#L28)
[
Those issues are submitted and discussed in the tracker](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md?plain=1#L29)

[They issue process improves the design before the work is done](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md?plain=1#L66-L68)

[Eventually a PR provides a minimal and accurate answer to the problem](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md?plain=1#L52)

**Comment by benj5378** [comment]
> You say there was mutual agreement reached but that isn't accurate. The forum doesn't constitute any formal consensus. Did the maintainers weigh in? Did they even see it?

Yourself, @yorikvanhavre, @chennes all saw it, some saying that the mock up is really good. Idk what more maintainers you wanted and if they had. Still you didn't mention any of your issues in the thread, but suddenly you mention them here.

If no one disagreeing with making it a configuration wizard isn't consensus, idk what is? Sounds like next time I should tag all maintainers and specifically ask if they agree, together with community members.

> > @prokoudine So the issue here was, that the mutual agreement was reached on the forum, and not on the GitHub issue? Is that really the issue here? Despite the disagree'r having seen the forum thread? 
> 
> In part, yes.

> I'm going to be a stickler on the process for this one

I should remember for next time, that we should have the exact same forum conversation just on a GitHub issue, just so you can add your comments there, because you don't want to add them in a forum thread. I don't have an issue with change of process to using GitHub issues, but purposely holding back your opinions, just to add them once a GitHub PR or issue is made, is just poor morale.

And still, there is a GitHub issue with a mockup of a configuration wizard, where you haven't stated any opinions that you oppose it being exactly that, a configuration wizard.

I'm sure there is someone with more detail for contribution processes that are willing to receive surprise opinions on their PR, that are willing meet the feature request. It's just not me, sorry.

**Comment by MisterMakerNL** [comment]
Oh no :(
I am pretty sure we can make this work!
My mockup was just empty code, although looked pretty good, now someone actually did the hard stuff. The rest is just a bit of tweaking and tuning.
We all agree that we need a getting started wizard, although I am now not sure if @sliptonic wants something different or he just just wants to follow procedures.

I hope you 2 get a beer and talk this out in a zoom meeting, so we can move on with this PR! Because it's a waste of good work to trash it for some small details like the layout.

**Comment by sliptonic** [comment]
Offered. 

I also offered to spend time on this at the hackathon.

I agree that this effort shouldn't be wasted. Let's make sure we're taking a baby step in the right direction and not an impulsive leap in the wrong one.

**Comment by PaddleStroke** [comment]
I think you guys are harsh with @benj5378. He has done the work after it was discussed at quite some length.
Even if the solution is not perfect it gives a basis on which to work and we should be doing constructive criticism. 

Besides I also side with him with the points you raised : 
- Guessing the system unit based on local system is wrong. My laptops is set to US_EN and if freecad gives me inches by default without asking me I'd be really annoyed. In europe many people set their computer to english.
- Configuring path on a FRW is wrong. The user is just getting started and he'd be overwhelmed by configuring questions about tools and such even if for now he's just getting started. If path needs that it should have a first-run-wizard of it's own launching when the workbench is activated for the first time.
- @sliptonic and @prokoudine both use the argument that theme should be shown on selection, when he actually said it was.
- The unit system for path must use min, I think that this by itself is what is wrong. If Path MUST have minutes, then it should detect if user's settings are in seconds and convert all the values automatically to minutes.

The different units are inconsistent in the metrics they define: some define a temporal, some don't. Some a speed unit. Some Newtons. Some length, length^2, length^3. What does that even mean? If I chose 'Imperial Decimal' Am I in seconds or mintues ? This all doesn't make sense for the user. Just look at the thing: 
image

**Comment by PaddleStroke** [comment]
Having said that maybe language is not required, as for language we can maybe safely use the system default. If a french guy set his computer to english, he probably wants the app in english.

**Comment by MisterMakerNL** [comment]
I definitely woukd use the language since I don't like the dutch language in my programs. It is also easier for finding help topics and sharing screenshots.
Solidworks isn't even in dutch and nobody cares. So I'll assume lots of professional CAD users will use English.

**Comment by obelisk79** [comment]
also if we are going to concern ourselves with time units, perhaps we should identify which workbenches rely on this setting. In my mind FreeCAD should just provide seconds, and the individual workbenches should be responsible for conversions as necessary when generating pathing/gcode etc.

**Pull request closed without merging**
