### PR TITLE
[PD] Extrude: modernize SignalSlot connection

### PR DESCRIPTION
**Pull request by donovaly**
as suggested recently by @chennes

@chennes , when this is correct, please merge (compiles for me, but I want to have a double-check)

### CODE REVIEW

**Comment by chennes** [comment]
Sure -- looks good at first glance, but I'll try testing it on a Linux VM (I assume you were testing on MSVC?)

**Comment by donovaly** [comment]
> Sure -- looks good at first glance, but I'll try testing it on a Linux VM (I assume you were testing on MSVC?)

Yep, I use MSVC 2019.

**Comment by chennes** [comment]
OK, tested on Ubuntu 20.04 and it seems to be working fine, so I'll merge it now.

**Comment by donovaly** [comment]
Thanks.

**Pull request merged**
