### PR TITLE
3rd Attempt

### PR DESCRIPTION
**Pull request by KeithSloan**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by KeithSloan** [comment]
I am lost on why this keeps failing.

I do
git pull --rebase official master
git push origin master
Make sure changes are there
git commit -m " A commit"
git push
Then via the web make to pull request.

**Comment by yorikvanhavre** [comment]
Ok in any case this PR looks good. So I'm merging! I'll adapt the code to print a warning if the PLY module is not there.

**Comment by yorikvanhavre** [comment]
Ok done. I have fixed the cmake file too, and added a warning in d2b943e8b7 and 630fc040a Could you or anyone else ( @vocx-fc ? ;) ) have a look at https://www.freecadweb.org/wiki/OpenSCAD_Module#Hints and add info as how to install the module?

**Comment by vocx-fc** [comment]
> git pull --rebase official master
> git push origin master

Your code should be inside a branch, not inside master.
```sh
# create a new branch and switch to it
git checkout -b my_branch

# do whatever additions and changes need to be done
# commit those changes
git commit -a -m "Commit message"

# rebase the current branch against the upstream master
git pull --rebase upstream master

# push only the created branch to your own online repository
git push origin my_branch

# then you can use the web interface to start the pull request
```
This is described in [Source_code_management](https://www.freecadweb.org/wiki/Source_code_management)

Anyway, I have added the installation documentation to the [OpenSCAD_Workbench](https://www.freecadweb.org/wiki/OpenSCAD_Workbench).

**Pull request merged**
