### PR TITLE
Path: Added postprocessor for UC-CNC

### PR DESCRIPTION
**Pull request by luzpaz**
Forum: https://forum.freecadweb.org/viewtopic.php?f=15&t=56987  

edit: I'm helping papaathome submit their PR to the FreeCAD repository. All credit goes to @papaathome

### CODE REVIEW

**Comment by papaathome** [comment]
@luzpaz 
I checked the build log to see why it is failing and two things came up (for me).

The first one is simple. Around line 10986 - 11003 in the build log files are listed in the .../Path/PathScripts/port/ folder.
The script uccnc_port.py is missing.
My explanation (to be checked):
I did add the uccnc_port.py file but have not looked at the build process at all. The build process is not doing anything with the new script.

The second one is more confusing (for me) and I have no explanation for it.
At the end of the build log there is a message about a .py file that cannot be parsed.
The file in question is not near the area of ../Path/ and the chances that I by accident did hit the file is very small.
Capture

I do not think it is a problem related to my actions.
It would be interesting to know if the same problem also occurs in other builds but I have not checked it.

recap:
A simple suggestion to create a 'Pull Request' turns out to be a bit more work than adding a file and a request to take it up in the standard distribution. So far I'm enjoying the experience and I will have a look into the build process and will try to get this working.

I also will try again to be able to build FreeCAD on my machine. Last year I tried but it failed because I could not solve all dependencies for a windows based build.

**Comment by chennes** [comment]
That second bug was introduced in commit af3643853cc0d5fbcbdbff1f84d39e8d6f0bc218, just a few hours ago.

**Comment by chennes** [comment]
Also, I should note that there are two issues that are preventing the Travis Windows builds from succeeding -- the first is simply that the dependencies have been moved. But the second is that the dependency library includes an updated version of Python, and this appears to be resulting in Travis being unable to run the unit tests for FEM, which counts as a test failure. So it's not really the fault of a specific commit here.

**Comment by luzpaz** [comment]
Closing in favor of #4664

**Comment by papaathome** [comment]
> 
> 
> Closing in favor of #4664

Thanks :) I was a bit slow on that action.

**Pull request closed without merging**
