### PR TITLE
Base: new FEM unit schema

### PR DESCRIPTION
**Pull request by berndhahnebach**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

https://forum.freecadweb.org/viewtopic.php?f=10&t=48642

### CODE REVIEW

**Comment by berndhahnebach** [comment]
some imperial unit conversation fails in unit test. But I did not do any explcit changes on any imperial unit code. Not some I know of ...

**Comment by vocx-fc** [comment]
Did you check that `FreeCAD.Units.listSchemas()` lists the new scheme? Do `FreeCAD.Units.schemaTranslate` and `FreeCAD.Units.parseQuantity` work as before?

**Comment by berndhahnebach** [comment]
`>>> 
>>> FreeCAD.Units.listSchemas()[8]
'FEM (mm, N, s)'
>>> 
>>> FreeCAD.Units.schemaTranslate(Units.Quantity("5 m"),8)
('5000.00 mm', 1.0, 'mm')
>>> `

**Comment by berndhahnebach** [comment]
```
>>> 
>>> FreeCAD.Units.parseQuantity("1000 m")
1000000.0 mm
>>> 
>>> FreeCAD.Units.parseQuantity("1000000 g")
1000.0 kg
>>> 
```
but the kg should be t IMHO ...

**Comment by berndhahnebach** [comment]
> I seem to remember that some unit handling is also done in the main `FreeCADInit.py` files, so maybe you need to check this as well.

only for the units itself not for the unit schema AFAIK. BTW: https://forum.freecadweb.org/viewtopic.php?f=10&t=48642&p=416435#p416435

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=10&t=48642&p=416455#p416455

**Comment by berndhahnebach** [comment]
I am ready.

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/3723

**Pull request closed without merging**
