### PR TITLE
Test: add a def to run all test case clases from a test module

### PR DESCRIPTION
**Pull request by berndhahnebach**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [commit is in the regard of test system] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [hopefully ;-)] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [there is not issue] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

extend this one:
https://github.com/FreeCAD/FreeCAD/commit/bf5f348
see:
https://forum.freecadweb.org/viewtopic.php?f=10&t=22190

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Are you sure it doesn't break anything, to remove an existing function (runTest())? It seems dangerous...

**Comment by berndhahnebach** [comment]
It has been added just a few days ago. https://github.com/FreeCAD/FreeCAD/commit/bf5f348 I thought it might be much more clear if we gone change the name. Since it has been added just a few days ago it is may be still possible ?

If you mind not change to the name runTest() drop a line and I will change my commit. 

bernd

**Comment by yorikvanhavre** [comment]
okay, indeed there should be no harm... Just pinging @looooo so he's aware of it.

**Comment by yorikvanhavre** [comment]
merged

**Pull request closed without merging**
