### PR TITLE
Refactor preferences into injected object instead of global.

### PR DESCRIPTION
**Pull request by Moult**
The following unrequired preferences are removed:

 - FORCE_BREP
 - STORE_UID
 - SERIALIZE
 - EXPORT_2D
 - FULL_PARAMETRIC
 - ADD-DEFAULT_SITE
 - ADD_DEFAULT_STOREY
 - ADD_DEFAULT_BUILDING

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I think your code makes the preferences being loaded only once at module import, right? However, the user might change preferences values between two imports. So we must reload all the preferences each time we perform an IFC import, because the module itself won't be imported again

**Comment by vocx-fc** [comment]
> I think your code makes the preferences being loaded only once at module import, right?

As I understand Moult's code, the preferences are given in the `insert()` function. I suppose this function is called by the interface whenever we import a file. Or what else calls it? What's the difference between `insert()` and `open()`, actually?

So, if the `insert()` function is called like `importIFC.insert(filename, docname)` it will automatically try to get the preferences at the current time using `getPreferences()`. That is, `importIFC` is not imported again; rather, `getPreferences()` is called every time, so it picks ups the preferences at that moment.

------
I also wonder about these global variables. I'm looking at `importDXF.py` and some functions use global variables. Is the idea that these global variables are always available in order to pick up the preferences change? I don't think this is needed; Moult's solution seems sensible.

I also thought that some global dictionary could be defined to place such options, like `FreeCAD.parameters["ImportDXF"].options["Variable name"]`. Then we could reduce the number of these global variables.

**Comment by yorikvanhavre** [comment]
Indeed, my bad... I had looked only at this
```
    if preferences is None:
        preferences = getPreferences()
```
and didn't see it was zeroed when running the function. Okay then!
The idea of the global variable was that you could do this:
```
import importDXF
importDXF.SOMEVARIABLE = False
importDXF.open(...)
```
But indeed it's not the only way and probably not the best way

**Comment by vocx-fc** [comment]
> The idea of the global variable was that you could do this:
> 
> ```
> import importDXF
> importDXF.SOMEVARIABLE = False
> importDXF.open(...)
> ```

I think the proper way to do it would be to
```
importDXF.open(filename, parameters=[somevariable, some2, some3])
```

Which I think is exactly what Moult's code does in IFC.

**Pull request merged**
