### PR TITLE
Core: Fix export extension problem

### PR DESCRIPTION
**Pull request by pieterhijma**
Closes https://github.com/FreeCAD/FreeCAD/issues/15203

Alternative to https://github.com/FreeCAD/FreeCAD/pull/15581

### CODE REVIEW

**Comment by adrianinsaval** [comment]
seems to work as expected, the only problem which would admittedly be pretty rare is that exporting something like Body.stl as stl will the first time be Body.stl.stl and the second time Body.stl.stl.stl but this is also the case for the other PR

**Comment by adrianinsaval** [comment]
Also it be nice if you are a little more verbose on the commit message. Like:
`Gui: Fix #15203 export filename incorrectly truncated after dot`

**Comment by pieterhijma** [comment]
@adrianinsaval, yes, sorry, was in a hurry. Fixed the commit message but still within 50 characters.

**Comment by FEA-eng** [comment]
I though this would only affect export and not saving but there seems to be a new issue related to it: https://forum.freecad.org/viewtopic.php?t=89791

**Pull request merged**
