### PR TITLE
Attacher UX enhancements

### PR DESCRIPTION
**Pull request by peterlama**
- New editor for MapMode with button to open attacher dialog
- Fix superPlacement being disabled after first change
- Disable MapPathParameter and MapReversed properties when they don't apply
- Disable super placement ui in attacher dialog when mode is deactivated
- Always select used mode in mode list

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by peterlama** [comment]
@DeepSOIC

**Comment by ickby** [comment]
You implemented the state based accessibility of the attachment properties, which I find very nice. I think it would be even nicer if next to setting the attacher properties (superplacement, MapPath, Reverse) to readOnly, you would also hide them in the Property editor. Is there a reason you did not implement that?

**Comment by peterlama** [comment]
You are the second person to request that. I guess I was just worried that people would find disappearing properties strange (I'm not aware of other features that do that), but maybe it would help to avoid confusion even more.

**Comment by sliptonic** [comment]
We often hide/show properties in the pane for Path objects.  For example, if the user doesn't use compensation on a profile, then there's no reason to show the property for 'side'.   It's worked really well for us and we've never had a complaint.

**Comment by peterlama** [comment]
Okay then, I've now changed it to hide the properties instead of making them read-only (I assumed read-only was meaningless if they are hidden).

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
