### PR TITLE
[TechDraw] Update Peoples Republic of China templates

### PR DESCRIPTION
**Pull request by luzpaz**
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=17&t=48854

CC @felixlee868

### CODE REVIEW

**Comment by luzpaz** [comment]
Added [skip-ci] to the last commit to avoid triggering travis

**Comment by vocx-fc** [comment]
Just a note. Some of the SVGs cannot be previewed on GitHub. This may have two causes:
* A GitHub problem; in the past I have noticed that GitHub experiences a temporary problem, and fails to display SVGs even if they are tiny in size, 4 KB or so. In this case we just have to wait until GitHub fixes itself.
* A problem with the SVG. If the SVG is not correctly constructed or has non-standard tags, it may be reported as Invalid, and fail to display. Make sure you save the SVG as "Plain SVG" as opposed to "Inskcape SVG". See #3060 and the links there for more information. In particular, using "Inkscape SVG" was found to cause problems sometimes when using such templates in TechDraw.

**Comment by WandererFan** [comment]
Is this ok to merge or does @vocx-fc comment need to be addressed?

**Comment by vocx-fc** [comment]
I think you can merge it; if it causes problems Felix or other Chinese users will report it, and at that point somebody who is familiar with these templates should step in to help.

**Comment by WandererFan** [comment]
merged.

**Comment by felixlee868** [comment]
Thanks

**Pull request merged**
