### PR TITLE
[TD] add Arch paper size templates

### PR DESCRIPTION
**Pull request by donovaly**
thanks to the recently merged PR #4292 one can use custom page sizes such as the templates in https://wiki.freecadweb.org/Arch_templates

This PR add them to be directly provided by FC.

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=35&t=54512&start=10#p470230

### CODE REVIEW

**Review by chennes — APPROVED** [review]
This looks great. I double-checked the sizes and they all correspond correctly to the table at https://www.agooddaytoprint.com/page/paper-size-chart-faq. All the template size fields have been updated correctly, and everything seems to be rendering the correct size. Thanks!

**Comment by chennes** [comment]
I suggest removing the `xml:space="default"` from the editable fields: Qt's DOM parser doesn't like the xml namespace, and when FC is compiled in debug mode this results in an `abort()` being called in FreeCAD. It's an upstream bug, but Qt DOM is no longer maintained so I doubt it will get fixed.

**Comment by donovaly** [comment]
> I suggest removing the `xml:space="default"` from the editable fields: Qt's DOM parser doesn't like the xml namespace

As I explained in the forum:
https://forum.freecadweb.org/viewtopic.php?f=35&t=54512&start=20#p470480
and following posts, the xml:space is a valid SVG 1.x tag. Thus it is a bug that FreeCAD does not handle it correctly and this needs to be fixed instead.

Not following the ISO standards will sooner or later make other problems so that cannot be our way to go. Since the bug in FC only occurs in debug mode, there must be a solution to ignore the xml:space DOM parser results when the parser cannot handle this.

**Comment by donovaly** [comment]
OK, for the meantime I removed the xml:space tags so that this PR can be merged.

**Comment by yorikvanhavre** [comment]
Thanks guys!

**Pull request merged**
