### PR TITLE
 Tools: reuse PY_CATCH in templateClassPyExport

### PR DESCRIPTION
**Pull request by realthunder**
I missed this patch in the big merge. It didn't fix anything. Just to improve exception handling and messaging and code reuse.

### CODE REVIEW

**Comment by wwmayer** [comment]
This change only partially improves exception handling in terms of consistency but also causes a regression because when setting/getting a Python attribute and an exception different to Py::Exception is raised the catch(...) block printed a message with the attribute name that made it really easy to locate the handler function (lines 623 and 662 of templateClassPyExport.py) .

Now with the change the meaningless message "Unknown C++ exception" will be printed. You even cannot be sure if the exception was raised in a Python handler or in a normal C++ function. And because of the heavy use of C macros it's not even possible to set a breakpoint, there.

The only option is to set a breakpoint in the Error() method of the console class but then it can take a long time until you encounter the scenario that raised this specific exception.

**Comment by realthunder** [comment]
I thought about including source and line information with something like, `Exception::ReportException(__file__, __line__)`, but then realized quickly that it is not very useful, as knowing where the exception is caught is not very useful in general. I always use `catch throw` to find out where the exception is thrown. I think it will be more useful to replace all throw statement with `FC_THROWM`, although it's debatable too.

So, do you think it's worthwhile to expand and PY_CATCH macro manually in templateClassPyExport.py? I feel the consistency is still very much needed.

**Comment by wwmayer** [comment]
TBH I am not a friend of excessive use of C macros. It's fine to use it in class declarations/definitions but IMO inside client code their usage should be minimized instead of maximized. After all we use more and more a modern C++ language and thus we should avoid the problem sites of C where possible.

Since the code generated by templateClassPyExport.py must be implemented only once I prefer to avoid using PY_CATCH there and instead harmonize the current exception handling with this macro.
Then a note to the macro definition can be added to also adjust templateClassPyExport.py in case the macro will be modified in the future.

**Comment by realthunder** [comment]
Modified according to you suggestions.

**Comment by wwmayer** [comment]
Thanks!

Merged.

**Pull request closed without merging**
