### PR TITLE
[TD] Prevent unused parameter warning

### PR DESCRIPTION
**Pull request by 0penBrain**
- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

### CODE REVIEW

**Comment by chennes** [comment]
Is there a reason this isn't getting used? There's a whole set of conditionals and operations in this function doing transforms, is flip being skipped for a reason?

**Comment by 0penBrain** [comment]
@chennes honestly I don't really know. :) I saw that in this function, determining the direction is fine with a so-called 'circulation test'. So I guess 'flip' is of no use. However I'm not a TechDraw expert and I basically just polished things. ;)

**Comment by chennes** [comment]
@donovaly Can you take a look at this? I'm hesitant to just blindly axe this warning, when it really seems to be indicating a potential error (a missing implementation of flip, which it looks like *might* be getting referenced in TaskCenterline (I'm looking at TaskCenterline.cpp line 420).

**Comment by yorikvanhavre** [comment]
I have no idea either :( In any case, if we're only removing it for cleanliness, I'd rather comment it out and add a note...

**Comment by 0penBrain** [comment]
@yorikvanhavre we can't just remove it as it is an argument. If we remove it we will break the function interface.

**Comment by chennes** [comment]
I think @donovaly is our de facto TD expert now that @WandererFan is gone -- he's the last one to touch code related to this, so I think we can just wait until he has time to weigh in. I'm concerned that this is one of those times when the static analyzer may have actually identified a genuine problem and shouldn't just be shut up.

**Comment by AjinkyaDahale** [comment]
This can probably be closed. @wwmayer just made this exact change recently in https://github.com/FreeCAD/FreeCAD/commit/378dec720c808f5b05216ed5e890e6d49bdc999a.

**Comment by 0penBrain** [comment]
Indeed. Closing.

**Pull request closed without merging**
