### PR TITLE
TechDraw: add Dialog Box for Balloons

### PR DESCRIPTION
**Pull request by fjullien**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by fjullien** [comment]
@WandererFan : if you like it, we could do the same for Dimensions.

I really don't like having to go to Properties view to change settings. Plus you have to click on recompute to get your changes displayed.

**Comment by fjullien** [comment]
And what about b9f6713 this also could be copied to other objects. For me, it looks better like this.

**Comment by WandererFan** [comment]
v0.19 is supposed to get create/edit dialogs for all TD objects - views,
dims, etc.  Lots of people have complained about this lack.

I'll push my Leader branch to git hub.  It has a line tracker/editor that
might be worth reusing.

**Comment by fjullien** [comment]
Ok I'll wait for your Leader branch.
I close this PR.

**Pull request closed without merging**
