### PR TITLE
[Spreadsheet] avoid removing user dynamic properties when clearing ce…

### PR DESCRIPTION
**Pull request by mwganson**
…lls, addresses issue #8655.  If you look at the hidden properties of a spreadsheet object you will see properties named such as "A1", or "B2" for cells that are in use.  When clearing the cells these properties are removed.  This was not an issue before changes were made to allow users to add their own dynamic properties to objects.  Now, we must check whether the dynamic property is one the user has added or if it is a cell address before removing it when clearing the cells.

An existing function isValidAlias(candidate) is there to check for whether a new alias being created is valid before creating it.  This is a 3-stage check: 1) is it already in use? 2) is it conflicting with reserved unit values, such as "mm"; and 3) is it a valid cell address name, such as "A1".  In orter to utilize this same functionality already there, this PR has separated that 3-stage validation function into 2 functions, one that only checks whether the candidate name is a valid cell address name, and other that checks already in use and unit name conflicts, the latter calling the new function as part of its check.

This allows us to call the new function to check if the dynamic property we are removing is a valid cell address name before removing it.  The diff isn't very clear as to exactly what changes were made for some reason.

### CODE REVIEW

**Comment by luzpaz** [comment]
An aside, codespell linting is broken in the CI
Screenshot_20241018_190825

**Comment by chennes** [comment]
I've added a basic set of C++ unit tests for the methods being modified here. They currently fail because "validAlias" accepts and empty string, which presumably it should not.

**Comment by mwganson** [comment]
Unit tests are a good idea.

The following is a way to clear an alias:

obj.setAlias("B2","")

If the alias validation function returns false for an empty string, then we need to account for the case where what we are trying to do is clear the alias.

Let me know if there is any change you need me to make on my end (or feel free to make any changes as you see fit, as well.)

**Comment by chennes** [comment]
I'm not sure what the right answer is here: I think I'd personally expect a method called `validAlias` to be able to be used to determine whether a given string is a valid alias (and the empty string is not), rather than just whether it can be passed to the `setAlias` method. But we're getting far afield from your original PR, so I think it makes sense to discuss that possible change separately from this PR. I'll adjust the test.

**Pull request merged**
