### PR TITLE
Material: fix windows debug builds

### PR DESCRIPTION
**Pull request by adrianinsaval**
Attempt to fix problem with yaml-cpp reported at https://forum.freecad.org/viewtopic.php?t=84376

@PaddleStroke please test if you have time

### CODE REVIEW

**Comment by davesrocketshop** [comment]
This does not work on windows. I'm working towards a fix in cMake/FreeCAD_Helpers/SetupLibYaml.cmake that will be a more general fix. I'm testing it on Windows now

**Comment by adrianinsaval** [comment]
it compiled but I'm not really sure if it actually works, windows is such a pain

**Comment by davesrocketshop** [comment]
> it compiled but I'm not really sure if it actually works, windows is such a pain

I'm testing now. It may be failing due to another unrelated issue (flat meshes) so it will take a bit

**Comment by davesrocketshop** [comment]
It appears to work. There are a number of unrelated runtime errors, but they don't appear to be related. They are:

- Problem loading MeshFlatteningCommand in AppMeshGui even with BUILD_FLAT_MESH disabled, perhaps related to
- Version incompatibility with NumPy and Python version

So the build is still broken, just not by yaml-cpp

**Review by davesrocketshop — APPROVED** [review]

**Comment by davesrocketshop** [comment]
During initialization the error "

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\Users\dcarter\Documents\Projects\freecad-build\bin\FreeCAD_d.exe"
  * The NumPy version is: "1.23.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
" occurred in C:\Users\dcarter\AppData\Roaming\FreeCAD\Mod\A2plus\.\InitGui.py
Please look into the log file for further information

**Review by chennes — APPROVED** [review]
I've tested this on my system and it works as advertised.

**Pull request merged**
