### PR TITLE
App: remove Py2 code from several src/App .cpp files 

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Review by DrInfiniteExplorer — APPROVED** [review]
Nice 👌

**Comment by luzpaz** [comment]
@wwmayer this PR should be good to go.

**Comment by yorikvanhavre** [comment]
Looks good to me... Ok for you to start removing py2-only code @wwmayer ?

**Comment by wwmayer** [comment]
> Ok for you to start removing py2-only code

Sure. We have already started removing Py2 code.

**Pull request merged**
