### PR TITLE
Use python3 to run MakeMacBundleRelocatable.py

### LINKED ISSUE #6773: [Feature Request] [macos] [mac] [osx] update `MakeMacBundleRelocatable.py` to work with python 3
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=10&t=68154

### Subproject(s) affected?

Other (specify in description)

### Idea description

basically as of macos monterey and newer aple stopped shipping a python 2 interpreter thus making a `FreeCAD.app` apple app bundle presently not possible due to the fact that the `MakeMacBundleRelocatable.py` will only run with a python 2 interpreter.

there have been several requests to produce a m1 build of a `FreeCAD.app` and this is one of the limiting factors.  

### Anything else?

after running,

```
cmake ...
make
```

then,

```
make install
```

i end up with the following stacktrace trying to run the `MakeMacBundleRelocatable.py` with a python 3 interpreter.

```
-- INFO: Analyzing bundle dependencies...
Traceback (most recent call last):
  File "/opt/code/freecad-git/src/src/Tools/MakeMacBundleRelocatable.py", line 388, in <module>
    main()
  File "/opt/code/freecad-git/src/src/Tools/MakeMacBundleRelocatable.py", line 371, in main
    build_deps_graph(graph, bundle_path, dir_filter, search_paths)
  File "/opt/code/freecad-git/src/src/Tools/MakeMacBundleRelocatable.py", line 221, in build_deps_graph
    if ( (ext == "" and is_macho(fpath)) or
  File "/opt/code/freecad-git/src/src/Tools/MakeMacBundleRelocatable.py", line 88, in is_macho
    if output.count("Mach-O") != 0:
TypeError: argument should be integer or bytes-like object, not 'str'
```

i'd fix the problem myself if i could, but my python skills are limited. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ageeye**
Python 2.7 was removed from macOS in update Monterey 12.3.  
Feature request in the forum [upgrade MakeMacBundleRelocatable.py to work with python 3](https://forum.freecadweb.org/viewtopic.php?f=10&t=68154).

Closes #6773

### CODE REVIEW

**Comment by ageeye** [comment]
@ipatch 
@looooo 

Please test it.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6784">pipeline status</a> for feature branch [PR_6784](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6784). Pipeline [523031767](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/523031767) was triggered at [c39b635](https://github.com/FreeCAD/FreeCAD/pull/6784/commits/c39b6352544ab2027e2305d4be0d6876a02ab708). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by ipatch** [comment]
awesome i'll take a look at this in a few.

**Comment by ipatch** [comment]
okay finally got around to testing this PR locally on my vm mojave build box, and im seeing the below error running `make install`

```
-- INFO: Analyzing bundle dependencies...
Traceback (most recent call last):
  File "/opt/code/freecad-git/freecad-src/src/Tools/MakeMacBundleRelocatable.py", line 391, in <module>
    main()
  File "/opt/code/freecad-git/freecad-src/src/Tools/MakeMacBundleRelocatable.py", line 374, in main
    build_deps_graph(graph, bundle_path, dir_filter, search_paths)
  File "/opt/code/freecad-git/freecad-src/src/Tools/MakeMacBundleRelocatable.py", line 229, in build_deps_graph
    for k in visited.keys():
RuntimeError: dictionary changed size during iteration
```

**Comment by ageeye** [comment]
Whatever with python3.10.2 method keys work fine. I think you used python3.9.7. I replace keys with list. See the new commit. Please test it again.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6784">pipeline status</a> for feature branch [PR_6784](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6784). Pipeline [523252207](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/523252207) was triggered at [3c91839](https://github.com/FreeCAD/FreeCAD/pull/6784/commits/3c918396bd4c9966df3eb1a7e5ff7f6a43d1d889). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6784">pipeline status</a> for feature branch [PR_6784](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6784). Pipeline [523256367](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/523256367) was triggered at [2934820](https://github.com/FreeCAD/FreeCAD/pull/6784/commits/29348203eeaad63c818d4bc41c3ead816b0542b2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by ipatch** [comment]
rebuilding now with your updates, will let you know in a few.

**Comment by ageeye** [comment]
Closes #6773

**Comment by ageeye** [comment]
> rebuilding now with your updates, will let you know in a few.

Have you had a chance to check it?

**Comment by ipatch** [comment]
> > rebuilding now with your updates, will let you know in a few.
> 
> Have you had a chance to check it?

working on it now. hopefully ill have something of meaning to share before COB CST 🤞

working with broken wrist so im down to one hand for typing 🤕

**Comment by ageeye** [comment]
Best wishes for a speedy recovery. No sweat!

**Comment by ipatch** [comment]
i'm pretty sure we should be good to go on this 👍 there was issue where this only worked with python ≥ 3.10 but has since been amended to work with python ≥ 3.9. 👍

ive been testing this PR on my movaje build box and with this PR python3 provided by homebrew is able to produce a `FreeCAD.app` bundle. so at this point i feel confident this is working.

and i just got access to an m1 box again the other so will test again on m1 shortly. (hopefully later today).

---

something non related however, is when the python script is `Updating dynamic loader paths...` it sometimes produces an app bundle that will halt on launch ie. double clicking the `FreeCAD.app` starts the launch process then the app never finishes launching and then macos opens with a crash report. i can only speculate why certain app bundles do this and others don't at this time unfortunately. i have found a very crude way to know that is the part where the script is `Updating dynamic loader paths...` but much more than that i don't know why the app bundle is failing to launch in certain instances. once again this is not related to this PR.

---

but once again, i consider this working, and should be merged ✅

**Comment by ageeye** [comment]
Thanks for the feedback. 

-----

If the App do not start, please start it with lldb:

`lldb FreeCAD.app/Contents/MacOS/freecad`

`r`

The prime suspect is shiboken. In the MacAppBundle CMake copy some libs like numpy to the bundle. But Homebrew do not allow keg_only formula to write the .pth in the lib path. So, the script do not find the dependencies.

**Comment by ipatch** [comment]
@ageeye 

thanks for sharing that. 🙏  next time i run into an app bundle that won't launch ill give this a go.

**Comment by ageeye** [comment]
In the forum looooo wrote, that conda do not use this script. So for my part I, it is possible to merge this PR.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6784">pipeline status</a> for feature branch [PR_6784](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6784). Pipeline [528781363](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/528781363) was triggered at [c79b38a](https://github.com/FreeCAD/FreeCAD/pull/6784/commits/c79b38aedb0c53da313826ea3c7b5f4f2beb1ff1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@donovaly ping

**Pull request merged**
