### PR TITLE
AddonManager: update icons for legibility on dark themes and update icons for WBs

### PR DESCRIPTION
**Pull request by maxwxyz**
Changed only SVGs.

Updated icons for legibility on dark themes and updated WB icons to their recent versions.

Current issue:
307885612-ada78eeb-e715-4af3-8668-27d4ade05d17
322610179-05269e57-bb46-4937-94eb-a6911c4c23bf

Original issue: https://github.com/obelisk79/OpenDark/issues/70

### CODE REVIEW

**Comment by maxwxyz** [comment]
@chennes FYI

**Comment by FEA-eng** [comment]
Nice, but could the Gear wb icon show the gear more from the front and maybe without the keyway to make it more clear? Currently, it's too detailed and poorly visible in its tiny version in the workbenches list.

**Comment by maxwxyz** [comment]
@FEA-eng its the current icon from the external gear WB. If it's changes there we could update it here too.

**Comment by chennes** [comment]
I should note that the Workbench icons included here are fallbacks, and they will be overridden by the icons specified in the WB's package.xml file, if present. I have no problem with updating them, of course, but in the long-term I'd rather not ship with them at all.

**Comment by maxwxyz** [comment]
Yes I know, I noticed these old icons popping up when clicking on refresh local cache. The progress took about 30 seconds and during this time, the old logos were displayed.

**Comment by FEA-eng** [comment]
Issue regarding Gear wb update in its repository: https://github.com/looooo/freecad.gears/issues/165

**Comment by 0penBrain** [comment]
GUI tests in the 22.04 workflow seem to fail since this PR is merged.

**Comment by chennes** [comment]
> GUI tests in the 22.04 workflow seem to fail since this PR is merged.

```
FileQResource: error decompressing zlib content (-3)
```
when trying to read the spdx.json file. Very odd. I can't reproduce locally, and have no idea why this PR would trigger it. @adrianinsaval or @oursland any insight here?

**Comment by 0penBrain** [comment]
This one is also interesting:
```
======================================================================
ERROR: test_content_combination (AddonManagerTest.app.test_metadata.TestMetadataReaderIntegration.test_content_combination)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/AddonManager/AddonManagerTest/app/test_metadata.py", line 623, in test_content_combination
    metadata = MetadataReader.from_file(filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/AddonManager/addonmanager_metadata.py", line 255, in from_file
    return MetadataReader.from_bytes(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/AddonManager/addonmanager_metadata.py", line 261, in from_bytes
    return MetadataReader._process_element_tree(element_tree)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/AddonManager/addonmanager_metadata.py", line 267, in _process_element_tree
    return MetadataReader._create_node(namespace, root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/AddonManager/addonmanager_metadata.py", line 376, in _create_node
    MetadataReader._parse_child_element(namespace, content_child, new_content_item)
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/AddonManager/addonmanager_metadata.py", line 303, in _parse_child_element
    metadata.license.append(MetadataReader._parse_license(child))
              QResource: error decompressing zlib content (-3)
QIODevice::read (QFile, ":/licenses/spdx.json"): device not open
QResource: error decompressing zlib content (-3)
QIODevice::read (QFile, ":/licenses/spdx.json"): device not open
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/AddonManager/addonmanager_metadata.py", line 322, in _parse_license
    lm = get_license_manager()
         ^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
There seems to be a maybe more general issue with zlib decompressing from the compiled Qt resources... :confused:

**Comment by chennes** [comment]
It's not unique to the CI, at least -- I've gotten some reports from people who see it locally. I don't have an explanation yet, though: this PR would have altered the contents of the resource file, but shouldn't have broken it like this. I saw some kind of indication in one of the reports that it might be size-related so I'm looking into that now.

**Pull request merged**
