### PR TITLE
created clang-format

### PR DESCRIPTION
**Pull request by berniev**
My first PR:

This PR is a first step to  achieving consistent code formatting. Currently there are many inconsistencies in FreeCAD codebase.

I propose to implement clang-format which sets out formatting instructions. clang-format is used by many editors/IDE's and is used by many repos. The proposed file is of course just a starting point and can be easily modified to meet community expectations.

Usage is optional (unless enforced by CI), but editors/IDE's using this will no longer have to be afraid of disturbing existing code layout as it can easily be brought back to the community accepted format.

Format can be enforced, if desired, in CI.

Usage is optional, but editors/IDE's using this will no longer have to be afraid of disturbing existing code layout as it can easily be brought back to the community accepted format.

Some discussion in https://forum.freecadweb.org/viewtopic.php?f=10&t=68041

berniev (aka FreddfyFreddy in FC forums)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783">pipeline status</a> for feature branch [PR_6783](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783). Pipeline [522924018](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/522924018) was triggered at [e167b17](https://github.com/FreeCAD/FreeCAD/pull/6783/commits/e167b179007019a7afaad1a48655cfe3054ec705). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783">pipeline status</a> for feature branch [PR_6783](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783). Pipeline [523000228](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/523000228) was triggered at [e167b17](https://github.com/FreeCAD/FreeCAD/pull/6783/commits/e167b179007019a7afaad1a48655cfe3054ec705). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
The latest available version of clang-format for me is v11. This doesn't allow following parameters:
`AlignConsecutiveAssignments: None`, `ContinuationdentWidth: 4` and `BreakeheritanceList: BeforeColon`

`AlignConsecutiveAssignments` is actually supported but its value cannot be set to None. It must be either true or false.
According to the clang-format [documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) `ContinuationdentWidth` has been added with v3.7 and `BreakeheritanceList` with v7 but somehow doesn't work here.

**Comment by berniev** [comment]
Tried stand-alone v14.0.1 (macOS) from homebrew with same format file. No errors or problems reported. What does "doesn't allow" mean?
There certainly appears to be ambiguity in the docs re AlignConsecutiveAssignments.
ContinuationdentWidth -> ContinuationIndentWidth?
BreakeheritanceList -> BreakInheritanceList?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783">pipeline status</a> for feature branch [PR_6783](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783). Pipeline [524410472](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/524410472) was triggered at [853675c](https://github.com/FreeCAD/FreeCAD/pull/6783/commits/853675cd91e8bb1602450a9d5fa974d421fd4ac7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
When running clang-format with this file I get these error messages:
```
Error in Beautifier: /usr/bin/clang-format-11: YAML:4:30: error: invalid boolean
AlignConsecutiveAssignments: 0
                             ^
Error reading /home/user/Projects/FreeCAD/.clang-format: Invalid argument
Error in Beautifier: /usr/bin/clang-format-11: YAML:5:30: error: invalid boolean
AlignConsecutiveAssignments: Consecutive
                             ^~~~~~~~~~~
Error reading /home/user/Projects/FreeCAD/.clang-format: Invalid argument
Error in Beautifier: /usr/bin/clang-format-11: YAML:6:3: error: unexpected scalar
  AlignCompound: false
  ^
YAML:6:3: error: invalid boolean
  AlignCompound: false
  ^
Error reading /home/user/Projects/FreeCAD/.clang-format: Invalid argument
Error in Beautifier: /usr/bin/clang-format-11: YAML:38:24: error: unknown key 'ContinuationdentWidth'
ContinuationdentWidth: 4
                       ^
Error reading /home/user/Projects/FreeCAD/.clang-format: Invalid argument
Error in Beautifier: /usr/bin/clang-format-11: YAML:35:22: error: unknown key 'BreakeheritanceList'
BreakeheritanceList: BeforeColon
                     ^~~~~~~~~~~
Error reading /home/user/Projects/FreeCAD/.clang-format: Invalid argument
Error in Beautifier: /usr/bin/clang-format-11: YAML:5:30: error: invalid boolean
AlignConsecutiveAssignments: None
                             ^~~~
Error reading /home/user/Projects/FreeCAD/.clang-format: Invalid argument
```

**Comment by berniev** [comment]
@wwmayer What was your source file? Was it cpp?

**Comment by wwmayer** [comment]
> What was your source file? Was it cpp?

I have opened any .cpp file and ran the Code Beautifier using clang-format. But because of the apparent incorrect/unsupported keys it didn't touch the source file. Only after fixing the .clang-format file the utility worked and applied the rules on the source file.

**Comment by berniev** [comment]
@wwmayer Is "Code Beautifier" the thing in Visual Studio? Maybe the version there is old or some other issue.
In my case I ran from the command line `clang-format -i -style=file:_clang-format cpp.cpp `
where cpp.cpp is a copy of document.cpp. It ran so fast I wondered if it did anything, so changed the indent setting in clang-format and ran it again. Worked perfectly.

**Comment by berniev** [comment]
@wwmayer Also tested on VSCode with a coupe of indents. Worked fine.

**Comment by wwmayer** [comment]
> Is "Code Beautifier" the thing in Visual Studio?

No, it's QtCreator under Ubuntu. clang-format is not a fix part of this IDE but there is an option to specify the full path to clang-format. This path is set to `/usr/bin/clang-format-11`

When running it from the terminal window I must start it as: `clang-format-11 -i -style=file Document.cpp`
I cannot pass the clang-format file name but the tool expects a file `.clang-format` in this or any parent directory. 

When launching it this way I still get the same error messages.

**Comment by wwmayer** [comment]
On https://apt.llvm.org/ I found a newer version. This is the latest available version I can install: `deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main`

Now using the current .clang-format file is fully accepted by clang-format-13.

**Comment by berniev** [comment]
I didn't modify it! Glad to hear it is now working for you.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783">pipeline status</a> for feature branch [PR_6783](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783). Pipeline [533755661](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/533755661) was triggered at [5f610c5](https://github.com/FreeCAD/FreeCAD/pull/6783/commits/5f610c5837395ebeafddf14d6ff151830ca5e4f0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783">pipeline status</a> for feature branch [PR_6783](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783). Pipeline [534992304](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/534992304) was triggered at [db5a2af](https://github.com/FreeCAD/FreeCAD/pull/6783/commits/db5a2af72b104eb9c643764e8cb2d2dfb146ae7e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783">pipeline status</a> for feature branch [PR_6783](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783). Pipeline [538997273](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/538997273) was triggered at [d46e97e](https://github.com/FreeCAD/FreeCAD/pull/6783/commits/d46e97ef643b2707b926ce8247576ec2cb21afb0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783">pipeline status</a> for feature branch [PR_6783](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6783). Pipeline [545490141](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/545490141) was triggered at [b997132](https://github.com/FreeCAD/FreeCAD/pull/6783/commits/b9971326759d6cc06659a82556e9960de4d164bb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
moved to PR 6918

**Pull request closed without merging**
