### PR TITLE
travis: build freecad with py3

### PR DESCRIPTION
**Pull request by looooo**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/852/commits/a9a34e3a145203eab5c3903358efb14fadd0ab7f?diff=unified#diff-3e3abd32a5c61ba7a5c7283988b9d904R621

You have to be careful with changing this. The unit test runs fine, but all result files of the unit test do not match to the analysis anymore! I will change this and go for a separeate PR in this regard

cheers bernd

**Comment by looooo** [comment]
depends on https://github.com/FreeCAD/FreeCAD/pull/867

**Comment by yorikvanhavre** [comment]
merged

**Comment by sasobadovinac** [comment]
one step closer 👍

**Comment by berndhahnebach** [comment]
congrats, it's just a small PR but a huge step for you looooo. It hopefully makes your work in the regard of py3 a bit easier, since you do not need to change again and again the non py3 in master .... :-)

cheers bernd

**Comment by looooo** [comment]
thanks!
this would not have been possible without the support of all the community members. So thanks to everyone helping with the py3 efforts and everyone involved in this great project!

**Pull request closed without merging**
