### PR TITLE
Python3 path

### PR DESCRIPTION
**Pull request by looooo**
this is all the diff of the python3 branch and master for the path-module. As the path-modul has many python3 incompatibilities and is active development, I would like to integrate the diff of the python3 branch and ask the guys behind this module to port the problems that still exist.

If I would do the porting of all the small incompatibilities, it most likely would lead to many conflicts of the branches which will increase the work to stay updated with the python3 branch. So doing it directly in the master is the better way.

@sliptonic, @yorikvanhavre maybe you can have a look.

### CODE REVIEW

**Comment by luzpaz** [comment]
ref: https://github.com/looooo/FreeCAD/issues/8

**Comment by sliptonic** [comment]
I can't comment on the C++ files but I have no issue with the python stuff.  In fact, I have a branch on my repo that has all the same python 3 style print statements fixed and the same for the rest of the post processors.

**Comment by looooo** [comment]
@sliptonic Does your branch has conflicts with the pr? If so we could leave the python fixes of this pr and only move the c++ changes to master.

**Comment by looooo** [comment]
https://github.com/looooo/FreeCAD/pull/10 I think we should try to get this in, as this is looking very good. This would make your branch @sliptonic redundant. Are you ok with this?

**Pull request merged**
