### PR TITLE
Core: Fix #7580

### LINKED ISSUE #7580: [Regression] Canceling Attachment dialog reverts renaming
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?p=630729#p630729

### Version

0.21 (Development)

### Full version info

```shell
OS: Ubuntu 18.04.6 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.30591 (Git)
Build type: Debug
Branch: master
Hash: 16f688e933eb849222219eac0a27058508b63035
Python 3.6.9, Qt 5.9.5, Coin 4.0.0a, Vtk 7.1.1, OCC 7.3.0
Locale: German/Germany (de_DE)
```
**Note: v0.20 is also affected**

### Issue description

* New document -> Part WB -> Create a Cube
* Select Cube in TreeView
* Change Label in property Editor (let's say "AAA") -> Tab
* Select Map Mode, click the "..." in the value field, cancel Task dialog => OK, Label is "AAA"
* Change Label in property Editor (let's say "BBB") -> Tab
* Select Map Mode, click the "..." in the value field, cancel Task dialog =>  NOK, Label is "AAA"

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fix https://github.com/FreeCAD/FreeCAD/issues/7580
@wwmayer

### CODE REVIEW

**Comment by chennes** [comment]
@wwmayer commented on #7580 -- https://github.com/FreeCAD/FreeCAD/issues/7580#issuecomment-2395597765

@PaddleStroke have you tested that condition?

**Comment by PaddleStroke** [comment]
I didn't get his comment. And I'm not sure its related to this PR actually.

**Comment by PaddleStroke** [comment]
@wwmayer can you please check this PR? It does fix the bug.

**Comment by wwmayer** [comment]
Yes, it fixes the mentioned problem but there are more undo/redo issues in context with the attachment dialog that is a sign for deeper problems. So, fixing the root cause of the problem would make obsolete this PR.

1. Create a part box
2. Open the attachment dialog and click OK
3. Click undo
4. Open the attachment dialog and click Cancel
5. The command from the redo list has been removed and a second command has been added to the undo command

This worked correctly in v0.18 and stopped working correctly since v0.19.

**Comment by wwmayer** [comment]
I have discovered the problem. The call of `document->abortCommand()` does nothing and further down in `TaskDlgAttacher::reject()` the document is recomputed. Because the box is touched it will be recomputed and here the auto-transaction mechanism (that was added with v0.19) jumps in and creates the undo command when it shouldn't.

I have found a proper fix that solves:
* the original problem why `document->hasPendingCommand()` has been added
* https://github.com/FreeCAD/FreeCAD/issues/7580
* the problem described in my previous posting

The needed changes:
```
void TaskDlgAttacher::open()
{
    Gui::Command::openCommand(QT_TRANSLATE_NOOP("Command", "Edit attachment"));
}
```
In `TaskDlgAttacher::accept()` replace `document->commitCommand();` with `Gui::Command::commitCommand();` and
in `TaskDlgAttacher::reject()` replace `document->abortCommand();` with `Gui::Command::abortCommand();`

**Comment by PaddleStroke** [comment]
Thanks. I have updated as you advised.
The commits should be squashed.

**Comment by chennes** [comment]
Backported to 1.0

**Comment by PaddleStroke** [comment]
@wwmayer this generated a regression : 
- Create body
- Create DatumLine
- Click cancel

Expected : Line is removed
What happens : The line is still there.

This is because the `hasPendingCommand` is removed.

What about the solution I offered initially? Use a boolean to store if command is opened here or not.

**Comment by PaddleStroke** [comment]
What about adding a boolean to the ctor like so : 

```
TaskDlgAttacher(Gui::ViewProviderDocumentObject* ViewProvider, bool createBox, bool openCommand = true)

void TaskDlgAttacher::open()
{
    if (openCommand)
         Gui::Command::openCommand(QT_TRANSLATE_NOOP("Command", "Edit attachment"));
}
```

So the Datum commands can call the dialog with this bool = false on creation.

**Comment by PaddleStroke** [comment]
In my current branch about Core Datums I have used this https://github.com/FreeCAD/FreeCAD/pull/16675/commits/eb9d9b35755b69128cdddedb75c2b0b898adbc7d to fix the problem.

This cannot be used directly by the PartDesign datum since they are not creating the task directly but instead set the datum as edit which set the task.
We may want to consider a solution for 1.0 since my PR 16675 is post 1.0

**Comment by wwmayer** [comment]
```
void TaskDlgAttacher::open()
{
    if (!Gui::Command::hasPendingCommand()) {
        Gui::Command::openCommand(QT_TRANSLATE_NOOP("Command", "Edit attachment"));
    }
}
```

**Comment by PaddleStroke** [comment]
The problem is that this would put back the previous issue: cancelling the task attacher would undo the previous property edition transaction. ie it will reinstate #7580. Both issues need the opposite : 
- New datum needs to not open if hasPendingCommand
- 7580 needs to open even if hasPendingCommand

This is why in my solution I added the possibility to ask specifically if it should create a task or not.

**Comment by wwmayer** [comment]
> The problem is that this would put back the previous issue: cancelling the task attacher would undo the previous property edition transaction. ie it will reinstate https://github.com/FreeCAD/FreeCAD/issues/7580

No, it won't. I have tested all these [issues](https://github.com/FreeCAD/FreeCAD/pull/17013#issuecomment-2397787379) and none of them will be back.

**Comment by PaddleStroke** [comment]
Ah good then. Well that's much simpler than the solution I made.

**Pull request merged**
