### PR TITLE
Management of Rotations (direction and angles) 

### PR DESCRIPTION
**Pull request by plgarcia**
See Forum :
https://forum.freecadweb.org/viewtopic.php?t=23563
and
https://forum.freecadweb.org/viewtopic.php?f=10&t=24662

This change keep track and the direction and the angle that has been set by the user, whatever the value of the angle is given. The quaternon is also evalutated for any calcuation based on them.
When seting a Rotation with the quaternion, the angle chosen is the one in ]-180, 180] what is more convienent in most cases than [0, 360[.

This allow to use angles in formulas without modulos,  if -5 * 2 is equivalent to 355 * 2, 
-5 /2 is definitively not the same as 355 /2!

Explanation:
Rotation:
-	Add a private attribute Vector to store the direction of the rotation, and manage not to erase this direction when the angle id 0.
-	Add a private attribute to store the angle as defined (no modulo etc)
-	Keep the quaternion for calculations 

PropertyGeo:
-	Saves the rotation with angle and direction instead of saving the quaternion.
-	Attribute name chosen: Ox, Oy and Oz for the coordinates of the axis and A for the angle in radians. This has to be validated.
-	Backward compatibility with the saved files with quaternion (test presence of A to determine which of  the Quaternion (old way) or the direction and angle is stored (new way). New files can be opened by old FreeCAD and vice-versa.

The only side effect I can imagine is that it was possible to set a vector to 0, 0, 0 if the angle was not 0, what is somehow non sense. Now when setting to 0, 0 0 the last not null vector is kept. The vector can not be null any longer.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0` (see comment)
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by plgarcia** [comment]
Little explanation :
Rotation:
-	Add a private attribute Vector to store the direction of the rotation, and manage it not to erase this direction when the angle id 0.
PropertyGeo
-	Saves the rotation with angle and direction instead of saving the quaternion.
-      Attribute name chosen : Ox, Oy and Ox for the coordinates of the axis and A for the angle in radians.
-	Backward compatibility with the saved files with quaternion (test presence of Q0 to determine which of  the Quaternium (old way) or the direction and angle is stored (new way).

**Comment by plgarcia** [comment]
Little explanation :
Rotation:
-	Add a private attribute Vector to store the direction of the rotation, and manage it not to erase this direction when the angle id 0.
PropertyGeo
-	Saves the rotation with angle and direction instead of saving the quaternion.
-      Attribute name chosen : Ox, Oy and Ox for the coordinates of the axis and A for the angle in radians.
-	Backward compatibility with the saved files with quaternion (test presence of Q0 to determine which of  the Quaternium (old way) or the direction and angle is stored (new way).

The only side effect I can imagine is that it was possible to set a vector to 0, 0, 0 if the angle was not 0. Now when setting to 0, 0 0 the last not null vector is kept. The vector can not be null any longer.

**Comment by plgarcia** [comment]
Today (10/28/2017) all checks were OK, but rebase needed.
No change
rebase on upstream.
cmake -DFREECAD_USE_EXTERNAL_PIVY=1 -DCMAKE_BUILD_TYPE=Release .
make -j2 >resBuild 2>&1
./bin/FreeCAD --run-test 0 >resTest 2>&1

Tests fail : ======================================================================
FAIL: test00 (PathTests.TestPathSetupSheet.TestPathSetupSheet)
Verify SetupSheet templateAttributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pagarcia/FreeCAD/FreeCAD/Mod/Path/PathTests/TestPathSetupSheet.py", line 56, in test00
    self.assertEqual(attrs[PathSetupSheet.Template.HorizRapid], '0.00 mm/s')
AssertionError: u'0,00 mm/s' != '0.00 mm/s'

----------------------------------------------------------------------
Ran 284 tests in 95.305s

FAILED (failures=1)
System exit

This is due to a change pulled on the 10/22/2017. and has noting to see with my change. It is linked to the locale ("," is the décimal separator un French).

So test are OK

**Comment by plgarcia** [comment]
The last change saves both the quaternion and the angle and orientation.
While loading if angle and orientation is available this information is used else the quaternion is used.
This allow to load an old file with the new verssion, a new file with the old implementation (with eventuel direction problem), and then allow to swich from one version to the other at list during a certain period of time for testing.

**Comment by plgarcia** [comment]
Can somebody having write access merge this pull request?

**Comment by plgarcia** [comment]
It seems that the error is due to loss of precision from angle to quaternion:
AssertionError: 0.17453292519943295 != 0.1745329251994329

I will investigate a bit more to be sure what is the exact cause of this error < E-14 degrees!

**Comment by plgarcia** [comment]
Hello,
Here is an example to show the use of the change I propose.

This model uses formulas to calculate to position of the different gears based on the position of the In shaft.
The macro I use simply sets the orientation and angle of the InShaft.
I manage not to set Angles nulls or multiple to 360°, but with the value 720°. If I do that is that I know that such an angle involves resetting the orientation to (0,0,1). 
The first video is recorded with the latest build on FreeCAD on Windows. The problem is the same on Linux with the daily build.
On can observe that the internal representation of the rotation of the In shafs varies from Angle from 0 et 360, back to 180, and then to 360 and the orientation is inverted when angle is going down. This is due to the internal coding of the rotation as a quaternion. When the angle is set to 720 then the axis of the gears is reset in the wrong direction and the behavior of the model becomes absolutely incoherent. This behavior is completely explained but is not the behavior an engineer would have expected when writing the formulas.
https://www.dropbox.com/s/87rapiqqmeiejvp/0.17.12619.avi?dl=0
The second video is done under Linux with the latest git version amended with the pull request I propose. The rotation is internally coded in 2 ways: The quaternion as previously, and angle and axis to keep track of the exact value set. These 2 representations are kept consistent. The rotation C++ object provides the Axis and angle when requested, instead of the Axis and Angle reconstructed from the quaternion. When the quaternion is provided when requested. So there is no impact for the code.
On this video one can see that the gear box runs properly, the orientation is not reset, there is not alteration of the angle. That is the result I expected.
As I run Linux in a Virtual Machine it is a bit slower. Nothing to see with the change I made.
https://www.dropbox.com/s/ujjuwvnmk2o1vv2/0.17.622.amended.avi?dl=0
You can find the model here:
https://www.dropbox.com/s/eaznsq29jy2b85z/gearCompound.FCStd?dl=0
and the macro here:
https://www.dropbox.com/s/j3me5njms0klq89/animGearExampleWithFormulas2.FCMacro?dl=0

As you see this change is quite well tested.
I hope this example is clear enough to explain what I wanted to achieve, and encourage to take advantage of this contribution.
Regards

The Windows version of FreeCAD :
OS: Windows 7
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.12619 (Git)
Build type: Release
Branch: master
Hash: b3631e134be8bfade0534f2dc0ee668ae71a223f
Python version: 2.7.8
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: French/France (fr_FR)


The Linux version of FreeCAD I compiled :
OS: Ubuntu 17.04
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.12622 (Git)
Build type: Release
Branch: master
Hash: 04565d64bc4a182eaa2e804035682d48f8e38e23
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: French/France (fr_FR)

**Comment by DeepSOIC** [comment]
Out of curiosity. Could you check if your PR fixes [issue 3281](https://freecadweb.org/tracker/view.php?id=3281)?

**Comment by plgarcia** [comment]
I believe it solves the problem in your case because the rotation axis is around Y axis. But I am not certain it will not solve the problem in all cases especially with a rotation around an axis different than the initial axis. It really depends on the order the GUI gets the values from the model.
The problem is that the panel is not completely updated with the internal representation (axis and angle) only the angle and the axis is erased by the non-updated value in the GUI.
 I will make some more tests. Follow in the Forum.
https://forum.freecadweb.org/viewtopic.php?f=8&t=25737

**Comment by plgarcia** [comment]
After testing I can say it solves completely the issue 3281.

**Comment by wwmayer** [comment]
Some comments:
1. IMO it's a waste of memory to use three doubles to store the axis direction. One could also simply store the length of the axis and change its sign where needed.

2. When already saving these additional information then it would be good not to normalize the axis. This means when in the property editor the user enters (1,1,1) as axis it should restore this and not change it to (0.57, 0.57, 0.57)

3. This PR does NOT fix issue 3281 at all. When I follow the instructions of the video then the rotation also gets overwritten by the old rotation as soon as the translation vector changes.

**Comment by plgarcia** [comment]
1 - I aggree it is more memory consuming. But when angle is 0 the vector is completely lost. But there is a way I think to optimize this. 3 double by rotaion make 6 double per part, 24Kb for 1000 parts. Are there rotations linked to other objects (faces, segments, points ?)

2 - Not normalizing the vector is a good idea so no confusion for the user.

3 - I made the test with and without the PR and for me the issue 3281 is solved. I will make more tests.

**Comment by plgarcia** [comment]
Sorry I changed my mind for the normalization of the axis. 
Because I do not know all the details of the software, I am not sure some functions do not rely on having a normalized vector. That is why I implemented the PR this way. 
This PR implements a better behavior, and I made some changes to have the vector initialized and not to lose information in all cases. At some point I replaced all commits by one.
I believe the good thing to do is to take the PR as is because it is working, and plan a further optimization and changes.

**Comment by wwmayer** [comment]
> 1 - I aggree it is more memory consuming. But when angle is 0 the vector is completely lost. But there is a way I think to optimize this. 3 double by rotaion make 6 double per part, 24Kb for 1000 parts. Are there rotations linked to other objects (faces, segments, points ?)

OK, that's a valid point. Then we can also leave your PR as is. An alternative might be to store axis and angle instead of the q's but the downside is that the q's always need to be recomputed when needed which causes a loss of performance.

> 2 - Not normalizing the vector is a good idea so no confusion for the user.
Sorry I changed my mind for the normalization of the axis.
Because I do not know all the details of the software, I am not sure some functions do not rely on having a normalized vector. That is why I implemented the PR this way.
This PR implements a better behavior, and I made some changes to have the vector initialized and not to lose information in all cases. At some point I replaced all commits by one.
I believe the good thing to do is to take the PR as is because it is working, and plan a further optimization and changes.

Actually it was never claimed that the returned axis will be normalized and thus client code shouldn't assume it. But nevertheless there is an easy way to avoid any problems: The _axis member should be stored as is and when retrieved via getValue(axis, angle) the reference can be normalized. Then we can have an additional method where we get the axis as is without normalizing it.

**Comment by plgarcia** [comment]
I believe quaternions are used for transformations everywhere and you are probably right when you say that it is a bad idea to remove them for performances.
Do you want me to change and store the _axis as provided? Note nevertheless that is some cases the axis has to be evaluated with quaternions and rotations, and in this case it will be normalized. Should we in this case get the length before update and multiply the produced axis by the operation before storing?

**Comment by plgarcia** [comment]
OK change is made. Just the time to recompile and make some tests. The PR should be ready tomorow.

**Comment by wwmayer** [comment]
> 3 - I made the test with and without the PR and for me the issue 3281 is solved. I will make more tests.

As said above this PR doesn't fix issue 3281. When testing the issue it's important not to de-select the object after using the axis cross for rotation because then internal values are set correctly and the whole test is useless.

The issue is caused by the implementation of PropertyPlacementItem::assignProperty which computes the cross product of the internally stored axis and that of the rotation. If the cross product is the null vector then the two axes are parallel but they can still have different orientation. So, it's not enough to only check for the length of the cross product but also the dot product must be checked and if this is negative the internally stored axis must be flipped.

**Comment by plgarcia** [comment]
yes you are right.

**Comment by plgarcia** [comment]
Templates do not do not take the un-normalized axis! so a difference is detected during tests.
I do not know anything arround templates so I have to analyse to uderstand what to do.

**Comment by plgarcia** [comment]
OK I know what to do. Just the time to rebuild and test.

**Comment by plgarcia** [comment]
OK the problem is solved. The templates were only built with quaternion. Now they can be made still with quaternion but also with axis and angle with, if both defined a priority the the axis and angle definition.

**Comment by plgarcia** [comment]
Note that even if I defined the function :
    void getValueNormalized(Vector3d & axis, double & rfAngle) const;

It is not used yet, and there is no capability defined to use it in python.

**Comment by wwmayer** [comment]
> Note that even if I defined the function :
void getValueNormalized(Vector3d & axis, double & rfAngle) const;

I rather meant the opposite: make sure that getValue(Vector&, double) normalizes the axis and then offer a second method which returns the axis as is. This is to avoid to change behaviour and because in the  Path module there is indeed assumed that the length is 1 and now the unit tests fail because of this. 

For now I merged your first and second commit and reworked the third one.

**Comment by plgarcia** [comment]
When I tested I must say that is quite peasent to find the values in the GUI. 1 1 1 is still 1 1 1.
A future evolution of the gui I beleive.

Thanks for having taken the time for that!

**Pull request closed without merging**
