### PR TITLE
Part 2D offset

### PR DESCRIPTION
**Pull request by DeepSOIC**
New feature of Part workbench: 2D offset.
2D offset offsets planar wires. It is powered by OCC's BRepOffsetAPI_MakeOffset.
Main capabilities:
* offsetting open and closed wires. Two offsetting modes for open wires: pipe and skin. 
* supports compounds. Two ways of treatment: independent or collective, controlled by 'Intersection' checkbox/property. On the screenshot, collective offset mode is presented.
* partial support for filling offset

Planned for future (not implemented yet):
* offsetting planar faces
* fill offset support for collective offset of compounds of wires

Py method Part.Wire.makeOffset was upgraded to support the same parameters as the feature does, and moved to become a member of Part.Shape (because it now applies to not only wires, but also compounds, and planned to support faces).

offset-collective

Forum threads:
[Make Part Offset support wires](http://forum.freecadweb.org/viewtopic.php?f=8&t=17174)

### CODE REVIEW

**Comment by DeepSOIC** [comment]
I just noticed there is another Py routine I didn't notice: Part.Face.makeOffset. This needs to be discussed...

**Comment by DeepSOIC** [comment]
Changed to new independent Part.Shape.makeOffset2D. Leaving old Wire.makeOffset and Face.makeOffset intact (marked Wire.makeOffset deprecated).

**Comment by wwmayer** [comment]
Merged.

**Comment by DeepSOIC** [comment]
Thanks!

**Pull request closed without merging**
