### PR TITLE
BIM: Fixed lock-unlock mode when opening IFC files

### LINKED ISSUE #18192: BIM: Opening IFC file as Unlocked opens in Strict IFC mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

- Open FreeCAD
- File -> Open -> Select any IFC file
- Select 'Unlocked' in the 'Lock Document' Option
- File opens in strict IFC mode. No non-IFC objects can be created until strict IFC mode is turned off

See behavior in the video:

https://github.com/user-attachments/assets/eb72ea45-c830-4bc5-93d0-1e5fce02e420

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

BIM

### Anything else?

I was able to reproduce with 

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39315 (Git) Conda
Build type: Release
Branch: main
Hash: 710542d121c2cabce05561591cfb00ef3b6e745c
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yorikvanhavre**
Fixes #18192

### CODE REVIEW

**Comment by luzpaz** [comment]
@semhustej any chance you can test this?

**Comment by semhustej** [comment]
> @semhustej any chance you can test this?

I can do that, but only once the weekly build with this commit is released. I am not able to build FreeCAD myself.

**Comment by yorikvanhavre** [comment]
Well it's merged already :) Please test once the weekly build is out!

**Comment by semhustej** [comment]
Tested with weekly release. Works fine on my side.
```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39503 (Git) Conda
Build type: Release
Branch: main
Hash: da45328f6f9b35cbbdc7167d7faadb6a07634bdb
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion

```

**Pull request merged**
