### PR TITLE
CAM: Fix creating Helix on Prototype, #17871

### PR DESCRIPTION
**Pull request by jbaehr**
For the "Op Defaults" from the setup sheet the operations get created with a `OpPrototype` instead of a real document object. This prototype provides only a small subset of FreeCAD's document object API. When a new Job is created via the GUI, each registered operation is created with such a dummy to populate the setup sheet panel. And if such an operation uses document APIs not provided by the prototype, the entire job creation fails, see #17871.
Unfortunately we don't have tests for the GUI part, where all the operations are registered and thus the integration with all of them could be verified, thus I just created a local test for the helix, where the actual issue was reported -- this can be verified with headlessly.

### CODE REVIEW

**Comment by jbaehr** [comment]
Yikes --  it looks the pre-commit hook went wild and committed tons of white-space changes in the translation files. This should not be part of this PR!

**Comment by jbaehr** [comment]
@yorikvanhavre it looks like the pre-commit hook did not run on your latest translation update, commit 5b00d7f1f23c844be8c82ed5d05826b7695f53db. Would you mind running it again (or cherry-picking its commit 55d898bb132b8cae2bc6b9cf0cb0223ce300eaba from here) -- right now my very tiny, and completely unrelated,  changes are barely visible. I'm then happy to rebase.

**Comment by maxwxyz** [comment]
@chennes @sliptonic is this to be backported for 1.0 prior to the release?

**Comment by maxwxyz** [comment]
@adrianinsaval also heads up if this needs to be in 1.0

**Comment by maxwxyz** [comment]
also this PR is against the 1.0 branch, not main

**Comment by jbaehr** [comment]
> also this PR is against the 1.0 branch, not main

Yes, it fixes #17871 -- the current 1.0rc4 pretty much useless for CAM: without this fix here you can work on existing CAM projects, but you cannot create new ones. I think it's critical.

I'll pull this commit into #17826 for the main line.

**Comment by sliptonic** [comment]
LGTM.

**Pull request closed without merging**
