### PR TITLE
Cmake - Windows: Copy depend dirs from libpack to build

### PR DESCRIPTION
**Pull request by Russ4262**
Changes targeted at copying dependency folders from libpack used to the build folder.  Changes only affect Windows builds per included IF(MSVC) tests.  These changes will make the Windows experience a little more pleasant.
Forum discussion at: [Windows Builders: Cmake build improvements](https://forum.freecadweb.org/viewtopic.php?f=4&t=36225)

Please review.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by Russ4262** [comment]
Needs review and feedback from FC developers and users. Any help testing via the CMake-Gui would be nice... @sgrogan … if you have time over the next few weeks.

**Comment by sgrogan** [comment]
> @sgrogan … if you have time over the next few weeks.

Sure, it looks like you have some extra stuff in the pull request?

**Comment by Russ4262** [comment]
@sgrogan
I don't know how to get the other commits removed.  Any help would be greatly appreciated!

**Comment by Russ4262** [comment]
@sgrogan 
Are you available on Gitter.im?

**Comment by Russ4262** [comment]
@sgrogan, @mlampert 
Do I need to delete my FreeCAD repo and re-fork a fresh repo?

**Comment by mlampert** [comment]
no - you just pull the latest master from freecad and create a new branch from there.

**Comment by Russ4262** [comment]
@mlampert 
> no - you just pull the latest master from freecad and create a new branch from there.

Okay. So, 
1.) delete this PR
2.) rebase my repo with master
3.) create new branch on my fork
4.) redo current cmakelist.txt changes in the new branch
5.) make new PR with that branch
?

**Comment by Russ4262** [comment]
Please HOLD this PR.  I plan to make use of some schooling by @mlampert to clean up the commits list.  I'll just post a new PR with the same changes.  So, I'll leave this for inspection until I get the new PR ready.

**Pull request closed without merging**
