### PR TITLE
[PATH] Fix bug with job object not found.

### PR DESCRIPTION
**Pull request by sliptonic**
fixes bug with PathSanity not finding job object.
https://forum.freecadweb.org/viewtopic.php?f=15&t=62533

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5076">pipeline status</a> for feature branch [PR_5076](https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5076). Pipeline [#379749837 ](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/379749837) was triggered at [c21f7ab](https://github.com/FreeCAD/FreeCAD/pull/5076/commits/c21f7ab023da87e0839bf63d8ea151c83dd3dcfc). All CI branch [pipelines](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches).

**Comment by snelweg** [comment]
I made the changes by hand in `PathSanity.py` on a fresh checkout of LinkStage3, same problems.

```
OS: Debian GNU/Linux 11 (bullseye) (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.28516 (Git)
Build type: Unknown
Branch: LinkDaily
Hash: 122b39003e4e75cf00f7b4f7cbd5a6fbff0ca023
Python version: 3.9.2
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.1
Locale: English/United States (en_US)
```

Report view:```

09:30:39  Feeds and Speeds Addon loaded: PathWorkbench
09:31:01  tool props: 2.9 mm 1 HSS 0.01 mm
09:31:01  material Softwood
09:31:01  found ss: 225
09:31:17  material Hard Plastics
09:31:17  found ss: 225
09:32:40  PathJobGui.INFO: Expected a specific object to edit - Job-boven-gaten not recognized
09:32:40  <Path.Area> PathUtils.py(314)|Area.cpp(1438): hit bottom -0,0,1e-06
09:32:40  <Path.Area> PathAreaOp.py(206)|Area.cpp(1438): hit bottom 0,0,1e-06
09:32:41  PathDressupHoldingTags.INFO: Tag #0 (-221.49, 240.56, 0.00) not on base wire - disabling
```

**Comment by sliptonic** [comment]
> I made the changes by hand in `PathSanity.py` on a fresh checkout of LinkStage3, same problems.
> 
The error shown isn't the issue resolved by this patch.  
In fact the log doesn't make sense.  The Path.Area messages usually mean there's something wrong with the depth settings on an operation.
There's an INFO coming from a holding tag dressup but you don't have a dressup in the attached file.
I tried running the PathSanity on your file and I got a valid report.  I had to change your toolbit shape file path on my machine but otherwise it generated as expected.



> ```
> OS: Debian GNU/Linux 11 (bullseye) (XFCE/xfce)
> Word size of OS: 64-bit
> Word size of FreeCAD: 64-bit
> Version: 0.19.28516 (Git)
> Build type: Unknown
> Branch: LinkDaily
> Hash: 122b39003e4e75cf00f7b4f7cbd5a6fbff0ca023
> Python version: 3.9.2
> Qt version: 5.15.2
> Coin version: 4.0.0
> OCC version: 7.5.1
> Locale: English/United States (en_US)
> ```
> 
> Report view:
> 
> ```
> 09:30:39  Feeds and Speeds Addon loaded: PathWorkbench
> 09:31:01  tool props: 2.9 mm 1 HSS 0.01 mm
> 09:31:01  material Softwood
> 09:31:01  found ss: 225
> 09:31:17  material Hard Plastics
> 09:31:17  found ss: 225
> 09:32:40  PathJobGui.INFO: Expected a specific object to edit - Job-boven-gaten not recognized
> 09:32:40  <Path.Area> PathUtils.py(314)|Area.cpp(1438): hit bottom -0,0,1e-06
> 09:32:40  <Path.Area> PathAreaOp.py(206)|Area.cpp(1438): hit bottom 0,0,1e-06
> 09:32:41  PathDressupHoldingTags.INFO: Tag #0 (-221.49, 240.56, 0.00) not on base wire - disabling
> ```
> 
> [outlets.zip](https://github.com/FreeCAD/FreeCAD/files/7257598/outlets.zip)

**Comment by snelweg** [comment]
> The error shown isn't the issue resolved by this patch. In fact the log doesn't make sense. The Path.Area messages usually mean there's something wrong with the depth settings on an operation. There's an INFO coming from a holding tag dressup but you don't have a dressup in the attached file. I tried running the PathSanity on your file and I got a valid report. I had to change your toolbit shape file path on my machine but otherwise it generated as expected.


I kinda suspected the shape file to be the culprit. It is very hard to use Windows and Linux machines to develop designs. The relative paths are not that relative, so a shared setup for the toolbits is not possible. I often get the error that shape files are not found.

**Pull request merged**
