### PR TITLE
[TD]Non-continuous Lines to Standards

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a solution to issue #9230.

Additional forum discussion: https://forum.freecad.org/viewtopic.php?t=82287&sid=88b288b1c46dd306928bbd46dc2eff4f
and
https://forum.freecad.org/viewtopic.php?t=81918

### CODE REVIEW

**Comment by maxwxyz** [comment]
@WandererFan not sure if this is related to this PR but I've noticed it on yesterday's weekly build on another computer: The drop down menu in the Preferences>Annotation>Lines for `Line standard` is empty and cannot be opened:
grafik
When I reset the preferences of the annotation tab the drop down menu with the new line styles is visible. So maybe old users with an existing config file cannot set the new styles?

After reset of annotation tab:
grafik

**Comment by WandererFan** [comment]
I can't duplicate this with FreeCAD_weekly-builds-35554-2024-01-08-conda-Linux-x86_64-py310.AppImage.

The code looks for available standards in one of two places:
Tools > Edit parameters
TechDraw / Files / LineDefLocation 

or

App.getResourceDir()/Mod/TechDraw/LineGroup/

If there is a LineDefLocation preference value that points to a directory with no line definition files,  that would give the empty drop down box.  It might be a value that AppImage can not access?

If you can make this happen again, please note the value of that preference and the result of 
"App.getResourceDir()".   That might give us a clue.

**Comment by maxwxyz** [comment]
I cannot reproduce as well, seemed that I had an older weekly build on the system and when I downloaded the current weekly this setting was empty. I tried to set it with 0.21 to ISO and apply the settings but the new weekly is working now.

**Comment by maxwxyz** [comment]
fresh user.cfg solved the issues!

**Pull request merged**
