### PR TITLE
[Base] fix issues with new units

### PR DESCRIPTION
**Pull request by donovaly**
- also sort units for better overview

### CODE REVIEW

**Comment by chennes** [comment]
Are these changes really all related to the new units? It seems like a lot of conditionals changing here.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789365278](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789365278) was triggered at [f581b59](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/f581b59974f03f7c68a215a0c94c284c720ff58b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789366543](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789366543) was triggered at [9a350f2](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/9a350f2f47885a5205c2a6b213eb41e8dc28f0bf). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> Are these changes really all related to the new units? It seems like a lot of conditionals changing here.

What do you mean? The new units are the inverse. I fixed its logic and the unit bugs.
For the length I used scientific notation and I sorted.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789367629](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789367629) was triggered at [89b3727](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/89b372781cfcd4c6e4c7317cb50b0ef5dc2cbe7a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789370270](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789370270) was triggered at [d6aab78](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/d6aab785f4defed1270d523b787c2f1b2f49e4fc). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789372339](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789372339) was triggered at [94f1015](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/94f101566d0efa86e48e0c4d221d63c3f69ac340). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789373663](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789373663) was triggered at [4da3e7b](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/4da3e7bb1e9657da3c83a4ad96c1673d0caa7ca9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789374927](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789374927) was triggered at [ea4a881](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/ea4a8814fa9574190bba66f206c1024cbd8007a7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789382766](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789382766) was triggered at [e8dff1f](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/e8dff1f8545973794d3de054762915adba183cea). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Ah, I saw now my logic mistake. Now it should be correct

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789383931](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789383931) was triggered at [f558ca8](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/f558ca8aa4168f49c976e233c93a43ae78ac92a1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678">pipeline status</a> for feature branch [PR_8678](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8678). Pipeline [789385418](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789385418) was triggered at [ce8e321](https://github.com/FreeCAD/FreeCAD/pull/8678/commits/ce8e3214d37968d59d6ac447ee01cd562dfae92a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
