### PR TITLE
TechDraw: Complete remake of drawing dimensions

### PR DESCRIPTION
**Pull request by pavltom**
Hello,

I have finished the remake of the dimension drawing. For the detailed description, please see the dedicated forum topic 

https://forum.freecadweb.org/viewtopic.php?f=35&t=39571

### CODE REVIEW

**Comment by WandererFan** [comment]
The changes to Base::Tool2d are additions, right?  Everything that was there works the same as before?

**Comment by WandererFan** [comment]
Two thoughts from an old maintenance programmer...

If you're changing functions in the core,  make a separate PR for them to keep them separate from the application code.

Try to resist the urge to make style changes . It doesn't really apply to us, but in theory every thing you touch should go through the QA process, even if it is just changing odd variable names to something sensible or inserting/removing spaces or moving code within the file(s).

**Comment by pavltom** [comment]
Hi! Yes in the Base/Tools2d there were only new methods and operators added plus few existing modifying methods had return type changed from "void" to "Vector2d &" returning now "*this". Anyway I made the changes always with respect to the code using them, never changing the functionality. If You would like, I can create a list with some comments... But OMG, changing the Base/* files is a great pain! Everytime practically all code has to be rebuilt :-/

As for Your suggestions:
1) OK, next time if any Base* change is required, I will deliver it separately.
2) Well, the code there looked like from ancient times, so if I had to touch it anyway, I tried to give it more modern form. Nevertheless, if minimal changes are what's preferred, I have no objections. Next time I will honor that rule.

**Comment by berndhahnebach** [comment]
> If you're changing functions in the core, make a separate PR for them to keep them separate from the application code.
+1 from my side. This is a very important workflow IMHO! If the PR title is TechDraw I would assume it is only TechDraw related (same as I make one for FEM). If I personaly would like to change or add something to the core I would never just merge it into master. Base stuff should be reviewed anytime from more than just the module maintainer and thus go into a separate PR.

cheers bernd

**Comment by berndhahnebach** [comment]
In minimum changes in Base should be a separate commit. IMHO. It is quite easy to separate this from each other in git and makes finding problems in Base later on much easier.

**Comment by WandererFan** [comment]
Travis failure in gcc/py2 build.  Not related to this PR?

CMakeFiles/Robot.dir/Robot6Axis.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
src/Mod/Robot/App/CMakeFiles/Robot.dir/build.make:1262: recipe for target 'Mod/Robot/Robot.so' failed
make[2]: *** [Mod/Robot/Robot.so] Error 1
CMakeFiles/Makefile2:2978: recipe for target 'src/Mod/Robot/App/CMakeFiles/Robot.dir/all' failed
make[1]: *** [src/Mod/Robot/App/CMakeFiles/Robot.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by berndhahnebach** [comment]
FYI. ATM, Master is failing for the same reason.

**Comment by wwmayer** [comment]
Are the changes made to TD okay for you? If yes I will merge this PR but move the changes made to Tools2d to a separate commit.

**Comment by pavltom** [comment]
No problem with that. As I've said, should there be any Base changes next time, I will split it into 2 separate PRs.

**Comment by WandererFan** [comment]
Yes, the TD changes look very good.  Please merge as 2 commits.  
Thanks.

**Comment by pavltom** [comment]
Now I am a bit confused - shall I close this PR and create 2 separate ones? Or remove the Base2D changes from this PR, create separate Base2D PR, let first merge Base2D and then this one?

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
