### PR TITLE
Fem: fix Gmsh analysis mesh groups - fixes #17427

### LINKED ISSUE #17427: FEM: Regression: Freeze at 100% CPU when searching mesh for solid
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When doing FEM with more than one material, it is necessary to assign materials to solids. 

If Materials are assigned to solids, these are being searched in the mesh

on the console this is printed:

```
Check prerequisites...

Get mesh data for constraints, materials and element geometry...
Materials
Constraint: MaterialSolid --> We're going to search in the mesh for the element ID's.
    ReferenceShape ... Type: Solid, Object name: Compound007, Object label: Compound007, Element name: Solid21

```

Then FreeCAD just sits there with 100% CPU load on all cores and nothing happens...

### Full version info

```shell
OS: Ubuntu 20.04.6 LTS (XFCE/xfce/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git)
Build type: Debug
Branch: debugTolerance
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * CurvedShapes 1.0.12
  * CfdOF 1.27.10
  * Curves 0.6.48
  * AirPlaneDesign 0.4.1

GMSH:
Version       : 4.14.0-git-efbef2df5
License       : GNU General Public License
Build OS      : Linux64
Build date    : 20241004
Build host    : frg03
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blossom Cairo DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack LinuxJoystick MathEx[contrib] Mesh Metis[contrib] Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] Untangle Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.3.4
OCC version   : 7.6.3
Packaged by   : eprice
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
```

### Subproject(s) affected?

FEM

### Anything else?

What other info do you need?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marioalexis84**
@FEA-eng

### CODE REVIEW

**Comment by maxwxyz** [comment]
@AIRCAP could you test if this fixes your issue?

**Comment by FEA-eng** [comment]
With this fix and mesh groups enabled, writing input file takes much shorter but I get some error related to force constraint:

```
20:48:15  Check prerequisites...
20:48:15  
20:48:15  Get mesh data for constraints, materials and element geometry...
20:48:15  Materials
20:48:15  Constraint: MaterialSolid --> We have mesh groups. We will search for appropriate group data.
20:48:15    found mesh group for the IDs: MaterialSolid_Volumes, Type: Volume
20:48:15  Constraint: MaterialSolid001 --> We have mesh groups. We will search for appropriate group data.
20:48:15    found mesh group for the IDs: MaterialSolid001_Volumes, Type: Volume
20:48:15  Count finite elements as sum of constraints:   92021
20:48:15  Count finite elements of the finite element mesh: 92021
20:48:15  True
20:48:15  ConstraintFixed:
20:48:15      Type: Fem::ConstraintFixed, Name: ConstraintFixed
20:48:15    found mesh group for the IDs: ConstraintFixed_Nodes, Type: Node
20:48:15  ConstraintForce:
20:48:15      Type: Fem::ConstraintForce, Name: ConstraintForce
20:48:15      ReferenceShape ... Type: Face, Object name: Unnamed1, Object label: Compound, Element name: Face13
20:48:15  Error on: ConstraintForce --> Unnamed1.Face13
20:48:15    sum_node_areas: 103605.8924151049
20:48:15    ref_face_area:  135533.48756206635
20:48:15  Deviation sum_node_load to frc_obj.Force is more than 1% :  0.7644302104131971
20:48:15    sum_ref_face_node_area: 103605.8924151049
20:48:15    sum_ref_face_area:      135533.48756206635
20:48:15    sum_node_load:          76.44302104131971
20:48:15    frc_obj.Force:          100.0
20:48:15    the reason could be simply a circle area --> see method get_ref_face_node_areas
20:48:15    the reason could also be a problem in retrieving the ref_face_node_area
20:48:15  Getting mesh data time: 126.726 seconds.
20:48:15  
20:48:15  CalculiX solver input writing...
20:48:15  Input file:/tmp/fcfem_l9xj4h4v/FEMMeshGmsh.inp
20:48:15  One monster input file.
20:48:15  Writing time CalculiX input file: 2.086 seconds.
20:48:43  editCalculixInputFile /tmp/fcfem_l9xj4h4v/FEMMeshGmsh.inp
```

```
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39098 (Git)
Build type: Unknown
Branch: fem-gmsh_groups
Hash: 5c9e5343ce741953876a272208de5c769bddb100
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * OpenDark 2024.3.13

```

**Comment by marioalexis84** [comment]
This commit re-enables the use of groups for elements within the analysis.
It is not related to possible later problems due to the handling of items within the analysis (constraint, materials) or how efficient the algorithm is that searches for nodes/elements in shapes.
I have tested the shared project in versions of FreeCAD prior to the modifications in the Gmsh task panel and I get the same error for the force constraint. Do you have any version of FreeCAD for which the error does not occur?

In any case, #17427  should be split into two. One issue to reinstate the use of groups (solved by this commit) and another issue to request an improvement of the algorithm that searches for mesh elements in Part shapes.

**Comment by AIRCAP** [comment]
I think the force constraint issue is a known issue that depends on the shape. if you apply a force constraint not on a point but on a face, then the area of that face needs to match the area covered by the corresponding mesh. for some reason this is not the case if the face is a nurbs surface and/or bounded by curved (circular) or bspline edges.  it does work if its just a flat face covered constrained by straight edges (side of a cube for example)

workaround: apply forces to vertices instead of spreading them out over an area

**Comment by AIRCAP** [comment]
confirmed fixed - works beautifully.

image


@marioalexis84 I think your commit https://github.com/FreeCAD/FreeCAD/commit/cabfbb749fdf5ad822c690a095e62388d9395a2d introduced another "regression" - when you create the mesh, there is a lot less information printed - it just says "success" if the mesher succeeded somehow, mesher warnings are no longer printed. is that on purpose? (typically when th mesh has negative jacobians thats already reported by gmsh as a warning)

**Comment by AIRCAP** [comment]
if its not on purpose, would it be possible to bring the gmsh output back?

**Comment by marioalexis84** [comment]
It's not on purpose. I'll try to have it corrected in the next few days.

**Comment by AIRCAP** [comment]
> It's not on purpose. I'll try to have it corrected in the next few days.

I opened a new issue for that so this one can be merged independently, since blocker and all such.

**Comment by AIRCAP** [comment]
note: the CI error is conda acting up on mac again after all tests have pass successfully  - PR is good for merge IMHO

**Comment by FEA-eng** [comment]
@chennes Can you merge it? This PR fixes an important regression (blocker) and we need it to look for more related issues.

**Comment by chennes** [comment]
Backported

**Comment by FEA-eng** [comment]
@marioalexis84 Don't you think that it would be also good to enable mesh groups by default to avoid such issues? Unless there are any other problems this could potentially cause. For example, it should be independent of pressure load's application to shells now, right?

**Comment by marioalexis84** [comment]
We can do a review and confirm that there are no problems, then set it as default.

My idea is to work only with groups in the future, especially considering that the new Netgen implementation allows working with groups (it is not implemented yet). But first my intention is to make some changes to use SMESH functions for group manipulation and filtering.
Currently, some functions (getNodesBy{Edge,Face,Solid}) are used to find nodes in shapes, but this represents a performance penalty and can be very time consuming.

**Pull request merged**
