### PR TITLE
[Sketcher] Constraint visuals - HDPI

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
This is a proposal based on:
https://github.com/FreeCAD/FreeCAD/pull/4155
https://github.com/FreeCAD/FreeCAD/pull/4146

I have done my best to preserve the ownership of the work.

PR #4155 proposes a scaling factor to be used to scale up constraint icons and the subindex font of icons. The
scaling factor is a parameter.

PR #4146 proposes to derive the constraint icon size from the system font size via function of the dpi. The
constraint icon subindex is a factor of the constraint size.

Observations:
- PR #4146 identifies the need for a scaling factor too, but this is a hardcoded 1.25 factor.
- PR #4146 appears to mix font points and font pixels when deriving the sizes.
- PR #4155 deals exclusively with icon size and subindex font, not with constraint label

Useful concepts:
- Font point is a physical distance. There are 72 points in one inch.
- Monitors have pixels with varying pixel densities. The number of pixels in one point varies
with pixel density. Hence the need for a correction based on the dpi of the monitor.

API constraints:
- While QT's configuration can be obtained in points or pixels, coin3D sets the font size in points.

Solution:
- Stop relying on the local font setting from preferences.
- Introduce a sketcher wide 3D view scaling factor, as per #4155, but relative to the system font size as per #4146.
- Derive the 3D view font size from the system font size by applying the scaling factor (while taking into account the dpi). The
font size of QT is the same as the font size of the 3D view if the scaling factor is 1.0 .
- Derive the 3D view icon size to be the same size as the 3D view font size.
- The constraint icon subindex, being a special case of font relative to the accompanying icon, is set to be the 80% of the
icon size (hardcoded). I think it is not worth to provide this as a configurable parameter.

### CODE REVIEW

**Comment by chennes** [comment]
Is it possible to make the setting apply to the current open sketch when you click "Apply" in the preferences? Also, I note that there are some things that are not scaled by the scale factor: vertex size and line widths are not affected. Is this intentional?

**Comment by abdullahtahiriyo** [comment]
@chennes 

Vertex size:
The vertex size is regulated by "Marker Size" in general FreeCAD preferences, in pixels. The fact that this setting is in pixels is a problem, because its size is device dependent (density of pixels of monitor). Other workbenches use this marker size as well (find a list in the thread where this is discussed in the forum). So: a) I would rather not change a global preference setting that affect other workbenches one month before release, b) I would rather have  a global solution instead of making marker size just custom to the Sketcher (and at the same time ignoring a global parameter), c) I am not sure marker size would affect the selection mechanism (but this is my limitation, not a technical reason, I would have to investigate it).

I am open to ideas though (you may read an in the middle idea in the forum thread).

Line width:
This was simply not part of the original proposals, but indeed it can be added. As far as I have seen, HDPI monitors have between 1x and 2x of normal monitors, so it may lead to 2 pixel thin lines instead of 1 pixel thin lines, which may make a difference. There are a lot of hardcoded sizes (take a look to ViewProviderSketch::createEditInventorNodes if you are curious).

Settings apply without reentering edit node:
I am unaware if it is possible to subscribe via a signal to the apply button (would need to take a look for that). In the current version exiting edit mode and reentering suffices (as opposed to previous versions that would require to close FreeCAD). 

Connected in line of thought to that question is whether these parameters should be cached or not. There was a comment about what would happen if somebody moves the window to another monitor having a different pixel density. I have left the caching version for the moment, but I think it is a valid case.

About caching, when look at the marker size this morning, I saw that the marker size is cached in the edit structure, as opposed to in the ViewProviderSketch object. I wonder if it would then be appropriate to move the coinfontsize and iconsize members to the edit structure for coherence.

Please, let me know your impressions. I am not too much into these visualisation things. We could also merge something reasonable now and further develop the rest. I am open to any ideas...

**Comment by chennes** [comment]
> I am unaware if it is possible to subscribe via a signal to the apply button
I think it's really the preference item itself you need to add an observer for, my understanding is that what Apply does is commit the UI changes to the under-the-hood preferences storage.

> We could also merge something reasonable now and further develop the rest.
FWIW, I think that's a good path forward. This PR looks like an improvement to me: I compiled and tested on a multi-monitor Windows HiDPI setup and it worked well. I can try a few different setups later today at work.

**Comment by abdullahtahiriyo** [comment]
@chennes 

I did not know parameters implemented the observer pattern. That is a cool thing to know.

Following your request, I have added the scaling of basically all remaining sizes in pixels by the scaling factor. The scaling factor is the product of the dpi ratio with respect to the standard 96 dpi and the view scaling ratio from preferences.

I appreciate you give it a run in HDPI monitors. I run a 96 dpi environment, so testing is not optimal.

I am not sure about the default font size, so I am starting to side with Chrisb, that maybe it makes sense to have an extra box for font size, as it was before.  I would appreciate if you comment on the forum about what you think rather than GitHub. The community lives in the forum and it is great to have extra input.

**Comment by abdullahtahiriyo** [comment]
@chennes 

Ah! I wanted to comment on the Vertex. If you look at the code I even made some changes to scale vertex markers too. However, I have realised that if a user changes the marker size taking into account other WBs and the Sketcher implements its own scaling, at the end the Sketcher will have a double correction, which should be undesirable. So, marker size is not corrected by this PR.

**Pull request closed without merging**
