### PR TITLE
Draft: importSVG, removed bad code introduced accidentally by 2a139a89, and partially fixed by 537a011a

### PR DESCRIPTION
**Pull request by vocx-fc**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists
---

Commit 2a139a89 accidentally introduced badly merged code that produced syntax errors; then 537a011a tried to fix it by removing the syntax errors; however a large block of code needs to be removed as well because it is actually repeated; this was supposed to happen in pull request #2418; however, since 537a011a was committed first, that pull request no longer merges cleanly so it was withdrawn; this commit finally fixes the problem.

See the forum thread [explaining what happened originally](https://forum.freecadweb.org/viewtopic.php?p=326312#p326312).

### CODE REVIEW

**Comment by luzpaz** [comment]
@vocx-fc this PR adds https://github.com/FreeCAD/FreeCAD/pull/2424/files#diff-b8c788167956562e44b1de9aeb0aacf0R746-R752
Why? I thought it was intended to just remove the code introduced in 2a139a8 ?

**Comment by vocx-fc** [comment]
Yes; those lines are part of the original code. Nothing is being actually added. That's just how the diff looks like. Compare it with 3e11cc5, which is the last working version.

**Comment by vocx-fc** [comment]
Paging @Syres916. Just a heads up, with the current master branch importing of SVG doesn't work with files not created by Inkscape. This pull request solves the issue, returning the code to the good state of 3e11cc5, which you said worked in PR #2393.

Also paging @yorikvanhavre. Without this commit, ``importSVG`` is broken for import.

**Comment by yorikvanhavre** [comment]
Thanks for fixing! Sorry for the mess!

**Comment by vocx-fc** [comment]
Thanks Yorik. May God pay you with many children. Sorry for submitting so many request!

**Pull request merged**
