### PR TITLE
[FEM] enable to run Elmer multi-threaded

### PR DESCRIPTION
**Pull request by donovaly**
- this needs proper testing, especially on a non-Windows system

- note that for some tasks multi-threading requires non-standard additional solvers like MUMPS. Ideally the user should be informed about this, depending on the equations he uses. But this should not block this PR, meaning to use multi-threading in general.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [584407553](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584407553) was triggered at [829f268](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/829f268a0f68e54b51bf704c646681bc3551697b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [584413790](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584413790) was triggered at [a1fddc9](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/a1fddc98b83948d1ce29586e1911f4fb480899f5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [584448610](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584448610) was triggered at [742a3ce](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/742a3ceb4f079f6ad8285262db62c6bf20348f5c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [584472228](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584472228) was triggered at [1acba39](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/1acba39bb1641da73c65a46f14a79bb26ecac8c3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [584477853](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584477853) was triggered at [994dd99](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/994dd993ab035aa712b9c77ea7fb69a3976fcd3e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Works now as expected

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [584501130](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584501130) was triggered at [9e0ca46](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/9e0ca46a863cbfba2ee2396418de750f5e7cc204). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [584501596](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584501596) was triggered at [bace42b](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/bace42b5e3dfbd0d9b0b2aec061926589e94875f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [585272117](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/585272117) was triggered at [09f9c10](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/09f9c106cda0b073e305f04ed02fc667bb9bef1f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [586492040](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/586492040) was triggered at [6122195](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/6122195c698903dc1a2c034d839e46cfa7adcc48). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [589474596](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589474596) was triggered at [8e24712](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/8e24712b5c659d84cf32da0dca9fbcc935467d98). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [589478770](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589478770) was triggered at [1c411dd](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/1c411dd072ad3c06d9a475aff5ff3cd22c48905e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159">pipeline status</a> for feature branch [PR_7159](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7159). Pipeline [589480144](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589480144) was triggered at [a2a336a](https://github.com/FreeCAD/FreeCAD/pull/7159/commits/a2a336a2ebf06b8fa425e3ce207e77ee95027554). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Time to move on. Changes like this have to maturize by testing. I tested this heavily the last 3 days on Windows but have no access the MacOS.

Now that it is merged, it will be in the weekly builds and more people will test it and give feedback.

**Pull request merged**
