### PR TITLE
GUI: Add UI for Up To Shape feature

### PR DESCRIPTION
**Pull request by kadet1090**
This adds UI for the Up To Shape feature in #11392 - must be merged after. 

For now it supports selecting only one shape and set of faces as it would be too hard to implement UI that supports the list in such short time frame. I'm also very not happy with how much code it required, the selection UI must be reworked in the future: https://github.com/FreeCAD/FreeCAD/issues/14432

https://github.com/FreeCAD/FreeCAD/assets/747404/33731d59-9c45-40cd-85e4-1b502da35285

### CODE REVIEW

**Comment by FEA-eng** [comment]
Nice, I like it. And it works as expected. I'm getting a crash (log below) when testing Up To Face on this simple example but I don't know if it's because of this PR.

[Up to shape test.zip](https://github.com/user-attachments/files/15523076/Up.to.shape.test.zip)

**Comment by FlachyJoe** [comment]
@kadet1090 well done! Do you notice that UpToShape without selection is allowed and pad up to the body shape? It's a kind of UpToFirst which works even if multiple faces are in front.

image

**Comment by kadet1090** [comment]
@FEA-eng thanks it is caused by the UI - I'll investigate why it happens, thanks!
@FlachyJoe yes, I noticed it but assumed that it will have the same behavior if I explicitly set the previous step (i.e. click on the solid), if that's not the case I'll figure out way to reset it.

**Comment by FlachyJoe** [comment]
@kadet1090 I just tested your code and the "no shape selected" message doesn't prevent to validate the task, it's ok. :+1:

**Comment by FEA-eng** [comment]
Can you updraft this PR to make sure it's considered for 1.0?

**Comment by FEA-eng** [comment]
The crash is gone and it works normally now, thanks.

**Comment by FlachyJoe** [comment]
@kadet1090 FYI https://github.com/FreeCAD/FreeCAD/issues/14390#issuecomment-2160196159

**Pull request merged**
