### PR TITLE
Sketcher: Chamfer tool (and fillet refactor)

### LINKED ISSUE #5623: [Feature Request] Add Chamfer Edge-Tool
Issue imported from https://tracker.freecad.org/view.php?id=2052

* **Reporter:** r-frank
* **Date submitted:** 4/13/2015
* **FreeCAD version:** 0.14
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Like the already existing "Fillet Edge" tool to apply a fillet to two lines, there should be a tool to apply a chamfer as well. Could use the same logic (workflow) as the "Fillet Edge" Tool.
See discussion here:
http://forum.freecadweb.org/viewtopic.php?p=83906#p83906

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: Windows 7 64 bit**
* **Platform:** Windows
* **Updated:** 2/6/2021

### LINKED ISSUE #12464: [Problem] Sketcher: No OVP/Widget for Fillet Tool
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The fillet tool currently does not work with a preselection and makes no use of the OVP (on-view-parameters) and the widget in the task dialog.
It should display the mode in the widget, e.g. simple fillet, corner preserving fillet, and if available a chamfer tool. Cycle though them with the `M`key should be possible.
The OVP should be visible to define the dimension(s) and create the constraints.

297326231-6fdd9776-5efb-423e-b5d0-ecce0ee25635

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35966 (Git)
Build type: Release
Branch: main
Hash: 7f5d89fa1942fec79222e4d173655744037164dc
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.1
  * CurvedShapes 1.0.5
  * Curves 0.6.23
  * Defeaturing 1.2.2
  * fasteners 0.5.2
  * FEMbyGEN 2.1.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.0
  * woodworking 0.21.2.33771
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
- Rework fillet tool, so that preserve corner is a checkbox not a separate tool.
- Introduce Chamfer tool.
- Few syntax fixes/modernization in fillet()
- unrelated but fix error in className of CmdSketcherCompHorizontalVertical
image
Fixes #12464 (though there is no OVP introduced)
Fixes #5623

### CODE REVIEW

**Comment by FEA-eng** [comment]
> * Introduce Chamfer tool.

Awesome to see this pretty much last major limitation of the sketcher being resolved. Can I help with testing or is it too early as the PR is still in draft?

**Comment by PaddleStroke** [comment]
If you can test it would be great. It's already finished.

**Comment by FEA-eng** [comment]
Very good decision to turn the separate corner-preserving fillet tool into a checkbox. The new chamfer tool works very well too. Here are some minor comments:
1. Fillet and chamfer are separate tools but when one of them is activated, the mode can be changed to the other tool. Doesn't it mean that they should be unified into a single fillet/chamfer tool?
2. The preserve corner checkbox is shown also for the chamfer mode but it has no use there, right? Moreover, it becomes unchecked automatically after the first use of the tool but it seems to be still in effect.
3. Do you plan to add the on-view parameters for those tools so that the user is asked for the fillet radius or chamfer size before the feature is created?

**Comment by PaddleStroke** [comment]
1. I think it's best to keep them separate as they are usually separate tools in other cads.
2. This needs to be fixed.
3. It's hard to implement OVP for fillet because of how the internal works. It would need much more work and I'm kind of swamped right now so if it comes it will be later.

**Comment by FEA-eng** [comment]
> 1. I think it's best to keep them separate as they are usually separate tools in other cads.

Sure, I don't mind it at all. I just thought that it was a bit different than the other tools but then I realized that it's already like this with some shape (circle/rectangle) drawing tools so never mind. Let's keep them separated.

> 3. It's hard to implement OVP for fillet because of how the internal works. It would need much more work and I'm kind of swamped right now so if it comes it will be later.

Sure, it's nothing urgent. Just a minor suggestion for the future.

**Comment by maxwxyz** [comment]
Nice to see this! A few questions:
- Is preserve corners checked by default?
- Does it work with 2 edges (lines/conics) and also just with 1 point?
- Does it work with a preselection?
- If OVP is too much work for now, would a radius constraint be feasible or should this be postponed to later as well?

**Comment by PaddleStroke** [comment]
- yes
- yes
- No, as fillet current doesn't.
- You mean create a radius constraint automatically? But then it can be annoying, say if you want to make 5 fillet and make them equal. If it creates a radius on every use it's bad

**Comment by maxwxyz** [comment]
OK thanks, that's good.

**Comment by PaddleStroke** [comment]
Small issue with the checkbox reseting itself to false fixed.

**Comment by FEA-eng** [comment]
I tested this again, the only small issue is indeed gone and it all works as expected.

**Pull request merged**
