### PR TITLE
Introduce GoogleTest C++ unit testing framework

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7923">pipeline status</a> for feature branch [PR_7923](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7923). Pipeline [710363748](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/710363748) was triggered at [ba763d0](https://github.com/FreeCAD/FreeCAD/pull/7923/commits/ba763d06c34feacd669385b6376a3a1edd3168d4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@wwmayer which directories should we tell `codespell` to avoid descending into in the PR ? (as I mentioned in https://github.com/FreeCAD/FreeCAD/pull/7903#issuecomment-1330894626)

**Comment by wwmayer** [comment]
The directory tests/lib contains all the Google unit testing code and can be ignored.

**Comment by wwmayer** [comment]
63d46325fe

**Pull request merged**
