### PR TITLE
[For v0.19]Issue 3866: Partial fix for inaccurate tooltips

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by donovaly** [comment]
Many thanks.

To avoid misunderstandings: I only collected in Issue 3866 because I thought the strings are already frozen for FC 0.18.

**Comment by luzpaz** [comment]
@donovaly shall I close this and you open a separate PR ?

**Comment by donovaly** [comment]
> shall I close this and you open a separate PR ?

Keep it open. It is not important to fix everything at once. We can do it bit by bit and you already started.

**Comment by luzpaz** [comment]
I'll close it and add it to #1965

**Comment by donovaly** [comment]
>> Keep it open.

> I'll close it

Why are you then asking me?

**Comment by luzpaz** [comment]
@donovaly sorry, just realized it was better to limit amount of PRs and since the crowdin PR is relevant I just cherry-picked it. Feel free to also send PRs related to issue 3866 there.

**Pull request closed without merging**
