### PR TITLE
Toponaming: make sure TopoShapes have Hashers

### PR DESCRIPTION
**Pull request by bgbsww**
Match behavior before ElementMaps refactored out of ComplexGeoData.

### CODE REVIEW

**Comment by FEA-eng** [comment]
May this fix #15484 or is it too optimistic or juts too early? Because I still have that failure when testing in this branch.

**Comment by bgbsww** [comment]
Actually it does, but you need to do a recompute of the document after loading it to cause the element map to get populated with hashed names instead of unhashed ones.

**Comment by FEA-eng** [comment]
> Actually it does, but you need to do a recompute of the document after loading it to cause the element map to get populated with hashed names instead of unhashed ones.

Just in case, I'm always testing the TNP PRs with fresh files (recreated models). And #15484 is easy to recreate. I still can't confirm that it works with non-centered rectangle but maybe I'm doing something wrong.

**Comment by bgbsww** [comment]
You're right.  But I did see it work ... with multiple PRs in that build.
I'll find the combination.

**Pull request merged**
