### PR TITLE
[Sketcher] hor/ver tool, remove unused variables

### PR DESCRIPTION
**Pull request by PaddleStroke**
hor/ver tool, remove unused variables
@wwmayer

### CODE REVIEW

**Comment by wwmayer** [comment]
Should be fine.

**Comment by PaddleStroke** [comment]
It was the same before in horizontal and vertical applyConstraints.
Please advise if the situation was wrong then and needs to be fixed, or if its ok.

**Comment by wwmayer** [comment]
> Please advise if the situation was wrong then and needs to be fixed, or if its ok.

As said this PR is fine. The issue possibly has existed for several years and I don't want to figure out the exact commit when it has been introduced since this is quite irrelevant.

**Comment by wwmayer** [comment]
#11549

**Pull request merged**
