### PR TITLE
Path Translation cleanup part 2 [PATH]

### PR DESCRIPTION
**Pull request by sliptonic**
- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5324">pipeline status</a> for feature branch [PR_5324](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5324). Pipeline [440637546](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/440637546) was triggered at [2a1f50f](https://github.com/FreeCAD/FreeCAD/pull/5324/commits/2a1f50fd7c82e109bc3be49d4891c6d9ab9fead3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
ooof, this is going to reset a whole lot of Path WB pre-translated translations  😬. 
But sometimes a good housecleaning is nseded

**Comment by sliptonic** [comment]
Yes.  And we're just getting started.  This is going to touch almost every file in Path.  We're trying not to touch the context strings very much so it should minimize the impact on translators but there's a lot of noise in path.  context strings like pathJob and path_job.   I'd appreciate advice on how to proceed.

**Comment by luzpaz** [comment]
:point_up: CC @yorikvanhavre @chennes (regarding any advice on minimizing impact on translators?)

**Review by chennes — APPROVED** [review]
These look solid to me: there aren't too many that will actually trigger a retranslate, and those that do are just context changes. It's my understanding that in those cases CrowdIn helps translators out by showing a possible translation string selected from the old context (though as a non-translator I don't know for sure how this works).

**Pull request merged**
