### PR TITLE
Gui: Update about dialog thumbnail image

### PR DESCRIPTION
**Pull request by qewer33**
Update the temporary about dialog thumbnail image introduced with my https://github.com/FreeCAD/FreeCAD/pull/16071 PR. This PR just replaces the image and nothing else, safe to merge before 1.0.

Dark:

image

Light:

image

### CODE REVIEW

**Review by maxwxyz — APPROVED** [review]

**Comment by 3x380V** [comment]
> Update the temporary about dialog thumbnail image introduced with my #16071 PR. This PR just replaces the image and nothing else, safe to merge before 1.0.

Diffstat does not agree:
```
 src/3rdParty/OndselSolver      |   2 +-
 src/Gui/Icons/freecadabout.png | Bin 229215 -> 72041 bytes
 2 files changed, 1 insertion(+), 1 deletion(-)
```
Please give more care preparing PR. Mentioned #16071 is not exactly shining example how it should work.

**Comment by qewer33** [comment]
> Mentioned #16071 is not exactly shining example how it should work.

No idea what you mean by that but anyway thanks for the heads up, I am not sure why the submodule "changes" were added but seems like it was mostly because of git being stupid.

**Comment by 3x380V** [comment]
Thanks for fixing that.
Short explanation: #16071 was merged as
```
ed97f3c459 fixup! Gui: Add new splash images
6680a295bc fixup! Gui: Add new splash images
f15647ef42 fixup! Gui: Add new splash images
479aeb2998 Gui: splashscreen: Use std::string as Log parameter
1868ab7c0a Gui: Drop showLic AboutDialog parameter
9beff61b72 Gui: Make splashscreen use multiple splash images
5850c2e04b Gui: Disable splashscreen messages by default
18db68ab84 Gui: Add new splash images
```
you were probably expecting fixups to be squashed on merge, but it rarely happens here. Also see #16428.

**Comment by yorikvanhavre** [comment]
backported

**Comment by adrianinsaval** [comment]
I think this now needs to be updated again on main since main is supposed to be 1.1 already, maybe we should just not have the version number in the image

**Comment by 3x380V** [comment]
...unless each version is supposed to have different image anyway to easily distinguish between them.

**Comment by qewer33** [comment]
> I think this now needs to be updated again on main since main is supposed to be 1.1 already, maybe we should just not have the version number in the image

This should only be changed on releases, no point on displaying dev versions.

**Comment by adrianinsaval** [comment]
> > I think this now needs to be updated again on main since main is supposed to be 1.1 already, maybe we should just not have the version number in the image
> 
> This should only be changed on releases, no point on displaying dev versions.

then it should have no version number, it is showing the wrong version number currently

**Comment by qewer33** [comment]
> it is showing the wrong version number currently

No? The release is 1.0 and it's showing 1.0. As I said, there is no need to display the dev version IMO. When we make the 1.1 release, it'll be updated to 1.1 with possibly a different style image.

**Comment by adrianinsaval** [comment]
> there is no need to display the dev version IMO.

yes there is, we have hundreds of people running dev releases, it is very important for bug reporting and triaging to have accurate version information. Anything that makes this more confusing is a problem

**Comment by qewer33** [comment]
I really don't think it's going to confuse anyone on dev versions considering the dev version is already displayed on the text below + the splash (also this is already done on other open source and I've never seen anyone say it's confusing, see Inkscape). I guess I can open another PR to remove the version number if you insist though, I don't really have a strong opinion.

**Comment by qewer33** [comment]
As a different solution, I can also implement simple logic to display a different image if the current version is marked as a dev version.

**Comment by adrianinsaval** [comment]
> As a different solution, I can also implement simple logic to display a different image if the current version is marked as a dev version.

I think this is more trouble than it's worth, IMO it is better to just not have the version on the image, like you said yourself the version is already displayed in the dialog. This is just my opinion though, if you feel like your design needs to have the version info feel free to write that logic, just make sure that this can be disabled or configured for future versions of freecad or branded versions, as is the case with the splashscreen.

I just don't want conflicting information on this page.

**Pull request merged**
