### PR TITLE
Core: Disable document activation when right-clicking a doc

### PR DESCRIPTION
**Pull request by farleyrunkel**
When you right-click a document, you simply want to perform an action from the right-click menu. Changing the tree view's appearance, including unfolding the current document's items and folding others, before the user makes a choice does not align with the user's expectations.

I believe it is better to let the user decide whether and how to activate a document. 

This change ensures that user actions are in line with their intentions and provides a more intuitive and customizable experience.

#13628

### CODE REVIEW

**Comment by chennes** [comment]
@FreeCAD/design-working-group what are your thoughts?

**Comment by pierreporte** [comment]
This change seems very sensible to me.

**Comment by maxwxyz** [comment]
@chennes I did not get a notification from that ping, am I included?
I am in favor of this change.

**Comment by kadet1090** [comment]
This is very sensible indeed.

**Comment by maxwxyz** [comment]
@farleyrunkel This is changing documents on right click in the tree view (again) for me.
I'm using the Collapse/Expand setting:
grafik


```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38043 (Git)
Build type: Release
Branch: main
Hash: 561e521817034ea7660de987d8ab7183ad583595
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.27.3
  * Curves 0.6.40
  * dodo 1.0.1
  * fasteners 0.5.24
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * OpticsWorkbench 1.0.18
  * Rocket 3.3.0
  * sheetmetal 0.4.21

```

**Comment by farleyrunkel** [comment]
@maxwxyz Ok, I'll check it again. It may need more tests.

**Pull request merged**
