### PR TITLE
Materials: Child ignoring parent material

### LINKED ISSUE #15503: Material: Child ignoring parent material
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When modifying a part, the resulting child ignores the parent material.

Steps to reproduce:
1. In Part WB create a Box
2. Set the material to something other than default
3. Create a chamfer
4. The resulting piece has been reset to the default material

Part Design WB has similar problems

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38259 (Git)
Build type: Release
Branch: main
Hash: c8046b1c60c786caca3050cf51f853454ffb5388
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * ArchTextures
  * CfdOF 1.25.11
  * fasteners 0.5.17
  * fcgear 1.0.0
  * FeedsAndSpeeds 0.5.0
  * GDML.backup1701064072.5104816 2.0.0 (Disabled)
  * kicadStepUpMod 11.1.2
  * LCInterlocking
  * MaterialTest
  * OpenTheme 2024.5.3
  * render 2024.6.11
  * Rocket 4.0.0
```

### Subproject(s) affected?

Part

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by davesrocketshop**
Inherit the material from the parent object when creating a new object, such as during a boolean operation, or when extruding a sketch.

fixes #15503

### CODE REVIEW

**Comment by maxwxyz** [comment]
This should be in RC3 as otherwise there will be multiple reports of this issue when it is closed but not in the RC.

**Comment by chennes** [comment]
Thanks for the PR, @davesrocketshop -- there's a lot of code duplication here, was it not tenable to put something like this into its own method someplace?
```c++
if (feature) {
    if (ShapeMaterial.getValue().getUUID() != feature->ShapeMaterial.getValue().getUUID()) {
        if (ShapeMaterial.getValue().getUUID() == mat->getUUID()) {
            ShapeMaterial.setValue(feature->ShapeMaterial.getValue());
        }
    }
}
```

**Comment by davesrocketshop** [comment]
> Thanks for the PR, @davesrocketshop -- there's a lot of code duplication here, was it not tenable to put something like this into its own method someplace?
> 
> ```c++
> if (feature) {
>     if (ShapeMaterial.getValue().getUUID() != feature->ShapeMaterial.getValue().getUUID()) {
>         if (ShapeMaterial.getValue().getUUID() == mat->getUUID()) {
>             ShapeMaterial.setValue(feature->ShapeMaterial.getValue());
>         }
>     }
> }
> ```

I'm sure if I worked longer I could, but the code is in many unrelated places, and they're all just slightly different. In the interests of time I thought it best to merge as is rather than refactor, but I'll be re-examining post pr

**Comment by davesrocketshop** [comment]
> Thanks for the PR, @davesrocketshop -- there's a lot of code duplication here, was it not tenable to put something like this into its own method someplace?
> 
> ```c++
> if (feature) {
>     if (ShapeMaterial.getValue().getUUID() != feature->ShapeMaterial.getValue().getUUID()) {
>         if (ShapeMaterial.getValue().getUUID() == mat->getUUID()) {
>             ShapeMaterial.setValue(feature->ShapeMaterial.getValue());
>         }
>     }
> }
> ```

Refactored to reduce duplicated code.

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
