### PR TITLE
FEM: Add missing Gmsh 2D algorithm (Quasi-structured Quad)

### PR DESCRIPTION
**Pull request by FEA-eng**
adds missing 2D meshing algorithm to Gmsh mesher in FEM

@marioalexis84 FYI

### CODE REVIEW

**Comment by marioalexis84** [comment]
@FEA-eng in https://github.com/FreeCAD/FreeCAD/pull/15624 I have cherry-picked these commits to avoid merge conflicts. Could you please close this pull request in favor of https://github.com/FreeCAD/FreeCAD/pull/15624?

**Comment by jintat87** [comment]
Hi, Will quasi be add in solid to Mesh FromPartShape under Mesh Workbench too?
Untitled-1

**Comment by FEA-eng** [comment]
> Hi, Will quasi be add in solid to Mesh FromPartShape under Mesh Workbench too?

Since #15661 was merged, it should be there in the next weekly build (around the end of the week): https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by jintat87** [comment]
> > Hi, Will quasi be add in solid to Mesh FromPartShape under Mesh Workbench too?
> 
> Since #15661 was merged, it should be there in the next weekly build (around the end of the week): https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

That's a great news! I appreciate your hard work, Thanks!

**Pull request closed without merging**
