### PR TITLE
LGTM: Remove unsafe time functions

### PR DESCRIPTION
**Pull request by chennes**
This PR is in two commits: the first, 7f1dc84, replaces the global-shared-memory versions of the time functions with those that work with local memory. The second, 32a34f5, eliminates entirely an unused function that would otherwise have needed both a similar fix for the time functions, and a function signature change (from char* to string) to eliminate a local version of the same flaw.

---

- [X]  Your pull request is confined strictly to a single module.
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [X]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0` (except the four that were failing before!)
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- No tracker ticket.

### CODE REVIEW

**Comment by wwmayer** [comment]
There is a problem with localtime_s. According to https://en.cppreference.com/w/c/chrono/localtime the MS implementation is incompatible to the C standard because the arguments are swapped.

Then in Document.cpp we have to include ctime in the ifndef _PreComp_ section.

**Comment by chennes** [comment]
> There is a problem with localtime_s. According to https://en.cppreference.com/w/c/chrono/localtime the MS implementation is incompatible to the C standard because the arguments are swapped.

It gets worse - it turns out this is one of the places that C++ and C are not synched. While the C11 standard defines the _s version of the function, C++11 does not. So it's a non-portable, implementation-defined feature. Which is to say, IMO we can't use it. C++ `std::chrono` doesn't really support the direct output of this style of time-string, even in C++20. So, if we want to address this, I believe we are left with `boost::chrono`. I'm happy to write it, but this has gotten to be less like a "quick bug fix" and more like a "feature". So what do you think about delaying it until after 0.19 is released?

**Comment by wwmayer** [comment]
> So what do you think about delaying it until after 0.19 is released?

Yes, that's probably best. But nevertheless I could cherry-pick the change to remove ConsoleSingleton::Time() as it's not used anywhere.

**Comment by wwmayer** [comment]
Cherry-picked 4ca6f68 became a0bbb173f47f

**Comment by chennes** [comment]
I'm closing this PR since the part that worked has been cherry picked, and the remainder needs to be rewritten (or we just need to tell LGTM to ignore the issue).

**Pull request closed without merging**
