### PR TITLE
Fem: Enable checkbox for references mesh groups - fixes #10071

### LINKED ISSUE #10071: [Problem] FEM experimental characteristic (Group meshing for analysis) is set to true in FEM General Preferences and can't be changed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Spanish/Peru (es_PE)
Installed mods: 
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Problem description

When trying to create a FEM mesh via the "FEM MeshGmshFromShape" tool this message appears:

"Group meshing for analysis is set to true in FEM General Preferences. Are you really sure about this? You could run into trouble!"

When i go to FEM General Preferences that option is grayed out and activated.

I'm having troubles to create a FEM mesh via the "FEM MeshGmshFromShape" tool and maybe this is the reason.

Excellent program and initiative. Thank you so much.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marioalexis84**
Enable the checkbox and set default value to false for the experimental feature.

### CODE REVIEW

**Comment by chennes** [comment]
This looks fine to me -- @FEA-eng can you confirm this fixes #10071?

**Comment by FEA-eng** [comment]
> Enable the checkbox and set default value to false for the experimental feature.

The problem is that without group meshing, pressure on shells won't work at all: #12114. So maybe it would be better to keep it enabled by default.

**Comment by marioalexis84** [comment]
Ok, thanks for pointing out https://github.com/FreeCAD/FreeCAD/issues/12114.
I willl mark this as  Draft and try to resolve https://github.com/FreeCAD/FreeCAD/issues/12114 first.
Pressure on shells should work with or without this feature enabled.

**Comment by FEA-eng** [comment]
> @FEA-eng this fix #10071 and also #12114

And #5699

@chennes I tested this and it works properly.

**Comment by marioalexis84** [comment]
@chennes #5699 and #12114 can also be closed.

**Pull request merged**
