### PR TITLE
[Do not merge] Geometry Extensions

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
Travis trials for windows

### CODE REVIEW

**Comment by sasobadovinac** [comment]
sorry but I don't think it is good to do this type of testing here (travis and appveyor accounts of the master)

**Comment by abdullahtahiriyo** [comment]
@sasobadovinac 
I do not understand. 

I see it like this:
1. Tests are necessary in order to arrive to a working configuration. The more the least documented options are. So tests will need to be run. AppVeyor is failing constantly due to time out, so it will stop being an option for FreeCAD soon (at least unless we split it into smaller subprojects, each having a different repo).
2. Using a PR does not interfere with github master behaviour.
3. The extended time provided by Travis for the FreeCAD account is necessary to complete the tests.

Maybe you see it from a different point of view?

**Comment by sasobadovinac** [comment]
@abdullahtahiriyo don't understand me wrong, it is great what you did, but our resources on both appveyor and travis are limited, if everyone would do it like this then the build queues would fill up very fast and it would take days for builds to finish. only the final solution should be tested here before the merge. developers should have their own build/test environments (for example using virtualbox or similar) or have their own appveyor and travis accounts.

ps: congratulations on making the win travis build working, add back the /m switch to the msbuild.exe command, it should run faster

**Comment by abdullahtahiriyo** [comment]
@sasobadovinac 

I am not getting you wrong at all. It is all good. Truly :). 

I see that you see that the way I am doing this may affect "something" negatively. I do not see it yet. So I am asking your help to understand it. 

First, I cannot run tests that are Travis configuration specific in a Virtual machine. I must use Travis.

what/who is the "something" I am affecting?

Travis would bear with my test whichever account I use. The load on their servers is the same. Only that I could never complete a test with my account because of the extended time needed.

Or do you mean I am affecting other FreeCAD developers?

Nobody else is using the queue at this moment. Most of the tests have been extremely short because it would not build for the last days. Since I discovered it, I am using just one queue of Travis, the one of windows, (because I right away cancel all others manually after PR).

I would honestly want to minimise any impact by these tests. If can see how, please let me know :)

**Comment by abdullahtahiriyo** [comment]
@sasobadovinac 

Ah! the /m... that is one of the problems I am running to now. Passing parameters to msbuild makes it not work properly:
https://forum.freecadweb.org/viewtopic.php?f=10&t=35884&p=303935#p303919

I have to figure out a way...

**Pull request closed without merging**
