### PR TITLE
[CAM] Skip Fixtures, Remove Linenumbers, Fix write the file

### PR DESCRIPTION
**Pull request by haraldhartmann**
Some improvements for the Estlcam PP:
- Estlcam doesn't need any G commands for the workpiece coordinate system, so the PP skip Fixtures now. _Else Estlcam gives you a warning about G54._
- Estlcam doesn't need linenumbers, so removed it from the PP
- Someone else has added `from builtins import open as pyopen` but hasn't changed the `write the file` section in `def export`

### CODE REVIEW

**Comment by sliptonic** [comment]
Please reference the CONTRIBUTING.md file in the root of the source tree for guidance on how to contribute.  Please provide some description in the PR and link to an issue that describes what problem(s) the PR is resolving. 

Thanks.

**Comment by haraldhartmann** [comment]
@sliptonic i have added the description. There's any problems/issue, just some improvements.

**Comment by sliptonic** [comment]
I don't understand this PR.  My understanding is that Estlcam supports but G20 units and linenumbers.  This PR seems to remove support for those features.

**Comment by haraldhartmann** [comment]
@sliptonic from [Requirements for CNC Programs](https://estlcam.de/steuerung_cnc_programme_en.php):

> * Only absolute coordinates...
> * Unit according to the length unit selected in Estlcam...
> * Line numbering possible but not required...

If you generated G-Code with the GRBL PP and load it into Estlcam 12 CNC you get this:

estlcam_FreeCAD_GRBL-PP

I will contact the developer of Estlcam.

**Comment by sliptonic** [comment]
Yep.  I understand.  So It needs either a G20/G21 to know whether the coordinates are in inches or mm.  Standard stuff.
Estlcam does not support coordinate systems like G55..G59 but does support line numbers.

So I would suggest that don't want to remove any features but the post should warn if the user tries to postprocess a job that has multiple fixtures selected.  Basically, if it encounters a G5n it should squawk.

**Pull request closed without merging**
