### PR TITLE
[TD]fix Jumping Dimensions

### PR DESCRIPTION
**Pull request by WandererFan**
- X,Y were changed to PropertyLength (>0), but some X,Y
  are relative, so X,Y sb PropertyDistance.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by WandererFan** [comment]
Linux gcc build failed.  Timed out?  2h54m

**Comment by donovaly** [comment]
Don't we also need the change then the X and Y in DrawViewBalloon?

> // sb PropertyDistance.  some X,Y are relative to existing point on page

What do your mean with this line? What means "sb"?

**Comment by WandererFan** [comment]
OriginX and OriginY should probably be PropertyDistance as well.  
"sb" is abbreviation for "should be".

**Comment by donovaly** [comment]
> OriginX and OriginY should probably be PropertyDistance as well.

Will you do this or should I do this?

> "sb" is abbreviation for "should be".

Can you please use "should be". The code is not that well commented ;-) and abbreviations in the comments raise questions like mine, while they should just explain.

**Pull request merged**
