### PR TITLE
UI: Update icons for consistency

### PR DESCRIPTION
**Pull request by maxwxyz**
Updated GUI icons for consistency:
- new icons for cut, copy, paste, delete
- new new document icon according to DWG discussion (the + replaces the sun), TechDraw will be updated separately
- new icons for preferences
- new icon for parameters (using the same gear as the new logo)

Previously:
image

This PR:
image

@FreeCAD/design-working-group FYI

### CODE REVIEW

**Comment by pierreporte** [comment]
The red cross on the trash can looks redundant.

**Comment by obelisk79** [comment]
I agree with pierre about the red X

**Comment by maxwxyz** [comment]
done: 
image

**Comment by maxwxyz** [comment]
messed something up, here is the new one: https://github.com/FreeCAD/FreeCAD/pull/14276

**Pull request closed without merging**
