### PR TITLE
Mesh: fix pep8 related issues in Init.py

### PR DESCRIPTION
**Pull request by luzpaz**
Added `import FreeCAD`  
Added missing whitespace after commas  
Removed DOS line endings

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6896">pipeline status</a> for feature branch [PR_6896](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6896). Pipeline [540516204](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/540516204) was triggered at [feec67e](https://github.com/FreeCAD/FreeCAD/pull/6896/commits/feec67e90f2c95f8c23ceaae42b8aeee09b4138b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
> Added missing whitespace after commas
Did you check that everything still runs fine after this change? I am 99.9% sure it will, but this string needs precise formatting for Qt, which can be picky about these things, so better make sure...

**Comment by luzpaz** [comment]
I will once i get the snap fixed

**Comment by luzpaz** [comment]
@yorikvanhavre I just extracted the AppImage, modified the code and tested. It LGTM.

**Comment by yorikvanhavre** [comment]
ok thanks!
My comment was actually a bad one... the spaces you added after the commas are not inside the format string, so everything OK!

**Pull request merged**
