### PR TITLE
Gui: Splash messages ratelimiter

### PR DESCRIPTION
**Pull request by 3x380V**
See https://forum.freecad.org/viewtopic.php?p=764724#p764724

### CODE REVIEW

**Comment by 3x380V** [comment]
@maxwxyz, note this PR cuts down time spent in splash screen considerably. I do not insist on this particular solution, but something should be done with startup time before release...

**Comment by MisterMakerNL** [comment]
On windows I get this message:
image
It does load faster but it also hangs.

**Comment by MisterMakerNL** [comment]
I am excited to make Freecad boot faster!

**Comment by 3x380V** [comment]
Hmm, it might actually make more sense to move timer stuff into SplashScreen class itself. I'll give it a try...

**Comment by 3x380V** [comment]
And even using `QTimer` is useless as even loop is not yet running. So thread, mutex and timed waiting on condition seem to do the job.

**Comment by 3x380V** [comment]
I need help with this one. Problem to be solved is this one: There is a log observer hooked to the log system which redirects certain messages to splash screen. Currently it renders all of them and adds delay after each, so user can read that (there are over 50 messages on my configuration).

To avoid that, lets limit messages to be printed only each, say 10ms. If new message arrives in 10ms windows, it is skipped and initial one is still displayed. Problem is, when message arrives, say at 9th millisecond. The initial one is still displayed, but I would be reasonable to expect the last one will show up after 10th ms passed. Because event loop is not yet running, `QTimer` is unusable, so `DelayMessage` class is implemented to deliver the last message after specified delay.

This is where the problem arises: how to repaint splash from another thread when event loop is not running? Also, splash screen do not use any kind of locking and based on @MisterMakerNL's feedback, it seems there are more threads involved, so this problem is probably even in current code. Hints and pointers greatly appreciated (I left some debug stuff in code intentionally)

**Comment by 3x380V** [comment]
There is no portable solution to this problem. And the easiest portable is having separate splasher application and sent messages to it. It is too late for that, so question is how to deal with that now. Just remove delays after each message printed?

**Comment by 3x380V** [comment]
Actually remove delay _and_ make messages scroll on the splash screen seems even better. I'll implement it over weekend unless someone comes with more feasible idea.

**Comment by berberic2** [comment]
This PR leads to sporadic segv on my system.
Please see the comments in https://github.com/FreeCAD/FreeCAD-render/issues/428

**Comment by 3x380V** [comment]
@berberic2, this PR will be probably closed and new one with different implementation opened (I'm leaving this decision for the time new implementation is ready for testing). For now it is left as a draft with explanation why original idea is not implementable using Qt. I still need to investigate logging system especially in terms of concurrent access, so you report is quite useful. Thank you.

**Comment by maxwxyz** [comment]
any news on this PR? I've heard that the messages will be disabled at all.

**Comment by 3x380V** [comment]
I've implemented basic idea of scrolling messages. Doing it properly needs some more refactoring, so that would make it out of 1.0 scope. I'll polish code and push. Disabling messages solves the problem definite way. Is that idea decided already?

**Comment by maxwxyz** [comment]
@qewer33 ^

**Comment by 3x380V** [comment]
Let me add one more notice. Splash screen is currently customizable (Ondsel comes in mind here) and its text color and alignment can be adjusted. That's what `SplashAlignment` and `SplashTextColor` config items are used for.
Now, if you allow that for scrolling text, it would probably make sense for the `Top` alignment the new line to apprear on the top, moving older lines down; for the `Bottom` alignment the new line appears on the bottom, scrolling older lines up. Defining how that should behave is the task on its own... @sliptonic?

**Comment by maxwxyz** [comment]
https://github.com/FreeCAD/FreeCAD/pull/16071 should disable the messages at all

**Pull request closed without merging**
