### PR TITLE
[TD]Implement Broken View (fixes  #5694)

### LINKED ISSUE #5694: [Feature Request] TechDraw: "Broken view" - ability to depict very large objects on a page by cutting a segment from the middle and juxtaposing them
Issue imported from https://tracker.freecad.org/view.php?id=3011

* **Reporter:** @luzpaz  
* **Date submitted:** 5/1/2017 
* **FreeCAD version:** 0.17

# Original report text

"Broken view" - the ability to depict very large objects on the page.

image
image

# Other bug information

Part of the [TechDraw Roadmap](https://www.freecad.org/wiki/TechDraw_Roadmap)
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=35&t=48655

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a solution to long standing feature request #5694.

### CODE REVIEW

**Comment by FEA-eng** [comment]
I wanted to test this but it crashes FreeCAD when I press the button:

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f52e4242520]
#1  0x7f51b7094f30 in TopoDS_Shape::ShapeType() const from /home/ubuntu/Documents/broken_view/freecad-source/build/Mod/TechDraw/TechDrawGui.so+0x1c
#2  0x7f51b690f681 in TechDraw::DrawBrokenView::isBreakObject(App::DocumentObject const&) from /home/ubuntu/Documents/broken_view/freecad-source/build/Mod/TechDraw/TechDraw.so+0x5f
#3  0x7f51b706aa3a in CmdTechDrawBrokenView::activated(int) from /home/ubuntu/Documents/broken_view/freecad-source/build/Mod/TechDraw/TechDrawGui.so+0x1ba
#4  0x7f52e949b6e5 in Gui::Command::_invoke(int, bool) from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x291
#5  0x7f52e949b40d in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x13d
#6  0x7f52e9483d9e in Gui::Action::onActivated() from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x2e
#7  0x7f52e9493b9a in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**) from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x7e
#8  0x7f52e949316d in void QtPrivate::FunctionPointer<void (Gui::Action::*)()>::call<QtPrivate::List<>, void>(void (Gui::Action::*)(), Gui::Action*, void**) from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x46
#9  0x7f52e9492211 in QtPrivate::QSlotObject<void (Gui::Action::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x84
#10  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2f1793) [0x7f52e4cf1793]
#11  0x7f52e5965be6 in QAction::triggered(bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x46
#12  0x7f52e59688fc in QAction::activate(QAction::ActionEvent) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xac
#13  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x26408a) [0x7f52e5a6408a]
#14  0x7f52e5a641e7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xf7
#15  0x7f52e5b60d9e in QToolButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xe
#16  0x7f52e59af4ee in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x20e
#17  0x7f52e596c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x83
#18  0x7f52e5974364 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xa84
#19  0x7f52e943651e in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x114
#20  0x7f52e4cb9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x13a
#21  0x7f52e5972e47 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1b7
#22  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1c8d40) [0x7f52e59c8d40]
#23  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1cbfd5) [0x7f52e59cbfd5]
#24  0x7f52e596c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x83
#25  0x7f52e943651e in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x114
#26  0x7f52e4cb9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x13a
#27  0x7f52e5141307 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0x697
#28  0x7f52e5116a2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0xac
#29  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x73d6e) [0x7f52de477d6e]
#30  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x26b) [0x7f52e411bd3b]
#31  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab258) [0x7f52e4171258]
#32  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f52e41193e3]
#33  0x7f52e4d130b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x68
#34  0x7f52e4cb875b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12b
#35  0x7f52e4cc0cf4 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x94
#36  /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so(+0x12cb42f) [0x7f52e92cb42f]
#37  /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so(+0x12cb760) [0x7f52e92cb760]
#38  0x7f52e92cbaa5 in Gui::Application::runApplication() from /home/ubuntu/Documents/broken_view/freecad-source/build/lib/libFreeCADGui.so+0x225
#39  ./FreeCAD(+0x2ddf2) [0x58ad07417df2]
#40  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f52e4229d90]
#41  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f52e4229e40]
#42  ./FreeCAD(+0x2cfc5) [0x58ad07416fc5]
```

**Comment by WandererFan** [comment]
Thanks for testing.   Steps to reproduce?  If I press the button with nothing selected I get "No Break objects found in this selection" but no crash.

**Comment by FEA-eng** [comment]
> Thanks for testing. Steps to reproduce? If I press the button with nothing selected I get "No Break objects found in this selection" but no crash.

I just added Part Cylinder, changed its height and created a view of it in TechDraw. Then selected the view and pressed the broken view button.

**Comment by WandererFan** [comment]
Ahh, I see it now.  The guards will prevent the crash.   

Making a broken view from another view isn't implemented yet.  To use this initial version, select the interesting object and your sketch(es) for the breaks, then push the button.

**Comment by FEA-eng** [comment]
Great, now it works well. But there's no way to customize this (cut line shape and width), right?

broken view

Maybe at least an option to use straight lines could be added (to avoid the gaps between the cut lines and the geometry).

P.S. Maybe #8075 could be implemented on this occasion if it could use a similar approach internally.

**Comment by WandererFan** [comment]
The Gap property will change the separation of the 2 pieces, but there is nothing for line options yet.

**Pull request merged**
