### PR TITLE
Addon welcome update

### PR DESCRIPTION
**Pull request by JamesHodgkins**

### CODE REVIEW

**Comment by chennes** [comment]
Looks like you're having more fun with git 😁 -- if you want some live help, hit the team up in the #Developer Discord channel.

**Comment by JamesHodgkins** [comment]
Yeah I think I've made such a mess that I'm not even sure where I am now... 😞

**Comment by chennes** [comment]
This is totally recoverable, I think you basically just need a rebase. But if you follow @hyarion's suggestion on Discord you can recover from nearly anything.

**Comment by hasecilu** [comment]
I'm curious, what does it does? try adding picture or video.

**Pull request closed without merging**
