### PR TITLE
Remove incorrect usage of if defined

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---
cmake man:

> `if(<variable>)`
> True if given a variable that is defined to a value that is not a false constant. False otherwise, including if the variable is undefined.

The altered code assumes if a variable is defined it is "truthy", which is not the case.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7829">pipeline status</a> for feature branch [PR_7829](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7829). Pipeline [698765422](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/698765422) was triggered at [28198df](https://github.com/FreeCAD/FreeCAD/pull/7829/commits/28198dffe4ce837098891d8551166bd8485eab30). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
aesthetically speaking, the changes make this code less readable. For example, it's informative (for me, FWIW)  to have for example: 
* `endif(DEPENDENCY)` name visible shows the end of the block regarding that dependency. Also I think the comments 
* `endmacro(PrintFinalReport)` be kept instead of `endmacro()`
*`     # -------------------------------- The final report ----------------------------------`  comment

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7829">pipeline status</a> for feature branch [PR_7829](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7829). Pipeline [699518797](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/699518797) was triggered at [333eaa8](https://github.com/FreeCAD/FreeCAD/pull/7829/commits/333eaa88039fd3e32b48e1c811dcb9a6a8120960). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
> The altered code assumes if a variable is defined it is "truthy", which is not the case.

By default [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) is an empty string and with this PR it won't appear in the summary report any more. But for trouble shooting it's important to know if this variable is defined -- even if it's empty.

**Comment by wwmayer** [comment]
Merged as: ab7644441f
I have only reverted the change with CMAKE_BUILD_TYPE. The rest is correct.

**Pull request closed without merging**
