### PR TITLE
[TD]Dimension Reference Error Detection and Correction Ph 1 [#8878]

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements the first phase of a solution for issue #8878.

This phase detects changes in referenced geometry and corrects the reference if an exact match is available.

Phase 2 will address partial matches.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8989">pipeline status</a> for feature branch [PR_8989](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8989). Pipeline [814596118](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/814596118) was triggered at [e35151c](https://github.com/FreeCAD/FreeCAD/pull/8989/commits/e35151c4091ddcc5aa9f361baae46bc37dcca4c2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
Thanks for the comments - much appreciated.

fixExactMatch is used (@ 1428 in LTNPAutoCorrect3, 1430 in the newest LTNPAutoCorrect4) - that is where we fix the reference when we fix identical geometry in the pile.
handleNoExactMatch is used (@ 1484 / 1486) - the implementation for phase 1 doesn't do much, but it does clear the error flag.

I added the explict keyword you indicated and fixed some of the lint/tidy warning (at least the ones I understood!).

**Comment by aapo-aapo** [comment]
Excellent!  I have now compiled this specific PR, and have confirmed that it works as expected.  I have used it to load some old files that have known corrupted dimensions (due to TechDraw evolution and TNP), and somehow the results with these files are better than before (less wrong dimensions)!  My main reason was to check against unexpected crashes with old files, and I know that old files should not have been improved with this PR, but somehow I got better results than I should have had.  However, my pet peeve, which is radically changing the ISO count for a dimensioned drawing still does not completely work, but seems to work better (as expected).  This is one of the difficult cases, where edges will be split into several pieces; and thus it's not even possible to find edge-to-edge correspondence for dimensions, just vertex-to-vertex mapping is possible.

I also noticed that there are some divisions by View->getScale() in the code and got suspicious about division-by-zero, but it seems that the getScale() function itself is protected against wrong scales:
`    if (!(result > 0.0)) {
        result = 1.0;
    }`

So, it compiles correctly, works, and I cannot find any problems with the code, so I'd say go for it!  :)

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8989">pipeline status</a> for feature branch [PR_8989](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8989). Pipeline [815056724](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/815056724) was triggered at [1e450aa](https://github.com/FreeCAD/FreeCAD/pull/8989/commits/1e450aa7b8b05fc542b5d5459e9922a0b6109bb5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
