### PR TITLE
Assembly: Support macros and console logs in Assembly

### PR DESCRIPTION
**Pull request by bgbsww**
Added support code to core to allow getting python objects back from python commands.

Added necessary wrappers and code to Assembly to provide console logs and Macro info for all commands executed.

Feedback requested, ~and this might best be a post 1.0 change, unless it gets a lot of attention.~  Feeling confident in it now, and it changes the game with reporting problems with Assembly since we can see what's going on.

@PaddleStroke Apologies for what this does to pristine code.  If there's another way, I'm all ears.

### CODE REVIEW

**Comment by chennes** [comment]
@PaddleStroke can you give this a look?

**Comment by PaddleStroke** [comment]
I am not sure to understand the goals of the PR nor the code modifications. I don't say there isn't, just that this is out of the scope of my understanding. So I may not be the best to validate this.
It doesn't seem to modify functionality and modify only the 'syntax' of python commands to fix macros if I understand correctly. This new syntax seems more complex, which I don't overly like. But if it's solving a problem then I have no problem with it.

**Comment by bgbsww** [comment]
Thanks, that's correct.  It basically executes any python commands that should be used to recreate the assembly steps in a macro inside of a doCommand() variant.  That isn't really a new syntax, it's more that there's not much prior art of python based workbenches to show how to do this, AFAICT.

I completely agree about the complexity/ugliness here, but if we want to support macros in a given set of code, we have to call doCommand to make that happen - accurate console output is a happy side effect of that.

Basically, if you have an open console, or a macro recording, and you then build an assembly, then without this you'll see nothing in the console as to the commands run to build the assembly, and your macro will be empty and not build an assembly if you run it.

Other folks know that I'm currently working through code that automatically converts macros to tests, which is why this caught my eye - I'd like to be able to ask people to record a macro of their problems should they occur making an assembly, and have it be useful.

Again, because this is new territory I also discovered a couple of holes in the python API for handling getting the results of these doCommands, so I added them as well.

I appreciate the check!

**Comment by PaddleStroke** [comment]
Great then!

**Comment by chennes** [comment]
Because #16973 fixes a bug introduced by this PR, and has been itself backported, pulling this one into 1.0 is a conflict.

**Comment by PaddleStroke** [comment]
This PR is apparantly generating a lot of issues. At least for exploded views : 
https://github.com/FreeCAD/FreeCAD/issues/17196
https://github.com/FreeCAD/FreeCAD/issues/17194
https://github.com/FreeCAD/FreeCAD/issues/17208

I think it has to do with this block of code : 

```
        commands = f'obj = App.ActiveDocument.getObject("{self.viewObj.Name}")\n'
        for move in self.viewObj.Moves:
            more = UtilsAssembly.generatePropertySettings("obj.Moves[0]", move)
            commands = commands + more
        Gui.doCommand(commands[:-1])  # Don't use the last \n
```

I don't understand what this was supposed to do. I'll dig into it.

**Comment by PaddleStroke** [comment]
Ok so this generatePropertySettings should not be taking `obj.Moves[0]` as objectName. In fact there's no need for this objectName parameter. See the PR https://github.com/FreeCAD/FreeCAD/pull/17724

**Pull request merged**
