### PR TITLE
Draft: Allow to change grid color in WP taskpanel

### PR DESCRIPTION
**Pull request by yorikvanhavre**
This adds a color button to the task panel that appears when pressing the Draft working plane button, that allows to change the grid color

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This was mostly because when you change the UI theme, your grid color often needs to be changed too. And it takes a lot of tweaking to find the right color for a certain background color. When you need to go to the preferences, then restart FreeCAD to see the changes, this takes a lot of effort.

Now with this, you can much more easily tweak the grid to exactly the right aspect and intensity you want. The other settings are indeed not so important to set often, that's basically why I left them out.

**Comment by Roy-043** [comment]
Yes, the `_param_observer_callback_grid` function in params.py currently does not handle grid color changes. I missed that. IMO we should improve that function instead. And even if a button is added to the task panel, that function needs to trigger the change.

**Comment by yorikvanhavre** [comment]
Okay for me

**Comment by yorikvanhavre** [comment]
Thanks for the fix! This PR now depends on a fix in the params observer, right?

**Comment by Roy-043** [comment]
The param observer already triggered the correct functions. Not changes were needed there.

**Pull request merged**
