### PR TITLE
Draft: DraftFillet, improved the tool, now the radius can be chosen when the tool is launched

### PR DESCRIPTION
**Pull request by vocx-fc**
Improved the tool, now the radius of the fillet can be chosen when the tool is launched.

Now the tool should work without needing `import DraftFillet` manually.

---
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I am not able to rebase and merge this branch, can you have a look? More chance to avoid errors if you do it than me...

**Comment by vocx-fc** [comment]
I don't get any collisions. Maybe try again. The only two files modified are ``DraftFillet.py`` which nobody has touched, and ``InitGui.py``, which changes only one line.

**Comment by yorikvanhavre** [comment]
Still gives conflicts for me when rebasing, and github doesn't even allow to merge (the button is greyed out)
I can look into it when I have a moment, but it might be faster if you do it..

**Comment by vocx-fc** [comment]
That's strange. I still don't get any problems with rebase. I will close this pull request and try again then.

**Pull request closed without merging**
