### PR TITLE
[TechDraw] seam line in HLR default false

### PR DESCRIPTION
**Pull request by grubertechnic**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by grubertechnic** [comment]
@WandererFan : question, i do not get the italic of the preferences. I do not see where the italic changes in the code, besides i barely see a difference, even with my new glasses.

Is that already needed? Because this statement is not only true in TechDraw, it is true for all objects in FreeCAD.

Thanks in advance!

**Comment by benj5378** [comment]
@grubertechnic As I understand it, properties marked italics in preferences will be used as the default for new object (whatever the preference value is set to).

**Comment by grubertechnic** [comment]
Thanks. Since pretty everything is italic (when i can trust my eyes), then it makes not much sense. Also some parameters are not italic, but have a similar tooltip (example in `TechDraw --> General --> Label Font*`) or none, but still affected.

I have not looked yet, if this note is in the TechDraw preferences ui or in every tab singular. But anyway, it is not important.

**Comment by WandererFan** [comment]
"I do not see where the italic changes in the code, besides i barely see a difference, even with my new glasses."

Can't help with the glasses.  I use QtDesigner:
italicsInDesigner

but if you really want to edit the ui code...
`class Ui_DlgPrefsTechDrawHLRImp
{
public:
...
    Gui::PrefCheckBox *pcbSeamViz;
...
        QFont font;
        font.setItalic(true);
...
        pcbSeamViz = new Gui::PrefCheckBox(gbMisc);
        pcbSeamViz->setObjectName(QString::fromUtf8("pcbSeamViz"));
        sizePolicy1.setHeightForWidth(pcbSeamViz->sizePolicy().hasHeightForWidth());
        pcbSeamViz->setSizePolicy(sizePolicy1);
        pcbSeamViz->setFont(font);  // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        pcbSeamViz->setChecked(true);
        pcbSeamViz->setProperty("prefEntry", QVariant(QByteArray("SeamViz")));
        pcbSeamViz->setProperty("prefPath", QVariant(QByteArray("Mod/TechDraw/HLR")));

        gridLayout_6->addWidget(pcbSeamViz, 4, 0, 1, 1);

`

**Comment by WandererFan** [comment]
"Because this statement is not only true in TechDraw, it is true for all objects in FreeCAD."

There are definitely properties where changing the preference will affect existing objects (may need a recompute).  LabelFont on the general tab is one example.

**Comment by grubertechnic** [comment]
I mean, if a label is italic or not is barely readable (at least for me) in the GUI itself, especially when it sis not in a floating text.

> LabelFont on the general tab is one example.
Only on labels, not on the dimensions.

Anyway, it is not important now and for this.

The questions is more,

is the PR valid?
if yes, 0.21 or 0.22? (since this issue occurs regular)

**Comment by WandererFan** [comment]
You don't need the change in DlgPrefsTechDrawHLRImp, the change to the ui will handle it. 
You do need a change in DrawViewPart to use the new default if the parameter is not set in user.cfg.   You need to change the true to false here:
    ADD_PROPERTY_TYPE(SmoothVisible, (Preferences::getPreferenceGroup("HLR")->GetBool("SmoothViz", true)),
        sgroup, App::Prop_None, "Show Visible Smooth lines");
    ADD_PROPERTY_TYPE(SeamVisible, (Preferences::getPreferenceGroup("HLR")->GetBool("SeamViz", true)),
        sgroup, App::Prop_None,
                      "Show Visible Seam lines");

**Comment by benj5378** [comment]
I can easily see what is italic, even though it isn't as distinct as with other fonts. That said, I do acknowledge that we could improve this. Why do we even have to do stuff italic and then make a label saying "italic settings will become default for new objects"? We could just have had a label at top stating "These settings will be used as default for new object", when all setting are italic anyway. And in any case, two group boxes would probably be better than marking some some properties italic and others.

What do you think of this change? Should we make it?

**Comment by WandererFan** [comment]
Some preferences are only used on new objects, some are used every time the object is recomputed/redrawn.  There needs to be some way of distinguishing these cases for the user.

We could use BOLD or an "*" or a different colour.  I'm not committed to italic.

**Comment by benj5378** [comment]
I'm generally not into using the font for communicating this. What about this instead, where one can select if the setting should also be used when recomputing. This would allow people for opt-in and out.

```
+-------------------+--------------------+--------------------+
| Setting           | Use for new object | Use on recomputing |
+===================+====================+====================+
| Show smooth lines | X                  | X                  |
+-------------------+--------------------+--------------------+
| Show UV ISO lines | X                  |                    |
+-------------------+--------------------+--------------------+
| Show seam lines   | X                  | X                  |
+-------------------+--------------------+--------------------+```

**Comment by WandererFan** [comment]
> I'm generally not into using the font for communicating this. What about this instead, where one can select if the setting should also be used when recomputing. This would allow people for opt-in and out.

But that is a much bigger change that just flipping a boolean preference.  Every place where showSmoothLines is used would have to change to use the 2nd preference instead of the object property.

**Comment by WandererFan** [comment]
This commit and the changes mentioned in the comments are included in PR #10019

**Comment by WandererFan** [comment]
closing in favour of #10019

**Comment by benj5378** [comment]
> But that is a much bigger change that just flipping a boolean preference. Every place where showSmoothLines is used would have to change to use the 2nd preference instead of the object property.

That is true :/ ... though I still consider it an improvement. Consider it low priority

**Comment by grubertechnic** [comment]
> You don't need the change in DlgPrefsTechDrawHLRImp, the change to the ui will handle it.

I know, but i think that is not really "clean" way. But also i am not a programmer.

> You do need a change in DrawViewPart to use the new default if the parameter is not set in user.cfg.

Thanks, maybe next time (if github let me, i will not do the 2FA, its BS).

**Pull request closed without merging**
