### PR TITLE
[ARCH] Arch_Roof fix for adjust_list_len function

### PR DESCRIPTION
**Pull request by Roy-043**
LGTM code analysis did not like that the adjust_list_len function would mutate default list values. The function now always clones the list.
See: https://forum.freecadweb.org/viewtopic.php?f=23&t=55943

### CODE REVIEW

**Comment by luzpaz** [comment]
@wwmayer this should be good to go, right? (Even though the CI fails, which looks like a totally different issue)

**Comment by chennes** [comment]
That's using the older CMake stuff - syncing it with master will probably clear up the Travis issue.

**Comment by wwmayer** [comment]
> @wwmayer this should be good to go, right? (Even though the CI fails, which looks like a totally different issue)

I do not handle Arch or Draft PRs as it's up to Yorik to accept or reject the changes.

**Review by yorikvanhavre — APPROVED** [review]
Looks OK.. Just redoing the CI tests

**Comment by luzpaz** [comment]
@yorikvanhavre CI is still broken.  
```
Your build has been stopped.
Libpack NOT found.
```
This should be a straightforward merge. Perhaps we can skip the CI test for now?

**Comment by wwmayer** [comment]
It should work as soon as it's merged into master. But it's up to @yorikvanhavre to accept or reject the changes.

**Pull request merged**
