### PR TITLE
Draft toggle grid as a toggle button to indicate grid visibility

### PR DESCRIPTION
**Pull request by furgo16**
Fixes https://github.com/FreeCAD/FreeCAD/issues/13527

Supersedes https://github.com/FreeCAD/FreeCAD/pull/13972

1. Makes the button for the [Draft_ToggleGrid](https://wiki.freecad.org/Draft_ToggleGrid) command act as a real toggle button to provide visual feedback of the grid visibility state:
   - Raised: the grid is not visible
   - Depressed: the grid is visible
3. Similar in spirit to the behavior of the [Sketcher_Grid](https://wiki.freecad.org/Sketcher_Grid) command, which is also a toggle button.
4. The button could get further styling (e.g. in `Sketcher_Grid` the grid turns green when pressed), but for now it has been left with the default style. That is, darker background when depressed.
5. Submitting as authored and suggested by `@Syres916` at https://github.com/FreeCAD/FreeCAD/issues/13527#issuecomment-2096322545.

## Demo

[Grid Toggle.webm](https://github.com/FreeCAD/FreeCAD/assets/148809153/9bd5f9a0-38f3-4e4f-afc1-5df0fad16bca)

### CODE REVIEW

**Comment by furgo16** [comment]
Left to address in this PR:

1. There might not be a need to change `gui_grid.py`. It may have been required in the past.
2. `update_grid_gui: `
   - `gui_utils.get_3d_view()` is used as a check twice. The 2nd check is superfluous.
   - If there is a 3D view it follows that the GUI is up. The check `FreeCAD.GuiUp` is therefore strange.
4. `_set_grid_button_state`: `action.setCheckable(button_enable)` can just become `action.setCheckable(True)`
5. The code does not handle multiple documents properly ([review comment](https://github.com/FreeCAD/FreeCAD/pull/13972#pullrequestreview-2055093228)). See [this comment](https://github.com/FreeCAD/FreeCAD/pull/13972#issuecomment-2124762668) for a pointer on how to fix this.

To address in a subsequent PR:

1. It may be worth considering merging the code with WorkingPlane.py. We can then use a single view observer. And there is the intention to make the grid a property of the working plane in the future.

From https://github.com/FreeCAD/FreeCAD/pull/13972#issuecomment-2118757092

**Comment by maxwxyz** [comment]
Could you add a demo in the PR how it will look (both states)?

**Comment by furgo16** [comment]
> Could you add a demo in the PR how it will look (both states)?

@maxwxyz, done. Note there seems to be a visual artifact over the File and View menus, which I don't think is caused by this PR.

**Comment by furgo16** [comment]
This is now ready for review. The only thing I have not addressed is:

- `_set_grid_button_state`: `action.setCheckable(button_enable)` can just become `action.setCheckable(True)`

This might be me not fully understanding `setCheckable()`, but I don't think it can be simplified to be always `True`. When there isn't a view, we disable the button by setting `button_enable=False`

**Pull request merged**
