### PR TITLE
Remove unused cmake

### PR DESCRIPTION
**Pull request by mosfet80**
Rift and spnav are no longer used in the freecad project.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8868">pipeline status</a> for feature branch [PR_8868](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8868). Pipeline [804563408](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/804563408) was triggered at [d18df1d](https://github.com/FreeCAD/FreeCAD/pull/8868/commits/d18df1dfda4096653a41d53796fc8bba25336591). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Is spnav really not used? Isn't that how we connect to SpaceMouse on linux?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8868">pipeline status</a> for feature branch [PR_8868](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8868). Pipeline [804720927](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/804720927) was triggered at [23b193e](https://github.com/FreeCAD/FreeCAD/pull/8868/commits/23b193e791361eac5219a9a2b243cf4b9fb341ef). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
It's of course still needed. See https://github.com/FreeCAD/FreeCAD/blob/master/cMake/FreeCAD_Helpers/SetupSpaceball.cmake#L7 and https://github.com/FreeCAD/FreeCAD/blob/master/CMakeLists.txt#L83

**Review by wwmayer — COMMENTED** [review]
It's of course still needed. See https://github.com/FreeCAD/FreeCAD/blob/master/cMake/FreeCAD_Helpers/SetupSpaceball.cmake#L7 and https://github.com/FreeCAD/FreeCAD/blob/master/CMakeLists.txt#L83

**Comment by mosfet80** [comment]
@chennes @wwmayer . For the spnav makefile, i'm using debian and i was able to complete successfully without the two makefiles, unfortunately i made a mistake in not enabling VR in the config and apologies for wasting your time. i will restore the spnav file.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8868">pipeline status</a> for feature branch [PR_8868](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8868). Pipeline [804812764](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/804812764) was triggered at [0c016e5](https://github.com/FreeCAD/FreeCAD/pull/8868/commits/0c016e57ee12979ada66b91dd2cf4e6beb6c505d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
But for those who own a Oculus Rift have the SDK and can enable BUILD_VR and therefore FindRift.cmake is needed.

**Pull request closed without merging**
