### PR TITLE
[On hold]Group error icon tree 

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
https://forum.freecadweb.org/viewtopic.php?f=10&t=37417&p=319184#p319184

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
@wwmayer 
This should be straight-forward to review.

**Comment by wwmayer** [comment]
The code looks basically OK to me but I wonder about the runtime performance because isErrorInOutListRecursive() is a rather expensive operation and it is called inside a timer every 300 ms.

For small projects you won't notice a slow-down but what about projects with several hundreds of objects?

**Comment by wwmayer** [comment]
This is a test code to create 1000 nested groups which has no impact on the current master but with this PR the whole GUI becomes unresponsive slow.

grp=App.ActiveDocument.addObject("App::DocumentObjectGroup","Grp")
for i in range(1000):
  grp2=App.ActiveDocument.addObject("App::DocumentObjectGroup","Grp")
  grp.addObject(grp2)
  grp=grp2

box=App.ActiveDocument.addObject("Part::Box","Box")
box.Length=0
App.ActiveDocument.recompute()
grp.addObject(box)

So, it must be avoided to call this expensive function all the time. I guess a better idea might be to use one of the StatusBits of a DocumentObject and then set it directly after a document recompute.

**Comment by abdullahtahiriyo** [comment]
@wwmayer 

Ok. It makes sense. 

At the moment I cannot change this. I will react in a couple of weeks.

**Pull request closed without merging**
