### PR TITLE
[TD] weld symbols cannot be rotated

### PR DESCRIPTION
**Pull request by donovaly**
- therefore hide the Rotation property

### CODE REVIEW

**Comment by WandererFan** [comment]
Merged.  
May have to revisit this.  The AWS symbols have versions for above the line and below the line.  GOST for example does not as yet.

**Comment by donovaly** [comment]
> May have to revisit this. The AWS symbols have versions for above the line and below the line. GOST for example does not as yet.

I don't understand. What do you mean with GOST? What has this to do with rotation?

**Comment by WandererFan** [comment]
For American WElding Society standard I made duplicate mirror images of
each icon.
For the Russian GOST (don't have Cyrillic characters here) standard the
author only made 1 of each icon.
We will need to either mirror the GOST symbols, or allow the symbol tile to
rotate 180* if we only use 1 svg per weld type.

**Comment by donovaly** [comment]
Thanks for the explanation. I never heard about GOST before.

**Pull request merged**
