### PR TITLE
Replaced all icons with a new updated logo

### PR DESCRIPTION
**Pull request by JacobHepworth**
The original Logo has a charm but is very wacky looking. I overhauled it by updating the alignment, proportions, and color scheme. I apologize for breaking the single module rule, I felt it would be fine since I wasn't modifying/adding code.

### CODE REVIEW

**Comment by luzpaz** [comment]
This is a super contentious topic. 
* [FreeCAD Logo Design](https://forum.freecadweb.org/viewtopic.php?p=235719#p235719)
* [FreeCAD Logo Gallery - Please read the first post!](https://forum.freecadweb.org/viewtopic.php?f=34&t=50640)
 
Looks like your [posted](https://forum.freecadweb.org/viewtopic.php?p=574898#p574898) to the latter already but got no response. We need more feedback from the community. But TBH, not sure the time for a rebrand is right now and in this upcoming version (v0.20).

**But that discussion is for the forum. Not this ticket.**  

If discussion is generated from this issue, it has to be done on the forum or this ticket will become bloated with conversation and with high probability devolve in to a flamewar.

**Comment by JacobHepworth** [comment]
Understandable, I'll withdraw the pull request to prevent further discussion here.

**Comment by luzpaz** [comment]
Don't get me wrong. Your contribution is appreciated. Hope you understand that.

**Comment by JacobHepworth** [comment]
The input is appreciated. I already felt I was stepping on the toes of the community by pushing this fork without discussion. Hopefully it can at least act as a catalogue to the original icon locations; Say it does get updated in the future.

**Pull request closed without merging**
