### PR TITLE
[App/Gui] improve coding style

### PR DESCRIPTION
**Pull request by donovaly**
inspired by the changes made with https://github.com/FreeCAD/FreeCAD/commit/dc65b055e514

### CODE REVIEW

**Comment by berndhahnebach** [comment]
we should write this down some how like I did in FEM in https://github.com/FreeCAD/FreeCAD/blob/c10275b439c2dacd8117a54d26f880d33d9b05cd/src/Mod/Fem/coding_conventions.md

**Comment by Vanuan** [comment]
Was there a proposal to use clang-format or something similar to prevent incorrectly formatted code to be checked in?

**Comment by Vanuan** [comment]
For example, here's some idea of a git pre-commit hook:


```
#!/bin/sh

CLANG_FORMAT="clang-format-diff-6.0 -p1 -v -sort-includes -style=Chromium -iregex '.*\.(cxx|cpp|hpp|h)$' "
GIT_DIFF="git diff -U0 --no-color "
GIT_APPLY="git apply -v -p0 - "
FORMATTER_DIFF=$(eval ${GIT_DIFF} --staged | eval ${CLANG_FORMAT})

echo  "\n------Format code hook is called-------"

if [ -z "${FORMATTER_DIFF}" ]; then
	echo "Nothing to be formatted"
else
	echo "${FORMATTER_DIFF}"
	echo "${FORMATTER_DIFF}" | eval ${GIT_APPLY} --cached
	echo "      ---Format of staged area completed. Begin format unstaged files---"
	eval ${GIT_DIFF} | eval ${CLANG_FORMAT} | eval ${GIT_APPLY}
fi

echo "------Format code hook is completed----\n"
exit 0
```

**Comment by Vanuan** [comment]
BTW, which style is this? LLVM, Google, Mozilla, WebKit, Chromium?

**Comment by donovaly** [comment]
Oh no, I opened Pandora's box ;-). I was just amazed that MSVC 2019 does all these changes automatically. The only automatic change that I did not take in was that every
else
begins at a new lie (no closing } before it in the line)

**Comment by Vanuan** [comment]
> MSVC 2019

Doesn't it use clang-format behind the scenes introduced in 2017?
https://devblogs.microsoft.com/cppblog/clangformat-support-in-visual-studio-2017-15-7-preview-1/

**Comment by wwmayer** [comment]
Funny, a few days ago I was reading about different coding style guidelines and various utilities.

FYI, the forum member saso provided the results of several code analysis scanners (coverity, PVS and LGTM) and they revealed many bad coding practices and in the recent weeks I was busy fixing most of them (besides the bugs).

While fixing the issues I came through so much really bad formatted C++ code that considerably reduces readability and thus maintainability and therefore I looked for various guidelines and tools that can be easily used from an IDE.

For example QtCreator directly supports astyle, clang-format and uncrustify. Since VS apparently supports clang-format too it is an option to use that in the future. On my system I have a customized _clang-format file that is based on LLVM but with a handful of modifications.

**Comment by Vanuan** [comment]
So, LLVM it is?

**Comment by donovaly** [comment]
> Which "default formatting style" option did you use?

These:
devenv_NgCaTHHZr4

The "Visual Studio" option has only an effect of no Clang format can be found.

**Comment by wwmayer** [comment]
> So, LLVM it is?

A modified LLVM. At some point this should be discussed in the forum.

**Comment by Vanuan** [comment]
@wwmayer done https://forum.freecadweb.org/viewtopic.php?f=10&t=49172

**Pull request merged**
