### PR TITLE
[App] Fix #5592 : Respect symbolic links

### LINKED ISSUE #5592: Respect symbolic links
Issue imported from https://tracker.freecad.org/view.php?id=1666

* **Reporter:** triplus
* **Date submitted:** 8/4/2014
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** #lowhangingfruit, Qt, Qt5

# Original report text

Based on discussion in this feature request:

http://www.freecadweb.org/tracker/view.php?id=1665#c4918

# Steps to reproduce

1.) Create new folder and save test .fcstd file in this folder
2.) Create symbolic link to test .fcstd file (ln -s) from different directory
2.) Open the file in FreeCAD by clicking on just created symbolic link
3.) Modify the file and save the changes

Expected behaviour:

FreeCAD saves the changes at original test .fcstd file location. Backup files are saved to original test .fcstd file location.

Current behaviour:

FreeCAD saves the changes at symbolic link test .fcstd file location. Backup files are saved to symbolic link test .fcstd file location.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **OS: Ubuntu 14.04**
* **Platform:** Linux
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by triplus 2014-10-25 22:55
For future reference if anybody will try to tackle this area and to provide symbolic links support for FreeCAD this is how Qt Creator deals with symbolic links:

https://qt.gitorious.org/qt-creator/qt-creator/commit/a8ee92a53ba4b1c4c7e2c34db27ee44ed7e9c585

Relevant discussion (don't rewrite symlink on save, rewrite target instead):

https://qt.gitorious.org/qt-creator/qt-creator/merge_requests/399

---

### Comment by Kunda1 2017-03-10 23:14
triplus can you find a more up-to-date source? since Qt seems to have moved their repo.

---

### Comment by Sam 2017-09-03 00:07
Forum thread: [Issues 1665 & 1666; Symbolic links & backups](https://forum.freecadweb.org/viewtopic.php?f=10&t=24195)

### PR DESCRIPTION
**Pull request by FlachyJoe**
Use the real path to the file when saving the document.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7034">pipeline status</a> for feature branch [PR_7034](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7034). Pipeline [565892421](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/565892421) was triggered at [5ba4abb](https://github.com/FreeCAD/FreeCAD/pull/7034/commits/5ba4abb544a982851c2e9941b2ee271695aea360). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7034">pipeline status</a> for feature branch [PR_7034](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7034). Pipeline [567116661](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567116661) was triggered at [1475a31](https://github.com/FreeCAD/FreeCAD/pull/7034/commits/1475a31b4dc0d3e757f3858ca72920ce14a761c6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7034">pipeline status</a> for feature branch [PR_7034](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7034). Pipeline [567366113](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567366113) was triggered at [159c89d](https://github.com/FreeCAD/FreeCAD/pull/7034/commits/159c89da7eecd5e060b09432c4918e789e950f0b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
This PR should theoretically also fix https://github.com/FreeCAD/FreeCAD-Bundle/issues/120

**Comment by luzpaz** [comment]
Building snap: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/2599688586

**Comment by adrianinsaval** [comment]
> This PR should theoretically also fix [FreeCAD/FreeCAD-Bundle#120](https://github.com/FreeCAD/FreeCAD-Bundle/issues/120)

how so? I don't see the relation

**Comment by FlachyJoe** [comment]
> This PR should theoretically also fix [FreeCAD/FreeCAD-Bundle#120](https://github.com/FreeCAD/FreeCAD-Bundle/issues/120)

I don't think so: #5592 is about document save when https://github.com/FreeCAD/FreeCAD-Bundle/issues/120 mention a symlink to the app.

**Comment by donovaly** [comment]
@wwmayer , can you please have a look?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7034">pipeline status</a> for feature branch [PR_7034](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7034). Pipeline [578984805](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/578984805) was triggered at [0d9dfd6](https://github.com/FreeCAD/FreeCAD/pull/7034/commits/0d9dfd6a552830c6268c4dc4ffe7a40f12c8f74d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Is this something that could/should be backported for FreeCAD 0.20.1?

**Comment by wwmayer** [comment]
IMO no.

**Comment by remidemers** [comment]
> > This PR should theoretically also fix [FreeCAD/FreeCAD-Bundle#120](https://github.com/FreeCAD/FreeCAD-Bundle/issues/120)
> 
> I don't think so: #5592 is about document save when [FreeCAD/FreeCAD-Bundle#120](https://github.com/FreeCAD/FreeCAD-Bundle/issues/120) mention a symlink to the app.

The symbolic link is not involved with issue #120. It do the same calling the executable directly.

**Comment by wwmayer** [comment]
Causes a regression reported with: #7277

**Pull request merged**
