### PR TITLE
[Draft] Draft Edit - various fixes (issue 3537)

### PR DESCRIPTION
**Pull request by carlopav**
Apparently this fixes #3537 and major modification of edit tool.
I'm sorry for not being able to split in multiple commits.
Feel free to ask for whatever it's not clear.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<3537>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@carlopav JFYI 
image  
Do you mind editing the commit and doing hard push to this PR (no need to close the PR) overwriting the commit title and body like so?

```
[Draft] Draft Edit - various fixes (fixes #3537)   

Apparently this fixes #3537 and major modification of edit tool.
I'm sorry for not being able to split in multiple commits.
Feel free to ask for whatever it's not clear.
```

**Comment by carlopav** [comment]
Oops, thanks for pointing out. I changed the body from mobile but couldn't change the title. Hope to be able to do it Sunday. Sorry.

**Comment by luzpaz** [comment]
@carlopav it doesn't work by changing it through the github gui, you need to change it via git and then repush it AFAIK

**Comment by carlopav** [comment]
Thx for the tip . I'll try on Sunday and if I'm not able to do it I'll close it and open again. :)

**Comment by luzpaz** [comment]
@carlopav https://stackoverflow.com/a/12610763/1033779

**Comment by carlopav** [comment]
Done, is it ok like this?

**Comment by yorikvanhavre** [comment]
The travis error seems unrelated... Okay, merging!

**Comment by carlopav** [comment]
Great! @yorikvanhavre can you give it a try and tell me what do you think? Any comment highly appreciated :)

**Comment by brainstorm** [comment]
Coming from post https://forum.freecadweb.org/viewtopic.php?t=38737 and running FreeCAD 0.19-18524 from Homebrew I have the following backtrace when trying to edit a dimension under `Draft->Edit`:

```python
<class 'IndexError'>
Traceback (most recent call last):
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Draft/DraftEdit.py", line 272, in mouseMoved
    self.updateTrackerAndGhost(event)
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Draft/DraftEdit.py", line 306, in updateTrackerAndGhost
    snappedPos = FreeCADGui.Snapper.snap((pos[0],pos[1]),self.node[-1], constrain=orthoConstrain)
IndexError: list index out of range
<class 'IndexError'>
Traceback (most recent call last):
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Draft/DraftEdit.py", line 272, in mouseMoved
    self.updateTrackerAndGhost(event)
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Draft/DraftEdit.py", line 306, in updateTrackerAndGhost
    snappedPos = FreeCADGui.Snapper.snap((pos[0],pos[1]),self.node[-1], constrain=orthoConstrain)
IndexError: list index out of range
```

Skärmavbild 2019-10-17 kl  21 54 17

**Comment by carlopav** [comment]
@brainstorm yes that should be my fault. I'll try to fix asap

**Comment by brainstorm** [comment]
Thanks @carlopav, hope that you can reproduce it easily and happy to test any fix 👍

**Comment by carlopav** [comment]
@brainstorm I'm not able to reproduce it with 18629... can you please describe better what you were doing? and if possible try with 18629? thanks. _Draft/Edit_ is still in development and there are still lots of issues to solve.

**Pull request merged**
