### PR TITLE
[TechDraw] Improve readability of QGSPage.cpp

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9270">pipeline status</a> for feature branch [PR_9270](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9270). Pipeline [838077628](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/838077628) was triggered at [15340e2](https://github.com/FreeCAD/FreeCAD/pull/9270/commits/15340e24da1eaa660cf2f237da24527cbdb78caf). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@benj5378 Pasted failure for convenience (+ please fix trailing whitespace introduced in this PR)
```
[ 91%] Building CXX object src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/QGSPage.cpp.o
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:293:23: error: use of undeclared identifier 'i'
        if (qsName == i->data(1).toString()) {//is there a QGIV with this name in scene?
                      ^
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:294:13: error: use of undeclared identifier 'found'
            found = true;
            ^
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:964:9: error: use of undeclared identifier 'deleteParentless'
        deleteParentless(qv);
        ^
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:971:15: error: out-of-line definition of 'deleteParentless' does not match any declaration in 'TechDrawGui::QGSPage'
void QGSPage::deleteParentless(QGIView* view, TechDraw::DrawPage page) {
              ^~~~~~~~~~~~~~~~
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:977:13: error: use of undeclared identifier 'thisPage'
        if (thisPage == p) {
            ^
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:983:17: error: use of undeclared identifier 'qv'
    removeQView(qv);
                ^
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:1176:5: error: use of undeclared identifier 'insertSVGtemplate'
    insertSVGtemplate(rootGroup);
    ^
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:1206:15: error: out-of-line definition of 'insertSVGtemplate' does not match any declaration in 'TechDrawGui::QGSPage'
void QGSPage::insertSVGtemplate() {
              ^~~~~~~~~~~~~~~~~
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:1228:37: error: use of undeclared identifier 'exportDoc'
        QDomElement templateGroup = exportDoc.createElement(QString::fromUtf8("g"));
                                    ^
/home/runner/work/FreeCAD/FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp:1252:9: error: use of undeclared identifier 'rootGroup'
        rootGroup.appendChild(templateGroup);
        ^
10 errors generated.
gmake[2]: *** [src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/build.make:1143: src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/QGSPage.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6519: src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 91%] Built target FemGui_autogen
gmake: *** [Makefile:136: all] Error 2
Error: Process completed with exit code 2.
```

**Comment by benj5378** [comment]
@luzpaz only draft. Far from finished. Enjoy some pictures from me taking some days off.

**Comment by luzpaz** [comment]
What's the status on this PR ?

**Comment by benj5378** [comment]
Still relevant

**Comment by WandererFan** [comment]
closing as too stale.

**Pull request closed without merging**
