### PR TITLE
Rest Machining for Path and Path3D Operations

### PR DESCRIPTION
**Pull request by davidgilkaufman**
WIP, but mostly done. Still TODO:

- [x] make rest machining work with saving (currently it only works using operations that have generated paths since opening the file)
- [x] disable setting debug log level in Path/Op/Area.py
- [x] change UI for enable rest machining instead of multiple modes?
- [x] squash commits
- [x] Bug: path dressups mask the clearedArea property -- look into how those are implemented, and loop through sub operations

Forum thread: https://forum.freecad.org/viewtopic.php?t=78773
Issue: https://github.com/FreeCAD/FreeCAD/issues/9756

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9782">pipeline status</a> for feature branch [PR_9782](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9782). Pipeline [903682370](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903682370) was triggered at [2f826a0](https://github.com/FreeCAD/FreeCAD/pull/9782/commits/2f826a0aad4cc5f882a5de145fbd4b8476333c30). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Do you mind using `git commit --amend` and prefixing `Path:` to both commits titles ?

**Comment by sliptonic** [comment]
[REST](https://trello.com/c/kcqXkE40/1-rest)

**Comment by luzpaz** [comment]
Congrats @davidgilkaufman on your first PR in FreeCAD!

**Pull request merged**
