### PR TITLE
Gui: fix issues in selection of nested objects inside Part container

### PR DESCRIPTION
**Pull request by 0penBrain**
https://forum.freecad.org/viewtopic.php?t=77214

@realthunder may you please review ? I actually hacked this without perfect understanding of code behavior. :smile:

### CODE REVIEW

**Comment by realthunder** [comment]
Sorry for not seeing this issue sooner. My proposed fix is in #10818

**Comment by yorikvanhavre** [comment]
@realthunder 's solution seems simpler... But I let you decide @0penBrain :)

**Comment by WandererFan** [comment]
Replace by#10818

**Comment by sliptonic** [comment]
Closing in favor of #10818

**Pull request closed without merging**
