### PR TITLE
View scaling for new documents

### PR DESCRIPTION
**Pull request by DeepSOIC**
* added preference for default view scaling
* changed initial default camera orientation to trimetric (FreeCAD is first and foremost about 3D, so Top isn't a good initial value IMO).
* fix sketch from switching back to Start workbench ([this is why](https://forum.freecadweb.org/viewtopic.php?f=3&t=39143)) 
pr-view-scale

### CODE REVIEW

**Comment by vocx-fc** [comment]
Is "trimetric" a standard term? I've never heard about it. I think most commonly the words "isometric" or "axonometric" are used for this purpose.

**Comment by DeepSOIC** [comment]
> Is "trimetric" a standard term? 

I don't know, english and drawings are not my native languages. That Trimetric option has been in there for quite a long time already, btw. I'll try to dig out the thread.

**Comment by DeepSOIC** [comment]
This looks like it: https://forum.freecadweb.org/viewtopic.php?f=8&t=31000&start=40

**Comment by vocx-fc** [comment]
Thank you for the link. That thread also references this one, [Question about axonometric view](https://forum.freecadweb.org/viewtopic.php?f=8&t=11911).

And I also checked Wikipedia, [Axonometric_projection](https://en.wikipedia.org/wiki/Axonometric_projection).

It seems that the general classification is "axonometric" which has three varieties, "isometric", "dimetric", and "trimetric". I presume these are correctly implemented in FreeCAD, as discussed in the above thread. I didn't realize this at the beginning. So, I guess, everything is okay and according to standards.

I don't have an opinion on what is best to be honest. Top view works fine for me, but if most people prefer trimetric view, that's also okay.

**Comment by DeepSOIC** [comment]
I was under impression the default 'top' was selected merely a conservativeness, but rereading the thread, the impression has changed. So I can remove that part of the pull request. @yorik @wwmayer  should I change it back to Top?

This "Trimetric" is just going to be a default for newcomers. Those who like that Top view by default can just change it in preferences (and I think, no existing FC users will even have to change it, as I haven't seen the effect of my change until I went to parameter editor and deleted the relevant parameters, even though have I never consciously changed that setting).

**Comment by DeepSOIC** [comment]
Also, I noticed commit 6cb7ddc74f3ed66a9ad3e900d111e779450c6db5 is about the same stuff. It uses a different setting path. Should we use this new setting instead?

Also, it looks like that commit has a bug where it would fail with perspective camera (perspective camera has no field `height`)

**Comment by yorikvanhavre** [comment]
I would leave the default as it is now too, seems to me that's what people are used to, but I have no strong opinion on the matter.

**Comment by wwmayer** [comment]
How do other 3d applications like Blender, CloudCompare, Paraview, ... handle it? I have tested the latter and it also shows the Top view after start.

**Comment by DeepSOIC** [comment]
OnShape: trimetric
SketchUp: trimetric, as far as I remember

**Comment by wwmayer** [comment]
Merged.

**Comment by DeepSOIC** [comment]
Thanks!

**Pull request closed without merging**
