### PR TITLE
Arch: Dice3DS/dom3ds.py LGTM fix

### PR DESCRIPTION
**Pull request by luzpaz**
Following recommendations from https://lgtm.com/rules/6770081/  
BTW, I have not tested this commit +  @yorikvanhavre this file has no license header etc...

### CODE REVIEW

**Comment by vocx-fc** [comment]
You should always test the changes locally before submitting. This particular change doesn't seem to be critical and should work fine, but still, you should compile FreeCAD every time and see if it doesn't fail when you compile, and when you load Arch (or the corresponding workbench), and when you load the module, like `import Dice3DS.dom3ds.py.`

**Comment by luzpaz** [comment]
I'm working on it. Trying to get the dependencies right + the length of compile time (haven't used `ccache` yet), is quite a barrier to overcome.

**Comment by vocx-fc** [comment]
If you modify the Python files, the re-compilation shouldn't take long, because it should only copy the new files on top of the old files.

**Comment by yorikvanhavre** [comment]
In any case, that's why we have CI tests too... But indeed it's always better to test locally, less unnecessary burden on the CI servers

**Comment by yorikvanhavre** [comment]
Note that the dice3ds stuff is mostly unmaintained now, and does not work anymore with py3. So I think sooner or later we'll kick it out, probably more interesting to use one of these universal convertors like assimp under the hood...

**Pull request merged**
