### PR TITLE
Core : Tree: Add 'Properties' action in contextual menu. Opens a prop…

### PR DESCRIPTION
**Pull request by PaddleStroke**
Tree: Add 'Properties' action in contextual menu. Opens a property dialog.
Does not affect the 'Property View' at all.
image

Fixes https://github.com/FreeCAD/FreeCAD/issues/11072

### CODE REVIEW

**Comment by adrianinsaval** [comment]
could we insert the property view inside the task view instead of opening an independent window?

**Comment by PaddleStroke** [comment]
It is an interesting idea. @obelisk79 @MisterMakerNL @kadet1090 @qewer33 ?

**Comment by kadet1090** [comment]
> could we insert the property view inside the task view instead of opening an independent window?

What would be the reason for that? IMHO if anything we should create more more capable docking system that allow to put any panels as tabs or something like that.

**Comment by MisterMakerNL** [comment]
> could we insert the property view inside the task view instead of opening an independent window?

No this won't work the workflow I had in mind was, if you need to change properties you open the properties window, do what you want close it when you are done.
If you dock it with task-view, you will close the task view with the properties. (or you need to make something complicated that only closes the properties panel, but I think it will get confusing)
Keeping it open by default is a waste of screen-space. Unless you need it a lot then you can still use the panel. Especially with the new overlay system where the task-view auto-hides.

I think this fix looks awesome! It cleans up the UI massively. Very nice work! Very happy with this, hope others will like it too!

**Comment by sliptonic** [comment]
I like this a lot.
The handling of property pane has always been sub-optimum.   It always occupies real estate even if the user doesn't need it.  When the user DOES need it, it's too small and always requires scrolling.   This is a very nice alternative but it needs to work very reliably and with good keyboard acceleration.

There's an accelerator key (F6) showing in the context menu but it doesn't work to open the property dialog.

**Comment by PaddleStroke** [comment]
I think there is a conflict with another tool for F6.
I am not sure what shortcut we can assign. I would have gone with F1 but it's help. F3 F4 are doing some overlay stuff. etc.
Is there a standard key for property?

**Comment by PaddleStroke** [comment]
Reading online Alt+Enter seems to be a 'classic' for properties. Any thoughts on that?

**Comment by sliptonic** [comment]
Alt-Enter is ok if it's standard.   It's two keys for something that is likely to be common.   'P' for properties would be nice and 'I' for info if we ever have a replacement for FCInfo.

**Comment by sliptonic** [comment]
We should probably have some design guidance on accelerator assignment

**Comment by adrianinsaval** [comment]
Alt+Enter is good IMO, my file manager (kde's dolphin) has that shortcut

**Comment by sliptonic** [comment]
Can you make the panel remember the last place and size when closed and reopened?

**Comment by kadet1090** [comment]
> I think there is a conflict with another tool for F6. I am not sure what shortcut we can assign. I would have gone with F1 but it's help. F3 F4 are doing some overlay stuff. etc. Is there a standard key for property?

We can always change the overlay stuff it isn't stable yet so we can do that without much problem., Besides, I doubt that anyone will notice lack of this shortcuts and it Wil free up those keys.

**Comment by adrianinsaval** [comment]
We could do that but using something that's standard is better

**Comment by PaddleStroke** [comment]
So I was starting to follow @sliptonic idea and save the dialog size and position. And from 7 lines of code, it started to be a custom QDialog class that kept growing.

Which made me think again about what @adrianinsaval said in the issue : why making a new view when we already have one.

My reasoning was that making a dialog was only few lines of code and clean. But if we start adding features to the dialog then it is not true anymore. And it becomes obvious that the right choice is not introducing a new dialog, but instead fix the overlay stuff so that the current PropertyView overlay dialog can be used. So here is a list of things that seems necessary : 
- The property action just make the PropertyView visible.
- PropertyView should save its state : dockDialog or overlay dialog? Position, size etc.

On a side note, I cannot get Alt + Enter to work. Needs a bit more of digging apparantly.

**Comment by PaddleStroke** [comment]
Ok so here is what I have done : 

- Added a 'Std_Properties' command that shows the property view. (this is required for the shortcut to work).
- Command added to the Edit menu.
- Command added to the tree item right click menu.
- Alt + Return shortcut working.
- The command only toggles the visibility of the property view.
- Bonus: Save the width of the first column when it is resized. Before it would always reinitialize on restart.

So where does that brings us ? You can achieve the same as with the QDialog I made before by dragging the property view outside of a dock area and resizing it : 
image

The issue is that the system does not save the fact that property view is a floating window. So on restart the system will forget and Alt+Return will open the PropertyView as a dock-widget docked on the left.

So what we need is to save in preference the position and size of the property view (docked vs floating vs overlay). But this is probably overlapping @kadet1090 PR : https://github.com/FreeCAD/FreeCAD/pull/11998 so I don't want to change something at the same time. Any thoughts on this btw @kadet1090 ?

I would say that this PR can already merge as it is, the save fix not being overlapping this PR.

**Comment by Roy-043** [comment]
Another issue: AFAICT the command does not do anything if "Tree view mode" is set to "Combo View".
https://wiki.freecad.org/Preferences_Editor#General_2

**Comment by Roy-043** [comment]
The command does not behave as a toggle. It does not hide the Property View. I don't understand the logic that pre-selecting an object is required to enable this command. The command can work even if there is no document, so why not allow that?

**Comment by PaddleStroke** [comment]
The logic was to have the same as most other software where you usally right click on something, select properties and get a property dialog.
It was not meant as a 'toggle property view visibility'.
In fact initially it was opening a QDialog showing the properties of the object. But then it was noticed that QDialog was kind of the same as the current property view when set as overlay.

Anyway @pieterhijma is working on a 'Property Manager' dialog. I think that when that merge, this command should then be changed to open the new 'Property Manager' instead of showing the property view.

**Pull request merged**
