### PR TITLE
small corrections of German translation in FEM Gmsh

### PR DESCRIPTION
**Pull request by e-dub**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7157">pipeline status</a> for feature branch [PR_7157](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7157). Pipeline [584302995](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584302995) was triggered at [d363149](https://github.com/FreeCAD/FreeCAD/pull/7157/commits/d363149aa7ccc534324f266856834c4b8553c966). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Thank you but translations are managed through [Crowdin](https://crowdin.com/project/freecad). Please open an account there and make the modifocation

**Comment by donovaly** [comment]
> Guess that isn't the policy anymore?

I think both is OK. For example wwmayer also directly edited the *_de.ts file recently. My knowledge is that the *_de.ts is what counts. You can edit it directly or via Crowdin,
@yorikvanhavre , is this correct?

**Comment by yorikvanhavre** [comment]
i think everytime @wwmayer has edited the .ts file directly he also edited on crowdin.. Yes, the important is to edit on crowdin, because if you edit the ts file without doing it on crowdin, your changes will pe overwritten next time we merge the crowdin ones

**Comment by donovaly** [comment]
OK, so @e-dub , please make your change again in Crowdin.

However, since we don't update the translations from Crowdin to the stable release, I think also changes directly here to the .ts file is fine. This way I already could backport the changes translation to FC 0.20. (the translations were are even wrong and users should not have to wait a year to the next major release to get translation fixes)

**Pull request merged**
