### PR TITLE
Toponaming: Restore code for instant sketch position updates

### LINKED ISSUE #14837: No instant Sketch position updates when position values are changed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I noticed that in actual dev versions, sketches don't move while you alter the position values. Only after pressing Enter and recalculating the model the position gets updated. That was different in 0.21, where you could see the movement immediately, which is crucial for careful placement. 
For example: make a sketch in 0.21, go to the tree view, select it and alter the position (using the mousewheel for example)
In 0.22, I can alter the values, but the sketch sits in its old position until I hit enter or click in the 3D view

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37819 (Git) AppImage
Build type: Release
Branch: main
Hash: 2ca9b6ef8036d5fd808f01205b66eb0424059e21
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.39
  * fasteners 0.5.24
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bgbsww**
Fix #14837.

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
Can confirm this should fix the issue. @bgbsww are you sure this is the only part that needed to be taken from the old code? There is also some hiding/unhiding going on.

**Comment by bgbsww** [comment]
To fix 14837 it was sufficient.  But you are absolutely correct, we can avoid future regression complaints by restoring the hide/unhide of unavailable options.  I'll add that, was looking too narrowly.

**Comment by AjinkyaDahale** [comment]
Thanks. I tried a little to remove attachment from body and the property would hide alright. Perhaps it called a recompute from somewhere else, so I wasn't sure whether or not it's needed. In any case thjs redundancy likely won't hurt 🤞.

**Comment by AjinkyaDahale** [comment]
@bgbsww maybe also a test (or series of tests)? In python set attachment offset and see if placement changes?

**Comment by PaddleStroke** [comment]
Any reason you did not used updatePropertyStatus and instead copy pasted the block ?
The only difference I can see is that in your copy pasted blocks it does not updatePropertyStatus of the base. Because updatePropertyStatus(false) is first updating the _props then after the baseprops, while your code only do it for _props.

Was this intended or should we just call updatePropertyStatus ?

**Pull request merged**
