### PR TITLE
TechDraw: Fixes snapping bugs.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fixes https://github.com/FreeCAD/FreeCAD/issues/14325 
Fixes https://github.com/FreeCAD/FreeCAD/issues/14333

1 - Dimensions of different types (Distance / DistanceX) not snapping: Now if the labels are parallel then it snaps.
2 - Center snapping not accurately on center : There was a problem in how the center of the label was defined, which did not take into account the angle of the label.
3 - For small dimensions the snapping zone is small : Instead of using a % of the dimension, we use a fraction of the cascade spacing variable which is similar to the font size.

### CODE REVIEW

**Comment by maxwxyz** [comment]
@PaddleStroke does this also fix https://github.com/FreeCAD/FreeCAD/issues/13831

**Comment by PaddleStroke** [comment]
No, https://github.com/FreeCAD/FreeCAD/issues/13831 is too big of a feature to be included here.

**Comment by maxwxyz** [comment]
@PaddleStroke vertical dimension text snapps still not to center:
grafik

shall I create a new issue?

**Comment by PaddleStroke** [comment]
Yes you can do.
I think the label is being centered correctly now, but the text is maybe not at the label center. Not sure.

**Pull request merged**
