### PR TITLE
[Sketcher] Address issue #17629, where Attach sketch command allows s…

### PR DESCRIPTION
**Pull request by mwganson**
…ketch to be attached to itself

To reproduce the issue, open attached file, select the circle in the 3d view, in Part Design Sketch menu -> select Attach Sketch command, in the dialog select the circle sketch.  This leads to a circular dependency graph must be a DAG error.  The solution implemented in this PR is to remove any selected sketches from the list in the dialog so that they are not available for selecting.

[sketchmap.FCStd.remove.zip](https://github.com/user-attachments/files/17614867/sketchmap.FCStd.remove.zip)

Another small change is to allow the command to be active when there are document objects of type Part::Part2DObject and not just sketches.  The body of the command supports Part::Part2DObjects, so there is no need to disable the command in such cases where there are no sketches, but there are some part2d objects.

### CODE REVIEW

**Comment by mwganson** [comment]
In testing this function I found another issue related the attachment engine, probably TNP related.  I get this error message in the report view:

`PositionBySupport: Null path in AttachEngine3D::calculateAttachedPlacement()!`

The model is not broken, so the error message can probably be disabled.

**Comment by mwganson** [comment]
Issue #17629 isn't properly linked because it appears too soon in the commit message, so this message here is to get the link working.

**Comment by yorikvanhavre** [comment]
Will give it a test spin

**Comment by yorikvanhavre** [comment]
Okay tested, it's working fine!

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
