### PR TITLE
Add HalfTurnLeft landing stairs basic feature.

### PR DESCRIPTION
**Pull request by paullee0**
- HalfTurnRight, stairs alignment etc. 'fix' added in 'later version' in my local machine not yet in this commit

Discussion posts :-

https://forum.freecadweb.org/viewtopic.php?f=23&t=29358&sid=bbca78d86eda8a6f8837fc2901d88be7#p240745
https://forum.freecadweb.org/viewtopic.php?f=23&t=29358&start=70#p247814

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
@yorikvanhavre This one is yours :)

**Comment by paullee0** [comment]
While Yorik may be reviewing if this proposed pull request is useful... 

- The current 2 commits are more of trials / tests on my understanding how PR / Commit works as I read through the Github help, colleague's discussion board wiki
- I just start to learn python, the original discussion want to solicit peoples' comments if the proposed code is written properly, features useful, what features maybe wanted when I started to look at the codes...
(... not figured out what this mean / how exactly works "...QT_TRANSLATE_NOOP("App::Property","The thickness of the treads")...)
- Still want to have comments on above aspect most importantly :)

e.g. the way I 'connect' different sections of Stairs, concept using Arch Pipe as railing etc in 'later' discussions / 'versions'... may have problems?

**Comment by yorikvanhavre** [comment]
This code looks totally OK (You're doing fine with python/git/github too btw, congrats), so I'll merge it. About your other questions, they are probably better to handle on the forum, but basically the stairs tool was very embrionary, and you are doing a great job developing it into something more mature. So personally I am fine with how you decide to do railings, etc. If someone else  or even yourself thinks it can be better in the future, it can always be upgraded into something better.

Like @wwmayer told me many years ago, the really important point when coding is to add enough comments in your code so other people reading you code can more easily understand how it works.

About QT_TRANSLATE_NOOP("App::Property","The thickness of the treads") we use that in a couple of specific places (namely the text of a FreeCAD command and the description text of properties), it will make the text picked by the script that gathers strings to be translated, but it won't translate it at runtime (like a translate() function would do). Because it will be handled by FreeCAD itself. We do this to make sure the english description is saved in the FreeCAD file, not the translated version. So you can fire up FreeCAD in another language and have the property description translated

**Comment by paullee0** [comment]
Ok thanks taking time to advise :)

I am tracking the changes(addition/omission) between ~ 17 different 'versions' in my local pc which is unfortunately based on 0.17 before it enable me to add back portion by portion to current 0.18.

1. I would take the chance to keep some of my previous comments which I may have taken out.
2. Not figured out yet exactly difference/best workflow between PR and Commit, I would try PR a small portion of code updates with recognisable feature / bug fix for the time being.
3. Though (2) above may introduce some bugs in-between 'versions' that may only be fixed in 'later versions'.  And more nos. of PR.

See how it goes then :)

**Comment by yorikvanhavre** [comment]
The easiest I think is to use git branches as much as you can, each "feature" being developed in a different branch Then you can do all kinds of interesting things like rebasing one branch on another if you need features from it, etc. Don't worry too much about doing many commits when working, because you can easily squash several commits into one when you are ready to send a PR

**Pull request merged**
