### PR TITLE
Assembly: Limits: Set one checkbox for each limit.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Set one checkbox for each limit.
Fixes https://github.com/FreeCAD/FreeCAD/issues/14690

https://github.com/FreeCAD/FreeCAD/assets/19984177/c093beee-7904-42e8-b390-4fd20d4eb73b

### CODE REVIEW

**Comment by furgo16** [comment]
If I understand the screenshot correctly, if a limit's checkbox is not checked, should its value not be grayed out (i.e. disallow input)? Otherwise the user might mistakenly enter a value that is effectively ignored.

**Comment by PaddleStroke** [comment]
The spinbox is disabled, it's open dark theme that is wrong here. Check the second screenshot

**Comment by pierreporte** [comment]
The text is wrong in English: it should be min/max length and min/max angle.

**Comment by PaddleStroke** [comment]
Ok I'll update the text

**Pull request merged**
