### PR TITLE
Option to opt-out from using a Linux desktop icon theme

### PR DESCRIPTION
**Pull request by triplus**
https://forum.freecadweb.org/viewtopic.php?f=4&t=35624

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Why is that exactly? I think the default way for linux apps is usually to adopt system theme... IMHO it should be opt-out, not opt-in

**Comment by triplus** [comment]
I can change it to opt-out, as previously on Linux this wasn't possible, you basically couldn't opt-out. And therefore things would still improve, being able to opt-out.

The reason i went with opt-in is i followed the debates on the forum and there was a plethora of people considering this behavior being a bug in need to get fixed, asking when it will get fixed. Due to i guess poor FreeCAD icon support in Linux icon theme packs. You get a couple of icons, such as Open, Save, Full Screen and usually it ends there. FreeCAD icons and such icons from themes are usually styled completely differently and people feel they lost FreeCAd icons, when in reality that is just how icons from the icon pack look, or some fallback icon gets used and it looks completely off. If you feel there should be more debate i can initiate that on the forum in the linked thread.

**Comment by triplus** [comment]
Note that i updated the PR and now this PR adds an ability to opt-out from using a desktop icon theme, by default nothing changes, desktop icon theme icons will still get used.

**Comment by f3nix** [comment]
Hi @triplus.

I have cherry picked this commit and it looks that the "Fit all" and "Fit selection" icons are now back :)
But all file dialogs have no icons now (I have checked native and qt). Are there any additional steps needed to make it work?

Thanks.

Cheers,
Mateusz

**Comment by triplus** [comment]
Hi Mateusz and thanks for testing.

Will take a look, likely tomorrow, and will report back.

**Comment by triplus** [comment]
Could you copy and paste this in FreeCAD Python console and provide the output for standard FreeCAD version and for your custom build with this PR included.

```
from PySide import QtGui
QtGui.QIcon.themeSearchPaths()
```

Thanks.

**Comment by f3nix** [comment]
Hi.
Here is the output with ThemeSearchPaths=false
`[':/icons']`

Here is the output with ThemeSearchPaths=true
`['/home/f3nix/.local/share/icons', '/usr/share/icons', '/var/lib/snapd/desktop/icons', ':/icons']`

FreeCAD version:

```
OS: Debian GNU/Linux bullseye/sid (KDE//usr/share/xsessions/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.19492 (Git)
Build type: Debug
Branch: master
Hash: 0532df4937dfb1bfcf09fad4949d1464bcf7f5dd
Python version: 3.7.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.3.0
Locale: Polish/Poland (pl_PL)
```
I have deleted my .FreeCAD folder to make sure that nothing else is messing with it (same result).

Cheers,
Mateusz

**Comment by wwmayer** [comment]
Since Qt 5.12 there is a new function QIcon::setFallbackThemeName which might solve this problem.
So, what happens when you do:
`
from PySide import QtGui
QtGui.QIcon.setFallbackThemeName("FreeCAD-default")
# optionally
QtGui.QIcon.setThemeSearchPaths(QtGui.QIcon.themeSearchPaths() + ":/icons/FreeCAD-default")
`

But what I still don't understand is why on some systems the icons do not appear. Is this distribution or DE specific?
At least on none of my Linux installations ((X)Ubuntu & XFCE) I have ever seen this problem. There I see the system icons for the standard stuff like New, Open, Save, Undo, Redo, ... and for all other stuff I get the FreeCAD icons.

**Comment by wwmayer** [comment]
Merged.
I slightly modified the PR.

**Comment by triplus** [comment]
Great. If people will still have issues with icons in file dialogs i will try to find a solution or an explanation for that.

@f3nix just to make sure it's about file dialog icons and not the file toolbar icons? As that could be related to not yet including https://github.com/FreeCAD/FreeCAD/pull/2940 in your local build.

**Comment by f3nix** [comment]
Hi.

@triplus 
Yes. It is about file dialog icons. I see something like this has also been reported here: https://forum.freecadweb.org/viewtopic.php?f=4&t=35624&start=10#p304122

I have also noticed some warnings in the console (did not catch them previously):
```
Icon theme "Default" not found.
"Nie można wejść do katalogu tags:/."
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
```

freecad-file-dialog

@wwmayer 
I have checked with Xfce and the problem does not exist. You were right to suspect the DE.
From the forum thread it looks like Plasma and Gnome are affected.

Cheers,
Mateusz

**Comment by triplus** [comment]
What happens if you remove the Inherits=Default line:

https://github.com/FreeCAD/FreeCAD/blob/master/src/Gui/Icons/index.theme

P.S. If that won't help i will take a look on how icons are added in the file dialog in the first place.

**Comment by f3nix** [comment]
@triplus 
The first warning goes away.
The rest stays like before.

The first line says: "Can't enter tags:/ directory.

```
"Nie można wejść do katalogu tags:/."
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
QPixmap::scaleWidth: Pixmap is a null pixmap
```
Cheers,
Mateusz

**Pull request closed without merging**
