### PR TITLE
PartDesign. Allow 0 distance if Occurrences is 1 in pattern

### PR DESCRIPTION
**Pull request by Jolbas**
Bypass all checks if Occurrences is 1.
This will save some unnecessary checks but my main reason is to allow an expression on LinearPattern property Length that evaluates to 0 if Occurrences is 1. This happens for example if you want the the Length including the length of the arrayed feature to be proportional to occurrences.

### CODE REVIEW

**Comment by luzpaz** [comment]
Please prepend `[PartDesign]` to commit title  
Screenshot_20230303_164407

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8732">pipeline status</a> for feature branch [PR_8732](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8732). Pipeline [795823978](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/795823978) was triggered at [2c104d1](https://github.com/FreeCAD/FreeCAD/pull/8732/commits/2c104d14d329d6679bc56548f7d2b16b9a4c10e5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8732">pipeline status</a> for feature branch [PR_8732](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8732). Pipeline [795849825](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/795849825) was triggered at [d0c68d6](https://github.com/FreeCAD/FreeCAD/pull/8732/commits/d0c68d64166f45d3a784cc02054222d8ac61fb73). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Jolbas** [comment]
Something went wrong with an old branch with the same name??

**Comment by adrianinsaval** [comment]
> This happens for example if you want the the Length including the length of the arrayed feature to be proportional to occurrences.

I don't know why you closed the PR but as a workaround I think you could use an if in the expression to give a bogus length when occurrences is 1

**Comment by Jolbas** [comment]
Yes, thanks, I did use that workaround but thought it should work so I made this PR. I closed it because the branch broke. A local branch with the same name corrupted it and rebase and reset didn't work. I can redo it but now I'm looking into  make it possible to set occurences to zero too. Which I think would be useful if for example the amount of features depends on the total length.

**Pull request closed without merging**
