### PR TITLE
Solver: Pass map by const reference to avoid performance penalty

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
================================================================

Credit goes for forum user acolomitchi:

https://forum.freecadweb.org/viewtopic.php?p=648807#p648807

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8070">pipeline status</a> for feature branch [PR_8070](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8070). Pipeline [729021811](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/729021811) was triggered at [8bdceb8](https://github.com/FreeCAD/FreeCAD/pull/8070/commits/8bdceb847d1caf11cecfc31d8db2198537842a29). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@abdullahtahiriyo do you mind also substituting single whitespace for the tabs? TIA!
image

**Comment by abdullahtahiriyo** [comment]
@luzpaz 

I saw your comment after merging (the page did not somehow have your comment, but it did have all the test passed).

Yes, this PR did not address the format issues the file had (and could have had a whitespace only commit).

I think it is appropriate to do that substitution (and even other formatting ones). Somehow I am having troubles configuring my IDE, KDevelop, to do this for me. I have configured it with clang format file, but it seems not to work. Hopefully Santa will bring me some extra time to look it more in depth and fix it.

Because of your screenshot, I now discovered that there is a "Tabs" entry in GH's CI. I would have liked that this were a little bit more visible. Are you checking this for every PR or do you have a trick?

**Comment by luzpaz** [comment]
@abdullahtahiriyo actually I just learned about check annotation file by accident! I was doing a superficial review of your submission and saw the link in the upper right hand corner of each code check
image
Which led me to https://github.com/FreeCAD/FreeCAD/actions/runs/3750568314/jobs/6370448347
I found the newline and tabs syntax checker in the list:  
image
That's a lot more convenient then going through the code submission to find instances.

**Pull request merged**
