### PR TITLE
Update Draft WB icons

### PR DESCRIPTION
**Pull request by marcuspollio**
Slight adjustments to some Draft WB icons for better consistency :

- Ellipse: make outline width consistent
- Label: make outline width consistent
- Snap_Dimensions, CubicBezCurve and Dimension: make text more readable
- SubElement Highlight and Edit: make outline width consistent and tweak pencil position for consistency
- Layer/VisGroup: tweak layers pile so it's evenly distributed and make LayerManager 64px based with consistent Document element
- N-Curve, N-Linear and N-Polygon: make outline width consistent and add highlights for better dark/light themes support
- Snap_Grid and Grid: tweak line ends and cleanup alignments

Also fix some Core and TechDraw WB icons that use the same elements for consistency.

Also save icons as Plain SVG, cleanup unused resources and add a bit of metadata when missing.

### CODE REVIEW

**Comment by Roy-043** [comment]
Some background info:
* Currently Draft_Apply.svg is more or less a copy of the Std_SetAppearance icon (which makes some sense). And Draft_Label.svg is a copy of the TechDraw_RichTextAnnotation icon.
* Draft_Apply.svg is currently used for 2 commands: Draft_ApplyStyle and Draft_SetStyle.
* IMO we should consider creating 4 style commands:
    * For objects: Draft_ObjectStyleEditor and Draft_ApplyObjectStyle. But maybe those should be Core functions?
    * For annotations: Draft_AnnotationStyleEditor and Draft_ApplyAnnotationStyle. For the icon of these I would include the letter A.

With that in mind I would not change Draft_Annotation_Style.svg and Draft_Apply.svg. The added sheet does not have the 'manager' connotation for me. But I am not a GUI specialist.

Regarding the blue pencil icons:
Black lines on dark blue are not the most legible. Draft_Edit.svg would improve if the pencil does not overlap the polygon shape. Now that the pencil is horizontal it is noticeable that its point is not symmetrical. You may also want to look at the pencil in Std_UserEditModeColor.svg etc.

**Comment by marcuspollio** [comment]
Hi @Roy-043 , thank you for the feedback and some background !


> Currently Draft_Apply.svg is more or less a copy of the Std_SetAppearance icon (which makes some sense). [...]
> 
> Draft_Apply.svg is currently used for 2 commands: Draft_ApplyStyle and Draft_SetStyle.
> 
> IMO we should consider creating 4 style commands:
>       
> For objects: Draft_ObjectStyleEditor and Draft_ApplyObjectStyle. But maybe those should be Core functions?
> For annotations: Draft_AnnotationStyleEditor and Draft_ApplyAnnotationStyle. For the icon of these I would include the letter A.
> 
> With that in mind I would not change Draft_Annotation_Style.svg and Draft_Apply.svg. The added sheet does not have the 'manager' connotation for me. But I am not a GUI specialist.

Ok, so I removed Draft_Annotation_Style and Draft_Apply changes from this PR. We can always revisited them later when the changes you propose above are implemented.

> And Draft_Label.svg is a copy of the TechDraw_RichTextAnnotation icon.

I made the TechDraw one consistent too.

> Regarding the blue pencil icons: Black lines on dark blue are not the most legible. Draft_Edit.svg would improve if the pencil does not overlap the polygon shape. Now that the pencil is horizontal it is noticeable that its point is not symmetrical.

I improved them regarding this aspect and cleaned the pencil paths, also making it symmetrical.

> You may also want to look at the pencil in Std_UserEditModeColor.svg etc.

I tweaked all icons using the pencil I could find, like Std_UserEditModeColor, Std_UserEditModeCutting.svg, Std_UserEditModeDefault.svg, Std_UserEditModeTransform.svg. Also simplified the scissors and palette paths while I was on it.

I'd like to squash all my commits into one, so it's easier to compare only once all changes, but I do not succeed to do it on my end with GitHub Desktop (I get this error "Unable to squash. Squashing replays all commits up to the last one required for the squash. A merge commit cannot exist among those commits").
Any clue how to do it ?

**Comment by Roy-043** [comment]
You have changed more icons, I did not expect that, but doing so does make sense. Thanks.

I have two remaining comments related to the Draft icons:
Draft_Edit.svg: the shape below the pencil is too triangular. Maybe use a scaled down version of the previous shape instead?
Draft_LayerManager.svg: the layers are not spaced evenly (was also the case in the old version).

Other than that this looks just fine to me. Thanks again.

**Comment by marcuspollio** [comment]
Hi @Roy-043 thank you for the comments !

> I have two remaining comments related to the Draft icons: Draft_Edit.svg: the shape below the pencil is too triangular. Maybe use a scaled down version of the previous shape instead?

I now reused a similar-ish shape to the original one.

> Draft_LayerManager.svg: the layers are not spaced evenly (was also the case in the old version).

Wow, you have an accurate vision, luck you ! =D I tweaked them so it's better distributed, in all 3 icons showing a pile of layers.

> You have changed more icons, I did not expect that, but doing so does make sense. Thanks.

I don't know what's best about these changes touching separate "areas" ? Should I make 3 different PR ?

**Comment by Roy-043** [comment]
This PR does not follow the prescribed procedure. I do not think that is a big issue here (everybody still has to get used to the new rules anyway). IMO this PR can be merged. I am not going to do that myself since this PR is not restricted to the Draft WB. The final call should be made in the next merge meeting (usually on Monday). Thanks again.

**Comment by maxwxyz** [comment]
@marcuspollio Draft_...

- ...N-Curve
- ...N-Linear
- ...N-Polygon

could be revamped too, they are too thin and have no highlight/shadow to be visible in light and dark themes (compare e.g. with Draft_Offset)

**Comment by marcuspollio** [comment]
Hi @maxwxyz 

> Draft_N-Curve, N-Linear, N-Polygon could be revamped too, they are too thin and have no highlight/shadow to be visible in light and dark themes (compare e.g. with Draft_Offset)

I tweaked them too in the last commit. To be honest, I've never used them, and don't even know what tool/command they're used for .

**Comment by FEA-eng** [comment]
Nice. Especially the ellipse icon is currently bad. But maybe the Bezier curve icon could be improved as well - 3 is barely visible there. Like 1.00 in Dimension.

**Comment by marcuspollio** [comment]
Hi @FEA-eng , thanks =D

> [...] the Bezier curve icon could be improved as well - 3 is barely visible there

What would you suggest ? On my side, it's fairly ok :

Bezier

**Comment by FEA-eng** [comment]
For me it looks like this:

Draft icons

The icons with the default settings are so small that numbers like this (including the one in the Dimension icon) are poorly visible and blurred.

**Comment by yorikvanhavre** [comment]
In any case I guess it's better than what we have now, so I wold merge this already, and we work further :) Unless you want to do some more here, @marcuspollio ?

**Pull request merged**
