### PR TITLE
[Arch] fix Arch_Site

### PR DESCRIPTION
**Pull request by Roy-043**
PR to fix several Arch_Site issues:
* A site's 3D representation would show 'ghosts' of the objects in its Group if Terrain was None.
* Wrong calculation of Perimeter.
* 3D Transformations were not correct if a site did not have a default position.

Forum topics:
https://forum.freecad.org/viewtopic.php?t=75658
https://forum.freecad.org/viewtopic.php?t=75883

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8409">pipeline status</a> for feature branch [PR_8409](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8409). Pipeline [772850179](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/772850179) was triggered at [a7b3fab](https://github.com/FreeCAD/FreeCAD/pull/8409/commits/a7b3fabac03cf9921624697c8d38267049154234). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Roy-043** [comment]
I have to look at the transformations again. The new behavior of the site is different from f.e. a wall object.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8409">pipeline status</a> for feature branch [PR_8409](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8409). Pipeline [775324636](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/775324636) was triggered at [72849c5](https://github.com/FreeCAD/FreeCAD/pull/8409/commits/72849c53d52c11d158e3aced1413bdf429152b0d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Interesting workaround with the terrain switches... I bumped into the same issue with nativeIFC... provisorily solved by adding a fake shape.

Ideally the group extension shouldn't build a coin repr of its children by default. Or at least offer to disable that behaviour

**Pull request merged**
