### PR TITLE
FEM: [skip ci] fix grammar for console message

### PR DESCRIPTION
**Pull request by luzpaz**
Small grammar fix

---

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by donovaly** [comment]
What is the grammar mistake? I am no native speaker but your change seems a matter of taste. No binary is as clear as missing binary.

**Comment by luzpaz** [comment]
I'm not certain it is a grammatical issue, honestly. But 'No or wrong' seems simplistic and lacking technical specifications. It read as of it was written by a non-native speaker.

**Comment by donovaly** [comment]
> But 'No or wrong' seems simplistic and lacking technical specifications. It read as of it was written by a non-native speaker.

Are you a native speaker?
Most users are non-native speakers so it is not too bad to use simple wording. But here i really cannot see that "no binary" is lacking technical specification. There is, just no binary and this is why you get the error.

**Comment by chennes** [comment]
I am a native speaker, and I agree that the language in the PR is more idiomatic. I suggest merging it.

**Pull request merged**
