### PR TITLE
[For 0.19] PathSurface: Add StepDown support

### PR DESCRIPTION
**Pull request by Russ4262**
Add StepDown support for path surface operation.
A low-level optimization algorithm is included.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by Russ4262** [comment]
I have already begun additional improvements since this PR.  Should I just open another PR when I have the next update ready?  I will need assistance with modifying the QT panel file referenced in the PathSurfaceGui.py script -- FreeCADGui.PySideUic.loadUi(":/panels/PageOpSurfaceEdit.ui").
I need to add some additional user inputs in the PathSurface settings window.

Thanks for your help!
Russ4262

**Comment by sliptonic** [comment]
It depends on how long you expect it to take.  You can continue to push to the branch that the PR is made from and the changes will be included in the current PR. This will also restart the automatic tests. If you think it's a couple days until the next part is ready, Make a note to hold the PR pending everything.  If it's going to be a while, do a new PR.  BTW, I'm on IRC and in the gitter room.  Feel free to ping me there for help with the UI stuff.

**Comment by Russ4262** [comment]
I located the necessary panel UI file I was looking for. I added a selection box.  I then updated the pathsurfacegui.py file to match.
I added my recent updates to the existing PR branch:
-- PageOpSurfaceEdit.ui - Added QComboBox for completion mode selection in UI
-- PathSurfaceGui.py - Connected QT form to signals and inputs
-- PathSurface.py - Updated to use the new UI completion mode selection box input

I also sent a PM to sliptonic on the FC site, asking for additional help with general communication for collaboration.

**Comment by sliptonic** [comment]
Please hold this PR pending further review.
Russ, This is looking interesting. I'd like to chat more.  I didn't get the PM but have sent you one myself.

**Comment by Russ4262** [comment]
I implemented the PathUtils.depth_params() to control step down.

**Comment by yorikvanhavre** [comment]
In any case, as this PR is a new feature, it won't be merged before the 0.18 release. So feel free to add more commits to it...

**Comment by Russ4262** [comment]
I have added features for 4th axis 3D surfacing.  Options are available for linear indexed, parallel-to-axis-of-rotation scans and circular, perpendicular-to-axis-of-rotation scans.  I would ask the FC community to assist in debugging before the PR is merged.  Thanks.

**Pull request closed without merging**
