### PR TITLE
Boost 1.73 fix for placeholders

### PR DESCRIPTION
**Pull request by hobbes1069**
Should be backwards compatible to Boost 1.60.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by vocx-fc** [comment]
Your changes are pretty small, you should squash your three commits into one.

**Comment by vocx-fc** [comment]
Unit test failure.
```bash
ERROR: testFunctions (TestSpreadsheet.SpreadsheetCases)
Test all built-in simple functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Spreadsheet/TestSpreadsheet.py", line 268, in testFunctions
    self.assertTrue(math.isnan(sheet.B6))
TypeError: a float is required
```

**Comment by hobbes1069** [comment]
The failure doesn't appear to be related but I'm not an expert by far. Without this patch, FreeCAD fails to build with Boost 1.73.

**Comment by vocx-fc** [comment]
Werner just made a change to some NaN code, 45c2e5cb21e. I wonder if it's related.

**Comment by wwmayer** [comment]
200c7c7e0

**Comment by wwmayer** [comment]
@vocx-fc see 89ddab33f

**Pull request closed without merging**
