### PR TITLE
[Path][DO NOT MERGE] Toolbit UI improve

### PR DESCRIPTION
**Pull request by Schildkroet**
Improved GUI for Toolbit Library. All libraries in path are now listed (like in legacy tool manager) and don't need to be opened file by file.

toolbit

### CODE REVIEW

**Comment by sliptonic** [comment]
This is great!  I'm glad to see you're working on the UI.  

I have a number of questions about the current UI, including your improved version.  I also have some improvements to toolbit in process.  Maybe we can work together and get everything into one PR.  

If that's ok with you, please make this PR a draft PR.

**Comment by Schildkroet** [comment]
Yes, this sounds good. I planned to contact you anyway, since i have a lot of questions.
How can i make this a draft?

**Comment by sliptonic** [comment]
> Yes, this sounds good. I planned to contact you anyway, since i have a lot of questions.
> How can i make this a draft?

Hmm.  I don't think you can.  I found an open issue with github.   You can create a new pr as a draft but you can't convert an existing one to a draft.  For now, just add 'draft' to the title

**Comment by vocx-fc** [comment]
> For now, just add 'draft' to the title

Honestly, this is more confusing than it is helpful given that we have actual Draft Workbench related pull requests that are ready to merge.

You should add a better description like "do not merge, work in progress".

**Pull request closed without merging**
