### PR TITLE
[Tools] Refactor updatets to support two-lang mods

### PR DESCRIPTION
**Pull request by chennes**
The script to extract translation strings from source code files was designed to skip the C++ translations of directories with Python. In some cases this was manually worked around, but in others it was not. This PR is an attempt to refactor that code to ensure that both C++ and Python translations are included whenever a Mod has both languages in it.

---

- [X]  Your pull request is confined strictly to a single module
- [X]  "Small" bug
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master 
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) e
- [X]  Your pull request is well written and has a good description, and its title starts with the module name
- [X]  No ticket

### CODE REVIEW

**Comment by chennes** [comment]
@yorikvanhavre and @luzpaz can you have a look at this PR and see if this actually works to get the necessary translation strings?

**Comment by yorikvanhavre** [comment]
Yeah, that script evolved a lot over time... Good cleaning! Maybe we could simply remove the pyfolders list completely and let the script run both C++ and py gathering in all Mod folders? That way nobody has to worry about that anymore...

**Comment by chennes** [comment]
If that doesn't break anything, then yeah, I think that's the best solution. I figured there was some reason we were so carefully avoiding running both lupdate and pylupdate on the same directory, but obviously we have some where we have to now.

**Comment by chennes** [comment]
@yorikvanhavre OK, I just force-pushed another pass at refactoring the code. Because of the variability in the directory structures, I still ended up explicitly listing out all of the directories that need to be scanned, but at least now if a new one isn't being done, it will be obvious why! I run both lupdate and pylupdate on all of them, and just combine the results of each. I don't have a great way of testing whether this really worked, though. The TS files are generated, but I don't know what sort of havoc this will wreak on CrowdIn.

**Comment by luzpaz** [comment]
@chennes we need to add `src/Mod/Plot` as well, see https://github.com/FreeCAD/FreeCAD-translations/issues/60
 
I've started on Plot here, but it's not complete yet https://github.com/FreeCAD/FreeCAD/pull/5042

**Comment by chennes** [comment]
Plot is omitted here because it doesn't have a Resources/translations directory. That is probably most appropriately added in #5042.

**Comment by berndhahnebach** [comment]
would you rebase the PR to make it run on CI?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by FreeCAD-Tools** [comment]
The Crowdin build needs to be updated when this script is merged. For get new strings in FEM and other workbenches.

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5037

pipeline:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/376765024

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Review by yorikvanhavre — APPROVED** [review]
Ok I'll merge and do a crowdin update and we compare... It is always possible to revert if anything goes wrong. For reference, here is the situation before the change
Screenshot from 2021-09-29 14-17-55
:

**Comment by yorikvanhavre** [comment]
Ok this seems consequent. This is after the merge:
Screenshot from 2021-09-29 14-28-52

**Comment by yorikvanhavre** [comment]
Updated files in 77925c428e Everything seems good!
Your refactored script does not update the main src/Gui/translations/FreeCAD.ts file or am I mistaken?

**Comment by chennes** [comment]
It does: that's the very first entry in the directories list, [line 56](https://github.com/FreeCAD/FreeCAD/blob/77925c428e82f3e2e76d0e4907ac06e4bd475134/src/Tools/updatets.py#L56).

**Comment by yorikvanhavre** [comment]
Ok! I was fooled because the script didn't change a line of the ts file, but that's good :)

**Comment by FreeCAD-Tools** [comment]
@yorikvanhavre why new strings not added to FEM workbench?

**Pull request merged**
