### PR TITLE
[Part] Add face validation to Face.cutholes()

### PR DESCRIPTION
**Pull request by tomate44**
Hello,
When I added Face.cutHoles() function, I simply copied a Face constructor.
But most of the time, the resulting face is not valid, and a Face.validate() call is necessary from the python coder.
So I added a face validation at the end of cutHoles().
It is provided by FaceMakerBullseye class.
In order to remove code duplicate, I also made Face.validate() PyImp function call the C++ one.
Thanks

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by tomate44** [comment]
I get some errors on Face.validate() ...
`Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3cf80) [0x7f0689520f80]
#1  0x7f0606773174 in TopoDS_Builder::Add(TopoDS_Shape&, TopoDS_Shape const&) const from /usr/lib/libTKBRep.so.7+0x24
#2  0x7f060705e484 in BRepLib_MakeFace::Add(TopoDS_Wire const&) from /usr/lib/libTKTopAlgo.so.7+0x34
#3  0x7f06070adf24 in BRepBuilderAPI_MakeFace::Add(TopoDS_Wire const&) from /usr/lib/libTKTopAlgo.so.7+0x14
#4  0x7f06097c617d in Part::FaceMakerCheese::validateFace(TopoDS_Face const&) from /home/tomate/Software/FreeCAD/build39/Mod/Part/Part.so+0xacd
#5  0x7f06096cea71 in Part::TopoShapeFacePy::validate(_object*) from /home/tomate/Software/FreeCAD/build39/Mod/Part/Part.so+0x51
#6  0x7f06096ceb44 in Part::TopoShapeFacePy::staticCallback_validate(_object*, _object*) from /home/tomate/Software/FreeCAD/build39/Mod/Part/Part.so+0x24`

**Comment by luzpaz** [comment]
for better readability please encase code or terminal output  in triple ``` backtick (markdown code block)

**Comment by chennes** [comment]
@tomate44 are you still working on this? Should we switch it to "draft"?

**Comment by tomate44** [comment]
> @tomate44 are you still working on this? Should we switch it to "draft"?

Chris, sorry for the late answer.
I rebased the branch, and checked again.
I no longer get the errors I mentioned above.
Maybe it was a problem with the compiler cache ?

**Comment by tomate44** [comment]
Here is a piece of test code : 

```
bss = Part.BSplineSurface()
bss.setPole(2,2, FreeCAD.Vector(1,1,1))
f = bss.toShape()

ci = Part.Geom2d.Circle2d(FreeCAD.Base.Vector2d(0.5,0.5), 0.3)
e = ci.toShape(bss)
w = Part.Wire([e])

f.cutHoles([w])
f.isValid()
f.check(True)
```
On current master branch, I get : 
```
f.isValid()
>>> False

f.check(True)
>>> Traceback (most recent call last):
>>>   File "<input>", line 1, in <module>
>>> ValueError: Bad orientation of sub-shape
```

On this branch, I get : 
```
f.isValid()
>>> True

f.check(True)
>>> No exception```

**Comment by chennes** [comment]
If it's ready for review, then, could you remove the "[On Hold]" from the title? I can remove the tag.

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_4803

pipeline:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/376802882

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Pull request closed without merging**
