### PR TITLE
[Path] Implement new path generation class

### PR DESCRIPTION
**Pull request by Russ4262**
Path: Numerous cut pattern fixes and upgrades
Path: Fix cut direction fidelity for Line, ZigZag, ZigZagOffset, Offset, and Spiral
Path: Fix cut patterns for Offset and Spiral
Path: Add additional cut patterns: Circular, CircularZigZag, LineOffset, and Adaptive**.  **Adaptive cut pattern is generated by a more condensed version of algorithm in current Adaptive operation, but is not implemented at this time due to additional requirements extraneous to this commit.
Path: Apply updated patterns to three PathAreaOps: PocketShape, MillFace, and 3D Pocket
Path: Current Grid and Triangle patterns will still be provided by Path.Area() and Path.fromShapes() combination similar to what is currently active.  The other cut patterns, except Adaptive, are generated with a new PathGeometryGenerator class.
Path: Two new cut strategy modules added: PathStrategyClearing and PathStrategyProfile.  The latter is not implemented yet, but ready to be `connected` to the Profile operation. The former contains a new PathGeometryGenerator class that seeds, edits, and links the cut patterns.
Path: Add 24 unit tests dedicated to testing cut patterns generated with new PathStrategyClearing module. Patterns tested are Line, LineOffset, ZigZag, Circular, Spiral, and Offset.  Each pattern has four individual tests: 2 for cut direction and 2 for pattern reversal.
Path: The new cut patterns have additional features available for customization, but are not implemented in this PR.  Additional properties are necessary for access to these features.  These features include selection of a pre-set pattern center, a custom pattern center point, and the capability of dynamic centerers for 3D Pocket.  Also, alternating patterns could be implemented, as well as pattern rotation with each layer.
Path: Correct Dogbone unit test to use current Profile operation instead of current proxy of old ProfileFaces operation that was merged into current Profile op.
Path: A new PathSelectionProcessing module is added.  It contains numerous gemometry manipulation functions, as well as: 2D target shape builder, 3D target shape builder, and open edge shape builder classes.  This commit does not implement this module completely, rather is provided due to dependencies in this commit.  This module and its contents are functional.

Forum discussion at [Proposed cut pattern updates: PR #4965](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=61146).

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
would you rebase the PR to make it run on CI?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by Russ4262** [comment]
Rebased.

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_4965

pipeline:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/376727626

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_4965">pipeline status</a>for feature branch [PR_4965](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_4965). Pipeline [#392500999 ](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/392500999) was triggered at [98654f7](https://github.com/FreeCAD/FreeCAD/pull/4965/commits/98654f70363040e568c2c055b117fef36a9fa5bb). All CI branch [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request closed without merging**
