### PR TITLE
New Std ViewFitAll icon

### PR DESCRIPTION
**Pull request by FEA-eng**
Discussed [on the forum](https://forum.freecad.org/viewtopic.php?t=83097) first and then with the Design Working Group on Discord.

@maxwxyz FYI

### CODE REVIEW

**Comment by maxwxyz** [comment]
@FEA-eng could we use the same style as the other zoom icons (magnifying glass)? Selection icon fr example is directly next to fit all.
image

**Comment by maxwxyz** [comment]
should the other icons then be adjusted to look consistent?

**Comment by marcuspollio** [comment]
What about something along these lines:

zoom-all

**Comment by maxwxyz** [comment]
> What about something along these lines:
> 
> zoom-all
> 
> 
> [zoom-all.zip](https://github.com/FreeCAD/FreeCAD/files/15272988/zoom-all.zip)
> 

That's good!

**Comment by FEA-eng** [comment]
Ok, I'm closing this PR as it doesn't make sense to keep working on it. I will be glad if one of you sends a PR with the icon by @marcuspollio.

**Pull request closed without merging**
