### PR TITLE
Dark theme: tweak error color

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fix https://github.com/FreeCAD/FreeCAD/issues/18466

image

### CODE REVIEW

**Comment by maxwxyz** [comment]
@PaddleStroke somehow it tells me that is has conflicts but clicking on resolve leads me to a 404 error page:
grafik

**Comment by PaddleStroke** [comment]
conflict fixed

**Comment by PaddleStroke** [comment]
Your colors looks good to me. let me update the PR then

**Comment by PaddleStroke** [comment]
Can you please check the changes to make sure I have not mixed anything? I used the same color as python (which is good for me) and the new warning color you posted

**Pull request merged**
