### PR TITLE
Add hotkey to expression tooltip, rename Formula editor

### PR DESCRIPTION
**Pull request by atlast-50**
For #10601

### CODE REVIEW

**Comment by chennes** [comment]
Thanks for the PR! FYI, you don't ever need to edit *.ts files, those are automatically generated during the translation generation process (about once per week).

**Review by luzpaz — CHANGES_REQUESTED** [review]
Remove the changes to *.ts files

**Comment by luzpaz** [comment]
[547bd9f](https://github.com/FreeCAD/FreeCAD/pull/10830/commits/547bd9fb68f3e753b6808e5a7d9630fe7e97a871) still shows the .ts files have been altered. They need to be fully removed from the PR.

**Comment by atlast-50** [comment]
> [547bd9f](https://github.com/FreeCAD/FreeCAD/pull/10830/commits/547bd9fb68f3e753b6808e5a7d9630fe7e97a871) still shows the .ts files have been altered. They need to be fully removed from the PR.

Is there a way to do that without just making a whole new PR with new commits that don't contain the .ts file changes?

**Comment by luzpaz** [comment]
Looks like your figured it out. Now squash them and rename the commit  
```
git rebase -i HEAD^3 # Use `fixup` on the 2 previous commits
git commit --amend -m "Gui: Rename forumula to expression + add hotkey to expression tooltip" -m "Fixes #10601"
```

**Comment by luzpaz** [comment]
We'll need to update the docs when this gets merged.

**Review by yorikvanhavre — APPROVED** [review]
Very good! Thanks!!
(I'll let the CI tests finish before merging, also this PR still shows "Changed requested", not sure how to clear that)

**Comment by luzpaz** [comment]
CI wasn't triggered. I just triggered it.

**Pull request merged**
