### PR TITLE
Gui: add decimal point converter to Translator

### PR DESCRIPTION
**Pull request by 0penBrain**
This PR moves the decimal point converter (eventFitler) from GuiApplication to Translator.
This allows to have a hot enabling/disabling of the feature.
Also it harmonizes things as Translator now take cares of number format, which it is directly related.

### CODE REVIEW

**Comment by 0penBrain** [comment]
@wwmayer Should we foreseen to `Attach` to `General` preferences so we can update if parameters are changed though script or Parameter editor ? Or is it fully optional and acceptable as is ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6725">pipeline status</a> for feature branch [PR_6725](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6725). Pipeline [512512309](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/512512309) was triggered at [67294ba](https://github.com/FreeCAD/FreeCAD/pull/6725/commits/67294ba55f6679d537867ecb90ae3296b8309909). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
> Or is it fully optional and acceptable as is ?

I don't see that attaching to a parameter group would be really needed and especially not from a script. Actually it's a setting that is done once and then kept like that.

**Comment by 0penBrain** [comment]
> I don't see that attaching to a parameter group would be really needed and especially not from a script. Actually it's a setting that is done once and then kept like that.

OK thanks. Seems very sensible to me. :)

**Comment by donovaly** [comment]
The PR description reads as this polishes the recent decimal point changes. So can or should it got in now or better for 0.21?

**Comment by wwmayer** [comment]
IMO it can wait for v0.21

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6725">pipeline status</a> for feature branch [PR_6725](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6725). Pipeline [674312502](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/674312502) was triggered at [dffa07c](https://github.com/FreeCAD/FreeCAD/pull/6725/commits/dffa07c83eaba5106ff2f139ce6af7c5858656f4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> IMO it can wait for v0.21

I think it is time to merge the PR.
@0penBrain , can you please rebase?
@wwmayer do you require further changes?

**Comment by 0penBrain** [comment]
@donovaly it was rebased on yesterday, so merging should be safe (I had 4 conflicts that are solved).

**Comment by wwmayer** [comment]
I will have a look soon...

**Comment by 0penBrain** [comment]
> I will have a look soon...

Can wait a bit. I found some issues I'll fix soon. ;) Will ping you.

**Comment by 0penBrain** [comment]
@wwmayer this is ready now.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6725">pipeline status</a> for feature branch [PR_6725](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6725). Pipeline [683542490](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/683542490) was triggered at [327d785](https://github.com/FreeCAD/FreeCAD/pull/6725/commits/327d785621659ac289129c4929d0da50a024fe9f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
