### PR TITLE
Draft Split objects and their functions

### PR DESCRIPTION
**Pull request by carlopav**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by carlopav** [comment]
@vocx-fc I changed `draftmake `folder into `draftfunctions`, so in the future it can contain also functions like move, rotate, join, etc. what do you think?
PS CMake group together all Draft_make_functions and insert them into Draft_functions.

**Comment by vocx-fc** [comment]
I'd like to keep it as `draftmake/` because then we know immediately these functions are intended to create or make objects. They aren't just generic functions, they are specific for creating the corresponding `draftobjects/`.

We can have a separate directory `draftfunctions/` for `move`, `join`, etc. The last few days I was precisely thinking about where to put these functions. I initially thought they could be inside `draftutils/`, but maybe inside `draftfunctions/` also works.

**Comment by carlopav** [comment]
Ok, let's do like this so. I'd prefer `draftfunctions/` because in utils you find more generical stuff.

**Comment by carlopav** [comment]
@vocx-fc by the way. 
I am leaving Array functions, cause I know they are your babies :)

**Comment by vocx-fc** [comment]
Nah, it's fine, you can move them. I only added the Gui Commands and task panels. But the make functions and _Array classes were written by other people, so you can move them just like every other function. Notice that `_Array` actually depends on `DraftLink`, a class created by realthunder. But I think this is only used in arrays; still I would probably place it into its own module, just to keep everything more granular.

**Comment by carlopav** [comment]
ok, I think i'll wait for kryptokommunist PR to be merged, so we can rebase before splitting them.

**Comment by vocx-fc** [comment]
Actually, I'd prefer these changes to be made before his. Because these changes are more fundamental. His code augments the behavior of the array but I think that can come once the new modules are in place.

**Comment by carlopav** [comment]
Ok, no problem!

**Comment by carlopav** [comment]
@vocx-fc @yorikvanhavre 
I'm facing a problem: I splitted Draft Wire, Should we change it's name to Polyline now or not? I'd like so, but this could introduce severe problems in other modules that use Draft just before 0.19 release I think... probably better to leave it as Wire internally for the moment...

**Comment by vocx-fc** [comment]
I would not change it to Polyline now. As you said, it may break things if we don't test this enough, so it's better to be careful.

Add a comment if you wish, `TODO: change to Polyline and test` or something that reminds you what needs to be done later.

**Comment by carlopav** [comment]
it seems Travis continue to fail the build also if I can compile locally without issues... May this be related to : https://forum.freecadweb.org/viewtopic.php?f=4&t=42368 ?

**Comment by vocx-fc** [comment]
> it seems Travis continue to fail the build also if I can compile locally without issues... May this be related to : https://forum.freecadweb.org/viewtopic.php?f=4&t=42368 ?

That's not really related. Well, it is, but it's a different cause this time. That problem was possibly due to some files that imported some graphical functions. Since Travis only runs non-GUI code, the functions should not call any code that accesses `FreeCADGui` nor view providers.

Did you try with your first commit about rectangles and circles? It seems to me that you import the base view provider without guarding it. Maybe something like this is the problem.
```py
from draftviewproviders.view_base import ViewProviderDraft
```

**Comment by vocx-fc** [comment]
The Windows test in Travis gives more information than the Linux ones.
```
import Draft
  File "C:\Users\travis\build\FreeCAD\FreeCAD\build\Mod\Draft\Draft.py", line 176, in <module>
    from draftmake.make_circle import  make_circle
  File "C:\Users\travis\build\FreeCAD\FreeCAD\build\Mod\Draft\draftmake\make_circle.py", line 41, in <module>
    from draftviewproviders.view_base import ViewProviderDraft
  File "C:\Users\travis\build\FreeCAD\FreeCAD\build\Mod\Draft\draftviewproviders\view_base.py", line 31, in <module>
    import FreeCADGui as Gui
ImportError: DLL load failed: The specified module could not be found.
```

So, you have to guard some imports, otherwise the code will error every time in the unit tests.

**Comment by carlopav** [comment]
damn again... sorry guys, it will take a while to spot all the wrong imports i guess :(

**Comment by carlopav** [comment]
@vocx-fc now the code we splitted seems fine, but 
`Mod\Draft\Draft.py", line 3537, in <module>` 
`class _ViewProviderDraftArray(_ViewProviderDraft)`
fails:. How could it be possible before to have this working?
At the moment I'd just like to try to complete the splitting so every wiewprovider will have it's guarded import (if App.GuiUp), and we can check if this is enough.

**Comment by vocx-fc** [comment]
Yes, remember that I mentioned that the first commit, where I placed `DraftObject` and `ViewProviderDraft` in their own modules, was untested. I haven't touched these files since November or something like that. So, I really need you to test every bit well.

**Comment by vocx-fc** [comment]
Hey Carlo, I suggest you rebase this branch on top of master. Master currently includes many of the commits on this branch, so to avoid having them, it's better to remove those commits which were already integrated.

When rebasing, you may find conflicts, so I suggest you create a copy of your current head, so if there is any problem you can always go back to the backup.

```sh
git checkout SplitDraftObjects
git checkout -b SplitBackup

git checkout master
git pull upstream master
git rebase master SplitDraftObjects
```

The rebase should remove around 16 commits, which were included by the merge of #3299.

The next commits should be integrated with #3308, which is not merged right now, but which will probably be merged tomorrow. In this case, since I modified #3308, you may find some conflicts, so I will advise you in that case to create a separate branch, or to drop commits, depending on what is easier.

**Comment by carlopav** [comment]
Ok. i saw the last fails of travis are about viewproviders that are not splitted yet, so I'm confindent that everything will work when we split them all!

**Comment by vocx-fc** [comment]
The problem right now is that you are importing `_ViewProviderDraft` only if the GUI is up. However, since Travis does tests without the GUI, it doesn't import it. And then when `_ViewProviderDraftArray` tries to use it as a parent class, it fails finding it.

So, I would suggest you add the `_ViewProviderDraft` outside the GUI test.

I understand that you want to split all these classes fast. However, that's why I take a long time to make my commits, because each commit is supposed to compile and not break the code. So, I would have started moving the things much slowly and in a different sequence. It takes longer, but the result is more ordered. As it is right now, this branch will not work until every single commit is moved around.

**Comment by vocx-fc** [comment]
Wow. It passes all tests in Travis, god job!

**Comment by carlopav** [comment]
Hey! great! how come!? :D
By the way, when I finish with Array splitting... that is really tangled... I was thinking to reorder everything and opening a new PR to cherrypick the commits in the right order...
It should be easy since now I kinda know where the problems were...

**Comment by vocx-fc** [comment]
Can you do one commit per object (file)? That is a better good way to organize it. I think you'd need to split a couple of commits.

**Comment by carlopav** [comment]
yes, i guess we can do that... i'm just struggling with arrays, because to split them i first need to split move, rotate and other functions (if we do not want to create circular import) ufff... this is the hard part...

**Comment by vocx-fc** [comment]
Yup. I would have tried to move these commands first before any object :)

**Comment by carlopav** [comment]
eh, you had a look at arrays before :)
I didn't expect an object to use a move command... and that's still seems quite strange to me...

**Comment by vocx-fc** [comment]
Actually, no. I didn't have to look at the Array classes because I was only working on the Gui Commands. I basically only needed to know how to call `makeArray`.

As a general rule, the functions can be moved more easily because they don't depend on the classes.

By the way, based on the experience with my previous branches, I think I will use a personal rule now that any pull request that I make should have a maximum of 10 commits. This will make it easy to rebase and review. I think splitting the work into two or three pull requests would be better. And as I said, I would actually start with the functions because they are the easiest to externalize.

By the way, my branch #3308 was merged, so you may want to rebase this branch into master. I will check for conflicts and see what is best.

**Comment by carlopav** [comment]
The point is that move function is tricky because it needs makeCopy. And makeCopy needs almost every object... So probably still better to follow the sequence i used here... I'm working at a new PR more ordered

**Comment by carlopav** [comment]
I'll reorder every commit until 10 in new PR: https://github.com/FreeCAD/FreeCAD/pull/3388

**Comment by vocx-fc** [comment]
Oh, I see! Crazy.

**Comment by carlopav** [comment]
LOL, this proves you didn't look at them :) 
by the way, this is something we can suggest to improve to who is woriking on arrays now :)

**Comment by vocx-fc** [comment]
Exactly what suggestion?

**Comment by carlopav** [comment]
ok, nothing, we will have a look at it later

**Comment by carlopav** [comment]
substituted by https://github.com/FreeCAD/FreeCAD/pull/3388

**Pull request closed without merging**
