### PR TITLE
Material: New data models to support elasticity

### PR DESCRIPTION
**Pull request by davesrocketshop**
Addresses non-linear models associated with issue #11642

This will allow FEM to expand support for other material types

### CODE REVIEW

**Comment by luzpaz** [comment]
Some trailing whitespace linting is needed:

```
Warning: src/Mod/Material/Resources/Models/Mechanical/MooneyRivlin.yml:30:    W is a linear combination of two invariants of the left Cauchy–Green <-- trailing whitespace
Warning: src/Mod/Material/Resources/Models/Mechanical/NeoHooke.yml:29:    A neo-Hookean solid is a hyperelastic material model, similar to <-- trailing whitespace
Warning: src/Mod/Material/Resources/Models/Mechanical/OgdenN1.yml:31:    such as rubbers, polymers, and biological tissue. <-- trailing whitespace
Warning: src/Mod/Material/Resources/Models/Mechanical/OgdenN2.yml:31:    such as rubbers, polymers, and biological tissue. <-- trailing whitespace
Warning: src/Mod/Material/Resources/Models/Mechanical/OgdenN3.yml:31:    such as rubbers, polymers, and biological tissue. <-- trailing whitespace
Found 5 whitespace errors
```

**Comment by chennes** [comment]
@marioalexis84 any comments? (I ask since it sound like this is a FEM-focused PR)

**Comment by davesrocketshop** [comment]
> @marioalexis84 any comments? (I ask since it sound like this is a FEM-focused PR)

This was done in conjunction with NewJoker on discord as part of issue #11642

**Comment by marioalexis84** [comment]
>@marioalexis84 any comments? (I ask since it sound like this is a FEM-focused PR)

No comments @chennes.

**Comment by chennes** [comment]
Oh, got it, that's @FEA-eng here, right?

**Comment by chennes** [comment]
(Any issues with me taking care of that trailing whitespace?)

**Comment by FEA-eng** [comment]
> Oh, got it, that's @FEA-eng here, right?

Yeah, that's me. NewJoker on the forum and Discord. This PR lays the foundations for the future implementation of hyperelasticity for the CalculiX solver.

**Comment by davesrocketshop** [comment]
> (Any issues with me taking care of that trailing whitespace?)

None. Saves me the hassle.

**Pull request merged**
