### PR TITLE
Fem: Add box filter function

### PR DESCRIPTION
**Pull request by marioalexis84**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by marioalexis84** [comment]
@donovaly surely you want to edit the widget file.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8825">pipeline status</a> for feature branch [PR_8825](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8825). Pipeline [802710507](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/802710507) was triggered at [5ced6bb](https://github.com/FreeCAD/FreeCAD/pull/8825/commits/5ced6bbd92803ff01adb5f7ecc6b83440ac57c22). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks, looks very good!

I only would like to change the default position
from
FreeCAD_Rd4vQOmcRY

to
FreeCAD_hIof6AA6n0

or to
FreeCAD_PKLzNcPRFG


So I only would like to make the box a bit wider tan the object to avoid the artifacts st the object's border you see in the first image.
OK for you and if yes, what do you prefer, the second or third image?

**Comment by donovaly** [comment]
> @donovaly surely you want to edit the widget file.

I usually only open it with Qt's designer. This fixes automatically issues it finds just by pressing the Save button.

**Comment by marioalexis84** [comment]
>make the box a bit wider tan the object to avoid the artifacts

Yes, better to avoid the artifacts. Either option is ok for me.

**Comment by donovaly** [comment]
> Either option is ok for me.

Please make a decision, you are the author so you have the full power ;-)

**Comment by marioalexis84** [comment]
Ok, the second image.

**Comment by Syres916** [comment]
I'm getting a warning that the QLabel 'label' is used twice in BoxWidget.ui, it automatically renames the second one but it would be prudent to fix in the near future.

**Comment by donovaly** [comment]
> I'm getting a warning that the QLabel 'label' is used twice in BoxWidget.ui,

Thanks, I fixed this now via #8841

**Comment by donovaly** [comment]
> Ok, the second image.

done: #8841

**Pull request merged**
