### PR TITLE
Draft: Added LayerManager command from BIM

### PR DESCRIPTION
**Pull request by yorikvanhavre**
This migrates the LayerManager command from BIM WB to Draft. The "Draft_Layer" Draft toolbar button is replaced with "Draft_LayerManager"

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8795">pipeline status</a> for feature branch [PR_8795](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8795). Pipeline [801275898](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/801275898) was triggered at [5c471be](https://github.com/FreeCAD/FreeCAD/pull/8795/commits/5c471bef37e1e675660035797b36be11a3af8385). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Roy-043** [comment]
I haven't had enough time to look at this PR, sorry about that. I'll try to create a Wiki page next week and will do some tests then.

**Comment by yorikvanhavre** [comment]
no worries! adding a wiki page is also on my todo list ;)

**Comment by yorikvanhavre** [comment]
Done https://wiki.freecad.org/Draft_LayerManager

**Comment by tibohu** [comment]
Hi! I am just a user of FreeCAD 0.20.2. How will this feature be available?

**Comment by yorikvanhavre** [comment]
You'll have to wait for the next stable release I'm afraid. But you can still install the BIM addon and use it from there (you can even add the BIM LayerManager command to a custom Draft toolbar) in the meantime.

**Pull request merged**
