### PR TITLE
BIM: update more icons

### PR DESCRIPTION
**Pull request by marcuspollio**
Following recent changes in TechDraw (#14887) and also for better readability and consistency of a few others (IFC symbol, delete, report view toggle, CutPlane).
They are now grid-aligned, with standard 2px outline, purged unused resources and saved as Plain SVG.

BIM-icons

Noted in #13895

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Cool, just why is the white IFC shape box becoming grey?

**Comment by marcuspollio** [comment]
@yorikvanhavre Do you mean the IFC_mesh.svg or the IFC_object.svg ? For the latter, I just made the top face also grey as the other faces, but it can be tweaked and made lighter.

What do you think about the icons used at the bottom of the BIM Level/views (new level, WorkingPlane, delete, visibility, etc.) ? They're not in this PR but could tweak some if needed.

**Comment by yorikvanhavre** [comment]
I'd make the ifc_object whiter, so it matches other BIM icons, if that's ok for you?

For the BIM_Views, sure! I'm reworking the whole thing ATM, and maybe some of these buttons will change, so I'd wait before changing the icons...

**Comment by marcuspollio** [comment]
IFC_object now uses the same light gradient as Arch_Building_Tree.svg, Arch_Panel_Tree.svg, etc.
The colored IFC symbol is also a little bit bigger in IFC_object and IFC_mesh.

For the BIM_View panel icons, sure, no worries. Let me know if you need help on that.

**Comment by yorikvanhavre** [comment]
Cool! Thanks!

**Pull request merged**
