### PR TITLE
[Path]: fix several minor bugs in arc slot ops

### PR DESCRIPTION
**Pull request by J-Dunn**
This corrects which end of the slot Extend Slot Start/End are applied; error with Extend lengths between 0 and 1  and direction of extension on arc slots ( neg. is shorten ). 
Some renaming to make code more readable and self documenting.

Consolidates earlier PR which has several commits.

https://forum.freecadweb.org/viewtopic.php?f=15&t=53866&view=unread&sid=b8378b178104431838d95a9ea0050f86#p464311

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by Russ4262** [comment]
I will try to build this and test a little over the next week.  Work has me busy.

**Comment by J-Dunn** [comment]
Great. I've given it a blast over the last few days but I have more important stuff to get back to as well. Keep me posted. Thanks.

**Comment by sliptonic** [comment]
I would like to merge this PR but I have no way to test it.  I don't use the slot op on a regular basis and I don't know what problem this is solving.  Moreover, I have no way of knowing if this fix introduces any regressions.

Somebody give me some direction here.  Do I merge?  Do I wait for tests/docs?

**Comment by J-Dunn** [comment]
Thanks for giving this some attention. 

As discussed in the forum and noted in PR, this addresses 3 issues. 
1. Arc slot paths went the wrong way. This seems to come from XY plane being CCW postitive angles whereas G2 is CW. This is noted in the PR code. 
2. Extensions between 0 and 1 were  processed in the wrong direction. This can be tested by using 0.5mm extension values.
3. With arc slots, the path did not apply start extension at the start of the path but at the end. This is probably a corollary of 1. above. This now works as expected.

I provided a model FCStd file in the forum with several arc slots which can be used to test this. 

With the exception of using vector cross product in parallel test, all the code changes only affect arc slots. That should limit the possibility of regression. The fact that these rather obvious errors were not already noticed suggests little use has been made of this feature so far. 

 It would be good to have someone else do some testing to ensure I'm not having a blind spot in my tests.

You could test it on some of the curved slots on your Aztec Tlatelolco Carving FCStd you posted about in the forum.

**Comment by Russ4262** [comment]
We need to tweak this a bit.  For arc slots, the `Extend Path End` and `Extend Path Start` are not correctly reversed when enabling `Reverse Direction`.  

Other tests are working okay.  Interpreting user intentions and direction from two items is bound to fail sometimes just because.  I am okay with failure to interpret at 100%, so long as we have the toggles and adjustments available to easily (within reason) correct the interpretation by the op.

Nice work.  Thanks for getting involved and making the improvements.

**Comment by J-Dunn** [comment]
Thanks for taking a look Russ. 
The extent thing was intentional and probably is a case of defining what is meant. If I set up a start and end extent and then select Reverse Direction, I interpreted that to mean the end point becomes the start point of the path, not that I want to change the geometry of the which end gets which offset.  

Where the offset is applied is related to the model and I would not expect this to jump when I decide to change cutting direction.

This needs to be consistent with straight slots and needs to be clearly documented.

**Comment by J-Dunn** [comment]
maybe discussion of how the tool should work is better on the forum. Keeping PR centred on code changes. 
https://forum.freecadweb.org/viewtopic.php?f=15&t=53866&p=467061#p467061

**Comment by Russ4262** [comment]
I waive additional comments at this time.  I am content with merger.

**Comment by J-Dunn** [comment]
Thanks Russ.  I would like this to be consistent between straight and arc so hopefully how this should be done can be discussed at some stage. 
Merging as is would at least remove some bugs and produce correct paths. A little confusion of what is start and end extents should not prevent folks doing what they need to get working machining slot paths. 
I know you're busy so thanks for taking the time to review the code.

**Comment by Russ4262** [comment]
I would like to throw in a fix for what appears to be a pre-existing error when selecting a single face with four edges where only two are parallel and the one of the others is non-linear.  I am headed out of town for a few hours.  I will try to get it into your branch in the next few days.

**Comment by J-Dunn** [comment]
Cool.  I think I've found another oddity. I put a description and pic at the forum link above.

**Comment by Russ4262** [comment]
Don't wait on my aforementioned fix. Don't know when i will get to it. Thanks.

**Comment by J-Dunn** [comment]
Thanks Russ.  I don't have any more time to take this further right now either. 

Since Russ is OK with changes so far, can this PR get merged. It does at least fix 3 separate issues.

**Comment by J-Dunn** [comment]
Since Russ4262 has no objections , can this be merged before it gets into merge conflicts and needs redoing all over?

**Comment by J-Dunn** [comment]
many thanks, one less PR in the queue.

**Pull request merged**
