### PR TITLE
Draft: Housekeeping: call 'make' functions with new name

### PR DESCRIPTION
**Pull request by Roy-043**
The `make` functions should be called with their new name, `make_`, in the Draft code.

Note that more PRs will follow.

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6337">pipeline status</a> for feature branch [PR_6337](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6337). Pipeline [468162484](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/468162484) was triggered at [07f604e](https://github.com/FreeCAD/FreeCAD/pull/6337/commits/07f604efaa70f135670af5c050ad3ac2ddab0464). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
These changes might break external workbenches and macros. It's not a big problem I think, it's easy enough to fix, but maybe there is a way to scan/grep addons code for these functions? Unfortunately on https://github.com/FreeCAD/FreeCAD-addons there is no way to search through submodules...

**Comment by Roy-043** [comment]
That should not happen. These functions all have aliases. So this is just a case of no longer using the deprecated names in the Draft code. What prompted me to do this is that the old names are still being used by the GUI commands.  Which means that users still see the old names in the Pyhton console, and, inspired by this, use them in new code...

**Comment by yorikvanhavre** [comment]
Oh sorry, indeed, I misread your code change.
Ok, good to go then!

**Pull request merged**
