### PR TITLE
Make show grid checkbox work again

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
This is probably not what should be. It is a minimum set of changes that makes the grid behaviour work again, but I do not fully understand how it was intended to work in the original implementation. Hopefully, it will serve to expose the problems:
1. Show Grid checkbox status is never stored, because savesettings() is never executed.
2. This can not be executed in the destructor, because ViewProviderSketch will change the grid to false before the destructor is executed, so it would always store "false".
3. ViewProviderSketcher sets the grid on programatically on entering edit mode.

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
https://forum.freecadweb.org/viewtopic.php?f=3&t=3964

**Comment by wwmayer** [comment]
Recently there was a bug report about not updating the properties of a (sketch) view provider when changing the settings in the task panel (and vice versa). Together with this there was a complaint that the old behaviour of the Edit Controls panel affected all sketch objects and not individual sketches. This has been fixed in 4f02b20 but the side-effect is that the grid is now always on when editing the sketch because the settings are not saved any more.

Your PR now partially restores the old behaviour which saves all settings when the user toggles the grid check box. What we need is to only save the settings if the grid view is on or off because this actually is still to be considered as a global setting.

**Comment by wwmayer** [comment]
Merged & 4d4f0162776b

Strange that cherry-pick didn't apply the changes to ViewProviderSktech.cpp

**Comment by abdullahtahiriyo** [comment]
@wwmayer 

Thanks.

I thought of only saving that setting too. However I found it akward that the saving function was not being called at all. I did not know if this was intended or not. This is why I decided to do a PR exposing that issue too and "warning" in the message above :)

**Comment by wwmayer** [comment]
As said above before the changes of 4f02b20 the method saveSettings was called. So, until there everything worked as expected and intended but the global behaviour of all sketch settings was a bit confusing and some people complained about it. That's why I made the changes but wasn't aware of the grid view issue.

**Pull request closed without merging**
