### PR TITLE
Fem: Fix mesh export to vtk formats

### PR DESCRIPTION
**Pull request by marioalexis84**
If a Fem mesh is exported to vtk file formats, only the highest dimensional elements will be exported.
For example:
Create a Fem mesh containing edge, face and volume elements.
Export the object to .vtu mesh format.
Import the object back as a Fem mesh -> Edge and face elements are lost.

@FEA-eng

### CODE REVIEW

**Comment by FEA-eng** [comment]
I think that there should be a preference like the one for INP export:

inp export

Especially since usually the highest level elements (those used for FEM analysis) are sufficient.

**Comment by chennes** [comment]
@FEA-eng can we live without that UI change for the 1.0 release? We are well past the UI strings lock deadline.

**Comment by FEA-eng** [comment]
> @FEA-eng can we live without that UI change for the 1.0 release? We are well past the UI strings lock deadline.

I will discuss it with Mario but the thing is that IMO the behavior implemented here should be only optional.

**Comment by chennes** [comment]
@marioalexis84 maybe I didn't understand your meaning -- are you still working on this PR? Or is it ready to go in?

**Comment by marioalexis84** [comment]
I'm still working on it.

**Comment by chennes** [comment]
OK, thanks -- I switched it to draft so it doesn't get merged accidentally.

**Comment by maxwxyz** [comment]
any news on this PR?

**Comment by marioalexis84** [comment]
I'll try to finish it this week.

**Comment by maxwxyz** [comment]
@marioalexis84 last chance before Monday :)

**Comment by marioalexis84** [comment]
This pull request is ready.
There is an entry on the VTK Import-Export preferences page to select which items to export.

@FEA-eng

**Comment by FEA-eng** [comment]
The "All" setting doesn't work for me (exports only the highest elements), also for .inp files (existing setting). It works in weekly so this might be a regression.

**Comment by marioalexis84** [comment]
@FEA-eng could you try again?

**Comment by FEA-eng** [comment]
> @FEA-eng could you try again?

Now it's ok.

**Review by FEA-eng — APPROVED** [review]

**Pull request merged**
