### PR TITLE
[DO NOT MERGE] Paddle widget testing

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
This is only for snap generation. It is not intended for review and it is not intended for merge.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
@luzpaz is the PR actually needed? github has no issue finding commits from forks even if you don't specify the fork, take this random example 03b925b3598f5bf9758881b69db96ce609467aeb from a branch in abdullah's fork, I can fetch it with git by specifying the hash without adding abdullah's fork as a remote. I believe you can build any commit from any fork just with the commit sha even if it's not a PR

**Comment by luzpaz** [comment]
@ppd can you weigh-in? :point_up_2:

**Comment by ppd** [comment]
@luzpaz @adrianinsaval is right; it shouldn't be necessary. The workflow was designed to build commits from PRs, but fetching commits from forks via the default remote works fine as long as it's a true fork of the original repository.

**Comment by luzpaz** [comment]
@ppd Great news! @adrianinsaval thanks for catching this!  
@abdullahtahiriyo from here on out PRs are not necessary in order to build experimental snaps.  Sorry for the extra work on your end :pray:

**Comment by luzpaz** [comment]
@abdullahtahiriyo snap build fails:  
```
[ 96%] Building CXX object src/Mod/Sketcher/Gui/CMakeFiles/SketcherGui.dir/CommandSketcherTools.cpp.o
/home/runner/work/FreeCAD-snap/FreeCAD-snap/parts/freecad/src/src/Mod/Sketcher/Gui/CommandSketcherTools.cpp:62:10: fatal error: BRepAdaptor_HCurve.hxx: No such file or directory
   62 | #include <BRepAdaptor_HCurve.hxx>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/Mod/Sketcher/Gui/CMakeFiles/SketcherGui.dir/build.make:536: src/Mod/Sketcher/Gui/CMakeFiles/SketcherGui.dir/CommandSketcherTools.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5474: src/Mod/Sketcher/Gui/CMakeFiles/SketcherGui.dir/all] Error 2
```
[Link](https://github.com/FreeCAD/FreeCAD-snap/runs/7131503792?check_suite_focus=true#step:6:11056)

**Comment by ageeye** [comment]
It use OCCT 7.6.2 ?

`#include <BRepAdaptor_HCurve.hxx>`

`#include <BRepAdaptor_Curve.hxx>`

**Comment by abdullahtahiriyo** [comment]
@ppd @luzpaz 

ppd noted this in the forum, the last time he made the snap for the testing branch. I am not sure how he fixed it:
https://forum.freecadweb.org/viewtopic.php?p=589919#p589919
https://forum.freecadweb.org/viewtopic.php?p=589941#p589941

Thanks you both for taking care of this!!

**Comment by abdullahtahiriyo** [comment]
> It use OCCT 7.6.2 ?
> 
> `#include <BRepAdaptor_HCurve.hxx>`
> 
> `#include <BRepAdaptor_Curve.hxx>`

It appears to relate to OCC version. I would not like to change the header before we have support, but thanks for making me aware.

**Comment by adrianinsaval** [comment]
he ended up building with the older libraries but IMO this is something that needs to be addressed in this branch as it will be a problem in the future anyways.

**Comment by adrianinsaval** [comment]
> > It use OCCT 7.6.2 ?
> > `#include <BRepAdaptor_HCurve.hxx>`
> > `#include <BRepAdaptor_Curve.hxx>`
> 
> It appears to relate to OCC version. I would not like to change the header before we have support, but thanks for making me aware.

support for what?

**Comment by luzpaz** [comment]
@abdullahtahiriyo can you make an `ifdef` for OCC 7.6.2 ?

**Comment by abdullahtahiriyo** [comment]
> support for what?

Good question.

I thought we did not have support for 7.6.2 yet in overall FreeCAD. But we do. So my comment does not make sense.

Now, I am building locally against 7.5.2 (where it compiles), and I do not know what exactly is going on wrong here.

The lines the compiler is complaining about are:

```
#include <BRepAdaptor_Curve.hxx>
#if OCC_VERSION_HEX < 0x070600
#include <BRepAdaptor_HCurve.hxx>
#endif
```

So HCurve should only be included for versions under 7.6.

The error shows that said BRepAdaptor_HCurve.hxx is not available in the system. This is the situation after 7.6, as it was removed.

But, why is this include being added if the library version is higher than 7.6.0?

Anyway, this is code I did nor review yet, and I have realised that BRepAdaptor_HCurve was not even used, so I have removed it and will push the branch with an additional commit.

**Comment by abdullahtahiriyo** [comment]
@luzpaz 

Hopefully now it will build. 

Thanks for your support! :)

**Comment by luzpaz** [comment]
Generating new build at: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/2605369955
(Will update this comment when build is successful and snap is available for testing)

**Comment by luzpaz** [comment]
Snap available for testing:  
`snap refresh freecad --channel="latest/edge/sketcher-7118-paddle-widget"`

To return to stable or edge respectively:  
`snap refresh freecad --channel=stable`
`snap refresh freecad --channel=latest/edge`

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7118">pipeline status</a> for feature branch [PR_7118](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7118). Pipeline [578984806](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/578984806) was triggered at [bdf1214](https://github.com/FreeCAD/FreeCAD/pull/7118/commits/bdf121413efcb84fe8f91e89ed65699785d05cd1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
does `snap refresh` work if you don't have any snap installed?

**Comment by luzpaz** [comment]
> does `snap refresh` work if you don't have any snap installed?

No idea.

**Comment by ppd** [comment]
> does `snap refresh` work if you don't have any snap installed?

refresh works for already installed snaps. Use `snap install`  for snaps that haven't been installed yet.

It's also possible to do a parallel install: https://snapcraft.io/docs/parallel-installs
In this way, a stable snap installation could be kept separate from an experimental installation like this.

**Comment by luzpaz** [comment]
Heads up, whomever makes the next commit should also include the fixes for spelling errors found in https://github.com/FreeCAD/FreeCAD/runs/7159753219?check_suite_focus=true

**Comment by abdullahtahiriyo** [comment]
@luzpaz 

I had them fixed locally. Just pushed them.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7118">pipeline status</a> for feature branch [PR_7118](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7118). Pipeline [581012051](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/581012051) was triggered at [b485cc4](https://github.com/FreeCAD/FreeCAD/pull/7118/commits/b485cc42663e76f7caca5a0d3aa845ed0c82114e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7118">pipeline status</a> for feature branch [PR_7118](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7118). Pipeline [693828752](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/693828752) was triggered at [b485cc4](https://github.com/FreeCAD/FreeCAD/pull/7118/commits/b485cc42663e76f7caca5a0d3aa845ed0c82114e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by abdullahtahiriyo** [comment]
Closing in favour of:
https://github.com/FreeCAD/FreeCAD/pull/10892

Other tools not in that PR will be provided later on separately.

**Pull request closed without merging**
