### PR TITLE
[BugFix] Part: fix XSkew+YSkew editing not took into account for cylinders

### PR DESCRIPTION
**Pull request by 0penBrain**
The values aren't transferred into the command line

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8624">pipeline status</a> for feature branch [PR_8624](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8624). Pipeline [787730719](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/787730719) was triggered at [701b136](https://github.com/FreeCAD/FreeCAD/pull/8624/commits/701b136489ecb19a1e63ad066ad7c29d6ae17434). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
With one of the recent changes there is now a regression that existing geometries cannot be modified any more. If you e.g. create a ellipse, double-click and click OK you will see this error:
```
<class 'SyntaxError'>: ("(unicode error) 'utf-8' codec can't decode byte 0xb0 in position 8: invalid start byte", ('<string>', 3, 54, 'App.getDocument("Unnamed").Ellipse.Angle1=\'3,00000 �\'\n', 3, 54))
Unhandled Base::Exception caught in GUIApplication::notify.
The error message is: ("(unicode error) 'utf-8' codec can't decode byte 0xb0 in position 8: invalid start byte", ('<string>', 3, 54, 'App.getDocument("Unnamed").Ellipse.Angle1=\'3,00000 �\'\n', 3, 54))
```

Affected are all types that use an angle: Ellipse, Circle, Helix, Prism, Torus, Ellipsoid, Sphere, Cone, Cylinder

I haven't checked it yet but I assume the culprit is getSafeUserString() that doesn't correctly handle the unicode form of the degree symbol.

**Comment by 0penBrain** [comment]
@wwmayer It has been discovered and fixed already by @donovaly with #8616. ;)
And no, it doesn't have to do with `getSafeUserString` :)
Can you still confirm with latest master ? (this PR is already rebased, so shouldn't have the issue BTW)

**Comment by wwmayer** [comment]
> It has been discovered and fixed already by @donovaly with https://github.com/FreeCAD/FreeCAD/pull/8616. ;)

Oh, thanks for the hint.

> Can you still confirm with latest master ?

Yes, it works. Thanks!

**Pull request merged**
