### PR TITLE
Material: Material editor enhancements

### PR DESCRIPTION
**Pull request by davesrocketshop**
Continues the work of the material subsystem improvements.

This merge covers the continued development of the material editor. The primary improvements are the addition of new data types, a new appearance preview UI, and changes in the array data types.

New data types were added to support more advanced workflows, such as the Render Workbench.The Image datatype allows the material to embed the image in the card instead of pointing to an image in an external file. Multi-buyte strings span multiple lines as the name implies. It preserves formatting accross those lines. Also several list types are now supported, with the primary difference being the editors. List is a list of strings, FileList is a list of file path names, and ImageList is a list of embedded images.

For the appearance preview, the UI now uses the same Coin library as is used in the documents, meaning the preview will look exactly the same as the material will be shown in the documents.

The array data types are now more complete. The default value wasn't being used as originially envisioned and was tehrefore removed. For 3D arrays, the Python API was implemented.

There were a lot of code clean ups. This involved removing logging statements used for debugging during development, reduction of lint warnings, and code refactoring.

The editor can automatically convert from previous format files to the current format. This has been extended to material files generated by the Render WB. Old format files are displayed in the editor with a warning icon. Selecting one will require saving the file in the new format before it can be used.

### CODE REVIEW

**Comment by davesrocketshop** [comment]
Hang on... git is messing with me again. I'll try to fix or recreate.

**Comment by davesrocketshop** [comment]
This branch is messed up. Closing and redoing

**Comment by FlachyJoe** [comment]
@davesrocketshop in such case and in order to keep the PR you can create a new local branch based on the current main, cherry-pick your commit from the problematic one and force push the new branch to the old remote.

When comments are already made on the PR it's smart to conserve them.

**Comment by davesrocketshop** [comment]
Tried to fix and force push but it made it worse. There are many commits in the original repository as I save often. The PR was just created without comments so I felt this was a safer route.

See https://github.com/FreeCAD/FreeCAD/pull/11628 for the new PR

**Pull request closed without merging**
