### PR TITLE
Sketcher: Polyline icon modification.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7588">pipeline status</a> for feature branch [PR_7588](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7588). Pipeline [662983435](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/662983435) was triggered at [049e480](https://github.com/FreeCAD/FreeCAD/pull/7588/commits/049e4801ad049e4ea361fb4f55ecbe808880d82e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks. But where in the forum was this discussed?

Just my first impression: it adds too much. For small icon sizes it is already packed with strokes. I understand the rationale to make clear that the tool can also create circular arcs, but this is not available directly. Therefore new users or those who did not yet use the What's this? feature on the icon will wonder how to get an arc.

But as always on UI changes, there should be a forum debate to hear the different arguments. While we are at this, please don't immediately start a poll. Please collect at first some arguments. (I recently made this mistake with the default background gradient and cannot recommend doing this again ;-) )

**Comment by chennes** [comment]
The forums discussion is here: https://forum.freecadweb.org/viewtopic.php?f=8&t=72494

**Comment by PaddleStroke** [comment]
That's exactly the point, user will wonder how to make arc and so they will look at the dock if they want to use it for arcs. Because currently it just goes unoticed. I spent 4 years without knowing it could do more than lines. I discovered it only when looking at its code.

**Comment by adrianinsaval** [comment]
It's exactly the point to give a hint to the user that arcs are available, I agree it's too loaded though, a similar concept but with less lines would be nice.

**Comment by abdullahtahiriyo** [comment]
Closing in view of less stroke preferred solution:
https://github.com/FreeCAD/FreeCAD/pull/7724

**Pull request closed without merging**
