### PR TITLE
[PD] Add PartDesign Python commands for translation

### PR DESCRIPTION
**Pull request by chennes**
PartDesign was missing as a Python subdirectory in the translation script. This fixes #4583 -- https://tracker.freecadweb.org/view.php?id=4583

### CODE REVIEW

**Comment by luzpaz** [comment]
Thank you @chennes !

@yorikvanhavre please merge asap and run a crowdin push/pull

Also cc @kaktusus, once yorik does that, lets test the open/ tickets for PartDesign related translations

**Comment by luzpaz** [comment]
@chennes i think this fixes it. @berndhahnebach can you please merge?

**Comment by kaktusus** [comment]
> Thank you @chennes !
> 
> @yorikvanhavre please merge asap and run a crowdin push/pull
> 
> Also cc @kaktusus, once yorik does that, lets test the [open tickets for PartDesign related translations](https://github.com/FreeCAD/FreeCAD-translations/issues)

great, i'm glad
good job

**Comment by luzpaz** [comment]
@kkremitzki please merge, thanks!

**Pull request merged**
