### PR TITLE
Tools: icon error when envoking pure python test module

### PR DESCRIPTION
**Pull request by mdkus**
The location of the workbench icon for pure python modules should be the recommended resource directory as described under chapter 6.2.2 in the developpers guide.

### CODE REVIEW

**Comment by luzpaz** [comment]
Ticket: https://tracker.freecadweb.org/view.php?id=4839

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5507">pipeline status</a> for feature branch [PR_5507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5507). Pipeline [464825519](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464825519) was triggered at [bb17aa9](https://github.com/FreeCAD/FreeCAD/pull/5507/commits/bb17aa97e1bd2ee38f9cfc08de5e28e1cb22daf1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Please close ticket #6314 when/if this PR gets merged. Thanks!

**Comment by yorikvanhavre** [comment]
Yes, makes sense. Don't know what the developers guide or chapter 6.2.2 are, though? :sweat_smile:

**Comment by mdkus** [comment]
Hi Yorik, chapter 6.2.2 can be found in this source: [FC module developer's guide](https://github.com/qingfengxia/FreeCAD_Mod_Dev_Guide)

**Pull request merged**
