### PR TITLE
PartDesign: Fix body shape not updated

### LINKED ISSUE #17210: PartDesign: New feature does not update Shape of Body correctly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After making a simple sketch and using the revolution tool, making a pocket on the end of the revolution will cause the exported STL (or 3MF) to use the wrong length. In the attached example, the figure has a 10 mm cylinder on top of a wider cylinder (this makes the problem easy to see later) after the revolution, but making a 10 mm pocket into the narrow cylinder and exporting to a STL file, the pocket will only be 5 mm deep when the STL is opened in a slicer. Setting the pocket to two dimensions and 2nd length to 10 mm will make the correct pocket depth.

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38926 (Git) Snap 1161
Build type: Release
Branch: main
Hash: a9bff78974f301100134a13c636e23aa91be5bcf
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

None

### Anything else?

[error.zip](https://github.com/user-attachments/files/17350002/error.zip)

Works correctly in 0.21.2 (AppImage).
Output STL tried in Cura and Bambu Studio.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix #17210

### CODE REVIEW

**Comment by chennes** [comment]
Can you manually create a PR against the release branch? We haven't merged the `isUpdateBlocked` feature there yet, and may not.

**Comment by FlachyJoe** [comment]
@chennes so their is nothing to fix in the release branch, do you request a backport of #16976 with this fix already applied?

**Comment by chennes** [comment]
My apologies, I misread the version that the error was reported against. No action is needed right now, we have to decide whether to backport #16976 first.

**Comment by maxwxyz** [comment]
So can I remove the `needs backport` label on this issue too or will both PRs still be backported?

**Comment by chennes** [comment]
No one has offered an opinion that we should backport #16976 -- unless we backport that one, this one doesn't need to be. I think we can drop the backport tag here.

**Comment by yorikvanhavre** [comment]
Cancelling backport unless someone requests it.

**Pull request merged**
