### PR TITLE
Path: renamed KineticNC_post.py to KineticNCBeamicon2_post.py

### PR DESCRIPTION
**Pull request by SamuelMayer**
Since the KineticNC_post.py is also fully compatible with the "Beamicon2" mill control I renamed the file and changed minor parts of the description in the file 

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6580">pipeline status</a> for feature branch [PR_6580](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6580). Pipeline [490966268](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/490966268) was triggered at [6499d0c](https://github.com/FreeCAD/FreeCAD/pull/6580/commits/6499d0c4f646ab0a39f3344850574d51ab357b69). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
Has this rename been discussed on the forum?   I would rather not rename for this reason because it will break any existing jobs that have the post processor selected with the old name.

**Comment by SamuelMayer** [comment]
Yes, it has: https://forum.freecadweb.org/viewtopic.php?f=15&t=57003
I am happy with adding an additional post processor but also think chrisb has a point there. The KineticNC post is relatively new so apart from me there shouldn't be many people already using it. And I use a slightly modified version most of the time anyway.
So what do you think, should I close this PR and make a new one for a "Beamicon2_post.py"?

**Comment by SamuelMayer** [comment]
How should I proceed? I'm happy with maintaining two postprocessors so should I rather close this PR and make a separate one for the Beamicon_post.py?

**Comment by sliptonic** [comment]
I'll merge but the branch has a conflict, probably from a Black cleanup.  Can you resolve that please?

**Comment by donovaly** [comment]
@SamuelMayer, please rebase.

If you don't have time, I can merge this PR manually. @sliptonic , do I have your OK to do this?

**Comment by sliptonic** [comment]
Of course. Have at it

**Comment by donovaly** [comment]
manually merged: https://github.com/FreeCAD/FreeCAD/commit/2714e682db

**Pull request closed without merging**
