### PR TITLE
Core: Expose Placement dialog to Python

### PR DESCRIPTION
**Pull request by wwmayer**

### CODE REVIEW

**Comment by maxwxyz** [comment]
@chennes I'll label it 1.0 to merge the other PR

**Comment by PaddleStroke** [comment]
Note : This is now in conflict with https://github.com/FreeCAD/FreeCAD/pull/16317. (Just to link the PR together somehow.)

**Comment by PaddleStroke** [comment]
@wwmayer I confirm that your solution works. And on top of that the 'apply Incremental' option is still there while I pruned it off, which is better.
Just small things : 
1 - bindObject does not set the UI to initial placement. So when you start editing with the function you gave before, the placement is reset. To fix this I can do a setPlacement like so : 

```
    def openEditingPlacementDialog(self, obj, propName):
        task_placement = Gui.TaskPlacement()
        dialog = task_placement.form
    
        # Connect to the placement property
        task_placement.setPlacement(getattr(obj, propName))
        task_placement.setSelection([obj])
        task_placement.setPropertyName(propName)
        task_placement.bindObject()
        task_placement.setIgnoreTransactions(True)
    
        dialog.exec_()
```
However perhaps it would be better that bindObject does it directly no?

2 - The dialog has 3 buttons "Ok" "Close" and "Apply". The 'Cancel' button is renamed 'Close' when setIgnoreTransactions I guess.
In this configuration, 'Close' button is useless and could be hidden. As it does the same as OK.
However in my solution I still have the Cancel button which is better. You could also keep the cancel button here : When the function 'bindObject' is called, it can save a backup placement. If cancel is clicked, it set the placement back to the backup.

**Comment by PaddleStroke** [comment]
One more small thing is the syntax complexity. My solution offers a very simple syntax : 

`Gui.PlacementDialog(self.joint, "Offset1")`

which is much simpler and more friendly to use. Could you perhaps also add a construction like this to make it simple?

**Comment by chennes** [comment]
@PaddleStroke it would be good if we can merge this soon: are you OK with the current solution?

**Comment by PaddleStroke** [comment]
Yes it can go in. There's just the 'Close' button thingy but it's small I can fix it later in my offset PR.

**Comment by wwmayer** [comment]
> However perhaps it would be better that bindObject does it directly no?

No, it won't. bindObject() is supposed to bind the widgets to the components of the placement property. It's the same behaviour as with the C++ API where one must explicitly call setPlacement().

I will add a new method that allows you to directly set the placement and bind the property so that calling setPlacement and setSelection is not needed any more.

> 2 - The dialog has 3 buttons "Ok" "Close" and "Apply". The 'Cancel' button is renamed 'Close' when setIgnoreTransactions I guess.

I will replace the 3 buttons with a dialog button box with Ok/Cancel/Apply

> However in my solution I still have the Cancel button which is better. You could also keep the cancel button here : When the function 'bindObject' is called, it can save a backup placement. If cancel is clicked, it set the placement back to the backup.

That isn't something the dialog can do for you if you don't want to let it handle transactions but it's up to the calling instance, then. This is because the dialog is not limited to work with a single object but multiple objects that can dynamically change at runtime.

**Comment by PaddleStroke** [comment]
It seems that there is now a cancel button instead of the close button, but the cancel does not seem to have any effect. Does it need to be implemented on my side by connecting to a signal?

**Comment by wwmayer** [comment]
If transactions are disabled then the Cancel button does nothing. In this case it's up to the calling instance to revert changes.

**Pull request merged**
