### PR TITLE
Gui: remove forcefully jumping to Python Console bottom line on single LMB click

### PR DESCRIPTION
**Pull request by 0penBrain**
https://forum.freecadweb.org/viewtopic.php?f=3&t=72321

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7601">pipeline status</a> for feature branch [PR_7601](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7601). Pipeline [665595621](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/665595621) was triggered at [67c7213](https://github.com/FreeCAD/FreeCAD/pull/7601/commits/67c7213cff8ea41aff922c3b441b74dd7ddd75c1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@wwmayer you already commented on this in the forum, can you please have a look?

**Comment by luzpaz** [comment]
@0penBrain would you minding changing `forcely` to `forcefully` in the commit summary title ? TIA!

**Comment by 0penBrain** [comment]
@luzpaz Always ready to improve my English.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7601">pipeline status</a> for feature branch [PR_7601](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7601). Pipeline [667942240](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/667942240) was triggered at [4d263ab](https://github.com/FreeCAD/FreeCAD/pull/7601/commits/4d263abc9850c6a6986ccad0f3f1ee23f30ae45f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Thanks! Somehow this PR didn't appear in my GH notification list.

**Pull request merged**
