### PR TITLE
[Bugfix] Expression: fix precedence+associativity management in parenthesis removal

### LINKED ISSUE #6948: [Bug] Expression : operator precedence and associativity wrongly handled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=52691

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.27422 (Git)
Build type: Release
Branch: master
Hash: d938733eaf2c2ce7cb18d1cbb56147185c473530
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United Kingdom (en_GB)
```

### Subproject(s) affected?

Expressions

### Issue description

Parenthesis removal in expression is wrongly handled (too much removed)

Simple demonstration.
In a Spreadsheet :
* Enter `=2*(5%3)` => Result is correctly displayed as 4
* Select the cell to see content => Displayed content is `= 2 * 5 % 3`. Parenthesis have been wrongly removed.
* Notice displayed result is still 4, but according precedence and associativity, it should be 1
* Save, close and reopen document => Now the cell result is 1

This behavior is reproducible across the whole FC expression system.
Interestingly, when doing same on a float (unitless) value (eg. a placement axis direction) the result immediately goes wrong, while on quantities it tends to keep a correct value till the document is closed and reopen.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0penBrain**
Fixes #6948

https://forum.freecadweb.org/viewtopic.php?f=3&t=52691

Set as Draft time to add unit test and PR to be checked by some users (there's a bit of sorcery in this)

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6949">pipeline status</a> for feature branch [PR_6949](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6949). Pipeline [553051638](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/553051638) was triggered at [4125aeb](https://github.com/FreeCAD/FreeCAD/pull/6949/commits/4125aeb52d79d5fcfbdc8bf436063c8e896cf5a9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@wwmayer it looks like the unit test I added in the 3rd commit isn't run (as many of the tests in the same file). May you please have a look ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6949">pipeline status</a> for feature branch [PR_6949](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6949). Pipeline [553086466](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/553086466) was triggered at [8d4e116](https://github.com/FreeCAD/FreeCAD/pull/6949/commits/8d4e1165c4b63de57270c163a080efc8b79b2335). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Can someone please help me out here to review?
Seems OK. If you agree, please merge.

**Comment by donovaly** [comment]
@chennes or @wwmayer ?

**Comment by chennes** [comment]
I think it's OK (and I appreciate the test case!), but this is a bit beyond my knowledge, so I leave it to those who know better than I to actually merge.

**Comment by donovaly** [comment]
OK, putting it then to the 0.20 milestone and hoping @wwmayer find time to review this.

**Comment by wwmayer** [comment]
```
    # add test for issue #6948
    self.Obj3 = self.Doc.addObject("App::FeatureTest", "Test")
    self.Obj3.setExpression('Float', u'2*(5%3)')
    self.Doc.recompute()
    self.assertEqual(self.Obj3.Float, 4)
```
is a badly chosen example to demonstrate the problem. When I run this code in current master then it also returns 4.0 but the expression has changed to `2*5%3`. To me it looks like the internally used expression still has the parentheses but its string representation lost them.

So to show the problem the string representation of the expression must be evaluated which can be done with
`self.Obj3.evalExpression(self.Obj3.ExpressionEngine[0][1])`

**Comment by 0penBrain** [comment]
> When I run this code in current master then it also returns 4.0 but the expression has changed to `2*5%3`.

Here it directly evaluates to 1.0. This is a case I only have for 'Float' property. Other cases give me same behavior as you describe.

**Pull request merged**
