### PR TITLE
Core: Remove unecessary ':' cluttering Placement.ui

### PR DESCRIPTION
**Pull request by PaddleStroke**
Placement dialog is extremely wide and invasive. The main reason being the size of the spinboxes (see https://github.com/FreeCAD/FreeCAD/issues/16810).

However there is also some unecessary ':' in the labels of groupboxes and of spinboxes. Cluttering unecessary the dialog and increasing a little the width.

### CODE REVIEW

**Review by hyarion — APPROVED** [review]
The de facto standard in FreeCAD seems to be to avoid ending labels and titles with `:` (though there are many places where more can be found).

I've tested the PR and the `:` are indeed gone and I couldn't see any missed in the panel. It does improve the look of the panel.

I think this is a great and safe improvement.

**Comment by chennes** [comment]
X, Y, and Z are currently set as translatable -- as long as you are touching those lines, should we also add the `notr="true"` attribute?

**Comment by hyarion** [comment]
> X, Y, and Z are currently set as translatable -- as long as you are touching those lines, should we also add the `notr="true"` attribute?

I've found multiple cases where x, y, and z is using the attribute `notr="true"`, this is one example: https://github.com/FreeCAD/FreeCAD/blob/9df2ec7b86aeecc066c0fe703b62fa5780eb3374/src/Gui/VectorListEditor.ui#L39

So, yes I think that would be a good idea too 🙂

**Comment by PaddleStroke** [comment]
done

**Comment by xtemp09** [comment]
@PaddleStroke, is the tab order correct?

**Comment by PaddleStroke** [comment]
I have not checked this. This PR modify only the strings.

**Comment by hyarion** [comment]
xtemp09 wrote:
> is the tab order correct?

I checked it and it is wrong, see screenshot:
tab order

However, maybe this is another issue?

**Comment by PaddleStroke** [comment]
Why do you say that it's wrong @hyarion ? Your screenshot seems correct to me.
And yes I think that's another issue.

**Comment by hyarion** [comment]
@PaddleStroke the current order is:
X -> Y -> Z -> Add incremental changes -> Angle

Wouldn't it make more sense with this order:
X -> Y -> Z -> Angle -> Add incremental changes

I can add an issue if you agree that the order is wrong.

**Comment by PaddleStroke** [comment]
Ah yes my eyes were not seeing it :)

**Comment by hyarion** [comment]
The tab order is now reported here https://github.com/FreeCAD/FreeCAD/issues/16944

**Comment by hyarion** [comment]
https://github.com/FreeCAD/FreeCAD/pull/16982 here is a fix for the tab order

**Comment by PaddleStroke** [comment]
@yorikvanhavre if we have started merging post 1.0 stuff, this PR is a no-brainer.

**Pull request merged**
