### PR TITLE
CAM: Rename CW/CCW to Climb/Conventional for consistency

### LINKED ISSUE #14314: CAM: CW/CCW/Conventional/Climb terminology consistency
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Some CAM operations define cutting direction with CW/CCW (Clockwise/Counterclockwise) which can be confusing, along with the fact that other operations use "conventional" and "climb" verbiage, which is more commonly used in the industry and (potentially?) easier to understand the effects of. IMO it would be good to standardise on the "conventional" and "climb" direction verbiage.

A very quick audit of the UIs for all operations is as follows:

| Operation     | Terms                           |
| ------------- | ------------------------------- |
| Profile       | Direction -> CW/CCW             |
| Helix         | Direction -> CW/CCW             |
| Deburr        | Direction -> CW/CCW             |
| Pocket        | Cut Mode -> Climb/Conventional  |
| MillFace      | Cut Mode -> Climb/Conventional  |
| Pocket3D      | Cut Mode -> Climb/Conventional  |
| Threadmilling | Direction -> Climb/Conventional |
| Adaptive      | No option                       |
| Slot          | No option                       |
| Engrave       | No option                       |
| Deburr        | No option                       |
| 3D surface    | No option                       |
| Waterline     | No option                       |

I also noticed the use of "Cut Mode" and "Direction". This could be made consistent too, although perhaps to a secret third option: "Cut Direction". IMO this makes more sense when used as part of a sentence, e.g. "The first pocket operation uses the conventional cut direction".

### Full version info

```shell
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git) AppImage
Build type: Release
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * freecad.gears 1.2.0
  * Assembly3 0.12.2
  * OpenTheme 2024.5.16
  * Assembly4 0.50.12
  * FeedsAndSpeeds 0.5.0
  * fasteners 0.5.21
```

### Subproject(s) affected?

CAM/Path

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jamwaffles**
As per title. I don't write much Python so I may have missed something silly, but the tests pass (locally anyway).

The translations were done with a naive find and replace. My editor stripped trailing whitespace which I can undo if it's significant, otherwise apologies for the diff noise. I'm unsure how to test if the translations are still correct.

Closes #14314

### CODE REVIEW

**Comment by sliptonic** [comment]
Will review and get the translation stuff out of the pr

**Comment by sliptonic** [comment]
@jamwaffles I'll review the PR functionality.  Can you please rebase it from main and remove the .ts files from the commis.  They don't need to be included and will be updated automatically later.

**Comment by jamwaffles** [comment]
Rebased and `*.ts` files now untouched :)

**Comment by sliptonic** [comment]
> Rebased and `*.ts` files now untouched :)

Wow that was fast! Thanks.
everything looks good to me.  I'll merge after CI passes.  (It'll probably fail the windows build for unrelated reasons)

**Comment by Connor9220** [comment]
I know this is closed, but.  I wanted to mention, that simply changing the wording from CW/CWW to Conventional / Climb may or may not be correct.  In some of the operations, we need to look at weather the op is a inside of outside operation, and the direction may change based on that.  So, CW indicates it'll go in a clock wise direction regardless if it's a inside or outside op, but, Climb cut, will switch direction.. Was this taken into account?

**Comment by jffmichi** [comment]
You changed the "direction" parameter for `diffAngle` on line 150 in Geom.py. Since `diffAngle` only operates on angles and not operations climb/conventional doesn't make sense here. If you ask me, it should be kept as cw/ccw in this case. Also on line 469 in Geom.py you're passing "Climb" or "CCW" to `diffAngle`. Funcionally it should work since `diffAngle` tests `if direction == "Climb" ... else ...` but it's not really consistent.

**Comment by jbaehr** [comment]
I get the feeling that this MR was merged a bit prematurely. While I appreciate the usage of common vocabulary in the area, in this particular case there is more than just search/replace. -- it changed the semantics as well, without the implementation reflecting this change.

The old names have been correct, in the sense how the generated paths behave but required some thinking of the person operating the software. The new naming implies that the implementation takes care of inside/outside profiles, but it's not. This results in the user-visible issue #15206. @Connor9220 comment above came 2h too late ;-)

Then this change affects older files, which is not taken care of. This introduces the regressions #15009 and #15643 (which was closed as duplicate, not as fixed). I think this one is particularly severe as it makes it impossible to work on files created with the previous FreeCAD version. I see them as release blockers.

Finally, as @jffmichi points out above, this PR also changes the naming in APIs that are independent of the inside/outside thing, making them more awkward to use as a developer.

Overall I vote to revert this PR for now. A follow-up could then implement the missing features of auto-detecting inside/outside, taking care of file backward compatibility, and don't change internal APIs where the previous names have been better.

@sliptonic, @jamwaffles what do you think?

**Comment by sliptonic** [comment]
If we revert, we go into the 1.0 release with non- standard terminology.  If we leave it alone, we go with bugs.  

IMHO, bugs are easier to fix.  They even encourage contributions.  

I recommend leaving it alone and documenting the bugs very clearly.

**Comment by jbaehr** [comment]
I agree that we generally should fix forward. In this particular situation I'm still not convinced, though. This MR here is just a blind search/replace, without any consideration of the actual semantics of the changed code. In my eyes, this is not an improvement.

Anyway, to move things forward, are open for a PR that
- Reverts this one, apart from translated UI strings (too late for this now, but maybe we can trick with the translation context)
- Changes the document objects Profile, Helix and Deburr to be in line with Pocket, MillFace and Pocket3D:
  - remove property "Direction" with values "CW" and "CCW"
    - or maybe better: leave it as hidden, calculated, property
  - add property "Cut Mode" with values "Climb" and "Conventional"
  - Upon document restore, check if we have property "Direction" but no "Cut Mode" and if that's the case
    - check for property "Side" ("Inside"/"Outside") in Profile and Deburr to infer the Cut Mode from the previous Direction
    - check for property "Start Side" ("Inside"/"Outside") in Helix to infer the Cut Mode from the previous Direction
- Changes the document object Threadmilling to be in line with the Pocket, MillFace and Pocket3D and now Profile, Helix and Deburr:
  - rename the property "Direction" (which already has the values "Climb" and "Conventional" there) to "Cut Mode"
  - Upon document restore, check if we have property "Direction" but no "Cut Mode" and perform the rename as necessary
- provides tests for loading documents from the previous FreeCAD version (something like commit 3933825)
- Keeps "direction" with the values "CW" and "CCW" in APIs like `Path.Geom.diffAngle`, where we have no ida about any potential cut mode

I can see what I can do; hopefully in time for v1.0 but unfortunately no guarantees.

**Pull request merged**
