### PR TITLE
[Path] Correction of drill speed calculation for grbl_G1 of 18.3

### PR DESCRIPTION
**Pull request by Jantek**

### CODE REVIEW

**Comment by sliptonic** [comment]
Why is this necessary? If you're using the metric small parts and cnc unit schema, the units fed to the post should be correct.

**Comment by Jantek** [comment]
Please look into line [304](https://github.com/FreeCAD/FreeCAD/blob/102b97aca7249891720aa5b99db36b40a512007f/src/Mod/Path/PathScripts/post/grbl_G81_post.py#L304): The feed rate is transferred from mm/s to mm/min. This also has to be done inside the drill_translate function as the original parameters gets passed to it. Else there is a mixed feed rate in the GCODE (mm/s for drills and mm/min for the rest). 

Original output:
```
(G81 X165.000 Y56.000 Z-3.000 F600.00 R10.000)
G0 Z10.000
G0 X165.000 Y56.000
G1 Z-3.000 F10.00
G0 Z10.000
```

Output of patched file:
```
(G81 X165.000 Y56.000 Z-3.000 F600.00 R10.000)
G0 Z10.000
G0 X165.000 Y56.000
G1 Z-3.000 F600.00
G0 Z10.000
```

**Comment by luzpaz** [comment]
@Jantek Do you mind opening a FreeCAD Path subforum discussion thread to discuss your contribution. I will help expedite a decision regarding it. Thanks. 

PS please post the thread url here so we can track its progress

**Comment by luzpaz** [comment]
@sliptonic is there a discussion about this PR ?

**Comment by luzpaz** [comment]
@Jantek please post a thread discussing this PR in the PR itself so devs/testers can link to for more context

**Comment by Jantek** [comment]
I opened a discussion in the FreeCAD Path forum. I will post a link here when the moderator accepted the thread.

**Comment by Jantek** [comment]
Here we go: [https://forum.freecadweb.org/viewtopic.php?f=15&t=39740](url)

**Comment by wwmayer** [comment]
Any news on this PR?

**Comment by Jantek** [comment]
No...

**Comment by sliptonic** [comment]
Will look into it today.

**Pull request merged**
