### PR TITLE
Part: fixes #9549: Part Fuse not working inside Part container

### LINKED ISSUE #9549: [Bug] Part Fuse not working inside Part container
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Arch Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33090 (Git)
Build type: Unknown
Branch: master
Hash: c5748fde7b5b975cab637ab99a016db93d882a85
Python 3.11.3, Qt 5.15.9, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * BOLTSFC 2022.11.5
  * BIM 2021.12.0
  * sheetmetal 0.2.63
  * Manipulator 1.5.0
```

### Subproject(s) affected?

None

### **How to reproduce:**
The bug is very simple to reproduce, in part workbench:

1.-Create two solid objects, for example press the cube and the cylinder icons
2.-Place both inside a Part container. (selecting both objects and pressing the yellow "create part" button)
3.-Select both solids make make part fusion.

Apparently it makes the fusion correctly but You get an error message: "Part::MultiFuse: Link(s) to object(s) 'Box Cylinder' go out of the allowed scope 'Fusion'. Instead, the linked object(s) reside within 'Part Part'." This is creating issues with gmsh when trying to create FEM meshes on the fused part.

If the two solids are taken out of the part container, the fusion goes flawlesly.

### **Expected behavior:**
Get one fused solid with no errors.

Thanks for your comments in advance!
Humberto

### Anything else?

This has been discussed in the forum 
[Here](https://forum.freecad.org/viewtopic.php?t=78251)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by 0penBrain** [comment]
@wwmayer Wouldn't that we worth adding (or modifying an existing) test ?

**Comment by wwmayer** [comment]
A test is a bit tricky because the logic to move the input shapes is part of the command. So, the test must change the selection and hope that the command is not inactive.

**Comment by wwmayer** [comment]
An alternative is to implement a helper class in Python that moves the input features as needed and creates the corresponding Boolean operation feature. For this Python function a unit test can be implemented.

**Comment by wwmayer** [comment]
See https://github.com/wwmayer/FreeCAD/tree/issue_9549_new

**Comment by 0penBrain** [comment]
> See https://github.com/wwmayer/FreeCAD/tree/issue_9549_new

Thanks for the link.
Notice I was fine with "adding a test is tricky". 😄 
Interesting though to see the tests are failing now in your branch. But didn't look if it comes from code or test. 😉

**Comment by 0penBrain** [comment]
> It's fixed now. It failed because in CLI mode ViewObject is None.

Great. Do you plan to open a subsequent PR, or would you merge your other branch to the one of this PR so it is updated ?

**Comment by wwmayer** [comment]
I will close this one and open the other one.

**Comment by luzpaz** [comment]
See #9594

**Pull request closed without merging**
