### PR TITLE
Mesh: Workaround to load 3mf files not supported by zipios library

### PR DESCRIPTION
**Pull request by wwmayer**
Fixes https://github.com/FreeCAD/FreeCAD/issues/11189

### CODE REVIEW

**Comment by luzpaz** [comment]
Thanks @wwmayer, out of curiousity, what makes said 3mf files incompatible with zipios ? (in english :blush: )

**Comment by wwmayer** [comment]
`https://github.com/Zipios/Zipios/issues/43#issue-1618151314`

**Comment by chennes** [comment]
Let's add a comment in the code someplace appropriate that documents that this is a workaround, and maybe links to this PR, or to the issue.

**Comment by maxwxyz** [comment]
@wwmayer could you please resolve the conflicts?

**Comment by Syres916** [comment]
@adrianinsaval this was never backported to the 1.0 branch that I can find and the fact that the `utils_zip.py` file can't be found suggests I'm on the right track, could you try a backport please? TIA

**Comment by adrianinsaval** [comment]
backported 25a3bd1239ac8556d0be9439ae7c4b3b9c1cff8e

**Pull request merged**
