### PR TITLE
Adding Image Scaling Macro to Image WB

### PR DESCRIPTION
**Pull request by easyw**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
The python3 travis build fails with this message:
```
Traceback (most recent call last):
  File "/usr/local/Mod/Test/TestPythonSyntax.py", line 44, in testAll
    test_python_syntax(mod_dir, self.whitelist)
  File "/usr/local/Mod/Test/TestPythonSyntax.py", line 27, in test_python_syntax
    raise RuntimeError("there are some files not parse-able with the used python-interpreter" + message)
RuntimeError: there are some files not parse-able with the used python-interpreter

##############################
1 python files are not parseable:

1 invalid syntax (/usr/local/Mod/Image/ImageTools/_CommandImageScaling.py, line 152)
```
IIRC py3 the except command takes parenthesis, which are supported in py2 too. So all that you need to do is change all `except args...` commands to `except(args...)`

**Comment by easyw** [comment]
@yorikvanhavre 
thanks, done it. 😄

**Comment by yorikvanhavre** [comment]
Thanks, that looks good. Let's wait for the builds to finish then I'll merge.

**Comment by yorikvanhavre** [comment]
Ok thanks, it's merged! The OSX build fails on all builds, there is something that needs to be fixed in master.

**Pull request closed without merging**
