### PR TITLE
Fixes #12494: Refactor PD patterns so Scaled works correctly with multiple features

### LINKED ISSUE #12494: [Problem] PartDesign scale transformation does not work with multiple features
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

A scale transformation in MultiTransform only works correctly on the first feature in the feature list.

pd_scale

The hexagonal hole is scaled correctly, but the round hole shifts because it is scaled based on the center of mass of the hexagonal hole.

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36005 (Git)
Build type: Unknown
Branch: main
Hash: c4daf256b2eb41fd75f8344d27890c14e1bcae08
Python 3.11.7, Qt 5.15.12, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.60.0
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.0.0
  * Assembly3 0.11.3
  * fasteners 0.4.21
```

### Subproject(s) affected?

PartDesign

#### Cause
The problem is expected, looking at the comment in the code:
https://github.com/FreeCAD/FreeCAD/blob/62c8469bded2f39099c7b067889052818b659fe9/src/Mod/PartDesign/App/FeatureScaled.h#L54-L63

This essentially results from the way the patterns are implemented. The ``getTransformations()`` function returns a list of transformations that are applied to the features:
```python
transformations = getTransformations(features)
for f in features:
  for t in transformations:
    tool_shape = f.transform(t)
    base_shape.fuse(tool_shape) # or cut
```
This requires two properties of the transformations:
1. The transformation is based on the LCS of the Body
2. The transformation is independent of the feature

Both are broken by the scale transformation:
1. The transformation is based on the center of mass
2. The center of mass is a property of the feature

The failure is mitigated for a single feature by providing the list of features to the ``getTransformations()`` function. But because the list of transformations is calcuated before the loop, this will only work for the first feature.

This also results in code duplication in MultiTransform and special handling for the scale transformation.

#### Solution
Instead of ``getTransformations()`` implement ``std::vector<TopoDS_Shape> applyTransformation(std::vector<TopoDS_Shape> const& shapes)``.

Then all transformation features can do what they need without the above requirements and the code should be cleaner.
Input is a list of shapes that should be transformed and the result is another list of shapes. The loop would be something like this:
```python
for f in features:
  tools = applyTransformation([f.shape])
  for t in tools:
    base_shape.fuse(t) # or cut
```
The use of ``std::vector<>`` is needed for MultiTransform:
```python
prevShapes = shapes
newShapes = []
for st in sub_transformations:
  newShapes = st.applyTransformation(prevShapes)
  prevShapes = newShapes
return newShapes
```
This is a rough sketch, there are probably some details I'm missing.

#### Change of behaviour
This could result in a small performance decrease because the transformations are not precalculated (and pre-multiplied by MultiTransform). I assume the scale transformation is rarely used, then this can be mitigated by providing the algorithm with the information if the transformations are independet of the features and then a code path with the same performance as currently can be used.

This could also break older files when they use the scale transformation with multiple features, but I would assume that is very
rare.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NomAnor**
This refactors the way the PD patterns apply their transformations to the feature list. It will also fix #12494.

### Explanation
The old code calculates the required transformations beforehand.
If a MultiTransform is used, the transformations from the subfeatures are pre-multiplied into a final list of transformations.
Then the transformations are applied to the feature shapes.

This requires that the transformations:
    1. Use the same coordinate system (that of the Body)
    2. Are independent of the shapes

Both are broken by the Scaled feature because:
    1. The effective coordinate system is the center of mass
    2. The center of mass is dependent on the shape

For the most often used case of a single feature, this is mitigated by supplying the list of shapes to the ``getTransformations()`` function. But this also requires code duplication in the MultiTransform feature and special handling of scale subfeatures.

In the new code the transformations are applied to the shapes directly, so that the transformations can be arbitrary.
For this, the function ``applyTransformation()`` is called with a list of shapes that should be transformed. The function returns a new list of transformed shapes.
For MultiTransform these calls are just chained in the order of subfeatures. The final list of shapes is then fused/cut with the base feature's shape.

#### Performance
The old code pre-calculated all transformations, but made an explicit copy of the underlying geometry for each shape and transformation. The new code only needs to make copies when necessary but can otherwise use sharing (internal ``TopoDS_TShape``) by only copying the ``TopoDS_Shape`` objects and changing the locations. I would assume that this might be a bit faster, but in any case the difference should be negligible.

There might be some more optimizations for Mirror and Scale that would only require a copy per shared ``TopoDS_TShape`` and then the rest of the transformations could be realized by copying the new ``TopoDS_Shape`` and changing it's location. But I'm not sure if the added complexity is worth the effort (and if I undestand the OCCT documentation correctly).

#### Output
There are changes in the behaviour of the scale feature that might break existing files:
    1. The center of mass of each shape is used instead of only the first
    2. The scale Occurrences don't need to be a multiple of the previous occurrences

I suspect that the order of scaling of the shapes worked a bit different with the old code. 
I thought the old code applied the scale to the occurrence groups of the previous feature, but playing around with it that does not seem constistent.
The new code scales the shapes in the order that the previous transformations created them, repeating the pattern if there are more shapes than occurrences.

If the new behaviour seems unexpected to users, I can try to change it to the expected behaviour.

### CODE REVIEW

**Comment by chennes** [comment]
@PaddleStroke could you please take a look at this?

**Comment by chennes** [comment]
@AjinkyaDahale do you have a moment to review this?

**Review by PaddleStroke — COMMENTED** [review]
Very little things

**Comment by luzpaz** [comment]
Fix typos

```
Warning: src/Mod/PartDesign/App/FeatureScaled.h:57: Occurences ==> Occurrences
Warning: src/Mod/PartDesign/App/FeatureScaled.h:58: Occurences ==> Occurrences
Warning: src/Mod/PartDesign/App/FeatureScaled.h:59: Occurences ==> Occurrences
```

**Review by pieterhijma — COMMENTED** [review]
I haven't looked much at the code, but it seems as if a `const std::list<gp_Trsf>` is replaced by a `std::vector<TopoDS_Shape>`. I can understand that this is more flexible, but it also made me think a bit about whether you can still call it a transformation. I then looked deeper into #12494 to understand the problem better. Now that I think of it, I think the behavior that you describe there is actually the behavior that I would expect. See my comments there.

**Comment by sliptonic** [comment]
There are some valid concerns raised on the original issue.  These were raised in the merge meeting today.  
I'm moving the PR back to draft status pending resolution of the issue discussion.

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale do you have a moment to review this?

@chennes @maxwxyz  sorry this slipped through. Is my review still needed?

**Comment by NomAnor** [comment]
This PR is blocked by a discussion in issue #12494. It is not clear how the scale feature should behave. The current implementation and some FIXME comment in the code seem to be in disagreement. 
@AjinkyaDahale maybe you can comment on issue #12494?

**Comment by maxwxyz** [comment]
@NomAnor @AjinkyaDahale is there already consensus on this discussion, I cannot find anything new in the issue.
Also here the reminder: If you want this draft PR to be considered for a version 1.0 release, it should be marked _ready for review_ by **Monday, 2024-06-03**

**Comment by NomAnor** [comment]
No, nothing new. I keep this as a draft, but I don't thing this is ready for 1.0

**Comment by maxwxyz** [comment]
@NomAnor pinged DWG/CWG on the issue. Hopefully this PR can be moved forward then.

**Comment by NomAnor** [comment]
I'm closing this as discussed in #12494.

**Pull request closed without merging**
