### PR TITLE
Source typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Your changes cause the build to fail... Generally, it's OK if you fix these typos in comments, but I would refrain from changing  class names or arguments if you don't mind... This could break other software or modules that are built on FreeCAD and that we don't know of.

**Comment by luzpaz** [comment]
@yorikvanhavre in general i skip source class name changes but I thought that these specific class names changes may merit correction as they may cause some confusion in the documentation because they are typos. I can alter the PR as you wish.

**Comment by luzpaz** [comment]
This time travis fails due to 
https://travis-ci.org/FreeCAD/FreeCAD/jobs/376376184#L8611-L8637

**Comment by yorikvanhavre** [comment]
merged

**Pull request closed without merging**
