### PR TITLE
Fix thumbnail preview on XDG desktops

### PR DESCRIPTION
**Pull request by pachi**
This fixes thumbnailing for XDG desktops. The new script doesn't depend on GNOME libs and works either with python3 or python2.
Also, a thumbnailer config file is added to the installation in CMakeList.txt

There's a missing step in the installation script, installing the freecad-thumbnailer script in the /usr/bin/ dir, though maybe some users may prefer not having the thumbnailer activated.

### CODE REVIEW

**Comment by luzpaz** [comment]
Nice. Thanks for your contribution!  
Please reference the [forum thread](https://forum.freecadweb.org/viewtopic.php?f=8&t=48509&p=451098#p451063) next time so the devs can reference it and understand the context + see if the community has vetted/tested the code.  

Also there is an open ticket concerning this: https://tracker.freecadweb.org/view.php?id=4475 which will help the devs to keep track of open issues and close them appropriately. In the future you can even use the webhook trigger commands to remotely reference and/or close bugs on our tracker. Info:https://wiki.freecadweb.org/Tracker#GitHub_and_MantisBT

Thank you!

**Comment by wwmayer** [comment]
> Also there is an open ticket concerning this: https://tracker.freecadweb.org/view.php?id=4475

The ticket is about the thumbnails of the recent files list shown in the start page of FreeCAD while this PR is about showing thumbnails inside the file manager of the DE.

**Comment by wwmayer** [comment]
Merged.

**Comment by luzpaz** [comment]
What was the commit associated with this PR ?

**Pull request closed without merging**
