### PR TITLE
Adding new points on wires tests the edge you clicked on instead of a…

### PR DESCRIPTION
**Pull request by Moult**
…n overcomplicated curve parameter check

 * Makes adding points on wires and closed wires simpler and more reliable
 * Minor code cleanup to reduce the nesting of "if" statements

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by Moult** [comment]
If it indeed works on bsplines perhaps we can purge some obsolete code, e.g. https://github.com/FreeCAD/FreeCAD/blob/5ccc65606e4e9cc4d864cbb72dc32785032a24d3/src/Mod/Draft/DraftTools.py#L4443

**Comment by yorikvanhavre** [comment]
Yes, you are right. However, it's maybe best to test that before...

**Comment by Moult** [comment]
I just tested it and it doesn't seem to work on BSplines, perhaps because BSplines are inherently parametric whereas regular wires are not. Perhaps it is best to revert 5ccc656?

**Comment by yorikvanhavre** [comment]
draft bsplines have exactly the same properties as draft wires (a series of points). So inserting a new point in the list should work too. But I'll give it a test spin when I have a moment

**Comment by yorikvanhavre** [comment]
Okay I just tested, the problem is that the bspline is actually made of one single edge. So your change indeed doesn't work for them. Reverting 5ccc656 and merging...

**Comment by luzpaz** [comment]
@Moult did this address http://freecadweb.org/tracker/view.php?id=3787  
https://forum.freecadweb.org/viewtopic.php?f=3&t=33622&p=359676#p282862

**Pull request merged**
