### PR TITLE
[PartDesign] OCC7.3 regression replace include..

### PR DESCRIPTION
**Pull request by Syres916**
..removed by https://github.com/FreeCAD/FreeCAD/commit/61d54b60786a0b7cefc44f965cf5d179726a8d20

Tested against : 

OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.20.27663 (Git)
Build type: Release
Branch: master
Hash: 5007c8358c21f2da5a08684f1e00247c1a842d7d
Python 3.6.9, Qt 5.9.5, Coin 4.0.0a, OCC 7.3.0
Locale: English/UnitedKingdom (en_GB)

and

OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.20.27663 (Git)
Build type: Release
Branch: master
Hash: 5007c8358c21f2da5a08684f1e00247c1a842d7d
Python 3.6.9, Qt 5.9.5, Coin 4.0.0a, OCC 7.6.0.beta
Locale: English/UnitedKingdom (en_GB)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6402">pipeline status</a> for feature branch [PR_6402](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6402). Pipeline [475174818](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/475174818) was triggered at [03b051d](https://github.com/FreeCAD/FreeCAD/pull/6402/commits/03b051d437caf4540dfa0953fab8c44f1abfaabb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Why is gp_Pln.hxx needed? It is not used by the code, the CI compiler and MSVC compiles fine.

What is the error you get? Could you please try to recompile PD from scratch? (At least for MSVC I have to do this sometimes when headers were changed to assure the compiler has nothing cached.)

**Comment by Syres916** [comment]
gp_Pln.hxx must be used by OCC7.3 because when I take that out it causes the following error and when I put it back the error disappears and then fact that OCC7.6 doesn't need it proves it to me beyond doubt:

```
[ 91%] Built target PathGui
/home/john/freecad-daily-source/src/Mod/PartDesign/App/FeaturePocket.cpp: In member function ‘virtual App::DocumentObjectExecReturn* PartDesign::Pocket::execute()’:
/home/john/freecad-daily-source/src/Mod/PartDesign/App/FeaturePocket.cpp:75:61: error: ‘Precision’ has not been declared
         (UpToFace.getValue() == NULL && Length.getValue() > Precision::Confusion()))
                                                             ^~~~~~~~~
/home/john/freecad-daily-source/src/Mod/PartDesign/App/FeaturePocket.cpp:80:68: error: ‘Precision’ has not been declared
     if ((std::string(Type.getValueAsString()) == "Length") && (L < Precision::Confusion()))
                                                                    ^~~~~~~~~
/home/john/freecad-daily-source/src/Mod/PartDesign/App/FeaturePocket.cpp:84:72: error: ‘Precision’ has not been declared
     if ((std::string(Type.getValueAsString()) == "TwoLengths") && (L < Precision::Confusion()))
                                                                        ^~~~~~~~~
/home/john/freecad-daily-source/src/Mod/PartDesign/App/FeaturePocket.cpp:138:22: error: ‘Precision’ has not been declared
         if (factor < Precision::Confusion())
                      ^~~~~~~~~
[ 94%] Built target TechDraw
[ 94%] Automatic MOC for target TechDrawGui
[ 94%] Built target TechDrawGui_autogen
src/Mod/PartDesign/App/CMakeFiles/PartDesign.dir/build.make:327: recipe for target 'src/Mod/PartDesign/App/CMakeFiles/PartDesign.dir/FeaturePocket.cpp.o' failed
make[2]: *** [src/Mod/PartDesign/App/CMakeFiles/PartDesign.dir/FeaturePocket.cpp.o] Error 1
CMakeFiles/Makefile2:2509: recipe for target 'src/Mod/PartDesign/App/CMakeFiles/PartDesign.dir/all' failed
make[1]: *** [src/Mod/PartDesign/App/CMakeFiles/PartDesign.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Built target TechDrawGui
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

I really think you need a more comprehensive testing lab because merging these commits without anyone else doing any quality control.

**Comment by donovaly** [comment]
OK, but then the correct fix is to add Precision.hxx.

Strange that it compiles on several machines without this header.

> I really think you need a more comprehensive testing lab

I think we have an acceptable testing lab. And you are part of it ;-). I mean as you can see in the commits, we have tons of unused stuff in our headers and nobody took care yet exactly because the danger is to break something. Now, close the next release it is time to be brave and do the job. When there are issues, like in this case, we can quickly act. Therefore many thanks for testing. I assume more issues will arise, but let's nevertheless please do the header work. In the end it will payout by less compile times and maybe even smaller file size due to less linked libraries.

**Pull request merged**
