### PR TITLE
[Draft] Remove Draft Drawing command from toolbars and menus

### PR DESCRIPTION
**Pull request by carlopav**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
Just for reference, I integrated these changes in #3308.

**Comment by carlopav** [comment]
@vocx-fc Can I close the PR so?

**Comment by vocx-fc** [comment]
It's up to you. If this is merged first, then I have to rebase my branches.

In any case the result will be the same, the Drawing command won't appear in the toolbar.

**Comment by carlopav** [comment]
let's just delete it so! :)

**Pull request closed without merging**
