### PR TITLE
part: bspline: test

### PR DESCRIPTION
**Pull request by looooo**

### CODE REVIEW

**Comment by looooo** [comment]
problems with copy.deepcopy:

```
ERROR: testSetters (TestPartApp.PartTestBSplineCurve)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Part/TestPartApp.py", line 85, in testSetters
    spline = copy.deepcopy(self.spline)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(method_descriptor) is not safe, use method_descriptor.__new__()
```

**Comment by wwmayer** [comment]
The osx build gives a slightly different type error:
> TypeError: can't pickle method_descriptor objects

**Comment by looooo** [comment]
so better not use deepcopy on freecad objects

**Comment by wwmayer** [comment]
According to https://docs.python.org/2/library/pickle.html#module-pickle you can make e.g. a tiny wrapper class which implements __setstate__/__getstate__ and inside there you return the relevant information about the spline

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
