### PR TITLE
(hold - do not merge) TechDraw Response Time 

### PR DESCRIPTION
**Pull request by WandererFan**
This PR addresses an issue of slow response by TechDraw.  Under certain conditions, unnecessary screen paints were being performed.  These have been removed.    Please merge.
Thanks,
wf

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Have you realized that on travis it causes a crash inside DrawProjGroup::getDirsFromFront(string)?

**Comment by WandererFan** [comment]
Fails self-test.  Revisions coming.

**Comment by wwmayer** [comment]
DrawProjGroup::getAnchor() returns null which isn't checked in DrawProjGroup::getDirsFromFront() and so it causes the segfault.

**Comment by wwmayer** [comment]
Another point:
There are several places in DrawProjGroup where a static_cast is applied on an unverified type which is dangerous. From Python it would be easy to change a link property to point to any other object and the above static_cast will cause undefined behaviour if the object has the wrong type.

Solution:
Either use dynamic_cast or check with getTypeId().isDerivedFrom(...) before doing a static_cast.

**Comment by WandererFan** [comment]
Will open a new PR when dynamic_cast issue is cleared.

**Pull request closed without merging**
