### PR TITLE
[Import] DXF make codepage case insensitive

### PR DESCRIPTION
**Pull request by Syres916**
See discussion https://forum.freecad.org/viewtopic.php?t=78719

I don't believe https://github.com/FreeCAD/FreeCAD/issues/8704 is fixed even after this change, the example file Encoding-error.dxf which can be opened by VariCAD Viewer still opens error free in FreeCAD but has nothing in the 3D View.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by Syres916** [comment]
@yorikvanhavre Could you please review this PR, TIA

**Review by yorikvanhavre — APPROVED** [review]
Looks good to me! I was wondering if there isn't a better way to convert a string to lowercase, you could [use boost](https://stackoverflow.com/questions/313970/how-to-convert-an-instance-of-stdstring-to-lower-case):

 ```
[Boost provides a string algorithm for this](https://www.boost.org/doc/libs/1_70_0/doc/html/boost/algorithm/to_lower.html):

#include <boost/algorithm/string.hpp>

std::string str = "HELLO, WORLD!";
boost::algorithm::to_lower(str); // modifies str

[Or, for non-in-place](https://www.boost.org/doc/libs/1_70_0/doc/html/boost/algorithm/to_lower_copy.html):

#include <boost/algorithm/string.hpp>

const std::string str = "HELLO, WORLD!";
const std::string lower_str = boost::algorithm::to_lower_copy(str);
```

But I leave that to you... If you prefer to stick with this version we merge it as is

**Comment by Syres916** [comment]
Thanks for the feedback Yorik but I did try the boost method and failed miserably, so I'm happy to merge as is.

**Comment by yorikvanhavre** [comment]
ok done!

**Pull request merged**
