### PR TITLE
Backport PR #17119 into 1.0

### LINKED ISSUE #17392: PartDesign: Applying a pattern to a curved pipe can produce incorrect geometry
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Applying a PartDesign pattern (polar pattern, linear pattern, mirror) to a pipe can sometimes lead to incorrect geometry.

The basic shape of the additive pipe:
BaseShape
The pipe after applying a linear pattern of 40 mm overall length, 2 occurences, along the BaseX axis:
LinearPattern
The pipe after applying a Mirror pattern around the YZ-plane:
Mirror
The pipe after applying a 360 deg total angle, 2 occurences Polar pattern around the base Z-axis:
PolarPattern

Strangely enough, this problem does not occur if a different order is applied, where the bent section is removed from the guide-line sketch, then the pattern is applied, and then the bend section is reintroduced. In this case, instead the following (correct) result is obtained:
PolarCorrect

### Full version info

```shell
System 1:
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: English/United Kingdom (en_GB) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
  * A2plus 0.4.68

System 2 (used for verification by running Macro's):
OS: macOS Mojave (10.14)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: C/Default (C) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Render 2024.9.25 (Disabled)
  * A2plus 0.4.68
  * Curves 0.6.50
```

### Subproject(s) affected?

PartDesign

### Anything else?

The following zip file contains both the .FCStd file, and the .FCMacro file that creates bugged geometry.
[PipeTest.zip](https://github.com/user-attachments/files/17465734/PipeTest.zip)
The following macro does successfully create the polar pattern:
[Run7.FCMacro.zip](https://github.com/user-attachments/files/17466048/Run7.FCMacro.zip)
Please note: This macro is slightly modified from a recorded macro, since the recorded macro could not be run without errors. The steps taken are the same between the original (recorded) macro, and this version.

The following file contains the .FCStd file which has the bugged geometry, as created in Release Candidate 2.
[PipeTestBugged.zip](https://github.com/user-attachments/files/17465794/PipeTestBugged.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AIRCAP**
fix #17392  (waiting for reporter confirmation)

Backport of #17119 into 1.0.

For now this PR is a draft to test if backporting even works or introduces undesired behavior or compilation errors from a technical side.

Once #17119 is merged in main this can later serve as a PR to consider the backport itself.

Method: 
1. combined all the commits in #17119 up to and including 81e17b76c435453eedae38a2c50e74e03be8f706 into a single commit (diff with main)
2. cherry pick that commit into releases/FreeCAD-1-0

if more commits get pushed into #17119 I would likely force-push them here in a new single commit

### CODE REVIEW

**Comment by AIRCAP** [comment]
@wwmayer #17119 has been merged into main and can see wider testing now.  I changed this review from draft mode into review mode to discuss steps forward (and any potential regressions that might pop up)

**Comment by AIRCAP** [comment]
did a last force-push based on latest release-1.0 with the commit to main cherry-picked

**Comment by AIRCAP** [comment]
FYI. there is a user on the forum who claims he has broken files from this ---
https://forum.freecad.org/viewtopic.php?p=788624#p788624
I do not know if this information is trustworthy based on the other posts, and no example files have been shared. Does anyone know of any reproducible regression caused by this?

**Comment by yorikvanhavre** [comment]
Waiting for issues to be fixed

**Comment by AIRCAP** [comment]
> Waiting for issues to be fixed

@yorikvanhavre  the reporter in #17543 can't share the file that triggered the issue - without that I can't reproduce - what do we do?

**Comment by chennes** [comment]
We have only heard of two possible issues. The first is only on the forums (e.g. no Issue created), with no detail, no follow-up, and of suspect provenance. The second is replicable in RC2 so cannot be caused by the #17119 PR. I believe this leaves us a clear path to merge this PR.

**Comment by yorikvanhavre** [comment]
Leaving this open for another week to see where the forum discussion is going. Decision to merge or not to be taken next monday

**Pull request merged**
