### PR TITLE
[Python] Re-enable Flake8

### PR DESCRIPTION
**Pull request by Vanuan**
Just to get an idea of what it takes to fix issues

Discussion:
https://forum.freecadweb.org/viewtopic.php?f=4&t=37405&start=10

### CODE REVIEW

**Comment by vocx-fc** [comment]
Flake8 is mostly for syntax conventions, so that the code follows PEP8.

There is already a Python unit tests that checks syntax in Python files. This already works in Travis; whenever a pull request is made, this test runs, and many times it has indicated errors in Python, particularly for Python 2.
* [TestPythonSyntax.py](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Test/TestPythonSyntax.py)

I think it is enough for now, unless you have a specific reason for which flake8 should be used as well. Do notice that FreeCAD's code is extremely non-PEP8 compliant because several people have worked on the code over the years with seemingly not a lot of consistency. FEM is probably the most compliant, then Draft, and then the rest.

**Comment by Vanuan** [comment]
> Flake8 is mostly for syntax conventions, so that the code follows PEP8.

Yeap. You mentioned several times that you want snake case to be adopted. That's exactly what flake8 is meant to enforce.

> There is already a Python unit tests that checks syntax in Python files

That's not enough.

> Do notice that FreeCAD's code is extremely non-PEP8 compliant

I've noticed. It's extremely irritating that reviewers are nitpicking stuff that should be enforced by the code style checker. There's a much better use of  their time.

> Also, most Python functions that are defined in C++ mostly use camelCaseConvention, so they are also not compliant and can be tested by flake8 because there is no explicit Python code.

Didn't you mention those are to be converted to snake_case as well?

**Comment by Vanuan** [comment]
It looks like flake8 can do some checking, after all:
```
./src/Mod/TechDraw/Init.py:28:1: F821 undefined name 'FreeCAD'
FreeCAD.__unit_test__ += [ "TestTechDrawApp" ]
```

**Comment by vocx-fc** [comment]
> How does it work exactly? Does FreeCAD import something before executing a module?

Yes. The thing is the loading process of FreeCAD works in mysterious ways. If I remember correctly, the initialization modules, `Init.py` and `InitGui.py`, are passed to an `exec()` function. They aren't loaded as regular Python modules. This is the reason inside these modules, `FreeCAD` is already defined from the calling environment, as well as many other things.

When you use flake8, it doesn't detect that `FreeCAD` was imported, and will mark it as an error. But the actual FreeCAD program doesn't have a problem with it because `FreeCAD` is in fact imported before this. Look for the files called `FreeCADInit.py` and `FreeCADInitGui.py` in the source code which contain the basic initialization code.

In Draft and Arch, I prefer to be explicit about this, and actually import FreeCAD, but this is just for consistency in the file.

Enforcing PEP8 would be good, but it is a titanic task, that will take many years to accomplish. So I suggest you set your expectations accordingly and don't try to do too much in a short span. It's better if you set your goals on something manageable and work on that. I have set myself the goal of updating the PEP8 style of Draft and Arch, but I don't expect to finish any time soon at the current development pace. So, the best thing you could do is try to get more programmers and people to help, and work on your own as well.

**Comment by Vanuan** [comment]
> that will take many years to accomplish

Well, if you don't start something it'll always be many years to accomplish.

**Pull request closed without merging**
