### PR TITLE
Path: Assign Contour label on restore fixes 2770

### PR DESCRIPTION
**Pull request by mlampert**
* consolidate contour label generation
* only touch dependent TC objects if the tool number changed;
* changed formatting of intermediate path representation to be valid g-code and not use exponents.

http://www.freecadweb.org/tracker/view.php?id=2770

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This commit fails to build on windows (see the appveyor log): C:\projects\freecad\src\Mod\Path\App\Command.cpp(138): error C3861: 'snprintf': identifier not found

**Comment by mlampert** [comment]
I added in the include which, according to the MSC documentation should do the trick, yet it failed again - I'm looking for an alternate solution.

**Comment by mlampert** [comment]
My bad, didn't consider the MSC version. It seems snprintf support only comes with MSVC 2014:
https://connect.microsoft.com/VisualStudio/feedback/details/809403/error-c3861-snprintf-identifier-not-found-in-visual-studio-2013

**Comment by wwmayer** [comment]
That's weird. snprintf is already used in many places in the code and the compiler doesn't complain about it. There is a variant of this method that starts with an underscore and is definitely available since msvc6 which is from 1998. So, maybe there is somewhere a hidden define that sets snprintf to _snprintf.

Nevertheless IMO it's a good thing to use real C++ functions instead of C functions which can easily become dangerous if not used correctly.

**Comment by mlampert** [comment]
I agree about using C++, except for the print formatting, they really screwed that one up. Anyhow, I wanted to use snprintf because I can control the precision, whereas std::to_string is fixed 6 digits after the comma.  I talked to sliptonic and he thinks that's still plenty, so we get away with it this time.

**Comment by wwmayer** [comment]
I think to_string shouldn't be used because it may return unexpected results: see here http://en.cppreference.com/w/cpp/string/basic_string/to_string (for 1e-9 it returns "0.000000")

You have two alternatives:
1. Use QString and its arg method. This works similarly to printf & friends
2. Use std::stringstream
`
#include <sstream>
std::stringstream stream;
stream << std::setprecision(12) << std::fixed << value;
std::string str = stream.str();
`

**Comment by mlampert** [comment]
Actually that was intentional. I originally had limited it to 9 digits just to be shure which brings resolution down to 1nm for metric and 25nm for imperial - both well below machine capabilities today.

I didn't want to use stringstream for it's poor performance (considering large jobs).

**Pull request merged**
