### PR TITLE
Part: `GeomBSplineCurve::interpolate` without tangency

### PR DESCRIPTION
**Pull request by ageeye**
Please see the [topic](https://forum.freecadweb.org/viewtopic.php?f=10&t=68838).

I will require it later for new importer. 

edit:

[cross-reference](https://github.com/ageeye/FreeCAD/blob/dxfNext/src/Mod/Import/App/dxf/fcDxfReader.cpp)

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6914">pipeline status</a> for feature branch [PR_6914](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6914). Pipeline [547237893](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/547237893) was triggered at [3ba395c](https://github.com/FreeCAD/FreeCAD/pull/6914/commits/3ba395cf485eca69554f488fa955bdc7b4bde850). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
For future reference, use `git rebase` instead of `git merge`. It leaves less clutter in the git history.

**Comment by ageeye** [comment]
> For future reference, use `git rebase` instead of `git merge`. It leaves less clutter in the git history.

Thanks for the hint. I didn't realize that. I used GitHub website for this. Now I try it with GitHub Desktop. Please check my new PR.

**Comment by ageeye** [comment]
> BTW, there is no need to open a new PR for this. But git isn't very intuitive and we've all been there so it's cool. Please x-post the new PR to this deprecated PR and close it. Thanks 😉

I think we're talking at cross purposes. I create new PR to other topic. Sorry for the confusion.

**Comment by ageeye** [comment]
@luzpaz Can you label this PR with "For 0.21"? There is no stress.

**Pull request merged**
