### PR TITLE
[hold] [Path] bugfix/8064-vcarve-skipping-certain-letters

### PR DESCRIPTION
**Pull request by mlampert**
- Rounding Voronoi input values after scaling for numeric stability

This seems to fix issue #8064 - however - I have currently no explanation as to why and how. Using an integer cast instead of `round` does _not_ fix the issue. It would be nice to understand what is going on and why this should fix it - hence the hold.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8111">pipeline status</a> for feature branch [PR_8111](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8111). Pipeline [735721969](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/735721969) was triggered at [c8dfc0a](https://github.com/FreeCAD/FreeCAD/pull/8111/commits/c8dfc0a84e1d6fb98fba6d918c88548de3e3a2b7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by br4243** [comment]
Just following up on this from the #8064 discussion.  The problematic letters occur when the path discretizer aims for the terminal vertex (presumably it could be any vertex?) and misses slightly.  insert_many_wires() closes the letter's outline polygon with a little short segment.

If Vcarve round()s like your fix, that slight miss vertex and the target vertex end up identical so the short segment added by insert_many_wires() goes to zero length, which doesn't hurt anything as long as orthognalProjection() checks for zero length segments.

Boost's Voronoi sweep line algorithm truncates the coordinates it gets to integer values, so there's a reasonable chance the two vertices that were close in FC's floating point coordinate system end up separated by one or two Manhattan distance abscissa values in Boost's coordinate system.  There's a further chance that the separation induced by that truncation makes the letter's outline polygon in Boost's coordinate space contain self-crossings, resulting in garbage out of VoronoiBuilder.

**Comment by sliptonic** [comment]
Ping @mlampert  
Can we get an update here?  If this is pending some future work, can we convert it to draft?

**Comment by mlampert** [comment]
Closing this PR since it didn't actually fix the issue.

**Pull request closed without merging**
