### PR TITLE
Create gmsh mesh on OK click if Apply not pressed

### PR DESCRIPTION
**Pull request by kkremitzki**
In FEM workbench, if one creates GMSH mesh and just clicks 'ok' but not 'apply' first, no mesh is created. This checks for that condition and creates a mesh first.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
It is intended to not create a mesh on ok! Mesh creation could tke hours, and click on ok by accident is quite common.

**Comment by kkremitzki** [comment]
If one means to click 'Cancel' it seems just as possible to mis-click 'Apply' as 'Ok'. Not having a mesh created on 'Ok' is unintuitive and surprising to me as a user. The correct way to avoid having an unintended long-running mesh job, imo, is to be able to kill the mesh creation, not require twice the clicks on every mesh generation.

**Comment by wwmayer** [comment]
Usually the OK button has the role to do what the Apply button does and then closes the dialog. Any other behaviour is uncommon and unintuitive.
So, if you are concerned that a click by accident will eventually block the user for a long time wouldn't it be better to either:
* open a further dialog asking the user to continue or
* remove the OK button completely

**Comment by berndhahnebach** [comment]
Ok, than we could add another popup and an adjustment to show the popup or not show the popup. The problen on huge meshes if you click on ok by accident. You loose the mesh and ob huge meshes it could take a looooong time to recreate it. bernd

**Comment by sasobadovinac** [comment]
Bernd obviously has a good argument but it is indeed unintuitive as it is and I was also puzzled about if for some time in the past. However adding more buttons, settings and popups is also also IMO not the way to go. Can we maybe improve it just by renaming the buttons (ok -> close, done; apply -> create)?

Also at the moment a new empty mesh object is created in the tree as soon as one opens the dialog, mesh is created only on apply, is there a difference between ok and cancel?

**Comment by kkremitzki** [comment]
Is it ok to rework this commit into changing the buttons to "Apply" and "Cancel"? From a logical standpoint I think "Close" only sounds right in the context of editing a mesh, e.g. from double-clicking it in the tree.  "Cancel" works to exit the editing state you've entered in my example, and it works to exit the creation state you'd enter if you had clicked the Create GMSH button.

If I had clicked the Create GMSH button and then clicked "Close", it might not be clear that the mesh object I'd created would be cleaned up. This is the current behavior as mentioned which I believe is a bug.

> Also at the moment a new empty mesh object is created in the tree as soon as one opens the dialog, mesh is created only on apply, is there a difference between ok and cancel?
Created https://freecadweb.org/tracker/view.php?id=2988

**Comment by sasobadovinac** [comment]
IMO the common expected behavior for a "Cancel" button is that the changes you make in a dialog are reversed to the original state before you entered the dialog and edit... I don't see this behavior in this case, if I hit "Apply" the mesh is created / updated and I see no difference in choosing "OK" or "Cancel" after it. It is why "Close" or  "Done" seem more appropriate to me for the way it works currently. But I am not using FEM to often and I had to quickly review some of my comments, so maybe I am wrong or misunderstand some things.

**Comment by ianrrees** [comment]
I agree with @sasobadovinac - "Apply" and "Cancel" have quite specific meanings, and it's not good practice to repurpose them.  I think "Create" or something like that for the positive button, and I think it's worth considering not having the negative button at all.  If we keep the negative button, then "Close" sounds good to me.

Good article that discusses similar things: https://www.nngroup.com/articles/top-10-application-design-mistakes/

**Comment by sgrogan** [comment]
Whatever is decided should be consistent with the gmsh and netgen meshers. It's not now.

**Comment by wwmayer** [comment]
Now, how should we continue on this?

**Comment by berndhahnebach** [comment]
> Usually the OK button has the role to do what the Apply button does and then closes the dialog. Any other behaviour is uncommon and unintuitive.
So, if you are concerned that a click by accident will eventually block the user for a long time wouldn't it be better to either:
    open a further dialog asking the user to continue or
    remove the OK button completely

I'd be for another dialog and the possibility (a preference) to omit the dialog on further use of the object (the ok button) (some user will complain about the dialog for sure) . I haven't had the time to do any development in the last few days ...

**Comment by kkremitzki** [comment]
Closing this PR to create a new one...

**Pull request closed without merging**
