### PR TITLE
[TD]Add sodipodi namespace to exported SVG

### PR DESCRIPTION
**Pull request by WandererFan**
Some TechDraw templates still contain Inkscape-centric SVG.  When exporting a Page, the exported SVG doesn't not include namespace definition for "sodipodi" (predecessor of Inkscape).  This PR adds the missing namespace definition. 

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by benj5378** [comment]
But does SVGs still need the sodipodi namespace? Are sodipodi attributes used in the files?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5491">pipeline status</a> for feature branch [PR_5491](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5491). Pipeline [462998129](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/462998129) was triggered at [fd75b27](https://github.com/FreeCAD/FreeCAD/pull/5491/commits/fd75b27a6becbdbb1ae1ae91d2fca2728f83cdbc). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
Somewhere, there is a statement that all templates should be in plain SVG -
no Inkscape/sodipodi extensions.

If I scan the Templates directory for "inkscape", I get lots of hits, so I
guess the answer is yes, currently the exported SVGs do need inkscape and
sodipodi namespaces.

**Comment by benj5378** [comment]
@WandererFan I am not sure I understand the argumentation of this? The sodipodi namespace should only be added if sodipodi attributes are used? If it should be plan SVG, then the templates should use have inkscape nor sodipodi words/attributes/names in them?

**Comment by WandererFan** [comment]
Yes, all the templates should be changed to plain SVG, but that is a long
boring job and in the interim, exported SVG won't display correctly in
browsers.  So we add the namespace definitions while we're waiting for
changes to the templates.

**Pull request merged**
