### PR TITLE
Path: Fix automatic `commitTransaction()` calls, issue #6149 [Bug]

### LINKED ISSUE #6149: Canceling a dressup does not clean up properly
Issue imported from https://tracker.freecad.org/view.php?id=4532

* **Reporter:** sliptonic
* **Date submitted:** 1/12/2021
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

If user tries to add a dressup and then cancels before completing, the project is not cleaned up properly and the dressup is created anyway.

# Additional information

This affects all dressups.

# Steps to reproduce

Create a job and operation.
Select an operation and add a dressup.  
Once the task panel opens, press 'cancel'
note the state of the tree.

# FreeCAD Info

```
OS: Linux Mint 20 (i3/i3)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23587 +23 (Git)
Build type: Unknown
Branch: (HEAD detached at mlampert/feature/toolbit-free-properties)
Hash: e0f1829ac9238b52bc6f2050b7bf1b2a7d8a69be
Python version: 3.8.5
Qt version: 5.12.8
Coin version: 4.0.0
OCC version: 7.3.0
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

### PR DESCRIPTION
**Pull request by Russ4262**
This commit removes the automatic committal of transactions when activated with GUI command.  The committal of the transaction is executed with the `accept()` and `reject()` methods of the respective task panel.

issue #6149 
fixes #6149 
No related forum thread found via "dressup cancel" search.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6576">pipeline status</a> for feature branch [PR_6576](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6576). Pipeline [490848719](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/490848719) was triggered at [20e3657](https://github.com/FreeCAD/FreeCAD/pull/6576/commits/20e365712536c33bfc5b5581b0f2405107576bb6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
JFYI @Russ4262 to auto-close a ticket via a PR the correct command is `Fixes #6149` or `Closes #6149`. 
It's those combinations or we have to close those tickets manually.

**Comment by Russ4262** [comment]
@luzpaz Thanks for the tip. Do those commands have to be in the commit message/description, or is inclusion in the PR title or PR description sufficient? What is preferred? 

Thanks for your guidance.

**Comment by luzpaz** [comment]
I'm not certain and it's a little [ambiguous](https://github.blog/2013-01-22-closing-issues-via-commit-messages/) but I always add them in the commit message body. And since we're on the topic if you don't mind prepending the `[Bug]` description to the front of the commit name instead of appending it to the end

Use: `Path: [Bug] Fix automatic commitTransaction() calls`
instead of: `Path: Fix automatic commitTransaction() calls, issue #6149 [Bug]`  
(though most other devs don't find it necessary to add that to the description at all.)

**Comment by Russ4262** [comment]
@luzpaz 
Did some research on your keyword comments provided above. 
Found these two helpful resources:
* https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
* https://stackoverflow.com/questions/12235620/automatically-closing-issue-from-pull-request-in-github

As a result, I will edit my remaining open bug fixes with the appropriate keywords and numbers.

**Pull request merged**
