### PR TITLE
Arch: Fixed trackers ending too soon

### LINKED ISSUE #13915: [Problem] Arch: crash when creating a structure object
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Switch to Arch wb
2. Create a structure object
3. Click into the 3D view
4. After a while FreeCAD crashes

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37239 (Git)
Build type: debug
Branch: main
Hash: 03a371d6e37f4ce47f5ffed7d5b039c5866a7e05
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

Arch

### Anything else?

Forum thread: https://forum.freecad.org/viewtopic.php?t=87493

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yorikvanhavre**
Deletes the trackers only after recompute
Fixes #13915

### CODE REVIEW

**Comment by maxwxyz** [comment]
@netikras can you build this yourself and check if this solves https://github.com/FreeCAD/FreeCAD/issues/13990 as well?

**Comment by maxwxyz** [comment]
@cpmach could you confirm if this also fixes https://github.com/FreeCAD/FreeCAD/issues/12682

**Comment by cpmach** [comment]
I really want to help you to help myself but I don't know what I am
supposed to do.
Can you help with that too?


Max Wilfinger ***@***.***> escreveu (quinta, 16/05/2024 à(s)
09:42):

**Comment by yorikvanhavre** [comment]
I'll merge as it is reported to fix the problem on https://forum.freecad.org/viewtopic.php?p=759627#p759627

**Comment by cpmach** [comment]
Hi!
As I'm not sure of what I have to do I started by installing the latest
weekly-builds and I changed the control to use any other then "Gestube".
Until now it's working well.
BIG THANKS

Yorik van Havre ***@***.***> escreveu (sexta, 17/05/2024 à(s)
11:14):

**Pull request merged**
