### PR TITLE
Draft: fix isClosed bug in offsets.py

### PR DESCRIPTION
**Pull request by Roy-043**
Use built-in `isClosed()` function instead of `isReallyClosed()` which is buggy.

Forum topic:
https://forum.freecadweb.org/viewtopic.php?p=567221#p567221

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5496">pipeline status</a> for feature branch [PR_5496](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5496). Pipeline [464174147](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464174147) was triggered at [c236649](https://github.com/FreeCAD/FreeCAD/pull/5496/commits/c236649595976c11e0049083ca031d1eb4510ca1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Roy-043** [comment]
Note that I have also refactored the `connect` function. The old code would calculate each intersection twice, I wanted to avoid that.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5496">pipeline status</a> for feature branch [PR_5496](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5496). Pipeline [467795279](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/467795279) was triggered at [6dacdbf](https://github.com/FreeCAD/FreeCAD/pull/5496/commits/6dacdbf93f6c8e6a019b22c6e402bb006247a6ef). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Okay, seems good. Thanks!

**Pull request merged**
