### PR TITLE
Gui: Set spin projector sphere depending on rotation center

### LINKED ISSUE #17246: Navigation: Trackball rotation around X view axis broken
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When set to trackball, view navigation does not rotate correctly when moving the mouse vertically in the viewport.  Horizontal seems correct.  Possibly not accounting for rotation point offset?

Video:
https://github.com/user-attachments/assets/12e7e1df-e1a8-4b59-8550-0be193ee001b

Settings:
image

### Full version info

```shell
OS: Linux Mint 20.3 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38946 (Git) AppImage
Build type: Release
Branch: main
Hash: e478192aa5393de9b7df190341a043f79ec6ac49
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Rexbas**
Fixes #17246.

https://github.com/user-attachments/assets/2a73a41f-5b79-49aa-942b-1551aa8db639

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
merged into main, but waiting for testing by the community before backporting to 1.0

**Comment by maxwxyz** [comment]
@Rexbas is this also changed regardless of the preference rotate at cursor or around window center or is just one specific navigation mode changed?

**Comment by Rexbas** [comment]
Only object center and rotate at cursor mode are affected.

**Comment by FlachyJoe** [comment]
This new implementation doesn't work correctly if the viewport is rotated around its normal axis:
tempo
```
OS: Debian GNU/Linux trixie/sid (XFCE/xfce/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39029 +6 (Git)
Build type: Debug
Branch: dev
Hash: 126f0abca4b105b606c0e6b970a065ac76266c57
Python 3.12.7, Qt 5.15.13, Coin 4.0.2, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US) [ OS: French/France (fr_FR) ]
Stylesheet/Theme/QtStyle: unset/Classic/Qt default
```

**Comment by maxwxyz** [comment]
can confirm.
@Rexbas could you take a look at it again?

**Comment by Rexbas** [comment]
With which navigation style, orbit style and rotation mode does that happen?

**Comment by maxwxyz** [comment]
I'm using CAD orbit around window center

**Comment by maxwxyz** [comment]
Trackball

**Comment by Rexbas** [comment]
I cannot reproduce the situation from @FlachyJoe with any of the rotation modes combined with trackball orbit style. I can only reproduce it with the turntable orbit styles but that is a long known problem and a limitation of the turntable orbit style (#9806).

**Comment by maxwxyz** [comment]
what version are you using?
I'm on the following and it is definitely different and "weird"
´´´
OS: Windows 11 build 26100
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git)
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * CfdOF 1.27.12
  * Curves 0.6.50
  * dodo 1.0.1
  * fasteners 0.5.29
  * fasteners.backup1721936159.7542229 0.5.24 (Disabled)
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.25
  * Rocket 3.3.0
  * sheetmetal 0.5.3
  * Silk 0.1.5
  * Silk.backup1727166062.7227929 0.1.5 (Disabled)
```

**Comment by Rexbas** [comment]
```
OS: Fedora Linux 40 (KDE Plasma) (KDE/plasma/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39035 (Git)
Build type: Release
Branch: main
Hash: b935c6a740bfe6bdd2e6bf18fd0bdb9f69e5d696
Python 3.11.0, Qt 5.15.8, Coin 4.0.3, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Fusion
Installed mods: 
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.23
 ```

**Comment by FlachyJoe** [comment]
> that is a long known problem and a limitation of the turntable orbit style (#9806).

Right, I'm sorry for the noise 😖

**Comment by FEA-eng** [comment]
https://forum.freecad.org/viewtopic.php?t=91595#p788585

**Comment by Rexbas** [comment]
Everyone who had problems please try #17466 and let me know if it is better.

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
