### PR TITLE
Draft: Fix several path array issues

### PR DESCRIPTION
**Pull request by Roy-043**
This PR fixes several issues:
* The hiding/unhiding of properties was not always correct.
* "Align Mode" Frenet did not ignore "Force Vertical" and "Vertical Vector".
* A binormal vector would be calculated from two vectors that were effectively parallel.
* The "Extra Translation" property, which should be applied to each element in the array, was applied to the array as a whole.

Remarks:
* The `placements_on_path` functions calculates all placements in a single loop. This ensues that the elements in the array are created in a logical order. This is important as a link array can be expanded. The element at the end of an open path would be the 2nd element in the old code.
* The `calculate_placement` function was changed to make better use of `App.Rotation()`. There is no need to calculate a binormal vector. Note that the main alignment options remain unchanged. But some problematic placements are handled differently. Where the old code would return a placement with a default rotation, the new code will use the available tangent vector. For an example of such a problematic placement see the first element in PathArray001 in the file attached to the 2nd forum topic. For each problematic placement there is still a warning.

Forum topics:
https://forum.freecadweb.org/viewtopic.php?f=23&t=59174
https://forum.freecadweb.org/viewtopic.php?f=23&t=59198
https://forum.freecadweb.org/viewtopic.php?f=23&t=59222

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7506">pipeline status</a> for feature branch [PR_7506](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7506). Pipeline [642980502](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/642980502) was triggered at [9142d4a](https://github.com/FreeCAD/FreeCAD/pull/7506/commits/9142d4ac5eae91a42d46b6a006522f2f417645b4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Roy-043** [comment]
@donovaly This PR significantly changes portions of the code. I'd like to see this thoroughly tested during the V0.21/V1.0 development cycle. So please do not backport.

**Comment by Overruler** [comment]
Looks good but you should apply a change in tangent vector to ExtraTranslation as well, like is done with final_rotation. I have this code that I've been testing:

```
        base_xlate = obj.ExtraTranslation
        final_xlate = base_xlate

        if (obj.Align and obj.AlignMode == "Tangent"
                and hasattr(obj, "TangentVector")):
            Xaxis = App.Vector(1.0, 0.0, 0.0)  # default TangentVector

            if not DraftVecUtils.equals(Xaxis, obj.TangentVector):
                # make rotation from TangentVector to X
                pre_rotation = App.Rotation(obj.TangentVector, Xaxis)
                final_rotation = base_rotation.multiply(pre_rotation)
                # apply rotation to ExtraTranslation
                final_xlate = pre_rotation.multVec(base_xlate)
```

**Comment by Roy-043** [comment]
Thanks for looking at this, and good catch! This makes more sense. Please submit a PR.

Personally I find both the TangentVector and the ExtraTranslation only semi useful. They make sense in a 2D model, but less so in a 3D context. And you can achieve the same effect by nesting the Base object in a Std_Part.

If others want to check the fix: the attached zip contains the revised patharray.py file and a test file (PathArray_ExtraTranslation.FCStd).
[patharray.zip](https://github.com/FreeCAD/FreeCAD/files/9863247/patharray.zip)

Minor detail: the `base_xlate` variable can be avoided:
`final_xlate = obj.ExtraTranslation`
and
`final_xlate = pre_rotation.multVec(final_xlate)`

**Comment by Roy-043** [comment]
It is also possible to solve this by changing the `calculate_placement` function instead. That solution is perhaps preferable?

https://github.com/FreeCAD/FreeCAD/blob/71d0490dab51c10e0cc99ddd6cf31156b5d2dd07/src/Mod/Draft/draftobjects/patharray.py#L491
Becomes:
```
    placement.Base = RefPt + placement.Rotation.multVec(xlate)
```

https://github.com/FreeCAD/FreeCAD/blob/71d0490dab51c10e0cc99ddd6cf31156b5d2dd07/src/Mod/Draft/draftobjects/patharray.py#L552-L554
Becomes:
```
    placement.Rotation = newRot.multiply(globalRotation)
    placement.Base = RefPt + placement.Rotation.multVec(xlate)
```

**Comment by Overruler** [comment]
Changing `calculate_placement` instead does seem cleaner to me, yes.

My motivation to look into Path Link Array came from adding new properties that'd let me control exactly where copies are placed. For example: to place 85, 5, and 10 copies within the half-open, closed, and open intervals `[`0,850mm`)`, `[`850,900mm`]`, `(`900,1000mm`)`, respectively, by using 3 Path Link Arrays on one closed path that's itself the result of an offset operation and whose length could thus be something like 1004.932mm, which isn't a nice round number.

I lack an intuition on what the math to move between local and global coordinate frames should look like, so I just tried things until I got a Box primitive centered and aligned to the path 😃

**Pull request merged**
