### PR TITLE
Mod Surface and Part Add includes

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---
Not sure why but these were blocking my build

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8053">pipeline status</a> for feature branch [PR_8053](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8053). Pipeline [725916348](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/725916348) was triggered at [099b012](https://github.com/FreeCAD/FreeCAD/pull/8053/commits/099b012453b521359ed497236231058038fa64f9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
What is this PR about? Can you please describe what your PRs do or why you make a change?
I can only guess you need it for compilation. But since the CI succeeds, what is your build environment that fails to compile?

**Comment by donovaly** [comment]
Personally, I recently had to recompile from scratch in order to make master compilable. I had to delete the CMake cache. Can you please try this out and also delete files from prior compilation attempts?

**Comment by berniev** [comment]
Pushing the limits a bit: C++20, Qt6, Python 3.10. I'm guessing its QT6 related, but I don't have Qt5 any more. There's been a couple of other issues identified by this test jig.
If the CI succeeds that means these changes arn't breaking existing stuff, right?

**Comment by donovaly** [comment]
> Pushing the limits a bit: C++20, Qt6, Python 3.10. I'm guessing its QT6 related, but I don't have Qt5 any more. There's been a couple of other issues identified by this test jig. If the CI succeeds that means these changes arn't breaking existing stuff, right?

Thanks. So this needs to be discussed in the forum first. There is currently an open Thread in the developer's forum.

Concerning the CI, yes this checks that compilation with our current requirements is working. We have 2 different CIs but I don't know at the moment what are the differences between both.

**Comment by berniev** [comment]
> So this needs to be discussed in the forum first

Have the 'new' PR merge guidelines been abandoned?

**Comment by donovaly** [comment]
> Have the 'new' PR merge guidelines been abandoned?

Can you please write so that I don't have to guess what you mean? Why abandoning guidelines? But more important what has this to do with what I wrote?
You want to push limits for 3rd-party versions and this has to be discussed somehow.

Please improve your information. Take for example this PR, there is no info in the initial PR text what the PR is about or why it was made, what are possible drawbacks etc.? The "Thank you for creating a pull request" text that is a generic note to the PR submitters. It is not helpful that you keep this.
The initial info should contain the relevant info to test and review a PR. (You can change it any time.)
We are all volunteers and don't have the time to request first info or to read through all comments to understand what the PR is about/why it is necessary or the like.

**Comment by berniev** [comment]
Just rebuilt with `BUILD_ENABLE_CXX_STD:STRING=C++17` and without this commit. Failed.

 Looks like the problem is Qt6 related.

Not a `3rd-party version`

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8053">pipeline status</a> for feature branch [PR_8053](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8053). Pipeline [729549311](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/729549311) was triggered at [176fa3e](https://github.com/FreeCAD/FreeCAD/pull/8053/commits/176fa3e34283aba835976d35f26fef0ae6b78433). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> Looks like the problem is Qt6 related

Thanks for testing. I added it in a separate commit 46927fa8 because it should be in the precompiled header.

**Pull request closed without merging**
