### PR TITLE
[Draft] Separate Draft Edit

### PR DESCRIPTION
**Pull request by carlopav**
Hi Yorik,
that's my last attempt to clean commit history and make a new pull request for the draft Edit.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by carlopav** [comment]
Improvements to the tool:
- separated it from draft tools, as yorik suggested: please to check if i did it correctly;
- ghost preview for wire, bezcurve and bspline;
- general refactor to make the code more readable and ready to improve it with a selection observer to allow multi object editing.

**Comment by luzpaz** [comment]
@carlopav thanks for the PR. Quick favor, could you:
1. put the workbench name in square brackets (like wandererfan does for TechDraw commits) when submitting code to a specific workbench to distinguish it in the code history?  
2. If you could split the commit in to commits so it's easier to code review and sift out any bugs that might have crept in to by accident through human error. Then a dev can decide to squash the commit or not.  

**Note:** No.2 depends on @yorikvanhavre decision

**Comment by carlopav** [comment]
@luzpaz, thanks for the hint. I changed the title. For n° 2 I squashed them because of Yorik request. 
I think you are right, maybe Yorik just asked for that because previous PR was a bit of a mess...
Let's wait for him to eventually split it in two different commits.

**Comment by yorikvanhavre** [comment]
This commit is not so big, so it's okay.. But for next times @luzpaz is right, if you are touching two different issues, it's best not to "bundle" them into one PR but make one PR per subject.

One thing bugs me, inside DraftTools you import DraftEdit, and in DraftEdit you import DraftTools... I don't think it's a problem for python, but it seems unclear to me...

Ideally, when we are done, DraftTools should become a ridiculously small stub with just a few basic generic classes and function to be used by others. So I think I'd rather 1) only have DraftEdit to import DraftTools, and 2) In all Draft and Arch code, wherever you see "import DraftTools", I would add "import DraftEdit".

Other idea that I began with DraftLayers: The DraftSomething contains EVERYTHING related to Something: command, objects, functions, everything. Insinde Draft.py, we import all the others. so for the user it's much clearer: "import Draft" will give you everything. Only, "import Draft"should 1) always work in non-GUI, 2) Only import lightweight libraries (no Part, no Qt, no Pivy). That means in each file imported in Draft.py, we should take care of having as few global imports as possible, and import all the heavy stuff inside the different functions and classes.

Also, I think all the FreeCADGui.addCommand() should go in InitGui.py... That would be actually much easier to handle there...

In your case,of course, DraftEdit is just a command, there is nothing else, so it's easier. Maybe just remove the "import DraftEdit" from DraftTools, and we attack the rest afterwards.

**Comment by carlopav** [comment]
Thanks @yorikvanhavre for reviewing!

> inside DraftTools you import DraftEdit, and in DraftEdit you import DraftTools...

it's because DraftTools contains "FreeCADGui.addCommand()", I'll try to move it to InitGui.py, so we can remove the import in DraftTools. If everything works i can take care also of the other tools later.

> 2) In all Draft and Arch code, wherever you see "import DraftTools", if needed, I would add "import DraftEdit"

Ok,  I'll add this to the PR

> That means in each file imported in Draft.py, we should take care of having as few global imports as possible, and import all the heavy stuff inside the different functions and classes.

I didnt get the whole thing, but i think i have to clear a bit all the stuff i'm importing at the beginning of Draft Edit. So for example better to not import Part at the beginning, but just import it in the arc3points edit functions?

> EDIT FYI Also, when we change something in the python files in Draft or Arch (or any other WB), we now also need to make a pull request against the debian packaging recipe, see https://forum.freecadweb.org/viewtopic.php?p=313380

I saw this in the forum before, I'll try to understand what that means and do it, but maybe it's easier if you do that when you think the PR is ready to merge?

**Comment by yorikvanhavre** [comment]
> I didnt get the whole thing, but i think i have to clear a bit all the stuff i'm importing at the beginning of Draft Edit. So for example better to not import Part at the beginning, but just import it in the arc3points edit functions?

Exactly. The reason is that Draft.py (and all others that will be imported from there) happens at FreeCAD startup. And we don't want to import heavy stuff like Part at FreeCAD startup, but rather on first use (late loading). There is no problem in python in repeating "import Part" a large number of times, it will only really be imported the first time.

But this is for later. No need to worry much about this at this point. Just to keep in mind.

> I saw this in the forum before, I'll try to understand what that means and do it, but maybe it's easier if you do that when you think the PR is ready to merge?

Sure, no problem!

**Comment by carlopav** [comment]
Hi Yorik, I think I did it! I'll keep working on the tool and commit new things after it's merged if you think everything is ok.

**Comment by yorikvanhavre** [comment]
Okay that looks perfect! Thanks!

**Comment by yorikvanhavre** [comment]
Ah FYI you just forgot to update the CMake file. Done in f2fd45e6e
I also did the Debian PR: https://salsa.debian.org/science-team/freecad/merge_requests/9

**Comment by carlopav** [comment]
wow, thanks yorik!

**Pull request merged**
