### PR TITLE
Activate Part/Part Design check and refine preferences by default

### PR DESCRIPTION
**Pull request by maxwxyz**
fixes https://github.com/FreeCAD/FreeCAD/issues/13472

Makes these preferences activated by default to check and refine the model:
grafik

@howie-j FYI

### CODE REVIEW

**Comment by Syres916** [comment]
The changes to prefEntry and prefPath in the UI file should be backed out, if you want to make a checkbox checked then you should add:
```
       <property name="checked">
          <bool>true</bool>
         </property>
```

**Comment by maxwxyz** [comment]
@Syres916 thanks! I've edited it, could you check again? The first time I'm opening the settings are unchecked. Is there a workaround or is it just with the manual builds?

**Comment by Syres916** [comment]
The easy way I check whether a UI file is correct is by opening it with Qt Designer and it looks fine to me. You are loading FreeCAD with none existent config files (I don't know whether these Booleans are held in Pref Packs?

**Comment by Syres916** [comment]
Also you'll have to speak nicely to @FEA-eng and @oliveroxtoby as this appears to break at least one of their tests in FEM (test_box_static) and CfdOF (test_run - TestCfdOF.DamBreak3DTest) workbenches due to the edge numbers changing I would guess.

**Comment by maxwxyz** [comment]
thanks for noticing.
@FEA-eng / @oliveroxtoby / @marioalexis84 is this change OK for those tests or other implementations and could these tests be changed?

**Comment by oliveroxtoby** [comment]
All good with me. Happy to fix up my one. Thank you! @Syres916 @maxwxyz

**Comment by FEA-eng** [comment]
> test_box_static

https://github.com/FreeCAD/FreeCAD/blob/958d83ed06ca32294227b4e1270cf41c838962e5/src/Mod/Fem/femexamples/boxanalysis_static.py

This example is literally just a Box (Part Box primitive). Strange that `refine` makes a difference here. But maybe adding a line setting refine to true for this part will be sufficient. I would be more worried about some FEM Examples with less basic geometry. Some time ago I fixed a similar issue where Make Face not set to true by default made several Elmer 2D examples fail: #12646 and #12777.

**Comment by maxwxyz** [comment]
@oliveroxtoby @FEA-eng great. Do I need to fix/change the tests in my PR (if so, how?) or do you change them?

**Comment by oliveroxtoby** [comment]
> @oliveroxtoby @FEA-eng great. Do I need to fix/change the tests in my PR (if so, how?) or do you change them?

Not for CfdOF, as it's an external module.

**Comment by FEA-eng** [comment]
There seems to be some interference with TNP stuff (at least according to the failing checks). Maybe that's also what causes the failure of that FEM test. Anyway, the failing checks here should be resolved first and then we'll see.

**Comment by marioalexis84** [comment]
@maxwxyz could you rebase the branch to test it?

**Comment by marioalexis84** [comment]
@maxwxyz I'm not getting any errors in the fem unit test even with three boxes checked.

**Comment by maxwxyz** [comment]
@bgbsww I get two test failures in CI:
```
======================================================================
FAIL: testRemovedExternalGeometryReference (SketcherTests.TestSketcherSolver.TestSketcherSolver.testRemovedExternalGeometryReference)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/Sketcher/SketcherTests/TestSketcherSolver.py", line 522, in testRemovedExternalGeometryReference
    self.assertEqual(len(hole.Shape.Edges), 13)
AssertionError: 12 != 13

======================================================================
FAIL: testPartDesignTNPFillet (PartDesignTests.TestTopologicalNamingProblem.TestTopologicalNamingProblem.testPartDesignTNPFillet)
Test Fillet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py", line 1431, in testPartDesignTNPFillet
    self.assertEqual(body.Shape.childShapes()[0].ElementMapSize, 62)
AssertionError: 64 != 62
```

**Comment by bgbsww** [comment]
Interesting.  It isn't unreasonable to change ElementMapSize tests, because sometimes the fix is changing how a shape is created and that affects the element map.  So the fillet test might just need adjusting.

The removed external geometry issue, however might be pointing at an introduced bug.  Looking ...

**Comment by maxwxyz** [comment]
No worries, just let me know if these tests should be fixed within this PR or in a separate (and how I could fix them).

**Comment by chennes** [comment]
Will merge after the CI failure is resolved.

**Comment by bgbsww** [comment]
@maxwxyz you should fix them in this PR, by changing the expected assertions in the tests to match above: the 13 to a 12 and the 62 to a 64.   Of course we want to understand changes to tests before making them, but in this specific case they are explained by the refine being on.

**Comment by maxwxyz** [comment]
@bgbsww thanks, updated. let's see...

**Comment by chennes** [comment]
Dropping this to Draft while you keep working.

**Comment by maxwxyz** [comment]
@bgbsww changing the tests to the values did not change the CI tests here. What else do I need to do to fix this?

**Comment by bgbsww** [comment]
Based on looking at a couple of the fails ( going down the details), it looks like that 64 should have stayed a 62.  Since the difference between those is a refine, I wonder if something is a little different between your local test environment and the CI builds.  In any case, step one is to take that change back out, and then if the CI still fails, look to see what the problem is.

**Comment by maxwxyz** [comment]
@chennes all tests should've been fixed now.

**Comment by wwmayer** [comment]
This PR reveals the weakness of several unit tests. On many users' systems the refine settings are still switched off and this makes some tests to fail now.

Correctly working unit tests must be independent of user settings as otherwise they are useless.

**Pull request merged**
