### PR TITLE
PathGui: ViewProviderPath visual enhancement

### PR DESCRIPTION
**Pull request by realthunder**
- Enabled preselect
- Shows GCode command and movement direction when preselected
- Support single/multi-stepping using property 'StartIndex' and 'ShowCount'

### CODE REVIEW

**Comment by wwmayer** [comment]
Broken unit tests:
======================================================================

FAIL: test00 (PathTests.TestPathCore.TestPathCore)

Test Path command core functionality

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/FreeCAD.app/Contents/Mod/Path/PathTests/TestPathCore.py", line 50, in test00

    self.assertEqual(c.toGCode(), 'G1 X1.000000 Y0.500000')

AssertionError: 'G1 X1.00000 Y0.50000' != 'G1 X1.000000 Y0.500000'

======================================================================

FAIL: test10 (PathTests.TestPathCore.TestPathCore)

Test Path Object core functionality

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/FreeCAD.app/Contents/Mod/Path/PathTests/TestPathCore.py", line 99, in test10

    self.assertEqual(p.toGCode(), 'G1 X1.000000 Y0.000000\nG1 X0.000000 Y2.000000\nG1 X1.000000 Y0.000000\n')

AssertionError: 'G1 X1.00000 Y0.00000\nG1 X0.00000 Y2.00000\nG1 X1.00000 Y0.00000\n' != 'G1 X1.000000 Y0.000000\nG1 X0.000000 Y2.000000\nG1 X1.000000 Y0.000000\n'

----------------------------------------------------------------------

Ran 140 tests in 19.037s

**Comment by realthunder** [comment]
Yeah, I saw that. See the discussion in the forum https://forum.freecadweb.org/viewtopic.php?f=15&t=21392

They may need to fix the unit test first before merging this. Or maybe I'll take a look when I got time.

**Comment by realthunder** [comment]
That's not caused by me, right? Maybe it's clang's bug.

clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
make[2]: *** [Mod/Points/PointsGui.so] Error 254
make[1]: *** [src/Mod/Points/Gui/CMakeFiles/PointsGui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by wwmayer** [comment]
> That's not caused by me, right? Maybe it's clang's bug.

Right! The points module doesn't depend on any other module, so your changes can't have an impact on it. No idea what exactly happened but since clang for Linux and macOS with Qt4  (and usually withQt5 too) works I guess it's a one-time failure.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
