### PR TITLE
Fluid material bugfix and improvement (part 1)

### PR DESCRIPTION
**Pull request by qingfengxia**
see the thread here
https://forum.freecadweb.org/posting.php?mode=edit&f=18&p=363083

I plan to split the bugfix into 2PR, without part1 fix, other developer can not reproduce the second bug. 

- [ x] Branch rebased on latest master `git pull --rebase upstream master`
- [ x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by qingfengxia** [comment]
commit 4 and 5 introduce failure in Unit Test

==============================================================

FAIL: test_known_quantity_units (femtest.app.test_material.TestMaterialUnits)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/Mod/Fem/femtest/app/test_material.py", line 73, in test_known_quantity_units

    .format(param)

AssertionError: False is not true : Unit of quantity material parameter VolumetricThermalExpansionCoefficient is not known by FreeCAD unit system.

----------------------------------------------------------------------
I will try to fix it, if not possible, I will remove the last 2 commits.

**Comment by yorikvanhavre** [comment]
No problem, tell me when it's fixed and we merge

**Comment by qingfengxia** [comment]
2 tests passed, once all tests passed, please check and merge it.  part 2 fix could takes some time to come.

**Comment by berndhahnebach** [comment]
merged

**Pull request closed without merging**
