### PR TITLE
[Sketcher] Attempt to fix #14736

### LINKED ISSUE #14736: [Problem] Sketcher: no way to "escape from" autosnapping a circle with autoconstrain on
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In Sketcher, after "Create external geometry" of a circle of a previous Pad, if "Auto constrains" is active, you can create a coincident circle with the external geometry but all following circles will snap too to the same circle, no matter how far you draw them. 

If after the first circle you draw a second circle with another centre, the first circle ends being totally defined and you can draw multiple circles with the same origin as the first one without problem.

See screencast and attached file.

Looks like it doesn't happen with FreeCAD revision 35966

Maybe related to #13228
I have searched in Github FreeCAD with [is:issue is:open label:"WB Sketcher" snap ] with no more relevant results.

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37730 (Git) AppImage
Build type: Release
Branch: main
Hash: 30f7f2688921e6e5242beaa9d71e0fdd844b20e3
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Installed mods: 
  * Movie 2024.2.15
  * FreeCAD-motion-workbench-master
  * dodo 1.0.1
  * PieMenu 1.2.7
  * BillOfMaterials 0.0.8.5
  * fasteners 0.5.22
```

### Subproject(s) affected?

Sketcher

### Anything else?

https://github.com/FreeCAD/FreeCAD/assets/18265355/2c1afaa7-a326-4cd8-820f-c5248d8b1d8f

[Snap.FCStd.zip](https://github.com/user-attachments/files/15866023/Snap.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Not yet completely successful.

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
So now the failure should look different, but the new circles are still that size.

**Comment by FEA-eng** [comment]
It seems that the second circle still results in an overconstraint.

**Comment by AjinkyaDahale** [comment]
> It seems that the second circle still results in an overconstraint.

That is known. Indeed, that issue is not yet fixed, and may be because of the way coincident points (also any other equal parameters as defined in GCS) are internally treated as same.

This PR only fixes the fact that the circle was not even drawn. What was assumed in the related issue to be a "snapping to the external geometry" was in fact the lack of that drawing.

**Comment by chennes** [comment]
@AjinkyaDahale do you know why we receive the message "Redundant constraint is not an autoconstraint. No autoconstraints or additional constraints were added. Please report!" when this bad constraint is deleted? I thought that it _was_ an autoconstraint.

**Review by chennes — APPROVED** [review]
This PR fixes the reported issue -- even though it still leaves a bit to be desired in terms of user experience, it is a clear improvement over the current state of `main`, and IMO also improves upon 0.22.x by actively removing the offending tangency constraint rather than just throwing an error.

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale do you know why we receive the message "Redundant constraint is not an autoconstraint. No autoconstraints or additional constraints were added. Please report!" when this bad constraint is deleted? I thought that it _was_ an autoconstraint.

Could you tell the steps to reproduce? There may be some confusion in interpretation here. It is especially not possible to have this happen when something is deleted.

Autoconstraint only matters _while the curve is created_. Once the operation is finished, all constraints are treated the same. What the error says is: "While the auto constraints were being added, some redundancy was detected, and the redundant constraint was judged to be a pre-existing one. So we are canceling."

**Comment by AjinkyaDahale** [comment]
Changed the circle-to-circle tangency in `planegcs`, so that there's less likelihood of constraints being detected as redundant. The tangent constraint is still strangely detected as redundant when adding as an auto-constraint and thus not added.

**Comment by obelisk79** [comment]
I would at least consider changing the tangency autoconstraint to equality. Rather than a feature it is a correction to an unintended error state that seems like it would be a common-enough use-case. Either way I appreciate the correction.

**Comment by AjinkyaDahale** [comment]
> I would at least consider changing the tangency autoconstraint to equality. Rather than a feature it is a correction to an unintended error state that seems like it would be a common-enough use-case. Either way I appreciate the correction.

Added in #16062.

**Pull request merged**
