### PR TITLE
Block constraint

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
New constraint as discussed here:
https://forum.freecadweb.org/viewtopic.php?f=10&t=25976&start=40#p206469

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
I cannot understand why the clang worker fails.

**Comment by bblacey** [comment]
@abdullahtahiriyo, the Homebrew ports have been upgraded to OCCT 7.2 but the Homebrew nglib port is incompatible with it.  The macOS job failed to download the ports-cache (this happens sometimes) that contains OCCT 7.1 so it tried to re-install all the dependencies which included OCCT 7.2.  I have restarted your PR job to see if it will build with the cached ports...  The macOS maintainers (@ianrrees, @peterlama and I) are all busy but will hopefully be able to address the netgen/nglib issue before our ports-cache becomes so stale that we need to rebuild it with OCCT 7.2.

**Comment by abdullahtahiriyo** [comment]
@bblacey 

Hi! thanks for the insight. I was going thru the history of the worker and could not find a specific cause. It is good to know it is not me ;)

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
