### PR TITLE
Path:  (WIP) Add some refactored postprocessors along with some tests.

### PR DESCRIPTION
**Pull request by LarryWoestman**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [X]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [561553414](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/561553414) was triggered at [cf70ebf](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/cf70ebf10fa6e2a74cc2cf36874c4c7c0497854f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [561560531](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/561560531) was triggered at [0a349ee](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/0a349eee23853acb67125cb460d6f6a5d4248758). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [561871280](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/561871280) was triggered at [43efc24](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/43efc24f0e825143c59209c5c2fd394aa1b9f5a2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [561878241](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/561878241) was triggered at [3aa0dcc](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/3aa0dccf83a84b0c28ca5471f8307db9b5e6d2b3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [563630665](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/563630665) was triggered at [01de3a2](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/01de3a2ba4c05b22432d2373895f40c922dcac66). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [563883873](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/563883873) was triggered at [d0e5b8a](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/d0e5b8a43f0caef5a4db725d814a8c87e019efa2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [564975003](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/564975003) was triggered at [2207ad9](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/2207ad9483b5de852b1a6ddff8cb1ee1b4718dfe). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [565344468](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/565344468) was triggered at [05a53f5](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/05a53f599100f0c33d72f75b01db2d53309cb478). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [567202303](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567202303) was triggered at [e30344f](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/e30344f417d4e4de27e3f097b61a7e35c3f5beb3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [567231987](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567231987) was triggered at [4a1e108](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/4a1e108ddb3c1af792b035772389d3ae16edbdb1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [567238214](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567238214) was triggered at [4a7cb07](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/4a7cb0786fa7d287f8dc9c4092b8345c1d687d55). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [567245532](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567245532) was triggered at [71c7f29](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/71c7f2997cb48be18cc6bcf39057658aab5771a4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [567501589](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567501589) was triggered at [3d8d2e3](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/3d8d2e32992164e0fa2b2863e7a8400bb4f85f63). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [578985554](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/578985554) was triggered at [e4122cb](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/e4122cb4737b9e7b4ddd585e02196efdeb136dd9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [584370705](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/584370705) was triggered at [ebca4ab](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/ebca4aba6ada0c15a6b109e73b8f3ea5f55919ff). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007">pipeline status</a> for feature branch [PR_7007](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7007). Pipeline [585356115](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/585356115) was triggered at [e7a8fd1](https://github.com/FreeCAD/FreeCAD/pull/7007/commits/e7a8fd18e083c7dd6b467217b44a9057f91edb7d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Some of the files that have been formatted aren't clear about what has been changed in the diff since every single line has been altered :cry:

**Comment by LarryWoestman** [comment]
Hopefully, the only thing that should have been changed was the formatting 
from black and a few "long-lined" comments that were too long to fit in 88 
characters, compared to the previous version of the file.

I have just finished re-building and re-testing the post-processor-related
tests so I am reasonably sure that I didn't break anything any more than 
it already was :-).  Unfortunately, I wasn't able to complete a
"./FreeCAD -t 0" test because of some base-related test that doesn't 
appear to have anything to do with my code.

Larry Woestman

**Comment by LarryWoestman** [comment]
In general for the whole PR, I am adding a bunch of new files for "refactored" postprocessors while changing very little of the code that was already there before.  I did refactor the PathPost.py file to pull out some functionality into a separate function.
Unless someone chooses to use the new "refactored*" postprocessors, they shouldn't be affected by this code (except for the above-mentioned PathPost.py file change).  I also added some additional postprocessor tests for both the old centroid, grbl. linuxcnc and mach3/4 postprocessors as well as their new refactored equivalents.

**Pull request merged**
