### PR TITLE
Qt6 build fixes

### PR DESCRIPTION
**Pull request by oursland**
Adjust a couple includes to permit building with Qt5 and Qt6.

### CODE REVIEW

**Comment by kadet1090** [comment]
This is the same as #14275 and #14273 but has better commit history - I'd go with this one.

**Comment by obelisk79** [comment]
Should I close my pr's then?

**Comment by kadet1090** [comment]
imho both can be open - let the maintainers decide which one should be merged as they differ a bit in solution

**Comment by oursland** [comment]
I'm entirely indifferent.  These were changes necessary to get the draft PR https://github.com/FreeCAD/FreeCAD/pull/14218. for Qt6 CI to build.  That PR still has a long way to go before it will be ready.

It looks like one of the PRs has been merged, so I'll close this one.

**Pull request closed without merging**
