### PR TITLE
Move Material workbench preferences from FEM workbench to its own preferences page

### PR DESCRIPTION
**Pull request by davesrocketshop**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9210">pipeline status</a> for feature branch [PR_9210](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9210). Pipeline [830835044](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/830835044) was triggered at [ed6a6b9](https://github.com/FreeCAD/FreeCAD/pull/9210/commits/ed6a6b989957e936c43cd30aaffaa971fe48b20d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
Is there an issue or forum topic where this was discussed?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9210">pipeline status</a> for feature branch [PR_9210](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9210). Pipeline [832018964](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/832018964) was triggered at [13ab05e](https://github.com/FreeCAD/FreeCAD/pull/9210/commits/13ab05e225ea750c5943ebcecd0ba43b7f77f246). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9210">pipeline status</a> for feature branch [PR_9210](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9210). Pipeline [836934205](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/836934205) was triggered at [d87beb9](https://github.com/FreeCAD/FreeCAD/pull/9210/commits/d87beb9b7b9b9eaae504c8fce4315fccf29e99b5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by davesrocketshop** [comment]
Included bug fixes, usability enhancements (mostly bug fixes), and use of new preferences that allow external workbenches to add to the material search paths.

This is all outlined in the discussion thread: https://forum.freecad.org/viewtopic.php?t=16714

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9210">pipeline status</a> for feature branch [PR_9210](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9210). Pipeline [903667657](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903667657) was triggered at [b282edd](https://github.com/FreeCAD/FreeCAD/pull/9210/commits/b282eddd0314992b1cb97ca5b6ca54f8188e4c1d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by davesrocketshop** [comment]
This pull request is now obsolete. It was intended as part of release 0.21, and quite frankly should have been in there.

This will now be addressed as part of the material overhaul

**Pull request closed without merging**
