### PR TITLE
fixed xlsx alias encoding issue

### PR DESCRIPTION
**Pull request by sirtoobii**
Since `getText()` already returns a string, the `encode()` function (called on this string) results in a byte object which is not compatible with `setAlias()`.

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This is a python2 thing. We can slowly think about stopping maintaining python2 compatibility, but while it is still the default on many mainstream linux distros, I would prefer to keep it for the time being... Would you mind adding something like: `if sys.version_info.major < 3:` and keep the original way in this case?

**Comment by sirtoobii** [comment]
Hi Thank you for you comment. That is a good point to make it compatible with python 2.x

**Comment by abdullahtahiriyo** [comment]
Note: CI passed. To check it click on "Details" next to "Required" in CI/Travis.

**Comment by sirtoobii** [comment]
@abdullahtahiriyo Do I have to take action somehow?

**Comment by abdullahtahiriyo** [comment]
No. Not at all. I was not reviewing the PR (having me review Python is as sound as having me landing a Boeing 737).

It is just a note for whoever who reviews this one, that even though the CI integration says "Some checks haven't completed yet", they are indeed completed and passed. It is just that Github did not update the status.

Sorry if my previous message was misleading.

**Pull request merged**
