### PR TITLE
[0.20]FEM: Adding buckling analysis for solver CCX

### PR DESCRIPTION
**Pull request by twangrt**
**Implementation of buckling analysis between the solver Calculix and FreeCAD**

- Adding a new analysis type called "buckling" to solver.py and writer.py.
- Adding buckling for writing different constraints(should be the same as analysis type "static") in writer.py.
- Adding a new FEM property "BucklingFactors" for number of buckling modes to calculate.
- Adding option and signals for buckling analysis to the UI

**Forum thread:**
https://forum.freecadweb.org/viewtopic.php?f=18&t=20217&start=60

### CODE REVIEW

**Comment by berndhahnebach** [comment]
cool stuff, I will jave a deeper look.

**Comment by hyarion** [comment]
@twangrt Could you add a "[0.20]" tag to the title? (FreeCAD is in feature freeze for the upcoming 0.19 release)

**Comment by berndhahnebach** [comment]
@twangrt 

Have you seen this post on the forum ?

**Comment by twangrt** [comment]
@berndhahnebach 

Now I have, thanks for notifying me! 👍

**Comment by berndhahnebach** [comment]
how about making it save by adding a unit test for this example. It is easy. See for example 0a43abcf0f7a

**Comment by twangrt** [comment]
@berndhahnebach Ill have a look on the units test. Ive been double checking my example and run in to some troubles that I want to correct. Also see my latest post https://forum.freecadweb.org/viewtopic.php?f=18&t=20217&p=482988#p482988

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=18&t=20217&start=80#p488280

**Comment by luzpaz** [comment]
```
ERROR: test_ccx_buckling_flexuralbuckling (femtest.app.test_solver_calculix.TestSolverCalculix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Fem/femtest/app/test_solver_calculix.py", line 93, in test_ccx_buckling_flexuralbuckling
    from femexamples.ccx_buckling_flexuralbuckling import setup
ModuleNotFoundError: No module named 'femexamples.ccx_buckling_flexuralbuckling'
```  

source: https://travis-ci.org/github/FreeCAD/FreeCAD/jobs/767690749#L15173-L15179

**Comment by twangrt** [comment]
Okey, now Im truly lost why the latest build is failing on Windows after the merge with FreeCAD/master. The linux build looks ok. 

`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
`
https://travis-ci.org/github/FreeCAD/FreeCAD/jobs/768240446#L5009-L5012

**Comment by luzpaz** [comment]
I was wondering if it was the latest commit in FEM that I made that removed pythong2 code but it looks like we're good since python3 is used https://travis-ci.org/github/FreeCAD/FreeCAD/jobs/768240446#L285 (I would've been surprised if we were still using py2, but checked nevertheless)

Off topic: but why does the windows build have this: 
`$ export DEPLOY_RELEASE=0.18_pre`  
https://travis-ci.org/github/FreeCAD/FreeCAD/jobs/768240446#L27

**Comment by luzpaz** [comment]
> Off topic: but why does the windows build have this:
> `$ export DEPLOY_RELEASE=0.18_pre`  

Updated travisci configs to 0.20_pre

**Comment by twangrt** [comment]
@berndhahnebach Have you seen this? https://forum.freecadweb.org/viewtopic.php?f=18&t=20217&start=90

**Comment by berndhahnebach** [comment]
merged,

https://github.com/FreeCAD/FreeCAD/compare/09f441c93e13...1bea75d62b0

I have problems getting the ltb example to work ... thus I did not include it for the merge ...

**Comment by berndhahnebach** [comment]
thus I leave the PR open

**Comment by berndhahnebach** [comment]
Does the ltb unit test work for you?

I get a 

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hugo/Documents/dev/freecad/freecadbhb_dev/build/Mod/Fem/femsolver/task.py", line 118, in protector
    self.run()
  File "/home/hugo/Documents/dev/freecad/freecadbhb_dev/build/Mod/Fem/femsolver/calculix/tasks.py", line 67, in run
    membertools.AnalysisMember(self.analysis),
  File "/home/hugo/Documents/dev/freecad/freecadbhb_dev/build/Mod/Fem/femtools/membertools.py", line 284, in __init__
    "Fem::ConstraintForce"
  File "/home/hugo/Documents/dev/freecad/freecadbhb_dev/build/Mod/Fem/femtools/membertools.py", line 315, in get_several_member
    return get_several_member(self.analysis, t)
  File "/home/hugo/Documents/dev/freecad/freecadbhb_dev/build/Mod/Fem/femtools/membertools.py", line 126, in get_several_member
    obj_dict["RefShapeType"] = femutils.get_refshape_type(m)
  File "/home/hugo/Documents/dev/freecad/freecadbhb_dev/build/Mod/Fem/femtools/femutils.py", line 364, in get_refshape_type
    first_ref_shape = get_element(first_ref_obj[0], first_ref_obj[1][0])
  File "/home/hugo/Documents/dev/freecad/freecadbhb_dev/build/Mod/Fem/femtools/geomtools.py", line 189, in get_element
    return part.Shape.getElement(element)  # Face, Edge, Vertex
Part.OCCError: Index out of bound

ERROR
```

but I did not yet investigated

**Comment by berndhahnebach** [comment]
the extracted ltb commit can be found here https://github.com/berndhahnebach/FreeCAD_bhb/commits/fembuckling

**Comment by berndhahnebach** [comment]
there are changes not related to centrif at all. I extracted them from the PR. some of them I would like to merge, some needs some explanation. See forum topic https://forum.freecadweb.org/viewtopic.php?f=18&t=59281&p=508956#p508956

cheers bernd

**Comment by twangrt** [comment]
> there are changes not related to centrif at all. I extracted them from the PR. some of them I would like to merge, some needs some explanation. See forum topic https://forum.freecadweb.org/viewtopic.php?f=18&t=59281&p=508956#p508956
> 
> cheers bernd
@berndhahnebach Wrong PR?

**Comment by berndhahnebach** [comment]
> > there are changes not related to centrif at all. I extracted them from the PR. some of them I would like to merge, some needs some explanation. See forum topic https://forum.freecadweb.org/viewtopic.php?f=18&t=59281&p=508956#p508956
> > cheers bernd
> 
> @berndhahnebach Wrong PR?

damn yes ...

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=18&t=20217&start=110#p510526

my version with shell elements is much smaller and gives good results too. Furthermore the verification example uses shell elements too. We should go for them. 

I will close the PR for now ...

**Comment by twangrt** [comment]
Shell elements is probably the best course for the ltb example. Nice work!

**Pull request closed without merging**
