### PR TITLE
Base: Class - Type checking template functions

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
Original idea of Werner:
https://github.com/FreeCAD/FreeCAD/pull/10643#issuecomment-1712966545

I really liked this syntax to avoid repetition and even explicit consideration of Types when type checking.

I thought it would be a pity to get it lost.

It includes a small demonstrator of usage.

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
@wwmayer 

I could not resist to have this added.

I have just added an overloading counterpart for isDerivedFrom to take class objects for consistency with the new is() function.

**Comment by FlachyJoe** [comment]
It's very smart as it can be used everywhere in the code.
We could run
```bash
find ./src -type f -name "*.cpp" -exec sed -i 's/getTypeId() == \([A-Za-z0-9_]*\(::[A-Za-z0-9_]*\)*\)::getClassTypeId()/is<\1>()/g' {} +
find ./src -type f -name "*.cpp" -exec sed -i 's/->isDerivedFrom(\([A-Za-z0-9_]*\(::[A-Za-z0-9_]*\)*\)::getClassTypeId()/->isDerivedFrom<\1>()/g' {} +
```

**Comment by abdullahtahiriyo** [comment]
@FlachyJoe 

Sure. 

If Werner agrees to the PR, then we can go WB by WB generating PRs to refactor/modernise the code. 

You may well be my guess and do those PRs...

**Review by wwmayer — APPROVED** [review]
Nice idea :)

**Pull request merged**
