### PR TITLE
Femdev

### PR DESCRIPTION
**Pull request by berndhahnebach**
see http://forum.freecadweb.org/viewtopic.php?f=18&t=17564

### CODE REVIEW

**Comment by berndhahnebach** [comment]
I do not have a glue why osx on travis failed. Added another two commits. Hopefully it will succeed now. Bernd

**Comment by berndhahnebach** [comment]
https://travis-ci.org/FreeCAD/FreeCAD/jobs/162702020

From my point of view the failure on OSX is not related to the changes in the Pull Request.

**Comment by bblacey** [comment]
@berndhahnebach, you are correct.   The macOS builds are suffering from Travis infrastructure changes that have introduced some instabilities in our builds...  I started a [Forum Thread](http://forum.freecadweb.org/viewtopic.php?f=10&t=17557&sid=784a65e91731f878b38f479c37e5b85b) where you can monitor the status if you are interested.  Unfortunately, it seems that it may be a while before we wring out all the kinks so to speak.

**Comment by yorikvanhavre** [comment]
merged!

**Pull request closed without merging**
