### PR TITLE
Revert "AddonManager: update icons for legibility on dark themes and update icons for WBs"

### PR DESCRIPTION
**Pull request by chennes**
Reverts FreeCAD/FreeCAD#13564 -- something about the new icons seems to be corrupting the resource file on some platforms. This PR is a check to see if this really is the culprit, or if it's a red herring and something else has changed.

### CODE REVIEW

**Comment by chennes** [comment]
@maxwxyz I don't really have a good explanation for this, but reverting your PR does resolve the issue with the Addon Manager. So I think we should do so, and then have you resubmit as two different PRs, one for the UI icons and one for the WBs.

**Comment by maxwxyz** [comment]
Yes just do it if it solves the issue. Although it was just changing SVG files, no code.

**Review by maxwxyz — APPROVED** [review]

**Comment by maxwxyz** [comment]
So I will create a PR for the UI icons first and then for the WB icons?

**Comment by chennes** [comment]
Sounds good, thanks.

**Pull request merged**
