### PR TITLE
Travis - determine cause of caching issues for GCC

### PR DESCRIPTION
**Pull request by triplus**
I disabled all other build jobs and lets see on how GCC caching will behave after a couple of builds. Hence once this PR builds successfully it makes sense to merge it.

https://forum.freecadweb.org/viewtopic.php?f=10&t=42615

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Seems to have worked! Should we merge then? It makes little sense to keep the builds running if they fail anyway...

**Comment by triplus** [comment]
Hi,

The plan changed and i am using this PR to determine on why GCC builds don't make use of ccache. ATM merging therefore shouldn't happen. Will further comment when it will start make sense, to merge this PR.

**Comment by yorikvanhavre** [comment]
Ok! I'll add an "on hold" flag so this doesn't get merged by accident

**Comment by triplus** [comment]
This PR is now ready to be merged.

**Comment by sgrogan** [comment]
I vote to merge. It fixes the Linux caching issues, reducing build time is reduced by about 90%

**Comment by wwmayer** [comment]
#3025 is merged now. Can you rebase and fix the conflicts of this PR, please?

**Comment by triplus** [comment]
I tested the conflict resolution solution provided on GitHub and i am not sure if i like the result. Hence i will close this PR and i added the changes here:

https://github.com/FreeCAD/FreeCAD/pull/3046

**Pull request closed without merging**
