### PR TITLE
App/Gui: fix property link editor

### LINKED ISSUE #6672: [Bug] [crash] PartDesign SubShapeBinder: crash and other issues when manually editing Support
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=67401&start=10#p582669

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 8.1 (6.3)
Word size of FreeCAD: 64-bit
Version: 0.20.28193 (Git)
Build type: Release
Python 3.8.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: C/Default (C)
Installed mods: 
```

### Subproject(s) affected?

PartDesign

### Issue description

There are some issues when you manually edit the Support property of a SubShapeBinder.

To make the Support property editable:

1. Right-click in the Property editor.
2. Select "Show All".
3. Right-click the Support property.
4. De-select "ReadOnly".
5. Click in another field.
6. Click in the Support field.
7. Press the "..." button.
8. The Link dialog opens.

A.

1. Open the attached file.
2. Make the Support property editable as already explained.
3. Click the "..." button in the Support field.
4. In the Link dialog press the "Clear" button.
5. Select the highest Cylinder entry in the dialog list (not under Part).
6. Press "OK".
7. Result: FC crashes.

B.

1. Open the attached file.
2. Drag and drop the Cube onto the SubShapeBinder.
3. Make the Support property editable.
4. Click the "..." button in the Support field.
5. In the Link dialog do nothing just press the "OK" button.
6. Recompute.
7. Result: The Support field now only contains a reference to the face of the cylinder, but in the 3D view the Cube is still shown as part of the SubShapeBinder.

C.

1. Open the attached file.
2. Delete the existing SubShapeBinder.
3. Make the Part visible.
4. Select the top face of the Cylinder.
5. Click the [PartDesign_SubShapeBinder](https://wiki.freecadweb.org/PartDesign_SubShapeBinder) button.
6. Result: Support is "Part.Cylinder.Face3".
7. Again delete the SubShapeBinder.
8. Make sure nothing is selected.
9. Click the [PartDesign_SubShapeBinder](https://wiki.freecadweb.org/PartDesign_SubShapeBinder) button again.
10. Make the Support property editable.
11. Click the "..." button in the Source field.
12. In the 3D view select the top face of the Cylinder.
13. Result: Support is "Cylinder.Face3". Without the nesting in the Part. Note that when selecting the face the statusbar does show the nesting in Part.

[test-ssb.zip](https://github.com/FreeCAD/FreeCAD/files/8361305/test-ssb.zip)

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by realthunder**
Fixes #6672

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6710">pipeline status</a> for feature branch [PR_6710](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6710). Pipeline [507864822](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/507864822) was triggered at [d6260c7](https://github.com/FreeCAD/FreeCAD/pull/6710/commits/d6260c7f124daaf1fb69dd3a915c964d15c22605). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
I have not yet tested the PR and thus don't know in how far it avoids the crash but it doesn't look like it addresses the actual reason of the crash.

According to the debugger output the crash happens in DynamicProperty::removeDynamicProperty() at line 247 `index.erase(it);`
For testing purposes I created a PD box and a Part cylinder where for one face of the box a sub-shape binder was created.

When following the instructions of procedure A the sub-shape binder is set to a face of the cylinder and clicking OK triggers SubShapeBinder::onChanged(). After several function calls it invokes DynamicProperty::removeDynamicProperty() where name is "Cache_Box". The property to be removed is a App::PropertyMatrix.

In line 245 the call of `GetApplication().signalRemoveDynamicProperty(*prop);` again triggers SubShapeBinder::onChanged() that again invokes DynamicProperty::removeDynamicProperty() with the same value of name, i.e. "Cache_Box".

So, this is a recursive call of DynamicProperty::removeDynamicProperty() and the removal of the iterator in the second call invalidates the iterator object of the first call and thus the repeated call of `index.erase(it);` leads to the crash.

Changing the corresponding part in DynamicProperty::removeDynamicProperty() fixes the crash:
```
        // Handle possible recursive calls of removeDynamicProperty
        if (prop->myName) {
            Property::destroy(prop);
            index.erase(it);
            // memory of myName has been freed
            prop->myName = nullptr;
        }
```

In case it can happen that there is a recursive call of DynamicProperty::removeDynamicProperty() for different properties then a few more things must be done:
* save the argument name to a local std::string because the address of name might be equal to prop->myName and use the std::string for the search
* before erasing the iterator perform a new search in index

**Comment by donovaly** [comment]
@realthunder will you do the crash fix in DynamicProperty::removeDynamicProperty() like @wwmayer in a new PR or will you change this PR?

(I would like to merge this PR soon to get closer to FC 0.20.)

**Comment by realthunder** [comment]
As mentioned in my [comment](https://github.com/FreeCAD/FreeCAD/issues/6672#issuecomment-1086871305) in the issue, this PR is for fixing case B and C, because I can't reproduce crash in case A. I'll recheck soon on another platform.

**Comment by wwmayer** [comment]
> As mentioned in my https://github.com/FreeCAD/FreeCAD/issues/6672#issuecomment-1086871305 in the issue, this PR is for fixing case B and C, because I can't reproduce crash in case A. I'll recheck soon on another platform.

OK, then I can implement my suggestion and merge this PR for procedure B+C.

**Pull request merged**
