### PR TITLE
[App] Add prefs for import/export in Recent Files

### PR DESCRIPTION
**Pull request by chennes**
Add two (currently hidden) preferences controlling whether imported and exported files are included in the recent files list.

`RecentIncludesImported` defaults to true, and `RecentIncludesExported` defaults to false.

Forums discussion here: https://forum.freecadweb.org/viewtopic.php?f=3&t=47642

Probably resolves issue #4375: https://tracker.freecadweb.org/view.php?id=4375

### CODE REVIEW

**Review by davidosterberg — COMMENTED** [review]
The code looks straight forward. I have compiled the code and it compiles cleanly and works as expected. (Edit: I had a typo in my property names before)

**Review by davidosterberg — CHANGES_REQUESTED** [review]
Why not include the parameters in the parameter list, so that the user can more easily modify it to his/her liking. Right now the parameter is not in there and the user have to create it himself

conf_no_params

**Review by davidosterberg — APPROVED** [review]
Code looks good. It compiles cleanly, and works as expected. I have a request to not hide the parameters but it is only a personal opinion.

**Comment by chennes** [comment]
> I have a request to not hide the parameters but it is only a personal opinion.

Thank you for reviewing. That seems like a reasonable suggestion, so I've tweaked the code to make sure that when those parameters are read, they are also written to (rather than just taking on a default value every time). That way once they have been accessed once (e.g. by exporting or importing a file), they will appear in the Parameter Editor. That change is in 636add0, so if maintainers disagree that commit can be easily omitted.

**Pull request merged**
