### PR TITLE
PartDesign_Helix fix misplaced start

### LINKED ISSUE #13121: partdesign: "Cannot subtract primitive feature without a Bbase feature"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Whenever I change a value in the spreadsheet, the resulting recalculation results in the error "Cylinder069: Cannot subtract primitive feature without base feature", even though the Body was valid when opening the file and no changes were made to the Body.

To reproduce: open the spreadsheet and edit any cell.

The freecad file 
[partdesign-error.zip](https://github.com/FreeCAD/FreeCAD/files/14735442/partdesign-error.zip)

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu-wayland)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36438 (Git) AppImage
Build type: Release
Branch: main
Hash: 0def330a9e2119a14bb349cc406c2aa365421ab4
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * CurvedShapes 1.0.4
  * Assembly3 0.11.3
  * Assembly4 0.12.3
  * ThreadProfile 1.83.0
  * fcgear 1.0.0
```

### Subproject(s) affected?

PartDesign

### Anything else?

This bug seems to have been introduced between weekly builds 35456 (not affected) and 35822 (affected).

The original FreeCAD file was a lot bigger, I removed all non-essential stuff to keep the minimum required to reproduce the bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix #13121 
I deleted too much in #12977 🥴

Fixes inner holes too.
image

### CODE REVIEW

**Comment by FlachyJoe** [comment]
Tests fail, what a surprise 🙄

**Comment by AjinkyaDahale** [comment]
@FlachyJoe I see this PR mentioned in some 1.0 blocker tickets. Could you share why this was closed?

**Comment by FlachyJoe** [comment]
@AjinkyaDahale this PR doesn't fix anything more than these already merged.

**Comment by AjinkyaDahale** [comment]
What do you mean by "these already merged"?

**Pull request closed without merging**
