### PR TITLE
[Preferences] small Fix in Preferences GUI, changed width

### PR DESCRIPTION
**Pull request by grubertechnic**
[Preferences] small Fix in Preferences GUI, changed width

 - before
before

 - after
after

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7312">pipeline status</a> for feature branch [PR_7312](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7312). Pipeline [605244401](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/605244401) was triggered at [dddc887](https://github.com/FreeCAD/FreeCAD/pull/7312/commits/dddc88704b218ec783a2080bc93f4ee0f72d28d8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
While this can be an improvement, a hardcoded pixel value is a bad idea, it breaks again with different font sizes or longer labels (for example due to translation). If we want a hardcoded width the label should have a fixed with too and just use more lines if it doesn't fit.

**Comment by grubertechnic** [comment]
> While this can be an improvement, a hardcoded pixel value is a bad idea, it breaks again with different font sizes or longer labels (for example due to translation). If we want a hardcoded width the label should have a fixed with too and just use more lines if it doesn't fit.

True, but Qt is not nice with that. I tried more attemps with QSizePolicy, but it seems not to work with a list with symbols. I think that is the reason, why it was hardcoded before.

**Comment by benj5378** [comment]
> > While this can be an improvement, a hardcoded pixel value is a bad idea, it breaks again with different font sizes or longer labels (for example due to translation). If we want a hardcoded width the label should have a fixed with too and just use more lines if it doesn't fit.
> 
> True, but Qt is not nice with that. I tried more attemps with QSizePolicy, but it seems not to work with a list with symbols. I think that is the reason, why it was hardcoded before.

Isn't it possible to make the labels wrap?

**Comment by wwmayer** [comment]
The best way is to use QFontMectris because you can determine the width of the shown text and to this value add e.g. 20 to have some spacing.
@grubertechnic when you enter the snippet into the Python console what's the returned value?
```
from PySide2 import QtGui
f=QtGui.QFont()
m=QtGui.QFontMetrics(f)
m.width("Part/Part Design")
```
For me it gives 93.

**Comment by grubertechnic** [comment]
> For me it gives 93.

The output is:
`<input>:1: DeprecationWarning: QFontMetrics.width(const QString & arg__1, int len) const is deprecated`



> Isn't it possible to make the labels wrap?

Many of them are just one words. Wrapping them looks more weird as an extra space.

**Comment by grubertechnic** [comment]
I changed a litte bit the macro and get 97. Funny thing is, that i still get the warning, even it matches according the docs [https://doc.qt.io/qtforpython-5/PySide2/QtGui/QFontMetrics.html](url) the Qt version. Anyway. So measuring the texts and adapt the width is an option.

**Comment by adrianinsaval** [comment]
> Many of them are just one words. Wrapping them looks more weird as an extra space.

but it's those with more than one word that don't fit.

**Comment by grubertechnic** [comment]
> but it's those with more than one word that don't fit.

No, when you look in the Screenshot, even oneliner does not fit. Worbenches, Spreadsheet and some Addons (look in the Addonmanager, how long the oneliner can be).

**Comment by grubertechnic** [comment]
Anyway i close it.

**Comment by wwmayer** [comment]
@grubertechnic See 0c7e521ff5

**Pull request closed without merging**
