### PR TITLE
TechDraw - EdgeWalker, Symbols, Section Dialog

### PR DESCRIPTION
**Pull request by WandererFan**
Please merge.  This PR contains: 
- improvements to EdgeWalker face detection & error handling
- minor changes to Section creation dialog
- add EditableText capability to Svg symbols
- Svg Tolerance Symbols from @bavariaSHAPE

Thanks.

### CODE REVIEW

**Comment by wwmayer** [comment]
There are serious bugs in
Py::Object edgeWalker(const Py::Tuple& args) and
Py::Object findOuterWire(const Py::Tuple& args):
1. If the parsing in PyArg_ParseTuple fails then "pcObj" is not a valid pointer but still undefined. Thus, accessing it to create the exception message causes a segfault
2. In general inside PyCXX based functions you should avoid FreeCAD exception types but use PyCXX exception when doing type checking, otherwise the raised exception is a bit confusing. Alternatively you can extend invoke_method_varargs and directly convert Base::TypeError to Py::TypeError
3.  In the above two functions you should not explicitly check for the list type because otherwise you make its usage again quite unpythonic since it won't accept other sequence types like tuples, numpy arrays or other containers. Instead you should only do a type checking when accessing the items of the sequence and raise an exception there if needed.

**Comment by WandererFan** [comment]
Error handling changed to Py::Exception/Py::TypeError

**Comment by WandererFan** [comment]
Travis OSX build timed out.  gcc/clang ok.

**Comment by bblacey** [comment]
I just restarted the macOS job - must have been a Travis hiccup and will probably pass this time given your changes pass on all other platforms.

**Comment by WandererFan** [comment]
Thank you, @bblacey.  Everything passed.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
