### PR TITLE
fixing stepZ for exporting

### PR DESCRIPTION
**Pull request by easyw**
fixing stepZ for exporting

fixing error builtin instead of builtins
on https://github.com/FreeCAD/FreeCAD/commit/42cb7565223ac602ab21ecfb41cac8c70156ee98

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9193">pipeline status</a> for feature branch [PR_9193](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9193). Pipeline [829157635](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/829157635) was triggered at [6d56f3a](https://github.com/FreeCAD/FreeCAD/pull/9193/commits/6d56f3a9ab9ca9a0e11085906fe4d589e23ca382). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@easyw does this address #8218 ?

**Comment by easyw** [comment]
@luzpaz 
the issue you referenced is not an issue... to export to a stpZ format, the python code is different.
That issue should be closed.
Simply manually export it with the Gui to view the code in the python panel.
This issue instead has been introduced recently
here:
https://github.com/FreeCAD/FreeCAD/commit/42cb7565223ac602ab21ecfb41cac8c70156ee98

**Comment by chennes** [comment]
Thanks for the fix, I missed this when I reviewed.

**Comment by easyw** [comment]
@chennes 
Thx

**Pull request merged**
