### PR TITLE
[Draft] Reordering modifiers toolbar

### PR DESCRIPTION
**Pull request by carlopav**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by carlopav** [comment]
https://forum.freecadweb.org/viewtopic.php?f=23&t=44289

**Comment by carlopav** [comment]
@yorikvanhavre @vocx-fc 
in the forum we were talking about removing the Draft_Drawing command. Since it's bound to Drawing WB it can cause confusion, and users can access those features from drawing wb anyway. We can add a tooltip or remove it. what do you prefer?

**Comment by yorikvanhavre** [comment]
I would leave it in the code and add it to the list of FreeCAD commands, but mark it as obsolete and remove it from all toolbars in Draft, Arch, etc

**Comment by carlopav** [comment]
@yorikvanhavre here you have it: https://github.com/FreeCAD/FreeCAD/pull/3257

**Pull request merged**
