### PR TITLE
[Macro Menu] add Recent macros to Macro menu + list size preference. …

### PR DESCRIPTION
**Pull request by mwganson**
… Executes selected macro or if Shift+click opens macro in editor.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@mwganson is there a forum thread associated with this PR ?

**Comment by mwganson** [comment]
No forum thread.  Should we start one?

**Comment by mwganson** [comment]
https://forum.freecadweb.org/viewtopic.php?f=8&t=48342

**Comment by spanner888** [comment]
Compiled, run and tried to break it on debian, but could not. Works well thanks.

Looked hard at the code...but I have a fair bit to learn yet...

**Comment by mwganson** [comment]
Thanks for testing.

**Comment by yorikvanhavre** [comment]
This looks really well done. Waiting just if @wwmayer has nothing to say against it, and I'll merge

**Comment by mwganson** [comment]
I think I'm finished working on this now unless someone notices any issues that need to be addressed.

**Pull request merged**
