### PR TITLE
GUI: Update MacOS detection macro

### PR DESCRIPTION
**Pull request by chennes**
Deprecated for many years now.

### CODE REVIEW

**Comment by 3x380V** [comment]
There is one more in https://github.com/FreeCAD/FreeCAD/blob/c0c7bd647dc91f8807d8632585b6e6a53a040798/src/Gui/Application.cpp#L2029 Also there are bunch of `Q_OS_MAC`, a deprecated synonym for `Q_OS_DARWIN`.

**Comment by luzpaz** [comment]
@ipatch JFYI

**Comment by chennes** [comment]
> There is one more in https://github.com/FreeCAD/FreeCAD/blob/c0c7bd647dc91f8807d8632585b6e6a53a040798/src/Gui/Application.cpp#L2029 Also there are bunch of `Q_OS_MAC`, a deprecated synonym for `Q_OS_DARWIN`.

These should all go to the newer MACOS define, then?

**Comment by 3x380V** [comment]
@chennes, I'm definitely not a MacOS expert, but to me it seems anything touching `Q_OS_DARWIN` is related to the BSD under the hood. Anything related to  `Q_OS_MACOS` is about the GUI. Then we have all those `FC_OS_MACOSX` which are related to BSD core as `Q_OS_DARWIN` is.
So any define related to QT GUI should read `Q_OS_MACOS`. Any define related to QT core should read `Q_OS_DARWIN` and any define related to QT independent (pure C++) code running on mac should read `FC_OS_MACOSX`.

**Comment by chennes** [comment]
OK, reading [Qt's documentation](https://doc.qt.io/qt-6/qtsystemdetection.html#Q_OS_APPLE), I've gone with Q_OS_APPLE for non-Widget stuff, and Q_OS_MACOS for widget-specific stuff. In FreeCAD there is likely no difference, we don't run on Apple's other devices of course.

**Comment by 3x380V** [comment]
Cool! Just don't give up on FreeCAD running on tablet ;-)

**Pull request merged**
