### PR TITLE
Travis CI: Python 3.4 in end-of-life so test on Py36 instead

### PR DESCRIPTION
**Pull request by cclauss**
https://devguide.python.org/#branchstatus

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Seems like travis doesn't like it...

**Comment by wwmayer** [comment]
I think it fails because travis still uses Ubuntu 14.04 which doesn't have Python 3.5. Before merging this PR the travis environment should be upgraded which must be done anyway because 14.04 will soon expire, too.

**Comment by wwmayer** [comment]
It still fails and it's because of boost. I guess version 1.55 must be changed to 1.58. Another little change I don't understand why Python 3.7 is required at some point and further down 3.5. Or is this just a typo? At least in xenial the standard Python version is 3.5

**Comment by cclauss** [comment]
__python2.7__ on Travis CI Xenial Linux is Python 2.7.15 with pip 18.1
__python3.5__ on Travis CI Xenial Linux is Python 3.5.6 with pip 18.1
__python3.6__ on Travis CI Xenial Linux is Python 3.6.7 with pip 18.1
__python3.7__ on Travis CI Xenial Linux is Python 3.7.1 with pip 18.1

**Comment by wwmayer** [comment]
No idea why it still fails. I guess we should ask in the forum for help of a travis expert.

**Comment by wwmayer** [comment]
Are you sure that Python 3.7 is available for Xenial? According to https://packages.ubuntu.com/ the highest Python3 version I can find is 3.5 which actually makes sense because Xenial is from 2016 while Python 3.7 was released in June 2018.

**Comment by sasobadovinac** [comment]
libboost-dev
libboost-filesystem-dev
libboost-program-options-dev
libboost-python-dev
libboost-regex-dev
libboost-signals-dev
libboost-system-dev
libboost-thread-dev
libcoin80v5

**Comment by cclauss** [comment]
Travis CI cpp builds have [__pyenv__](https://github.com/pyenv/pyenv) v1.1.5 builtin so we should be able to do __pyenv install --force 3.6.3 ; pyenv global 3.6.3__

**Comment by sasobadovinac** [comment]
this testing in the pull request is really bad, things should get developed and tested in the private repos and why is py3.5 not ok?

**Comment by sasobadovinac** [comment]
@cclauss what are you trying to do? IMO you should use the boost and coin libraries as I have suggested above

**Pull request closed without merging**
