### PR TITLE
FEM: Fix ElementSet compile on Windows

### PR DESCRIPTION
**Pull request by chennes**
I believe this is the minimum viable fix to get the new ElementSet code compiling on Windows.

### CODE REVIEW

**Comment by chennes** [comment]
As an alternative to this, we could consider reverting #11492 (and therefore also  #14744) -- it's not clear to me that overall the structure of this new code is repairable. We were marginal on merging this at the meeting this morning, we could just shelve it until after 1.0.

**Comment by Syres916** [comment]
See change required for compiling with OCCT 7.8.1 https://github.com/FreeCAD/FreeCAD/issues/14762#issuecomment-2176462918

**Comment by FEA-eng** [comment]
@chennes I don't know the quality of this code but it was working fine from the user perspective when I was testing this and it would be nice to have it already in 1.0 (it has been waiting really long). Of course, only if it's possible to fix all the issues with that.

Maybe @marioalexis84 could share his opinion on whether it's fixable or not (and thus should be reverted).

**Comment by marioalexis84** [comment]
> Maybe @marioalexis84 could share his opinion on whether it looks fixable or not (and thus should be reverted)

wwmayer is working on the code. Better not to interfere.

**Comment by FEA-eng** [comment]
> wwmayer is working on the code. Better not to interfere.

Yeah but Chris mentioned that he was considering reverting this PR and the first patch for it instead of fixing it further so I thought it might be good if we address this now. But if Werner is still trying to get it working then let’s wait for that.

**Pull request closed without merging**
