### PR TITLE
Path: Update translated message syntax - InitGui module

### PR DESCRIPTION
**Pull request by Russ4262**
This is a proposed solution for a translation issue mentioned to me by @luzpaz at (https://github.com/FreeCAD/FreeCAD-translations/issues/120).

Please post any discussion or proposed changes here in this PR.
I do not see a forum thread.

I do not know how to link that issue to this PR since it is a different repo.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6789">pipeline status</a> for feature branch [PR_6789](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6789). Pipeline [523416274](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/523416274) was triggered at [d0d98e0](https://github.com/FreeCAD/FreeCAD/pull/6789/commits/d0d98e0c29aafe1a9555b9396551c49207e73f27). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
I think this will be confusing for translators, who will see only the disjointed parts of the sentence now. I suggest moving to using a `.format()` operator on the original string instead. It's just the f-string that `lupdate` doesn't understand.

**Comment by chennes** [comment]
The translations won't be extracted correctly if you do break the string up like that -- I've patched the upstream, but it won't be released until Qt 6.3 (I think).

**Comment by Russ4262** [comment]
Changed to use string `format()` method per comments.  Squashed and rebased branch.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6789">pipeline status</a> for feature branch [PR_6789](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6789). Pipeline [524385794](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/524385794) was triggered at [7d09462](https://github.com/FreeCAD/FreeCAD/pull/6789/commits/7d09462bc2b6e02908116abbe0628ce8f930d1d9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6789">pipeline status</a> for feature branch [PR_6789](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6789). Pipeline [524386752](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/524386752) was triggered at [f65b924](https://github.com/FreeCAD/FreeCAD/pull/6789/commits/f65b924ed443a78379902dcee06274028908b9a7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Kuzma30** [comment]
@Russ4262 
After big update of .ts files there is no string on crowdin
https://crowdin.com/translate/freecad/6766/en-uk?filter=basic&value=3#q=unit%20schema

**Comment by Russ4262** [comment]
@Kuzma30 
Please direct this statement to project supervisors.  I modified the PR per their comments, and as far as I know, the modification was per their specification. If I failed to do so, I will gladly correct it.

I am not familiar with the translation process and workflow.  My reading suggests there might be a script that is run on the source code that extracts all phrases to be translated, so long as they adhere to the syntax recognized by the script.  These phrases are then passed to CrowdIn in some way, manually or automatically - this is only my speculation.  I say this only because there might be a possibility that the effected message in the PR has still not been passed to CrowdIn for translation.  I really do not know, and I do not know how to find out other than to ask project supervisors who know the translation process and workflow.

Thanks for testing and providing great feedback.

**Pull request merged**
