### PR TITLE
Gui: introduce ShortcutManager for shortcut management and conflict resolving

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7771">pipeline status</a> for feature branch [PR_7771](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7771). Pipeline [691571866](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/691571866) was triggered at [9761a4e](https://github.com/FreeCAD/FreeCAD/pull/7771/commits/9761a4ea7931c9248914f1dbce96cbecc22893d0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Experimental snap builds are available (once they are built) in https://github.com/FreeCAD/FreeCAD-snap/pull/70  
Note to devs: please bump that ticket when you'd like a new build to be made

**Comment by chennes** [comment]
Note to self: this feature would probably be worth a post on blog.freecad.org

**Comment by luzpaz** [comment]
Note: to anyone viewing this and wants more background, here's the original PR summary: https://github.com/FreeCAD/FreeCAD/pull/6506?notification_referrer_id=NT_kwDOAD8s17IzMjEzNzE2MjM0OjQxNDAyNDc&notifications_query=is%3Aunread#issue-1159210089

**Comment by donovaly** [comment]
@wwmayer , @realthunder , since this PR master compiles for me but the resulting build does not start. I see the splash screen and after all libraries are loaded there, FreeCAD ends, so the main Window is never shown before FreeCAD ends. Bisecting lead me to

----------
039d1a01935201940b4b0ba328360b5b35950d19 is the first bad commit
commit 039d1a01935201940b4b0ba328360b5b35950d19
Author: Zheng, Lei <realthunder.dev@gmail.com>
Date:   Sat Mar 12 13:38:46 2022 +0800

Gui: fix macro command sync in Customize -> Keyboard/Toolbar

src/Gui/DlgKeyboardImp.cpp | 17 ++++++++++++-----
1 file changed, 12 insertions(+), 5 deletions(-)
--------------
(since I had compilation failure during bisecting, it might be one or two commits before or after.)

Can you please have a look?

**Comment by chennes** [comment]
@donovaly I just compiled on my copy of MSVC and it is working well for me. Maybe try a clean build?

**Comment by donovaly** [comment]
> @wwmayer , @realthunder , since this PR master compiles for me but the resulting build does not start. I see the splash screen and after all libraries are loaded there, FreeCAD ends, so the main Window is never shown before FreeCAD ends. Bisecting lead me to...

Weird, weird. I could narrow the issue down to this commit +- 2 commits. Then I went back to latest master and got a linker error for SketcherGui. However, FC did not start either. Then I cleaned and rebuilt only the the SketcherGui target and since this, I can start FC again and (also the linker error went away).

So it was false-alarm. Sorry.

**Comment by luzpaz** [comment]
Snap build available at https://github.com/FreeCAD/FreeCAD-snap/pull/70#issuecomment-1311024766

**Pull request merged**
