### PR TITLE
AddonManager: Tweak UI to return friendlier HTML formatted responses

### PR DESCRIPTION
**Pull request by luzpaz**
Using the Obsolete addons to test this on

### CODE REVIEW

**Comment by luzpaz** [comment]
FC-Addon-Manager-Banner-installed
FC-Addon-Manager-Banner-pending

**Comment by luzpaz** [comment]
@yorikvanhavre heads up, I think I fixed a regression, see 7f88f02  
Before the Addon Manager wasn't actually pulling obsolete addon's description in to the dialog. Now it does.

**Comment by yorikvanhavre** [comment]
This looks good to me! Will wait a bit to see if anyone has issues with it, then merge

**Comment by luzpaz** [comment]
@yorikvanhavre found an issue 
https://forum.freecadweb.org/viewtopic.php?f=10&t=37394&start=40#p340255

**Pull request merged**
