### PR TITLE
Import: fixes #5793: DXF export (Autodesk DXF 2D type) doesn't add an…

### LINKED ISSUE #5793: DXF export (Autodesk DXF 2D type) doesn't add any UNITS field inside the dxf file.
Issue imported from https://tracker.freecad.org/view.php?id=3494

* **Reporter:** @easyw 
* **Date submitted:** 5/25/2018
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** confirmed
* **Tags:** DXF, export, units

# Original report text

FreeCAD DXF export does not add $LUNITS and $INSUNITS both of which are needed for correct importing into any CAD.
$LUNITS and $INSUNITS should be included in the exported file, to specify which units the design is based on.
Autodesk section group codes:
https://www.autodesk.com/techpubs/autocad/acad2000/dxf/header_section_group_codes_dxf_02.htm

Related forum topics:
https://forum.freecadweb.org/viewtopic.php?f=8&t=28925
https://forum.kicad.info/t/units-once-more-dxf-import-trouble/10844

# Other bug information

* **Priority:** high
* **Severity:** feature
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @easyw 2018-05-25 22:58
following the KiCAd forum here some valuable notes:
The fun you find while digging into obscure specifications

$INSUNITS was introduced in the “Autocad 2000” specification for DXF.

This means any export methods set to AC1006 = R10, AC1009 = R11 and R12, AC1012 = R13 or AC1014 = R14. Will not have that tag present if the tool is respecting the export option,

Freecads export is for AC1009 / R12, so it will never include that tag so long as they are following the specification, and to include it would involve them remaking the exporter to support whatever the Autocad 2000 version is.

Before this, It was simply that DXF files where unitless, Most tools like solidworks and Autocad assumed this to be in inches if not specified on import,

---

ref: https://forum.freecadweb.org/viewtopic.php?f=8&t=28925#p235782

---

### Comment by Kunda1 2018-09-14 19:56
Related: #5805

---

### Comment by rawrpenguinzombies 2018-09-14 20:05
I am willing to pitch in on something for whoever fixes this and the related #5805 ID tickets.

---

### Comment by Kunda1 2018-09-15 12:48
rawrpenguinzombies please mention that on the forum thread so it's more visible.

### PR DESCRIPTION
**Pull request by wwmayer**
…y UNITS field inside the dxf file

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
CC @easyw

**Comment by wwmayer** [comment]
At least VariCAD Viewer (VV) likes the change. If VV opens a dxf file from FreeCAD without unit then a warning comes up that by default mm is used. With this change VV opens the file without printing a warning.

**Comment by yorikvanhavre** [comment]
Interesting.. In the python Draft DXF exporter, INSUNITS is set to 4 too (millimeters), We didn't set $LUNITS as it seems seldom used, and value 2 (metric)  is the default anyway. Setting $MEASUREMENT could also be a good idea.. https://ezdxf.readthedocs.io/en/stable/concepts/units.html

**Comment by yorikvanhavre** [comment]
Should we merge, @wwmayer ? Or are you waiting for more testing?

**Comment by wwmayer** [comment]
I wondered if anybody else has access to other applications that support DXF and either see an improvement or a regression.

So far I have tested:
* for VariCAD Viewer it's an improvement
* for Inkscape it doesn't seem to make a difference
* for LibreOffice Draw it doesn't seem to make a difference

**Comment by donovaly** [comment]
> I wondered if anybody else has access to other applications that support DXF

I use OCC Assistant for DXF and can test. (up to now everything that worked with Assistant also worked fro my work partners and their SolidWorks)

How do I test?

**Comment by wwmayer** [comment]
Create a sketch and export it as DXF. That's the file without units.
Now replace `Mod/Import/DxfPlate/header14.rub` of your FreeCAD build with this PR and export the sketch again as DXF.
Open both DXF files in an editor to see that they are different.

Import both files in OCC Assistant.

**Comment by donovaly** [comment]
> Create a sketch and export it as DXF.

Done. These were my export settings:
FreeCAD_FXfn0X7Jq9

I tested larger sketch I used to test the Sketcher performance and a sketch containing splines.
Both files look the same in Assistant, their dimensions are the same.

Since @yorikvanhavre suggested to also set $MEASUREMENT I did this and also this is safe for CAD assistant.

Reading https://ezdxf.readthedocs.io/en/stable/concepts/units.html I cannot imagine that setting these values could have any adverse effect.

So fine from my point to merge for 0.20, if possible also with $MEASUREMENT set.

**Comment by yorikvanhavre** [comment]
the botom line is, DXF has no real support for units. All these settings are for other things, but they are commonly used by apps to guess the file units. I think $insunits is by far the most commonly used... we could actually almost consider it was a bug in freecad not to have it set :) but the other settings have all unpredictable effects, so IMHO we should just merge this. If someone some day needs  $measurements , we can add it. but it's probably best not to without a specific reason.

**Comment by donovaly** [comment]
Thanks for the background info.
Merging now as you suggested.

**Pull request merged**
