### PR TITLE
[Draft]PathArray Colours and Angle Fix

### PR DESCRIPTION
**Pull request by WandererFan**
- the prerotation for Tangent mode was reversed.
- face colours in the Base object were not propagated to the copies.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by WandererFan** [comment]
@vocx-fc, @carlopav:  I can't pick either of you as reviewers.    Please look at the diffuse colour bit.  Not sure it should be in the App code, but don't know where else to put it.
Thanks.

**Comment by vocx-fc** [comment]
The object should not handle GUI properties, this should be handled by the `make_path_array` function in draftmake/make_patharray.py.

Once you assigned all properties, you can modify the view properties.
```py
if App.GuiUp:
    vobdc = obj.Base.ViewObject.DiffuseColor
        dc = vobdc
        for x in range(obj.Count - 1):
            dc =  dc + vobdc
    obj.ViewObject.DiffuseColor = dc
```

**Comment by yorikvanhavre** [comment]
@vocx-fc @carlopav I added you guys to the FreeCAD/developers github group that enables you to review PRs. I think you must accept the invite somewhere

**Comment by vocx-fc** [comment]
Thanks Yorik. I'm not sure what that entails, but I review pull requests when I can anyway.

**Comment by WandererFan** [comment]
cancelled.  to be split into 2 PAs.

**Pull request closed without merging**
