### PR TITLE
Mesh: Infinite loop when repairing mesh facet indices

### PR DESCRIPTION
**Pull request by Megidd**
Addressing the issue discussed here:

https://forum.freecadweb.org/viewtopic.php?f=8&t=62108

### CODE REVIEW

**Comment by luzpaz** [comment]
Please amend commit title:  
```
git commit --amend -m "Mesh: fix infinite loop when repairing mesh facet indices"  
git push --force
```

**Review by chennes — APPROVED** [review]
This compiles, runs, and fixes the issue described in the forums discussion. I think this should be fine to merge as-is.

**Comment by Megidd** [comment]
@luzpaz Done.

**Comment by luzpaz** [comment]
CC @AjinkyaDahale care to review  as well ?

**Comment by AjinkyaDahale** [comment]
@luzpaz sorry I was busy. I suppose @chennes and others handled this, so that's good.

**Pull request merged**
