### PR TITLE
PATH: fix for 2805

### PR DESCRIPTION
**Pull request by tuxintrouble**
changed TaskPanels to use unit conversions via FreeCAD.Units
commented out references to segLen since it is used nowhere

### CODE REVIEW

**Comment by sliptonic** [comment]
One small thing that should be fixed before merge:

If you edit the .ui panel files, you need to re-save them on whichever tab you want to be the default when they open.  As a loose convention, I always have the tabs open on the 'base geometry' since that's where the user is most likely to make changes. If the operation doesn't have a 'base geometry tab', it should open on the 'operation' tab since that has the most pertinent settings. 

I haven't actually built but everything else looks good to me.

**Comment by wwmayer** [comment]
Everything ready for merge?

**Comment by tuxintrouble** [comment]
requested changes are done. Ready for merge from my side.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
