### PR TITLE
Add SearchBar

### PR DESCRIPTION
**Pull request by ToddG**
**WHAT**
Migrate [Suzzane Soy's SearchBar Add-On](https://github.com/SuzanneSoy/SearchBar) to here.

**WHY**
`pierreporte` suggested, in [this thread I started about accessibility](https://forum.freecad.org/viewtopic.php?t=90034&start=10), that this would be a good project to work on.

```
Access to commands via keyboard could be achieve with the requested search function (see [issue #8290](https://github.com/FreeCAD/FreeCAD/issues/8290)) and a good shortcut to put the focus on it.
```

**HOW**
1. This is a direct port of Suzzan's work into this branch. I attempted to preserve her history:

First I prepared her code to place it in `src/Mod/SearchBar` 
```
cd SearchBar
git checkout main
git filter-repo --to-subdirectory-filter src/Mod/SearchBar -f
cd ..
```

Then I merged her code in to the FreeCAD repo as follows:
```
cd freecad
git co -b toddg/searchbar-04
git remote add searchbar ../SearchBar 
git fetch searchbar --tags
git merge --allow-unrelated-histories searchbar/main
git remote remove searchbar
```

2. Create CMakeLists.txt
3. Add build option to cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake
4. Add conditional add to src/Mod/CMakeLists.tx
5. Update LICENSE to latest LGPL
6. Remove unnecessary package.xml

**TODO**
1. This code is `as-is` from Suzzane's repo. I do not know what the code quality requirements are in FreeCAD. I don't see evidence of standard linting, e.g. isort, flake, black, mypy. I'll need guidance as to what is required here.
2. It doesn't seem like people are actually using `namespaced workbenches` as shown in the [workbench starterkit](git@github.com:ToddG/freecad.workbench_starterkit.git)... I have a [related PR in that repo](https://github.com/FreeCAD/freecad.workbench_starterkit/pull/23). If there is interest/need, I can convert this to a namespaced repo.
3. I need help with assigning a global key binding to the SearchBar. It will be much more useful if the user does not have to use the mouse in order to enter keyboard commands...that sort of defeats the purpose of this accessibility feature.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Thanks for retaking this, @ToddG !

I feel this should be done right after 1.0, because of the possible danger of introducing undetected last-minute bugs into 1.0, and the time is short to fix them (RC probably out today)

**Comment by luzpaz** [comment]
@ToddG hi, any reason you closed this ?

**Comment by pierreporte** [comment]
@luzpaz He left a message on the forum: https://forum.freecad.org/viewtopic.php?p=783191#p783191

**Comment by luzpaz** [comment]
> Sorry, I've run out of time and no one has responded to my questions. I've canceled my PRs. When I have time again (probably in 2026), then perhaps I'll try contributing again.
>Warm regards.

bummer

**Pull request closed without merging**
