### PR TITLE
Step Reader Improvement (Pass 3)

### PR DESCRIPTION
**Pull request by vejmarie**
This PR is removing the massive amount of Coin warnings about bad name forming coming from Step Import which are not fully compliant with various naming standards (it does add _ if the first charachter of a Shape is [0-9] and invalidate any remaining characters which are not within [0-9][a-z][A-Z][_])

It does also activate only leaf of the UI tree, accelerating rendering, selection and browsing of complex STEP files.

### CODE REVIEW

**Comment by wwmayer** [comment]
Sorry but linking a GUI module (FreeCADGui) in an App module is a no-go.

**Comment by vejmarie** [comment]
Hi. No problem. So it probably means I need to expand the code to the ImportUI part where I could probably link with FreeCADGui.

**Comment by wwmayer** [comment]
Is this latest change only related to the Coin warnings? Can you provide me a simple STEP example file which shows such warnings?
I created a file with object labels with characters outside the VRML standard but didn't get any warnings. A while ago I implemented this in ViewProvider::addDisplayMaskMode where not allowed characters are replaced by "_".

**Comment by vejmarie** [comment]
can you download these files ? 
https://github.com/opencomputeproject/zaius-barreleye-g2/tree/0.5.3/HW/ME , any of the STEP file there. This git repo is using lfs extension from GIT that is why you don't see them into the web interface. So you need to activate it while cloning it and you will get the files. If this is too much for you I can extract them and push the example on a dropbox equivallent ;)

**Comment by wwmayer** [comment]
Ah, and in ViewProviderDocumentObject::updateData object labels that are changed later are encoded and in the scene inspector decoded again. Maybe the encoding still creates not allowed characters?

In case this still causes problems then we need an encoding which only produces supported characters as replacing everything with "_" will make the whole function useless when working with a language like Chinese.

**Comment by vejmarie** [comment]
Yep. One of the issue is probably coming from the fact that there is some chinese character into these STEP files, and we do not know the original encoding (utf-8 or other). We are trying to promote usage of pure ASCII character for STEP within Open Hardware as this issue is raised with many tools and pretty hard to address especially when you support multiple O/S. I should have finished the PR update in a few minutes.

**Comment by vejmarie** [comment]
@wwmayer I have moved the code into the Gui part. So it shall work "properly" now. Still needs some code cleaning, and will have a Pass 4 probably, but this is still a good step forward I think.

**Comment by wwmayer** [comment]
Cleaning the names in the STEP importer to conform with Coin/VRML is the wrong way because this may "damage" a lot of apart from that correct names. Also clean_name creates a lot of memory leaks because the allocated memory will never be freed.

I decided to pick up only the relevant parts and re-implement the way to transfer names to the scene inspector. See git show 321ca98

**Comment by vejmarie** [comment]
Ok no problem, thanks a lot. By the way you are right my clean_up function was really too dirty to support utf-8 encoded strings. I shall have had focused this function purely on space, and numbers characters ;).

**Pull request closed without merging**
