### PR TITLE
clean base

### PR DESCRIPTION
**Pull request by mosfet80**
removed unused getA() and setA()

### CODE REVIEW

**Comment by wwmayer** [comment]
Who says it's unused? Because it's a Python function nobody knows.

**Comment by wwmayer** [comment]
Function is used in https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Test/BaseTests.py#L446

**Comment by luzpaz** [comment]
Is it worth adding a comment (for posterity) ?

**Comment by wwmayer** [comment]
Actually not. It's always a bad idea to simply remove functions from the Python API because there is no control which external scripts use it.

Before a Python function can be removed it must be marked as deprecated and left in the code for at least one or two releases so that users of the function have enough time to port their code. Removing it as an ad-hoc decision is bad practice.

**Pull request closed without merging**
