### PR TITLE
Streamline scaling for DXF import

### PR DESCRIPTION
**Pull request by kpemartin**
Eliminate m_measurement_inch to clean up logic for priority of MEASUREMENT and INSUNITS. Save the actual scaling factor rather than the scaling enum so a switch statement is not executed for each call to mm() Add to CDxfRead the work to handle dxfScaling option, ImpExpDxfRead just has to set it up now. Get the scaling factor from a lookup table rather than a switch statement Display a message explaining what the scaling factor is and where it comes from

### CODE REVIEW

**Comment by kpemartin** [comment]
Still want to clean up some of the lint

**Comment by kpemartin** [comment]
Hmmm, I have cpplint complaining about some of the NOLINT categories I'm using to quiet down Clang-tidy.
Cpplint has a category for complaining about unknown lint categories (readability/nolint) but does not seem to understand NOLINTBEGIN/NOLINEND so a blanket suppression does not work.

I will next try to precede each NOLINTNEXTLINE or NOLINT with single-line NOLINTNEXTLINE(readability/nolint) to see if that shuts it up. Although this will eliminate the spurious lint messages it is still a PITA to have to do.

On the other hand because cpplint doesn't understand the BEGIN/END directives I don't have to protect those since cpplint doesn't realize these contain lint categories!

However, it would be much easier if cpplint didn't believe it was the only lint in the universe and that it therefore has a complete list of all the valid lint categories. Maybe it is possible to modify the automatic Lint check to suppress this category (readability/nolint) by default.

**Comment by kpemartin** [comment]
Using  NOLINTNEXTLINE(readability/nolint) before each clang-tidy NOLINTNEXTLINE or NOLINT directive has indeed suppressed the cpplint complaints about clang-tidy lint categories. Still a real pain to have to do this.

**Comment by yorikvanhavre** [comment]
I might have introduced a conflict here by merging something else earlier, sorry about that... Mind to have a look @kpemartin ?

**Comment by yorikvanhavre** [comment]
Thanks!

**Pull request merged**
