### PR TITLE
Fix navigation styles on Windows

### PR DESCRIPTION
**Pull request by hlavaatch**
Make mouse navigation work on Windows.

### CODE REVIEW

**Comment by wwmayer** [comment]
https://forum.freecadweb.org/viewtopic.php?f=3&t=50628

**Comment by chennes** [comment]
I cannot reproduce this bug, but it does seem plausible that `ev->getPosition()` might not give a viable mouse position during a keyboard event, which would then corrupt `lastmouseposition`. Coin's documentation is not clear (to me) on this point. This PR  would eliminate that possibility. I applied this patch to a more recent fork and it compiled and did not seem to have any negative effects, but since I can't reproduce the bug, I can't verify whether this fixed it. I'm on Windows 10, Qt 5.12.1, Coin 4.0.0a.

**Comment by hlavaatch** [comment]
I think it only happens when you have a joystick plugged in, it gets misdetected as the space navigator and the space navigator gets activated sending the extra event type. Thats why it is not easy to reproduce.

**Comment by wwmayer** [comment]
> I cannot reproduce this bug, but it does seem plausible that ev->getPosition() might not give a viable mouse position during a keyboard event, which would then corrupt lastmouseposition.

No, that's wrong. According to https://developer.openinventor.com/refmans/9.9/RefManCpp/class_so_event.html the method getPosition() is defined for SoEvent:
> Returns the window pixel location of the cursor when the event occurred as integer values.
The position is relative to the lower left corner of the window in which the event occurred.
Position should be set for all events, but that may not be possible for some events in some display environments. If position was not available, the method returns 0,0.

For keyboard events this returns plausible values for me. Sure, it's correct that a key event doesn't really have a location but Quarter (it's the binding between Qt and Coin3d) saves the position of the last mouse movement and sets the values to all SoEvents that are converted from QEvents.

Now, the handling of space mouse events is handled by FreeCAD, not Quarter and there is a mistake because it doesn't set the saved last mouse position.

Since I don't have a joystick or space mouse I cheated by modifying StdCmdUndo::activated to simulate a SoMotion3Event event:
```
void StdCmdUndo::activated(int iMsg)
{
    Q_UNUSED(iMsg);
    Spaceball::MotionEvent* event = new Spaceball::MotionEvent;
    qApp->postEvent(Gui::getMainWindow(), event);
}
```

so that whenever I press Ctrl+Z the event is sent to the main window. The event then comes through my navigation style handler and there indeed the value of getPosition() seems to be random.

To fix this issue the method SpaceNavigatorDevice::translateEvent() must be changed.
```
            SoMotion3Event* motion3Event = new SoMotion3Event;
            motion3Event->setTranslation(translationVector);
            motion3Event->setRotation(xRot * yRot * zRot);
            motion3Event->setPosition(this->mousepos); // <<<<<<<===   Add this line
```

@hlavaatch Apparently you have a joystick. So can you please check if adding the above missing line fixes the issue for you, too?

**Comment by hlavaatch** [comment]
I can't reproduce the original problem on current master of https://github.com/FreeCAD/FreeCAD.git now, it is working fine.
Should I try on an older version or different branch?

**Comment by wwmayer** [comment]
> I can't reproduce the original problem on current master of https://github.com/FreeCAD/FreeCAD.git now, it is working fine.

Have you reverted your changes of this PR?

> Should I try on an older version or different branch?

I have tested it with the master branch from yesterday (with my hack) and there I could basically confirm that the values were not correct.

**Comment by wwmayer** [comment]
99e9b4db1c45 fixes the actual problem

**Pull request closed without merging**
