### PR TITLE
SubWCRev out ot source build fix by sopwith

### PR DESCRIPTION
**Pull request by PrzemoF**
Signed-off-by: Przemo Firszt <przemo@firszt.eu>

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by elliotclee** [comment]
Ship it! :)

**Comment by PrzemoF** [comment]
Perfect, thanks!

**Comment by luzpaz** [comment]
@PrzemoF Sorry, don't mean to nit-pick but perhaps you would consider making the git commit subject a little more recognizable that this is related to building Fedora ?

**Comment by wwmayer** [comment]
Merged.

**Comment by PrzemoF** [comment]
> @PrzemoF Sorry, don't mean to nit-pick but perhaps you would consider making the git commit subject a little more recognizable that this is related to building Fedora ?

You're right, but it wasn't ever my patch and my impression was that it's not only related to fedora. More here: [1] (search for SubWCRev, direct link doesn't seem to work for me)

[1] https://www.freecadweb.org/tracker/view.php?id=4132#c13651

**Comment by luzpaz** [comment]
@PrzemoF :+1: 

BTW, does this ticket, now that it's merged, means that [Issue 4132](https://www.freecadweb.org/tracker/view.php?id=4132) on the tracker can be closed? If so, next time do you mind using the [mantisbt<->github syntax](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) to automate referencing or closing mantisbt tickets from github? Thanks in advance.

**Pull request closed without merging**
