### PR TITLE
Path: Correct beginning retraction to safe height in Boundary Dressup, issue #6279 [Bug]

### PR DESCRIPTION
**Pull request by Russ4262**
This commit changes the feed rate of the beginning retraction from G1 at Feed to a G0 Rapid rate.  This initial command is causing a problem with the Tag Dressup due to the first move being a G1 to Safe Height.

This bug was discovered via Tag Dressup error in forum at [Boundary Dressup and Tag Dressup](https://forum.freecadweb.org/viewtopic.php?f=15&t=63433).

We should really consider adding a warning to the user in the Boundary Dressup that informs them their effective Z-boundary is higher than the base operation's Final Depth.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6566">pipeline status</a> for feature branch [PR_6566](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6566). Pipeline [490728709](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/490728709) was triggered at [dd76cab](https://github.com/FreeCAD/FreeCAD/pull/6566/commits/dd76cabb34de7eea99cf759ab202c0c443eff13b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Russ4262** [comment]
@sliptonic 
When you git a chance, please think through the implications of the simple feed rate change here.  My confidence is at 90%-ish for this being a safe change, especially since it is only changing the feed rate for the initial retraction to Safe Height.  However, I am working under the assumption that the original author likely used G1 feed rate for a reason, but I cannot see that reason at the moment.  I figure your expertise would help determine if the simple change here is safe or if we need to look for another solution.

Thanks.

**Comment by sliptonic** [comment]
Take a look at PathHelix and how I've changed the feedrate handling.   I haven't done this across the board.  Just helix and drilling so far.   However I really like it.
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Path/PathScripts/PathHelix.py#L226
It puts all the feedrate assignment in one place and simplifies the code quite a lot.

**Comment by Russ4262** [comment]
@sliptonic 
I looked at your Helix reference that uses the `PathFeedRate.setFeedRate()` method to parse and set all feed rates.  I do not plan to re-write this code now due to the feature freeze.

My primary concern with this fix in its current state is whether or not changing the initial retraction rate from Feed to Rapid is a safe change to make.  Do you know of any reasons that it should `not` be done?  I don't see any, but I am not 100% convinced that it is indeed a safe change to make, due to my narrow CNC experiential knowledge.  I have a small concern that I might be missing some use cases that need the Feed rate for safety, rather than the standard Rapid rate.

Thanks.

**Comment by sliptonic** [comment]
Gotcha.  Yes, it's safe to go to safeheight at rapid speed.  

refactoring to use the setFeedRate method can happen as we refactor generally.  Not necessary to do it as a single work effort.  I've been doing it as I move gcode generation into the generator functions.

**Pull request merged**
