### PR TITLE
removing unused (zipios++) files due to library updates

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8797">pipeline status</a> for feature branch [PR_8797](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8797). Pipeline [801368892](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/801368892) was triggered at [f98c1f5](https://github.com/FreeCAD/FreeCAD/pull/8797/commits/f98c1f5ed93344bbed9ef9ed217fd1253ee4c302). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
https://github.com/Zipios/Zipios/tree/main/src is the wrong reference because it's the new library version which lacks of some features we need in FreeCAD. Furthermore many classes are still available in the new version but the files have been renamed. E.g. the class CollectionCollection is available in collectioncollection.hpp

Our version is based on 0.1.5.9 that is still used in many Linux distributions like Debian & derivatives or Fedora (see https://packages.ubuntu.com/kinetic/amd64/libzipios++-dev/filelist)

I recommend not to remove any further files of this library.

**Review by wwmayer — COMMENTED** [review]
See last comment

**Comment by mosfet80** [comment]
I was trying to update the library with the version I mentioned. As soon as the last changes I open a discussion on the forum

**Pull request closed without merging**
