### PR TITLE
Material: Material editor enhancements

### PR DESCRIPTION
**Pull request by davesrocketshop**
Continues the work of the material subsystem improvements.

This merge covers the continued development of the material editor.
The primary improvements are in the handling of 2D and 3D array properties.
These properties are now fully editable, and can be saved and restored.

The cards now separate the author and license. These were previously saved
as a single item. Future support will be provided for standard open source licenses.

Saving operations validate the cards to ensure UUIDs of materials are considered.
Warnings are given when a save could potentially impact the models, such as
saving over a material instead of creating a new instance.

The editor is still not complete. There are a number of functional elements, such as
drag/drop operations, folder creation, and deletion operations that need to be added
to the main tree. State needs to be saved and restored to improve the user experience.
The appearance preview also needs significant work. This will be handled in a future
PR.

### CODE REVIEW

**Comment by luzpaz** [comment]
Are the .vscode/ files included in this PR relevant to the PR too ?

**Comment by davesrocketshop** [comment]
> Are the .vscode/ files included in this PR relevant to the PR too ?

No. That's .gitignore not .gitignoring. I'll fix that.

**Comment by davesrocketshop** [comment]
> I think this is good to merge as soon as the .vscode stuff gets removed.

Done

**Comment by wwmayer** [comment]
There is one thing I would like to know:
Why are all changes reverted that fixed various compiler warnings, fixed build failures, removed deprecated code, ...?

**Comment by davesrocketshop** [comment]
I'm not sure. This was an odd merge for me... automatic merge wasn't automatic at all. I'll go back and review

**Comment by davesrocketshop** [comment]
Were there problems outside of src/Mod/Material?

**Comment by davesrocketshop** [comment]
I don't know how those were missed in the merge, but they were automatically merged over. I'll prepare a regression PR

**Comment by luzpaz** [comment]
automatic merge meaning using the github ui merge functionality  ?

**Comment by davesrocketshop** [comment]
No. Standard git merge. Things that should have been automatic showed as merge conflict, requiring me to manually resolve over 200 files worth. None of the previous changes were shown as options.

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/11256

**Pull request merged**
