### PR TITLE
add toolbar icon to create mesh from shape

### PR DESCRIPTION
**Pull request by donovaly**
In daily work there are 2 main methods to work with meshes: creating one from a shape or importing an existent one.
Since the generation from a shape is often needed, add its icon to the default toolbar.

### CODE REVIEW

**Comment by vocx-fc** [comment]
Is this the same tool? [Mesh_MeshFromShape](https://www.freecadweb.org/wiki/Mesh_MeshFromShape)

If this is the case, the wiki page should be renamed to "Mesh_FromPartShape" to match the source code.

**Comment by donovaly** [comment]
> Is this the same tool? [Mesh_MeshFromShape](https://www.freecadweb.org/wiki/Mesh_MeshFromShape)

Yes.

> If this is the case, the wiki page should be renamed to "Mesh_FromPartShape" to match the source code.

If a renaming is really necessary I vote to rename it in the code since the feature works also fine for PartDesign features (and I use this almost every day).
@wwmayer what do you think?

**Comment by vocx-fc** [comment]
Well, PartDesign Features are ultimately derived from PartFeatures, so the name makes sense as it is now. Which is why I think only the wiki should be renamed to match the code.

**Comment by yorikvanhavre** [comment]
There is often that problem, commands have a "hard-coded" name, which is by which they are registered in FreeCAD and all the other subsystems (translation, what's this? etc...). This name is not necessarily what appears in menus. Hence sometimes the confusion, someone starts a wiki page with the name from the menu.
At some point we would need a kind of transparent system where users don't need to know the internal name of a command to find the right wiki page... But even so, pages should still be named after the internal name...

**Comment by yorikvanhavre** [comment]
But in any case we can already merge this.

**Comment by vocx-fc** [comment]
Just a note, the wiki page was renamed. It is now named [Mesh_FromPartShape](https://www.freecadweb.org/wiki/Mesh_FromPartShape).

See forum thread, [Rename: Mesh_MeshFromShape to Mesh_FromPartShape](https://forum.freecadweb.org/viewtopic.php?f=21&t=40432).

**Pull request merged**
