### PR TITLE
Gui: prevent crashes on MacOS using boost::format

### PR DESCRIPTION
**Pull request by 0penBrain**
This PR is an attempt to solve crashes on MacOS described here :
https://forum.freecad.org/viewtopic.php?t=75442
https://forum.freecad.org/viewtopic.php?t=77234

### CODE REVIEW

**Comment by 0penBrain** [comment]
@wwmayer do you see any risk at merging this PR ? I just replaced all `%i` with `%d` which at worst shouldn't change anything.

**Comment by wwmayer** [comment]
According to https://www.boost.org/doc/libs/1_66_0/libs/format/doc/format.html#printf_directives using "%i" should be valid. But since `%d` is also valid it's worth a try.

**Comment by 0penBrain** [comment]
Yes `%i` is valid as is `%d`. But while both converts to decimal numbers, there are cases where 'such as in `scanf` where they are not equivalent.
Hence my present try. :)
I'm gonna merge and we'll see. If it's not enough, I may try change all `%d` to `%.1d`.

**Comment by wwmayer** [comment]
> Yes %i is valid as is %d. But while both converts to decimal numbers, there are cases where 'such as in scanf where they are not equivalent.

Sooner or later we should move from boost::format to libfmt because for `fmt::sprintf` this library does some proper run-time checks whether the passed arguments match with the format specifiers. (From what I have read it can even do some compile-time checks with C++20.)

When using `fmt::format` (what I prefer) then for each argument `{}` can be used which will simplify things a lot. The compiler will find the right type automatically, then.

**Pull request merged**
