### PR TITLE
[Arch] IFC (structural view) export for slabs (new pull request)

### PR DESCRIPTION
**Pull request by balrobs**
This pull request replaces this one: https://github.com/FreeCAD/FreeCAD/pull/4823
Regarding to this minor code improvements have been made which were validated through performed tests.
(see dedicated forum thread: https://forum.freecadweb.org/viewtopic.php?f=39&t=54286&start=30#p508306)
As @Bernd suggested I split it into two commits:

First commit:
- does only code formating for better readability

Second commit
- IFC export for StructuralSurfaceMembers (ATM only slabs with their thickness)
- IFC export for RelConnectsStructuralMember [connection between structural members (linear/surface) and structural connection (punctual/linear)]

### CODE REVIEW

**Comment by berndhahnebach** [comment]
very much better to read :-)

**Comment by balrobs** [comment]
Thank you @Bernd for merging and sorry for the mess with my pull request #4823.
However everything should be good now:
#4831 was merged and improves IFC2x3 export
#4823 was closed and in its place this pull request was merged
Now I will try to improve material export
Cheers

**Comment by luzpaz** [comment]
Thanks for all the work @balrobs !

**Comment by balrobs** [comment]
It's my pleasure ;-)

**Pull request merged**
