### PR TITLE
Conda: Adding conditional `typedef long ssize_t;` if compiling on Windows with Python 3.10

### PR DESCRIPTION
**Pull request by looooo**
`d:\bld\freecad_1652648767916\work\src\gui\SplitView3DInventor.h(101): error C2061: syntax error: identifier 'ssize_t'`

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6891">pipeline status</a> for feature branch [PR_6891](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6891). Pipeline [539969348](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/539969348) was triggered at [86f325f](https://github.com/FreeCAD/FreeCAD/pull/6891/commits/86f325fb2e05c539e305e90229a01b6dbf38aca3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
@looooo does Py3.10 still have defined Py_ssize_t?
Actually using the ssize_t in AbstractSplitViewPy is wrong here because the virtual function `sequence_item` of the base class PythonExtensionBase uses Py_ssize_t and thus the overridden function should use it, too. Otherwise it can happen that if Py_ssize_t and ssize_t are not a typedef of the same type the overridden function `sequence_item` won't be called.

Can you check please if a8411881c9 fixes the build failure for you?

**Comment by looooo** [comment]
thanks @wwmayer It seems like this error was fixed. There is another occurrence here:
```
[2838/4075] Building CXX object src\Gui\CMakeFiles\FreeCADGui.dir\ExpressionCompleter.cpp.obj
FAILED: src/Gui/CMakeFiles/FreeCADGui.dir/ExpressionCompleter.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\cl.exe  /nologo /TP -DBUILD_ADDONMGR -DCMAKE_BUILD_TYPE=\"Release\" -DCOIN_DLL -DFCGui -DFreeCADGui_EXPORTS -DHAVE_PYSIDE2 -DHAVE_SHIBOKEN2 -DHAVE_SNPRINTF -DNDEBUG -DOVR_OS_WIN32 -DPYSIDE_QML_SUPPORT=1 -DQSINT_MAKEDLL -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WIDGETS_LIB -DQT_WINEXTRAS_LIB -DQT_XML_LIB -DQUARTER_INTERNAL -DQUARTER_MAKE_DLL -D_OCC64 -D_USE_3DCONNEXION_SDK -I%SRC_DIR%\build\src\Gui\FreeCADGui_autogen\include -I%PREFIX%\Library\include\smesh -I%SRC_DIR%\build\src -I%SRC_DIR%\src -I%SRC_DIR%\build -I%SRC_DIR%\src\Gui -I%SRC_DIR%\src\Gui\Quarter -I%SRC_DIR%\build\src\Gui -I%SRC_DIR%\src\Gui\.. -I%SRC_DIR%\build\src\Gui\.. -I%SRC_DIR%\build\src\Gui\Language -I%SRC_DIR%\build\src\Gui\propertyeditor -I%SRC_DIR%\build\src\Gui\TaskView -I%SRC_DIR%\build\src\Gui\Quarter -I%SRC_DIR%\build\src\Gui\DAGView -I%PREFIX%\Library\include -I%PREFIX%\Library\include\eigen3 -I%SRC_DIR%\src\3rdParty\OpenGL\api -I%PREFIX%\Library\include\PySide2\QtCore -I%PREFIX%\Library\include\PySide2\QtGui -I%PREFIX%\Library\include\PySide2\QtWidgets -I%PREFIX%\include -I%PREFIX%\Library\include\qt -I%PREFIX%\Library\include\qt\QtCore -I%PREFIX%\Library\.\mkspecs\win32-msvc -I%PREFIX%\Library\include\qt\QtWidgets -I%PREFIX%\Library\include\qt\QtGui -I%PREFIX%\Library\include\qt\QtANGLE -I%PREFIX%\Library\include\qt\QtOpenGL -I%PREFIX%\Library\include\qt\QtPrintSupport -I%PREFIX%\Library\include\qt\QtSvg -I%PREFIX%\Library\include\qt\QtNetwork -I%PREFIX%\Library\include\qt\QtUiTools -I%PREFIX%\Library\include\qt\QtWinExtras -I%PREFIX%\Library\include\shiboken2 -I%PREFIX%\Library\include\PySide2 -I%PREFIX%\Library\include\qt\QtXml /DWIN32 /D_WINDOWS /W3 /GR  /MP /MD /O2 /Ob2 /DNDEBUG /Zm150 /bigobj /Zi /EHa -std:c++17 /showIncludes /Fosrc\Gui\CMakeFiles\FreeCADGui.dir\ExpressionCompleter.cpp.obj /Fdsrc\Gui\CMakeFiles\FreeCADGui.dir\ /FS -c %SRC_DIR%\src\Gui\ExpressionCompleter.cpp
%SRC_DIR%\src\Gui\ExpressionCompleter.cpp(491): error C2065: 'ssize_t': undeclared identifier

```

**Comment by wwmayer** [comment]
OK, thanks.

Unlike size_t the issue with ssize_t is that it's defined in POSIX and because Windows is not (fully) POSIX compliant it's not necessarily defined there. Because it's not trivial how ssize_t should be defined I think it's best to avoid this type completely. Either we use Py_ssize_t instead or int/long directly.

Looking at the whole code base ssize_t isn't used that much. Currently I found it in:
* libe57Format library twice but only for GNU -> OK
* SMESH library twice but only for GNU -> OK
* in FreeCAD itself 10x for Windows and GNU -> Not OK

I will fix this code shortly and ask you again to test the build...

**Comment by wwmayer** [comment]
OK, here is the change: d0f98bf45c

**Comment by looooo** [comment]
tested and works. Thanks!

**Comment by wwmayer** [comment]
Great!

**Pull request closed without merging**
