### PR TITLE
[Widgets] register transparency property of Gui::ColorButton

### PR DESCRIPTION
**Pull request by donovaly**
- at the moment it is not possible to set the property "allowTransparency" in Qt Designer

### CODE REVIEW

**Comment by donovaly** [comment]
@wwmayer, I don't know yet much about the widgets, can you please review the PR and merge if OK?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8651">pipeline status</a> for feature branch [PR_8651](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8651). Pipeline [788930607](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/788930607) was triggered at [0cc4fcb](https://github.com/FreeCAD/FreeCAD/pull/8651/commits/0cc4fcb9ac5139e9f6c08629bbc8c7f66303006c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Currently I am busy with other things. So, it will take me two or three days.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8651">pipeline status</a> for feature branch [PR_8651](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8651). Pipeline [788960528](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/788960528) was triggered at [6de2ed0](https://github.com/FreeCAD/FreeCAD/pull/8651/commits/6de2ed016802b2730cfef9de1e19f347dd0c5474). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
