### PR TITLE
[MOD:PART] removed unused parameter

### PR DESCRIPTION
**Pull request by mosfet80**
d variable is never used

### CODE REVIEW

**Comment by chennes** [comment]
@bgbsww can you review?

**Comment by bgbsww** [comment]
Looks correct to me:  makeElementRevolution exists because makeElementRevolve ( based on LS3 ) didn't support a mode of operation that main has.  Ideally, both would get compressed into a single method someday, but in the interim, d is simply a vestigial parameter that migrated with the signature.

**Review by bgbsww — APPROVED** [review]

**Comment by chennes** [comment]
I see in the meantime that the parameter has been updated to be marked as `[[maybe_unused]]`. I don't feel strongly about whether this PR's conflict is resolved, or if it is just closed.

**Comment by chennes** [comment]
In the PR review meeting we agreed that we should remove the parameter -- can you please resolve the conflict?

**Pull request merged**
