### PR TITLE
Spreadsheet

### PR DESCRIPTION
**Pull request by mwganson**
Adds alias line edit control next to contents line edit control in Spreadsheet view.

https://forum.freecadweb.org/viewtopic.php?f=8&t=43957

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@mwganson since this passed travis and a user opened up [FR No. 4287, after the fact](https://forum.freecadweb.org/viewtopic.php?f=8&t=43957#p376140), do you mind doing a force push again but revising the last commit summary to have `[skip ci]` in it and also `Closes #4287`

So for example:  
```
[skip ci] [Spreadsheet] fix bug where duplicate / bad aliases were being allowed

Closes #4287
```
See https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#rewriting-the-most-recent-commit-message

**Comment by wwmayer** [comment]
Merged.

**Comment by mwganson** [comment]
@luzpaz  What is the git command line to do this?  Also, since it has already been merged and closed would it still work to close the FR?  One final question, it says the pull request is closed, but the mwganson:spreadsheet branch has unmerged commits.  What does this mean?

**Comment by luzpaz** [comment]
> What is the git command line to do this? 

See https://wiki.freecadweb.org/tracker#GitHub_and_MantisBT

> Also, since it has already been merged and closed would it still work to close the FR? 

No. 

> One final question, it says the pull request is closed, but the mwganson:spreadsheet branch has unmerged commits. What does this mean?

This means that wmayer merged this commit manually without merging your PR. He may a have also merged it partially (tweaked it) but I'm not sure if that's accurate.

**Comment by mwganson** [comment]
Okay.  I have another bug I found.  It's displaying an error message about not being able to set an alias when the new alias is the same as the old one, so I have another PR I'll do with that fix in it.  I'll add #fixes 4287 in the commit message.

**Comment by luzpaz** [comment]
@mwganson  `Fixes #4287`

**Pull request closed without merging**
