### PR TITLE
[ArchWall] Add Offset per Edge Feature

### PR DESCRIPTION
**Pull request by paullee0**
(Similar to Width and Align per edge features)

ArchWall.py - Add Override Offset property & ground work for Multi-Layer Wall 
Offsets.py - Add offset per edge support to ArchWall

Forum Discussion :
- https://forum.freecad.org/viewtopic.php?p=759634#p759634

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
The CI tests fail with:
``` 
FAILED: testWallMultiMatAlign (TestArch.ArchTest.testWallMultiMatAlign)
Traceback (most recent call last):
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/home/runner/work/FreeCAD/FreeCAD/.conda/freecad/opt/freecad/Mod/BIM/TestArch.py", line 432, in testWallMultiMatAlign
    self.assertTrue(ptMin.isEqual(checkLst[i][0], 1e-8),
AssertionError: False is not true : Arch Wall with MultiMaterial and 3 alignments failed
```

**Comment by paullee0** [comment]
Thanks for bringing this up.  Any pointer to document explaining what this message means so I can follow up?  Seems some kind of 'test' TestArch.py?  I can have a look at this file.  Thanks :)

**Comment by paullee0** [comment]
Ok, though I haven't found how to run this TestArch.py, I understand what it is trying to do; have manually constructed the ArchWall based on DWire and Sketch and see the problem; would check where it comes from.

**Comment by paullee0** [comment]
OK, pushed a commit to fix the regression.

Though haven't know how to run the Arch unit test :)

(referring to https://wiki.freecad.org/Testing)

**Comment by yorikvanhavre** [comment]
> Though haven't known how to run the Arch unit test :)

`freecad -t TestArch` ;)

**Comment by paullee0** [comment]
> > Though haven't known how to run the Arch unit test :)
> 
> `freecad -t TestArch` ;)

Thanks.  The wiki has that line but the context is so minimal that I dare not run that over the git copy :LOL

Also thanks for the merge :)

**Pull request merged**
