### PR TITLE
Femopensees

### PR DESCRIPTION
**Pull request by ebrahimraeyat**
it remove this error:

- __future__ imports must occur at the beginning of the file. it is not needed for python3
- 'FemInputWriterOpenSees' object has no attribute 'femmesh'

### CODE REVIEW

**Comment by vocx-fc** [comment]
You are using `f{strings}` which are exclusive to Python 3. At the moment, the Travis tests still test for Python 2, and therefore the tests fail.

Personally, I would suggest you avoid these `f{strings}`. I think 0.19 will be the last version to be Python 2 compatible. Once that version is released, we could stop testing for Python 2 compatibility at all, and then we can use Python 3 features exclusively.

**Comment by ebrahimraeyat** [comment]
yes, thanks.

**Comment by berndhahnebach** [comment]
Did you made the PR on the wrong branch? IMHO your intention was to make a PR on this branch: https://github.com/berndhahnebach/FreeCAD_bhb/tree/femopensees

**Comment by berndhahnebach** [comment]
BTW: I do not think OpenSees Solver will make it into 0.19 release. Thus writing Python3 code exclusively is ok IMHO.

Bernd

**Comment by ebrahimraeyat** [comment]
> Did you made the PR on the wrong branch? IMHO your intention was to make a PR on this branch: https://github.com/berndhahnebach/FreeCAD_bhb/tree/femopensees
It is my first collaboration in another project. i try to learn git more. thanks

**Pull request closed without merging**
