### PR TITLE
LGTM:  various fixes for using string operator instead of numeric 

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by vocx-fc** [comment]
These changes test for `None`. It is fine to substitute the equality comparison `==` for `is`, however, it is a bit more Pythonic to simply test for the existence of the object. If the object is `None`, then it is equal to `not object`.

```python
if something == None:
    proceed()

if something is None:  # better
    proceed()

if not something:  # best
    proceed()
```

Using `object` and `not object` tests for existence and non-existence.
```python
if something:  # exists
    proceed()
 
if not something:  # does not exist
    proceed()

**Comment by yorikvanhavre** [comment]
For the story, the rationale I read is that `something is None` is faster than `something == None` as it compares pointers and not values

**Comment by joelgraff** [comment]
I can't help but comment on the `is None` vs `not` issue.  I'm sure we're all familiar with it - that `not` is a test to see if something is "falsey".  Thus, None, 0, False, [], {}, and '' all qualify.  

The problem for me is that `not` is testing for two very different conditions and returning the same result.  That is, 'False', 0, [], {} and '' are all about *state*.  `None` is about *existence*.  Failing to distinguish whether `not something` means it's is just empty / zero / false or means it doesn't exist at all usually ends up biting me.

Thus, I expressly avoid using `not` if I'm really testing for `None`.  At very least, I test for it separately.

**Comment by vocx-fc** [comment]
Joel, I think in all cases mentioned above the test is for existence, which is why I think using `not something` is fine. There is no separate test for empty content (empty value). If this exists, proceed, if it doesn't exist, then don't proceed.

**Pull request merged**
