### PR TITLE
Feature: export mesh with boundary for Fenics solver

### PR DESCRIPTION
**Pull request by qingfengxia**
It is fixed PR of #930  (failed to pass CI test), code has been commented by Bernd

New feature based on FemGmshTools, more mesh (volume and especially boundary mesh) export formats are supported. Fenics 3D and 2D mesh with boundary mesh can be exported now, to support my FenicsSolver project for FreeCAD. Also for Elmer solver

More feature description is here:
https://forum.freecadweb.org/viewtopic.php?f=18&t=23702&p=186894#p186894

I also run flake8 for the newly added python files.

- [ *] Branch rebased on latest master `git pull --rebase upstream master`
- [* ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ *] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [* ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
@berndhahnebach is this PR OK for you?

**Comment by qingfengxia** [comment]
I have explained my design on forum:

https://forum.freecadweb.org/viewtopic.php?f=18&t=23702&p=186894#p186894

**Comment by berndhahnebach** [comment]
> @berndhahnebach is this PR OK for you?

I'll have a look this evening or tomorrow morning. 

bernd

**Comment by berndhahnebach** [comment]
@wwmayer:
better to wait, a def we gone use in GSoC Elmer project was removed. Discussion continues on https://forum.freecadweb.org/viewtopic.php?f=18&t=23702

bernd

**Comment by wwmayer** [comment]
@berndhahnebach any news on this?

**Comment by qingfengxia** [comment]
I moved my feature into CFDWorkbench, now FenicsSolver is working in my CfdWorkbench now.

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=18&t=23702&p=331481#p331481

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=18&t=23702&start=20#p401794

**Pull request closed without merging**
