### PR TITLE
Draft: Add "legacy importer only" to DXF option

### LINKED ISSUE #13598: DXF Importer (C++) ignores the "Create as" import settings and always creates simple Part shapes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The DXF importer preferences present the following "Create" options to the user, as shown in the screen capture below:

- simple Part shapes
- Draft objects
- Sketches

image

However, regardless of the complexity of the DXF and the option chosen, the resulting FreeCAD objects created after the import are always simple Part shapes. I have tested this with multiple files and settings, and while I might have not been exhaustive, I never managed to obtain Draft objects or Sketches.

This can be tested with a [sample DXF file](https://github.com/jscad/sample-files/blob/master/dxf/dxf-parser/layers.dxf) that contains 3 layers, with a simple object (rectangle or circle) in each layer. The drawing looks like in the following screenshot, as loaded by QCAD:

Captura de pantalla de 2024-04-23 10-55-57

Steps to reproduce:

1. Go to Preferences > Import-Export > DXF
2. Under Create, select either "Draft objects" or "Sketches"
3. Import the [sample DXF file](https://github.com/jscad/sample-files/blob/master/dxf/dxf-parser/layers.dxf)
4. Expected: the imported components appear as "Draft objects" or "Sketches" (depending on the selection on step 2) in FreeCAD
5. Actual: the imported components are always "simple Part shapes"

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36961 (Git) Snap 996
Build type: Release
Branch: main
Hash: c4c453312d148fd67bd893366c42b559e28a85e6
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.4.20
  * BIM 2021.12.0
  * Curves 0.6.35
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.4.16.01
  * Assembly4 0.50.12
```

### Subproject(s) affected?

File formats

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Roy-043**
Fixes #13598.

### CODE REVIEW

**Comment by furgo16** [comment]
@Roy-043 thanks! I think there are stilll more capabilities in the preferences dialog that are legacy-importer-only. I wonder if there is a more concise way to mark them without prepending the ("legacy importer only") string to them.

I started doing a side by side comparison recently. It is not exhaustive and includes those features in the preferences dialog (e.g. it does not contemplate DXF entities support, etc.)- I'm not done yet (the `[TBD]` means I've not looked at that capability yet), but I'm including it here for illustration purposes:

| Capability | Python importer | C++ importer | Notes |
| --- | --- | --- | --- |
| Import texts and dimensions | [TBD] | :white_check_mark:  |
| Import points | [TBD] | :white_check_mark:  |  |
| Import layouts | [TBD] | :white_check_mark: |  |
| Import *blocks | [TBD] | :white_check_mark:  |  |
| Create simple Part shapes | [TBD] | :white_check_mark:  |  |
| Create Draft objects | [TBD] | :white_check_mark:  | C++: works partially, for annotations only. Other Draft objects (line, circle, etc) are not created, Part shapes are created instead |
| Create Sketches | [TBD] | :white_large_square: |  |
| Apply scale factor to import | [TBD] | :white_check_mark:  |  |
| Use colors from the DXF file | [TBD] | :white_check_mark:  |  |
| Join geometry | :white_check_mark: | :white_large_square: |  |
| Group layers into blocks | [TBD] | :white_check_mark:  |  |
| Use standard font size for texts | [TBD] | :white_large_square: |  |
| Use layers | :white_check_mark:  | :white_check_mark:  |  |
| Import hatch boundaries as wires | :white_check_mark: | :white_large_square: |  |
| Render polylines with width | :white_check_mark:  | :white_large_square: |  |

Here's a mockup of what I had in mind:

image

Conceivably, a better implementation would be to disable the relevant options when the <kbd>Use legacy python exporter</kbd> checkbox is ticked. However, as a first iteration, just marking those options would already go a long way preventing user confusion and spending time in trial and error importer passes (which can take a quite a few time depending on the imported file's complexity and the options chosen).

**Comment by Roy-043** [comment]
Thanks for the detailed analysis. It is indeed better to do this properly. I'll convert this PR to Draft for now. If I remember correctly there may even be a setting that affects both import and export...

**Comment by furgo16** [comment]
Thank you. I just finished the analysis and updated the original comment. The comparison table is now up-to-date to the best of my knowledge.

**Comment by furgo16** [comment]
Related: https://github.com/FreeCAD/FreeCAD/issues/13751

**Comment by Roy-043** [comment]
Result of the updated PR:
DXF-options

**Comment by furgo16** [comment]
This is excellent, thanks so much. This removes the previous uncertainty, it will make life easier and it will prevent unnecessary trial and error trying combinations of unimplemented options. Some other comments:

1. Is it worth considering sensible default settings in this PR, or rather discuss it in a separate issue? If so, happy to file it. Otherwise, in addition to the options already ticked in the screenshot, I'd suggest to tick the following ones as well:
   - [x] <kbd>Show this dialog when importing and exporting</kbd> => once there is one single importer with feature parity with the old one, and it is reasonably stable, this setting could be unticked as default for a more seamless import/open operation. But I think for now, it's worth letting the user know what and how will be imported, and showing them how to control that.
   - [x] <kbd>texts and dimensions</kbd> => I could imagine that given the low input in importing and processing them, and that they seem to be reasonably well supported, most folks would like to keep texts and dimensions from the original DXF file.
   - [x] <kbd>Use colors from the DXF file</kbd> => same as above
2. I'm not familiar enough with the exporter part to be able to comment on that section.

**Comment by furgo16** [comment]
Does this PR need further testing or review before getting merged? Thanks.

**Comment by Roy-043** [comment]
The `Show this dialog when importing and exporting` option is now checked by default. Changing the other preferences does not necessarily make sense for other workflows where a DXF is just used as a vector format, for example to import the contour of a product.

**Comment by furgo16** [comment]
Makes sense, thanks!

**Pull request merged**
