### PR TITLE
[Draft] add more patterns

### PR DESCRIPTION
**Pull request by donovaly**
This commit just syncs with the pattern of TechDraw:
- add further patterns
- save all patterns as plain SVG (strictly following thee SVG specifications) using Inkscape 1.0

### CODE REVIEW

**Comment by vocx-fc** [comment]
If I'm not mistaken the existing SVG patterns were already in plain SVG, #3060.  You can see the diffs; the information is basically the same, it is just arranged a bit differently, in more lines. The previous patterns were saved in Inkscape 0.92, I think.

**Comment by donovaly** [comment]
> If I'm not mistaken the existing SVG patterns were already in plain SVG

Yes. The purpose of this commit is to be in sync with TechDraw since it provides more patterns.
I only mentioned the plain SVG because I see that Inkscape 1.0 arranges the SVG ines now a bit different, this the changes in the diff.

**Comment by yorikvanhavre** [comment]
Honestly I've never seen a file that Qt wouldn't cope with when saved as inkscape SVG, that would open better when saved as plain SVG. The difference between the two are basically all the additional attributes that inkscape adds to objects in order to be better editable in inkscape. But it's the essence of XML (and thus SVG) to allow custom attributes, and Qt handles it properly by skipping unknown attributes. So the only real advantage in saving as plain SVG is reducing the file size a little bit. But I don't see an reason why not either...

**Comment by donovaly** [comment]
> Honestly I've never seen a file that Qt wouldn't cope with when saved as inkscape SVG, that would open better when saved as plain SVG.

This is not about Qt but about other programs around. We already had this case this year: the SVG export from FreeCAD could not be viewed by the browsers Chrome and Firefox.

The reason is non-plain SVGs contain style links such as
`xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"`

In the case we had, the browsers complained about that such an URL because it could not be reached thus the style to be used to display the SVG was not available.

So every SVG file that is used to be later exported as SVG should be plain SVG to avoid such cases. So icons are not effected but files for drawings, sketches etc.

**Pull request merged**
