### PR TITLE
Smesh upgrade and occ6 compatibility

### PR DESCRIPTION
**Pull request by ickby**
This branch updates SMESH to version 7 and makes it compatibel with OCC version 6 builds. It adopts FreeCAD to the new SMESH behavior.  It is the rebased version after latest FEM merges.

### CODE REVIEW

**Comment by bblacey** [comment]
@ickby, nice! You also need to modify the [.travis.yml for the OS X section](https://github.com/ickby/FreeCAD_sf_master/blob/610e43d8d7ae60b3b84422088a54a291a424e6af/.travis.yml#L121-L134) to add `brew install vtk` ignorder to install vtk 7.0 on OS X.  There isn't currently a port of MEDFile available for OS X (at least I couldn't find one) but I have managed to build med-3.0.7 on OS X 10.9+. It looks like we (I or @ianrrees ?) may need to write a brew formula for MEDFile.  

In the mean time, you can add the following to the .travis.yml to satisfy the MEDFile dependency on OS X

`curl -O 'http://files.salome-platform.org/Salome/other/med-3.0.7.tar.gz'`
`tar xvzf med-3.0.7.tgz`
`cd med-3.0.7 && mkdir build && cd build`
`cmake -DMEDFILE_BUILD_TESTS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=/usr/local ../`
`make -j2 install`

The above is untested but based upon some experimentation to build OCCT7 on OS X to support that initiative.  I recommend disabling the tests because there is a cmake quoting error that causes failures on OS X.  That will be addressed by a proper formula but this should allow you to build your PR on OS X.

**Comment by ickby** [comment]
bblacey thanks for the input. I added it and will push as son as the current build finished. How do I disable tests for OSX?

**Comment by bblacey** [comment]
The test-disabling that I recommended is accomplished by passing -DMEDFILE_BUILD_TESTS:BOOL=OFF when calling cmake for MEDFile (already in the code snippet above).  Also, I forgot but you will also need a `brew install hdf5` because MEDFile relies upon hdf.  I will watch the build and help you wring out any other kinks on OS X.

**Comment by ickby** [comment]
Ok, seems the MedFile build has been successfull but cannot find the libraries.  What do I need to chnge in the FindMedFile.cmake ?

**Comment by bblacey** [comment]
It looks like the [medfile download/tar](https://travis-ci.org/FreeCAD/FreeCAD/jobs/130584195#L247).  Checking now.

**Comment by bblacey** [comment]
Change the med file curl to:

`curl -o med-3.0.7.tgz 'http://files.salome-platform.org/Salome/other/med-3.0.7.tar.gz'`

**Comment by ickby** [comment]
Ok, changed that. Can I somehow abort running builds on travis?

**Comment by ickby** [comment]
Ok now it seems to build the medfile, however, after building it still fails with
sudo make -j2 install
make: *** No rule to make target `install'.  Stop.

This is strange, shouldn't this have already been finished? I don't understand that stuff.

**Comment by bblacey** [comment]
Checking from my phone but it looks like we need to add a `cd ..` after the MEDFile make install to set the current working directory back to the Travis build directory before invoking the FreeCAD make install.

**Comment by bblacey** [comment]
Actually `cd ../..` or `cd ${TRAVIS_BUILD_DIR}`

**Comment by vejmarie** [comment]
hi bblacey, I might be interested to have a look to your homebrew script, this is something I liked to learn ;). Sorry guys not being helping you tonight I have a complex things to finish for work. Will jump back tomorrow for sure, if Ickby is not successfull, but something tells me he will be !

**Comment by sasobadovinac** [comment]
build seems to finish fine, the install test seems to be broken and it actually comes from the latest merge on master 

file INSTALL cannot find
  "/home/travis/build/FreeCAD/FreeCAD/src/Mod/Fem/_TaskPanelFemSolverZ88.py".

broken master build
https://travis-ci.org/FreeCAD/FreeCAD/builds/130548118

**Comment by ickby** [comment]
yes trusty builds work fine except the install issue. But OSX failled again. This time all dependencies are installed OK, it is actually a code issue. And a strange one...

**Comment by bblacey** [comment]
@ickby, You can cancel a Travis if you are logged in, you can drill down to the sub-build (e.g. build 180.1) build and click the icon in the upper right corner that looks like a grey circle with an X inside it.

I just ginned up a quick MEDFile home-brew formula that seems to work.  I have to tend to some work items so I will be away for a bit but will make it available as a tap later - for now, the steps we are using should be adequate. @vejmarie, I will post to your forum thread when it is available.

**Comment by bblacey** [comment]
ok @ickby, try replacing all the individual medfile build and install steps with the following.

`brew install bblacey/taps/med-file --with-python`

**Comment by vejmarie** [comment]
Looks like the mac build failed because of this issue 

https://github.com/BristolTopGroup/AnalysisSoftware/issues/115

Travis Mac environment is quite old as XCode is currently supporting clang 7.3

**Comment by ickby** [comment]
Thanks vejmaria. As patching xcode in travis seems very involved I try to go the lazy route: It seems that the include of shiboken brings the definition error, and shiboken is only used at one place in freecad. So I try a simple #undef after the import to resolve the issue. 

It seems the same is done in src/Base/PyObjectBase.h for the normal python import. I copyed the code.

Lets see what happens :)

**Comment by vejmarie** [comment]
what is strange is that we should have had this issue in past build. Perhaps travis has changed something on there build or we shall be using brew python implementation instead of the one installed (this will have an impact on FreeCAD.app size). I don't know if brew python has the workaround from macport one or not.

**Comment by ickby** [comment]
Ok linux works after rebase to latest master (clang succeeds, gcc fails only due to build time). There is still this annoying OSX issue, my lazy fix did not work at all. Any ideas for this?

**Comment by vejmarie** [comment]
I will ask one of my colleague if I can borrow his mac (if he is in today), as he always joke at me for using macport instead of brew, so he should have brew installed on his. It will be faster to test fixes. Stay tune during the day.

**Comment by vejmarie** [comment]
ickby: I think there is no other option than patching the /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pyport.h file, or try to rely on brew python. Did you try to install brew python ? 
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
brew install python
Luckily this issue has been fixed into brew python. If not, then we will have to fix it. So, can you update your travis.yml to install brew python, run the compilation upload the  /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pyport.h somewhere that we could patch it ;)

**Comment by ickby** [comment]
vejmarie: in travis python is installed by brew, see https://github.com/ickby/FreeCAD_sf_master/blob/SMESH/.travis.yml#L121
what would additional be needed? I really have no idea about OSX/brew, I need a step by step instruction here

**Comment by vejmarie** [comment]
That is strange that brew install contents into /System/Library (everything into /System is coming from Apple normally), it should be into /usr/local to me if it was coming from brew. But I agree I can see the command line into the travis file.
This is my PATH when I compile with macport
export PATH=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/opt/local/bin:/opt/local/libexec/qt4/bin
I believe you should replace /opt/local by /usr/local on the Python Framework and that should be ok. (or at least we shall execute the right python code). Can you just try to redefine the PATH variable before issuing the CMAKE and make command (under the right user id ;))

**Comment by vejmarie** [comment]
Hi ickby, my friend sent me the pyport.h from homebrew and it does include the fix from macport, so if we properly setup the environment it should be working.

**Comment by ickby** [comment]
Ok, I will try tha tlater, I just started two tests with some stuf fin found on the net, random patch testing :)

**Comment by ickby** [comment]
Ok my stupid fixes all failed :) Now we need to change some path so that the correct include file is used (brew python instead of /system/library python). But is this something we need to change in brew? or should we add a hack in cmake? Honestly testing this with only travis available is aweful, it takes forever to check an idea...

**Comment by vejmarie** [comment]
Did you tried just the path change ? I believe that if it works like on Macport this is the only thing you might be needing. I will try to setup a homebrew compile environment into my office this afternoon, as I agree debugging on travis is a nightmare.

**Comment by ickby** [comment]
according to this: https://cmake.org/Bug/view.php?id=14809 it does not work well with path setting, as this only affects the binary search, not the include/framework search. I hence tried it with 
-DCMAKE_PREFIX_PATH=/usr/local
for OSX which should actually affect all search functions within cmake

**Comment by vejmarie** [comment]
Ok. So I am setting up a system with XCode currently and home brew. It will be ready in about 2 hours ( 3.8GB to download). I might be more helpfull that way. Just need to be sure I will clone the right github branch if you just can point me back to it. I thought the path change was good enough as it might catch some binaries which will point out to the relevant python cmake configuration file.

**Comment by ickby** [comment]
next faillure, cmake_prefix_path did not work. I seriously consider to just delete tha tfile and copy the brew verion into system python folder... arghh.

vejmarie: this is the branch, you should omit all commits from today: https://github.com/ickby/FreeCAD_sf_master/tree/SMESH

**Comment by ickby** [comment]
vejmarie: it seems VTK and openCV had the same issue. They generated the paths themself: https://github.com/Homebrew/legacy-homebrew/blob/51d054c/Library/Formula/opencv.rb#L50-73
Maybe this is also possible for us, we could just adopt this for travis

**Comment by ickby** [comment]
And I definitely need to quote that from the link above, they have my whole hearted approval:

# The CMake `FindPythonLibs` Module is dumber than a bag of hammers when
# more than one python installation is available---for example, it clings
# to the Header folder of the system Python Framework like a drowning
# sailor.

**Comment by vejmarie** [comment]
that could be a workaround yes. My system is still installing ... This is an old MacMini with an ultra slow internet connection. And yes it is a big mess ! But python-config script shall be able to manage that ...

**Comment by bblacey** [comment]
Hi guys, early morning here in SF CA...  Was reading about https://bugs.python.org/issue10910 just before crashing last night as the potential root cause.  Noticed the HB Python formula patches pyport.h to avoid the issue but our homebred-based os x builds incorrectly use the system python framework headers instead of the home-brew python framework headers - this is clearly wrong and could pose other problems as well.  I have a 10.9 VM setup that mimic's the travis environment for analysis/debug and once we get past this issue, hopefully the os x builds will work although there isn't much encouraging prior art of salomemesh on OS X out there ;)

Finally, I have a change to the med-file formula so I plan to push an update.  It fixes a formula bug that prevented the formula from using additional cmake_args and also patches the source to work around a swig issue that is only encountered when using the --with-python option so I recommend that we avoid that switch for now.

Looks like you guys did some more great work while I was sleeping ;)

**Comment by vejmarie** [comment]
welcome bblacey. That is really strange I am just running a test on a freshly installed MacMini (he is suffering currently as it doesn't have SSD), and got this -- Detected Homebrew install at /usr/local
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.11") 
-- Found PythonLibs: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (Required is exact version "2.7.11") 
-- Looking for pthread.h
at cmake stage. I am using homebrew for the first time, let's see if I can replicate the issue or if this is a pure travis one. (I am using XCode 7.3 and el capitan, 10.9 is out of our company for a couple months)

**Comment by ickby** [comment]
vejmarie: what about python include path? that is the one of relevance, and the one that I think points to /system/ path.  

bblacey: I think the openCV workaround I linked is the best option: finding the path to the homebrew python ourself and pass it directly to cmake as python include folder. But this is something that needs to be done with someone with a real system, my hacky travis try and error approach is too annoying for that.

**Comment by vejmarie** [comment]
Good news or not, I have reproduced the problem on my local box

**Comment by bblacey** [comment]
This is my work-around test:

`python_prefix=$(/usr/local/bin/python-config --prefix)`
` `
`cmake -DFREECAD_USE_EXTERNAL_KDL=ON \`
`      -DFREECAD_CREATE_MAC_APP=ON   \`
`      -DBUILD_FEM_NETGEN=ON         \`
`      -DCMAKE_BUILD_TYPE=Debug      \`
`      -DPYTHON_LIBRARY=${python_prefix}/Python \`
`      -DPYTHON_INCLUDE_DIR=${python_prefix}/Headers \`
`      -DPYTHON_PACKAGES_PATH=${python_prefix}/lib/python2.7/site-packages \`
`      ../`

If I look in the CMakeCacheList, I still find a reference to `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib` in the SMDS_LIB_DEPENDS.  Haven't figured out where CMAKE is picking that up yet...

**Comment by vejmarie** [comment]
there  might be a more elegant way if it works, which is to use the local Library directory.
ln -s /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework ~/Library/Frameworks/Python.framework which might be forcing clang to use that Framework instead of using the system wide framework. I used that stuff in the past for other libraries (this is like LD_LIBRARY_PATH but at compile run time, and one of the Framework benefit). I am testing it currently

**Comment by bblacey** [comment]
Sounds good...  While it is running, it would be good to see if you have any references in CMakeCache.txt to the system python in the component lib depends.  I think NETGEN is hovering up the system python and then SMESH includes the NETGEN libs.  Boost is another suspect to rule in/out.

**Comment by vejmarie** [comment]
Didn't worked :(, really strange

**Comment by bblacey** [comment]
I think the absolute path to the framework overrides implicit paths...  You could symlink /SystemLibrary/Frameworks/Python.framworks back to /usr/local... but that is a pretty drastic approach.  We need to find out which cmake module is ignoring the python libs variables.  I think it is the FEM part but not sure...  Maybe two sets of eyes on the CMake scripts will yield results ;)

**Comment by vejmarie** [comment]
Ok, seems to work that way into Gui, edit CMakeList.txt, remove PYTHON_INCLUDE_DIR and kick the compilation ... (I still have the link into my home directory)

**Comment by vejmarie** [comment]
I was too fast just failed sorry guys

**Comment by vejmarie** [comment]
@bblacey that is strange because this stuff works with macport, and we do have the issue "only" with homebrew, this should be more related to homebrew rather than to the Fem module itself. Might be good to find the issue at least for the brew people. I have disabled SIP on my Mac just to check if there could be issue with that, but as the feature didn't exist on 10.9 I was not optimistic, and there is finally no difference still the same compiler issue.

**Comment by bblacey** [comment]
Can you send me the build/CMakeCache.txt file from you MacPorts install that works?

**Comment by vejmarie** [comment]
I can, but I don't know how (sorry for the stupid approach, just tried a drag and drop)
[CMakeCache.txt](https://github.com/FreeCAD/FreeCAD/files/268740/CMakeCache.txt)

**Comment by vejmarie** [comment]
I think I might have found something ... On macport

This is the CMakeFindFrameworks.cmake, which is different from the standard one coming with cmake. Can somebody provide the homebrew one ?
`
if(NOT CMAKE_FIND_FRAMEWORKS_INCLUDED)
  set(CMAKE_FIND_FRAMEWORKS_INCLUDED 1)
  macro(CMAKE_FIND_FRAMEWORKS fwk)
    set(${fwk}_FRAMEWORKS)
    if(APPLE)
      foreach(dir
          ~/Library/Frameworks/${fwk}.framework
          /opt/local/Library/Frameworks/${fwk}.framework
          /Library/Frameworks/${fwk}.framework
          /System/Library/Frameworks/${fwk}.framework
          /Network/Library/Frameworks/${fwk}.framework)
        if(EXISTS ${dir})
          set(${fwk}_FRAMEWORKS ${${fwk}_FRAMEWORKS} ${dir})
        endif()
      endforeach()
    endif()
  endmacro()
endif()
`

**Comment by vejmarie** [comment]
This is the one from HomeBrew and it doesn't include the /usr/local/Cellar/Frameworks while the one from macport is have /opt/local/library/Frameworks to look inside it !

`#.rst:
# CMakeFindFrameworks
# -------------------
#
# helper module to find OSX frameworks
#=============================================================================
# Copyright 2003-2009 Kitware, Inc.
#
# Distributed under the OSI-approved BSD License (the "License");
# see accompanying file Copyright.txt for details.
#
# This software is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the License for more information.
#=============================================================================
# (To distribute this file outside of CMake, substitute the full
#  License text for the above reference.)
if(NOT CMAKE_FIND_FRAMEWORKS_INCLUDED)
  set(CMAKE_FIND_FRAMEWORKS_INCLUDED 1)
  macro(CMAKE_FIND_FRAMEWORKS fwk)
    set(${fwk}_FRAMEWORKS)
    if(APPLE)
      foreach(dir
          ~/Library/Frameworks/${fwk}.framework
          /Library/Frameworks/${fwk}.framework
          /System/Library/Frameworks/${fwk}.framework
          /Network/Library/Frameworks/${fwk}.framework)
        if(EXISTS ${dir})
          set(${fwk}_FRAMEWORKS ${${fwk}_FRAMEWORKS} ${dir})
        endif()
      endforeach()
    endif()
  endmacro()
endif()`

**Comment by ianrrees** [comment]
Hey guys, sorry if I'm missing something (it's a long thread and I'm trying to read in bursts while stuff compiles), but it seems like there's some problem with part of the build finding the wrong Python?

If that's the case, then there's some code in the top level FreeCAD CMakeLists.txt that sets some relevant cmake variables.  It's a bit complicated on OSX because there's a bundled Python that we don't want to use, the Homebrew folks have a section on it: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

Definitely do not add symlinks or whatever to change the Python environment just to build FreeCAD.

**Comment by bblacey** [comment]
Hey @ianrrees, nice to hear from you ;)  No one is thinking symlinks are the final solution, was merely trial and error to narrow the root cause.   While the top-level CMakeLists.txt scripts properly detect the brewed python interpreter, it seems that some underlying element is referencing the python include header in /System/Library/Frameworks and dragging it into Fem and SMESH causing compilation errors.  Specifically, SMDS_LIB_DEPENDS and Fem_LIB_DEPENDS are both erroneously including the system python framework instead of the brew'd python framework that is properly patched for c++11...  Unfortunately, I have been out straight today with other obligations today so I haven't been able to delve into the details but @vejmarie  and @ickby have been working diligently to triage and resolve it.  If you have any ideas, by all means, send them our way.  Where is our FreeCAD home-brew czar @peterl94?

**Comment by ianrrees** [comment]
> it seems that some underlying element is referencing the python include header in /System/Library/Frameworks and dragging it into Fem and SMESH causing compilation errors. 

If that Python header is edited to add:
`#error "Should not get here"`

then compilation is run, the error dump from the compiler should tell what pulled in the header.  I'm hoping to get some FreeCAD stuff done over the next few days, but focusing on TechDraw to try and get that ready to pull in to master.

**Comment by ianrrees** [comment]
Oh, sorry I misread and was thinking C++ include, not cmake include... disregard.

**Comment by vejmarie** [comment]
I think there is a side issue which is coming from the VTK build
within this 
/usr/local/Cellar/vtk/7.0.0_1/lib/cmake/vtk-7.0/VTKTargets.cmake
There is absolute path to 
INTERFACE_LINK_LIBRARIES "vtkCommonCore;/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib;vtksys"

**Comment by bblacey** [comment]
@vejmarie, I believe you just honed in the root cause.  This is probably due to an issue in the vtk formula.

```
      if build.with?("python") && build.without?("python3")
        args << "-DVTK_WRAP_PYTHON=ON"
        # CMake picks up the system"s python dylib, even if we have a brewed one.
        args << "-DPYTHON_LIBRARY='#{`python-config --prefix`.chomp}/lib/libpython2.7.dylib'"
        # Set the prefix for the python bindings to the Cellar
        args << "-DVTK_INSTALL_PYTHON_MODULE_DIR='#{lib}/python2.7/site-packages'"
```

Perhaps python-config should be invoked as #{HOMEBREW_PREFIX}/bin/python-config

**Comment by vejmarie** [comment]
@bblacey do you know who has made this brew ? If yes, can you ask him/her to regenerate it with this as cmake option:

cmake .. -DVTK_Group_Rendering:BOOL=OFF -DVTK_Group_StandAlone:BOOL=ON -DVTK_RENDERING_BACKEND=None

We do not need more, and any reference from Python Framework disappear from the VTKTargets.cmake.

**Comment by vejmarie** [comment]
Hey, it wooorks !
So the issue is coming from the VTK build that we use ;). Good to have found it.
For OCCT the build should be cmake .. -DUSE_VTK:BOOL=OFF

**Comment by vejmarie** [comment]
@bblacey : I think your fix proposale might be working either, as it will look for the right python library. @ickby do you need python interface in VTK (I am pretty sure I am asking the most stupid question)

**Comment by bblacey** [comment]
@vejmarie - great work!  We can pursue a formula change to meet our needs but that will take some time so for now we should just modify the .travis.yml to build vtk from source using the required options and -DCMAKE_INSTALL_PREFIX=$(brew --prefix).  Sound like a plan?  If so, I can pursue the vtk formula changes.

**Comment by ickby** [comment]
Awesome work guys! Vejmaria: we dont need it yet, but in the future it would be nice to support its usage within freecad.

**Comment by bblacey** [comment]
@ickby - sweet.  For now then, just modify the `brew install vtk` to `brew install vtk --without-python` and we should be good to go.

**Comment by ickby** [comment]
Ok, it is on its way! lets cross our fingers...

**Comment by ickby** [comment]
Arghhhh seems we are failing due to a travis oddity when buildig vtk takes too long...

**Comment by vejmarie** [comment]
Aaah bblacey can u prebuild it ? I can make a tar available with object files inside but we have to wait tomorrow i left my office where my single "brewed" Mac stands

**Comment by bblacey** [comment]
I can fix that.  I will add vtk and med-file to the 0.17 ports cache when I get home later today.

**Comment by sasobadovinac** [comment]
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

but adding it to ports cache is better for later

**Comment by ianrrees** [comment]
Looks like there are changes in progress around Homebrew/VTK/Python: https://github.com/Homebrew/homebrew-science/issues/3401

**Comment by bblacey** [comment]
@ianrrees - nice find.  Looks like we can just wait for a vtk fix.  

I just built this PR branch on a clean 10.9 VM using the aforementioned ports changes to mimic the travis build and all unit tests pass so I just pushed a ports-cache commit to my repo that adds med-file and vtk for testing.  If the dev build of the ports-cache passes, I will push the commit to the official FreeCAD ports-cache repo - I will try to propagate the new ports-cache before the end of the day so @ickby's pull requests will pass all checks.

@vejmarie, is SMESH version 5.1.2.2 in Salome 7.7.1 (i.e. are we using the latest SMESH version)?

**Comment by sgrogan** [comment]
I'm having a similar issue trying to making the Win Libpack relocatable to compile ickby's FEM VTKpostprocessing commits to master. I think I add I've removed all absolute paths from the VTK cmake.config stuff, and make it through Cmake. But when compiling I get a linker error to python.lib in the FEM project, that points to a library since deleted on my system, but I believe I compiled VTK against this lib originally. Searching the entire Libpack, and the VTK release directory it's derived from, I can't find the hardcoded path. I'll try to rebuild VTK without the python wrapper.

**Comment by bblacey** [comment]
@ickby & @vejmarie, your great work should be good to go now.  I have updated the FreeCAD 0.17 [ports cache](https://github.com/FreeCAD/FreeCAD-ports-cache) to include the SMESH dependencies, successfully built [icky's SMESH branch](https://travis-ci.org/bblacey/FreeCAD-MacOS-CI/jobs/131290085) in a [forked repo](https://github.com/bblacey/FreeCAD-MacOS-CI/tree/SMESH), and submitted a [pull request](https://github.com/ickby/FreeCAD_sf_master/pull/1) to @ickby's SMESH branch that includes some subtle .travis.yml changes to ensure congruence with the FreeCAD ports-cache.

@ickby, if you merge the  [pull request](https://github.com/ickby/FreeCAD_sf_master/pull/1), rebase against master and push, this PR should build properly.

@vejmarie, if you want to take [your work](https://travis-ci.org/bblacey/FreeCAD-MacOS-CI/jobs/131290085#L7424) for a preview spin, you can [download the build for this PR](https://github.com/bblacey/FreeCAD-MacOS-CI/releases/tag/v0.17) from my repo...

**Comment by bblacey** [comment]
@ickby, there are occasional instances where the travis<->github comm channel flakes...  You may need to poke this pr again because there is no pending job in the [Pull Request Builds](https://travis-ci.org/FreeCAD/FreeCAD/pull_requests).  I noticed that there will be merge conflicts so perhaps this a good opportunity to rebase SMESH with master and push...

**Comment by vejmarie** [comment]
Hi Folks, just a quick note to share that my build on MacOS / Travis worked ;) (I have some issue with the linux one but I know why), I have no doubt that ickby will make work his. I rebase my branch on master before issuing the build and solve the various conflits due to my patches.

**Comment by ickby** [comment]
Yes travis is not invoked if the pull request cannot automatically be merged. I now rebased on current master, lets go for it travis!

**Comment by bblacey** [comment]
@ickby, I took a quick look at the OS X build failure and it appears that there are unresolved externals unless `-DBUILD_FEM_VTK=ON` is set because AppFem.cpp references FemPostFilter.cpp that is only compiled when FEM_VTK is enabled.

While the Linux build appeared to be successful, you can see [evidence of the unresolved externals](https://travis-ci.org/FreeCAD/FreeCAD/jobs/131527117#L8129-L8141) when travis attempts to run the unit tests.

I pulled the SMESH branch from your repo and built it with BUILD_FEM_VTK=ON and BUILD_FEM_NETGEN=ON on OS X 10.9 (same OS as Travis) but the build crashes with a segmentation fault while running the unit tests.

```
testFloatList (Document.DocumentPlatformCases) ... Importing project files......
ok      					(100.0 %)       
testPoints (Document.DocumentPlatformCases) ... Importing project files......
ok      					(100.0 %)       
testVectorList (Document.DocumentPlatformCases) ... Importing project files......
ok      					(100.0 %)       
testDescent (Document.DocumentPropertyCases) ... *** Abort *** an exception was raised, but no catch was found.
	... The exception is:SIGSEGV 'segmentation violation' detected. Address 0
```

Just passing this along in case it helps with further triage and debug.

**Comment by vejmarie** [comment]
Hi, if needed you can have a look to my PR, it is compiling now on both Linux and MacOS (thank bblacey). It is merged with latest master. I am pretty sure your are closed to the finish line now.

**Comment by ickby** [comment]
finaly it compiles on OSX :+1: :+1: :+1:  Don't know why travs fails, but compiling and running of freecad works,so I'm very happy!

**Comment by vejmarie** [comment]
Congrats ! Which version of OSX is working ? (Travis one is quite old)

**Comment by bblacey** [comment]
@ickby - here is what I see in the [Travis Logs](https://travis-ci.org/FreeCAD/FreeCAD/builds/131761283) for the latest build.

The [Linux build failed with compile errors](https://travis-ci.org/FreeCAD/FreeCAD/jobs/131761284#L5857) along the lines of '/usr/include/vtk-6.0/vtkMath.h:1249:11: error: call to 'isinf' is ambiguous'  On OS X, we are using VTK 7 so perhaps they addressed the ambiguity.  I suspect that you can work around this issue with compiler settings or altered #include statements but there is an open [Unbuntu issue](https://github.com/JuliaPCL/PCL.jl/issues/16).  Travis is running Trusty - is that what you use?

That said, the OS X build compiles properly but fails while executing the FEM unit tests with a [segmentation fault](https://travis-ci.org/FreeCAD/FreeCAD/jobs/131761285#L7129).  This is a new issue as your original SMESH branch compiled and passed all unit tests on OS X so probably is related to your FEM_POST work.  I reproduced the problem on OS X and trapped the issue in lldb in hopes that you will know the root cause:

```
testPoints (Document.DocumentPlatformCases) ... Importing project files......
ok      					(100.0 %)       
testVectorList (Document.DocumentPlatformCases) ... Importing project files......
ok      					(100.0 %)       
testDescent (Document.DocumentPropertyCases) ... Process 23816 stopped
* thread #1: tid = 0xa7ca, 0x000000010629cc09 Fem.so`Fem::PropertyPostDataObject::Save(this=0x000000010f6278a0, writer=0x00007fff5fbfae98) const + 281 at PropertyPostDataObject.cpp:189, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010629cc09 Fem.so`Fem::PropertyPostDataObject::Save(this=0x000000010f6278a0, writer=0x00007fff5fbfae98) const + 281 at PropertyPostDataObject.cpp:189
   186 	void PropertyPostDataObject::Save (Base::Writer &writer) const
   187 	{
   188 	    std::string extension;
-> 189 	    switch( m_dataObject->GetDataObjectType() ) {
   190 	        
   191 	        case VTK_POLY_DATA:
   192 	            extension = "vtp";
```

Finally, I get the same results with `FEM_NETGEN=ON` or `-DBUILD_FEM_VTK=ON -DBUILD_FEM_NETGEN=ON`

Let me if you want me to dump any additional information from a debug session.

**Comment by bblacey** [comment]
Just found this - http://www.vtk.org/Bug/view.php?id=14164

Looks like there is an issue when compiling VTK with C++11.  Here is the [VTK commit](http://review.source.kitware.com/gitweb?p=VTK.git;a=commitdiff;h=fffc1de829e2f7ced97413ea5b40672998ca6370;hp=fb32f84fd36f4e4206cc0932bc3dd770345ddbff) from 2013.  Doesn't look like it is in VTK 6 so perhaps that is the problem that @sgrogan is seeing on Windows too.  OS X is using VTK 7.

**Comment by ickby** [comment]
Yes found that too. I for now disable the vtk post processing when using vtk 6.0. For later versions the fix is included I think (sure for vtk 6.2)

**Comment by vejmarie** [comment]
Hi @ickby is there a way I can help you to reach the target ? I really loved to see this PR go through as to progress on the contact from makkemal ;) I think your current disabling fix is too strong as it totally disable VTK which is still needed for SMESH

**Comment by vejmarie** [comment]
I believe you are missing 
find_package(VTK REQUIRED)
within your Fem/App/CMakeList.txt file (at the top)

**Comment by ickby** [comment]
no, the problem was not the findpackage, that is available in the toplevel cmake. The problem was the removal of vtk include file when Postprocessing is not used. I try to remove the manual switch for the VTK postprocessing but encountered a bug with vtk 6.0 (which is on travis) and c++11. So I want to disable it for postprocessing while keeping it for SMESH for VTK <6.2

**Comment by ickby** [comment]
Hah fianlly it works!! only gcc fails due to too long build time, not an issue!

**Comment by bblacey** [comment]
Great to see this PR compile and pass tests...  Well done!  👍 👍 👍

**Comment by vejmarie** [comment]
Hi ickby,
Congrats ! regarding the issue, yes I had seen tht you were disabing VTK within the top level if you had a version < 6.2 as well as FEMPost, that is why I wanted to force it whatever happens within the lower level to define at least the required libraries and include for SMESH. (which was a stupid approach under jetlag)
I have some deb files which works on travis with VTK 7 and OCCT7 if you want to give them a try they are pretty easy to include within your build just have a look to my branch and PR this what I use on Linux. 
vejmarie
ps: Do you believe that you PR will go through the whole process now ?

**Comment by vejmarie** [comment]
Any news guys ? Looks like windows build is still the blocking step. So I am ready to give it a try even if I had didn't built anything on windows since 20 years. I loved to see it moving forward !

**Comment by ickby** [comment]
Fixed the Generator deletion issue and rebased on master

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
