### PR TITLE
Draft: Draft_Rotate fix Base angle behavior

### LINKED ISSUE #12175: [Problem] Base angle doesn't work when using input field in Draft Rotate
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Draft Rotate has the Base angle setting. However, it works only when the tool is used by selecting the points. When the base angle is specified in the input field, it has no effect on rotation. This makes the base angle setting even more confusing.

Forum discussion: https://forum.freecad.org/viewtopic.php?t=69525

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35691 (Git)
Build type: Release
Branch: main
Hash: cc45b58dadae53d7a99be1ed7db25f6c93bb13d5
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Draft

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Roy-043**
Fixes #12175.

The Base angle is subtracted from the Rotation angle (which always starts from the +X axis). The behavior of the command when clicking points in the 3D view remains the same, the values displayed in the task panel are different though.

### CODE REVIEW

**Comment by Roy-043** [comment]
Windows build seems to on the blink ATM.

**Comment by yorikvanhavre** [comment]
Does it make sense? I mean, someone usually wants to rotate something, say, 45 degrees. Now if they start at for ex. 11.583 degrees, they'll need to enter 56.583? This seems counter-intuitive, no?

**Comment by Roy-043** [comment]
If you want to rotate an object 45 degrees, you can just enter zero for the base angle. Or if you are clicking points you can pick a random point constrained to the +X direction from the rotation center.

FWIW this is how the base angle is handled in DwgCAD. But providing a base angle is optional there.

**Comment by yorikvanhavre** [comment]
I still would want to, for ex, pick an alignment (which is not 0) and specify, say, 45° from that...

**Comment by yorikvanhavre** [comment]
I still think this is a wrong approach, and is changing a paradigm without a real reason...
I think what needs to be fixed is the wrong behaviour described in #12175 , but not change the modelling paradigm.

I can work on an alternate fix if you prefer @Roy-043

**Comment by Roy-043** [comment]
Hmm, I think there is a real reason for this proposal, and also some logic involved. But maybe I my DwgCAD background has closed my eyes to alternative options. So by all means, make a proposal.

**Pull request closed without merging**
