### PR TITLE
Added color prefs to sketcher create commands

### PR DESCRIPTION
**Pull request by jcbinf**
Create geometry commands in sketcher now have configurable crosshair color
and editCurve color.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@jcbinf can you open a freecad forum thread to discuss this PR and also display what it can do?

**Comment by jcbinf** [comment]
Done: development pull requests

Jeff

> @jcbinf can you open a freecad forum thread to discuss this PR and also
> display what it can do?
>


510-745-0408

**Comment by luzpaz** [comment]
https://forum.freecadweb.org/viewtopic.php?f=17&t=25391

**Comment by wwmayer** [comment]
Merged & reworked to avoid code duplication

**Pull request closed without merging**
