### PR TITLE
[Sketcher][Bugfix] Fix crash when applying 'Constrain internal alignment' on contraints

### PR DESCRIPTION
**Pull request by 0penBrain**
fixes #4790

https://forum.freecadweb.org/viewtopic.php?f=3&t=63909

### CODE REVIEW

**Comment by luzpaz** [comment]
Did you mean `constrain` instead of `contrain` in the commit title?

**Comment by 0penBrain** [comment]
@luzpaz yes. Should not prevent code to work though. 🤣

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5190">pipeline status</a> for feature branch [PR_5190](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5190). Pipeline [413453963](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/413453963) was triggered at [f965015](https://github.com/FreeCAD/FreeCAD/pull/5190/commits/f96501509cac11ade1e271eb97a21d5f3acf4831). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks. Merging it now and backporting it as well.

**Pull request merged**
