### PR TITLE
PATH DressupTrochoidalProfiling

### PR DESCRIPTION
**Pull request by IchGucksLive**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x ] Branch rebased on latest master `git pull --rebase upstream master`
- [x ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

A Sadly needed Feather for a Hobby Mill is Troichodal milling,as it reduces workforce for machines to a min 
Here is a Dressup for Path  Profiling to get around TILL the BASE operation got a full Troichodal 
as on youtube many request this i decided to Ones More file this Pull Request to get it in MY Youtube on Freecad and CNC is here
https://www.youtube.com/channel/UCmwhCL92ZQRSVqFe3jGwJSQ/videos
Workflow it needs the OffsetExtra  from the Base operation to get Troichodal wide
and it only starts on Straight in Moves Error filed on Circle in 

Woudt be good to get it IF not not a Problem long time to go for 0,18

Thanks 
@sliptonic  @wwmayer  @realthunder 
---

### CODE REVIEW

**Comment by sliptonic** [comment]
Please start a discussion thread on the forum so you can get testers and feedback.

**Comment by yorikvanhavre** [comment]
In any case, this PR doesn't modify existing functionality in any way, so I guess it can be safely merged.. Any objection @sliptonic ?

**Comment by sliptonic** [comment]
I don't object to the code but I haven't looked at it. I **do** object, however, to the process.  

Once this (or any code) is merged, it BECOMES existing functionality and requires support.  But IchGucksLive is unwilling to participate on the forum so he cannot get that feedback or contribute to that discussion.  Since he can't/won't communicate with the broader community, all requests for support both from him and from others necessarily fall on other developers.  This puts those developers into an unfair position - either ignore the issue and allow FreeCAD to look bad, or solve it themselves.  

Developers occasionally leave the community and support falls to the everyone else but that is NOT what's happening here.  IchGucksLive wants to stay involved and will raise issues if the code he submits doesn't continue to function.  But he won't use the community tools and standards.  He will use private emails, IRC direct messages, or other means to reach individuals.  Once again, this is unfair and inefficient.

**Comment by IchGucksLive** [comment]
its not needed and it is faulty untested

**Pull request closed without merging**
