### PR TITLE
[PartDesign] Allow single (viewport) click for mapping feature selection

### PR DESCRIPTION
**Pull request by 0penBrain**
Parameter 'singleClickFeatureSelect' can be used to enable/disable

https://forum.freecadweb.org/viewtopic.php?f=19&t=65020

Set as Draft time it is discussed

### CODE REVIEW

**Comment by wwmayer** [comment]
There is an odd behaviour. When you select a plane in the dialog and then move the mouse into the viewport and hover over any plane the selection will be immediately accepted.

So, you should protect the new code block with:
`if (msg.Type == Gui::SelectionChanges::AddSelection) {` 

Another small thing: following the advises of "Clean code" gurus the query of the parameter group should be moved into a separate function, e.g.:
`
bool TaskFeaturePick::isSingleSelectionEnabled() const
{
    ParameterGrp::handle hGrp = App::GetApplication().GetUserParameter().GetGroup("BaseApp")
                                                  ->GetGroup("Preferences")->GetGroup("Selection");
    return hGrp->GetBool("singleClickFeatureSelect", true);
}
`

**Comment by 0penBrain** [comment]
@wwmayer Thx for review. Will fix this later on.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5408">pipeline status</a> for feature branch [PR_5408](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5408). Pipeline [454040205](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/454040205) was triggered at [6f927c2](https://github.com/FreeCAD/FreeCAD/pull/5408/commits/6f927c2cf96ab9d13c63f2c2377cd0c8c3656e4e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Merged as e3c0a43797

**Pull request closed without merging**
