### PR TITLE
[TD] icon name uniformity (cont.)

### PR DESCRIPTION
**Pull request by luzpaz**
`WeldSymbol`, `PageDefault`, `PageTemplate`, `Symbol`, `ExportPageSVG`. `ExportPageDXF`, and `Tile`

### CODE REVIEW

**Comment by luzpaz** [comment]
//cc @bitacovir juet letting you know I'm working on this, is that alright?

**Comment by bitacovir** [comment]
Great work!

**Comment by luzpaz** [comment]
@bitacovir Would you do me a favor and convert `src/Mod/TechDraw/Gui/Resources/icons/techdraw-lock.png` to SVG please?

**Comment by bitacovir** [comment]
> @bitacovir Would you do me a favor and convert `src/Mod/TechDraw/Gui/Resources/icons/techdraw-lock.png` to SVG please?

Sure! Here you are. It is saved as plain SVG file


[TechDraw_Lock.zip](https://github.com/FreeCAD/FreeCAD/files/6287938/TechDraw_Lock.zip)

**Comment by luzpaz** [comment]
@bitacovir can you also do the same for `src/Mod/TechDraw/Gui/Resources/icons/cursor-balloon.png`, please? :blush:

**Comment by bitacovir** [comment]
> @bitacovir can you also do the same for `src/Mod/TechDraw/Gui/Resources/icons/cursor-balloon.png`, please? 😊
@luzpaz  We already have a SVG file for that icon: https://wiki.freecadweb.org/File:TechDraw_Balloon.svg

**Comment by luzpaz** [comment]
Ah, @bitacovir nice catch. Looks like someone missed removing the `.png` and references to it in the source. Made the change in 839cd41. Thanks

**Comment by luzpaz** [comment]
There is still more work to do but this PR is getting too big. I think this is ready for merge and we can submit another PR soon.

**Comment by luzpaz** [comment]
@wwmayer this PR should be ready for merge

**Comment by luzpaz** [comment]
@bitacovir there is still some work left to do in TD. Some TD functions need to be renamed or vice-versa some TD image files need to be renamed. Where can we discuss this? I can't find the thread on the wiki.

**Comment by bitacovir** [comment]
Hi. I don't think there is a thread. Can you create one in UX/UI forum? You know the problems with icons in this workbench. There we can talk about what must be done.

**Comment by luzpaz** [comment]
@bitacovir done. see https://forum.freecadweb.org/viewtopic.php?f=34&t=58401

**Pull request merged**
