### PR TITLE
Path: Restore PocketMode reference list for PocketShape [Bug]

### PR DESCRIPTION
**Pull request by Russ4262**
Restore reference list modified in PR #6649 .
Forum discussion at [Bug: PocketShape - ZigZagOffset is now Spiral](https://forum.freecadweb.org/viewtopic.php?f=15&t=67677).

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6700">pipeline status</a> for feature branch [PR_6700](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6700). Pipeline [507423649](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/507423649) was triggered at [f7ce854](https://github.com/FreeCAD/FreeCAD/pull/6700/commits/f7ce854d82f65ad1e02a5e1d49bc80cb1a342403). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
The point of #6649 was specifically to remove these patterns.  We still want to do that.  We just need to make the pocketmode translation correct.  
The PathArea pocketmode parameter is 0=None,1=ZigZag,2=Offset,3=Spiral,4=ZigZagOffset,5=Line,6=Grid,7=Triangle.  
It was determining the value by list position.  My naive removal  of the values from the list caused the problem

**Comment by Russ4262** [comment]
Yes, per conversation with MLampert, my understanding is to remove Spiral, but keep Triangle (or remove both).  #6649 Achieved that goal, except we need to restore this reference list based on the existing index lookup for `PocketMode` that directly follows the list. 

If we do not want the word `Spiral` to appear or be known, simply replace it with an empty string in the list there, and/or place a comment stating "Do not use for error sake."  Otherwise, is the intention to go edit the C++ code to remove the option of Spiral there as well?  If so, is the intention to also delete the C++ code related to Spiral path generation also?  I do not follow.

The restoration of this list (per this PR) does not make Spiral available in Path without writing a manual script to access it.

 Respectfully, am I missing something?

**Comment by sliptonic** [comment]
I think both spiral and triangle can go away.  My brief survey showed nobody using either of those and spiral being consistently buggy.
Relying on list position seems brittle and hack-y to me.  Probably the right way to do this is to make a PocketMode enumeration that maps the values to the PathArea numbers so we don't rely on list position at all.
If you want to work on this, let me know.  Otherwise I'll work on it today.

**Comment by Russ4262** [comment]
I do not plan to mess with it. It has been considered stable for quite a while. Thanks for reviewing. If you do make changes, I can just close this PR. No problem.

**Comment by sliptonic** [comment]
Fixed in other pr

**Comment by J-Dunn** [comment]
It was far less buggy than the Sim IMO.  

What git command can I issue to roll back to where this was still in the code, and what file do I need to look at ?

**Comment by sliptonic** [comment]
Teaching git is beyond what I can do in a closed PR comment.  Find a commit # earlier than the change.  You can git checkout the sha.

The fix is non-trivial because the linking is not done in python.  It's coming out of PathArea itself.  That's why the feature has gotten no attention for more than five years.  It requires C++ expertise to resolve it and RealThunder isn't working on it.

IMHO, a new python-based spiral clearing algo should be developed.  Use PathArea offset PocketMode to get back a set of wires, then use python to reprocess them into one or more spirals.

**Comment by J-Dunn** [comment]
It seems this was PR ( incorrectly ) removing the links to spiral clearance options. 
https://github.com/FreeCAD/FreeCAD/pull/6649/commits/5496accd5fbd0afcd86ac8c0222719b397e6824b

How do I get a SHA from that ?

**Comment by sliptonic** [comment]
That IS a sha.  You can check it out.  But you need a sha prior to that point.  Maybe look into something like git kraken  or another gui git tool.

**Comment by J-Dunn** [comment]
Thanks. The mods were trivial so I just did _git checkout 5496acc_  then edited them back in. 
Just spend last 2 days picking through the mess in libarea !   Some fun there. 
Reused filenames, reused variable names, same method names used in at least 4 difference classes, lots of unused code. I'm not surprised no one's been brave enough to fix it ! 
I'm getting some feel for how it all works, so hopefully I'll be able to plug a few holes.

**Comment by sliptonic** [comment]
You can check the git history of any file.  You can even investigate that through github.  Near-term changes are unlikely, both because we're in feature freeze and because the code is rarely touched.  Unlikely but not guaranteed.

**Pull request closed without merging**
