### PR TITLE
Update iso10642.json

### PR DESCRIPTION
**Pull request by czinehuba**
Update ISO10642 with M2 and M2.5 sizes

### CODE REVIEW

**Comment by chennes** [comment]
Thanks for the PR -- I don't have access to the updated 2019 version of this standard, I presume that's the document that these dimensions are coming from?

**Comment by czinehuba** [comment]
Hi. Me neither unfortunately,  but I was using some M2 & M2.5 fasteners lately from this company I looked at their specs. The values I used matches the fine threaded ISO10642 as the countersunk head wouldn't change. I wanted to add it the standard threads as well just in case there is a need for 3d printing holes, as it is in my case.

https://www.westfieldfasteners.co.uk/Standards/ScrewBolt_SHCsk_M.pdf

Indeed some documentation stops at M3. I tried to look for more updated info, had no luck. Apart from this section in this document that said they've added M2 and M2.5 to the specs.

https://webstore.ansi.org/preview-pages/ISO/preview_ISO+10642-2019.pdf

**Comment by quarnster** [comment]
There's a table at: https://www.globalfastener.com/standards/detail.php?sid=MjAzMDI=

Previous entries in this json file appear to use the rounded theoretical max number.

Also, separate from this PR, isn't M5 wrong? Aforementioned link, as well as the [2004 standard preview](https://www.google.com/search?q=ISO+10642%3A2004+filetype%3Apdf&client=ubuntu-sn&sca_esv=579945731&bih=803&biw=1600&hl=sv&sxsrf=AM9HkKnWZqwfiTq9KiiI8NaDKtuSTShnsQ%3A1699312008221&ei=iHFJZcKSDc6rwPAP_r628AQ&udm=&ved=0ahUKEwjC9vLEvrCCAxXOFRAIHX6fDU4Q4dUDCA8&uact=5&oq=ISO+10642%3A2004+filetype%3Apdf&gs_lp=Egxnd3Mtd2l6LXNlcnAiG0lTTyAxMDY0MjoyMDA0IGZpbGV0eXBlOnBkZkjDDVDvA1jtCXABeAGQAQCYAZgCoAGzBaoBBTEuMS4yuAEDyAEA-AEBwgIKEAAYRxjWBBiwA-IDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp) lists it as 11.2, not 12.2

**Comment by czinehuba** [comment]
Yes. They are the theoretical max values rounded. I've adjusted them to match. Also the M5 was incorrect. Must have been a typo before.

**Pull request merged**
