### PR TITLE
Reuse Std_Delete shortcut instead of hardcoding Delete

### PR DESCRIPTION
**Pull request by hyarion**
This pull request is not finished as I haven't tested all code paths yet, but I would like to get some feedback on my suggested way of fixing the issue.

--- 

This is a fix for a bug reported in a comment of another issue here: https://github.com/FreeCAD/FreeCAD/issues/9639#issuecomment-2336005447

I haven't seen this issue reported separately, so nothing to close.

While it is possible to assign any shortcut to the Std_Delete command, that command isn't used in these places.
From a users point of view, I think it is expected that these uses the same shortcut.

---

I changed the all instances where an action was hardcoded to delete, but I haven't been able to find all places where they are used yet.

The marked checkboxes in this list has been tested:
- [ ] src/Mod/Fem/Gui/TaskFemConstraint.cpp
- [x] src/Mod/Material/Gui/Array2D.cpp
- [x] src/Mod/Material/Gui/MaterialSave.cpp
- [X] src/Mod/PartDesign/Gui/TaskBooleanParameters.cpp
- [X] src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
- [ ] src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
- [x] src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- [x] src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- [x] src/Mod/PartDesign/Gui/TaskShapeBinder.cpp
- [ ] src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
- [ ] src/Mod/Surface/Gui/TaskSections.cpp

### CODE REVIEW

**Comment by chennes** [comment]
In my opinion this is the right solution. @FreeCAD/design-working-group any comments?

**Comment by hyarion** [comment]
I split up the change set to one commit per file. I'm thinking that it will be easier for you if you want to cherry pick only a couple of changes (and if you want all of them, then it's easy to squash it).

All changes are independent of each other.

**Comment by chennes** [comment]
@hyarion do you still have more you intend to do as part of this PR before it gets merged?

**Comment by hyarion** [comment]
@chennes I have only been able to verify the once that are checked. To check the rest I need some help as I'm having trouble finding where they are used in the ui.

Maybe the easiest way forward is to remove the unchecked files and do them later.

**Comment by chennes** [comment]
I'll ask for volunteers/suggestions at this morning's review meeting.

**Comment by chennes** [comment]
This needs backport to 1.0, pending some additional testing on the weekly build.

**Comment by adrianinsaval** [comment]
It'll be good to have instrucitons on what we need to test

**Comment by hyarion** [comment]
> It'll be good to have instrucitons on what we need to test

1. change the shortcut for Std_Delete to something else than Del.
2. go to the ui item where the change was
3. try and see if the key works

If it doesn't work, please continue with:
1. change the shortcut back to Del
2. go to the ui item and see if that works

It would also be interesting to know if it worked at all before these change set.

**Comment by luzpaz** [comment]
Lets follow-up here and make sure the remaining functionality is also tested on macOS to put this UX issue to bed. 

- [ ] src/Mod/Fem/Gui/TaskFemConstraint.cpp
- [ ] src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
- [ ] src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
- [ ] src/Mod/Surface/Gui/TaskSections.cpp

Any macOS volunteers using latest weekly build able to test delete key functionality in these workbenches ?

**Comment by hyarion** [comment]
> Any macOS volunteers using latest weekly build able to test delete key functionality in these workbenches ?

These changes doesn't depend on macos, as long as you change the shortcut for Std_Delete you should be able to test it.

**Comment by maxwxyz** [comment]
@JohnOCFII would you be able to test this on the weekly? This still needs to be backported to 1.0

**Comment by JohnOCFII** [comment]
> @JohnOCFII would you be able to test this on the weekly? This still needs to be backported to 1.0

Maybe?  The Extrude data entry fields properly accept the Mac delete key now -- not sure how to find the other specific areas listed.

**Comment by maxwxyz** [comment]
@chennes IMO this can be backported too now.

**Comment by chennes** [comment]
OK, I've backported it.

**Pull request merged**
