### PR TITLE
Sketcher: Offset & tranforms: enable external geos input.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Enable offset tool and transform tools to use external geometries as input

Fix https://github.com/FreeCAD/FreeCAD/issues/12461
Fix https://github.com/FreeCAD/FreeCAD/issues/17616

### CODE REVIEW

**Comment by pierreporte** [comment]
Would the nature of offset geometry be the same as external, normal, or construction? #10043 is still open…

**Comment by PaddleStroke** [comment]
Currently the geos are created as construction.
Should it be as normal?

**Comment by pierreporte** [comment]
In the current state, it doesn’t matter as long as the status of new geometry can be changed. In the future, when #10043 is fixed, I think that it should match the status of the original geometry.

**Comment by FEA-eng** [comment]
Compiled and tested, works as expected. There's just one CI failure on Mac.

**Review by FEA-eng — APPROVED** [review]

**Pull request merged**
