### PR TITLE
[0.20] Tools: updatecrowdin.py rewrite to support new api

### PR DESCRIPTION
**Pull request by hyarion**
Crowdin has depreciated their old api and will shut it down completely in december 2021.

What's new:
 * rewritten in Python 3 (drops support for discontinued Python 2)
 * uses Crowdin's api v2
 * runs on vanilla Python 3, (no external modules)
 * automatically adds new translation from the src directory
 * supports api token to be specified in an environment variable
   (Makes GitHub integration easier in the future)
 * requires project id to be explicitly set with an environment variable
   (Makes testing safer)

The api token can be set either in ~/.crowdin-freecad-token similar to
how the old api key was set, or by specifying it in an environment
variable. The later has been added to make it easier with GitHub-Crowdin
integration in the future.

The requirement to explicitly set CROWDIN_PROJECT_ID has been introduced
to avoid accidentally using the main Crowdin project while testing the
script.

The script has been tested on Python versions 3.7, 3.8 and 3.9.

Co-authored-by: Mattias Pierre <github@mattiaspierre.com>

---

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by hyarion** [comment]
I can add people to my crowdin test project https://crowdin.com/project/just-another-test if someone would want to test this.

@yorikvanhavre ping :)

**Review by yorikvanhavre — CHANGES_REQUESTED** [review]
This script updates all ts files found in the source, not only the "source" ts files but also the translated ts files. While this doesn't harm anything, I'd prefer to update only the source files I think... This would make commits clearer, easier to differentiate later on... I guess it would just be a matter to strip out all ts files with a "_" character in it. How does that sound?
Other thing I wanted to do, if you are interested, is to add a fifth argument, for ex. "install", that would execute the updatefromcrowdin.py script. But that can be a matter for another PR too.

**Comment by hyarion** [comment]
> This script updates all ts files found in the source, not only the "source" ts files but also the translated ts files. While this doesn't harm anything, I'd prefer to update only the source files I think... This would make commits clearer, easier to differentiate later on... I guess it would just be a matter to strip out all ts files with a "_" character in it. How does that sound?

Strange, I've tested this and it works for me. @yorikvanhavre which version of python did you test it with? (If you haven't tested it, would you like to get access to a test project for safe testing?)

This should already handled in [updatecrowdin@ Line 231 to 238](https://github.com/FreeCAD/FreeCAD/pull/4536/files#diff-1d7e7553d60210967422f16704fe3809ca79b5b231aa2507117e5673e3ced0fcR231-R238)
It iterates over all files and checks if another filename (without file extension) is a subset of the current one. If there is, then remove the current one. Example: `Arch` is a subset of `Arch_en`so remove `Arch_en.ts`

> Other thing I wanted to do, if you are interested, is to add a fifth argument, for ex. "install", that would execute the updatefromcrowdin.py script. But that can be a matter for another PR too.

Sure, but I think it might be better to add it afterwards.

**Review by yorikvanhavre — APPROVED** [review]

**Comment by yorikvanhavre** [comment]
OOh sorry I didn't read the code correclty. Then yeah, everythingis fine!
Just scheduling this for 0.20 so we don't hinder ongoing 0.19 hotfixes.

**Comment by luzpaz** [comment]
> I can add people to my crowdin test project https://crowdin.com/project/just-another-test if someone would want to test this.

Forgot to ask, but please add `luzpaz` to this repo to test. thansk!

**Comment by luzpaz** [comment]
Can we merge this?

**Comment by luzpaz** [comment]
After this merge, @yorikvanhavre we need to create a test crowdin repo and add @hyarion as an admin to do further testing on improving the crowdin scripting

**Pull request merged**
