### PR TITLE
Gui: Add Mod info to copied About string

### PR DESCRIPTION
**Pull request by chennes**
Adds some Mod installation info to the string you get when you click "Copy to clipboard" in the About FreeCAD dialog. Version info is pulled from package.xml, so is only available for Addons that provide that metadata file. I tried to tighten up the display of the other version info so this didn't get too long, but I still think the major downside here is that if you have a lot of addons it's going to get lengthy. You can always edit when you paste it, of course.

Fixes https://github.com/FreeCAD/FreeCAD-addons/issues/199

### CODE REVIEW

**Comment by chennes** [comment]
Here's some output borrowed from @kisolre:
```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.20.27517 +1 (Git)
Build type: Release
Branch: (HEAD detached at chennes/aboutFreeCADAddonInfo)
Hash: 4ab8c724a2daae18a77057f847f744ebb3e61836
Python 3.8.8, Qt 5.15.2, Coin 4.0.1, OCC 7.5.3
Locale: Bulgarian/Bulgaria (bg_BG)
Installed mods: 
  * .stfolder
  * .stignore
  * 3DfindIT 1.2.0
  * A2plus 0.4.54b
  * AirPlaneDesign 0.4.0
  * ArchTextures
  * Assembly4 0.11.8
  * Autoload
  * BIM 2021.12.0
  * BOLTSFC
  * CfdOF 1.9.6
  * CubeMenu
  * CurvedShapes 1.0.0
  * Curves 0.3.0
  * CycloidGearBox
  * Defeaturing
  * Design456
  * DesignSPHysics 0.6.1-2201-31-01
  * dodo
  * DynamicData 2.32.0
  * ExplodedAssembly
  * ExtMan
  * fasteners
  * FCGear
  * FCPDWorkbench 0.2.0
  * FEM_FrontISTR
  * frame
  * freecad.xray
  * FreeCAD_ExtMan
  * FreeCAD_mcm_addon
  * GDT
  * InvGears 0.1.2
  * kicadStepUpMod 10.10.4
  * Launcher
  * Manipulator
  * Mechatronic
  * MeshRemodel 1.8918.0
  * MnesarcoUtils
  * Nikra-DAP
  * nurbs
  * OpticsWorkbench 1.0.7
  * ose-piping
  * parts_library
  * Plot
  * Pyramids-and-Polyhedrons
  * Reinforcement
  * Render 2022.1.0
  * Rocket 2.2.2
  * SearchBar
  * SelectorToolbar
  * sheetmetal 0.2.49
  * Ship
  * Silk
  * SlopedPlanesMacro
  * StemfieWB
  * symbols_library
  * ThreadProfile 1.80.0
  * toSketch
  * workfeature
  * ```

**Comment by kisolre** [comment]
@luzpaz two columns in what way? As this is mainly pasted to the forum does it support two columns?
I suggested default Code tags added to reduce vertical span.

**Comment by luzpaz** [comment]
Something like:  
```
OS: "Manjaro Linux"		Word size of OS: 64-bit
Version: 0.16.Unknown		Word size of FreeCAD: 64-bit
Build type: Release
Python version: 2.7.13		Netgen version: x.x.x
Qt version: 4.8.7		Matplotlib version: x.x.x
Coin version: 3.1.3		KDL version: x.x.x
OCC version: 6.9.1		Med version: x.x.x
VTK version: 7.1.0		Smesh version: x.x.x
```

**Comment by chennes** [comment]
I think even if we decide against the mod listing, we could do something like
```
OS: Windows 8.1 Version 6.3 (Build 9600)
Version: 0.20.27517 +1 (Git), 4ab8c724a, Release, 64-bit
Branch: (HEAD detached at chennes/aboutFreeCADAddonInfo)
Python 3.8.8, Qt 5.15.2, Coin 4.0.1, OCC 7.5.3
```

Making the mod list multi-column is not a horrifying amount of work, but it's quite a lot more code, for something pretty trivial. On the forums someone suggested having a second button that copied "Auxiliary information" or something like that.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6362">pipeline status</a> for feature branch [PR_6362](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6362). Pipeline [470442981](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/470442981) was triggered at [4ab8c72](https://github.com/FreeCAD/FreeCAD/pull/6362/commits/4ab8c724a2daae18a77057f847f744ebb3e61836). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Whatever is easy.. We can tweak things later.

**Comment by yorikvanhavre** [comment]
I'd advocate against the two colums at it makes automatic parsing more difficult

**Comment by luzpaz** [comment]
@yorikvanhavre automatic parsing, like with regex? I don't follow how it would be difficult. Wouln't the delimerterbe a tab (`\t`) character? Should be easy peasy

**Pull request merged**
