### PR TITLE
[PartDesign] Fix and expose ViewProvider strings to translation

### PR DESCRIPTION
**Pull request by Kuzma30**
https://github.com/FreeCAD/FreeCAD-translations/issues/24

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6822">pipeline status</a> for feature branch [PR_6822](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6822). Pipeline [529533072](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/529533072) was triggered at [fb58fd8](https://github.com/FreeCAD/FreeCAD/pull/6822/commits/fb58fd825367bb35f9fbe75a3d89fa9f48ec2249). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Kuzma30** [comment]
what command I need after git commit --amend? 
I try git push with error.

**Comment by noahwilliamsson** [comment]
@Kuzma30 If you rewrite the Git history with e.g. `git commit --amend`, then you need to force push your branch with:

```
git push --force
```

**Comment by Kuzma30** [comment]
Done

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6822">pipeline status</a> for feature branch [PR_6822](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6822). Pipeline [529837080](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/529837080) was triggered at [0fca61b](https://github.com/FreeCAD/FreeCAD/pull/6822/commits/0fca61b07ac63c536acfc68780f2ba8447a6d750). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Kuzma30** [comment]
@donovaly This PR is also ready.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6822">pipeline status</a> for feature branch [PR_6822](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6822). Pipeline [531610696](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/531610696) was triggered at [b2334f8](https://github.com/FreeCAD/FreeCAD/pull/6822/commits/b2334f85740bcd80ef421af59de3109ad5c3d5c2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
I cannot test at the moment. @wwmayer , can you please have a look if everything is OK so far?

**Comment by Kuzma30** [comment]
@donovaly or @wwmayer please review this PR.

**Comment by Kuzma30** [comment]
Anybody can review this PR?

**Review by chennes — APPROVED** [review]
I think this looks good -- the code compiles and runs without issue. Obviously the translations themselves won't be fixed until we do a cycle with CrowdIn, but my plan is to merge this shortly since it is a reasonable solution to the problem and it would be good if we fixed this for the 0.20 release.

**Pull request merged**
