### PR TITLE
Assembly: Fix explosion view group deletion issue.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Make ExplodedView: a group extension. So that we don't mimick group. Fixing the delete exploded view group issue. Fixes  https://github.com/FreeCAD/FreeCAD/issues/17902

### CODE REVIEW

**Comment by chennes** [comment]
@PaddleStroke is this safe to back port to the 1.0 branch?

**Comment by PaddleStroke** [comment]
I'm not entirely sure. This PR adds a group extension to the exploded view objects, which is what advised Werner so it should be fine. It's just that I do not know the implications of doing this. It appears to do nothing beyond fixing the bug.
Considering the little gravity of the bug I wouldn't backport it to avoid any potential unforseen issue.

**Comment by PaddleStroke** [comment]
Perhaps merge it and give it some time for people to test

**Comment by chennes** [comment]
If we backport this, we'll also need #18644

**Comment by adrianinsaval** [comment]
@PaddleStroke is this ok for backport or has it introduced any issue?

**Comment by PaddleStroke** [comment]
Yes it's ok

**Comment by adrianinsaval** [comment]
backported b8b02f5f4624636dcf9e062204e4ac606a991709 and also werner's fix c75fe83a4ed0fbf033dec411c512aab51c0927a0

**Pull request merged**
