### PR TITLE
Fix error caused by insufficient rights to create symlink under Windo…

### PR DESCRIPTION
**Pull request by wschildbach**
…ws 10

On Windows 10, symlink creation is not allowed unless the process runs with elevated rights. 

As per https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#joC5tFKhdXs2gGml.97, starting with Windows 10 Insiders build 14972, symlinks can be created without needing to elevate the console as administrator.

To use this functionality, 0x2 needs to be set in the flags argument for the CreateSymbolicLinkW() call. See also https://github.com/FreeCAD/FreeCAD-addons/commit/e8838474846383caff216385c5a1ddf2c6a8774d .

### CODE REVIEW

**Comment by wschildbach** [comment]
Note that this still fails unless the user has [activated developer mode](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development). This should probably go into notes somewhere, or be printed when the symlink creation fails.

**Comment by sgrogan** [comment]
What does this do on Win < 10?
After this Flag is set is it persistent?

**Comment by wschildbach** [comment]
I only have Win10 machines so can't test the code on older Windows machines. As per the linked blog post, symlink creation has never worked under windows (unless you run under admin priviledges) so I tend to think that it cannot get any worse, even if the call did now fail under older versions.

I don't understand what you mean with whether the flag is persistent. The flag in the source code has scope inside the subroutine so can not be persistent. Developer mode, OTOH, is a global setting in Windows. I don't think that the symlinks have any special "flag" set.

**Comment by sgrogan** [comment]
> I don't understand what you mean with whether the flag is persistent.

+            # set the SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE flag
+            # (see https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#joC5tFKhdXs2gGml.97)
+            flags += 2
+

**Comment by wschildbach** [comment]
My understanding is that the flag used in the function call does not make the link special. It is just telling the symlink call that it is OK to execute even when the process does not run under admin rights. So, I don't how it can be persistent.

Why did you close the pull request? Do you believe this is not a bug, or that this is not a solution for it?

**Comment by sgrogan** [comment]
I did not close the pull request,
I appreciate your answers, I'm only a packager not a developer, I am paranoid about opening backdoors.

**Comment by yorikvanhavre** [comment]
My understanding is that symlinks are in any case problematic on windows. A person still needs to have developer mode enabled, which is likely not the case for most people. While this change seems safe enough, it is just a different argument to pass to the Windows API function, and it is meant to be used like this, it will still likely fail for most users.

So I propose the following:

1) check if, in case Developer mode is disabled, line 85 ( if csl(link_name, source, flags) == 0: ) is still correct (that is, if it still returns 0 in case of failing) - @wschildbach can you test that? I don't have a win10 machine.
2) instead of the next line (raise ctypes.WinError()) we add something like this:
```
print("symlinks unavailable on this system. Copying maxro instead...")
shutil.copy(source,link_name)
```

After that we will still need to update the install code around line 786 (unindent line 786->793 twice) so the macro symlinking/copying is executed not only on installing but on updating too, because in case the macro gets copied, it will need to be copied again...

But then, inside the symlink function, we must perform the copying again in case it is not a symlink. Not sure yet how to do that...

**Comment by wschildbach** [comment]
OK, I can confirm for now that csl() still returns 0, if not running under developer mode.

Maybe we need to sit on the rest of the fixes for a bit and think. I am halfway torn to suggest we should be doing away with the symlink functionality altogether -- it makes the code complicated, with not much gain (the way I see it anyways).

Or, alternatively, invest in getting gitpython to work everywhere -- though that might entail some lengthy philosophical discussions around licenses...

**Comment by sgrogan** [comment]
gitpython doen't solve the symlink problem. It;s the packaging of the specific packages.
https://forum.freecadweb.org/viewtopic.php?f=10&t=27213
https://forum.freecadweb.org/viewtopic.php?f=9&t=27195#p217853

If on win a symlink requires elevated privileges, maybe you must run as admin. Not much different than sudo on Linux. The packages should remove this hurdle?

 @wschildbach I see I did close the pull request inadvertently, sorry about that. Thanks for your efforts in this issue.

**Comment by yorikvanhavre** [comment]
We could get rid of the symlink, if we add code to replace the macro at every update, but it's convenient. You keep the macro in its git-managed directory, symlink it, and it' s updated automatically, nothing to do. And on Unix-based systems, symlinks are a VERY normal thing to use. I'd be more in favor to keep using it and add a special case for windows.

**Comment by yorikvanhavre** [comment]
In any case there seem to be nothing that prevent this PR, so I'm merging it already..

**Pull request closed without merging**
