### PR TITLE
Remove occ<7.3 references

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by donovaly** [comment]
@chennes , @yorikvanhavre , @wwmayer , what is your opinion? Should be purposely remove traces of OCC < 7.3 before the release or afterwards?

**Comment by luzpaz** [comment]
There's no rush, right? FWIW, i think it's best to postpone till post-release.

**Comment by chennes** [comment]
This is valuable cleanup -- anything that makes the code short and less complex is good. But as @luzpaz suggests, there's no reason to rush this into 0.20. I propose merging it after we release.

**Comment by mosfet80** [comment]
I have read the minimum requirements at the following link https://wiki.freecadweb.org/0.20_Development_Cycle#:~:text=Minimum%20supported%20library%20versions,Clang%206.0
The minimum supported library versions for freecad 0.20 are OCC v 7.3.
I thought about removing the useless piece of code.
In replying to you, I noticed that the FreeCAD / cMake / FindOpenCasCade.cmake file still reports occ 6.7.3 as a minimum version

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6983">pipeline status</a> for feature branch [PR_6983](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6983). Pipeline [559062777](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/559062777) was triggered at [238c01e](https://github.com/FreeCAD/FreeCAD/pull/6983/commits/238c01e4fb004bba2774b9675eba209e76d4858b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> there's no reason to rush this into 0.20. I propose merging it after we release.

Thanks, so for 0.21.

**Pull request closed without merging**
