### PR TITLE
Fem: Add local refinement and second order linear for Netgen meshing

### PR DESCRIPTION
**Pull request by marioalexis84**
Both features work with the same workflow as in Gmsh meshing.

@FEA-eng

### CODE REVIEW

**Comment by maxwxyz** [comment]
@FEA-eng 1.0?

**Comment by FEA-eng** [comment]
> @FEA-eng 1.0?

It adds Netgen support for options that previously only Gmsh supported so I guess it's more like post 1.0.

**Comment by marioalexis84** [comment]
If this is post 1.0, I will edit https://github.com/FreeCAD/FreeCAD/pull/17197 so that it does not depend on this pull request.

**Comment by FEA-eng** [comment]
> If this is post 1.0, I will edit #17197 so that it does not depend on this pull request.

I mean, I'd love to have it in 1.0 but it may not be in line with feature freeze rules. The line is sometimes rather thin though. Here we are talking about a limitation, not a typical bug.

**Comment by marioalexis84** [comment]
No problem, I'll rebase the branch when the other PR is merged.

**Review by FEA-eng — APPROVED** [review]

**Pull request merged**
