### PR TITLE
TechDraw: Introduce snapping

### PR DESCRIPTION
**Pull request by PaddleStroke**
1 - Enable snapping views to align them vertically/horizontally.

When you drag a view, if you get near aligning them, it will snap them into position.

Making the tool TechDraw_ExtensionPositionSectionView obsolete.
Removes the tool TechDraw_ExtensionPositionSectionView from toolbar.

2 - Enable snapping of dimensions to align them
- snap text to the center
- Snap dimension to other dimension positions.
- Removes TechDraw_ExtensionPosChainDimensionGroup
- Removes TechDraw_ExtensionCascadeDimensionGroup

Video demo 

https://github.com/FreeCAD/FreeCAD/assets/19984177/8b8e67c4-a4f9-41be-b2b8-9fd14d585c49

### CODE REVIEW

**Comment by maxwxyz** [comment]
Wow this is great! 
Fixes almost all of https://github.com/FreeCAD/FreeCAD/issues/11636

Could the distance between layered  dimensions be slightly increased, I guess there is a standard for it somewhere in an ISO. Ans could it also snap to the same distance from the models edge (or created at that distance outside of the model)?

I'm curious: is there a modifyer key to temporarily disable snapping or to only move direction / view in one axis?

**Comment by pierreporte** [comment]
The first part of the video is not clear because the two views are from different parts. Is the alignment based on the view bounding box or on geometry? If the bounding box is used, the alignment will be wrong if the label is present in one view and missing in the other. This is very important for section views that may not have the same dimensions than their parent view.

image

**Comment by PaddleStroke** [comment]
@pierreporte ah yes you are correct I'm using the bounding box. So for section views that don't have the same size it doesn't work
image

And the 'position section view' tool let you select a point and an edge additionally, which let the user match the views correctly. However this is not ideal either I can think of a lot of cases where it wouldn't work. I'll think about it to try to find the best solution.

**Comment by PaddleStroke** [comment]
Take this example for example
image
Current alignment tool doesn't work there as there are no points and line to select. We would need to add 2 cosmetic vertexes on the section line.

**Comment by maxwxyz** [comment]
@PaddleStroke
https://github.com/FreeCAD/FreeCAD/issues/11636#issuecomment-1843622153

Could it be possible to consider these distances between dimension lines and the body (automatically created and snapping when moving) and between cascading dimension? 

Dimension lines are drawn at a distance of 10 mm from the body edges as a fine solid line. If several dimension lines are required, they should be drawn parallel at a distance of 7 mm - under no circumstances should they cross.

**Comment by pierreporte** [comment]
The alignment of views should be enforced by FreeCAD automatically by default, so that when one moves, the others do as well. Views that are not aligned should be an exception, not the rule. Here is an illustration of how it should work:

image

There are three views of the same part. When view 1 moves alongside the red direction, view 2 doesn’t move and view 3 moves the same distance. When view 1 moves alongside the blue direction, view 2 moves the same distance and view 3 doesn’t move. If view 1 moves in both directions, views 2 and 3 moves the projected distances.

**Comment by WandererFan** [comment]
re aligning views: 

DrawViewPart::getBoundingBox() returns the bounding box of all the edges in the view.   Captions, frames, dimensions, etc are not included in this box.

A View's X/Y properties should give you the center of the view.

**Review by Sult3475 — APPROVED** [review]
5a1ff23290a116ae49b12cd71d824bd5fa62a2c1

**Comment by PaddleStroke** [comment]
Added support to snap section views to their base view.

**Comment by edi271** [comment]
How to position an oblique section view ?
PositionSectionView

**Comment by pierreporte** [comment]
@PaddleStroke You should get access to the [ISO 128-3 standard](https://www.iso.org/standard/83356.html). The [ISO 128 Wikipedia article](https://en.wikipedia.org/wiki/ISO_128) gives an extensive list of standard related to engineering drawings. I don’t know the equivalent American standard.

@sliptonic @yorikvanhavre It would be good if the FPA provided standards (ISO and American) to maintainers to help them determine what feature should do, especially in TechDraw. Non-standard drawing can lead to communication problems or worse.

**Comment by prokoudine** [comment]
The American standard is likely ASME Y14.3, but I don't think it's freely available :)

**Comment by PaddleStroke** [comment]
@edi271 it should work actually with oblique sections. However I have tested and found that it was anoyingly not snapping to the correct vector. It's offset.

**Comment by edi271** [comment]
Also this situation should became managed:
ObliqueSectionView

**Comment by PaddleStroke** [comment]
@edi271 yes this is the case that is currently problematic.

**Comment by PaddleStroke** [comment]
I mark as draft until oblique section snapping works correctly.

**Comment by maxwxyz** [comment]
I hope this gets in for 1.0

**Comment by PaddleStroke** [comment]
Aligning Oblique section views is actually particularly difficult.
To make them work we need a way to know which points to align along the normal to the cut direction. And this is actually difficult I can't find how.

image

We can use SectionOrigin which is on the base view. 
Now we just need to know where SectionOrigin is on the section view.

Is there a way to get the position of SectionOrigin on the section view @WandererFan ?
Something like this, though it doesn't make much sense : 
image

**Comment by maxwxyz** [comment]
any news on this? That would also work for complex section views IMO.

**Comment by PaddleStroke** [comment]
@WandererFan any update on the previous question? If you don't know, then perhaps it is best that : 
- I revert the removal of TechDraw_ExtensionPositionSectionView tool.
- I set the PR as ready so it can already go in as it is now.

**Comment by yorikvanhavre** [comment]
FYI The FPA has purchased both the *ASME Y14_3_2012_R2018 - Orthographic and pictorial views* and *ISO 128-3_2022 - Technical product documentation part 3* norms. We don't have the right to publish them here, but anyone needing to have them, please reach to me or any other FPA admin!

**Comment by sliptonic** [comment]
please fix conflicts

**Pull request merged**
