### PR TITLE
[TD]fix minimum width in TaskCustomizeFormat

### PR DESCRIPTION
**Pull request by WandererFan**
This PR addresses a request made here: https://forum.freecad.org/viewtopic.php?t=77959

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Review by benj5378 — APPROVED** [review]
Tested and works.

Had also done a fix myself... but then I saw you already did one. Also, for some reason, I can't push to my FreeCAD fork as a remote... can push to other remotes, but not my FreeCAD branch specifically... have used at least one hour to solve this so far............................

**Comment by benj5378** [comment]
ffs then I switch branch and back again and suddenly I can push. This is what I spend my time on: git issues and compiling issues. I still haven't fixed the issue that doesn't detect files to recompute on my laptop.

Oh, and btw, last PR of the season again... trying to find time, but it doesn't seem like it's realistic till summer holidays

**Comment by WandererFan** [comment]
OK. Thanks for the help. See you in summer.

**Comment by benj5378** [comment]
@WandererFan After having looked at it for an additional hour, I tried pushing from another git gui and it worked. After that, I tried again in GitKraken where I had issues... not it all just started to magically work again.

Hours spent.

**Pull request merged**
