### PR TITLE
[Sketcher] Constraintselect: further work

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Apart from moving more constraint commands to the continuous framework, changed the internals of DrawSketchHandlerGenConstraint to shorten some grunt work.

### CODE REVIEW

**Comment by bblacey** [comment]
@AjinkyaDahale - The macOS build failed but in a position to look into it right now but will do so later.  The build failed while trying to make the macOS bundle relocatable during the install phase and it failed on an hdf5 dependency.  I noticed that the hdf5 formula was updated in the homebrew ports so it is possible that is the root cause.  I will investigate and ideally resolve later today.

**Comment by AjinkyaDahale** [comment]
@bblacey: Fortunately (for me) it seems like the error was not introduced by my code and on checking older requests it seems like only #501 had the same problem, which didn't seem to do anything big either. Just a bit of info that might help.

**Comment by bblacey** [comment]
@AjinkyaDahale - the macOS builds have been fixed and your PR now passes cleanly, as expected.

**Comment by wwmayer** [comment]
Merged.

There is an oddity with the symmetry command:
+ symmetry between two point and a line the selection order must be point, line, point. Point, point, line doesn't work but with the old mode it does
+ symmetry between three points it uses the second point as symmetry point but the old mode uses the last point

**Comment by AjinkyaDahale** [comment]
@wwmayer: I copied your comment to [the thread on this topic](https://forum.freecadweb.org/viewtopic.php?f=34&t=18175&p=159241#p159241) and answered it there, since I believe it's be more relevant to continue the discussion there.

**Pull request closed without merging**
