### PR TITLE
Preferences: Reorganize UI and Theme pages in Display group

### PR DESCRIPTION
**Pull request by kadet1090**
This changes current "Display/UI" pages to "Display/Advenced" as most of settings there were pretty technical. These settings are not removed as it is hard to decide which one should be removed and which one should stay and we are too close to UI freeze.

Settings that should be obviously kept were moved to new "Display/UI" section which now includes also options from previous "Display/Theme".

Hard to explain in words so:

Before:
image
image

After:
image
image

Fixes: #14412

### CODE REVIEW

**Comment by JohnOCFII** [comment]
I like it!

**Comment by MisterMakerNL** [comment]
We should make a mindmap with the settings.

**Comment by furgo16** [comment]
Thank you. 

image

In the picture above, from the "After" screenshot, would it be possible to: 

1. Rename `Theme` to `Theme customization`. To differentiate it from the theme switcher in the General section. In the past, having two sections named `Theme` have misled users (myself included, but also others) to try to change the theme here instead of finding and using the theme switcher drop-down.
2. Rephrase `This page lets you customize...` to `This section lets you customize...`. After the change, that set of preferences is no longer in its own page, so the text should be updated accordingly.

**Comment by kadet1090** [comment]
Thanks! I included your remarks and fixed some minor issues. Should be ready to go now.

image

**Pull request merged**
