### PR TITLE
py3: fix unicode problem

### PR DESCRIPTION
**Pull request by looooo**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
The Py3 build fails and somewhere the error message is printed: Err: must be str, not bytes

**Comment by looooo** [comment]
> The Py3 build fails and somewhere the error message is printed: Err: must be str, not bytes

So this function must be used somewhere else where unicode is expected for python3. Is it possible to write the html file not in binary-format? maybe @yorikvanhavre 
https://github.com/FreeCAD/FreeCAD/blob/a39f05fd8b520728b89f80b97feaa39f8eeb3114/src/Mod/Start/StartPage/StartPage.py#L484

**Comment by yorikvanhavre** [comment]
Done in da9c65278. I'm rebasing this PR to see if it solves...

**Comment by wwmayer** [comment]
The function handle() always returns a byte string on Py3. When looking for this function then it's always used this way:
self.browser.setHtml(StartPage.handle(), ...)
The function setHtml comes from BrowserViewPy::setHtml and internally the PyArg_ParseTuple expects two strings "ss"
According to https://docs.python.org/3/c-api/arg.html the argument should be "Ss".

**Comment by looooo** [comment]
@yorikvanhavre so with your changes handle should always return unicode (also for py2)? I made a commit to see if it works.

> The function setHtml comes from BrowserViewPy::setHtml and internally the PyArg_ParseTuple expects two strings "ss"
According to https://docs.python.org/3/c-api/arg.html the argument should be "Ss".

so if we still use "ss" this means we must pass a bytes-object for py2 and a unicode-object for py3. If we go for bytes always we should use "Ss" and if we go for unicode always we should use "Us". So this means that my changes now should break the py2-tests.

**Comment by wwmayer** [comment]
> But I still couldn't find which part of that function is produing a bytestring...

Isn't that obvious? The line "if not isinstance(HTML, bytes):" is passed if the string is a unicode/str object and will be encoded to return a bytes object. If the string is already a bytes object nothing is done. Since there exists no further string type in Python it's always a bytes object, then.

> So this means that my changes now should break the py2-tests.

Obviously not. When using "ss" then it also works when passing a unicode object but only as long as the encoding to ASCII is possible. When passing some Chinese characters instead then it fails.
Now with PyArg_ParseTuple it's also possible to pass arbitrary unicode strings but we must tell it explicitly to use the utf-8 encoding then. The call must be of this form:
`
    char* fn;
    if (!PyArg_ParseTuple(args, "et", "utf-8", &fn))
        return NULL;

    std::string utf8Name = fn;
    PyMem_Free(fn);
`
So, I think your PR can be merged now. But then we have to adjust BrowserViewPy::setHtml to support unicode and then it would be good to write a unit test.

**Comment by wwmayer** [comment]
Merged.

**Comment by wwmayer** [comment]
f5befc75c

**Comment by yorikvanhavre** [comment]
Thanks! I'll write a small unit test for the start page.

**Comment by wwmayer** [comment]
To TestWebGui.py I have added a simplified unit test where the French translation for French is passed as it contains a non-ASCII character.
A more sophisticated test could be to load the .qm files of the Start workbench into a QTranslator and check if StartPage.handle() always returns valid HTML code. However, I haven't seen a function in Qt to evaluate HTML. Maybe Python has such a function...

**Pull request closed without merging**
