### PR TITLE
[Pending]Path.Area: respect zero start point when generating path

### PR DESCRIPTION
**Pull request by realthunder**
Related to issue #0003129

Relevant forum thread https://forum.freecadweb.org/viewtopic.php?f=15&t=23451

### CODE REVIEW

**Comment by IchGucksLive** [comment]
DONT AGREE on THIS 
the almost farest Point is a Better way to get it Started
Dressups Dogbone /dragnive/leadin caculate on Q lines WILL FAIL if the First move is not present 
AS Tool DEFAULT pos is 0,0,Clear 
THIS Might Rip the SYSTEM 
libarea heeks does Find the Best Point it is not involved 
BETTER To not start at ZERO let the system CALC a BEST START

**Comment by realthunder** [comment]
Path.Area is not facing end user directly. Path workbench has an end-user facing parameter to let user decide whether to manual or auto select the start position. This PR is just to enable user manual selecting the zero point as a start position for whatever reason.

**Comment by IchGucksLive** [comment]
My English may not good enough to understand the thinking behind 
THE User has Ever Had the opportunity to select a Start point After the Default where set
by the GUI selected a Point First
OR is my understanding Wrong and you added a Mouseklick Startpoint to the Base OP

**Comment by realthunder** [comment]
This PR did not touch anything in Path GUI

**Comment by IchGucksLive** [comment]
@realthunder  It Touches the Startline that 3 Dreeups calculating the Main entry angel 
Tool is at 0,0.clear
first move will be non planar only Z depth not Regionised as XY as we All Bearly Calc on this line Angle on this RED line you take away!
We will see how it comes out with non Planar Startpoint 
Dogbone and DragKnive reli on 3 lines 
i  gone with leadin on 2 as SOMEone might change the Circle mode to FULLCircle insted of 4Quaters i got the 2 lines MIN as there are only 2 lines in this MODE ZerotoStart,Circle

**Comment by realthunder** [comment]
@sliptonic can you please comment onthis?

**Comment by sliptonic** [comment]
I've pulled the PR code and it seems to be working correctly.  @IchGucksLive:  All the path work and dressup is downstream from this change.  Please pull realthunder's code and test it yourself.  If you can find a case where it breaks, please comment here.   We'll leave the PR pending for a couple days to test.

@realthunder: thanks.

**Comment by sliptonic** [comment]
This is good to go.  Please merge.

**Comment by luzpaz** [comment]
TravisCI error is from the OSX build:
```
-- Xerces-C was not found.
CMake Error at CMakeLists.txt:615 (MESSAGE):
  ==================
  XercesC not found.
```
ref: https://travis-ci.org/FreeCAD/FreeCAD/jobs/331707043#L553-L559

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
