### PR TITLE
FEM: more improvements on FEM code base :-)

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
> If we test if the ccx command is available ('which ccx), and it is, we should use the command directly and not the path. Although there shouldn't be much difference.

I will keep this and adapt this on one of the next PR. Does either have any advantages or disadvantages?

**Comment by looooo** [comment]
> Does either have any advantages or disadvantages?

No. I thought it's the cleaner way. But I guess there should be no difference. Did yoo encounter any issues with the way I suggested?

**Comment by berndhahnebach** [comment]
yes. If you comment this line I set back no binary is set at all and no ccx can be executed. Thus I can hardly believe it worked for you. If we would set the binary to "ccx" instead of "path to ccx + ccx" it would need other but small changes. As I said I consider this for one of my next PR. Since it has been this way (path + ccx) for years this PR can be merged without any problems.

**Comment by looooo** [comment]
I guess it works because it's set to "ccx" by default. There is a comment above

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
