### PR TITLE
Fix bug #6679, add new profiles

### PR DESCRIPTION
**Pull request by manuvarkey**
Reclassify profile sections by type to fix bug #6679.
Add IS RHS & IS SHS profiles.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7181">pipeline status</a> for feature branch [PR_7181](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7181). Pipeline [586961713](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/586961713) was triggered at [dd0bb33](https://github.com/FreeCAD/FreeCAD/pull/7181/commits/dd0bb33a01232afb811f7c640ef0a71fb496fec9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7181">pipeline status</a> for feature branch [PR_7181](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7181). Pipeline [587134758](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/587134758) was triggered at [f14132a](https://github.com/FreeCAD/FreeCAD/pull/7181/commits/f14132ab71b39633a2355f4e7d013c519d92e638). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
i don't understand why the CTH profile needed to be removed?

**Comment by manuvarkey** [comment]
The same profile is already under CHS.

`CHS,CHS42.4x3.2,C,42.4,3.2`

Thought the line might be a mistake. Couldn't find any reference to CTH or CTH423 anywhere. 

`CTH,CTH423,C,42.4,3.2`

Please correct if wrong. I will re-add and update branch.

**Comment by manuvarkey** [comment]
@yorikvanhavre Any thing to be done for this pull request ?

**Comment by yorikvanhavre** [comment]
Sorry for the delay! Ok I see it now, perfect! Indeed I can't find anything on the net either about CTH. Ok then! Thanks for the PR!

**Comment by manuvarkey** [comment]
@yorikvanhavre Thanks for your attention. 

On the same topic, will it be possible to allow change to the profile type after addition ? While going through the code, it seems that each type of profile is a separate subclass of _Profile. Any thoughts about how it would be possible to implement this ?

Thanks again.

**Pull request merged**
