### PR TITLE
Offscreen rendering

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@wwmayer this looks interesting, what does it do?

**Comment by wwmayer** [comment]
It renders a scene off-screen :)

Coin has an integrated off-screen rendering mechanism but it always lacked the possibility to support anti-aliasing or correctly handle transparent backgrounds and for several years it has stopped working for me completely.

So, the alternative we have implemented several years ago is using Qt's off-screen rendering capabilities combined with framebuffer objects.

Now this PR only exposes the corresponding C++ class to Python. This allows it to create high-quality images of a scene in true headless mode and thus could be used as the groundwork for a thumbnailer for XFCE that supports any file format that FreeCAD supports.

**Comment by wwmayer** [comment]
What do you mean with alternative GUI?

**Comment by luzpaz** [comment]
> What do you mean with alternative GUI?

Meaning, not using the FreeCAD regular GUI, but like a unix pipe (if you will) to a dialog of some sort showing the model being manipulated through the headless instance of FreeCAD

**Comment by wwmayer** [comment]
You could show the rendered image in a widget and use some buttons to control the headless FreeCAD. But an interaction with the scene won't be possible and also the rendering might be a bit slow.

**Comment by yorikvanhavre** [comment]
Fantastic! There are a lot of possibilities there...

I also think it would be impractical to run FreeCAD in another GUI that way, as it would need to re-render the scene 30 times per second or something like that, no sure that would be achievable... Better path would be to export the coin scene directly to some other format (webgl, etc...) and let the other app do the rendering

**Comment by luzpaz** [comment]
CC @ickby (you may be interested in this since you've been working on https://github.com/OpenCollaborationPlatform/CollaborativeFC)

**Comment by adrianinsaval** [comment]
does that mean it could be also used to generate thumbnails even for FCStd files that don't have the embedded thumbnail?

**Comment by wwmayer** [comment]
> does that mean it could be also used to generate thumbnails even for FCStd files that don't have the embedded thumbnail?

Basically yes. However, it's not my primary goal to implement a general thumbnailer. I just wanted to make the real off-screen rendering working again. The thumbnailer is just a side-product of it.

For a thumbnailer there are a few points to consider:
* The thumbnailer would have to load FreeCAD in headless mode and if there is a directory with hundreds of files I am not sure how much it would freeze the system
* If a STEP, STL or any other data file is relatively big then loading it can be quite time consuming. So, there should be a certain limit of the file size for that an image is created.

**Pull request merged**
