### PR TITLE
Adds 'extend' feature to sketcher.

### PR DESCRIPTION
**Pull request by a2lin**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---
This patch adds an 'extend' functionality for the 'GeomArcOfCircle' and 'GeomLineSegment' edges. It also adds a new Python API to Sketcher:
```
Sketch.extend(int GeomId, double increment, int pointPos);
```
where `increment` refers to the increase in length (for geomLineSegment), or the increase in angle (for GeomArcOfCircle), with negative inputs allowed. `pointPos` is expected to be either `Sketcher::start` or `Sketcher::end`.

Tested on OSX.

### CODE REVIEW

**Comment by luzpaz** [comment]
Any relationship to https://freecadweb.org/tracker/view.php?id=1187 ?

**Comment by a2lin** [comment]
Yep, it's related! Sorry, I added #fixes 1187 to the commit message, but should probably have mentioned it in the  PR comment too.

**Comment by luzpaz** [comment]
@a2lin oh nice! Didn't notice that. Well done 👍

**Comment by a2lin** [comment]
A gif:
Sketcher Extend

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
