### PR TITLE
Move glortho2d to GLKMatrix4MakeOrtho as to avoid Deprecated Warning …

### PR DESCRIPTION
**Pull request by vejmarie**
…on Mac OS

Fix issue 0002897

### CODE REVIEW

**Comment by vejmarie** [comment]
Yep, I did changed the line ending as it was full of weird character coming from Windows edit ( ^M ) stuff and made the file unreadable with vi (I am a really old school guy on this ;)). I should have made 2 commits, sorry, hope it will be fine. 

Changes are there 

line 31
+# include <GLKit/GLKMatrix4.h>

Line 103

+#if defined (FC_OS_MACOSX)
+    GLKMatrix4 orthoMat = GLKMatrix4MakeOrtho(0, width() - 1, height() - 1, 0, -1, 1);
+    glLoadMatrixf(orthoMat.m);
+#else
+    gluOrtho2D(0, width() - 1, height() - 1, 0);
+#endif

**Comment by wwmayer** [comment]
Merged.

**Comment by bblacey** [comment]
Yeah, I wish we could do [this](https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings) to the FreeCAD repo some day...

**Comment by luzpaz** [comment]
@bblacey also https://freecadweb.org/tracker/view.php?id=1352 (DOS line endings makes applying patches on Linux really hard)

**Pull request closed without merging**
