### PR TITLE
[Sketcher] Line DSH Fixes #12322 

### LINKED ISSUE #12322: [Problem] V0.22 Sketcher OVP: sign ignored for width and height input for line
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Set the On-View-Parameters preference to "All".
2. Create a new sketch and start Sketcher_CreateLine.
4. Select Mode "Point, width, height".
5. For the start point pick the origin (in practice this might be another already constrained point).
6. Move the cursor to the left of the Y axis and below the X axis.
7. The distances are now displayed with a minus sign.
8. Enter negative values for the X and Y distance.
9. Result: The endpoint has positive coords.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35803 (Git)
Build type: Release
Branch: main
Hash: 90c90f705bec20faf4b8bb419574134c33c7d4b5
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fixes https://github.com/FreeCAD/FreeCAD/issues/12322
Change the bahavior of line DSH length/width mode so that it behaves like the rectangle length/width DSH.

### CODE REVIEW

**Comment by PaddleStroke** [comment]
First commit is unrelated and because master is still broken. https://github.com/FreeCAD/FreeCAD/pull/12291

**Comment by sliptonic** [comment]
@Roy-043 Will you please comment if this resolves correctly your original issue?

**Comment by Roy-043** [comment]
@PaddleStroke Thanks for looking at this.

@sliptonic Sorry, but I do not compile myself. I have to wait for the weekly. Please merge. Thanks.

**Comment by chennes** [comment]
I gave this a try and it works as advertised. I'm fine with this behavior since it's consistent, but I'd also have been OK with those negative signs being kept around.

**Pull request merged**
