### PR TITLE
Part: Allow helix primitive with negative Angle

### PR DESCRIPTION
**Pull request by davidosterberg**
Forum discussion:
https://forum.freecadweb.org/viewtopic.php?f=8&t=55449

negative_helix_angle

### CODE REVIEW

**Comment by donovaly** [comment]
@wwmayer , I would say it is 0.19 stuff. The helix is a new feature in just since a week. Users tested it and in fact negative angles were simply forgotten. So this PR polishes a new feature to make it fully usable.
Moreover the "fix" of this PR is trivial.

**Review by donovaly — APPROVED** [review]
Thanks. Now the helix feature should be fully usable.

**Comment by wwmayer** [comment]
There are really not many changes so it can be accepted for v0.19.

**Comment by davidosterberg** [comment]
Thanks

**Pull request merged**
