### PR TITLE
python3-FEM

### PR DESCRIPTION
**Pull request by looooo**
The python3 commits for FEM would have been quite difficult to cherry-pick. There was an unresolved merge-conflict at the bottom, which was solved somewhere in the middle... Most of the commits include diff for other workbenches too. So comparing the tip of py3 to the master was the easier way. The included commits are listed in the commit message.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
Would you mind if I wuold split them again into more commits and use some appropriate commit messages. I could keep you as the author. 

I'm a bit off e commit history freak ...

**Comment by wwmayer** [comment]
Btw, the build fails on all platforms in FemMeshPyImp.cpp because there the Py::Int's haven't been replaced.

**Comment by looooo** [comment]
@berndhahnebach for sure you can split them again. But be sure no other wb is influenced. Some of the listed commits have fixes for other directories too....

@wmayer That was my fault. I remember trying to fix the py3-branch after conflicted rebase...

**Comment by berndhahnebach** [comment]
OK, I will come up with something ...

**Comment by looooo** [comment]
just checking the test: there is one more ```map -> list(map```: 
```
freecad/Mod/Fem/importCcxFrdResults.py", line 179, in importFrd
    results.MaxShear = map((lambda x: x * scale), shearstress)
AttributeError: Attribute (Name: MaxShear) error: 'type must be float or list of float, not map' 
```
maybe you can correct this too.

**Comment by berndhahnebach** [comment]
I have never compiled FreeCAD against Python3. looooo would you try this: https://github.com/berndhahnebach/FreeCAD_bhb/commits/fempy3  

btw: What is the "from __future__ import print_function"  ?

bernd

**Comment by berndhahnebach** [comment]
> ust checking the tests: there is one more map -> list(map:

freecad/Mod/Fem/importCcxFrdResults.py", line 179, in importFrd
    results.MaxShear = map((lambda x: x * scale), shearstress)
AttributeError: Attribute (Name: MaxShear) error: 'type must be float or list of float, not ma

done, but what is with this:  
https://github.com/berndhahnebach/FreeCAD_bhb/blob/86c8bcf01be36abf48b62574c76d05861d2ea96d/src/Mod/Fem/importCcxFrdResults.py#L195

https://github.com/berndhahnebach/FreeCAD_bhb/blob/86c8bcf01be36abf48b62574c76d05861d2ea96d/src/Mod/Fem/importCcxFrdResults.py#L155

**Comment by looooo** [comment]
>> What is the "from future import print_function" for ?

print(a, b) in python2 prints a tuple, with the future import the output is the same for python3 and 2

>> Why is from FreeCAD import Units needed.

This one I am also wondering. Importing has slightly changed with python3. Maybe this was causing this. But this way it's clear it's a freecad-modul. So I think we should use it like this or not?

>> The Units module is imported in other modules in FEM too but without from FreeCAD For example https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Fem/_TaskPanelFemMaterial.py#L36 ?

The python3 branch is only compileable, python2 compatible, and checks the test. We really can't check every hidden function. This should be done directly on master once the python3-branch is in master and master is python3 compilable.

>> done, but what is with this:

this isn't checked by the tests I think ;-) priorities with python3 are:
1. get python3 branch to master and don't break python2 code
2. make master python3 compilable
3. make master tests work with python3.
4. stay updated with python3 branch

I think such things can be done directly on master branch.

**Comment by looooo** [comment]
on branch py3-21:
```
git fetch bernd
git rebase bernd/fempy3
conflicts....
```
git merge isn't any better. Cant we merge the commit in the way I have pullrequested and do the additional changes you added afterwards? This would simplefy the task for me a lot.

**Comment by looooo** [comment]
ok, rebasing on my pull-request-branch is also quite difficult.... 
I will try your branch, but this could take a while :-)

**Comment by looooo** [comment]
ok after rebasing and resolving merge-conflicts:
```
git diff bernd/fempy3 src/Mod/Fem/
diff --git a/src/Mod/Fem/App/AppFem.cpp b/src/Mod/Fem/App/AppFem.cpp
index ebd4124..1b49452 100644
--- a/src/Mod/Fem/App/AppFem.cpp
+++ b/src/Mod/Fem/App/AppFem.cpp
@@ -129,7 +129,7 @@ PyMOD_INIT_FUNC(Fem)
     // NOTE: To finish the initialization of our own type objects we must
     // call PyType_Ready, otherwise we run into a segmentation fault, later on.
     // This function is responsible for adding inherited slots from a type's base class.
-
+ 
     Fem::FemAnalysis                ::init();
     Fem::FemAnalysisPython          ::init();
     Fem::DocumentObject             ::init();
diff --git a/src/Mod/Fem/App/FemMeshPy.xml b/src/Mod/Fem/App/FemMeshPy.xml
index c5975f3..a70fb6c 100755
--- a/src/Mod/Fem/App/FemMeshPy.xml
+++ b/src/Mod/Fem/App/FemMeshPy.xml
@@ -266,3 +266,4 @@
         </Attribute>
     </PythonExport>
 </GenerateModel>
+
diff --git a/src/Mod/Fem/App/FemMeshPyImp.cpp b/src/Mod/Fem/App/FemMeshPyImp.cpp
index 43f3273..06cbf55 100644
--- a/src/Mod/Fem/App/FemMeshPyImp.cpp
+++ b/src/Mod/Fem/App/FemMeshPyImp.cpp
@@ -1172,3 +1172,4 @@ int FemMeshPy::setCustomAttributes(const char* /*attr*/, PyObject* /*obj*/)
 {
     return 0;
 }
+
diff --git a/src/Mod/Fem/FemMesh2Mesh.py b/src/Mod/Fem/FemMesh2Mesh.py
index 20a3df8..08e8d9a 100644
--- a/src/Mod/Fem/FemMesh2Mesh.py
+++ b/src/Mod/Fem/FemMesh2Mesh.py
@@ -20,6 +20,8 @@
 # *                                                                         *
 # ***************************************************************************
 
+from __future__ import print_function
+
 __title__ = "FemMesh to Mesh converter"
 __author__ = "Frantisek Loeffelmann, Ulrich Brammer, Bernd Hahnebach"
 __url__ = "http://www.freecadweb.org"
diff --git a/src/Mod/Fem/FemToolsZ88.py b/src/Mod/Fem/FemToolsZ88.py
index 45b33ab..b707042 100644
--- a/src/Mod/Fem/FemToolsZ88.py
+++ b/src/Mod/Fem/FemToolsZ88.py
@@ -19,6 +19,7 @@
 # *   USA                                                                   *
 # *                                                                         *
 # ***************************************************************************
+from __future__ import print_function
 
 __title__ = "FemToolsZ88"
 __author__ = "Bernd Hahnebach"
```
I don't know if this happend with resolving the merge-conflicts, or if this isn't within your branch.

then I have added a message to this commit:
https://github.com/berndhahnebach/FreeCAD_bhb/commit/87e87c15cc34f0108093656c39f22a7c6beb62a5

Your branch builds fine with python3, workbench loads, test are running. good job ;-)

So maybe you can fix the ```from __future__ import print_function``` problems, and then create a new pull request. Thanks for your collaboration, and sorry for my harsh words ;-)

**Comment by berndhahnebach** [comment]
I will do, and go for a new PR !

BTW:
How do you compile this against python3? I get lots of 

```
SyntaxError: Missing parentheses in call to 'print'
-- /home/hugo/Documents/dev/freecad/freecadbhb_dev/build/src/Gui/SelectionObjectPy.cpp
  File "/home/hugo/Documents/dev/freecad/freecadbhb_dev/freecad/src/Tools/generate.py", line 42
    print "Done generating: " + GenerateModelInst.Module[0].Name
                            ^

```

**Comment by ianrrees** [comment]
@berndhahnebach A good way to fix those, is to change the print statements in to print() calls by adding parenthesis and add that "from future import print_function" at the top of the source file.  This will work fine on Python 2 or 3.

**Comment by looooo** [comment]
I rebased my py3-21 branch on your branch and then compiled with dependencies from conda.
You can't expect master to work with python3 right now. The merging of py3 branch is an ongoing process. I try to minimize the diff step by step. First I tried to merge the base things first, but this was breaking python2 compatibility of master because  some changes on the base are for python2 and 3 (eg. _getattro). So currently I am trying a bottom up strategy, which works quite well. First all the little diff of the modules gets into master. After that the base things hopefully can be merged without breaking python2.
Yorik did an amazing job with the porting. But the branch had to move away to make it work with python3. We could have merged everything at once, but this most likely would have brought complications in... (like the big merges in last summer smesh, vtk, ...) so I think there is no other way than merging one by one.
You can follow the python3 merge process here: https://github.com/looooo/FreeCAD/issues/8

To build with python3 you can have a look here: https://www.freecadweb.org/wiki/Python_3

**Comment by berndhahnebach** [comment]
thanks for all the informations!

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/536

**Pull request closed without merging**
