### PR TITLE
[PartDesign] Hole, ignore duplicate circle/curve centers

### PR DESCRIPTION
**Pull request by Syres916**
Fixes https://github.com/FreeCAD/FreeCAD/issues/11672 even though the root cause is user education, i.e. don't create two circles in the same location.

### CODE REVIEW

**Comment by Syres916** [comment]
Polite reminder @FlachyJoe could you please review, TIA.

**Comment by Syres916** [comment]
It would appear @FlachyJoe isn't available to review, @AjinkyaDahale could you spare a few minutes to look over the PR please?

**Review by FlachyJoe — CHANGES_REQUESTED** [review]

**Comment by FlachyJoe** [comment]
@Syres916 sorry, I left my review pending.

**Comment by Syres916** [comment]
Thanks @FlachyJoe changes tested locally and applied.

**Pull request merged**
