### PR TITLE
Arch: touch Axis when key property change

### PR DESCRIPTION
**Pull request by carlopav**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This PR likely doesn't do anything... If a property changes, but is not handled by onChanged(), the execute() method is triggered, which leads to the same result as doing obj.touch(). Maybe you meant something else?

**Comment by carlopav** [comment]
> 
> 
> This PR likely doesn't do anything... If a property changes, but is not handled by onChanged(), the execute() method is triggered, which leads to the same result as doing obj.touch(). Maybe you meant something else?

Nope, exactly that. Check out the last modification of the experimental wall in BIM wb: if the axis is touched, the wall auto align itself to the axis through the mustExecute method. If the axis is just executed, the wall can't check if the axis has been changed. At least that's what I experienced... do you think there are other ways to make it work?

**Comment by yorikvanhavre** [comment]
Hmm maybe there is an order/priority thing there... But anyway okay, if you found it works for you then let's do it!

**Comment by carlopav** [comment]
Thanks!

**Pull request merged**
