### PR TITLE
FEM: Remove improperly licensed files

### LINKED ISSUE #8894: Certain .FCStd files in source code are licensed "All Rights Reserved"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=76603

### Version

0.21 (Development)

### Full version info

```shell
Not applicable
```

### Subproject(s) affected?

None

### Issue description

.FCStd files contain embedded licensing information. The FreeCAD source code itself includes .FCStd files, and many of these are (most likely inadvertently) marked with the license "All Rights Reserved".

This license is incompatible with the FreeCAD project (see [Licensing, Ownership, and Credit](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md#4-licensing-ownership-and-credit) in the FreeCAD Contribution Process). This is also incompatible with requirements for inclusion in distributions such as [Debian](https://www.debian.org/social_contract#guidelines) or [Fedora](https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/).

### Anything else?

Affected files include:
- [ ] src/Mod/Fem/femtest/data/calculix/box.FCStd (b25d2cd @PrzemoF, a0a989f @berndhahnebach; was cube.fcstd)
- [ ] src/Mod/Fem/femtest/data/calculix/thermomech_flow1D.FCStd (9fd6738 @kgoao; was Flow1D_thermomech.fcstd)
- [ ] src/Mod/Fem/femtest/data/calculix/thermomech_spine.FCStd (1caeb68 @stoflap, 73b9c73 @berndhahnebach; was spine_thermomech.fcstd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chennes**
The original authors of the two FCStd files could not be contacted to correct the licensing mistake in those files, so the test cases are removed entirely.

Fixes #8894.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9794">pipeline status</a> for feature branch [PR_9794](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9794). Pipeline [904914343](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/904914343) was triggered at [c03c38a](https://github.com/FreeCAD/FreeCAD/pull/9794/commits/c03c38a67fa38abb224d96e793d98f621e59d2b5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9794">pipeline status</a> for feature branch [PR_9794](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9794). Pipeline [904945846](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/904945846) was triggered at [d2ee5e3](https://github.com/FreeCAD/FreeCAD/pull/9794/commits/d2ee5e35252f62e1ce5218a72de78f711e29e516). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
ohh nooooo All the hard work we did years ago in FEM will be removed of FreeCAD.  What do we need to do to get them back ... Where is a Forum disscussion about this?

**Comment by berndhahnebach** [comment]
What was wrong with this python file? [src/Mod/Fem/femexamples/thermomech_flow1d.py](https://github.com/FreeCAD/FreeCAD/pull/9794/commits/bdc0077497280101b05ce8171728802befffc53d#diff-4b0310cc045f505b3b4317389524c9973285312811f4264ba578a688aa22d8db)

**Pull request merged**
