### PR TITLE
PathGui: added Path selection style setting to preference

### PR DESCRIPTION
**Pull request by realthunder**
As requested from here: https://forum.freecadweb.org/viewtopic.php?f=15&t=21549

### CODE REVIEW

**Comment by dlhenke** [comment]
After last pull  today impossible to make.
 
[ 12%] Building CXX object src/Gui/CMakeFiles/FreeCADGui.dir/ActionFunction.cpp.o
/Users/duhenke/FreeCAD/source/src/Gui/ActionFunction.cpp:124:23: error: implicit instantiation of undefined template 'QPointer<QObject>'
    QPointer<QObject> argQObject;
                      ^
/usr/local/Cellar/qt@5.6/5.6.2/include/QtCore/qmetatype.h:1333:1: note: template is declared here
QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
^
/usr/local/Cellar/qt@5.6/5.6.2/include/QtCore/qmetatype.h:209:7: note: expanded from macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
    F(QPointer)
      ^
1 error generated.
make[2]: *** [src/Gui/CMakeFiles/FreeCADGui.dir/ActionFunction.cpp.o] Error 1
make[1]: *** [src/Gui/CMakeFiles/FreeCADGui.dir/all] Error 2
make: *** [all] Error 2

**Comment by realthunder** [comment]
I don't know, but it doesn't seem to be related to my patch. Maybe you can try make again without parallel, probably make clean the Gui module first.

**Comment by ianrrees** [comment]
The compile problem comes from 47847513a85ff6615774ef628230f79e37471daf - I responded to @dlhenke's post in the forum https://forum.freecadweb.org/viewtopic.php?f=4&p=168080

**Comment by yorikvanhavre** [comment]
merged

**Pull request closed without merging**
