### PR TITLE
[Path] fix 3Dsurface with countersink tools

### PR DESCRIPTION
**Pull request by J-Dunn**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
Forum thread associate with PR: https://forum.freecadweb.org/viewtopic.php?f=15&t=50570

**Comment by luzpaz** [comment]
@J-Dunn In the future, do you mind prepending the Workbench associated with the PR *in the commit not just the PR)? In this case it would be `Path:`. Thanks.

**Comment by J-Dunn** [comment]
There is  a link in boiler plate which refers to a guide by chrisB .  I scanned it and did not see this. It is rather long so maybe I missed it. 

Can you please insure there is a centralised checklist of all the hoops we are expected to jump through to submit a PR.  This is a constant problem and should not be a case of personal memory or something that needs to be researched every time. 

If you want compliance, make it is fast, reliable and easy. ;)

**Comment by luzpaz** [comment]
oh my bad. you did add it via 1830c14bb0fc7e87d009ffa51515a6b33e1282c3

**Comment by J-Dunn** [comment]
thanks Sliptonic . 
grbl  G83 ?
https://github.com/FreeCAD/FreeCAD/pull/3725

**Pull request merged**
