### PR TITLE
[TD] Rewrite balloon placing method

### PR DESCRIPTION
**Pull request by fjullien**
When clicking on balloon command, cursor is changing to balloon cursor.
It means user is ready to place a balloon (anywhere on the page).
Balloon object is not created until user click somewhere.

Balloon command can be aborted pressing escape or when page view lost
focus (in other words, when user clic somewhere else than the page).

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by fjullien** [comment]
@WandererFan : could you give it a try ?
Let me know if it works for you and what do yo think of it

**Comment by WandererFan** [comment]
I like that the fancy cursor doesn't leave the tab area.  That's much better.  

From a structure standpoint, I don't like creating document objects inside the QGraphicsView code.   It would be better to follow the standard pattern of creating objects in the Commandxxx.cpp.  

The next maintenance programmer will thank you.

**Comment by WandererFan** [comment]
And I miss the nice dialog for the parameters. :(

**Comment by fjullien** [comment]
> From a structure standpoint, I don't like creating document objects inside the QGraphicsView code. It would be better to follow the standard pattern of creating objects in the Commandxxx.cpp.

Yes, I know. But as you use this kind of thing in TaskLeaderLine::createLeaderFeature I thought it was acceptable.
However, your code is not attached to a toolbar button so it is not exactly the same thing.

Anyway, how would you do ? I can create a function in command.cpp, put it in command.h and call it from QGVPage.

**Comment by fjullien** [comment]
> 
> 
> And I miss the nice dialog for the parameters. :(

I was thinking I could add it in a separate commit. But, if you agree I 'll include in my next PR.

**Comment by WandererFan** [comment]
OK.  Let's merge it now to fix the wandering icon.  Then we can refactor when you do the dialog.

Just waiting on Travis and Appveyor

**Comment by WandererFan** [comment]
merged & closed.

**Pull request merged**
