### PR TITLE
Assembly: Improve JCS appearance and implement autoscale

### PR DESCRIPTION
**Pull request by qewer33**
Completes https://github.com/FreeCAD/FreeCAD/issues/10745 and https://github.com/FreeCAD/FreeCAD/issues/10746

CC @PaddleStroke 

Preview video:

[vokoscreenNG-2023-09-21_19-30-07.webm](https://github.com/FreeCAD/FreeCAD/assets/69015181/603f1a3e-a20b-4d7f-ad4c-c64695311c3f)

### CODE REVIEW

**Comment by qewer33** [comment]
ok uhhh... what?

I have no idea how @chennes' TNP fixes ended up in my commit :joy: 

really weird,I think it might be caused by the pre-commit, I'll see how I can fix it

**Comment by PaddleStroke** [comment]
Awesome work !
Maybe you did a rebase interactive with 1 commit too much? If so you can redo the rebase and drop chris commit.

**Comment by qewer33** [comment]
> Looks like its squashed with a commit from chris ?

I didn't do any squashing or rebasing, that's why I am confused. Should be all good now though!

**Comment by PaddleStroke** [comment]
Yes it looks better now.

Any other card holds your interest perhaps ? With such efficiency we'll be through them quickly😄

**Comment by qewer33** [comment]
> Any other card holds your interest perhaps ? With such efficiency we'll be through them quickly😄

I'll see what I can do :sweat_smile:

**Comment by luzpaz** [comment]
@qewer33 please `git commit --amend` the typo:  appereance - > appearance

**Comment by tobiasfalk** [comment]
It would be nice if there were a seting for the size of JCS, if there is not already one.

**Comment by PaddleStroke** [comment]
Another small thing regarding the JCS appearance : 
I initially put the axis colors as properties. But this is a mistake, there no point to have them as properties. The axis colors should be preferences instead.

 If you want to tackle that as well in this PR? Or it can come later.

**Comment by qewer33** [comment]
> Another small thing regarding the JCS appearance : I initially put the axis colors as properties. But this is a mistake, there no point to have them as properties. The axis colors should be preferences instead.
> 
> If you want to tackle that as well in this PR? Or it can come later.

I used parameters as axis colors on my recent transform dragger improvements PR. The idea is to unify all the axis colors across FreeCAD (axis cross, corner coord system, transform dragger, navi cube axis's etc.) and make them configurable from Preferences. I'll open an issue and a PR for this later.

For now I can JCSs also use these parameters.

**Comment by PaddleStroke** [comment]
Yes it needs to be removed. It's an inaccuracy.

**Comment by qewer33** [comment]
@chennes ready for review/merge now

**Comment by wwmayer** [comment]
Some remarks:
* In order to avoid possible problems with scripting you should consider moving the view provider code into a separate file
* In the view provider you shouldn't add a callback function that is linked to the camera of the active view because this is error prone. If you open a new 3D view from the View menu then auto-scaling doesn't work.

Instead you should use the class SoShapeScale:
```
from pivy import coin

cube = coin.SoCube()

type = coin.SoType.fromName("SoShapeScale")
scale = type.createInstance()
scale.setPart("shape", cube)

graph = Gui.ActiveDocument.ActiveView.getSceneGraph()
graph.addChild(scale)
scale.scaleFactor = 10
```

**Pull request merged**
