### PR TITLE
Removing not maintained stylesheets

### PR DESCRIPTION
**Pull request by MisterMakerNL**
The remaining stylesheets all have the same code, just different colors. Which is easy to maintain. 
No one seem to be working on the other ones.
If someone is missing them they can make an addon for them.
I am not making this addon, since then I am the maintainer. Don't mind anyone else doing this off-course. 
Don't have the time to maintain 4 different stylesheets.
Don't think we need 4 different dark styles. 
And for the people who do, they can create or install them as an addon.

### CODE REVIEW

**Comment by Syres916** [comment]
Who says **you** have to maintain them, they are community maintained, have I not done any stylesheet contributions recently? This PR comes across as autocratic.

**Comment by MisterMakerNL** [comment]
> Who says **you** have to maintain them, they are community maintained, have I not done any stylesheet contributions recently? This PR comes across as autocratic.

No no, I say if I upload them to a separate github to make an addon/workbench from them so users can still use them, then they will be under my name and I have to maintain them.
I totally don't mind someone doing this, more options the better, but keep me out of it.

**Comment by maxwxyz** [comment]
I'm supporting this PR.
There are 6 default themes in main for dark themes. Dark, Darker, Dark contrast,... No user gets what is which theme and how is it different from the other dark themes. `Darker` is lighter than `Dark` for example.
Also it is hard to maintain if not all new features are supported by all themes.
Ideally two polished themes are shipped with FreeCAD. One Dark and one Light theme which is coherent and up to date to support all features. On top of that, everyone can publish themes as addon through the addon manager.

**Comment by MisterMakerNL** [comment]
It probably should be called 
- Light
- Gray
- Dark
But the autistic in me also is annoyed that one is color and the other 2 are light settings. 
Then you get
- White 
- Gray
- Black
But since this is the internet, we probably can't do this either.

**Comment by chennes** [comment]
This is definitely a PR that should have an Issue attached to it. @MisterMakerNL could you please create an issue stating the problem you are trying to solve here? We can discuss it there and come to a consensus about the correct course of action.

**Comment by sliptonic** [comment]
Moved to draft pending discussion on the issue.

**Comment by MisterMakerNL** [comment]
Sooo thanks to [this](https://forum.freecad.org/viewtopic.php?p=743391#p743391) forum post I discovered that auto dark mode just works in QT if we set
```
[Platforms]
WindowsArguments = darkmode=2
```
In qt.conf (qt.conf) is currently in library pack. Ot by settings: 
`
qsetenv("QT_QPA_PLATFORM", "windows:darkmode=[1|2]")
`
According too: https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5
If we do this then it will automatically switch to dark mode. 
But then the issue is it would look terrible: 
image
But then we can apply the a good looking style-sheet according to the same article.

**Comment by maxwxyz** [comment]
I guess there were some more discussions around this topic, especially in the DWG.
@MisterMakerNL are you intending to resuming to this PR?
As a reminder: If you want this draft PR to be considered for a version 1.0 release, it should be marked _ready for review_ by **Monday, 2024-06-03** at the latest. (further details in the 1.0 feature freeze [forum announcement](https://forum.freecad.org/viewtopic.php?p=759605#p759605)).

**Comment by MisterMakerNL** [comment]
These are the propose themes or currently just style-sheets to be default:
https://github.com/FreeCAD/FreeCAD/pull/13772#issuecomment-2108147673
Still some discussions on the gradients.
But it looks like I am going to suggest @obelisk79 Opentheme colors and backgrounds. although for the light theme I'd make it more dark just because this issue exist:
https://github.com/FreeCAD/FreeCAD/issues/13980#issuecomment-2112986938

This is the proposed setup:
Freecad styles
Also posted here:
https://forum.freecad.org/viewtopic.php?t=87317&e=1&view=unread#unread

**Comment by MisterMakerNL** [comment]
I am closing this one and moving towards the new new here https://github.com/FreeCAD/FreeCAD/pull/13772

**Pull request closed without merging**
