### PR TITLE
Sketcher: Add gtest unit test framework

### PR DESCRIPTION
**Pull request by chennes**
Begin the process of adding Google Test C++ unit tests to Sketcher.

---

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by chennes** [comment]
@wwmayer can you help me figure out why linking is failing here?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9326">pipeline status</a> for feature branch [PR_9326](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9326). Pipeline [842853006](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/842853006) was triggered at [7429d21](https://github.com/FreeCAD/FreeCAD/pull/9326/commits/7429d21faf298a6ced2914000ea2d49fd0ea1999). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
> can you help me figure out why linking is failing here?

Because none of the classes of PlaneGCS have the export macro.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9326">pipeline status</a> for feature branch [PR_9326](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9326). Pipeline [843579385](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/843579385) was triggered at [1c1271b](https://github.com/FreeCAD/FreeCAD/pull/9326/commits/1c1271b1ef831a1a4f771946d297746728c73540). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9326">pipeline status</a> for feature branch [PR_9326](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9326). Pipeline [845217846](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/845217846) was triggered at [79711f9](https://github.com/FreeCAD/FreeCAD/pull/9326/commits/79711f9e848cd4c98cff1da4c57635a7128d4768). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9326">pipeline status</a> for feature branch [PR_9326](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9326). Pipeline [845222982](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/845222982) was triggered at [d31bd36](https://github.com/FreeCAD/FreeCAD/pull/9326/commits/d31bd3629c18cd4b7e220b42948cb984b7f31485). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
