### PR TITLE
Sketcher : allow to select points & other elements from the backside view

### PR DESCRIPTION
**Pull request by 0penBrain**
https://forum.freecadweb.org/viewtopic.php?f=3&t=71482

This achieved by a camera sensor at viewprovider level that detects side change, inverse all Z layer values used for rendering and redraws.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
Nice! it compiles and runs fine, definitively a big improvement over the previous situation, the points can be properly selected now from the backside, tilted sketches can still give trouble but I don't know if it's even possible to solve that.

**Comment by adrianinsaval** [comment]
this solves #5673 and #7341

**Comment by 0penBrain** [comment]
> tilted sketches can still give trouble but I don't know if it's even possible to solve that.

Not sure I get it completely. Could you give an example to reproduce so that I can have a look?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7417">pipeline status</a> for feature branch [PR_7417](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7417). Pipeline [627028741](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/627028741) was triggered at [1a6d4a1](https://github.com/FreeCAD/FreeCAD/pull/7417/commits/1a6d4a149af32ae96211385a18158ac1bc5f94a3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
image
See how the line is drawn above the point on the left side but the point is drawn above the line on the right, it's not hard to select the point but sometimes the edge is selected when I would have expected the point. Like I said it's still a major improvement over the current state.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7417">pipeline status</a> for feature branch [PR_7417](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7417). Pipeline [627373412](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/627373412) was triggered at [2b41db5](https://github.com/FreeCAD/FreeCAD/pull/7417/commits/2b41db561c5e1296184c05c1ad33cc6889500641). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
> To clarify this is sketch in edit mode from the backside but the 3d view is somewhat rotated

OK I see. Same happens in front side too in similar conditions, so it's at least a different problem. I guess it comes from Coin. We could increase Z-shifts, but at some point it may lead to strange visualization for ones dealing with tiny sketches (in the range of µm).

I added 3 commits so now section view adapts to view side.

**Comment by adrianinsaval** [comment]
nice, I did a quick test and seems to work very well, it updates immediately when you rotate enough. Thanks for your great work!

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7417">pipeline status</a> for feature branch [PR_7417](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7417). Pipeline [632033801](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/632033801) was triggered at [563abd9](https://github.com/FreeCAD/FreeCAD/pull/7417/commits/563abd93a24985666a46b83985564ba6504b61ca). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@0penBrain , since it fixes a long-standing bug, can this be backported to 0-20?

**Comment by 0penBrain** [comment]
> @0penBrain , since it fixes a long-standing bug, can this be backported to 0-20?

I guess technically it could be backported. Though I have no clue if this matches FC policy to do it. ;)
To me, it wasn't a bug but a limitation, and this PR is rather a feature improvement than a bug fix.
I let you (core developers) decide whether it should be backported or not. I can support if needed.

**Comment by 0penBrain** [comment]
> Can you please add it to the new features in our Wiki page:

Will do by the end of the week

**Comment by 0penBrain** [comment]
@donovaly Release notes are updated

**Pull request merged**
