### PR TITLE
[v0.21] Qt6: Fix build issues

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berniev** [comment]
For completeness, there are 19 more occurrences of `QGenericReturnArgument(),` which could be removed here (or later)

**Comment by wwmayer** [comment]
Out of curiosity can you upload your QMetaObject.h file, please? I wanted to check which overloaded versions of invokeMethod are available on your Qt version.

**Comment by berniev** [comment]
[qobjectdefs.h.zip](https://github.com/FreeCAD/FreeCAD/files/12016575/qobjectdefs.h.zip)
[QMetaObject.zip](https://github.com/FreeCAD/FreeCAD/files/12016586/QMetaObject.zip)

**Comment by wwmayer** [comment]
https://forum.freecad.org/viewtopic.php?p=692779#p692779

**Comment by chennes** [comment]
@wwmayer do you need another reviewer to look at this, or is it good to go?

**Comment by wwmayer** [comment]
The PR can be merged

**Pull request merged**
