### PR TITLE
Better Thumbnail quality by oversampling hires screenshot

### PR DESCRIPTION
**Pull request by MatthiasWM**
See issue  #7501

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`
---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7515">pipeline status</a> for feature branch [PR_7515](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7515). Pipeline [648025309](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/648025309) was triggered at [80d7f4d](https://github.com/FreeCAD/FreeCAD/pull/7515/commits/80d7f4db79bf571dca5767262e2eaaccd8088089). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@wwmayer do you mind weighing-in on this PR ?

**Comment by wwmayer** [comment]
Creating a 4x4 bigger image and scaling it down solves the anti-aliasing issue. But this can also be done directly by changing the third argument of imageFromFramebuffer() from 0 to 4.

Both methods produce an image of much better quality but there is a small difference: the lines of your method are very thin while with the other method they are rendered normally.

For solid objects it's probably not a problem but when you save a sketch the it might be hardly visible.

**Comment by MatthiasWM** [comment]
Makes sense. I will try that out when I have the time and update the PR.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7515">pipeline status</a> for feature branch [PR_7515](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7515). Pipeline [652249401](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/652249401) was triggered at [0fce6a0](https://github.com/FreeCAD/FreeCAD/pull/7515/commits/0fce6a0fdae277cfb68ec063a48f9e6a9fe17416). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7515">pipeline status</a> for feature branch [PR_7515](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7515). Pipeline [652251815](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/652251815) was triggered at [75db072](https://github.com/FreeCAD/FreeCAD/pull/7515/commits/75db0727957ce5bbd29b29cc7161fabae7be2735). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
It looks like this fixes a bug. Therefore i would backport this PR for FreeCAD 0.20.2. OK or objections?

**Pull request merged**
