### PR TITLE
Travis CI: Use flake8 to find Python syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This generates a lot of errors in obsolete or not yet used files which will make all our builds fail. I'll have a run at fixing these issues, but it's better not to merge this right now

**Comment by yorikvanhavre** [comment]
```
flake8 . --count --select=E901,E999,F822,F823 --show-source --statistics        
./build/py2/Mod/Import/automotive_design.py:2353:54: E999 SyntaxError: invalid syntax
		eval_wr1_wr = ((SIZEOF(self.self.styles)  ==  1) XOR (SIZEOF(None)  ==  0))
                                                     ^
./build/py2/Mod/Import/ifc4.py:10588:63: E999 SyntaxError: invalid syntax
		eval_axisandrefdirprovision_wr = ( not (EXISTS(self.axis) XOR EXISTS(self.refdirection)))
                                                              ^
./build/py2/Mod/Import/ifc2x3.py:8809:44: E999 SyntaxError: invalid syntax
		eval_wr5_wr = ( not (EXISTS(self.axis) XOR EXISTS(self.refdirection)))
                                           ^
./build/Mod/Import/automotive_design.py:2353:54: E999 SyntaxError: invalid syntax
		eval_wr1_wr = ((SIZEOF(self.self.styles)  ==  1) XOR (SIZEOF(None)  ==  0))
                                                     ^
./build/Mod/Import/ifc4.py:10588:63: E999 SyntaxError: invalid syntax
		eval_axisandrefdirprovision_wr = ( not (EXISTS(self.axis) XOR EXISTS(self.refdirection)))
                                                              ^
./build/Mod/Import/ifc2x3.py:8809:44: E999 SyntaxError: invalid syntax
		eval_wr5_wr = ( not (EXISTS(self.axis) XOR EXISTS(self.refdirection)))
                                           ^
./src/Tools/ArchiveNameFromVersionHeader.py:19:50: E999 TabError: inconsistent use of tabs and spaces in indentation
	   version[tokens[1]] = tokens[2].replace('"',"")
                                                 ^
./src/Tools/wiki2qhelp.py:621:90: E999 SyntaxError: invalid syntax
    print "Warning! This script is obsolete. Use the scripts in the offlinedocs folder..."
                                                                                         ^
./src/Tools/generateTemplates/templateCPPFile.py:12:30: E999 SyntaxError: invalid syntax
    print "Generate() App Dir"
                             ^
./src/Tools/offlinedoc/buildwikiindex.py:63:56: E999 SyntaxError: invalid syntax
            if VERBOSE: print "Reading existing list..."
                                                       ^
./src/Tools/offlinedoc/downloadwiki.py:140:33: E999 SyntaxError: invalid syntax
    if VERBOSE: print "crawling ", URL, ", saving in ", FOLDER
                                ^
./src/Tools/offlinedoc/buildqhelp.py:55:63: E999 SyntaxError: invalid syntax
        print "Error: QAssistant not fully installed, exiting."
                                                              ^
./src/Tools/generateBase/generateDS.py:138:17: E999 SyntaxError: invalid syntax
        print msg
                ^
./src/Tools/generateBase/__exec_old.py:4:13: E999 SyntaxError: invalid syntax
    exec text in globals, locals            ^
./src/Mod/Import/App/automotive_design.py:2353:54: E999 SyntaxError: invalid syntax
		eval_wr1_wr = ((SIZEOF(self.self.styles)  ==  1) XOR (SIZEOF(None)  ==  0))
                                                     ^
./src/Mod/Import/App/ifc4.py:10588:63: E999 SyntaxError: invalid syntax
		eval_axisandrefdirprovision_wr = ( not (EXISTS(self.axis) XOR EXISTS(self.refdirection)))
                                                              ^
./src/Mod/Import/App/ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py:2587:54: E999 SyntaxError: invalid syntax
		eval_wr1_wr = ((SIZEOF(self.self.styles)  ==  1) XOR (SIZEOF(None)  ==  0))
                                                     ^
./src/Mod/Import/App/ifc2x3.py:8809:44: E999 SyntaxError: invalid syntax
		eval_wr5_wr = ( not (EXISTS(self.axis) XOR EXISTS(self.refdirection)))
                                           ^
./src/Mod/Assembly/DevAssembly.py:3:47: E999 SyntaxError: invalid syntax
print "Script to test the assembly development"
                                              ^
./src/Mod/TechDraw/moveViews.py:21:64: E999 SyntaxError: invalid syntax
        print "Please select 1 Drawing Page and 1 TechDraw Page"
                                                               ^
./src/Mod/Path/PathScripts/post/fablin_post.py:119:24: E999 TabError: inconsistent use of tabs and spaces in indentation
	    SHOW_EDITOR = False
                       ^
./src/Mod/Path/libarea/kurve/test.py:9:7: E999 SyntaxError: invalid syntax
print p.x,  p.y      ^
./src/Mod/OpenSCAD/OpenSCADUtils.py:72:19: E999 SyntaxError: cannot mix bytes and nonbytes literals
        ascript = (b'tell application "Finder"\n'
                  ^
./src/Mod/Arch/importGBXML.py:92:117: E999 SyntaxError: invalid syntax
                    FreeCAD.Console.PrintError(translate("Arch","Error: Space '%s' has no Zone. Aborting.")+ "\n" + % space.Label)
                                                                                                                    ^
24    E999 SyntaxError: invalid syntax
24
```

**Comment by cclauss** [comment]
I count 17, not 24...  The Travis CI tests pass again because the Python 3 flake8 test is temporarily run in __allow_failures__ mode.

**Comment by cclauss** [comment]
@yorikvanhavre Can we please remove the __on hold__ label on this PR.  The tests are now run in __allow_failures__ mode so they no longer halt the build and their output is helpful to contributors as we work on PRs to achieve compatibility.

**Comment by yorikvanhavre** [comment]
But if they don't fail the build, is it really so interesting? Nobody will likely see the output. Isn't it better to fix those errors first? Most are easy to fix, we just need to solve the XOR mystery...

**Comment by cclauss** [comment]
You and I will see the errors and once we have fixed them all we can just remove the allow_failures.

**Comment by cclauss** [comment]
The following corresponds to the our current state of affairs with the Python 3 and macOS builds.

_[allow_failures] lets you add in experimental and preparatory builds to test against versions or configurations that you are not ready to officially support._

https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail

**Comment by cclauss** [comment]
Current stats on Python 3.7m
```
6     E999 SyntaxError: invalid syntax
584   F821 undefined name 'long'
590
```

**Comment by sasobadovinac** [comment]
I would disable the osx build for now. It was disabled for the reason not to use Travis resources while the osx building is getting fixed.

**Comment by sasobadovinac** [comment]
I have also canceled few appveyor builds for this pull request since it is not related to it

**Comment by cclauss** [comment]
Why use Appveyor at all?  Why not https://docs.travis-ci.com/user/reference/windows

**Comment by sasobadovinac** [comment]
There was no Windows environment on Travis when we started. It is still sort of beta and I guess no one has yet find the time to test if it work for us...

**Pull request merged**
