### PR TITLE
Removed unnecessary float casts

### PR DESCRIPTION
**Pull request by mosfet80**
removed unnecessary casts

### CODE REVIEW

**Comment by xtemp09** [comment]
```cpp
auto root = (float)(sqrt(2.0)/2.0);
```


`root` is float here.


```cpp
auto root = sqrtf(2.0)/2.0;
```


Here, `root` is double. Would it better to write:


```cpp
const float root = sqrtf(2.0f) / 2.0f;
```


to get rid of the lint warnings?

**Comment by yorikvanhavre** [comment]
@mosfet80 could you adress @xtemp09 's observations? Also we think the example python code should not be removed because it explains the magic numbers right after

**Comment by xtemp09** [comment]
@yorikvanhavre, as you have commented recently, these examples should be added to the documentation or added in doxygen-style annotation.

**Comment by mosfet80** [comment]
> And, actually, compilation errors.
> 
> ```
> /home/runner/work/FreeCAD/FreeCAD/src/Gui/Camera.cpp:109:13: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
>     return {root, 0, 0, root};
> ```

Some compilers promote the result to double when "double=float/double" operation is performed. I solved the problem by adding an "f" to the number so as to transform the double into a float.
with this modification we will have that:float=float/float

**Comment by yorikvanhavre** [comment]
@xtemp09 in this case this commented python code is not an example but an explanation of the magic numbers right after. So they should stay at that position, and there is not much necessity of them being added to the documentation

**Comment by yorikvanhavre** [comment]
Sorry I tried to fix this on my side but something goes wrong... I'll cherry-pick the commits

**Comment by yorikvanhavre** [comment]
Superseded by #11772

**Pull request closed without merging**
