### PR TITLE
Part design py

### PR DESCRIPTION
**Pull request by DeepSOIC**
Opens PartDesign to be extended with Python.
(added PartDesign::FeaturePython object type)

### CODE REVIEW

**Comment by DeepSOIC** [comment]
There is a potential for problems with using PartGui::ViewProviderPython instead of PartDesign... I think I need to fix it.

**Comment by yorikvanhavre** [comment]
So we wait before merging?

**Comment by DeepSOIC** [comment]
Yes, I think, wait.

**Comment by bblacey** [comment]
@DeepSOIC - I am in the midst of rolling out some inter-repo changes that will most like cause the macOS builds to fail for this PR.  I announced it in the Gitter room and will let you guys know when I am done.  Given the changes I am rolling out include a change to the Travis config, you may have to push a new, or at least an empty, commit to rebuild.

**Comment by DeepSOIC** [comment]
Looks like I'm done again, it's ready for review and merge. Also, keep an eye on @shaise to reply here: https://forum.freecadweb.org/viewtopic.php?f=22&t=20743&start=30

**Comment by bblacey** [comment]
@DeepSOIC - as predicted, the macOS builds failed because I was in the midst of making an inter-repo PR that required a travis config change, verification and merge (pre-coordinated with Yorik & Werner).  Those changes are now complete and merged to master so if you want a clean build of this PR branch, please do the following to rebase your PR branch with the travis changes and force a rebuild:
```
git checkout master
git fetch upstream master
git merge --ff-only upstream/master
git checkout PartDesignPy
git rebase master
git push -f origin PartDesignPy
```

**Comment by DeepSOIC** [comment]
rebased

**Comment by yorikvanhavre** [comment]
Didn't know you could add some smileys to github now... How ridiculous, is this a social network or what :) Ok, I'll wait for the appveyor to complete and do the merge

**Comment by yorikvanhavre** [comment]
merged

**Comment by shaise** [comment]
I can confirm it works well with SheetMetal WB (Branch V0.17)

**Comment by DeepSOIC** [comment]
Awesome, thanks to all!

**Pull request closed without merging**
