### PR TITLE
Path: Adaptive work

### PR DESCRIPTION
**Pull request by bryanbendall**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by bryanbendall** [comment]
Discussion:
https://forum.freecadweb.org/viewtopic.php?f=15&t=53371

**Comment by Russ4262** [comment]
Welcome to the project!
Please tag the PR titles with a leading workbench marker such as "[PATH], [Path], Path:, or PATH:" so reviewers can easily identify which PRs to review based on their involvement with the project.  This also helps passersby to know to which workbench a PR pertains.

Thanks,
Russell

**Comment by Schildkroet** [comment]
I already mentioned in the forum, that we have a "leave stock" option.

**Comment by bryanbendall** [comment]
I changed the title Russell, sorry I thought I had done that. Still getting used to this.

Schildkroet, I know that we have that but that is not the point of this. Please see the rest of the post.

**Comment by Schildkroet** [comment]
> Ive seen this before so that you can finish it with a different and sharper tool.

Thats exactly what "leave stock" does. It leaves some stock to finish it with a differnt tool/OP

**Comment by bryanbendall** [comment]
Schildkroet, I added to the post, please look at it. I hope you can see the difference.

**Comment by Russ4262** [comment]
@bryanbendall  May I suggest a rebase on current master so that Travis can verify build without errors.  MLampert submitted a PR to fix Travis failure in Path tests and Sliptonic merged it yesterday.

**Comment by bryanbendall** [comment]
@Russ4262 did I get that correct? I still have some trouble working with git

**Comment by Russ4262** [comment]
Afternoon sir.
Just FYI, I am very ignorant when it comes to Git.  I am using GitKraken as my source manager.  I do know, from many past attempts, that there are multiple ways to bring a branch current.  From my end, it looks like you merged the upstream/master into your branch, rather than rebasing on upstream/master.  But I could be incorrectly interpreting what I am seeing. lol.  Nonetheless, what you did should yield the same result as far as the code is concerned.

I had a whole lot of help from senior users `Sliptonic` and `MLampert` in the beginning.  I am confident that user Vocx-fc can help as well. Early on I made a mess of the Git history and my usage was horrible.  They helped me at least get to a level they can tolerate - God bless those guys.

**Comment by Russ4262** [comment]
I just initiated a cloning of your repo.  When finished, I will build and run a few tests to support your effort.  If it merges beforehand, good deal.

**Comment by bryanbendall** [comment]
Thats great Russ, if you have any questions let me know. Hope it all works.

**Pull request merged**
