### PR TITLE
BSpline Curve and Surface approximate

### PR DESCRIPTION
**Pull request by tomate44**
Replaces PR 604
- fixes BSplineCurve approximate sometime failing with smoothing algorithm
- adds Parametrization and smoothing algorithm to BSplineSurface approximate

### CODE REVIEW

**Comment by tomate44** [comment]
In the smoothing algorithm of the function approximate of BSplineCurve and BSplineSurface, I disabled the continuity auto-correction, following DeepSOIC's comment here : https://forum.freecadweb.org/viewtopic.php?f=17&t=21191#p164431

**Comment by yorikvanhavre** [comment]
@wwmayer if you could have a look, I'm not too comfortable with bspline code. Also experimenting with the "request review" function :)

**Comment by wwmayer** [comment]
I will have a look at it soon. Was too busy with other stuff in the past few days.

**Comment by tomate44** [comment]
Werner, Yorik,
No hurry on this one.
It is of lowest priority and importance.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
