### PR TITLE
[Arch] IFC (structural view) export for slab

### PR DESCRIPTION
**Pull request by balrobs**
adds support for this features:
- IFC export for StructuralSurfaceMembers (ATM only slabs)
- IFC export for RelConnectsStructuralMember [connection between structural members (linear/surface) and structural connection (punctual/linear)]
minor code changes:
- improve variable names
- improve code readability (I hope so!)

I'm new to Python and also to IFC so I'm totaly aware that this changes could have been done much better and probably need some further testing but I can confirm they are working right now for me.
If this pull request should be improved or even rejected I am open to it.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by balrobs** [comment]
I forgot to x-post to the corrisponding forum post:
https://forum.freecadweb.org/viewtopic.php?f=39&t=54286&start=20#p507149

**Comment by berndhahnebach** [comment]
great stuff ...

just some hint for further PRs. Generally it is much better if you would split the changes:
- one commit on the existing code which does the code formating for better readability
- one commit for the change

Code formating looks like big changes but nothing raeally should change. It is much simpler to see what really changed than. 

I will have a look

cheers bernd

**Comment by yorikvanhavre** [comment]
Okay this looks good (although I have no real way to test :) )
I understand by the forum thread that you might want to work more on it @balrobs ? Tell when you see it good for merging!

**Comment by balrobs** [comment]
I realized that my pull request has some issues probably due to IFC version problems.
I have to investigate more and will tell if and when IMO this pull request can be merged.
In the meantime I submitted another pull request that solved some problems when exporting structures to IFC2X3.
I think that it make sense to merge it before I continue with the structural view export of slabs.

**Comment by berndhahnebach** [comment]
> In the meantime I submitted another pull request that solved some problems when exporting structures to IFC2X3.
> I think that it make sense to merge it before I continue with the structural view export of slabs.

this one https://github.com/FreeCAD/FreeCAD/pull/4841 ?

**Comment by berndhahnebach** [comment]
was replaced by https://github.com/FreeCAD/FreeCAD/pull/4841

**Pull request closed without merging**
