### PR TITLE
fix some warnings

### PR DESCRIPTION
**Pull request by ppphp**
a cmake string quotes
a float mark
a character replacement

### CODE REVIEW

**Comment by 3x380V** [comment]
Why is '°' sign replaced with text? The patch seems as a bunch of random changes without any explanation. Care to explain them?

**Comment by ppphp** [comment]
> Why is '°' sign replaced with text? The patch seems as a bunch of random changes without any explanation. Care to explain them?

It fixes some warning issues on msvc.

Degree sign shows tofu on my system and bump warning
[build] D:\FreeCAD\src\Mod\Sketcher\Gui\SnapManager.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
It means "The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss"

`points` is a `std::vector<Base::Vector3f>` but we push int without suffix into it. It will bump warning
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\xmemory(677): warning C4244: “参数”: 从“_Ty”转换到“float_type”，可能丢失数据

The string quote prevents from string REPLACE argument number problem(my versoin is cmake 3.26.0 rc6). It will fail when I make a clean and rebuild.

**Comment by 3x380V** [comment]
Huh... I though Microsoft abandoned whole concept of code pages decades ago and they are now used by legacy apps only.

Btw, why does compiler does not complain to other assignments to `Base::Vector3f` in the very same file? Anyway, these are perfectly legal.

+1 to cMake change.

**Comment by wwmayer** [comment]
> points is a std::vector<Base::Vector3f> but we push int without suffix into it. It will bump warning

The suffix should be `F` then, not `f`. Otherwise clang-tidy will raise a warning: readability-uppercase-literal-suffix

**Comment by chennes** [comment]
> It means "The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss"

I'd argue that the file's encoding is wrong, not that the degree symbol should be replaced -- I don't think we should have any `windows-1252` files in our repo.

**Comment by 3x380V** [comment]
That is local issue, git has no concept of encoding unless something like UTF-16 is used in which case it detects it as a binary blob.

**Comment by 3x380V** [comment]
That sounds reasonable. UTF-8 is standard for at least a decade now, so it is probably not worth doing anything on behalf just one IDE of many.
Besides, if you split your changes in two commits with appropriate commit messages, you are ready to go.
(note, that many people are commiting unrelated changes in single commit, but I consider such a commit history hard to read and understand. Choice is yours, after all I'm not the one merging PRs :))

**Pull request merged**
