### PR TITLE
App: Improved ParameterString::setValue performance by using std::string_view

### PR DESCRIPTION
**Pull request by Flast**
This PR relates #18124. I'm not familiar with parameter management but this PR improves performance by using std::string_view instead std::string: reduces allocating and copying.

I profiled with perf(1); just D&D dxf file and close FreeCAD:

baseline
```
# Children      Self  Command  Shared Object  Symbol                  
# ........  ........  .......  .............  ........................
#
    73.51%     0.00%  FreeCAD  Import.so      [.] CDxfRead::ReadLine()
            |
            ---CDxfRead::ReadLine()
               |          
                --73.28%--Import::ImpExpDxfRead::OnReadLine(Base::Vector3<double> const&, Base::Vector3<double> const&, bool)
                          |          
                           --73.13%--Import::ImpExpDxfRead::DrawingEntityCollector::AddObject(TopoDS_Shape const&, char const*)
                                     |          
                                      --69.58%--App::Document::addObject(char const*, char const*, bool, char const*, bool)
                                                |          
                                                 --19.49%--App::PropertyString::setValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

This PR
```
# Children      Self  Command  Shared Object  Symbol                  
# ........  ........  .......  .............  ........................
#
    70.35%     0.00%  FreeCAD  Import.so      [.] CDxfRead::ReadLine()
            |          
             --70.34%--CDxfRead::ReadLine()
                       |          
                        --70.06%--Import::ImpExpDxfRead::OnReadLine(Base::Vector3<double> const&, Base::Vector3<double> const&, bool)
                                  |          
                                   --69.84%--Import::ImpExpDxfRead::DrawingEntityCollector::AddObject(TopoDS_Shape const&, char const*)
                                             |          
                                              --65.63%--App::Document::addObject(char const*, char const*, bool, char const*, bool)
                                                        |          
                                                         --10.80%--App::PropertyString::setValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
                                                                   App::PropertyString::setValue(char const*)

```

### CODE REVIEW

**Comment by maxwxyz** [comment]
@kpemartin FYI

**Comment by wwmayer** [comment]
The algorithm to create unique names still has a runtime of O(n^2) while the solution of @kpemartin has a runtime of O(n).

**Comment by kpemartin** [comment]
@wwmayer I agree. This change makes a tiny dent in time but still leaves the O(n^2) algorithm. I had a look at the changes (on my phone, Xmas vacations...) but did not really find any minor improvements to add to my PR

**Comment by Flast** [comment]
IIUC #18589 is going improve `getUniqueObjectName`, and `setValue` performance issue still exists, right?

**Comment by Flast** [comment]
Ah, OK, https://github.com/FreeCAD/FreeCAD/pull/18676/files#diff-5ad53cc6f40d2529890be512be95fac89dd0a811b9f2be1c6a057a8dfa2c5ec9 shows that entire `setValue` will be updated. I close this PR.

**Pull request closed without merging**
