### PR TITLE
Fix part of #2504 - revolve and groove failed to apply to faces

### PR DESCRIPTION
**Pull request by usakhelo**
This should fix failing Revolve and Groove when applied to selected faces.

Discussion is [here](https://forum.freecadweb.org/viewtopic.php?f=19&t=21182).

Issue is [here](https://freecadweb.org/tracker/view.php?id=2504)

P.S. I did it again - closed and re-opened the same issue. Sorry, didn't want to have opened issue hanging around for long time. Should probably have it opened until resolved.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
@ickby @usakhelo will a unit test be added, as discussed on the forum? If so, better to add it to this PR...

**Comment by usakhelo** [comment]
Yes, I'll add unit tests for sure.

**Comment by luzpaz** [comment]
@usakhelo can you edit your original git commit to [link this PR to the mantis ticket](https://www.freecadweb.org/wiki/Tracker#Attaching_a_git_commit_to_a_ticket):
Example on a separate line: `issue #2504`

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
