### PR TITLE
add doc and a couple of new methods to MakePipeShell

### PR DESCRIPTION
**Pull request by tomate44**
This PR adds some doc to the Part.BRepOffsetAPI.MakePipeShell class.
It also adds 3 new methods :
- setMaxDegree(degree)
- setMaxSegments(num)
- setForceApproxC1(bool)

### CODE REVIEW

**Comment by wwmayer** [comment]
Fails with older OCC versions. Make sure to protect this with a version check and for older OCC version that doesn't offer the methods raise an exception.

**Comment by tomate44** [comment]
Hi Werner,
Oops, OK, I'll check this tomorrow.
Thanks

**Comment by tomate44** [comment]
I added the OCC version check.
I hope this is good now.

**Comment by wwmayer** [comment]
Merged.

> I hope this is good now.

Yes, unless that type error doesn't really match. I have replaced it with runtime error.

**Comment by tomate44** [comment]
OK, I see that.
Thanks a lot.

**Pull request closed without merging**
