### PR TITLE
[TD]add alignment grid to page

### PR DESCRIPTION
**Pull request by WandererFan**
This PR adds an alignment grid function to Pages and adds associated preferences.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6465">pipeline status</a> for feature branch [PR_6465](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6465). Pipeline [480389238](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/480389238) was triggered at [d5a49da](https://github.com/FreeCAD/FreeCAD/pull/6465/commits/d5a49da9951c95ac4617c5eef18170c32b615ca0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by FlachyJoe** [comment]
Hi!
It fails to make:
```
In file included from /home/git/FreeCAD/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:64:
/home/git/FreeCAD/src/Mod/TechDraw/Gui/QGVPage.h:187:18: error: field ‘m_gridPath’ has incomplete type ‘QPainterPath’
  187 |     QPainterPath m_gridPath;
      |                  ^~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmessagebox.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMessageBox:1,
                 from /home/git/FreeCAD/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:25:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
```

> Package: qtbase5-dev
> Architecture: amd64
> Version: 5.15.2+dfsg-12ubuntu1.1

**Comment by donovaly** [comment]
Fixed: https://github.com/FreeCAD/FreeCAD/commit/4184218

**Comment by WandererFan** [comment]
Thank you.  Wonder why it builds here?

**Pull request merged**
