### PR TITLE
[Std_SendToPythonConsole] add variables 'doc' and 'elts', clear any v…

### PR DESCRIPTION
**Pull request by mwganson**
…ariables from previous run

Still only 1 object is supported, but now multiple subobjects from the same object is allowed.

Variables now will be:

doc = document containing selected object
obj = selected object
shp = obj.Shape
elt = first selected subobject, if any (Gui.Selection.getSelectionEx()[0].SubObjects[0]
elts = list of all subobjects selected

This would allow, for example, to select the edges of a wire in a closed sketch, then Ctrl+Shift+P, then into the console:

```
wire = Part.Wire(elts)
face = Part.makeFace(wire, "Part::FaceMakerCheese")
f = doc.addObject("Part::Feature","Face")
f.Shape = face
```
Or you could select the faces and do:

```
shell = Part.Shell(elts)
solid = Part.Solid(shell)
Part.show(solid,"solid")
```

Or select some vertices and:

`Part.show(Part.makeCompound(elts),"vertices")`

### CODE REVIEW

**Comment by luzpaz** [comment]
@mwganson quick question, where are we documenting this?

**Comment by adrianinsaval** [comment]
sounds like a good addition but why elt and elts? I don't understand those names and it's easier to remember when you understand what they mean

**Comment by yorikvanhavre** [comment]
This is a highly welcome change, thanks!!
I kind of like having both elt and elts... really, why not both, it's quite self-explaining, one is a single element, the other is a list of elements

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5375">pipeline status</a> for feature branch [PR_5375](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5375). Pipeline [446454470](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/446454470) was triggered at [97e380c](https://github.com/FreeCAD/FreeCAD/pull/5375/commits/97e380c48920d71ec813284256990e0d78b78152). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
Oooh so elt stands for element? maybe sobj is a better name since they are called subobjects? It's probably fine either way.

**Comment by Syres916** [comment]
I definitely prefer sobj to elt.

**Comment by mwganson** [comment]
I don't have strong feelings on the names, just so they're short and easy to type.  The name elt was already being used, so I kept it.  The big thing for me is I dislike having to type out App.ActiveDocument all the time.

**Comment by mwganson** [comment]
> @mwganson quick question, where are we documenting this?

https://wiki.freecadweb.org/Std_SendToPythonConsole

**Comment by yorikvanhavre** [comment]
obj, sobj, sobjs would be fine for me too... The main thing IMHO is to keep it short so it's easy to type.

**Comment by mwganson** [comment]
How about sub and subs?

**Comment by mwganson** [comment]
I tried to rebase, but did it wrong.  I think I know what I did wrong, but not how to fix it.  Now there is all kinds of other stuff in here.  I'll close and start a new PR.

**Pull request closed without merging**
