### PR TITLE
[Core] Status bar : reduce number of decimals

### LINKED ISSUE #10837: [Problem] Status messages precisions of doubles is too high
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

image
It has been said on the forum before at several places.
The precision of double values is needlessly high in status messages, which reduce readability and serve no purpose as far as I know.
I suggest reducing the number of decimals to 1 or 2 max so that it will be much more readable and will clutter less the view.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fixes #10837

@wwmayer can you give your opinion on this ? Also if you have an idea where we could put a function to avoid this 3 time copy paste.

Thanks

### CODE REVIEW

**Comment by PaddleStroke** [comment]
By the way there has been a feature request before to show more useful information about the (pre)selected element. Such as volume (/weight) for solids, length for edges, positions for vertexes. Area for surfaces. Radius for arc/circle and so on.

**Comment by wwmayer** [comment]
> Also if you have an idea where we could put a function to avoid this 3 time copy paste.

I think it's best to implement a helper class. See also: https://github.com/FreeCAD/FreeCAD/issues/10837#issuecomment-1806826459

> By the way there has been a feature request before to show more useful information about the (pre)selected element. Such as volume (/weight) for solids, length for edges, positions for vertexes. Area for surfaces. Radius for arc/circle and so on. But I can't find it anymore.

I don't know but this cannot be done with this helper class because it doesn't know anything about geometries of the Part module.

**Comment by PaddleStroke** [comment]
> I don't know but this cannot be done with this helper class because it doesn't know anything about geometries of the Part module.

So what would be the proper way then ? Best to make it right the first time.

Perhaps we should have a 'getObjectPreselectionMessage()' function in the base class of viewProvider so that it can be overriden by modules?

**Comment by wwmayer** [comment]
> So what would be the proper way then ? Best to make it right the first time.

The correct way is to implement a class in the PartGui module. But I wouldn't write this information to the status bar because it's too much information and for people with a rather small monitor the text might be truncated.

Instead I would implement a special task watcher that reacts on selection changes. This task watcher will add a widget to the task view that shows all needed information. As an example code have a look at the class MeshInfoWatcher from the MeshGui module.

**Comment by PaddleStroke** [comment]
> The correct way is to implement a class in the PartGui module. But I wouldn't write this information to the status bar because it's too much information and for people with a rather small monitor the text might be truncated.

I don't think the text is going to be so big. If you look at our current messages : 

> Preselected: docname.Part001.Body001.Pad002.Face14 (43.123456 mm, 39.123456 mm, 19.123456 mm)

A lot of this information is not useful. Actually the whole information is useless. What is the point of the mouse coordinates on the preselected face ? A message like the following would be much more useful : 

> Body001.Face14 (surface : 435.12 mm²)

Besides instead of message on preselection, it would be best to have a message on selection. This way we could also show meaningful information between several objects. For example : 

> Body001.Face14 - Body002.Vertex14 (distance: 120.12 mm)

**Comment by wwmayer** [comment]
> I don't think the text is going to be so big. If you look at our current messages :

But wouldn't this be additional text? Assuming you hover a cylindrical face then the displayed string might be something like:
Preselected: docname.Part001.Body001.Pad002.Face14 (43.123456 mm, 39.123456 mm, 19.123456 mm) Cylinder Base (45.000000, 40.00000, 19.123456) Axis (0.000000, 0.000000, 1.000000) Radius 10 Area 620.123456

> A lot of this information is not useful.

I wonder how you know this. If it's not useful for you it doesn't mean it's not useful for everybody else.

> This way we could also show meaningful information between several objects. For example :

And if 3, 4, 5 or more objects are selected? At some point it will become too complicated to show sensible information in the status bar. By using a task watcher instead this can be much better organized.

**Comment by PaddleStroke** [comment]
By the way I found the forum discussion about this : https://forum.freecad.org/viewtopic.php?style=4&t=80919

**Comment by wwmayer** [comment]
> If you know of use cases please share.

When developing algorithms or hunting bugs I very often need an easy way to get quickly some information about the current geometry. E.g. when moving over a planar face and observing which of the (x,y,z) value change I already know the normal.
Or recently I have fixed this bug 4c509c03efc6 and therefore knowing some basic information about the position of the shape was very useful.

**Comment by PaddleStroke** [comment]
I have : 
- changed to QString
- changed to UnitApi.

I have not : 
- Capped the number of decimals to 6 : I don't see any justification to do so. If the user is using 8 or 9 decimals, or even 16, he is probably in a special case and he may actually want to see the precision in the message.
- Create a helper class : I have done minimal modification which are not making the situation worse. It would be better to make a class yes, but as I want to tackle this again later to add more information, I don't want to do a temporary class now.

So I suggest we merge this as it is to solve the number of decimals. Then later we'll improve the message with more information.

**Comment by PaddleStroke** [comment]
> [ 69%] Building CXX object src/Gui/CMakeFiles/FreeCADGui.dir/SoFCSelection.cpp.o
> /home/runner/work/FreeCAD/FreeCAD/src/Gui/SoFCSelection.cpp:43:10: fatal error: Base/UnitsAPI.h: No such file or directory
>    43 | #include <Base/UnitsAPI.h>

I can't understand why linux doesn't build. The CI report says the header doesn't exist while it's correct. What is wrong here?

**Comment by PaddleStroke** [comment]
@wwmayer we could then keep the mouse position like so : 

> At (43.12 mm, 39.12 mm, 19.12 mm) : Body001.Face14 Radius 10.00 mm Area 620.12m²

But then this would mean we keep the messages on preselection rather than selection.

**Comment by 0penBrain** [comment]
> I can't understand why linux doesn't build. The CI report says the header doesn't exist while it's correct. What is wrong here?

Haa. Windows users and case sensitivity... 🙊

**Comment by wwmayer** [comment]
> Capped the number of decimals to 6 : I don't see any justification to do so.

The corresponding OpenInventor nodes and the API to get the picked point only supports floats which have a precision of 6 digits. So, showing numbers with more digits is pointless or even confusing because they won't be correct any more.

**Comment by PaddleStroke** [comment]
@0penBrain thanks!

@wwmayer thanks for the explanation, it makes perfect sense now.

**Comment by wwmayer** [comment]
Code Cleanup #11469

**Comment by PaddleStroke** [comment]
@wwmayer could you please elaborate on :

> The correct way is to implement a class in the PartGui module. 

I see what the class could look like, but where do I instanciate this class?

**Pull request merged**
