### PR TITLE
TPN: Modify `README.md` of toponaming branch to help orientate testers

### PR DESCRIPTION
**Pull request by luzpaz**
This README is purely for orientation. It should be omitted from being merged back in to master when the time comes.

Preview: https://github.com/luzpaz/FreeCAD/blob/toponaming/README.md

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049">pipeline status</a> for feature branch [PR_7049](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049). Pipeline [567096590](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567096590) was triggered at [c4f6475](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/c4f64750c8bbf263cc15d2c178e9f4f0a3dba742). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
got wizards, is there a way to automatically omit a certain file from being merged in a specific branch ?! (something like .gitignore I guess ?)

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049">pipeline status</a> for feature branch [PR_7049](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049). Pipeline [567159894](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567159894) was triggered at [0c510f5](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/0c510f591c13e639fca68910de716acfeb57efa3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049">pipeline status</a> for feature branch [PR_7049](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049). Pipeline [567160758](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567160758) was triggered at [5c52654](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/5c52654a15b57482bf338e7bf6fec21c5623f028). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049">pipeline status</a> for feature branch [PR_7049](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049). Pipeline [567166808](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567166808) was triggered at [3b15e99](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/3b15e9980a9c35d99ff421ada57493781f0d2940). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049">pipeline status</a> for feature branch [PR_7049](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049). Pipeline [567344747](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567344747) was triggered at [e670152](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/e670152f7cb7c2290bf4f8068d81fac60015ec0c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049">pipeline status</a> for feature branch [PR_7049](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049). Pipeline [567350868](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567350868) was triggered at [cf17910](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/cf17910d312bcb27fb39975bdc0da6fe511cad29). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049">pipeline status</a> for feature branch [PR_7049](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049). Pipeline [567351239](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567351239) was triggered at [6fae567](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/6fae567619596336d483c754d57ab2afeaf7941b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@AjinkyaDahale interesting. Is there a way to automate the script ?  
@realthunder is there a technique you use to avoid merging certain files ?

**Comment by yorikvanhavre** [comment]
I would modify the .gitignore file, and then maybe in the readme, indicate which files (README.md and .gitignore basically) should not be merged back at the end

**Comment by luzpaz** [comment]
@yorikvanhavre like this: [d4280bb](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/d4280bb13f0460fd839a5063cd430908b0ff3867) ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049">pipeline status</a> for feature branch [PR_7049](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7049). Pipeline [568056067](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/568056067) was triggered at [d4280bb](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/d4280bb13f0460fd839a5063cd430908b0ff3867). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
> @yorikvanhavre like this: [d4280bb](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/d4280bb13f0460fd839a5063cd430908b0ff3867) ? Or do I need to use a absolute path because this would ignore all README.md files ? So in that case: `./README.md`

No, because we still want the README (and the .gitignore) tracked. We just need a note (on the README I would say :) ) that says "before the final merge, please restore the following files from master: README.md, .gitignore,..."

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale interesting. Is there a way to automate the script ? @realthunder is there a technique you use to avoid merging certain files ? (ref: [#7049 (comment)](https://github.com/FreeCAD/FreeCAD/pull/7049#issuecomment-1159477825))

@luzpaz this is how I expect to do it:
1. Run `git rebase -i` (or whatever the command is, I do it via some tools). A file will be created with the list of commits like
```
keep <hash> One commit
keep <hash> Second commit
keep abcdef Edit Readme
.
.
.
keep <hash> Nth commit
```
2. Find that file (it should be documented somewhere how to), and run `sed` or something on it to make it
```
keep <hash> One commit
keep <hash> Second commit
drop abcdef Edit Readme
.
.
.
keep <hash> Nth commit
```
3. Repeat for any other commit and continue with the rebase.

This entire process should in principle be convertible to a bash file. I would be mindful that we are changing the entire branch though. Would definitely have to create a separate branch (say toponaming-pr) in the intermediate steps so that toponaming branch has this commit but master does not. So we'd have to do this every time we merge.

**Comment by luzpaz** [comment]
Can someone drop [d4280bb](https://github.com/FreeCAD/FreeCAD/pull/7049/commits/d4280bb13f0460fd839a5063cd430908b0ff3867) and merge this then ? (I screwed up my git repo trying to rebase)

**Comment by luzpaz** [comment]
I dropped the .gitignore commit. Please review https://github.com/luzpaz/FreeCAD/blob/toponaming/README.md

**Comment by luzpaz** [comment]
I'm proposing to merge the README changes. And remind the core devs that the README shouldn't be overwritten when:  
1. merging @realthunder's PRs
1. rebasing on master

**Comment by donovaly** [comment]
Why is wmayer listed as main developer? Did you contact him? To my knowledge he is not yet involved. The last time I spoke with him, he only wanted to see how the branch develops.

**Comment by donovaly** [comment]
Then I suggest to remove Werner unless you got his OK to put his name there in public.

**Pull request merged**
