### PR TITLE
[PartDesign] Add individual QString for menu text which exposes text to translation

### PR DESCRIPTION
**Pull request by Kuzma30**
…s 
https://github.com/FreeCAD/FreeCAD-translations/issues/125
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6821">pipeline status</a> for feature branch [PR_6821](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6821). Pipeline [529532053](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/529532053) was triggered at [e1e172b](https://github.com/FreeCAD/FreeCAD/pull/6821/commits/e1e172b5d39efbbb84ffc5e174239bd3f7a327fb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
`git commit  --amend -m "[PartDesign] Add individual QString for menu text which exposes text to translation" -m "Closes https://github.com/FreeCAD/FreeCAD-translations/issues/125"`

**Comment by Kuzma30** [comment]
Done. Thanks for text correction

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6821">pipeline status</a> for feature branch [PR_6821](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6821). Pipeline [529837072](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/529837072) was triggered at [92b3592](https://github.com/FreeCAD/FreeCAD/pull/6821/commits/92b3592589d1d18e55127ccfdb998c18d021b14d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
Regarding 'ViewProviderDatum' class, as it doesn't inherit 'QObject', it should be better to use 'Q_DECLARE_TR_FUNCTIONS' macro on it so then translation functions are available with the right context.

**Comment by Kuzma30** [comment]
It use QString without patch
https://github.com/FreeCAD/FreeCAD/blob/dc53e6dce1eb7f7a67d0f448355d92e4ac086d7f/src/Mod/PartDesign/Gui/ViewProviderDatum.h#L91-L93

**Comment by 0penBrain** [comment]
> It use QString without patch

Was this meant to be a reply to my remark ???

**Comment by Kuzma30** [comment]
Yes

**Comment by 0penBrain** [comment]
@Kuzma30 So I think you don't get it. ;)
Using `QObject::tr()` will generate translation strings without context (they will be pushed in an "unclassified" category) so it makes it hard for translator to now where they come from. Also it creates risk of collisions.
Setting `Q_DECLARE_TR_FUNCTIONS(class_name)` macro in the class declaration will add to it "contextualized" translate functions. So then you only use `tr()` function in the class implementation, and the translation strings will be extracted with an helpful usage context. ;)

**Comment by Kuzma30** [comment]
If I proper understand you
https://github.com/Kuzma30/FreeCAD/commit/d6f4f0847e2533b61f0e370c7b829c1dcaf19a78
https://github.com/Kuzma30/FreeCAD/commit/23d495d1a668529bd886602052d516264beaab20
If this correct, I will this to commit in [fix_issue_125](https://github.com/Kuzma30/FreeCAD/tree/fix_issue_125) branch.

**Comment by 0penBrain** [comment]
@Kuzma30 that's it :+1:

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6821">pipeline status</a> for feature branch [PR_6821](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6821). Pipeline [530809762](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/530809762) was triggered at [fe91c46](https://github.com/FreeCAD/FreeCAD/pull/6821/commits/fe91c4678b5f09da97dd0ec4480a8cc4a86927f4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks. Please tell me when this PR is ready. It should go in for FC 0.20.

**Comment by Kuzma30** [comment]
@donovaly I think this PR is ready

**Comment by donovaly** [comment]
Thanks. merging.

**Pull request merged**
