### PR TITLE
[Gui] Makes corner axis cross fully scalable by user

### PR DESCRIPTION
**Pull request by 0penBrain**
This PR :
* Adds 4 Python API methods to set+get corner axis cross visibility+size
* Modifies GL rendering of corner axis cross so labels and lines are nicely resizeable
* Adds corner axis cross size as a user preference in Display/3D View/General

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum => No changes introduced, just new abilities
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [X]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5182">pipeline status</a> for feature branch [PR_5182](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5182). Pipeline [411476336](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/411476336) was triggered at [473c6d5](https://github.com/FreeCAD/FreeCAD/pull/5182/commits/473c6d559eb07e22a47053f06f8eea6b4165202a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Code looks good to me but View3DInventorViewer.cpp shouldn't be cluttered up with the XPM images. Please put them into an extra header file.

**Comment by 0penBrain** [comment]
@wwmayer not really XPMs but anyway I get it. Actually I just placed the pixmaps where the bitmaps originally were. Will provide an update according your remark beginning of next week. ;)

**Comment by wwmayer** [comment]
> not really XPMs but anyway I get it.

How have you created them and what is the origin of them?

**Comment by chennes** [comment]
The comment in the code says
> // It is generated with Gimp using Bitstream Charter Bold font, 28 px, on transparent background
// It is then directy exported as C source type after image is vertically flipped for direct GL usage

**Comment by 0penBrain** [comment]
@wwmayer As @chennes wrote I tried to add in the comment above the pixmaps enough info so it can be replicated. I'll move this comment into the separate file too. Feel free to tell me if some details are missing. I'll add them also.

**Comment by 0penBrain** [comment]
@wwmayer PR updated according your remark Tell me if more needed

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5182">pipeline status</a> for feature branch [PR_5182](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5182). Pipeline [413453487](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/413453487) was triggered at [a1e7b76](https://github.com/FreeCAD/FreeCAD/pull/5182/commits/a1e7b76913006a2b3d3bac36c900a8735d704188). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
