### PR TITLE
Fedora fixes3

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
Can you also look into this? [FreeCAD 0.18.4 fails to build with vtk 9.0](https://forum.freecadweb.org/viewtopic.php?f=4&t=46934)

Apparently there were many changes in Vtk 9.0 so compilation fails. The thread's title mentions v0.18, but v0.19 was also tested.

**Comment by wwmayer** [comment]
OK, I will look into the vtk issue too.

**Comment by realthunder** [comment]
@wwmayer commit 6f8ca18 causes build failure on boost before 1.60. Maybe you can consider a work around [here](https://github.com/FreeCAD/FreeCAD/pull/3062/commits/8621553851d45a9fbce7376b4aec33f490fedfac).

**Comment by wwmayer** [comment]
Based on your idea I have implemented a less invasive solution that can be easily reverted once Xenial or other distros with old boost version will expire.

**Pull request merged**
