### PR TITLE
[PATH] Single wires also need to be able switch the orientation

### PR DESCRIPTION
**Pull request by sundtek**
Single wires might also need to be able to switch the orientation, this fixes CW/CCW for the Facing operation (basically anything that would reverse wires / the cutting path)
It was assumed that this is not needed, that's why the check was there.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5277">pipeline status</a> for feature branch [PR_5277](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5277). Pipeline [439264146](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/439264146) was triggered at [dc5d32f](https://github.com/FreeCAD/FreeCAD/pull/5277/commits/dc5d32f068aeec321889f19d8b3a201540bd967d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
What do you mean "fixes CW/CCW for the Facing operation"?   Is there a bug report?

**Comment by sundtek** [comment]
it just enables the option to fix this again. I mentioned it at some point in the chat that the "line" pattern is defacto zigzag.
To fix the line pattern in the facing operation the sorting needs to be disabled in the python script (this is not part of this patch). Zig-Zag won't care about CW/CCW, but the line operation should take care about CW/CCW.

I have noticed that the overall pattern generation is inefficient inside the cornes (lots of jumping around with G0).
I also talked with realthunder about it some time ago, it was just done the way it is because he didn't think that it's necessary.

**Comment by sliptonic** [comment]
Are you saying this PR fixes no bugs, introduces no new features and doesn't make performance faster?  Is it JUST in preparation for future work?  If that's true, then it is risking a regression bug for no reason.  Why not introduce the change when the supporting feature improvements are introduced?

**Comment by sundtek** [comment]
it doesn't add any regression, as mentioned I'm not satisfied with the line pattern itself I don't see that it makes any sense to fix the actual line pattern issue due to the inefficiency in the corners (I have done that on my side).
Moreover the line pattern should be evaluated and possibly rewritten to remove the G0 jumps, any more detailed work on it will require this modification anyway. Go step by step.

**Comment by sliptonic** [comment]
> it doesn't add any regression

How do you know? I know it runs but we have poor test coverage of PathArea.  

Does this patch, itself, fix a problem with line pattern?  If not, what is the wisdom of making a change that adds no benefit and risks regression?

If it is half of a fix, why not wait until both parts are ready?

**Comment by sundtek** [comment]
I'm using FreeCAD on a daily basis. I have modified thousands of lines here in order to be able to mill my object. The mainline FreeCAD path doesn't work at all for me since it's too slow and has other issues.

**Comment by pwnorbitals** [comment]
@sundtek Any news about the other modifications that go along with this PR ? Could help justify merging this one

**Comment by sundtek** [comment]
Hi,

no sorry and I don't have any further time to work on FreeCAD at the moment.
The ticket can be closed, I'll stay with my local version which can do what I need (I'm machining various aluminium parts).

BR,
Markus

**Pull request closed without merging**
