### PR TITLE
[TechDraw] Split up Cosmetic.cpp

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by benj5378** [comment]
Only took me 5 hours to through brute force how to do this.

While I can successfully compile, I can't test if CenterLine and CosmeticVertex still works due too `./bin/FreeCAD: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE` at startup. So if you could run FreeCAD and check for us (also, do you know this error???)

And btw, sorry for spoiling your Easter holidays 😉

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9195">pipeline status</a> for feature branch [PR_9195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9195). Pipeline [829399038](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/829399038) was triggered at [4fa9d02](https://github.com/FreeCAD/FreeCAD/pull/9195/commits/4fa9d02db28e751f75e80e7ea6d4cb25aa001503). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9195">pipeline status</a> for feature branch [PR_9195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9195). Pipeline [829580116](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/829580116) was triggered at [9fef1d9](https://github.com/FreeCAD/FreeCAD/pull/9195/commits/9fef1d9af4516d8f988202614fed7873c4b35ac9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by benj5378** [comment]
> I pushed a commit that seems to fix the issue. Is it ok for you?

Yeah yeah, no problem. Feel free to push if you tested that the centerline and cosmeticvertex still works. Else I can just test it: I found the reason to the symbol error: VS code terminal (wtf)

**Comment by benj5378** [comment]
OKay okay, looked good, centerline and cosmeticvertex still works

**Pull request merged**
