### PR TITLE
[Path] Job Type Selection

### PR DESCRIPTION
**Pull request by dubstar-04**
PR to track changes required to implement job types in the Path workbench.

Forum discussion: https://forum.freecad.org/viewtopic.php?t=80115

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
Hi @dubstar-04 how's the progress on this PR going ?

**Comment by luzpaz** [comment]
@dubstar-04 ping

**Comment by dubstar-04** [comment]
I'm progressing several turning related areas at once. I haven't done any work on this PR for a while but I will try and get back to it once the turning addon is released.

**Comment by maxwxyz** [comment]
@dubstar-04 will you come back to this PR? It needs a rebase after the Path/CAM rename.
If you want this draft PR to be considered for a version 1.0 release, it should be marked _ready for review_ by **Monday, 2024-06-03** at the latest. (further details in the 1.0 feature freeze [forum announcement](https://forum.freecad.org/viewtopic.php?p=759605#p759605)).

**Comment by dubstar-04** [comment]
This won't be ready for FreeCAD 1.0.

**Comment by maxwxyz** [comment]
@dubstar-04 will you work on this PR again?

**Comment by dubstar-04** [comment]
I currently don't have any time to work on FreeCAD related projects. I will close this PR.

**Comment by maxwxyz** [comment]
@spanner888 @sliptonic anyone else who could pick up this PR?

**Pull request closed without merging**
