### PR TITLE
Replace deprecated qt functions toList() & toSet()

### PR DESCRIPTION
**Pull request by shiftee**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ *]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ *]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ *]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ *]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ *]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ *]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ *]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Review by 0penBrain — CHANGES_REQUESTED** [review]
@shiftee you can't do this straight away. The constructors you are using have only been introduced in Qt 5.14, which isn't the minimal Qt version we are supporting (IIRC it's currently 5.9). You have to detect Qt version and use one or the other method depending on it.

**Comment by shiftee** [comment]
Sorry, I did a quick search but couldn't find the minimum Qt version and then forgot about it.
It should be sorted now

**Comment by 0penBrain** [comment]
Looks good to me. Didn't try to compile though.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5213">pipeline status</a> for feature branch [PR_5213](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5213). Pipeline [419733775](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/419733775) was triggered at [244877e](https://github.com/FreeCAD/FreeCAD/pull/5213/commits/244877e2e2977a81795b9aaf95ac8a3f0b9afb81). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> Looks good to me. Didn't try to compile though.

Thanks for the review. 
The CI compiled it and I can also compile -> merging

**Pull request merged**
