### PR TITLE
Tests: add zipios++ unit tests

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8807">pipeline status</a> for feature branch [PR_8807](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8807). Pipeline [801831854](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/801831854) was triggered at [64bd03a](https://github.com/FreeCAD/FreeCAD/pull/8807/commits/64bd03a79ae706124cc1640cc9ebc49dac725578). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8807">pipeline status</a> for feature branch [PR_8807](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8807). Pipeline [801834439](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/801834439) was triggered at [5cc262c](https://github.com/FreeCAD/FreeCAD/pull/8807/commits/5cc262ccfae6668404724e71dc71d2d790795a51). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
This PR breaks the compilation of the test target for me:

```
3>D:\FreeCADGit\src\App/PropertyLinks.h(1368,48): warning C4251: 'App::PropertyXLinkContainer::_XLinkRestores': class 'std::unique_ptr<std::vector<App::PropertyXLinkContainer::RestoreInfo,std::allocator<App::PropertyXLinkContainer::RestoreInfo>>,std::default_delete<std::vector<App::PropertyXLinkContainer::RestoreInfo,std::allocator<App::PropertyXLinkContainer::RestoreInfo>>>>' needs to have dll-interface to be used by clients of class 'App::PropertyXLinkContainer' (compiling source file D:\FreeCADGit\tests\src\App\Expression.cpp)
3>D:\FreeCADGit\src\App/PropertyLinks.h(1368,10): message : see declaration of 'std::unique_ptr<std::vector<App::PropertyXLinkContainer::RestoreInfo,std::allocator<App::PropertyXLinkContainer::RestoreInfo>>,std::default_delete<std::vector<App::PropertyXLinkContainer::RestoreInfo,std::allocator<App::PropertyXLinkContainer::RestoreInfo>>>>' (compiling source file D:\FreeCADGit\tests\src\App\Expression.cpp)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: __cdecl zipios::CollectionCollection::CollectionCollection(void)" (??0CollectionCollection@zipios@@QEAA@XZ) referenced in function "private: virtual void __cdecl Collection_TestValidity_Test::TestBody(void)" (?TestBody@Collection_TestValidity_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: bool __cdecl zipios::CollectionCollection::addCollection(class zipios::FileCollection const &)" (?addCollection@CollectionCollection@zipios@@QEAA_NAEBVFileCollection@2@@Z) referenced in function "private: virtual void __cdecl Collection_TestAdd_Test::TestBody(void)" (?TestBody@Collection_TestAdd_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: bool __cdecl zipios::CollectionCollection::addCollection(class zipios::FileCollection *)" (?addCollection@CollectionCollection@zipios@@QEAA_NPEAVFileCollection@2@@Z) referenced in function "private: virtual void __cdecl Collection_TestAdd_Test::TestBody(void)" (?TestBody@Collection_TestAdd_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: virtual void __cdecl zipios::CollectionCollection::close(void)" (?close@CollectionCollection@zipios@@UEAAXXZ) referenced in function "private: virtual void __cdecl Collection_TestValidity_Test::TestBody(void)" (?TestBody@Collection_TestValidity_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: virtual class std::vector<class zipios::SimpleSmartPointer<class zipios::FileEntry>,class std::allocator<class zipios::SimpleSmartPointer<class zipios::FileEntry> > > __cdecl zipios::CollectionCollection::entries(void)const " (?entries@CollectionCollection@zipios@@UEBA?AV?$vector@V?$SimpleSmartPointer@VFileEntry@zipios@@@zipios@@V?$allocator@V?$SimpleSmartPointer@VFileEntry@zipios@@@zipios@@@std@@@std@@XZ) referenced in function "private: virtual void __cdecl Collection_TestValidity_Test::TestBody(void)" (?TestBody@Collection_TestValidity_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: virtual class zipios::SimpleSmartPointer<class zipios::FileEntry const > __cdecl zipios::CollectionCollection::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum zipios::FileCollection::MatchPath)const " (?getEntry@CollectionCollection@zipios@@UEBA?AV?$SimpleSmartPointer@$$CBVFileEntry@zipios@@@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4MatchPath@FileCollection@2@@Z) referenced in function "private: virtual void __cdecl Collection_TestValidity_Test::TestBody(void)" (?TestBody@Collection_TestValidity_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2001: unresolved external symbol "public: virtual class std::basic_istream<char,struct std::char_traits<char> > * __cdecl zipios::CollectionCollection::getInputStream(class zipios::SimpleSmartPointer<class zipios::FileEntry const > const &)" (?getInputStream@CollectionCollection@zipios@@UEAAPEAV?$basic_istream@DU?$char_traits@D@std@@@std@@AEBV?$SimpleSmartPointer@$$CBVFileEntry@zipios@@@2@@Z)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: virtual class std::basic_istream<char,struct std::char_traits<char> > * __cdecl zipios::CollectionCollection::getInputStream(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum zipios::FileCollection::MatchPath)" (?getInputStream@CollectionCollection@zipios@@UEAAPEAV?$basic_istream@DU?$char_traits@D@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@W4MatchPath@FileCollection@2@@Z) referenced in function "private: virtual void __cdecl Collection_TestValidity_Test::TestBody(void)" (?TestBody@Collection_TestValidity_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: virtual int __cdecl zipios::CollectionCollection::size(void)const " (?size@CollectionCollection@zipios@@UEBAHXZ) referenced in function "private: virtual void __cdecl Collection_TestValidity_Test::TestBody(void)" (?TestBody@Collection_TestValidity_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: virtual class zipios::FileCollection * __cdecl zipios::CollectionCollection::clone(void)const " (?clone@CollectionCollection@zipios@@UEBAPEAVFileCollection@2@XZ) referenced in function "private: virtual void __cdecl Collection_TestClone_Test::TestBody(void)" (?TestBody@Collection_TestClone_Test@@EEAAXXZ)
3>collectioncollection.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl zipios::CollectionCollection::~CollectionCollection(void)" (??1CollectionCollection@zipios@@UEAA@XZ) referenced in function "private: virtual void __cdecl Collection_TestValidity_Test::TestBody(void)" (?TestBody@Collection_TestValidity_Test@@EEAAXXZ)
3>D:\FreeCAD-build\tests\Release\Tests_run.exe : fatal errror
```

**Comment by wwmayer** [comment]
Try adding BaseExport to CollectionCollection

**Comment by donovaly** [comment]
> Try adding BaseExport to CollectionCollection

Many thanks! This fixes it for me. I made a PR accordingly: #8835

**Pull request merged**
