### PR TITLE
[Path] fix flipEdge not taking into account FirstParameter and LastParameter…

### PR DESCRIPTION
**Pull request by jffmichi**
… for splines

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by jffmichi** [comment]
This PR fixes issue https://github.com/FreeCAD/FreeCAD/issues/8915.

When FirstParameter or LastParameter in edge differ from the respective values in spline, the values in the edge were not taken into account when returning the flipped edge.

All tests complete successfully but I would prefer if there were another set of eyes having a look at the proposed changes. Thank you.

**Comment by mlampert** [comment]
Could you add a unit test that exposes the issue and verifies that it's fixed?

**Comment by jffmichi** [comment]
Like so? Please tell me if you need something else 👍

**Review by mlampert — APPROVED** [review]
Great, thanks

**Pull request merged**
