### PR TITLE
[PartGui] Use Parameters for Measure labels font name and size

### PR DESCRIPTION
**Pull request by VM4Dim**
For customize the view measure labels
  to already used parameters:
-    Dimensions3dColor
-    DimensionsDeltaColor
-    DimensionsAngularColor

  it proposed to add:
-    DimensionsFontName
-    DimensionsFontSize

https://forum.freecadweb.org/viewtopic.php?f=3&t=69707

### CODE REVIEW

**Comment by luzpaz** [comment]
Is this feature proposed just for the Part WB ?

**Comment by VM4Dim** [comment]
This is implemented in Part
but once created, it remains visible in other WB

**Comment by adrianinsaval** [comment]
The tools are also shown in Part Design IIRC, if this gets merged please document it at the fine-tuning wiki page

**Comment by donovaly** [comment]
Many thanks, this is very welcome!
However, as you have read in the forum thread, a GUI for this is necessary.

So when the Part or PartDesign Workbench was once loaded, there should be a new tab in the Preferences under Display, called maybe "Measuring" and there the user can select the color, fontname and size.

Can you please add this?

p.s. since there are currently heavy code shits in master, please rebase your PR whenever you make a new commit (just for the next days).

**Comment by VM4Dim** [comment]
> So when the Part or PartDesign Workbench was once loaded, there should be a new tab in the Preferences under Display, called maybe "Measuring" and there the user can select the color, fontname and size.
> 
> Can you please add this?

I'll get on it.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7088">pipeline status</a> for feature branch [PR_7088](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7088). Pipeline [578986819](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/578986819) was triggered at [85f9a8d](https://github.com/FreeCAD/FreeCAD/pull/7088/commits/85f9a8dfb733b81b758e414b817305988beed389). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@VM4Dim hows the progress going? Are you figuring it out?

**Comment by donovaly** [comment]
No stress, we are all hobbyists and do tings when it is possible for us.

**Comment by VM4Dim** [comment]
@donovaly Thanks.

**Comment by VM4Dim** [comment]
out

**Comment by VM4Dim** [comment]
I can't change the commit.
New https://github.com/VM4Dim/FreeCAD/commit/705b8105620f725027b3cb6da6e4cc242be20500

**Comment by VM4Dim** [comment]
New PR #7148

**Pull request closed without merging**
