### PR TITLE
TechDraw: Fix View Spreadsheet with merged cells.

### PR DESCRIPTION
**Pull request by meapeteze**
Hello,
What this pull request fixes is explained here:
https://forum.freecadweb.org/viewtopic.php?f=35&t=58563
Regards,

Mikel

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Review by 0penBrain — COMMENTED** [review]
I'm not sure the fix is optimal as same line is already run in same loop / all conditions at https://github.com/FreeCAD/FreeCAD/blob/32cbd7fabc12834b7c51c046c3411b3e7ba40029/src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp#L279 then eventually overrode in some conditions here https://github.com/FreeCAD/FreeCAD/blob/32cbd7fabc12834b7c51c046c3411b3e7ba40029/src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp#L333

While the fix eventually works -- I didn't test -- it looks suboptimal to me.

**Comment by meapeteze** [comment]
My code understanding is very limited I should recognize...

My impressions:

The "cellheight" variable is used in line 359 to offset the next row and also seems to be used (I do not know where in the code) to assign the height of the row . The row can eventually be spanned so lines 326 to 336 calculates a sum of the "cellheight".

I somehow found that the correct value for the row offset is always, even for spanned rows, the original "cellheight" value without sum (line 279), while the spanned row height needs to be calculated as a sum.

Then, one option seems to use two distinct variables for offset and height and another option is what I propose, that is to recalculate the variable to the needed value before the corresponding usage in the code. The first option is doable but needs more code lines.

Another option with no added code line could be to substitute line 359 with 
`rowoffset = rowoffset + sheet->getRowHeight(address.row());`
but really, I have no idea if this type of expression is accepted (I can give a try but I would appreciate any opinion before).

As long as the variable "cellheight" seems to be used exclusively to fill cells from code line 261 to 364 in this file (I suppose that variables are local for the file... but I have no idea!), any of the options commented above seem to be safe.

**Comment by meapeteze** [comment]
Indeed

` rowoffset = rowoffset + sheet->getRowHeight(address.row());

on line 359 works as well.

I will make another pull request and it is up to you to decide what to do. I cannot do better.

**Comment by 0penBrain** [comment]
@meapeteze : please don't open another pull request. Let's discuss this one and find the better solution. I had no time looking at it right now but will ASAP. Maybe another one will join the discussion too

**Comment by meapeteze** [comment]
ups! I already did it.

**Comment by 0penBrain** [comment]
@yorikvanhavre This PR and #4806 was 2 exclusive solutions. I have no idea what merging both can do.

@meapeteze Please check that merging both of your PRs isn't bringing regression

**Pull request merged**
