### PR TITLE
Path: fix potential tool crash in boundaryDressup : #4260

### PR DESCRIPTION
**Pull request by J-Dunn**
avoid using fake machine position and inserting extra G1 before existing path data. This can produce arbitrary cut paths through safe space above SafeHeight and cause tool crash into clamps.
Fix skips comment lines in input but does assume first active lines are the standard G0 to clearance ht , then G0 to x,y above first real point in path, to recove a valid machine position. This seems to be uniform in Path WB path tools. Merger should consider if this is always valid.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by J-Dunn** [comment]
I agree in principal, however the whole way boundarydressup is written involves converting all moves and cuts to edges which in the case of first move requires knowledge of the machine position which is not available from the path data which is being processed. It seems this cannot be known until commands which include explicit x,y,z values have been processed. That information is provided by the initial safety move and G0 to the safe space above the first point of the first actual cut in the path being processed. 

I don't like the fact the present solution makes assumptions but it seems better than the present ( almost certainly false ) assumption that the machine position is 0,0,0 and the potentially dangerous results. 

I'm well aware of this short-coming but lack wider knowledge of FC and the potential content of all possible path tool output which need to be processed by this dressup.

Please correct me if I'm wrong but I don't think that there is any defined spec. for how the various path commands work or what they should or do produce. Maybe this is what is needed. If there was a defined behaviour this would no longer be an assumption. 

It seems that all the 2.5D AreaOps work like this, can you point me to what other cases do not work this way so that I can get a more general idea of what is required?

**Comment by sliptonic** [comment]
Can we get an update on this PR?   What's the status?  What are the outstanding questions?

**Comment by J-Dunn** [comment]
The key problem is that the machine position is unknown and unknowable at the start of processing. 

I developed a method to recover position and avoid ill-defined moves but it needs to assume that what the first two lines of code are.  As mlampert points out this is less than ideal but if the only info dressup has is the path itself I can't see a way around this problem. 

I asked if those with a better knowledge could confirm that all existing paths follow this pattern and I'm still awaiting a response on that. 

If this does not produce problems now ( and we need to check 3D stuff too ) then making this a formal specification for path tools would make this solution robust.  Again that solution is awaiting comment. 

The idea that the first thing a path tool does is move vertically to safe space seems to be a de facto standard, maybe it could be formalised. 

I could bring the patch up to date but I need input on how we are going to handle this first.

**Comment by mlampert** [comment]
The correct way to deal with this issue is for the dressup to only
emit parameters which have already been specified by the op.

So if X hasn't been set by the op then the dressup should also not set X
in any commands it generates. Once the op sets X the dressup can
manipulate it.

**Comment by J-Dunn** [comment]
Agreed. That is the ideal way to treat the problem. However that will require considerable rewriting of the code by someone with fuller understanding of all inside/outside code and incorrect ordering of path segments that goes on in the various other sections of FC that get called here. That is more time than I have to throw at it.

**Comment by luzpaz** [comment]
Please post a forum link discussing this PR further.

**Comment by J-Dunn** [comment]
Please post a forum link discussing this PR further.
#4260


> Please post a forum link discussing this PR further.

There is  a bug ref in the title, this points to forum post IIRC.

**Comment by luzpaz** [comment]
@J-Dunn Thanks. As a courtesy to testers and devs please also add links to the forum thread in the summary. Also please familiarize yourself with https://wiki.freecadweb.org/tracker#GitHub_and_MantisBT

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=15&t=42820

**Comment by J-Dunn** [comment]
What way can this be moved ahead? 

The current code invents a fake m/c position 0,0,1 and creates an edge to the first real x,y point . This edge gets converted to a new path segment which was not in the original path. This is the origin of the bug.

The rest of the loop seems to work fine, it is just the initialisation which is problematic. So either some special treatment is given to the first point or the whole PathGeom.edgeForCmd(cmd, pos) paradigm needs to be rewritten. ie all of existing code need rewriting.

The alternative is some special treatment of the first commands. 

The existing special treatment of inventing fake m/c position has potentially dangerous consequences. My patch leveraged additional knowledge of the nature of the initial commands but was rejected, without criticising a specific failing. 

mlampert:
#The correct way to deal with this issue is for the dressup to only
emit parameters which have already been specified by the op.

So if X hasn't been set by the op then the dressup should also not set X
in any commands it generates. Once the op sets X the dressup can
manipulate it.

That is what my patch achieved by applying additional information about what the first two commands are. 

It seems that either we apply some knowledge about initial commands ( not necessarily the same very specific assumptions I made ) or we ditch the entire  PathGeom.edgeForCmd(cmd, pos) paradigm and rewrite the dressup. 

We could make some less rigid assumptions, like ignore everything before the first x,y move which is inside or partially inside the boundary ( since the dressup already adds the safety move ). Then the m/c pos is recovered and the rest of the loop is fine. 

The implicit assumptions here are : all moves before x,y are safety moves; the first real positional move contains both x and y , we add a safe z and x,y,z is fully determined. Again requires imposing a spec on what path tools do or do not do in order to provide a situation robust to future changes and / or additional function.

If that approach is not acceptable can someone suggest an acceptable strategy for dealing with this bug. 

This is  a tool crash bug, it needs resolving.

**Comment by mlampert** [comment]
> So if X hasn't been set by the op then the dressup should also not set X
> in any commands it generates. Once the op sets X the dressup can
> manipulate it.
Correct. You just have to remove parameters from an emitting command which have not been specified yet by an incoming command, and if that leaves the command without parameters then don't emit it. I think all that is required is some post processing of the commands returned from `boundaryCommands()` instead of blindly adding them all to the output.

> That is what my patch achieved by applying additional information about what the first two commands are.
The comment I made is that your patch is not using _additional information_, it is making assumptions.

**Comment by J-Dunn** [comment]
new PR
prevent added paths creating tool crash #4260 #3028 #3751

**Pull request closed without merging**
