### PR TITLE
Vbo support

### PR DESCRIPTION
**Pull request by wwmayer**
Replacement for PR #514
+ fix build failure on Windows
+ cleanup code
+ correct notification of VBO status changes

### CODE REVIEW

**Comment by vejmarie** [comment]
Thanks for the clean up. I will have a look to the SoElement side as to learn how I was supposed to make it properly.

**Comment by wwmayer** [comment]
If you have a minute can you please test if you still have the performance boost? On my machine I haven't realized any difference between VBO on or off.

Thanks in advance.

**Comment by vejmarie** [comment]
Sure I will Just give me a few hours.

**Comment by vejmarie** [comment]
Just tried and it worked like a charm
OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.10068 (Git)
Build type: Unknown
Branch: vbo_support
Hash: c9f3949d8fe936ac21bf0f8958635893ddfec255
Python version: 2.7.11
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.0.0

Got 11 fps instead of 1 .5fps on bareleye model. You are good to go. Just a question, what is your graphic adapter ? You need to have a big model to see the difference, something where you got around 512MB to 1GB of GPU memory allocated.

**Comment by wwmayer** [comment]
It's an Nvidia GeForce GTX 680MX. OK, then I probably have to use your STEP benchmark model which I wanted to avoid because it needs so long to load.

I had to push a further commit to fix the rendering on Windows when using two views. Once the the travis build succeeded  can merge this branch.

See also on the forum thread later about further points.

**Comment by vejmarie** [comment]
ok, no problem. Your GPU is far much more efficient than the CPU integrated one I use ;). Fortunatly you need to use a reasonably big model to benefit from the patch. Good luck with the fix on windows. Just push on the forum the weak parts you identified and let's fix them.

**Comment by easyw** [comment]
@wwmayer 
triplus did some test using its own models
here the forum link
https://forum.freecadweb.org/viewtopic.php?f=10&t=20487&start=40#p159010
probably he can share the models to facilitate tests
Maurice

**Comment by vejmarie** [comment]
You can also give a try to the STEP model, it should take around 500s to open with the latest commit. This is still a lot of time, but much more reasonnable than it was before, and I am interested to know how long it takes on as many platform as possible to keep improving the STEP reader. (you do need at leat 4GB of RAM)

**Comment by wwmayer** [comment]
The 200MB file takes 29 min to load.
Without VBO it has 1.6 fps
With VBO it has 8.0 fps

**Comment by vejmarie** [comment]
Thanks for the update and good to see the improvement on the rendering. Let's discuss the loading time on the forum, it is really really strange as it is far much faster on MacOS currently. I think there is a compilation issue on OCCT somewhere on Windows (I suppose you ran the test on Windows)

**Comment by wwmayer** [comment]
Merged.

**Comment by easyw** [comment]
Hi,
triplus replied me and so now I have also smaller, but still complex test files 
at the forum I uploaded FC source file and STEP exported
https://forum.freecadweb.org/viewtopic.php?f=10&t=20487&p=159514#p159514
STEP file takes 119s to load and stresses quite a lot when displayed (200ms/5fps) ...
so now tests can be done with different level of complexity, and faster result for quick review :)
Tested on a 
    Windows 10 64b
    Intel® Core™ i7-6700HQ
    16 GB di SDRAM
    GeForce GTX 965M (4 GB GDDR5)

**Pull request closed without merging**
