### PR TITLE
[CAM] implement multipass profile operations

### PR DESCRIPTION
**Pull request by davidgilkaufman**
Implementation of #16623, multi-pass support for profile operations. [Forum link](https://forum.freecad.org/viewtopic.php?t=90247)

I was surprised to discover that the C++ back end for this feature largely already exists. Specifically, there are already area offset parameters "Stepover" and "ExtraPasses", and an implementation for generating extra passes based on those values. As best I can tell, these features are unused before this PR.

As [dimitrios2 mentioned](https://forum.freecad.org/viewtopic.php?p=780268#p780268), profile operations handle open and closed paths separately, so this PR makes changes to implement the feature in both pipelines.

20241018_13h23m47s_grim

This screenshot shows the feature in action. Of note:

- In the left panel, there are new options "Number of Passes" and "Pass Stepover" in the profile operation ui. Not shown here, but "Pass Stepover" becomes disabled if "Number of Passes" is 1
- On the left side of the model, there two profile operations, tracing closed contours of positive and negative features
- On the right side of the model, there are two profile operations, tracing open contours on positive and negative features

20241018_13h41m52s_grim

- Note that the profile of the open edge on the right side of the model has a more-recessed stop point on the more-offset path. This happened naturally while I was writing the code, and I'm honestly unsure if this is better or worse behavior than matching the stop point of the non-stepped pass, and I decided to leave it this way.

### CODE REVIEW

**Comment by dbtayl** [comment]
I'd argue you want to match the stop point of non-stepped passes for the ends of your selection. If I'm facing the end off some stock, I don't really want the paths to get progressively longer (wasting motion on the outside passes) or progressively shorter (leading to residual fillets on the inner passes from the previous passes) as I offset further.

Both this and the opposite are unexpected and undesirable.
Screenshot_2024-10-20_18-08-48

For nodes where two segments join, offsetting as you show makes sense.

**Comment by davidgilkaufman** [comment]
I'm convinced that it would be better if the end position did not change for further-offset passes. Unfortunately, I have now spent a few hours today learning about how these open-edge offset paths are generated, and I learned that the algorithm is not conducive to generating your suggested endpoints.

For anyone interested in the details, I originally I assumed that it would first perform a edge-based offset operation on the selected edges and then pick end points for the resulting path, and that I would be able to easily configure the second step to set the offset paths' end points however I like. However, it does not follow that process. It actually extracts a closed 2D shape based on the model geometry and a bounding box (with only the bounding box determined from the selection), offsets the model geometry, and post processes from there to produce a path. The end points of the offset path appear to be fully determined from model geometry and offset distance, and I am uninterested in writing post processing code to redo parts of that offset operation to place the end points correctly (I'd sooner reimplement the full offset operation along the lines that I expected the feature to be implemented, because I think that approach would be much less error-prone than fitting two separate offset shapes together piecemeal).

On the bright side, my new understanding of the open-edge offset code substantially helps me to understand why this feature works poorly on non-top edges (that's the condition where it does a good job extracting a useful 2D shape from the model), and perhaps in a later ticket/PR I'll make a larger change to address this issue, and also set things up for picking the offset end points more flexibly.

In the mean time, I think the easy-to-generate end points are good enough for this feature to be very useful, and I'd like to merge the feature as is.

**Comment by dbtayl** [comment]
Not going to argue with that- definitely more useful as-is than not having anything and making a bunch of copy-pasted offset operations.

If you've got an understanding of (one of?) the problem(s?) with processing edges, that would be a huge fix IMO. Too many weird instances where closed edges work fine, or open edges from an extrusion- but not the base sketch- work, etc. Maybe that's a different issue. Either way, improvements in the consistency of edge handling would be great.

**Comment by chennes** [comment]
This is waiting on a review from @sliptonic

**Comment by maxwxyz** [comment]
still waiting for review by @sliptonic

**Comment by luzpaz** [comment]
https://github.com/user-attachments/assets/e8f88f64-a644-43cb-9dc4-4d18a42386c8

Sorry, had to do it

**Comment by maxwxyz** [comment]
waiting for review

**Comment by davidgilkaufman** [comment]
That's too bad about the holding tags. I guess that can also be added to the list of follow-up work to get this feature to be compatible with other features. I still think we should merge this PR as is, though. This feature will be very useful even with the compatibility caveats.

> I guess it can be merged

@sliptonic, if you're ok with merging this PR, could you click whatever button makes that happen? I do not have sufficient privileges to merge, even with written approval.

**Comment by maxwxyz** [comment]
@davidgilkaufman we are merging most of the PRs in the merge meeting on Mondays and Fridays. We sort for last recently updated, so this PR might be in the queue for about 1-2 weeks.

**Comment by yvan-r** [comment]
The offset Extra should also have a Z value.
This is used for Onion Skinning small parts, reducing cutter pressure and preventing the part from shifting on the vacuum bed.

Example:
- Offset Extra XY plane:  0.1mm
- Offset Extra Z: 1mm

**Pull request merged**
