### PR TITLE
Sketcher: Point to Circle Distance Constraints

### PR DESCRIPTION
**Pull request by FlachyJoe**
Implements Point to Circle distance constraint

Capture d’écran_2023-05-13_14-28-46

### CODE REVIEW

**Comment by FlachyJoe** [comment]
I've fixed the case where the point is in the circle
Capture d’écran_2023-05-15_21-06-31

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9559">pipeline status</a> for feature branch [PR_9559](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9559). Pipeline [903669770](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903669770) was triggered at [0998992](https://github.com/FreeCAD/FreeCAD/pull/9559/commits/0998992de06ba9fd57352d1a678faa3163a87a56). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by FlachyJoe** [comment]
My branch compile well in my side but CI failed at Prepare has somebody an explanation?

**Comment by luzpaz** [comment]
Specifcally
```
Run commitCnt=$(jq -re '.ahead_by' /tmp/logs/compare.json)
  commitCnt=$(jq -re '.ahead_by' /tmp/logs/compare.json)
  echo "Changeset is composed of $commitCnt commit(s)" | tee -a /tmp/report/Prepare-5853726224-report.md
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    isPR: true
    isPush: false
    logdir: /tmp/logs/
    reportdir: /tmp/report/
    reportfilename: Prepare-5853726224-report.md
    baseSha: 2fd17be36108feb94188fa21f513d99ac1537241
    headSha: fefdef6f479829989442e0a77b9f2d3f92a5f987
Error: Process completed with exit code 1.
```

**Comment by FlachyJoe** [comment]
@luzpaz I had server errors on github.com in the same time. Now I merged the main branch and it seems to work as expected.

**Comment by PaddleStroke** [comment]
Do you plan to implement point to arc distance as well?

**Pull request merged**
