### PR TITLE
Fem: add FemResult export to VTK files for visualization externally

### PR DESCRIPTION
**Pull request by qingfengxia**
see discussion 
https://forum.freecadweb.org/viewtopic.php?f=18&t=19851&p=156894#p156894

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
@berndhahnebach can we merge this?

**Comment by berndhahnebach** [comment]
@yorik
on branch https://github.com/berndhahnebach/FreeCAD_bhb/commits/bhbdev066 I rebased on uptodate master, added some code formating and the code for documentation you added some time ago to any module. BUT ... 

@qingfengyxia:
in FEM and in FreeCAD most module for im- and export are called importsomething. How about naming the module importVTKResultMesh.py ?

cheers bernd

**Comment by berndhahnebach** [comment]
BTW: export results from calculix 3D FEM example to vtk and view them in paraview works gread :-)

**Comment by qingfengxia** [comment]
"in FEM and in FreeCAD most module for im- and export are called importsomething. How about naming the module importVTKResultMesh.py ? "

> Mesh import and export is done in cpp  FemMesh.cpp file, and current Fem.open() only deals with mesh, and it can not distinguish mesh or result by file suffix, so a new file is needed. 

Actually  FemResultTools.py could be a better name.  to support other format in the future. 
currently, only vtk FemResult will be export in that file. 

Do you need my to submit another/ redo a commit on renaming this file?

Thanks

**Comment by berndhahnebach** [comment]
> I did not understand why "im- and export are called importsomething" yesterday,
It depends on the workbench. Some workbenches distinguish between importsomthing and exportsomething. Some workbenches do import and export of file formats in one file called importsomething. 

I would vote for one import for one kind of file type, like importZ88Mesh for import and export of Z88 meshes or importIFC for import and export of all kind of IFC data. 

If it is ok I would rename it too importVTKResults.py this evening?

Yorik what do you think from whole FreeCAD point of view?

Bernd

**Comment by yorikvanhavre** [comment]
yes, one importXXX file for each filetype looks good and easy for other people, but I wouldn't make this a golden rule, for ex. C++ workbenches have a very different way to work. I think there is no problem in doing things differently.

**Comment by qingfengxia** [comment]
please go ahead to merge,  and rename the file name(any further retouch), bernd.

  result import has not been implemented but easy. I have made the boilerplate code already, you can just leave it there, until I finish all code next week.

**Comment by berndhahnebach** [comment]
here we are: rebased, renamed, code formating, time stamps 

 https://github.com/berndhahnebach/FreeCAD_bhb/commits/bhbdev066

**Comment by berndhahnebach** [comment]
to be sure checks are passed for my branch too ...
https://github.com/FreeCAD/FreeCAD/pull/487

**Comment by wwmayer** [comment]
Replaced by #487 => Close

**Pull request closed without merging**
