### PR TITLE
Missing import FreeCAD and/or FreeCADGui

### PR DESCRIPTION
**Pull request by cclauss**
These files refer to __FreeCAD__ and/or __FreeCADGui__ but those modules are not imported which results in an _undefined name_ which has the potential to raise NameError at runtime.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
All the Init.py and InitGui.py files are not loaded via import but via exec or execfile. So for them importing FreeCAD or FreeCADGui is superfluous, IMO.

**Comment by cclauss** [comment]
__execfile()__ was removed in Python 3.

Two ways to solve this:
1. Add the linter directive __# flake8: noqa__ to each file.
2. Create a __flake8 --exclude__ list in the Travis CI job.

Do you have a preference?

**Comment by wwmayer** [comment]
I think option 1 is the easier one and this way devs can run flake8 locally without passing anyarguments.

**Comment by cclauss** [comment]
Closed in favor of #1897

**Pull request closed without merging**
