### PR TITLE
Path: Fixes for Engrave & add Engrave unit tests

### LINKED ISSUE #9114: [Issue] Unable to engrave an arc.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=77106

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.32457 (Git)
Build type: Release
Branch: master
Hash: 85216bd12730bbc4c3cbf8f0bc50416ab1556cbb
Python 3.8.16, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
[/code]
```

### Subproject(s) affected?

Path

### Issue description

I first found the issue in 0.20 and after a discussion on the forum, I can also reproduce it on 0.21.
The overall issue is that I was trying to engrave a faceplate dial that consisted of an arc with graduations and numbering. What I found is that it would calculate paths for everything except the arc.

I have since created a simpler example that shows the issue and what I have found.

- I select the job and press engrave so it auto-selects all the models, the path for the arc will not be created. (Engrave1)

- Press engrave and manually add each model to the base geometry, the path for the arc will not be created. (Engrave2)

- Press engrave and manually add the models for A, line, square, and circle, then select the line of the arc and add it. Only the path for the arc will be generated (Engrave3) If the Model-Arc.Edge1 is removed, the paths for the A, line, square and circle will be generated.

- Press engrave and manually add the model for the A, and then select and add each line segment for the line, square, circle and arc. The paths for line, square, circle and arc will be generated but the ShapeString A will be omitted. (Engrave4)If lines in the A are selected instead of the model they will be added to the path.

It seems that the models in the base geometry are ignored if any line segments are present.
The arc model does not automatically get processed.
[Example2.zip](https://github.com/FreeCAD/FreeCAD/files/11099266/Example2.zip)

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #9303: [Problem] CAM: Engraving duplicates gcode for some base elements
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
N/A
```

### Subproject(s) affected?

Path

### Problem description

A user creates a sketch with a circle and the sets up path to engrave it.  The gcode is correctly generated.  If the sketch contains two circles, the gcode is generated to run one of them a single time and the other is run twice.

Forum discussion: https://forum.freecad.org/viewtopic.php?t=77694

### Anything else?

It appears the generation of wires from subelements has a bug.

@Russ4262 proposed a solution: https://forum.freecad.org/viewtopic.php?p=676528#p676467

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Russ4262**
This PR contains four commits, fixing three bugs and adding some simple unit tests based on the fixes.
- Fixes #9303 
- Fixes #9114
- Removes repetitive retraction to clearance height, though another remains.
- Adds some unit tests based on included fixes.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
was this merged?

**Comment by Russ4262** [comment]
Do not think so.

**Comment by luzpaz** [comment]
@Russ4262 what is the reason this was closed ?

**Comment by Russ4262** [comment]
As I read the contribution policy again, it appears this PR is
non-compliant. For that reason, I self-directed and closed. Thanks.

**Comment by luzpaz** [comment]
May I ask in what way is it non-compliant ?

**Comment by Russ4262** [comment]
5.4
5.9
Possibly 5.7
5.12
6.2
6.3

Have a great weekend.

**Pull request closed without merging**
