### PR TITLE
PATH: Make drill location list sortable

### PR DESCRIPTION
**Pull request by pekkaroi**
As discussed here, it makes sense to make the list of drillable holes sortable by diameter.
https://forum.freecadweb.org/viewtopic.php?f=15&t=30077

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by sliptonic** [comment]
As described, the list is sortable.  This makes it easier to selectively enable and disable holes by size but doesn't do anything about the actual drilling order.  I'd like to see this further improved so that the list order controls the drilling order as well.  This might need additional discussion and controls to permit moving a single location up and down in the list.

**Comment by pekkaroi** [comment]
Correct - this will only sort the list. It is useful when you want to disable the drilling of holes with certain diameter, for example. The order of the actual drilling is still determined by the nearest neighbor algorithm which is desired in most cases - I think?

**Comment by sliptonic** [comment]
ok by me.  If more control of actual drilling order is desired, a feature request should be entered

**Comment by yorikvanhavre** [comment]
then I'll merge already!

**Pull request merged**
