### PR TITLE
Pathworks

### PR DESCRIPTION
**Pull request by daveseff**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [X] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

This PR does not address any existing issue. This is the beginning of my contributions to the project. I wanted to make the tool setup images a bit nicer and easier to understand.

### CODE REVIEW

**Comment by luzpaz** [comment]
Would it be possible for you to submit the PR when it's ready to be reviewed (so it doesn't contribute to the current log-jammed PR queue that we have going on already)?

**Comment by sliptonic** [comment]
Thanks for the contributions.   Pull Requests are approved by different people depending on the content area.   I approve PRs for the path workbench and others look after the sketcher, FEM, etc.   
That means a PR that touches a lot of areas either requires a lot of communication or it has to be approved by Werner (who's already overloaded).   Could you please split the PR into smaller workbench-specific areas?

**Comment by daveseff** [comment]
Hi slip, This PR only affects the Path workbench. I'll have to see why the check has failed.

**Comment by sliptonic** [comment]
I see. The pr contains commits that have already been merged.

It's better not to merge master into your branch. Git can work it out but it makes the history messy so it's harder to review. Instead of merging, It's better to rebase your branch on master. That way the branch will only contain your commits. You can rebase as often as necessary and push/force to your repo. The pr will update automatically. 

But don't worry too much about trying to keep your branch up to date with master unless it touches files that are often edited by others. Unless there's a conflict, it'll merge fine.

**Comment by daveseff** [comment]
I always rebase. I don't ever remember merging master directly.

**Comment by daveseff** [comment]
I will redo my changes to fix this.

**Comment by daveseff** [comment]
Fixed.,

**Comment by sliptonic** [comment]
Thanks!   Before you spend any more effort on tools, please make sure you understand where things are going with Toolbits.  The old tool system is quickly being deprecated.  PR 4014, currently in draft, will make Toolbits the default.

**Comment by daveseff** [comment]
Thanks. Will have a look at 4014. Cheers.

**Pull request merged**
