### PR TITLE
Fix regexp string quoting

### PR DESCRIPTION
**Pull request by dov**
Fix regexp string quoting that cause warnings during cmake

### CODE REVIEW

**Comment by wwmayer** [comment]
Which warnings do you get?

**Comment by dov** [comment]
Here's the error during cmake:
```
[1/1505] Generating version_check
/space3/pub-repos/FreeCAD/src/Tools/SubWCRev.py:269: SyntaxWarning: invalid escape sequence '\.'
  match = re.match("git@github\.com:(\S+?)/(\S+\.git)", url) or re.match(
/space3/pub-repos/FreeCAD/src/Tools/SubWCRev.py:270: SyntaxWarning: invalid escape sequence '\.'
  "https://github\.com/(\S+)/(\S+\.git)", url
/space3/pub-repos/FreeCAD/src/Tools/SubWCRev.py:274: SyntaxWarning: invalid escape sequence '\S'
  match = re.match("ssh://\S+?@(\S+)", url)
/space3/pub-repos/FreeCAD/src/Tools/SubWCRev.py:372: SyntaxWarning: invalid escape sequence '\*'
  if re.match("\*", self.branch) is not None:
git
/space3/pub-repos/FreeCAD/build/src/Build/Version.h.out written
```

It's a simple raw string python error. You can reproduce it by doing:
```
python
>>> '\s+'   # This is an error
<stdin>:1: SyntaxWarning: invalid escape sequence '\s'
'\\s+'
>>> r'\s+'   # This is ok!
'\\s+'
```
See e.g.: https://realpython.com/python-raw-strings/

**Comment by wwmayer** [comment]
Thanks. It seems it 's deprecated since Py3.11 or 3.12 because with Py3.10 I don't get this warning.

**Comment by dov** [comment]
@wwmayer 

It's actually always been invalid code. How else would you distinguish between '\n' and '\\n' if the former was written? However the warnings indeed to be new. See:

https://adamj.eu/tech/2022/11/04/why-does-python-deprecationwarning-invalid-escape-sequence/

In an case, thanks for merging! Perhaps it will prompt me to submit something more substantial one day.

**Pull request merged**
