### PR TITLE
[Arch Component] Fix placement multiplication problem (re-PR)

### PR DESCRIPTION
**Pull request by paullee0**
- see forum discussion : https://forum.freecadweb.org/viewtopic.php?f=23&t=67008

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6617">pipeline status</a> for feature branch [PR_6617](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6617). Pipeline [496466577](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/496466577) was triggered at [4385d60](https://github.com/FreeCAD/FreeCAD/pull/6617/commits/4385d6017eebb5676d0f505d123976e2dac982e9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
This is a serious change that will affect drastically all existing files... I would leave this to after 0.20 to make sure we don't destroy any user model...

**Comment by paullee0** [comment]
Wondering if this is a better moment for this PR be tested and merged in the discussion thread https://forum.freecadweb.org/viewtopic.php?f=23&t=67008, a rebase is suggested.

I had broken my git commit/pr etc. for a numbers of time ( :oops ) and I have not much idea what a 'rebase' in this context means and what needs to be done with limited knowledge about git.

Whilst suggesting peoples to test the PR, see if what needs to be done on github, thanks :)

**Comment by paullee0** [comment]
@Roy-043 commented that I need to re-base.  Without much knowledge in git / github, wondering if below is correct ?

Thanks !

( on my pc ? )
  git checkout master
  git fetch upstream
  git merge upstream/master
  git checkout ArchComponent_03_Fix-Placement-Multiplication_r
  git rebase master
  git push origin

**Comment by luzpaz** [comment]
>git checkout master
git fetch upstream
git merge upstream/master  # <--- Should be git rebase upstream/master
git checkout ArchComponent_03_Fix-Placement-Multiplication_r
git rebase master
git push origin

**Comment by paullee0** [comment]
> > git checkout master
> > git fetch upstream
> > git merge upstream/master  # <--- Should be git rebase upstream/master
> > git checkout ArchComponent_03_Fix-Placement-Multiplication_r
> > git rebase master
> > git push origin

Thanks @luzpaz for the advice.  

Just wondering the difference, the original steps are from Wanderfan in FC forum for 'normal' development.  So if I had already 'git merge upstream/master' for other development, very likely as there are other concurrent development, would it frustrate 'git rebase upstream/master';  Or they can always be executed in parallel / repeatedly without problems?

( https://forum.freecadweb.org/viewtopic.php?f=10&t=23204&start=10#p197095 )

Sorry, git / github is an area which I do not have much time to explore, try and make errors :D

**Comment by luzpaz** [comment]
In my experience `git merge` creates a commit. `git rebase` doesn't. So rebase is cleaner on the git history.

**Comment by paullee0** [comment]
Thanks for the hint :D

**Comment by paullee0** [comment]
> > > git checkout master
> > > git fetch upstream
> > > git merge upstream/master  # <--- Should be git rebase upstream/master
> > > git checkout ArchComponent_03_Fix-Placement-Multiplication_r
> > > git rebase master
> > > git push origin
> 
> Thanks @luzpaz for the advice.
> 
> Just wondering the difference, the original steps are from Wanderfan in FC forum for 'normal' development. So if I had already 'git merge upstream/master' for other development, very likely as there are other concurrent development, would it frustrate 'git rebase upstream/master'; Or they can always be executed in parallel / repeatedly without problems?
> 
> ( https://forum.freecadweb.org/viewtopic.php?f=10&t=23204&start=10#p197095 )
> 
> Sorry, git / github is an area which I do not have much time to explore, try and make errors :D

It seems this is not working, any idea what needs to be done ? :)

[paullee@fedora FreeCAD]$ git push origin
Username for 'https://github.com': paullee0@gmail.com
Password for 'https://paullee0@gmail.com@github.com': 
To https://github.com/paullee0/FreeCAD.git
 ! [rejected]              ArchComponent_03_Fix-Placement-Multiplication_r -> ArchComponent_03_Fix-Placement-Multiplication_r (non-fast-forward)
error: failed to push some refs to 'https://github.com/paullee0/FreeCAD.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by luzpaz** [comment]
Yea, I'll take a look a little later to see what's going on. It looks like you need to `git pull` first. If anyone else has a moment before I do, feel free to jump in.

**Comment by luzpaz** [comment]
@paullee0 this is what it's complaining about: Screenshot_20220907_173849

**Comment by luzpaz** [comment]
Now you're ready.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6617">pipeline status</a> for feature branch [PR_6617](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6617). Pipeline [633998387](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/633998387) was triggered at [9f6151b](https://github.com/FreeCAD/FreeCAD/pull/6617/commits/9f6151b802f9dea85f48c29f28cd9e5be19e8bcd). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by paullee0** [comment]
> Now you're ready. Screenshot_20220907_175203

Sorry, I have not much idea what all these are about :)  So, nothing I need to do ?

And below are supposed to be done ?

        git checkout master
        git fetch upstream
        git merge upstream/master # <--- Should be git rebase upstream/master
        git checkout ArchComponent_03_Fix-Placement-Multiplication_r
        git rebase master
        git pull  # <--- ...') before pushing again.
        git push origin

Thanks again.

**Comment by luzpaz** [comment]
What's left here ?

**Comment by paullee0** [comment]
> @paullee0 can you rebase your branch on master again ? Thanks!

I messed up the whole setup every time I tried this, I'll see if it works out this time :)

**Comment by paullee0** [comment]
> > @paullee0 can you rebase your branch on master again ? Thanks!
> 
> I messed up the whole setup every time I tried this, I'll see if it works out this time :)

This is what I get up to 'git pull', any idea ? :)

[paullee@fedora FreeCAD]$ git pull
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 6 (delta 5), reused 5 (delta 5), pack-reused 1
Unpacking objects: 100% (6/6), 12.40 KiB | 373.00 KiB/s, done.
From https://github.com/paullee0/FreeCAD
 + 4385d6017e...9f6151b802 ArchComponent_03_Fix-Placement-Multiplication_r -> origin/ArchComponent_03_Fix-Placement-Multiplication_r  (forced update)
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
[paullee@fedora FreeCAD]$

**Comment by luzpaz** [comment]
Make sure you're in your branch and then type `git pull -rebase`

**Comment by paullee0** [comment]
> Make sure you're in your branch and then type `git pull --rebase`

Thanks, is it ok  with below message ?  Or should use '--reapply-cherry-picks' ?

```
[paullee@fedora FreeCAD]$ git pull --rebase
warning: skipped previously applied commit acfdb4c139
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
dropping d784cffe3f90665e75928de6530f23dccfe7f6c8 Fixed typo in UI test case -- patch contents already upstream
Successfully rebased and updated refs/heads/ArchComponent_03_Fix-Placement-Multiplication_r.
[paullee@fedora FreeCAD]$ 
```

**Comment by luzpaz** [comment]
Looks like it ignored a commit you had on your local branch.   
Look at the code and see if it's correct by running `git diff`

**Comment by paullee0** [comment]
> Looks like it ignored a commit you had on your local branch. Look at the code and see if it's correct by running `git diff`

Nothing returned, is it normal ?

```
[paullee@fedora FreeCAD]$ git diff
[paullee@fedora FreeCAD]$ 

```

**Comment by luzpaz** [comment]
oof... sorry. 
OK, are these all the changes you made: https://patch-diff.githubusercontent.com/raw/FreeCAD/FreeCAD/pull/6617.diff  
(or is there anything missing ?)

**Comment by paullee0** [comment]
> oof... sorry. OK, are these all the changes you made: https://patch-diff.githubusercontent.com/raw/FreeCAD/FreeCAD/pull/6617.diff (or is there anything missing ?)

Yes please

**Comment by Roy-043** [comment]
I am going to try to get the PR merged. I'll update the branch first. If there are any problem I'll fix them afterwards.

**Comment by Roy-043** [comment]
Hmm, I was hoping for more than GitHub is delivering. I'll manually updated the file to avoid merge conflicts.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6617">pipeline status</a> for feature branch [PR_6617](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6617). Pipeline [774875141](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774875141) was triggered at [1527793](https://github.com/FreeCAD/FreeCAD/pull/6617/commits/1527793ce982a76acb6d17e92b8b4d117cd894d3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6617">pipeline status</a> for feature branch [PR_6617](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6617). Pipeline [774884594](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774884594) was triggered at [0ebd66a](https://github.com/FreeCAD/FreeCAD/pull/6617/commits/0ebd66ae2045f26cb9b76931f87efc0390dedfcf). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by paullee0** [comment]
Thanks @Roy-043

**Pull request merged**
