### PR TITLE
Update original .ts files by official src/Tools/updatets.py script ru…

### PR DESCRIPTION
**Pull request by Kuzma30**
…nning.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

This fixes many issues described here https://github.com/FreeCAD/FreeCAD-translations/issues.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6804">pipeline status</a> for feature branch [PR_6804](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6804). Pipeline [526100478](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/526100478) was triggered at [eed7848](https://github.com/FreeCAD/FreeCAD/pull/6804/commits/eed78487b7b3fcb4a13edf8bb450a365232c8c7b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@Kuzma30 can you explain the reason for this PR (in comparison to when yorik runs it) ?

**Comment by Kuzma30** [comment]
@luzpaz The reason is the desire to help a busy person. I'm also trying to help the project with faster translation updates.

**Comment by donovaly** [comment]
@yorikvanhavre , can you please have a look at this PR if it is valuable for 020?

**Comment by yorikvanhavre** [comment]
This is cool. Anybody is welcome to help with this!

Usually I do a full update -> upload -> build -> download -> apply cycle at once, but there is no problem doing part of it either.
However, in this case, @chennes has just been working on the updatets.py script and there are issues we need to solve (on my system the newer version contains fewer strings than the older one), that I want to check before merging.

**Pull request closed without merging**
