### PR TITLE
Gui: Add translations for color bar labels

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by chennes** [comment]
Thanks -- I don't see what the CI failure is, do you?

**Comment by wwmayer** [comment]
The GUI unit tests cause a segmentation fault somewhere:

> Program received signal SIGSEGV, Segmentation fault.
Segmentation fault (core dumped)
Error: Process completed with exit code 139.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9308">pipeline status</a> for feature branch [PR_9308](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9308). Pipeline [842290227](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/842290227) was triggered at [749ab85](https://github.com/FreeCAD/FreeCAD/pull/9308/commits/749ab850deff96642128e4650f3facb5c1dccac0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Did you figure out what was segfaulting?

**Comment by wwmayer** [comment]
No. I have carefully checked the log messages but couldn't find where exactly it has crashed. But several weeks ago we have seen sporadic crashes in GUI mode and in most cases it was related to the graphic driver.

**Pull request merged**
