### PR TITLE
Fix various typos throughout the codebase

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
Postpone until https://github.com/FreeCAD/FreeCAD/pull/15261 is merged

**Comment by maxwxyz** [comment]
@luzpaz oh sorry, did not see that

**Comment by luzpaz** [comment]
Perhaps merging this into #15261 ?

**Comment by maxwxyz** [comment]
I just checked, there are no overlaps. I only changed strings that will be translated / visible in the GUI, in this PR here, mostly code/comments are corrected.

**Pull request merged**
