### PR TITLE
Fem: Export post-processing data to VTK - fixes #5816

### LINKED ISSUE #5816: FEM, export vtk pipeline to vtk file format directly
Issue imported from https://tracker.freecad.org/view.php?id=3628

* **Reporter:** berndhahnebach
* **Date submitted:** 10/10/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** confirmed
* **Tags:** 

# Original report text

some helpful links ... 

https://forum.freecadweb.org/viewtopic.php?f=18&t=31288&start=30#p261202

https://github.com/FreeCAD/FreeCAD/blob/6178c795817e7f513c9ed1f5673565a4c17fdc5b/src/Mod/Fem/feminout/importVTKResults.py#L71

https://github.com/FreeCAD/FreeCAD/blob/6178c795817e7f513c9ed1f5673565a4c17fdc5b/src/Mod/Fem/App/FemPostPipeline.h#L42-L68

https://github.com/FreeCAD/FreeCAD/blob/6178c795817e7f513c9ed1f5673565a4c17fdc5b/src/Mod/Fem/App/FemPostPipelinePyImp.cpp#L40-L49

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

### PR DESCRIPTION
**Pull request by marioalexis84**
It works using the `Export...` item in the menu bar and from Python using the `writeVTK` method of post-processing objects.
File extension is automatically detected from data type.

@FEA-eng

### CODE REVIEW

**Comment by FEA-eng** [comment]
Nice, it's working but the extension becomes `*.vtk.vtu` for some reason.

**Comment by marioalexis84** [comment]
> the extension becomes *.vtk.vtu for some reason

Fixed.

There is a limitation in the export dialog. Currently, it's not possible to automatically select the appropriate filename extension, so the default extension is `vtu`. In any case, it is subsequently modified internally by the export function.
For example, if you try to save a file as `result.vtu` but the extension should be `.vtp`, this is changed internally so the file is saved as `result.vtp`.
The recommendation is to write the name without an extension and let the system add the appropriate one.

**Comment by FEA-eng** [comment]
Now the extension is correct, thanks.

**Comment by marioalexis84** [comment]
@chennes this PR is ready.

**Pull request merged**
