### PR TITLE
[TD]Allow override of dimension line angles

### PR DESCRIPTION
**Pull request by WandererFan**
replacement for PR #5441 with correct version of TaskDimension.ui.

This PR adds the ability to override the layout of dimension and extension lines in linear dimensions.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5447">pipeline status</a> for feature branch [PR_5447](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5447). Pipeline [457078699](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/457078699) was triggered at [da34b2f](https://github.com/FreeCAD/FreeCAD/pull/5447/commits/da34b2ffdc598c755234090d8092e7b6c24be35d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by edi271 — CHANGES_REQUESTED** [review]
File DrawUtil.cpp, line 626:

Checking  det against 0 is problematic. If the value is near to zero, e.g. 0.01 the intersection point is far away, which can lead to unexpected situations. I recommend

if(abs(det) < 0.01){


In CommandExtensionPack.cpp find the function _intersection which calculates the intersection of two objects of type TechDraw::BaseGeomPtr (line-line, circle-line, circle-circle). Should we try to transfer this function to DrawUtil ?

**Comment by luzpaz** [comment]
@edi271 Just an aside about reviewing code on GitHub:. 
You can click on the [Files changed](https://github.com/FreeCAD/FreeCAD/pull/5447/files) tab and click on the line or lines you're reviewing. This allows the author and other devs to see the code (and context said code is in) immediately. Does that make sense?

**Comment by WandererFan** [comment]
there is a function in DrawUtil for floating point comparisons -
fpCompare(float1, float2, tolerance), but I guess it was created after
intersect2D.  I'll do another PR to change the comparisons.  Thanks for
pointing this out.

Yes, an intersection routine would be useful in DrawUtil.  Should it be a
method of BaseGeom? point = baseGeom1.intersect(baseGeom2)?

**Pull request merged**
