### PR TITLE
Sketcher: Chamfer Fix #13049

### LINKED ISSUE #13049: Inconsistent chamfer generation in Sketcher
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Every time you click on a point with the new Chamfer tool, you get a different result.

https://github.com/FreeCAD/FreeCAD/assets/57467/1af32eb2-3fb3-4b64-a11a-22b92b7efb6e

### Full version info

```shell
OS: Ubuntu 23.10 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36487 (Git)
Build type: Unknown
Branch: main
Hash: f5baef888c25937026ee50001a4fe4293a9f11ee
Python 3.11.6, Qt 5.15.10, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * ExtremeProDark 2.9.0
  * DynamicData 2.60.0
  * Assembly4 0.50.6
  * ExplodedAssembly
  * sheetmetal 0.3.15
  * BIM 2021.12.0
  * A2plus 0.4.61
  * Render 2023.12.28
  * Rocket 3.2.4
  * Curves 0.6.21
  * freecad.gears 1.2.0
  * Assembly3 0.12.0
  * boltsfc 2022.11.5
  * OpenDark 2023.12.17
  * dodo 1.0.0
  * Ondsel-Lens 2023.12.13.01
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fix #13049

### CODE REVIEW

**Comment by prokoudine** [comment]
Unfortunately, with the fix applied, I can still reprosuce the issue. I also get occasional computation freezes, although I'm not sure they were introduced by this patch. The video below starts with such a freeze and continues with chamfer being applied differently every time in the same scenario.

https://github.com/FreeCAD/FreeCAD/assets/57467/79e48f54-3d05-426a-a15a-8bed0deb3914

**Comment by PaddleStroke** [comment]
Indeed you are right. This actually do not always happen. It seems to depend on the geometries, and even does not always happen with the same geometries. Which is why I thought it was fixed.

**Comment by PaddleStroke** [comment]
Ok now it should be ok @prokoudine

**Comment by prokoudine** [comment]
Can't reproduce the bug anymore. Thanks!

**Pull request merged**
