### PR TITLE
 ArchSpace - Correct computed dimensions (floor area and perimeter length) 

### PR DESCRIPTION
**Pull request by DeniseBryson**
Now the user can decide between two ways of computation. As discussed in the issue #13424.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
That's very good! Congrats!

Only comment: I wouldn't remove the Area property, because it is used by other tools (Draft Label and IFC quantities export IIRC). Instead, I would leave it but link it to the HorizontalArea property with `obj.setExpression("Area", "HorizontalArea.Value")`

**Comment by DeniseBryson** [comment]
Sorry for the delay and thanks for the comment I added the area property again.
But I am having difficulties to build the entire program, since the commit, that renamed the Arch folder to BIM, FreeCAD does not find the module anymore. with the error: "No module named 'Arch_rc"
Not sure if i am missing another commit but this is the reason i am taking so long...

**Comment by yorikvanhavre** [comment]
No worries, sorry this came in the middle of the big BIM migration...

The "Arch_rc not found" problem is because you still have the BIM addon installed. Just uninstall it. (We're working on a solution for people who still need it for 0.21)

I still see the Area property being removed, though... Maybe there is a commit missing here? (Working with Git can be complicated the first times if you're not used to it, no worries, it happens often ;) ). For next times, it's actually better to make a special branch to work on a specific thing. You are working on your main branch currently, but it's easier if you keep your main branch clean so it's easy to keep in sync with FreeCAD's main branch.

Shout if you need any help with sorting out the git stuff!

**Comment by DeniseBryson** [comment]
Thanks for the reply! 
After reinstalling it, it worked and I added the commit adding the Area property.

And indeed I am new to git.
I create an extra branch next time. 
But one question, it is easier to keep the main branch in sync then but for the merge request, I need the extra branch to be in sync as well and therefore have the same problem of constantly sync the extra branch no? What am I missing? Maybe I just try it and it will become obvious... :)

**Comment by yorikvanhavre** [comment]
Okay this looks good, thanks! Waiting for the CI tests to run and we can merge.

Basically what I do here on my machine:

- my "origin" remote is the official FreeCAD repo
- my "github" remote is my github FreeCAD repo
- so when I `git pull` it takes from the official FreeCAD repo
- when I `git push github` it goes to my github fork
- Everytime I want to do a PR, first I `gut pull` to make sure my local machine is in sync with the official repo
- Then I create a branch for it (you can do that before you make the code changes, or after): `git checkout -b my-new-branch`
- When you're done, `git push github my-new-branch`
- When you do that, Github will even give you a link to create a PR (as long as it knows your github repo was forked from the FreeCAD one)
- So this way, you don't use your github's `main` branch anymore, there is actuaqlly no real need to keep it in sync with FreeCAD... The main thing is that your next coding will happen in a new branch on yuor machine that is in sync with the current FreeCAD one

**Comment by DeniseBryson** [comment]
Thanks a lot for the advice, with the next issue I will try that!

The windows check did not pass how can I fix that?

**Comment by chennes** [comment]
Thanks for the PR -- the CI failure is a known issue that we are working on.

**Comment by DeniseBryson** [comment]
Thanks a lot for the support @yorikvanhavre !

**Comment by marcuspollio** [comment]
Hi @DeniseBryson
Nice work, thank you for the fix =D
Testing so far, it works great !

I found a [similar issue](https://github.com/FreeCAD/FreeCAD/issues/14687) in the computed "Vertical Area", would you be interested to have a look ?

**Pull request merged**
