### PR TITLE
Draft: fix issue with undo

### LINKED ISSUE #8044: [Bug] [WB Draft] Undo doesn't work after using Move function on lines created in Draft WB
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=74424

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.31109 (Git)
Build type: Release
Branch: master
Hash: c23ee7ad88433a0f00e84afae0a62fe738be0c09
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * CurvedShapes 1.0.4
  * Curves 0.5.3
  * FeedsAndSpeeds 0.5.0
  * Marz 0.0.26-alpha
  * Silk 1.0.0
```

### Subproject(s) affected?

Draft

### Issue description

Create a line in Draft WB. Use the Move function in Draft WB to move the line and then press undo (ctrl Z), the line doesn't move back to it's original position. However, other objects not created in Draft WB do move back to their original positions such as primitives created in Part WB when the undo function is used. It seems to be lines, splines etc. created in Draft WB that aren't working properly.

This seems to be potentially just a windows problem. Another user, DrMarco, reported correct behaviour from a Linux installation of Freecad.

The problem occurs on the latest development version of Freecad 0.21.31109 and the stable version(0.20.1)

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Roy-043**
This PR fixes #8044.

Two techniques are used:
1. Do not recompute inside the transaction.
2. Avoid the creation of a new Shape if only the Placement is changed.

Instead of updating all draftguitools, the recompute is removed from `self.commitList` in the `finish` function of the `DraftTool` class (see gui_base_original.py).

Only updating a Shape when required has the added advantage that f.e. moving a complex object such as a [Draft_ShapeString](https://wiki.freecadweb.org/Draft_ShapeString) or a [Draft_Shape2DView](https://wiki.freecadweb.org/Draft_Shape2DView) is almost instantaneous.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

---

### CODE REVIEW

**Comment by Roy-043** [comment]
See [this forum post](https://forum.freecadweb.org/viewtopic.php?p=654653#p654653) below for a test case where the Windows version and the Linux version have a similar undo issue.

```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.31513 (Git)
Build type: Release
Branch: master
Hash: b2ab8edba4bfd71681e639f8c3f1105066bed4c7
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/Australia (en_AU)
Installed mods:
```

```
OS: Ubuntu 22.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.0.31598 (Git) AppImage
Build type: Release
Branch: master
Hash: f7db685a2821adaf23c85a25855401ecc1eeff2c
Python 3.10.8, Qt 5.15.6, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
```

**Comment by donovaly** [comment]
The unit tests failed, but I cannot see where exactly. Can you see this?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8267">pipeline status</a> for feature branch [PR_8267](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8267). Pipeline [761013630](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761013630) was triggered at [738ca48](https://github.com/FreeCAD/FreeCAD/pull/8267/commits/738ca486894eb9c3225256771f191c4cd451fecc). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by yorikvanhavre — APPROVED** [review]
Didn't test very far but this looks very good and a welcome cleaning too, hadn't realized these recomputes were there...

**Pull request merged**
