### PR TITLE
Adds 3DConnexion Device Button Map loading from XML file

### PR DESCRIPTION
**Pull request by casiobearing**
Re-based on latest master and unit tests run... some unit test errors occurring not related to my pull.

"3Dconnexion.xml" - at the moment temporarily I've put this file into src/Gui (I'm open for suggestions where such config files should go in the repository).
For use at run-time, the XML file should be copied into the folder containing the FreeCAD executable. (I'm open for suggestions where such config files should go).

If the XML file is present, the button mappings for are preloaded into the Tools... Customize...Spaceball Buttons dialog.
If the XML file does not exist, no change in FreeCAD functionality occurs.

The XML file is designed to hold configurations for multiple types of 3Dconnexion mice.
Currently the code is hard-coded to load in the mappings for "SpacePilot Pro" - I need to investigate if the type of mouse can be provided by the spacenavd service; likewise for button held down duration.

### CODE REVIEW

**Comment by vocx-fc** [comment]
Please open a thread in the forum. If there is already a thread there, then add it to the description of this pull request so people can continue the conversation there.

Please don't develop in the master branch of your own fork. Create a branch, and use that to add new functions. See [Source_code_management](https://www.freecadweb.org/wiki/Source_code_management). As it is now, your pull request will add strange messages to the commit history like "merge branch master", or "merge pull request #1 from FreeCAD/master".

The proper workflow is to create a branch, and then rebase that branch on top of the upstream master.
```
git checkout casiobranch
git pull --rebase upstream master
```

As for where to put the configuration file, it should not be with the binary. Surely it can be provided as auxiliary. FreeCAD has a function to return directories where resources can be placed. I'm sure you can use that to find a suitable place for the configuration.
```
App.getResourceDir()
```

I'm not sure how to call it from C++, maybe `App::getResourceDir()`.

**Comment by casiobearing** [comment]
Thanks.
I assumed generating a pull would generated a corresponding forum thread. I'll make a forum thread.
My 1st use of github and I couldn't find any obvious document outlining that workflow. I'll create a branch.
I'll try the resourcedir mechanism.



-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


16 Feb 2020, 17:19 by notifications@github.com:

**Comment by luzpaz** [comment]
Was a forum thread created?

**Comment by casiobearing** [comment]
Yes :o)

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


27 Feb 2020, 23:03 by notifications@github.com:

**Comment by luzpaz** [comment]
@casiobearing URL?

**Comment by vocx-fc** [comment]
Forum thread: [Adds 3DConnexion Device Button Map loading from XML file (#3065)](https://forum.freecadweb.org/viewtopic.php?f=17&t=43421)

**Comment by yorikvanhavre** [comment]
This is a kind of preset right? Does it actually make sense to be accessible at runtime? I wonder if it coudn't be embedded in FreeCAD itself (in one of the resources file maybe?)
Also, AFAICS your code throws an error if the file is not found at runtime, which could be annoying.
If it makes sense to keep the xml file at runtime, Add it to the FreeCAD resources location as @vocx-fc vocx explains. Look for a few cmakefile.txt in the FreeCAD source code, many of them have files copied to the resources dir too.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
