### PR TITLE
Remove unused conda files and PKGBUILD

### PR DESCRIPTION
**Pull request by adrianinsaval**
@donovaly 
https://forum.freecadweb.org/viewtopic.php?p=613554#p613554
https://github.com/FreeCAD/FreeCAD/pull/7022#discussion_r896978826
@looooo can you reconfirm that none of these conda files are used anymore?

the makepkg file is for archlinux but it is extremely outdated, it was made for svn! Nowadays the equivalent is maintained here: https://aur.archlinux.org/packages/freecad-git

### CODE REVIEW

**Comment by adrianinsaval** [comment]
other possibly unused files:
https://github.com/FreeCAD/FreeCAD/blob/master/appveyor.yml
https://github.com/FreeCAD/FreeCAD/blob/master/.circleci/config.yml
https://github.com/FreeCAD/FreeCAD/blob/master/ChangeLog.txt

should these be removed too?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7270">pipeline status</a> for feature branch [PR_7270](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7270). Pipeline [600469892](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600469892) was triggered at [cae2d07](https://github.com/FreeCAD/FreeCAD/pull/7270/commits/cae2d07dd946e3b19f3f5dcaea45d22d4367443c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by looooo** [comment]
> @looooo can you reconfirm that none of these conda files are used anymore?

yes, I don't use it any more and I think these files are outdated anyway

**Comment by donovaly** [comment]
> yes, I don't use it any more and I think these files are outdated anyway

Thanks. Merging then.

**Pull request merged**
