### PR TITLE
Try to use pkg-config to find libhdf5 and openmpi

### PR DESCRIPTION
**Pull request by ysangkok**
This fixes the build on my Ubuntu 17.04 machine. Otherwise it doesn't build.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This proposed change doesn't compile anymore on travis...

**Comment by ysangkok** [comment]
@yorikvanhavre Fixed. Should not break any builds anywhere now, just add the possibility to build out-of-the-box on Ubuntu.

**Comment by yorikvanhavre** [comment]
merged

**Comment by Earnestly** [comment]
If `find_file` is to be used with `NO_DEFAULT_PATH` then it needs to search the correct path based on the result from `pkg_search_module`.

I believe the author made a mistake by using `OPENMPI_INCLUDE_DIRS` instead of `OPENMPI_INCLUDEDIR` which is the variable `pkg_search_module` provided.

With the current code:

```cmake
find_file(MpidotH mpi.h PATHS ${OPENMPI_INCLUDE_DIRS} NO_DEFAULT_PATH)
if(NOT MpidotH)
    message( WARNING "mpi.h was not found. Check for error above.")
endif()
```

cmake will produce an error because `OPENMPI_INCLUDE_DIRS` is empty:

```
CMake Warning at CMakeLists.txt:803 (message):
  mpi.h was not found.  Check for error above.
```

Currently I change this to `OPENMPI_INCLUDEDIR` which works correctly.

**Pull request closed without merging**
