### PR TITLE
[Do not merge]Fix remove dynamic prop

### PR DESCRIPTION
**Pull request by realthunder**
Improved fix in 5d5d056 (see comments inside).

### CODE REVIEW

**Comment by wwmayer** [comment]
This PR re-introduces the crash that has been fixed with 5d5d056

When running the example code
```python
class Feature:
  def __init__(self, fp):
    fp.Proxy = self
    fp.addProperty("App::PropertyString","Test")
  def onBeforeChange(self, fp, prop):
    if prop == "Test":
      fp.removeProperty("Test")
  def onChanged(self, fp, prop):
    getattr(fp, prop)


doc = FreeCAD.newDocument("PropertyTests")
box = doc.addObject("Part::Box","Box")

obj = doc.addObject("App::FeaturePython")
fea = Feature(obj)
obj.Test = "test" # <=== BOOM
```

It again crashes in ShapeCache::slotChanged

**Comment by vosk** [comment]
Shameless "I told you so"
https://forum.freecadweb.org/viewtopic.php?f=10&t=55689

**Comment by chennes** [comment]
Should this PR be closed?

**Comment by realthunder** [comment]
Just hold for a few days. I'll check soon.

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by AjinkyaDahale** [comment]
Bump. Just noticed this PR is awaiting update.

**Comment by donovaly** [comment]
@realthunder , Ping!

**Comment by realthunder** [comment]
This PR is obsolete now.

**Pull request closed without merging**
