### PR TITLE
TD: Adding more TechDraw svg symbols

### PR DESCRIPTION
**Pull request by JohnHyslop**
Per the discussion in https://github.com/JohnHyslop/FreeCAD-SVG-TechDraw=Symbols/issues/1

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by JohnHyslop** [comment]
Additional svg Symbols to Directory TechDraw/Symbols/misc  "for your appraisal .."
Best Regards
John Hyslop

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5506">pipeline status</a> for feature branch [PR_5506](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5506). Pipeline [464463568](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464463568) was triggered at [534d487](https://github.com/FreeCAD/FreeCAD/pull/5506/commits/534d487cffc9efdafb06b611b97fb65dfa095290). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Nice work on the PR. It would be good to open a forum thread to discuss with the community as well. So you mind doing that and the x-posting back to this PR?

**Comment by JohnHyslop** [comment]
Hi luzpaz
There are a couple of forum threads one I put in open discussion and the other is under TechDraw thread ,I just don't want to get into trouble for posting the same topic multiple times? will I add to one of these? 
please see links below one also has details on how some of the symbols work.

https://forum.freecadweb.org/viewtopic.php?f=8&t=61749
https://forum.freecadweb.org/viewtopic.php?f=35&t=61787

Re:x-posting back to this PR? did you mean putting a link on the forum back to this? 
I'll be out most of today so hopefully I can tidy things up when I get back..

Again I can't thank you enough for your help :)
Have a great day/night..

Cheers
John Hyslop [thebighaggis]

**Pull request merged**
