### PR TITLE
[path][for discussion] Improve path area projection performance [hold]

### PR DESCRIPTION
**Pull request by gwicke**
While working on molds for a hydrofoil I found that the path 3D surface
code got stuck in getEnvelope(), which is based on Area's projection
methods. A moderately complex mold model with several 3d surfaces would
cause the projection function to basically get stuck, running 8+ hours
until eventually running out of memory.

Based on perf profiles, the expensive bit that stood out was
WireJoiner::splitEdges. As an experiment, I commented out the call, and
was actually able to successfully calculate an envelope for several
complex 3d models, as well as some simpler models.

## Discussion & this diff

I have very little background on the circumstances under which edge
splitting is absolutely required. Input on this would be much
appreciated.

Right now, this diff implements a heuristic where splitEdges is only
called when no closed loop was found. Input on whether this kind of
approach is useful would be appreciated as well.

---

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
If you want to discuss this, you should open a forum thread and link it to this pull request.

**Comment by yorikvanhavre** [comment]
Not also that you can mark a PR as "draft" which prevents from merging it accidentally before you see it fit

**Comment by gwicke** [comment]
We had a small amount of discussion on the freecad/path gitter, but yeah I'll post in the forum as well.

> Not also that you can mark a PR as "draft" which prevents from merging it accidentally before you see it fit

Thanks for the hint, hadn't seen that feature yet.

**Comment by gwicke** [comment]
Superseded by newer performance optimizations that have already landed.

**Pull request closed without merging**
