### PR TITLE
[TechDraw] Make dimension labels centered

### LINKED ISSUE #15103: TechDraw: Snapping vertical dimensions - text is not aligned to the center
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Dimension text of vertical dimensions is snapping but not centered:
grafik

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git)
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

Techdraw

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by benj5378**
Partially fixes #15103

I have no idea, why the bounding rect was offset with 4 times linewidth. Might need to check if removing this has any side effects.

### CODE REVIEW

**Comment by maxwxyz** [comment]
@PaddleStroke maybe you can look over this one line PR

**Comment by WandererFan** [comment]
The  Ubuntu_22-04_Conda_Qt6 CI failure is unrelated to this PR.

**Comment by benj5378** [comment]
> You'll need to check if the dimension is "framed" before making the bounding rect smaller. The extra space is to allow for the frame line.

Isn't only views that gets framed? I don't understand

**Comment by Syres916** [comment]
> Isn't only views that gets framed? I don't understand

If the user changes a dimension to have _Theoretical Exact_ to be _true_ then the dimension will be framed as per:

Framed_Dimension

so I assume there needs to be a `if (m_isFramed) {` condition???

**Comment by WandererFan** [comment]
Not what I thought.  I could not create artifacts with or without the adjustment.   

But that adjustment creates leading whitespace when the dimension has a frame:
FrameNoAdjustment
FrameWithAdjustment

**Comment by WandererFan** [comment]
And there is something not right the frame drawing logic.  The painter should be drawing inside the bounding rect, not right along it as 1/2 of the line width will be out side the br.   Beyond the scope of this PR, though.

**Comment by benj5378** [comment]
@WandererFan So what is the ISO specification here? Should there be leading whitespace in front of the dimension? And only in front of the dimension? I'm being a bit confused on what you would like of changes

**Comment by WandererFan** [comment]
All the examples show the text of a TED as centered in the frame, which the current implementation doesn't do.  I suspect the adjust() call was intended to keep the frame from hitting the leading edge of the dimension text.  In which case the adjustment should be a little bit on the left edge (2x line width?) and a little bit on the right.

So the minimum change to your PR is to add the isFramed() test and only adjust the brect if this is a framed dim.

A nice to have would be to fix the centering of the the text in the frame.

**Comment by benj5378** [comment]
> So the minimum change to your PR is to add the isFramed() test and only adjust the brect if this is a framed dim.
> 
> A nice to have would be to fix the centering of the the text in the frame.

I have adressed this by making the frame a child QGraphicsItem that now gets included in the regular boundingRect rather than hacking boudingRect. Also, the incorrect centering when using over- and undertolerance has also been fixed.

Should completely address everything in #15103. @WandererFan 

The very small margin between dimension line and frame is outside the scope of this PR. It would require adding functions giving bounding rect when using X height to fix the margin. The margin without the frame is very low, as it's relative to the decimalseperator and not the number. Using the same margin for the frame makes it the margin look incredible small - even though it's the same margin spacing used in between the bounding rects.

image

**Comment by WandererFan** [comment]
Win CI fail is not related.

**Comment by maxwxyz** [comment]
is this already in the latest weekly from today? 
It seems not centered and also the distance between the snapping positions is so close, that the text now overlaps the arrows:
grafik

**Comment by benj5378** [comment]
> is this already in the latest weekly from today?

It must not be, as I cannot recreate this on the current main branch

**Comment by luzpaz** [comment]
Can you both kindly add your full [About](https://wiki.freecad.org/About) info ?

**Comment by maxwxyz** [comment]
```
OS: macOS 13.6.9
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38622 (Git)
Build type: Release
Branch: main
Hash: ed97f3c4591303ee3b54906768f8f4eba5211265
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.8.17
  * CfdOF 1.27.5
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.27
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.24
  * Curves 0.6.45

```

**Pull request merged**
