### PR TITLE
Sketcher - Add new Split Edge action

### PR DESCRIPTION
**Pull request by pavltom**
A new Sketcher functionality "Split Edge" allowing the user to split a line segment, circle or an arc of circle at selected point.

### CODE REVIEW

**Comment by pavltom** [comment]
For more detailed description please see the forum topic at https://forum.freecadweb.org/viewtopic.php?f=9&t=55412

**Comment by luzpaz** [comment]
@bitacovir do you mind converting the 2 SVG files to plain SVG?

**Comment by bitacovir** [comment]
> @bitacovir do you mind converting the 2 SVG files to plain SVG?

Ok. I'll have a look.

**Comment by yashpalgoyal1304** [comment]
wow, that's super awesome. thanks a lot for this. i missed this a lot in v0.19

**Pull request merged**
