### PR TITLE
Delete .log_errors

### PR DESCRIPTION
**Pull request by mosfet80**
remove unused file

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
> remove unused file

Who says that it's unused?

**Comment by wwmayer** [comment]
@PrzemoF please check if it can be removed.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6458">pipeline status</a> for feature branch [PR_6458](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6458). Pipeline [480389236](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/480389236) was triggered at [98a856d](https://github.com/FreeCAD/FreeCAD/pull/6458/commits/98a856df4622b3c5ee226f4e74bc24af12b27219). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@PrzemoF, can you please comment?

**Comment by wwmayer** [comment]
> However, the File log_errors is generated with the execution of travis

No, it doesn't look like it gets created by running travis. Instead it's used by grep to load some pattern in order to search through the file FreeCAD_installed.log and that one gets created by running travis.
```
${INSTALLED_APP_PATH} --log-file /tmp/FreeCAD_installed.log
...
grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )

```

**Comment by adrianinsaval** [comment]
is anything else besides travis expected to use this? we've removed the travis stuff now

**Comment by mosfet80** [comment]
now travis has been removed. the file is no longer used

**Pull request merged**
