### PR TITLE
Draft: Point array: Take placement of point object into account and accept more point object types

### PR DESCRIPTION
**Pull request by Roy-043**
The Placement of some point objects was ignored. And the number of supported point object types was rather restrictive.

Forum topics:
https://forum.freecadweb.org/viewtopic.php?f=23&t=59359
https://forum.freecadweb.org/viewtopic.php?f=3&t=61144&p=524241#p524233
https://forum.freecadweb.org/viewtopic.php?f=23&t=71957

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7597">pipeline status</a> for feature branch [PR_7597](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7597). Pipeline [664665323](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/664665323) was triggered at [a4a11a4](https://github.com/FreeCAD/FreeCAD/pull/7597/commits/a4a11a42d3a2b87fd248804f2be5353d0974c73f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@Roy-043 , can this be backported for 0.20.2?

**Comment by Roy-043** [comment]
@donovaly No, do not backport. This PR has been added to 1.0 release notes.

**Comment by donovaly** [comment]
> @donovaly No, do not backport. This PR has been added to 1.0 release notes.

Thanks

**Pull request merged**
