### PR TITLE
Topo Naming accumulated fixes

### PR DESCRIPTION
**Pull request by realthunder**
Fixed some problems that the user [reported](https://github.com/realthunder/fcad_pcb/issues/61) as well as I discovered during my own testing.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7792">pipeline status</a> for feature branch [PR_7792](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7792). Pipeline [693255773](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/693255773) was triggered at [b8fb433](https://github.com/FreeCAD/FreeCAD/pull/7792/commits/b8fb433caf4931715ca8d0b7bcf618ddc7fc1fb0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by realthunder** [comment]
@chennes @donovaly Hi, can anyone take a look at this PR? It is a fix for FreeCAD/FreeCAD-Bundle#143

**Comment by chennes** [comment]
It looks to me like @easyw is still experiencing the reported issue, even after you patched LinkDaily: https://forum.freecadweb.org/viewtopic.php?p=640814#p640814

Or has this since been patched again?

**Comment by realthunder** [comment]
No, the patch comes after the release he tried.

**Comment by chennes** [comment]
I don't see any problems with the code, but I am unable to run the snippet of test code that @easyw provided. I propose we merge this now, and revisit if it turns out that it doesn't actually solve his problem.

**Comment by donovaly** [comment]
I agree with @chennes.

@realthunder , can you please have a look at the comments from the CI (clazy) about the code:
https://github.com/FreeCAD/FreeCAD/pull/7792/commits/b8fb433caf4931715ca8d0b7bcf618ddc7fc1fb0
and address those you find reasonable?

**Pull request merged**
