### PR TITLE
Marlin Post Processor not able to write to disk - PR

### PR DESCRIPTION
**Pull request by ronaksingh27**
final returned at line 461 in  `src/Mod/CAM/Path/Post/scripts/marlin_post.py `

### CODE REVIEW

**Comment by ronaksingh27** [comment]
@ringnutz I appreciate your assistance with this, and I'm hopeful it will resolve the G-code export issue. Please let me know if you need anything further from my side!

**Comment by hyarion** [comment]
While this PR fixes the error, it will write the file twice, right?

* 1st time in here: https://github.com/FreeCAD/FreeCAD/pull/17172/files#diff-9d03745d3d77f3817a2a4ec2fe2169b165f9460a99c530a6d32b17b76e5b7eb3R459
* 2:nd time here: https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/CAM/Path/Post/Command.py#L135 called from here https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/CAM/Path/Post/Command.py#L207

This issue looks like a regression from the [major refactor of the post stack](https://github.com/FreeCAD/FreeCAD/commit/0514163ec71a8380e7ebaddc0bf6944e8caddf01).

@sliptonic what do you think here? Should the post command or the post processor write the gcode file?
If the former (as the new code suggests), are there other post processor scripts that needs to be changed as well?

**Comment by ringnutz** [comment]
I copied that line by comparing it to the grbl_post file which did write the file properly. If that line is not there it writes a 0 byte file to the specified location. 

I am unsure if it writes it twice

**Comment by sliptonic** [comment]
The grbl and Marlin posts are the old style. Ideally they would be refactored into the new style.  Short of that, they should be'wrapped' by the WrapperPost which should happen automatically.  

Writing output should not happen in the post.  If it does, it won't be compatible with Sanity which needs the post to return the output without writing it to disk.

**Comment by hyarion** [comment]
@sliptonic do you know if anyone is refactoring these two post processors or how should we proceed here?

**Comment by sliptonic** [comment]
@chennes This is ok to merge and backport.

@hyarion @ringnutz  It's probably writing to disk twice, but it's not a big deal. Yes, the post should be refactored—all of them should be—and there's some work in that area. @LarryWoestman has been picking on it for some time.

The generic_post.py is a place to start.  The important part is that logic common to all the posts should be factored out to the PostProcessor base class and the individual posts should just handle the unique aspects.  That's more work than we'll tackle for 1.0.

**Comment by hyarion** [comment]
@sliptonic can you create a new issue for the refactoring of these two post processors? (So we don't forget about it)

**Comment by chennes** [comment]
This was backported two weeks ago, right after I merged it, I just forgot to mark it as such.

**Pull request merged**
