### PR TITLE
Windows: Sync StackWalker class with upstream

### PR DESCRIPTION
**Pull request by wwmayer**

### CODE REVIEW

**Comment by chennes** [comment]
Do we have local changes rolled in here, or is this now 100% upstream code?

**Comment by 3x380V** [comment]
After removing formatting and whitespace noise the diff reads:
```
--- /tmp/StackWalker.h	2024-07-30 12:11:22.874520651 +0200
+++ /tmp/StackWalker-upstream.h	2024-07-30 12:11:45.527289757 +0200
@@ -1,5 +1,3 @@
-// clang-format off
-// NOLINTBEGIN
 #ifndef __STACKWALKER_H__
 #define __STACKWALKER_H__
 
@@ -43,10 +41,7 @@
 // so we need not to check the version (because we only support _MSC_VER >= 1100)!
 #pragma once
 
-#include <Windows.h>
-#ifndef FC_GLOBAL_H
-#include <FCGlobal.h>
-#endif
+#include <windows.h>
 
 // special defines for VC5/6 (if no actual PSDK is installed):
 #if _MSC_VER < 1300
@@ -59,7 +54,7 @@
 #endif // _MSC_VER < 1300
 
 class StackWalkerInternal; // forward
-class BaseExport StackWalker
+class StackWalker
 {
 public:
   typedef enum ExceptType
@@ -265,7 +260,8 @@
 
 // The following is defined for x86 (XP and higher), x64 and IA64:
 #define GET_CURRENT_CONTEXT_STACKWALKER_CODEPLEX(c, contextFlags)                                  \
-    do {                                                                                           \
+  do                                                              \
+  {                                                               \
         memset(&c, 0, sizeof(CONTEXT));                                                            \
         c.ContextFlags = contextFlags;                                                             \
         RtlCaptureContext(&c);                                                                     \
@@ -275,5 +271,3 @@
 #endif  // defined(_MSC_VER)
 
 #endif  // __STACKWALKER_H__
-// NOLINTEND
-// clang-format on
--- /tmp/StackWalker.cpp	2024-07-30 12:14:20.044497260 +0200
+++ /tmp/StackWalker-upstream.cpp	2024-07-30 12:15:58.631790239 +0200
@@ -1,5 +1,3 @@
-// clang-format off
-// NOLINTBEGIN
 /**********************************************************************
  *
  * StackWalker.cpp
@@ -24,9 +22,10 @@
  *                       which can be used in the readMemoryFunction-callback)
  *  2005-08-02   v4    - OnSymInit now also outputs the OS-Version by default
  *                     - Added example for doing an exception-callstack-walking in main.cpp
- *                       (thanks to owillebo: http://www.codeproject.com/script/profile/whos_who.asp?id=536268)
- *  2005-08-05   v5    - Removed most Lint (http://www.gimpel.com/) errors... thanks to Okko Willeboordse!
- *  2008-08-04   v6    - Fixed Bug: Missing LEAK-end-tag
+ *                       (thanks to owillebo:
+ *http://www.codeproject.com/script/profile/whos_who.asp?id=536268) 2005-08-05   v5    - Removed
+ *most Lint (http://www.gimpel.com/) errors... thanks to Okko Willeboordse! 2008-08-04   v6    -
+ *Fixed Bug: Missing LEAK-end-tag
  *                       http://www.codeproject.com/KB/applications/leakfinder.aspx?msg=2502890#xx2502890xx
  *                       Fixed Bug: Compiled with "WIN32_LEAN_AND_MEAN"
  *                       http://www.codeproject.com/KB/applications/leakfinder.aspx?msg=1824718#xx1824718xx
@@ -84,7 +83,6 @@
  *
  **********************************************************************/
 
-#include <PreCompiled.h>
 #include "StackWalker.h"
 
 #include <stdio.h>
@@ -1624,5 +1622,3 @@
 {
     OutputDebugStringA(buffer);
 }
-// NOLINTEND
-// clang-format on
```
So this could be as well a 3rd party git submodule.

**Comment by wwmayer** [comment]
There are a couple of local changes:
* include FCGlobal.h
* use export macro BaseExport
* include PreCompiled.h
* use clang-format off/on
* use NOLINTBEGIN/NOLINTEND

**Comment by 3x380V** [comment]
@chennes, I do not have easy access to a Windows machine to give an idea a try. It is in the in office I'm attending few times a month, so I suggest to apply this one as it is clearly an improvement and I'll prepare PR on the top of this one. Then you can decide whenever you like or not.

**Comment by wwmayer** [comment]
> include PreCompiled.h

As far as I can see this is not even needed because inside the CMakeLists.txt of FreeCADBase PCH is not activated for StackWalker.cpp.

 > use export macro BaseExport

A way is to not link in FreeCADBase but FreeCADMain. But as soon as also using it in a different module it may  cause linking problems because of duplicated symbols.

**Comment by chennes** [comment]
Sounds good, I'll merge this one now, and we can investigate making it a submodule later on.

**Pull request merged**
