### PR TITLE
PD: Fix Loft's Closed option

### PR DESCRIPTION
**Pull request by Fat-Zer**
Closes: https://github.com/FreeCAD/FreeCAD/issues/6156

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8748">pipeline status</a> for feature branch [PR_8748](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8748). Pipeline [796769963](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/796769963) was triggered at [d1f80a7](https://github.com/FreeCAD/FreeCAD/pull/8748/commits/d1f80a7d396fac8c0e9f8f4b672fe24b201caf43). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Hi @Fat-Zer do you mind fixing the typo in the commit from 'Fis' to 'Fix' ?

**Comment by Fat-Zer** [comment]
> Hi @Fat-Zer do you mind fixing the typo in the commit from 'Fis' to 'Fix' ?

Hi, sorry about that... it just slipped from my view...

Fixed... also fixed compilation with an older boost...

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8748">pipeline status</a> for feature branch [PR_8748](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8748). Pipeline [796995402](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/796995402) was triggered at [067574b](https://github.com/FreeCAD/FreeCAD/pull/8748/commits/067574b387299d8b2a7691fb5093518817933d0c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks! This was a long-standing and well-known bug.

**Comment by luzpaz** [comment]
@Fat-Zer off-topic but would you mind going through some of the old TODOs in the code you've added back in the day (circa ~2015(
https://github.com/search?q=repo%3AFreeCAD%2FFreeCAD%20Fat-Zer&type=code

**Comment by luzpaz** [comment]
@Fat-Zer :point_up_2: would you have any time for that?

**Pull request merged**
