### PR TITLE
Revert "Address the poor performance of the existing unique-name generation (#17944)"

### PR DESCRIPTION
**Pull request by hyarion**
This reverts commit 83202d8ad67a719cb62e29d9dc3496a076999f1f (https://github.com/FreeCAD/FreeCAD/pull/17944) which is causing issues.

Looks like more work needs to be done before we can include it in main branch, see: https://github.com/FreeCAD/FreeCAD/issues/18504

Conflicts:
    src/Base/Tools.cpp
    src/Base/Tools.h

Kept as Draft until verified to compile (was conflicts)

### CODE REVIEW

**Comment by hyarion** [comment]
Created this revert pr for the meeting today, as requested.

**Comment by hyarion** [comment]
@maxwxyz ping

**Comment by hyarion** [comment]
@kpemartin FYI, if this revert is applied, your work will be removed. Hopefully it can be fixed and reapplied again. Fast name generation would be good to have 👍 

Feel free to join the meeting, you have the link here https://www.freecad.org/events.php

**Comment by Syres916** [comment]
@kpemartin when you resubmit please include some simple unit tests around duplication of Part Design Bodies and deeply nested Step assemblies with certain solids using non-default materials. If the document does not contain exactly 100% more objects than before the duplication then it's a fail, as well as all objects must have the same appearance settings in the _copy_ as the _original_.

**Pull request merged**
