### PR TITLE
[PD] UserEditMode : fix operating on PartDesignObject

### PR DESCRIPTION
**Pull request by 0penBrain**

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5204">pipeline status</a> for feature branch [PR_5204](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5204). Pipeline [417423674](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/417423674) was triggered at [3a03551](https://github.com/FreeCAD/FreeCAD/pull/5204/commits/3a03551987af2c2e327c90d41af62fd44b4a1862). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
The fix works but I must admit that I don't have the knowledge yet to understand what side effects on the PD WB could occur.

**Comment by 0penBrain** [comment]
@donovaly I had asked in the past information about that but never get an answer. So I choose to move on and thoroughly test the behavior. I didn't find anything weird so pushed the PR. But better if someone with a good understanding of what's running under the hood can review.

**Comment by donovaly** [comment]
You did everything right. It is just that I don't know yet enough to judge the PR. I asked already Werner to have a look.

**Comment by wwmayer** [comment]
> But better if someone with a good understanding of what's running under the hood can review.

The PR is fine and as side-effect makes things even more consistent because the doubleClicked() function should do exactly the same as when you open the context-menu and click the bold item.

**Review by wwmayer — APPROVED** [review]

**Comment by wwmayer** [comment]
Merged by hand since the first line needs to be removed: 7aef0b3de7

**Comment by 0penBrain** [comment]
@wwmayer Thx. Sorry for missing the unused variable in the commit. ;)

**Pull request closed without merging**
