### PR TITLE
PATH: Feature/Stock - first steps in supporting Stock

### PR DESCRIPTION
**Pull request by mlampert**
Adds the first support for Base object alignment and Stock to PathJob.

Job references the Base object through a clone, allowing independent placement for machining, and different placements for the same Base object in different jobs. Creates a stock object from different sources and provides tools for simple placement of stock and base object.

New TaskPanel for Job that should make it easier to edit a Job and get to a valid output that can be processed by a machine.

JobTemplate also has support for stock allowing the definition of a standard machine setup minimizing design placement and thickness mistakes (not that any of those ever happened to me...)

### CODE REVIEW

**Comment by bblacey** [comment]
FYI, I just restarted the Travis-CI Mac jobs because they seemed to have failed in an unusual manner symptomatic of a Travis infrastructure issue.

**Comment by mlampert** [comment]
Thanks - much appreciated!

**Comment by mlampert** [comment]
Same thing seems to have happened again. I can't see an error in the logs it just seems to stop. Any help/pointers?

**Comment by bblacey** [comment]
I believe the root cause is an issue with the Travis infrastructure for macOS and not your pull request..  The builds seem to be exceeding a 20 minute timeout while fetching the FreeCAD-ports-cache.  The ports-cache is hosted on GitHub so these downloads should be quick and typically take a couple of minutes so I think Travis either has a networking or I/O issue.  I will restart the builds again but if they fail, please ping me and I will submit a request with the Travis folks to take a look.

**Comment by mlampert** [comment]
yeah - all builds passed!

**Comment by bblacey** [comment]
👍

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
