### PR TITLE
Draft: Avoid faulty Base.Placement.rotate() in draftobjects.array.py

### PR DESCRIPTION
**Pull request by Roy-043**
The implementation of `Base.Placement.rotate()` is 'faulty': it is not compatible with `TopoShape.rotate()`. To deal with this, unnecessarily complex code was created. Which did not always work for circular arrays.

The new code uses a workaround provided on the forum:
https://forum.freecadweb.org/viewtopic.php?p=613196#p613196

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by Roy-043** [comment]
Example of an incorrect circular array produced with the old code.

The white circle indicates the center of the array.
The dashed white polylines indicate where two elements in the array should occur.
circ_array_test

Zipped circ_array_test.FCStd file:
[circ_array_test.zip](https://github.com/FreeCAD/FreeCAD/files/9209482/circ_array_test.zip)

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7267">pipeline status</a> for feature branch [PR_7267](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7267). Pipeline [600453109](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600453109) was triggered at [f2b05b2](https://github.com/FreeCAD/FreeCAD/pull/7267/commits/f2b05b2986e6cf414df3dc93c7358cb6349967b3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> The implementation of Base.Placement.rotate() is 'faulty': it is not compatible with TopoShape.rotate(). 

Shouldn't this be fixed then directly in Base rathewr than introducing a workaround? @wwmayer ?

**Comment by yorikvanhavre** [comment]
Placement multiplication operate indeed backwards while toposhape multiplication apparently not (I wasn't aware of this..)... I don't think it would be safe to change the way placements operate, nor toposhapes, as it could cause a massive earthquake all over FreeCAD, because many many operations depend on the way it works now.

I'd vote to rather merge this one

**Comment by Roy-043** [comment]
There already is a PR to fix the issue with Base.Placement.rotate(): https://github.com/FreeCAD/FreeCAD/pull/7273

So we can also wait for that PR to be merged first and then update this one.

**Comment by wwmayer** [comment]
> Shouldn't this be fixed then directly in Base rather than introducing a workaround?

IMO yes. The current behaviour of Placement.rotate() is a bug because the doc string clearly says it's compatible with TopoShape.rotate() but in fact it isn't. 
So, we should check the FreeCAD code base where this faulty rotate() function is used (I only found the 2 occurrences in Draft's array module) and fix the broken rotate() function and its occurrences.

The only point to consider is how much the broken function is used in external Python scripts where we have no control over. But I can hardly imagine that it's used that much because of its weirdness.

To be 100% safe in the other PR an optional parameter `comp` is added that by default shows the faulty behaviour and to get the correct behaviour it must be explicitly set.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7267">pipeline status</a> for feature branch [PR_7267](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7267). Pipeline [611204248](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/611204248) was triggered at [2647c37](https://github.com/FreeCAD/FreeCAD/pull/7267/commits/2647c37289e1bda011001ca3259f212b2d76b6e2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7267">pipeline status</a> for feature branch [PR_7267](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7267). Pipeline [611206814](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/611206814) was triggered at [f22de4c](https://github.com/FreeCAD/FreeCAD/pull/7267/commits/f22de4cfd2d495cd6e06b86617a110356eeab68c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Okay this looks fine now, then. Ok to merge @Roy-043 ?

**Comment by Roy-043** [comment]
Yes, this can be merged.

**Pull request merged**
