### PR TITLE
FEM: extend Abaqus writer to write groups

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT]

https://forum.freecadweb.org/viewtopic.php?f=10&t=25381
in my mind for a long time but initiated by https://forum.freecadweb.org/viewtopic.php?f=3&t=25347

@werner:
it makes sense to have a closer look here https://github.com/berndhahnebach/FreeCAD_bhb/blob/bhbdev103/src/Mod/Fem/App/FemMesh.cpp#L1296-L1561 IMHO

### CODE REVIEW

**Comment by berndhahnebach** [comment]
Damn, I'm to late with this PR ... The 11th of November, 11 past 11 has happened around two weeks ago ...

**Comment by yorikvanhavre** [comment]
merged

**Comment by wwmayer** [comment]
@berndhahnebach 
> it makes sense to have a closer look here ...

What exactly do you expect me to do?

Some comments:
FemMesh::getEdgesOnly is extremely inefficient because for every edge you iterate over all faces until you find one with the given edge id. This leads to a quadratic runtime.
Wouldn't it be much more efficient to iterate once over all faces and store their edge ids in a set and then iterate over all edges storing the ids in a different set? The difference of both sets gives you the edge ids that are not shared by any face. The runtime will then be linear.

The same applies to FemMesh::getFacesOnly.

**Comment by berndhahnebach** [comment]
Nothing special I just really appreciate any C++ tip since I'm still learning a lot on any C++ code I write. 

In the regard of run time and your hint. This should work. I will give it a try! 

Bernd

**Pull request closed without merging**
