### PR TITLE
Add TaackPLM_workbench_icon.svg in resources

### PR DESCRIPTION
**Pull request by Taack**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8446">pipeline status</a> for feature branch [PR_8446](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8446). Pipeline [775006532](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/775006532) was triggered at [b914999](https://github.com/FreeCAD/FreeCAD/pull/8446/commits/b9149997649923768ce95645864b8b4246bee78a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@Taack why are you adding this icon into FreeCAD master rather than in your workbench Resources? Doesn't make much sense. 😕

**Comment by wwmayer** [comment]
@0penBrain It's fine because for many other add-ons their icon is part of the resources of the AddonManager.

**Comment by Taack** [comment]
@0penBrain I was just following instructions there: 
https://github.com/FreeCAD/FreeCAD-addons/issues/251

You are right, the workbench brings its own icons, I was thinking it was mandatory.. (sorry for yesterday PR..)

**Comment by 0penBrain** [comment]
@wwmayer thanks for pointing this out. 

@Taack my bad, I wasn't aware of this procedure

**Comment by chennes** [comment]
@0penBrain You are actually correct -- it's no long necessary for Addons to have their resources added to the main repo. I will update the instructions (I thought I had done so already, but I must have missed a spot).

**Pull request merged**
