### PR TITLE
Sketcher: Split B-Splines

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
With these changes the split tool in sketcher also works on b-splines.

Some changes also had to be made in `Part::GeomBSplineCurve::Trim()` to split periodic b-splines.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6494">pipeline status</a> for feature branch [PR_6494](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6494). Pipeline [483331501](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/483331501) was triggered at [5fc2ed1](https://github.com/FreeCAD/FreeCAD/pull/6494/commits/5fc2ed154cb276641de0e77d7915976194821c13). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6494">pipeline status</a> for feature branch [PR_6494](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6494). Pipeline [485159465](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/485159465) was triggered at [abf5289](https://github.com/FreeCAD/FreeCAD/pull/6494/commits/abf5289b2207457700544136bafebe68631f5d62). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6494">pipeline status</a> for feature branch [PR_6494](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6494). Pipeline [485290457](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/485290457) was triggered at [387a561](https://github.com/FreeCAD/FreeCAD/pull/6494/commits/387a561e032a3d9d2ce20d30fd3530fe958b4a73). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by AjinkyaDahale** [comment]
@donovaly do you plan to add this to 0.20? If yes I'll make any further developments in this tool in a separate branch.

**Comment by donovaly** [comment]
> do you plan to add this to 0.20?

Now that the feature freeze is in effect, all developers will revise the pending PRs and either merge of postpone it.
@abdullahtahiriyo maintains Sketcher and will have a look.

If this PR makes it in, please only bugfixes to it for 0.20. I hope you understand that we must freeze the features in order to stabilize the code and to allow translators to do their work.

While we are at it, please have a look at
https://wiki.freecadweb.org/Release_notes_0.20
and the different Wiki pages if all your great features are properly described.

**Comment by AjinkyaDahale** [comment]
> If this PR makes it in, please only bugfixes to it for 0.20. I hope you understand that we must freeze the features in order to stabilize the code and to allow translators to do their work.

I understand, which is why I was asking before I make any changes.

> While we are at it, please have a look at https://wiki.freecadweb.org/Release_notes_0.20 and the different Wiki pages if all your great features are properly described.

I'm pretty sure anything worth mentioning is already in (apart from this, #6494 and #6476), but I'll take a look.

**Comment by AjinkyaDahale** [comment]
accidentally deleted branch which closed this issue

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6494">pipeline status</a> for feature branch [PR_6494](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6494). Pipeline [553484979](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/553484979) was triggered at [d528eec](https://github.com/FreeCAD/FreeCAD/pull/6494/commits/d528eec64419d9cbb65c89a626f696ff5354aa60). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by AjinkyaDahale** [comment]
Rendered obsolete because of recent changes in `DrawSketchHandler` structure. Better to only rebase one PR #6971.

**Pull request closed without merging**
