### PR TITLE
[Feature Request] [Draft] [UI/UX] Remove the center arrow on radial dimensions

### PR DESCRIPTION
**Pull request by CalligaroV**
Related to issue #7573

**Forum discussion**

https://forum.freecadweb.org/viewtopic.php?p=631252#p631252

These modifications don't add the new properties suggested on the issue mentioned above and suggested on the forum discussion but just remove the center arrow

Other info and discussion can be found at https://gitlab.com/calligarov/FreeCAD/-/merge_requests/1

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Looks good to me!

**Comment by Roy-043** [comment]
While testing I discovered a dimension bug not related to the proposed code. Will do a PR for that later.

**Comment by Roy-043** [comment]
@CalligaroV Thanks again! Merging...

**Comment by luzpaz** [comment]
Congrats on your PR merge and thanks for contributing!

**Comment by CalligaroV** [comment]
@Roy-043, @yorikvanhavre , @luzpaz Thank you very much for your feedback, your help and your kind words!
As an Open Source fan, receiving this kind of messages and seeing my contribution merged has much value, thanks again!

I was thinking about writing a post on the Release Notes 0.22 forum topic but I saw that you @Roy-043 already added to the wiki page. You beat me on time! :smile: 

That said, is there something else I should do to consider this issue/PR closed on all it's aspects?

**Comment by Roy-043** [comment]
This PR is completed, but IMO #7573 should stay open.

**Pull request merged**
