### PR TITLE
Reduce demo icon theme

### PR DESCRIPTION
**Pull request by triplus**
Mitigate an issue with scaled icons as discussed:
https://forum.freecadweb.org/viewtopic.php?f=10&t=28838&p=363487#p363487

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Isn't this PR bettering things for some, but worsening for others? (Removing theme support)

**Comment by triplus** [comment]
This PR doesn't remove icon theme support.

There is a demo theme embedded in FreeCAD and it's set to ON by default, named FreeCAD-default. There are only a few icons added to it, but they are the exact same icons that are used as a "fallback". Therefore if this theme is set to ON or OFF the icons will still look the same. I left one icon in it for demonstration purposes, on how can an icon theme be embedded in FreeCAD. And it is a good thing to have such option, for still being able to enable such icon theme on Linux, when you want to override the system default one. As seen in this PR:

https://github.com/FreeCAD/FreeCAD/pull/2945

**Comment by yorikvanhavre** [comment]
Understood. Ok then!

**Comment by Mikhaylov-yv** [comment]
Do I understand correctly that this commit should fix the display of icons? 

[I do not see changes](https://github.com/Mikhaylov-yv/Mi_img/blob/master/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202020-01-29%2000-02-06.png?raw=true)

OS: Ubuntu 19.10 (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.19406 (Git)
Build type: Unknown
Branch: master
Hash: 1991a08ffdd518ac218a782738e97b9948029d00
Python version: 3.7.5
Qt version: 5.12.4
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Russian/Russia (ru_RU)

**Pull request merged**
