### PR TITLE
PD: Make InvoluteGear's property descriptions translatable and reuse them as task panel tooltips

### PR DESCRIPTION
**Pull request by jbaehr**
This is a follow-up to #8184, extending the task panel with tool tips.

For the tool tips, the property descriptions are reused. This avoids maintaining the same information in two places. The property descriptions have been made translatable, too, to ensure a fully translatable UI.

Overall, this PR follows the same methodology as #5321. However, I did not managed to make an *open* task panel retranslate itself in case the UI language is changed. In C++ this is done by overwriting the TaskPanel's `changeEvent`, but this does not seem to be exposed to Python. @wwmayer, any ideas?

I did not find any Python task panel reacting on language-change while open. When closing and reopening the task panel, the new language setting is used, though.

---

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Please open a ticket for a feature request to support language change.

**Comment by jbaehr** [comment]
> Please open a ticket for a feature request to support language change.

Done: #8274

Should this PR wait till then? Otherwise I'd just open a follow-up once this base functionality is ready. In that case I consider this PR here as ready -- I do not want to spoil it by introducing artificial base classes, checking-in uic-generated code, or other ugly stuff just to provide a minor feature that no other Python task panel offers either.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8247">pipeline status</a> for feature branch [PR_8247](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8247). Pipeline [761019273](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761019273) was triggered at [727209b](https://github.com/FreeCAD/FreeCAD/pull/8247/commits/727209b94592cea05357ea2fc528c9c0bf380aff). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
> Should this PR wait till then? 

No, it can already be merged.

**Comment by jbaehr** [comment]
Any updates on this? I didn't expect this to be a controversial PR...

**Comment by chennes** [comment]
I just merged it -- it's a solid improvement. @luzpaz this doesn't close #8274 -- that would be an extra feature that we don't support yet.

**Comment by wwmayer** [comment]
> Any updates on this? I didn't expect this to be a controversial PR...

It's all good with your PR, nothing controversial at all. I only hoped to find the time to implement the language change event handling and test against your PR.

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/8602

**Pull request merged**
