### PR TITLE
Sketcher:  copy,paste (or export/import as xml) geometries with ctrl-c/x ctrl-v

### PR DESCRIPTION
**Pull request by PaddleStroke**
Video and description : https://forum.freecadweb.org/viewtopic.php?f=9&t=65892
Description : add support to copy/paste geometries in sketcher using ctrl-X/C and ctrl-V
Geometries (and relevent constraints) are copied to computer clipboard as xml text. Enabling exporting and paste in other Freecad instances or even share on forum.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5480">pipeline status</a> for feature branch [PR_5480](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5480). Pipeline [462151177](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/462151177) was triggered at [e791491](https://github.com/FreeCAD/FreeCAD/pull/5480/commits/e7914912d31512d14651803687778d5dc64741c8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Better to `git rebase` than `git merge` as it pollutes the git history. Also all commits should have `Sketcher:` pre-pended to their summary

**Comment by 0penBrain** [comment]
Please squash the commits so master merges don't appear.
CI build failed for valid reason (also warnings are valid). Please have a look.
IMO, this should be refactored to use the standard Cut/Copy/Paste commands (which --good point-- currently are undefined for this use case).

**Comment by PaddleStroke** [comment]
Thank you guys for the reviews.
I see, those extra commits are ugly indeed. Github is very tempting with it's 'update branch' button! I can squash them then.

> CI build failed for valid reason (also warnings are valid). Please have a look.
Sorry but I don't understand. What does that means?

>this should be refactored to use the standard Cut/Copy/Paste commands
I implemented it where I could due to my lake of understanding of the general keyboard controls. It would indeed be better if it was in the standard cut/copy/paste commands.
@OpenBrain, if you are familiar with the general copy/paste system can you handle it from here to move it to the correct places? If so should I still squash the commits? Thanks

**Comment by 0penBrain** [comment]
> > CI build failed for valid reason (also warnings are valid). Please have a look.
> 
> Sorry but I don't understand. What does that means?

Look at the build errors/warnings there : https://gitlab.com/freecad/FreeCAD-CI/-/jobs/2046678580
> > this should be refactored to use the standard Cut/Copy/Paste commands
> 
> I implemented it where I could due to my lack of understanding of the general keyboard controls. It would indeed be better if it was in the standard cut/copy/paste commands. @openbrain, if you are familiar with the general copy/paste system can you handle it from here to move it to the correct places? If so should I still squash the commits? Thanks

In such a case, you'd better ask before starting to code. ;) 
I won't do this for you but can tell you where you have to look at : 

Cut/Copy/Paste commands are defined in https://github.com/FreeCAD/FreeCAD/blob/master/src/Gui/CommandDoc.cpp

Then you'll find same functions in each command : 

- 1st you have to modify "isActive()" function of each command, so commands are enabled in new situations that you implement
- 2nd you have to modify "activated()" function of each command. This is what is called when user tun the command (click, shortcut, ...). There you have to identify and handle new cases you want to add

**Comment by PaddleStroke** [comment]
> Cut/Copy/Paste commands are defined in https://github.com/FreeCAD/FreeCAD/blob/master/src/Gui/CommandDoc.cpp

Oh I had a look at those yesterday actually. So it should be implemented here?
There's currently only one behaviour which is defined there, to copy paste model tree objects.
The big question for me is how to identify the different cases: are we in sketch edit? How can we check that?

Beside regarding the general copy paste, I actually posted yesterday about that on the forum : https://forum.freecadweb.org/viewtopic.php?f=10&t=65899 if you want to give me your opinion about that too.

**Comment by 0penBrain** [comment]
> Oh I had a look at those yesterday actually. So it should be implemented here?

Probably not the whole feature. But you should catch there if the current situation is the one that you want to handle, then call your functions.
>There's currently only one behaviour which is defined there, to copy paste model tree objects. The big question for me is how to identify the different cases: are we in sketch edit? How can we check that?

Take example where it already works ;) https://github.com/FreeCAD/FreeCAD/blob/8492cfb9eb49f6d882ceefb60440acd2a30fccfd/src/Mod/Sketcher/Gui/Command.cpp#L321-L331

**Comment by 0penBrain** [comment]
> Thanks! When you know where it is it may be obvious, but when you don't figuring it out is very slow an painful.

Nobody born knowing where things are. ;) That's a somewhat painful learning, but useful if you want to contribute on a regular basis. In this case, I just open FreeCAD and searched for a command that was enabled only (and always) when a sketch is in edit mode. ;)
 > Besides I can't get that to work. VS is interpreting 'SketcherGui::ViewProviderSketch* vp' as SketcherGui::SketcherGuiExport SketcherGui::ViewProviderSketch And so doesn't accept it. I included : #include <Mod/Sketcher/Gui/ViewProviderSketch.h> Is that not enough?

Most probably you need to `using namespace SketcherGui;` (generally it's added just below #includes imports).

**Comment by PaddleStroke** [comment]
> Nobody born knowing where things are. ;) That's a somewhat painful learning, but useful if you want to contribute on a regular basis. In this case, I just open FreeCAD and searched for a command that was enabled only (and always) when a sketch is in edit mode. ;)

Well unless you made the code yourself. It's frustrating because I spend 90% of my time trying to understand the current code structure and only 10% doing usefull stuff.

> Most probably you need to `using namespace SketcherGui;` (generally it's added just below #includes imports).

I already tried that and it doesn't change. :(

**Comment by 0penBrain** [comment]
> I already tried that and it doesn't change. :(

Can't tell much without seeing some code. :) Can you switch the PR to "Draft" state then push your code as is ?

**Comment by jbaehr** [comment]
Please note that there is a second forum thread about this PR: https://forum.freecadweb.org/viewtopic.php?f=17&t=65903, which is unfortunately not linked from the original description.
Where should the discussion finally take place?

**Comment by 0penBrain** [comment]
@jbaehr Things purely related to code can be discussed here. For other things, please use the topic in the PR description.

**Comment by PaddleStroke** [comment]
I basically just copy pasted your example in the copy command : 
`
#include <Mod/Sketcher/Gui/ViewProviderSketch.h>
using namespace SketcherGui;

void StdCmdCopy::activated(int iMsg)
{
    Q_UNUSED(iMsg);

    //Case : in sketch edit
    Gui::Document* doc = getActiveGuiDocument();
    if (doc) {
        // checks if a Sketch Viewprovider is in Edit and is in no special mode 
        SketcherGui::ViewProviderSketch *vp = dynamic_cast<SketcherGui::ViewProviderSketch*>(doc->getInEdit());
        if (vp /*&& vp->getSketchMode() == ViewProviderSketch::STATUS_NONE*/)
            return ;
    }

    bool done = getGuiApplication()->sendMsgToFocusView("Copy");
    if (!done) {
        QMimeData * mimeData = getMainWindow()->createMimeDataFromSelection();
        QClipboard* cb = QApplication::clipboard();
        cb->setMimeData(mimeData);
    }
}`

**Comment by 0penBrain** [comment]
@PaddleStroke : do not stack fix commits. All commits of the history shall be correct (and as much as possible atomic).
Now please squash commits. In the future,make extensive use of `git commit --fixup` and `git commit --autosquash` ;)

Also please rewrite commit message so it start with "WORKBENCH_NAME:"

**Comment by 0penBrain** [comment]
BTW, I had a look how to use ViewProviderSketch in CommandDoc.cpp but can't sort it out. Using it creates forward declarations.
Seems to be over my skills.

@wwmayer : may you have an idea how this could be worked out ? https://github.com/FreeCAD/FreeCAD/pull/5480#issuecomment-1029232462

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5480">pipeline status</a> for feature branch [PR_5480](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5480). Pipeline [464174140](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/464174140) was triggered at [b405ade](https://github.com/FreeCAD/FreeCAD/pull/5480/commits/b405ade1fe3e5e6e107c342b3ac6e83befc5b5b9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
> BTW, I had a look how to use ViewProviderSketch in CommandDoc.cpp but can't sort it out. Using it creates forward declarations.

You cannot and you mustn't . The design is that the core provides the basic infrastructure but it's up to the extension modules to do then the actual work. The core is not interested in what exactly an extension modules does and how it does it.

As a consequence you are not allowed to implicitly or explicitly add a dependency of an extension module to the core system. In this case it would not even work technically because SketcherGui links FreeCADGui and now you can't make FreeCADGui to also depend on SketcherGui as this would be a cyclic dependency and thus impossible to build the libraries. 

Please keep in mind: everybody is free to use the core system and e.g. implements his own Sketcher extension module. When doing so the core must behave the same independent on how the extension module is implemented but this wouldn't be possible if you added a dependency.

If you want to do something in an extension module but the core doesn't provide the basics then the way to go is to add a virtual function to a class in the core (here ViewProviderDocumentObject) and the override this function in the class of the module (here ViewProviderSketch).

**Comment by 0penBrain** [comment]
> If you want to do something in an extension module but the core doesn't provide the basics then the way to go is to add a virtual function to a class in the core (here ViewProviderDocumentObject) and override this function in the class of the module (here ViewProviderSketch).

Thx for insight. In this case, there is something interesting in https://github.com/FreeCAD/FreeCAD/blob/b806115015e4e69cd84f0c82821b9a434eb90316/src/Gui/CommandDoc.cpp#L1130
If I understand well, it would be possible that when Sketch is in edit mode, it is able to receive/accept a "Copy" command. Am I correct ? How does it roughly works to add/remove such a view command ? Thx

**Comment by PaddleStroke** [comment]
I fixed the compilation errors and squashed commits to get it clean.
But I don't understand where it should be implemented. Though I understand it's not in src/Gui/CommandDoc.cpp

> If I understand well, it would be possible that when Sketch is in edit mode, it is able to receive/accept a "Copy" command. Am I correct ? 

I understand the same by reading this line of code. Question is : How can we receive this message and where should we receive it?
I don't understand what function should be added to ViewProviderDocumentObject.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5480">pipeline status</a> for feature branch [PR_5480](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5480). Pipeline [468687006](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/468687006) was triggered at [8b5e33f](https://github.com/FreeCAD/FreeCAD/pull/5480/commits/8b5e33fe67f3caad2d760cbd2cb85018bfe05bf2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
> I understand the same by reading this line of code. Question is : How can we receive this message and where should we receive it? I don't understand what function should be added to ViewProviderDocumentObject.

I was looking after this but actually it's not currently possible because messages are only sent to views, and not to view providers. I think about a solution but as it is quite coding effort, prefer to check it's acceptable.

@wwmayer : what would you think if viewproviders may register/unregister message handlers to MDIView (or derived) ? So when a message arises the MDIView will call sequentially every registered message handler.

**Comment by wwmayer** [comment]
First of all I wonder what's wrong with the current behaviour? If you copy a selected sketch it is copied to the clipboard and can be pasted into a second FreeCAD instance. This is a global mechanism and works for all object types.

The only difference to your suggestion is that it's not an XML format but very similar to FreeCAD's FCStd file format. If you want to use a different file format you cannot use the general Copy command because there is no way to figure out if the FCStd or XML format is supposed to be used.

If you want to support the XML file format I recommend to add a new command to the Sketcher workbench to bypass the general mechanism. 

At least for the Paste command you could eventually use the global function. The class MainWindow allows to register so called "url handlers". You can make a subclass of UrlHandler in SketcherGui and register it with getMainWindow()->setUrlHandler(). Your Copy function than has to crate a MIME object that holds a url with the scheme name you choose with setUrlHandler().

**Comment by wwmayer** [comment]
OK, then it makes even more sense to create a special Copy command in the Sketcher module.

**Comment by luzpaz** [comment]
@PaddleStroke do you mind rebasing this PR? I'd like to create a dedicated Snap for this PR so folks can test it easier

**Comment by 0penBrain** [comment]
@luzpaz FYI this PR had implementation and architecture issues ;)

**Comment by luzpaz** [comment]
@0penBrain thanks. Yes, I was aware of that. But I was thinking it would still be cool to test the changes directly.

**Comment by chennes** [comment]
@PaddleStroke what are your thoughts on continuing this PR? It seems that it had some architectural issues that might warrant a complete restart. Do you want to keep this PR open to continue working on, or is your plan to drop or completely rework the concept?

**Comment by PaddleStroke** [comment]
Hi Chris,
I'll definitely pick it up soon.
I didn't went further because I didn't understand wmayer comments.
But now I think I can do the architecture correctly.

**Comment by PaddleStroke** [comment]
@wwmayer please advise what si the correct architecture to catch the CTRL + C key press.

I understood we need to create Sketcher_Copy command. That's OK I know how to do it.

The question is how do you catch the key presses to trigger the command. 

In my PR I caught them in the ViewProviderSketch::keyPressed but apparantly this is not acceptable.

**Comment by wwmayer** [comment]
> please advise what si the correct architecture to catch the CTRL + C key press.

I am not sure what you are after but it's not possible to have two commands using the same shortcut. What's possible is that several widgets can support the same shortcut and therefore one the widgets must have the focus but for a command no widget is involved.

**Comment by PaddleStroke** [comment]
> I am not sure what you are after but it's not possible to have two commands using the same shortcut. What's possible is that several widgets can support the same shortcut and therefore one the widgets must have the focus but for a command no widget is involved.

@wwmayer Please check the video to see what I want to do : https://forum.freecadweb.org/viewtopic.php?f=9&t=65892
Currently I just catch the ctrl + C events in the VPSketch. However @0penBrain reported this is not the way it should be done.

**Comment by AjinkyaDahale** [comment]
@PaddleStroke do you plan to get this merged?

**Comment by PaddleStroke** [comment]
Yes definitely. But it needs some architectural rework which was not clear
to me

**Comment by adrianinsaval** [comment]
converted to draft, you can mark as ready for review once it is reworked or close if you prefer starting the PR from scratch.

**Comment by luzpaz** [comment]
Closed with no reason ?

**Comment by PaddleStroke** [comment]
I picked it up and started fresh. Will post another PR soon.

**Pull request closed without merging**
