### PR TITLE
Navicube : Add missing view menu entries.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Edit: now this PR only adds 'fit selection'

Fixes https://github.com/FreeCAD/FreeCAD/issues/12317

This adds menu entries to the navicube button. The idea is to make the menu more complete so that users can hide the view toolbar and still have access to all its functionality.

image
Before left, after right
Remarks : 
- Yes I have put front/top... even though the cube provide this already. My reasoning is that sometimes I use the view toolbar because I don't want to analyze the cube to find top view. So I still like to have quick access to those.
- I have not added the Std_TreeViewActions because they feel out of context here. And not very useful so feel ok only in the main menu. Thoughts ?

### CODE REVIEW

**Comment by obelisk79** [comment]
There's nothing inherently wrong with this, but I don't see the value in the view functions being in the menu. In the same amount of mouse interaction, or less, you can get the same views just by interacting directly with the cube. It feels like redundant functionality in the same widget.

Also does the selection filter make sense here? What draws a user to associate 'selection priority' with the navicube? 

I think the other menu items added are sensible.

If the views are really desired in this menu, I'd suggest they be placed in a "named views" sub menu in order to keep the menu length easier to parse visually.

Section view might be a good addition here as well.

**Comment by MisterMakerNL** [comment]
Looks good!
From a user standpoint.
I never use default views, since big chances are my model doesn't have a correct upside.
And so if I would use default view I have to click true them. I just use the cube.
Solidworks btw also has the cube but it is only shown when you press space. Which to me is logical since I don't need it enough to take up valuable screen space all the time.
Solidworks also has these pull-down menu's those are logical, they belong to the 3D view and placing them there is a good spot!
So don't care about default views.
The cube is nice, but can be hidden by default in my opinion. 
The pulldown menu's are also very nice! A good PR!

**Comment by obelisk79** [comment]
> @obelisk79 what does DWG think?

So, I loaded up to do some actual testing and draft a modified proposal for this and noticed that these features are pretty much already available by right clicking on the cube itself. In light of that, I believe this PR brings nothing new and should not be merged.

@PaddleStroke

**Comment by PaddleStroke** [comment]
Right click on the tree is undefined actually. What you are seeing is the standard right click that happens on any empty view space.

However this doesn't mean this PR is not necessary, because the cube does have a menu button and this menu button is currently inconsistent in what it offers. Why "fit all" and not "fit selection"?
I think at the least we should add : 
"View selection"
and perhaps also : 
- "View section" 
- "Draw styles"

**Comment by obelisk79** [comment]
@PaddleStroke I was not referring to the tree. Right click on the actual navicube, not the menu button for it.

**Comment by obelisk79** [comment]
In this screenshot, I happened to right-click the corner of the cube:

image

**Comment by PaddleStroke** [comment]
You misunderstood my message. Anywhere you right click on the 3d view you get this menu. It is not specific to the cube : 
image

**Comment by sliptonic** [comment]
@PaddleStroke @obelisk79  
Can we get an update?  Do we have consensus on whether to move forward?

**Comment by yorikvanhavre** [comment]
I'd put the views in a "standard views" submenu maybe?

**Comment by obelisk79** [comment]
With these options available when nothing contextual is selected in the 3d view, only exception I'm aware of being sketcher. Wouldn't this be considered duplication of functionality? I don't disagree that the cube menu is a reasonable place for these options, but they seem more than accessible enough as it it. 

I would like to see better access to cube related settings from the cube menu, size, color, font settings, degrees of rotation per click on an arrow, etc. Standard views would at least be better as yorik mentions in a submenu in this case. However, I don't think this is necessary right now.

**Comment by PaddleStroke** [comment]
Yes it is somehow a duplication of functionality. However I would say that many are not aware of the right click menu, as we both didn't even knew about it before looking into this PR. So what are the odds that the majority of users know about them?

- As I said before there is still a consistency issue. Why 'Fit All' and not 'Fit selection' when they usually come together?
Either it's a duplication of functionality and we remove both (which I don't think is best) either we add at least 'Fit Selection' and maybe also "View section" & "Draw styles".

- I agree, it would be great to have cube settings in this menu. Probably make a 'cube settings' menu at the end of the menu.

**Comment by adrianinsaval** [comment]
> I'd put the views in a "standard views" submenu maybe?

+1 to this

**Comment by obelisk79** [comment]
Not against putting standard views as a submenu under the cube settings menu, but then should those entries be removed from the context menus in the 3d view? I don't think we need so many ways to display standard views. 

1. Toolbar (I never cared for these personally)
2. 3d view right click menus
3. navicube menu
4. clicking directly on the navicube
5. 'View' menu in the menubar

There's some duplication here.

**Comment by PaddleStroke** [comment]
Another idea for standard views.
image

Regarding this PR, what about just adding 'Fit Selection' for consistency. (and  "View section" & "Draw styles"?)

**Comment by pierreporte** [comment]
What is the use of the cube template?

**Comment by obelisk79** [comment]
@PaddleStroke the unwrapped cube for navigating standard views is an interesting approach. But one of the tenets of usability relates to considering target size for mouse interactions. I think that might be too small for reasonably quick targeting and interaction. I'm not necessarily opposed to this, but I do have some concerns about how useful it would be to the typical user.

As a side note, it may also be nice to add numbers correlating to the shortcut for each standard view angle with that.

**Comment by chennes** [comment]
@PaddleStroke I think just adding FitSelection for consistency is a good strategy.

**Comment by PaddleStroke** [comment]
I still think this is not ideal to not have consistency between the toolbar and different places. But for now let's just add the dit selection for minimal consistency.

(for reference here's the initial menu offer: 

```
        commands.emplace_back("Std_OrthographicCamera");
        commands.emplace_back("Std_PerspectiveCamera");
        commands.emplace_back("Separator");
        commands.emplace_back("Std_ViewFitAll");
        commands.emplace_back("Std_ViewFitSelection");
        commands.emplace_back("Separator");
        commands.emplace_back("Std_ViewIsometric");
        commands.emplace_back("Std_ViewFront");
        commands.emplace_back("Std_ViewTop");
        commands.emplace_back("Std_ViewRight");
        commands.emplace_back("Std_ViewRear");
        commands.emplace_back("Std_ViewBottom");
        commands.emplace_back("Std_ViewLeft");
        commands.emplace_back("Separator");
        commands.emplace_back("Std_DrawStyle");
        commands.emplace_back("Part_SelectFilter");
        commands.emplace_back("Separator");
        commands.emplace_back("NaviCubeDraggableCmd");
```)

**Pull request merged**
