### PR TITLE
[TD]Fix auto correct msg missing16892

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for issue #16892.

### CODE REVIEW

**Comment by luzpaz** [comment]
@WandererFan just a reminder:     
`fixes #16892`  
Is what links the PR to the issue to auto-close it. Better to add it to the body of the commit then in the summary. 

```shell
git commit -m "[TD] Fix auto corrent msg" -m "Fixes #16892"
```

**Comment by yorikvanhavre** [comment]
backported

**Comment by 3x380V** [comment]
@WandererFan, this breaks almost every dimension of drawing created before this change...
Screenshot from 2024-10-03 23-35-47

**Comment by 3x380V** [comment]
Hmm, I see. Set `<FCBool Name="AutoCorrectRefs" Value="0"/>` in `<FCParamGroup Name="Dimensions">` avoids problem. I'm leaving aside why it breaks so badly as there is a workaround. I also wonder why was commits squashed on merge.

**Pull request merged**
