### PR TITLE
[FEM and Units] Bugfix material editor for fluid material

### PR DESCRIPTION
**Pull request by qingfengxia**
The bug has been discussed in forum, yet submit to Mantis
see [more technical details in forum thread](https://forum.freecadweb.org/viewtopic.php?f=18&t=42718&p=363103#p363103)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
It might makes sense to split these PR, one for the new unit and the unit change of VolumetricThermalExpansionCoefficient and one for the change in the task panel. They are mixed in each other in the second commit. Wheras the unit changes could be merged imideatelly if ok, the change in task panel needs some testing first.

cheers bernd

**Comment by qingfengxia** [comment]
Hi Bernd,  Thank you for your quick review.

 I think you are the best person to test the second commit manually as the author. I have manually tested this GUI for solid and fluid material. From code side, this commit should be safe, it should do the same thing, but more robust if input field widget may change unit. 

Actually, I do not know how to split, so I just leave it to merge after your confirmation. 

BTW, I have responsed (provide the solution on forum) your question in forum on why Json error in general fem constraint.

Thank you.

**Comment by berndhahnebach** [comment]
Ok. Thanks. I will have a look.
cheers bernd

**Comment by berndhahnebach** [comment]
splitted and merged

**Pull request closed without merging**
