### PR TITLE
[don't merge] remove unused code

### PR DESCRIPTION
**Pull request by mosfet80**
remove unused code

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7051">pipeline status</a> for feature branch [PR_7051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7051). Pipeline [567144258](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567144258) was triggered at [7eb127a](https://github.com/FreeCAD/FreeCAD/pull/7051/commits/7eb127a3df05fdae8740e20a55ee88d1c616370b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
The CI fails. Can you please have a look?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7051">pipeline status</a> for feature branch [PR_7051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7051). Pipeline [568906826](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/568906826) was triggered at [6a08cf8](https://github.com/FreeCAD/FreeCAD/pull/7051/commits/6a08cf832b415ce3af8dcf4452fab393448b3d57). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@mosfet80 , see my comment: https://github.com/FreeCAD/FreeCAD/pull/7036#issuecomment-1166279390

Besides this, 131 changed files in one PR is overkill for reviewing. For these kind of refactoring we usual choose therefore the way of making a PR for every workbench. This way several people can review the PR and we assure nothing is accidentally lost. For example with your PR to remove OCC 6.x code there were 2 mistakes we first found after your PR was merged - because we are humans and there were too many changes at once to review everything correctly.

So please make new PRs for each Workbench, for Gui, Base and App.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7051">pipeline status</a> for feature branch [PR_7051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7051). Pipeline [578985892](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/578985892) was triggered at [5707f09](https://github.com/FreeCAD/FreeCAD/pull/7051/commits/5707f0901eea2d208d23de319112d840babf671c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7051">pipeline status</a> for feature branch [PR_7051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7051). Pipeline [579735895](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/579735895) was triggered at [6dc91ea](https://github.com/FreeCAD/FreeCAD/pull/7051/commits/6dc91ea02de138ec839431568ce98cdae643b847). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request closed without merging**
