### PR TITLE
Cleand UnitsApi.cpp

### PR DESCRIPTION
**Pull request by mosfet80**
removed unused constant definitions

### CODE REVIEW

**Comment by 3x380V** [comment]
@mosfet80, would you mind to add your hand to #15276? It is a bit frustrating to constantly rebase patchset on behalf of minor modifications... Your patch is already part of it as https://github.com/FreeCAD/FreeCAD/pull/15276/commits/e8143f302c492541348e64e3a7f63f9e7a5c098f

**Comment by 3x380V** [comment]
@maxwxyz, how should I proceed here? Should I remove patch from #15276 (where it has been for months) in favour of this PR?
@mosfet80, to be more specific, I would appreciate testing, reviewing and general feedback.

**Comment by maxwxyz** [comment]
as you like, clean up will be merged after 1.0

**Comment by wwmayer** [comment]
>  how should I proceed here?

I suggest to close this one in favour of your PR.

**Comment by Reqrefusion** [comment]
> @mosfet80, would you mind to add your hand to #15276? It is a bit frustrating to constantly rebase patchset on behalf of minor modifications... Your patch is already part of it as [e8143f3](https://github.com/FreeCAD/FreeCAD/commit/e8143f302c492541348e64e3a7f63f9e7a5c098f)

I think @mosfet80 does these PRs automatically with github personal token. So I don't think he is aware of this PR. I recommend creating a github app instead of a personal token.

@3x380V the other person probably can't or won't answer you. So I think your priority is higher.

**Comment by maxwxyz** [comment]
Closing this in favor of https://github.com/FreeCAD/FreeCAD/pull/15276

**Pull request closed without merging**
