### PR TITLE
Draft: Fix orientWP method used by in Draft_Line command

### PR DESCRIPTION
**Pull request by marioalexis84**
If the set WP button is used in the `Draft_Wire` command to reorient the work plane, closing the command does not restore the plane to the state before the button was pressed, instead it sets the plane aligned with the current view. This is because the plane is restored using the `Plane.copy` method, which ignores the attribute `weak` of the plane.
Also, after closing the command and restoring the plane, archDimTrackers stops working correctly because the instance generated by `Plane.copy` is different from the original instance used by the tracker.
Two new methods are added to the Plane class: `getParameters` to get the work plane data, and `setFromParameters` to modify the working plane without creating a new instance.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6749">pipeline status</a> for feature branch [PR_6749](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6749). Pipeline [516606040](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/516606040) was triggered at [374d948](https://github.com/FreeCAD/FreeCAD/pull/6749/commits/374d9482bda4b211235b44b0dcaf16e74d69d7e7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6749">pipeline status</a> for feature branch [PR_6749](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6749). Pipeline [516914407](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/516914407) was triggered at [9b8ec7c](https://github.com/FreeCAD/FreeCAD/pull/6749/commits/9b8ec7c01cda7741ea58fac6ba253baccc944bdb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@Roy-043 , can you please have a look? If it is OK, it could go in for FC 0.20

**Comment by Roy-043** [comment]
If I understand correctly the `getParameters` and `setFromParameters` functions are only needed for the `archDimTracker`.  The `gridTracker` does not have the same issue as it does not store the workingplane in its `__init__` function. So another solution would be to change the `archDimTracker` code accordingly. I wonder if that may be preferable?

**Comment by marioalexis84** [comment]
> wonder if that may be preferable?

Yes, in that way we get the same structure across the trackers.
In any case, I will keep the methods `getParameters` and `setFromParameters` to not create another WorkingPlane and to prevent other posible drawback

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6749">pipeline status</a> for feature branch [PR_6749](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6749). Pipeline [520860477](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/520860477) was triggered at [e62496b](https://github.com/FreeCAD/FreeCAD/pull/6749/commits/e62496b6365f777fa274b2b0e8ff4ecbc724cff7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> Seems good to me too!

Please commit. Everything that fixes an issue can go in.

**Pull request merged**
