### PR TITLE
Gui: Usability improvements added to ProDark-FreeCAD-theme

### PR DESCRIPTION
**Pull request by turn211**
forum thread: https://forum.freecadweb.org/viewtopic.php?f=34&t=55134&start=80

LineEdit, QComboBox ans ListView color enhancements for easier editing useablity. Bim View Manager Icon separation and background. HyperLinks color changed in line of https://forum.freecadweb.org/viewtopic.php?f=34&t=55844&start=10

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [passed ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
I think u need to create a new branch. No changes are being proposed.

**Comment by turn211** [comment]
I did it fast from Github Desktop. I'll do it manually,

**Comment by turn211** [comment]
I think i fixed it. If not I'll close PR and start fresh. Still learning.

**Comment by luzpaz** [comment]
@turn211 thanks!  
2 things:   
1. I see the changes now :+1:  BUT you're still using the same branch you used to commit previously. That's unorthodox. Usually one deletes the branch they used to commit previous changes once those changes have been merged. Though there may be usecases that I'm not aware of, this is the way it's done in this repo, AFAICT.
2. because you are making changes to a `.qss` stylesheet there is really no reason for the CI to compile FreeCAD from scratch to test you changes (it takes ~1.5 for the CI to compile FC) So if you could append `[skip ci]` to your commit message from here on out (unless you're introducing changes to source code in the future) that would be awesome!

I think it would make it easier on the devs if you created a new PR with said guidelines. Is that OK?

**Pull request closed without merging**
