### PR TITLE
Fix Cmake Messages

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@donovaly do you mind making sure the commit message if formatted correctly next time? TIA
Screenshot_20220630_211513

**Comment by donovaly** [comment]
> @donovaly do you mind making sure the commit message if formatted correctly next time?

No ;-) To be honest typos there don't matter and it is pain to change them -> really not worth it.

**Comment by luzpaz** [comment]
What i'm hearing you say is that typos in the git log don't matter to you? I have a different perspective but anyway just clarifying I wasn't asking to repair the typo. Instead just maybe as a merge dev practice to check the git log summary. That was my intention at least. But that may not be a priority or of importance to you.

**Comment by donovaly** [comment]
> you say is that typos in the git log don't matter to you

Yes. Why should they matter? Looking in the commit history, there are already many and nobody cared yet nor were they a problem.

Commit messages are written by the PR creator and cannot easily changed when merging.

**Comment by luzpaz** [comment]
### Why 

1. Commit messages can be utilized to build better changelogs like other FLOSS projects do (which we should probably consider adopting because the wiki release notes is a very inefficient method to track release changes. How many relevant features/bugs are omitted from the  ) 
1. Commit messages can be parsed to report commits that change the API
1. Commit messages can be parsed to run statistical analysis on the codebase
    

### How

Just because we haven't required it doesn't mean we shouldn't. PR creators **can** be oriented to write better commit summaries and messages. We can put in to effect using a github action/bot that would report this. If you want examples of how other projects do this, I can show some.

**Comment by donovaly** [comment]
> Commit messages can be utilized to build better changelogs

This does not work in practice. look at the diversity of PR committers we have. You cannot teach them all in advance on how to write a proper commit message.
Especially for release notes humans are necessary to describe a change properly to a wider audience. Experts like e.g. Werner use of course technical terms on commit messages. This has the advantage that other devs understand what was done, but non-developers - the target audience of release notes - do not know the technical terms.

In my former FLOSS project (lyx.org) we once tried this and the main developer tried really hard but gave up after some weeks.

**Pull request merged**
