### PR TITLE
[DO NOT MERGE]add multiple selection with cursor

### PR DESCRIPTION
**Pull request by JuanJ67m**
please, add multiple selection with cursor similar to AutoCAD lasso and square selection

### CODE REVIEW

**Comment by vocx-fc** [comment]
@JuanJ67m Sorry, but what are you doing? You are submitting a pull request to the `master` branch from what appears to be your own v0.18 branch (`releases/FreeCAD-0-18`). This makes no sense.

Do you have a forum post where you discuss what you want?

**Comment by luzpaz** [comment]
bump

**Comment by JuanJ67m** [comment]
@vocx-fc  I use the last dev version, for lasso or rectangle selection I mean this:

image

image


I did the same request in the forum, but 0 answers, this selecting method is very common and is the standard.

**Comment by luzpaz** [comment]
@JuanJ67m the forum is getting slammed these days from all the Fusion360 refugees. So please be patient. You can bump your thread if it doesn't get any responses the next day.

image

As vocx pointed out you made your modifications on top of old code (the `releases/FreeCAD-0-18` branch) instead of our `master` branch. We have a wiki page explaining how to submit PRs to our repo: https://wiki.freecadweb.org/Source_code_management  

You'll need to: 
1. Stash the modifications you made to the files in `releases/FreeCAD-0-18` branch
2. Pull our `master` branch to your local repo
3. make a new branch off of the master
4. cherrypick the specific commits from `releases/FreeCAD-0-18` in to your new branch. 
5. fix any code clashes
6. test your changes
7. Force push the branch to this PR or start a new PR.

**Comment by vocx-fc** [comment]
I think this is a "feature request" that was mistakenly made as a pull request. It's not a real pull request; in this case, I recommend closing it.

**Comment by luzpaz** [comment]
where are the new commits from @JuanJ67m in this PR? Can't seem to differentiate them from the older ones.

**Comment by vocx-fc** [comment]
> where are the new commits from @JuanJ67m in this PR? Can't seem to differentiate them from the older ones.

I think this pull request is a mistake. It is basically a "feature request", not a programmer's "pull request". Basically, the user doesn't know what he is doing.

**Comment by luzpaz** [comment]
Weird. In that case this PR should be closed.

**Comment by vocx-fc** [comment]
> Weird. In that case this PR should be closed.

That's what I said.

**Comment by luzpaz** [comment]
Indeed, thanks for pointing it out vocx.  
@yorikvanhavre please close PR.

**Pull request closed without merging**
