### PR TITLE
Revert "Fixups with Qt6 enums"

### PR DESCRIPTION
**Pull request by chennes**
Reverts FreeCAD/FreeCAD#13611, as discussed in #13851

### CODE REVIEW

**Comment by wwmayer** [comment]
Can you please rebase your PR? Due to the reported build failure and several warnings I merged another PR that fixed the syntax error.

**Comment by chennes** [comment]
Yes, I just saw that -- conflict should be resolved now.

**Comment by wwmayer** [comment]
Thanks!

**Comment by YakoYakoYokuYoku** [comment]
I've overlooked that `#else` with the unclosed parenthesis and the redundant `Py::Int` cast that triggered warns, a mistake from my part sorry much for that. OTOH, @3x380V you've mentioned that it was a bit screwed, I acknowledge that, though what I did was necessary one way or another. IIUC you want something like this?

```
val = wrap.toEnum<QDialogButtonBox::StandardButton>(getStandardButtonsPy());
```

**Comment by wwmayer** [comment]
Here is a fix for the problem: https://github.com/FreeCAD/FreeCAD/pull/13902

**Comment by chennes** [comment]
My read is that the reversion is no longer necessary, given the two fixup PRs -- is that correct?

**Comment by wwmayer** [comment]
Yes, that's correct.

The problem of the current version is when a Python int (e.g. `int(QtGui.QDialogButtonBox.Ok | QtGui.QDialogButtonBox.Cancel)`) is passed to `Shiboken::Enum::getValue` then it returns 1 instead of 4195328 (which is 0x00000400 + 0x00400000).
The calling instance converts the int to the [C++ enum](https://doc.qt.io/qt-6/qdialogbuttonbox.html#StandardButton-enum) `QDialogButtonBox::StandardButton` but because this is an invalid value no button will be shown.

**Pull request closed without merging**
