### PR TITLE
Reusable Draft Snap toolbar commands

### PR DESCRIPTION
**Pull request by triplus**
- Reusable Draft Snap toolbar commands
- Use default size for toolbar/toolbuttons

Forum discussion:
https://forum.freecadweb.org/viewtopic.php?f=8&t=13509&p=168552#p168552

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
@yorikvanhavre your turn :)

**Comment by yorikvanhavre** [comment]
The size things have been implemented by people using retina screen on mac. I have no way to judge if removing them still works for them, I'd prefer either to leave it like it was before, or find someone with a retina screen who can test this...

**Comment by bblacey** [comment]
I have a Retina display so I can test this however it may not be for a couple of days.

**Comment by yorikvanhavre** [comment]
No worries. Thanks @bblacey !

**Comment by triplus** [comment]
Thanks @bblacey.

**Comment by bblacey** [comment]
Guys, sorry I haven't tested this yet but the Qt 4 formula maintainer renamed the formula today that borked a number of things with our builds.  I have been working with the maintainer to fix the issues.  Once the Qt 4 builds are back online, I will try to test this - again, apologies for the delay.

**Comment by triplus** [comment]
Take your time. When you get to it could you provide screenshot of both toolbars mentioned here:

https://forum.freecadweb.org/viewtopic.php?f=10&t=18932&start=20#p147796

As after Draft Snap toolbar work will be finished i will work on the second one. And i am interested in how it looks like ATM on high resolution display.

**Comment by bblacey** [comment]
Sure - will do.  I Resolved the Qt 4 issues with the Qt 4 maintainer late last night so builds are fixed.  Need to switch my development environment back to Qt 5 in order to test.  I will try to run the tests within the next couple days.

**Comment by bblacey** [comment]
I just completed testing this PR on a Retina display and the scaling seems fine.  Per request, here is a screenshot of the draft menu-bar that includes the two menus of interest.  Let me know if you would like any additional tests/screenshots.

screen shot 2017-04-07 at 10 04 13 pm

Version details:

```
OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.10675 (Git)
Build type: DEBUG
Branch: pr-671
Hash: 26a8729aa81c0c7a46e5772e564871b62b4a4278
Python version: 2.7.13
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.1.0
```

**Comment by wwmayer** [comment]
Thanks for testing! So, does it mean that without this PR the draft menu bar is broken in a certain way? Could you please add a screen shot of this broken menu too -- just to get an impression of how it looks like?

**Comment by triplus** [comment]
Thanks @bblacey for providing the screenshot. To me Draft Snap toolbar looks OK. I expected that as i have only reset the button/toolbar size to default values. The toolbar next to it (on the left) doesn't use standard size ATM and as i expected it doesn't look good. This will be fixed in future pull request related to that toolbar.

@wwmayer 

The main point of this PR is user can reuse commands from Draft Snap toolbar in for example PieMenu. And not just the wrapper FreeCAD Draft Snap commands found in the Draft menu that don't have toggle capability.

Resting the Draft Toolbar size to defaults is just an extra and unrelated feature.

**Comment by wwmayer** [comment]
OK, so then it can be merged or is there still something not clear?

**Comment by triplus** [comment]
As far as i am concerned proposed changes work for me. I can reuse Draft Snap toolbar commands in for example PieMenu. And at the same time i didn't introduce any changes that would make life harder for Yorik as the logic is still the same. It comes down to using QAction instead of QToolButton and everything else works in the same way as it did in the past.

 P.S. As for the planned work on the second toolbar. That will be done as a part of separate pull request anyway.

**Comment by yorikvanhavre** [comment]
Okay then I'm merging.

**Pull request closed without merging**
