### PR TITLE
TechDraw: create closure for concurrent thread context

### PR DESCRIPTION
**Pull request by andre-caldas**
We use a lambda function with a copy of variables that  might be destructed in the original calling thread, possibly producing dangling references.

See:
https://forum.freecad.org/viewtopic.php?t=81260

All tests have passed.

### CODE REVIEW

**Comment by luzpaz** [comment]
```bash
git commit --amend -m "TechDraw: create closure for concurrent thread context" -m "We use a lambda function with a copy of variables that might be destructed in the original calling thread, possibly producing dangling references." -m "See: https://forum.freecad.org/viewtopic.php?t=81260" -m "All tests have passed."
git push --force
```

**Comment by andre-caldas** [comment]
> ```shell
> git commit --amend -m "TechDraw: create closure for concurrent thread context" -m "We use a lambda function with a copy of variables that might be destructed in the original calling thread, possibly producing dangling references." -m "See: https://forum.freecad.org/viewtopic.php?t=81260" -m "All tests have passed."
> git push --force
> ```

Thank you... and sorry! :-)
I tried to fix the comment but I could not figure how to do it.

**Review by WandererFan — COMMENTED** [review]
LGTM, but I barely understand what is going on.  We should have somebody competent like Werner look at it.

**Review by wwmayer — COMMENTED** [review]
I don't see that technically this makes a big difference. It just  makes it more explicit that the capture of the lambda copies the passed shape.

But the good thing about this PR is that it eliminates the differences between Qt5 & Qt6

**Pull request merged**
