### PR TITLE
[consider for v0.18] Geom python fixes 

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
During v0.18 we changed the inheritance hierarchy of Geometry in c++, but we did not adapt the Python classes correspondingly. The first commit does this.

The second commit provides python functionality to re-trim a trimmed curve.

The third commit exposes the clone functionality to Python, so that power users may produce copies with the same tagid.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
Thread:
https://forum.freecadweb.org/viewtopic.php?f=22&t=32814&p=282624#p282624

**Comment by abdullahtahiriyo** [comment]
Inheritance correspondence:

Geometry
- GeomPoint
- GeomCurve (GeometryCurvePy)
- - GeomBoundedCurve (BoundedCurvePy)
- - - GeomBezierCurve (BezierCurvePy)
- - - GeomBSplineCurve (BSplineCurvePy)
- - - GeomTrimmedCurve (ArcPy)
- - - - GeomArcOfConic (ArcOfConicPy)
- - - - - GeomArcOfCircle (ArcOfCirclePy)
- - - - - GeomArcOfEllipse (ArcOfEllipsePy)
- - - - - GeomArcOfHyperbola (ArcOfHyperbolaPy)
- - - - - GeomArcOfParabola (ArcOfParabolaPy)
- - - - GeomLineSegment (LineSegmentPy)
- - GeomConic
- - - GeomCircle
- - - GeomEllipse
- - - GeomHyperbola
- - - GeomParabola
- - GeomLine
- - GeomOffsetCurve

**Comment by wwmayer** [comment]
Note, the class ArcPy is kept for backward compatibility and the class is supposed to handle arcs of circles, ellipses, parabolas and hyperbolas in one class.
Later we made an explicit arc class for each conic section because some of them has specific attributes which we cannot handle in a general ArcPy class.
So, it should be avoided to make ArcOf...Py a sub-class of ArcPy.
This means that you either have to add the method setParameterRange to each ArcOf...Py and the ArcPy class or to avoid the code duplication add the class GeometyTrimmedCurvePy and derive all Arc classes from that class.

Also a LineSegmentPy is a straight curve so from a mathematical point of view it doesn't make sense to derive it from ArcPy.

**Comment by abdullahtahiriyo** [comment]
Ok. I have created TrimmedCurvePy in my local branch. 

Do you want the remaining ArcPy to derive from BoundedCurvePy or from GeometryCurvePy?

**Comment by wwmayer** [comment]
The ArcPy class should then be derived from TrimmedCurvePy, too.

**Comment by abdullahtahiriyo** [comment]
ok

**Comment by abdullahtahiriyo** [comment]
Done!

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
