### PR TITLE
Reword rigid/flexible sub-assemblies tooltip.

### LINKED ISSUE #17636: Assembly: Flexible/rigid subassemblies: tooltip is misleading
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After merging https://github.com/FreeCAD/FreeCAD/pull/15629 subassemblies can be added as rigid or flexible. The tooltip when adding a component states:

> If checked, the inserted sub-assemblies will not be flexible.
> Rigid means that the sub-assembly will be considered as a solid.
> Flexible means that the sub-assembly joints will be taken into account in the main assembly.
> **You can change this property of sub-assemblies at any time by right clicking them.**

image

Unlike stated on the tooltip, right-clicking sub-assembiles does not give the ability to change their rigidness. Or at least I've not found a way to do it.

Instead, the **Rigid** property can be changed on the Property Editor

image

I believe the tooltip should read

```diff
- You can change this property of sub-assemblies at any time by right clicking them.
+ You can change this behavior at time by editing the Rigid property of a given sub-assembly in the Property Editor.
```

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39100 (Git) Snap 1179
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * ezydxf
  * Ondsel-Lens 2024.9.13.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Assembly

### Anything else?

> Flexible means that the sub-assembly joints will be taken into account in the main assembly.

This description of flexible sub-assemblies is in my opinion not easy to understand. What does exactly "will be taken into account" mean?

An alternative description, adapted from https://help.solidworks.com/2021/english/SolidWorks/sldworks/c_flexible_sub-assemblies.htm might be clearer:

> Flexible sub-assemblies allow movement of their individual components within the parent assembly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by furgo16**
Fixes #17636

### CODE REVIEW

**Comment by furgo16** [comment]
Given that it fixes a bug, and it's a self-contained, trivial fix, can it not be targeted for 1.0?

**Comment by PaddleStroke** [comment]
Right clicks works, it's right click on the tree item. Did you try to right click on the 3dview object?

**Comment by maxwxyz** [comment]
@furgo16 will you add right click again?

**Comment by furgo16** [comment]
> Right clicks works, it's right click on the tree item. Did you try to right click on the 3dview object?

Sorry, I had not seen this the first time. Most probably a user error. After re-adding the note about the right-click, I still think think this PR adds some value by adding more context and mentioning the property in the Property Editor.

@maxwxyz re-added note about right click, thanks for the review and the heads up!

**Pull request merged**
