### PR TITLE
Select code page during STEP Import 

### PR DESCRIPTION
**Pull request by Kuzma30**
Added the ability to select the encoding of the source file when importing.
Requires OCCT version 7.8.0 and higher

Fix https://github.com/FreeCAD/FreeCAD/issues/7987

### CODE REVIEW

**Comment by Kuzma30** [comment]
Please review code in this state

**Comment by Syres916** [comment]
Educated guess but the test failure on _CI/Ubuntu_20-04_ is because there's no condition around _Resource_FormatType_ in ImportExportSettings
If I get time later today/tomorrow I'll compile a build based on OCC 7.8.0 and with the above changes give it a test.

**Comment by Syres916** [comment]
Please see https://github.com/FreeCAD/FreeCAD/compare/main...Syres916:FreeCAD:Fix_Step_Import_780 you'll need to double check the ISO850 line, not sure whether you had a typo in there originally. Apologies there's some formatting changes so it looks like I did more work that I actually achieved. This will at least get the tests to complete successfully but it's become a bit messy as a result so whether the maintainers are going to be happy with this is debatable.

**Comment by Kuzma30** [comment]
Is OCC_VERSION_HEX >= 0x070603 support  ReadFile(filename, parameters) format? I found this function only in 7.8.0

**Comment by Syres916** [comment]
I've only been using the error feedback on compiling to add the conditions. If you want to lock everything down to 7.8.0 or above then that's absolutely fine.

**Comment by Kuzma30** [comment]
I make some modifications, can you review @Syres916 ?

**Comment by Syres916** [comment]
I've started another piece of work and to save a lot of back and forth if you look in the Checks/Tests https://github.com/FreeCAD/FreeCAD/pull/14416/checks you'll see that _Ubuntu_20-04_ has failed again. You just expand the _CMake Build_ log and go down the output and at the end it'll tell you the reason for the failure and in this instance line 160 of _src/Mod/Import/App/AppImportPy.cpp_ needs a condition to stop the build failure.

**Comment by Syres916** [comment]
I'll have another look at this in 3 hours or so, I think there's a crash going into Edit>Preferences with any OCC version under 7.8.0 due to the combobox being empty. It shouldn't be too difficult to solve even if it means it's hidden and disabled by default and enabled/shown when using 7.8.0 or greater.

**Comment by Kuzma30** [comment]
I test this on OCCT 7.8.1 and 7.6.3/ no crash.

**Comment by Syres916** [comment]
After recompiling all three builds of OCC 7.3, 7.6.3 and 7.8.0 no crashes were found, all good with the test Step files I had to hand.

**Comment by Kuzma30** [comment]
@chennes, can you review and commit this?

**Comment by chennes** [comment]
@bgbsww can you give this a compilation test on OCT 7.8? None of the CI runs use it yet.

**Comment by bgbsww** [comment]
Sure can ...  compile passes just fine.

**Pull request merged**
