### PR TITLE
Gui: Add runtime check to choose between modern and legacy space mous…

### PR DESCRIPTION
**Pull request by wwmayer**
…e devices

https://forum.freecad.org/viewtopic.php?t=90561

### CODE REVIEW

**Comment by maxwxyz** [comment]
Related to https://github.com/FreeCAD/FreeCAD/pull/17000

**Comment by chennes** [comment]
I expected this to also require a cMake change, to also ensure that `FREECAD_USE_3DCONNEXION` doesn't get set to false when `FREECAD_USE_3DCONNEXION_NAVLIB` is true. I don't have an older device to test that out on, though.

**Comment by wwmayer** [comment]
See 2nd commit.

**Comment by hyarion** [comment]
Is this something we should backport to 1.0.1?

**Comment by maxwxyz** [comment]
I'll label it for discussion so it won't get lost

**Comment by wwmayer** [comment]
Before continuing on it is there any Windows or macOS user out there with an old space mouse who can confirm that in legacy mode the device is supported again?

**Comment by cculpepper** [comment]
I can test this, Just need to find a build with raw_input enabled it looks like?

**Comment by hyarion** [comment]
@wwmayer I can ask a friend to test it on macOS with both new and old device. Can it be tested in the latest weekly?

**Comment by wwmayer** [comment]
Sure.

**Comment by adrianinsaval** [comment]
backported 0ce373c07282380eb1eb1b0d45521ef376fcea07 fa88a6e74e86191315065e1ee790920ea0c2bf32

**Pull request merged**
