### PR TITLE
Path.Area: various bug fix and improvements

### PR DESCRIPTION
**Pull request by realthunder**
New features:
- Arc plane selection

Improvements:
- wire sorting speed up using RTree
- solid section tolerance and transformation
- reduced FeatureArea recompute

Fixes:
- Correct handling of object with placement
- wire sort ordering
- and more ...

### CODE REVIEW

**Comment by realthunder** [comment]
The windows compilation failure is most likely caused by [this boost bug](https://svn.boost.org/trac/boost/ticket/9332). The link contains a patch to fix that. Also boost 1.56.0 onwards should have fixed this problem. So how are we going to solve this?

**Comment by wwmayer** [comment]
What about using the old behaviour (i.e. using #ifdef's) for broken boost versions and using the new behaviour for fixed boost versions?

**Comment by realthunder** [comment]
The problem is inside a boost header file, and only happens for Windows. So, update the libpack somehow?

**Comment by realthunder** [comment]
Let me try replace that header file and see if it fix first

**Comment by wwmayer** [comment]
> The problem is inside a boost header file, and only happens for Windows. So, update the libpack somehow?

This would be hard to achieve and would be a lot of work for a rather small issue.

> Let me try replace that header file and see if it fix first

You can try what jobermayr tried with failures of boost in other cases: write a corrected header file and include this in the source code. For more details have a look at the file boost_any_1_55.hpp in the src directory.

**Comment by realthunder** [comment]
Unfortunately, this is one of those magic header. It doesn't prevent repeated inclusion. In fact, it needs to be repeatedly included for code generation. Here are options I can think of,
- Only one boost head needs to be replaced in libpack. I have verified that it can compile once replaced.
- I can write a simple script to patch the file during cmake stage. If you prefer this way, where shall I put the patch, in root cmake (when finding boost in libpack), or in Path/App?

**Comment by wwmayer** [comment]
> It doesn't prevent repeated inclusion. In fact, it needs to be repeatedly included for code generation. Here are options I can think of,

Am I right that it suffices to just replace the header file and you don't have to rebuild any boost libs? If yes, is there a way to easily determine if the header is patched or not? In case cmake can raise a warning or error to notify the user to update the header manually.

I don't like to automatically update the header and it anyway isn't guaranteed that it works because the directory might be write-protected.

Then the AppVeyor maintainer should be contacted to replace the header.

**Comment by sasobadovinac** [comment]
This is in the https://github.com/FreeCAD/FreeCAD-ports-cache/releases/download/v0.17/FreeCADLibs_11.5.1_x86_VC12.7z right? If the file can be just changed then it should not be a big problem, however if the libs have to be recompiled then it can be a bit more problematic :) @sgrogan made the current win libs.

Will this change be backward compatible, so we could just update the current libs or would it be better to also keep the current version of the libs?

**Comment by realthunder** [comment]
It's header only. No need recompilation. 

Anyway, I dug a bit deeper. It seems the magic header is only included inside two non-magic overridable header. I am trying to see if I can override them.

**Comment by wwmayer** [comment]
Merged.

**Comment by sgrogan** [comment]
I'm glad to see the problem is solved, but I am perplexed because Travis uses boost version is 1.55. On Win we use the same version. I'll look if the Ubuntu boost has already been patched.

**Comment by realthunder** [comment]
@sgrogan the problem only happens when using MSVC compiler. And boost is fixed for that specific problem in 1.56, http://www.boost.org/users/history/version_1_56_0.html, intrusive, issue 9332

**Pull request closed without merging**
