### PR TITLE
[fixes #5965] CarbonCopy: if existing use constraint name in expressions

### LINKED ISSUE #5965: CarbonCopy should use names of constraints if available.
Issue imported from https://tracker.freecad.org/view.php?id=4053

* **Reporter:** chrisb
* **Date submitted:** 7/12/2019
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

Instead of referencing dimensions by their constraint number, CarbonCopy should use the names where the user provided them.
[See forum discussion](https://forum.freecadweb.org/viewtopic.php?f=8&t=37638)

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

### PR DESCRIPTION
**Pull request by adrianinsaval**
The solution is working but I have doubts, I had to construct the expression in different ways for named an unnamed constraints, for some reason `spath.toString()` returns the path with a leading `.` for the named case and without the leading `.` for index based path, would appreciate some clarification as to why this happens and if I dealt with this correctly.

here a file to test the feature (just remove zip extension)
[carbonCopyTest.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/9925569/carbonCopyTest.FCStd.zip)

when you create a new sketch and make a carbon copy of this the constraint that has a valid name will be linked using the name in the expression, and those that have invalid names or no name will be linked using the index based expression.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7688">pipeline status</a> for feature branch [PR_7688](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7688). Pipeline [684203118](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/684203118) was triggered at [730b413](https://github.com/FreeCAD/FreeCAD/pull/7688/commits/730b41358e915c121d88402f4c1677fe22cf18b8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7688">pipeline status</a> for feature branch [PR_7688](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7688). Pipeline [689868556](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/689868556) was triggered at [c9d9171](https://github.com/FreeCAD/FreeCAD/pull/7688/commits/c9d91710daf3441e5aa28ef8e04b9ea01cf8461c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7688">pipeline status</a> for feature branch [PR_7688](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7688). Pipeline [705575401](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/705575401) was triggered at [4e085da](https://github.com/FreeCAD/FreeCAD/pull/7688/commits/4e085dacd3c66c7b596427a2d680d55d0429c6e2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
realthunder has confirmed that the different output is expected behavior so I think my solution is correct

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7688">pipeline status</a> for feature branch [PR_7688](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7688). Pipeline [711229833](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/711229833) was triggered at [8d43391](https://github.com/FreeCAD/FreeCAD/pull/7688/commits/8d43391eb622f7a6bfafc22cbb72b86225cab47a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
OK, I tested and the PR is OK.
It slightly changes the behavior seen in a carbon copy when the base sketch uses both named and unnamed constraints and one is removed.
But behavior in this case is "faulty" in both cases, so not a regression.

@donovaly I know you plan to backport this to stable branch, but IMO it shall not be qualified as a bug fix, but as a feature improvement.

**Comment by donovaly** [comment]
> @donovaly I know you plan to backport this to stable branch, but IMO it shall not be qualified as a bug fix, but as a feature improvement.

OK, thanks.

@adrianinsaval , please don't forget to update our release notes and the corresponding Wiki page(s).

**Comment by adrianinsaval** [comment]
Already updated the release notes, the wiki page for carbon copy just mentions that the constraints are linked by expression so it didn't need update

**Pull request merged**
