### PR TITLE
[PartDesign] Translation fixes for reported issues in FreeCAD-translations

### PR DESCRIPTION
**Pull request by luzpaz**
Attempt to fix pending bugs reported in several ticket on https://github.com/FreeCAD/FreeCAD-translations/issues

### CODE REVIEW

**Review by yorikvanhavre — APPROVED** [review]
Cool... What is the reason for the // lines?

**Comment by luzpaz** [comment]
@yorikvanhavre I was following @berndhahnebach lead in the Fem `Workbench.cpp` specifically:    
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Fem/Gui/Workbench.cpp#L37-L73

He parses out the list by how they are situated in the dropdown GUI. This is useful to make the formatting of Workbench.cpp a little more intuitive, IMHO.

**Comment by luzpaz** [comment]
@yorikvanhavre if you don't mind, please make a crowdin push/pull after merging this. Thanks!

**Comment by luzpaz** [comment]
7c5f8d8737cd5e0bafac83241ed137976672713f
69b084f492863c2fb4c3c554130bd8b65693398a  
:facepalm:

**Pull request merged**
