### PR TITLE
[PartDesign] setting Datum Line size manually

### PR DESCRIPTION
**Pull request by Zolko-123**
See forum:

https://forum.freecadweb.org/viewtopic.php?f=8&t=41710&p=387360#p387360

### CODE REVIEW

**Comment by Zolko-123** [comment]
all modifications are ported from DatumPlane, identically.

**Comment by yorikvanhavre** [comment]
Looks good! Will wait for the travis build to finish and merge.

**Comment by Zolko-123** [comment]
There was a confusion with a test I made (a PR for Draft_Array) and that screwed up a previous test-build. Now it has passed and should be all right

**Comment by vocx-fc** [comment]
This introduces changes to both Draft and PartDesign. I think it'd be better if you break the behavior in two distinct pull requests, because ultimately they are independent of each other.

Also, for Draft Arrays I thought we wanted to call the property something else, not just `Edge`.

**Comment by Zolko-123** [comment]
> This introduces changes to both Draft and PartDesign

what do you mean ? It's only about PartDesign::Line datum axis.

**Comment by vocx-fc** [comment]
There are 5 files changed by this pull request: Draft.py, DatumLine.cpp, DatumLine.h, ViewProviderDatumLine.cpp, and ViewProviderDatumLine.h.

There are 12 commits, one which makes changes to Draft.py, 9ebb10f.

If you don't want that, then you need to discard that commit.

In general, you shouldn't try to merge your master branch with FreeCAD's master branch. You should create a branch with only your changes, and try to merge that branch only. Maybe this is the issue we are seeing; maybe while you were testing you got another commit into your master branch, and now you are merging it with this pull request.

**Comment by Zolko-123** [comment]
> If you don't want that, then you need to discard that commit.

is there a way to do that from within GitHub ? Alternativeley, since my local repo is not usable right now, could you propose the changes made to the other 4 files from your branch ?

**Comment by vocx-fc** [comment]
See this branch https://github.com/vocx-fc/FreeCAD/tree/Zolko_DatumLine, it contains only one commit, which corresponds to the DatumLine modifications.

To fix your issues with the master branch, you need to do something like this
```
git checkout master
git reset --hard 9e57caf2e
git pull upstream master
```

Then you could create a new branch and cherry pick my commit, which is actually yours.
```
git checkout -b DatumLine
git cherry-pick cd994364
```

**Comment by Zolko-123** [comment]
closed. This PR has been replaced by PR #3377

**Pull request closed without merging**
