### PR TITLE
[Gui] Ensure FreeCAD Classic theme is properly reset...

### PR DESCRIPTION
**Pull request by Syres916**
...to defaults when switching from another theme. Also ensure that when a user has selected a theme in the First Start Widget but doesn't click _Done_ the theme name is set so when Preferences > General is opened the Theme displayed in the combobox is the correct one.

Fixes https://github.com/FreeCAD/FreeCAD/issues/15667

Also corrects report from the forum https://forum.freecad.org/viewtopic.php?t=89456&sid=8ffb0b92bce76390b566ec735afe17ce

FYI @MisterMakerNL

### CODE REVIEW

**Comment by MisterMakerNL** [comment]
Wow this is pretty hefty PR, it was kinda more easy to having too set the colors in the cfg format, than running true code.
Is there any chance we can do the reverse, removing the colors from code and just use the cfg?

**Comment by Syres916** [comment]
If what you suggest was implemented what happens to a new user who just clicks File > Open or File > New ? I'm guessing here but the core developers would want a serious sit-down before anyone considered that kind of recode, it's a serious change of methodology IMHO.

**Comment by MisterMakerNL** [comment]
> If what you suggest was implemented what happens to a new user who just clicks File > Open or File > New ? I'm guessing here but the core developers would want a serious sit-down before anyone considered that kind of recode, it's a serious change of methodology IMHO.
Load the cfg file as a setup file when the program start, then apply the theme. But this is a feature and as you said it sounds like a lot of work, so maybe something for in the future.

**Comment by chennes** [comment]
IMO this is the right approach for now -- I'll leave it open for a bit before merging in case someone wants to make an alternative proposal.

**Comment by furgo16** [comment]
Thank you for this PR. It will remove a lot of confusion when switching themes back to Classic, and hopefully also result in less bug reports.

**Comment by adrianinsaval** [comment]
the classic theme was intended to store what where freecad's defaults at the time, the idea being that we could then change the defaults in the code and whoever wanted to stay with the classic look could just apply the preference pack. If the preference pack just removes preferences then this won't be the case anymore and whenever we change any default the "classic" look will be lost.

**Comment by FEA-eng** [comment]
I don't know what the right way to solve this is but the issue with themes not being completely reset when going back to Classic is really nasty and IMO should be fixed for 1.0. Themes shouldn't leave any leftovers making it necessary to reset your config. Currently, I still see some elements of themes other than Classic (like the tree highlight color) when going back to it.

**Comment by adrianinsaval** [comment]
I think for now we just need to set proper working values in classic.cfg

another option would be to remove "Classic" from the startpage or rather rename it to something like "None" instead that does what Syres is proposing. The classic theme can be left to rot as an addon theme that will have to be downloaded and set manually by those that really want to stick with the old look. Something like this would likely need more discussion though

**Comment by maxwxyz** [comment]
Is it possible that this PR broke the ability to switch to the classic theme in the preferences at all in the latest weekly? #15890

**Comment by FEA-eng** [comment]
> Is it possible that this PR broke the ability to switch to the classic theme in the preferences at all in the latest weekly? #15890

Yes, I’ve also noticed that but I thought that it was because I still have 0.21.2 on the same computer.

**Comment by GeneGH** [comment]
> another option would be to remove "Classic" from the startpage or rather rename it to something like "None" instead that does what Syres is proposing. The classic theme can be left to rot as an addon theme that will have to be downloaded and set manually by those that really want to stick with the old look. 

This is a really, really nasty thing to do. Themes are not standalone, but they interact strongly with settings the user has chosen for his or her computer(s). Just "rotting" a long-standing display appearance most likely means the wonderful "modern" appearance will look like crap until the computer settings are updated.

**Comment by MisterMakerNL** [comment]
First start setup also doesn't work good (wrong color in buttons) anymore. I think because it is missing settings.Since as soon as you applied a theme and reboot it all works fine.
If so I rather see this pr reverted as it doesn't add a lot and breaks more.

**Comment by maxwxyz** [comment]
@Syres916 this PR does not reset stylesheet for classic / does not set it to No stylesheet

**Pull request merged**
