### PR TITLE
Sketcher: fix CircleToCircle distance constraint with external

### PR DESCRIPTION
**Pull request by FlachyJoe**
Create c2c distance constraint with one external geometry raised a malformed constraint error
https://forum.freecad.org/viewtopic.php?p=688538#p688538

The precommit hook also clang-formats some lines…

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by FEA-eng** [comment]
@luzpaz Can this be marked to be merged for 0.21?

**Comment by luzpaz** [comment]
@abdullahtahiriyo if you're available, do you mind reviewing?

**Comment by FlachyJoe** [comment]
@luzpaz I think @0penBrain is competent to review and maybe more available than adbullah.

The fix resides in 2 lines already used in the point to point distance constraint just above. And checkGeoId() comment says `convert negative external-geometry index to index into Geoms`.

**Comment by FlachyJoe** [comment]
Thank you @0penBrain

**Pull request merged**
