### PR TITLE
fix wrong size svg export page

### PR DESCRIPTION
**Pull request by WandererFan**
Pls merge.  
Thanks,
wf

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by WandererFan** [comment]
Travis build fails in FreeCAD/src/Gui/ActionFunction.cpp.
===================================================================
[ 41%] Building CXX object src/Mod/Part/App/CMakeFiles/Part.dir/SurfaceOfRevolutionPyImp.cpp.o
/home/travis/build/FreeCAD/FreeCAD/src/Gui/ActionFunction.cpp:124:5: error: ‘QPointer’ does not name a type
     QPointer<QObject> argQObject;
     ^
/home/travis/build/FreeCAD/FreeCAD/src/Gui/ActionFunction.cpp: In member function ‘void Gui::TimerFunction::setFunction(boost::function<void(QObject*)>, QObject*)’:
/home/travis/build/FreeCAD/FreeCAD/src/Gui/ActionFunction.cpp:148:8: error: ‘class Gui::TimerFunctionPrivate’ has no member named ‘argQObject’
     d->argQObject = args;
        ^
/home/travis/build/FreeCAD/FreeCAD/src/Gui/ActionFunction.cpp: In member function ‘void Gui::TimerFunction::timeout()’:
/home/travis/build/FreeCAD/FreeCAD/src/Gui/ActionFunction.cpp:163:34: error: ‘class Gui::TimerFunctionPrivate’ has no member named ‘argQObject’
         d->timeoutFuncQObject(d->argQObject);
                                  ^
[ 42%] make[2]: *** [src/Gui/CMakeFiles/FreeCADGui.dir/ActionFunction.cpp.o] Error 1
make[1]: *** [src/Gui/CMakeFiles/FreeCADGui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by yorikvanhavre** [comment]
The compile problem comes from 4784751 - It has just been fixed now... I'll try to trigger a new travis build

**Comment by wwmayer** [comment]
Merged.

**Comment by dlhenke** [comment]
Now tool management is broken .. not working. 
there is no way to import or even create new tool on Job.

**Comment by yorikvanhavre** [comment]
I don't think that is related to this PR...

**Comment by dlhenke** [comment]
Path workbench activated
Running the Python command 'Path_ToolLibraryEdit' failed:
Traceback (most recent call last):
  File "/Users/duhenke/FreeCAD/build/Mod/Path/PathScripts/PathToolLibraryManager.py", line 620, in Activated
    self.edit()
  File "/Users/duhenke/FreeCAD/build/Mod/Path/PathScripts/PathToolLibraryManager.py", line 602, in edit
    editor = EditorPanel()
  File "/Users/duhenke/FreeCAD/build/Mod/Path/PathScripts/PathToolLibraryManager.py", line 363, in __init__
    self.loadTable()
  File "/Users/duhenke/FreeCAD/build/Mod/Path/PathScripts/PathToolLibraryManager.py", line 431, in loadTable
    tooldata = self.TLM.getTools("<Main>")
  File "/Users/duhenke/FreeCAD/build/Mod/Path/PathScripts/PathToolLibraryManager.py", line 228, in getTools
    itemDiameter =  QtGui.QStandardItem(unitconv(t.Diameter))
  File "/Users/duhenke/FreeCAD/build/Mod/Path/PathScripts/PathToolLibraryManager.py", line 203, in unitconv
    digits = parms.GetContents()[1][2] #get user's number of digits of precision



OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.10670 (Git)
Build type: Release
Branch: master
Hash: c80f6f0941c4a64814b4b7ea85c5299cd28a09b4
Python version: 2.7.13
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.1.0


It was working before..

**Comment by dlhenke** [comment]
To solve i need to go to Preferences->General->units change number of decimals to 3
open the PathTool Library and the tools are there
close it and again change numbers of decimals to 2
and the PathTool Library brings all of my tools. 
Working now.

**Pull request closed without merging**
