### PR TITLE
Materials: Correct installation paths

### PR DESCRIPTION
**Pull request by davesrocketshop**
Correct the installation paths affecting builds on various systems while still maintaining the old material editor required for backwards compatibility

### CODE REVIEW

**Comment by wwmayer** [comment]
This causes a new regression after installing (with `make install DESTDIR=/tmp`) the binaries:
`Cannot find icon: /tmp/usr/share/Mod/Material/Resources/icons/MaterialWorkbench.svg`

**Comment by adrianinsaval** [comment]
how can one test the functionality affected by this?

**Comment by chennes** [comment]
Closes #15571

**Comment by pinkavaj** [comment]
> how can one test the functionality affected by this?

https://github.com/FreeCAD/FreeCAD/pull/16105#pullrequestreview-2266417264

**Comment by chennes** [comment]
#16105 included a change to [src/Mod/Material/MaterialEditor.py](https://github.com/FreeCAD/FreeCAD/pull/16105/files/78523bf2290b062268b12bde812c3aa95b279b56#diff-7144881a64cfda52a7d1f7c6aa85529bf2e81902afa925cd5ce1e89e756cfd8a), switching the UI loader to use the compiled-in resource. That change is not included here -- should it be?

**Comment by chennes** [comment]
Cherry-picked to 1.0

**Comment by FEA-eng** [comment]
It seems that with this PR, the "Use FreeCAD material editor" option in FEM brings the old editor. Previously (before it stopped working in recent builds), it was the new one. Why did it change?

**Comment by davesrocketshop** [comment]
> It seems that with this PR, the "Use FreeCAD material editor" option in FEM brings the old editor. Previously (before it stopped working in recent builds), it was the new one. Why did it change?
> 
> ```
> OS: Windows 10 build 19045
> Word size of FreeCAD: 64-bit
> Version: 1.1.0dev.38830 (Git)
> Build type: Release
> Branch: main
> Hash: b38c42262f58cf0587b627e7a866d3756da34dc4
> Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
> Locale: Polish/Poland (pl_PL)
> Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
> ```

The short answer is I have no idea.

Nothing in this PR would have changed that. In fact, I don't understand why the new editor would have ever been called.

If you look at the code in `src/Mod/Fem/femtaskpanels/task_material_common.py`, in the function `edit_material` (line 319), you'll see that the editor is called with the function `MaterialEditor.editMaterial`. This function has only ever used the old editor, and would require modifications to use the new editor.

I've gone back in the commit history for both files and have not seen any modifications that would have changed this.

**Comment by FEA-eng** [comment]
> This function has only ever used the old editor, and would require modifications to use the new editor.

Do you know if it's hard to modify to call the new editor this way? Would you be able to do it or will we need to have a look at it with Mario (I'll create a new issue then)?

**Comment by davesrocketshop** [comment]
> > This function has only ever used the old editor, and would require modifications to use the new editor.
> 
> Do you know if it's hard to modify to call the new editor this way? Would you be able to do it or will we need to have a look at it with Mario (I'll create a new issue then)?

It's not that hard... I'm almost done. Maybe another day or two with testing. But you really need to change how you're using the editor and use material objects instead of the dictionary (post 1.0).

**Comment by FEA-eng** [comment]
> It's not that hard... I'm almost done. Maybe another day or two with testing. But you really need to change how you're using the editor and use material objects instead of the dictionary (post 1.0).

So you'll make a PR? Thanks a lot. Mario planned some changes to adapt FEM to the new materials system but indeed it's a goal for the next release cycle.

**Pull request merged**
