### PR TITLE
[Start] set sensible size for DlgStartPreferences.ui

### PR DESCRIPTION
**Pull request by donovaly**
- as mentioned in #8330, new size set by QtDesigner

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8353">pipeline status</a> for feature branch [PR_8353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8353). Pipeline [767663895](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/767663895) was triggered at [2ace2cb](https://github.com/FreeCAD/FreeCAD/pull/8353/commits/2ace2cb49510fab0929bd86af785029da003144c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@donovaly should we look at adding some more things to prevent merging of CI failing PR? Or did you voluntarily ignored it?

**Comment by donovaly** [comment]
> @donovaly should we look at adding some more things to prevent merging of CI failing PR? Or did you voluntarily ignored it?

The latter because:
- the GitLab CI succeeds
- there is a known issue that a Draft objects cannot be accessed by the other CI. @Roy-043 is informed and there is a forum thread about this. The strange thing is that this error occurs not on every CI run
- I checked the CI error and saw exactly that Draft issue
- for now I have to rely on our GitLab CI

The point with @yorikvanhavre 's PR was that there was an issue with a CSS file. This was hidden since the Draft issue occurred too. I have no clue why this is important since there are no compiler or user-visble issues and the GitLab CI has no problem. But the issue was already fixed anyway.

However, before I merge, I grab the code, compile, test the feature, look at the changed code. Then I rely on the GitLab CI. That's how I work at the moment.

**Comment by donovaly** [comment]
>     * there is a known issue that a Draft objects cannot be accessed by the other CI. @Roy-043 is informed and there is a forum thread about this. The strange thing is that this error occurs not on every CI run

Here an example:
#8355

So the GitLab CI succeeds, also the second CI but the third one not. Forcing a rebase triggers a new run and then maybe all succeed, or the second fails while the first one does not. I has all cases the last 24 hours and I am really tired. In this state the first two CIs are not helpful.

**Comment by donovaly** [comment]
I started now a new forum thread about this: https://forum.freecad.org/viewtopic.php?t=75831

**Comment by 0penBrain** [comment]
CI failed every time with the W3C validation error.

**Comment by donovaly** [comment]
> CI failed every time with the W3C validation error.

Yes. my fault,  I only saw the "usual" Draft error and therefore did not look further. Therefore I hope the Draft error can be resolved soon to see the issues of the particular PR.

**Comment by 0penBrain** [comment]
Yep, the new CI has put forward some latent issues. Guys are working hard on fixing them. 
I also plan to work soon on the CI (and eventually the code) to improve extracting the data from the log and have an easier view of what is failing.

**Pull request merged**
