### PR TITLE
[BUGFIX]Core: partially revert 4ab37fc that introduced composed units

### LINKED ISSUE #6735: [Bug] [regression] unit python code N/mm^2 works in 0.19, but fails in 0.20
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=10&t=67882

### Version

0.20 (Development)

### Full version info

```shell
OS: Ubuntu 21.04 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28657 (Git)
Build type: Debug
Branch: master
Hash: fb1f4433c6bdafc5ec58bea0e1ea799f302c0bf1
Python 3.9.5, Qt 5.15.2, Coin 4.0.0, OCC 7.5.2
Locale: French/France (fr_FR) [ OS: French/France (fr_FR) ]
```

### Subproject(s) affected?

Core

### Issue description

```
import FreeCAD

q = FreeCAD.Units.Quantity 

kFactor = q('1400.0 N/mm^2')
print("Kf : ", kFactor, kFactor.Unit)
```

Works fine in FC 0.19 and gives output:

`13:33:53  Kf :  1400000.0 kg/(mm*s^2) Unit: kg/(mm*s^2) (-1,1,-2,0,0,0,0,0) [Pressure]`

But in Fc 0.20, gives error:

```
# 13:48:46  Traceback (most recent call last):
#  File "/home/spanner888/.local/share/FreeCAD/Macro/units@001.FCMacro", line 5, in <module>
#    kFactor = q('1400.0 N/mm^2')
#<class 'ValueError'>: syntax error
```

Confirmed by [openBrain](https://forum.freecadweb.org/memberlist.php?mode=viewprofile&u=22265)

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0penBrain**
Parser shall only deal with atomic units or it breaks other composed units
 Fixes #6735

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6737">pipeline status</a> for feature branch [PR_6737](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6737). Pipeline [514790384](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/514790384) was triggered at [fbcb980](https://github.com/FreeCAD/FreeCAD/pull/6737/commits/fbcb9805b1c5e75894b93d4f77ef2513aa27584b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
> but it looks like it makes a lot of update compared to what I changed. Is this correct to run this script ?

This is normal. If you want to have updated the generated files with as less changes as possible you must use the exact same flex/bison version.

**Comment by 0penBrain** [comment]
> This is normal. If you want to have updated the generated files with as less changes as possible you must use the exact same flex/bison version.

OK, thanks. What disturbed me is that `YY_NUM_RULES` increased by 51 !

For the Quantity parser/lexer, for sake of completeness, I only ran `bison QuantityParser.y --output=QuantityParser.c` but feel like it's not enough when dealing with lexer.

**Comment by 0penBrain** [comment]
@wwmayer OK, found the line to be ran here : https://github.com/FreeCAD/FreeCAD/blob/a70d6fd7ecf0bf9ac4e2f99ab6e4dcabeb5e6503/src/Base/QuantityParser.l#L26

I think it's clean now. As I only touch the lexers, I only ran the `flex` commands.
I should say that there is still a bit of mystery why the `bison` command makes the build to fail, but I'll eventually have a look at this later.
Sorry for noise.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6737">pipeline status</a> for feature branch [PR_6737](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6737). Pipeline [514847740](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/514847740) was triggered at [e5056ce](https://github.com/FreeCAD/FreeCAD/pull/6737/commits/e5056ce03ce224b1726e7b993a52fcd50d6d7110). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks for the fix. Since it fixes a regression is a milestone PR.

The CI succeeds and the fix if pretty obvious in my opinion. It works me correctly. -> merging

**Pull request merged**
