### PR TITLE
Add Unit (Length) Aware Preferences Widget

### PR DESCRIPTION
**Pull request by WandererFan**
This PR adds a Unit Aware (Length only) spinbox to the custom preference widget collection and modifies the TechDraw preference pages to use it.  NOTE: this PR affects Gui and Tools!
Please merge.
Thanks,
wf

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Is there a reason not to use the class PrefQuantitySpinBox?

**Comment by WandererFan** [comment]
Seemed too complicated.  Don't need the history stuff/ the context menus,
just a simple length aware save/restore.

The existing code knows how to get/use a simple float from Prefs, but there
is no getQuantity in Parameters.cpp.

Also, couldn't find any samples of PrefQuantitySpinBox except in Sketch/PD
taskDialogs, wasn't sure if PQSB was really meant for preferences.

**Comment by WandererFan** [comment]
1st AppVeyor build failed due to missing "GuiExport".  Fixed and builds restarted.

**Comment by wwmayer** [comment]
I reworked your PR as I don't like to have a class PrefLengthSpinBox for two reasons:
* we have almost 30 different units atm (and there will come a few more in the future for sure) and if we start to implement for each of them a pref widget we end up in duplicating the code 30x with only a single line that is different
* the API of such a specialized class is inconsistent as you can still change its unit afterwards. So, we would end up with a class PrefLengthSpinBox that e.g. handles temperature

So, I replaced it with the simplified class PrefUnitSpinBox without the overhead of PrefQuantitySpinBox which does the same as all the other prefwidget classes

**Comment by WandererFan** [comment]
OK.  Is is possible to expose QuantitySpinBox attributes :   Base::Unit
unit() const;  & void setUnit(const Base::Unit &unit);  ?
As is, new PrefUnitSpinBox does not completely support Unit preference for
data entry.  If prefix is set, then there is room to specify units whose
text is <= sizeof(prefix), but result is not displayed in preferred units.

**Comment by wwmayer** [comment]
I am not quite sure if I understand your request. Can you give an example of what exactly you want to have?

**Comment by WandererFan** [comment]
Adding PrefsUnitSpinBox(pusb) as-is to a UI results in this:

​
essentially just a DoubleSpinBox.  Fair enough, it doesn't know what units
to use.

If we add UnitText of mm to pusb we get UI like this:

​Looks good, but Unit pref is set to cm, not mm.

If we tell pusb somehow that it is acting as a Length spinbox we get

​which is what we want.

I used this hack in Gui::PrefWidgets.cpp for demo purposes:
void PrefUnitSpinBox::restorePreferences()
{
    if (getWindowParameter().isNull()) {
        Console().Warning("Cannot restore!\n");
        return;
    }
    setUnit(Base::Unit::Length);   //hack here
    double fVal = (double)getWindowParameter()->GetFloat( entryName()
,rawValue() );
    setValue(fVal);
}

Is there some way to specify unit type in Designer, and have pusb use it in
PrefWidgets?

**Comment by wwmayer** [comment]
> Looks good, but Unit pref is set to cm, not mm.

It basically just follows the system settings. If there you use "Building Euro" then lengths are given in cm. If you write pusb->setProperty("unit", "mm"); then QuantitySpinBox::setUnitText is invoked which parses the quantity to extract the unit Length and sets it to the pusb.
I admit that this behaviour is a bit odd. It would be nicer and less confusing if we could write
pusb->setProperty("unit", "Length"); but there is currently no way to convert a unit string to Base::Unit.

> Is there some way to specify unit type in Designer, and have pusb use it in PrefWidgets?

Yes, the unit property of the pusb also appears in QtDesigner where you can set any length unit, like mm, cm, m, ...
But again as said above it should be changed so that we set Length, instead. And for the designer it would be convenient if we could offer a combo box with all predefined units as otherwise for less common units the user always had to check the source code.

**Comment by WandererFan** [comment]
<<the unit property of the pusb also appears in QtDesigner where you can
set any length unit, like mm, cm, m, ...>>
It does eventually, but at Restore time, it uses the Designer unitText, not
the Preference Unit so you get anomalies like in the second screen grab.

The user in this case is a programmer. Maybe we don't have to be as nice to
programmers as we do to end users?

**Comment by wwmayer** [comment]
I just wonder where we would ever need the possibility that a pusb changes its unit type at runtime which would make it necessary to also save the unit type.

**Comment by WandererFan** [comment]
When you have a minute, check out this branch:
https://github.com/WandererFan/FreeCAD/tree/wmWidget

It has a popup of UnitTypes at design time and follows Unit preference
immediately at restore time.  There's a UnitType property that we could use
to change the type at run time, but like you I'm not sure why we would ever
need to do that.


​



​
The enum for UnitTypes appears three times in this version.  Don't like
that, but haven't figured out a way around it yet.

BTW there is a typo in "LuminoseIntensity".  It should be
"LuminousIntensity".

**Comment by wwmayer** [comment]
Unfortunately, I couldn't test your branch because I got tons of merge conflicts. Anyway, just looking at the code I think I got the ideas and it goes into the right direction.
However, as you said the enums appear three times and together with getUnitFromTypeString and getTypeString it's just too complicated and error-prone to add new units in the future. This should be much simpler.

**Comment by WandererFan** [comment]
No worries.  I'll try to work out something easier to maintain.

**Comment by wwmayer** [comment]
I have already something working that simplifies getUnitFromTypeString & getTypeString a lot. But I don't plan to merge this before the release.

**Comment by WandererFan** [comment]
OK.  Lots of other stuff to keep me busy!

**Pull request closed without merging**
