### PR TITLE
Introduce GoogleTest C++ unit testing framework

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

First baby step to C++ unit testing.

GoogleTest still appears to be the most popular C++ unit testing framework.

[GoogleTest](https://github.com/google/googletest)

[GoogleTestUserGuide](https://google.github.io/googletest/)

#7801

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7903">pipeline status</a> for feature branch [PR_7903](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7903). Pipeline [707618568](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/707618568) was triggered at [a062c25](https://github.com/FreeCAD/FreeCAD/pull/7903/commits/a062c2515117fb74867d05cd6f3ff6819ee1aa76). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Recently I have tested to create QTest and Goggle test following the instructions at https://doc.qt.io/qtcreator/creator-autotest.html and it worked pretty well.

For the Google test I had to download the sources from [GH](https://github.com/google/googletest) as otherwise it has failed to build.

QtCreator has created these files:
CMakeLists.txt:
```
CMAKE_MINIMUM_REQUIRED(VERSION 3.1)

PROJECT(testCase
        LANGUAGES CXX)

add_definitions(-DGTEST_LANGUAGE_CXX11)

find_package(Threads REQUIRED)

if ($ENV{GOOGLETEST_DIR})
    SET(GOOGLETEST_DIR $ENV{GOOGLETEST_DIR})
else ()
    message(WARNING "Using googletest src dir specified at Qt Creator wizard")
    SET(GOOGLETEST_DIR "/tmp/unittest")
endif ()
if (EXISTS ${GOOGLETEST_DIR})
    SET(GTestSrc ${GOOGLETEST_DIR}/googletest)
    SET(GMockSrc ${GOOGLETEST_DIR}/googlemock)
else ()
    message( FATAL_ERROR "No googletest src dir found - set GOOGLETEST_DIR to enable!")
endif ()

include_directories(${GTestSrc} ${GTestSrc}/include ${GMockSrc} ${GMockSrc}/include)

add_executable(${PROJECT_NAME} main.cpp tst_testcase.h
               ${GTestSrc}/src/gtest-all.cc
               ${GMockSrc}/src/gmock-all.cc)
add_test(${PROJECT_NAME} COMMAND ${PROJECT_NAME})
target_link_libraries(${PROJECT_NAME} PRIVATE Threads::Threads)
```

main.cpp:
```
#include "tst_testcase.h"

#include <gtest/gtest.h>

int main(int argc, char *argv[])
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
```
tst_testcase.h:
```
#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>

using namespace testing;

TEST(testCase, testOrder)
{
    EXPECT_EQ(1, 0);
    ASSERT_THAT(0, Eq(0));
}
```

Additionally I have tested Qt's unit testing framework that has created the files:
CMakeLists.txt:
```
CMAKE_MINIMUM_REQUIRED(VERSION 3.1)

PROJECT(testCase
        LANGUAGES CXX)

find_package(Qt5Test REQUIRED)
find_package(Qt5Gui REQUIRED)

SET(CMAKE_AUTOMOC ON)
SET(CMAKE_INCLUDE_CURRENT_DIR ON)
SET(CMAKE_CXX_STANDARD 11)
ENABLE_TESTING()

add_executable(${PROJECT_NAME} tst_testcase.cpp)
add_test(${PROJECT_NAME} COMMAND ${PROJECT_NAME})

target_link_libraries(${PROJECT_NAME} PRIVATE Qt5::Gui Qt5::Test)
```
tst_testcase.cpp:
```
#include <QTest>

// add necessary includes here

class testCase : public QObject
{
    Q_OBJECT

public:
    testCase();
    ~testCase();

    bool myCondition()
    {
        return true;
    }

private slots:
    void test_case1();
    void initTestCase()
    {
        qDebug("Called before everything else.");
    }
    void cleanupTestCase()
    {
        qDebug("Called after myFirstTest and mySecondTest.");
    }
};

testCase::testCase()
{

}

testCase::~testCase()
{

}

void testCase::test_case1()
{
    QVERIFY(true); // check that a condition is satisfied
    QCOMPARE(1, 1); // compare two values

    QVERIFY(myCondition());
    QVERIFY(1 != 2);
}

QTEST_MAIN(testCase)

#include "tst_testcase.moc"
```

The documentation also mentions boost.test and Catch2 but for some reason they don't appear in the settings of my QtCreator installation.

Now your PR lacks of some files and thus fails to build. So, I wonder whether we should use the created files from QtCreator and adjust them accordingly.

**Comment by wwmayer** [comment]
See https://github.com/wwmayer/FreeCAD/tree/unit_test_frameworks

**Comment by berniev** [comment]
I have added a commit with (hopefully all) the other files. Somehow they never made it into the original commit. This setup is working great in CLion IDE.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7903">pipeline status</a> for feature branch [PR_7903](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7903). Pipeline [709792686](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/709792686) was triggered at [46d7fdf](https://github.com/FreeCAD/FreeCAD/pull/7903/commits/46d7fdf607cd4d49e62131de8bb328137dc45db9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Great, builds OK now.

**Comment by wwmayer** [comment]
Replaced with #7923. The new PR squashed the two commits into one.

**Pull request closed without merging**
