### PR TITLE
TechDraw: Improve code in Python DrawViewPartPy class

### PR DESCRIPTION
**Pull request by marioalexis84**
* Check Python args using `PyArg_ParseTuple`.
* Use Python Errors to rise exceptions.
* Use `Py_Return` to correct reference count of `Py_None`.
* If `PyArg_ParseTuple` return `false`, it sets a PyError. In order for the function `removeCosmeticVertex` to continue executing code, that error must be cleaned with `PyErr_Clean`, otherwise an undefined behavior is generated.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7663">pipeline status</a> for feature branch [PR_7663](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7663). Pipeline [680112183](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/680112183) was triggered at [0dcce0f](https://github.com/FreeCAD/FreeCAD/pull/7663/commits/0dcce0ff6c5bf0847898b29f4b38d4c28a0b7ee5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
Replacing "throw" with "return nullptr" means the user does not get any indication of what was wrong.  Is this the intended behaviour?

**Comment by WandererFan** [comment]
Thank you for your contribution!

**Comment by marioalexis84** [comment]
> Replacing "throw" with "return nullptr" means the user does not get any indication of what was wrong. Is this the intended behaviour?

It is the expected behaviour (of course, it can be a matter of taste).
Most of the time, I think it's preferable to let the PyArg* functions generate the corresponding error in terms of the type and number of arguments.
Details about the arguments, such as their names, should be specified in the function's documentation.
Most of FreeCAD's Python interface follows this logic.

**Pull request merged**
