### PR TITLE
Import: support to export to glTF file in headless mode

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8649">pipeline status</a> for feature branch [PR_8649](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8649). Pipeline [788850593](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/788850593) was triggered at [388207e](https://github.com/FreeCAD/FreeCAD/pull/8649/commits/388207ecfe5ad19cc18715845aac868a66d3d69b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8649">pipeline status</a> for feature branch [PR_8649](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8649). Pipeline [788865241](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/788865241) was triggered at [5043c9f](https://github.com/FreeCAD/FreeCAD/pull/8649/commits/5043c9f7878667f802c74402b967939185d5c4fb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by gbroques** [comment]
It's out of the scope of this PR, but OpenCascade supports multi-threaded or parallel execution for glTF exporting.

See the `SetParallel(true)` method:
https://dev.opencascade.org/doc/refman/html/class_r_w_gltf___caf_writer.html

Is these any reason why we don't do this?

It may have a big effect on performance when you export a large and complex model.

**Comment by wwmayer** [comment]
It must have been added with 7.6 or 7.7. In 7.5 it's not yet available.

**Comment by wwmayer** [comment]
Multi-threading support has been added with OCCT 7.7. I will prepare a new PR to enable it.

**Comment by gt2ming** [comment]
> Multi-threading support has been added with OCCT 7.7. I will prepare a new PR to enable it.↳

Hello wwmayer

I see this PR, and I need some help!

I need to convert stp to gltf file via headless mode, using python script. But I can't find some help documentation, can you tell me how to do this conversion?

Thank you every much!

**Comment by wwmayer** [comment]
```
import Import
result = Import.open("myfile.step")
# result is a list of tuples
objlist = [i[0] for i in result]
for obj in objlist:
    data = obj.Shape.tessellate(0.5)
Import.export(objlist, "myfile.gltf")
```

**Comment by gt2ming** [comment]
> ```
> import Import
> result = Import.open("myfile.step")
> # result is a list of tuples
> objlist = [i[0] for i in result]
> for obj in objlist:
>     data = obj.Shape.tessellate(0.5)
> Import.export(objlist, "myfile.gltf")
> ```

Thank for you reply, [wwmayer](https://github.com/wwmayer)

When I use the your code, it can output the gltf file.

but When I load the gltf file in `three.js` there is a problem: a lot of mesh that will not convert, so I can't see these mesh in `three.js`.

So I changed the way, like this:

```
import os
import sys
sys.path.append('C:\\Program Files\\FreeCAD 0.21\\bin')
import FreeCAD
import Import

Import.open('C:/1.stp')
objectList.append(FreeCAD.getDocument("Unnamed").getObject("Model"))
Import.export(objectList, 'C:/1.gltf')

```

This way you can output the file correctly.

**Pull request merged**
