### PR TITLE
[PD] missing changes from commit d4be4a02

### PR DESCRIPTION
**Pull request by donovaly**
(key event handling for more dialogs)

### CODE REVIEW

**Comment by wwmayer** [comment]
Merged.

**Comment by donovaly** [comment]
> Merged.

No, because commit ee8228e was not merged. Should iIopen a new PR for this?

**Comment by donovaly** [comment]
Interesting, so the Git server seems to be slow. Now everything is in.

**Comment by wwmayer** [comment]
I merged your PR and when I closed it I realized you added a new commit. So, I fetched your changes again and merged them on top.

**Pull request closed without merging**
