### PR TITLE
Arch: Fix wall baseface generation for overlapping and self-intersecting traces

### LINKED ISSUE #7370: [Bug] Arch Wall not visible when base sketch lines overlap
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=23&t=71107
https://forum.freecadweb.org/viewtopic.php?f=23&t=67107

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Debian GNU/Linux bookworm/sid (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.30058 (Git) AppImage
Build type: Release
Branch: master
Hash: cb96332a64db8ae855ca700212eebb0f5151230a
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: English/United States (en_US)
Installed mods: 
  * BIM 2021.12.0
  * parts_library
[/code]
```

### Subproject(s) affected?

Arch

### Issue description

Create sketch, apply Wall. Edit sketch and overlap a new line within one of the existing lines. In the view your wall is not visible anymore. This seems broken, overlapping lines should get merged not cause a failure of the wall to be visible.

### Anything else?

FCArchWallsOverlapBug-2view
FCArchWallsOverlapBug-2sketch
FCArchWallsOverlapBug-1view
FCArchWallsOverlapBug-1sketch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Roy-043**
To fix the issue a new argument, `per_segment`, was introduced for the `bind` function in `faces.py`. Additionally the call to `face.fix()` was moved to that function.

Fixes #7370

Forum topics:
https://forum.freecadweb.org/viewtopic.php?f=23&t=67107&start=30
https://forum.freecadweb.org/viewtopic.php?f=23&t=71107

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7436">pipeline status</a> for feature branch [PR_7436](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7436). Pipeline [630414837](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/630414837) was triggered at [8aaa36a](https://github.com/FreeCAD/FreeCAD/pull/7436/commits/8aaa36a01308c02dc377be68a1ad0d8c677512ca). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Amazing job!

**Comment by Roy-043** [comment]
@donovaly FYI: this bug fix can be backported.

**Comment by donovaly** [comment]
Thanks, backported.

**Pull request merged**
