### PR TITLE
SurfaceOfExtrusion: use uIso and vIso methods of parent class

### PR DESCRIPTION
**Pull request by tomate44**
Currently, SurfaceOfExtrusion methods uIso() and vIso() fail on several basis curves : 

ellipse = Part.Ellipse()
extrusion = Part.SurfaceOfExtrusion(ellipse, FreeCAD.Vector(0,0,1))
viso = extrusion.vIso(0)
viso
--->
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NotImplementedError: Iso curve is of type 'Geom_Ellipse'

Similarly to what is done in SurfaceOfRevolution, it seems better to use parent GeometrySurface methods directly. 
  

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I still have the impression this code is useful and simply not fully implemented... Is it a good thing to ditch it altogether? Maybe just commenting it out is better...

**Comment by tomate44** [comment]
Thanks for your feedback.
I had further look at the file history.
In fact, it was me that [added the 2 methods in 2016](https://github.com/FreeCAD/FreeCAD/commit/d6f2446e57a902dc822d22cadfae50d45ec2c504) ;D
But the same day, Werner [modified these 2 methods in the parent class](https://github.com/FreeCAD/FreeCAD/commit/7baeb6e51ac961f9931a11887618ad37503cefb8#diff-dc13f870820ed4b71bbde40e99367a9a).
So I am a bit confused now ... It is hard to figure the logic now, but I have the feeling that my additions were obsolete from day one !

**Comment by tomate44** [comment]
I had more thinking about this.
Too me, here is what happened : 
Before this 2016 commit, SurfaceOfExtrusion had no overridden uIso / vIso methods.
So it was using parent class methods, that were returning generic [GeometryCurve](https://github.com/FreeCAD/FreeCAD/commit/7baeb6e51ac961f9931a11887618ad37503cefb8#diff-dc13f870820ed4b71bbde40e99367a9aL64) that were probably not very useful in a python script. So I tried fixing this by copy/pasting the parent class methods.
While, at the same time, Werner did a correct fix in the base class.
So, I still think these 2 overrides can now be removed.

**Comment by wwmayer** [comment]
UIso and VIso (and many others) are virtual methods of OpenCascade's abstract Geom_Surface class. At the very beginning when implementing the Python wrapper classes we haven't implemented a wrapper for Geom_Surface and thus implemented its virtual methods in all derived Python wrapper classes. This led to a lot of code duplication and made maintenance more difficult.

That's why also a wrapper for Geom_Surface has been added and this made the implementation in various sub-classes obsolete.

**Comment by tomate44** [comment]
Thanks for the explanation.

**Comment by wwmayer** [comment]
I have looked at the current code and most of the surface classes implement their own uIso/vIso:
BSplineSurfacePy, BezierSurfacePy, ConePy, CylinderPy, PlanePy, RectangularTrimmedSurfacePy and ToroidPy. SpherePy invokes the method of its base class.

These classes assume that an iso curve can be only of a certain curve type and only handle this case. Basically these methods can all be removed (maybe except for RectangularTrimmedSurfacePy because this a special case and must be checked carefully).

**Comment by tomate44** [comment]
I can put this on my TODO list if you wish.

**Comment by wwmayer** [comment]
Sure! TIA!

**Pull request merged**
