### PR TITLE
[TD] TaskCenterLine add missing unit initialization

### PR DESCRIPTION
**Pull request by donovaly**
(for the editing dialog this is already set)

- also use Gui::QuantitySpinBox as recently discussed
- also add alignment properties

### CODE REVIEW

**Comment by WandererFan** [comment]
resolved merge conflict in center line ui, but no PR is stuck.

**Comment by WandererFan** [comment]
OK, unstuck now.  Was just a delay in report CI status back to github.

**Comment by donovaly** [comment]
Please close this PR if PR #3281 can be merged.

**Comment by WandererFan** [comment]
closed in favour of #3281

**Pull request closed without merging**
