### PR TITLE
Path:  Fixing postprocessor testing (with refactoring) and adding a few postprocessor tests.

### PR DESCRIPTION
**Pull request by LarryWoestman**
The existing code for testing Path postprocessors was not included in the tests.  It appears to have been based on an older version of the Path code and tools.

This pull request refactors the code for testing Path postprocessors to make it easier to add additional tests and updates the code to work with all of the Path changes that are in the 0.20 code base.

I have also added three tests each for the linuxcnc and centroid postprocessors.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [X]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6535">pipeline status</a> for feature branch [PR_6535](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6535). Pipeline [487733656](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/487733656) was triggered at [4199fe0](https://github.com/FreeCAD/FreeCAD/pull/6535/commits/4199fe07a70fb8c781752a353ee7d9d188af1e69). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6535">pipeline status</a> for feature branch [PR_6535](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6535). Pipeline [490848361](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/490848361) was triggered at [0a8d9b2](https://github.com/FreeCAD/FreeCAD/pull/6535/commits/0a8d9b266578a17657a523a0c7a5d9f6f1606fc5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6535">pipeline status</a> for feature branch [PR_6535](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6535). Pipeline [499844821](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/499844821) was triggered at [79b0a44](https://github.com/FreeCAD/FreeCAD/pull/6535/commits/79b0a4461d7b8064b908585186efb597b742641d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6535">pipeline status</a> for feature branch [PR_6535](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6535). Pipeline [505497282](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/505497282) was triggered at [dfddff3](https://github.com/FreeCAD/FreeCAD/pull/6535/commits/dfddff339f55132b494659b2295c80933e6c6764). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Something went wrong with this PR since it has 395 commits.

However, master is now closed until FreeCAD 0.20 is released. Please make a new PR then.

**Pull request closed without merging**
