### PR TITLE
Allow automatic tests discovery

### PR DESCRIPTION
**Pull request by Pesc0**

### CODE REVIEW

**Comment by wwmayer** [comment]
What does this PR try to achieve?

**Comment by Pesc0** [comment]
Enables ctest to discover all the unit tests specified by googletest. This PR does nothing really, but enables vscode to display and run the tests. This is part of #11076

**Comment by wwmayer** [comment]
So, it's just a thing to display the unit tests in your IDE?  I asked because I use QtCreator and for me unit tests have always been visible.

**Comment by Pesc0** [comment]
Basically yes, its just for vscode. I don't know if there's other use cases. Anyway it should be harmless by itself

**Comment by luzpaz** [comment]
The principle question is why does Qt Creator find it and not vscode ?

**Comment by wwmayer** [comment]
Because it's smarter.

**Pull request merged**
