### PR TITLE
[Preference pages] Rename some and move to sub-folder

### PR DESCRIPTION
**Pull request by PaddleStroke**
This is a code-only PR to organize some files better: 

- Rename DlgGeneralImp to DlgSettingsGeneral to match others.
- Rename DlgEditor to DlgSettingsEditor to match others.
- Rename DlgReportView to DlgSettingsReportView to match others.

Move all the preference pages to 'PreferencePages' subfolder, to reduce the number of files of the main gui folder.

Issue : #10014

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by PaddleStroke** [comment]
@wwmayer What do you think about this ?
This PR is likely to get a lot of conflicts as it moves a lot of files. So perhaps it's best merge it sooner rather than later if it's deemed worthy.

**Comment by PaddleStroke** [comment]
I'm not familiar with the translation files. Which ones are concerned ? qm files are compiled version of the ts files ?

**Comment by wwmayer** [comment]
> Which ones are concerned ?

All .ts files under src/Gui/Language. The compiled .qm files will be broken, too.

**Comment by chennes** [comment]
IMO, we should make this change: translators will have a little bit of work to do, but CrowdIn will assist them in generating the new translations because it will recognize the strings (even though the context changed). @wwmayer do we have to change something in the CMake files to make sure the qm files are compiled correctly? Or is it just that the translations will be out of date until the ts files are updated?

**Comment by wwmayer** [comment]
> do we have to change something in the CMake files to make sure the qm files are compiled correctly?

No, nothing needs to be changed.

> Or is it just that the translations will be out of date until the ts files are updated?

Yes. Or the .ts files can be edit manually but this I don't recommend. Since we started with the new development version it's fine if the translation is "broken" for a while.

**Comment by chennes** [comment]
Great, let's get this in then -- @PaddleStroke can you please rebase to the latest master and make sure nothing breaks? I just merged in a preferences-related PR so you'll probably have to fix a conflict or two.

**Comment by PaddleStroke** [comment]
Rebased. There were conflicts with Selection and ViewColor preference pages.

**Comment by PaddleStroke** [comment]
It's the theme PR that you just merged that made a new conflict.
I will rebase it again asap

**Comment by PaddleStroke** [comment]
@chennes rebased.
Note : I have not moved DlgSettingsImage and DlgSettingsColorGradient because I don't know what are those pref pages and they don't appear to be in the main preference page. So we will have to look at them after.

**Comment by wwmayer** [comment]
* DlgSettingsImage: opens when saving an image (Tools > Save image)
* DlgSettingsColorGradient: when e.g. computing the curvatures of a mesh then a color gradient on the right side appears. Double-clicking on it opens this dialog

In order to further clean-up the Gui folder we can create a sub-directory _Dialog_ and move all dialog classes there.

**Comment by wwmayer** [comment]
> dialog/PregerencePages.

Actually not because the individual pages are no dialogs but normal widgets. Only the container widget itself DlgPreferencesImp is a dialog.

Beyond that I wouldn't create a too nested directory structure.

**Pull request merged**
