### PR TITLE
PartDesign: Fix typo in function getContiniusEdges->getContinuousEdges

### PR DESCRIPTION
**Pull request by luzpaz**
Related to PR #5029

### CODE REVIEW

**Comment by chennes** [comment]
@luzpaz @troyp76 Would you prefer this be merged before #5029, or do you want to wait until that PR is ready?

**Comment by luzpaz** [comment]
I defer to @troyp76

**Comment by troyp76** [comment]
@chennes @luzpaz 
Yes merge #5031 first as it is _functionally_ unrelated to #5029 and relatively low risk.

I expect #5029 still has a way to go before being ready to merge so no need to wait for it.

**Comment by luzpaz** [comment]
@chennes quick question, I'm not seeing doxygen markup for this function. How would we add some ? (I can make a new PR if we do so)

**Comment by chennes** [comment]
@luzpaz If you look at the function immediately above it (`getBaseObject`), you will see a "template" of how to add Doxygen documentation. I personally use the guidance from OpenOCD for what Doxygen should look like, I haven't seen any sort of style guide for FreeCAD. https://openocd.org/doc-release/doxygen/styledoxygen.html

**Comment by luzpaz** [comment]
@chennes thanks. Maybe it's time to officially decide on one? Anyway.. back to this PR. Feel free to merge when you decide appropriate.

**Comment by chennes** [comment]
I really miss having CI... I'm just double-checking to make sure it compiles on a few different systems. Stay tuned...

**Comment by chennes** [comment]
OK, I tested this on Ubuntu 21.04 and Windows (Visual Studio), it compiles fine on both. Merging now...

**Pull request merged**
