### PR TITLE
[GUI] Add window decorations to About

### PR DESCRIPTION
**Pull request by chennes**
Recently the window decorations on the About window disappeared. Examining the code, it's not clear why they were ever there in the first place, but their absence is missed. This removes the "Frameless" window hint, restoring the frame and close buttons to the window (the window remains modal).

https://forum.freecadweb.org/viewtopic.php?f=34&t=56174&p=483233#p483233

---

- [X]  Your pull request is confined strictly to a single module. 
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [X]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  No tracker ticket

### CODE REVIEW

**Comment by wwmayer** [comment]
> Recently

"Recently" was more than 15 years ago :) 
See also: https://forum.freecadweb.org/viewtopic.php?f=34&t=56174&p=483233#p483401

**Comment by chennes** [comment]
> "Recently" was more than 15 years ago :)

I know! I don't know why it felt like a change, when the code clearly hasn't been modified in many, many years. Probably just faulty memory on my part.

At any rate, I've pushed another commit to prevent resizing. @hyarion's suggestion is probably a good one, too, but I have some other internal changes I'd like to make to this dialog, so I will wait on that one until the next PR.

**Comment by hyarion** [comment]
Tested on macos and decorators are added and window can't be resized as requested (see screenshot below).

However, all tabs are the same size except the Credits tab which is slightly smaller vertically. This makes the window change size when cycling through the tabs.

image

**Comment by hyarion** [comment]
Btw, shouldn't the pull request be called:
`[GUI] Add window decorations to about`
instead of:
`[GUI] Add window decorations to splashscreen`?

**Comment by chennes** [comment]
Well, I tried to amend that commit message, but having never done that before it looks like I've made a bit of a mess. @wwmayer let me know if you'd like me to create the PR from scratch. At any rate, yes, @hyarion, both the commit and the PR should refer to About, not Splashscreen (the About window is in Splashscreen.cpp, so it was in my mind as I was typing).

To resolve the resizing thing I went ahead and made the next change that I wanted to do to the window, which was to replace the hard-coded version of the Credits list in the .ui file with one that is loaded from a plaintext CONTRIBUTORS file. In the long run we should be able to auto-generate this file, I hope. I left it as a separate commit, and can make it a totally separate PR if preferred, just let me know.

**Comment by hyarion** [comment]
No need to create a new PR, you can salvage this:

1. Run `git rebase -i master`
2. Remove the lines for the commits you want to remove from your branch.
3. Verify that the new branch looks alright
4. Run `git push -f`

**Comment by wwmayer** [comment]
> let me know if you'd like me to create the PR from scratch

No, I think I can get it working by only cherry-picking the first two and last commit.

**Comment by wwmayer** [comment]
Merged as d8e523978ca5f (that contains the first two commits) and f5cc3027f40cebef

**Pull request closed without merging**
