### PR TITLE
Fixes Xercesc include, harmonize XercesC_INCLUDE_DIRS statement

### PR DESCRIPTION
**Pull request by dirkolbrich**
Fixes file-not-found error for including XercesC files during build, due to typo error in cmake statement.
Harmonizes XercesC_INCLUDE_DIRS statements across code base.

See https://forum.freecadweb.org/viewtopic.php?f=4&t=60663 for error description.
See https://stackoverflow.com/questions/68714618/compile-freecad-on-macos-big-sur-11-5-1-with-homebrew-error-finding-xercesc-fil for solution.

### CODE REVIEW

**Comment by ageeye** [comment]
Hello Dirk, nice to see that you found a solution. I test your PR. For me work both.

Kind regards Benjamin (gift)

**Comment by luzpaz** [comment]
cc @ipatch

**Comment by ipatch** [comment]
i'll give it a go here in a sec.

@dirkolbrich

something i thought about 🤔 while emptying cat liter boxes earlier today.

are you running a case sensitive file system of some sort?

i remember years ago when apple introduced jHFS+ file system with case sensitivity support a lot known apps mostly `[INSERT_APP_NAME].app` stopped working for me. and eventually settled on not using a case sensitive file system on my macos installations.

**Comment by ipatch** [comment]
didn't run into any issues on my end with the below cmake command

```
cmake \ -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG \                                                                                  
                -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG \
                -DCMAKE_CXX_STANDARD=14 \
                -DBUILD_ENABLE_CXX_STD:STRING=C++14 \
                -Wno-deprecated-declarations \
                -DCMAKE_FIND_FRAMEWORK=LAST \
                -DCMAKE_VERBOSE_MAKEFILE=OFF \
                -Wno-dev \
                -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk \
                -DBUILD_QT5=ON \
                -DUSE_PYTHON3=1 \
                -DPYTHON_EXECUTABLE="/usr/local/opt/python3.9/bin/python3" \
                -DPYTHON_INCLUDE_DIR="/usr/local/opt/python3.9/Frameworks/Python.framework/Headers" \
                -DCMAKE_PREFIX_PATH="" \
                -DBUILD_SMESH=1 \
                -DBUILD_FEM_NETGEN=0 \
                -DBUILD_FEM=0 \
                -DBUILD_TECHDRAW=0 \
                -DFREECAD_USE_EXTERNAL_KDL=ON \
                -DBUILD_WEB=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DFREECAD_CREATE_MAC_APP=ON \
                -DFREECAD_USE_FREETYPE:BOOL=OFF \
                -DCMAKE_INSTALL_PREFIX=/opt/beta/freecad.apl ../freecad-src

```

---

```
-- Making bundle relocatable...
-- INFO: Analyzing bundle dependencies...
-- INFO: Copying external dependencies to bundle...
-- INFO: Updating dynamic loader paths...
-- INFO: Setting bundled library IDs...
-- INFO: Done.
```

image

**Comment by dirkolbrich** [comment]
My system runs an AFPS case sensitive file system. The machine came with macOS 10.12 Sierra. With the update to macOS 10.13 High Sierra there was a switch to AFPS. But I don't remember intentionally setting the case sensivity. Must have been done automatically by the system.

Anyways, as it should be good coding practice, the statement `XercesC_INCLUDE_DIRS` should only use the case sensitive version as specified in the [Cmake docs](https://cmake.org/cmake/help/latest/module/FindXercesC.html) to prevent such errors I encountered.

There are 67 occurrences of `XercesC_INCLUDE_DIRS` within the complete FreeCAD code base. All but the 4 changed ones already used the correct case sensitive version.

**Review by chennes — APPROVED** [review]
This is a good change -- it compiled and runs fine in my tests on Windows 10.

**Comment by luzpaz** [comment]
Packagers, please confirm changes are OK please? Thx!

@apeltauer (Windows)   
@kkremitzki (Debian)  
@greyltc (Arch)  
@hobbes1069 (Fedora)  
@PrzemoF (Fedora Copr)  
@adrianschroeter (openSUSE)

**Comment by apeltauer** [comment]
Just builded against the latest remote master branch with no errors.
So i think your changes are not effecting the windows build.

**Comment by hobbes1069** [comment]
Looks fine to me. Nothing I couldn't work around it if did cause an issue.

**Pull request merged**
