### PR TITLE
[UI] Logo Update

### PR DESCRIPTION
**Pull request by obelisk79**
Here is an update to all instances I could find of the old logo to reflect the new logo. TechDraw templates will be updated via a separate PR.

### CODE REVIEW

**Comment by FEA-eng** [comment]
This one will also need update:
IMG_7733

**Comment by maxwxyz** [comment]
@FEA-eng yes there are plenty to change for the website as well but this PR only changes the logo in the application.

**Comment by FEA-eng** [comment]
> @FEA-eng yes there are plenty to change for the website as well but this PR only changes the logo in the application.

There were some discussions about improving the colors in this new logo but I guess it's nothing official for now so it should make sense to update everything already.

**Comment by maxwxyz** [comment]
Yes it was optimized. This is the new version.

**Comment by adrianinsaval** [comment]
should also be updated:
https://github.com/FreeCAD/FreeCAD/blob/main/src/Main/icon.ico 
https://github.com/FreeCAD/FreeCAD/blob/main/src/Doc/sphinx/_static/favicon.ico
https://github.com/FreeCAD/FreeCAD/tree/main/tools/build/WindowsInstaller/icons

**Comment by maxwxyz** [comment]
@obelisk79 ^
and also: 
[tools/build/WindowsInstaller/graphics](https://github.com/FreeCAD/FreeCAD/tree/main/tools/build/WindowsInstaller/graphics)
[tools/build/WindowsInstaller/Bitmaps](https://github.com/FreeCAD/FreeCAD/tree/main/tools/build/WindowsInstaller/Bitmaps)

**Comment by obelisk79** [comment]
I've addressed the identified logo instances.

**Comment by maxwxyz** [comment]
@obelisk79 you've missed https://github.com/FreeCAD/FreeCAD/blob/main/tools/build/WindowsInstaller/graphics/orange.bmp

**Comment by obelisk79** [comment]
regarding orange.bmp, this is a bit challenging since I have to completely recreate the image... I don't have a source to re-add the new logo.

**Comment by maxwxyz** [comment]
We can do those in a separate PR, I've plenty of time on Thursday.

**Comment by obelisk79** [comment]
@chennes this is ready for merge. I've also added an SVG file for future updates to orange.bmp as I had to recreate the image by hand in order to add the new logo for the windows installer. I've also changed the logo reference for readme.md to /src/Gui/Icons/freecad.svg.

**Comment by obelisk79** [comment]
> I believe this is the source 

@adrianinsaval After recreating this by hand in inkscape, seeing the reference image hurt to the core lol

**Comment by adrianinsaval** [comment]
> @adrianinsaval After recreating this by hand in inkscape, seeing the reference image hurt to the core lol

uff, I can imagine. Here's the actual bmp that nsis provides if it's of any use.
[orange.zip](https://github.com/FreeCAD/FreeCAD/files/15459336/orange.zip)
like I said we're not married to the style so if you want to do some other design the door is open.

header.bmp seems to have some white lines on the logo, not sure why, can you check that?

**Comment by adrianinsaval** [comment]
I'll merge so this gets into today's weekly, the installer stuff can be fixed later since that's only used for stable releases

**Comment by maxwxyz** [comment]
@adrianinsaval also this one: https://github.com/FreeCAD/FreeCAD-Bundle/pull/233

**Pull request merged**
