### PR TITLE
Mesh: remove trailing whitespace

### PR DESCRIPTION
**Pull request by luzpaz**
I intend to open a PR similar to #7766 for this PR once it's merged

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7768">pipeline status</a> for feature branch [PR_7768](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7768). Pipeline [690983788](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/690983788) was triggered at [3e18a69](https://github.com/FreeCAD/FreeCAD/pull/7768/commits/3e18a6903ab359f632a1e75e4b8755c590683ff3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Putting PR on hold because it looks like my IDE is introducing `^M` as line endings. Can we add a test to the CI to root out this issue?

**Comment by wwmayer** [comment]
> Putting PR on hold because it looks like my IDE is introducing ^M as line endings.

I don't know how it comes but when running `git diff` for my changes then it also shows the `^M` but they are not added to touched files. It's just a visual glitch. If you open the PR on GH and add `.diff`to the url (i.e. https://github.com/FreeCAD/FreeCAD/pull/7768.diff) you won't see them there either.

**Comment by luzpaz** [comment]
Thanks @wwmayer. Rebased and ready for review.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7768">pipeline status</a> for feature branch [PR_7768](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7768). Pipeline [694343024](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/694343024) was triggered at [acd2513](https://github.com/FreeCAD/FreeCAD/pull/7768/commits/acd2513905fd22bfe60fed09a7e3db4820b9e9a8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Merged - the CI failure is just codespell's braindead handling of camel case.

**Pull request merged**
