### PR TITLE
Walkthrough for adding macros to custom global toolbar

### PR DESCRIPTION
**Pull request by mwganson**
Link to video demonstration and forum discussion: [(https://forum.freecadweb.org/viewtopic.php?f=8&t=37551&p=319824#p319700)]

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by mwganson** [comment]
Working link:

https://forum.freecadweb.org/viewtopic.php?f=8&t=37551&p=319824#p319700

**Comment by mwganson** [comment]
I'm going to add some null pointer checks to this.

**Comment by yorikvanhavre** [comment]
This is a very nice idea. I'll give it a test spin too. Is it done, or are you going to add more commits?

**Comment by wwmayer** [comment]
https://forum.freecadweb.org/viewtopic.php?f=8&t=37551&p=320313#p320313

**Comment by mwganson** [comment]
Yorik, it's ready for a test drive.   

I'm getting this warning in the report view intermittently upon closing the macro execute dialog:

`QXcbConnection: XCB error: 3 (BadWindow), sequence: 10280, resource id: 8389772, major code: 40 (TranslateCoords), minor code: 0`  

It has only happened a few times.  Never a crash on this debug build, only the warning message.  I thought I had fixed it when I stopped hiding the macro execute dialog and then showing it again after the customize dialog closes, but I just got the warning again.   Perhaps this only happens on my system.  The reason for thinking that could is because I had a hard time getting the 0.19 qt5 build setup in cmake.  I had to go in and do a lot of editing.  Some old references to qt4 I just changed to qt5 and others I deleted entirely.  Could be I made some mistake somewhere and now some qt5 component is missing on my builds.

I would also like to be sure the qt4 builds will not be broken in case I used something that was qt5-specific.

There is another minor issue I mentioned on the forum related to the toolbar state not getting stored to user parameters when the customize dialog is closed.  It seems to be only committed to user parameters upon exiting FreeCAD.  And of course if FreeCAD crashes or is force closed, then those changes would be lost.  This is unrelated to my code except it causes the detection of existing macro actions to fail, but this is minor and harmless -- the user just gets an extra dialog.  Could go back to advising the user to restart FreeCAD to apply changes, but I think 99% of the time it won't be necessary to restart.  Merely switching workbenches gets the toolbar to update.  And I think most of the time the user will add the macro to the toolbar upon creation of the macro action, so he won't have reason to go back again with the same macro selected.

**Comment by mwganson** [comment]
One more thing.  I know you have been working on the addon manager.  Great job by the way.  The way the macro icons are being handled is very awkward for the user.  He has to manually download the icon file and save it to his custom icon folder, which he has to add in the pixmap selection dialog, then select the icon from all the other icons listed.

I have an idea, but I don't know exactly how to do it.

We could adopt a naming convention where the icon name is the same as the macro name, example MyMacro.FCMacro would have an icon file named MyMacro.svg or MyMacro.png.  When the user opens the customize dialog and selects a macro from the list, FreeCAD would check the user's custom icon folder for a file named MyMacro.svg or MyMacro.png and if found set the default pixmap to that file.

Mario mentioned some work is being done in the wiki to add icon download links for the macros.  I'm thinking the addon manager could download this icon file, rename it to conform with the above naming convention and save it to the custom icon folder, which by default could be a subfolder of the macros folder.  For example, if the macros folder is /home/macros, then the icon folder would be /home/macros/icons.  When the user uninstalls the macro using the addon manager the icon could also be removed.

Even if we can't have FreeCAD automatically set the pixmap, at least having the icon automatically placed in the macros/icons folder would be a big step in the right direction.

**Comment by mwganson** [comment]
I think I have everything resolved on this.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
