### PR TITLE
[Gui] Sort Add Property types list

### PR DESCRIPTION
**Pull request by VM4Dim**
- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
---

Add_property_sort2

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8461">pipeline status</a> for feature branch [PR_8461](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8461). Pipeline [775311271](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/775311271) was triggered at [75b1509](https://github.com/FreeCAD/FreeCAD/pull/8461/commits/75b1509ad3c684e48c1ab13c677a8358332c740a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Is there an issue/discussion linked to this PR ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8461">pipeline status</a> for feature branch [PR_8461](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8461). Pipeline [776100294](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/776100294) was triggered at [e9779ef](https://github.com/FreeCAD/FreeCAD/pull/8461/commits/e9779efaddfa3232be38b0c80b029bb0e69bac7f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by VM4Dim** [comment]
> Is there an issue/discussion linked to this PR ?

No

**Comment by luzpaz** [comment]
Can you then please explain/elaborate what you are trying to achieve and why you deem this necessary? TIA

**Comment by VM4Dim** [comment]
I think it's easier to select item from a sorted large list than from random.

**Comment by donovaly** [comment]
How is this dialog opened?

In principle sorting is fine if data has no other structure. So fine with me to merge this PR.

**Comment by VM4Dim** [comment]
> How is this dialog opened?

https://wiki.freecad.org/Property_editor#Actions

First need to activate "Show all"
 then click "Add property"

**Comment by donovaly** [comment]
> First need to activate "Show all" then click "Add property"

Thanks. I never knew this feature yet.
-> merging

**Pull request merged**
