### PR TITLE
Fix build warnings from deprecated Boost headers (they are used inter…

### PR DESCRIPTION
**Pull request by f3nix**
…nally by Boost)

Cheers,
Mateusz

### CODE REVIEW

**Comment by wwmayer** [comment]
In the first place this seems a boost-internal issue and I wonder if there is a ticket for that on the boost bug tracker.
The issue about these warning has come up recently in: https://forum.freecadweb.org/viewtopic.php?f=4&t=52796#p453604
and IIRC it was about function_output_iterator.hpp being deprecated that is still used by boost itself.

I don't mind changing our code to suppress this warning but I prefer a less-invasive change that can be easily reverted when boost has fixed the issue.
Like we did for
`# include <boost_bind_bind.hpp>`
to fix the warnings about the _1, ... placeholders I prefer to create the file boost_signals2.hpp with this content:
```
#ifndef FREECAD_SIGNALS2_HPP_WORKAROUND
#define FREECAD_SIGNALS2_HPP_WORKAROUND

// Workaround for boost >= 1.74
#define BOOST_ALLOW_DEPRECATED_HEADERS
#include <boost/signals2.hpp>
#undef BOOST_ALLOW_DEPRECATED_HEADERS

#endif // #ifndef FREECAD_SIGNALS2_HPP_WORKAROUND
```

To revert this change sometime in the future we only have to use the IDE's Search & Replace function to replace
`<boost_signals2.hpp>` again with `<boost/signals2.hpp>`

**Comment by f3nix** [comment]
Hi.
> In the first place this seems a boost-internal issue and I wonder if there is a ticket for that on the boost bug tracker.
> The issue about these warnings has come up recently in: https://forum.freecadweb.org/viewtopic.php?f=4&t=52796#p453604
> and IIRC it was about function_output_iterator.hpp being deprecated that is still used by boost itself.

Yes. It is about function_output_iterator.hpp.

> I don't mind changing our code to suppress this warning but I prefer a less-invasive change that can be easily reverted when boost has fixed the issue.
> Like we did for
> `# include <boost_bind_bind.hpp>`
> to fix the warnings about the _1, ... placeholders I prefer to create the file boost_signals2.hpp with this content:
> 
> ```
> #ifndef FREECAD_SIGNALS2_HPP_WORKAROUND
> #define FREECAD_SIGNALS2_HPP_WORKAROUND
> 
> // Workaround for boost >= 1.74
> #define BOOST_ALLOW_DEPRECATED_HEADERS
> #include <boost/signals2.hpp>
> #undef BOOST_ALLOW_DEPRECATED_HEADERS
> 
> #endif // #ifndef FREECAD_SIGNALS2_HPP_WORKAROUND
> ```
> 
> To revert this change sometime in the future we only have to use the IDE's Search & Replace function to replace
> `<boost_signals2.hpp>` again with `<boost/signals2.hpp>`

Thanks for the info! :) I'll redo the changes in a minute.

Cheers,
Mateusz

**Comment by f3nix** [comment]
Branch updated with the proposed changes.

Cheers,
Mateusz

**Comment by wwmayer** [comment]
Cool and thanks :)

**Comment by f3nix** [comment]
Thanks @wwmayer ! :)

**Pull request merged**
