### PR TITLE
Add test for child visibility in Arch BuildingPart or GroupExtensions

### PR DESCRIPTION
**Pull request by bgbsww**
Fix for #9277.

This fixes the immediate issue with space bar or Std_ToggleVisibility,  Thats a step forward.  It seems to allow all the visibility switches at each level to not be overridden when you set them manually,  fixing that issue as well.

I'm not sure if the exact behaviors when you have architectural parts inside a group inside a BuildingPart are completely what we want - you can turn visibility on and off at each level, and it affects the parts at the bottom just fine.  I'm not sure what our expected behaviors are for all permutations of Vis On/Off inside of Vis On/Off inside of Vis On/Off.

The complexity level here is fairly high ( at least for my experience level in this codebase), and it took quite a bit of debug time to locate the issue.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This seems to work fine for Arch objects indeed, but there might be more involved, that I can't foresee... IIRC this was part of Realthunder's work... @realthunder could you have a quick look here if that solution might present problems in your opinion?

**Comment by realthunder** [comment]
See my fix at #11763

**Comment by bgbsww** [comment]
I've removed the code change and just left the test, which does pass after #11763 is applied.

**Comment by yorikvanhavre** [comment]
Awesome! Waiting for the CI tests to finish and we can merge this. Thanks to both of you!

**Comment by Freedman-CB1** [comment]
The expected behavior was to change the Transparency at the object level. Part and Group don't have their own transparency property so I would not expect them to be included in the selection process. I'm not sure about Arch. The idea of the toggle was a quick selection of an object/objects in the Workbench including Sketcher. Valid Sketcher selections will be from the tree only because Sketcher is sketch object modal in the 3D. Maybe the name "Transparency toggle" needs to be "Transparency Object toggle" for clarity.

**Comment by bgbsww** [comment]
@Freedman-CB1 did you mean to be commenting on #11763 ?

**Comment by Freedman-CB1** [comment]
No, I will try to fix this. Thanks

**Pull request merged**
