### PR TITLE
remove unused GZstream library interface files

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8585">pipeline status</a> for feature branch [PR_8585](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8585). Pipeline [786853279](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/786853279) was triggered at [ef045e5](https://github.com/FreeCAD/FreeCAD/pull/8585/commits/ef045e570390d9b92b5d955092a54560d6135eca). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8585">pipeline status</a> for feature branch [PR_8585](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8585). Pipeline [787066405](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/787066405) was triggered at [9dcc28c](https://github.com/FreeCAD/FreeCAD/pull/8585/commits/9dcc28c24b3a9806fada2b75288df2c4a20ebd24). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8585">pipeline status</a> for feature branch [PR_8585](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8585). Pipeline [787072182](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/787072182) was triggered at [757b7b6](https://github.com/FreeCAD/FreeCAD/pull/8585/commits/757b7b6ee38007c55f94fb5e3af0c455c651772e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
What function did this library provide ?

**Comment by mosfet80** [comment]
@luzpaz gzstream was used by zlib. This hase been removed in https://github.com/FreeCAD/FreeCAD/pull/8213/files.

I checked that the two files removed were not included in other files.

**Comment by chennes** [comment]
I just merged the fdstream -- can you resolve the conflict and force-push? Thanks!

**Comment by xtemp09** [comment]
Has `gzstream` been removed completely or [something remains](https://freecad.github.io/SourceDoc/d7/d34/classBase_1_1ogzstream.html)?

**Comment by mosfet80** [comment]
@xtemp09 completely removed

**Pull request merged**
