### PR TITLE
PD: improve hole dialog layout

### PR DESCRIPTION
**Pull request by adrianinsaval**

### CODE REVIEW

**Comment by maxwxyz** [comment]
I guess more a UI fix and a fresh PR but also the ping for the upcoming feature freeze on this one.

**Comment by chennes** [comment]
@adrianinsaval can you add before and after screenshots?

**Comment by adrianinsaval** [comment]
before:
image

after:
image

**Comment by chennes** [comment]
Ready for @FreeCAD/design-working-group review.

**Pull request merged**
