### PR TITLE
Part: CheckGeometry -- address issues with using original shape when …

### PR DESCRIPTION
**Pull request by mwganson**
…link has been transformed and/or scaled

https://forum.freecadweb.org/viewtopic.php?f=3&t=67961

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6743">pipeline status</a> for feature branch [PR_6743](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6743). Pipeline [515545517](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/515545517) was triggered at [146bde8](https://github.com/FreeCAD/FreeCAD/pull/6743/commits/146bde8f01bc8a8a6f831c34bbf5a125ffbba794). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@realthunder , could you please review this PR? If OK, it can go in for FC 0.20

**Comment by realthunder** [comment]
It's good.

**Comment by donovaly** [comment]
Thanks. Merging.

**Pull request merged**
