### PR TITLE
py3: AddonManager: use urllib.request insted of urllib2

### PR DESCRIPTION
**Pull request by looooo**
issue 0000995

maybe someone with better insights into addonmanager can test this with python2. @yorikvanhavre

### CODE REVIEW

**Comment by wwmayer** [comment]
Merged.

**Comment by easyw** [comment]
there is an issue that may be related to this PR
Using the addon manager from the menu and clicking to the Macros tab an error raises:

> Traceback (most recent call last):
> File "C:\FreeCAD\Mod\AddonManager\AddonManager.py", line 391, in run
> macros.sort(key=str.lower)
> TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

**Comment by looooo** [comment]
oh sry. Thats was my fault. str == bytes in python2. stupid me. I will try to find another way.
I think this should solve it:
https://github.com/looooo/FreeCAD/commit/a3d329d129832e860c668d932c8b2b3b5333173c

**Comment by easyw** [comment]
it's fine now, thx 😸

**Comment by easyw** [comment]
I found an other issue that may be related to this lib...
trying to install a WB with FC 0.17 11091 win64 I get:

python-git not found. Using standard download instead.
Downloading https://github.com/jreinhardt/BOLTS/archive/master.zip
Traceback (most recent call last):
  File "C:\FreeCAD\Mod\AddonManager\AddonManager.py", line 561, in run
    self.download(self.repos[self.idx][1],clonedir)
  File "C:\FreeCAD\Mod\AddonManager\AddonManager.py", line 593, in download
    zfile.write(u.read())
TypeError: unicode argument expected, got 'str'

**Comment by looooo** [comment]
thanks for reporting.
This one is most likely related to io vs StringIO. I will try to revert it for python2.
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/AddonManager/AddonManager.py#L587L593
io.StringIO -> py2, py3 unicode
io.BytesIO -> python2 str, python3 bytes
StringIO.StringIO -> python2 str

**Comment by looooo** [comment]
https://github.com/looooo/FreeCAD/commit/7c8c24db2243236bdaa79bfceb747079790ed5d5

**Pull request closed without merging**
