### PR TITLE
Fix Path Keep View and Sim in Sync,typo Linuxcnc_post

### PR DESCRIPTION
**Pull request by IchGucksLive**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---
The commit is about changes to keep Path Creater View and Simulation View in Sync on viewing 
rapid and feed lines in color  
and adding different Shapes of tools in the CPP file 
also a need of Startcommand without Feedrate to the Post as EMC Linuxcnc  dont like this 
AS a FIX to sliptonics push of my already pushed files

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
@sliptonic or @mlampert either of you mind to have a look? Thanks!

**Comment by mlampert** [comment]
@shaise wanna have a look at the simulator changes?

**Comment by IchGucksLive** [comment]
to make a aprove of function 
Video on YT SIM at 4min timeline https://www.youtube.com/watch?v=o6MPhZLWIsc

**Comment by shaise** [comment]
I'm taking a look now

**Comment by shaise** [comment]
I see that the drill simulation is already merged into master, so I guess the fixes for the code should be ok as well.

**Comment by yorikvanhavre** [comment]
Ok then, thanks for looking! It's merged now

**Comment by shaise** [comment]
It seems the last commits cost some issues:
https://forum.freecadweb.org/viewtopic.php?f=15&t=24422&start=100#p209025
@IchGucksLive, can you check?

**Pull request closed without merging**
