### PR TITLE
StartPage: Add custom CSS option, re-organize preferences and further fixes

### PR DESCRIPTION
**Pull request by qewer33**
The changes made by this PR:
- Re-organize Start WB preferences and add "Custom CSS" option (closes https://github.com/FreeCAD/FreeCAD/issues/10451) + rename preference page widget names to make code more readable

Screenshot_20230903_192913
Screenshot_20230903_192944

- Turn the StartPage "Import" quickstart button into "Open" (uses Std_Open now instead of Std_New & Std_Import)
- Removes the "Hide scrollbars" preference, seems like this was originally added because the scrollbars looked ugly. They're styled according to the theme now and they're thinner so there shouldn't be any reason to keep this
- Minor CSS and HTML fixes

### CODE REVIEW

**Comment by qewer33** [comment]
Not sure why the merge conflicts happened but they should be fixed now, hopefully CI builds fine

**Comment by qewer33** [comment]
Ok I have no idea why the tests are failing. Ran locally on my machine and I get this output:
```
======================================================================
ERROR: test_html_validates (TestStart.TestStartPage.TestStartPage.test_html_validates)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/lib64/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/home/qewer/Desktop/Git/freecad-build/Mod/Start/TestStart/TestStartPage.py", line 144, in test_html_validates
    StartPage.exportTestFile()
  File "/home/qewer/Desktop/Git/freecad-build/Mod/Start/StartPage/StartPage.py", line 665, in exportTestFile
    f.write(handle())
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 22662: ordinal not in range(128)

```
"\xfc" seems to be the letter "ü" which does exist on my keyboard but I couldn't find any instance of it on the StartPage files. I'll investigate further.

**Comment by qewer33** [comment]
Alright neverminds. This should fix it.

**Comment by Syres916** [comment]
Don't ignore that Python 3.11 UnicodeDecodeError, they appear to be popping up in all sorts of places, I believe part of the test is specifically around the author field must be able to save non-ascii characters.

**Comment by chennes** [comment]
Start is now in our pre-commit config -- please install pre-commit to fix up the formatting here. See Item 3 in "Setting Up for Development" here: https://freecad.github.io/DevelopersHandbook/gettingstarted/

**Comment by yorikvanhavre** [comment]
This looks very good and apparently all issues are solved, so I think we can merge!

**Comment by Syres916** [comment]
@yorikvanhavre please see https://forum.freecad.org/viewtopic.php?p=704090#p704090

**Pull request merged**
