### PR TITLE
Add safe mode description to issue template and guide in readme

### PR DESCRIPTION
**Pull request by maxwxyz**
Add safe mode description to issue template and guide in readme.
@chennes FYI, not sure if this needs a backport

### CODE REVIEW

**Comment by luzpaz** [comment]
Note: At some point we will want to examine the config files in order to ascertain the deeper issue that may be causing the bug. So maybe we can ask them to backup their config instead of deleting them, for now? (Until we will automate this process somehow as discussed in https://github.com/FreeCAD/FreeCAD/issues/6106#issuecomment-2423342525

cc @hyarion

**Comment by maxwxyz** [comment]
maybe config file could somehow be copied with about info to GitHub?

**Comment by chennes** [comment]
No need to back port, GitHub doesn't use the branches when you use an Issue template.

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD/blob/2d57e9f2afa1da442a20a3426719055fc4e906a9/README.md?plain=1#L85

Again, just re-iterating that we may want to reconsider using 'delete' config files with 'backing up' config files for the purposes stated above.

**Comment by hyarion** [comment]
@luzpaz btw, should we add safe mode in the release notes too?

**Pull request merged**
