### PR TITLE
correction to TempalteMaterial.yml and importFCMat.py

### PR DESCRIPTION
**Pull request by dietmarczekay**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ x] Branch rebased on latest master `git pull --rebase upstream master`

### CODE REVIEW

**Comment by berndhahnebach** [comment]
What is the unit of this electrcal property? If we would add it as a known quantity to the FreeCAD unit system it could be added as quantity to the yaml template. This would be much more smarter than as a float.

bernd

**Comment by dietmarczekay** [comment]
vacuum permittivity [F / m], relative permittivity is without unit

**Comment by dietmarczekay** [comment]
What's the difference between quantity and float?

**Comment by berndhahnebach** [comment]
a float is just a number. The user has to take care about the unit in all usage in all FreeCAD of this float material parameter. A quantity is know to FreeCAD (the unit of the quantity). If the module you gone use the material parameter in, supports FreeCAD unit system, you do not need to take care of the unit.

**Comment by berndhahnebach** [comment]
Which may lead to the next question, how to make the unit for vacuum permittivity known to FreeCAD unit system. AFAIK you need to add it at least in this files:

- https://github.com/FreeCAD/FreeCAD/blob/master/src/App/FreeCADInit.py
- https://github.com/FreeCAD/FreeCAD/blob/master/src/Base/Unit.h
- https://github.com/FreeCAD/FreeCAD/blob/master/src/Base/Unit.cpp

These commits may help:
- https://github.com/FreeCAD/FreeCAD/commit/0f90e25638e799d034083e0ef8f879f13fddd675
- https://github.com/FreeCAD/FreeCAD/commit/aa67d5636138e0b9196b79cc72130c134d254219

**Comment by berndhahnebach** [comment]
Ahh some unit code (which shows what could be done with a unit in FreeCAD) might be help too ...

https://github.com/FreeCAD/FreeCAD/blob/7c48ad754c6a35f6331f133b27294fdd458bf67d/src/Mod/Material/materialtools/cardutils.py#L775-L785

**Comment by berndhahnebach** [comment]
relative permittivity is like poissons ratio. If it is unit less we do not make in known to FreeCAD unit system, means float is just fine.

**Comment by dietmarczekay** [comment]
Thanks for the explanation. I think, vaccum permittivity is just needed inside Elmer, we can export it to the sif file separately.

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=10&t=38414

**Comment by wwmayer** [comment]
This PR is un-mergable. It shows 393 commits and 766 file changes.

When you make contributions then please create a separate branch and don't make changes directly to the master branch of your repo. Once you opened a PR you can leave the branch as it is because we will rebase it when it's being merged.

**Comment by dietmarczekay** [comment]
The long list here in this thread confuses me a little bit😁 I check this tomorrow and make the pull request again.

**Comment by berndhahnebach** [comment]
> The long list here in this thread confuses me a little bitgrin I check this tomorrow and make the pull request again.

very goo idea ... close this one, make a new PR and reference this PR.

**Pull request closed without merging**
