### PR TITLE
Spreadsheet: fix parens in conditionals

### PR DESCRIPTION
**Pull request by CarlOlson**
I was experimenting with FreeCAD's expression grammar, here are some small changes that I don't think should be controversial. The commits should be clear, but I can squash and rename them to better fit the repo's style (just tell me what is best).

**Notes**
- A single test doesn't pass, but it fails on `master` as well
- Changes to associativity/precedence was done based on warnings and should have no changes in behavior
- A more recent flex/bison was used, but I can rebuild them in any version if needed

<details><summary>Show Failure</summary>
<p>

```
======================================================================
FAIL: test_import_resize (OpenSCADTest.app.test_importCSG.TestImportCSG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/carl/git/FreeCAD/build/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py", line 352, in test_import_resize
    self.assertAlmostEqual (object.Shape.BoundBox.XLength, 2*8.5, 1)
AssertionError: 25.499999999999996 != 17.0 within 1 places (8.499999999999996 difference)

----------------------------------------------------------------------
Ran 565 tests in 49.568s

FAILED (failures=1)
```

</p>
</details>

<details><summary>PR Template</summary>
<p>
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just **fixing small bugs**, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [X]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).
---
</p>
</details>

### CODE REVIEW

**Comment by chennes** [comment]
As noted in the description, that failing test has nothing to do with this PR (I'm working on tracking it down, but I can't reproduce it on any of my systems!). It won't fail on Travis, which doesn't run the OpenSCAD unit tests.

**Comment by CarlOlson** [comment]
> (I'm working on tracking it down, but I can't reproduce it on any of my systems!).

It could be because I've compiled OpenSCAD myself from master. I can investigate this weekend.

**Comment by wwmayer** [comment]
It may take a while before merging this PR because there are few pending PRs that address the expression parser and the spreadsheet module...

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by donovaly** [comment]
@chennes since you merged some spreadsheet code the last weeks, what can be done with this PR?

**Comment by chennes** [comment]
The spreadsheet merge is not yet complete: I am waiting on a PR from @realthunder addressing several of @wwmayer's concerns about the last chunk of merge, then a final rebase, and then I am going to call for assistance reviewing the last commit. After that, I think PR #3062 needs to be handled. Then we can see if this is still relevant.

**Comment by donovaly** [comment]
OK, so apparently this PR won't make it in for 0.20. -> making it a draft and set the 0.21 label

**Comment by adrianinsaval** [comment]
Is this PR still relevant?

**Comment by CarlOlson** [comment]
> Is this PR still relevant?

Probably? But I haven't used FreeCAD much this past year, my workstation is in storage. I'll not be able to work on this for several months, someone else can certainly take over though.

**Comment by luzpaz** [comment]
Why was src/App/ExpressionParser.tab.c removed from App/ ?

**Comment by wwmayer** [comment]
The removed file is srcMod/Spreadsheet/App/ExpressionParser.tab.c and as far as I can see it's not used anywhere. We have a file with the exact name under src/App and which is part of the expression parser.

When looking at the history then some part of the expression engine was part of the Spreadsheet module and then moved to the core system. The file looks like a leftover that has been forgotten.

**Comment by wwmayer** [comment]
Replaced by https://github.com/FreeCAD/FreeCAD/pull/9054

**Pull request closed without merging**
