### PR TITLE
Draft: remove getPlacementFromPoints function

### PR DESCRIPTION
**Pull request by Roy-043**
This somewhat convoluted function was only used by gui_trackers.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
Is this considered a public API? Could it maybe be in use by some macro?

**Comment by Roy-043** [comment]
That is indeed an issue. I have meanwhile found that the BIM WB uses the function. Will convert this to Draft for now.

**Comment by luzpaz** [comment]
CC @yorikvanhavre (BIM WB related)

**Comment by Roy-043** [comment]
The BIM code (BIMBox) that relies on getPlacementFromPoints in WorkingPlane.py still works after this PR. Users that use the dev version will only see a `use_instead` warning.

**Pull request merged**
