### PR TITLE
WIP: Sketcher refactor

### PR DESCRIPTION
**Pull request by vosk**
Rationale:

The sketcher is contained in very few very large files with extreme repetition and copy-pasting.
I propose a gradual and complete rewrite of Mod/Sketcher "hard to read" files, and reduce code size by at least 30%
The goal of the rewrite is to be able to reason about new future additions in a comprehensive way.

Technical Goals:
1) decouple driving code from geometry specific code : points should be handled elsewhere than BSplines etc.
2) Reuse functionality: the umpteenth time I came across `switch( type of geometry)` I nearly lost it. 
3) Make the code dimension-agnostic. The GCS code is 2d, but that can change later.
4) Make code multi-threading ready. Use immutable objects, reduce coupling and transform the handling code into a stream-like pipeline.

Technical Analysis:

Objective 1:

I propose a Filter/Interceptor chain handling of geometry-specific code where needed. I have sketched (pun intended) a solution for **Sketcher.cpp/h.**
Instead of handling each geometry type in a method in a trillion line file, I have specified a `FilterChain` that represents a chain of transformations and operations that need to be applied, described in a `FilterInput` object. The chain allows each filter the option to terminate the chain execution, or to transform the Input into a different one, or to spawn different executions of the chain to handle derived operations: 
inserting a line (should but not yet done) spawns insertion of 2 points. 
Inserting a BSpline knot point transforms the insertion into a `fixed=true` insertion and recuses.
In essence : https://en.wikipedia.org/wiki/Interceptor_pattern

The interceptor pattern accommodates all five of the https://en.wikipedia.org/wiki/SOLID principles with respect to different geometry types.
I have NOT seperated the filters and the chain from the Sketcher file, just to avoid messing everyone's mind that is not used to dependency inverted code. These Filter Objects will be moved into a different file each.
FilterChains would only be generated at specified gather point files (Single responsibility principle) and could be extended with various additions.
Objective 2:
Generate testing code for each and every refactored line.

Objective 3:
Explore options for 3d constraint solving, implement  bspline   to <other geometry> intersections, etc.

### CODE REVIEW

**Comment by luzpaz** [comment]
Hi @vosk. This is quite an ambitious and somewhat invasive change to Sketcher and right before the upcoming release.This type of change needs to be discussed on the forum ([example of discussion](https://forum.freecadweb.org/viewtopic.php?f=10&t=51716&sid=4cb8601fc5010f7ca8a387d8dc3ec727)). It's also very difficult to track this many changes in so few commits. From experience (as an observer) it is bound to be problematic and introduce new bugs. Nevertheless, it's cool that you've undertaken this. Please create a forum thread and link to this PR (a vice-versa) so the subject can be explored in more depth. Thanks!

**Comment by vosk** [comment]
Hi @luzpaz , thank you for your feedback. I would OF COURSE be splitting this into incremental changes here and there, merged individually, I will ask around in the forum for guidance. This PR is just a proposal, it probably would be rejected even if it was complete :100: .

**Comment by davidosterberg** [comment]
As someone who has recently fixed some issues in Sketcher, I must agree with the general premise. The files really are huge, and full of repetition. Sketcher would benefit from a systematic refactoring effort. My doubt is if this "Filter/Interceptor" pattern is the right way. I am a hobby coder, so I am not familiar with this design pattern. 

From what I see when googling, the filter/interceptor pattern seems to be used frequently for web servers. Could you explain why this is the right pattern for Sketcher? Perhaps there are other even more suitable design patterns? Maybe there are stuff all can agree on, and other stuff that will be controversial. I agree with @luzpaz, better discuss on the forum.

**Comment by vosk** [comment]
I do not presume to have the perfect answer! Thank you for your time and perspective. 
I have created: https://forum.freecadweb.org/viewtopic.php?f=10&t=53829

**Pull request closed without merging**
