### PR TITLE
[FEM] make fluid boundary dialog behave like the other dialogs

### PR DESCRIPTION
**Pull request by donovaly**
- allows highlighting and multiple selection

### CODE REVIEW

**Comment by qingfengxia** [comment]
I can do a code review for this PR as the original author, about this weekend.

**Comment by qingfengxia** [comment]
I can do a code review on this bugfixing this weekend. Feb 23

**Comment by berndhahnebach** [comment]
great.

would be good to have your opinion QingFeng.

**Comment by donovaly** [comment]
> I can do a code review on this bugfixing this weekend. Feb 23

Thanks.
For information: I used just the code that is used for the majority of the other FEM constraint dialogs. The only new thing is the procedure TaskFemConstraintFluidBoundary::onButtonDirection because the other dialogs don't have the direction feature.
So if you find issues outside this function, we need to change the other dialogs as well.

**Comment by qingfengxia** [comment]
### code review 

Before this PR,  multiple shapes can be selected, and also can be remove  (right click the listed shape link, in the shortcut menu,  select "delete").
This PR add a "remove button", this has improved the user friendliness. 

On code side,  "onSelectionChange()" is functionally split into 2 functions "addToSelection()" and "removeFromSelection()", or also "setSelection()", this make code a more clear. So this is a higly appreciated refactoring work.  

`updateSelectionUI()` is renamed to `updateUI()`, what is the reason?  `updateUI()` imply it will update all UI elements, but it only updates selection UI.  While, this is not important to me. 

I have compile this branch and manually tested it, it works well. I recommend to be merged.

Thank you for your contribution.

### not quite relavant here 
BTW, recently there are some change, like `App::Part`,  `PartDesign::Body` containner to hold shapes, does that affect our shape selection? I have a quick test, put cube into part container, it does not affect reference selection. but I have not done more tests. 

```cpp
    // we can only handle part objects
    if (TypeName.substr(0, 4).compare(std::string("Part")) != 0) {
        QMessageBox::warning(this, tr("Selection error"), tr("Selected object is not a part!"));
        return;
    }
```

**Comment by donovaly** [comment]
> Before this PR, multiple shapes can be selected, and also can be remove (right click the listed shape link, in the shortcut menu, select "delete").
> This PR add a "remove button", this has improved the user friendliness.

Before the PR you could only select one face/edge and then add. So if you had e.g. 12 more faces to add, this was a lot of work.
Also, once you selceted multiple faces, and select one of them in the dialog list, the selected one was not highlighted in the CAD model. There was no highlighting at all.

However, I just took the existing code that is used for all other FEM constrain. I did this to bring all FEM constraint dialogs to one code level.

Personally, I never dealt with fluids but was annoyed that the Force constraint dialog behave different from all other ones. Later on I realized that there are 2 more dialogs effected: the fluid boundary and the gear constraint. (I'll have a look at the gear dialog soon.)

>     // we can only handle part objects
>     if (TypeName.substr(0, 4).compare(std::string("Part")) != 0) {
>         QMessageBox::warning(this, tr("Selection error"), tr("Selected object is not a part!"));
>         return;

This assures that the user doesn't e.g. select another constraint in the tree view. it works for me well also for PartDesign objects/faces. I mean I can select faces created by PartDesign without problems because a body is a part object.

**Comment by donovaly** [comment]
> `updateSelectionUI()` is renamed to `updateUI()`, what is the reason? `updateUI()` imply it will update all UI elements, but it only updates selection UI. While, this is not important to me.

The only reason is that `updateUI()`, is the name used in the other FEM constraint dialogs.

**Comment by qingfengxia** [comment]
Thank you for elaborating the new feature,  I have one hour before sleeping to briefly go thorough the code.  I may got used to single section so did not appreciate the benefit this mutliple selection at one go at that time.  I love this new feature, it is really useful to deal larger geometry.  Thank you.

And also, is that possible to encapsulate the 2 button and list widget into one FemSelectionWidget, so shared by all other constraint cpp class? As you have done this job, you must know the pro and con, feasibility.

**Comment by donovaly** [comment]
> And also, is that possible to encapsulate the 2 button and list widget into one FemSelectionWidget, so shared by all other constraint cpp class? As you have done this job, you must know the pro and con, feasibility.

I don't know. my aim was to uniform all dialogs in order to improve them at once.
For example Werner now found a general issue with the dialogs: https://forum.freecadweb.org/viewtopic.php?f=18&t=43581
and we can fix this for all dialogs.

**Comment by donovaly** [comment]
I propose to merge the PR. Then all dialogs are in the same state and issues like the Cancel handling can be fixed the next days for all dialogs.

**Pull request merged**
