### PR TITLE
PartDesign: Show me your tip

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
===========================

It generates a small green icon on the treeview for those features being the tip of the body.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by luzpaz** [comment]
I request the git summary to be revised to `PartDesign: Show me your tips`

**Comment by ianrrees** [comment]
Guys, I don't think we should be putting this sort of humour in FreeCAD.  This is about geometry; the commit message should be something like "PartDesign: Highlight tip feature in treeview"

**Comment by abdullahtahiriyo** [comment]
I honestly do not understand what you mean. It is not humour. Do we need fancy commit messages now?

**Comment by abdullahtahiriyo** [comment]
Somebody has explained me why native speakers wanted to change this. Ok, here you have an updated message without subliminal message:
https://github.com/FreeCAD/FreeCAD/pull/1279

**Pull request closed without merging**
