### PR TITLE
stpZ: Import Export support for compressed STEP files '.stpZ'

### PR DESCRIPTION
**Pull request by easyw**
this PR is following this thread:
https://forum.freecadweb.org/viewtopic.php?f=9&t=26535
[Reference documentation for STEP file Compression](https://www.cax-if.org/documents/rec_prac_file_compression_v12.pdf)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I take it that the PSF license that comes with thr gzip_utf8.py file is comaptible with LGPL -https://en.wikipedia.org/wiki/Python_Software_Foundation_License anyone confirms/infirms this?

**Comment by easyw** [comment]
gzip_utf8.py is a slight modified version of gzip.py, already distributed with FC windows build... python in general can be re-licensed as GPL or not...
>  Python Software Foundation License (PSFL) is a BSD-style, permissive free software license which is compatible with the GNU General Public License (GPL).
Unlike the GPL the Python license is not a copyleft license, and allows modified versions to be distributed without source code.

**Comment by wwmayer** [comment]
According to Wikipedia PSF is a BSD-like license (i.e. more permissive than LGPL) and compatible to GPL. If it's compatible to GPL then it's also compatible to LGPL.

**Comment by easyw** [comment]
https://www.gnu.org/licenses/license-compatibility.en.html

**Comment by wwmayer** [comment]
Merged.

**Comment by easyw** [comment]
Hi @wwmayer 
thank you for merging this.
I checked the FC 0.17 release 13188 on Win and OSX and they both are working.
Instead on Ubuntu 16.04, after a 'sudo apt-get install freecad-daily' I get the same release nbr (13188) but I cannot load/export 'stpZ' files.
I went to usr/lib/freecad-daily/Mod/Importer and I cannot find the extra two files (stepz.py and gzip_utf8.py) and the Init.py is as the previous one...
Have I missed something on my commits?
Thanks again for support,
Maurice

**Comment by wwmayer** [comment]
No, I guess that the PPA does not include these changes yet.

**Comment by easyw** [comment]
You are right @wwmayer: now with 13190 everything is fine also on ubuntu.
Thanx a lot!

**Pull request closed without merging**
