### PR TITLE
[Do not merge] Draft edit improved

### PR DESCRIPTION
**Pull request by carlopav**
Tried to bring everithing concerning object handling in methods at the end of the command definition. So for every object type at least two methods are created: setObjectPts and updateObject(v).
Also changed a bit the bezcurve editing methods so now they are more integrated inside the tool.
What do you think about it? I find this useful for further implementations... do you?

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This PR reverts several changes to the translation system I did recently (getting rid of the msg() function)... Can you undo that somehow? Also, your changes are becoming a very "separate" thing, I wonder if it wouldn't be best to separate it from DraftTools and set everything in its own file?

**Comment by carlopav** [comment]
Thanks yorik for reviewing it, It will take time for me to learn :). 
I'm sorry, I didnt realize that. I'll check them and undo it one by one if necessary as soon as I can.
I think the draf edit it's always been quite different from other commands (it's a small monster, with maybe to much customized approach for every object), so no problem for me to separate it from draft tools. I can update the PR and split the tool to a new file, so you can tell me if it's the right way to do it.

**Comment by yorikvanhavre** [comment]
Okay, thanks for the fix. Let's merge this as it is now, then in a next one we can split the Draft Edit tool. I'm actually planning to do that for all other tools too.

Just one little thing for next time if you can, is to try to condensate your changes in less commits, if possible, because they take several pages of git logs :smile: There are several git tools to do that, ( git squash for ex)

**Comment by carlopav** [comment]
Ok, super! thanks for the tips, I'll try git squash. If you have any other suggestion i'll be glad to follow them, since i don't know much about software development. Also I spotted some bugs in the tool in circle and spline editpoint placement that are on my list.

**Pull request closed without merging**
