### PR TITLE
[Icons]Increasing the visibility of technical drawing icons in dark theme fix

### PR DESCRIPTION
**Pull request by Reqrefusion**
Increasing the appearance of the icons in the dark theme, made within the scope of the revision specified by Max. 

Increasing the thickness of the middle lines of the small circles of the TechDraw_ExtensionHoleCircle.svg icon was not done because it covers the circles completely. The great circle is thickened. But I'm not sure about that. I'm waiting for ideas.
Their 24px appearance is as follows:
TechDraw_ExtensionChangeLineAttributes TechDraw_ExtensionCircleCenterLines TechDraw_ExtensionDecreaseDecimal TechDraw_ExtensionHoleCircle TechDraw_ExtensionIncreaseDecimal TechDraw_ExtensionThreadBoltBottom TechDraw_ExtensionThreadBoltSide TechDraw_ExtensionThreadHoleBottom TechDraw_ExtensionThreadHoleSide TechDraw_2LineCenterline TechDraw_2PointCenterline TechDraw_BrokenView TechDraw_ComplexSection TechDraw_DecorateLine TechDraw_FaceCenterLine  TechDraw_SectionView

Having flaws in a fix is ​​a result of being human. I don't believe there is a definitive countermeasure against this.

### CODE REVIEW

**Comment by Reqrefusion** [comment]
Ready to merge.

**Comment by maxwxyz** [comment]
please add a screenshot so we do not need another fix afterwards

**Comment by Reqrefusion** [comment]
@WandererFan Can you merge this too?

**Comment by maxwxyz** [comment]
Could we get an in app screenshot with dark/light theme?

**Pull request merged**
