### PR TITLE
[Sketcher][Bugfix] Slot: fix segfault accessing empty vector

### PR DESCRIPTION
**Pull request by 0penBrain**
Fix segfault introduced in 834ae29ad00b2

### CODE REVIEW

**Comment by 0penBrain** [comment]
@abdullahtahiriyo : may you be lpease be kind to have a look at this ? I'm ashamed right now. :rofl: Thanks

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5212">pipeline status</a> for feature branch [PR_5212](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5212). Pipeline [419732506](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/419732506) was triggered at [6b3b813](https://github.com/FreeCAD/FreeCAD/pull/5212/commits/6b3b813aa47894091749d8ac45ce9da166f00765). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@0penBrain would you mind adopting the 'no whitespace before a colon' convention in your commit names? 
Instead of `[Sketcher][Bugfix] Slot : fix segfault accessing empty vector`  
Please use: `[Sketcher][Bugfix] Slot: fix segfault accessing empty vector`

**Comment by 0penBrain** [comment]
@luzpaz not sure I can think of it anytime as actually I just apply my locale way of doing. ;) What's the rational ?

**Comment by 0penBrain** [comment]
@donovaly @wwmayer : sorry to stress you out on this, but I'm worried about having this segfault issue in the builds. Could you please merge ?

**Comment by 0penBrain** [comment]
Thx @wwmayer

**Comment by luzpaz** [comment]
> @luzpaz not sure I can think of it anytime as actually I just apply my locale way of doing. ;) What's the rational ?

Sorry to sound nit-picky but if you look at the commit list, we use that convention. So basically, 'uniformity' :blush:

**Pull request merged**
