### PR TITLE
[FEM] pipelines: distinguish stresses

### PR DESCRIPTION
**Pull request by donovaly**
- it seems using the same Field name for a vector and a scalar result causes problems with ParaView, see https://forum.freecadweb.org/viewtopic.php?p=601775#p601775
 therefore rename the vectors

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7246">pipeline status</a> for feature branch [PR_7246](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7246). Pipeline [600445268](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600445268) was triggered at [8e04108](https://github.com/FreeCAD/FreeCAD/pull/7246/commits/8e041081560c01a2dd483712ce7352edcc2edb76). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@donovaly I've removed trailing whitespace from one of the files.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7246">pipeline status</a> for feature branch [PR_7246](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7246). Pipeline [601226823](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/601226823) was triggered at [7de77af](https://github.com/FreeCAD/FreeCAD/pull/7246/commits/7de77aff93221b4a0417cdb5f9e66772320929f5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> @donovaly I've removed trailing whitespace from one of the files.

This is not good because a PR has a special purpose. You are free to correct mistakes of the lines a PR edited, but you made a change to code that was not changed by the PR.

Therefore please make a separate PR for changes.

**Comment by luzpaz** [comment]
Sorry, I was hoping that the edits that I made would turn in to suggestions for you to decide to add or not. But github didn't display them that way. Though the edits are minor, are you sure they need a separate PR this time? I'll make edits like this in separate PRs moving forward.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7246">pipeline status</a> for feature branch [PR_7246](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7246). Pipeline [601266279](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/601266279) was triggered at [8e04108](https://github.com/FreeCAD/FreeCAD/pull/7246/commits/8e041081560c01a2dd483712ce7352edcc2edb76). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> Sorry, I was hoping that the edits that I made would turn in to suggestions for you to decide to add or not.

Please make a separate PR in any case. We can make as many PRs as we want. A separate PR means a separate commit and a clean commit history helps us a lot in case of errors, backporting etc.

You change here will for example most probably be lost. I will rebase and then force-push a further change from my repository.

**Comment by luzpaz** [comment]
Yea, i dropped the commit so it's back to how it was.

**Comment by donovaly** [comment]
Merged as it was reported the issue is fixed by the PR: https://forum.freecadweb.org/viewtopic.php?p=619524#p619524

**Pull request merged**
