### PR TITLE
PathDrilling improvements

### PR DESCRIPTION
**Pull request by pekkaroi**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

Overhaul for PathDrilling operation.
-Allow enabling and disabling features to drill
-Add custom locations (edges, faces, vertices) to be drilled

Discussion on forum: https://forum.freecadweb.org/viewtopic.php?f=15&t=22141

### CODE REVIEW

**Comment by sliptonic** [comment]
This looks very good to me.  Only two minor suggestions before merge:

1)Please set the PathLog level back to INFO 

2)Please run a PEP8 filter.    Code generally looks very good but there's some missing whitespaces and extra blank lines.  Don't worry too much about line lengths.

**Comment by sliptonic** [comment]
One more suggestion:  sort_locations() looks like a copy of  the sort_jobs() procedure from PathHelix.py.   It takes a list and returns a sorted list.  I think for maintainability this procedure should be moved into PathUtils.py and removed from both PathDrilling and PathHelix.

**Comment by wwmayer** [comment]
Please not that this branch gives merge conflicts! Part of the problem might be that  9a203be and 587a717 have identical changes.

**Comment by pekkaroi** [comment]
Yes, it seems that most commits appear twice. I think that happened when I rebased my branch to upstream/master and then pushed the change to my fork. Is this something I should not do? How can I remove the duplicate commits? Some of the Travis builds seemed failing, but checking the log I could not figure how that could be related to my changes? Is that some anomaly on the build system?

**Comment by wwmayer** [comment]
> Yes, it seems that most commits appear twice. I think that happened when I rebased my branch to upstream/master and then pushed the change to my fork. Is this something I should not do?

Apparently not. But I am not enough of a git expert to give good advices.

> Some of the Travis builds seemed failing, but checking the log I could not figure how that could be related to my changes?

Only one of the travis build failed because it timed out -- took more than 2 hours. So, don't worry about this.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
