### PR TITLE
TD: cleanup after #5457

### PR DESCRIPTION
**Pull request by luzpaz**
Fix header uniformity  
Fix grammar  
Fix trailing whitespace

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5464">pipeline status</a> for feature branch [PR_5464](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5464). Pipeline [459369083](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/459369083) was triggered at [c89d920](https://github.com/FreeCAD/FreeCAD/pull/5464/commits/c89d92036888f3fd4bf2e421106989155d7fc445). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by benj5378 — APPROVED** [review]

**Comment by luzpaz** [comment]
Note: the specific commit hash for this merge should be appended to https://github.com/FreeCAD/FreeCAD/blob/master/.git-blame-ignore-revs

**Comment by WandererFan** [comment]
> Note: the specific commit hash for this merge should be appended to https://github.com/FreeCAD/FreeCAD/blob/master/.git-blame-ignore-revs

Who is this comment for?

**Comment by WandererFan** [comment]
Thanks for this.  It was on my list.

**Comment by luzpaz** [comment]
@WandererFan that was for chennes. The commit hash `a5135efd879abcfb34868c775f4178124ccd771c` could be added to https://github.com/FreeCAD/FreeCAD/blob/master/.git-blame-ignore-revs now. I'm on mobile so can't do it ATM

**Pull request merged**
