### PR TITLE
cmake changes for conda (because patches are outdated soon :)

### PR DESCRIPTION
**Pull request by looooo**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by looooo** [comment]
does any distro currently use external smesh. Because this diff assumes smesh is from this repo: https://github.com/LaughlinResearch/SMESH

**Comment by looooo** [comment]
else I could add the conda conditional

**Comment by luzpaz** [comment]
https://repology.org/metapackages/?search=smesh&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=

* Arch AUR pulls from salome: https://aur.archlinux.org/packages/salome-smesh
* A bunch of others pull from https://github.com/tpaviot/smesh
* An a few pull from https://sourceforge.net/projects/salomesmesh :cry:

**Comment by looooo** [comment]
And are they used in freecad?

**Comment by looooo** [comment]
@wwmayer @yorikvanhavre Is it possible to merge this until tomorrow? It would help a lot to continue the weekly conda-builds. Otherwise I have to rewrite the patches.

**Comment by looooo** [comment]
thanks

**Comment by wwmayer** [comment]
For my Py3 build on Windows I use the external smesh and using your PR makes CMake configure to fail with the error: CMake error : The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FOUND_LIB
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "MeshPart" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "flatmesh" in directory C:/Projects/FreeCAD-git/src/Mod/MeshPart/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
    linked by target "Fem" in directory C:/Projects/FreeCAD-git/src/Mod/Fem/App
But I don't see an obvious error. So, I guess your changes are wrong.

**Comment by looooo** [comment]
sry, I will revert this part. It seems I have used this only for osx.

**Comment by wwmayer** [comment]
In my SMESHConfig.cmake file I have this line:
set(SMESH_LIBRARIES optimized Driver;debug Driverd;optimized DriverDAT;debug DriverDATd;optimized DriverGMF;debug DriverGMFd;optimized DriverSTL;debug DriverSTLd;optimized DriverUNV;debug DriverUNVd;optimized MEFISTO2;debug MEFISTO2d;optimized SMDS;debug SMDSd;optimized SMESH;debug SMESHd;optimized SMESHBasics;debug SMESHBasicsd;optimized SMESHControls;debug SMESHControlsd;optimized SMESHDS;debug SMESHDSd;optimized SMESHMisc;debug SMESHMiscd;optimized SMESHTrace;debug SMESHTraced;optimized SMESHUtils;debug SMESHUtilsd;optimized StdMeshers;debug StdMeshersd;optimized NETGENPlugin;debug NETGENPlugind)

Now by looping over the list the optimized and debug entries are separated from the actual library names and find_library then of course fails because it cannot find a library called optimized or debug.

On MSVC the optimized & debug entries are very important because it tells the linker which library is used in Release & Debug mode.

**Pull request merged**
