### PR TITLE
Gui: Allow None parameter again in drag and drop methods in Python ViewProviderPy class

### PR DESCRIPTION
**Pull request by marioalexis84**
@donovaly separate pull request acording to https://forum.freecad.org/viewtopic.php?p=625495&sid=fbd133d17eb6673b7df62527a4054cfb#p625495
Pull request related: https://github.com/FreeCAD/FreeCAD/pull/7236

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7507">pipeline status</a> for feature branch [PR_7507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7507). Pipeline [643111783](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/643111783) was triggered at [a53a256](https://github.com/FreeCAD/FreeCAD/pull/7507/commits/a53a2564879770b33fa6a45336883e78dda5c6d6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks! I will merge after I could merge #7236

**Comment by donovaly** [comment]
Wait, this PR is for master. In https://forum.freecad.org/viewtopic.php?p=625495&sid=61fd6b73f879d0636baa47506e4a0cf6#p625495 I requested a PR for the 0-20 branch.

To avoid confusions, can you please make ONE PR for master fixing the bug. If necessary please make a second PR for further improvements. First when the changes are merged into master, we can take care for the backporting.

**Comment by marioalexis84** [comment]
@donovaly pull request changed to FreeCAD-0-20.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7507">pipeline status</a> for feature branch [PR_7507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7507). Pipeline [645562980](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/645562980) was triggered at [600a644](https://github.com/FreeCAD/FreeCAD/pull/7507/commits/600a644af3a8f0850e12c99d7e9accb50f936c78). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
