### PR TITLE
Releases/free cad 0 18

### PR DESCRIPTION
**Pull request by AlexandrParkhomenko**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---
if the headers in the your working directory, you use "",
if the headers in the system path or inside the your include path you should use <>.
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf#page=182

REPLACE #include <((App|Base|Gui|Main|Mod)/.*?\.h)> TO #include "" THAT FIND IN SOURCE FOLDER FIRST
https://github.com/AlexandrParkhomenko/FreeCAD/commit/016dd7d9d0958424a4296594c05eaebdc8650886

DELETE /// Here the FreeCAD includes sorted by Base,App,Gui......
https://github.com/AlexandrParkhomenko/FreeCAD/commit/2b241e181370245f38a1a0b0e69fe88d546fe42a

### CODE REVIEW

**Comment by AlexandrParkhomenko** [comment]
correct please if somewhere it is not right

**Comment by luzpaz** [comment]
This PR has way too many changes in it at once. IMO it should be split up. Please open a forum thread to discuss your thought process and proposal with theae fixes. Also, note that we are in the middle of a very large code review regarding #2350

Nevertheless, thank you for your contribution!

**Comment by luzpaz** [comment]
Also learn about the difference between `git rebase` instead of `git merge`

**Comment by sgrogan** [comment]
@AlexandrParkhomenko 
Please post on the forum what you are trying to do.
The from in the pull request is FreeCAD/FreeCAD:releases/FreeCAD-0-18
So your trying to merge FreeCAD's release branch into FreeCAD's master.
If you notice you have no commits yourself in this pull request.

I think it safe to close this. A new PR would be better than trying to fix this IMHO.

**Comment by yorikvanhavre** [comment]
I don't understand either what this PR tries to achieve @AlexandrParkhomenko ?

The only commits added to 0.18 nowadays are commits that were added to master first, and that were judged important enough to be backported to 0.18. Unless someone did something wrong, there is nothing in 0.18 that doesn't exist in master too. However, the commit hashes are different because they get rebased when going to 0.18, which can give the impression there is different content. It can also screw git a lot :laughing:

If you see something that has been added to 0.18 that isn't present in master, that is definitely an error, and please notify us or explain what it is, and indeed it needs to be fixed. In the meantime I'm going to close this PR to avoid having someone mistakenly push the button :) Please reopen if needed

**Pull request closed without merging**
