### PR TITLE
Issue 3299

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
A rather simple one:

https://forum.freecadweb.org/viewtopic.php?f=3&t=26139&start=20#p211466

https://freecadweb.org/tracker/view.php?id=3299

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
This PR causes a crash in CmdSketcherConstrainTangent::activated(int)

**Comment by abdullahtahiriyo** [comment]
@wwmayer 

Yup!! It worked perfectly in my example... only in it...

pushed a fix...

**Comment by wwmayer** [comment]
The crash is not resolved. Now the assert in isInVirtualSpace() fails. This must be caused by updating the ConstraintItem which internally still has the old constraint number and thus makes the assert to fail.

**Comment by wwmayer** [comment]
Merged.

It appeared that the new crash is not caused by this PR but #1167. So no need to hold back this one.

**Pull request closed without merging**
