### PR TITLE
add new constraints to FEM

### PR DESCRIPTION
**Pull request by berndhahnebach**
see topic:
http://forum.freecadweb.org/viewtopic.php?f=18&t=16749

@werner or yorik
commit https://github.com/berndhahnebach/FreeCAD_bhb/commit/cf4e097b608e638858c768c8d3da0e1a2de5b5f0 adds code to the unit system. Would you check this commit explicit. All other commits are in FEM module

### CODE REVIEW

**Comment by wwmayer** [comment]
Merged.

**Comment by wwmayer** [comment]
ThermalExpansionCoefficient:
Is it normal to have a length unit in the numerator and denominator? You should not write 'u' but '\xC2\xB5' if you mean "mu".

**Comment by berndhahnebach** [comment]
@werner:
would you point me to the code?

**Comment by wwmayer** [comment]
Don't worry I will fix this quickly since I'm doing some code cleanup.

However, about the "factor" in the schemaTranslate method are you sure they are correct? I have to admit that I don't fully understand the logic behind but when comparing with other dimensions I would have expected a different factor here and there.

**Comment by wwmayer** [comment]
`
App.Units.parseQuantity('1000000 W/m/K').UserString
App.Units.parseQuantity("W/mm/K").UserString
App.Units.parseQuantity('1000 W/m/K').UserString
App.Units.parseQuantity("W/mm/K").UserString
App.Units.parseQuantity("0.1 W/mm/K").UserString
App.Units.parseQuantity("0.1 W/m/K").UserString
App.Units.parseQuantity("mm/mm/K").UserString
App.Units.parseQuantity("m/mm/K").UserString
App.Units.parseQuantity("m/m/K").UserString
App.Units.parseQuantity("0.001 m/m/K").UserString
App.Units.parseQuantity("0.001 mm/m/K").UserString
App.Units.parseQuantity("J/kg/K").UserString
App.Units.parseQuantity("W/m^2/K").UserString
`
I found a nice way to test your code and everything looks correct.

**Comment by wwmayer** [comment]
Hm, apparently the numbers are correct but I still don't see that the logic fits. In the internal scheme (everything is in mm, kg, s) we have for the density kg/cm^3 the factor 0.001 which I can follow because kg/cm^3 = kg/(10mm)^3 = 0.001 kg/mm^3, hence the factor 0.001.

However, for W/m/K = W/(m*K) = W/(1000 mm * K) = 0.001 W/(mm * K) I would expect 0.001 but the factor is 1000. But why?

**Comment by wwmayer** [comment]
Ahh, now I got it: one has to also express the W with the base units (m, kg, s) which is kg*m^2/s^3 so that W/m/K becomes kg*m/s^3/K = 1000 kg*mm/s^3/K

Sorry for the self-conservation :D

**Pull request closed without merging**
