### PR TITLE
Fixes:  CAM ToolBit Library NOT always saved #15284

### PR DESCRIPTION
**Pull request by spanner888**
Added calls to librarySave() after Add New/Existing and Delete.

Not sure if this is best approach as adds extra write overhead to Lib file, but could not work out how to sub-class dialog close button. Suspect not possible when using Uic load of the ui file.

Tests of Add New/Existing and delete, all showed Library saved if close dialog via the X, as well as via Close button.

### CODE REVIEW

**Comment by luzpaz** [comment]
@spanner888 thanks for the PR. Can you revise the git commit title and body

Screenshot_20240902_174650

Here's what I propose: 

```shell
git commit --amend -m "CAM: calls to librarySave() after Add New/Existing and Delete of Toolbits" -m "Fixes #15284"
git push --force
```

**Comment by spanner888** [comment]
@luzpaz  I did the ```git commit --amend -m ```.

But the ```git push --force``` says: 
```
fatal: The current branch ToolBitEditor_NotSave has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin ToolBitEditor_NotSave

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.
```
I was under impression I would have no rights to upstream, so wonder if the above suggestion is correct.

Happy to take your recommendation. Also happy for advice on getting it correct next time.

**Comment by luzpaz** [comment]
@spanner888 the recommendation (`git push --set-upstream origin ToolBitEditor_NotSave`) is correct. What is confusing you here is the word 'upstream' and that makes sense because it has a few meanings. upstream can be the main upstream remote git repo that you forked from (freecad/freecad in this case), and it is also used to refer to where do you want to push your changes to remotely (in this case it is to your "origin" fork:branch `spanner888:ToolBitEditor_NotSave`. This will make better sense when you invoke `git remote -v` and you'll see upstream and origin remotes and their respective addresses.

```
git push --set-upstream origin ToolBitEditor_NotSave
git push --force
```

**Comment by sliptonic** [comment]
@spanner888  Will you rebase this and push again?  Also reword the commit per @luzpaz's comment.  
This is failing on one CI check but we think it's related to a problem that has been solved.  I'll merge as soon as it passes CI.

Thanks for the contribution

**Comment by spanner888** [comment]
I did the rewording and updated that commit and also rebased, but git was not happy. So I updated my fork and pulled that and tried a few more times, but no success.

Is it easier to delete this PR and get everything up to date on my end and do a new properly titled PR?

**Comment by luzpaz** [comment]
@spanner888 not necessary, a merge dev can also do it for you.

**Comment by spanner888** [comment]
@luzpaz thanks and go ahead.

Thanks also yor all of your patience, will try hard do much better in future

**Comment by luzpaz** [comment]
930r4a

**Pull request merged**
