### PR TITLE
Path: Feature/external thread milling

### PR DESCRIPTION
**Pull request by mlampert**
This PR adds external threads to the thread milling operation and fixes some issues.
Lead in/out is de-selected by default, it probably isn't as useful as one thinks it is. 
There is now a notion of an `elevator` which is the position used for moving the tool to the other end of the thread in case of a multi-pass path. The elevator is rather close to the thread so the tool doesn't have to be moved to the center and back all the time (for internal threads).
Multi pass is now adaptive, each pass removes the same amount of material from the thread.
The thread tables are split into the different tolerance classes to make it easier to select the appropriate thread.
Generator function split out with additional unit tests.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6485">pipeline status</a> for feature branch [PR_6485](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6485). Pipeline [481534666](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/481534666) was triggered at [aaf58a8](https://github.com/FreeCAD/FreeCAD/pull/6485/commits/aaf58a836e93d049e1b0c36cb95703168de2ab37). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6485">pipeline status</a> for feature branch [PR_6485](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6485). Pipeline [481535217](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/481535217) was triggered at [3abf9ce](https://github.com/FreeCAD/FreeCAD/pull/6485/commits/3abf9ce0cdb69f6b56913710060a6cb52ca31c78). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
JIC reminder for merge dev, please try and squash trivial commits and also prepend `[Path]` or `Path:` to the commit summaries. It helps the doc writers immensely. Thank you in advance!

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6485">pipeline status</a> for feature branch [PR_6485](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6485). Pipeline [483331491](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/483331491) was triggered at [ae20eff](https://github.com/FreeCAD/FreeCAD/pull/6485/commits/ae20eff8e7111583087a364d22d163e69a775a9b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
