### PR TITLE
[WIP] Doxygen: Base/Parameter.h description

### PR DESCRIPTION
**Pull request by luzpaz**
Adding a cursory description for these 2 files.  
This is a pretty rudimentary description but at least it's a start.  
@vocx-fc do you mind reviewing?

### CODE REVIEW

**Comment by vocx-fc** [comment]
It's fine, but in general you don't add the documentation to the `.cpp` file, only to the header `.h` file. Why? Because the header file defines the public interface of the classes and functions. So, in general, just by looking at the header file, and reading its documentation, an external programmer should understand "how it works". The `.cpp` file defines the implementation details, what goes inside the functions, and this is not important for other programmers.

* Doxygen comments, [FaceMaker.h](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/FaceMaker.h)
* No Doxygen comments, [FaceMaker.cpp](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/App/FaceMaker.cpp)

The implementation `.cpp`, still has some comments inside with `/* */` or `//`, but these aren't meant to be picked up by Doxygen, so they don't define a "documentation block" with `/** */` or `///`.

**Comment by yorikvanhavre** [comment]
Agree with @vocx-fc 
You mind transferring the doc block to the h file @luzpaz ? So we set the sail straight from the start.

**Comment by luzpaz** [comment]
@vocx-fc Done. It's not as technical as the other comments. Feel free to spruce it up if you see fit. Thanks again for the explanation, I found that very useful.

**Comment by yorikvanhavre** [comment]
Thanks!

**Pull request merged**
