### PR TITLE
clang-format set column limit

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

Current column limit = 0 (no limit).

Proposal: 80 characters (industry standard). Affects wrapping.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7409">pipeline status</a> for feature branch [PR_7409](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7409). Pipeline [624857828](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/624857828) was triggered at [9f6acc5](https://github.com/FreeCAD/FreeCAD/pull/7409/commits/9f6acc59e744a920f2b19d334708b915cb95a7fd). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
For reference, Black (the Python formatter) wraps at 88 chars, and claims a fairly significant line reduction over 80. My recollection is that our PyLint warns over 100 chars.

**Comment by berniev** [comment]
I'd be happy with 100

**Comment by chennes** [comment]
I'd swear that last time I looked at this PR it was a one-line change to the clang-format file. Now GitHub is showing a hundred modified lines in CommandView.cpp -- is GitHub just messing with me?

**Comment by berniev** [comment]
WTF? How is that possible? Forced a clean commit.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7409">pipeline status</a> for feature branch [PR_7409](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7409). Pipeline [640375520](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/640375520) was triggered at [bf30e68](https://github.com/FreeCAD/FreeCAD/pull/7409/commits/bf30e68a2dac385132adcf84a1c4e8605e9c61bc). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
No idea, that was really strange. I'm going to merge now before anything else goes sideways...

**Pull request merged**
