### PR TITLE
Remove obsolete cmake

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berniev** [comment]
The ${CMAKE_VERSION} VERSION_LESS "3.12" ELSE code (not altered) seems to overrule all before it in this file. Is this intended? Am I missing something?

**Comment by chennes** [comment]
It was my understanding that 
```
find_package(Python3 COMPONENTS Interpreter Development REQUIRED)
```
should have basically taken care of all the stuff the custom Homebrew/Macports stuff was doing originally. If I recall correctly, on my Homebrew system I was able to just drop the whole top block once I had a new enough cMake, but that was a while ago. I can re-test that later today or tomorrow.

**Comment by berniev** [comment]
Is working well for me too.

But I am wondering how to specify which python when there could be several Home brew installed, one or more in venv, one or more not in venv, plus system.

**Comment by chennes** [comment]
I guess the same way as in other cMake stuff, in Python's case by manually setting `PYTHON_EXECUTABLE` and `PYTHON_LIBRARY` within cMake. At least, as I look at the cMake cache file on my Mac, that appears to be what I've done there (where I have several versions of Python). My Windows cache doesn't have those set, so presumably I had some reason for doing so on the Mac.

**Comment by berniev** [comment]
I have those set too, because the earlier code spits the dummy.

**Comment by berniev** [comment]
I cannot see how/if setting those affects the way find_package operates. Any clues?

**Comment by berniev** [comment]
Anyhow... I think this PR is safe to merge.  I'll do another removing the other code and the discussion can move there?

**Comment by berniev** [comment]
In case I forget I'll just mention that further discussion will also impact src/MacAppBundle/CmakeLists.txt

**Comment by chennes** [comment]
I think git is just cranky about the changed Python version -- can you please resolve the conflict?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8254">pipeline status</a> for feature branch [PR_8254](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8254). Pipeline [761019274](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761019274) was triggered at [094e31e](https://github.com/FreeCAD/FreeCAD/pull/8254/commits/094e31e0d89dee587e52b6a5fc51e072c6299612). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8254">pipeline status</a> for feature branch [PR_8254](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8254). Pipeline [761032897](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761032897) was triggered at [7b5e312](https://github.com/FreeCAD/FreeCAD/pull/8254/commits/7b5e312c07c2b84852999bef5b211a77caafec04). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
