### PR TITLE
[Gui] Fix 100% CPU usage due to StartView

### PR DESCRIPTION
**Pull request by benj5378**

### CODE REVIEW

**Comment by benj5378** [comment]
@wwmayer, https://github.com/FreeCAD/FreeCAD/pull/17376#issuecomment-2442546384 :
> This looks like a serious regression:
> 
> * Pre-selection of the top buttons works very unreliably
> * It's extremely slow
> * One core of the processor is at 100% as long as the start page is open

@benj5378, https://github.com/FreeCAD/FreeCAD/pull/17376#issuecomment-2442969242 :
> I will have a look at this tomorrow. Wondering why it's not an issue here though
> 
> https://github.com/FreeCAD/FreeCAD/blob/ef2156d0f6d116b1642a5531a2d44fc6b7d17042/src/Mod/Start/Gui/FileCardDelegate.cpp#L85-L88

It don't think it was using `paintEvent` itself, that caused the issue. I believe it was `setStyleSheet` that recursively called `paintEvent`.

**Comment by hyarion** [comment]
is it possible to rerun the mac CI? it timed out during the tests

**Comment by yorikvanhavre** [comment]
Will give it a test spin tomorrow

**Comment by hyarion** [comment]
@yorikvanhavre have had the time to test this? There are multiple users reporting performance issues

**Comment by yorikvanhavre** [comment]
On it right now :)

**Comment by yorikvanhavre** [comment]
backported

**Comment by Roy-043** [comment]
@yorikvanhavre AFAICT this has not been backported yet.

**Comment by hyarion** [comment]
@Roy-043 Good catch!

**Comment by chennes** [comment]
I'm sure what happened, but I've got it now. Thanks for the catch @Roy-043 .

**Pull request merged**
