### PR TITLE
Draft: re-organization of Draft Edit code

### PR DESCRIPTION
**Pull request by vocx-fc**
* The edit module is moved to another module, `gui_edit`.
* Update the unit tests so they pass.

This pull request needs to be merged after #3096 is merged so that the new files are correctly included in the variables in `CMakeLists.txt`. When this happens, this request will create a conflict, so this pull request will have to be rebased onto the master branch, and then it will be able to be merged.

Since this request touches `DraftEdit.py`, it will cause a conflict with #3023.

Depending on which pull request is merged first, one or the other will have to be rebased to solve the conflicts.

Forum thread: [[Discussion] Splitting Draft tools into their own modules](https://forum.freecadweb.org/viewtopic.php?f=23&t=38593&start=40#p370895).

---

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by vocx-fc** [comment]
@carlopav heads up, your beloved `Draft_Edit` has been moved to `gui_edit`.

**Comment by carlopav** [comment]
@vocx-fc this is a great news!
I'd just like to change one or two things :D

**Comment by carlopav** [comment]
ok, there are some more cleanup commits from you, perhaps better to wait also them to be merged before modifying it. :)

**Comment by vocx-fc** [comment]
Yes, the big one on the queue #3082 touches several files to correct a few things of style and PEP8 compliance. After that one, the following pull requests aren't too invasive and focus more on specific files.

**Pull request merged**
