### PR TITLE
Private shape

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
This pull request changes `TopoShape::_Shape` to a private member variable, and adds access functions `TopoShape::getShape` and `TopoShape::setShape`. Most of the changes are trivial, switching to the use of the access functions rather than direct access to `TopoShape::_Shape`. The following are non-trivial changes:

1. `Part/App/Attacher.cpp:784` the original array took the address of `TopoShape::_Shape`, I have now created a copy of the `_Shape` and added that to the array
2. `PropertyPartShape::getValue` returns a `const TopoDS_Shape&`, which means I cannot return the private `TopoShape::_Shape`. Instead, I have added `PropertyPartShape::OCCShape` as a member variable, and I'm returning that instead

### CODE REVIEW

**Comment by ickby** [comment]
Seems not all Workbenches have been ported, Raytracing fails in Travis :)
Also please consider to squash th ecommits a bit and give them better messages, having multiple "More conversions." does not make for an expressive commit history.

**Comment by ezzieyguywuf** [comment]
Just saw the failure on the travisi-ci, I'll go through and update this branch for the RayTracing workbench.

**Comment by ezzieyguywuf** [comment]
@ickby how do I squash the multiple commits into one?

**Comment by ezzieyguywuf** [comment]
@ickby went ahead and squashed the things and fixed the errors, travis is passing now.

**Comment by ezzieyguywuf** [comment]
Rebased to current master, it seems a pull request was recently merged.

**Comment by ezzieyguywuf** [comment]
Rebased again.

**Comment by wwmayer** [comment]
Are you sure you rebased the branch or did you rather merge master back into this branch? From the history it looks like the latter. If so, this should be avoided because it complicates the merging.
At least I got merge conflict but not sure if it's because of this or that I had to skip one of your commits.

"TopoDS_Shape getShape() const" is actually wrong because at several places a const reference is hold when accessing the TopoDS_Shape and this may cause problems when now a copy is
returned. If it returns a const reference instead, you can everywhere blindly replace the "_Shape" with "getShape/setShape" -- unless where a non-const reference is used.
Especially this ugly hack in PropertyTopoShape becomes obsolete.

Also, it makes sense to declare the getShape/setShape functions inline so that the compiler can make it as efficient as it was before when the member was public.

> Part/App/Attacher.cpp:784 the original array took the address of TopoShape::_Shape, I have now created a copy of the _Shape and added that to the array

That was wrong because you created a local copy and set its address into the array. As soon as the function is left the array keeps a dangling pointer. With getShape returning a const reference, however,  this is not problem at all.

**Comment by ezzieyguywuf** [comment]
@wwmayer At first I was rebasing, but then I noticed the "Update branch" feature on github and thought I'd use that instead. Moving forward I'll continue rebasing rather than using the "Update branch" feature, which merges master into my branch.

If a `const TopoDS_Shape&` is being held, I don't see why it matters wether `getShape` returns a copy or a reference. I wanted to be sure that no one was modifynig `TopoShape::_Shape` without using `seShape`, but your point is a valid one: as long as the caller is holding a `const` reference, this should not be a problem. **NOTE:**, however, that there are a few places in the code where a non-const reference is held. I don't know if this is by design or just an oversight. In those cases, I've changed the functions to hold a copy, make their changes, and then use `setShape` at the end of the function.

I'll go ahead and change `getShape` to return a `const` reference, and I'll also make `getShape` and `setShape` `inline` functions. Thanks for the feedback.

**Comment by wwmayer** [comment]
I have already made the changes and merged your branch as a single commit. Due to the merge conflicts I had to redo most of your changes.

There are a few places where a non-const reference was used and it was intentional because further down the shape has been modified. I replaced this by making a copy, change it and assign to the TopoShape afterwards.

**Comment by ezzieyguywuf** [comment]
:-\ ok, sorry bout the trouble.

**Comment by wwmayer** [comment]
No problem :)

**Pull request closed without merging**
