### PR TITLE
[For 0.19] Add a move base property that moves the base object instead of the object itself is true

### PR DESCRIPTION
**Pull request by Moult**
From this discussion:

https://forum.freecadweb.org/viewtopic.php?f=23&t=33580

This is useful because it is the default case for most architectural work.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by paullee0** [comment]
First time using this feature of Github :)

See discussion post:-

https://forum.freecadweb.org/viewtopic.php?f=23&t=33580&p=285486#p285486

**Comment by Moult** [comment]
Warning added - instead of a popup it shows as a console warning and a statusline warning (which may prompt them to open the console so that they can see the full list of warnings). Popups really break the workflow IMO, so we'll see how it goes. Maybe we need a better status line in the future. Kinda like how Blender does it - no popups dialogs in Blender :)

**Comment by yorikvanhavre** [comment]
I've been hindering the feature freeze of 0.18 too much lately by committing many new features, and it's time to be more rigorous about it, otherwise the release will never happen, so I'll keep this for after the release okay?

**Comment by Moult** [comment]
Sounds good :) Looking forward to the 0.18 release!

**Comment by paullee0** [comment]
:) Looking forward to 0.19_pre for yours works.

**Pull request merged**
