### PR TITLE
Material: important FIX, choosing material in FEM is broken ATM

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by berndhahnebach** [comment]
added commits from https://github.com/FreeCAD/FreeCAD/pull/1983

**Comment by donovaly** [comment]
> added commits from #1983

Hmm, in https://github.com/FreeCAD/FreeCAD/pull/1982/commits/d5400eb893e643d403c9a46f5da4ff8e68506bbb
you "stole" my copyright in my new cards ;-) 
 "(c) 2019 Bernd Hahnebach (CC-BY 3.0)"

It should be 
"(c) 2019 Uwe Stöhr (CC-BY 3.0)"

**Comment by berndhahnebach** [comment]
> 
> 
> > added commits from #1983
> 
> Hmm, in [d5400eb](https://github.com/FreeCAD/FreeCAD/commit/d5400eb893e643d403c9a46f5da4ff8e68506bbb)
> you "stole" my copyright in my new cards ;-)
> "(c) 2019 Bernd Hahnebach (CC-BY 3.0)"
> 
> It should be
> "(c) 2019 Uwe Stöhr (CC-BY 3.0)"

changed, hopefully FreeCAD will not be angry with the ö

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
