### PR TITLE
fix codespell warnings

### PR DESCRIPTION
**Pull request by sliptonic**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7599">pipeline status</a> for feature branch [PR_7599](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7599). Pipeline [665027193](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/665027193) was triggered at [126c8a4](https://github.com/FreeCAD/FreeCAD/pull/7599/commits/126c8a48db32d7b1a8e3d1f7c683cd57e84fe781). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7599">pipeline status</a> for feature branch [PR_7599](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7599). Pipeline [666298698](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/666298698) was triggered at [cdc3e54](https://github.com/FreeCAD/FreeCAD/pull/7599/commits/cdc3e5466fc5aebe4ba2260f8cc0bca9fa6a38b2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Can this go in? If yes, I assume this should be backported, right?

**Comment by sliptonic** [comment]
I haven't merged any PRs lately.  I'm wondering why the gitlab ci isn't completing.
I doubt any PRs after #7440 are candidates for backporting.  That PR radically rearranged the Path codebase.

**Comment by donovaly** [comment]
> I haven't merged any PRs lately. I'm wondering why the gitlab ci isn't completing.

The first CI completed and this is stated also in GitHub: https://github.com/FreeCAD/FreeCAD/actions/runs/3245017006/jobs/5321977786
For the second CI we have a display issue. It succeeded as well but to see this one must manualy have a look here: https://gitlab.com/freecad/FreeCAD-CI/-/pipelines

> I doubt any PRs after #7440 are candidates for backporting. That PR radically rearranged the Path codebase.

OK.

**Pull request merged**
