### PR TITLE
[NaviCube] Make customizable the rotation step increment

### PR DESCRIPTION
**Pull request by 0penBrain**
- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [X] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0` **=> Tests failed for other reason than this PR. Made a complete functional test & basic functional non-regression as no particular risk**
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

And please remember to update the Wiki with the features added or changed once this PR is merged. **=> I'll do as soon as PR is merged ([Fine-tuning](https://www.freecadweb.org/wiki/Fine-tuning))**

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Great! One might want to add a control to the preferences pages too.
In the meantime, please update https://www.freecadweb.org/wiki/Fine-tuning

**Comment by 0penBrain** [comment]
@yorikvanhavre : Unfortunately I'm not so familiar with how to add preferences but I can try it when I'll have a bit more time. ;)
Wiki updated (as said in the PR description). ;)
Thx for merging.

**Comment by yorikvanhavre** [comment]
Basically:

1. Install qtdesigner and build the qtdesigner FreeCAD extension as https://www.freecadweb.org/wiki/Compile_on_Linux/Unix#Qt_designer_plugin
2. Locate the desired place in the preferences where you want to add a new control
3. Locate the corresponding .ui file in src/Gui
4. Edit the file in qtdesigner, add your own control, make sure the name matches what you used in this PR (FreeCAD pref controls have 2 extra fields at the bottom)
5. Edit the corresponding .cpp file and add your new control to it

That's it! But no worries, adding it to the documentation is fine for now

**Comment by 0penBrain** [comment]
I had a look at the code. Will be easier done by just hacking the files. ;) Coming soon

**Comment by 0penBrain** [comment]
PR #2923 fixes a bug introduced in this PR and adds the newly introduced parameter in preference dialog. ;)

**Pull request merged**
