### PR TITLE
Fem: Fix deprecated import style

### PR DESCRIPTION
**Pull request by je-cook**
With freecad installed through conda when running pytest on my project I get this warning on test collection:
`<frozen importlib._bootstrap>:1047: ImportWarning: FemMigrateApp.find_spec() not found; falling back to find_module()`

I have implemented the same workflow that is done in the importlib module and renamed `find_module` to `find_spec` (https://github.com/python/cpython/blob/35c799d79177b962ddace2fa068101465570a29a/Lib/importlib/_bootstrap.py#L1047)

This should have no end user effect as it is the same as what happens internally. I also in the second commit ran black on the resulting files although it seems these two files are not yet included in the pre-commit. If you want me to remove that let me know.

Thanks!

### CODE REVIEW

**Comment by FEA-eng** [comment]
@marioalexis84 FYI

**Comment by chennes** [comment]
@je-cook thanks for the PR, sorry for the delay on triggering the CI, it's running now.

**Comment by je-cook** [comment]
Thanks @chennes, I dont really understand the `Windows/Build` failure when the conda version passes without error.  I've just rebased to see if that helps.

I've had a look through the tests and I can't see anything that jumps out. The failure is an Access Violation:
image

As I mention in my original message this should have no effect as we would hit the try here:
https://github.com/python/cpython/blob/3.11/Lib/importlib/_bootstrap.py#L1069-L1078

whereas before we would hit the exception and then the below (which is essentially the change made):
https://github.com/python/cpython/blob/3.11/Lib/importlib/_bootstrap.py#L1044-L1051

The links here are to py3.11 tag but it exists the same in py3.10 although with slightly different line numbers

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD/pull/14362#issuecomment-2137859196

ping @marioalexis84

**Review by marioalexis84 — APPROVED** [review]

**Pull request merged**
