### PR TITLE
FEM: Allow assigning materials to compounds to avoid having to assign the same material by hand to all subsolids

### LINKED ISSUE #17561: FEM: Cannot assign material to a compound
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The typical workflow for Material assignment in FEM requires to create a material, open its Task, then repeatedly click "Add" and click on a solid in the part that is part of the mesh (typically a sub-solid of a BoleanFragments operation)

depending on the type of shape and how much it is intersecting, this process needs to be repeated possibly hundreds of times, and if part topology changes, it all has to be repeated.

This is unnecessary, when BooleanFragments are created in standard mode, the resulting part is a compound with sub-compounds that correspond to all shapes that were originally part of one of the constituents. It would therefore be sufficient to assign the material to one of these sub-compounds.

This can be done by Assigning "BooleanFragments.SubShape1" or similar to the Material References . to select the sub-compound of the compound that makes the mesh

however meshtools.py in FEM does not like compounds and will abort with an error like:

```
17:06:32    ElementDimension: 3
17:06:32    Group meshing for analysis is set to true in FEM General Preferences. Are you really sure about this? You could run into trouble!
17:06:32    Empty reference: MaterialSolid
17:06:32  Compound is not supported.
17:06:32  Problem: For the geometry of the following shape was no Shape found: <Compound object at 0x563bb82c7750>
17:06:32      MaterialSolid002
17:06:32      [(<Part::PartFeature>, ('SubShape3',))]
17:06:32      Compound009
17:06:32  This should not happen, please debug!
17:06:32  Unexpected error when creating mesh: list index out of range
17:06:32  Gmsh had warnings:
17:06:32  list index out of range
```

this is easy to fix - all that needs to be done is iterate over all solids in the compound.

### Full version info

```shell
current main - 2024-10-29
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AIRCAP**
fix #17561

only tested with MeshGroups so far

probably needs retesting once #17427 is fixed <-- edit: retested, done, works

### CODE REVIEW

**Comment by FEA-eng** [comment]
@marioalexis84 FYI

**Comment by AIRCAP** [comment]
I tested that with #17575 applied - works both with and without meshgroups and has the same result :-)))

**Comment by chennes** [comment]
Still waiting on @marioalexis84 's review.

**Comment by FEA-eng** [comment]
Looks good if this is what you want to be able to do:

[Compound mat mesh.FCStd.zip](https://github.com/user-attachments/files/17623003/Compound.mat.mesh.FCStd.zip)

I just hope it doesn't introduce any regressions but it looks pretty safe.

**Review by marioalexis84 — APPROVED** [review]

**Comment by AIRCAP** [comment]
ping @chennes  
@FEA-eng  - more like 
[Compound.mat.mesh.FCStd.txt](https://github.com/user-attachments/files/17635422/Compound.mat.mesh.FCStd.txt)
the whole mesh being a compound isn't a big issue since if theres only one Material, it will be treated as the default material anyway, but if you assign a material to a subset of the mesh - and that subset happens to be a compound, then this becomes useful (previously you needed to assign to each and every solid, in the example it's two, but if you do boolean compounds with intersecting grid-sructures, it can be 100s )

**Comment by chennes** [comment]
Backported

**Pull request merged**
