### PR TITLE
Tests: add unit tests for Matrix4D and Rotation

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by chennes** [comment]
@0penBrain clang-tidy is giving garbage results here: looking at its run I see 
```
 Error while trying to load a compilation database:
Could not auto-detect compilation database from directory "build/"
No compilation database found in /home/runner/work/FreeCAD/FreeCAD/build/ or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
```
Any idea what those errors are about?

**Comment by 0penBrain** [comment]
@chennes I know almost nothing about all that. But this is very interesting information.
I found a page letting me think that Clang tools will better work if Cmake is run on the folder.
This indeed is not the case in the CI currently, and I guess it was the case before because the CI was a single job.

Maybe that explains all problems. I will try that in the CI and see if it improves. ;)

**Comment by 0penBrain** [comment]
Re-running the checks to see if remarks made by @chennes are solved with new CI

**Comment by 0penBrain** [comment]
OK, it's useless because it uses the CI as it was at time of PR. :)
@wwmayer, may you please update your repo master then force push this branch (one used for this PR) to your repo so I can have a check ? Thx

**Comment by 0penBrain** [comment]
Thx @wwmayer 
@chennes Does that look better : https://github.com/FreeCAD/FreeCAD/actions/runs/4269666366/jobs/7432989501 ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8584">pipeline status</a> for feature branch [PR_8584](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8584). Pipeline [788809157](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/788809157) was triggered at [6661c4d](https://github.com/FreeCAD/FreeCAD/pull/8584/commits/6661c4d38eee78e4fe4f7b9c12104ce285273463). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8584">pipeline status</a> for feature branch [PR_8584](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8584). Pipeline [788835900](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/788835900) was triggered at [06a0a1e](https://github.com/FreeCAD/FreeCAD/pull/8584/commits/06a0a1efa60fb5510a9f2ab486865f9853824a63). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Beautiful, thanks!

**Pull request merged**
