### PR TITLE
[Path] Fix for inactive ramp dressup base operation

### PR DESCRIPTION
**Pull request by Russ4262**
This PR has two commits.
- The first fixes the issue.  It adds a `Base.Active` check to determine if the Base is Active.  If the Base is Inactive, the new code sets the `obj.Path` property to the same inactive message used in PathOp module and the `execution()` method returns immediately, stopping further execution.
- The second is purely a Black code formatting application, which makes the PR much larger than the actual fix.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by troyp76** [comment]
@Russ4262 
Might be an obvious question as I am just getting into this but I just wanted to confirm that "Black Code formatting application" refers to https://black.readthedocs.io/en/stable/ and if so is this an automatic GitHub action that has been applied to this PR? 

The "active" change itself seems ok from a code review. 
Would it help to progress the PR if I "approve" it?

**Comment by Russ4262** [comment]
> ... and if so is this an automatic GitHub action that has been applied to this PR?
> 
> The "active" change itself seems ok from a code review.
> Would it help to progress the PR if I "approve" it?

Yes, the Black code formatting is via the Black you referenced so far as I know.  I use VS Code on Windows 10.  I followed some install/enable instructions found on the web.  The procedure applied appears to function correctly, as best I can tell.  One of the FC project managers, Sliptonic, suggested I start to use it as a means to sync with his leadership in the Path WB.  If I need to change something to apply Black correctly, or in a preferred manner, please let me know.  I am not a programmer by trade.

In regard to your question of approval, my perspective is rather raw.  I mean no disrespect to anyone reading this, but I have little awareness of the hierarchy of devs involved in the project.  I say this because I do not know who knows what, who trusts who's FreeCAD/programming skills, and who has influence with whom in the big picture.  ((I do mean this in a nice, straight-forward manner, as I am one of the littler fish in this vast FreeCAD ocean.))  So, that said, I would say, sure, if you would like to approve, I will gladly accept the review and input!  Thanks!

I am thankful to be a part of this project, and enjoying the experience.  I am also glad to have others getting involved.  Welcome!

**Comment by troyp76** [comment]
Thanks for the explanation, Given the large number of PR's that you have done to Path I assumed you were one of the big FC fish! 

I have not used the ramp dressup yet, but when I get a chance I will apply this change and give it a test drive then report back here.

**Review by troyp76 — APPROVED** [review]
tested and worked as expected.

**Comment by berndhahnebach** [comment]
would you rebase to get it run by CI?

**Comment by Russ4262** [comment]
@berndhahnebach 
Rebase complete.  Is Travis CI back online for this project?  Or is the rebase for GitLab?  Should I rebase my other active (non-draft) PRs?

Thanks.

**Comment by berndhahnebach** [comment]
would you rebase the PR to make it run on CI?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by Russ4262** [comment]
Rebased.

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5009

pipeline:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/376670187

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Pull request merged**
