### PR TITLE
Path Simulator: A workaround of the bug while milling curves with small radius

### PR DESCRIPTION
**Pull request by belov-oleg**
Path Simulator produces out of trace artifacts while milling curves with small radius.
In VolSim.cpp the branch for curve radius smaller then tool radius is not implemented yet.
In this condition the simulator produces artifacts of higher radius while milling path using G2 or G3.
There is an implementation of G2 and G3 in python level. The proposed patch can be applied without recompilation of the core.

### CODE REVIEW

**Comment by sliptonic** [comment]
Nice improvement!  Thanks for this.  The PR is showing a merge conflict.  Can you please resolve that and force-push?  Thanks.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5329">pipeline status</a> for feature branch [PR_5329](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5329). Pipeline [443700923](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/443700923) was triggered at [cd7cf1b](https://github.com/FreeCAD/FreeCAD/pull/5329/commits/cd7cf1b712f9f43af3eeb141e041768c8d6a410c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5329">pipeline status</a> for feature branch [PR_5329](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5329). Pipeline [443882260](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/443882260) was triggered at [d556a38](https://github.com/FreeCAD/FreeCAD/pull/5329/commits/d556a387528f71a484458a970ad6468327cdd47c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5329">pipeline status</a> for feature branch [PR_5329](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5329). Pipeline [443915608](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/443915608) was triggered at [a81dedc](https://github.com/FreeCAD/FreeCAD/pull/5329/commits/a81dedc79176b97c5dbb5da644060c9f30ac2d97). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
