### PR TITLE
FEM: femmesh: fix AttributeError: module 'numpy' has no attribute 'int'

### PR DESCRIPTION
**Pull request by looooo**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by looooo** [comment]
this should be back ported to 0.20.2 @donovaly

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8092">pipeline status</a> for feature branch [PR_8092](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8092). Pipeline [732479544](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/732479544) was triggered at [88a39c1](https://github.com/FreeCAD/FreeCAD/pull/8092/commits/88a39c1c44632be6287a8f95b3cbf15cb5120719). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
merged

**Comment by donovaly** [comment]
> this should be back ported to 0.20.2 @donovaly

Done.
However, I am wondering you get errors in code that hasn't changed. The code you stumbled upon is in since April 2021.

**Pull request merged**
