### PR TITLE
Add Docker configuration for conda.

### PR DESCRIPTION
**Pull request by Pesc0**

### CODE REVIEW

**Comment by adrianinsaval** [comment]
what's the idea behind using docker here? isn't conda something that doesn't interfere with the system anyways?

**Comment by Pesc0** [comment]
@adrianinsaval someone on discord was trying to build with docker, but the configurations were all outdated. Jacob kindly provided a conda configuration

**Comment by luzpaz** [comment]
@Pesc0 any volunteers to update https://wiki.freecad.org/Compile_on_Docker ?

**Comment by Pesc0** [comment]
I dont know how docker works, 
I dont know if we should support docker at all since we're moving to conda

I dont know how to update the wiki, i dont know if that documentation should be moved to developers handbook directly

**Pull request merged**
