### PR TITLE
Github: Automatically run codespell on modified files in a pull request

### PR DESCRIPTION
**Pull request by Floriansimmer**
This GitHub Actions runs codespell over all modified files in an PR.
The workflow will trigger on all changes in the PR.

Any error will be annotated in the Files changed tab.

Bildschirmfoto von 2022-01-01 17-21-53

All words in the file `.github/codespellignore` are ignored by codespell. File must contain one word per line. Words are case sensitive based on how they are written in the dictionary file (mostly lowercase).

For more information, see: https://github.com/codespell-project/actions-codespell

It can be tested in my Github Repo https://github.com/Floriansimmer/FreeCAD

### CODE REVIEW

**Comment by luzpaz** [comment]
Thanks for doing this!
Feedback:
You can see the args i pass to codespell here:

`git log | grep codespell | head -n1`

returns:

```bash
codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,bottome,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childrens,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,inout,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,ontop,orgin,orginx,orginy,ot,pard,parm,parms,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/Mod/Robot/App/kdl_cp,./src/Mod/Import/App/SCL,./src/WindowsInstaller,./src/Doc/FreeCAD.uml,./build/doc/SourceDocu
```

**Comment by chennes** [comment]
Is there a way to test this without merging it?

**Comment by Floriansimmer** [comment]
Yes make a pull request in my github repo

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5314">pipeline status</a> for feature branch [PR_5314](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5314). Pipeline [439855200](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/439855200) was triggered at [3e89abe](https://github.com/FreeCAD/FreeCAD/pull/5314/commits/3e89abeda7b5f97acfe74c693499a4cc961d8567). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Floriansimmer** [comment]
@luzpaz added all your words to the ignored words.

**Comment by luzpaz** [comment]
@Floriansimmer  This looks awesome! 
Is there a way for the bot to pull the latest upstream `dictionary.txt` file as described in https://github.com/codespell-project/codespell#updating-the-dictionaries ?

**Comment by Floriansimmer** [comment]
Not yet, for that functionality I have to make changes at https://github.com/codespell-project/actions-codespell to use the --dictionary parameter. I will try it tomorrow.

**Review by luzpaz — APPROVED** [review]

**Comment by luzpaz** [comment]
@Floriansimmer Thanks! But I don't think that feature should be a merge blocker. Devs, lets merge this as it is?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5314">pipeline status</a> for feature branch [PR_5314](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5314). Pipeline [439975720](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/439975720) was triggered at [4d9be94](https://github.com/FreeCAD/FreeCAD/pull/5314/commits/4d9be941ea10334345d6c996282a029f5c24c1f8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
I think this is worth a go. If something goes sideways it is easy enough to roll back. Thanks for setting this up @Floriansimmer .

**Comment by wwmayer** [comment]
@Floriansimmer is it possible to mark a word to be ignored by the spell checker. In PR https://github.com/FreeCAD/FreeCAD/pull/5323 there is a comment: // radx and rady 
Now the spell checker wants rady to become: ready

**Comment by Floriansimmer** [comment]
See #5325 
Just add the word to the file ./github/codespellignore

**Comment by chennes** [comment]
@Floriansimmer do you know if it's possible to get code spell to ignore anything that looks like camel case? It looks like nearly all of the false-positives on the current trunk are things that would be ignored if anything with a capital letter in the middle was ignored (or something less naive, like split into components and spellchecked individually, whatever).

**Comment by Floriansimmer** [comment]
@chennes I don't think this is possible without changing the codespell source code.Codespell is very simple, it only compares if a misspelled word is in the dictionary file.
I am currently preparing a pr that will add many words that have been incorrectly detected to the codespellignorelist. Furthermore I will also ignore *.svg, there are also many false positives coming from it.

**Comment by luzpaz** [comment]
@Floriansimmer can you also have a look at https://tracker.freecadweb.org/view.php?id=3206 ?

**Comment by Floriansimmer** [comment]
@luzpaz i'm working on it 😄 
Bildschirmfoto von 2022-01-23 16-04-45

**Comment by luzpaz** [comment]
@Floriansimmer we're also thinking about tomorrow's migration from our Mantis Bugtracker to github. We will probably need to have a housecleaning bot that checks if users have posted their full [About](https://wiki.freecad.org/About) info, if they opened a forum thread to discuss the issue first before opening a ticket, and a way for devs to override the bot checks if needed. Maybe we can coordinate efforts in a thread on the forum ?

**Pull request merged**
