### PR TITLE
Path: adds chamfer op to experimental features.

### PR DESCRIPTION
**Pull request by mlampert**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
There are some error in the path tests... check the travis log..

```
======================================================================
FAIL: test00 (PathTests.TestPathOpTools.TestPathOpTools)
Check that face orientation has anything to do with the wire orientation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Path/PathTests/TestPathOpTools.py", line 97, in test00
    self.assertCoincide(Vector(0, 0, -1), f.Surface.Axis)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 44, in assertCoincide
    self.assertRoughly(pt1.z, pt2.z)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 38, in assertRoughly
    self.assertTrue(math.fabs(f1 - f2) < error, "%f != %f" % (f1, f2))
AssertionError: -1.000000 != 1.000000

======================================================================
FAIL: test10 (PathTests.TestPathOpTools.TestPathOpTools)
Check offsetting hole wire succeeds.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Path/PathTests/TestPathOpTools.py", line 207, in test10
    self.assertLines(wire.Edges, False, [Vector(0, 4, 0), Vector(x, -2, 0), Vector(-x, -2, 0), Vector(0, 4, 0)])
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 67, in assertLines
    self.assertLine(edges[i], points[i], points[i+1])
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 57, in assertLine
    self.assertCoincide(pt2, edge.valueAt(edge.LastParameter))
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 42, in assertCoincide
    self.assertRoughly(pt1.x, pt2.x)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 38, in assertRoughly
    self.assertTrue(math.fabs(f1 - f2) < error, "%f != %f" % (f1, f2))
AssertionError: 3.464102 != -3.464102

======================================================================
FAIL: test12 (PathTests.TestPathOpTools.TestPathOpTools)
Check offsetting a body wire succeeds.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Path/PathTests/TestPathOpTools.py", line 261, in test12
    self.assertCoincide(Vector(0, 0, -1), f.Surface.Axis)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 44, in assertCoincide
    self.assertRoughly(pt1.z, pt2.z)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 38, in assertRoughly
    self.assertTrue(math.fabs(f1 - f2) < error, "%f != %f" % (f1, f2))
AssertionError: -1.000000 != 1.000000

======================================================================
FAIL: test28 (PathTests.TestPathOpTools.TestPathOpTools)
Check offsetting a shape hole.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Path/PathTests/TestPathOpTools.py", line 455, in test28
    self.assertCoincide(Vector(0, 0, -1), e.Curve.Axis)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 44, in assertCoincide
    self.assertRoughly(pt1.z, pt2.z)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 38, in assertRoughly
    self.assertTrue(math.fabs(f1 - f2) < error, "%f != %f" % (f1, f2))
AssertionError: -1.000000 != 1.000000

======================================================================
FAIL: test32 (PathTests.TestPathOpTools.TestPathOpTools)
Check offsetting multiple outside edges.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Path/PathTests/TestPathOpTools.py", line 555, in test32
    self.assertCoincide(Vector(-x, y, 0), wire.Edges[0].Vertexes[0].Point)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 42, in assertCoincide
    self.assertRoughly(pt1.x, pt2.x)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 38, in assertRoughly
    self.assertTrue(math.fabs(f1 - f2) < error, "%f != %f" % (f1, f2))
AssertionError: -19.052559 != 19.052559

======================================================================
FAIL: test33 (PathTests.TestPathOpTools.TestPathOpTools)
Check offsetting multiple backwards outside edges.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Path/PathTests/TestPathOpTools.py", line 607, in test33
    self.assertCoincide(Vector(+x, y, 0), wire.Edges[0].Vertexes[0].Point)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 42, in assertCoincide
    self.assertRoughly(pt1.x, pt2.x)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 38, in assertRoughly
    self.assertTrue(math.fabs(f1 - f2) < error, "%f != %f" % (f1, f2))
AssertionError: 19.052559 != -19.052559

======================================================================
FAIL: test36 (PathTests.TestPathOpTools.TestPathOpTools)
Check offsetting multiple inside edges.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Path/PathTests/TestPathOpTools.py", line 702, in test36
    self.assertCoincide(Vector(+x, y, 0), wire.Edges[0].Vertexes[0].Point)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 42, in assertCoincide
    self.assertRoughly(pt1.x, pt2.x)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 38, in assertRoughly
    self.assertTrue(math.fabs(f1 - f2) < error, "%f != %f" % (f1, f2))
AssertionError: 6.928203 != -6.928203

======================================================================
FAIL: test37 (PathTests.TestPathOpTools.TestPathOpTools)
Check offsetting multiple backwards inside edges.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Path/PathTests/TestPathOpTools.py", line 745, in test37
    self.assertCoincide(Vector(-x, y, 0), wire.Edges[0].Vertexes[0].Point)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 42, in assertCoincide
    self.assertRoughly(pt1.x, pt2.x)
  File "/usr/local/Mod/Path/PathTests/PathTestUtils.py", line 38, in assertRoughly
    self.assertTrue(math.fabs(f1 - f2) < error, "%f != %f" % (f1, f2))
AssertionError: -6.928203 != 6.928203
```

**Comment by mlampert** [comment]
Will check it out tonight, thanks for the ping. I'm glad I added that very first sanity unit test, if that one fails all the other ones have to fail. Seems to be different behaviour depending on OCC version.

**Comment by mlampert** [comment]
Closing this for now, needs more work.

**Comment by mlampert** [comment]
I don't think the mac os build failure is related to this changeset. Fixed all other issues.

**Comment by yorikvanhavre** [comment]
ok thansk for the rework! It's merged.

**Comment by mlampert** [comment]
This turned out to be a good thing - there are significant differences between python and occ that would have caused us a lot of pain in the field. The algorithm is a lot more stable now regardless of which way occ orients an edge and how the python version handles collections. Learned a lot1

**Pull request closed without merging**
