### PR TITLE
Fixes for Calculix input files and spreadsheet tables

### PR DESCRIPTION
**Pull request by ulrich1a**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ yes] Branch rebased on latest master `git pull --rebase upstream master`
- [ no] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ yes] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ nearly] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by ulrich1a** [comment]
More precise real values fixes an issue reported here: https://forum.freecadweb.org/viewtopic.php?f=18&t=21571&sid=640af8ca62494c2465d2c5665ccf0358&start=10#p168148

The other is a fix for issue#0002978

**Comment by luzpaz** [comment]
FYI, @ulrich1a https://freecadweb.org/wiki/tracker#Remotely_resolving_a_ticket 
In the git commit I think you need to have a **#** in front of the issue number:
`fixes #0002978`
for it to trigger the regex and for the commit to be associated with the mantis ticket.

**Comment by berndhahnebach** [comment]
@ulrich1a, I'm on the way and can not test, I wonder why the unit tedt does not fail. If we gone write more precison the inp file should be different, should it not ?!?

bernd

**Comment by yorikvanhavre** [comment]
@ulrich1a Silly remark, but could you also change the PR title to something more meaningful than "Pullrequest"? ;) So when we look back at the history we know what it is. Thanks!

**Comment by ulrich1a** [comment]
@luzpaz I am learning still doing pull request. I will remember it the next time. I already put a link manually in a note of the issue.
@yorikvanhavre Will do better next time.
@berndhahnebach The FEM unit tests seem to be broken. It is not possible to write inp-files with the test cases.

**Comment by bblacey** [comment]
@ulrich1a - you can easily update a push request including changing the commit message with `git commit --amend`.  If you want to try and learn, simply do the following:

When the editor opens, change the commit message to your liking.  FYI, you can also use `git commit --amend` to modify files in the commit if you do a `git add <file>` after you have edited <file> and before you use `git commit --amend`.  

To update your pull request, you push your branch with force update because amending a commit changes the git history and requires a force-update on GitHub.

So, in this case, if you simply wanted to modify the commit message to add the Mantis id, do the following

```
# Switch to the branch for your pull request
git checkout pullrequest

# Amend the last commit
git commit --amend
<Edit the commit message to add the mantis id and exit the editor with save>

# It is also good to update your branch with any changes from master before pushing to GitHub (makes merging by the repo managers easier)
git pull --rebase upstream master

# Update Github with the changes to your local branch
git push -f origin pullrequest
```

At this point, if you check your pull request on GitHub, you will see your changes.

**Comment by berndhahnebach** [comment]
The FEM Commit works great. 

BTW: unit test work great too. Inp files are generated :-) unit test does not fail because zeros are not written to input file. Thus the higher precision does not change the unit test input file. 

Ahh I normally add an FEM: to the commit message.

bernd

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
