### PR TITLE
Add PropertyXLinkList, refactored DlgPropertyLink

### PR DESCRIPTION
**Pull request by realthunder**
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=17&t=43060

This PR added new external linking property PropertyXLinkList (in request from [here](https://forum.freecadweb.org/viewtopic.php?p=361271#p361271)).

And in order for the new property to be editable from property view, DlgPropertyLink is refactored to support all major types of link properties.

### CODE REVIEW

**Comment by WandererFan** [comment]
DO NOT MERGE!  this has an error in TaskRichAnno.cpp.    Need to remove commit 2c0d39f45e.

**Comment by realthunder** [comment]
Fixed. The commit is necessary to avoid qt4 build error.

**Comment by WandererFan** [comment]
Fix has already be applied to master - TaskRichAnno 212-216.  
This one is superfluous.

**Comment by realthunder** [comment]
I see. Fix removed.

**Comment by WandererFan** [comment]
This looks good to me.

**Comment by WandererFan** [comment]
11 hours later and Travis hasn't started!!

**Pull request merged**
