### PR TITLE
Update Fem_ru.ts

### PR DESCRIPTION
**Pull request by PushKK**
Fix error in Russian translate "Fixed".

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
Translations are managed via a 3rd party service called [Crowdin](https://crowdin.com/project/freecad). In order to submit translations, you need to request permission to join the RU translation team. In other words, we won't merge translations via PR. Thank you for your understanding and we hope you decide to continue volunteering.

**Comment by vocx-fc** [comment]
Is there an official policy about this? I don't see why somebody shouldn't be able to make small corrections like this. That's equivalent to what you normally do, fixing spelling mistakes everywhere on the source code. Doing big translations should definitely be done in Crowdin but fixing Zakfiksirovano, to Zafiksirovano doesn't seem like a big issue.

**Comment by luzpaz** [comment]
> I don't see why somebody shouldn't be able to make small corrections like this.

@vocx-fc, the simple reason is that any update if not done a specific way will get overwritten by the next crowdin import.

**Comment by wwmayer** [comment]
Merged & changed on Crowdin

**Pull request closed without merging**
