### PR TITLE
refuse to create partdesign objects if no active body in document

### PR DESCRIPTION
**Pull request by usakhelo**
One more try to fix the bug http://freecadweb.org/tracker/view.php?id=2533
Fixes following commands: Add/Sub. Lofts, Add./Sub. Pipes, Pad/Pocket, Revolution/Groove

### CODE REVIEW

**Comment by usakhelo** [comment]
Ahh, I think I've just got last comment in previous attempt - to remove the workflow query... Sorry, I have to fix it.

**Comment by ickby** [comment]
Hello, 

still not there yet. To abort without body in every circumstance is only valid for loft, pipe and primitives, as those two have not been available in 0.16. hence they are not part of the legacy workflow.  However, Pad/Pocket and Revolution/Grove have been available in 0.16. Hence they need to also work in legacy workflow. If a user opens a 0.16 file in 0.17 he should be able to still work like he did before. For those operations it makes sense to check if the old workflow is used and still ork when no body is available in old workflow.

**Comment by usakhelo** [comment]
Got it. I've made PD sketches and pads in 0.16 and opened it in 0.17. Now pads/pockets and revolve/groove are able to start and are added to the root of the tree.

**Comment by ickby** [comment]
Yes thats it, thanks for adjusting. The pullrequest seems fine now and builds on travis. Normal procedure now is to make a thread in the forums pull request section and link to this PR on github.

**Comment by usakhelo** [comment]
Thank you ickby!
I've made PR topic http://forum.freecadweb.org/viewtopic.php?f=17&t=16568 and I've rebased this branch on updated master. Hope this is proper way to do it..

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
