### PR TITLE
Add support for exporting part mesh to JSON

### PR DESCRIPTION
**Pull request by jcoffland**
This adds support for writing objects mesh data to JSON.  It allows for easy access to FreeCAD models from **many** programming languages.  The format is as follows:

```
{
  "version": "0.0.1",
  "description": "Mesh data exported from FreeCAD",
  "objects": [
    {
      "name": "<object name>",
      "description": "<object description>",
      "color": "<object color>",
      "wires": [[[<float>, <float>, <float>], . . .], . . .],
      "vertices": [[<float>, <float>, <float>], . . .],
      "normals": [[<float>, <float>, <float>], . . .],
      "facets": [[<int>, <int>, <int>], . . .]
    }, . . .
  ]
}
```

This could be expanded to included more relevant data.

### CODE REVIEW

**Comment by luzpaz** [comment]
Step closer to https://freecadweb.org/tracker/view.php?id=1558

**Comment by yorikvanhavre** [comment]
Great addition! Would you mind updating the wiki with a small desciption/explanation page?

**Comment by yorikvanhavre** [comment]
merged

**Comment by jcoffland** [comment]
That's awesome.  Thanks!

I'd be happy to add something to the wiki but I've got to say it's not at all easy to figure out how to create an account.  Or maybe I'm missing something obvious.  Can you give me some guidance?

**Comment by ianrrees** [comment]
@jcoffland - The usual way is via https://forum.freecadweb.org/viewtopic.php?f=21&t=6830 however @yorikvanhavre sets up accounts :).

**Comment by yorikvanhavre** [comment]
Do you have an account on the forum already @jcoffland? That's the easiest way, so I just use the same user on the wiki...

**Comment by luzpaz** [comment]
@jcoffland please also mention on the wiki a list of other elements this exporter could be expanded for. Thanks!

**Comment by jcoffland** [comment]
Yes, I'm on the forum.  User name ``jcoffland``.

Re: other elements that could be exported.  I'm not familiar with the FreeCAD internal data structures so I don't really know what the options are here.  I may have included more if I knew what was available.  Basically, I was having a lot of trouble finding an output format that was easy to parse from C++.  I looked at STEP but it is way too complicated and other formats like IGES don't have all the info I needed.  I noticed that the WebGL output contained all the data I wanted so I used the WebGL output plugging as a template for creating the JSON plugging.

**Comment by jcoffland** [comment]
Done: https://www.freecadweb.org/wiki/Arch_JSON

**Pull request closed without merging**
