### PR TITLE
Arch: Replace Drawing functions with TechDraw functions

### PR DESCRIPTION
**Pull request by marioalexis84**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@marioalexis84 There is also a mention in the the `src/Mod/Material` directory  
https://github.com/luzpaz/FreeCAD/blob/973eb27d7ebafabbaa04b1f45094aba61d4b9bf0/src/Mod/Material/MaterialEditor.py#L450-L457

**Comment by adrianinsaval** [comment]
> @marioalexis84 There is also a mention in the the `src/Mod/Material` directory https://github.com/luzpaz/FreeCAD/blob/973eb27d7ebafabbaa04b1f45094aba61d4b9bf0/src/Mod/Material/MaterialEditor.py#L450-L457

it's commented out, so it isn't even being used.

**Comment by luzpaz** [comment]
...but in your opinion, not worth migrating to TechDraw syntax ?

**Comment by adrianinsaval** [comment]
don't know but doesn't seem like it, first off, does that code block work if you uncomment it? Presumably since it's commented out and I know of no report of it causing issues it is not called anywhere so what's the point anyway (what's the point of it being there to begin with?). Then is there a techdraw equivalent for that? wandererfan mentioned he created equivalents for the projection functions, I don't know if there is an equivalent for this patterning one.

**Comment by marioalexis84** [comment]
>There is also a mention in the the `src/Mod/Material` 

Leaving aside the fact that the code is commented out, I didn't find an equivalent for `DrawingPatterns` in `TechDraw`.
That method was commented out in this commit: 195c530c002e7365c88aa

**Comment by WandererFan** [comment]
I've never heard of DrawingPatterns.  We could move the file to TechDraw
directory if it is the last bit of Drawing that is still in use.

**Comment by adrianinsaval** [comment]
It's not in use since 2018, it should be safe to remove that if desired

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6420">pipeline status</a> for feature branch [PR_6420](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6420). Pipeline [476344467](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/476344467) was triggered at [aec0ae2](https://github.com/FreeCAD/FreeCAD/pull/6420/commits/aec0ae2d39bf59aaf9c860ed458a5420b4fa7511). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Ok looks good!
The DrawingPatterns module was indeed an attempt, but has never really been used anywhere. I'll have a better look but Ithink it can safely be discarded everywhere

**Review by yorikvanhavre — APPROVED** [review]

**Pull request merged**
