### PR TITLE
[Gui] Overlay hide mode improve contrast in both themes...

### LINKED ISSUE #15602: Dark theme: Low contrast and no selection indicator in auto hide menu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The dark icons are almost impossible to see over the dark background. Also, there is no indication of which of the options is currently selected while the menu is open. It took me a while to figure it out that it is a single selection and not a "bitmask" with a toggle for each of those options.

Screenshot 2024-07-24 at 21 28 12

### Full version info

```shell
OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Syres916**
...and ensure selected mode stands out from the deactivated modes.

Fixes #15602

OverlayModeLight

OverlayModeDark

### CODE REVIEW

**Comment by MisterMakerNL** [comment]
Impressive work so quickly!

**Comment by chennes** [comment]
@kadet1090 is going to look at refactoring some of that code duplication.

**Comment by obelisk79** [comment]
I was literally just trying to override those icons via stylesheets last night. This would certainly save a lot of frustration on my end as a theme developer.

**Comment by chennes** [comment]
Still leaving this for @kadet1090 for a little while longer.

**Pull request merged**
