### PR TITLE
Update icons for legibility and consistency

### PR DESCRIPTION
**Pull request by maxwxyz**
Slight update of some icons for better legibility and consistency (follow current artwork guidelines).

Example: Redo icon has currently not a good contrast in grayed out and active state:
image
image

### CODE REVIEW

**Comment by Reqrefusion** [comment]
Must have changes, congratulations.

**Comment by MisterMakerNL** [comment]
QT grabs these from a secret stash that is hidden in the depths of your computer.

**Comment by FEA-eng** [comment]
Nice icon enhancements as always. But maybe the Undo and Redo icons could be highlighted even more? What about a different color like blue? Yellow is less conspicuous.

**Comment by maxwxyz** [comment]
I've kept the colors as is. Refresh is blue already and right next to it.

**Comment by Reqrefusion** [comment]
It would be much better if you resize the icons here according to the keyline.

**Comment by FEA-eng** [comment]
> I've kept the colors as is. Refresh is blue already and right next to it.

It doesn't have to be blue. Maybe green, orange or other well-visible shade. Just to make those important icons stand out more.

**Comment by chennes** [comment]
I'm going to merge as-is, since this is an improvement. If there are other changes to be made please submit a new PR. Thanks!

**Pull request merged**
