### PR TITLE
[Arch] Added Linecut function in arch/ArchCutPlane

### PR DESCRIPTION
**Pull request by JeromeL63**

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This looks perfect, thanks!
Just a small detail: The Part module is very heavy to load. It's the central part of FreeCAD and it pushes all of OpenCasCade. So we try to avoid importing it at the top of the file, as it makes FreeCAD much slower to start. Instead, we import it only inside the functions where it is used. That way, the whole file can be imported at FreeCAD startup without triggering Part import.
Can you do that change? Otherwise I'll do it.

**Comment by JeromeL63** [comment]
Erf, I don't know how to and what to import selective ! I'll show your import and I'll try to learn  :'(
just another thing, I didn't modify the .qrc to add icon !

**Comment by yorikvanhavre** [comment]
Ok I merged this now, as it doesn't "harm" the rest of FreeCAD. Let's see what is missing...

**Comment by JeromeL63** [comment]
You rock's ! 
I've saw what changes you make, I understand. I'll do that in futur PR

**Comment by vocx-fc** [comment]
For reference, the original thread was this [draft layer separate line and shape color override](https://forum.freecadweb.org/viewtopic.php?t=40966). A first attempt was #2726.

**Pull request merged**
