### PR TITLE
Sketcher: fixes #13999

### LINKED ISSUE #13999: Sketcher segfaults when using the symmetry tool
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Uncompress and open attached file 
2. Double click on the `Sketch` sketch on the tree view
3. In the `Tasks` panel, under `Elements`, select the last four lines (`50-Line`, `51-Line`, `52-Line`, `53-Line`)
4. Click on the Sketcher symmetry command (`Sketcher_Symmetry`) on the toolbar
5. Move the mouse so as to position the selected lines on the right hand side of their original position, using the vertical construction line (`49-Line`) as the axis of symmetry
6. When the desired position is achieved, click Enter to confirm the operation
7. Expected: symmetry operation is applied
8. Actual: segmentation fault, FreeCAD crashes and exits

[Symmetry segfault.webm](https://github.com/FreeCAD/FreeCAD/assets/148809153/7cf841b9-d298-4344-8677-70550476322f)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37303 (Git) Snap 1019
Build type: Release
Branch: main
Hash: 869cb1f83b5f92ee134dafde46c9c5e0dceb8889
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.4.20
  * BIM 2021.12.0
  * Curves 0.6.35
  * ezydxf
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.4.16.01
```

### Subproject(s) affected?

Sketcher

### Anything else?

[File to reproduce](https://github.com/FreeCAD/FreeCAD/files/15303452/windows_front_bug.zip)

Segmentation fault

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f4dc37e8520]
#1  0x7f4d81380675 in non-virtual thunk to SketcherGui::DrawSketchControllableHandler<SketcherGui::DrawSketchDefaultWidgetController<SketcherGui::DrawSketchHandlerSymmetry, SketcherGui::StateMachines::OneSeekEnd, 0, SketcherGui::OnViewParameters<0>, SketcherGui::WidgetParameters<0>, SketcherGui::WidgetCheckboxes<2>, SketcherGui::WidgetComboboxes<0>, SketcherGui::ConstructionMethods::DefaultConstructionMethod, false> >::onModeChanged() from /snap/freecad/1015/usr/lib/SketcherGui.so+0x75
#2  0x7f4d8135b572 in SketcherGui::DrawSketchControllableHandler<SketcherGui::DrawSketchDefaultWidgetController<SketcherGui::DrawSketchHandlerSymmetry, SketcherGui::StateMachines::OneSeekEnd, 0, SketcherGui::OnViewParameters<0>, SketcherGui::WidgetParameters<0>, SketcherGui::WidgetCheckboxes<2>, SketcherGui::WidgetComboboxes<0>, SketcherGui::ConstructionMethods::DefaultConstructionMethod, false> >::pressButton(Base::Vector2d) from /snap/freecad/1015/usr/lib/SketcherGui.so+0x92
#3  0x7f4d8145bffb in SketcherGui::ViewProviderSketch::mouseButtonPressed(int, bool, SbVec2s const&, Gui::View3DInventorViewer const*) from /snap/freecad/1015/usr/lib/SketcherGui.so+0x22b
#4  0x7f4dc6ace32c in Gui::ViewProvider::eventCallback(void*, SoEventCallback*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x15c
#5  0x7f4dc33adb47 in SoEventCallback::handleEvent(SoHandleEventAction*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0xb7
#6  0x7f4dc31d6095 in SoAction::traverse(SoNode*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x65
#7  0x7f4dc3370908 in SoChildList::traverse(SoAction*, int, int) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x168
#8  0x7f4dc33b7660 in SoGroup::doAction(SoAction*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x50
#9  0x7f4dc33cc66c in SoSeparator::doAction(SoAction*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x2c
#10  0x7f4dc31d6095 in SoAction::traverse(SoNode*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x65
#11  0x7f4dc3370908 in SoChildList::traverse(SoAction*, int, int) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x168
#12  0x7f4dc33b7660 in SoGroup::doAction(SoAction*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x50
#13  0x7f4dc33cc66c in SoSeparator::doAction(SoAction*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x2c
#14  0x7f4dc31d6095 in SoAction::traverse(SoNode*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x65
#15  0x7f4dc31dfa9b in SoHandleEventAction::beginTraversal(SoNode*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0xab
#16  0x7f4dc31d66e8 in SoAction::apply(SoNode*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0xc8
#17  0x7f4dc3385559 in SoEventManager::actuallyProcessEvent(SoEvent const*) from /snap/freecad/1015/usr/lib/x86_64-linux-gnu/libCoin.so.80c+0x79
#18  0x7f4dc6a446b2 in SIM::Coin3D::Quarter::QuarterWidget::processSoEvent(SoEvent const*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x22
#19  0x7f4dc6a52ff9 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent(SoEvent const*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x59
#20  0x7f4dc6a5e751 in Gui::NavigationStyle::processSoEvent(SoEvent const*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x41
#21  0x7f4dc6a6622f in Gui::GestureNavigationStyle::EventQueue::forwardAll() from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x9f
#22  0x7f4dc6a6fbd2 in Gui::GestureNavigationStyle::AwaitingMoveState::react(Gui::GestureNavigationStyle::Event const&) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x662
#23  0x7f4dc6a703a1 in boost::statechart::simple_state<Gui::GestureNavigationStyle::AwaitingMoveState, Gui::GestureNavigationStyle::NaviMachine, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x21
#24  0x7f4dc6a69f7a in Gui::GestureNavigationStyle::processSoEvent(SoEvent const*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x28a
#25  0x7f4dc6a5e9d2 in Gui::NavigationStyle::processEvent(SoEvent const*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x62
#26  0x7f4dc6a8f98e in Gui::View3DInventorViewer::processSoEvent(SoEvent const*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x6e
#27  0x7f4dc6a3b085 in SIM::Coin3D::Quarter::EventFilter::eventFilter(QObject*, QEvent*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x1e5
#28  0x7f4dc3f13baa in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0xaa
#29  0x7f4dc4aad752 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x72
#30  0x7f4dc4ab53a4 in QApplication::notify(QObject*, QEvent*) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xa84
#31  0x7f4dc663afa8 in Gui::GUIApplication::notify(QObject*, QEvent*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x98
#32  0x7f4dc3f13e4a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x13a
#33  0x7f4dc4ab3e87 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1b7
#34  /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1c91cb) [0x7f4dc4b0a1cb]
#35  /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1cc525) [0x7f4dc4b0d525]
#36  0x7f4dc4aad763 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x83
#37  0x7f4dc663afa8 in Gui::GUIApplication::notify(QObject*, QEvent*) from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x98
#38  0x7f4dc3f13e4a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x13a
#39  0x7f4dc433c1e7 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x687
#40  0x7f4dc430fdbc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5+0xac
#41  /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5(+0x76f5e) [0x7f4dbd907f5e]
#42  /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x26b) [0x7f4dc19acd3b]
#43  /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab258) [0x7f4dc1a02258]
#44  /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f4dc19aa3e3]
#45  0x7f4dc3f6d338 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x68
#46  0x7f4dc3f1276b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x12b
#47  0x7f4dc3f1ad14 in QCoreApplication::exec() from /snap/freecad/1015/kf5/usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x94
#48  0x7f4dc6575ae4 in Gui::Application::runApplication() from /snap/freecad/1015/usr/lib/libFreeCADGui.so+0x6c4
#49  /snap/freecad/1015/usr/bin/FreeCAD(+0xa709) [0x559417380709]
#50  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f4dc37cfd90]
#51  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f4dc37cfe40]
#52  /snap/freecad/1015/usr/bin/FreeCAD(+0xaac5) [0x559417380ac5]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
fixes #13999
@wwmayer I could not reproduce the crash on windows. Can you please check and feedback if this solves correctly the crash ?

### CODE REVIEW

**Comment by wwmayer** [comment]
No need to test it because I can tell you straightaway that it will still crash. handleContinuousMode() calls purgeHandler that destroys the handler but returns true. So, the calling instance onModeChanged() still calls toolWidgetManager.afterHandlerModeChanged() after its destruction.

**Comment by PaddleStroke** [comment]
> No need to test it because I can tell you straightaway that it will still crash. handleContinuousMode() calls purgeHandler that destroys the handler but returns true. So, the calling instance onModeChanged() still calls toolWidgetManager.afterHandlerModeChanged() after its destruction.

Actually you missed that the boolean is changed in the middle : 
`return !finish();`

I'm not sure its the best but I felt the finish function would return true if the handler is purged. And onModeChanged return true if the mode changed, ie !finish().

Do you prefer that we avoid the '!' to keep things simpler?

**Comment by wwmayer** [comment]
> Actually you missed that the boolean is changed in the middle :

Oh, you're right. OK will test it and report back.

Do you mind to change the comment right to the call of `!finish` to move it one line above so that won't be broken into two lines?

**Comment by wwmayer** [comment]
OK, it works!

**Comment by PaddleStroke** [comment]
> Do you mind to change the comment right to the call of !finish to move it one line above so that won't be broken into two lines?

Done

**Pull request merged**
