### PR TITLE
App: use auto - strange iterator

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

I can't understand why the original is written like it is. Is there any reason not to refactor like I show here?

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7405">pipeline status</a> for feature branch [PR_7405](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7405). Pipeline [624455748](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/624455748) was triggered at [7664134](https://github.com/FreeCAD/FreeCAD/pull/7405/commits/76641347ba373446d2e7d1f6035c516632efc1b7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
You have to change the dependencies code too, it reuses the same iterator.

**Comment by berniev** [comment]
Thanks Chris, yes I see that now. Added a commit. But why would the iterator have been written as it was? Seems like a very long-hand way

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7405">pipeline status</a> for feature branch [PR_7405](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7405). Pipeline [624508603](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/624508603) was triggered at [c3e6d45](https://github.com/FreeCAD/FreeCAD/pull/7405/commits/c3e6d45f2185e847d9c5b23aa615e3b2ffec9ac7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
There are a few more such cases of while-loops where a for-loop is more suitable:
https://github.com/FreeCAD/FreeCAD/blob/master/src/App/Document.cpp#L447
https://github.com/FreeCAD/FreeCAD/blob/master/src/App/Document.cpp#L698

**Comment by berniev** [comment]
Yes I know there are more. This was a precautionary PR in case I shoot myself in the foot (again). Thank you sir.

**Comment by wwmayer** [comment]
Squashed and merged as 2a2062ec46ddf9

**Pull request closed without merging**
