### PR TITLE
Gui: add parameter switch to optionally stretch 'Description' column of Tree view

### PR DESCRIPTION
**Pull request by 0penBrain**
https://forum.freecadweb.org/viewtopic.php?f=34&t=68000

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6751">pipeline status</a> for feature branch [PR_6751](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6751). Pipeline [516950426](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/516950426) was triggered at [d5c8752](https://github.com/FreeCAD/FreeCAD/pull/6751/commits/d5c8752ea5c096cd65a60f8b0784e96ff6f2be69). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Do you mind using this parameter group instead `User parameter:BaseApp/Preferences/TreeView`? It's already used for the tree view.

In Tree.h there is a class TreeParams that can be extended by a method getTreeViewStretchDescription()
```
bool TreeParams::getTreeViewStretchDescription() const
{
    return handle->GetBool("TreeViewStretchDescription", false);
}
```

**Comment by 0penBrain** [comment]
> Do you mind using this parameter group instead `User parameter:BaseApp/Preferences/TreeView`? It's already used for the tree view.

Sure. Missed it.
> In Tree.h there is a class TreeParams that can be extended by a method getTreeViewStretchDescription()

Honestly, this class is totally unreadable with all the #define things :rofl:

**Comment by wwmayer** [comment]
> Honestly, this class is totally unreadable with all the #define things

Absolutely agree on this! I think for v0.21 we should start to clean-up this mess.

**Pull request merged**
