### PR TITLE
[TechDraw] Add The People's Republic of China State standard Drawing Page Documents ( A serial ) 

### PR DESCRIPTION
**Pull request by felixlee868**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by felixlee868** [comment]
Writing Template file for TechDraw Mod which used by the People's Republic of China State standard. A serial page size.

**Comment by WandererFan** [comment]
Hi Felix, thanks for the contribution.  There's a typo in the "landscape" directory name - "landscpae".

**Comment by felixlee868** [comment]
Thanks for your e-mail. Due to I am not familiar with GitHub. I push wrong version yesterday. I have  remove landscape directory. 
Please clone from GitHub  

Best Regards 

Felix

**Comment by WandererFan** [comment]
Merged!

**Pull request merged**
