### PR TITLE
Assembly: Fix exploded view regressions

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fix issues of exploded views introduced by #16671

Fix https://github.com/FreeCAD/FreeCAD/issues/17196
Fix https://github.com/FreeCAD/FreeCAD/issues/17194
Fix https://github.com/FreeCAD/FreeCAD/issues/17208
Fix https://github.com/FreeCAD/FreeCAD/issues/15344

### CODE REVIEW

**Comment by PaddleStroke** [comment]
@chennes this must go in for 1.0. With the regressions of https://github.com/FreeCAD/FreeCAD/pull/16671 exploded views are totally unusable and messed up.

**Comment by chennes** [comment]
I will review it today.

**Comment by chennes** [comment]
@furgo16 have you had a chance to test this to confirm that it solves the bugs you've reported?

**Comment by furgo16** [comment]
@chennes not yet. But I'm building the branch now.

**Comment by furgo16** [comment]
So far, I tested the following:

- [x] https://github.com/FreeCAD/FreeCAD/issues/17196: can no longer reproduce. I've also tested it adding the subassembly as rigid and as flexible. All works now.
- [ ] https://github.com/FreeCAD/FreeCAD/issues/17194: TBD
- [x] https://github.com/FreeCAD/FreeCAD/issues/17208: can no longer reproduce. Seems fixed by this PR.
- [ ] https://github.com/FreeCAD/FreeCAD/issues/15344: TBD

**Comment by furgo16** [comment]
@PaddleStroke @chennes this is as far as I got with testing. I'll try to test the remaining issue in the next few days, but I cannot guarantee it.

**Comment by chennes** [comment]
Thanks for your help here, @furgo16 -- I'm going to merge and backport as-is since it seems to clearly address some important issues. This will auto-close all of the listed bugs, but please re-open any that don't seem to have actually been resolved.

**Comment by chennes** [comment]
@PaddleStroke this backport had conflicts as well -- please double-check to make sure that the merge didn't result in any problems. Thanks!

**Pull request merged**
