### PR TITLE
[TD] New Icon for AreaAnnotation

### PR DESCRIPTION
**Pull request by edi271**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---
New icon version including the characters "A²", see wiki documentation.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7063">pipeline status</a> for feature branch [PR_7063](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7063). Pipeline [568682419](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/568682419) was triggered at [95b53ee](https://github.com/FreeCAD/FreeCAD/pull/7063/commits/95b53ee54466ea84aabf2ec5b2614ec97706b205). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Please rename both PR and commit: `[TD] New Icon for AreaAnnotation`

**Comment by WandererFan** [comment]
@chennes - a big A for area works fine in some languages, but not others.  Do we have any policies on internationalization of icons?

**Comment by chennes** [comment]
"Policy" is putting it too strongly, but for exactly the reason you suggest, it's not a good idea to use a letter to represent a concept (except to mean something like "The text tool"). In this case "A" for "Area" only works in a few languages, and obviously not something like Mandarin (or even German, I believe).

**Comment by edi271** [comment]
@WandererFan: This PR should repair an issue. The original svg of this icon had included the "A²", but Qt's svg renderer had problems to show the characters. Meanwhile I recognised, that you changed the icon (and some more icons) in commit 1cd952f dated 30 mar 2022. The new version of the icon has no problems using Qt's svg renderer.
The German word for area is "Fläche". But usually in German in mathematical texts the character "A" is used for areas. I think it is the abbreviation of the Latin word, which is the same as the English word.
If the community is of the mind that the icon without the characters is the better one, I have no problem to close the PR.
Please tell me what to do.

**Comment by edi271** [comment]
Proposal of @domad (who created the icon): we should refer to the International System (S.I.) when using letter symbols for icons, so it should be: "m²" (square meters)

**Comment by WandererFan** [comment]
I'm not sure m2 is any better than a2.  I would just leave the current icon (without letter) for now.

**Comment by donovaly** [comment]
> In this case "A" for "Area" only works in a few languages, and obviously not something like Mandarin (or even German, I believe).

In German we also use "A" as standard variable for areas.

However not everybody looking at the icon will understand that A stand here for the variable for areas. Therefore I al not in favor of the icon change.

**Comment by WandererFan** [comment]
Let's try to come up with something else for area.  Closing this PR.

**Comment by luzpaz** [comment]
> Let's try to come up with something else for area. Closing this PR.

Maybe @bitacovir has an idea?

**Pull request closed without merging**
