### PR TITLE
[PartDesign] inverse for substractive features / remove outside

### PR DESCRIPTION
**Pull request by berberic2**
This adds an “inverse” option for PartDesign pocket feature and other additive features.
Essentially this cuts away anything that is **not** covered by the
sketch. (boolean common instead of cut.)

https://forum.freecadweb.org/viewtopic.php?style=5&f=19&t=59116
https://forum.freecadweb.org/viewtopic.php?style=5&f=13&t=59115

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by 0penBrain** [comment]
As suggested on the forum thread, would IMO be better to introduce this feature for all PartDesign soustractive features at one time (except Hole).

**Comment by adrianinsaval** [comment]
@berberic2 as I said in the forum (https://forum.freecadweb.org/viewtopic.php?style=5&f=19&t=59116&p=514324#p514324) I just submitted a PR to your branch extending the functionality to the other subtractive features however I didn't implement the GUI for them

**Comment by berberic2** [comment]
extended the PR by @adrianinsaval s PR.

**Comment by czinehuba** [comment]
Great feature but I would you the correct boolean cad operation which in this case is "intersect". Included a link FIY. 
http://www.ann.ugal.ro/im/anale2009/L16%20Article%201%20-%20BRAILA%202009%20Georgeta.pdf

**Comment by adrianinsaval** [comment]
If I'm not mistaken that is the autocad nomenclature, there's no reason for FreeCAD to use the same terms, in any case the OCC terminology could be used were this is called boolean common

**Comment by 0penBrain** [comment]
@czinehuba the problem is that this isn't a boolean operation (which applies between 2 solids). Here it applies to a sketch with the meaning of "remove material outside the sketch up to a limit set by certain conditions". Not easy. "Remove outside" is pretty fine to me.

**Comment by adrianinsaval** [comment]
It's more like making a pad and then running a boolean common, I've been thinking about it and I think maybe it's better if we pass the complement of the sketch shape to generatePrism instead of doing a boolean common, I haven't gotten around to trying it though and I don't think I will have time this week.

**Comment by czinehuba** [comment]
@adrianinsaval Yes. Common would be good alternative.

**Comment by czinehuba** [comment]
@0penBrain Yes and no. It's wouldn't be a boolean between two existing solids true, but it would be a boolean between the previous solid and the imaginary solid what the sketch would create. At least that's how I see it.

**Comment by majkrzak** [comment]
What is the reason of closing this?

**Comment by berberic2** [comment]
The discussion on the forum:

https://forum.freecadweb.org/viewtopic.php?f=17&t=61265&sid=fddc338c05a9d0074647e196d495c874&start=20#p533740

**Pull request closed without merging**
