### PR TITLE
[App] fix display of decimal separator in expressions

### PR DESCRIPTION
**Pull request by donovaly**
as discussed here: https://forum.freecadweb.org/viewtopic.php?p=418986

- also sort includes and remove double include

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Looks good to me, but the travis build failures could be related to this PR (output was 1 and now it's 1.00). In this case either we need one additional line in  your code (truncate decimals if .00) or adapt the tests so they all pass?

**Comment by donovaly** [comment]
> 
> 
> Looks good to me, but the travis build failures could be related to this PR (output was 1 and now it's 1.00). In this case either we need one additional line in your code (truncate decimals if .00) or adapt the tests so they all pass?

As I also wrote in the forum, that the output was 1 and not 1.000 (depending on the user's decimal settings) was the bug. Therefore the test should be adapted as well. Unfortunately I have only a very basic knowledge of Python.

I cannot just change the test to accept "1.00" because users like e.g. me use 3 decimals so then the output would be "1.000". So the test should simply compare floats. Is that right?

**Comment by donovaly** [comment]
> Therefore the test should be adapted as well.

I adapted the tests now according to the fix made with this PR - now the number of decimals set by the user is also respected by the tests.

**Comment by DeepSOIC** [comment]
I think this is completely unacceptable. It's a step in the wrong direction. FreeCAD should do its best to preserve the information users enter. This change is precisely against it.

Example.
My FC is set to 8 digits of precision. My colleague's FC may be set to the default 2 decimals.
I create a file, where I use this expression somewhere: 
".Constraints.mylen * 0.0001"
So far so good, saves and restores as expected.
Now I send it to a colleague. He opens the file, edits some labels, saves the file.
-> Boom, the expression now says ".Constraints.mylen * 0.00000000", even though he didn't even touch my expression.
Expressions are a small programming language, and not a "nice display". They should never truncate numbers. Please. FreeCAD is already guilty of rounding numbers to the displayed value, which really sucks. And expressions were a good workaround for it. Now this.

In my opinion, every number entry field in freecad should behave like expressions did: display a rounded number (preferably, giving a clue that it has rounded something off), but switch to full precision when one places a cursor there. Truncation is a bug.

**Comment by wwmayer** [comment]
> Now I send it to a colleague. He opens the file, edits some labels, saves the file.
-> Boom, the expression now says ".Constraints.mylen * 0.00000000", even though he didn't even touch my expression.

What's even worse is that numbers of expressions are saved in localized form into the project file. It looks like the parser can handle the comma vs dot but localized numbers is more than the different meaning of dot and comma.
E.g. in some languages strange Unicode characters can be used for the minus and this is something the parser definitely won't handle. So, the problem will be that even on the same machine a file can't be loaded any more.

**Comment by donovaly** [comment]
> So, the problem will be that even on the same machine a file can't be loaded any more.

Thanks for having a closer look. I'll comment in the forum.

**Comment by donovaly** [comment]
Closing in consequence of: https://forum.freecadweb.org/viewtopic.php?f=3&t=48907&sid=e9aa284852fa64a1eb622341a4b5794f&start=20#p428996

**Pull request closed without merging**
