### PR TITLE
Fix build with boost 1.76

### PR DESCRIPTION
**Pull request by vejmarie**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5315">pipeline status</a> for feature branch [PR_5315](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5315). Pipeline [439855298](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/439855298) was triggered at [8474b2f](https://github.com/FreeCAD/FreeCAD/pull/5315/commits/8474b2f13a964d2423e21dbcbdeb4cfac953814b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
What is the problem with boost 1.76 that the direct assignment doesn't work? I have tried it with the latest boost version 1.78 and the compiler doesn't complain.

**Comment by vejmarie** [comment]
> What is the problem with boost 1.76 that the direct assignment doesn't work? I have tried it with the latest boost version 1.78 and the compiler doesn't complain.

Hi, 

Here you are. It might be a compiler an XCode issue on mac. I am using latest version. Sorry for the mix.

[ 10%] Building CXX object src/App/CMakeFiles/FreeCADApp.dir/PropertyExpressionEngine.cpp.o
In file included from /Users/jmverdun/dev/git/freecad/src/App/PropertyExpressionEngine.cpp:24:
In file included from /Users/jmverdun/dev/git/freecad/src/App/Application.h:27:
In file included from /Users/jmverdun/dev/git/freecad/src/boost_signals2.hpp:6:
In file included from /usr/local/include/boost/signals2.hpp:19:
In file included from /usr/local/include/boost/signals2/signal.hpp:18:
In file included from /usr/local/include/boost/function.hpp:30:
In file included from /usr/local/include/boost/function/detail/prologue.hpp:17:
In file included from /usr/local/include/boost/function/function_base.hpp:21:
In file included from /usr/local/include/boost/type_index.hpp:29:
In file included from /usr/local/include/boost/type_index/stl_type_index.hpp:47:
In file included from /usr/local/include/boost/container_hash/hash.hpp:761:
In file included from /usr/local/include/boost/container_hash/extensions.hpp:22:
In file included from /usr/local/include/boost/detail/container_fwd.hpp:94:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/map:710:17: error: no viable overloaded '='
        __ref() = __v.__get_value();
        ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~

**Comment by jbaehr** [comment]
This looks like an alternative fix for the issue addressed with #5281

**Comment by chennes** [comment]
@vejmarie can you check whether this was fixed when we merged #5281?

**Comment by wwmayer** [comment]
Unlikely that this PR is still needed.

**Pull request closed without merging**
