### PR TITLE
cmake: add_definitions(-DSALOME_USE_64BIT_IDS) for smesh via config

### PR DESCRIPTION
**Pull request by looooo**
continued from here:

https://github.com/FreeCAD/FreeCAD/pull/7475

`add_definitions(-DSALOME_USE_64BIT_IDS)` if smesh is found via `find_package(SMESH, CONFIG)`

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7496">pipeline status</a> for feature branch [PR_7496](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7496). Pipeline [641019505](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/641019505) was triggered at [236e5a8](https://github.com/FreeCAD/FreeCAD/pull/7496/commits/236e5a84024386eda0fafd64bf295c2f13e21d71). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@looooo can you `git commit --amend` and prepend `cmake:` to the commit summary? TIA!

**Comment by donovaly** [comment]
@looooo , should I backport the whole file SetupSalomeSMESH.cmake and FindSMESH.cmake that you can use your build system also for FC 0.20.x or should I leave the 0-20 branch untouched?

**Comment by looooo** [comment]
yes I guess it's good to back port these changes. But currently I am a bit limited in thinking about all consequences. So let's try :)

**Comment by donovaly** [comment]
> So let's try :)

OK, I backported it now.

**Pull request merged**
