### PR TITLE
Draft: Working Plane improvements

### PR DESCRIPTION
**Pull request by carlopav**
ref forum: https://forum.freecadweb.org/viewtopic.php?f=23&t=61455

Several improvements to Working plane and Grid. See commits for more details.

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Great!! Thanks!

**Comment by carlopav** [comment]
I already tried to implement it, but I have some problems with `Gui.Snapper.grid.reset()`: It does not seem to recompute the grid on the fly, so also this preference I introduced is only effective when a new 3dView is opened... 
but that's really strange, so perhaps I did something wrong. Let me check again!

**Comment by yorikvanhavre** [comment]
I am not sure, I don't remember exactly, but the grid can be recalculated on the fly somehow (for ex. the axes colors change, or when you change the gird size in the Draft WP task panel. So there must be something

**Comment by berndhahnebach** [comment]
would you rebase the PR to make it run on CI?

**Comment by berndhahnebach** [comment]
would you rebase the PR to make it run on CI?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by carlopav** [comment]
@yorikvanhavre done!

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_4998

pipeline:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/377382875

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by yorikvanhavre** [comment]
Okay thanks!! Merging then!

**Pull request merged**
