### PR TITLE
[For 0.18] Build improvements

### PR DESCRIPTION
**Pull request by rpavlik**
- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [X ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
  - Seeing some errors (a few of which aren't related to modules I have disabled) in some tests, but I see the same errors with current master, so I don't think this should be an issue:

```
======================================================================
ERROR: testDescent (Document.DocumentPropertyCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ryan/src/third-party/FreeCAD-master/build/Mod/Test/Document.py", line 1261, in testDescent
    self.Doc = FreeCAD.open(tempFile)
IOError: Cannot get value from invalid enumeration

======================================================================
ERROR: testMenu (Menu.MenuCreateCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ryan/src/third-party/FreeCAD-master/build/Mod/Test/Menu.py", line 50, in setUp
    w.appendMenu("TestMenu",list)
  File "<string>", line 59, in appendMenu
AttributeError: TestWorkbench instance has no attribute '__Workbench__'

======================================================================
ERROR: testMenu (Menu.MenuDeleteCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ryan/src/third-party/FreeCAD-master/build/Mod/Test/Menu.py", line 74, in setUp
    w.removeMenu("TestMenu")
  File "<string>", line 61, in removeMenu
AttributeError: TestWorkbench instance has no attribute '__Workbench__'

======================================================================
FAIL: testActivate (Workbench.WorkbenchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ryan/src/third-party/FreeCAD-master/build/Mod/Test/Workbench.py", line 46, in testActivate
    self.fail("Loading of workbench '{0}' failed: {1}".format(i, e))
AssertionError: Loading of workbench 'PathWorkbench' failed: Test on activating workbench PathWorkbench failed

======================================================================
FAIL: failed_to_load_TestFem (TestApp.LoadFailed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ryan/src/third-party/FreeCAD-master/build/Mod/Test/TestApp.py", line 52, in _runTest
    self.fail("Couldn't load " + self.testName)
AssertionError: Couldn't load TestFem

----------------------------------------------------------------------
Ran 289 tests in 57.460s

FAILED (failures=2, errors=3)
Exception (Fri Jun 15 13:42:58 2018): System exit  
Debug: DraftGui.todo.doTasks: queue contains a deleted object, skipping

```

- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] (*n/a*) Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

---

This does some clean-up of the build system, mostly to fix warnings with newer CMake versions as well as improve compatibility with the Ninja generator and potentially paths with spaces (untested with spaces in path, likely not complete but they were easy fixes to make while I was in the neighborhood)

Specifically, this warning at CMake time is fixed by these commits:

```
CMake Warning (dev):
  Policy CMP0058 is not set: Ninja requires custom command byproducts to be
  explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  This project specifies custom command DEPENDS on files in the build tree
  that are not specified as the OUTPUT or BYPRODUCTS of any
  add_custom_command or add_custom_target:

   src/Mod/Arch/Arch_rc.py
   src/Mod/Draft/Draft_rc.py
   src/Mod/Material/Material_rc.py
   src/Mod/Plot/Plot_rc.py
   src/Mod/Ship/Ship_rc.py
   src/Mod/Tux/Tux_rc.py

  For compatibility with versions of CMake that did not have the BYPRODUCTS
  option, CMake is generating phony rules for such files to convince 'ninja'
  to build.

  Project authors should add the missing BYPRODUCTS or OUTPUT options to the
  custom commands that produce these files.
This warning is for project developers.  Use -Wno-dev to suppress it.

```

and this warning, seen when running Ninja after cmake in master, is also fixed by these changes:

```
~/src/third-party/FreeCAD-master/build$ ninja
ninja: warning: multiple rules generate Mod/Web/Init.py. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate Mod/Path/Init.py. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]

```

Additionally/as a part of the above, this properly sets up dependencies for generated files (execute_process with two commands was used on non-windows before to generate at cmake time, but this doesn't handle removal of build products - it's now using add_custom_command like Windows, but with an extra command to strip variable datestamps as indicated by the comment.)

### CODE REVIEW

**Comment by rpavlik** [comment]
Ugh, the build error is because of the non-gnu sed on Mac OS X. Will look into doing it a different way - should be able to script cmake to do it in a cross-platform way.

**Comment by yorikvanhavre** [comment]
This looks ok for me, but leaving it to @wwmayer to be sure...

**Comment by wwmayer** [comment]
Merged.

**Comment by peterlama** [comment]
@rpavlik, any news on a sed fix? https://travis-ci.org/FreeCAD/FreeCAD/jobs/415153467#L566

**Comment by wwmayer** [comment]
I wonder what's the reason of using sed at all. Any why changing the output files on Linux/macOS but not on Windows?

**Pull request closed without merging**
