### PR TITLE
Path: add HorizSpeed to boundaryDressup

### PR DESCRIPTION
**Pull request by J-Dunn**
boundaryDressup fails to set horizontal feedrates meaning previous feed rates carry over from previous lines. This can lead to horizontal cuts being done at inappropriate vertical feedrates. This one line change ensures toolcontroller values are used.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by Russ4262** [comment]
Afternoon.
We are glad to have another contributor to the PathWB.  Please tag the title of this PR with "[Path]" or "Path:" to better categorize and identify the PR for the devs who review them.  

Also, will you please attempt to adjust your PR so that only your changes to the file are highlighted.  Unfortunately I do not know enough about GIT and this system to say what was done - in this PR the entire file shows as changed.  I have this happen on occasion, but I am not certain what I am doing to cause it.  So, I can't offer the necessary change/correction.  As is, if I want to see the specific changes you made, I will paste the file contents from this PR into the same file in a new branch and see what pops up as changed.

Thanks for the involvement.

**Comment by J-Dunn** [comment]
Thanks Russ, I could not work that out either. I assumed I was misreading something. Neither do I understand why Travis is having sulk. I trashed by previous fork and did a fresh one just before creating these two PRs.  Like you I have trouble working out what you need to do with github so I tends to be trash the whole fork and start again.

**Comment by J-Dunn** [comment]
in fact the change was trivial: 

`commands.extend(PathGeom.cmdsForEdge(edge, flip, False,50,tc.HorizFeed.Value,tc.VertFeed.Value)) # add missing HorizFeed to G2 paths`

**Comment by J-Dunn** [comment]
I've just updated the branch, hopefully Travis will feel happy now.

**Comment by J-Dunn** [comment]
Looks like Travis VisualStudio building broken, so I guess we can ignore that.

**Comment by sliptonic** [comment]
Will you please rebase the branch from master rather than merging master into it?  

The git history becomes very messy and it's difficult to see what changed.

**Comment by J-Dunn** [comment]
> Will you please rebase the branch from master rather than merging master into it?
How can I do that on github , this interface seems pretty limited. I could simple delete the repo but then the other PR will disappear too. 

I created a fresh fork just before uploading this file , why does it need rebaseing straight away? Was that just bad luck that someone committed some PRs in the time between me creating a fork and uploading a file? 

Do you know what is going on which Travis?  He seems to retire to his "safe space" as soon as he runs VS tests and won't come out again.

**Comment by sliptonic** [comment]
I don't think you can do a rebase on github.  
If you click on the files changed link above, you'll see the problem.  It shows the one changed file (PathDressupPathBoundary.py) but it looks like every line in the file is changed.  This is because the PR contains both your commit to change the file and your commit to merge master into this branch. 

Ideally, you'd:
1) start with a new branch from master
2) change only the file you need
3) commit that change 
4) push that branch to github.
5) do a PR.

If master has moved forward between 1 and 4, you'd do `git rebase upstream/master`  and push the rebased branch.

I'm not sure what's up with travis.  I'm often merging PRs if they're exclusive to Path and the travis error appears to be elsewhere.

**Comment by J-Dunn** [comment]
well that's exactly what I did , no idea why it sees  the whole file changed. To cut the pain, I've just deleted the whole fork, since github is too crippled to do anything about it. 

So now I deleted the local copy of the file and rebase refuses 

> error: cannot rebase: You have unstaged changes.

and _git pull_ thinks I'm up to date despite the fact an entire file is missing and if I delete the local repo and start again I'll be doing nothing with it for the next three hours while it does a complete build. 

I've  had it running round in circles with this mess for a one line edit. Please see the code I posted above and work from that. Here it is again. 

`commands.extend(PathGeom.cmdsForEdge(edge, flip, False,50,tc.HorizFeed.Value,tc.VertFeed.Value)) # add missing HorizFeed to G2 paths`

**Comment by J-Dunn** [comment]
created a new PR , looks clean.

**Comment by sliptonic** [comment]
I see the other one.  I'm closing this one.

**Pull request closed without merging**
