### PR TITLE
TechDraw: Fix Windows compilation

### PR DESCRIPTION
**Pull request by chennes**
A clean recompile on Windows was failing because of a couple of precompiled header issues.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9225">pipeline status</a> for feature branch [PR_9225](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9225). Pipeline [832298897](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/832298897) was triggered at [ad8753e](https://github.com/FreeCAD/FreeCAD/pull/9225/commits/ad8753e17607c2bb1366a8fb4a38235c73d78360). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
Thank you.

**Review by WandererFan — APPROVED** [review]

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9225">pipeline status</a> for feature branch [PR_9225](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9225). Pipeline [832339158](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/832339158) was triggered at [c68cb55](https://github.com/FreeCAD/FreeCAD/pull/9225/commits/c68cb555652b93d30e4b72683d0528f53c974d00). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by benj5378** [comment]
@chennes As far as I remember, the GitHub CI build test on Windows passed... could it be relevant to look into? Maybe has to do with whether the Windows build test uses precompiled headers...

**Comment by chennes** [comment]
That's not a clean rebuild: it copies the cache files from the last run. This was working fine for me until I had to build clean, that's when it started failing. MSVC's handling of PCH files is a mystery to me: nevertheless I think this is correct, and it build both from scratch and from the cache.

**Pull request merged**
