### PR TITLE
[Icons]Revision of TechDraw Icons(Cascade-Coord)

### PR DESCRIPTION
**Pull request by Reqrefusion**
#14145

### CODE REVIEW

**Review by kadet1090 — CHANGES_REQUESTED** [review]
Looks fine but needs a bit of technical work with pixel alignment.

For lines to look crisp on as many sizes as possible you must align paths to pixel grid. In order to achieve best possible results try to aim for even pixel values and use odd pixel coordinates only when it is necessary due to for example ensuring even spacing.

**Comment by Reqrefusion** [comment]
It's interesting that you say this because, except for oblique, the other icons are pixel perfect. They are perfectly aligned. Oblique is not perfectly aligned because doing so reduces its similarity to other icons. However, it is also quite understandable, especially in 24x24.

**Review by kadet1090 — APPROVED** [review]
Same thing as #14876. 
image

Github does not render the preview crisply so I was fooled, checking with inkscape it is fine

**Comment by Reqrefusion** [comment]
Yes unfortunately github disappoints us a lot. We encountered more bugs than both FreeCad and Inkscrape.

**Review by maxwxyz — APPROVED** [review]

**Pull request merged**
