### PR TITLE
Bugfix: support DXF files generated by deepnest, try to fix misaligned DXF stream reads.

### PR DESCRIPTION
**Pull request by sundtek**
Fix reading DXF files generated by deepnest
https://forum.freecadweb.org/viewtopic.php?f=3&t=68997&p=598001

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6924">pipeline status</a> for feature branch [PR_6924](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6924). Pipeline [550115555](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/550115555) was triggered at [f43ed77](https://github.com/FreeCAD/FreeCAD/pull/6924/commits/f43ed775714836d23252d7a86e084e47aae806c0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by ageeye — COMMENTED** [review]
You should check the line length too. It exists group codes e.g. 90 too. How do you separate group codes and content? Your should get an line, check what ever you want to check, and read a line again. 
Is there no way to use the section ENTITIES as solution?

**Comment by sundtek** [comment]
It can be seen as a workaround it will try to re-align the stream. If that "workaround" will do something, something unexpected happened earlier already.
Eg. unhandled identifier "8".
Certainly I could have handled "8" before, but if other codes are not implemented and use "0" as value the same problem will happen again.

I'm not that deep into the DXF file format, I only had a look at it for a few minutes; possibly someone else who really worked with it can add correct handling code for the missing codes.

If the dxf format is fully implemented that workaround will just do nothing, so it should be safe to apply it.

**Comment by yorikvanhavre** [comment]
In any case, this needs thorough testing as it can affect. many other users.. as it's dangerous to do so close to the 0.20 release, i'll mark it for handling after the release..

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6924">pipeline status</a> for feature branch [PR_6924](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6924). Pipeline [552783670](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/552783670) was triggered at [513b4c4](https://github.com/FreeCAD/FreeCAD/pull/6924/commits/513b4c4af6b744f0ad34ec485eaf53cdb5e363af). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
This PR will be invalidated by #7101 
Could you add your changes to https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Import/App/dxf.cpp instead?

**Comment by ageeye** [comment]
@sundtek 
In my opinion the cause had to be eliminated. What do you think about [this](https://github.com/ageeye/FreeCAD/commit/457bba36bd4c9608d0dc8afe10d741f127688faf) solution.

**Comment by ageeye** [comment]
Please test [this](https://github.com/ageeye/FreeCAD/tree/dxfNext) branch. 

To load a file:

from PySide import QtGui

```
# open dxf file
path = FreeCAD.ConfigGet('UserAppData')
fname, filter = QtGui.QFileDialog.getOpenFileName(None, 'Read DXF file', path, '*.dxf')
if fname:
    # set flag to use the new Library to test
    grp = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/Draft")
    grp.SetInt("nativLibraryVersion", 2)

    # load the dxf
    import Import
    Import.readDXF(fname)

    # set the standard library
    grp.SetInt("nativLibraryVersion", 1)
```

**Comment by sliptonic** [comment]
This PR is now 14 months old and has merge conflicts.  Can we please get it rebased or closed?  
Is the original issue still relevant?

**Comment by yorikvanhavre** [comment]
There have been some work on the DXF importer recently... It might be good to test if the problem is still there before refactoring this

**Comment by sliptonic** [comment]
We are cleaning up the PR queue.   The branch has merge conflicts.   Moving this to Draft status.  Please resolve conflicts and remove draft status if you want it to be reviewed.

**Comment by luzpaz** [comment]
@ageeye can you resubmit this PR ?

**Pull request closed without merging**
