### PR TITLE
[PD and Part] add possibility to create skew prisms

### PR DESCRIPTION
**Pull request by donovaly**
it is a valuable feature to create skew prisms. This PR add this to part/PartDesign:

8FsyJadqPW

(The additional .ui changes were automatically made by Qt's designer since there is no property "margin" only left/bottom/right/topMargin and the property value does not exist for the widgets (only "rawValue") thus were never taken into account.)

### CODE REVIEW

**Comment by wwmayer** [comment]
Nice feature. But
* the default of Skew should be 0 instead of 10
* like the Height property the Skew property should be of type PropertyLength
* wouldn't it make sense to have two skew properties? One for x and one for y direction
* my recent changes to the plugin for the QuantitySpinBox causes a regression because all "value" entries have been removed.
For the real QuantitySpinBox there is a rawValue property of type double and a value property of type Base::Quantity. However, Qt Designer doesn't know the type Base::Quantity and thus cannot read or write it. Here I have to restore the old behaviour.

**Comment by wwmayer** [comment]
See 6d56b3e3b. It fixes the issue with the removed value property

**Comment by donovaly** [comment]
>     * the default of Skew should be 0 instead of 10

Oops. I'll correct this.

>     * like the Height property the Skew property should be of type PropertyLength

I purposely did not do this because while playing with this, I was quicker to use a negative skew. Length however cannot be negative.

>     * wouldn't it make sense to have two skew properties? One for x and one for y direction

I thought about this but thought one could rotate the prism.

**Note:** I just found a bug, since the offset is incorrect, meaning an offset of 1 mm does not mean the axis is skewed at 1.0 mm at the prism height. I'll correct this too now.
 
>     * my recent changes to the plugin for the QuantitySpinBox causes a regression because all "value" entries have been removed.
>       For the real QuantitySpinBox there is a rawValue property of type double and a value property of type Base::Quantity. However, Qt Designer doesn't know the type Base::Quantity and thus cannot read or write it. Here I have to restore the old behaviour.

Thanks, I'll fix my pending commits.

**Comment by wwmayer** [comment]
> I purposely did not do this because while playing with this, I was quicker to use a negative skew. Length however cannot be negative.

Then use PropertyDistance because this can accept negative values.

> I thought about this but thought one could rotate the prism.

You can do this with rotation only if one of the values is 0. If both values are non-zero you cannot achieve the same with one value + rotation. Btw, above you said you didn't use PropertyLength because it doesn't allow negative values but (with one Skew property) this could be easily done with a rotation.

**Comment by donovaly** [comment]
> Then use PropertyDistance because this can accept negative values.

I'll do so.
 
> You can do this with rotation only if one of the values is 0. If both values are non-zero you cannot achieve the same with one value + rotation.

Stupid me. You are right.
Since my PR for the pad direction is almost the same than a skewed prism, I'll use two angles for the prism primitve too. The benefit is real life (at least mine ;-) - I can simply define a taper draft for moulds and 3D-rpimted parts. In both cases they are defined as angle and so one save the manual recalculation what offset is necessary to get what angle.

**Comment by donovaly** [comment]
Now everything should be in shape. I changed the feature to accept angles. This is more convenient and consistent to my Pad PR.

oZPA0xp8HF

**Comment by donovaly** [comment]
Hmm, this feature needs more thought. I think about a third angle because the attachment of the prism can be every plane. However in most cases it is a base plane, so only in 1/3 of the cases the attachment is the xy-plane.

**Comment by donovaly** [comment]
Today I asked a colleague. He likes the feature as it is, only the name x and y angle was misleading. His argument was that one uses primitives in most cases from a base plane but one rotates and translate them too. And a rotated prism will never have a clearly named angle or direction. The proposal is simply to name it first and second direction. When applying an angle, one sees which direction this will be and it becomes immediately clear.
So I implemented this and it is sensible. So from my point of view this could be the solution.

Skewed prism that is also rotated:
FreeCAD_S6P6nQCwcL

Skewing as subtractive feature:
FreeCAD_kiMH1tJO3L

**Comment by wwmayer** [comment]
> Now everything should be in shape. I changed the feature to accept angles. This is more convenient and consistent to my Pad PR.

In that other PR you moved from angles to an axis. So, this PR is now less consistent to the pad. So, will you leave it as it is?

**Comment by donovaly** [comment]
> In that other PR you moved from angles to an axis. So, this PR is now less consistent to the pad.

Yes, this is a different approach than pad. However, obviously this is no inconsistency for users. Yesterday I asked another colleagues (who uses Alibre CAD) and they stated that a prism is a rare use case compared to a pad. when adding a prism one uses in the vast majority angles to define the skew while for a pad angles would be hard to understand since the sketch plane's normal vector is often "weird" (sketch is attached to a face of another object etc.). A prism however will only be in very rare cases attached to a face of another object. So when prism with skew, then setting an angle is more convenient.

I have no strong opinion. Since the 2 persons I could ask say defining an angle is more convenient for prisms, I would go on with this, meaning I leave the PR as it is.

**Comment by donovaly** [comment]
> In that other PR you moved from angles to an axis. So, this PR is now less consistent to the pad.

I showed the prism as well as the pad direction feature to another colleague today. I thought he argues to have the same UI for both features but also he likes the angle solution for prisms.

So I am reluctant what to do. For the pad the opinions are clear -> use a vector since the sketch could be oriented in any position.
Technically, the same argument applies for prisms, but I see that the application for a prism is different: They are rarely used compared to pads and if one does this, in most cases their base is parallel to one of the base planes. Then it is useful to input just an angle.
One the other hand, I don't like that bots are basically pads and have different UI.

What is your opinion? Should I change the UI for the prism feature to that of the pad direction feature or not?

**Comment by wwmayer** [comment]
Merged.

> What is your opinion? Should I change the UI for the prism feature to that of the pad direction feature or not?

The actual question is what's the more common use case.

**Pull request closed without merging**
