### PR TITLE
Added types to Attacher Type tooltip

### PR DESCRIPTION
**Pull request by edwilliams16**
The Attacher Type is a text string, To modify it you need to know the allowed possibilities. This adds it to the tooltip.

See  [https://forum.freecad.org/viewtopic.php?p=761923#p761923](https://forum.freecad.org/viewtopic.php?p=761923#p761923)

### CODE REVIEW

**Comment by wwmayer** [comment]
> The Attacher Type is a text string

I never understood why it's a PropertyString instead of a PropertyEnumeration. With the latter it will be possible to directly offer all available options to the user.

But to avoid to break old project files I suggest to:
1. Make the AttacherType property hidden and read-only so that it (by default) doesn't show up in the editor
2. Add a new PropertyEnumeration AttacherEngine with the modes "Engine 3D", "Engine Plane", "Engine Line", "Engine Point"
3. Add converter functions between the enum values and class names (e.g. "Engine 3D" <=> "Attacher::AttachEngine3D", ...)
4. If the AttacherEngine is changed it will automatically set the AttacherType

Does this sound reasonable?

BTW: With the FaceMakerClass property of the Extrusion feature we have the exact same problem.

**Comment by edwilliams16** [comment]
> Does this sound reasonable?

 Totally reasonable. Enum is the way to go.  However, I don't know any C++, just enough C to make this quick and dirty fix. In the meantime, this could be an incremental improvement until the issue crosses the radar of a C++  developer.

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/14402

**Comment by edwilliams16** [comment]
Handled by #14402

**Pull request closed without merging**
