### PR TITLE
Support common operations for all subtractive parts, and refactor related code

### PR DESCRIPTION
**Pull request by bgbsww**
Potential fix for #5991.

Open questions:  What's the right approach to copyright / assigning copyright on new files?

Don't love the "Remove outside of Profile" description of the checkbox, is there better language?

### CODE REVIEW

**Comment by FlachyJoe** [comment]
Hi @bgbsww, thank you for this great work.

I'm testing and find some inconsistencies
On App side:
- Pocket removes above the sketch. Give red when green is expected 
image
- Outside has no effect with Pocket UpToFirst / Last / Face
image


On GUI side:
- Outside is not displayed in properties. Only with Show All checked.
- Set Outside=true open task dialog: the box is unchecked (but Outside keeps its value if you validate the task).
- check the taskdialog box, change pocket type:  the box is unchecked

**Comment by bgbsww** [comment]
Of course the case I missed was the most involved one, and forced rethinking of the other after improving my test regieme.  @FlachyJoe I think I've addressed all the bugs you found, and a few more.

**Comment by FlachyJoe** [comment]
@chennes it works as expected. I'm suggesting a code change but nothing about functionality.

**Comment by FlachyJoe** [comment]
@bgbsww can you please squash your commits and then rebase. Conflicts were introduced by [2cef4cf](https://github.com/FreeCAD/FreeCAD/commit/2cef4cfdbe1a6b9ebf50a85c04fbe99f23cd3829)

**Comment by bgbsww** [comment]
Well, that didn't work right, but I already had another branch prepared.  Is there some button in Github I'm missing?  I was forced to attempt this externally.

**Comment by luzpaz** [comment]
What didn't work right ?

**Comment by bgbsww** [comment]
When I force pushed back to github, I ended up with all the commits since the start of the branch, and not just mine.  I'm sure it's my error, and I already had the other branch prepared in case.  The complicating factor is that I synched this branch several times during its long lifetime, and that led to my mistake.

**Comment by FlachyJoe** [comment]
In this case and  in order to keep the same PR you can:

1. create a new branch from main
2. cherry pick the needed commits from the problematic branch
3.  force push the new branch to this distant
4. delete the problematic branch

**Pull request closed without merging**
