### PR TITLE
BIM+Draft: Bring back human figure

### PR DESCRIPTION
**Pull request by Roy-043**
* For the human figure attached to the Draft grid a hard-coded point list is used (instead of deriving the points from human figure.brep). This is more efficient and avoids a dependency on the BIM WB.
* The default for the human figure preference of the grid was changed to false. And the tooltip adjusted.

Forum post:
https://forum.freecad.org/viewtopic.php?p=791779#p791761

### CODE REVIEW

**Comment by maxwxyz** [comment]
@Roy-043 CI is failing. Does it really need to be backported? 
@yorikvanhavre FYI

**Comment by Roy-043** [comment]
I can live with this not making V1.0. But we can expect some bug reports then.

**Comment by yorikvanhavre** [comment]
For me this can be after 1.0, no?

**Comment by Roy-043** [comment]
That is fine.

Maybe the brep file should be added to the Resources?

**Comment by Roy-043** [comment]
Needs to be backported to V1.0.1.

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
