### PR TITLE
Core: Add libfmt via FetchContent

### PR DESCRIPTION
**Pull request by chennes**
This is a different attempt to add libfmt to our codebase by using cMake's FetchContent facility. The PR includes two commits: the first adds the actual cMake commands. The second is a dummy commit that references the formatting library in code so that you can see if it compiles on your system. The second commit is not intended to be merged, and will be removed after testing. To test, just run cMake and compile FreeCAD. If the compilation succeeds, then this worked on your system.

If successful, this would replace #8077 (though that PR adds the library in a couple of additional modules that this one does not yet).

---

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by chennes** [comment]
This runs successfully when compiled with CLion on:
```
OS: macOS 13.2
Word size of FreeCAD: 64-bit
Version: 0.21.0.31820 (Git)
Build type: Release
Branch: cMakelibfmt
Hash: 16cacfb3fbdd4a71de283730c28945425e120cd6
Python 3.10.9, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
```

**Comment by chennes** [comment]
This runs successfully when compiled with MSVC on:
```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.31916 +2 (Git)
Build type: Release
Branch: cMakelibfmt
Hash: 90feb219ea8c61f4bea4a96b98d1b5259905bdb7
Python 3.8.6+, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.5.3
Locale: English/United States (en_US)
```

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [779258768](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/779258768) was triggered at [90feb21](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/90feb219ea8c61f4bea4a96b98d1b5259905bdb7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [779281371](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/779281371) was triggered at [5034127](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/5034127a55846d7072bed7a164c175866e1a21c8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [779932952](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/779932952) was triggered at [572ac62](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/572ac62ea4e89eb34d4e845aa422d0b86372fca0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [780042331](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/780042331) was triggered at [d379c49](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/d379c4985ff33b2ada531ba2c4098c5a7e96430d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
The Linux build fails with
```
[ 52%] Linking CXX shared library ../../lib/libFreeCADApp.so
/usr/bin/ld: ../../_deps/fmt-build/libfmt.a(format.cc.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/App/CMakeFiles/FreeCADApp.dir/build.make:1302: lib/libFreeCADApp.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:3296: src/App/CMakeFiles/FreeCADApp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
For some reasons I couldn't see the reasons in the CI builds but the build on gitlab shows it.

Besides this I think we should add an option where either a system package could be used or the CMake facility to download the sources. Package maintainers probably prefer the former option.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [780213840](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/780213840) was triggered at [ea7cae1](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/ea7cae1fced69ef5e04e5045a3adc0797c4be552). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
> For some reasons I couldn't see the reasons in the CI builds but the build on gitlab shows it.

Oh damn, I accidentally deleted the line that fixed that. Sorry! I'll get it back in there.

**Comment by chennes** [comment]
> 



> Besides this I think we should add an option where either a system package could be used or the CMake facility to download the sources. Package maintainers probably prefer the former option.

cMake provides this internally: find_package() is used first to locate the package, and it only falls back to downloading the code if find_package() doesn't yield anything. Since cMake 3.24 there have been additional options to control that process, so packagers with recent versions of cMake should be able to achieve whatever effect they like.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [780342851](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/780342851) was triggered at [d4bf1af](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/d4bf1af0662348c233ad90b52db20a6a8ea6e4e5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
You could make a unit test. Its easy!

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [780517241](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/780517241) was triggered at [9cdfc4a](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/9cdfc4a55c01c47c24a593f58b7479cc892226ba). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [780614814](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/780614814) was triggered at [5b00c95](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/5b00c95a93ae0b10b03dee831c6f3e4aec6ae700). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [780628487](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/780628487) was triggered at [d0dde50](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/d0dde5067a75c1e94e4cb7e77d78cd3c57482478). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [780641881](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/780641881) was triggered at [613564f](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/613564f79ea16753be440e15ca3d599890c690ac). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
Fantastic ! !

Best I drop my PR #8077 now?

**Comment by abdullahtahiriyo** [comment]
@chennes 

Thank you very much.

Your PR appears to work in all supported OS as per reports of @donovaly @berniev  and myself.

Do you think the time has arrived to remove the testing commit and merge?

**Comment by chennes** [comment]
Yes -- I've removed the testing commit and will merge as soon as CI is complete.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508">pipeline status</a> for feature branch [PR_8508](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8508). Pipeline [782093063](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/782093063) was triggered at [29660e5](https://github.com/FreeCAD/FreeCAD/pull/8508/commits/29660e5a61f0ad586866cad675ed9665666ccca4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by abdullahtahiriyo** [comment]
Thank you so much :)

**Comment by chennes** [comment]
OK, merging now... if this causes anyone build problems, or if I need to add additional find_package logic to make it work for anyone, please create a GitHub Issue.

**Pull request merged**
