### PR TITLE
Fixes "Project Information" is Misleading #11296 - replace project with document

### LINKED ISSUE #11296: [Problem] "Project Information" is Misleading
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FreeCAD does not deal in "projects", only documents.  "Project Information" implies the existence of projects.  This also applies to "Project Utility".

### Full version info

```shell
any
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by maxwxyz**
Fixes #11296

- Project information --> Document information
- Project utility --> Document utility
- Merge project --> Merge document

Changed in menus and ui (windows). Changed in translation source files. Marked "old" translations as unfinished.

### CODE REVIEW

**Comment by luzpaz** [comment]
modifyuing .ts files is not necessary as it done automagically via lupdate. Please revert.

**Comment by maxwxyz** [comment]
@luzpaz done

**Review by WandererFan — COMMENTED** [review]
LGTM! Thanks for this.   There's another one in DlgSettingsGeneral - "Project Unit System", but that can go in a new PR.

**Comment by maxwxyz** [comment]
done as well

**Comment by sasobadovinac** [comment]
I don't see the need for this change, there have been several discussions about the possibilities to manage/store FC models in different ways in addition to the existing file/documents, eg. in git, in a database,... Project is a much more generic name that fits much better for all the different cases, besides such changes, introduces confusion to all of the existing tutorials, documentation, etc.

**Comment by luzpaz** [comment]
This was WandererFan's request in #11296

**Comment by maxwxyz** [comment]
In all other occurrences the file is referenced as document, not a project. It should be consistent in the entire application. Either change these 4 occurrences to match the others, or change all the other occurrences to project.

**Comment by sasobadovinac** [comment]
Well, it is not something critical so if others think that it is better I would also not argue about it...

**Comment by chennes** [comment]
FYI manual changes to translation files are not necessary and will be overwritten by the automated translation extraction process.

**Comment by maxwxyz** [comment]
Thanks, already reverted these changes. Is this able to merge or does it need adjustments?

**Pull request merged**
