### PR TITLE
[TechDraw] make QGIViewPart less BaseGeom independent

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---
https://forum.freecad.org/viewtopic.php?t=78050

### CODE REVIEW

**Comment by benj5378** [comment]
> I suggest that we start skinnying down BaseGeom before removing it completely.
So this is how far I got tonight for making a smaller PR. What blocked me is that I can't get rid of BaseGeom for now as it holds a lot of information from cosmetic edges...

**Comment by benj5378** [comment]
@WandererFan

https://github.com/FreeCAD/FreeCAD/pull/9452/files#diff-e94f7bf1e4dbe707233b508a7d0733502a2c813fdb31ef78bbdc2af9494c8f36R696-R720

All these three cases actually do the exact same logic. The only difference is the pointer type. All this because there are three seperate functions `getCosmeticEdge` `getCenterline` `getGeomFormat` for returning an object that has a `LineFormat` member variable. All this because `CosmeticEdge` `Centerline` `GeomFormat` is stored in each their variable.

So for even making QGIViewPart partially independent of BaseGeom, I have to chase this all the way up. Only partially independent! I still have to pass a bool whether something is cosmetic or not all the way down again.

If we chase this all the way up and merge `PropertyCosmeticEdgeList` `PropertyCenterLineList` `PropertyGeomFormatList`, we can get rid of about 3 x 8 identical function just for different types in `CosmeticExtension` alone, 3 identical functions in QGIViewPart and perhaps also `m_source` of BaseGeom as it seems to me its purpose is to tell other code whether it shoud go look in `PropertyCosmeticEdgeList` `PropertyCenterLineList` or `PropertyGeomFormatList`.

So what do you say? I am ready, but are you willing to hunt this monster down? It would be a start to making it all less clutterly and relying less on BaseGeom...

image

**Comment by WandererFan** [comment]
This is about QGIViewPart right?  QGIView shouldn't be using Geometry.

**Comment by benj5378** [comment]
@WandererFan No, QGIViewPart, the lines I linked to.

```
        TechDraw::GeomFormat* gf = viewPart->getGeomFormatBySelection(i);
        if (gf) {
            App::Color  color = Preferences::getAccessibleColor(gf->m_format.m_color);
            item->setNormalColor(color.asValue<QColor>());
            item->setWidth(gf->m_format.m_weight * lineScaleFactor);
            item->setStyle(gf->m_format.m_style);
            showItem = gf->m_format.m_visible;
        }
```

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9452">pipeline status</a> for feature branch [PR_9452](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9452). Pipeline [903673412](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903673412) was triggered at [b0dffea](https://github.com/FreeCAD/FreeCAD/pull/9452/commits/b0dffeaeb954d24c0420e4f36239058e1c8356fb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
stale and ci errors.  closing.

**Comment by WandererFan** [comment]
stale and has CI errors.  closing.

**Pull request closed without merging**
