### PR TITLE
[report view] add preferences to report view context menu

### PR DESCRIPTION
**Pull request by mwganson**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

Related discussion: (PR to disable show on warning/error by default)

https://forum.freecadweb.org/viewtopic.php?f=17&t=48962

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by 0penBrain** [comment]
@mwganson : could you please fixup the 3 last commits (and eventually squash with the 1st) so commit history is kept clean ?

**Comment by mwganson** [comment]
What are the steps for squashing them?  I thought it had to be done when Werner or Yorik committed it.

**Comment by 0penBrain** [comment]
@mwganson : AFAIK when a PR is merged, commits are just pushed to the master as they are.
To squash/fixup, you have to use interactive rebase called with 'git rebase -i COMMIT', where COMMIT is the first ancestor of the first commit you want to deal with.
So in your case, your branch was created from master commit cd53410, so you can run 'git rebase -i cd53410'
But it may be easier to make reference to your own commits. In your case your first commit is 6b26bef so you can enter the equivalent 'git rebase -i 6b26bef~1'.
Finally another way is knowing you have done 4 commits, you can enter 'git rebase -i HEAD~4'.
Then everything is quite well explain on the text editing you get. If you want to squash (merge commits + merge commit messages) a commit with its parent, replace 'pick' by 's' or 'squash'. If you want to fixup (merge commits + discard commit message of fixup commit) a commit with its parent, replace 'pick' by 'f' or 'fixup'.
Of course you can chain several subsequent fixups/squashes.
For sake of completeness, it is possible to move up/down a commit in the list (this is especially useful for fixups).
Let's say that in your case, the file you accidentally added was introduced with your first commit (I didn't check), your rebasing could look something like) : 
pick 6b26bef
fixup 83711b6 #The 4th commit actually fixes the 1st
squash c357859 #Could be 'pick' if it has sense it's a separate commit
fixup 6545f0f

As it will create non fast-forward changes, after using an interactive rebase you have to force push. I advise to use 'git push --force-with-lease' (rather than a brutal '--force') so it stays safe.

**Comment by mwganson** [comment]
Okay.  Thanks a lot.  Here are the notes I already had on doing this:

how to squash commits
git rebase -i master
(will see a list of commits, each starting with "pick"
leave the first commit with "pick"
put the rest of them "squash"
save and close editor
will get chance to change commit message
save and close editor again
git push -f

But I thought it would just add yet another commit if I did it after opening the PR.  Good to know also about git push --force-with-lease.  I'll update my notes to use that instead.

**Comment by wwmayer** [comment]
Merged.

In your case you could also do a: git reset --soft HEAD~4
This sets the tip back to the commit before your first commit but leaves the changes you made. The file you added and removed won't reappear. This is how I squashed your PR locally.

**Pull request closed without merging**
