### PR TITLE
TechDraw Projection Group Views

### PR DESCRIPTION
**Pull request by WandererFan**
Please merge.  This PR improves the display of secondary views in DrawProjectionGroup and fixes section angles when base view is not in standard orientation. 

Thanks,
wf

### CODE REVIEW

**Comment by WandererFan** [comment]
gcc linux build timed out at 49:07    clang/mac, clang/linux and Appveyor all pased.

**Comment by WandererFan** [comment]
Trying "update branch" to restart builds.

**Comment by sasobadovinac** [comment]
Linux builds are failing https://travis-ci.org/FreeCAD/FreeCAD/jobs/187452023#L5549

`In file included from /home/travis/build/FreeCAD/FreeCAD/src/Mod/TechDraw/App/DrawViewPart.h:40:0,
                 from /home/travis/build/FreeCAD/FreeCAD/src/Mod/TechDraw/App/AppTechDraw.cpp:25:
/home/travis/build/FreeCAD/FreeCAD/src/Mod/TechDraw/App/DrawProjectSplit.h:82:87: error: ‘gp_Ax2’ has not been declared
     static TechDrawGeometry::GeometryObject*  buildGeometryObject(TopoDS_Shape shape, gp_Ax2 viewAxis);
                                                                                       ^
In file included from /home/travis/build/FreeCAD/FreeCAD/src/Mod/TechDraw/App/AppTechDraw.cpp:25:0:
/home/travis/build/FreeCAD/FreeCAD/src/Mod/TechDraw/App/DrawViewPart.h:117:13: error: ‘gp_Ax2’ does not name a type
     virtual gp_Ax2 getViewAxis(const Base::Vector3d& pt,
             ^
/home/travis/build/FreeCAD/FreeCAD/src/Mod/TechDraw/App/DrawViewPart.h:144:88: error: ‘gp_Ax2’ has not been declared
     virtual TechDrawGeometry::GeometryObject*  buildGeometryObject(TopoDS_Shape shape, gp_Ax2 viewAxis);
                                                                                        ^
In file included from /home/travis/build/FreeCAD/FreeCAD/src/Mod/TechDraw/App/AppTechDraw.cpp:29:0:
/home/travis/build/FreeCAD/FreeCAD/src/Mod/TechDraw/App/DrawProjGroupItem.h:79:20: error: ‘virtual gp_Ax2 TechDraw::DrawProjGroupItem::getViewAxis(const Vector3d&, const Vector3d&, bool) const’ marked override, but does not override
     virtual gp_Ax2 getViewAxis(const Base::Vector3d& pt,
                    ^
make[2]: *** [src/Mod/TechDraw/App/CMakeFiles/TechDraw.dir/AppTechDraw.cpp.o] Error 1
make[1]: *** [src/Mod/TechDraw/App/CMakeFiles/TechDraw.dir/all] Error 2`

**Comment by wwmayer** [comment]
Merged & fixed.

**Pull request closed without merging**
