### PR TITLE
Pixi [wip]

### PR DESCRIPTION
**Pull request by looooo**

### CODE REVIEW

**Comment by oursland** [comment]
I made a couple changes on my branch https://github.com/FreeCAD/FreeCAD/compare/main...oursland:FreeCAD:pixi that utilize the `CMakePresets.json` presets to define the platform-specific build flags as well as updating the dependencies to match the configuration in `main`.

**Comment by looooo** [comment]
@oursland What do you think about making the pixi builds qt6 only. Mixing qt5 and qt6 leads to a lot of issues I guess. As far as I know there is only gmsh missing for the qt6 dependency tree. We can start with a minimal setup and then slowly try to get all the dependencies added.

**Comment by oursland** [comment]
My preference would be to support both Qt5 and Qt6 through [multi-environments](https://pixi.sh/latest/features/multi_environment/#feature-environment-set-definitions) until it has been determined to move FreeCAD to Qt6 and abandon Qt5.

The biggest barrier of compatibility between Qt5 and Qt6 environments I'm aware of is the lack of support for Qt5 on Python 3.12.  The ROS project, and therefore RoboStack, has strong dependency upon Qt5 without a path forward to Qt6 at this time.  Consequently, there has been discussion of porting the Debian patches to Qt5 to support Python 3.12 in conda-forge.

**Comment by looooo** [comment]
> Consequently, there has been discussion of porting the Debian patches to Qt5 to support Python 3.12 in conda-forge.

Yes this would be nice. Didn't know there exists patches.

**Comment by oursland** [comment]
The last example on the list [Multi-Environment: Real World Examples](https://pixi.sh/latest/features/multi_environment/#real-world-example-use-cases) titled `"Multiple machines from one project"` shows how to define different environments and specify which environment to use on the command line, along with setting a default environment.

I believe both `qt5` and `qt6` should be environments, with the default being whichever is used for the weekly builds.  This would assist a developer in quickly reproducing published builds with a reasonable set of defaults.

**Comment by looooo** [comment]
Ok this sounds good to me. Thanks for the information.

If we specify the dependencies for qt6 and qt5 we have a lot of deps in common. Do you know if it's possible to use multiple environments on top of each other. Similar like it is done for building a feedstock (host env on top of the build env). This way we could specify all the dependencies in common in one env and all the qt specific dependencies in another env.
Also we might have to think about multiple python versions. My original plan for conda was to support python 3.9-3.11 in combination with qt5 and python3.12 and newer versions with qt6. But if patches are added to pyside2 it should be possible to support python3.12 and newer also for qt5.

**Comment by oursland** [comment]
Yes, multi-environment configurations can be structured as a hierarchical set.  We can define a `base` environment in which the `qt5` and `qt6` environments will be strict supersets.

First, any dependencies in the `[dependencies]` will be inherited by all environments, which could satisfy the `base` environment.

Second, we can define environments as `[feature.*]` elements and construct the environments from them.  Thisis described in [Multi Environment: Feature & Environment Set Definitions](https://pixi.sh/latest/features/multi_environment/#feature-environment-set-definitions) in the `"Creating environments from features"` subheading.  In this several environments are constructed through composition of features.

I'm generally in favor of avoiding tying features to versions, if they're not explicitly linked (e.g. PySide2 is linked to Qt5, and PySide6 is linked to Qt6).  Consequently, I do not believe we should use Python version as the feature flag for Qt6.

**Comment by looooo** [comment]
@oursland any ideas where the win/qt6 error is coming from?
```
CMake Error at CMakeLists.txt:28 (project):
  Generator

    Ninja

  does not support platform specification, but platform

    x64

  was specified.
``

**Comment by oursland** [comment]
I submitted a PR into your branch that gets past that error.  I believe this is an issue introduced in the CMake version.

The PR encounters other issues on Windows-64 Qt6 builds due to link failures to `boost`.

**Comment by oursland** [comment]
@chennes Do you know what could be causing this? https://github.com/FreeCAD/FreeCAD/actions/runs/11201063761/job/31135545570?pr=16795#step:4:1299

It is only affecting Windows with Qt6, not the other platforms or Windows with Qt5.

**Comment by looooo** [comment]
@oursland we can also try to use clang for windows like I did with pivy:

https://github.com/coin3d/pivy/blob/master/pixi.toml#L41

**Comment by oursland** [comment]
That's pretty wild, but I'm not sure that's the best idea as this should be something in CI to test the many ways in which developers may build their environment.  It'd be a real issue to commit something that builds in CI, but breaks the build for all devs using MSVC++.

**Comment by looooo** [comment]
Windows qt6 has some cmake warnings like this one:
```
CMake Warning at .pixi/envs/qt6/Library/share/cmake-3.28/Modules/FindBoost.cmake:1398 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  .pixi/envs/qt6/Library/share/cmake-3.28/Modules/FindBoost.cmake:1523 (_Boost_COMPONENT_DEPENDENCIES)
  .pixi/envs/qt6/Library/share/cmake-3.28/Modules/FindBoost.cmake:2135 (_Boost_MISSING_DEPENDENCIES)
  cMake/FreeCAD_Helpers/SetupBoost.cmake:7 (find_package)
  CMakeLists.txt:70 (SetupBoost)
```
and fails with:
```
Application.cpp.obj : error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > boost::program_options::arg" (?arg@program_options@boost@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
Application.cpp.obj : error LNK2001: unresolved external symbol "public: static unsigned int const boost::program_options::options_description::m_default_line_length" (?m_default_line_length@options_description@program_options@boost@@2IB)
bin\FreeCADApp.dll : fatal error LNK1120: 2 unresolved externals
```

Windows qt5:
```
error LNK1104: cannot open file 'bin\FreeCAD.ilk'
2024-10-20T12:22:56.2245380Z 
2024-10-20T12:22:56.2245682Z [3759/6074] Linking CXX executable bin\FreeCADCmd.exe
2024-10-20T12:22:56.2855002Z [3760/6074] Linking CXX shared library bin\FreeCAD.pyd
2024-10-20T12:22:58.6641038Z
```

**Comment by oursland** [comment]
This may be due to `CMakePresets.json` being derived from previous dependencies.  This file was originally derived from the configuration in [`freecad-feedstock`'s `build.sh`](https://github.com/FreeCAD/freecad-feedstock/blob/master/recipe/build.sh#L41).

I have removed `Boost_NO_BOOST_CMAKE` on my [`pixi` branch](https://github.com/oursland/FreeCAD/tree/pixi) and it seems to get past that.  I wonder what other `CMakePresets.json` settings may be relaxed.

**Comment by oursland** [comment]
I reproduced the Qt6 build failure in a Windows VM.  The issue arrises from the inclusion of the [`/permissive-`](https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170) command line argument to `cl.exe`.  Removing this manually results in successful building of the the files currently causing an error on WM4 template expansion.

Globally removing the option, however, results in build failures on files including Qt6's `QtCore/qcompilerdetection.h` that indicate the flag is mandatory on MSVC for certain features used by Qt6.  I believe this option is being introduced by Qt6's CMake.

I do wonder if the errors are valid, and hidden by default permissive behavior that is disabled by [`/permissive-`](https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170).  For context, the error is: 

    C:\Users\jso\FreeCAD\src\Mod\Mesh\App\WildMagic4\Wm4TRational.inl(699): error C2446: '<=': no conversion from 'int' to 'unsigned int *'
    C:\Users\jso\FreeCAD\src\Mod\Mesh\App\WildMagic4\Wm4TRational.inl(659): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast

Which suggests that an integer is being converted to a pointer, which would likely be a *very* **bad thing**.

**Comment by oursland** [comment]
[This commit](https://github.com/oursland/FreeCAD/commit/e6eb6c795e4e2606eadf6815cb52144f198cbf38) gets past the build failure.  It is not at all what I was expecting as a fix, and am wondering if `i` has another definition prior to template expansion leading to ambiguity that is resolved when making the variable loop-local.

**Comment by looooo** [comment]
continued here: https://github.com/FreeCAD/FreeCAD/pull/18182

**Pull request closed without merging**
