### PR TITLE
Use src/XDGData in fedora spec file

### PR DESCRIPTION
**Pull request by PrzemoF**
Signed-off-by: Przemo Firszt <przemo@firszt.eu>

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
@PrzemoF As you saw on #1732 there is now a distro-agnostic directory with those files... I would merge this PR now, so fedora can benefit it immediately, then later on we see about merging the two. What do you think?

**Comment by yorikvanhavre** [comment]
Oops you're right... I read the diff inverted :D waiting for appveyor to complete and I merge it.

**Comment by PrzemoF** [comment]
No rush, I'm afraid it might be broken. Or COPR system is broken. Or both. :-)

**Comment by PrzemoF** [comment]
It needs more work

**Pull request closed without merging**
