### PR TITLE
add c++14 option

### PR DESCRIPTION
**Pull request by looooo**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
This solution is quite ugly and also will makes things more complex when adding further C++ standards like C++17 or C++20 in the near future.
A much better way is to implement a combo box-like behaviour as done in 885ef4b This can be easily extended with further C++ versions.

Another issue of the offered solution is that if C++14 is activated it sets the compiler flags for every compiler which may run into errors or warnings

**Comment by looooo** [comment]
nice, thanks

**Comment by wwmayer** [comment]
I tested it on Windows where the match for C++17, ... is inactive. However, with compilers other than msvc the check is active and is causing a regex failure. Obviously the plus chars of C++ must be escaped. A fix is already checked-in.

**Comment by looooo** [comment]
sry, I have only checked my PR yesterday on win and linux.

**Pull request closed without merging**
