### PR TITLE
PartDesign: Highlight body tip

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
==============================

It generates a small green icon on the treeview for those features being the tip of the body.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
Reworded commit message of https://github.com/FreeCAD/FreeCAD/pull/1274

**Comment by sasobadovinac** [comment]
Can the visibility of the active Part and Body also be improved? It is IMO not the best at the moment, specially when they are selected. Maybe change to underline the text instead of the current highlight?

**Comment by abdullahtahiriyo** [comment]
@sasobadovinac 
I can work on that issue, but:
1. It is a separate issue
2. I am not sure if this should be left for after 0.17 release. Whatever Werner says is fine for me.

**Comment by sasobadovinac** [comment]
@abdullahtahiriyo yes, of course, it is however a very similar UX issue

**Comment by wwmayer** [comment]
Changing current behaviour when an object is active should be done after v0.17 is out.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
