### PR TITLE
Path:  Fixed test00010 sensitivity to terminal column count.

### PR DESCRIPTION
**Pull request by LarryWoestman**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by LarryWoestman** [comment]
This fixes a test failure in the master branch.  I am working on another build that includes the two changes that have been check into master since my last build.

**Comment by LarryWoestman** [comment]
This passes the "./FreeCAD -c -t TestPathApp" and "./FreeCADCmd -t TestPathApp" tests in terminal windows that are 80 characters and not 80 characters wide.

**Comment by LarryWoestman** [comment]
The latest fix passes the tests described above on a new build with the more recent changes to master rebased in.

**Comment by luzpaz** [comment]
Thank you. Lets see if the CI passes now

**Comment by LarryWoestman** [comment]
And another push to catch up with changes to master.  Still passes the tests described above.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7469">pipeline status</a> for feature branch [PR_7469](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7469). Pipeline [636514551](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/636514551) was triggered at [ae4ddec](https://github.com/FreeCAD/FreeCAD/pull/7469/commits/ae4ddec6440ba5713335cf834c54c1bae8ffe2d0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by LarryWoestman** [comment]
Another push to keep up with the changes in master.
I also added one line to allow error diff's to be as long as necessary to allow better debugging of tests such as the one that is causing this update.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7469">pipeline status</a> for feature branch [PR_7469](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7469). Pipeline [636636361](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/636636361) was triggered at [fb1a361](https://github.com/FreeCAD/FreeCAD/pull/7469/commits/fb1a36159320d1a6bb20e759e2dc90f6efc7090e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7469">pipeline status</a> for feature branch [PR_7469](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7469). Pipeline [636636971](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/636636971) was triggered at [9b322be](https://github.com/FreeCAD/FreeCAD/pull/7469/commits/9b322be497e747d790a25c807406244803c00124). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Is the bug in FreeCAD 0.20. If so, can I backport it for the next 0.20 release? @sliptonic

**Comment by sliptonic** [comment]
I believe the bug was introduced by   https://github.com/FreeCAD/FreeCAD/pull/7185
backporting is both or neither

**Comment by donovaly** [comment]
> I believe the bug was introduced by #7185 backporting is both or neither

OK, So it is part of a new feature then.
Can you please mention the new feature of G73 decomposition here: https://wiki.freecadweb.org/Release_notes_1.0#Path_Workbench

**Comment by LarryWoestman** [comment]
I will update the wiki in the Release notes 1.0 area as soon as I get permission to edit the wiki.  I have started that process.

**Comment by LarryWoestman** [comment]
I have updated the G73 decomposition information in the Release notes 1.0 area.

**Pull request merged**
