### PR TITLE
Added Length property in the Rebar object

### PR DESCRIPTION
**Pull request by amrit3701**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---
This property calculates the total length of the rebar.

### CODE REVIEW

**Comment by amrit3701** [comment]
Forum Link: https://forum.freecadweb.org/viewtopic.php?f=17&t=25298

**Comment by yorikvanhavre** [comment]
I think it would be best to not set obj.Length inside the getBaseAndAxis function, because this can trigger the execute() function again and create an infinite loop. Best is to make all property changes inside the execute() function so it will be run only once.

**Comment by yorikvanhavre** [comment]
Also, in chakkree's idea, there would be two length properties, one is the length of each rebar, and the other one (total length) is the length of the individual rebar multiplied by the number of occurrences of the rebar (basically the length of the placements list). I think both are useful. We could take the opportunity to already implement both, what do you think?

**Comment by amrit3701** [comment]
Hi yorik,

I already did same that you said above. obj.Length is inside the execute function(https://github.com/amrit3701/FreeCAD/blob/0c79b27d758f2ae3c9e90f4e214a4e827704bf17/src/Mod/Arch/ArchRebar.py#L314). Firstly, when I saw a difference in the file changed (https://github.com/FreeCAD/FreeCAD/pull/1082/files#diff-ac142c57b0c3b3cb7987a2613537bf03R314), I amazed that Github show in obj.Length is inside getBaseAndAxis function but after saw a whole file obj.Length is under execute function.

Thanks.

**Comment by amrit3701** [comment]
Yes, both length and total length property are useful. I will send another PR after implementing total length.

**Comment by yorikvanhavre** [comment]
Oh right.. I have been fooled by github's display... Thanks for the addition!

**Comment by yorikvanhavre** [comment]
merged

**Pull request closed without merging**
