### PR TITLE
Update FreeCAD_nl.ts

### PR DESCRIPTION
**Pull request by keuninkske**
small commits to the dutch translations

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ x ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@keuninkske why not through the translation portal that all translators are using ?

**Comment by chennes** [comment]
Thanks for the PR. Unfortunately, we are unable to merge it: all translation work needs to be done through [CrowdIn](https://crowdin.com/project/freecad). The TS files in the git repository get overwritten by CrowdIn data, so manually modifying them won't work... your translations will be lost next time we sync. If you need help getting set up with a CrowdIn account let me know.

**Comment by keuninkske** [comment]
> @keuninkske why not through the translation portal that all translators are using ?

sorry, i was not aware of another system for the translations
although i wanted to contribute to put my stone as a thank you for the free software

i will check out de crowdln
thanks for informing me

**Comment by yorikvanhavre** [comment]
it *might* be possible to bulk-import the changes you did in this pull request to crowdin.. i'm not suree But since it's not much it might be as easy to replicate them there manually

**Pull request closed without merging**
