### PR TITLE
Topo Naming: Improve coding quality

### PR DESCRIPTION
**Pull request by realthunder**
According to suggestion of @chennes

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7534">pipeline status</a> for feature branch [PR_7534](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7534). Pipeline [652506905](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/652506905) was triggered at [03ae3fc](https://github.com/FreeCAD/FreeCAD/pull/7534/commits/03ae3fcfe536890b79a5ed4d0699c109df8a1e9b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7534">pipeline status</a> for feature branch [PR_7534](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7534). Pipeline [652508052](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/652508052) was triggered at [7c5d1c6](https://github.com/FreeCAD/FreeCAD/pull/7534/commits/7c5d1c62df162e6d1e6a31b15df31fd86c1b3316). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks.

I am merging. However, I see several warnings from the CI that we maybe should address: https://github.com/FreeCAD/FreeCAD/pull/7534/commits/7c5d1c62df162e6d1e6a31b15df31fd86c1b3316

**Comment by donovaly** [comment]
> I see several warnings from the CI that we maybe should address: [7c5d1c6](https://github.com/FreeCAD/FreeCAD/commit/7c5d1c62df162e6d1e6a31b15df31fd86c1b3316)

We even must address them since there are now compilation errors:
https://github.com/FreeCAD/FreeCAD/actions/runs/3162974463/jobs/5150092372

@realthunder Can you please have a look?

I fixed meanwhile some minor CI warnings (whitespace etc.)

**Comment by realthunder** [comment]
@donovaly That doesn't seem to be compilation error, but error reported by static analyzer while doing partial compilation I guess. Not sure about root cause though

**Comment by donovaly** [comment]
> @donovaly That doesn't seem to be compilation error, but error reported by static analyzer while doing partial compilation I guess. Not sure about root cause though

OK, so let's ignore it for now.

I merged meanwhile only some clang format updates to the toponaming branch.

Can I have your final OK to announce the branch for testing or do you have further cleanups in the making/planning?

**Comment by realthunder** [comment]
It's good to go. I'll make adjustment/cleanup according to tester reports.

**Comment by donovaly** [comment]
> It's good to go. I'll make adjustment/cleanup according to tester reports.

Great. So I will now trigger the colleagues that we make test builds for the MacOS and Linux so that we can offer test builds when making the announcement.

**Comment by luzpaz** [comment]
JFYI, don't forget that nightly snaps of `development/toponaming` are available for testing.

**Comment by donovaly** [comment]
@luzpaz , great! Can you please send me the link?
Meanwhile I asked Lorenz (looo) to create Conda builds. He replied that he will do this the next days.

**Comment by luzpaz** [comment]
> Can you please send me the link?

Here you go, @donovaly:
```shell
snap refresh freecad --channel='latest/edge/toponaming' # switch to dedicated nightly toponaming snap channel
snap refresh freecad --channel='latest/edge'            # switch back to nightly development snap channel
```

**Comment by donovaly** [comment]
Thanks @luzpaz

For information: the recent commits into the branch fixed the reported build errors for Conda. Later today there will only be a commit that gives builds a dedicated name to avoid that people mix it with the weekly builds.

Then we collect all builds here: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/topo-naming

Eventually the announcement will only by done on the developer's forum because developers are the first target group. This decision was made since we want to sanitize possible issues first before inviting average users.

**Pull request merged**
