### PR TITLE
TechDraw: add units for position

### PR DESCRIPTION
**Pull request by donovaly**
see https://forum.freecadweb.org/viewtopic.php?f=35&t=40608&p=349650#p349650 why it cannot yet be merged

### CODE REVIEW

**Comment by donovaly** [comment]
The patch is now ready to be merged I think.
Many thanks to wandererfan and wmayer for the help!

**Comment by WandererFan** [comment]
Balloon unit test fails with Unit mismatch on OriginX property. 

====================================================================
ERROR: testBalloonCase (TestTechDrawApp.TechDrawTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/TechDraw/TestTechDrawApp.py", line 92, in testBalloonCase
    rc = DVBalloonTest()
  File "/usr/local/Mod/TechDraw/TDTest/DVBalloonTest.py", line 54, in DVBalloonTest
    balloon1.OriginX=view1.X + 20
ArithmeticError: {'sclassname': 'N4Base18UnitsMismatchErrorE', 'sErrMsg': 'Quantity::operator +(): Unit mismatch in plus operation', 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': 'Quantity::operator +(): Unit mismatch in plus operation', 'btranslatable': False, 'breported': True}
----------------------------------------------------------------------

**Comment by donovaly** [comment]
> ## Balloon unit test fails with Unit mismatch on OriginX property. 

I did not get this when I files the PR. Now, with your yesterday's changes, I get this error. I'll have a look, but first tomorrow evening.

**Comment by donovaly** [comment]
>  I'll have a look, but first tomorrow evening.

I had now a close look and after I merged my PR wit master (this PR is now in this merged state) and a recompilation of the complete FC, everything is fine. I also posted in the forum: https://forum.freecadweb.org/viewtopic.php?f=35&t=40608&start=20#p350911

**Comment by donovaly** [comment]
> I had now a close look ...

OK I had to change the test Python script as well. Let's see if Travis is now happy.

**Comment by WandererFan** [comment]
merged

**Pull request merged**
