### PR TITLE
Gui: support toolbar drag and drop to status bar and menu bar

### PR DESCRIPTION
**Pull request by realthunder**
Closes FreeCAD/FreeCAD#12979

### CODE REVIEW

**Comment by PaddleStroke** [comment]
Thanks for bringing in these changes !

Few issues I have noticed : 
1 - The sketcher 'edit mode' toolbar are present all the time in all workbenches : 
image
The only way to remove them is to edit a sketch, which hides them. Then they stay gone until reboot.

2 - There is no way to remove toolbar from the **menubar**. Once a toolbar is dropped in there it cannot be removed. We would need at least the same menu as in the status bar 'Unlock toolbar':
image

3 - The tabbar is oriented South instead of North when dropped in the menu bar : 
image

4 - The tools icon size is relatively big compared to the menu and tabbar which does not look great : 
image
Maybe there are some paddings or margins that could be removed. Or alternatively reducing the icons from 24 to 20px when in menubar or status bar? Here how it would look with 20 px icons : 
image

5 - When dragging to the menubar, if the mouse is too close to the window border, things get weird : 
image
And can get even more weird on some occasions :
image

**Comment by realthunder** [comment]
Add a few fix, please check again.

**Comment by PaddleStroke** [comment]
Thanks!
1, 2, 4 and 5 are fixed.

- 3 is not fixed yet. I think it's just the tab bar that defaults to south so this should be easily fixed.

One more small things :
6 - the preference 'Workbench Selector Position' needs to be removed.
image

- Currently if your corner widget preference is set to right corner, the workbench toolbar does not appear at all, you need to set it back to toolbar and reboot. So if you remove the setting, don't forget to remove where the preference is used as well.

**Comment by realthunder** [comment]
More fix. Please check again.

**Comment by PaddleStroke** [comment]
Thanks all fixed now!

**Comment by Syres916** [comment]
@realthunder please see https://forum.freecad.org/viewtopic.php?p=758767#p758767 regarding new users regression.

**Pull request merged**
