### PR TITLE
Draft: Make featureName attribute translation-independent

### PR DESCRIPTION
**Pull request by marioalexis84**
Currently, the featureName attribute set in Activated() method is translation-dependent, which is error prone due it is used on some logic blocks generating different behaviors depending on the language used in the UI (for instance in Activated method of Arc class).
TODO: Some names aren't appropriate to use as title for the task panel. In the future should be two variables: One associated to the internal name (ex. BezCurve, CubicBezCurve) and another to use in titles (ex. "Bezier curve", "Cubic Bezier curve")

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
That's a really good fix... Much translation-related stuff has been messed up during the big Draft rework in 0.19. I'll give it a careful review before merging. Thanks!!! :pray:

**Comment by marioalexis84** [comment]
There is some more work to do around this.

**Comment by yorikvanhavre** [comment]
I would still want to have the box titles translatable, though, otherwise we just remove an existing functionality for the sake of clarity. I'll try to work a bit on this too when I have a moment

**Comment by yorikvanhavre** [comment]
sorry about the delay.. Ok, good to go!
In any case the translation system of Draft needs a deep look all over again..

**Pull request merged**
