### PR TITLE
Part: Loft, Sweep, Extrude, Revolution, update dialogs to work with A…

### PR DESCRIPTION
**Pull request by mwganson**
…pp::Link objects

https://forum.freecadweb.org/viewtopic.php?f=10&t=66159

### CODE REVIEW

**Comment by jbaehr** [comment]
This seems to introduce quite a lot of duplicated code... Maybe there is a way to extract a shared `getShapeFromFeatureOrLink`?

**Comment by mwganson** [comment]
Where would be the best place to put it?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353">pipeline status</a> for feature branch [PR_6353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353). Pipeline [470452308](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/470452308) was triggered at [f1ff697](https://github.com/FreeCAD/FreeCAD/pull/6353/commits/f1ff697e38d173ea1f30bd4ed45210d15ab64a6c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by mwganson** [comment]
Putting this into draft mode for now.  I want to add a few more dialogs.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353">pipeline status</a> for feature branch [PR_6353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353). Pipeline [471996723](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/471996723) was triggered at [844c111](https://github.com/FreeCAD/FreeCAD/pull/6353/commits/844c1110556822be85ef5db3fc45cd9e226c1d78). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by mwganson** [comment]
I will add a few more dialogs and then mark ready for review.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353">pipeline status</a> for feature branch [PR_6353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353). Pipeline [473755098](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/473755098) was triggered at [4b9eb4c](https://github.com/FreeCAD/FreeCAD/pull/6353/commits/4b9eb4c755ec6d71971a6f1a544d184d57083d35). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353">pipeline status</a> for feature branch [PR_6353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353). Pipeline [473796728](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/473796728) was triggered at [da2deef](https://github.com/FreeCAD/FreeCAD/pull/6353/commits/da2deef505ac72921bb9c79c5a5ed86a3b19b489). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by mwganson** [comment]
Would it be better to break this into separate PR's?  One for each dialog?  I don't intend to add anything else, just fix whatever issues there are to be fixed.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353">pipeline status</a> for feature branch [PR_6353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353). Pipeline [474840305](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/474840305) was triggered at [ddc22f9](https://github.com/FreeCAD/FreeCAD/pull/6353/commits/ddc22f936a8cf77124c8daf00b0b7f92c2280a02). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by mwganson** [comment]
Switching to draft mode.  I want to try to simplify some of the code used.

**Comment by mwganson** [comment]
> This seems to introduce quite a lot of duplicated code... Maybe there is a way to extract a shared `getShapeFromFeatureOrLink`?

I found a way to do it.

Part::TopoShape shape = Part::Feature::getShape(docobj, "", false, 0, 0, true, false);
TopoDS_Shape also works.

Fetches the shape whether docobj is a part::feature or app:link linking to a part::feature.
shape.isNull() if it wasn't a part::feature

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353">pipeline status</a> for feature branch [PR_6353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353). Pipeline [475139147](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/475139147) was triggered at [2eec7c5](https://github.com/FreeCAD/FreeCAD/pull/6353/commits/2eec7c51f5076bf256858a264f9024e41e1b36a0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353">pipeline status</a> for feature branch [PR_6353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6353). Pipeline [475352060](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/475352060) was triggered at [31ac986](https://github.com/FreeCAD/FreeCAD/pull/6353/commits/31ac986118ccebb4edf3fe8a9e2a158a0b3d2c23). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by mwganson** [comment]
Converting to draft.  I need to run a few tests.

**Pull request closed without merging**
