### PR TITLE
[FEM] small gmsh panel tweak

### PR DESCRIPTION
**Pull request by grubertechnic**
small gmsh panel tweak

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by grubertechnic** [comment]
Is something wrong with it? It is a really small change. I do not see any regressions here.

**Comment by benj5378** [comment]
@grubertechnic Sorry, it drowned.

@WandererFan I don't know who is FEM responsible. Can you merge it since it is such a small PR?

**Comment by grubertechnic** [comment]
No Problem. I also have no problem, also when it added past 0.21. Just knowing if something is helpful.

**Comment by benj5378** [comment]
plz keep coding

**Comment by WandererFan** [comment]
@berndhahnebach is the FEM maintainer.

**Comment by benj5378** [comment]
@WandererFan @chennes I know @berndhahnebach is the maintainer, but he is away, so please just merge this, as it's an improvement and is really harmless to merge.

I don't see what we are awaiting or any problem merging it?

**Comment by benj5378** [comment]
@WandererFan @chennes I know @berndhahnebach is the FEM maintainer, but since he is away, please just merge this, as it's an improvement and a very small change. What are we awaiting?

**Comment by grubertechnic** [comment]
It is not that important. I have seen, that there are more lines like this that must be changed.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9569">pipeline status</a> for feature branch [PR_9569](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9569). Pipeline [903572412](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903572412) was triggered at [ac67d93](https://github.com/FreeCAD/FreeCAD/pull/9569/commits/ac67d9328c41744208526054cbaf120e3b9e8536). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by benj5378** [comment]
@luzpaz Why are they ghosting us?

**Comment by berndhahnebach** [comment]
merged

**Pull request merged**
