### PR TITLE
[v0.20][Gui] Consolidate Std view modes

### PR DESCRIPTION
**Pull request by uLeonis**
Consolidates ViewBoxZoom, BoxSelection, BoxElementSelection, MeasureDistance in the aspect of:
- Change the cursor
- Abort via ESC

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
Hi @uLeonis, congrats on your first FreeCAD PR. Did you discuss your code changes on the forum? If so please link to said forum thread. FreeCAD is used by many users so prior to adding features it' important to get community feedback and agreement. That said, we've also been working toward making FreeCAD HiDPI compatible. Any idea how the XPMs you're using look in such an environment ?

**Comment by uLeonis** [comment]
> Hi @uLeonis, congrats on your first FreeCAD PR. Did you discuss your code changes on the forum? If so please link to said forum thread. FreeCAD is used by many users so prior to adding features it's important to get community feedback and agreement. That said, we've also been working toward making FreeCAD HiDPI compatible. Any idea how the XPMs you're using look in such an environment ?

No there is no forum thread about it as I know. Actually, my changes are not intended to add any new feature but consolidate the behavior. In the MeasureDistance feature, the cursor was already changing and leaving the mode via ESC was also there. 
But when using BoxZoom, BoxSelect, BoxElementSelect, there was no feedback about the current state of the view. (Except for a slight change in transparency of the Navigation Cluster) It was also not possible to abort these modes by pressing ESC. 
To abort BoxZoom you had to find out that pressing and releasing the left mouse button without moving the mouse executes the command without changing the zoom. For the selection modes (if you are in the middle of a multi-select pressing Ctrl) the only way to leave selection mode without changing anything was holding Ctrl while clicking on an empty place on the view.
I addressed these two issues with my changes. 
Concerning the cursor XPM I was simply copying the solution from the MeasureDistance feature, where such a cursor definition was already in use.

**Comment by luzpaz** [comment]
Does the Escape button functionality here affect the Preferences -> Sketcher -> General -> 'Esc can leave sketch edit mode' ?

Screenshot_20201222_081352

**Comment by uLeonis** [comment]
Yes, Esc of the sketcher mode (if option enabled) still works as before. If you are in BoxZoom, BoxSelection, BoxElementSelection mode you have to press ESC twice. First to terminate the selection mode and 2nd to leave the sketcher mode. 
BTW in sketcher mode all those commands are active, but selecting in sketcher mode works a bit different in the sense that box select is always active by default. (Press right mouse button and drag a rectangle) I'm not sure if it would be better to disable BoxSelect and BoxElementSelect in Sketcher mode, also because these command do not select sketcher drawing elements, but elements of the model tree. But that's may be for a next improvement. But BoxZoom command is perfectly valid in sketcher mode and here it works too.

**Comment by wwmayer** [comment]
Postpone this PR for v0.20 development as this requires special testing on HighDPI monitors.

**Comment by yorikvanhavre** [comment]
Will give this a test spin and merge.

**Comment by yorikvanhavre** [comment]
This seems to work fine. Great job! Sorry for the delay in merging...

**Pull request merged**
