### PR TITLE
Path: Fixes #6693 - Add Z and K values to arc commands

### LINKED ISSUE #6693: [Bug] LeadInOut dressup breaks simulator
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

None

### Version

0.20 (Development)

### Full version info

```shell
[code]
OS: Linux Mint 20 (i3/i3)
Word size of FreeCAD: 64-bit
Version: 0.20.28560 +1 (Git)
Build type: Unknown
Branch: bug/2TCspinspeed
Hash: a8a72cf04b9fa47216e0b09cd9dec070182822a2
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, OCC 7.5.2
Locale: English/United States (en_US)
Installed mods: 
  * FeedsAndSpeeds 0.1.0
[/code]
```

### Subproject(s) affected?

_No response_

### Issue description

The LeadInOut dressup logic is quite messy.  It adds path commands in a modal style.  In other words it will add a command like G0 Z10 and not explicitly state the other coordinates.  
The simulator has a problem with this and will throw an error, usually in performvoxelcut.

### Anything else?

```
12:38:37  Traceback (most recent call last):
12:38:37    File "/home/brad/FCD/FC/Mod/Path/PathScripts/PathSimulatorGui.py", line 418, in PerformCut
12:38:37      self.PerformCutVoxel()
12:38:37    File "/home/brad/FCD/FC/Mod/Path/PathScripts/PathSimulatorGui.py", line 364, in PerformCutVoxel
12:38:37      dz = (cmd.z - self.curpos.Base.z) / n
12:38:37  TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Russ4262**
Adds missing Z and K values to arc commands.
No forum discussion. Fixes #6693

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6760">pipeline status</a> for feature branch [PR_6760](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6760). Pipeline [518167457](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/518167457) was triggered at [d0e18ab](https://github.com/FreeCAD/FreeCAD/pull/6760/commits/d0e18aba6d36d845ca590ed8e152338a89d60d90). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Russ4262** [comment]
Build failed for a reason I cannot identify easily from the build report.  Will rebase or otherwise trigger another build.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6760">pipeline status</a> for feature branch [PR_6760](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6760). Pipeline [518257006](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/518257006) was triggered at [56cc4b3](https://github.com/FreeCAD/FreeCAD/pull/6760/commits/56cc4b399cf6da9001c09790158f38fcffb565b1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Russ4262** [comment]
After some more reading on the forum and running some tests, I do mot think this PR fully addresses #6693 in its entirety. Therefore,  closing.

**Comment by Russ4262** [comment]
Think I found the problematic code for the related Lead In/Out missing `G1` feed rate as identified in forum thread at [LeadInOut Dressup missing feed rate](https://forum.freecadweb.org/viewtopic.php?f=15&t=68267).  Therefore, I am reopening this PR and going to add a commit for a fix for the feed rate issue.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6760">pipeline status</a> for feature branch [PR_6760](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6760). Pipeline [567235118](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567235118) was triggered at [56cc4b3](https://github.com/FreeCAD/FreeCAD/pull/6760/commits/56cc4b399cf6da9001c09790158f38fcffb565b1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Russ4262** [comment]
@sliptonic 
I reopened this PR and added a commit to address the missing feed rate for the `G1` layer command.  This PR should now address both existing issues related to the Lead In/Out dressup.  This PR would then be a good candidate for the first minor bug-fix release for 0.20

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6760">pipeline status</a> for feature branch [PR_6760](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6760). Pipeline [567238205](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/567238205) was triggered at [8edc9b1](https://github.com/FreeCAD/FreeCAD/pull/6760/commits/8edc9b142d1e60c01f8bc7615f6151060431d298). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
