### PR TITLE
[TechDraw] Issue #5903 - Autofill template information

### PR DESCRIPTION
**Pull request by pavltom**
This pull request is an initial implementation of issue #5903, which suggests automatic filling of basic editable fields in the technical drawing templates. As this is an enhancement, I will try to cover the design decisions, so they can be discussed and the final behavior eventually improved or changed.

1. New **freecad:autofill** attribute in FreeCAD SVG namespace
The **freecad:editable** attribute is used to mark editable texts in the SVG templates. The value of this attribute is used in the "Change Editable Field" dialog as the text name and in the national versions of the templates it is localized. Thus the value of this attribute would be very tricky to use for identification what should be filled in. In this light I propose to introduce a new FreeCAD SVG attribute **freecad:autofill**, which will determine the value the field should obtain on a blank page.

2. Basic autofilled fields and their values
At the moment, not all editable fields can be automatically filled. Some would require nontrivial application enhancements, therefore this pull request implements only the values currently available. Of course, it is counted with future additions and these should be easily implemented.
- **Author** (Created by) field: Adding to a SVG text element freecad:autofill="**author**" attribute triggers inserting into the field the value of Preferences->General->Document->Author name. Another option would be the value of "Created By" property of the current document, but because the 3D model could be provided by a different person than the one creating the technical drawing, my proposal uses the preferences value, as this denotes the actual **drawing author**. If the preference value is empty, the default template value is kept.
- **Date** field: Marked by freecad:autofill="**date**", this instructs to insert the current date. The date should correspond to the current time zone (not a UTC date) and will be formatted by currently selected locale in the _short_ format. The selected locale is driven by the Preferences->General->General->Number format dropdown. Therefore it is possible to have FreeCAD UI texts in English, but the inserted date will be in the national format, like the dimensional values. Another option would be inserting the date string according to ISO 8601 ("YYYY-MM-DD" format), but my feeling is the localized variant is the preffered one. For sure, it is not difficult to implement e.g. "date-iso" attribute value to provide this functionality.
- **Organization** (Company) field: Marked by freecad:autofill="**organization**", inserts the value of Preferences->General->Document->Company. Again, current document's "Company" property could be used, but see _Author_ value for the reasoning. If the preference value is empty, no action is invoked.
- **Scale** field: Marked by freecad:autofill="**scale**", inserts the default page scale in the "X : Y" format, where X/Y is the fraction representation of the scale value. While the decimal representation could be used as well, I have never encountered a drawing using it. Again, it is very easy to add e.g. "scale-decimal" attribute value to implememt this behavior.
- **Sheet** field: Marked by freecad:autofill="**sheet**", inserts the page order position in the "X / Y" format. The implementation is rather tricky and may need some adjustments or complete revision. The **Y** number is the total number of TechDraw pages in the document. The **X** number is the order of the new page Label (which is usually something like _Page00x_), in the (according to locale) sorted array of all TechDraw page labels. This may or may not be a good decision, my feeling was it is better than nothing.
- **Title** field: Marked by freecad:autofill="**title**", inserts the as the drawing title the value of the current document's Label property. Another options are "Id" or "Comment" properties of the current document, but from my point of view the label makes the most sense.

3. The updated templates
In this pull request, I have modified the two main templates to demonstrate the new feature. First one is the FreeCAD's default "**A4_LandscapeTD.svg**" template, but because the ISO templates do not contain Organization/Company fields, I have also added the "**ANSIC_Landscape.svg**" template, which contains all the implemented autofilled fields. Adding the autofill attributes to all (possibly localized) templates is out of scope of this pull request.

I hope you will find the implementation useful, as always some parts can be done better, some other parts may be done differently and some bugs may be fixed. In all cases, please let me know, so we can accomplish the most suitable solution.

### CODE REVIEW

**Comment by ab0v3g4me** [comment]
I would definitely add a `freecad:autofill="mass"` to this list of parameters. All parts have mass and the reason why it's not grouped with material properties is because you can have assemblies hence the parameter can be independent of the material.
 
What happens if you send a file to another person that has different parameters, does the drawing update for that person upon opening? Should an option be added like `Sync parameters` so the other person can do that if needed?

**Comment by WandererFan** [comment]
https://forum.freecad.org/viewtopic.php?t=86165

**Comment by pavltom** [comment]
For my reply to @ab0v3g4me  please see the [forum topic](https://forum.freecad.org/viewtopic.php?p=747697#p747697) above created by @WandererFan

**Comment by WandererFan** [comment]
I had hoped for some discussion about how this might impact the other two initiatives that try to update the template.  Since there was no input, I am merging this.

**Comment by croicheck** [comment]
Hello, I don't know if this belongs in here, but I always wanted to have the possibility to have a system of sth. like dynamic variables.
E.g. in tech draw you set a dynamic variable and for its value you click on a specific parameter under the feature tree.
This sets a link and in the tech draw it will always show the value of the parameter.

The auto-fill approach makes absolute sense to me, this dynamic var thing is meant as additional feature.

If this is too crazy, I suggest at least fields in the document parameters for standard things like drawing no., article no., description, revision, etc. and have these auto-filled in tech draw if parameters are set.

**Comment by pavltom** [comment]
Hi @croicheck, would You mind posting Your comment to this forum thread: [https://forum.freecad.org/viewtopic.php?t=86165](https://forum.freecad.org/viewtopic.php?t=86165) ? This PR is already closed now, but we can discuss the new enhancements on the forum.

**Comment by croicheck** [comment]
> Hi @croicheck, would You mind posting Your comment to this forum thread: https://forum.freecad.org/viewtopic.php?t=86165 ? This PR is already closed now, but we can discuss the new enhancements on the forum.

Hi @pavltom, just posted it there: https://forum.freecad.org/viewtopic.php?t=86165

**Comment by maxwxyz** [comment]
@pavltom is this the dialog? 
grafik

<details><summary>Windows 11</summary>
<p>

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36677 (Git)
Build type: Release
Branch: main
Hash: 3fadb1f40bdfa4ee1c61acbf12fbe44680723965
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.4
  * CurvedShapes 1.0.8
  * Curves 0.6.29
  * Defeaturing 1.2.2
  * fasteners 0.5.15
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.9

``` 

</p>
</details>

**Pull request merged**
