### PR TITLE
Part/Toponaming: tests for MapperHistory

### PR DESCRIPTION
**Pull request by CalligaroV**
this PR adds the tests for the struct `MapperHistory`, its constructors and its methods

### CODE REVIEW

**Comment by CalligaroV** [comment]
In draft until it's added the test for the `modified` method

**Comment by chennes** [comment]
Looks like older OCCT doesn't have `History()` -- what version was it added in?

**Comment by bgbsww** [comment]
Uh, https://dev.opencascade.org/doc/occt-7.5.0/refman/html/class_b_rep_algo_a_p_i___builder_algo.html seems to have it.  Confused.

**Comment by CalligaroV** [comment]
Doing a blame it looks 6 years ago, before version 7.4.0.

I'm compiling with 7.6.3, same as [here](http://ppa.launchpad.net/freecad-maintainers/occt-releases/ubuntu)
Shouldn't the CI do an `apt update` before compiling?

**Comment by chennes** [comment]
We currently support compiling with OCCT 7.3 -- so if there is something here that doesn't support that, we'll have to find a way to code around it (even if that means we disable that chunk of TNP code on those old platforms).

**Comment by CalligaroV** [comment]
Did a little bit of research (using RT branch as reference).

The toponaming methods that need something with an `History()` looks like they initialize `MapperHistory` with `ShapeFix_Shape` (and access to the history using `Context()->History()`) or with `BRepTools_History`.

In both cases there will be an history also with OCCT 7.3.0.

For the methods that use `MapperMaker` there's no history and in those cases the `modified` and `generated` methods of that class call the related OCCT methods for the various classes used to initialize the `MapperMaker` objects (for example `BRepFeat_MakePrism`).

Also in those cases the Modified and Generated methods are available for those classes with OCCT 7.3.0.

Summarizing, no action needed except modifying the test to use another class that has an history or creating one and populate it manually.

Beside that, can you too please give a look at the imported/original code and see if I missed something?

**Comment by CalligaroV** [comment]
Consequence of what I wrote on the previous comment:

As `MapperHistory` is initialized only with `ShapeFix_Shape` and it's history is rebuilt every time that there's a call to `Context()->History()`, there won't be anything about generated shapes (no methods like `Generated` are called within `History()`, only `Modified` and `Remove`)

Therefor I would say that it makes no sense to test `MapperHistory::generated()` as the result will always be 0 when used for TopoNaming.

What do you think?

**Comment by bgbsww** [comment]
I think that if MapperHistory::Generated() does something other than return zeroes, that will be based on code we haven't transferred yet ( or even read ).  So I think these tests are fine, and we can revisit if we discover more.

**Comment by CalligaroV** [comment]
> I think that if MapperHistory::Generated() does something other than return zeroes, that will be based on code we haven't transferred yet ( or even read ). So I think these tests are fine, and we can revisit if we discover more.

Yes, indeed you're right.

Looking again RT code i found a method in the class `WireJoiner` that populates a `BRepTools_History` object so I did a similar thing for the test.

The `WireJoiner` class isn't imported yet but probably it will be better to do that soon, within `makeElementWires` related tasks.

**Pull request merged**
