### PR TITLE
Fix incremental update of Version.h using Ninja

### PR DESCRIPTION
**Pull request by adrianinsaval**
fixes https://github.com/FreeCAD/FreeCAD/discussions/9606

### CODE REVIEW

**Comment by luzpaz** [comment]
Does it also fix #5945

**Comment by adrianinsaval** [comment]
No but I have something in mind for that one once I get the ppa revived

**Comment by 0penBrain** [comment]
Well, it seems there are some problem there.

I tested having the main branch to 1338385080.
I built the main.
Then I have this PR in a "PR11396" branch.
When I switch from main to this latter branch, and try to run a build, I get a `ninja: no work to do.` and nothing is built while there is some diff in between both branches (there is at least SHA, but there is actually lot more).

**Comment by 0penBrain** [comment]
OK sorry. After pruning my project and building from scratch, problem disappeared. May be a glitch on my side.

However I'm hesitating to merge as there is a problem now in the main. While I'm currently compiling 0ac0882eeb4e3390aef464e1807a3631c5f2e858 , version info tells me it's f30e643c828cbc901377184e752619253308b4f1 .

I have no clue why and maybe there is something to be fixed first before this PR can be thoroughly tested again.

**Comment by 0penBrain** [comment]
Last test for today probably. The PR actually doesn't solve problem in following situation:
 * checkout this PR and clean build => OK, SHA is correct
 * add a single comment in a file and commit the change
 * Build => NOK, the SHA is stuck on previous one

**Comment by wwmayer** [comment]
See:
ae27d8e3bc4c6
3b7da50ca7d0f

**Comment by adrianinsaval** [comment]
yeah I think this didn't actually fix it, I had tested between the previous commit and my own commit and it had worked, but probably because the target name changed. Later runs then don't work

**Comment by FlachyJoe** [comment]
Note the easiest way to get the correct version is to run `rm src/Build/Version.h && ninja` instead of `ninja`. It re-links at most 61 unchanged files and takes very few more time.

**Pull request closed without merging**
