### PR TITLE
Draft: better check for Gui object

### LINKED ISSUE #17342: Draft: CLI: Labels broken in documents stored in headless
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When a FCStd is stored headless mode without GUI (for example from FreeCADCmd) then Draft labels get broken - permanently

When opening the file in FreeCAD and recomputing the following error happens:

```
15:16:34  v0.19, dLabel, added view property 'ScaleMultiplier'
15:16:34  v0.19, dLabel, added view property 'AnnotationStyle'
15:16:34  pyException: Traceback (most recent call last):
  File "/mnt/slow1/src/FreeCAD/main/Mod/Draft/draftobjects/label.py", line 227, in onDocumentRestored
    super().onDocumentRestored(obj)
  File "/mnt/slow1/src/FreeCAD/main/Mod/Draft/draftobjects/draft_annotation.py", line 69, in onDocumentRestored
    self.add_missing_properties_0v19(obj, vobj)
  File "/mnt/slow1/src/FreeCAD/main/Mod/Draft/draftobjects/draft_annotation.py", line 81, in add_missing_properties_0v19
    vobj.Proxy.set_annotation_properties(vobj, vobj.PropertiesList)
<class 'AttributeError'>: 'NoneType' object has no attribute 'set_annotation_properties'
```
It seems the label relies on properties stored with the viewprovider that can't be re-generated. These should not be in the viewprovider in the first place but in the Data object.

for reproduction details see #17340

[bigmess.zip](https://github.com/user-attachments/files/17445430/bigmess.zip)

### Full version info

```shell
OS: Ubuntu 20.04.6 LTS (XFCE/xfce/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38991 +37 (Git)
Build type: Debug
Branch: fixBooleans,debugTolerance
Hash: c3068fee8082c905a9bf50e284cd8f9b23f0e19c
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

Draft

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yorikvanhavre**
fixes #17342

### CODE REVIEW

**Comment by AIRCAP** [comment]
This does not fix the issue it seems.

On opening the file saved in CLI, the label still breaks with

```
Traceback (most recent call last):
  File "/mnt/slow1/src/FreeCAD/main/Mod/Draft/draftobjects/label.py", line 237, in onDocumentRestored
    self.update_properties_0v21(obj, vobj)
  File "/mnt/slow1/src/FreeCAD/main/Mod/Draft/draftobjects/label.py", line 241, in update_properties_0v21
    old_fontname = vobj.TextFont
<class 'AttributeError'>: 'Gui.ViewProviderDocumentObject' object has no attribute 'TextFont'
```

**Comment by Roy-043** [comment]
Similar code occurs in other places as well. We should check those as well I think.

**Comment by yorikvanhavre** [comment]
I think we would need a general assessment on restoring ViewProviders all across Draft...

@AIRCAP does Roy's commit above solve the issue for now?

**Comment by yorikvanhavre** [comment]
I think this has become more than just a bug fix... I'll reschedule it for after 1.0

**Comment by chennes** [comment]
@AIRCAP can you take another look and see if it's working now?

**Comment by maxwxyz** [comment]
@AIRCAP ping

**Comment by maxwxyz** [comment]
@AIRCAP bump

**Comment by maxwxyz** [comment]
waiting for review

**Pull request merged**
