### PR TITLE
fix Expressions assignment for FreeBSD

### PR DESCRIPTION
**Pull request by moench-tegeder**
Just like Apple, FreeBSD uses clang as it's main compiler, and thus
runs afoul of the same problem in src/App/PropertyExpressionEngine.cpp
like Apple (issue #5281): "error: no viable overloaded '='".
Extend the fix from #5281 for the BSDs (check macro FC_OS_BSD) -
at least OpenBSD uses clang, too (maybe this check should be reworked
to test for clang, but I can't test on Apple, so let's keep this fix
minimalistic).

References: #5281

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7032">pipeline status</a> for feature branch [PR_7032](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7032). Pipeline [564878385](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/564878385) was triggered at [72d7780](https://github.com/FreeCAD/FreeCAD/pull/7032/commits/72d77809d1b33dce1fc7cb1b032ce6e6d793a23b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@moench-tegeder Thanks for the fix! Are you involved with the FreeCAD FreeBSD port ? That was one of the first packages that upgraded to v0.20. If so, thank you for being so 'Johnny-on-the-spot'!

**Comment by moench-tegeder** [comment]
> @moench-tegeder Thanks for the fix! Are you involved with the FreeCAD FreeBSD port ? That was one of the first packages that upgraded to v0.20. If so, thank you for being so 'Johnny-on-the-spot'!

https://github.com/freebsd/freebsd-ports/commit/21a1b657eea111bc0864c10754fabc5e55728c39
Yeah, it's me, your neighbourhood FreeBSD maintainer.

**Comment by luzpaz** [comment]
Thank you for all your work!

**Pull request merged**
