### PR TITLE
Add readNastran95() function in FemMesh.cpp

### PR DESCRIPTION
**Pull request by ceanwang**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

See talk at https://forum.freecadweb.org/viewtopic.php?f=18&t=51569

### CODE REVIEW

**Comment by luzpaz** [comment]
It would be better if the commits were more elaborately named. It helps when reading the commit history. 
`FEM: add readNastran95() to header to FemMesh.h`  
`FEM: add readNastran95() to FemMesh.cpp`  
etc....

**Comment by ceanwang** [comment]
How do I separate the first 3 commits with the second 2 commits? 

The second 2 is talked here https://forum.freecadweb.org/viewtopic.php?f=10&t=46317&start=10

**Comment by luzpaz** [comment]
@ceanwang it looks like they are 2 separate issues. Lemme see if I can help.

**Comment by luzpaz** [comment]
@ceanwang you made a few `git` mistakes. One of the cardinal ones is never to work on the `master` branch. Instead, you create a **new branch** that **branches from the latest master** and give it a name. Then you work on that branch until you are done. When you're ready, you make PR **against the master** branch.  Does that make sense?

I've pulled the changes, modified some stuff, and then push them to separate branches in to my remote repo:
https://github.com/luzpaz/FreeCAD/tree/ceanwang-nastran  
https://github.com/luzpaz/FreeCAD/tree/ceanwang-python-console-run-py-file

**Comment by ceanwang** [comment]
@lazpaz I forked from the master, made my change and then raised the PR. Do you mean my one should not have a link to the master, looks like formed a loop between the two.

**Comment by luzpaz** [comment]
> I forked from the master, made my change and then raised the PR. Do you mean my one should not have a link to the master, looks like formed a loop between the two.

See https://wiki.freecadweb.org/Source_code_management#Git_development_process

**Comment by berndhahnebach** [comment]
the repo of ceanwang is no longer available. @luzpaz Would you go for a new PR, set it to 0.20, add the label FEM to it and reference it from here.

cheers bernd

**Comment by luzpaz** [comment]
@ceanwang care to re-up?

**Comment by berndhahnebach** [comment]
> https://github.com/luzpaz/FreeCAD/tree/ceanwang-nastran
> https://github.com/luzpaz/FreeCAD/tree/ceanwang-python-console-run-py-file

I still have them in my remotes. But they do not rebase on master :-(

**Comment by luzpaz** [comment]
@ceanwang please follow up

**Comment by ceanwang** [comment]
These have already been merged.  You can use it with FreeCAD 0.19.23970 at least.

**Comment by luzpaz** [comment]
That's right, I forgot I saw that wmayer merged in 5903ff442657e7b6630d5867374adb62924037d8

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/compare/59ec3cb141e3...5903ff442657

**Pull request closed without merging**
