### PR TITLE
[OpenSCAD] Fix colors not working correctly when polygons are extruded

### PR DESCRIPTION
**Pull request by helaslo**
When importing OpenSCAD models, colors sometimes disappear, especially when using for loops and dxf imported polygons with linear extrude.
This commit fixes that, I don't know if its the best way, but basically it saves every set color, then loops over all groups, and if a group member doesn't have any set colors yet, it will change the color to the groups, then it hides the group the prevent single faces having the wrong colors.

Demo files are available in this [gist](https://gist.github.com/helaslo/074259a2c7b6d0b0f89025080dfc33a9)

Here it is how they shall render according to OpenSCAD
openscad_render

Here it is how they render with the latest version of FreeCAD
without_patches

And here it is how they render with the patches applied
with_patches

### CODE REVIEW

**Comment by luzpaz** [comment]
@KeithSloan care to review? :smiley:

**Comment by yorikvanhavre** [comment]
Marking for 0.19 if CI tests pass

**Comment by yorikvanhavre** [comment]
Tests still fail.. I'll reschedule this for after the release as we try to get it out today.

**Comment by helaslo** [comment]
Shall I change something?
Asking because the tests fail at the configuring phase, if I see it right, because they can't find boost, and I didn't even touch that part.

**Comment by wwmayer** [comment]
I am testing it locally right now and if it works I will merge it.

**Comment by wwmayer** [comment]
I don't know what to do with the linked dxf file to test this PR. I have expected to get a .scad or .csg file instead.

**Comment by helaslo** [comment]
There are multiple files, you can download them all via the top right "Download ZIP" button

**Comment by wwmayer** [comment]
OK, found it. When opening the demo.scad in OpenSCAD it looks like in your screenshot but when I try to load it in FreeCAD I get this lengthy output but an empty document:
```
ImportCSG Version 0.6a
Start Lex
End Lex
Load Parser
Parser Loaded
Start Parser
Vector
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'circle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : circle.dxf Layer : 
Process DXF file
File Name : circle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/circle.dxf
Vector
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'circle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : circle.dxf Layer : 
Process DXF file
File Name : circle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/circle.dxf
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'circle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : circle.dxf Layer : 
Process DXF file
File Name : circle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/circle.dxf
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'circle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : circle.dxf Layer : 
Process DXF file
File Name : circle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/circle.dxf
Vector
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'circle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : circle.dxf Layer : 
Process DXF file
File Name : circle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/circle.dxf
Vector
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'circle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : circle.dxf Layer : 
Process DXF file
File Name : circle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/circle.dxf
Vector
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'circle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : circle.dxf Layer : 
Process DXF file
File Name : circle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/circle.dxf
Vector
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'triangle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : triangle.dxf Layer : 
Process DXF file
File Name : triangle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/triangle.dxf
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'triangle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : triangle.dxf Layer : 
Process DXF file
File Name : triangle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/triangle.dxf
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'triangle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : triangle.dxf Layer : 
Process DXF file
File Name : triangle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/triangle.dxf
Vector
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'triangle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : triangle.dxf Layer : 
Process DXF file
File Name : triangle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/triangle.dxf
Vector
Vector
Vector
Vector
Vector
Matrix
('height', '5')
('center', 'false')
('convexity', '1')
2d Point
('scale', [1.0, 1.0])
('$fn', '0')
('$fa', '12')
('$fs', '2')
('file', 'triangle.dxf')
('layer', '')
2d Point
('origin', [0.0, 0.0])
('scale', '1')
('convexity', '1')
('$fn', '0')
('$fa', '12')
('$fs', '2')
('timestamp', '1614023138')
Import File
Importing : triangle.dxf Layer : 
Process DXF file
File Name : triangle
Layer : 
PathName : /tmp/download
DXF Full path : /tmp/download/triangle.dxf
End Parser
None
End processing CSG file
```

**Comment by helaslo** [comment]
I suspect maybe OpenSCAD is generating a wrong intermediate file.
Does any other `.scad` file work?
Also if it is not a big problem, can you apply [this patch](https://gist.githubusercontent.com/helaslo/8c6172216bcfcccc24f0c1f5c653454e/raw/274f7d757db627eedbcd8696f772f14525e3a2dc/csg_test.patch), then send the file `/tmp/csgDebug.csg`?

**Comment by wwmayer** [comment]
No, I couldn't get working any other .scad file either. Might be the OpenSCAD version the problem?
> OpenSCAD version 2019.05

> Also if it is not a big problem, can you apply this patch, then send the file /tmp/csgDebug.csg

The content is exactly the same as in demo.scad.

When switching to the OpenSCAD workbench there is a function with the OpenSCAD symbol. When I run it a text box pops up where I can enter some OpenSCAD code. If I enter this snippet it only prints something to the output window but doesn't create an object:
```
color("red")
{
    linear_extrude(5) import(file = "/tmp/download/circle.dxf");
}
```
As soon as I set the "as Mesh" option it creates at least a mesh.

**Comment by helaslo** [comment]
Sorry, I was wrong, please replace the line
```
        copyfile(filename, "/tmp/csgDebug.csg")
```
with
```
        copyfile(tmpfile, "/tmp/csgDebug.csg")
```

**Comment by wwmayer** [comment]
This is the generated file: (I replacde the file extension so that GH accepts it)

[csgDebug.txt](https://github.com/FreeCAD/FreeCAD/files/6043212/csgDebug.txt)

**Comment by helaslo** [comment]
Can you try updating your OpenSCAD?
Also here is my CSG file 
[csgDebug.txt](https://github.com/FreeCAD/FreeCAD/files/6043335/csgDebug.txt)

**Comment by wwmayer** [comment]
I think I found the issue. On this machine I use the built-in dxf importer while on my other machine I use the external Python library. With the latter it works and I can confirm that your PR fixes the colors.

So, it's good to merge now and about the dxf importer issue I have to investigate what exactly is the problem.

Many thanks for your assistance!

**Comment by wwmayer** [comment]
The problem was that the dxf Python library was very old and probably wasn't ported to Py3. Unfortunately, the scad importer suppresses the raised exceptions so that it is impossible to see why it failed.

**Comment by luzpaz** [comment]
Off-topic: @helaslo do you have any more openscad fixes in the pipeline?

**Comment by helaslo** [comment]
At the moment, no, I don't fully understand the workings yet, but I've got a problematic model where one side still doesn't render correctly, I will try to fix that, but I have no idea what can cause that but will look into that in the future.
Is there any known problem I shall check?

**Comment by luzpaz** [comment]
To name a few:  
* https://tracker.freecadweb.org/view.php?id=3626  
* https://tracker.freecadweb.org/view.php?id=4353

**Comment by helaslo** [comment]
Right now I can't promise anything, but I will look into them in the future If I have time.

**Pull request merged**
