### PR TITLE
Addon Manager: Switch to using QWebEngineView for README

### PR DESCRIPTION
**Pull request by chennes**
Take Two -- some different design decisions this time. The basic idea is to use QWebEngineView (which is basically a fork of Chromium) to display the README and Macro Wiki Page content, since that content is really web-based and makes sense in a web browser. However, it is not intended as a general purpose web browser: almost all links you click on will ask the system to open its default web browser, the same way the original version did. The only exception is FreeCAD wiki pages, which this web view will render.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5458">pipeline status</a> for feature branch [PR_5458](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5458). Pipeline [459054347](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/459054347) was triggered at [4c6bae8](https://github.com/FreeCAD/FreeCAD/pull/5458/commits/4c6bae83cc613d18b08f4463edfe1e1906f2b242). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5458">pipeline status</a> for feature branch [PR_5458](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5458). Pipeline [459369082](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/459369082) was triggered at [92b0df7](https://github.com/FreeCAD/FreeCAD/pull/5458/commits/92b0df70991a4cbd1167c26bb384b25fd681f213). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5458">pipeline status</a> for feature branch [PR_5458](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5458). Pipeline [459527779](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/459527779) was triggered at [062b23a](https://github.com/FreeCAD/FreeCAD/pull/5458/commits/062b23a7e441370c65eda32b591be33c4303f697). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Not sure how to fix the conflict... Can you have a look @chennes ? I'd like to test this!

**Comment by chennes** [comment]
@yorikvanhavre Rebased, conflict should be gone now. Thanks for testing!

**Comment by yorikvanhavre** [comment]
"Rock 'n roll"

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5458">pipeline status</a> for feature branch [PR_5458](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5458). Pipeline [461151121](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/461151121) was triggered at [57f9364](https://github.com/FreeCAD/FreeCAD/pull/5458/commits/57f9364a4e14393db06d442d08979f63ccf0a92f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
That predated me, but I felt like I had to leave it in 😄

**Comment by yorikvanhavre** [comment]
I gave it a test spin, pretty cool! One little thin I would do is add some padding so there is a little space between the HTML text contents and the widget border:

Screenshot from 2022-02-02 12-43-10
:

**Comment by chennes** [comment]
Good idea -- I've added 1em of padding inside the whole body in the cases where we are extracting the article element and reparenting it. This appears to work well for the four known git hosts.

**Pull request merged**
