### PR TITLE
Refactoring viewer settings

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8338">pipeline status</a> for feature branch [PR_8338](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8338). Pipeline [766914802](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/766914802) was triggered at [f41f3e4](https://github.com/FreeCAD/FreeCAD/pull/8338/commits/f41f3e4ae299cc8b13390210640e3f4968036338). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks! So updating the view for all views was that easy that it is embarassing for me. 
Also thanks for the fix that the cube was recreated also when not desired to be shown.

Can this be merged? From my side, looks fine.

**Review by donovaly — APPROVED** [review]

**Comment by wwmayer** [comment]
Yes, it's ready for merge.

**Comment by donovaly** [comment]
> Yes, it's ready for merge.

OK.

I don't know how you was involved in the recent discussion to directly commit. Since I could not come to Brussels, I was also not finally involved, but I triggered the discussion.
What i take out of it is that one can merge own PRs and it is up to the developer to wait for others if nothing is controversial. So for example Wandererfan merges his own work after half a day or so if nobody objects, Abdullah will do so as well. I will force myself to wait for non FEM-stuff. For the FEM stuff I will act as Wandererfan acts since Bernd is currently not available.

If you feel I am moving to quick or put in unmature stuff, please shout. I know my weak points of sometime being too fast. This is when I get negative user feedback and the NaviCube was such a thing. I was proud to introduce FreeCAD to a new colleague and on his Win 11 PC the cube looked pixeled and this is what people see as first. Then I tried FC on my new Win 11 laptop and it looked poor as well.

By the way, could you please have a look at my pending SectionCutting PR? As promised, I will refactor it after the PR is in. In the meantime people can give it a try and the section cutting for assemblies is something I often got as feedback what FC misses.

**Comment by wwmayer** [comment]
> I don't know how you was involved in the recent discussion to directly commit.

I was asked if locking master for direct commits is OK for me and I agreed.

> Since I could not come to Brussels, I was also not finally involved, but I triggered the discussion.

I wasn't there either.

> What i take out of it is that one can merge own PRs and it is up to the developer to wait for others if nothing is controversial.

Good to know. So, I will merge own PR for simple things, too.

> If you feel I am moving to quick or put in unmature stuff, please shout.

I am not proactive on PR. If it's addressed to me then notify me. But note that I have switched off any email notifications in GH and I am not looking at my notification list every day. So it can take a few days until I see it. If it's something urgent then write me a PM on the forum.

> By the way, could you please have a look at my pending SectionCutting PR?

This one #8252 ?

**Comment by donovaly** [comment]
> I am not proactive on PR. If it's addressed to me then notify me. But note that I have switched off any email notifications in GH and I am not looking at my notification list every day.

Good to know. Maybe there is a setting that you get an email when there is a request to review a PR. For example, this PR needs your quick review: #8247
It would be good if some of the core developers request a review from you, you get a notification. Since only few persons can do the request, there should not be many messages.

> > By the way, could you please have a look at my pending SectionCutting PR?
> 
> This one #8252 ?

Yes. As said, this PR is for now only for the new functionality, The rewrite will be done while it is merged and people can test (because I expect like for the last times some valuable feedback)

p.s. I will send you a private forum message regarding something we are discussing in the core team.

**Comment by wwmayer** [comment]
> It would be good if some of the core developers request a review from you, you get a notification. Since only few persons can do the request, there should not be many messages.

I couldn't find a specific setting to allow this.

**Comment by donovaly** [comment]
> I couldn't find a specific setting to allow this.

Too bad. I googled now around again and it seems such an option does not exist.

Besides this, can you please have a look at the private message I sent you via the forum?

**Pull request merged**
