### PR TITLE
[TechDraw] Add 'getPage' Python API ; returns page from view

### PR DESCRIPTION
**Pull request by 0penBrain**
This PR adds a new 'getPage' functions in TechDraw ViewProviderPage.
It uses this function to add a 'getPage' Python API that returns from a TechDraw MDIView that DrawPage being displayed

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum => n/A
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805` => N/A

### CODE REVIEW

**Comment by 0penBrain** [comment]
@yorikvanhavre : thanks, that was a good challenge and finally less pain than previous time. :)
I implemented as I did #4842 so 'getPage()' returns a TechDraw page (DrawPage) object directly and not the viewprovider.

**Comment by yorikvanhavre** [comment]
You are a hero! :D
Thanks!!

**Comment by 0penBrain** [comment]
@yorikvanhavre Maybe that's a bit too much :D
Do you know if this is kind of things that shall be documented somewhere ?

**Comment by yorikvanhavre** [comment]
Not really... When writing python bindings, the most important is to write a good docstring (you did this). At some point we need a better automatic doctool like we currently use on https://freecadweb.org/api that will correctly gather all this in a nice user-friendly documentation

**Comment by luzpaz** [comment]
:pray:

**Pull request merged**
