### PR TITLE
Spreadsheet: different improvements on Merge/Split functions

### PR DESCRIPTION
**Pull request by 0penBrain**
https://forum.freecadweb.org/viewtopic.php?f=3&t=67969

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6748">pipeline status</a> for feature branch [PR_6748](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6748). Pipeline [516208978](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/516208978) was triggered at [dd3a5f5](https://github.com/FreeCAD/FreeCAD/pull/6748/commits/dd3a5f5e051c009935dc6c98b0e233cbe719eb68). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@chennes , if this also fixes bugs (it seems so), can you please review and commit?

**Comment by 0penBrain** [comment]
IMO it fixes only minor bugs (say 'user inconvenience' level). Up to you to decide. :)

**Comment by donovaly** [comment]
A bug is a bug ;-)
(I can only speak for myself - sometimes even small things drive me crazy, especially on repeating actions.)

**Comment by chennes** [comment]
The code looks good, and I think the bugs/inconveniences are worth fixing. I'd prefer the warning to be done in a dialog box, but Report View is a decent option for the time being. I'm going to merge this.

**Comment by donovaly** [comment]
> I'd prefer the warning to be done in a dialog box

@0penBrain could you please do this in a further PR and CC there @chennes that he will commit this?

**Comment by 0penBrain** [comment]
> I'd prefer the warning to be done in a dialog

I did it on purpose because I wanted the message to also appear if someone got this situation when using a script in headless mode. ;) 
Though an improvement may be to throw a custom exception instead, then in case of GUI catch it and display a message box. Would this be OK for you? 

@donovaly yes I can do it at a later time. ;)

**Comment by chennes** [comment]
Yes, I think that would be fine. We could also just implement the feature 😃 .

**Comment by 0penBrain** [comment]
@chennes @donovaly Should we open a feature ticket about implementing missing features ?

**Pull request merged**
