### PR TITLE
MainWindow: Fix for Automatic WB and edit mode WBs

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
==================================================

As described here:
https://forum.freecad.org/viewtopic.php?p=687188#p687188

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
@0penBrain 

The PR fixes the issue. However, as you coded this feature, you may be best positioned to know if the pre-existing order was important and this swapping is a no go, or if changing it is just fine.

**Comment by abdullahtahiriyo** [comment]
As I am going to be unavailable, feel free to edit the PR or merge an alternative PR to fix the issue. Thanks.

**Comment by 0penBrain** [comment]
@abdullahtahiriyo Pretty busy ATM too. I tested and it works fine (it improves the situation) but there is a small glitch remaining. When leaving then coming back to a tab/view where a sketch is currently being edited, the "[Sketcher]" toolbar is also restored while it should be hidden (it shall be displayed in non-edit mode).

I'm a bit confused about merging now. The PR definitely improves the situation but isn't perfect. :) What's your feeling ?

Ping @PaddleStroke that introduced the toolbar mechanism in Sketcher

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9758">pipeline status</a> for feature branch [PR_9758](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9758). Pipeline [903574341](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903574341) was triggered at [6002705](https://github.com/FreeCAD/FreeCAD/pull/9758/commits/6002705314a43737b7884740c61ba6414755f67c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
Merging and logging remaining issue in #9859

**Pull request merged**
