### PR TITLE
Unflagging

### PR DESCRIPTION
**Pull request by Sharath529**

### CODE REVIEW

**Comment by maxwxyz** [comment]
@Sharath529 there are a lot of conflicts and 172 commits.

**Comment by Syres916** [comment]
This PR is set against the wrong branch, surely this was intended to be merged into _releases/FreeCAD-0-21_ or the unflagging branch was created off the wrong branch in the first place. Either way it doesn't seem suitable to be merged in this state IMHO.

**Comment by AjinkyaDahale** [comment]
Most likely there is no substance here. Only one of the 172 commits seems to be authored by the OP. If that commit has any substance, it is not clear from the message, and is lost in the plethora of formatting changes.

**Comment by Roy-043** [comment]
Let's close this then.

**Pull request closed without merging**
