### PR TITLE
TravisCI spellcheck [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by luzpaz**
This PR checks the possibility of integrating a spell checker in the PR process that does not fail the build if typos are found but instead returns the results to the comment thread of said PR. 

This PR is not ready to be merged.

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=24908

**EDIT:**
Example output looks like:
```
[beast@beast FreeCAD]$ codespell -d -q 3 --skip="*.po,*.ts,./.git,./src/3rdParty,./src/zipios++,./src/CXX,./src/Mod/Assembly/App/opendcm,./src/Mod/Cam/App" --ignore-words=../fc-word-whitelist.txt
./src/Doc/FreeCAD.uml:1910: Persistance  ==> Persistence
./src/Doc/FreeCAD.uml:3184: Persistance  ==> Persistence
./src/Mod/Fem/FemMeshTools.py:676: ans  ==> and
./src/Mod/Fem/FemMeshTools.py:735: retrive  ==> retrieve
./src/Mod/Fem/FemMeshTools.py:735: elments  ==> elements
./src/Mod/Fem/FemMeshTools.py:783: lokale  ==> locale
./src/Mod/Fem/ObjectsFem.py:252: regon  ==> region
./src/Mod/Fem/ObjectsFem.py:275: regon  ==> region
./src/Mod/Fem/FemInputWriterCcx.py:384: retriving  ==> retrieving
./src/Mod/Fem/FemInputWriterCcx.py:877: elment  ==> element
./src/Mod/Fem/PyObjects/_FemMeshGmsh.py:46: inflatoin  ==> inflation
./src/Mod/Fem/PyObjects/_FemMeshGmsh.py:87: Gemetrical  ==> Geometrical
./src/Gui/Stylesheets/Dark-green.qss:74: Reseting  ==> Resetting
./src/Gui/Stylesheets/Dark-blue.qss:74: Reseting  ==> Resetting
./src/Gui/Stylesheets/Light-blue.qss:74: Reseting  ==> Resetting
./src/Gui/Stylesheets/Dark-orange.qss:74: Reseting  ==> Resetting
./src/Gui/Stylesheets/Light-orange.qss:74: Reseting  ==> Resetting
./src/Gui/Stylesheets/Light-green.qss:74: Reseting  ==> Resetting
```
False positives are whitelisted. The current whitelist can be found at:
https://gist.githubusercontent.com/luzpaz/7ac1bf4412b9c1e5acde715ef9cb612c/raw/fc-word-whitelist.txt

### CODE REVIEW

**Comment by luzpaz** [comment]
It's failing at: https://github.com/luzpaz/FreeCAD/blob/1ca543247054a29626738406c2d2b15766e88516/spellcheck_code.sh#L38-L43
which is where the script uses the API to report back to the PR thread the spelling mistakes it found.

Specific Error:
https://travis-ci.org/FreeCAD/FreeCAD/jobs/287707763#L804-L830
```
HTTP/1.1` 401 Unauthorized
Server: GitHub.com
Date: Fri, 13 Oct 2017 19:48:42 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 93
Status: 401 Unauthorized
X-GitHub-Media-Type: github.v3; format=json
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
X-RateLimit-Reset: 1507927722
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-rack: 0.015513
X-GitHub-Request-Id: C5E6:062E:13DE26E:2F1450D:59E11899
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```
https://developer.github.com/v3/#failed-login-limit

Looks like the Travis $GH_TOKEN env variable isn't working when it should per https://github.com/FreeCAD/FreeCAD/blob/master/.travis.yml#L9-L11 
```
#  GH_TOKEN is defined as a secure environment variable and contains a
#           a valid GitHub OAUTH token with repo_deployment scope.
#           NOTE: Define this env using the Travis-CI Repo Settings UI
```
 
@bblacey or @peterlama care to take a look at this?

I also need to add conditional statements to the spellcheck_code.sh script so that it can exit cleanly (`exit 0;`). Haven't gotten that far yet. I'm such a newb with bash.

**Comment by luzpaz** [comment]
Maybe the issues is that $GH_TOKEN is only in the scope of `repo_deployment`! I think i need the `write:repo_hook` token.
 
Read more about `write:repo_hook` at https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/

**Comment by peterlama** [comment]
I haven't had a chance to look at your exact problem, but GH_TOKEN is not set for pull requests for security reasons. If there is a token that is safe to display publicly, then we can create a new non-secure variable for it that you could use for this.

**Comment by luzpaz** [comment]
@peterlama According to the [tutorial I've been referencing](https://blog.eleven-labs.com/en/how-to-check-the-spelling-of-your-docs-from-travis-ci/) I actually need the `public_repo` token. It needs to be hidden. Hmm... this may be a problem from a security POV.

**Comment by luzpaz** [comment]
Opened a ticket with the folks that created the tutorial: https://github.com/eleven-labs/eleven-labs.github.io/issues/263

**Comment by luzpaz** [comment]
Spoke to @bblacey on gitter.im at https://gitter.im/FreeCAD/FreeCAD?at=59e4f40abbbf9f1a386b0a6c 
Long story short: what we need is webhooks and @kkremitzki to swoop in and save the day :laughing:

**Comment by luzpaz** [comment]
Closing this per the advice of @kkremitzki until a solution is realized.

**Pull request closed without merging**
