### PR TITLE
[FEM] fix binary check

### PR DESCRIPTION
**Pull request by donovaly**
- the current implementation only considers explicitly given binaries (with full path) and ignores the setting to check the environment paths

### CODE REVIEW

**Comment by donovaly** [comment]
@marioalexis84 , please if it a try if this find all solvers on your system

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051">pipeline status</a> for feature branch [PR_9051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051). Pipeline [817887927](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/817887927) was triggered at [8340d77](https://github.com/FreeCAD/FreeCAD/pull/9051/commits/8340d77e1d3d97c997763f41077608f6fc5da20f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051">pipeline status</a> for feature branch [PR_9051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051). Pipeline [817930078](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/817930078) was triggered at [a223d32](https://github.com/FreeCAD/FreeCAD/pull/9051/commits/a223d3264fc3b72907a3313e6e59adb14c91c778). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
An aside, not sure if you're aware but there is some interesting work being done in https://github.com/jaheyns/CfdOF/pull/76

There may be features in there that would be of interest for FEM workbench.

**Comment by donovaly** [comment]
@marioalexis84 , I will have to provide a new weekly thus I need either this PR to be merged the next hours or your solution.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051">pipeline status</a> for feature branch [PR_9051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051). Pipeline [818264122](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818264122) was triggered at [6bcac68](https://github.com/FreeCAD/FreeCAD/pull/9051/commits/6bcac68f9ce3d526c4edec8ccf46f51f39186074). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051">pipeline status</a> for feature branch [PR_9051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051). Pipeline [818268039](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818268039) was triggered at [acc066e](https://github.com/FreeCAD/FreeCAD/pull/9051/commits/acc066e46198e93cc6bf2d0784d5b4be7382bc29). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051">pipeline status</a> for feature branch [PR_9051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051). Pipeline [818276136](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818276136) was triggered at [458df3b](https://github.com/FreeCAD/FreeCAD/pull/9051/commits/458df3bb872fc4e5d9f212a58873ee3cd1025147). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051">pipeline status</a> for feature branch [PR_9051](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9051). Pipeline [818291383](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818291383) was triggered at [ba19ec0](https://github.com/FreeCAD/FreeCAD/pull/9051/commits/ba19ec0c4e3031471376a3172cc0c8f22e8113e3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
