### PR TITLE
BIM: Added NativeIFC support to Add/remove tools

### PR DESCRIPTION
**Pull request by yorikvanhavre**
(+ a few small fixes)

### CODE REVIEW

**Comment by marcuspollio** [comment]
Hi, please add the https://github.com/FreeCAD/FreeCAD/labels/File%20format%3A%20IFC label. TIA =D

**Comment by maxwxyz** [comment]
@yorikvanhavre can you resolve the conflict?

**Comment by maxwxyz** [comment]
@yorikvanhavre ping for conflicts

**Comment by yorikvanhavre** [comment]
conflict solved!

**Pull request merged**
