### PR TITLE
Fem: Netgen meshing parameters improvements

### PR DESCRIPTION
**Pull request by marioalexis84**
~To be merged after https://github.com/FreeCAD/FreeCAD/pull/17170 just to avoid conflicts (The first two commits come from that pull request).~

Currently, the first and last mesh steps are defined by integer values. More meaningful enumeration values ​​are now used.

Fineness has a few predefined values ​​(`VeryCoarse`, `Coarse`, etc.) and `UserDefined` which is used to set custom parameter values. The predefined values ​​basically set a few parameters and leave all others as Netgen internal defaults, which makes all remaining properties obsolete. Now, only explicit parameters set by predefined fineness values ​​are set, while the rest can be defined by the user.

@FEA-eng

### CODE REVIEW

**Comment by FEA-eng** [comment]
Don't the Fineness levels set the Maximal and Minimal Size? When I change them for UserDefined, they are still respected after switching to other types. But then shouldn't those fields be editable for all Fineness types?

**Comment by marioalexis84** [comment]
> Don't the Fineness levels set the Maximal and Minimal Size?

No, Fineness don't set maximal a minimal size.
Can you try again? Now you can set size for any fineness type.

**Comment by FEA-eng** [comment]
So the remaining 3 parameters available in the task panel (growth rate, curvature safety and segments per edge) have fixed values for the predefined Fineness types? Then it would be nice if they were changed in the grayed out input fields when switching between the predefined Fineness types.

**Comment by marioalexis84** [comment]
@FEA-eng 
* The parameters change according to fineness mode.
* Entries in the properties panel are read-only for predefined fineness.

In the task panel:
  * If the initial fineness is `UserDefined`, the values are saved so if the user switches to another fineness and back, the values are not lost.
  * If the initial fineness is not `UserDefined` and the user switches to `UserDefined` fineness, the values change to default values.

**Comment by marioalexis84** [comment]
@maxwxyz could this be marked for 1.0? It would be nice not to have projects with those less meaningful parameters from the start.

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
