### PR TITLE
Transfer dialog for recompute on older files and disable warning

### PR DESCRIPTION
**Pull request by bgbsww**
This should eliminate the huge number of recompute warnings on older files without element maps.

It is a UI change, so a decision on whether to 1.0 or 1.1 this needs to be made.  If we do decide on 1.0 I expect the most stringent possible review, and to have to adjust to the results.  Please question everything.

### CODE REVIEW

**Comment by bgbsww** [comment]
Oh no, many of the tests that trigger this dialog.  Never simple.

**Comment by Syres916** [comment]
While I realise this breaks the translation rules, the reduction in reports on the forum/GH Issues will be significant for 1.0 Release. The polish would be to have a progress bar during recompute for the larger files but that's being picky.

**Comment by bgbsww** [comment]
A progress bar for all recomputes of non-trivial duration is a good idea.

**Comment by yorikvanhavre** [comment]
backported

**Comment by Syres916** [comment]
@bgbsww I appreciate you're not as active on the forum so could I please bring [this](https://forum.freecad.org/viewtopic.php?t=90683) to your attention, I hope I've interpreted the errors reported and flagged the correct contributor, TIA.

**Comment by bgbsww** [comment]
Thanks!  Dammit, I've been trusting CLion, and it likes c++11 stuff that
looks like python.  I'll crush this one and try to remember which language
I'm working in.

**Pull request merged**
