### PR TITLE
macos fix for #7550

### PR DESCRIPTION
**Pull request by ipatch**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

this PR should fix the issue i just opened ie. #7550

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7553">pipeline status</a> for feature branch [PR_7553](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7553). Pipeline [657394799](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/657394799) was triggered at [77833b7](https://github.com/FreeCAD/FreeCAD/pull/7553/commits/77833b7d3b3c5b7842171ae0a22b4e0332a323d2). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7553">pipeline status</a> for feature branch [PR_7553](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7553). Pipeline [657395531](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/657395531) was triggered at [6370ebd](https://github.com/FreeCAD/FreeCAD/pull/7553/commits/6370ebd5b349f141a3bc6b9df9fef79bd24a1926). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
I see homebrew references in the PR, is it safe to assume this would be running in that environment? @looooo does this affect the conda builds?

**Comment by ipatch** [comment]
> I see homebrew references in the PR, is it safe to assume this would be running in that environment? @looooo does this affect the conda builds?

correct this should only effect 🤞 people on macos building freecad using cmake to produce a `FreeCAD.app` bundle due to the path of the cmake file being updated ie. the `./src/MacAppBundle/CMakeLists.txt`

i believe the conda build system doesn't use that cmake file, but definitely get a confirmation from @looooo before merging. not trying to blow up anybody else workflows.

**Comment by looooo** [comment]
I guess this has no impact on the conda-builds.

**Comment by luzpaz** [comment]
Thanks @ipatch and all involved!

**Pull request merged**
