### PR TITLE
[DO not merge] CI integration test

### PR DESCRIPTION
**Pull request by berndhahnebach**
CI integratetion test

### CODE REVIEW

**Comment by freecadci** [comment]
FreeCAD CI-repository:
branch:
https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074

pipeline for commit 62bc1c39a35887:
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/379634051

status:
success

all pipelines for each branch: 
https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074">pipeline status</a>

**Comment by berndhahnebach** [comment]
[PR_5074](https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074)

**Comment by berndhahnebach** [comment]
FreeCAD CI-repository:
Pipeline status for [feature branch PR_5074](https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074) is <a href="https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074">pipeline status</a>

[All feature branch pipelines](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches)

[pipeline #pipelineid](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/pipelineid) at commit commitid

**Comment by freecadci** [comment]
<a href="https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074">pipeline status</a> for [feature branch PR_5074](https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074) is 

[All feature branch pipelines](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches)

[pipeline #pipelineid](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/pipelineid) at commit commitid

**Comment by freecadci** [comment]
<a href="https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5076">pipeline status</a> for feature branch [PR_5076](https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5076). Pipeline [#379749837 ](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/379749837) was triggered at [shortc21f7ab023da87e0839bf63d8ea151c83dd3dcfc](https://github.com/FreeCAD/FreeCAD/pull/5076/commits/c21f7ab023da87e0839bf63d8ea151c83dd3dcfc). All CI branch [pipelines](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074">pipeline status</a> for feature branch [PR_5074](https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074). Pipeline [#380182752 ](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/380182752) was triggered at [230d3b6](https://github.com/FreeCAD/FreeCAD/pull/5074/commits/230d3b68b60f993dc109ad5d099af80ce7252d79). All CI branch [pipelines](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074">pipeline status</a> for feature branch [PR_5074](https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5074). Pipeline [#380207341 ](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/380207341) was triggered at [b3d843f](https://github.com/FreeCAD/FreeCAD/pull/5074/commits/b3d843f702cc1f20b86a1d0126502d1f58333d1e). All CI branch [pipelines](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches).

**Pull request closed without merging**
