### PR TITLE
Pref: general: Re-organize page.

### PR DESCRIPTION
**Pull request by PaddleStroke**
Just reorganizing the page to fix some things. Please see the commits for the individual fixes.

Below how it looks after this PR: 
image

Including https://github.com/FreeCAD/FreeCAD/issues/9255

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9260">pipeline status</a> for feature branch [PR_9260](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9260). Pipeline [836520468](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/836520468) was triggered at [7888608](https://github.com/FreeCAD/FreeCAD/pull/9260/commits/7888608dc31279d428fe84245ae81dc0138dceb5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by PaddleStroke** [comment]
@chennes I reverted the change of 'style sheet' to 'theme' so that the rest can merge.
I will think about the Theme issue, but I think this needs to be tackled later.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9260">pipeline status</a> for feature branch [PR_9260](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9260). Pipeline [836554781](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/836554781) was triggered at [beb866e](https://github.com/FreeCAD/FreeCAD/pull/9260/commits/beb866efdcc52139af34ddcb21e495101ae3e440). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Looks nice, thanks!

**Pull request merged**
