### PR TITLE
Gui: Remove rogue preferences from PreferencePacks (Light theme should not change PickRadius)

### PR DESCRIPTION
**Pull request by Roy-043**

### CODE REVIEW

**Comment by Roy-043** [comment]
The "CanAbortRecompute" preference should not be there either IMO.

**Comment by pierreporte** [comment]
This was likely the cause of my issue with angle constraints: https://github.com/FreeCAD/FreeCAD/issues/12756#issuecomment-2365156229

**Comment by Roy-043** [comment]
I have changed the title. Other preference pack CFG files have similar issues.

**Comment by obelisk79** [comment]
To be fair, the default pick radius is far too small, but 16px may very well be too large. Either way, it should be consistent across the packaged themes. In my mind, I don't care what the values are, either and existing user, or new user will have to make changes. 

I'm firmly of the opinion that FreeCAD has horrible default across the board and is often off-putting to newcomers. The scope of this PR doesn't cover that as a conversation topic so I won't comment any further on the matter here.

**Comment by JohnOCFII** [comment]
There was a request on Discord to offer opinions on this issue.  

Some thoughts:

- If a Preference Pack or Theme seems to imply it is offering a Dark or Light Theme, my thought is that it only impacts colors/shadings, etc.  
- Other preferences would be in a "different" preference pack.  So -- perhaps there should be a different "standard" Preference Pack (as @obelisk79 might be suggesting above) that has separate defaults items.
- I know that when I set up FreeCAD, I choose items like Pick size, text size, etc., and when I switch between a Theme titled Light or Dark, I wouldn't expect to change preferences that impact things other than just the Light and Dark color changes.
- Can themes be combined in different preference packs?

**Comment by MisterMakerNL** [comment]
Current theme preferences are from the open theme preferences. @obelisk79 
I did not check if these aren't theme related like pick-radius.
I do understand that this can be an issue when the user sets custom values which get overwritten by setting a theme.

I do see an issue that these initial settings are very complicated to change if we remove them from theme config files.

I would suggest that we make a cfg file with initial settings that creates the user.cfg on first boot and we offer a reset settings option on a new release installation. This also makes it way easier to make a custom Freecad installation.

**Comment by Roy-043** [comment]
> I'm firmly of the opinion that FreeCAD has horrible default across the board and is often off-putting to newcomers.

I disagree (with contents and tone). Which does not mean I like every default of course.

For settings in px we should aim for a cleverer system than hard-coded values. A PickRadius of 5px works fine for me, but on HD screens and screens with a higher resolution that value is no doubt too small.

**Comment by obelisk79** [comment]
I don't understand what is wrong with the tone. I was plainly staying my opinion without appointing any sort of blame, and acknowledged that further discussion is out of scope. A rather of reaction for you to have.

**Comment by Roy-043** [comment]
Based on @JohnOCFII comment I have removed more preferences.

I am unsure about these, and have therefore kept them (in FreeCAD Dark.cfg):
```
        <FCParamGroup Name="TreeView">
          <FCInt Name="FontSize" Value="11"/>
          <FCInt Name="ItemBackgroundPadding" Value="11"/>
```

**Comment by chennes** [comment]
@JohnOCFII can you re-review this one now with the added changes?

**Comment by obelisk79** [comment]
those can be safely removed.

**Comment by JohnOCFII** [comment]
> @JohnOCFII can you re-review this one now with the added changes?

I wasn't the OP.  I've been going back and forth between FreeCAD Light and Dark, and while I think fewer "unexpected" changes are happening, I did notice that marker size is changed back to 7px when switching between Dark to Light.

**Comment by Roy-043** [comment]
Backported to V1.0.1.

**Pull request merged**
