### PR TITLE
Tools: small bug fix for showing the correct test icon

### PR DESCRIPTION
**Pull request by mdkus**
The genereation of a new cpp module should work analogue to the generation of a python module. When generating and compiling a new cpp module, an error is shown while loading the module after starting FC: "Cannot find icon: Test1"

### CODE REVIEW

**Comment by chennes** [comment]
As a general rule when saving an SVG from Inkscape for use in FreeCAD, you should use a "Plain SVG" rather than an "Inkscape SVG". It's unlikely to matter in this case, but if this is intended as a template for people to look at when creating their workbenches it's probably good to follow best-practices here.

**Comment by mdkus** [comment]
> As a general rule when saving an SVG from Inkscape for use in FreeCAD, you should use a "Plain SVG" rather than an "Inkscape SVG". It's unlikely to matter in this case, but if this is intended as a template for people to look at when creating their workbenches it's probably good to follow best-practices here.

Ok, I see. I just copied the svg from existing file
[here](https://github.com/FreeCAD/FreeCAD/blame/master/src/Tools/_TEMPLATEPY_/Resources/icons/_TEMPLATEPY_Workbench.svg) and renamed it. Shall we take there also a plain svg?

**Comment by chennes** [comment]
For now let's just do it here, to keep this PR simple and compact. That change can be made later (for exactly this reason, so when someone copies it again later they get a clean SVG).

**Comment by mdkus** [comment]
Ok. Do you have an example plain svg? Shall I make a new PR after converting the svg into a plain svg?

**Comment by chennes** [comment]
If you just open it in Inkscape and re-save, choosing "Plain SVG" as the option, you'll get the right thing. Then you can add a new commit to the branch you are working on with the new SVG file. When you push that commit, it will show here as part of the PR.

**Comment by mdkus** [comment]
Ok, thank you.

**Comment by mdkus** [comment]
Added the replacement of Inkscape svg with plain svg to the PR.

**Comment by wwmayer** [comment]
Merged as a single commit: e4c2cc3c76

**Pull request closed without merging**
