### PR TITLE
[TD]fix double pdf file on win (fix #16538)

### LINKED ISSUE #16538: TechDraw: Two PDF files are created when using virtual PDF printer (Windows related)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When printing TechDraw page (using 'Print....' command or 'Print preview..,' command) using virtual PDF printer (I tried with Microsoft Print to PDF and PDF Creator), two PDF files are created. One is the correct print, the other one is empty PDF file.

I am not able to reproduce this behavior with FC 0.21.2, so it seems like a regression. I am not able to reproduce this problem when using 'Print...' command from main 3D view.

My test file (I could reproduce with 2 files):
[techdraw-print-test.zip](https://github.com/user-attachments/files/17002972/techdraw-print-test.zip)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git)
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

TechDraw

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for issue #16538.

### CODE REVIEW

**Review by chennes — APPROVED** [review]
LGTM

**Comment by luzpaz** [comment]
backport?

**Comment by chennes** [comment]
Yes, this is flagged for 1.0.

**Comment by chennes** [comment]
Cherry-picked to 1.0

**Pull request merged**
