### PR TITLE
[Base] rename a variable to please the spellchecker CI

### PR DESCRIPTION
**Pull request by donovaly**

### CODE REVIEW

**Comment by 0penBrain** [comment]
Don't think the spell checker cares really about variable names. 
But it complains about typos in comments, which are not fixed by the PR. ;)

**Comment by donovaly** [comment]
It cares, see: https://github.com/FreeCAD/FreeCAD/runs/5273561402?check_suite_focus=true

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6414">pipeline status</a> for feature branch [PR_6414](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6414). Pipeline [476344158](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/476344158) was triggered at [0ba5d92](https://github.com/FreeCAD/FreeCAD/pull/6414/commits/0ba5d9264831801a54b8212c5cfb4ed95be4e904). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
418cb98010

**Pull request closed without merging**
