### PR TITLE
[Bugfix] PartDesign: Fix HoleCutDepth not being recalculated correctly

### PR DESCRIPTION
**Pull request by stefanklug**
`HoleCutDepth` is reset to 0 to force a recalculation of the depth when `HoleCutType` is set to a new value.
But the line
```cpp
	pcHole->HoleCutCustomValues.setValue(false)
```
also forces a recalculation. So the depth was recalculated with the old value in `HoleCutType` which was not expected behaviour.

@donovaly This is the first tiny bugfix for https://forum.freecadweb.org/viewtopic.php?f=8&t=72404

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7626">pipeline status</a> for feature branch [PR_7626](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7626). Pipeline [673899240](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/673899240) was triggered at [d207fe3](https://github.com/FreeCAD/FreeCAD/pull/7626/commits/d207fe33906ab44c970da1f726fa1a6af32f2ceb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Please push a revision that fixes the typo `beeing` to `being` in the commit summary. TIA

**Comment by stefanklug** [comment]
@luzpaz Thanks. I fixed the typo and rebased.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7626">pipeline status</a> for feature branch [PR_7626](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7626). Pipeline [674438783](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/674438783) was triggered at [55884e8](https://github.com/FreeCAD/FreeCAD/pull/7626/commits/55884e85861710accf609f4ac71019305dccf902). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks. It will also be backported for FC 0.20.2

**Pull request merged**
