### PR TITLE
Path: Don't override style colors

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---
Currently, FreeCAD sets the color of the text within an InputField to Gray if it has been set by an expression, or Black if not. This ignores stylesheets, and results in unreadable text fields, especially in dark themes. For example, note the fields in the "Parameter" section of this screenshot:
image
The only way to fix this in the stylesheet is to set the background to a light color.

I propose a better solution. Rather than setting the color, set a property. The stylesheet can then change the color based on that property if desired.
I have not included changes to stylesheets in this PR. Most if not all stylesheets already change the text color based on whether or not the text field is read-only. I am not opinionated on whether this property is needed at all; perhaps the read-only selector is sufficient.

### CODE REVIEW

**Comment by luzpaz** [comment]
Note: This PR doesn't indicate that you're referring to the Path Workbench. Please update the commit prepended with `Path:` please.

**Comment by chuckwagoncomputing** [comment]
For documentation's sake, here is the same screenshot, after the change:
image
It appears that I was wrong about themes setting the color based on whether it was read-only. At least this one (Dark-contrast) doesn't.
Here is a screenshot of the current release, with one of the fields set by expression:
Screenshot_20230317_220013

**Comment by chuckwagoncomputing** [comment]
I pushed another commit - the widget needs to be polished for stylesheet rules that select on the exprSet property to work.
Here is an example of what can be done with a stylesheet:
```
QAbstractSpinBox[exprSet="false"] {
    color: white;
}

QAbstractSpinBox[exprSet="true"] {
    color: #18a503;
}
```
I added the above lines to Dracula.qss, and this was the result:
image

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8941">pipeline status</a> for feature branch [PR_8941](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8941). Pipeline [813042696](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/813042696) was triggered at [6bf0db5](https://github.com/FreeCAD/FreeCAD/pull/8941/commits/6bf0db5d89aaa213f30fecd2e480c682954cf5cd). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Can someone review this ?

**Comment by chuckwagoncomputing** [comment]
Would it be better to only remove the `setStyleSheet` calls for now?

**Pull request merged**
