### PR TITLE
Resize external link overlays relative to the device's pixel ratio

### PR DESCRIPTION
**Pull request by furgo16**
Fixes: #15372

- Use the same resize method for local and external link overlay icons (before, external link overlay icons were hardcoded), based on the device pixel ratio (https://github.com/FreeCAD/FreeCAD/commit/a93997df64)
- Remove obsolete `src/Gui/Icons/LinkOverlay.xpm` icon to avoid confusion 
- In the table with screenshots below, `Cube002` is the external link to look at for the changes in the overlay icon. Notice the difference comparing the overlay icon with a local link (`Cube001`) before, and the same size after
- It seems that the overlay icon for external links is composed of two `LinkOverlay.svg` icons next to another, which is different to the one for local links, with one icon only.
- Related, but not addressed: https://github.com/FreeCAD/FreeCAD/issues/6765
- Also related: https://github.com/FreeCAD/FreeCAD/pull/13110. There is a [note](https://github.com/FreeCAD/FreeCAD/pull/13110/files#discussion_r1545390943) on that discussion that I feel has a more robust way of setting the size of the overlay to 25% of the size of the icon it is layed over. However, I do not know how to get the size of that icon (or if it's possible from that code location).
- The https://wiki.freecad.org/Tree_view#Overlay_icons needs an update. There are many overlay icons (including the one on this PR) that are not featured there. I think most of those not present are the ones referenced in the `#6765` issue. For now, I've updated the wiki to include the link and external link overlays.
- Test file: [test-overlay-icons.zip](https://github.com/user-attachments/files/17318175/test-overlay-icons.zip)
- Only tested on Linux.

| State/Scale| 1x| 2x |
|---|---| --- |
| Before | image | image |
| After | image| image| |

```
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38925 (Git)
Build type: Unknown
Branch: fix-link-overlay-issue
Hash: 12c6fc2920d083c7407419f8b9ae3651798c005a
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.8.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
```

### CODE REVIEW

**Comment by maxwxyz** [comment]
https://github.com/FreeCAD/FreeCAD/issues/6765 is not resolved? @JohnOCFII could you test this on mac?

**Comment by JohnOCFII** [comment]
> #6765 is not resolved? @JohnOCFII could you test this on mac?

Tested the linked issue: https://github.com/FreeCAD/FreeCAD/issues/6765#issuecomment-2408631355

**Comment by luzpaz** [comment]
cc @chrisb-github (OP of #6765)

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
