### PR TITLE
App: fix property ordering problem when undo/redo

### PR DESCRIPTION
**Pull request by realthunder**
Related #0004265

See https://tracker.freecadweb.org/view.php?id=4265#c14271

### CODE REVIEW

**Comment by luzpaz** [comment]
Checking on the status of this PR. Came here from https://tracker.freecadweb.org/view.php?id=4265

**Comment by donovaly** [comment]
@yorikvanhavre you once approved this PR and it fixes an important bug. Could you merge it or if not what needs to be done first?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by donovaly** [comment]
@realthunder , please rebase this that it can be merged.

**Comment by donovaly** [comment]
@realthunder , I made a mistake, I thought the CI already run on your rebase. But it did not.

Now we have a CI error with a failing test. Can you please have a look?:
https://gitlab.com/freecad/FreeCAD-CI/-/jobs/2117342714

**Comment by realthunder** [comment]
I'll check in the morning at my time zone. I should have run the command line test. The GUI mode test passes, though.

**Comment by wwmayer** [comment]
> I made a mistake, I thought the CI already run on your rebase. But it did not.

Why do you merge code then for that no review was done? At least you could have checked out the code locally and run the unit tests to see if they still pass before blindly merging it.

**Comment by wwmayer** [comment]
> I should have run the command line test. The GUI mode test passes, though.

It neither works in CLI nor in GUI mode. In both cases the same test fails.

**Comment by donovaly** [comment]
> Why do you merge code then

Why does one do mistakes? ;-)
I merged few minutes before another PR from realthunder, there the CI run fine and I missed that for this PR the CI was not even started. I of course compiled. For the test I usually rely on the CI to save time. If the Ci did not run, I wait a day until it did. here i thought the CI passed, but had obviously the wrong browser tab opened.

I can revert the merge, or we wait a day when realtunder will have fixed this.

**Comment by wwmayer** [comment]
> For the test I usually rely on the CI to save time. If the Ci did not run, I wait a day until it did

Are you kidding? You think if the unit tests pass then everything is fine and replaces a proper code review?

> I can revert the merge, or we wait a day when realthunder will have fixed this.

The merge has to be reverted because to me it looks that the PR doesn't address the deeper problem but just adds more complicated code and further side-effects.

If a new PR is prepared it must be thoroughly tested because undo/redo is one of the most important key features and thus must work very reliably.

**Comment by donovaly** [comment]
I reverted it now.

Nevertheless, yes I made a mistake. I noticed it first when the CI failed that the CI was not run at all.

> You think if the unit tests pass then everything is fine and replaces a proper code review?

You misunderstood me. This PR was already reviewed by Yorik. Then it stood here for almost 2 years. We spoke about the PR in the Telegram chat, I also asked here about a year ago, if Yorik still approves this. So I did not review the code. In PRs that I review I am on the reviewers list and I comment.
Therefore I only compiled and then put it in - not seeing that the CI was not triggered at all. I cannot do more than to apologize.

Regarding the code review, this went not fine. I mean, someone set a PR, then he gets it approved and then nothing happens. Therefore I acted in pushing people to give an OK or not. It is in my opinion no problem to deny a PR as long as the author gets feedback.

**Comment by realthunder** [comment]
I have just fixed problem with [this](https://github.com/realthunder/FreeCAD/commit/8ee95433a2de2c5562b37020d0dd2c85c46b4e21) commit. The reason of failure is in the commit message.


> The merge has to be reverted because to me it looks that the PR doesn't address the deeper problem but just adds more complicated code and further side-effects.
> 
> If a new PR is prepared it must be thoroughly tested because undo/redo is one of the most important key features and thus must work very reliably.

I doubt it is 'the most' import key feature, because it is not working reliably since, I don't know, ever? And FreeCAD seems working just fine. There are indeed deeper problems, which I attempted to address in several occasions in this and other commits, but got either ignored or rejected. So, let's discuss about this, shall we?

It is not that difficult to handle transactions right, in principle, if there is only one thread involved, which applies to FreeCAD. In order to reliablely roll back a transaction, every change must be reocrded in order, and while rolling back, no further change except the recorded ones shall be made.

The first obvious problem with FreeCAD in this regard is that it is the user code's repsonsibility to setup transaction instead of the core, which means any arbitary user code (e.g. some external workbench, addon etc) can disrrupt the undo chain. I tried to reduce this problem by automating transaction setup in Gui::Command class.

Second, document recompution is often not recorded in transaction on purpose, for some reason I don't fully understand. This will surely break undo chain in some cases. For example, sketch often fails undo because the recomputed geometry/shape is not recorded in transaction, and the fact that the solver relies on the current geometry/shape to provide a sensible initial state. Part of the effort of the above Gui::Command change is to be able to auto record the changes bye recomputation in a command action.

Then there is the problem with proeprty change notification, which this PR is trying to address. It takes extra effort for the user code to distinguish whether a property is changed by user or by undoing, and the code actually need to treat them differently. One of the consequences of not doing so is explained in the [issue](https://tracker.freecadweb.org/view.php?id=4265#c14271) post linked in OP.

In order to not break too many existing code, this PR makes a compromise by delay the property change notification until all changes have been made. The correct way to handle it, IMO, is to not notify user code about property undo/redo changes at all, because we are suppose to disallow user code for any further property changes any way. As soon as the user code makes any change, the redo queue must be flushed, and new transaction should be setup and start recording. If user code has to have some state tracking internal variables, they can syncrhonize it by handling the undo/redo signals.

**Comment by wwmayer** [comment]
> I doubt it is 'the most' import key feature, because it is not working reliably since, I don't know, ever?

I didn't say it is _the_ most important but _one_ of the most important features and this is still true. If it's not our goal to make it as robust as possible then there is no reason to offer it at all. 

And yes, it never worked 100% correctly because in the past a map with a pointer to a Property as key  was used. It then only failed in cases where a newer Property instance had a lower address than older instances _and_ if there is a relation between two properties like the Geometry and Constraints properties of a sketch. Having a container that allows fast access and guarantees to keep the order of insertion should have solved this problem, too.

> There are indeed deeper problems, which I attempted to address in several occasions in this and other commits, but got either ignored or rejected. So, let's discuss about this, shall we?

In the related Mantis bug report I have described several cases of regressions compared to older versions. Some of them has been fixed by other changes and I can't see that this PR fixes any of the remaining issues. So, why should something be merged that doesn't solve any of the reported regressions? And I simply don't have the time to regularly do more or less two full rebuilds in order to realize that the described issues are not addressed.

If a PR is supposed to fix a weakness of the current version then it's up to the author to explain that and give an example. And for changes in the core system I consider it as mandatory that the author writes a unit test to easily confirm the weakness and its fix. But when reading the sparse commit messages and without any test code then it's up to the reviewer to figure out what the author is trying to achieve.

> It is not that difficult to handle transactions right, in principle, if there is only one thread involved, which applies to FreeCAD. In order to reliablely roll back a transaction, every change must be reocrded in order, and while rolling back, no further change except the recorded ones shall be made.

That's in theory but in practice it's a little bit more complicated than this. JRiegel originally has designed the transaction system and intentionally allowed some special cases where an object was changed after opening but then deleted after the transaction was committed without having opened a second transaction. The undo then has to be aware of the deleted object. I guess the idea was to be forgiving to possible errors programmers make in their client code.

Another special case is the support of adding or removing dynamic properties that makes things more complex or the above mentioned relation of two properties.

> The first obvious problem with FreeCAD in this regard is that it is the user code's repsonsibility to setup transaction instead of the core, which means any arbitary user code (e.g. some external workbench, addon etc) can disrrupt the undo chain. I tried to reduce this problem by automating transaction setup in Gui::Command class.

The one and only responsibility of client code is to open and commit or abort a transaction. Everything else has to be handled by the core system. If client code had to handle more than that you can be sure that things will never work correctly.

As far as I understand the concept of automatic transaction then its primary goal is to avoid empty transactions. And after the automatic transaction was added it took several iterations to fix bugs or to make things more flexible.

But when reading forum posts in the developer corner many people have problems to understand the idea and to make things work as they want. The main point developers have to be aware of: when invoking a Command then it makes a big difference if a dialog is modal or non-modal. If it's modal then there is still an instance of AutoTransaction that effectively disallows to open a transaction with a user-defined text or intentionally open a second transaction while with a non-modal dialog things work as they expect it because the AutoTransaction has been cleaned up. There is a way to avoid the issue with modal dialogs but most people simply don't know how.

> Second, document recompution is often not recorded in transaction on purpose, for some reason I don't fully understand.

Are you talking about commands that open/commit a transaction and does the update outside the transaction or the Recompute command?

For the latter I once added a user option to avoid to create a transaction because it disallows effective undo/redo. When I undo a change and a manual recompute opens a new transactions it's impossible to redo my previous change because adding a transaction to the undo stack clears the redo stack.

For the former case there might be indeed cases where it currently causes problems. I think in most cases this was done by Copy&Paste where it wasn't further tested if the recompute should be recorded or not.

> Then there is the problem with proeprty change notification, which this PR is trying to address. It takes extra effort for the user code to distinguish whether a property is changed by user or by undoing, and the code actually need to treat them differently.

For the vast majority of cases there is no need to check if it's a user change or undo/redo change. One case I am aware of at the moment is the sketcher but there the issue is actually that the Geometry and Constraints properties might not be in a consistent state.

**Comment by wwmayer** [comment]
> You misunderstood me. This PR was already reviewed by Yorik.

No idea if "Approving" is equivalent to "Reviewed" but from the history I cannot see if or what has been discussed. But if it's marked as approved without any further comment then it's not a review, IMO.

Anyway, I once opened a ticket where I described several regressions and posted test code that can be easily used to confirm the issues. And this PR fixes none of them.

As realthunder explained a bit further in his last post he tries to improve some things but then still the PR doesn't really match with the bug report.

> Regarding the code review, this went not fine. I mean, someone set a PR, then he gets it approved and then nothing happens. Therefore I acted in pushing people to give an OK or not. It is in my opinion no problem to deny a PR as long as the author gets feedback.

You're right! I also have to blame myself not giving further feedback but it's not so easy to respond to every PR in sensible time because all the time I am asked for feedback on other PR, on the forum, PM and so on.

> I cannot do more than to apologize.

Accepted. But in the future please don't merge PR that haven't got any feedback for long time. And especially changes in the core system it's most of the time up to me to review them (unless it's a trivial change).

**Comment by realthunder** [comment]
> In the related Mantis bug report I have described several cases of regressions compared to older versions. Some of them has been fixed by other changes and I can't see that this PR fixes any of the remaining issues. So, why should something be merged that doesn't solve any of the reported regressions? And I simply don't have the time to regularly do more or less two full rebuilds in order to realize that the described issues are not addressed.

Maybe I didn't make it clear in the PR description. This PR is not meant for the problems described in Mantis issue [#0004625](https://tracker.freecadweb.org/view.php?id=4265) opening post. It is meant for a specific problem you [commented](https://tracker.freecadweb.org/view.php?id=4265#c14271) in that issue. And I have [analyzed](https://tracker.freecadweb.org/view.php?id=4265#c14273) the cause of the problem in reply to your comment.

This regression you discovered actually exposes some 'deeper problem' of the transaction handling, and this PR tries to address it, which is, as the PR title suggests, an ordering problem when undo/redo property changes. The problem you discovered relates to the AttachEngine. Sketch object is another example that is sensitive to property change order. There is no 'correct' order of changes. Both forward and reverse can go wrong. It really depends on the implementation of the object's change handling. We'll have to treat it like black box. What this PR does is to suppress change notification until all changes have been restored into previous state, only then do we notify the object.


> If a PR is supposed to fix a weakness of the current version then it's up to the author to explain that and give an example. And for changes in the core system I consider it as mandatory that the author writes a unit test to easily confirm the weakness and its fix. But when reading the sparse commit messages and without any test code then it's up to the reviewer to figure out what the author is trying to achieve.

I have analysed the cause of the problem, and explained the PR in Mantis comments. Unit test usually helps, but not always, apparently. In this specific case, how should one write a test case? Using a while loop to check if the box moves like it suppose to every single time? That's not much of a proof.



> > It is not that difficult to handle transactions right, in principle, if there is only one thread involved, which applies to FreeCAD. In order to reliablely roll back a transaction, every change must be reocrded in order, and while rolling back, no further change except the recorded ones shall be made.
> 
> That's in theory but in practice it's a little bit more complicated than this. 

Yes, I agree. The handling will be simple only if we can make sure to record all changes and disable user code change while rolling back. In practice, these two requirements are difficult to satisfy without serious impact on existing code. My `AutoTransaction` and `Command` commits are my attempt to capture as much changes as possible without too much change of user code. But it didn't went so well.

  

> > The first obvious problem with FreeCAD in this regard is that it is the user code's repsonsibility to setup transaction instead of the core, which means any arbitary user code (e.g. some external workbench, addon etc) can disrrupt the undo chain. I tried to reduce this problem by automating transaction setup in Gui::Command class.
> 
> The one and only responsibility of client code is to open and commit or abort a transaction. Everything else has to be handled by the core system. If client code had to handle more than that you can be sure that things will never work correctly.

What I am trying to say is that the core system should handle more. It should some how continuously record changes in the background. The user code initiated calling of open and close transaction are just for tagging the changes to be rolled back together. BTW, the transaction ID I introduced is for tagging transactions in different documents (joined by App::Link), so that they can be rolled back together as well.



> > Second, document recompution is often not recorded in transaction on purpose, for some reason I don't fully understand.
> 
> Are you talking about commands that open/commit a transaction and does the update outside the transaction or the Recompute command?

I am referring to both cases. I am concerned about these non-captured changes because it may break object state consistency when undo/redo. 


> For the latter I once added a user option to avoid to create a transaction because it disallows effective undo/redo. When I undo a change and a manual recompute opens a new transactions it's impossible to redo my previous change because adding a transaction to the undo stack clears the redo stack.


It is okay to not flush the redo queue only if we can guarantee that the recomputation can restore the object to the exact same state as before the transaction. If we can capture every single change, then there is no need to recompute when undo/redo, because the object will be perfectly restored. But if we cannot capture all changes, we have to recompute to fully restore, but then we cannot make sure that the recompute will produce the same result, because some input property used for recompute may not be captured in the transaction and hence not restored. If recompute produces a different result, it may introduce inconsistent state when the user perform further redo.

**Pull request merged**
