### PR TITLE
FEM: removing "constraint" from the names

### PR DESCRIPTION
**Pull request by kaktusus**
Removing "constraint" from the names of most FEM workbench features.
https://github.com/FreeCAD/FreeCAD/discussions/10217

### CODE REVIEW

**Comment by chennes** [comment]
@FEA-eng I believe you are the local expert in this area -- would you mind reviewing?

**Comment by FEA-eng** [comment]
> @FEA-eng I believe you are the local expert in this area -- would you mind reviewing?

I checked this and discussed with @kaktusus. Everything is fine, this PR can be merged.

**Comment by chennes** [comment]
FYI @kaktusus, I fixed up your branch a bit: I used an interactive rebase (`git rebase -i`) to "drop" all but the single commit you actually wanted to keep, and then I rebased onto the latest HEAD of the master branch. That's what I've force-pushed here.

**Comment by maxwxyz** [comment]
@kaktusus @FEA-eng Nice to see this change, unfortunately when creating the "constraints", the tree items still keep the name with "constraint":
grafik

**Comment by luzpaz** [comment]
@maxwxyz can you please add your full about info so we know how you built it ?

**Comment by kaktusus** [comment]
This problem coincides with an open ticket ...
was recently raised I think by you luzpaz _(or by chennes)_
can't find it now ...
will try to look for it again later :wink:

**Comment by kaktusus** [comment]
it took me a while but I found it: https://github.com/FreeCAD/FreeCAD/issues/5547
so that we can link this post to that thread.

**Comment by maxwxyz** [comment]
Not sure if #5547 is about the same. I thought in this PR here, the idea was to remove the prefix "constraint" in FEM. When adding the "constraints" the tree elements still have the name "constraint" in them, shouldn't they be removed in the tree items as well, to match the button names?

**Comment by kaktusus** [comment]
> Not sure if #5547 is about the same. I thought in this PR here, the idea was to remove the prefix "constraint" in FEM. When adding the "constraints" the tree elements still have the name "constraint" in them, shouldn't they be removed in the tree items as well, to match the button names?

These are related topics for me I noticed another problem.

On the other hand, you are definitely right about the mainstream. :wink:

**Pull request merged**
