### PR TITLE
Dag

### PR DESCRIPTION
**Pull request by ickby**
This pull request changes the document graph structure from directed to undirected, adding backlink datastructures to objects. This enables more efficient graph traversal from bottom to top, which will become more important with the stacked coordinate systems and assemblies in 0.17.

### CODE REVIEW

**Comment by looooo** [comment]
this pull-request has many conflicts with the python3-branch. can we merge this after python3 is in master?

**Comment by ickby** [comment]
Oh, but the changes have nothing to do with python code? Or is also the c++ *PyImp part relevant? If so a small explanation would be nice, as I intend to work further on a few things on the python wrapper.

**Comment by looooo** [comment]
sry for being  too cautious, but I had some bad experiences with some rebasing. Just tried rebasing on the dag-branch again, and the conflicts are resolving quite easy. So it shouldn't be a problem.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
