### PR TITLE
FEM: Reformat fem .py sources

### PR DESCRIPTION
**Pull request by lyphrowny**
- Upgraded syntax used in fem .py sources to python3.8 using [`pyupgrade`](https://github.com/asottile/pyupgrade)` --py38-plus`
- Formatted fem .py sources using `black -l 100` (took the line length from the [`.pre-commit-config.yaml`](https://github.com/FreeCAD/FreeCAD/blob/d1d2b730ef62642bee333ea36fdfb92885fedb72/.pre-commit-config.yaml))
- Included applying pre-commit to fem .py sources in the `.pre-commit-config.yaml`

I chose to upgrade the syntax to only py3.8 because it is used in Windows LibPack. If needed. I can upgrade to py3.11, which is used in weekly builds.

### CODE REVIEW

**Comment by chennes** [comment]
I'm asking @marioalexis84 and @FEA-eng to review this mostly so they are aware of the precommit change. In particular, @marioalexis84, if you don't have the git precommit hook enabled on your repo you will want to do so once this is merged. Also, once this is finally merged, @lyphrowny please make another PR that adds the final commit hashes of the pure-formatting changes to our .git-blame-ignore-revs file (but don't do it until after merge, in case the hashes are changed by a rebase).

We do need to retain compatibility with Python 3.8 for the time being.

**Comment by lyphrowny** [comment]
I didn't expect the changes from the pre-commit.ci
I decided that excluding test files from the pre-commit-config would be worse, than changing the code, that generates the input files for solvers. So I made the appropriate changes to the code

I plan to squash-merge (with force push) all formating-related commits into a single commit this Sunday, unless the PR needs changes

**Comment by chennes** [comment]
That's fine (and also rebase so the CI runs the latest, now-correct, code). @marioalexis84 I won't merge this until I hear from you, since it's likely to cause conflicts with anything you've got in progress that touches these files, and will require a tweak to your workflow to add precommit.

**Comment by marioalexis84** [comment]
I have the precommit hook activated. It would be good to first merge #14771 and #14519 to avoid having to rebase those pull requests again.

**Comment by lyphrowny** [comment]
For #14771 to be merged, we're waiting for FEA-eng's approval, right?

The latest I can do the rebase is this Sunday evening (19:00 GMT+0), after that I will be afk for <2 weeks. I propose to do the rebase at the latest possible time: if #14771 isn't merged, it wouldn't be complicated for a maintainer to do an additional rebase to account for #14771. I don't want to postpone this PR until I'm back, as there may be more issues to consider before merging this PR

**Comment by marioalexis84** [comment]
ok, if necessary I will rebase #14771 later

**Comment by lyphrowny** [comment]
I did the rebase, including the changes from the above mentioned PRs
Squashed all the formatting related changes into one commit

**Comment by chennes** [comment]
@marioalexis84 if you're good with this now, can you please hit the "approve" button on the reviewer screen? Thanks!

**Review by marioalexis84 — APPROVED** [review]
I have tested it and found no problem.
The change in the writeABAQUS function removes the addition of an unnecessary comma.

**Pull request merged**
