### PR TITLE
UI: update FEM icons

### PR DESCRIPTION
**Pull request by maxwxyz**
fixes https://github.com/FreeCAD/FreeCAD/issues/13125
fixes https://github.com/FreeCAD/FreeCAD/issues/13141
fixes https://github.com/FreeCAD/FreeCAD/issues/13143
also changes icons to be consistent. WB icon also changed.

### CODE REVIEW

**Comment by FEA-eng** [comment]
That's a major overhaul, cool. Maybe just "E" could be a bit more visible in FEM_SolverElmer.svg

And I'm thinking about small changes in those S icons - their gear and play button symbols could be slightly bigger.

**Comment by maxwxyz** [comment]
@FEA-eng done. For Elmer I now used their simplified logo.

**Comment by FEA-eng** [comment]
> @FEA-eng done. For Elmer I now used their simplified logo.

Great, thanks.

**Comment by marioalexis84** [comment]
For the Contours icon, a different color could be used for each isoline.

**Comment by maxwxyz** [comment]
@marioalexis84 done.

**Pull request merged**
