### PR TITLE
Functions deprecated in freecad v0.17 are removed

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by donovaly** [comment]
The CI fails but it seems your PR is not the reason. Can you please rebase and force-push your PR to trigger another CI run?

@Roy-043 , can you please review the PR?

**Comment by donovaly** [comment]
@mosfet80 , to avoid the merge commits you need to rebase to master and then on pushing it is important to set the option to force push

**Comment by donovaly** [comment]
OK, the CI error is real: https://github.com/FreeCAD/FreeCAD/actions/runs/4441102614/jobs/7795757611

So not only the path tests fail, also the ones for Draft.

**Comment by donovaly** [comment]
Why do you close this PR and open a new one instead? The new one has no proper description.

**Comment by Roy-043** [comment]
> OK, the CI error is real

How do you find the errors in that 5000+ line report?

**Comment by donovaly** [comment]
>How do you find the errors in that 5000+ line report?

This is what you see as report:

firefox_XT4DXGuQFO

click on the red icon and the section opens. The errors are at the end of that section

**Pull request closed without merging**
