### PR TITLE
[Hold]Material: Create and save material colors as 3 floats

### PR DESCRIPTION
**Pull request by justnope**
This fixes creating emissive, specular,.. colors in the material card dialog and changing the diffuse color.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Before merging the PR we must reach consensus to represent colors with int or float

**Comment by justnope** [comment]
No worries. I can work with both representations.
I'll post a reply in the forum. Basically it will say: although I have a very slight preference in the end floats or ints, alpha or no alpha, if it's consistent for all colors then I'm good with it.

**Comment by wwmayer** [comment]
it's up to @berndhahnebach to decide how to handle colors there because did a lot of on the material editor.

**Comment by berndhahnebach** [comment]
I will have look.

**Pull request closed without merging**
