### PR TITLE
FEM: Start examples rework

### PR DESCRIPTION
**Pull request by FEA-eng**
As discussed in #15776, this PR replaces the current 3 FEM examples with one containing all the 3 versions of the cantilever beam analysis in Group containers. A text document with a short description was also added. Moreover, the deprecated Fem.FCStd and Fem2.FCstd files were removed and any references to the removed FEM examples were also corrected.

@qewer33 and @marioalexis84 FYI

### CODE REVIEW

**Comment by qewer33** [comment]
Awesome, thank you!

**Comment by luzpaz** [comment]
Does this close any other FEM tickets ?

**Comment by FEA-eng** [comment]
> Does this close any other FEM tickets ?

No, but #15754 may need to be merged first (or updated) since it modifies the files that I removed here. @maxwxyz

**Review by maxwxyz — CHANGES_REQUESTED** [review]
Could you please save without the logo thumbnail to be in line with: https://github.com/FreeCAD/FreeCAD/pull/15754


Bildschirmfoto 2024-08-05 um 21 08 21

Currently the icon is in the bitmap. You can disable the logo in the preferences > document

**Comment by FEA-eng** [comment]
> Could you please save without the logo thumbnail to be in line with: #15754

Sure, done. I don't know if I can mark this change request as resolved or if you have to do it.

But I guess that your PR will still have to be merged first, right?

**Review by maxwxyz — APPROVED** [review]
Looks good.

Off-topic:
Interestingly your legend is rendered black in the thumbnail but appears white when opening the file.
I clicked on the visibility of the 2D folder and the legend disappeared, do you know how I can get this back? I tried double clicking on the legend but there were only color options and I clicked cancel, now the entire model became green:

Bildschirmfoto 2024-08-07 um 12 48 40

Edit: selecting the WarpVector brings back the color but I can reproduce it when clicking on the legend and cancelling.

**Comment by FEA-eng** [comment]
> Looks good.

Thanks. I guess that merging your thumbnail PR may cause conflicts with this one. Could you exclude the 5 files that I delete here (including obsolete Fem and Fem2) from it?

> Off-topic: Interestingly your legend is rendered black in the thumbnail but appears white when opening the file. 

At the beginning of the release cycle, there was a change in legend fonts. It used to be black but now it's white by default. This behavior might be a leftover from this change. Especially if you have 0.21.2 installed on the same machine.

> I clicked on the visibility of the 2D folder and the legend disappeared, do you know how I can get this back? I tried double clicking on the legend but there were only color options and I clicked cancel, now the entire model became green:

I can't reproduce those issues on Windows but the legend is still very buggy and often jumps to the right hiding all labels like in your screenshot. I hope that it will get a major fix in the next release cycle.

**Comment by chennes** [comment]
Conflicts resolved, waiting on CI.

**Pull request merged**
