### PR TITLE
Fem: Add electrostatic constraint symbol

### PR DESCRIPTION
**Pull request by marioalexis84**
@FEA-eng

Screenshot_20241214_170905

### CODE REVIEW

**Comment by FEA-eng** [comment]
It looks good in general but I've noticed that, unlike with other constraint symbols, this one doesn't appear right after adding a geometrical entity to the selection (it shows up only after quitting the tool's task panel).

Do you plan to add symbols for other electromagnetic constraints as well for consistency?

**Comment by marioalexis84** [comment]
Yes, this is the current behavior for FeaturePython-based constraints. I am redesigning the task panels so that Python and C++ constraints behave the same way.
The idea is to add symbols for all constraints and boundary conditions.

**Review by FEA-eng — APPROVED** [review]

**Comment by maxwxyz** [comment]
To be merged after CI passes

**Comment by maxwxyz** [comment]
@chennes CI still fails here

**Pull request merged**
