### PR TITLE
[Robot] fix typo reported by spellchecker CI

### PR DESCRIPTION
**Pull request by donovaly**
- Accelaration -> Acceleration

- plus some style fixes done by MSVC

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6419">pipeline status</a> for feature branch [PR_6419](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6419). Pipeline [476344163](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/476344163) was triggered at [ae11a12](https://github.com/FreeCAD/FreeCAD/pull/6419/commits/ae11a12de9243752e0b259c6c605bdce2efb67e7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
This causes a build failure
```
../../../../../src/Mod/Robot/Gui/TaskTrajectory.cpp: In constructor 'RobotGui::TaskTrajectory::TaskTrajectory(Robot::RobotObject*, Robot::TrajectoryObject*, QWidget*)':
../../../../../src/Mod/Robot/Gui/TaskTrajectory.cpp:84:84: error: 'class Robot::Waypoint' has no member named 'Accelaration'; did you mean 'Acceleration'?
   84 |         ui->trajectoryTable->setItem(i, 4, new QTableWidgetItem(QString::number(pt.Accelaration)));
      |                                                                                    ^~~~~~~~~~~~
      |                                                                                    Acceleration
```

**Comment by donovaly** [comment]
I found even more instances and fixed them now.

The problem was that my compiler broke yesterday, meaning it compiled everything, no matter if typos or missing headers. (the result was a binary that crashed immediately.)
Thanks to the CI I could continue my cleanup work.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6419">pipeline status</a> for feature branch [PR_6419](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6419). Pipeline [477358227](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/477358227) was triggered at [105eb7a](https://github.com/FreeCAD/FreeCAD/pull/6419/commits/105eb7adb0352a0eedc86ee5d1f5a55422822154). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
