### PR TITLE
[Arch] Remove obsolete code related to the Drawing WB

### PR DESCRIPTION
**Pull request by Roy-043**
This PR removes obsolete code related to the Drawing WB.

Additionally:
* Arch_Panel_Sheet_Tree.svg to replace Draft_Drawing.svg
* Removed the underscore from Draft base class names.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9162">pipeline status</a> for feature branch [PR_9162](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9162). Pipeline [826777381](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/826777381) was triggered at [d116f82](https://github.com/FreeCAD/FreeCAD/pull/9162/commits/d116f82abc1f9bcba4d32c47af6e0928c247866a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Wouldn't we rather convert these Drawing-based panel tools to TechDraw? They contain some specific code to render text, which won't work that well without it

**Comment by Roy-043** [comment]
The makePanelView code cannot be used from the GUI as there is no command that invokes it (in V0.17-V0.21). Nor can I find any reference to "PanelView" in the code of the Drawing Workbench. Testing the function from the Python console in V0.17 shows that it does create a Drawing page and a view on that page. But that view is only visible in the tree, the page itself seems empty. Maybe the code has never worked properly?

The current (V0.21) workflow is to create a PanelCut from the panel (the PanelCut can show the tag, label or description of the panel) and create a Draft view from that in the TD workbench.

The PanelView code is therefore obsolete IMO.

[Panel_PanelView_V0.17.zip](https://github.com/FreeCAD/FreeCAD/files/11180149/Panel_PanelView_V0.17.zip)
[Panel_PanelCut_V0.21.zip](https://github.com/FreeCAD/FreeCAD/files/11180148/Panel_PanelCut_V0.21.zip)

**Comment by yorikvanhavre** [comment]
Hm yes I remember now... the panel tag is actually a shapestring, because it needs to be engravable. Ok, my mistake! This is good to go then

**Pull request merged**
