### PR TITLE
[For 0.19] TechDraw: add Balloons

### PR DESCRIPTION
**Pull request by fjullien**
This PR add a new Balloon command to TechDraw.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by fjullien** [comment]
Wait before merge, I found a problem when suppressing balloon in some conditions.

**Comment by fjullien** [comment]
Please contact me before you merge this

**Comment by wwmayer** [comment]
@WandererFan please have a look at this PR as it affects your area.

**Comment by WandererFan** [comment]
OK, will do.

**Comment by WandererFan** [comment]
Werner, this PR is OK.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
