### PR TITLE
[Do not merge][Travis] Update CI to use new libpack location

### PR DESCRIPTION
**Pull request by chennes**
The Windows Travis builds were failing because the old libpack is no longer available in the specified location. This PR updates Travis to pull the Windows Libpack from the 0.19.1 release tag -- note that this also updates the libpack version and therefore all included libraries.

### CODE REVIEW

**Review by hyarion — APPROVED** [review]

**Comment by luzpaz** [comment]
We should merge this ASAP. Thanks chennes!

**Comment by chennes** [comment]
Just an update: this is now building and running on Travis/Windows, but the FEM test app is not loading.

**Comment by chennes** [comment]
I'm marking this as ready to review since it does fix the problem it claims to: but it also leaves us with another problem, since the FEM unit test won't load.

**Comment by hyarion** [comment]
Please add [Do not merge] to the title while testing the windows builds so it doesn’t get merged by accident.

**Comment by wwmayer** [comment]
I will cherry-pick a0620dc2cc97aea1c8e and add it to master because as it is now all Windows builds fail

**Comment by luzpaz** [comment]
> Please add [Do not merge] to the title while testing the windows builds so it doesn’t get merged by accident.

Or just set the PR to a [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

**Comment by chennes** [comment]
@wwmayer has integrated the only real contribution from this PR (the rest was just working on testing Travis), so I'm closing it now that he's found the solution to the FEM stuff.

**Comment by wwmayer** [comment]
In I have added the system32 directory in e825148cf454 to the search path which didn't solve the problem. My alternative idea (8277b3f9e9) was to disable Netgen support to avoid to try to load nglib.dll and this did the trick.

Conclusion: apparently on the travis system the files opengl32.dll and glu32.dll are missing. Can this really be true?

**Comment by sgrogan** [comment]
For opengl32.dll  this is a problem  reported for Win virtual machines. Qt provides openglsw.dll which is in the Libpackx. If this is renamed opengl.dll it is known to solve the problem, sometimes.

**Pull request closed without merging**
