### PR TITLE
[Github] Add "detet" to the ignored misspellings

### PR DESCRIPTION
**Pull request by Floriansimmer**
see: https://github.com/FreeCAD/FreeCAD/pull/6464#issuecomment-1066980812

### CODE REVIEW

**Review by luzpaz — APPROVED** [review]

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6666">pipeline status</a> for feature branch [PR_6666](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6666). Pipeline [502142283](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/502142283) was triggered at [e3d5c2a](https://github.com/FreeCAD/FreeCAD/pull/6666/commits/e3d5c2a37afe173e5c1ddb85c8b5408e4db5bc94). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@Floriansimmer thanks. BTW, please use [skip ci] next time as this PR doesn't merit a built test

**Comment by donovaly** [comment]
Thanks.

> please use [skip ci] next time as this PR doesn't merit a built test

In this case we want the CI to run, to see the changed spellchecker in action.

**Comment by luzpaz** [comment]
I'm confused, @donovaly. 'run' on what? There is no input file for it to be tested against in this PR.

**Comment by donovaly** [comment]
> 'run' on what?

On everything ;-) Sometimes the spellchecker runs on the entire code. Here it did not but he could not know this.

**Pull request merged**
