### PR TITLE
fix default state of combo view #backport

### PR DESCRIPTION
**Pull request by funny0facer**
Hi, this is my first PR to FreeCAD.

This is related to the following forum thread: [Start-up, Combo-View: task panel instead of Model panel](https://forum.freecad.org/viewtopic.php?t=74583)

I know, that I should actually base a PR on "main", but as this has - at least from my observation - no impact on 0.22, I chose 0.21 as a base.
I saw that a 0.21.2 is in the making... I hope, this is not too late.
thanks

### CODE REVIEW

**Comment by chennes** [comment]
Thanks for the PR -- calling @adrianinsaval for an evaluation.

**Comment by adrianinsaval** [comment]
I could be very wrong but this seems a hardcoded hack to suit the preference of one person

**Comment by funny0facer** [comment]
I am sorry. The idea for the solution itself was not my idea. See referenced forum post.
I will not insist on a merge. I agree it is a quite minor inconvinience, even though i am not completely alone (I did not create the forum post in the beginning)
In general, I am looking forward for the Tasks view in 0.22 which seems quite nice with its auto-hide functionality.

**Comment by adrianinsaval** [comment]
I think we just leave this as is. Next version is not so far

**Comment by funny0facer** [comment]
this is fine for me.

**Pull request closed without merging**
