### PR TITLE
Base: fix #2996 PyObjectBase notification breaking links

### PR DESCRIPTION
**Pull request by DeepSOIC**
Add an attribute "isTrueRef" to generate-from-xml. If set, the
object is treated as a direct reference to the object the attribute
returns, so no reassignment is performed.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I don't understand totally what this does. 
That's a mission for... @wwmayer  !

**Comment by DeepSOIC** [comment]
Since the tracker issue was lost, I'm linking in the thread:
https://forum.freecadweb.org/viewtopic.php?f=10&t=20597&start=10#p168380

**Comment by wwmayer** [comment]
The tracker issue is still there: https://freecadweb.org/tracker/view.php?id=3016

**Comment by DeepSOIC** [comment]
> The tracker issue is still there
and also https://freecadweb.org/tracker/view.php?id=3014 looks quite similar. Is the tracker already fixed? Judging by the number of bugs in "general" category, it's not

So. Should I update the commit message to point to one of these bugs (which one)? Or just link to the forum thread?

**Comment by DeepSOIC** [comment]
The issue is there again, available by its original number, thanks @kkremitzki !
http://freecadweb.org/tracker/view.php?id=0002996

If there's anything subtly wrong with this fix, don't hesitate telling me.
For example, I think maybe "IsTrueRef" name choice isn't great, I think of renaming it into something more specific, such as "EnableNotify"... but it doesn't sound very good too.

**Comment by wwmayer** [comment]
This PR doesn't fix the root of the problem but simply hides by stopping the chain of notification at a certain level. The real problem is fixed in a2dd176

**Comment by DeepSOIC** [comment]
I disagree. My fix is a fix for the root of the problem, because notification chain should be stopped there. Reassigning links is absolutely unnecessary, and an object that has the link touched whereas it shouldn't be. 
My opinion is that the notification system is broken by its very concept, i.e. making a copy behave as if it were a reference.

**Comment by wwmayer** [comment]
> I disagree. My fix is a fix for the root of the problem, because notification chain should be stopped there.

No, it is only a workaround and hides the problem. The real problem is that it must not happen that inside the dict of PyObjectBase an attribute object suddenly is considered as parent object or vice versa. This is what the above commit fixes. The same problem could re-occur on low-level data classes then stopping the chain for PropertyContainers won't fix anything.

> Reassigning links is absolutely unnecessary, and an object that has the link touched whereas it shouldn't be.

Yes, here I agree that on this level the chain can be stopped. That's why I didn't close the PR. But I am not happy with some naming and the fact that the generated file generateModel_Module.py is manually changed. As soon as the file gets re-generated all changes are lost and will cause tons of build errors.

> My opinion is that the notification system is broken by its very concept, i.e. making a copy behave as if it were a reference. (EDIT) and consequently causing trouble when applied to real reference.

The solution is not perfect but what are the alternatives? Using real references everywhere as you suggest simply doesn't work and will cause crashes everywhere. A soon as the central C++ instance is destroyed (e.g. a DocumentObject) then all its memory is freed and if there is still somewhere a Python wrapper object for one of the properties or of its sub-elements  and it is invoked you may or may not get a crash. Have fun to find this kind of errors!

Another point is that e.g. to make undo/redo work properly it must be disallowed that the data can be modified from everywhere.

**Comment by DeepSOIC** [comment]
> generated file generateModel_Module.py

Aha, that's why it is so ugly! I didn't notice the file is generated. I'll try to rework it then.

> But I am not happy with some naming

+1, but I would like suggestions.

> The same problem could re-occur on low-level data classes then stopping the chain for PropertyContainers won't fix anything

Maybe disable it everywhere by default, and enable it explicitly in specific places, such as Placement and Vector?

> The solution is not perfect but what are the alternatives? Using real references everywhere as you suggest simply doesn't work and will cause crashes everywhere.

It is solved for DocumentObject by not destroying its Py counterpart, but marking it invalid instead. Sure, proper solution is going to be very long and boring. 

Another alternative is to implement it like it works in C++: have methods getValue/setValue. Which is somewhat equivalent of simply removing the notification system altogether. After all there is a bunch of places already where attributes return copies, and offer no notification update (e.g. PropertyLinkList: doing Group.Group.append(object) does nothing).

**Comment by wwmayer** [comment]
> Aha, that's why it is so ugly! I didn't notice the file is generated. I'll try to rework it then.

No need. I will do it today evening.

> +1, but I would like suggestions.

What about **Notify**? Then it's also clear it is related to the notification chain as it anyway has not much to do with true references or not.

> Maybe disable it everywhere by default, and enable it explicitly in specific places, such as Placement and Vector?

I think as you suggested it for PropertyContainer should be fine. There are not so many classes where PyObjectBase is used as wrapper other than PropertyContainer & sub-classes. It's Vector, Placement, Rotation, Matrix and maybe a few more.

> It is solved for DocumentObject by not destroying its Py counterpart, but marking it invalid instead. Sure, proper solution is going to be very long and boring.

It's only done for DocumentObject and ViewProvider this way because there you can't make a copy. But doing this for any kind of Python wrappers is not feasible.

> Another alternative is to implement it like it works in C++: have methods getValue/setValue.

I fear no Python guru will accept such a solution. It is more or less the same as what we had before the automatic notification where you needed to create a tmp. object and then assign it. For lengthy expressions like object.Placement.Position.x = 123.0 it is a pain.

**Comment by DeepSOIC** [comment]
OK, then "Notify" it be, sounds good enough to me =)

I'm waiting for it to rebase my containers work then. There, I have already rewritten commit history, and I'm preparing a test request/PR/feature announcement message.

**Comment by wwmayer** [comment]
df1e264

**Comment by DeepSOIC** [comment]
Thanks!

**Pull request closed without merging**
