### PR TITLE
[0.20][PATH] Deburr improve

### PR DESCRIPTION
**Pull request by Schildkroet**
Added option to select an angled face (chamfer) for a deburr operation
Added option to deburr an arc segment (open circle)

image

### CODE REVIEW

**Comment by J-Dunn** [comment]
This is nice. I've always thought it was a shame not be able have the chamfer on the model. This is important when designing in relation to other features.  Thanks.

**Review by Russ4262 — APPROVED** [review]
I recall working on this with Schrildkroet and tracking down a bug.  It works as intended.  Current Deburr test passes, as do the others.

Thanks for the improvement, sir.

**Comment by Russ4262** [comment]
Afternoon Schildkroet.
Does this PR need to be rebased due to changes that have occurred since its submission?

**Comment by Schildkroet** [comment]
I updated the branch. No coflicts. Checks are still running

**Comment by sliptonic** [comment]
This looks ok so I'll merge.  The opExecute method is getting quite long and heavily indented.  That's usually a clue that it's doing too much and should be refactored.  I see a couple parts of it that could be pulled out to helper functions.  Not critical but worth noting.

**Pull request merged**
