### PR TITLE
Turns on C++11 support for GCC and Clang

### PR DESCRIPTION
**Pull request by ianrrees**
Following up on result from http://forum.freecadweb.org/viewtopic.php?f=10&t=14006 - I'd like to propose that we switch on the compiler options for C++11 on platforms where those are used.  These don't appear to have negative effects when building gcc versions going back at least to 4.5, and don't affect builds on Windows.

On recent MacOS at least, building without -std=c++11 can result in lots of compile warnings when newer libraries are used.

### CODE REVIEW

**Comment by bblacey** [comment]
Hey Ian,

Looks like a bug slipped through with this pull-request.  Here's the patch to fix it.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 419427b..d7d4a46 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -69,7 +69,7 @@ IF(CMAKE_COMPILER_IS_GNUCXX)
     ELSE(GCC_VERSION)
         SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
     ENDIF(GCC_VERSION)
-ENDIF()
+ENDIF(CMAKE_COMPILER_IS_GNUCXX)
 
 # ================================================================================
 # Output directories for install target
```

**Comment by peterl94** [comment]
It depends on the version of cmake. The empty endif works fine with cmake >= 2.8, but was a required for 2.6. We should really officially update the minimum required version. I'm sure it doesn't work with 2.6 anymore, or at least not without warnings. Having the expression in the endif is not too bad, but I think having it in the else is totally weird. I find I'm always misreading it as an "else if".

Did you get a warning about a not matching if?

**Comment by bblacey** [comment]
Yep, on Travis-CI Linux builds...
```
CMake Warning (dev) in CMakeLists.txt:
  A logical block opening on the line
    /home/travis/build/bblacey/FreeCAD-MacOS-CI/CMakeLists.txt:67 (IF)
  closes on the line
    /home/travis/build/bblacey/FreeCAD-MacOS-CI/CMakeLists.txt:71 (ENDIF)
  with mis-matching arguments.
```

**Comment by peterl94** [comment]
Must be the version set with cmake_minimum_required than. I’m pretty sure ubuntu 12.04 has cmake 2.8

**Comment by bblacey** [comment]
It turns out the last patch was incomplete, the else GCC_VERSION was incorrect - this is the proper patch.  Verified with Travis-CI Linux build.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 419427b..9f0c474 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -66,10 +66,10 @@ IF(CMAKE_COMPILER_IS_GNUCXX)
                      OUTPUT_VARIABLE GCC_VERSION )
     IF(GCC_VERSION VERSION_GREATER 4.7 OR GCC_VERSION VERSION_EQUAL 4.7)
         SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
-    ELSE(GCC_VERSION)
+    ELSE(GCC_VERSION VERSION_GREATER 4.7 OR GCC_VERSION VERSION_EQUAL 4.7)
         SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
-    ENDIF(GCC_VERSION)
-ENDIF()
+    ENDIF(GCC_VERSION VERSION_GREATER 4.7 OR GCC_VERSION VERSION_EQUAL 4.7)
+ENDIF(CMAKE_COMPILER_IS_GNUCXX)
 
 # ================================================================================
 # Output directories for install target
```

**Comment by ianrrees** [comment]
Thanks for the fix Bruce.  I agree with Peter that the else(condition) construct is weird, so if we don't really support cmake 2.6 then it would be better to just bump the cmake minimum version.  If we actually do support cmake 2.6 then I suppose it's better to fill in the condition.

Not personally attached to either solution.

FWIW, Ubuntu 12.04 seems to use cmake 2.8: http://packages.ubuntu.com/precise/devel/

**Comment by bblacey** [comment]
All is good on os x, this just causes a regression on the default Linux distro on Travis-CI.  From a recent os: linux build node:

```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

Given the regression affects the Linux devs, one approach would be to fix the regression and then submit a separate pull request to set the cmake minimum to something reasonable to give the linux stakeholders a chance to weigh in...

**Comment by bblacey** [comment]
FYI, Travis default linux distro seems to be running cmake 2.8.7?

```
$ cmake --version
cmake version 2.8.7
```

**Comment by ianrrees** [comment]
@wood-galaxy - That crash is interesting - have you done a clean build and still see the crash?  What gcc are you using?  Can you run FreeCAD in a debugger and share a trace of the crash?  Thanks!

**Comment by wood-galaxy** [comment]
Le 01/02/2016 19:53, Ian a écrit :
>
> @wood-galaxy <https://github.com/wood-galaxy> - That crash is 
> interesting - have you done a clean build and still see the crash? 
> What gcc are you using? Can you run FreeCAD in a debugger and share a 
> trace of the crash? Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeCAD/FreeCAD/pull/83#issuecomment-178127506>.
>
yes, clean build, right now I'm on master and I manually added 
https://github.com/bblacey/FreeCAD-MacOS-CI/commit/5a26cec6d4ff84d8108e25569fa70f120eedf96d
But it still crash
More info here : http://forum.freecadweb.org/viewtopic.php?f=10&t=14087
I can give more bt in a couple of hours.

**Comment by ianrrees** [comment]
Interesting, I'll try to replicate the problem on a VM this evening.  From your backtrace, the error about no libstdc++ might be telling us something - I wonder if somehow FreeCAD is trying to use the wrong C++ standard library.

**Comment by wood-galaxy** [comment]
Le 01/02/2016 19:53, Ian a écrit :
>
> @wood-galaxy <https://github.com/wood-galaxy> - That crash is 
> interesting - have you done a clean build and still see the crash? 
> What gcc are you using? Can you run FreeCAD in a debugger and share a 
> trace of the crash? Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeCAD/FreeCAD/pull/83#issuecomment-178127506>.
>
About gcc version : gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

Is the trace on the forum is enough ? 
http://forum.freecadweb.org/viewtopic.php?f=10&t=14087&p=112695#p112667

**Comment by ianrrees** [comment]
Yep, thanks for the info!  I can reproduce the bug, currently trying to figure it out.

**Comment by wood-galaxy** [comment]
Le 02/02/2016 07:39, Ian a écrit :
>
> Yep, thanks for the info! I can reproduce the bug, currently trying to 
> figure it out.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeCAD/FreeCAD/pull/83#issuecomment-178401659>.
>
Ok, thank you !

**Comment by wood-galaxy** [comment]
Le 01/02/2016 20:26, Ian a écrit :
>
> Interesting, I'll try to replicate the problem on a VM this evening. 
> From your backtrace, the error about no libstdc++ might be telling us 
> something - I wonder if somehow FreeCAD is trying to use the wrong C++ 
> standard library.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeCAD/FreeCAD/pull/83#issuecomment-178140668>.
>
About the libstdc++ error. Don't worry, i think, it look like an ubuntu 
bug, i can fix it with 
http://stackoverflow.com/questions/32389977/import-error-no-module-name-libstdcxx

**Comment by ianrrees** [comment]
Very good!  I'm collecting information, but it's slow progress (running debug build of FreeCAD, in valgrind, in a virtual machine...).  One of the things that caught my eye earlier was a reported "invalid read" by PyObject_Free(), but applying the fix for your import problem doesn't seem to prevent the crash :/.

Am currently waiting on a build without the -std=c++11 option to see if there are any obvious differences, but might call it a day before it's done building.

**Comment by ianrrees** [comment]
Off to bed, but I think the bug is at src/App/DocumentObject.cpp line 275 - the boost::any essentially runs off into an infinite loop when -std=c++11 is enabled.

**Comment by ianrrees** [comment]
First try of fix in https://github.com/ianrrees/FreeCAD_tinkering/tree/20160203-boost-any-bug-workaround - haven't really tested it yet.

**Comment by wood-galaxy** [comment]
Le 02/02/2016 20:32, Ian a écrit :
>
> First try of fix in 
> https://github.com/ianrrees/FreeCAD_tinkering/tree/20160203-boost-any-bug-workaround 
> - haven't really tested it yet.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeCAD/FreeCAD/pull/83#issuecomment-178776845>.
>
That's fix it for me. :)

**Pull request merged**
