### PR TITLE
remove unused CXX standards.

### PR DESCRIPTION
**Pull request by mosfet80**
change boost min version to 1.65

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7349">pipeline status</a> for feature branch [PR_7349](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7349). Pipeline [609166429](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/609166429) was triggered at [7093288](https://github.com/FreeCAD/FreeCAD/pull/7349/commits/70932880d8692a181a2e9608fa89bd96b0c1d58f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks for the PR. Unfortunately we cannot go to C++17, see https://wiki.freecadweb.org/FreeCAD_1.0_Development_Cycle
Can you therefore please change the PR so that also C++14 is allowed?

**Comment by donovaly** [comment]
Ah, with Booth we can go up to 1.71: https://wiki.freecadweb.org/FreeCAD_1.0_Development_Cycle#Minimum_supported_library_versions

Can you change that too please?

**Comment by adrianinsaval** [comment]
> Thanks for the PR. Unfortunately we cannot go to C++17

what do mean, that page itselfs says

> This version of FreeCAD is compiled requiring the C++17 standard

And that was already the case for 0.20 too

**Comment by donovaly** [comment]
"and all C++17 features are allowed with two exceptions"

So there are exceptions -> we must allow below C++17. This is how I understand it.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7349">pipeline status</a> for feature branch [PR_7349](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7349). Pipeline [613022047](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/613022047) was triggered at [0150639](https://github.com/FreeCAD/FreeCAD/pull/7349/commits/0150639974f5ccc918f12d80f02e2bdaae6dbed9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
> So there are exceptions -> we must allow below C++17. This is how I understand it.

No, it just means we're still using the boost implementation of some stuff that's already in C++17 std because they work better, am I correct @wwmayer ?

**Comment by donovaly** [comment]
> we're still using the boost implementation of some stuff that's already in C++17 std

Ah, now I understand. Makes sense.

Merging the PR as it is.

@mosfet80 , feel free to make a further PR where you raise the limit to C++17 and to boost 1.71. Request then a review from @wwmayer fro that PR.

**Comment by wwmayer** [comment]
C++17 is the minimum supported C++ standard and the two exceptions where C++14 is forced are the Netgen plugin if the used netgen version is < 6.2 and in Path for a certain boost version.

However, this switch to C++14 is hard-coded inside the CMakeLists.txt files where needed and doesn't depend on the macro CompilerChecksAndSetups where C++11 is handled.

**Pull request merged**
