### PR TITLE
[Icons]Applying Icon Size Rules to TechDraw

### PR DESCRIPTION
**Pull request by Reqrefusion**
When starting the change in TechDraw, I first resized the slightly boring ones. The aspect ratios of the black icons have not changed, only the 48x48 area they are in has been changed and enlarged to fit it. And one or two more boring changes.

### CODE REVIEW

**Comment by maxwxyz** [comment]
@WandererFan FYI are these used somehow with respect to their size (48x48)?

**Comment by WandererFan** [comment]
AFAIK, the 64x64 icon size is for toolbar icons. The black icons are used in drop down lists, not toolbars.  The blue arrows are used on buttons in dialogs.   

Do the new sizes look reasonable in actual use?   They should be +/- the same size as the text in the drop down.

**Comment by WandererFan** [comment]
The icons are drawn as 16x16 for the drop downs.

**Comment by Reqrefusion** [comment]
So is there any obstacle to merging this PR? If there is such an obstacle, please close PR.

**Pull request merged**
