### PR TITLE
Plot: Expose src/Mod/Plot strings to translation

### PR DESCRIPTION
**Pull request by luzpaz**
Closes https://github.com/FreeCAD/FreeCAD-translations/issues/60

Also relies on https://github.com/FreeCAD/FreeCAD/pull/5037 to add Plot to the Crowdin `updatets.py` script

### CODE REVIEW

**Comment by chennes** [comment]
In order to have updatets.py create the appropriate TS files, we'll need to add a Resources/translations directory as well, and presumably update the CMakeLists.txt file to do something with it.

**Comment by luzpaz** [comment]
@chennes other workbenches have a put `Resources/translations/` within their `Gui/` directory. So should we appropriately create `Gui/Resources/translations/` then?

**Comment by chennes** [comment]
The mods that do that have separate App and Gui directories. But we do have several that don't: I think Addon Manager, Arch, and Draft all simply use Resources. That said, I don't actually care either way.

**Comment by berndhahnebach** [comment]
would you rebase the PR to make it run on CI?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by yorikvanhavre** [comment]
This PR basically doesn't modify anything anymore (just whitespaces/line fixes)... We could merge it already. Mind to remove the "draft" status @luzpaz ?

**Comment by luzpaz** [comment]
@yorikvanhavre I've marked for review and rebased. What do we do about  https://github.com/FreeCAD/FreeCAD-translations/issues/60 ? Is it not an issue anymore?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5042">pipeline status</a> for feature branch [PR_5042](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5042). Pipeline [423701021](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/423701021) was triggered at [e6ccc5c](https://github.com/FreeCAD/FreeCAD/pull/5042/commits/e6ccc5cae3ab79e695f1332355e6d141cbf110a3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@yorikvanhavre I should prob. rename this commit then, right? (ref: https://github.com/FreeCAD/FreeCAD/pull/5042#issuecomment-986070653)

**Comment by donovaly** [comment]
approved by yorik -> merging

**Pull request merged**
