### PR TITLE
Change PartDesign Pad and Revolution tree icons

### LINKED ISSUE #14066: Wrong tree icons for PD Pad and Revolution
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The icons for Pad and Revolution are blue, but the toolbar icon are yellow. Loft for example uses the same icon for the toolbar as for the tree. Pad and Revolution should do the same to be consistent in the color scheme for additive and subtractive features.

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37330 (Git)
Build type: Debug
Branch: main
Hash: a094bf0df7e2b3e5c5b2e3b158a9040a6474892f
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.3.0, OCC 7.3.0
Locale: German/Germany (de_DE)
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.62.0
  * Assembly3.backup1715897154.0970206 0.11.3 (Disabled)
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.2.0
  * fasteners 0.4.21
```

### Subproject(s) affected?

PartDesign

### Anything else?

There are two special icons:
* [Tree_PartDesign_Pad.svg](https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/PartDesign/Gui/Resources/icons/Tree_PartDesign_Pad.svg)
* [Tree_PartDesign_Revolution.svg](https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/PartDesign/Gui/Resources/icons/Tree_PartDesign_Revolution.svg)

while the others features all seem to use the `PartDesign_*.svg` icons.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NomAnor**
Use the same icons as the toolbar buttons.

Fixes #14066.

### CODE REVIEW

**Comment by maxwxyz** [comment]
I would hold back on this until we have consensus as this was done intentionally at some point, also in other workbenches.

**Comment by NomAnor** [comment]
I updated the icons based on the comments in #14066. I commented some screenshots.
@Reqrefusion provided some recolored versions of the icons.

* Some unused icons are removed
* All PartDesign features use the same icons for the toolbar and the tree
* All Part icons use a blue theme and the primitives use the same icon for the toolbar and the tree
* The task suggestions use the blue Part_Box icon in their header

**Comment by FEA-eng** [comment]
For me, the Shapebuilder icon is still yellow. Is it normal?

icon

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37436 (Git)
Build type: Release
Branch: main
Hash: 040502280fc9637fb3aada037523283168b81a02
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

**Comment by NomAnor** [comment]
Here too, its a problem with the BIM Workbench which has a copy of the yellow icon, but with the same name. I'll file an issue.

**Pull request merged**
