### PR TITLE
Part: Add Sketcher_NewSketch to Part toolbar 

### LINKED ISSUE #14190: Part should have the Create Sketch button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I know that toolbars can be customized and sketches are mostly created in Part Design but I think that it would be nice to have a button for a new sketch in Part wb as well. After all, operations like extrusion need some input and it's usually a sketch. So it would be convenient to have such a shortcut available by default.

sketch

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37436 (Git)
Build type: Release
Branch: main
Hash: 040502280fc9637fb3aada037523283168b81a02
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Part

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
fixes #14190

adds Sketcher_NewSketch to the Part menu and toolbar (right before Extrude)

sketch 1

sketch 2

### CODE REVIEW

**Comment by FEA-eng** [comment]
Preview:

sketch 1

sketch 2

**Comment by wwmayer** [comment]
If Part is the default workbench the change will cause this error message:
> CommandManager::addTo() try to add an unknown command (Sketcher_NewSketch) to a widget!

**Comment by FEA-eng** [comment]
> If Part is the default workbench the change will cause this error message:

Is there an easy way to avoid this? It was based on the PR where Part CheckGeometry was added to PartDesign toolbar and menu so I didn't expect such issues.

**Comment by wwmayer** [comment]
> It was based on the PR where Part CheckGeometry was added to PartDesign toolbar and menu so I didn't expect such issues.

There it works because PartDesignGui depends on PartGui. And because SketcherGui depends on PartGui too it's not possible to make PartGui depend on SketcherGui.

**Comment by FEA-eng** [comment]
> There it works because PartDesignGui depends on PartGui. And because SketcherGui depends on PartGui too it's not possible to make PartGui depend on SketcherGui.

Ok. And there's no way to fix it with some small workaround? Maybe it should be implemented differently - by adding a default custom toolbar with this button to Part wb. Like what you can do manually via Tools --> Customize --> Toolbars. Could it work this way?

**Comment by wwmayer** [comment]
You can do that in the InitGui.py file of the Part module:
```
# ***************************************************************************
# *   Copyright (c) 2002 Juergen Riegel <juergen.riegel@web.de>             *
# *                                                                         *
# *   This file is part of the FreeCAD CAx development system.              *
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU Lesser General Public License (LGPL)    *
# *   as published by the Free Software Foundation; either version 2 of     *
# *   the License, or (at your option) any later version.                   *
# *   for detail see the LICENCE text file.                                 *
# *                                                                         *
# *   FreeCAD is distributed in the hope that it will be useful,            *
# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
# *   GNU Lesser General Public License for more details.                   *
# *                                                                         *
# *   You should have received a copy of the GNU Library General Public     *
# *   License along with FreeCAD; if not, write to the Free Software        *
# *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *
# *   USA                                                                   *
# *                                                                         *
# ***************************************************************************
"""Initialization of the Part Workbench graphical interface."""

import FreeCAD as App
import FreeCADGui as Gui
import os




class PartWorkbench(Gui.Workbench):
    """Part workbench object."""

    def __init__(self):
        self.__class__.Icon = os.path.join(App.getResourceDir(),
                                           "Mod", "Part",
                                           "Resources", "icons",
                                           "PartWorkbench.svg")
        self.__class__.MenuText = "Part"
        self.__class__.ToolTip = "Part workbench"

    def tryAddManipulator(self):
        try:
            import SketcherGui

            class Manipulator:
                def modifyToolBars(self):
                    return [{"insert" : "Sketcher_NewSketch", "toolItem" : "Part_Extrude"}]
                def modifyMenuBar(self):
                    return [{"insert" : "Sketcher_NewSketch", "menuItem" : "Part_Extrude"}]

            manip = Manipulator()
            Gui.addWorkbenchManipulator(manip)
        except ImportError as err:
            pass

    def Initialize(self):
        # load the module
        import PartGui

        try:
            import BasicShapes.CommandShapes
        except ImportError as err:
            App.Console.PrintError("'BasicShapes' package cannot be loaded. "
                                   "{err}\n".format(err=str(err)))

        try:
            import CompoundTools._CommandCompoundFilter
            import CompoundTools._CommandExplodeCompound
        except ImportError as err:
            App.Console.PrintError("'CompoundTools' package cannot be loaded. "
                                   "{err}\n".format(err=str(err)))

        try:
            bop = __import__("BOPTools")
            bop.importAll()
            bop.addCommands()
            PartGui.BOPTools = bop
        except Exception as err:
            App.Console.PrintError("'BOPTools' package cannot be loaded. "
                                   "{err}\n".format(err=str(err)))

        self.tryAddManipulator()

    def GetClassName(self):
        return "PartGui::Workbench"


Gui.addWorkbench(PartWorkbench())

App.__unit_test__ += ["TestPartGui"]
```

**Comment by FEA-eng** [comment]
@wwmayer Thank you. It works with this change so I updated the PR. But the Create Sketch button landed at the end of the toolbar for some reason. Previously, it was the first button before Extrude (I positioned it this way in the Workbench.cpp file).

**Comment by wwmayer** [comment]
For me with the modified InitGui.py the sketcher icon is left from the extrude icon.

**Pull request merged**
