### PR TITLE
Fix DXF importer wrongly prioritizes the MEASUREMENT variable

### LINKED ISSUE #11394: [Problem] C++ DXF importer wrongly prioritizes the MEASUREMENT variable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The C++ DXF importer wrongly prioritizes the MEASUREMENT variable. It should first check INSUNITS. Only if this variable is missing or set to zero, should MEASUREMENT be considered.

Forum topic:
https://forum.freecad.org/viewtopic.php?t=82546

Test file:
[DXF_import_test_cpp.zip](https://github.com/FreeCAD/FreeCAD/files/13348195/DXF_import_test_cpp.zip)

For reference: algorithm used by the legacy importer:
https://github.com/FreeCAD/FreeCAD/blob/8b6d133c26857363bedec2ba31bacbecb2a9bf89/src/Mod/Draft/importDXF.py#L2079-L2092

### Full version info

```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35024 (Git)
Build type: Release
Branch: main
Hash: 4ff00ef99869e35295a5a17b8f486901504c655b
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tmksw**
In case INSUNITS are set to any valid (non-zero) value, prioritize INSUNITS over MEASUREMENT variable.

This PR resolves #11394 

This bug fix is also related to #6461 

image

### CODE REVIEW

**Comment by kpemartin** [comment]
My planned fix was to initialize m_eUnits to eUnspecified and have the code that handles $MEASUREMENT do something more or less like:
```
if (m_eUnits == eUnspecified && sscanf(...) == 1) {
    m_eUnits = n ? eMillimeters : eInches ;
}
```
This eliminates the (IMHO) confusing m_measurement_inch flag altogether, along with the burp to handle it near the start of `mm`, and leaves m_eUnits as eUnspecified if there is indeed nothing in the DXF to hint at any units. Note that `mm` treats eUnspecified the same as eMillimeters.

**Comment by yorikvanhavre** [comment]
Is that fix of yours coming somewhere, @kpemartin ? I am in favour to merge this PR already, because it's very small and already fixes the issue and acknowledges the work done by @tmksw , even if we come up with a more robust solution later...

**Comment by kpemartin** [comment]
I'm hoping to have it as soon as #11701 is accepted. That pr is fairly extensive and I'm still new with git so I would prefer to avoid juggling two possibly non-mergeable changes by having more than one active branch with changes in the same file.

**Comment by yorikvanhavre** [comment]
okay for you to close this one, @tmksw ?

**Comment by tmksw** [comment]
@yorikvanhavre My recommendation would be to proceed with this merge as it is very low risk and easy to get rid of when more holistic fix from @kpemartin will be available.

**Comment by kpemartin** [comment]
Sounds good to me

**Comment by yorikvanhavre** [comment]
Hm I should have merged this one first... Tried to fix the conflict but I think I screwed it all, sorry about that :sweat_smile: 
I'll cherry-pick the relevant commits instead

**Pull request closed without merging**
