### PR TITLE
Fem: Fix link scope for Python objects

### PR DESCRIPTION
**Pull request by marioalexis84**
Similar to [#14897](https://github.com/FreeCAD/FreeCAD/issues/14897), but for Material, Element geometry and Mesh Elements obejcts.

@FEA-eng

### CODE REVIEW

**Comment by FEA-eng** [comment]
Have you noticed some issues (similar to those reported in #14897) that should be fixed by this PR so that I can check if it works as expected? I've only encountered the ones with meshing.

**Comment by marioalexis84** [comment]
Create a PartDesign Body.
Add some feature (e.g a Box)
Create Fem Analysis
Add Material Solid.
Add the Box to material References.
recompute the object ---> The warning is raised

Same with the other Fem features mentioned.

**Comment by FEA-eng** [comment]
All right, I can confirm that this PR fixes it then. I thought that selecting an object in the 3D view using FEM feature selectors would pick the Body but it indeed picks the features inside it itself.

**Review by FEA-eng — APPROVED** [review]

**Comment by chennes** [comment]
@marioalexis84 can you clean up that bare exception catch by handling a more specific exception type? We'd also like to start addressing those linter warnings about missing function docstrings, if you have time to add a line about those methods.

**Comment by marioalexis84** [comment]
@chennes , I added a new `Base.PropertyError` exception that is more specific than `AttributeError` for use in `PropertyContainer` objects methods.
We can start completing docstrings in future pull requests.

**Pull request merged**
