### PR TITLE
Addon Manager: download and display Macro metadata

### PR DESCRIPTION
**Pull request by chennes**
This PR adds an option to download and display macro metadata. Doing so will also make it searchable using the filter box. The first-launch dialog is expanded to display the most important options, including this one. Note that this will make that dialog re-display for everyone, even those who had already seen the old version of the warning.

### CODE REVIEW

**Comment by Syres916** [comment]
Sorry Chris but `:=` (line 201 in addonmanager_macro.py) isn't backwards compatible to Python 3.6, I believe it first came in Python 3.8

**Comment by chennes** [comment]
You are right - back to the "old way' I guess! Thanks!

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5312">pipeline status</a> for feature branch [PR_5312](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5312). Pipeline [439824100](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/439824100) was triggered at [70c9804](https://github.com/FreeCAD/FreeCAD/pull/5312/commits/70c9804fc02570ba3d71bc3a253c42597f0ddc86). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5312">pipeline status</a> for feature branch [PR_5312](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5312). Pipeline [439855199](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/439855199) was triggered at [f48d79a](https://github.com/FreeCAD/FreeCAD/pull/5312/commits/f48d79a2271391b52b142a5fa0f5ebc3f60a631a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
