### PR TITLE
[GUI] Adjust Preferences dialog display position to be fully visible.

### PR DESCRIPTION
**Pull request by kisolre**
based on [commit](https://github.com/Syres916/FreeCAD/commit/b1effe2250dd17fbf632b0b65f94a9f60d0533ca)
forum thread [thread](https://forum.freecadweb.org/viewtopic.php?f=8&t=66410)

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6398">pipeline status</a> for feature branch [PR_6398](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6398). Pipeline [475020612](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/475020612) was triggered at [e2822de](https://github.com/FreeCAD/FreeCAD/pull/6398/commits/e2822dee53c48ed6b79fee3eafe555c83c30c185). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by kisolre** [comment]
Ok, it looks I have no proper idea how  Git works and it is becoming big mess here. Please, if somebody finds this usable make another pull request and comment here so I can trash this branch :(

**Comment by luzpaz** [comment]
@kisolre been there done that :stuck_out_tongue_winking_eye:  
Which commits are relevant?

**Comment by kisolre** [comment]
@luzpaz 
ce8980f62c67189c8feda96d67b773bf54372a1a  and
d8a80a36762e980ad04d930bcf7dc706f94643ab

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6398">pipeline status</a> for feature branch [PR_6398](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6398). Pipeline [475139149](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/475139149) was triggered at [d2c89de](https://github.com/FreeCAD/FreeCAD/pull/6398/commits/d2c89de69f861927a08030249187cf17b69907eb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
I created #6404 to replace this PR.
Thanks @kisolre!  
BTW, the @Syres916 repo (that you reference in the PR summary) needs a rebase :rofl:   
image

**Pull request closed without merging**
