### PR TITLE
Core: improve rotation axis affinity

### PR DESCRIPTION
**Pull request by bdieterm**
This adds new method "preferRotationAxisDirection" to the Base::Rotation class. Since there are two rotation axis (with opposite signs) that can represent the same rotation, the caller can specify a preferred rotation axis direction, for example the old rotation axis vector, to avoid sudden rotation axis flips.

Related discussion: https://forum.freecad.org/viewtopic.php?t=85552

### CODE REVIEW

**Comment by Jolbas** [comment]
I think it should handle the special cases where rotation angle is 0° or 180° which is quite common and then set the rotation axis to exactly the preferred axis.

**Comment by wwmayer** [comment]
Writing some unit tests would be good:
* https://github.com/FreeCAD/FreeCAD/blob/main/tests/src/Base/Placement.cpp
* https://github.com/FreeCAD/FreeCAD/blob/main/tests/src/Base/Rotation.cpp

**Comment by Jolbas** [comment]
I would prefer building this functionality into the `Rotation::evaluateVector()`. Then we can create a copy of the original rotation and then use `setValue(matrix)` and the axis would be kept if possible. Or `setValue(matrix)` directly on the original rotation. That way we doesn't need to do a lot to have access from python console too.

**Comment by bdieterm** [comment]
@Jolbas 

> I think it should handle the special case where rotation angle is 0° which is quite common and then set the rotation axis to exactly the preferred axis.

I am not sure if I understand this correctly. Do you mean to store the `preferedAxis` additionally to the `rawAxis` vector in each `Base::Rotation` object and then use it as a fallback value whenever angle gets 0° (even after many operations)? Then this gets really tricky. It does not only increase storage (also when saved in FCStd xml files), but this would then also override the current strategy of keeping the previously used rotation axis and could cause sudden axis-flips again. In my opinion, setting the proper desired axis without saving it would be a lower mental burden because you don't have an additional state (think of defining if two rotation objects are identical).


> void Rotation::evaluateVector()
> This would also keep the axis when setting the rotation by matrix in the Python console

Maybe I missed something, but as far as I can see in the code, assigning a Matrix to a `Base::Rotation` object is only possible by calling the constructor/initializer of the Rotation class. At that time the rotation object has an undefined or hard coded default value for the rotation axis. There is no useful preferred rotation axis defined yet that could be kept in `evaluateVector`. The function `evaluateVector` only gets interesting when an already created rotation object is modified, e.g. via `rot1 = App.Rotation(1, 2, 3); rot1 *= App.Matrix(...)`.


> void Feature::onChanged(const App::Property* prop)
> ...
>                 this->Placement.setValue(p);

The problem I see with this idea is that I would not trust the property to have the desired prefered rotation axis right from the beginning of its existence. If `this->Placement` (of the property) is created with a default value, the prefered rotation of the default value will be kept. When you create a rotation value with its own desired rotation axis (e.g. `App.Rotation(App.Vector(0, 0, -1), Degree=0)` and you want to assign it to the property, the first time you write to the property, then your desired rotation axis gets overwritten by the initial value of the property.

**Comment by kwahoo2** [comment]
@bdieterm 
Hello, I am the OP of the forum thread. 
I compiled the bdieterm:improveRotationAxisAffinity branch, and I can confirm that it fixes flipping in my test-case. I also downloaded the **matyk**'s files, and his animation seems to be fixed too.

Great work!

**Comment by Jolbas** [comment]
> I am not sure if I understand this correctly. Do you mean to store the `preferedAxis` additionally to the `rawAxis` vector in each `Base::Rotation` object and then use it as a fallback value whenever angle gets 0° (even after many operations)? Then this gets really tricky. It does not only increase storage (also when saved in FCStd xml files), but this would then also override the current strategy of keeping the previously used rotation axis and could cause sudden axis-flips again. In my opinion, setting the proper desired axis without saving it would be a lower mental burden because you don't have an additional state (think of defining if two rotation objects are identical).

No I didn't mean to store any addtional data. I meant the `preferRotationAxisDirection` method isn't necessary and could be replaced by just modifying `Rotation::evaluateVector`. My suggested code alone is enough to solve the described issues. It uses the previous rawAxis only to compare with the new quaternion before updating it.  Actually I think less could be stored to file. The quaternion data is not used for restoring from file since 7 years and its probably enough to keep the possibility to restore old files but not necessary to save it to new files.

> Maybe I missed something, but as far as I can see in the code, assigning a Matrix to a `Base::Rotation` object is only possible by calling the constructor/initializer of the Rotation class. 

You can `setValue(matrix)` on existing rotations and placements. This is also used by python function. What happens in my suggested change of `void Feature::onChanged(const App::Property* prop)` is that a copy of the current placement is created to setup the default axis: `Base::Placement p(this->Placement.getValue());`. Then the matrix is applied to the copy and `evaluateVector()` will take care of selecting a best choice of new axis.

**Comment by Jolbas** [comment]
> @Jolbas
> 
> > I think it should handle the special case where rotation angle is 0° which is quite common and then set the rotation axis to exactly the preferred axis.
> 
> I am not sure if I understand this correctly.

What happens in your implementation if object `rot1` has angle is 0° and axis 0,0,1. This is what you currently always get when you set the rotation using a quaternion or matrix. Then you invoke `rot1.preferRotationAxisDirection(0.0, -0.7, -0.7)`. In your implementation I think the axis will be set to 0, 0, -1 but I suggest it would better be set to 0.0, -0.7, -0.7

**Comment by bdieterm** [comment]
> You can `setValue(matrix)` on existing rotations and placements. This is also used for python setting and getting Matrix from a placement and similarly setting and getting Q from a rotation.

You are right. But this `setValue(matrix)` method is not exposed to the Python interface. You can modify, for example, the `Angle` attribute of a Python rotation object in-place, but for assigning a matrix to a Python rotation object you have to create a new object through the `__init__` constructor. When staying within Python scripts, a rotation object could only be updated by a matrix (and keeping the preferred axis orientation) via the work-around
```python3
rot = App.Rotation(10, 20, 30)
mat = App.Matrix()
rot.setYawPitchRoll(*App.Rotation(mat).getYawPitchRoll())
```

By the way: I just discovered a bug: `Rotation::setEulerAngles` directly sets the private `quat` array, but without updating `_axis` (also no call to `evaluateVector`). And `setEulerAngles` is also exposed to the Python interface. I will create an extra PR for that later.


> Think a rotation `rot1`created with a quaternion or matrix with zero rotation. It is given the angle 0° and the axis 0,0,1 no matter the origin of the matrix. Then invoke `rot1.preferRotationAxisDirection(0.0, -0.7, -0.7)`, which is a vector saved from the initial rotation. In your implementation I think the axis will be set to 0, 0, -1 but I suggest it would better be set to 0.0, -0.7, -0.7

Ok, now I understand. That makes sense. But wouldn't it be better in that case to explicily create a rotation object specifying the angle=0 and rotAxis=something? Otherwise you really have to be sure that the angle is exactly zero and not 1e-14.

Actually I would prefer to have a solution that does not need a `preferRotationAxisDirection` method -- that means updating `evaluateVector` as suggested by you (and also my first idea in the forum) and extending the Python interface to update the value of a rotation object in-place.

**Comment by Jolbas** [comment]
> Ok, now I understand. That makes sense. But wouldn't it be better in that case to explicily create a rotation object specifying the angle=0 and rotAxis=something? Otherwise you really have to be sure that the angle is exactly zero and not 1e-14.

Yes, maybe, but then in the given example the `onChanged()` of MeshFeature need to make that choice instead. And every macro that sets the placement through a matrix

>  But this setValue(matrix) method is not exposed to the Python interface.

Indirectly through the placements Matrix attribute it is. But the same problem occurs also when editing the Q attribute of a rotation
```python
rot1 = App.Rotation()
rot1.Axis = 0,0,-1
rot1.Q = rot1.Q
rot1.Axis # Will give vector (0.0, 0.0, 1.0)
```
It would be nice if the following would retain the Axis too:
```python
rot1 = App.Rotation()
rot1.Axis = 1,1,-1
rot2 = App.Rotation(rot1)
rot2.Axis # Currently also returns (0.0, 0.0, 1.0)
```
But that would require changing
```c++
int RotationPy::PyInit(PyObject* args, PyObject* kwds)
{
   ...
    if (PyArg_ParseTuple(args, "O!", &(Base::RotationPy::Type), &o)) {
        Base::Rotation* rot = static_cast<Base::RotationPy*>(o)->getRotationPtr();
        getRotationPtr()->setValue(rot->getValue());
        return 0;
    }

```
in RotationPyImp.cpp to something like this
```c++
int RotationPy::PyInit(PyObject* args, PyObject* kwds)
{
   ...
    if (PyArg_ParseTuple(args, "O!", &(Base::RotationPy::Type), &o)) {
        *getRotationPtr() = *(static_cast<Base::RotationPy*>(o)->getRotationPtr());
        return 0;
    }

```
because the `getValue()`will only give a pointer to the quaternion which cant provide any information about the axis but the signs of the coordinates if the angle is 0°

**Comment by bdieterm** [comment]
I did some deeper reflection about rotation axis affinity. Actually, implementing this in the `Base::Rotation` and `Base::Placement` classes would be the wrong path to follow -- it would only add a very small benefit at the high cost of complexity, mental burden, special cases, documentation and susceptibility to bugs. I would even venture to say that storing the rotation axis with the rotation angle (and also the raw rotation axis) in a `Base::Rotation` object additionally to the quaternion is a bad idea from my ignorant point of view -- having the rotation stored only as quaternion without any extra state would be the cleaner solution. I guess there have been reasons to implement it like this which I am not aware of (no sarcasm here).
Maybe it was because of making it easier to modify the rotation in the property editor panel.
Directly editing the axis or angle of a rotation object feels to me the same as if someone would also want to only edit the pitch angle of a rotation object that also saves its (raw) yaw, pitch and roll angles, expecting the yaw and roll values to stay the same.
For a simple rotation object, it is normal that the rotation axis can change when modifying the rotation, because the rotation axis (always paired with an angle) should only be one of many derived representations of the actual rotation.
There is also no unwrapped rotation angle affinity. Rotating an object in smaller steps around its constant rotation axis for several full rotations will also reset the angle to a -180°..180° or 0°..360° range (similar to the axis flip).

If there is a need to keep the rotation axis direction constant, I am sure that it can be implemented in a cleaner way, for example by using an expression for the whole rotation ([see the wiki page](https://wiki.freecad.org/Expressions#Object_creation_functions)) in the property editor instead of using an expression only for the angle.

**Comment by Jolbas** [comment]
I think we could go even further and drop the placement property entirely replacing it with a simple transformation matrix. Then the users can add extensions to the object after their liking to control it. The user can for example add the "Position" extension and the "Axis and angle" extension if it's the current behaviour that is wanted. There could be a "Yaw Pitch Roll" extension for those that find it more useful. Else the user can select any attachment mode to control the placement. Or a constraint like in the assembly workbench.

**Comment by bdieterm** [comment]
Actually we already have something similar. With the "three dots" button in the placement property you can open the placement task panel and view/edit the rotation as yaw, pitch, roll or rotation axis with angle.
A matrix representation in the placement property would lead to (temporary) invalid rotations as soon as you modify one of the nine values -- you have to update at least two of the three columns of the 3x3 matrix when changing a single rotation angle.

If someone wants to only modify the rotation angle in the property panel, I recommend to store the rotation axis outside the placement property, for example via an expression for the whole rotation or whole placement.

I will close this draft -- see my previous comment for the reasoning.

**Pull request closed without merging**
