### PR TITLE
[Translation] Remove French translation of workbench names

### PR DESCRIPTION
**Pull request by FlachyJoe**
and keep English words.

https://forum.freecadweb.org/viewtopic.php?f=12&t=66730

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6501">pipeline status</a> for feature branch [PR_6501](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6501). Pipeline [483331897](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/483331897) was triggered at [87f5842](https://github.com/FreeCAD/FreeCAD/pull/6501/commits/87f584292ba40161cc048fe19187c4abdf95734d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
Translations are done on https://crowdin.com/project/freecad and everything that was done in this PR will be overwritten by next crowdin merge. The correct way is to fix things on crowdin, then if really urgent request a merge, but we do it more or less each week anyway...

I'll close this pull request because there is no point in merging it, but don't hesitate to reopen if I'm mistaken somehow.

**Comment by luzpaz** [comment]
I haven't looked in detail, but workbench names shouldn't be translated.

**Comment by luzpaz** [comment]
Related to #5548

**Comment by FlachyJoe** [comment]
> I haven't looked in detail, but workbench names shouldn't be translated.

They currently are in preferences and related strings are hidden in Crowdin.
Can you please show them ?

I created a poll for menu titles translation in French : https://forum.freecadweb.org/viewtopic.php?f=12&t=66804

**Pull request closed without merging**
