### PR TITLE
Path job cleanup

### PR DESCRIPTION
**Pull request by mlampert**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Have you tested that this https://github.com/FreeCAD/FreeCAD/pull/802/commits/441ba7526531b9d124dbab5ac7d73f813673c196 doesn't break the translation mechanism?

In order to keep things working it must fulfill these conditions:
1. when running lupdate/pylupdate then it must pick up all strings marked for translation and put them into the .ts files with the correct context string
2. when running FreeCAD the translation system must use the correct context string when requesting the translated string

I think this PR doesn't break the latter point but I'm not sure about the former since I don't know if lupdate/pylupdate is clever enough to recognize the default context string passed to the translate function.

**Comment by wwmayer** [comment]
I have tested this and indeed commit 441ba75 breaks the translation system. Before the change there is this line of code in PathArray.py
translate("Path_Array", "Please select exactly one path object\n"))
And when running  pylupdate4 PathArray.py -ts test.ts the tool finds and adds the string to the .ts file.

Now after the change the line turns into
translate("Please select exactly one path object\n"))
and thus the pylupdate utility doesn't add this string to the .ts file any more

**Comment by mlampert** [comment]
Thanks for noticing and testing! Didn't know about pylupdate - will fix.

**Comment by mlampert** [comment]
I checked pylupdate and the strings are extracted correctly again, with context and line numbers. I like this better anyway, there is now a single uniform interface for translate in all components.

**Pull request merged**
