### PR TITLE
Erase version 3

### PR DESCRIPTION
**Pull request by mac-the-bike**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7769">pipeline status</a> for feature branch [PR_7769](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7769). Pipeline [691009374](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/691009374) was triggered at [d3737fe](https://github.com/FreeCAD/FreeCAD/pull/7769/commits/d3737fe545f61939a6266fd972266ad1a5bf7fcf). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by mac-the-bike** [comment]
I have created a new pull request - this request, 7769, replaces 7560. I have done this because I don't know how to remove files from a commit. I have used the "Node set" code as a template for generating my "Erase Elements" code. So a lot of my code is a simple "copy and paste" with "Nodes" changed to "Elements". I have added my copyright but I have left the other copyright as I don't want to claim any credit for other people's work.

donovaly from pull request 7560:
I have taken note of your comments and changed my code appropriately thus:
enum - I have used comments instead
sorting of includes -  I have added my includes in the correct position
Command.cpp - the places you say should have comments are copied from the "Node Set" code

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7769">pipeline status</a> for feature branch [PR_7769](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7769). Pipeline [693828761](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/693828761) was triggered at [a99e816](https://github.com/FreeCAD/FreeCAD/pull/7769/commits/a99e816b4c6d8e24b773b3303404fc6bb5e622f5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@mac-the-bike could you please :
* rebase and squash your PR ?
* Explain in the description what it's aiming at ?

**Comment by luzpaz** [comment]
@mac-the-bike ping

**Comment by mac-the-bike** [comment]
0penBrain 

- rebase and squash your PR ? - how do I do this?
- Explain in the description what it's aiming at ? - where do I do this?

**Comment by 0penBrain** [comment]
> * rebase and squash your PR ? - how do I do this?

There are several methods. You can Google "git squash". 
> * Explain in the description what it's aiming at ? - where do I do this?

In the description of the PR (head comment).

**Pull request closed without merging**
