### PR TITLE
Measure: Fix measure issues in assemblies

### LINKED ISSUE #14559: Measurement: tool doesn't work properly in the Integrated Assembly WB
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When trying to measure (eg. distances, angles...) between two bodies of an assembly file or even trying to measure over a body inside the assembly, the results are incorrect.
The old distance measuring tool (in the Edit menu) works in those situations.

I have searched in:
- Github with [is:issue is:open measure label:"WB Assembly" ], with no results.
- FreeCAD forum with [Integrated Assembly workbench measure] and [Integrated Assembly workbench measurement] with no relevant results.

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37668 (Git) AppImage
Build type: Release
Branch: main
Hash: ea68c5e88cdc80044ede482f6ad908820f4c1c82
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Installed mods: 
  * Movie 2024.2.15
  * freecad.gears 1.2.0
  * A2plus 0.4.64a
  * FreeCAD-motion-workbench-master
  * dodo 1.0.1
  * Trails 2022.1.0
  * PieMenu 1.2.7
  * fasteners 0.5.21
  * Render 2024.1.23
```

### Subproject(s) affected?

Assembly

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

https://github.com/FreeCAD/FreeCAD/assets/18265355/7367efd0-7359-40c1-b50d-47d9d62d430a

https://github.com/FreeCAD/FreeCAD/assets/18265355/371afe1d-5b31-4c8e-9580-de852b98e25e

https://github.com/FreeCAD/FreeCAD/assets/18265355/3ac1be26-79a1-41cf-804b-66710f9ef544

[Ass_test_Github_3.FCStd.zip](https://github.com/user-attachments/files/15748264/Ass_test_Github_3.FCStd.zip)

### PR DESCRIPTION
**Pull request by hlorus**
As described in #14559 measurements don't properly work with the integrated assembly workbench. This PR adds checks for App::Link types and resolves them to get the responsible module and fixes the retrieval of the located shapes.

Closes #14559

### CODE REVIEW

**Review by chennes — CHANGES_REQUESTED** [review]

**Comment by FEA-eng** [comment]
@hlorus Can you resolve the conflicts?

**Review by chennes — APPROVED** [review]

**Comment by chennes** [comment]
...and another round of conflicts (I presume with the recent merge of another of your PRs, so hopefully they are an easy fix).

**Comment by yorikvanhavre** [comment]
Waiting because of conflicts

**Comment by chennes** [comment]
Did you mean to include a change to the OndselSolver submodule git ref?

**Comment by hlorus** [comment]
> Did you mean to include a change to the OndselSolver submodule git ref?

No, that was a mistake. Not quite sure how to revert submodule changes, i'll have to look into that.

**Comment by chennes** [comment]
I can confirm that this fixes the issues reported in #14559  -- the code seems sane to me, and since the PR is going on a month old I'm going to merge as-is. If there is further work to be done please create an Issue (or submit a PR 😉).

**Pull request merged**
