### PR TITLE
[Gui] ExpressionCompleter: fix some GitHub Action reports

### PR DESCRIPTION
**Pull request by donovaly**
- too long lines
- too short variable names

- also some reformatting according to our current clang file

### CODE REVIEW

**Comment by donovaly** [comment]
@acpopescu , GitHub actions [reports](https://github.com/FreeCAD/FreeCAD/pull/8264/commits/00e753c769d3e9982e25677af6354275aeca2c88) two of these issues:
`narrowing conversion from 'unsigned long long' to signed type 'qint32'`

Can you please have a look?

by the way you use `size() == 0` to check for emptyness. You can directly use `empty()`.

**Comment by donovaly** [comment]
> by the way you use `size() == 0` to check for emptyness. You can directly use `empty()`.

Fixed now in a second commit. Please check if OK.

**Comment by acpopescu** [comment]
They look good to me. I have a local change on this branch that fixes the qint32 issue., and a .size()==0 comparison which was not needed  - should I try to push it to your depot?

**Comment by donovaly** [comment]
> They look good to me. I have a local change on this branch that fixes the qint32 issue., and a .size()==0 comparison which was not needed - should I try to push it to your depot?

I would say, Step by step. So I merge this one then please make a further PR.

**Pull request merged**
