### PR TITLE
[Sketcher] 3-pt circle : allow tangent constraint for any click

### PR DESCRIPTION
**Pull request by 0penBrain**
https://forum.freecadweb.org/viewtopic.php?f=3&t=60596&p=520217#p520209

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [X]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

### CODE REVIEW

**Comment by luzpaz** [comment]
@abdullahtahiriyo any chance you can take a look at this soon?

**Comment by 0penBrain** [comment]
@yorikvanhavre I'll keep an eye on follow-ups. Anyway if there are problems, we can revert the commit as a quick fix. ;)

**Comment by luzpaz** [comment]
Please add feature to https://wiki.freecadweb.org/Release_notes_0.20 thanks!

**Comment by 0penBrain** [comment]
@luzpaz I have some concern about that as this isn't really a feature addition but a small fix. Anyway I'll add a few lines. ;)

**Pull request merged**
