### PR TITLE
Fem: Add box and elliptical beam section types - fixes #12614

### LINKED ISSUE #12614: [Problem] Missing FEM beam section types
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently, [FEM ElementGeometry1D](https://wiki.freecad.org/FEM_ElementGeometry1D) supports only rectangular, circular and pipe beam sections while CalculiX offers 3 more types:
- elliptical:
```
*BEAM SECTION, SECTION=CIRC
axis_1_length, axis_2_length
```
- box:
```
*BEAM SECTION, SECTION=BOX
a, b, t_1, t_2, t_3, t_4
```
- general - described in detail [here](https://forum.freecad.org/viewtopic.php?p=522386), moved to #15867

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36082 (Git)
Build type: Release
Branch: main
Hash: 7a025e4e60a607bdbdd1599627ce13bb8eeda071
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marioalexis84**
Fixes #12614

@FEA-eng

### CODE REVIEW

**Comment by FEA-eng** [comment]
Great, thanks for adding this. #12614 also includes a general beam section. Could you add it here or should I create a separate issue for it to be added in the future? I've tried implementing it 3 years ago but there were some issues with new units: https://github.com/FEA-eng/FreeCAD/tree/general_beam

**Comment by marioalexis84** [comment]
Please add a separate issue for general beam section as we need to add a new unit and new property for the moment of inertia.

**Comment by FEA-eng** [comment]
> Please add a separate issue for general beam section as we need to add a new unit and new property for the moment of inertia.

Ok, done: #15867

**Review by FEA-eng — APPROVED** [review]

**Comment by maxwxyz** [comment]
@marioalexis84 can you please resolve the conflicts?

**Comment by marioalexis84** [comment]
@maxwxyz branch rebased.

**Comment by WandererFan** [comment]
2024-1--29 no FEM expert available. deferred to next meeting.

**Comment by FEA-eng** [comment]
> 2024-1--29 no FEM expert available. deferred to next meeting.

I am on vacation until the end of this week. But I tested this PR in August and it was all good.

**Pull request merged**
