### PR TITLE
[Arch] Fix ifc project

### PR DESCRIPTION
**Pull request by Moult**
Please don't merge this PR! It is a work in progress!

https://forum.freecadweb.org/viewtopic.php?f=39&t=36663

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Looks great! Just need to add Arch Project to the Cmake file. I guess we could add the icon too :)
This PR also conflicts with a small fix I did in 0f56ec4135 would you mind adding it too? So we get rid of the github merge conflict...

**Comment by yorikvanhavre** [comment]
It seems you are working on several issues at once in this PR... This makes it harder for us to review and merge. Could you in the future take care of making different PRs for different issues? Thanks!

**Comment by Moult** [comment]
So as of the last commit, there is basic import and export of projects and CRS support.

There are many things still to be done. Here's a list off the top of my head:

 1. Support for project libraries, not just projects (perhaps this means I need to explore with types and psets that aren't part of a real element, since that is the purpose of a project library)
 2. Better UI in general - half the fields can be removed with an EPSG CRS selector just like in QGIS. Abscissa/ordinate fields can be merged. Then of course there are plenty of ways to make the UI look cleaner (line up fields, nicer looking headings, etc).
 3. Link CRS data to long/lat in the site object.
 4. Do true north calculation.
 5. Projects should support sites and sub-sites (really important in infrastructure projects)
 6. Projects should support including or referencing a project library
 7. Maybe even cool things like projects supporting a 2D plan representation context
 8. I'm sure there are bugs

As this PR is ready in terms of a basic implementation, would you like to review and merge this first, and then I can start working on the todo list in separate, smaller PRs? This might make it easier to review PRs, and start testing earlier because I'm sure there will be bugs. Alternatively, I can just keep on adding commits to this PR, but it could get rather large.

**Comment by yorikvanhavre** [comment]
Yeah let's merge this one already. I'll give it a test spin tomorrow

**Comment by Moult** [comment]
The merge commit 9b6cbef was done to resolve a merge conflict that appeared yesterday.

**Comment by Moult** [comment]
Not sure why the build failed, it was working before I resolved the merge conflict. However the merge conflict was only one line:

https://github.com/FreeCAD/FreeCAD/commit/9b6cbef894608728d341ded86de691b8d3d52634#diff-a67bc853387be10103213182e125ed0cL747

**Comment by Moult** [comment]
Bump?

**Comment by berndhahnebach** [comment]
is it still in progress or does it still waiting for review?

**Comment by Moult** [comment]
Waiting for review :) As it's quite a big change I'm sure issues will crop up, but I don't want this PR to get too large or deviate too much from master, since a lot of the import/export code needs refactoring too.

**Comment by yorikvanhavre** [comment]
Sorry things have been rather hectic here these days :sweat_smile: But I'm almost free! I'll review this first thing!

**Comment by berndhahnebach** [comment]
Done. Best might be to rebase this on uptodate master?

**Comment by yorikvanhavre** [comment]
Ok the contents of this PR is now merged with a937461d6f
I'm sorry, there was no way to maintain the history because of the large number of changes I had to do, both because of the importIFC split from #2388 and because this needed quite many fixes all over the place (none of my freecad files would export to ifc anymore)... In the future to avoid extra work and lengthy testing sessions it would be cool if you could make a bit smaller PRs ;)

**Comment by yorikvanhavre** [comment]
Related PPA package PR: https://salsa.debian.org/science-team/freecad/merge_requests/15

**Comment by berndhahnebach** [comment]
Arch modeule is some how broken ... 

https://forum.freecadweb.org/viewtopic.php?f=39&t=38651

**Pull request closed without merging**
