### PR TITLE
[Sketcher] Project ellipse pr

### PR DESCRIPTION
**Pull request by shermelin**
Implementation of the projection of ellipses in sketcher.

### CODE REVIEW

**Comment by vocx-fc** [comment]
Forum thread: [[Sketcher] projection of ellipses](https://forum.freecadweb.org/viewtopic.php?f=17&t=46480)

**Comment by abdullahtahiriyo** [comment]
@wwmayer I will review this one today (mutex)

**Comment by abdullahtahiriyo** [comment]
@wwmayer hopefully this time nothing passed through. I have pushed a fix just after the merge to remove warnings of unused variables and a unused function.

**Comment by shermelin** [comment]
@abdullahtahiriyo thanks forme reviewing my code. Sorry if I let some warnings at compilation, I'll try to be more thorough next time!
I just realised that I had added projlib_plane.hxx from occ, which I finally do not use…
Either I let you delete it or I will remove it on my next PR (which should be on the projection of arcs).

**Pull request merged**
