### PR TITLE
Measure: Use getGlobalPlacement method

### LINKED ISSUE #16058: Measure: wrong measurements in nested parts with linked objects
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Create part
2. Within part insert standard cube in Part workbench
3. Create Link (Std_LinkMake) to first cube within the same part
4. Move the linked cube e.g. y-position to 13mm
5. Insert measurement (Std_Measure) between two edges of the original cube and the linked cube
6. Move the part e.g. y-position to 10mm

Issue: the measurement is wrong and not positioned correctly (e.g. should be 3mm in the example but gives 7mm).

image

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38506 (Git)
Build type: Release
Branch: main
Hash: ebf02483af225b502fccfa7111499dfde33999fd
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Austria (de_AT)
Installed mods: 
  * Assembly4 0.50.4
  * OpenDark 2023.10.30
  * ProDarkThemePreferencePack 1.0.0
  * Woodworking 0.21.30486
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hlorus**
Currently the placement of linked elements is not retrieved correctly. This is due to the absence of a getGlobalPlacement method as described in #13978.
 
This PR is currently copying the method from the AssemblyObject class. With #11977 the method will be moved to the core and can be used here as well. 
This PR is set to draft until #15262 is merged.

Fixes #16058

### CODE REVIEW

**Comment by Rexbas** [comment]
I think you mean until #15262 is merged as that PR moves `getGlobalPlacement()` to a core location.

**Comment by maxwxyz** [comment]
@hlorus #15262 is merged now.

**Comment by FEA-eng** [comment]
@hlorus If it's ready, can you undraft it and rebase it to fix the CI?

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
