### PR TITLE
[TechDraw] Improve readability of DrawUtil.cpp

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195">pipeline status</a> for feature branch [PR_7195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195). Pipeline [589502869](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589502869) was triggered at [ba16841](https://github.com/FreeCAD/FreeCAD/pull/7195/commits/ba16841c0b6261b58cbdb96a9d6aed642523a3c8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
"return -1; // would this cause type errors???"

No, the compiler is smart enough to change -1 to -1.0, but the code should really specify the value as a float (-1.0).

**Comment by WandererFan** [comment]
"       angleMin = angleY; // why is anglemin assigned a new value??"
I imagine it is debris from a previous version where it didn't return until the end.  Should be ok to delete these.

**Comment by benj5378** [comment]
@WandererFan Oh, okay, thank you. I will just do an update then. Originally, I never meant to include these comments, they were just notes for myself

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195">pipeline status</a> for feature branch [PR_7195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195). Pipeline [589518973](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589518973) was triggered at [35b1b72](https://github.com/FreeCAD/FreeCAD/pull/7195/commits/35b1b7201767de83d8767e40b95364dcab534540). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195">pipeline status</a> for feature branch [PR_7195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195). Pipeline [589519652](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589519652) was triggered at [d1078c7](https://github.com/FreeCAD/FreeCAD/pull/7195/commits/d1078c7e85cfa0eacee194a66fed325153a71a49). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195">pipeline status</a> for feature branch [PR_7195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195). Pipeline [589533250](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589533250) was triggered at [1e30dc6](https://github.com/FreeCAD/FreeCAD/pull/7195/commits/1e30dc62c744c5cb096b080d279a0518e8c290f9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195">pipeline status</a> for feature branch [PR_7195](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7195). Pipeline [589536289](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589536289) was triggered at [d1078c7](https://github.com/FreeCAD/FreeCAD/pull/7195/commits/d1078c7e85cfa0eacee194a66fed325153a71a49). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
