### PR TITLE
Add lib64 to python path

### PR DESCRIPTION
**Pull request by dev-at-stellardeath-org**
On certain distributions the library directories are called "lib64" on
amd64 machines.

### CODE REVIEW

**Comment by wwmayer** [comment]
What is the reason to have?
Lib64Dir = FreeCAD.getHomePath()+'lib64'

Usually FreeCAD is installed under /usr/lib/freecad/... (or maybe /usr/lib64/freecad) and the output of FreeCAD.getHomePath() should be /usr/lib/freecad (or /usr/lib64/freecad respectively) but not just /usr.
FreeCAD's own libraries then go to /usr/lib/freecad/lib or /usr/lib64/freecad/lib respectively.

So, do you have a system where the FreeCAD package is configured to return just "/usr" as home path?
And if yes, does it actually find all its workbenches and resource files?

**Comment by dev-at-stellardeath-org** [comment]
(Sorry for the long delay)
Yes, on my system FreeCAD.getHomePath() actually returns "/usr". I don't know whether this is sensible, but everything seems to work. The origin of this is that it was set-up like that in an RPM packaged build of FreeCAD for openSUSE, which I wanted to update to a more recent version.

However, if this build is done in a very non-standard way I can try to set it up differently, I mostly took over the existing build procedure from the package that was available.

**Comment by saxa** [comment]
I think this should also go into CMakeLists file as on my slackware64 build I have to patch that file to get the things installed into /usr/lib64 which is the libdir according to the LFS.

**Comment by dev-at-stellardeath-org** [comment]
Ok, it was indeed configured strangely with a home path of "/usr", this created all sorts of directories below there.

I now package it with a home path of "/opt/FreeCAD". It still needs the patch to get its modules, otherwise all workbenches are missing. This is probably due to the way cmake is invoked by the distribution's rpm %cmake macro:

cmake -DCMAKE_INSTALL_PREFIX=/opt/FreeCAD -DLIB_SUFFIX=lib64 -DCMAKE_INSTALL_DATADIR=/opt/FreeCAD/share/FreeCAD -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/packages/FreeCAD -DCMAKE_INSTALL_INCLUDEDIR=/opt/FreeCAD/include/FreeCAD -DCMAKE_INSTALL_LIBDIR=/opt/FreeCAD/lib64 -DCMAKE_BUILD_TYPE=Release -DFREECAD_USE_EXTERNAL_ZIPIOS=TRUE -DFREECAD_USE_EXTERNAL_PIVY=TRUE ../

As I do not need to patch CMakeLists.txt, it seems that specifying some of these paths is not supported, it is thus probably also not sufficient to just add "lib64", the proper path that is specified to cmake should be included, CMAKE_INSTALL_LIBDIR

**Comment by saxa** [comment]
Would be really good that we could simply build FreeCAD to be installed according to the FHS so everything could go into the proper place instead of /opt/FreeCAD, I will see if I can get some time and try to propose a patch for this.

**Comment by dev-at-stellardeath-org** [comment]
That would be best, of course, and make this merge request unnecessary

**Comment by saxa** [comment]
Ok, will see if I can play a bit with it tonight.

**Pull request closed without merging**
