### PR TITLE
Build test, please ignore (ActiveContainer0)

### PR DESCRIPTION
**Pull request by DeepSOIC**
This is getting close to a real PR, feel free to look around if curious =)

### CODE REVIEW

**Comment by DeepSOIC** [comment]
@wwmayer 
Can you help me please? Builds failed because there's no precompiled.h in App/Containers. MSVC seems to ignore that, but Clang obviously doesn't. 

Should I create one? if yes, should I put some stuff into it, like inclusion of App/PreCompiled.h? Or should I include App/PreCompiled.h direcly?

**Comment by DeepSOIC** [comment]
Somehow inlusion of PreCompiled.h works in subdirectories in:
* src/Gui/DAGView/*.cpp (and many others)
* src/Mod/Part/App/Geom2d/*.cpp
but I can't seem to find anything special that makes it work there and not in src/App/Containers/*.cpp

I added a trivial PreCompiled.h to src/App/Containers/ to see if it fixes the build. If this does not work, I'm out of ideas.

**Comment by wwmayer** [comment]
The proper solution is to add ${CMAKE_CURRENT_SOURCE_DIR}
The ${CMAKE_CURRENT_BINARY_DIR}/Containers shouldn't be needed.

Can you do the following fixes, please?
1. Add the copyright notice to all new .cpp and .h files
2. It would be good to incorporate the namespace name into the file guard to avoid possible ambiguities. For example CONTAINER_H => APP_CONTAINER_H

Then it might be good to write a couple of unit tests to demonstrate the capabilities & requirements of the container framework.

**Comment by DeepSOIC** [comment]
> The ${CMAKE_CURRENT_BINARY_DIR}/Containers shouldn't be needed.

Then I get:
`T:\_vt\dev\PC\Qt\FreeCAD\FreeCAD-ellipse\src\App\Containers\ContainerBasePyImp.cpp:8: error: C1083: Cannot open include file: 'ContainerBasePy.h': No such file or directory`


> The proper solution is to add ${CMAKE_CURRENT_SOURCE_DIR}

Qt creator now recognizes the include, hopefully clang will too. Thanks!


> Can you do the following fixes, please?
sure! Thanks for looking into it.

There is a lot of stuff that I haven't done yet, such as container path retrieval, and workspaces. But I think I will actually write unit tests around containers first.

**Comment by wwmayer** [comment]
> C1083: Cannot open include file: 'ContainerBasePy.h': No such file or directory

Well, you could write #include <Containers/ContainerBasePy.h> It's how it's for Geom2d in the Part module, too.

**Comment by DeepSOIC** [comment]
Works, thanks again =)

**Pull request closed without merging**
