### PR TITLE
Add measurement icons

### PR DESCRIPTION
**Pull request by hlorus**
This PR addresses #13710

It adds icons to:
- the labels in the 3d view
- the elements in the tree view
- the measurement group in the tree view

Screenshot from 2024-05-14 17-28-19

Icons by @maxwxyz

### CODE REVIEW

**Comment by pierreporte** [comment]
This is great but the inertia icon is not that clear at first sight. Why not a spinning top ?

image

**Comment by FEA-eng** [comment]
@hlorus Btw. do you plan to change the area unit display from **cm^2** to **cm<sup>2</sup>** ? I haven't seen an issue for this but I think that I've seen it somewhere among the discussions. Should I create a new issue for this?

**Comment by FEA-eng** [comment]
> This is great but the inertia icon is not that clear at first sight. Why not a spinning top ?

If it's for COG/COM then I would use the classic symbol:

COG

**Comment by maxwxyz** [comment]
> > This is great but the inertia icon is not that clear at first sight. Why not a spinning top ?
> 
> If it's for COG/COM then I would use the classic symbol:
> 
> COG

That's used for COG/COM

**Comment by hlorus** [comment]
> @hlorus Btw. do you plan to change the area unit display from **cm^2** to **cm<sup>2</sup>** ? I haven't seen an issue for this but I think that I've seen it somewhere among the discussions. Should I create a new issue for this?

Yeah it's best to create an issue, otherwise it might get lost. Not sure why it's displayed that way, afaik UMF uses the standard quantity type so it should display the same way as in any other place. Are you sure it's specific to UMF?

**Comment by FEA-eng** [comment]
> Yeah it's best to create an issue, otherwise it might get lost. Not sure why it's displayed that way, afaik UMF uses the standard quantity type so it should display the same way as in any other place. Are you sure it's specific to UMF?

Thanks for the information. I'm not sure where else to check, to be honest. TechDraw displays it properly but it may not be representative. Quick measure displays it like UMF but it might be because it's based on it. I'm pretty sure you're right, I just thought that UMF annotations could use a different style in some way.

**Pull request merged**
