### PR TITLE
Mod: Add C9 tool change command to opensbp path post processor

### PR DESCRIPTION
**Pull request by ervanalb**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

This PR modifies the `opensbp` (shopbot) post-processor. It adds the `C9` tool change command when there is a tool change. The `C9` command seems to be necessary for ATC-enabled shopbots and even for some manual-tool-change shopbots, as the spindle will not start without it. See [this forum thread](http://www.talkshopbot.com/forum/archive/index.php/t-21055.html).

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7477">pipeline status</a> for feature branch [PR_7477](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7477). Pipeline [637051797](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/637051797) was triggered at [16f3619](https://github.com/FreeCAD/FreeCAD/pull/7477/commits/16f3619d1038bcd59d1213427c2e84f7c6b1c20b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@ervanalb please `git commit --amend` the title of this commit and change 'Mod:' to 'Fem:'  
TIA

**Comment by ervanalb** [comment]
I did not have any discussion with the devs about this. Maybe once I have something more substantial to contribute I will make a forum account and start a discussion, but it does not seem worth it to me for such a small change. For now, I will close this PR. Sorry to bother you!

**Comment by luzpaz** [comment]
@ervanalb all good. Thanks nonetheless.

**Pull request closed without merging**
