### PR TITLE
[Do not merge] Draft: Split Draft_Line and Draft_Wire into their own module DraftWire.py, instead of Draft.py

### PR DESCRIPTION
**Pull request by vocx-fc**
This pull request is not meant to be merged as it still contains errors.

Its intention is to show how the commands to create Draft Lines and Draft Wires could be moved to their own module, and to discuss problems. This is inspired by 5ee99ca4 which introduced DraftLayers outside of `Draft.py`, and a4e2df115 which also splits DraftEdit, and 16c26cb3b1 which sets the DraftEdit for the "future".

The changes introduced are summarized as follows
- New module `DraftWire.py` to hold the commands.
- Removed the `makeLine()` and `makeWire()` commands from `Draft.py`
- Removed the `_Wire` class and its respective `_ViewProviderWire` class from `Draft.py`. These two classes are also used by the Line object, as a Line is just a Wire.
- Inside `Draft.py` the new module `DraftWire` is imported, and the two functions `makeLine()` and `makeWire()` are made available, as they may be used by other functions, and they also should be available in the `Draft` namespace.
- The `_Wire` and `_ViewProviderWire` class are also imported in `Draft.py`, as these need to be present in the `Draft` namespace for compatibility with previous versions. Without these classes, it isn't possible to recreate the shapes when a file is re-opened.
- Removed the `Wire` and `Line` classes from `DraftTools.py`. These are the Gui Commands, meaning, the commands run when the buttons in the Draft toolbar are pressed.
- Removed the `FreeCADGui.addCommand("Draft_Line", Line())` and `FreeCADGui.addCommand("Draft_Wire", Wire())` from `DraftTools.py`, as these instructions are now added in the new module, `DraftWire.py`
- Updated the `CMakeLists.txt` file with the new module `DraftWire.py` so that when the build is made, the file is moved to the appropriate directory.
- In `Draft.py` auxiliary functions and classes need to be moved to before the `import DraftWire` instructions. Otherwise, they aren't found.

---
This fails the test
- `./bin/FreeCAD --run-test TestDraft`

```
======================================================================
ERROR: TestDraft (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: TestDraft
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/opt/freecad-build-vocx/Mod/Draft/TestDraft.py", line 26, in <module>
    import FreeCAD, os, unittest, FreeCADGui, Draft
  File "/opt/freecad-build-vocx/Mod/Draft/Draft.py", line 462, in <module>
    import DraftWire
  File "/opt/freecad-build-vocx/Mod/Draft/DraftWire.py", line 48, in <module>
    from DraftTools import getPoint
  File "/opt/freecad-build-vocx/Mod/Draft/DraftTools.py", line 562, in <module>
    from DraftWire import Line
ImportError: cannot import name 'Line'
```

This is possibly a circular dependency. `Draft` is imported, which imports the new `DraftWire` to define `Line` and `Wire`; this `DraftWire` needs some utilities from `Draft` itself like `typecheck()`, `getParam()`, `dimSymbol()`, etc. Moreover, `DraftWire` also needs some utilities from `DraftTools`, like the `Creator` class, as well as a few auxiliary tools `getPoint()` and `getSupport()`; but `DraftTools` also imports `DraftWire` because it needs to import `Line`, as it is used by other tools, like `BSpline`.

I don't know what the proper solution is but maybe a new module should be created like `DraftAuxTools.py` that includes all small utilities, but doesn't actually define a working tool like Line, Circle, Ellipse, etc. In similar fashion, another module `DraftBaseTools.py` would define the auxiliary classes, like `_DraftObject`, `_ViewProviderDraft`, `Creator`, `DraftTool`, etc., that actual tools require.

I believe this is done in the Arch Workbench, as `ArchComponent.py`, `ArchCommands.py`, etc., define auxiliary tools that the other objects need.

### CODE REVIEW

**Comment by vocx-fc** [comment]
Since this pull request was opened a lot of work has happened. We have managed to split all the graphical commands and the task panels, and we are looking to split the object classes and view providers of all "scripted objects" in the workbench.

We didn't do it as I originally described above, with one file per object. Instead we went deeper, and decomposed each object into five essential pieces:
* object
* view provider
* make function
* Gui command
* task panel

They each have a directory, so the code is more organized, and future programmers can look at the particular piece of the code that they are interested in. Not only that, but we also added more directories to organize the code that is more general, such as utilities, and unit tests. The basic description is in the thread, [[Discussion] Splitting Draft tools into their own modules](https://forum.freecadweb.org/viewtopic.php?f=23&t=38593&start=40#p368890).

These are relevant pull requests:
* #2668, #2727, #3005, new and improved unit tests
* #2823, base of all Gui Commands
* #2824, #2825, #2988, new Polar and Circular array graphical tools; and new Orthogonal array
* #2829, new utility module
* #2830, new GUI utility module
* #2831, new module for `ToDo` class
* #2832, #3002, #3003, new modules and functions to perform translation and print messages
* #2844, update `CMakeLists.txt`
* #2970, #2971, clean up the initialization in `InitGui.py`
* #2972, grouping of the array tools
* #2976, #3017, `README.md` file to explain the new structure
* #3004, function to create `Arc` object by entering 3 points
* #3012, #3254, #3302, module and script to produce a sample file, and sample file with preview
* #3051, #3058, #3060, #3070, #3170, new icons
* #3082, various fixes in style in many modules
* #3086, Pivy install for Python 2 to run unit tests
* #3091, #3092, #3093, #3094, #3261, re-organization of snaps, trackers, and select plane code
* #3095, #3096, move task panel code for `ShapeString` and `Scale` tools
* #3097, move `Draft Edit` code
* #3106, run unit tests without graphical interface and with graphical interface
* #3156, improvements in make functions
* #3157, improvements in `Working Plane` and `Working Plane Proxy` tools
* #3158, improvements in task panels and `.ui` files
* #3182, move various Gui Commands outside `DraftTools.py`
* #3191, coding conventions for Draft and Arch, essentially PEP8
* #3291, move base classes `DraftTool`, `Creator`, `Modifier` outside `DraftTools.py`
* #3299, move `Creator` tools outside `DraftTools.py`
* #3308, move `Modifier` tools outside `DraftTools.py`
* #3344, make the Gui Commands compatible with Python 2 still

Further work, moving the object code, view providers, and make functions is being carried by carlopav, in various pull requests.
* #3367, #3388

**Comment by yorikvanhavre** [comment]
I think this one can be closed, right?

**Comment by vocx-fc** [comment]
Yes, I guess so. Although I use this pull request to collect the links to other pull requests that are on the same topic of reorganization.

**Comment by yorikvanhavre** [comment]
Closing this as obsolete.

**Pull request closed without merging**
