### PR TITLE
Stylesheet fixes part IV - A new hope (to be done for 1.0)

### PR DESCRIPTION
**Pull request by MisterMakerNL**
Some small fixes.

### CODE REVIEW

**Comment by MisterMakerNL** [comment]
Change default colors from:
image
to
image

**Comment by MisterMakerNL** [comment]
I have added a fix for https://github.com/FreeCAD/FreeCAD/issues/15040 from @Syres916 
Selection border is now blue:
352653478-3549d983-bab8-4728-8f28-5e55867ad4cf

**Comment by MisterMakerNL** [comment]
User colors are now set by applying the theme and are blue and purple and orange, although orange isn't used atm.
afbeelding

**Comment by Syres916** [comment]
In order that we don't get another out-of-sync situation with default colors and themes, I believe the following should be changed to suit:

https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/PreferencePages/DlgSettingsViewColor.ui#L345-L347
https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/PreferencePages/DlgSettingsViewColor.ui#L378-L380
https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/TreeParams.cpp#L120-L123

**Comment by MisterMakerNL** [comment]
> In order that we don't get another out-of-sync situation with default colors and themes, I believe the following should be changed to suit:
> 
> https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/PreferencePages/DlgSettingsViewColor.ui#L345-L347 https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/PreferencePages/DlgSettingsViewColor.ui#L378-L380 https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/TreeParams.cpp#L120-L123

ugh that gonna take some time.

**Comment by chennes** [comment]
Re-running CI on the Mac to see if that was a false failure.

**Comment by FEA-eng** [comment]
> Re-running CI on the Mac to see if that was a false failure.

Tests passed, can you merge?

**Comment by Syres916** [comment]
> Tests passed, can you merge?

A little disappointed that my constructive feedback appears to be ignored, how long can it take to update two files with a maximum of 6 lines. If they don't get updated all that's going to happen is an issue will get raised by a user questioning why their default colours don't match what's in the documentation/other users' feedback. We've had the exact same thing happen with UI Preferences and Sketcher CreateLineColor within the last week.

**Comment by maxwxyz** [comment]
@Syres916 I can make a separate PR for that

**Comment by MisterMakerNL** [comment]
@Syres916 I didn't had time for it today, and also converting everything between rgb and decimal and hex is a pain in the ass.

**Comment by MisterMakerNL** [comment]
I am having a go at it rtn

**Comment by MisterMakerNL** [comment]
Ok, that was a lot less work than I though, hope I have not switched them around :)

**Comment by Syres916** [comment]
@MisterMakerNL thank you

**Pull request merged**
