### PR TITLE
Step parameter / Single Shape placement bug correction

### PR DESCRIPTION
**Pull request by vejmarie**
This PR fixes issues reported into
https://forum.freecadweb.org/viewtopic.php?f=10&t=23400 
Aka: Single Shape Placement / Color issues

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by vejmarie** [comment]
Argh it kept my previous branch commit. Just need

Export single STEP object with absolute coordinate instead of (0,0,0)… … |   |   | 4c22798
-- | -- | -- | --
  |   | Fix Step hierarchical color export of single shape |   |   | 23ca4d2
  |   | Some code cleanup and additionnal comment to better understand the hi… … |   |   | ea4f183
  |   | Merge remote-tracking branch 'origin/master' into step_parameter |   |   | 8d9a311

To be merged !

**Comment by yorikvanhavre** [comment]
I merged only 4c22798, is that correct?

**Comment by vejmarie** [comment]
nop you need 

4c22798, 23ca4d2, ea4f183

And that shall be ok
,

**Comment by yorikvanhavre** [comment]
Closing cf talk with @vejmarie on irc

**Pull request closed without merging**
