### PR TITLE
Spreadsheet: fix possible crash in SheetModel::setData

### PR DESCRIPTION
**Pull request by wwmayer**
See https://forum.freecadweb.org/viewtopic.php?f=8&t=68529

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6881">pipeline status</a> for feature branch [PR_6881](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6881). Pipeline [538676761](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/538676761) was triggered at [3841820](https://github.com/FreeCAD/FreeCAD/pull/6881/commits/38418203156c9940fc97445b7c1886dfbd00fc85). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
CCing @chennes for info

If possible this should go in the next days.

**Comment by chennes** [comment]
I can't answer @wwmayer's question about whether this solution (using `setData`) is better than using a `singleShot`. I also can't reproduce the reported bug. So I have no objection to this code as written, and if Werner says it fixes the weird threading issue I think we should merge as is, rather than waiting to see if someone at Qt can answer about whether this is the best way.

**Comment by donovaly** [comment]
I fully trust Werner, I mentioned you to keep you informed.

**Comment by wwmayer** [comment]
In the meantime I have tested the QtCrash example on Windows with Qt 5.15.2 under MSYS2 and there I get the crash after a while, too. After applying the suggested solution I couldn't get it to crash any more.

**Comment by donovaly** [comment]
> After applying the suggested solution I couldn't get it to crash any more.

Great. Then this PR can be merged.

**Comment by donovaly** [comment]
> Then this PR can be merged.

Doing so now since it is for 0.20 and I would like to release another test build.

**Pull request merged**
