### PR TITLE
[Mesh] Avoid false negatives during self-intersection checks

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Fixes issue #4732.

Within the code, a different algorithm is used for intersection checks when
faces are found to be coplanar. That algorithm does not return the "intersection
line", which is used to remove false-positives. This however results in
false-negatives.

---

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum. Small fix, but see https://forum.freecadweb.org/viewtopic.php?f=8&t=61757&p=528994#p528994.
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
Possibly not complete since performing the check sometimes makes the mesh disappear temporarily until "repaired". Please test with the STL file provided in forum.

**Comment by chennes** [comment]
I can confirm that this compiles and runs, and both fixes the self-intersection problem, and introduces the "hidden mesh" problem.

**Comment by yorikvanhavre** [comment]
Okay, since the 'bug' is intermittent and not critical I think we can already merge this...

**Comment by AjinkyaDahale** [comment]
Marking as ready for review since @yorikvanhavre mentioned mentioned this somewhere (though I don't recall where)

**Comment by yorikvanhavre** [comment]
Okay let's merge then. The hidden mesh bug doesn't seem critcal. (Indeed I have a déja-vu impression of having written that already somewhere, but can't find where :laughing: )

**Comment by luzpaz** [comment]
Please add to the [0.20 Release Page](https://wiki.freecadweb.org/Release_notes_0.20)

**Comment by AjinkyaDahale** [comment]
> Okay let's merge then. The hidden mesh bug doesn't seem critcal. (Indeed I have a déja-vu impression of having written that already somewhere, but can't find where laughing )

@yorikvanhavre: confirmed that I have an email where this was a reply. I guess you deleted the comment sometime.

**Comment by AjinkyaDahale** [comment]
> Please add to the [0.20 Release Page](https://wiki.freecadweb.org/Release_notes_0.20)

Added to thread because I don't have edit access.

**Comment by AjinkyaDahale** [comment]
Guess I did have that edit access after all. Made the changes.

**Pull request merged**
