### PR TITLE
FEM: Fluid material properties fix

### LINKED ISSUE #12934: FEM: Some input fields in FEM MaterialFluid and FEM MaterialSolid are getting reset automatically
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the current weekly builds, some input fields of [FEM MaterialFluid](https://wiki.freecad.org/FEM_MaterialFluid) and [FEM MaterialSolid](https://wiki.freecad.org/FEM_MaterialSolid) (available after checking the "use this task panel" box) are not working properly - they are getting reset when the default value is changed. The following input fields are affected:
- FEM MaterialFluid: Kinematic viscosity (this one is the worst because it's reset to 0, preventing fluid analyses from running), Specific Heat
- FEM MaterialSolid: Specific Heat (but it seems to be inconsistent - it doesn't always happen)

@davesrocketshop 

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
fully fixes #12934

This fix consists of 3 parts:
- check of empty string fix from @benj5378 (#16270)
- higher maximum values - they were way too low which was a nasty bug/oversight: https://github.com/FreeCAD/FreeCAD/pull/16270#issuecomment-2329560196
- correct writing of viscosity to CalculiX input files (it was broken and did not use kinematic viscosity)

@marioalexis84 FYI

### CODE REVIEW

**Comment by benj5378** [comment]
I just removed the empty object because I don't think it can be empty, however idk. In case it can be empty, we can't use `if value:` because it also returns on other then empty object, like if `value == 0`

**Comment by FEA-eng** [comment]
@benj5378 In my tests, it didn’t seem to work correctly without your fix so I included it here. Altogether it finally works as expected.

But let’s also ping @davesrocketshop just in case.

**Comment by davesrocketshop** [comment]
Looks good to me

**Comment by FEA-eng** [comment]
@chennes Can you merge this? It fixes a nasty FEM bug. I also submitted a separate PR for the 1.0 release branch.

**Pull request merged**
