### PR TITLE
[Mesh] remove Python.h from headers

### PR DESCRIPTION
**Pull request by donovaly**
seems not to be necessary anymore

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6621">pipeline status</a> for feature branch [PR_6621](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6621). Pipeline [496591864](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/496591864) was triggered at [3ecb397](https://github.com/FreeCAD/FreeCAD/pull/6621/commits/3ecb397cbd24b5f49c5bed867c65a6649e850203). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Have you tried it with VS and activated PCH?

**Comment by donovaly** [comment]
> Have you tried it with VS and activated PCH?

Yes. master works with PCH and I rebased this PR onto master and tested that it works with PCH too.

**Comment by donovaly** [comment]
The CI succeeded, I compiled with and without PCH and similar commits today worked. Therefore merging this one.

**Pull request merged**
