### PR TITLE
Fem: Set startupinfo for gmsh subprocess - fixes #17298

### LINKED ISSUE #17298: [Regression] FEM: pops up gmsh.exe window
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

* create a meh in FEM using GMSH
result: a big black window for the gmsh.exe process pops up

This is a regression to FC 0.21for which I once fixed this. The windows just has to be hidden/make invisible.

@marioalexis84 maybe you have a quick fix, otherwise I can have a look this week

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38937 (Git)
Build type: Release
Branch: releases/FreeCAD-1-0
Hash: 64d8ab5e55e14c3818aa417b7e2cd7b3ef30793e
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.0, OCC 7.8.0
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/windowsvista
Installed mods: 
  * A2plus 0.4.61
  * Assembly4 0.50.4
  * CfdOF 1.24.8
  * Curves 0.6.14
  * fasteners 0.4.70
  * FEMbyGEN 1.2.0
  * Manipulator 1.5.0
  * Plot 2022.4.17
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marioalexis84**
Fixes #17298

@donovaly could you confirm?

### CODE REVIEW

**Comment by donovaly** [comment]
Many thanks! I can confirm it fixes the bug when executing GMSH withing the mesh dialog.

For the remaining issue, see my comment in https://github.com/FreeCAD/FreeCAD/issues/17298

**Review by donovaly — APPROVED** [review]
Many thanks! I can confirm it fixes the bug when executing GMSH withing the mesh dialog.

For the remaining issue, see my comment in https://github.com/FreeCAD/FreeCAD/issues/17298

**Comment by marioalexis84** [comment]
> For the remaining issue, see my comment in https://github.com/FreeCAD/FreeCAD/issues/17298

It should be fixed now.

**Comment by FEA-eng** [comment]
@chennes CI passed, can you merge it?

**Comment by chennes** [comment]
Backported to 1.0

**Pull request merged**
