### PR TITLE
Enhance readability of 'formula' for comboview property value

### PR DESCRIPTION
**Pull request by Axeia**
Enhances the readability of a formula value in the ComboView by using a color appropriate to the theme overwriting the default dark blue that contrasts poorly on themes with a dark background. The ProDark.qss file does this already, this merely makes a similar change to the other 'Darker' themes.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7542">pipeline status</a> for feature branch [PR_7542](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7542). Pipeline [656322568](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656322568) was triggered at [2f7d1b8](https://github.com/FreeCAD/FreeCAD/pull/7542/commits/2f7d1b868623f1e96e84e09de6c3ee64ff881c69). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7542">pipeline status</a> for feature branch [PR_7542](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7542). Pipeline [656339967](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656339967) was triggered at [c39e8bc](https://github.com/FreeCAD/FreeCAD/pull/7542/commits/c39e8bc7c550234d8c286ae18fe914e4b95d0c32). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7542">pipeline status</a> for feature branch [PR_7542](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7542). Pipeline [657433849](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/657433849) was triggered at [18166c1](https://github.com/FreeCAD/FreeCAD/pull/7542/commits/18166c137adde18eae8fcadfd7bcd27f8f6a81d4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
any particular reason why this was closed?

**Pull request closed without merging**
