### PR TITLE
[TD]Section scale and preference drop downs

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements fixes for 2 issues:
Section scale not equal to base view scale reported here: https://forum.freecad.org/viewtopic.php?t=82762, and
#11634 preference drop downs for line styles

### CODE REVIEW

**Comment by maxwxyz** [comment]
@WandererFan in the current weekly builds the dropdown for the line styles / standards is missing (the entire line section in the preferences). Is this intentional?

**Comment by WandererFan** [comment]
The fields are there, but empty or the fields aren't there at all?  Either way, this is news to me.   The two versions I have here on my travel laptop both have the fields and they are filled with data.

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35735 +1 (Git)
Build type: debug
Branch: fixExtensionCosmetics
Hash: f32a118b28dc9299bd9869771354dc885f668c0b
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk , OCC 7.7.1
Locale: English/Canada (en_CA)
Installed mods: 
  * dodo 1.0.0
  * BOLTSFC 2022.11.5
  * sheetmetal 0.2.63
  * ExplodedAssembly
  * fasteners 0.4.56
  * FreeCAD_Electric
  * freecad.gears 1.0.0
  * Curves 0.6.14
  * Assembly4 0.50.2
  * A2plus 0.4.60n
```

```
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35735 (Git) AppImage
Build type: Release
Branch: main
Hash: c12a5c2a163c1a277cf273106899209792be152d
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * dodo 1.0.0
  * BOLTSFC 2022.11.5
  * sheetmetal 0.2.63
  * ExplodedAssembly
  * fasteners 0.4.56
  * FreeCAD_Electric
  * freecad.gears 1.0.0
  * Curves 0.6.14
  * Assembly4 0.50.2
  * A2plus 0.4.60n
```

**Comment by maxwxyz** [comment]
@WandererFan the fields are missing. In which sections were those fields?
Here are my TD settings (I've noticed they all have the same size as the first one of the group, all display the scrollbar but no content @kadet1090):
image
image
image
image
image
image

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35449 (Git)
Build type: Release
Branch: main
Hash: f3fa2ba9c9b1999e5c32d3ae544481b6e17553bb
Python 3.11.7, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.1
  * CurvedShapes 1.0.5
  * Curves 0.6.22
  * Defeaturing 1.2.2
  * fasteners 0.5.0
  * FEMbyGEN 2.1.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.0
  * woodworking 0.21.2.33771
```

**Comment by kadet1090** [comment]
This is very strange issue. The "Annotation" page does not have this issue but I don't know why it has different behavior. Some pages want to grow to the biggest one, but I'm not able to find any similarities between them.

**Comment by WandererFan** [comment]
The empty fields in the General tab are fine.  That just means you haven't set a non-default preference for those items.

**Comment by maxwxyz** [comment]
@WandererFan sure, but I am missing the whole annotation page / tab in the left sidebar.

**Comment by WandererFan** [comment]
The most recent appimage I can find (OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit Version: 0.22.0dev.35858 (Git) AppImage Build type: Release) 
shows the Annotation tab correctly, both with my regular user.cfg and an empty user.cfg.

AnnoTab_v022AppImage_emptyConfig

**Comment by WandererFan** [comment]
This is a bit of a wild guess, but are you using the "overlay" thing (sorry don't use it and don't know the official terminology)?  That seems to mess up otherwise well behaved panels.

**Comment by WandererFan** [comment]
My next wild guess is that this is a Windows-only problem.  

Is there another Windows user watching this thread that can say yea or nay?

**Comment by maxwxyz** [comment]
Yes I'm using the overlay thing :) Just tried it with the current weekly but the Annotation tab is still missing. I've tried to disable the overlays and also reset the preferences but this page is still missing

**Comment by maxwxyz** [comment]
On the same machine I've also FC 0.21.2 installed. Could this be interfering because there, different line styles were used in the preferences? When I open 0.21.2 the Annotation tab is there but not in the 0.22:
image

**Comment by WandererFan** [comment]
I don't think so.  If the annotation panel was showing with everything empty then it might be a preference conflict.  Given that the panel doesn't even show up for you, I'm inclined to look elsewhere.  

I'm not even sure how to stop the Annotation tab from being created, other than commenting out the code in AppTechDrawGui.cpp that creates it.

My next step is to dig into Gui::PrefPageProducer, but given that I can't duplicate it here that's going to be mostly guesswork.

**Comment by maxwxyz** [comment]
@WandererFan steps how I can reproduce it reliably:

1. fresh install / delete configs --> everything is working, default line style is ASME...
2. apply OpenDark Theme @obelisk79 
3. Then the default line style field is empty
4. Reopening preferences and the annotation tab is gone and TD is broken

when the theme is applied, the output is:
grafik

**Comment by obelisk79** [comment]
The config settings set by OpenDark can be viewed here: https://github.com/obelisk79/OpenDark/blob/main/OpenDark/OpenDark.cfg

I do not have that parameter set

**Pull request merged**
