### PR TITLE
[Postponed]Use C++11 std::regex instead of boost::regex

### PR DESCRIPTION
**Pull request by plaes**
Since we require C++11 since 0.17 version, use std::regex instead of boost::regex and do some related cleanups.

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`

### CODE REVIEW

**Comment by plaes** [comment]
Hmm, these are weird errors. Windows fails are somewhat expected because I couldn't test it locally, but seeing also all Linux builds fail with cmake error is something I did not really expect...
And what puzzles me the most is that only clang/Xcode succeeds.

Do you want me to split it up into following pieces:
1. Unneeded boost_include cleanups
2. Separate module-based cleanups
3. Final configuration cleanup

**Comment by plaes** [comment]
OK, Windows errors are because I have the `<regex>` header inside these blocks:
```
#ifndef _PreComp_
...
#endif
```

Unfortunately I do not really understand the way that `precompiled.h` headers are utilized in this project and how should I use them. :(

**Comment by plaes** [comment]
@wwmayer Apparently the application crashes are due to this: https://github.com/travis-ci/travis-ci/issues/6300

So I build with proper c++11 compatible compiler, but runtime does not support it.

**Comment by wwmayer** [comment]
OK, then I think this PR should be postponed as Ubuntu Trusty is still supported until mid of 2019 and IMO we shouldn't make it stop working on this platform for cosmetic reasons only.

But also the Windows build doesn't work. Somehow there is an overloaded version of std::isspace that requires two arguments now.

**Comment by hyarion** [comment]
> OK, then I think this PR should be postponed as Ubuntu Trusty is still supported until mid of 2019 and IMO we shouldn't make it stop working on this platform for cosmetic reasons only.

Ubuntu Trusty's standard support was ended in April 2019 but it has not yet reached end of life as that is planned for April 2022. Should this PR be postponed until EoL or can we continue with this now since standard support has ended?

**Comment by wwmayer** [comment]
Considering the date when standard support ends (i.e April 2019) is fine. However, this PR should be at least postponed until v0.19 has been released (I guess in March).

Since Xenial support ends in April Bionic as minimum version can be required.

**Comment by hyarion** [comment]
> Since Xenial support ends in April Bionic as minimum version can be required.

0.20 developement has started now and minimum ubuntu version is now 18.04 LTS which has gcc 7.4.
@plaes are you interested in continuing on the quest to getting it merged?

**Comment by plaes** [comment]
> > Since Xenial support ends in April Bionic as minimum version can be required.
> 
> 0.20 developement has started now and minimum ubuntu version is now 18.04 LTS which has gcc 7.4.
> @plaes are you interested in continuing on the quest to getting it merged?

I probably won't have time for a while..

**Comment by hyarion** [comment]
> > @plaes are you interested in continuing on the quest to getting it merged?
> 
> I probably won't have time for a while..

No worries, we can take it from here :)

**Comment by wwmayer** [comment]
> I've skimmed through the code and noticed that we use regex quite a lot when parsing some file types (for example src/Mod/Mesh/App/Core/MeshIO.cpp, src/Mod/Points/App/PointsAlgos.cpp)

If I got the slides right then it the worst case std::regex can be up to 60x slower than boost::regex. At least for reading mesh files or point clouds this is absolutely not acceptable.

**Comment by hyarion** [comment]
@wwmayer check, I'll test that and get back with the result

**Comment by wwmayer** [comment]
I have tested it with an 80 MB big OBJ file.
With boost::regex it takes 12 sec to load and with std::regex it takes 60 sec. So, it's not as bad as on the above benchmark test but 5x slower is still not acceptable.

**Comment by hyarion** [comment]
@wwmayer: I agree, that’s way too slow.

It was a nice idea though and I appreciate the effort of trying to remove a dependency, but I think we should end it here and close this PR 🚫

We can always revisit this later if they manage to fix the speed of std::regex.

**Comment by luzpaz** [comment]
> We can always revisit this later if they manage to fix the speed of std::regex.

Is there an upstream ticket we could track to stay abreast of this?

**Comment by wwmayer** [comment]
The test above was done with a clang build under Ubuntu. On Windows with VS 2019 I have tested a 436 MB big OBJ file that takes 33 sec with boost::regex and 10 min 40 sec with std::regex. So, there it's slower by a factor of almost 20.

**Comment by wwmayer** [comment]
> Is there an upstream ticket we could track to stay abreast of this?

There is not the one "upstream" here because it's up to each compiler constructor to make std::regex much faster. Until this is not done for all compilers (gcc, clang, msvc) it makes no sense to switch to std::regex.

**Comment by wwmayer** [comment]
So, closing this PR as at the moment it causes a serious performance regression.

**Comment by luzpaz** [comment]
How do we make a note-to-self to explore this again?

**Comment by hyarion** [comment]
@luzpaz We will be reminded every time we look at the list of dependencies and it's not like we need to switch from boost so I think we can just leave it.

**Comment by xtemp09** [comment]
Gentlemen, I wrote a simple program importing ASCII STL file, completely mimicking this code. I used `std::regex`, `boost::regex` and `QRegularExpression`. I took `std::regex` code from this PR, `boost::regex`  from the FreeCAD code, the code utilizing `QRegularExpression` I wrote myself. Time elapsed:

|  | Small model | Large model |
| --- | --- | --- |
|std::regex |95 ms| 26 723 ms|
|boost::regex |87 ms| 24 368 ms|
| QRegularExpression |87 ms| 25 348 ms|

I used gcc 11.2 together with Qt 6.3 on Windows 10. The speed comparison shows that the difference between them is negligible.

I think it's time to reconsider this topic. Why does import depend on regex at all? If you look [here](https://github.com/sokunmin/stl-gcode-viewer/blob/master/model.cpp), [here](https://github.com/wangxinkuan/qt-stl/blob/master/model.cpp) and [here](https://github.com/vladkrylov/STLViewer/blob/master/STLParser.cpp), none of the developers use regex to import file. They use `QFile`, `QStringList`, `QString`, `QVector3D`, `QTextStream` etc. The usage of regular expressions is quite burdensome.

My proposition is to rewrite the import code using `QFile`, `QStringView`, `QTextStream` and `QByteArray`. It's a Qt application anyway.

**Comment by chennes** [comment]
Thanks for running those tests, it's good to see that gcc has improved their regex library. Can you also test clang and msvc?

Regarding the import code: is there an advantage to using Qt? My general impulse is to use C++ standard library stuff whenever possible.

**Comment by xtemp09** [comment]
I can recheck it on openSUSE 15.4; my clang and MSVC toolchains (MSVS 2019) on Windows are rather old.

The main advantage of Qt is portability. You may heard problems concerning `std::filesystems` and, of course, `std::regex` on different platforms that are absent in Qt. In case of import/export there will be some gain in speed or none at all.

Some programs can be written utilizing C(++)/Qt interchangeably. However, usage of regular expression in some parts of FreeCAD is extensive, like in src/Mod/Mesh/App/Core/MeshIO.cpp

In my point of view, it is better to write `stream >> fX >> fY >> fZ` instead of 30 lines of code utilizing regex. Some parts of MeshIO.cpp use C++ streams, some parts use regexps. I'll compare import of ACSII STL using regex and C++ streams, though, beforehand I think the latter is faster.

**Comment by chennes** [comment]
If the resulting code is simpler, and you are willing to put the time in, a short PR demonstrating your idea in one place would be a good start. That way you don't invest too much time in case someone has a good reason why we shouldn't take that route.

**Comment by xtemp09** [comment]
I wrote an ASCII STL (c++) parser using `std::stringstream` and `std::stof` instead of regexp and `(float)std::atof`, compiled with gcc 11.2, static Qt 6.3 on Windows 10.  The comparison:

| | Small model | Large model |
|---|---|---|
| std::regex                 | 95 ms | 26 619 ms |
| boost::regex             | 90 ms | 25 316 ms |
| QRegularExpression | 85 ms | 25 051 ms |
| c++                          | 58 ms | 17 022 ms |

It means removal of regexp increases speed. Blender [now uses the new importer](https://github.com/blender/blender/commit/7c511f1b47d857f37aa36ee6ed8107cb88eb5c39), perhaps, it will give much better results in comparison to mine.

**Pull request closed without merging**
