### PR TITLE
[Part] FaceColors cleanup

### PR DESCRIPTION
**Pull request by donovaly**
- indicate if one is in the Box Selection mode
- get rid on dialog if one really wants to cancel (no other Task dialog does this and it is annoying)
- fix clumsy dialog layout:

current layout:
FreeCAD_b8BCWIcPGR

new layout:
FreeCAD_IEu7kbu7rt

### CODE REVIEW

**Comment by wwmayer** [comment]
https://tracker.freecadweb.org/view.php?id=801

**Comment by wwmayer** [comment]
> indicate if one is in the Box Selection mode

This causes incorrect behaviour. When I press the button twice the button is not toggled any more but the dialog is still in box selection mode

> fix clumsy dialog layout:

The label above the color button is used to show the ids of selected faces. Limiting its width to a few pixels makes it pretty useless as it cannot show the ids of more than four faces

**Comment by donovaly** [comment]
> But in no other dialog you may have changed many things and then lose your work by an accidental click on Cancel or pressing ESC. What can be done is to remove the security check if nothing has actually changed.

We consistently don't have safe guards for a cancel button. This dialog is in my opinion not very special. Take for example the fillet and chamfer dialog. In my documents I often have more than a dozen edges to be filleted. Pressing Cancel is a purpose decision and since this button is not in the inner dialog area, it is not pressed unwantedly.
So for being consistent I don't see why this dialog should get an exception.

> The label above the color button is used to show the ids of selected faces. Limiting its width to a few pixels makes it pretty useless as it cannot show the ids of more than four faces

I don't understand. I did not limit its width. I shows the selected items in the width as before:
FreeCAD_s0AbUpgrA2

> When I press the button twice the button is not toggled any more but the dialog is still in box selection mode

Thanks, I will have a look.

**Comment by donovaly** [comment]
> > When I press the button twice the button is not toggled any more but the dialog is still in box selection mode
> 
> Thanks, I will have a look.

This is now fixed.

**Comment by wwmayer** [comment]
> This is now fixed.

A better way is to replace on_boxSelection_clicked() with on_boxSelection_toggled(bool checked) because the "checked" parameter tells you if the button is checked or not. This way the implementation can be simplified.

**Comment by donovaly** [comment]
>  If you don't want the color button to fully expand then put spacer inside the group box right to the color button.

Indeed. Fixed now:

> Edit: I just realized with the designer that no top-level layout is set.

But there is one: `<layout class="QVBoxLayout" name="verticalLayout">`
Qt's Designer warns you if there is no top level layout.

> A better way is to replace on_boxSelection_clicked() with on_boxSelection_toggled(bool checked) 

Done.

**Comment by wwmayer** [comment]
> But there is one: <layout class="QVBoxLayout" name="verticalLayout">

Sorry, then I have missed that. Usually I expect a grid layout and in the designer you can see if the button is active it's not set. But I haven't checked the vertical/horizontal layout.

> Qt's Designer warns you if there is no top level layout.

I cannot remember to have ever seen such a warning.

**Comment by donovaly** [comment]
> I cannot remember to have ever seen such a warning.

Here it is:
designer_aNEum2sVR0

**Comment by wwmayer** [comment]
> Here it is:

Then it must be a feature of newer Qt versions. With 5.9 I don't get it.

f2770a4169 be careful when sorting headers alphabetically. After the block of 3rd party headers the very first header should be the one that contains the class declaration of the source file, i.e. in this case TaskFaceColors.h should included before SoBrepFaceSet.h. Violating this rule is considered bad practice.

In C++ it's considered good practice that a header file is self-contained, i.e. it includes all necessary headers or uses forward declarations so that the source file that includes this header doesn't need to include other headers beforehand.
By changing this order the risk raises to hide the fact that a header is not self-contained.

In one of your other PRs you ran into exactly this problem. By changing the order of headers you got a build error because one of the header is not self-contained. You hided this fact by changing the order inside the source file. The right way would be to fix the header that is not self-contained.

**Comment by donovaly** [comment]
> Then it must be a feature of newer Qt versions. With 5.9 I don't get it.

I got this since I work with Qt 5. I use it with the default settings. I don't know how I could disable this.
Now I use apeltauer's LibPack and this comes with Qt 5.12

> [f2770a4](https://github.com/FreeCAD/FreeCAD/commit/f2770a416976faf9a6528b5d8ecbefcc096c725f) be careful when sorting headers alphabetically. After the block of 3rd party headers the very first header should be the one that contains the class declaration of the source file, i.e. in this case TaskFaceColors.h should included before SoBrepFaceSet.h. Violating this rule is considered bad practice.

Yes, I learned this this weekend with another commit. This was not yet clear to me -> my programming skills are still basic :-(
I am sorting because I have seen that sometimes the same header is included twice because one cannot see at the first glance what is already included. When I program the sorting helps me too.

Concerning the PR, what do I have to to get it merged besides to fix the include ordering?

**Comment by wwmayer** [comment]
Nothing, it's already merged.

**Pull request closed without merging**
