### PR TITLE
Remove unused 3rdparty library

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
The glext.h shouldn't be removed as it's not necessarily available on all platforms.

It's true that FreeCAD itself doesn't use the CxImage library but it's used by the ThumbnailProvider that you find in the Tools directory. This is a shell extension for Windows and its purpose is to extract the PNG file from a FCStd project and convert it into a Bitmap handle so that the Windows Explorer can show it as preview.

When removing (the statically linked) CxImage we need an adequate replacement for it. Qt is not an option because it's linked dynamically and thus takes longer to load, requires several Qt DLLs and it's not guaranteed that the thumbnail provider DLL finds the correct Qt version.

**Comment by wwmayer** [comment]
Must be checked if one of the suggestions can be used: https://stackoverflow.com/questions/4567875/how-would-i-load-a-png-image-using-win32-gdi-no-gdi-if-possible

The code here does the opposite: https://docs.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-converting-a-bmp-image-to-a-png-image-use

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6388">pipeline status</a> for feature branch [PR_6388](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6388). Pipeline [473508949](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/473508949) was triggered at [76e8f25](https://github.com/FreeCAD/FreeCAD/pull/6388/commits/76e8f257dd8228e1261556f5a0b3668b866b7cb3). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by AjinkyaDahale** [comment]
@mosfet80 please do not repeatedly merge the branch with `master`. It will eventually cause a mess when this needs to be merged into `master`. Additionally, unless there's a reason not to do so, please rebase your branch on to `master` instead.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6388">pipeline status</a> for feature branch [PR_6388](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6388). Pipeline [474146635](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/474146635) was triggered at [0099219](https://github.com/FreeCAD/FreeCAD/pull/6388/commits/0099219ea73bc2dec3740794151ded4c331fd3f5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Merged as a4628adb49e1b91

**Comment by luzpaz** [comment]
Nice! Thanks to everyone involved!

**Comment by luzpaz** [comment]
@wmayer JFYI, there are still artifacts of cximage in the FC source, see https://github.com/FreeCAD/FreeCAD/search?q=cximage&type=code is that intentional?

**Comment by wwmayer** [comment]
This is all old code and probably won't compile any more with any newer Windows SDK. IIRC it once was developed for Windows XP but the internal working of thumbnails providers has changed in newer Windows versions. In case it unexpectedly compiles and works with newer Windows versions it should be ported as well and otherwise it can be removed.

**Comment by luzpaz** [comment]
@WandererFan thank you for the explanation. Shall we open a ticket so that the Win based devs keep an eye on this to see if it should be ported or removed?

**Comment by wwmayer** [comment]
If I don't forget it I will have a look the next time I am on Windows.

**Pull request closed without merging**
