### PR TITLE
Remove qt4

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I personally would keep this for after 0.20...

**Comment by mosfet80** [comment]
https://wiki.freecadweb.org/Release_notes_0.20
Since this release FreeCAD can only be compiled using Qt 5 and Python 3.

**Comment by chennes** [comment]
I had been thinking we might leave the cMake flags alone in anticipation of adding support for Qt6.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6503">pipeline status</a> for feature branch [PR_6503](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6503). Pipeline [485159466](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/485159466) was triggered at [641a2c2](https://github.com/FreeCAD/FreeCAD/pull/6503/commits/641a2c237242d266fece942283a69ea8f36df6f5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
I think it is the right time to remove traces of Qt 4 since we are cleaning up the code anyway at the moment. @wwmayer , what is your opinion.

However, Qt4All.h cannot just be removed since it includes all Qt headers when using precompiled headers. So Qt4All stands for "Qt for all" ;-)

**Comment by wwmayer** [comment]
I would have cleaned it up, too. But...

> I had been thinking we might leave the cMake flags alone in anticipation of adding support for Qt6.

... that's a fairly good point because it will make it easier to handle Qt6 support with CMake. So, I recommend to only apply the changes on the source code -- and of course revert the changes that removes Qt4All.h.

Maybe to avoid confusion about this filename we could rename it to QtAll.h (or QtForAll.h).

**Comment by donovaly** [comment]
> Maybe to avoid confusion about this filename we could rename it to QtAll.h (or QtForAll.h).

Since we have "InventorAll.h", I think for consistency it should be "QtAll.h". Here is a PR that does this: https://github.com/FreeCAD/FreeCAD/pull/6524

**Comment by donovaly** [comment]
@mosfet80 , can you please rebase your PR and do this: https://github.com/FreeCAD/FreeCAD/pull/6503#issuecomment-1060394106 (the file renaming is already done)

**Comment by wwmayer** [comment]
Merged the relevant part.

**Pull request closed without merging**
