### PR TITLE
Gui: Add getObject<T>() helpers to various classes

### PR DESCRIPTION
**Pull request by kadet1090**
Obtaining specific kind of document object is very common task. This commit introduces handy helper which makes that a lot easier.

```diff
-        auto geometry = dynamic_cast<App::GeoFeature*>(getObject());
-        if (geometry) {
+        if (auto geometry = getObject<App::GeoFeature>()) {
```

First commit introduces the required methods, second commit replaces all trivial casts with uses of introduced methods. It can be regenerated if needed with simple regex based find and replace.

### CODE REVIEW

**Comment by maxwxyz** [comment]
@kadet1090 could you please resolve the conflicts? TIA

**Comment by kadet1090** [comment]
I'll once we agree that we want to merge that. There is no reason for me to resolve conflicts if this will wait in the queue for another month.

**Comment by maxwxyz** [comment]
Looked at this at the merge meeting but it still has conflicts. Could you please resolve them?

**Comment by kadet1090** [comment]
Will do on Sunday

**Comment by kadet1090** [comment]
There is a problem with linker on windows that I do not know how to solve as I don't have windows machine available. We could replace the `freecad_dynamic_cast` with normal one but I:m not sure if this is correct way

**Comment by chennes** [comment]
@kadet1090 is going to update to use a `dynamic_cast`

**Comment by kadet1090** [comment]
Done, @wwmayer if you could take a look if using `dynamic_cast` is fine here and if we even need our own dynamic cast today it would be nice

**Comment by wwmayer** [comment]
dynamic cast is fine (and even faster). 

> is fine here and if we even need our own dynamic cast 

I would still keep the `freecad_dynamic_cast`

I quickly looked through all touched files and the PR looks good to me.

**Comment by chennes** [comment]
@kadet1090 is going to rebase

**Comment by maxwxyz** [comment]
to be merged after CI is successful

**Comment by 3x380V** [comment]
@kadet1090, in case you are not aware [coccinelle](https://coccinelle.gitlabpages.inria.fr/website/), lets fix it now :) It might help with commits like those merged.

**Comment by kadet1090** [comment]
Thanks, I'll look into it!

**Pull request merged**
