### PR TITLE
TD: move all XML query handling to a single function

### PR DESCRIPTION
**Pull request by wwmayer**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
This PR refactors the code where classes of the QtXmlPatterns module are used. The pattern of using QXmlQuery is always the same so that the code could be simplified to have a single function and the special handling is done with lambda expressions.

In the final step only the function XMLQuery::processItems() must be ported.

This PR already allows it to fully compile the TechDraw module with Qt6 and functionality-wise the only limitation at the moment is that editable text markers of SVG files cannot be replaced.

@WandererFan can you have a look, please?

**Comment by WandererFan** [comment]
Works ok.  Thank you!

**Comment by chennes** [comment]
The merged PR has a failing test in the Addon Manager code on Ubuntu 22.04 -- I can think of no reason this would have affected that, so I will look at that AM test and see why it is overly fragile.

**Comment by wwmayer** [comment]
The CI tests of the PR have all passed and the error only occurred after merging it. And since after adding further PR no error is reported any more I guess there must be something that causes some random behaviour.

**Pull request merged**
