### PR TITLE
[TD] some Detail View fixes

### PR DESCRIPTION
**Pull request by donovaly**
see https://forum.freecadweb.org/viewtopic.php?f=35&t=45236&p=388925#p388925 for a description of the changes

### CODE REVIEW

**Comment by WandererFan** [comment]
I'm missing something in the EditingFinished vs ValueChanged part of this PR.  Both signals seem to behave the same - new values, whether typed or incremented by the arrows, are only applied on change of focus (tab to or click on different widget).  

Clicking the arrows does not update the graphics by itself.

**Comment by donovaly** [comment]
I just followed the Qt docs and here it works as it should:

P11vXEo4Oi

See also my latest post in the forum: https://forum.freecadweb.org/viewtopic.php?f=35&t=45236&p=389882#p389882

**Comment by donovaly** [comment]
The patch should now be ready to go in. I omitted the signal slot issue since this appeared to be a general FC issue: https://forum.freecadweb.org/viewtopic.php?f=10&t=47030

**Comment by WandererFan** [comment]
Uwe:  I can't merge this.  Github complains about conflicts.  Can you resolve them please?
Thanks,
wf

**Comment by donovaly** [comment]
I just tried it and git had no complaints. I remerged now. Can you please try again? If it fails again, I'll make a new PR.

**Comment by WandererFan** [comment]
merged.

**Pull request merged**
