### PR TITLE
Fix for null string and single blank string

### PR DESCRIPTION
**Pull request by KeithSloan**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Is there a reason to include the file OpenSCAD_rc.py? The file shouldn't be part of the repository but gets created at build time.

**Comment by KeithSloan** [comment]
Well the reason I included it was when I ran git status it told me it 
was an untracked file. So I naively assumed it should be added. Perhaps 
it should be added to .gitignore

**Comment by yorikvanhavre** [comment]
Can you remove it from your PR? You need to 'git rm' it, then add a new commit to your fix_text_null_string  branch.

**Comment by KeithSloan** [comment]
I seem to only have OpenSCAD_rc.py in master not in my branch what am I 
doing wrong?

**Comment by yorikvanhavre** [comment]
Using gitignore is not the right way to do it, if we merge your commit like this it will still contain the rc file. You still have that file committed in your branch.
Maybe easier to cancel this PR and start over? Sorry about that, but if we merge like this we'll need to add another commit afterwards to reverse the error.

**Comment by KeithSloan** [comment]
Hi Yorik

Okay try As requested new pull request for text command null string fix #717

I do hate git. If you wonder off the straight and narrow it raises its 
head to bite you

Keith

**Comment by yorikvanhavre** [comment]
Thanks Keith! I'll close this one and merge the other as soon as the CI tests finish.

**Comment by KeithSloan** [comment]
I am still confused so you need to double check the .gitignore does not 
have rc in latest pull request

**Comment by yorikvanhavre** [comment]
you could have any new file in your source tree (for example the backup files left by some text editors), it's up to you to know what you have changed or not when you are committing, and not just send any file found there.

the rc file shouldn't be there normally, it is there probably because you did an in-source build, which is really not recommended when you are going to push stuff with git, because it dirties your source tree. Better set a separate directory, which will be your build directory, and launch cmake from there. So all the files produced during the build go there instead of inside your source.

**Comment by KeithSloan** [comment]
On 28/04/17 19:16, Yorik van Havre wrote:
>
> you could have any new file in your source tree (for example the 
> backup files left by some text editors), it's up to you to know what 
> you have changed or not when you are committing, and not just send any 
> file found there.
>
Aware of that. but often forget to check
>
> the rc file shouldn't be there normally, it is there probably because 
> you did an in-source build, which is really not recommended when you 
> are going to push stuff with git, because it dirties your source tree. 
> Better set a separate directory, which will be your build directory, 
> and launch cmake from there. So all the files produced during the 
> build go there instead of inside your source.
>
No in source build just the following I think there was an initial clone 
a long time ago

#one off's
git remote add official https://github.com/FreeCAD/FreeCAD.git
git remote -v

git checkout master
# Get latest master from offical FreeCAD repository
git pull official master
# Update master on Keith Sloan version of FreeCAD
git push

git checkout <local_branch>
git rebase master <local_branch>
git push

**Pull request closed without merging**
