### PR TITLE
Sketcher: Join curves

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Rudimentary tool to join two b-splines into a single curve. Theoretically it is possible to join other curves as well after converting them to NURBS.

What is not complete:
* Thorough testing: I was trying to get this in time for the 0.20 feature freeze so this ended up being a last minute rush.
* ~No icons: I didn't design an icon for this tool. I made a temp with just a red "J" but I can't get it to appear on the toolbar. All that's visible is a placeholder.~ @bitacovir provided the icons and I figured out I was using the wrong name in command's pixmap field.

UI forum post: https://forum.freecadweb.org/viewtopic.php?f=34&t=66785

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
@PaddleStroke would you have some time to take a look at why the icon doesn't show?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [485159468](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/485159468) was triggered at [2f9e172](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/2f9e17224b587892fdc44e5adc72350295a8be61). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [485242808](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/485242808) was triggered at [8299463](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/829946315b93cdee4ac0bf423eb4615a571c6eef). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by AjinkyaDahale** [comment]
Force-pushed with icon from @bitacovir.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [485593443](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/485593443) was triggered at [c62a215](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/c62a2158cf1bb82eae91a1b863efaccc284b7e3a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [485782595](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/485782595) was triggered at [d03dc38](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/d03dc38c5f9421a490146be1d3f78f5042b20308). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [488726953](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/488726953) was triggered at [bee752b](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/bee752ba475ff6f53ff6fa17f9b34ccbc6955340). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [489543178](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/489543178) was triggered at [1a37a45](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/1a37a455d09cd426f74620cb81e2bd48770a621e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [490566561](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/490566561) was triggered at [3742791](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/374279199ff36f3b8f7c7fd91f2e0419a6750c47). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [490728513](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/490728513) was triggered at [51490c2](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/51490c2e4b3336a4ce44ed81e2de61636e6384a4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [491259467](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/491259467) was triggered at [58cc1bd](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/58cc1bd8231c716814fae018c70498f32a833185). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [492097101](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/492097101) was triggered at [7e96e0e](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/7e96e0e025f3450d773b3df7b0623ee420f5cf8e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [493289355](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/493289355) was triggered at [0fcf30c](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/0fcf30c9dda7b5177890ecc7202b065e0f5018b0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [495111150](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/495111150) was triggered at [5feac5f](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/5feac5fb0f6b3173efbd1f0928f65fa9a2ab524b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [496115011](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/496115011) was triggered at [c837c5c](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/c837c5cc4906cd771bd815b79dae3bc752022017). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [496447117](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/496447117) was triggered at [f6a7f82](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/f6a7f82763f3821ecd3c8d70f34f45cf7c470072). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [498856685](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/498856685) was triggered at [d49508e](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/d49508e2a898cd40dcc2633d72b70588c8d15096). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Heads up: If anyone on **Linux** wants to easily test this PR it's possible to do through the [freecad-ppd](https://snapcraft.io/freecad-ppd) snap package.

#### Installation
If you already have the 'edge' version installed all you need to do is:  
`snap refresh freecad-ppd --channel edge/sketcher-6507-join-curves`
  
If you **don't** have 'edge' installed: 
`snap install freecad-ppd --channel edge/sketcher-6507-join-curves`

Note: to return back to using the normal 'edge': `snap refresh freecad-ppd --channel edge`

Special thanks goes out to @ppd for setting up the Snap package to test individual PRs like this.

**Comment by AjinkyaDahale** [comment]
> Heads up: If anyone on **Linux** wants to easily test this PR it's possible to do through the [freecad-ppd](https://snapcraft.io/freecad-ppd) snap package.

Does this also work outside the Ubuntu derivatives?

**Comment by adrianinsaval** [comment]
it should work in anything that has snapd, they're supposed to be distro agnostic

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [552530667](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/552530667) was triggered at [3d6ee26](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/3d6ee2670b1b458b17b7e81c261dba85b89d37da). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [553015584](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/553015584) was triggered at [b5d36b3](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/b5d36b365cefec2efcab5223751dee57da4536b8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [553417863](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/553417863) was triggered at [3dafb95](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/3dafb955a9e7a856834a0364e9d4d185ac635a3b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [578984804](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/578984804) was triggered at [498e491](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/498e491adec76dd590fa147a9b1e7d6aeaeb157a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [650029791](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/650029791) was triggered at [03fe66e](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/03fe66ed043c46fbe68aacd2404bc5420e63e42c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [653235899](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/653235899) was triggered at [7578220](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/757822088b4a912e6c4f200e30ce1ba00d452581). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [669090180](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/669090180) was triggered at [a072a57](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/a072a57d6cba71caf1bcc02ebf4df3ff4c6106e0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507">pipeline status</a> for feature branch [PR_6507](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6507). Pipeline [691949389](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/691949389) was triggered at [126e497](https://github.com/FreeCAD/FreeCAD/pull/6507/commits/126e4978e09c9add36a0b59c2b9a58f52c807a45). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by abdullahtahiriyo** [comment]
@AjinkyaDahale 

I am looking into this older PRs that got stuck into the review process.

I see you have made recent pushes. Can you confirm this is ATM ready for review/merge?

**Comment by AjinkyaDahale** [comment]
@abdullahtahiriyo I can confirm it's ready. There are some improvements possible to make the resulting spline C1 or C2 continuous but that can be done in a separate PR.

**Comment by abdullahtahiriyo** [comment]
Possible future improvement:

When joining two curves (a B-Spline and an arc for example), B-Spline poles lose all the weight information. Of course, the weights of some poles need to be adapted (i.e. the ones affected by the merge), but it appears that removing all equality constraints (as currently is the case) is a little bit too much. The user then has to redo all this equalities.

Otherwise it works well and the code is ok.

**Comment by AjinkyaDahale** [comment]
I guess any equalities can be kept by improving the logic. However all bets are off if the b-splines are rational. Definitely a relatively easier problem to handle.

**Comment by AjinkyaDahale** [comment]
@donovaly trying to put up a gif for this in the release notes but not able to. A 1.7 MB file is "too large". Left it as a webp for now, please take a look if you can. Here's the file I tried:

https://user-images.githubusercontent.com/4316933/205505252-065fbfd5-be73-4d1f-92c3-7c3001afc7b3.mp4

**Comment by donovaly** [comment]
> @donovaly trying to put up a gif for this in the release notes but not able to. A 1.7 MB file is "too large". Left it as a webp for now, please take a look if you can. 

No problem, here is a GIF to be used for our Wiki:

FreeCAD_Dmjs36xWYu

**Pull request merged**
