### PR TITLE
[Draft] Update task_scale.py

### PR DESCRIPTION
**Pull request by JAndersM**
The changes solves the Ticket #3691 - Bug in draft scale. Only integers work
See: https://forum.freecadweb.org/viewtopic.php?f=3&t=33952&p=455483#p455483

### CODE REVIEW

**Comment by chennes** [comment]
This compiles, runs, and fixes the problem from the ticket (https://tracker.freecadweb.org/view.php?id=3691).

**Review by chennes — APPROVED** [review]
This compiles, runs, and fixes the problem from the ticket (https://tracker.freecadweb.org/view.php?id=3691).

**Review by abdullahtahiriyo — COMMENTED** [review]
Looks good to a basic skilled Python user. Title updated to reflect the Workbench.

**Comment by yorikvanhavre** [comment]
Thanks for the fix! FYI you can add things like "Fixes #3691" (closes the issue automatically) or "Issue #3691" (simply attaches the commit to an existing issue) in your (hopefully future ;) ) commit messages

**Comment by luzpaz** [comment]
Note: ticket was not closed on tracker. Now it is. Thanks for the heads up @marioalexis84 :wink:

**Comment by JSpinelli73** [comment]
I'm new to coding but have been using FreeCAD for a few years now, and I just discovered this scaling problem.  I am having an issue with trying to edit the FreeCAD code, as in I can't find out how to open it to make the changes.  Would someone be able to help with a walkthrough as if I am a child? Thanks!

**Comment by luzpaz** [comment]
@JSpinelli73 please ask on the forum thread related to this issue or open a new thread. Thanks.

**Pull request merged**
