### PR TITLE
Draft: fix normal calculation for angular dims

### PR DESCRIPTION
**Pull request by Roy-043**
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=75676

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8335">pipeline status</a> for feature branch [PR_8335](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8335). Pipeline [766407724](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/766407724) was triggered at [065ce34](https://github.com/FreeCAD/FreeCAD/pull/8335/commits/065ce344e449c43956cda9ea9aa7647e02de2151). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Roy-043** [comment]
Yes, this is one of 3 PRs that are on my ToDo list for backporting.

**Comment by donovaly** [comment]
Thanks for taking care about the backporting!

Other issue: Since a while I get this CI error:
```
File "/usr/local/Mod/Draft/draftutils/todo.py", line 139, in doTasks
    f(arg)
  File "/usr/local/Mod/Draft/draftmake/make_clone.py", line 129, in <lambda>
    ToDo.delay(lambda col: setattr(cl.ViewObject, "DiffuseColor", col),
ReferenceError: Cannot access attribute 'ViewObject' of deleted object

ToDo.doTasks, Unexpected error:
```

For example here: https://github.com/FreeCAD/FreeCAD/actions/runs/4085407531/jobs/7043347454

Can you please have a look?

**Comment by Roy-043** [comment]
I have noticed that too.
See: https://forum.freecad.org/viewtopic.php?p=656201#p656201

**Pull request merged**
