### PR TITLE
Fix casts

### PR DESCRIPTION
**Pull request by mosfet80**
int_number * float_number return a int_number.
float_number * int_number return a float_number.
swap int and float and remove the cast, this also increase the result precision.

### CODE REVIEW

**Comment by wwmayer** [comment]
Sure?

```
#include <iostream>

int main()
{
    auto res1 = 2 * 1.2F;
    std::cout << typeid(res1).name() << '\n';

    auto res2 = 1.2 * 2F;
    std::cout << typeid(res2).name() << '\n';
}
```
The output of this test application is:
f
f

which means that it's a float in both cases.

**Comment by wwmayer** [comment]
See also: https://stackoverflow.com/questions/5563000/implicit-type-conversion-rules-in-c-operators

**Comment by mosfet80** [comment]
...correct. freecad uses g++17 or higher.
Sometimes I develop on older compilers < g++11 and these changes make a difference.

**Comment by wwmayer** [comment]
Hmm, when I rewrite the code
```
#include <iostream>
#include <typeinfo>

int main()
{
    std::cout << typeid(2 + 1.23456789F).name() << '\n';

    std::cout << typeid(1.23456789F + 2).name() << '\n';
}
```
and build it with the option `--std=c++98` it still says that both are floats.

**Pull request closed without merging**
