### PR TITLE
Draft: Fix regression in annotations for recently introduced ScaleMultiplier

### PR DESCRIPTION
**Pull request by carlopav**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by carlopav** [comment]
@yorikvanhavre 
I spotted a problem with your fix of the regression. The attribute self.ScaleMultiplier was not found when restoring old objects.
So I managed to add the property onDocumentRestored, if it did not exist.
Everything fine, but I noticed a strange thing that I can't understand if it is related (I don't think so): if a document with a label object from 0.18 is opened in 0.19, and no workbench was activated before, FC crashes.
I'll investigate further next days... 
sorry for this inconvenience...

**Comment by yorikvanhavre** [comment]
Strange, self.ScaleMultiplier is defined in the attach() method, which is run when restoring an object... Probably it happens too late.
There is a problem with your PR I think... It contains a lot of changes already merged... Should I cherry-pick only 71d0685 ?

**Comment by carlopav** [comment]
Yes, it's strange indeed...
The pr contains those changes because I tried to drop your fix (I could not avoid the error with your implementation). Perhaps better to wait for the weekend when I'll have a bit more time to test the fix... can we?

**Comment by yorikvanhavre** [comment]
Sure! No problem.

**Comment by carlopav** [comment]
substituted by https://github.com/FreeCAD/FreeCAD/pull/3396

**Pull request closed without merging**
