### PR TITLE
[Surface] Allow modal adding/removal of geometric entities

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
See https://forum.freecadweb.org/viewtopic.php?f=3&t=57538&p=592134#p592134.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909">pipeline status</a> for feature branch [PR_6909](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909). Pipeline [545154308](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/545154308) was triggered at [39bc616](https://github.com/FreeCAD/FreeCAD/pull/6909/commits/39bc616126456e1393ba92e875be748c96aed71a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909">pipeline status</a> for feature branch [PR_6909](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909). Pipeline [550828810](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/550828810) was triggered at [f9e90f8](https://github.com/FreeCAD/FreeCAD/pull/6909/commits/f9e90f82734e7288b651fcabb5de0bdd848f53ed). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909">pipeline status</a> for feature branch [PR_6909](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909). Pipeline [551274783](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/551274783) was triggered at [221e649](https://github.com/FreeCAD/FreeCAD/pull/6909/commits/221e649e4bd6b8208b1500cbcc6919d62c4ab099). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@tomate44 would you also take a look at this when you get a chance?

**Comment by AjinkyaDahale** [comment]
@donovaly, @wwmayer is anyone handling Surface these days?

**Comment by donovaly** [comment]
When you rebase the PR, I will test and merge.

**Comment by donovaly** [comment]
Since it fixes a crash, can you please split the PR in two parts, one that only fixes the bug (no further code optimization, so that I can backport it for FC 0.20.3) and one with the code improvements.

**Comment by AjinkyaDahale** [comment]
@donovaly I don't believe it fixes the crash. I was not able to reproduce it under Manjaro. Besides, this only changes the GUI side.

I have rebased the PR, but I haven't tried to build it locally.

**Comment by wwmayer** [comment]
Will have a look at the weekend...

**Comment by donovaly** [comment]
> @donovaly I don't believe it fixes the crash. I was not able to reproduce it under Manjaro. Besides, this only changes the GUI side.
> 
> I have rebased the PR, but I haven't tried to build it locally.

Many thanks. I can also not reproduce the crash in master and also not in FC 0.20.2.

Your changes makes sense and the code looks good so far.

**Review by donovaly — APPROVED** [review]

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909">pipeline status</a> for feature branch [PR_6909](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909). Pipeline [726104766](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/726104766) was triggered at [8855c50](https://github.com/FreeCAD/FreeCAD/pull/6909/commits/8855c50081e685b18e088a7c536f12fc58de330a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
It basically works fine but there is one issue: with the Surface_Filling command there are three sub-panels and for each of them you can independently press the Add or Remove button. When doing so you have up to three toggled buttons and then it's not obvious in what mode the task dialog is.

**Comment by AjinkyaDahale** [comment]
I might have missed that or chosen to ignore in the first run. We already have done similar things for PD pipe so I'll try to follow that. I'm just running out of builds to work on simultaneously :sweat_smile:.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909">pipeline status</a> for feature branch [PR_6909](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6909). Pipeline [727773385](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/727773385) was triggered at [693d37a](https://github.com/FreeCAD/FreeCAD/pull/6909/commits/693d37a939b9d0d99dd6e4048b3338fdad01c8d7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
>  I'm just running out of builds to work on simultaneously

Don't worry. I can make the needed changes, too.

**Comment by wwmayer** [comment]
e8cba4dda9
6d535f834d

**Pull request merged**
