### PR TITLE
Add export config directory specification feature

### PR DESCRIPTION
**Pull request by wasd845**
From  https://github.com/FreeCAD/FreeCAD/issues/15108

Add the feature to specifying the directory of config file when export.  so that users can find the file quickly.

### CODE REVIEW

**Comment by FEA-eng** [comment]
Compiled and tested, works as expected. It's intentional that configs saved this way aren't listed under Preference packs, right? Maybe the Import config, Save new, Manage and Revert buttons should go outside the Preference packs section if they affect the whole config.

**Comment by wasd845** [comment]
> Compiled and tested, works as expected. It's intentional that configs saved this way aren't listed under Preference packs, right? Maybe the Import config, Save new, Manage and Revert buttons should go outside the Preference packs section if they affect the whole config.

I think configs specified by the user should be considered special, as the user might want to back them up. Otherwise, saving them in the default directory would be fine. So it makes sense that configs with a specified directory aren't under Preference Packs

And you mentioned that the Import config, Save new, Manage and Revert buttons  would affect the whole config.. Could you provide more details on that?

**Comment by wasd845** [comment]
> @FreeCAD/design-working-group can someone check if the UI for this feature is good? Also @wasd845 there are conflicts that needs to be resolved

Conflicts Resolved.

**Comment by kadet1090** [comment]
This change affects the UI so as per the [FreeCAD Contributing Process](https://github.com/FreeCAD/FreeCAD/blob/main/CONTRIBUTING.md) - can you add screenshot representing the UI for this feature? This helps with reviewing it as UI can be mostly checked without compiling the branch.

**Comment by maxwxyz** [comment]
@wasd845 could you add a screenshot?

**Pull request merged**
