### PR TITLE
Sketcher: Improve Join Curves

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Make a C1 continuity at joining. WIP: Intended for when there is already a tangent constraint; those checks are coming.

### CODE REVIEW

**Comment by maxwxyz** [comment]
would it be possible to add a setting (task dialog widget) or some kind of constraint to define or change the continuity (during creation or later on)?

**Comment by AjinkyaDahale** [comment]
> would it be possible to add a setting (task dialog widget) or some kind of constraint to define or change the continuity (during creation or later on)?

I'm working on that. Right now I can think of so:
1. If there is no constraint between the points, move the second to the first and make it C0.
2. If their is an endpoint to endpoint tangent constraint (which also implies coincidence), replace that with C1. Note that this is different from G1, and I haven't yet been able to work out how to preserve shape if weights vary wildly.

At thia point all remaining changes are in the GUI territory. If you need some specific behaviour, which is consistent with existing tools, that maybe possible, but I need clear instructions to confirm. Perhaps the DWG would want to brainstorm over it a little.

**Comment by AjinkyaDahale** [comment]
Marked as ready for review since the behaviour as described in https://github.com/FreeCAD/FreeCAD/pull/12607#issuecomment-1963104326 works. However, there is still some cases where this fails, like when the splines are of degree one.

Additionally, I would like to add the ability to join one curve to itself and create a loop. But I haven't gotten to that yet...

**Comment by chennes** [comment]
How much of this is supposed to work now? When I create two splines, three points each, select an endpoint from each, and choose a tangency constraint, I get a partially redundant constrain and the curves are not made continuous.

**Comment by AjinkyaDahale** [comment]
> How much of this is supposed to work now? When I create two splines, three points each, select an endpoint from each, and choose a tangency constraint, I get a partially redundant constrain and the curves are not made continuous.

Could you add a screenshot? I created two splines with 3 control points (so it has degree 2), and repeated your instructions, and it worked out. No partial constraint. 

Also unclear on what you mean by "made continuous". The tangent constraint itself doesn't join the B-splines. For that, you need to select the point and then press the "join" button.

[Screencast from 2024-03-01 10-24-08.webm](https://github.com/FreeCAD/FreeCAD/assets/4316933/a42f38b7-9a1c-4a27-9dcf-180b81239624)

**Pull request merged**
