### PR TITLE
Make source code comments use gender neutral pronouns

### PR DESCRIPTION
**Pull request by luzpaz**
The changes also include some grammatical fixes as well.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5219">pipeline status</a> for feature branch [PR_5219](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5219). Pipeline [421495104](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/421495104) was triggered at [0042f58](https://github.com/FreeCAD/FreeCAD/pull/5219/commits/0042f58e4c874cf4aec397b49a8175f8948ca77e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by hdt551** [comment]
Virtual signaling acknowledged.

**Comment by luzpaz** [comment]
The presupposition in your statement is that I'm 'showing off' and want everyone to see. In short, you're **so way off** wrong and thanks for clearing your suspicion with me beforehand in private instead of in publicly 'calling me out' for the attention-seeker that I must be. 

Perhaps this is a case of reverse virtual-signalling?

**Comment by hdt551** [comment]
These changes do nothing for readability (not talking about grammar fixes), and when committed will give the impression of some major update which I imagine someone might have to go through to see what was recently changed, maybe on code that otherwise hasn't been touched in a long time. Trying to be "PC" is the only reason to do this.

**Comment by yorikvanhavre** [comment]
This is important. Well done @luzpaz

**Comment by luzpaz** [comment]
@hdt551 you have no sense of your audacity, but I will break it to you that you are wrong in your hot take on 'political correctness.' The real reason is that I would love for devs of any gender, sexual orientation etc... to feel a sense of community and awareness when reading the FreeCAD source code knowing that we've considered them in our scope. 

As for you concern about wrong impressions of a major update, FC is in the middle of a major update.

**Pull request merged**
