### PR TITLE
[FEM] Added spring boundary condition for mechanical problems

### PR DESCRIPTION
**Pull request by Helios113**
This PR adds a spring boundary condition to the FEM workbench of FreeCAD. This boundary condition is going to be used by various MoFEM modules and is also available to other solvers which deal with mechanical problems.

An amendment to src/Base/UnitsSchemaImperial1.cpp is also made, to standardise the naming convention of imperial stiffness units.

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
would you split the unit changes into a separate commit, may be even a separate PR? All changes outside the modules should be reviewed more deeply.

**Comment by berndhahnebach** [comment]
the new object should be added to the unit test https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Fem/femtest/app/test_object.py

**Comment by Helios113** [comment]
Added unit test, all tests are OK. Also, I split the commit.

**Comment by Helios113** [comment]
@berndhahnebach Any extra changes that I need to do, or can I help with code review?

**Comment by berndhahnebach** [comment]
cool, LGTM,  :-)

I still need to compile and run it before merging.

**Comment by Helios113** [comment]
Yeah, absolutely, splitting makes everything easier.

I have another PR waiting once this one goes through ;).

**Comment by donovaly** [comment]
Dear Helios113, can you please also document the new feature? I already created a Wiki page that you just need to fill out:
https://wiki.freecadweb.org/FEM_ConstraintSpring
See the other constraint descriptions for how this is done. Many thanks!

**Pull request merged**
