### PR TITLE
[CheckGeometry] add new shapecontent builder instead of OCCT's to cor…

### PR DESCRIPTION
**Pull request by mwganson**
…rect some errors in OCCT's values and to add for some more advanced information, e.g. volume or area, add new method to Base::Interpreter runStringWithKey() -- allows to run a python script and get a string return value

There are times when OCCT returns unexpected information, example the wrong number of faces of the checked shape.  See this forum topic:

https://forum.freecadweb.org/viewtopic.php?f=22&t=48792

There is already a method to get a string return value from python in Base::Interpreter().runString() but it didn't work for me.  The new function also adds the ability to pass a parameter to the python script as a key value.

The advanced shape properties can be disabled in settings for users who do not wish to have it.

The OCCT shape content is still used as a fallback if the script has a runtime error.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by mwganson** [comment]
Open Discussion topic
https://forum.freecadweb.org/viewtopic.php?f=8&t=48994

**Comment by mwganson** [comment]
I'm working on a fix for the travis ci python2 build failure.

**Comment by mwganson** [comment]
I'll need to revise that last commit.  After further testing I got a seg fault.

**Comment by mwganson** [comment]
I was able to build and test for both py2 and py3.

I inserted intentional errors in the python script to test what would happen in those cases, and with the try/catch block I was able to still fallback on the old method to at least provide the basic shape content.

runStringWithKey() will now check for an throw a python exception rather than simply return the default key value.  If a python runtime error occurs it will include the script text in the error message to aid in debugging.

I think I'm finished working on this for now.

**Comment by yorikvanhavre** [comment]
Looks very good to me! Leaving to master @wwmayer to have a look too

**Pull request merged**
