### PR TITLE
[GUI] Stylesheet QToolButton icon fix in QT file dialogs

### PR DESCRIPTION
**Pull request by turn211**
Fixes no icons showing in QT File Dialogs
forums discussion here: https://forum.freecadweb.org/viewtopic.php?f=34&t=57427

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by donovaly** [comment]
So this PR must go in also for the 0-19 branch in order to release FC 0.19.2 since this release will be for the style fixes.

**Comment by turn211** [comment]
> 
> 
> So this PR must go in also for the 0-19 branch in order to release FC 0.19.2 since this release will be for the style fixes.

Yes correct.

**Comment by wwmayer** [comment]
In PR #4719 the same forum thread is linked. There it's about the tiny icons of the file dialog which the other PR already fixes. 
When looking at the code changes of this PR than a many other things are done. Are you sure you linked the correct forum thread?

**Comment by turn211** [comment]
I really don't know why everytime I issue a PR it combines the last commit with the new PR. I've rebased on my end and its fine. This PR consists only of these lines of code as ProDark. 40f3646.  Don't know what to say as I'm trying my best.

` 
/*==================================================================================================
Tool button Icon fix in save dialogs
==================================================================================================*/
/* found under Tools -> Save Picture */ /* Draft -> ShapeString -> Font file */

QFileDialog#QFileDialog QToolButton {
    background-color: transparent;
    padding: 1px;
    border: 1px;
    margin: 0px;
}

QFileDialog#QFileDialog QToolButton:hover,
QFileDialog#QFileDialog QToolButton:focus {
    color: #ffffff;
    background-color: #557bb6;
    border: 1px solid #f5f5f5;
}

/*==================================================================================================
Tool button inside QDialogs that works as QPushButtons
==================================================================================================*/
@ -1753,8 +1772,8 @@ Tool button inside Task Panel content that works as QPushButtons
QSint--ActionGroup QFrame[class="content"] QToolButton {
    color: #e0e0e0;
    text-align: center;
    background-color: qlineargradient(spread:pad, x1:0, y1:0.3, x2:0, y2:1, stop:0 #2a2a2a, stop:1 #1e1e1e);
    border: 1px solid #1e1e1e;
    background-color: #2a2a2a;
    border: 1px solid #494949;
    border-bottom-color: black; /* simulates shadow under the button */
    padding: 2px 6px; /* different than regular QPushButton */
    margin: 2px; /* different than regular QPushButton */
@ -1765,14 +1784,14 @@ QSint--ActionGroup QFrame[class="content"] QToolButton {
QSint--ActionGroup QFrame[class="content"] QToolButton:hover,
QSint--ActionGroup QFrame[class="content"] QToolButton:focus {
    color: white;
    border-color: #557BB6;
    border-color: solid #f5f5f5;
    background-color: #557BB6;
}

QSint--ActionGroup QFrame[class="content"] QToolButton:disabled,
QSint--ActionGroup QFrame[class="content"] QToolButton:disabled:checked {
    color: #f5f5f5;
    border-color: #424242;
    border-color: #494949;
    background-color: #424242;
}
`

**Comment by luzpaz** [comment]
@turn211 you have to create a new branch off of the master branch HEAD each time you make a new PR.

**Pull request closed without merging**
