### PR TITLE
Core: Add App::PropertyXLinkSubHidden

### PR DESCRIPTION
**Pull request by PaddleStroke**
This PR is adding a PropertyXLinkSubHidden property. Which is just a PropertyXLinkSub with the hidden scope.

This addition is needed to solve the assembly 'getGlobalPlacement' (https://github.com/FreeCAD/FreeCAD/issues/15090) where  PropertyXLinkSub cannot be used because it cause dependency loops.

@wwmayer is this change ok for you? If so it would be great if this can be merged as soon as possible because this change requires almost a full rebuild, so everytime I checkout from my 15090-branch (which is a huge work so i'll be at it for long), I have to rebuild almost the whole project which takes more than 30 minutes on my machine. And currently I have 15 opened PR to maintain so this is bound to be very tedious. Also this change is very trivial.

Thanks!

### CODE REVIEW

**Comment by wwmayer** [comment]
It's fine for me. But this is just a convenience class and you can achieve the same effect with:
```
App::PropertyXLinkSub linkProperty;
linkProperty.setScope(LinkScope::Hidden);
```

**Comment by PaddleStroke** [comment]
In cpp yes but I couldn't find how to do this in python. So I thought this was the reason we had all these types of PropertyLink.

**Comment by wwmayer** [comment]
That's right, in Python you can't.

**Comment by PaddleStroke** [comment]
Thanks for the fast processing ! :)

**Pull request merged**
