### PR TITLE
[GUI] QuantitySpinBox: Regex optimization.

### PR DESCRIPTION
**Pull request by ConnorWorrell**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---
Addressing issue https://github.com/FreeCAD/FreeCAD/issues/9864, regex performance improvements.

### CODE REVIEW

**Comment by chennes** [comment]
I propose to merge this into master now, and if it seems to solve the bug reporter's issue, back port it to the 0.21 release branch for inclusion in 0.21.1 -- any objections?

**Comment by grubertechnic** [comment]
> back port it to the 0.21 release branch for inclusion in 0.21.1

+1, that would be nice (not for me, i use master, but for others).

**Comment by adrianinsaval** [comment]
@grubertechnic is this making it faster enough? Or is it still a very noticeably slowdown?

**Comment by grubertechnic** [comment]
@adrianinsaval : will compile and test it today, (un)luckly i get some time.

**Comment by grubertechnic** [comment]
@adrianinsaval and @ConnorWorrell : as i see, that is in the master already. Anyway i recompiled the master and can confirm, that it is work now pristine.

```
OS: Debian GNU/Linux 11 (bullseye) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33742 (Git)
Build type: Release
Branch: master
Hash: 0af4990817621a78a3e7e24a1f78ac7c9e543add
Python 3.9.2, Qt 5.15.2, Coin 4.0.0, Vtk 9.0.1, OCC 7.7.1
Locale: English/United States (en_US)
Installed mods: 
  * QuickMeasure 2022.10.28
```

**Comment by chennes** [comment]
I'm going to mark this for back porting to the 0.21.x series.

**Pull request merged**
