### PR TITLE
Correct code tag for info

### PR DESCRIPTION
**Pull request by Kuzma30**
Change [code] to ``` as code tag don't recognize and user need manualy correct tag when post About info on github.

### CODE REVIEW

**Comment by luzpaz** [comment]
Maybe we can figure out how to support the 3 backticks in the forum too ?

**Comment by Kuzma30** [comment]
> Maybe we can figure out how to support the 3 backticks in the forum too ?

https://forum.freecad.org/app.php/help/bbcode
at the end of document


Can I add my own tags?
    If you are an administrator on this board and have the proper permissions, you can add further BBCodes through the Custom BBCodes section.

**Comment by luzpaz** [comment]
@Kuzma30 we've tried that but I think bbcode requires square brackets if I'm not mistaken

**Comment by Kuzma30** [comment]
> @Kuzma30 we've tried that but I think bbcode requires square brackets if I'm not mistaken
> 
> it would need to be an addon for the forum or a custom hack ?

I think we need https://www.phpbb.com/customise/db/extension/markdown/

**Comment by luzpaz** [comment]
@Kuzma30 we need a phpbb developer to help us with the forum. We tried to install the markdown extension and it created some problems IIRC.

**Comment by Kuzma30** [comment]
@luzpaz What type of problem you get?

**Comment by luzpaz** [comment]
@kkremitzki do you remember the issues that cropped up from enabling markdown in the forum? (apologies if I may be confusing you with yorik or someone else who tested this)

**Comment by wwmayer** [comment]
> What type of problem you get?

Having the three apostrophes at the end causes formatting errors when creating new tickets. Once had to always fix the pasted content.

**Comment by luzpaz** [comment]
ticket template should chance then ?

**Pull request merged**
