### PR TITLE
Spreadsheet: export CSV file extension by default (fixes #10829)

### LINKED ISSUE #10829: [Problem] Spreadsheet Workbench export does not have an associated filetype
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When a Spreadsheet object is created in a Project, the "Export Spreadsheet to CSV' function does not save the file with a filetype. The .CSV filetype must be manually added on the exported file.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3D_Printing_Tools
  * Assembly4 0.50.2
  * CommandPanel
  * fasteners 0.4.66
  * Manipulator 1.5.0
  * slic3r-tools
[/code]
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Predko**
Correction
'Spreadsheet Workbench export does not have an associated filetype #10829'

### CODE REVIEW

**Comment by xtemp09** [comment]
I'm not an expert in FreeCAD, I've just looked at similar code across the source.

The function `Gui::FileDialog::getSaveFileName` checks the extension.[^1] One has merely to use `selectedFilter` like it is done in TechDraw.[^2] [^3]


[^1]: https://github.com/FreeCAD/FreeCAD/blob/0d7880a902154adc22ee24df40b443c9aa3a7d8a/src/Gui/FileDialog.cpp#L159
[^2]: https://github.com/FreeCAD/FreeCAD/blob/0d7880a902154adc22ee24df40b443c9aa3a7d8a/src/Mod/TechDraw/Gui/Command.cpp#L1627
[^3]: https://github.com/FreeCAD/FreeCAD/blob/0d7880a902154adc22ee24df40b443c9aa3a7d8a/src/Mod/TechDraw/Gui/MDIViewPage.cpp#L536

**Comment by Predko** [comment]
@xtemp09 ,
You are right, if selectedFilter is not set, the function finds the first extension in the filter and adds it.
I made a commit with these changes.

**Comment by luzpaz** [comment]
Note to merge dev, please rename commit: 
title: 'Spreadsheet: export CSV file extension by default'  
body: 'Fixes #10829'

or whatever other title seems fit

**Comment by Predko** [comment]
sorry, I did something wrong)

**Comment by luzpaz** [comment]
No problem. It happens all the time. We need to rebase the commit. Is there a merge dev available ?

**Comment by Predko** [comment]
Added the latest commit.
Compiled and tested.

**Comment by xtemp09** [comment]
Maintainers and reviewers don't seem to be paying attention to this pull request.

@Predko, why does your PR have 18 commits? How can they be merged without introducing some hell? Why do your commits still have meaningless titles, despite luzpaz' remark above? _Merge branch 'FreeCAD:master' into Predko-patch-FreeCAD#10829_ and others don't convey any meaning.

I don't want to do by no means job of maintainers, but in my understanding, one-line patch is supposed to be one commit.

**Comment by Predko** [comment]
@xtemp09 ,
Everything is very simple:
1. I don’t understand well how git works in a team. This is my first experience.
2. Apparently I made a mistake and added commits from other developers to my branch. Hence the number of commits.
It might be possible to do a rebase, but I'm afraid of causing even more chaos...
3. I don’t yet understand what the requirements for the name of the commit are.
Sorry again.

**Comment by xtemp09** [comment]
Maintainers can modify pull requests. Let's hope they fix it. =)

**Comment by Predko** [comment]
Created a new request #10889, replacing this one.

**Pull request closed without merging**
