### PR TITLE
improve unit testing directory structure

### PR DESCRIPTION
**Pull request by berniev**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---
Second attempt. See #8078

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8125">pipeline status</a> for feature branch [PR_8125](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8125). Pipeline [737702536](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/737702536) was triggered at [191f98f](https://github.com/FreeCAD/FreeCAD/pull/8125/commits/191f98f81f6760ea71240978434ffc493d61348f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
@wwmayer Could you consider having a look at this when you get a moment? TIA.

**Comment by chennes** [comment]
Running cMake on this gives me a warning at the end:
```
CMake Warning (dev) at tests/src/App/CMakeLists.txt:1 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  A private source from a directory other than that of target "Tests_run" has
  a relative path.
```

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8125">pipeline status</a> for feature branch [PR_8125](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8125). Pipeline [761010431](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761010431) was triggered at [1e65431](https://github.com/FreeCAD/FreeCAD/pull/8125/commits/1e654316845dfe716200b811e79f6179f0f6d17d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
I don't get any warning from cmake run.

Is there some special setup?

**Comment by chennes** [comment]
Do you have the `-Wno-dev` option set? That would deactivate this warning. I'm on 3.22.0 vanilla cMake on Windows, nothing special that I'm aware of.

**Comment by berniev** [comment]
> Do you have the -Wno-dev option set?

Yep!!! Deleted

**Comment by berniev** [comment]
I've force-pushed an update. Looks good here. All included tests run as expected.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8125">pipeline status</a> for feature branch [PR_8125](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8125). Pipeline [761072578](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761072578) was triggered at [0f476a3](https://github.com/FreeCAD/FreeCAD/pull/8125/commits/0f476a300018cd79b33972effd38362219962765). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
It seems like there are no objections to the proposed structure, so if you'll resolve that conflict I'll get it merged.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8125">pipeline status</a> for feature branch [PR_8125](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8125). Pipeline [761533888](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761533888) was triggered at [2841f0f](https://github.com/FreeCAD/FreeCAD/pull/8125/commits/2841f0f5c009783291cba663b3966e1774b750d4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
Thanks!

**Pull request merged**
