### PR TITLE
Sketcher: Add constraint icon scaling.

### PR DESCRIPTION
**Pull request by kisolre**
https://forum.freecadweb.org/viewtopic.php?f=3&t=4362&start=20#p458026

### CODE REVIEW

**Review by hyarion — COMMENTED** [review]
Here are some minor tips which might help you with your pull request :)

**Comment by luzpaz** [comment]
Hi @kisolre, thanks for the PR. Do you mind force pushing an amend  to the summary which should have `Sketcher:` prepended to it? Also it's better to `git rebase` than `git merge`. The devs can change that stuff for you but in general it's good practice to do so.

**Comment by kisolre** [comment]
@luzpaz I changed the title of the pull request. Is that what you meant? 
I was too fast to make that pull request without actually understanding what is going on under the hood with Git... 
My fork is a mess (I think)  so I plan to reset it to FreeCAD master. Will that brake the pull request? Is there a simple guide of how to do such edits? Like create a fork, clone locally, edit some files, rebase, stage changes, commit, push, create pull request from within github site...

**Comment by hyarion** [comment]
@kisolre you don't need to redo it. It can be fixed like this using a terminal on your computer (I'm writing this from memory so there might be an error in the instructions):

Add freecad's repository as a remote (maybe you have done this already, if you have, just run `git fetch`):
`git remote add upstream https://github.com/freecad/freecad.git`

Create a temporary branch (but don't switch to it)
`git branch tmp`

Make sure you have created the temporary branch but still have on your master branch checked out with `git branch` 

Reset your master branch (which you are now standing on) with:
`git reset upstream/master`

Cherry pick your changes:
`git cherry-pick 30656e64` <--- the number is a shortened version of your commit's SHA identifier which lives on the tmp-branch. If you have more commits, cherry-pick each one the same way

Now your master branch will have your change on the latest freecad master branch

Fix the amend thing luzpaz asked you, run:
`git commit --amend`
This will let you change the last commit message (if you have multiple commits, do this after each cherry-pick)
Prepend `Sketcher: ` to the commit message

Now you're ready to push your fixes, but since you changed the history, git will complain... so add `-f` to overwrite what you have on origin:
`git push -f`

This pull request will update since it's linked to your branch.

Once you've verified that everything is like you want it, remove the tmp branch:
`git branch -D tmp`

There are other ways to do the same thing, but I think the instructions above are the easiest way to follow if you aren't that used to git. `git rebase -i upstream/master` would be a better way, but in my opinion it has a higher chance to screw things up if you're not used to git
You might be interested in read this article: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by chennes** [comment]
The wiki includes a nice set of instructions for forking, branching, editing, rebasing, and submitting a PR, here:
https://wiki.freecadweb.org/Source_code_management

**Comment by kisolre** [comment]
@hyarion Thanks, looks like it worked :) Is there a way to directly modify the code to implement your suggestions or I need to make a new pull request?

@chennes Thanks, I should have read that before jumping in..

**Comment by luzpaz** [comment]
@kisolre sometimes you just need to jump in :laughing:

**Comment by hyarion** [comment]
@kisolre: Whatever you push onto your branch will be added here in this pull request (the PR is a request for freecad to pull your changes from the source branch you specified onto the specified target branch). I haven't yet seen a good reason why you ever would need to close and make a new pull request, as it seems like you can always fix the issues without doing that.

As for modifying the code:
The suggestion I made can be applied directly, the other comments needs to be manually modified.
It is however best practise to change and test fixes locally first, even when it's feedback in a review. This to ensure that you haven't introduced any new bugs.

**Comment by kisolre** [comment]
Another question: If I implement suggested changes should I make a new commit or just amend the existing one (as I understand this will result in commit with the final changes only)?

**Comment by luzpaz** [comment]
You can make a new commit. That way reviewers can see what you changed. If you're wondering how to deal with numerous commits (that would pollute the commit history) there is a command called `git squash` that allows squashing commits together. But don't worry about that in this context

**Comment by abdullahtahiriyo** [comment]
Thank you! Merged as part of https://github.com/FreeCAD/FreeCAD/pull/4258.

**Pull request closed without merging**
