### PR TITLE
[Path] GUI scripting support and other improvements

### PR DESCRIPTION
**Pull request by Russ4262**
This PR makes some useful changes to the existing operations to ease scripting with GUI support for the Path WB.  This improvement is done by relocating the creation of the `PathOpGui.CommandResources` object from being an object inside the `PathOpGui.SetupOperation()` function to each GUI operation module, and passing this independent resource object to the `PathOpGui.SetupOperation()` function in place of the original arguments that were used to create the same resource object.  With this relocation, the ability to disable the initial Task Panel GUI interaction is added.  This means users can script with GUI/view-provider support without having to interact with the Task Panel for new operations or jobs.  The good news is that the normal/existing ability to edit operations and jobs with the Task Panel is still available once the new operation or job is created.

This PR adds the ability to pass the parent job for a new operation as an optional argument in the `Create()` function within each operation module.  This allows the new operation to be pre-assigned to the provided parent job instead of needing to ask the user during GUI sessions.

This PR refactors the PathDressupBoundary module only by isolating the boundary dressup algorithm into an independent class so it is accessible without the requirement of creating a new dressup object.

This PR contains a fix for failed toolbit lookups from fixed-path toolbits used in shared files, that allows Path to locate the equivalent bit on the local machine.  There is bug 4647 in the tracker system that this might affect in a positive way.  I have not investigated whether the fix in this PR has a positive affect on that particular bug.

This PR also adds an improvement to the Job Simulator usage.  It simply adds an auto-loading action of a Job in the simulator if the user has one selected, otherwise the simulator feature is untouched.  This improvement is really just an ease-of-use improvement.  If the user has a job selected prior to running the job simulator, then that job will be auto-loaded in the simulator.
 
 
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by Russ4262** [comment]
I added a commit to improve Path Simulator by way of auto-loading the pre-selected Job in the simulator.

**Comment by sliptonic** [comment]
Can the tiling feature proposal be split out as a separate (later) PR?

**Comment by Russ4262** [comment]
> Can the tiling feature proposal be split out as a separate (later) PR?

For clarity, you are asking that this current PR be cleansed of the Tile Job Utility portion, and limited to the scripting and other improvements?  And then create another Tile Job Utility PR independently, that would be dependent on this PR being merged, yes?

If this is the correct interpretation of your question, I believe the answer to be yes.  I believe I can repurpose this current PR into a scripting-only improvements PR, and then create a secondary follow-up PR that contains the Tile Job Utility.
 
Awaiting confirmation and/or correction.
Thanks.

**Comment by Russ4262** [comment]
On a separate note, if @dubstar-04 is able to test the included commit [https://github.com/FreeCAD/FreeCAD/pull/4797/commits/1761bc1f59366b5e240ff085ccfcdcd892ed598b](https://github.com/FreeCAD/FreeCAD/pull/4797/commits/1761bc1f59366b5e240ff085ccfcdcd892ed598b) as it pertains to bug 4647 in the tracker system, I would be appreciative.  
During development of this new tiling feature, I also ran into a problem with the toolbit system's resolution/location of a standard bit used within a shared file from another user.  My machine failed to locate the same bit on my machine because my bit file was not at the location specified in the ToolBit object in the shared file.
 
The fix proposed at the commit in this PR, at the link above, fixed the issue on my machine, but does need review by others - another reason for this PR being a Draft.  I will try to figure out how to reproduce bug 4647 and then test with this commit in discussion here.

**Comment by sliptonic** [comment]
> 
> For clarity, you are asking that this current PR be cleansed of the Tile Job Utility portion, and limited to the scripting and other improvements? And then create another Tile Job Utility PR independently, that would be dependent on this PR being merged, yes?
> 
Yes, exactly.  Big PRs are problematic.  Not just because there's a lot of code to review but also because acceptance is all or nothing.  I haven't played with the feature yet but it might be that we want to move forward with the scripting improvements and give the new feature more time for evaluation.

**Comment by Russ4262** [comment]
@sliptonic 
This PR has now been reduced to scripting improvements and fixes only.  The proposed Tile Job Utility feature has been removed.  
.
I will see if I can reproduce the relative/absolute toolbit path bug posted in the bug tracker and see if the toolbit path related fix committed in this PR has any influence on it.

**Comment by Russ4262** [comment]
There is a small change/improvement I would like to make to this PR regarding the current scripting improvements.  What I have in mind should make these changes a little easier for users to implement in scripts.  I am doing some more research on the changes and testing to see which is better for interaction and simplicity.

**Comment by Russ4262** [comment]
Okay.  Small change made.  Added a simple `CreateOp()` method for simpler scripting with GUI/viewprovider support. 
.
Might need to take out commit 89137c2.  Doing some research on toolbit bug 4697 in tracker.  I don't think the fix here improves that bug.

**Comment by Russ4262** [comment]
I removed the toolbit-related fix commit from this PR.

**Comment by Russ4262** [comment]
@sliptonic 
This PR is ready.  I removed the gui-related scripting improvements and their commits.  I learned how to successfully add a ViewProvider to a non-gui operation.  It would be nice to add some code to make this easier, but that can be later down the road.  I also fixed a bug in the ff3adac commit in this PR.
Thanks

**Pull request merged**
