### PR TITLE
[App] sort includes in PreCompiled.h

### PR DESCRIPTION
**Pull request by donovaly**
- also remove a superfluous private: statement
- also remove an unnecessary include

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8527">pipeline status</a> for feature branch [PR_8527](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8527). Pipeline [781998479](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/781998479) was triggered at [8b2b271](https://github.com/FreeCAD/FreeCAD/pull/8527/commits/8b2b2719087a296d2756805319f890dd2c933f5c). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by JanneKro** [comment]
This causes Windows-builds to fail.
Maybe because there seems to be whitespaces between '#' and 'include' at some places?

**Comment by donovaly** [comment]
> This causes Windows-builds to fail.

I am on Windows and compile with MSVC 2022. If you use precompiled headers, you need to delete the *.pch files in your build folder then recompile.
If this does not fix your issue our you don't use precompiled headers. clean in MSVC only the target "FreeCADApp" and recompile.

**Comment by donovaly** [comment]
I see now that master in uncompilabe because of this: https://github.com/FreeCAD/FreeCAD/pull/8352#issuecomment-1435769625

**Comment by JanneKro** [comment]
@donovaly Yes, this is the one.  I saw that commit and somehow ended here when I checked later. Sorry.

**Comment by donovaly** [comment]
> @donovaly Yes, this is the one. I saw that commit and somehow ended here when I checked later. Sorry.

I applied now a hotfix: #8536 Please checkout master and recompile. Please report back if your problems are fixed.

**Pull request merged**
