### PR TITLE
Fix MacOS-X build of FreeCAD-0.20.1

### PR DESCRIPTION
**Pull request by jbaehr**
This PR allows building 0.20 branch on macos 10.14 again. Some over aggressive include optimisations made the build fail here. For details please refer to respective commit messages, which also list the commits that introduce the errors.

@wwmayer @donovaly as you commited the original changes, you're probably the most suited to review my "undoings".

I'm aware that this PR is not limited to a single module. However, the commits are semantically grouped and the issue does span multiple modules. In fact, it was quite cumbersome that the original commits *were* splitted despite addressing one thing. This made the analysis and partial reversion harder than needed so I really prefer to not split them again.

Note that the master branch is also affected by the issue. However, depending on the origin (maybe an outdated cmake? or compiler?) the solution may be different; i.e. you may choose to not support Mojave any more, as did Apple. But as 0.20 used to build fine on macos 10.14, I want to keep this possible for the 0.20.x releases.

-------
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
The PR can be merged as it is. All what it does is to extend the include path and include some mandatory headers. So, everything is fine.

> Note that the master branch is also affected by the issue. However, depending on the origin (maybe an outdated cmake? or compiler?) the solution may be different;

The PR should be applied to master branch too, then. But there might be merge conflicts.

**Comment by ipatch** [comment]
this is something i have run into as well when building on macos mojave using the 10.15 SDK.  i don' think these errors arise when using the 10.16 SDK, but i haven't fully tested. either way adding the include of cmath fixes the two issues i ran into. and also  added them in a preprocessor directive as seen below,

https://github.com/FreeCAD/FreeCAD/compare/master...ipatch:FreeCAD:ipatch.builds.0.20.1

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7389">pipeline status</a> for feature branch [PR_7389](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7389). Pipeline [620878078](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/620878078) was triggered at [21c7b34](https://github.com/FreeCAD/FreeCAD/pull/7389/commits/21c7b34d4663f2688af07fd9a4ac713e69a40f27). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@jbaehr , many thanks. I will merge it now. Can you please also create a PR for master? (I am currently abroad without access to my development PCs) therefore  cannot do this.

**Comment by jbaehr** [comment]
> Can you please also create a PR for master?

Will do. I already picked the two commits to the current master and resolved the conflicts. Just waiting for the build to complete.

**Comment by ipatch** [comment]
was this suppose to be a part of the `0.20.1` release that came out a while back?

**Comment by adrianinsaval** [comment]
It was merged afterwards so you would have to apply it as a patch if building the 0.20.1 tag, the future 0.20.2 should have this included

**Pull request merged**
