### PR TITLE
Path: Fix step transition optimizations

### PR DESCRIPTION
**Pull request by gwicke**
Avoid generating paths that are intersecting the model by making the step transition optimization logic more conservative.

Test case:  https://drive.google.com/open?id=1ZxDGlWaVBBg9iyBH6RRQ2zQrGGbCfM0e

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
I strongly suggest you don't use Black for formatting. It adds a ton of lines for parentheses, making the code look like C, not like Python.

**Comment by gwicke** [comment]
I used black since it is mature and widely used. The parentheses are primarily added when horizontal space is approaching the limit; do you prefer backslash continuations in that situation?

**Comment by vocx-fc** [comment]
Parentheses have automatic line continuation, so no need to add backslashes. Black breaks lines in an opening parenthesis similar to C, which is unnecessary. You can just continue at the same visual level. This style is more Pythonic, while Black tries to force some C style.
```py
something(argument, two,
          three, four)
```

With Black you get something like this
```py
something(
    argument, two,
    three, four
)
```

**Comment by gwicke** [comment]
@vocx-fc, I re-formatted the file with yapf instead of black, which uses the more compact formatting for multi-line statements.

**Comment by vocx-fc** [comment]
You have to stop relying in automatic formatters. Python is meant to be read by humans. Automatic formatting is okay for C or Java, because readability isn't as important in that case.

**Comment by gwicke** [comment]
Since I am more interested in the transition fix than the cleanup, I dropped the latter from this PR. Happy to put up a separate autoformat diff if there is interest in cleaning up line endings & PEP8 issues at a later point.

**Comment by vocx-fc** [comment]
About the line endings, this was already noticed a while ago. See #2752 and #2757.

The solution is to use a global `.gitattributes` file which automatically handles line ending conversion in the source code when commits are made. This file is currently in `src/Mod/.gitattributes`.

At that time, the line endings of several directories were converted, like Draft, Arch, Fem, Addon Manager, etc.

Many directories were not touched, like Path, Drawing, Image, Import, Mesh, TechDraw, etc. The idea is that the maintainer of a particular module should look into this with detail and decide when it's okay to normalize the line endings of the module and make sure no source file breaks. So, please discuss in the forum with the Path guys and with @sliptonic, and if everybody agrees, I think the only thing that you need to do is comment the line in the `.gitattributes` file.
```
# Path/** -text
```

**Comment by gwicke** [comment]
@vocx-fc, thanks for the suggestion, put up a separate diff with just the newline change in #3506.

**Comment by gwicke** [comment]
I am still not completely happy with this PR. One issue I saw in practice is that permanently ramping up view resolution on complex models can make opening such files later super slow if the internal model is not marked as hidden.

The alternative, bringing back a plain tessellate(linearDeflection) call works fine, but is very slow since that call is single threaded (while view tessellation allows multi threading). Allowing multi threading with a small CPP change improves things, and should benefit other users of tessellate() as well. Still not perfect, but probably the best we can do unless we can figure out a way to cache / share tessellations of sufficient resolution across path generations. I'll put up a new version with that change in a bit, probably after #3506 is decided.

**Comment by gwicke** [comment]
I have some more ambitious follow-up changes locally, but those can go into a separate PR.

**Pull request merged**
