### PR TITLE
Add page size to ISO 5457 template borders, replaced page size data fields, added blank owner data fields

### PR DESCRIPTION
**Pull request by HowThatWorks**
As pointed out by @tobiasfalk [here](https://forum.freecad.org/viewtopic.php?t=85519&start=10#p756469), TechDraws' ISO 5457 templates are missing the page size in the lower right section of the grid reference border required by ISO 5457:1999. As discussed later in that thread, correcting this mistake makes the page size data field in the title block redundant, so I replaced it with a language code data field.

In that same forum thread @aapo-aapo also requested that some editable data fields be added for the owner, so I took the opportunity to add some blank data fields, as well as generally clean up the .SVG files.

### CODE REVIEW

**Comment by tobiasfalk** [comment]
I just took a look and I saw that with the A4 templates the Titleblock overlaps with the bottom Centering Mark of the frame, to my knowledge in this case the Centering can be shortened so that it  o longer intrudes in to the Titleblock.
But to be sure I will look in to it when I am at home🤦‍♂️😁.

**Comment by HowThatWorks** [comment]
Yeah that's something I went back and fourth on when I originally made them. It's not something that the standard covers explicitly, and I ultimately decided to go with consistency over readability. Now that you bring it up however, I think what I'll do is make that Centring Mark a bit shorter, so that it'll still extend into the title block but it won't interfere with any text.
Screenshot 2024-05-05 211717

**Comment by HowThatWorks** [comment]
And of course I found a typo as well...

**Comment by tobiasfalk** [comment]
Since this is something that happens only on smaller paper sizes I think that the other Centering Mark on the top is more than enough and so making it completely not intruding is the the best(my opinion), especially if you leave the short line with a bigger line width

**Comment by HowThatWorks** [comment]
I disagree, as long as it isn't interfering with the text (and it's now short enough that it won't touch any descenders) it's an aesthetic decision. To my eye, looking at the sheet as a whole, it looks better with just a bit of protrusion into the title block.

**Pull request merged**
