### PR TITLE
[TD] rename some Draw* elements

### PR DESCRIPTION
**Pull request by donovaly**
as discussed here: https://forum.freecadweb.org/viewtopic.php?p=360042#p360042

### CODE REVIEW

**Comment by vocx-fc** [comment]
`TaskActiveView.cpp`, `TaskLeaderLine.cpp`, `TaskRichAnno.cpp`, look like they are being modified entirely.

Are you sure you aren't changing the line endings.

**Comment by WandererFan** [comment]
@vocx-fc just beat me to it.  Check your git settings (core.autocrlf) or maybe your editor.  We want LF endings in the repository, not CRLF.   
Could be trailing whitespace too, but line endings are more likely.

**Comment by wwmayer** [comment]
When you review the code you can add "?w=1" to the end of the url so that GH shows only the actual changes.
But nevertheless you're right that it should be avoided to change the line endings of the whole file.

**Comment by WandererFan** [comment]
Uwe, the actual changes look fine.  Just fix the line endings and the conflict in TaskLeaderLine.cpp(yours is older than the one in master and doesn't have the recent changes for load time problems).

Thanks,
wf

**Comment by donovaly** [comment]
> Uwe, the actual changes look fine. Just fix the line endings and the conflict in TaskLeaderLine.cpp(yours is older than the one in master and doesn't have the recent changes for load time problems).

OK. I'll tried this already but cannot resolve the merge conflict. So I will open a new PR to save time (later today).

**Comment by donovaly** [comment]
> OK. I'll tried this already but cannot resolve the merge conflict. So I will open a new PR to save time (later today).

here it is:
https://github.com/FreeCAD/FreeCAD/pull/2911

**Pull request closed without merging**
