### PR TITLE
2 TechDraw Fixes

### PR DESCRIPTION
**Pull request by WandererFan**
Please merge these TechDraw fixes.  
Thanks,
wf

- Handle variable UoM schemes in Dimensions 
  - [https://www.forum.freecadweb.org/viewtopic.php?f=35&t=24694](url)
- Fix 3215 - ViewDetail does not handle Scale correctly 
  - [https://freecadweb.org/tracker/view.php?id=0003215](url)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by WandererFan** [comment]
Travis OSX builds failed.  Time out?  Log seems to just end.
Appveyor and Travis Linux builds succeed.

**Comment by wwmayer** [comment]
I recently added the change to suppress -Wno-undefined-var-template because it created tons of false-positives. Apparently the macOS builds use an older compiler version which lacks of the compiler switch.

**Comment by luzpaz** [comment]
We should then update the OSX compiler, right?

**Comment by wwmayer** [comment]
No, I can make a check around the compiler flag but therefore I must know which compiler version exactly is used, hence the commit 5823aac

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
