### PR TITLE
Path helix

### PR DESCRIPTION
**Pull request by lhuedepohl**
Two small fixes, one deals with issue #2864 (http://freecadweb.org/tracker/view.php?id=2864, apparently this is different from the GitHub issue list...), one is to be less strict about what constitutes a "straight" cylinder.

### CODE REVIEW

**Comment by wwmayer** [comment]
@sliptonic  or others please have a look if this is OK for you.

**Comment by sliptonic** [comment]
@wwmayer No issues here.

**Comment by lhuedepohl** [comment]
(I should probably have mentioned that I recently changed my GitHub username. Previously I was dev-at-stellardeath.org)

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
