### PR TITLE
Draft: Fix alignment of angular dimension arrows

### PR DESCRIPTION
**Pull request by Roy-043**
When calculating the alignment of the arrows the length of the arrows, in mm, was subtracted or added to a parameter in radians.

Additionally:
* When updating the `ArrowSize` or `ArrowType` the `updateData()` function is now called. Without this the dimension would need to be recomputed to see the results.
* Changed `self.updateData(obj, "Start")` to `self.updateData(obj, None)` since the function ignores the `prop` argument.

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7453">pipeline status</a> for feature branch [PR_7453](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7453). Pipeline [632450934](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/632450934) was triggered at [c5a79d3](https://github.com/FreeCAD/FreeCAD/pull/7453/commits/c5a79d39090fa485691787079cfb31c57fc1db41). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7453">pipeline status</a> for feature branch [PR_7453](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7453). Pipeline [633819521](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/633819521) was triggered at [a71a062](https://github.com/FreeCAD/FreeCAD/pull/7453/commits/a71a06291b0f97586f908ace7a9286dc31d69e88). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Roy-043** [comment]
I have updated the PR the improve the alignment of flipped arrows. In the case of consecutive angular dimensions, flipped arrows should be coincident with neighboring non-flipped arrows.

**Comment by donovaly** [comment]
Is this something that could/should be backported? @Roy-043

**Comment by Roy-043** [comment]
This can be backported.

**Pull request merged**
