### PR TITLE
[Raytracing] Bugfix for compiling with OCC 7.6.x

### PR DESCRIPTION
**Pull request by Syres916**
See discussion https://forum.freecadweb.org/viewtopic.php?f=4&p=577109#p577109

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by chennes** [comment]
This looks fine to me, but since @donovaly is working on these includes I leave it to him to merge.

**Comment by donovaly** [comment]
Instead of the quite costly Base/Stream.h, does it work when you replace `<string>` by
`# include <sstream>` ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6518">pipeline status</a> for feature branch [PR_6518](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6518). Pipeline [485593470](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/485593470) was triggered at [2d5cccf](https://github.com/FreeCAD/FreeCAD/pull/6518/commits/2d5cccff5c55d82f5e1326b5e543a08f605f60ac). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Syres916** [comment]
Changing `# include <string>` to `# include <sstream>` does not work, produces the same error as quoted in the forum discussion. I specifically chose the change in this commit because I was following Werner's lead in the change he made to src/Mod/Raytracing/App/PovTools.cpp as part of https://github.com/FreeCAD/FreeCAD/commit/58a719e20719b5c4fbd5a86e20fa436b621b4ca2

**Comment by donovaly** [comment]
OK. Thanks for testing.  Merging now.

**Pull request merged**
