### PR TITLE
[NotificationArea] Sketcher: Constraint - notification and internal geometry command clean up

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
This is the first Sketcher package of conversion of intrusive notifications into the new framework, which provides intrusive or non-intrusive notifications depending on user preferences.

So far only for constraints.

In the same PR it also removes the deprecated framework of manual addition of internal geometries.

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
@donovaly 

This one would be good if you eventually have time to check if it links in Windows.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8863">pipeline status</a> for feature branch [PR_8863](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8863). Pipeline [803766150](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/803766150) was triggered at [1ff9dca](https://github.com/FreeCAD/FreeCAD/pull/8863/commits/1ff9dcac66321b02514c9da05f800ab8ba417908). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> This one would be good if you eventually have time to check if it links in Windows.

Compiles and links fine

**Comment by abdullahtahiriyo** [comment]
> Compiles and links fine

Thanks.

**Pull request merged**
