### PR TITLE
Add support for OCCT 7.8.0

### PR DESCRIPTION
**Pull request by bgbsww**
Also compiled and tests run against 7.7.2, 7.6.3, 7.5.2 and 7.3.0p4

Note that 7.7.2 has one anomalous test error at OpenSCADTest.app.test_ImportCSG.TestImportCSG test_import_resize that I have not explored since they run fine in the other 4 versions, including the one after this.

#9651 works with this.

### CODE REVIEW

**Comment by chennes** [comment]
Do you have time to check against 7.3?

**Comment by bgbsww** [comment]
Trying tag V7_3_0p4 from https://github.com/Open-Cascade-SAS/OCCT/tags?after=V7_5_0_beta.  Build cycle runs about 90 minutes, might be tomorrow before I see the results.

**Comment by ipatch** [comment]
can this cleanly be applied to the 0.21.2 release. trying to cook up a backport of this commit to make the homebrew-freecad tap work with the latest version of OCC. ie. v7.8.x as upstream homebrew-core updated OCC.

**Comment by bgbsww** [comment]
It should apply cleanly to 0.21.2.

**Comment by luzpaz** [comment]
An aside, it would be advantageous to coordinate with the KiCAD team to stay in parity regarding OCCT versions

https://twitter.com/mfraz74/status/1812384309438828890

**Comment by oursland** [comment]
@luzpaz Why?  How could this be beneficial?

**Comment by luzpaz** [comment]
There is a large demographic of users who leverage both FreeCAD and KiCAD in their workflow. KiCAD has OCCT as a dependency.

**Comment by oursland** [comment]
I am one of them, but have never encountered a situation in which different versions of OCCT has impacted my ability to interop between these two software packages.  I can still export models for use in KiCAD and import PCBs using KiCAD Step-Up.

I don't see how parity between these two packages improves things or what value it brings.

**Comment by ipatch** [comment]
@bgbsww 

more than likely i'm doing something wrong on my end, but with a fresh clone of freecad and checking out tag `0.21.2`, and then pulling in the PR as single patch file. ie. https://github.com/FreeCAD/FreeCAD/pull/11909.patch

which should redirect to,

https://patch-diff.githubusercontent.com/raw/FreeCAD/FreeCAD/pull/11909.patch

downloaded above such patch then attempted to apply the `.patch` to clone of freecad at the 0.21.2 tag, and i got the below error messages.

```
 git apply ../tmp/11909.patch
../tmp/11909.patch:243: trailing whitespace.

error: patch failed: cMake/FindOCC.cmake:164
error: cMake/FindOCC.cmake: patch does not apply
error: patch failed: src/Mod/Fem/Gui/TaskCreateNodeSet.cpp:28
error: src/Mod/Fem/Gui/TaskCreateNodeSet.cpp: patch does not apply
error: patch failed: src/Mod/Import/App/ImportOCAF.cpp:151
error: src/Mod/Import/App/ImportOCAF.cpp: patch does not apply
error: src/Mod/Import/App/Tools.h: No such file or directory
error: patch failed: src/Mod/MeshPart/App/CurveProjector.h:65
error: src/Mod/MeshPart/App/CurveProjector.h: patch does not apply
error: patch failed: src/Mod/Robot/Gui/PreCompiled.h:38
error: src/Mod/Robot/Gui/PreCompiled.h: patch does not apply
error: patch failed: src/Mod/Import/App/ImportOCAF.cpp:152
error: src/Mod/Import/App/ImportOCAF.cpp: patch does not apply
error: src/Mod/Import/App/Tools.h: No such file or directory
error: patch failed: src/Mod/MeshPart/App/CurveProjector.h:73
error: src/Mod/MeshPart/App/CurveProjector.h: patch does not apply
error: patch failed: src/Mod/Fem/Gui/TaskCreateNodeSet.cpp:28
error: src/Mod/Fem/Gui/TaskCreateNodeSet.cpp: patch does not apply
error: patch failed: src/Mod/Robot/Gui/PreCompiled.h:38
error: src/Mod/Robot/Gui/PreCompiled.h: patch does not apply
error: patch failed: src/Mod/Robot/Gui/PreCompiled.h:38
error: src/Mod/Robot/Gui/PreCompiled.h: patch does not apply
error: patch failed: src/Mod/Fem/Gui/TaskCreateNodeSet.cpp:28
error: src/Mod/Fem/Gui/TaskCreateNodeSet.cpp: patch does not apply
```

**Comment by ipatch** [comment]
and when i tried to use cherry-pick sub git command i get below errors.

https://github.com/FreeCAD/FreeCAD/commit/8abd09398a010337c3b294e687e0666b60bceacf

```
ipatch@cfarm104 ~/c/f/freecad-src-tmp (ipatch.builds.0.21.2-tmp) [128]> git cherry-pick 8abd09398a010337c3b294e687e0666b60bceacf
Auto-merging cMake/FindOCC.cmake
CONFLICT (content): Merge conflict in cMake/FindOCC.cmake
Auto-merging src/Mod/Fem/Gui/TaskCreateNodeSet.cpp
CONFLICT (content): Merge conflict in src/Mod/Fem/Gui/TaskCreateNodeSet.cpp
Auto-merging src/Mod/Import/App/ImportOCAF.cpp
CONFLICT (content): Merge conflict in src/Mod/Import/App/ImportOCAF.cpp
Auto-merging src/Mod/Import/App/ImportOCAF2.h
CONFLICT (modify/delete): src/Mod/Import/App/Tools.h deleted in HEAD and modified in 8abd09398a (Add support for OCCT 7.8.0 (#11909)).  Version 8abd09398a (Add support for OCCT 7.8.0 (#11909)) of src/Mod/Import/App/Tools.h left in tree.
Auto-merging src/Mod/MeshPart/App/CurveProjector.h
CONFLICT (content): Merge conflict in src/Mod/MeshPart/App/CurveProjector.h
Auto-merging src/Mod/Part/App/TopoShapePyImp.cpp
Auto-merging src/Mod/Part/Gui/AppPartGui.cpp
Auto-merging src/Mod/Part/Gui/Command.cpp
Auto-merging src/Mod/Part/Gui/CommandSimple.cpp
Auto-merging src/Mod/Part/Gui/CrossSections.cpp
Auto-merging src/Mod/Part/Gui/ViewProvider2DObject.cpp
Auto-merging src/Mod/Part/Gui/ViewProviderExt.cpp
Auto-merging src/Mod/Part/Gui/ViewProviderExt.h
Auto-merging src/Mod/Part/Gui/ViewProviderMirror.cpp
Auto-merging src/Mod/Part/Gui/ViewProviderPython.cpp
Auto-merging src/Mod/Part/Gui/ViewProviderReference.h
Auto-merging src/Mod/Robot/Gui/PreCompiled.h
Auto-merging src/Mod/Sketcher/Gui/EditDatumDialog.cpp
error: could not apply 8abd09398a... Add support for OCCT 7.8.0 (#11909)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
ipatch@cfarm104 ~/c/f/freecad-src-tmp (ipatch.builds.0.21.2-tmp|CHERRY-PICKING) [1]>
```

**Comment by bgbsww** [comment]
I am not a git expert, so I can't really help here.  To me, if you just take the first file in the list,  FindOCC.cmake, and look at what this patch PR changes, I can't see any reason why the right magic git incantation would not apply in cleanly.  Clearly the one you're using doesn't, but unfortunately the best I could do would be to suggest 'git abracadabra' and hope for the best.  Maybe someone with more git fu can weigh in.

**Comment by mfraser** [comment]
> I am one of them, but have never encountered a situation in which different versions of OCCT has impacted my ability to interop between these two software packages. I can still export models for use in KiCAD and import PCBs using KiCAD Step-Up.
> 
> I don't see how parity between these two packages improves things or what value it brings.

In Ubuntu 22.04 I'm using [FreeCAD](https://launchpad.net/~freecad-maintainers/+archive/ubuntu/freecad-daily) &  packages from their PPA [KiCAD](https://launchpad.net/~kicad/+archive/ubuntu/kicad-8.0-releases)

**Comment by oursland** [comment]
Thank you @mfraser, I have a better understanding of the issue.

I think this poses some challenges for FreeCAD. There's been discussion on forking OCCT to address bugs that are not being addressed upstream.  In that circumstance, even the same version number of OCCT may be incompatible.

The FreeCAD AppImage will not have these issues as it bundles these dependencies instead of installing them site-wide, which should provide a workaround for compatibility issues.

@adrianinsaval @chennes OCCT versioning could pose an issue for PPA releases.

**Comment by bgbsww** [comment]
> ... OCCT versioning could pose an issue for PPA releases.

Iff the PPA releases are dependent on the official OCCT package.  If they are made dependent on an alternate release of the forked OCCT that was released then both problems are solved at the cost of some mostly redundant space use.

**Comment by ipatch** [comment]
here is a patch file of these commits in this PR that successfully got to work with `git apply ...` and `brew install freecad` for the 0.21.2 release.

as mentioned above this PR would not cleanly apply to the tagged relase of 0.21.2 without resolving some of the files in a git mergetool.

i'm sitll building the 0.21.2 release of freecad on m1 box right now using macos, so hopefully this will complete with out any build errors, then i'll attempt to build on my local linux box using homebrew/linuxbrew.

https://raw.githubusercontent.com/FreeCAD/homebrew-freecad/13cff0680069fd9c564b17e7ea8d4f012d887c8a/patches/freecad%400.21.2_py310-backport-occ-v7.8.patch

did run a diff on the two different patch files to see what exactly the issue was, but i hope this helps someone else.

**Pull request merged**
