### PR TITLE
[For 0.19] Crowdin: continuing translation string refinements/fixes + Misc. typo/whitespace fixes

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Keeping for 0.19 okay? Trying to avoid delaying 0.18 any further.

**Comment by luzpaz** [comment]
@yorikvanhavre I'd respectfully argue that it would be relevant to slip in before release and then do one last pull and push for crowdin (since we pushed those recent translation fixes translators have worked on them).

**Comment by yorikvanhavre** [comment]
We always do backports when needed, that's not a problem. The problem here is more that everytime we push stuff to crowdin, translations that were at 100% drop below, and it takes weeks  before they reach 100% again... Let's do like this then: Let's keep this "frozen", add more fixes to this PR if you find more to fix, and we'll try to do one more round before the release. Is that okay for you?

**Comment by luzpaz** [comment]
@yorikvanhavre thank you that is a very good compromise. You bring up a good point for sure and I will be mindful of that. Cheers!

**Comment by luzpaz** [comment]
@yorikvanhavre do you mind running another crowdin push now ?

**Pull request merged**
