### PR TITLE
Color for arch drawing view

### PR DESCRIPTION
**Pull request by simsiem**
This feature adds two properties to ArchDrawingView: LineColor and FillColor (see attached screen shot). Thus it completes for ArchDrawingView what is already available for Draft's Shape2DView.

To realize this feature, ProjectionAlgos is extended to make the SVG styling accessible on the interface. User code can provide SVG attributes (key-value pairs) for each kind of line (V, V0, V1, H, H0, H1).

### Design decisions

- ProjectionAlgos: Offer style parameters for each kind of line. Alternatively: Maybe two kinds (e.g. V0 and V1 as well as H0 and H1) could be grouped to use only one set of style attributes.
- AppDrawingPy: Use keyed arguments on the Python interface of projectToSVG. There are too many arguments now.
- AppDrawingPy/ProjectionAlgos: Move the default values into one single module: ProjectionAlgos. Thus remove some defaults from AppDrawingPy.
- ArchSectionPlane: Add the new properties to objects from old files with onDocumentRestored (see https://forum.freecadweb.org/viewtopic.php?f=10&t=21891)
- ArchSectionPlane: Remove the placeholders from getSVG. With the changes to ProjectionAlgos, they are not necessary anymore.
- In the consequence, the following interface break: ArchSectionPlane::getSVG, AppDrawingPy - Module::projectToSVG, projectionAlgos::getSVG.

### Further notes

- I had to update FeatureViewPart to use the new interface of ProjectionAlgos. Did I do it right?
- Can someone review the code again to see whether I did break something?
- I tried to clean up some things. But I am very open to adjust the style if wanted.
- This is my first pull request to this project. Do not hesitate to push me that the pull request complies with your needs.

---

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [X] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

color_for_section_view

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I think your changes will make TechDraw's ArchView and DraftView break, since you changed the order of parameters in Draft.getSVG(). There might also be other modules out there that use that function. It is always wiser to append new arguments at the end, so old code still works. I'll look better at the other changes you propose in the Drawing algos.

**Comment by yorikvanhavre** [comment]
Ok I gave it a little test, the only argument order you changed is in ArchSectionPlane. getSVG, which is fairly recent and used with correct keywords everywhere, so the change of argument order has no consequences, and I don't think it is used outside the FreeCAD source code yet. So this looks ok to merge.

The reason for the placeholders was that some operations wouldn't require a complete recalculation of the SVG projection, for ex. if you just changed the color, no new call to getSVG was necessary, but this has been abandoned since quite some time...

Too bad you didn't adapt TechDraw's DraftView and ArchView!

This is now merged

**Comment by wwmayer** [comment]
It turned out that this PR breaks the line width of a drawing, see here: https://forum.freecadweb.org/viewtopic.php?f=13&t=23621

**Comment by wwmayer** [comment]
Fixed in 8659302

**Pull request closed without merging**
