### PR TITLE
Tempovis stack

### PR DESCRIPTION
**Pull request by DeepSOIC**
# Improvents:
* global stack for each document, where we can scan existing TempoVis instances
* Thanks to the stacking, using several tempovis instances in arbitrary order becomes possible.
* plugin system (SceneDetail), ease of extending, 
* Mild restore feature - more respect for changes made by user
* workbench switching support
* undo saveable changes for the time of writing a file
* added EditingWorkbench property to ViewProviderSketch, to allow changing the workbench that gets activated when opening the sketch. ([this is why!](https://forum.freecadweb.org/viewtopic.php?f=10&t=25945))
* Sketcher New Sketch now won't change camera zoom for every new sketch being created ([discussed here](https://forum.freecadweb.org/viewtopic.php?f=8&t=39034))

## Mild restore:
the best example is workbench switching. When opening sketch for editing, Sketch used to save current workbench into a temporary variable, and restore it later when the sketch is closed. This is good, except I sometimes switch to another workbench before closing the sketch (forgetting). Then, when I close the sketch,  suddenly workbench switches to the one I had open when opening the sketch (which is usually Sketcher). Mild restore checks if user is still on sketcher, before switching back. Same is supported on viewprovider properties. 

## Undo for writing files:

This was causing problems with Part-o-magic x-ray tool (which I plan bringing to FC soon). X-ray is meant to remain on for long times. x-ray is a combination: change display mode to shaded, make object transparent, and make unpickable. When saving a file with anything x-rayed, the transparency and display mode would be saved, but pick style wouldn't. Then, opening the file, I find an object looking like it's x-rayed, but selectable, and x-ray button won't restore it back to normal display. 

Tempovis will now undo all changes that affect saving, for the time while file is being written, and redo them back when it's finished. So the object will be saved in its regular (non-xrayed) state.

# Regressions:
* Removed support for pickling TempoVis (with hopes to reintroduce later)

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Although it touches the sketcher, the changes there are very few, and there are no objections to it on the forum... So I'll merge

**Comment by DeepSOIC** [comment]
thanks =)

**Comment by wwmayer** [comment]
For some days I reliably get a crash in debug mode when I close sketch editing. In release mode sometimes it works and sometimes I got this output:

TempoVis.restore: failed to restore detail ('SDWorkbench', None, 'workbench'): PartDesignWorkbench: Access violation

The issue is caused by this change 47ba2c00da2e which when I locally undo fixes the crash.

In debug mode the crash always happens inside QStyleSheetStyle::repolish() where the style sheet is applied to all children of the passed widget because one (or more) of it is being destroyed.

So the actual problem with the new behaviour is that we close the task panel while changing the workbench while with the old behaviour we first closed completely the task panel and then changed the workbench.

**Comment by wwmayer** [comment]
I have opened a forum topic and added the call stack there.

**Pull request merged**
