### PR TITLE
[PD] add missing include to get rid of MSVC error

### PR DESCRIPTION
**Pull request by donovaly**
since I while I got an "unknown warning" when compiling PD, despite the compilation succeeds.
Today I realized that MSVC cannot find App::PropertyVector.
With this PR the problem is resolved.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5353">pipeline status</a> for feature branch [PR_5353](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5353). Pipeline [443882264](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/443882264) was triggered at [304eaaa](https://github.com/FreeCAD/FreeCAD/pull/5353/commits/304eaaad456bfa633935965a304390d057c3eee9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
For which source files do you get the failure? Or for which class it cannot find PropertyVector? 

It's odd that the compiler apparently cannot find App::PropertyVector for the classes where you added the include because the compiler should be able to find them.

For example: FeatureExtrude.h > FeatureSketchBased.h > Mod/Part/App/Part2DObject.h > Mod/Part/App/PartFeature.h > App/PropertyGeo.h The same you have for FeatureGroove.h, FeatureHelix.h and FeatureRevolution.h.

**Comment by donovaly** [comment]
I get `PCH warning: an unknown error occurred.  An IntelliSense PCH file was not generated.`
So it is pure MSVC. 
Please close this PR if we should not add includes just to please a certain compiler.

**Comment by donovaly** [comment]
Closing since this is a special MSVC issue and should therefore made it into the main code.

**Pull request closed without merging**
