### PR TITLE
Issue #7510 - rectified transparency in importOBJ.py

### PR DESCRIPTION
**Pull request by Hubhubhurra**
Now export and import shows correct transparency

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7512">pipeline status</a> for feature branch [PR_7512](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7512). Pipeline [646443645](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/646443645) was triggered at [3c7782b](https://github.com/FreeCAD/FreeCAD/pull/7512/commits/3c7782b1273232934c52f3b225403a27ccace3a8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7512">pipeline status</a> for feature branch [PR_7512](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7512). Pipeline [646718761](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/646718761) was triggered at [49e37dd](https://github.com/FreeCAD/FreeCAD/pull/7512/commits/49e37dd611ef5093b4084720ace7c5d963ccf7c9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Wrong branch my dude. Need to make the PR against master not toponaming. Please close and try again

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7512">pipeline status</a> for feature branch [PR_7512](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7512). Pipeline [647103192](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/647103192) was triggered at [9e1ed4a](https://github.com/FreeCAD/FreeCAD/pull/7512/commits/9e1ed4a68ad43309c2b38f7f5efbb1feac4323cb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Try again, but cherrypick your changes on the correct branch. Closing.

**Pull request closed without merging**
