### PR TITLE
improve search for VTK-9

### PR DESCRIPTION
**Pull request by waebbl**
Improve the find_package calls with vtk-9 cmake config files.
In this version, the variable VTK_MODULES_ENABLED has been
replaced by VTK_AVAILABLE_COMPONENTS.

The additional change of the components names, which have their
'vtk' prefix removed in vtk-9 is not covered by this patch for
compatibility reasons.

See the forum thread noted below for a description of this:
https://forum.freecadweb.org/viewtopic.php?f=4&t=60068

Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
> This request is only for configuring against VTK-9, compilation succeeds on my tests, if the patch from @wmayer is applied.

Quoted from the forum thread. Assigning to wmayer

**Comment by luzpaz** [comment]
Just a heads up to the packagers that this is in the pipeline

@apeltauer (Windows)  

@greyltc (Arch)  
@looooo (Conda)
@kkremitzki (Debian)
@hobbes1069 (Fedora)  
@PrzemoF (Fedora Copr)  
@adrianschroeter (openSUSE)

**Comment by hobbes1069** [comment]
Fortunately I could apply this PR as a patch to 0.19.2 and it built fine.

```
$ rpm -qp --requires ./results_freecad/0.19.2/1.fc36/freecad-0.19.2-1.fc36.x86_64.rpm | grep vtk
libvtkCommonCore.so.1()(64bit)
libvtkCommonDataModel.so.1()(64bit)
libvtkCommonExecutionModel.so.1()(64bit)
libvtkFiltersCore.so.1()(64bit)
libvtkFiltersExtraction.so.1()(64bit)
libvtkFiltersGeneral.so.1()(64bit)
libvtkFiltersGeometry.so.1()(64bit)
libvtkFiltersSources.so.1()(64bit)
libvtkFiltersVerdict.so.1()(64bit)
libvtkIOCore.so.1()(64bit)
libvtkIOLegacy.so.1()(64bit)
libvtkIOXML.so.1()(64bit)
```

**Comment by looooo** [comment]
trying to build current master with this commit:
https://github.com/looooo/freecad-feedstock/runs/3388068263

**Comment by luzpaz** [comment]
> trying to build current master with this commit:
> https://github.com/looooo/freecad-feedstock/runs/3388068263

```
Applying patch: D:\a\1\s\recipe\vtk_cmake.patch
Applying patch: D:\a\1\s\recipe\vtk_cmake.patch with args:
['-Np1', '-i', 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpt_8amfqj\\vtk_cmake.patch.native', '--binary']
checking file cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake
Hunk #1 FAILED at 27 (different line endings).
1 out of 1 hunk FAILED
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['D:\\bld\\freecad_1629527103755\\_build_env\\Library\\usr\\bin\\patch.exe', '--no-backup-if-mismatch', '--batch', '-Np1', '-i', 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpt_8amfqj\\vtk_cmake.patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
Failed to download or patch source. Please see build log for info.
##[error]Cmd.exe exited with code '1'.
```

**Comment by waebbl** [comment]
> Hunk #1 FAILED at 27 (different line endings).

I have this issue too sometimes, when applying patches made on mac or windows. Sadly I know of no way to create a _unified_ patch, usable on win, mac and linux platforms. I'm converting the line endings using `dos2unix` before applying such patches, if they fail, but that's with a manual workflow.

**Comment by looooo** [comment]
> > Hunk #1 FAILED at 27 (different line endings).
> 
> I have this issue too sometimes, when applying patches made on mac or windows. Sadly I know of no way to create a _unified_ patch, usable on win, mac and linux platforms. I'm converting the line endings using `dos2unix` before applying such patches, if they fail, but that's with a manual workflow.

yes, this happens some times. I will make another patch for windows and try again. Frustrating...

**Comment by yorikvanhavre** [comment]
Merging now to let people test. Let's keep an eye open for problems!

**Pull request merged**
