### PR TITLE
[For v0.19]Backup files policy

### PR DESCRIPTION
**Pull request by plgarcia**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

Improvement of saves:
-	Handling configuration changes (increasing reducing the number of backups, switching backup, …)
-	Changing the naming of the backup with the timestamp instead of numbers.
-	Hopefully solves errors on Google Drive.
See Forum :
https://forum.freecadweb.org/viewtopic.php?f=8&t=25601

### CODE REVIEW

**Comment by plgarcia** [comment]
Changed in one commit but identical

**Comment by plgarcia** [comment]
Is there any objection or comment for this PR ?

**Comment by yorikvanhavre** [comment]
I prefer the way backup files are now, it keeps things much cleaner IMHO. My opinion is that if you want to implement this, it should be optional and not mandatory.

**Comment by plgarcia** [comment]
OK there are two things in the PR.
Everything around solving issues:
- Maintaining the right number of archives when changing the configuration
- Reporting to the user when a problem occurs

Changing the naming policy of the backups.

I will make the naming policy selectable. I have to think about that.

**Comment by yorikvanhavre** [comment]
Ok I just gave it a test, for me it is OK now, it runs nicely, you can switch between the two systems, etc...
@wwmayer I'll wait for you to have a look, if you don't mind...

**Comment by plgarcia** [comment]
Has somebody mentionned that since a few days all builds on OSX fail (a problem on installation of doxygen if I understand well).

**Comment by wwmayer** [comment]
No, it's not doxygen but it was boost. Since version 1.67 it doesn't work any more to search for the package python. It must now include major and minor version, e.g. python27. This issue was fixed yesterday.

**Comment by yorikvanhavre** [comment]
This PR is more than one year old and IIRC it was made to respond a google drive problem... Is it still an issue? Should we reconsider merging it? Honestly I'm a bit uneasy with it because it changes a lot of stuff in the file saving system which might potentially bring bugs... So close to the release it might be a bad idea, even  more if it's not fixing anything critical. Or we reschedule it for 0.19?

**Comment by plgarcia** [comment]
The PR proposes also a policy in the naming of the different archives.

It also makes the sofware resilent to file system issues (archive locked for whatever reason, unability to erase an archice, ...).

 

these 2   reasons are good enough to take the PR.

 

Google solved the problem obviously, and I did not entcunter the problem since many month. But who can ensure other software do not introduce this kind of issure (dropbox, onedrive, anti-virus, ...)

 

It has been tested ot only by me, and the change is quite well located in the code.

 

Do whatever you want!

 

 

> Message du 16/02/19 22:44
> De : "Yorik van Havre" 
> A : "FreeCAD/FreeCAD" 
> Copie à : "Pascal Garcia" 
, "Author" 
> Objet : Re: [FreeCAD/FreeCAD] [For v0.18]Backup files policy (#1148)
> 
>
> This PR is more than one year old and IIRC it was made to respond a google drive problem... Is it still an issue? Should we reconsider merging it? Honestly I'm a bit uneasy with it because it changes a lot of stuff in the file saving system which might potentially bring bugs... So close to the release it might be a bad idea, even more if it's not fixing anything critical. Or we reschedule it for 0.19?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeCAD/FreeCAD","title":"FreeCAD/FreeCAD","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeCAD/FreeCAD"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yorikvanhavre in #1148: This PR is more than one year old and IIRC it was made to respond a google drive problem... Is it still an issue? Should we reconsider merging it? Honestly I'm a bit uneasy with it because it changes a lot of stuff in the file saving system which might potentially bring bugs... So close to the release it might be a bad idea, even more if it's not fixing anything critical. Or we reschedule it for 0.19?"}],"action":{"name":"View Pull Request","url":"https://github.com/FreeCAD/FreeCAD/pull/1148#issuecomment-464388838"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/FreeCAD/FreeCAD/pull/1148#issuecomment-464388838", "url": "https://github.com/FreeCAD/FreeCAD/pull/1148#issuecomment-464388838", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by plgarcia** [comment]
I have been rebasing the PR may be 50 times until I gave up. The PR is 1 year and 4 month old.
Now there is a conflict, not complex to sole, I do not understand even why Git does not resolve it by itself.
OK I will solve that conflict, I will rebuild under Windows and retest it, building under linux and retest it also.
I am ready to do that, but my question is is it worth the effort. I think the change is of interest:
- it avoid conflicts with whatever software (Anti virus, ...) would lock an archive and avoid an archive to be deleted (do not tell me it never happens under windows at least)
- it allows to choose the extention of the archives and he name of the archives can be sorted by age.
- if a hardware or software problem occurs FreeCD cannot cope with despite the different measures I put in place, the user is warned (today he does not even know and then may loose his work, do not tell me it does not happen I had the case what is the original reason of this change, the other features being added opportunely)

Tell me if I make this effort the PR will be considered and will not wait an extra 1.5 years until next release, and again and again.

Regards

**Comment by wwmayer** [comment]
> Tell me if I make this effort the PR will be considered and will not wait an extra 1.5 years until next release, and again and again.

No need to put more effort into that. Most of the PR has become obsolete in the meantime anyway and for the part of the PR that can be integrated some refactoring work of FreeCAD must be done beforehand. There I plan to split the code for the backup creation to its own class so that it will be much easier to support different strategies.
But at the moment this is of low priority as I am busy to set-up the new infrastructure for the v0.19 development.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
