### PR TITLE
Add rocket workbench addon

### PR DESCRIPTION
**Pull request by davesrocketshop**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
@davesrocketshop Nice!  One thing: save your file as a 'Plain SVG' rather than the 'Inkscape SVG' that Inkscape defaults to. The Inkscape SVG file type will include extraneous data that will not be necessary.
File > Save as > Choose `Plain SVG`   
https://wiki.inkscape.org/wiki/index.php/Inkscape_SVG_vs._plain_SVG

**Comment by wwmayer** [comment]
Merged as plain SVG.

**Comment by luzpaz** [comment]
@davesrocketshop congrats! Please make a PR to [FreeCAD-addons](https://github.com/FreeCAD/FreeCAD-addons/) repo so we can download via the Addon Manager

**Comment by luzpaz** [comment]
@davesrocketshop nvm, Rocket is now in Addon Manager :stuck_out_tongue_winking_eye: 
https://github.com/FreeCAD/FreeCAD-addons/commit/078447fc07cef6475bf500981f3c0ba3f83eb8db

**Pull request closed without merging**
