### PR TITLE
New integration with 3Dconnexion devices

### PR DESCRIPTION
**Pull request by pskowronskiTDx**
The following changes set introduces a refined integration with 3Dconnexion devices.

### CODE REVIEW

**Comment by chennes** [comment]
Thanks to 3DConnexion for adding contributing this development -- I'm sure our Spacemouse-using Windows users will appreciate it.

At first glance it looks like an ideal candidate to be a git submodule rather than a direct source inclusion in the FreeCAD tree. Did you consider that approach?

**Comment by pskowronskiTDx** [comment]
I didn't consider this but I think it makes sense. Would you like to see all of the new sources being linked as a submodule in existing Gui/3Dconnnexion directory?

**Comment by chennes** [comment]
I was thinking of the set of files in 3rdParty -- we've been discussing moving the other stuff in there into submodules, so this would be a first step in that direction. That said, I'm not wedded to any particular organization scheme.

**Comment by 3x380V** [comment]
It is a bit unfortunate to introduce yet another OS specific interface. A lot of `NavlibInterface` looks pretty generic, but is bound with that 3DConnection driver. Whoever needs also Linux support will need to start implementing generic interface and trying not to break Windows and MacOS support. It is pretty hard as it is, with this patches applied it becomes even harder. Unless, of course, it is acceptable to write Linux specific stuff and put it under #ifdef ;-)
I can implement Linux side if there is a will to cooperate.

**Comment by pskowronskiTDx** [comment]
@chennes Let's keep current scheme of the changes then. Once you are convinced about changing the organization scheme of the FreeCAD's repository to be more submodule based, then I will reorganize the integration sources.

**Comment by chennes** [comment]
OK, that sounds fine. Let me reach out so some Windows SpaceMouse users to see if they can test this in its current state (alas, my SpaceMouse is trapped in an inaccessible building at the moment!)

@3x380V my recollection from last time I worked on this is that the SpaceMouse stuff is _always_ tied to the 3DConnexion driver, on all OSes. Is that not the case on Linux? It was on my Mac at any rate. And I agree that it is unfortunate that this is Windows-only, but might it provide a framework for eventual extension to support Linux and MacOS?

**Comment by adrianinsaval** [comment]
On Linux libspnav is used IIRC, which is an open source implementation

**Comment by daskygit** [comment]
Hi, what's the limitation for this not working with MacOS?  

With a couple of quick tweaks and a little testing, it almost looks as if it's working albeit there's no response in FreeCAD to SpaceMouse inputs. But the Navlib library loads and it seems happy to write commands without error.

**Comment by pskowronskiTDx** [comment]
By the way, I am struggling with building FreeCAD on M1 Mac as an .app bundle using conda environment. The build itself goes fine but the install step fails because it cannot find some dependencies in .conda/libexec etc. Can you please provide any hints on that issue?

**Comment by chennes** [comment]
@oursland or @adrianinsaval do you have any Conda compilation insight here?

**Comment by adrianinsaval** [comment]
> By the way, I am struggling with building FreeCAD on M1 Mac as an .app bundle using conda environment. The build itself goes fine but the install step fails because it cannot find some dependencies in .conda/libexec etc. Can you please provide any hints on that issue? 

Would you explain what procedure you are following and what specific errors you are getting

**Comment by oursland** [comment]
I have not done any work on `.app` bundling.  My efforts thus far have been to establish a build-test environment only.

I do want to get `.app` bundling functioning and documented under the conda environment, but I am in the final stages of my MSEE degree and need to focus on my thesis and cannot spare time.

**Comment by pskowronskiTDx** [comment]
@adrianinsaval I am following the procedure provided by @oursland: https://github.com/oursland/FreeCAD-Build-Notes. In term of Debug/Release build, everything goes well. The procedure fails during install step, when I am getting an error saying that some of the files to be bundled cannot be found in .conda environment.
@oursland Ok, I understand. Thank you for the information. Well, until we are unable to build complete .app bundle on our end, we unfortunately cannot continue with the investigation of the Mac solution.

**Comment by oursland** [comment]
@pskowronskiTDx Is running from a `.app` bundle necessary?  I have been using a 3Dconnexion SpaceTraveler by running the `./build/debug/bin/FreeCAD` binary from a build.

**Comment by pskowronskiTDx** [comment]
@oursland It is preferred, yes. I took another look this week and there may be something else going on, which causes the application not responding to the input. I will keep working on that. 

For now we can deliver the solution for Windows only.

**Comment by 3x380V** [comment]
@chennes, indeed [Spacenav](https://github.com/FreeSpacenav/libspnav) is used on Linux. As it stands now, Linux, MacOS and Windows does not share too much code and spacemouse behaves differently on each OS. The new implementation does make it any better and things seems to stand upside down. Instead of FreeCAD providing abstract interface class which each OS derives and fills with appropriate methods, it is 3Dconnexion's navlib as a centre around which everything revolves. If a read the code incorrectly, please correct me. As a side note, here's branch with minor tweak to pull request: https://github.com/3x380V/FreeCAD/tree/tdx-integration - squashes original commits as following ones just fixes previous one, so there is no point to merge them separately.

**Comment by chennes** [comment]
@3x380V It sounds to me from the preceding discussion that we will eventually be able to unify the MacOS and Windows support using this new contribution, once the Mac driver problems are resolved. So it is not at all clear to me that this submission makes anything *worse*, and it almost certainly makes Windows support better right now, and will eventually make Mac support better.

It's tough to get any meaningful testing from users until this is available in a Weekly, so my inclination is to merge this. Let's discuss it at next Monday's PR review meeting.

**Comment by 3x380V** [comment]
@chennes, please do not get me wrong, I'm not against merging this PR (but please take a look at my branch where few things are fixed; in ideal world all those additional commits should be squashed into single commit). I'm just saying it makes further unification more difficult as it diverges more from common interface (current version at least pretends to care about other OS).
I will continue to work on cleaning Linux spnav. In fact, if Windows and MacOS moves to this new interface, it will make life easier - then we can have Linux based on spnav and Windows and MacOS based on libnav.

**Comment by 3x380V** [comment]
@pskowronskiTDx, could you elaborate a bit more about this PR? It seems Mac users have two options. Either use proprietary implementation which this PR is adding support for or [Spacenav Project](https://github.com/FreeSpacenav). They get completely different user experience based on implementation compiled in. This implementation seems to completely ignoring GUIApplicationNativeEventAware class and does all things on its own. This is pretty strong argument to put it into git submodule before the rest gets merged.
@chennes, above answers your question how does this implementation making things worse. It simply ignores everything already done. Author so far show no will to care about other platforms, so it is dead end for Linux at least.

**Comment by pskowronskiTDx** [comment]
@3x380V You are right. The NavLib integration does not use GUIApplication classes anymore. The implementation in PR is meant to support both Mac and Windows, and the issue we are facing on Mac was not expected. At the moment, there is no option to build FreeCAD on Mac/Linux with NavLib navigation. For these platforms the previous solution is used.  On Windows there are two build options to enable support for 3Dconnexion devices, either with NavLib or SpNav code. We would like to do the same for Mac once we have the PR implementation fixed there. The previous code will be ignored only if NavLib build option was selected (available only on Windows at the moment).

**Comment by chennes** [comment]
@pskowronskiTDx I notice that the directory you've added to 3rd Party is spelled with a capital "C" -- I assume that is actually a typo, and a lowercase "c" was intended?

**Comment by pskowronskiTDx** [comment]
@chennes Thank you for catching this. Of course, I did a typo here. It should be 3Dconnexion.

**Comment by chennes** [comment]
Thanks, I'll fix on merge. Another question: is the FREECAD_USE_3DCONNEXION_NAVLIB option supposed to be used *with* FREECAD_USE_3DCONNEXION, or *instead of* FREECAD_USE_3DCONNEXION?

**Comment by 3x380V** [comment]
@pskowronskiTDx, thank you for clarifying. SpNav code has a few glitches anyway, so I do not think it makes sense to still support it, as Navlib solution seems superior to it. I'll try clean Linux code once this gets merged. It is of course using SpNav, but not having to care about breaking other platforms is helpful itself.
@chennes, looks good to me, feel free to squash, rebase and merge :-)

**Comment by chennes** [comment]
My system is showing that directory with a lowercase name in all places (including the name of the directory), and that appears to be what GitHub is showing as well. Where are you seeing it capitalized?

**Comment by 3x380V** [comment]
Gah, indeed. I failed to apply commits properly. Sorry for the noise.

**Comment by pskowronskiTDx** [comment]
@chennes Thank you for merging the PR. As we keep looking into a Mac solution, we would like to exclude any possible architectural causes of the issue we are facing on this platform. Is it possible for you to provide a custom Mac build (both x86 and x64) of FreeCAD with the NavLib integration enabled (just a little tweak in CMake file needed)? I am unable to build it by myself under x86 architecture and  this conda environment for arm64 seems to be a work in progress.

**Comment by oursland** [comment]
@pskowronskiTDx The [weekly builds](https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds) were made two days ago, after the merge of these changes and should include this work.

**Comment by pskowronskiTDx** [comment]
@oursland For MacOS/Linux these changes are hidden at the moment. As I noted I need a custom build (built with one CMake option modified).

**Comment by carlospsa** [comment]
Hi,
Starting with 0.22.0dev.36874 (Git) version my old "SpaceBall 5000 USB " has stopped working.

it is not detected by FC.

Thank you.

<code>
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36874 (Git)
Build type: Release
Branch: main
Hash: a4dd600ec6d5a53a9960cd9f8693d7d307b9e359
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Spain (es_ES)
Installed mods: 
  * A2plus 0.4.64
  * Curves 0.6.30
  * fasteners 0.5.17
  * Help 1.0.3
  * Render 2024.1.23
  * sheetmetal 0.4.11
 </code>

**Comment by ngo3dx** [comment]
> Hi, Starting with 0.22.0dev.36874 (Git) version my old "SpaceBall 5000 USB " has stopped working.
> 
> it is not detected by FC.

The SpaceBall 5000 USB was [discontinued](https://3dconnexion.com/uk/support/faq/3dconnexion-discontinued-devices/) in late 2009. The required driver API for the new solution requires version 10.5.6 (released early 2018)  or newer of 3DxWare 10.

**Comment by andreymrt** [comment]
@chennes @pskowronskiTDx I think this pull request needs a lot more testing before a merge into master.
Relying on the 3DX config window as you suggested in issue #13801, setting Zoom direction to "Up/Down" does not result in the expected behavior.
Instead of the model zooming in/out, it just pans in screen Y axis as if nothing changed. Deactivating axes in the config window also has no effect.
Restarting FreeCAD between changing 3DX settings has no effect.
Restarting 3DX has no effect.


Screen cap:

https://github.com/FreeCAD/FreeCAD/assets/1222366/74856d7d-fe31-46d1-af27-678e9af1a7ca

Can someone confirm whether or not you experience the same behavior in the latest build?

FreeCAD
```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37302 (Git)
Build type: Release
Branch: main
Hash: 0e24e121eb3e5708c380596e0a9fd583befac977
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods:
  * Help 1.0.3
```

3DxWare
```
3DxWare 10.8.20.3729
3DxWinCore 17.8.20.20889
```

To further check driver behavior, when using KiCad 8.0.2, 3DX works fine.
And deactivating axes in the config window does indeed limit the movements affected in the 3D viewer.
So I think we can rule out an issue with the driver.

**Comment by chennes** [comment]
This has been merged, so you should copy this post into a new issue so it doesn't get lost here.

**Comment by andreymrt** [comment]
@chennes, moved to #14044 as you recommended

**Comment by dewi-ny-je** [comment]
> Thanks to 3DConnexion for contributing this development -- I'm sure our Spacemouse-using Windows users will appreciate it.

But will they? I mean, FreeCAD allowed people with low budget to use second-hand, perfectly working devices. Now newer ones are better supported, and older ones dropped completely, out of the blue?? (requiring compilation with a different setting is practically equivalent to dropping support, unless you provide the binaries).

Now a hobbyist has to spend not less than 150 Euro or dollars to get a second hand, working device. Not exactly entry-level I would say.

Please reconsider and allow both interfaces to coexist, so that both users of older devices and users of newer ones can enjoy the most out of FreeCAD.

**Comment by 3x380V** [comment]
@dewi-ny-je, as development was sponsored by 3Dconnexion, there is obviously an interest to sell more devices, so what you wish for is unlikely to happen. I'd recommend to open separate issue for that in hope someone will volunteer to do the job.

**Comment by dewi-ny-je** [comment]
@3x380V  I understand, but let me summarise it to clarify my surprise better:
- a working solution was available. Were there issues? this PR does not link to any recorded one on Github, and it does not mention any issue it's trying to solve in the initial commit. I follow several projects (out of interest) and this is definitely unusual.
- a party with an economic interest behind proposes a change which will maybe improve support for latest devices, but ... completely drops for older ones. Isn't this like... sabotage? (de facto, not necessarily meant to be in bad faith by @pskowronskiTDx ). If not, this is for sure a regression.
- the maintainer(s) don't even try to ask this party to combine the best of both worlds (I never dug into FreeCAD source, but is maybe an if statement to pick an interface based on the USB ID possible?), the change is just approved. Like that.

Well... support for outdated hardware is indeed routinely dropped, I saws it several times around, but it is done when supporting it would cause a continuous effort, not justified anymore. In this case the old devices WORK ALREADY, the proof is that just recompiling to activate the old approach just requires a different setting.

I'll try to advertise this issue to find someone willing to combine old and new interfaces at runtime, but I am definitely disappointed. I mean, right now FreeCAD seems to be in practice used more by hobbyists than large companies, so this change directly affect (the small fraction of Spacemouse users of) the predominant user base!

Can @chennes clarify why a combination of both approaches was not even requested to the developer as requirement to merge this "refinement"? Maybe some convincing argumentation would have been provided and the result would have been the same, but not asking at all seems like a breach of duty.

**Comment by 3x380V** [comment]
@dewi-ny-je, when this PR appeared, I though it will replace previous 3Dconnexion support on Windows and Mac, so I can fix it for Linux without fearing to break other platforms. It did not happen and it seems it cannot happen without dropping older hardware. So unless someone willing to cooperate and do the Windows and Mac part, I lost interest. I'm curious whenever you'll find someone willing to fix it - just open the issue and lets see :)
(as for your 3 points list, FreeCAD does not use feature branches nor subsystem based development, so sometimes code is merged based on some overall issue and later left in void without fulfilling initial goal)

**Comment by dewi-ny-je** [comment]
@3x380V  I appreciate you replying and explaining, thanks. Unfortunately you are the only one so far who did it.

Well, it seems I can only open a ticket (hoping there is no automatic marking of stale ones) and see. At least it's recorded.

Then I'll have to fork and then spend several hours (as inexperienced user) and several GB to install MSVC 2022 and compile FreeCAD with the other compile-time option active. 

And I'll be sure to publish it for people to avoid duplicating this effort.

I hope the old interface won't be dropped altogether from the source, but since it's used on Linux, hopefully it won't (can you confirm/reassure me?).

**Comment by 3x380V** [comment]
@dewi-ny-je, the original interface is based on 3dxserv and Linux is using a free alternative [Spacenav](https://spacenav.sourceforge.net/). As it stands now, no other alternative exists for Linux.

**Comment by al-ai-alt** [comment]
I run FreeCAD 0.2.1.2 and I am also trying FreeCAD 1.0.0RC2.

And on both versions my 3DCONNEXION SpaceMouse Wireless (P/N 3DX-600044) works on both, but works better on FreeCAD 1.0.0RC2, whereas on 0.2.1.2 if I have the cursor in the drawing pane it is erratic as hell, om version 1.0.0RC2 it is smooth motion.

So hopefully you're problem has been solved.

**Comment by MadMark13** [comment]
I agree, being someone that extensively uses both newer and older devices.  3Dconnexion has been running this game for a long time, the hardware is very robust, and this update cycle is one of the few things driving some of their sales.  
I've a box full of older devices at work that the 3dx drivers refuse to use.  A couple of our packages (CATIA being one) don't even use the 3dx drivers on Win10.  I use the devices extensively (pan/zoom/etc) to help with my RSI, and wouldn't do without them.  Once you figure out their customizations for other apps, it's pretty useful.  Except for the forced obsolescence bit.

dewi-ny-je, I look forward to your published fork with the older device support.

**Comment by MrFaul** [comment]
Why did you have to do that?  
The Connexion win driver suit is atrocious... and I was happy that I don't have to use it.

I get it, it is normal that someone's Workflow gets broken with every major update.  
But just shoving that into everyones face without notice and alternative is MS tactics.

But this is a chance to add native Gamepad/Joystick support with a FreeCAD native GUI to it.  
Because I think this long overdue.  
I know there are scripts for that, but thats hardly user friendly.

**Comment by dewi-ny-je** [comment]
> Why did you have to do that? The Connexion win driver suit is atrocious... and I was happy that I don't have to use it.
> 
> I get it, it is normal that someone's Workflow gets broken with every major update. But just shoving that into everyones face without notice and alternative is MS tactics.
> 
> But this is a chance to add native Gamepad/Joystick support with a FreeCAD native GUI to it. Because I think this long overdue. I know there are scripts for that, but thats hardly user friendly.

The official 3dconnexion driver works pretty well actually. If you don't like its interface that's another issue freecad devs likely care little about.

A user explicitly reported issues with the built-in legacy interface which disappeared with the newer one, based on the official drivers.

Gamepad and joystick is off topic in this ticket.

**Comment by dewi-ny-je** [comment]
> dewi-ny-je, I look forward to your published fork with the older device support.

Unfortunately I'm using lately way more fusion 360 and solidworks, so I'm not sure I'll spend time to compile freecad. Also someone is currently trying to allow free as to work with both interfaces, so it might not be needed. Check tickets opened by me.

If I were to use freevad extensively in the future I would either build a spacemouse clone (there's a project by adamHH which is recognised as a genuine space mouse!) or I would get a second hand space mouse, I was already able to find a second hand one for 70 euro which I gave away as present, while I kept my space pilot for myself (I like the buttons).

**Pull request merged**
