### PR TITLE
Gui: Fix document tree background rendering with overlay (Qt6)

### PR DESCRIPTION
**Pull request by kadet1090**
> [!WARNING]  
> I don't have ability to build FreeCAD with Qt5 right now. So I need someone to test if this solution works with Qt5. To test it use patched OpenLight: https://github.com/obelisk79/OpenTheme/pull/30
>
> You can checkout it from your `~/.local/share/FreeCAD/Mod/OpenTheme` directory using:
> ```
> git fetch origin pull/30/head:qt6-workaround
> git checkout qt6-workaround
> ```

This aims to fix rendering of tree view items in Qt6. While I don't belive that this is a good way to fix this, I am worried that it is the only way to do it.

**BC BREAK:** This change introduces artificial QTreeView widget that can be targeted using QSS and can be used in the delegate for painting background of items. `QTreeView::item` would now be used to render background for the whole row, while each cell can be targeted using `#DocumentTreeItems` selector.

I managed to find a hacky solution to this problem. To disable rendering of the background I can abuse this if statement in Qt:
```
        // For compatibility reasons, QTreeView draws different parts of
        // the background of an item row separately, before calling the
        // delegate to draw the item. The row background of an item is
        // however not separately styleable through a style sheet, but
        // only indirectly through the background of the item. To get the
        // same background for all parts drawn by QTreeView, we have to
        // use the background rule for the item here.
        if (renderRule(w, opt, PseudoElement_ViewItem).hasBackground())
            pseudoElement = PseudoElement_ViewItem;
```

So disabling background for `::item` disables rendering of branches and not-wanted background (I'm using qtsass):

```css
  QTreeView::item {
    &, &:selected, &:hover {
      background: none;
      border: none;
    }
  }
```

This however denies me from defining background in qss. But as a workarond I create artificial QTreeView widget inside the delegate with some well defined object name, `DocumentTreeItems` in my case:

```cpp
TreeWidgetItemDelegate::TreeWidgetItemDelegate(QObject* parent)
    : QStyledItemDelegate(parent)
{
    artificial = new QTreeView(qobject_cast<QWidget*>(parent));
    artificial->setObjectName("DocumentTreeItems");
    artificial->setFixedSize(0, 0);
}
```

Thanks to that I can attach styles to this widget inside qss:
```css
  #DocumentTreeItems::item {
    border: 1px solid transparent;
    border-radius: 2px;
    background-color: $primaryBackground;

    &:hover {
      border: 1px solid $contrastBorder;
      background-color: $controlWidgetBackground;
    }

    &:selected {
      border: 1px solid $accentBorder;
      background-color: $accentBackground;
    }
  }
```

Then I can repaint the background using style and referring to my artificial widget in the `paint` method of delegate:

```cpp
    style->drawControl(QStyle::CE_ItemViewItem, &opt, painter, artificial);
```

This gives the expected result:

[![enter image description here][1]][1]

I'm however deeply dissatisfied with this solution, so if anyone knows a better one I'd be glad to hear suggestions.

  [1]: https://i.sstatic.net/ZeniYQmS.png

Fixes: #13760

### CODE REVIEW

**Comment by FEA-eng** [comment]
All those disclaimers and warnings are worrying but if it's the only solution to this nasty issue for now then it might be worth applying it before the next release. If someone finds a better way, it can always be implemented in place of this one.

**Comment by chennes** [comment]
Here's what I see in the tree with this PR on Qt5 (I see basically the same strange truncation regardless of the overlay state or theme applied).

Screenshot 2024-05-16 at 3 03 59 PM

**Comment by kadet1090** [comment]
Ok, I can confirm this issue - I thought that it was present before but it seems not. As a workaround you can extend the first column of the tree view to be big enough to be big enough. Can you test it with the style mentioned in the description of the background gets applied?

I will fix the issue before next merge meeting as I am able to reproduce it.

**Comment by chennes** [comment]
Yes, the background is applied correctly.

**Comment by kadet1090** [comment]
@chennes I restored the random width addition that seems to fix the issue properly, I'm not happy with hardcoding of such values but it works and I am not able to obtain the required value by other means.

**Comment by pieterhijma** [comment]
I see the following with OpenLight (having checked out `qt6-workaround` in OpenTheme):

screenshot-tree-openlight

However, for OpenDark, I see this:

screenshot-tree-opendark

**Comment by pieterhijma** [comment]
Ok, I checked in on Qt 5 as well, and can confirm it works there as expected.

**Pull request merged**
