### PR TITLE
add QWinTaskbarProgress to windows build

### PR DESCRIPTION
**Pull request by apeltauer**
Windows only!
With this change the FreeCad icon in the taskbar is also used as an progress identifier.

### CODE REVIEW

**Comment by luzpaz** [comment]
@apeltauer Typo in the commit summary, should be **QWinTaskbarProgress** can you change the commit itself to reflect that? Thanks.

**Comment by efferre79** [comment]
the PR would likely introduce a build failure on non-Windows platforms where QWinTaskbarProgress and QWinTaskbarButton are not defined

**Comment by apeltauer** [comment]
I have to add some ifdef definitions to exclude the code from non windows builds. Also the qt version needs to be checked.

**Comment by apeltauer** [comment]
@wwmayer  Does anyone has any concerns about the modifications?

**Comment by wwmayer** [comment]
Some comments:
find_package(Qt5WinExtras REQUIRED) the package shouldn't be mandatory because others might still have a libpack which lacks of the WinExtras stuff. So, replace REQUIRED with QUIET

Where does the define QT_WINEXTRAS_LIB come from? Is it defined by Qt already? If yes where?

**Comment by apeltauer** [comment]
I have made Qt5WinExtras optional in cmake.
QT_WINEXTRAS_LIB is defined in the cmake config file of Qt5WinExtras
(see lib\cmake\Qt5WinExtras\Qt5WinExtrasConfig.cmake) line 71

**Comment by wwmayer** [comment]
Something doesn't work correctly.
E.g. when opening a STEP file then a progress bar is shown. While loading the data then as expected it also shows the progress on the button in the task bar. However, when the operation is finished you can still see that the left part of the icon still has a green border.

So it seems there is a missing function call to get rid of the green border.

**Comment by wwmayer** [comment]
OK, I figured it out. Just have to run my test builds before merging it.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
