### PR TITLE
Bugfix/compile warnings

### PR DESCRIPTION
**Pull request by mlampert**
gcc 8 introduced a bunch of new warnings which make the build really noisy - to the point where all relevant errors and warnings are hard to spot.

This change fixes the most notorious two warnings, catch of an exception by value and the incompatible pointer cast of python functions with and without keyword paramater.

<s>Also added an attribute for `case` fallthrough warnings in sketch - should be interesting to see how they fair with other compilers.</s> As it turns out all builds other than the clang have an issue with the `__attribute__`, removed that commit.

The changes go through the entire code base.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Leaving this one for you @wwmayer

**Comment by f3nix** [comment]
Hi @mlampert.

Regarding [-Wimplicit-fallthrough=]
Please take a look here:
https://github.com/FreeCAD/FreeCAD/pull/1135/commits/23e9809a8866a1fad978d4828abc5cbb969840bb#diff-c9cff1a34105c2740673a3c505a02679R342

It seems to work ok.

Cheers,
Mateusz

**Comment by mlampert** [comment]
@f3nix it wasn't my intent to clean up all warnings. I got worried by the "incompatible function pointer casts" and while looking into that also cleaned up some other warnings. The current change eliminates ~800 lines of warning messages on a clean build. I think the rest should be cleaned up by the respective code owners.

**Comment by wwmayer** [comment]
The changes about using references in the catch block looks okay to me. However, the double casts in the second commit look very ugly and I don't think that it's the correct way to fix them.

When looking at the Python API we have three different C functions with one, two or three arguments.
`
typedef PyObject *(*PyCFunction)(PyObject *, PyObject *);
typedef PyObject *(*PyCFunctionWithKeywords)(PyObject *, PyObject *, PyObject *);
typedef PyObject *(*PyNoArgsFunction)(PyObject *);
`
and the appropriate flags METH_NOARGS, METH_VARARGS or METH_KEYWORDS

Now e.g. for ConsoleSingleton::sPyMessage the function has three arguments but sets 1 (METH_VARARGS) as flag and uses PyCFunction as cast. So, the correct way to fix it is either removing the superfluous argument (which is commented out anyway) or set METH_KEYWORDS and use the PyCFunctionWithKeywords cast.

I think that this once was made wrong in the initial manually written Python binding and the mistake was copied over and over again in many classes. But for example for our Python/XML generators this has been done correctly and there the compiler doesn't print any warnings.

So, the first commit can be merged but I would like to rework the second one to properly fix all the flaws.

**Comment by wwmayer** [comment]
With a9c4bcb all the mistakes are fixed where flag and number of arguments don't match.
Now the remaining warnings are due to how Python keeps function pointers. The second member of the struct PyMethodDef is of type PyCFunction and all other function types (PyCFunctionWithKeywords, PyNoArgsFunction) must be cast to it which now triggers the gcc warning.

This PR suggests this construct (PyCFunction) (void*) to suppress the warning but according to the Python ML this is not fully correct: https://bugs.python.org/issue33012#msg317853
Instead of (void*) it should be (void (*) (void))
Here is an example how pybind11 did it: https://github.com/pybind/pybind11/pull/1396/files
However, I would apply this fix only on the PyCXX code and for the generated swig-code I would simply suppress the warning with a pragma call.

**Comment by mlampert** [comment]
I concur. I had not found the reference to `(void (*)(void))` but that is indeed better.  Thanks for the follow up and rework.

**Comment by wwmayer** [comment]
I guess you have access to gcc 8 to build the latest changes to see what still needs to be fixed. From this PR there should be only left the two files of PyCXX and the one in the Path module.

But from a few days old build on Launchpad I have seen that functions with the METH_KEYWORDS flag are affected, too. Here we have to adjust the script templateClassPyExport.py

In case you will prepare a new PR I recommend to use the reinterpret_cast keyword instead of the old C-casts to improve readability.

Thanks!

**Pull request closed without merging**
