### PR TITLE
[GUI] Enable sort of zoom in Light Sources dialog

### PR DESCRIPTION
**Pull request by xtemp09**
@maxwxyz, added _Push In_ and _Pull Out_ buttons, replaced colors. Now the dialog looks like this.

https://github.com/user-attachments/assets/4e5b4903-9fe3-4383-b783-c7314cd9515b

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
There might be a problem with this code @xtemp09 , see the failed ubuntu CI test. Maybe not tested with Qt6?

**Comment by FEA-eng** [comment]
@xtemp09 Tests failed, can you rebase?

**Comment by xtemp09** [comment]
@FEA-eng, I don't know how to do that. Do you mean `git fetch` and then `git push`?

**Comment by FEA-eng** [comment]
> @FEA-eng, I don't know how to do that. Do you mean `git fetch` and then `git push`?

I use only the web interface of GitHub so I go to my forked repo and branch and select Sync fork —> Update branch but I guess you could use the commands that you’ve mentioned and `git rebase` between them.

**Pull request merged**
