### PR TITLE
PartDesign: new "dogbone" operator

### PR DESCRIPTION
**Pull request by bobtwinkles**
This generates geometry for dogbone corners.
Known limitations:

  - The operator lets you select faces, but ignores them.
  - Curved edges are not handled correctly

This PR is currently in what I would consider an RFC state. It works, but the UI is still a bit janky, and this is my first time working with OpenCascade so I suspect my algorithm for generating the final shape is far from optimal. It's also missing tests, I can write those prior to merge assuming the implementation looks good.

---
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by mlampert** [comment]
Took me a while to figure out how this is supposed to work. To make it usable for the unsuspecting user I would recommend adding proper support for faces, or disallow adding faces as a reference.

I'm not sure what purpose a dogbone in a design serves, so please take this with a grain of salt. From a machining standpoint the generated dogbone is way deeper than necessary, the corner only needs to touch the circumference of the dogbone, not be its center.

Other than that - love it!

**Comment by bobtwinkles** [comment]
Thanks for the review =). I wrote this with laser cutting in mind, so the feature is modeled after how I use/create them manually and not on how a machinist would use the feature. Supporting moving the dogbones "out" so the circle isn't centered on the line seems like it's both a good idea and complicated, but perhaps there's a simple algorithm somewhere in the literature. It's probably a good idea to support that though, especially if it's not complicated. I'll take a look at disallowing face selection and supporting pushing the cutouts around this weekend.

**Comment by luzpaz** [comment]
@bobtwinkles is there a forum thread associated with this PR for the community to discuss your proposed changes ?

**Comment by bobtwinkles** [comment]
There is not an associated forum thread. Unfortunately I'm unlikely to be able to find the time to push this any further in the short term. I'll close this PR for now, if someone else has the time to push it forward feel free to do so.

**Comment by luzpaz** [comment]
@sliptonic do you mind weighing in

**Pull request closed without merging**
