### PR TITLE
Path: Fix Path.Length calculation.

### PR DESCRIPTION
**Pull request by mlampert**
fixes: https://www.freecadweb.org/tracker/view.php?id=4199

### CODE REVIEW

**Comment by luzpaz** [comment]
@mlampert thanks for the fix. Please familiarize yourself with:  
* https://www.freecadweb.org/wiki/Tracker#GitHub_and_MantisBT
* https://www.freecadweb.org/wiki/Tracker#MantisBT_.3C.3D.3E_GitHub_Markup

Perhaps you can overwrite this PR and add `Fixes #4199 - Fix Path.Length calculation` to the title?

**Comment by mlampert** [comment]
TBH I don't see much value of those conventions. I'll close the mantis issue manually once this PR is merged, I actually like doing that.

**Comment by luzpaz** [comment]
The value is that the commit is linked to the ticket within the MantisBT database. Then we can in the future use said database to accurately associate each fix with each ticket. Along with possible uses for creating reports and stats etc...

**Comment by donovaly** [comment]
> fixes: https://www.freecadweb.org/tracker/view.php?id=4199

Many thanks! This should also be backported to 0.18

**Pull request merged**
