### PR TITLE
issue 3443, Override new doc generation when user loaded docs via command line

### PR DESCRIPTION
**Pull request by mwganson**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by mwganson** [comment]
https://www.freecadweb.org/tracker/view.php?id=3443
https://forum.freecadweb.org/viewtopic.php?f=8&t=28178

**Comment by wwmayer** [comment]
Some comments:
The ParameterGrp class is used to make user settings persistent and it shouldn't be misused to handle application-internal stuff that is only relevant for the running FreeCAD instance. Otherwise we start to clutter up the user.cfg with a lot of garbage. Instead Application::Config() should be used where an arbitrary parameter can be set and read.
And as far as I understand the feature request this should not apply to fcstd files only but any file format that creates a document. This means when in the program argument I list an .stl file then it still creates a a second document.
So, all what needs to be done actually is checking inside MainWindow::delayedStartup() if a document already exists (because this can only have happened by loading a file specified in the program argument) and if yes do nothing further.

**Comment by mwganson** [comment]
Great ideas, as always.  Wasn't aware of Application::Config().  Will have to look into that.

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
