### PR TITLE
Gui: TaskCheckGeometry message translation

### PR DESCRIPTION
**Pull request by chennes**
Cleanup of translation issues related to https://github.com/FreeCAD/FreeCAD-translations/issues/182 (note that this does not close that issue, which has many sub-issues).

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9294">pipeline status</a> for feature branch [PR_9294](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9294). Pipeline [838994128](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/838994128) was triggered at [1f4757c](https://github.com/FreeCAD/FreeCAD/pull/9294/commits/1f4757c40cd095e37565e1d347d4cdd0854c2106). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by xtemp09** [comment]
Should [#L419](https://github.com/FreeCAD/FreeCAD/blob/1f4757c40cd095e37565e1d347d4cdd0854c2106/src/Mod/Part/Gui/TaskCheckGeometry.cpp#L419) and  [#L424](https://github.com/FreeCAD/FreeCAD/blob/1f4757c40cd095e37565e1d347d4cdd0854c2106/src/Mod/Part/Gui/TaskCheckGeometry.cpp#L424) be translated too?

**Comment by xtemp09** [comment]
Thank you for fixing this. Yes, it looks good.

I could not find space-prepended strings in FreeCAD, so I assume it does not follow FreeCAD UI guideline. I think it would be much better not leaving the space before the string, but to put the checkboxes into a frame.

So, instead of this:
<details><summary>Screenshot 1</summary>



</details>

To make it look more like this:
<details><summary>Screenshot 2</summary>





</details>

The latter exists in every dialog/window, but space-prepended checkboxes I see for the first time.

**Comment by chennes** [comment]
I didn't do a git blame to see who made those strings -- I was trying to just leave them alone except improve the translation. I could be easily convinced to just drop the spaces entirely, I don't see that they add anything. :)

**Comment by xtemp09** [comment]
All tasks in FreeCAD have their buttons north. This is the first task I see with buttons south. Wouldn't it be better to move them up to follow the guideline?

<details><summary>Screenshot 1</summary>




</details>


<details><summary>Screenshot 2</summary>




</details>

**Comment by chennes** [comment]
> All tasks in FreeCAD have their buttons north. This is the first task I see with buttons south. Wouldn't it be better to move them up to follow the guideline?

That's out of scope for this PR, but is worth looking into further. Do we have anything about it in the [Developer Handbook](https://freecad.github.io/DevelopersHandbook/stylebook/)? If not, a PR there is where I'd start.

**Pull request merged**
