### PR TITLE
Test: add unit tests for PropertyPythonObject

### PR DESCRIPTION
**Pull request by wwmayer**
Adds some tests to demonstrate issue #10460 with Py3.11

### CODE REVIEW

**Comment by chennes** [comment]
@wwmayer do you want to hold off on merging this until there is a resolution for the bug, or is it OK to merge now?

**Comment by wwmayer** [comment]
If we merge the PR now there will be failures with the self-tests for Py3.11 builds. A solution for the actual issue is to rename the methods to avoid a clash with the methods of Python's object class.

**Comment by sliptonic** [comment]
We're making more use of Draft status now to keep the PR queue clean and let maintainers know what is ready for merge.
This is a different case.  Maybe we need to prepend the title with a [HOLD]  or add a label to PRs that are, themselves, ready to go but depend on something else to happen first.

**Comment by wwmayer** [comment]
I don't mind if the PR is merged now because the people with a Py3.11 anyway already suffer from the problem that objects are not correctly restored.

**Comment by wwmayer** [comment]
The PR is now based on https://github.com/FreeCAD/FreeCAD/pull/10769

**Pull request merged**
