### PR TITLE
Py3 21

### PR DESCRIPTION
**Pull request by looooo**
pseudo-pr to show difficulties

### CODE REVIEW

**Comment by bblacey** [comment]
@looooo - did you ```git rebase``` this branch/PR with master before submitting?  It looks like there are a number of redundant commits.  If not, you should do so to reduce the commits to only those that are needed for your py3 changes.

**Comment by looooo** [comment]
I did it the other way.
git checkout Freecad/master
git rebase python3

Maybe it would have been better the other way. My understanding was that it is the same, but actually it isn't.

**Comment by yorikvanhavre** [comment]
This branch is not rebased, it should have all the py3 commits on the top. Besides, it can not just be merged into master like that without proper testing and the OK of everyone involved, it's just a too big change. Please leave me a couple of days and I'll do a separate branch.

**Comment by looooo** [comment]
For sure. I just wanted to show the difficulties. See the discussion on freecad.
I asked there if git rebase is commutative. And the answer was yes, but actually it's not.

**Pull request closed without merging**
