### PR TITLE
FEM Beam Shell Result Output 3D true by default

### LINKED ISSUE #12492: [Problem] FEM Beam Shell Result Output 3D should be true by default
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The `Beam Shell Result Output 3D` property controls the display of results for 1D (beam) and 2D (shell) elements. If it's `true`, they are shown in their expanded (3D) form. Currently, it's `false `by default but it would be better if it was `true` because otherwise there are no results in FreeCAD FEM for beam elements while the results for shell elements can be misleading:

_If OUTPUT=2D the fields in the expanded elements are averaged to obtain the values in the nodes of the original 1d and
2d elements. In particular, averaging removes the bending stresses in beams and shells._

(from CalculiX User's Manual)

### Full version info

```shell
OS: Ubuntu 22.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35994 (Git)
Build type: Release
Branch: main
Hash: 69097667df47b2cc86d8688d2dbb545319e33e68
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
fixes #12492

### CODE REVIEW

**Comment by FEA-eng** [comment]
No idea why this tiny change is not working. It seem that e.g. `ThermoMechSteadyState` (which is `true `by default) is defined in the same way - `true `set in both solver.py and DlgSettingsFemCcx.ui,

@marioalexis84 Can you take a look at this when you have some time ? It's a small but quite important improvement.

**Comment by marioalexis84** [comment]
because `BeamShellOutput` is a preference paramenter and the value in the configuration file takes precedence over the default value.

**Comment by FEA-eng** [comment]
> `BeamShellOutput` is a preference paramenter and the value in the configuration file takes precedence over the default value.

Oh, I see. So the code should work. I just updated the tests with the new default setting. Can you confirm that it's ok to merge?

**Comment by marioalexis84** [comment]
The change will work for new user configuration files.
You can test the change by removing the specific line in your current configuration file (or generating a new one).

**Comment by FEA-eng** [comment]
> The change will work for new user configuration files. You can test the change by removing the specific line in your current configuration file (or generating a new one).

Right, thanks for confirming this. It will be sufficient.

**Pull request merged**
