### PR TITLE
Added-API-Documentation-for-RectangularTrimmedSurfacePy.xml and others.

### PR DESCRIPTION
**Pull request by Ovalelephant35**
Related to https://github.com/FreeCAD/FreeCAD/issues/12547 as a part of improving API documentation for FreeCAD.

### CODE REVIEW

**Comment by Ovalelephant35** [comment]
kindly review @luzpaz @yorikvanhavre I am working on more files to add API docs for each of them.

**Comment by Ovalelephant35** [comment]
Currently going to through files and making it one to two lines only do we want to keep it more descriptive?

**Comment by yorikvanhavre** [comment]
I would not REMOVE description. The more the better! If it does not format well when rendered to HTML, that's another problem, and we could find good practices for those cases. But the idea here is to be as complete as possible.

**Comment by Ovalelephant35** [comment]
@yorikvanhavre i havent removed anything i dont know why its showing like this https://github.com/FreeCAD/FreeCAD/blob/410d4f9f6acb56cf84f1117dd39a595bcd551f15/src/Mod/Part/App/ShapeFix/ShapeFix_EdgePy.xml 
I added to this can you take a look so that i can make changes asap!!!

**Comment by Ovalelephant35** [comment]
Currently I copy pasted from here only and added those to docs kindly see.

**Comment by yorikvanhavre** [comment]
Ok this looks good!

**Pull request merged**
