### PR TITLE
Crowdin: Expose View -> 'Standard views' -> 'Axonometric' to translation

### PR DESCRIPTION
**Pull request by luzpaz**
Closes https://github.com/FreeCAD/FreeCAD-translations/issues/63

### CODE REVIEW

**Comment by luzpaz** [comment]
Note: I haven't tested if this fix in fact works

**Comment by marioalexis84** [comment]
that change will not be compiled because it is inside the block `#if 0 ... #endif.`
https://stackoverflow.com/questions/2852913/what-exactly-does-an-if-0-endif-block-do

**Comment by chennes** [comment]
I don't think it's supposed to be compiled -- it's one of those weird machinations we go through to get Qt's translation facilities to produce the strings we need. This change doesn't affect the compiled executable, just the output of `lupdate` (which it turns out ignores preprocessor directives).

**Comment by yorikvanhavre** [comment]
Using Qt_TRANSLATE_NOOP doesn't do anything at compile time (Normally, we use translate() or tr()). Qt_TRANSLATE_NOOP allows the text to be translatable (picked up by lupdate), so its translation is available to FreeCAD, but the text is not translated immediately, but by another mechanism of FreeCAD somewhere else. This is mostly used in places where you still want to keep the english string (for example stuff that needs to be written to a FCStdc file), and FreeCAD will translate it itself, when needed.

**Comment by luzpaz** [comment]
@yorikvanhavre where can we add these tips for devs/'interested users' to learn about ?

**Comment by yorikvanhavre** [comment]
Maybe somewhere here? https://wiki.freecadweb.org/Localisation#Development_-_How_to_Add_Localisation there might need a new paragraph to explain all the Qt translation structures... I'll try to start something

**Comment by luzpaz** [comment]
> Maybe somewhere here? https://wiki.freecadweb.org/Localisation#Development_-_How_to_Add_Localisation there might need a new paragraph to explain all the Qt translation structures... I'll try to start something

Remember you did add a lot of info about translations to https://wiki.freecadweb.org/Translating_an_external_workbench

**Pull request merged**
