### PR TITLE
[Path]: Expose experimental feature flag in preferences - with warning.

### PR DESCRIPTION
**Pull request by mlampert**
https://forum.freecadweb.org/viewtopic.php?f=15&t=49591&p=475339#p475332

### CODE REVIEW

**Comment by spanner888** [comment]
Confirmed changes NOT in:    
    OS: Debian GNU/Linux 10 (buster) (XFCE/xfce)
    Word size of OS: 64-bit
    Word size of FreeCAD: 64-bit
    Version: 0.19.23756 (Git) AppImage
    Build type: Release
    Branch: master
    Hash: 9c6e9184930a52b165a0b7274e3a45d1006bfe67
    Python version: 3.8.6
    Qt version: 5.12.5
    Coin version: 4.0.0
    OCC version: 7.4.0
    Locale: English/Australia (en_AU)

    
Confirmed Path preferences now has advanced tab, which allow experimental features, plus very large warning & advice and that some other path prefs moved to this tab. tested that experimental path features do now appear in the Path menus.
    OS: Debian GNU/Linux 10 (buster) (XFCE/xfce)
    Word size of OS: 64-bit
    Word size of FreeCAD: 64-bit
    Version: 0.19.23964 +1 (Git)
    Build type: Unknown
    Branch: mlampert/Expose_experimental
    Hash: b9f2dc7f7b8d7f6886386d3378bbd3a277d7da75
    Python version: 3.7.3
    Qt version: 5.11.3
    Coin version: 4.0.0a
    OCC version: 7.3.0
    Locale: English/Australia (en_AU)

    
Issues noted:

1. Info text about experimental features is very large. See attached screen capture.
    
2. Path - Path Addons menu text is sometimes blank ...ie there is an empty/blank as frist item below menu seperator. Note in this FC config, I have dubstar-04 Feeds and Speeds addon installed https://github.com/dubstar-04/FeedsAndSpeeds. Hovering over the blank menu position, does cause the flyout menu to appear with the Feeds and Speeds addon shown. 

Used path pref, to disable experimental features, saved, restarted FC and menu line blank again, and captured image, attached.
Can mostly replicate without restarting FC, just by toggling Path pref, exp features on/off. Mostly means start FC & load APath WB. Check path menu (usually correct), toggle the pref and menu item text goes blank. Toggle exp pref again (always with an OK to save) and the menu text may or may not change... I have not go to the bottom of the behaviour. eg I have seen the menu text blank survive a FC close/repopen (ie not present both before closing and still not present on reopening/restarting FC).

#4387 Large info text 2021-02-09 22-19-20
#4387 Blank Path addons menu text 2021-02-09 22-00-45

**Comment by sliptonic** [comment]
If we are going to make it easier for users to access experimental features, I agree with having a big scary warning.  I think the proposed text misses four important ideas:
1) These features are **experimental**  That's not the same as _untested_ or _still in development_. There is no guarantee that these features will _ever_ escape experimental status.  I don't want users thinking that what they see in experimental **in any way** represents the future of path.
2) These features pose serious risk.  They may crash equipment, ruin parts, or destroy tools.
3) These features are unsupported.  People might do their best to help, but by turning this on, you're on your own.  
4) Using these feature can corrupt your project file.  Saving your project file with an experimental operation or feature does not mean you'll be able to open it again in the future.

**Comment by mlampert** [comment]
Added additional preference for the OCL dependent  features and expose those through the preferences. Other "experimental" features remain behind the original guard which is not exposed anymore. 
Let me know if this works.

**Comment by spanner888** [comment]
Last changes work as described, but the "Path Addons menu text is sometimes blank" mentioned above still remains, even with a new sys & user configs.

**Comment by mlampert** [comment]
> Last changes work as described, but the "Path Addons menu text is sometimes blank" mentioned above still remains, even with a new sys & user configs.
That might be an issue with the Feeds&Speeds, this PR doesn't really change anything around the Addon menu

**Pull request merged**
