### PR TITLE
Stylesheet-fixes V: The final frontier

### PR DESCRIPTION
**Pull request by MisterMakerNL**
@maxwxyz time to start tagging all the things I fixed.
https://github.com/FreeCAD/FreeCAD/issues/15136#issuecomment-2266932393
https://github.com/FreeCAD/FreeCAD/issues/15611#issuecomment-2266853775
https://github.com/FreeCAD/FreeCAD/issues/15695#issuecomment-2266820754
and some more!

### CODE REVIEW

**Comment by MisterMakerNL** [comment]
I also changed the blue of the task menu to something a little more fancy:
image

**Comment by kadet1090** [comment]
I don't think that change to task panel is a good one. Color should be used to mean something, provide a visual hint and so should be used relatively scarcely. Backgrounds should use neutral colors - which for this particular theme would be dark-grayish. On the screenshot I feel that task panel pops out more than the actual model which should be the "star" of the 3D view.

**Comment by maxwxyz** [comment]
all themes do currently have color background and headers for the panel (classic and light) and also dark had a blue tinted BG. I kind of liked the one in dark the most.

**Comment by MisterMakerNL** [comment]
Currently it is this color:
image
But it wasn't really a good color in my opinion, now it is oxford blue.

**Comment by kadet1090** [comment]
That color has low contrast to the background of 3D view so it does not stand out so much - It is fine(ish). Same goes for light - color there is low in contrast to background and not saturated so it kinda works. Blue can be used as neutral color if used correctly i.e. is not saturated and does not stand out too much.



> And like Max said it is blue because classic is blue. If we want to remove the blue we should start with classic, then we do the rest too.

I don't get why. Classic has a lot other problems with color use, we kinda agreed that we are living it as is so people who are used to it can keep it. Why repeat mistakes in new themes?

**Comment by MisterMakerNL** [comment]
I moved the color back to what it was.
As this pr has a bunch of fixes that are more important :)

**Comment by MisterMakerNL** [comment]
Task window background can now be set in the settings with Accent color nr 3.
image
image

**Comment by MisterMakerNL** [comment]
You can have pink task windows if you like:
image

**Comment by MisterMakerNL** [comment]
or green 
image

**Comment by qewer33** [comment]
> Task window background can now be set in the settings with Accent color nr 3. ![image]

Are we sure that's a good idea? A task background is a *background* color, not an accent. Just making it a dark gray consistent with other background is the sensible option.

**Pull request merged**
