### PR TITLE
Path: PocketShape - Fix repositioning of Job model; ProfileFaces - add 4th-axis feature

### PR DESCRIPTION
**Pull request by Russ4262**
This PR:
- fixes an error in the existing PathPocketShape code that causes random repositioning of the Job model to previous or undesired placements. 
- prepares the PathAreaOp script for better 4th-axis integration as a base script for various tools in the PathWB. 
- Add 4th-axis feature to PathProfileFaces

Issue for the PathPocketShape fix is presented in forum: [Bug in Path/Pocket 0.19](https://forum.freecadweb.org/viewtopic.php?f=15&t=36507).  
In MantisBT, this PR addresses issue #3982 and fixes #3982 

Forum discussion for the PathProfileFaces 4th-axis is at: [Path Profile Faces: 4th-axis integration](https://forum.freecadweb.org/viewtopic.php?f=15&t=36773)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by Russ4262** [comment]
Please review.

Thanks.

**Comment by Russ4262** [comment]
Please hold. 
Looking into issue presented in forum: [Re: Path Pocket Shape: 4th-axis Integration](https://forum.freecadweb.org/viewtopic.php?p=312218#p312218).

**Comment by Russ4262** [comment]
I am making progress on the fix.  I have been testing the changes to ensure success.  I suspect that soon I will be able to update this PR with the new code and remove the '[Hold]' tag in title.

**Comment by Russ4262** [comment]
Please review.

**Comment by Russ4262** [comment]
PathWB's dogbonedressup test is still causing problems from time to time.  I have made zero changes to that file, nor the basic PathWB code upon which it is based and it still fails on occasion.  Ideas?

**Comment by Russ4262** [comment]
Thanks to @mlampert and @sliptonic for assistance with tracking down source of DogBoneDressup related error.  Indeed it was a FreeCADGui usage error in the PR code.  
Hoping for that suave four letter 'P' word from our freunde at Travis CI.

**Comment by Russ4262** [comment]
Ready for review. Thanks.

**Comment by Russ4262** [comment]
@yorikvanhavre 
I would like to request removal of the "HOLD" tag currently attached to this PR, so long as the devs have no issues with the code contained herein.  Thanks.

**Comment by sliptonic** [comment]
Let me pull it and look it over one more time tonight and I'll merge.

**Comment by Russ4262** [comment]
No hurry, Sir. I was just hoping to avoid a long-term hold due to the official HOLD tag. I am certain it was placed as a support to the simple [Hold] tag I had placed in the title. I know admin was simply honoring my title hold tag. 
Now that I've worked out the issue presented in the forum, I felt it was no longer needing to be held from my end. 
Thanks to the repo admins here for their support while I wiggle my way through development of worthwhile PRs.

**Pull request merged**
