### PR TITLE
[Draft]PathArray TangentVector & gimbal lock

### PR DESCRIPTION
**Pull request by WandererFan**
- allows user to specify orientation of copies relative to base object
- prevents gimbal lock by using Base.Rotation (quaternions) instead of
  YRP transforms

[Forum discussion](https://www.forum.freecadweb.org/viewtopic.php?f=23&t=45424)

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by WandererFan** [comment]
FEM unit test errors in Qt4/Py2 build. Otherwise OK.

**Comment by WandererFan** [comment]
@vocx-fc:  I see lots of activity in Draft.  Can I merge this without messing up your stuff?

**Comment by vocx-fc** [comment]
Yes, you may. @carlopav is moving the code into modules, but the array classes aren't done right now. So right now it should be fine.

**Comment by carlopav** [comment]
@WandererFan confirmed!
I saw several activities with arrays so I still have to touch them. Merge without problems :)

**Comment by WandererFan** [comment]
Still have FEM unit test errors in Qt4/Py2 build. Otherwise OK.

**Comment by vocx-fc** [comment]
I suggest you rebase your branches carlo, just to confirm that your pull requests merge cleanly.

**Pull request merged**
