### PR TITLE
[Sketch] placecgs: remove unused includes

### PR DESCRIPTION
**Pull request by donovaly**
- also sort includes
- also fix too long lines etc. (done by clang formatter)

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9063">pipeline status</a> for feature branch [PR_9063](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9063). Pipeline [818300673](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818300673) was triggered at [2971d64](https://github.com/FreeCAD/FreeCAD/pull/9063/commits/2971d64ce0b751d12d931fc7cbbb68c352022672). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9063">pipeline status</a> for feature branch [PR_9063](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9063). Pipeline [818309400](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/818309400) was triggered at [334b215](https://github.com/FreeCAD/FreeCAD/pull/9063/commits/334b215cd60c8c684f00c75e882f291d31fb1a8d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by abdullahtahiriyo** [comment]
@donovaly 

Did you really open a PR 45 minutes ago changing all the format of planecgs without even asking whether anybody is working on it, and without consulting, and merged it yourself 45 minutes later?

This is something I do not appreciate. Please, refrain to merge into the Sketcher WB.

**Comment by donovaly** [comment]
> Did you really open a PR 45 minutes ago changing all the format of planecgs without even asking whether anybody is working on it, and without consulting, and merged it yourself 45 minutes later?

This does not change anything, just code reformatting to get rid of Lint warnings.

With the include checks I behaved like for all other include checks I did the last 12 months. Sorry if that interfered with pending work.

**Pull request merged**
