### PR TITLE
[TD] correct icon name

### PR DESCRIPTION
**Pull request by donovaly**
see https://forum.freecadweb.org/viewtopic.php?f=35&t=42979

### CODE REVIEW

**Comment by WandererFan** [comment]
QTextEdit has no placeholderText property in Qt4, so the Py2Qt4 build fails.   Either take the placeholder text reference out (my preference), or use conditional compilation to skip it for Qt4.
    #if QT_VERSION >= 0x050200
           //Qt5.2 specific code
    #else
          //code for other versions
    #endif

**Comment by donovaly** [comment]
> QTextEdit has no placeholderText property in Qt4, so the Py2Qt4 build fails.
> #if QT_VERSION >= 0x050200

This PR only changes a file name, nothing more.

**Comment by donovaly** [comment]
> This PR only changes a file name, nothing more.

Ah, you men this PR: #2975, I commented there.

**Comment by WandererFan** [comment]
replaced by #2986

**Pull request closed without merging**
