### PR TITLE
Toponaming:  Final save/restore changes

### PR DESCRIPTION
**Pull request by bgbsww**
Appear to be fixed:  #15549  #15380 #15484   Each of these should get verified before being closed which is why no direct Fix link here.  I'm pretty sure on these ( my tests worked ), and very hopeful on 15549.

### CODE REVIEW

**Comment by FEA-eng** [comment]
I built FreeCAD from your branch (_bgbsww-toponamingSaveRestore9_) but none of those issues are fixed there. Can it be the case that I'm doing something wrong?

**Comment by bgbsww** [comment]
Are you using the broken files, or recreating the shapes?   The broken
files are not fixed, the operations and future saving should be.

**Comment by FEA-eng** [comment]
> Are you using the broken files, or recreating the shapes? The broken files are not fixed, the operations and future saving should be.

Ok, I retested with fresh files (recreated all the models) and it's working as expected now. Thanks.

**Comment by bgbsww** [comment]
Apologies, I was so close to this I forgot to note that key fact:  because this is a save/restore problem, and the files in the bug reports are already broken, the only way to test and correct this was to create new test cases, which I have done in code in the testing, but not as replacement sample files.  So validating this requires new models; simply trying an existing broken file will not work.

It might be that a full recompute immediately after opening a bad file recovers it enough to work, or that full recompute plus save and then restore does this, but my focus is on matching the behavior with a test, and then fixing it.

**Pull request merged**
