### PR TITLE
Path: Setting origin

### PR DESCRIPTION
**Pull request by spontarelliam**
Currently, when setting the origin position in Path workbench using the X=0, Y=0, or Z=0 buttons, the model and stock are able to move independent of one another. This leads to odd results, placing the model outside of the stock in a way that not even Michelangelo could achieve. A demonstration is shown [here](https://drive.google.com/open?id=1REBK5z5LWy5cr5wbmlmml47HUkGjt0dQ).

This modification forces the model and the stock to move together when using these buttons, as shown [here](https://drive.google.com/open?id=15lj3NIuOcZcg6Kp6ndziksUMNqo-x5F0). I believe this is more consistent with expectations and with other CAM software. The user should have no knowledge of the part moving when they change the origin.

### CODE REVIEW

**Comment by Russ4262** [comment]
Hello again, Sir. 
Nice to see you branching out into other areas of FreeCAD.  I hope your gear creation PR went well.  We ask that you tag your PR title with a "[Path]" or "Path:" prefix.  This will allow for easier recognition by those who review PRs and are browsing the PR list in general.

In regard to your proposed change, I think the stock must be manually updated by clicking the `Refresh` button in the Job Setup tab, after applying translations or other changes to the model or the stock.  That said, I'm okay with your application of the user's translations to the model, to the stock; an alternative would be to identify the method triggered when clicking the `Refresh` button and add it to one or more strategic locations in the same module.

Glad to have another dev improving PathWB.  Welcome!

Thanks.
Russell

**Comment by spontarelliam** [comment]
Well I added the radio button with about 20 minutes of coding and an hour of git confusion. I've made a complete mess. Suggestions on how to move forward?

**Comment by Russ4262** [comment]
If you will kindly provide your simple system setup:OS, and git setup(command line or gui front end).

You have a couple options.
Option 1: Simplest might be copy the files you changed to a separate location. Create a new git branch off upstream/master. Check it out. Paste your modified files in the branch, and create a new PR. Delete this one.  
Option 2: check with another dev here. I know very little about git. I use windows and gitkraken gui for git usage.

Vocx-fc, mlampert, or sliptonic come to mind

**Comment by spontarelliam** [comment]
Thanks. Closing this one out and reopening as #3368.

**Pull request closed without merging**
