### PR TITLE
[TD]code clean up

### PR DESCRIPTION
**Pull request by WandererFan**
This PR is a code clean up effort.  It includes changes to QGIViewPart, DrawViewPart, CosmeticExtension, DrawViewSection and DrawViewDetail to remove unused code and move code to more appropriate locations.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by benj5378** [comment]
I'm generally glad to see improvements of some of the most central TechDraw code that is also some of the most cluttered... but some of this will just cause one very big merge conflict with https://github.com/FreeCAD/FreeCAD/pull/9499. Please merge https://github.com/FreeCAD/FreeCAD/pull/9499 first.

**Comment by WandererFan** [comment]
#9499 has merge conflicts with master. 

Does it handle old documents now with separate cosmetic edges and centerlines now?

**Comment by benj5378** [comment]
@WandererFan I don't know when I will get to look #9499, so just go ahead and merge this

**Comment by WandererFan** [comment]
:( 
I have to make some changes in cosmetics.  I may try some of your ideas while I'm in there.

**Pull request merged**
