### PR TITLE
Accelerate 3D rendering with VBO support

### PR DESCRIPTION
**Pull request by vejmarie**
This is the initial PR to accelerate 3D rendering of TRIANGLES using VBO for rendering. The option must be activated by the end user within the main preferences otherwise standard rendering pipeline is used. Expected performance increase is about x2 to x5 depending on 3D model

### CODE REVIEW

**Comment by wwmayer** [comment]
The Windows SDK doesn't include the file glext.h. But it can be retrieved from here: https://www.khronos.org/registry/OpenGL/api/GL/
So, just don't care about the failing Windows builds...

**Comment by vejmarie** [comment]
thank you, thank you ! Windows is a nightmare to me (I am a 20+ years Linux/Unix guy). So we leave the pain to sgrogan ?

**Comment by wwmayer** [comment]
I got it working under Windows now. I pushed a new branch to my github repo including your and my changes: https://github.com/wwmayer/FreeCAD/tree/vbo_support

Before it's ready for merge I have to clean up all the mess :) Then the way how the node queries the VBO status from the viewer is wrong and will fail in many cases. So it must be adjusted to the OpenInventor way, too.

Question:
The call of glDeleteBuffersARB inside the destructor of SoBrepFaceSet is this actually safe? Usually at this point there is no current GL context any more. And also in the constructor you cannot rely on having a current context in all cases.

**Comment by vejmarie** [comment]
Sorry for the mess with the VBO status from the Viewer. It was the source of the crash reported by a user. I just adapt the code a little to make it work with the test suite. I am not knowing that much Open Inventor and your help will be really appreciated to finish properly that stuff. I put the VBO trigger into the Viewer structure as I believed this was a good place to make it happens.

I think we must call the glDeleteBuffersARB within a GL context to be safe. I thought that this was the case within SoBrepFaceSet object. We can move the constructor within the Render operation pretty easily. Regarding the destructor phase, as I do not know (yet) where the GL context is destroyed it is going to be hard for me to position it properly. What I know is that it is needed to call it because on messy video driver if we don't release the memory it is going to keep it up to next reboot. By the way I do not have any issue on my Mac system with the calls positionned where they are.

Just let me know if you need further help, I really like to see this improvement going upstream.

**Comment by wwmayer** [comment]
PR #517 replaces this one

**Pull request closed without merging**
