### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by yorikvanhavre**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
For some reason a lot of strings have apparently been "untranslated", but it is so on crowdin... Maybe an effect of the "do not merge duplicates" option? Did we enable it?

**Comment by chennes** [comment]
I enabled the "show but auto translate duplicates" option that we had discussed before -- I don't know if that is the cause, here.

**Comment by chennes** [comment]
I wonder if this has to do with the branch creation -- it looks like it's stripped out ALL of the translations, no?

**Comment by chennes** [comment]
@yorikvanhavre I just ran a translation cycle on my machine, and all of these strings that have gotten stripped out in this PR are fine in my local copy. Maybe close this PR and try to re-run?

**Comment by kaktusus** [comment]
> I wonder if this has to do with the branch creation -- it looks like it's stripped out ALL of the translations, no?

that was the effect

all strings that were imported were imported "as new" even if their translated counterparts existed
if the strings are somehow indexed in the import file I assume that these indexes may have changed and Crowdin did not recognize them as existing.

lots of new stuff for me
I need to read this and that I will be more helpful then :wink:

**Comment by kaktusus** [comment]
> For some reason a lot of strings have apparently been "untranslated", but it is so on crowdin... Maybe an effect of the "do not merge duplicates" option? Did we enable it?

Ustawienia określające obsługę duplikatów nie mają wpływu na liczbę ciągów znaków importowanych lub eksportowanych w Crowdin.

Jest to tylko wewnętrzna polityka platformy określająca sposób postępowania w przypadku znalezienia identycznych rekordów tłumaczeń
może to ułatwić lub uprzykrzyć pracę tłumaczom.

As I wrote earlier I would try to look for the reason why Crowdin recognized all imported strings "as new" without rewriting the translations even if they existed.

Yorik make a test environment.

**Comment by chennes** [comment]
I figured out what was wrong with the CrowdIn settings that we seemed to lose all those translations. I'm going to close this, I've run a new translation cycle with the updated setting.

**Pull request closed without merging**
