### PR TITLE
[TD] update menu name to fit into the current naming scheme

### PR DESCRIPTION
**Pull request by donovaly**
To fit into the new naming scheme, see also the updated Wiki: https://www.freecadweb.org/wiki/TechDraw_Module#Views

### CODE REVIEW

**Comment by vocx-fc** [comment]
Stop! I dislike completely this `Title Case`. Only the first letter should be capitalized, like a proper sentence.

**Comment by donovaly** [comment]
> Stop! I dislike completely this `Title Case`. 

This had properly beendiscussed months ago and the current naming is there since around October. All this PR does is her an there changing a single letter to be consistent with the scheme.

I already updated the Wiki pages now which cost me lot of work and I won't change it again. I mean I waited as long as possible and after more than 3 months of waiting it was time to prepare the Wiki for the 0.19 release.

**Comment by WandererFan** [comment]
Making many separate commits is good development practice.  When you move to production (master) though, your commits should be squashed into tidy packages.

What happened with CommandDecorate?  I don't like having a commit that changes every line.

**Comment by donovaly** [comment]
> What happened with CommandDecorate? I don't like having a commit that changes every line.

What do you mean? I already fixed this in the PR yesterday.

**Comment by WandererFan** [comment]
>>> What do you mean? I already fixed this in the PR yesterday

ec1871f in this PR touches every line.

**Comment by donovaly** [comment]
> [ec1871f](https://github.com/FreeCAD/FreeCAD/commit/ec1871fe876506737d62ffa2f9171cef55e5c926) in this PR touches every line.

I cannot follow you. This commit is the fix because in the previous commit 39a25d065ff1c76f80d3ae67410985695d22c113 the line endings were changed to CRLF so I need to correct this. All in all when you merge the PR the line endings will be LF as before.

**Comment by WandererFan** [comment]
replaced by #2986

**Pull request closed without merging**
