### PR TITLE
OndselSolver: solver update from @pieterhijma to fix warnings

### PR DESCRIPTION
**Pull request by PaddleStroke**
@pieterhijma has fixed some warnings in the Ondsel Solver.

### CODE REVIEW

**Comment by chennes** [comment]
Very nice -- OndselSolver compiles without warnings using MSVC-latest and /permissive-.

**Comment by maxwxyz** [comment]
1.0 relevant?

**Comment by PaddleStroke** [comment]
This is just fixing warnings during compilation. I don't know how it stands regarding 1.0, I think it can probably go in.

**Comment by pieterhijma** [comment]
It's not a bugfix per se, but it helps getting rid of lots of warnings. I think it would be good to have a build process for 1.0 without all these warning, so I would recommend including it in 1.0.

**Pull request merged**
