### PR TITLE
simplify the cmake-setup of occt and netgen in

### PR DESCRIPTION
**Pull request by looooo**
newer versions of occt and netgen provide cmake-configuration files. So I guess we should use them.

### CODE REVIEW

**Comment by wwmayer** [comment]
On Windows this crashes cmake. I guess the problem is because file names are case-insensitive and thus adding the line find_package(Netgen) or find_package(OpenCASCADE QUIET) causes an infinite recursion. This means instead of trying to find the external cmake files it opens FindNETGEN.cmake and FindOpenCascade again and again.

**Comment by looooo** [comment]
that is not good. should we add a extra cmake-variable?

**Comment by wwmayer** [comment]
> should we add a extra cmake-variable?

To do what?
IMO, there are two options we can try:
* rename our files FindOpenCascade.cmake and FindNETGEN.cmake and adjust the calls of find_package in the top-level CMakeLists.txt file
* I assume the files provided by OCCT and Netgen are called OpenCASCADEConfig.cmake and NetgenConfig.cmake. Now I wonder whether cmake allows it to search directly for these files.

**Comment by looooo** [comment]
> rename our files FindOpenCascade.cmake and FindNETGEN.cmake and adjust the calls of find_package in the top-level CMakeLists.txt file

sounds good. In the long run we maybe want to use the default configs anyway. So prefixing our FindOpenCascade and FindNetgen with eg. `FreeCAD_` is not a bad idea. I will add this to the PR so we can see if it works.

**Comment by wwmayer** [comment]
Check the documentation of find_package https://cmake.org/cmake/help/v3.0/command/find_package.html
It explicitly supports the modes MODULE where it searches for a FindPackage.cmake file or the CONFIG mode where it searches for PackageConfig.cmake or package-config.cmake. If this works it would be more elegant than the other option.

**Comment by looooo** [comment]
but I guess there is still the potential of a naming conflict if we choose the CONFIG-mode. Also using same names will make it very difficult to understand the configuration. Therefor I would vote for renaming.

ok I can see your point. I will try using the CONFIG-mode once the ci's are done.

**Comment by wwmayer** [comment]
Some problems:
https://forum.freecadweb.org/viewtopic.php?f=4&t=29009

**Comment by looooo** [comment]
for me cmake hangs for quite some time after the configuration. It isn't a big problem, but I guess it's also related to this PR...

**Comment by looooo** [comment]
btw: fallback added to this PR: https://github.com/FreeCAD/FreeCAD/pull/1485

**Pull request closed without merging**
