### PR TITLE
[TD]Add tests for geometry creation

### PR DESCRIPTION
**Pull request by WandererFan**
- check that edge geometry count is correct
- handle delay waiting for threads to complete
- add test for DrawViewDetail

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7849">pipeline status</a> for feature branch [PR_7849](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7849). Pipeline [700287765](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/700287765) was triggered at [55ea8ac](https://github.com/FreeCAD/FreeCAD/pull/7849/commits/55ea8ac948bc87b96c772290159e79c967ad2d37). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
The unit tests have failed because they exceeded the max. of 5 hours. This happened because the command line version is used and thus no QApplication instance is created and no GUI thread is running.

So, in other words the trick with the local event loop doesn't work in CLI but only in the GUI version. To make this working you have to split the tests that can be run in CLI and that require a running GUI.

The best way to keep them separated is:
* create the file TestTechDrawGui.py
* from TestTechDrawApp.py move these lines to TestTechDrawGui.py:
```
from TDTest.DrawViewSectionTest import DrawViewSectionTest
from TDTest.DrawViewPartTest import DrawViewPartTest
from TDTest.DrawViewDetailTest import DrawViewDetailTest
```
* in InitGui.py add `FreeCAD.__unit_test__ += ["TestTechDrawGui"]`

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7849">pipeline status</a> for feature branch [PR_7849](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7849). Pipeline [701361903](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/701361903) was triggered at [3bd05fa](https://github.com/FreeCAD/FreeCAD/pull/7849/commits/3bd05fa9837211ca789646b19ba1743683e079aa). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
Passes tests with Test Framework and with
$ ./FreeCAD -t TestTechDrawApp
$ ./FreeCAD -t TestTechDrawGui

Also passes CI.

**Pull request merged**
