### PR TITLE
Path: Pocket clearing extension [New Feature]

### PR DESCRIPTION
**Pull request by Russ4262**
This is a new feature. It is clean, elegant, and simple with zero regressions.  It allows clearing of odd-shaped pockets where current ops fail.  This extension feature includes some collision avoidance with the model, only allowing travel within voids in the model.  It is only 2D and collision does not include overhangs - additional coding required for overhang awareness.

Thanks to forum user MRx for pushing the boundaries of the current `Pocket` op and seeking a solution.

This new feature is applied to both the PocketShape and Adaptive operations.  The code is independent and is not entangled within either of the improved operations.  There is only a single function and it is placed in the PathUtils module.

This PR also clones the current `UseOutline` feature from PocketShape to the Adaptive op, making Adaptive a bit more robust for clearing material.

**EDIT: Laying in bed, it occurred to me there is one regression starring me blatantly in the face!  Holes!  I'll try to get to it soon.**  
**EDIT: Holes issue fixed and feature applied to Adaptive op also.**  

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---
Snip macro screenshot-f56165

Snip macro screenshot-75dea3

### CODE REVIEW

**Comment by Russ4262** [comment]
I need to add code for holes(opennings) in face.

**Comment by Russ4262** [comment]
Okay. Holes are fixed and new feature added to Adaptive op per @dubstar-04 's late Christmas request.  
Snip macro screenshot-c030e4

This new feature is simple, isolated, and easy to access for future ops.

I do need to clean up the commit history here a bit.

@mlampert I suggest you get that mill fixed !  Path is a changin'.

**Comment by sliptonic** [comment]
No tests? 
No test files?  
Forum link to discussion?  
It's really difficult for me to evaluate contributions without some basis to go on.

**Comment by Russ4262** [comment]
Understood.  My errors. Thank you.

**Comment by tribut** [comment]
For posterity, this seems to be the forum thread this was based on: ["Which milling strategy" by MRx](https://forum.freecadweb.org/viewtopic.php?f=15&t=54189)

**Pull request closed without merging**
