### PR TITLE
Arch: Fix Site, Building, Floor objects creation

### PR DESCRIPTION
**Pull request by wood-galaxy**
-New param : GetBool("FreeLinking",False), unavailable in pref see
parameters
-by default :
allow create Site on Building only
deny create Building on Site or Building
deny create Floor on Site, Building,Floor
-option:
allow create and linking what you want (until non-DAG)

### CODE REVIEW

**Comment by wwmayer** [comment]
The messages that gets popped up should be prepared for translation.

**Comment by wood-galaxy** [comment]
Indeed, I will fix that asap. Btw is there a global system for popup in FreeCAD ? Like FreeCAD.Console.PrintMessage but with a window ?

**Comment by wwmayer** [comment]
No, if you want to pop up a message you should explicitly use a QMessageBox.

**Comment by yorikvanhavre** [comment]
@wood-galaxy should we wait for you to add translation to the messages? Also, IFC allows to have floors inside floors. Maybe we should too...

**Comment by wood-galaxy** [comment]
@yorikvanhavre I'm on it : translation and floors in floor.

**Comment by yorikvanhavre** [comment]
merged!

**Pull request closed without merging**
