### PR TITLE
Measure: Show delta option also in interactive mode

### PR DESCRIPTION
**Pull request by Murmele**
When using the measurement currently it is only possible to enable the delta's by saving the measurement and turning the option on.
With this MR the delta option is already available in the TaskMeasure to see the deltas also in the interactive mode (if possible). The delta option is stored in the  measurement so when saving the measurement, the option is also applied

https://github.com/user-attachments/assets/21bf0048-59ce-4ae4-921a-a290f924f6a0

### CODE REVIEW

**Comment by FEA-eng** [comment]
@hlorus Can you take a look at this?

**Comment by hlorus** [comment]
Hey that's a great addition! Looks looks good to me.

**Review by hlorus — APPROVED** [review]

**Comment by chennes** [comment]
I am going to double-check the MSVC with PCH compilation before merging.

**Comment by chennes** [comment]
Thanks for the PR, @Murmele -- this is a nice addition. I'm going to merge it as-is into main, but also backport it via a cherry-pick to the 1.0 release branch. We discussed it in the PR review meeting this morning and decided that since the lack of deltas represents a sort of regression over the previous measure tool, it would be fair to include this in the release.

**Pull request merged**
