### PR TITLE
[Draft] Add Units Selector to Status Bar

### PR DESCRIPTION
**Pull request by MauricioLucas**
This addition already belongs to Workbench BIM, the proposed change only allows it to be used throughout FreeCad

https://www.forum.freecadweb.org/viewtopic.php?f=22&t=72223

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7579">pipeline status</a> for feature branch [PR_7579](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7579). Pipeline [661856497](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/661856497) was triggered at [0d06280](https://github.com/FreeCAD/FreeCAD/pull/7579/commits/0d06280ce88cba34cd77cf244609569d61f828be). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
This is a good idea... I'll give it a try before merging, just to be sure

**Comment by luzpaz** [comment]
what did get closed ?

**Comment by MauricioLucas** [comment]
This topic started on the FC forum, it was Syres who adjusted this solution in the Draft module, but he chose to continue with another similar solution that met his needs and put it in the Tux module. It was he who also suggested closing this pull.

I particularly prefer this solution, but Yorik himself seems to have liked this one. As Syres will no longer work on this part of the code and I didn't see the possibility of completing this pull, I accepted the suggestion of closing it until I myself found a way to solve it.

Join the thread, there are still many ways to achieve the same result and we will get there.
[https://forum.freecadweb.org/viewtopic.php?f=22&t=72223](url)

**Comment by MauricioLucas** [comment]
@luzpaz, you want to reopen?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7579">pipeline status</a> for feature branch [PR_7579](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7579). Pipeline [698942969](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/698942969) was triggered at [0d06280](https://github.com/FreeCAD/FreeCAD/pull/7579/commits/0d06280ce88cba34cd77cf244609569d61f828be). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by yorikvanhavre** [comment]
I think this is still valid for merge... I'll try to test it tomorrow, see what conflicts with @Syres916 's branch and merge it if there is nothing against it

**Comment by yorikvanhavre** [comment]
Implemented in a653108bba (Sorry for losing the commit authorship, I had to do heavy rebasing)
Since this is a simple solution, I figured it's best to add it now, as it is easily reversible if a better solution comes up later.

**Pull request closed without merging**
