### PR TITLE
Addon Manager: set size adjust policy for sort

### LINKED ISSUE #12827: [Problem] Addon manager UI: sort by field too narrow
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The drop down menu to sort the result list in the addon manager is too narrow to read the contents. It's even worse with the translated text. 

No matter how wide the display is, its not readable unless it is selected. So it is only unreadable when the menu is pulled down.
grafik

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36277 (Git)
Build type: Release
Branch: main
Hash: 9e1903d46112b3660bf10c6a4537d728101d560b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.2
  * CurvedShapes 1.0.5
  * Curves 0.6.23
  * Defeaturing 1.2.2
  * fasteners 0.5.12
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.2
```

### Subproject(s) affected?

Addon Manager

### Anything else?

Not sure if this is related to @obelisk79 OpenDark.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chennes**
Might fix #12827 - @maxwxyz can you test to see if this resolves the issue you reported?

### CODE REVIEW

**Review by maxwxyz — CHANGES_REQUESTED** [review]
Unfortunately no difference:
grafik

When it is not *open* all items are displayed in full length:
grafik

It interrupts the words only when I open the drop down.

**Comment by chennes** [comment]
It's very odd, I wonder what the difference is between your system and mine -- I don't see this issue, and it looks like there is even plenty of room in that drop down to eliminate the text elision. Let me try turning elision off and see what happens.

**Comment by maxwxyz** [comment]
It must have to do something with the theme, even without this PR.

In Classis it's ok: 
grafik

In the shipped dark it is without elision but the text is cut off and not legible:
grafik


@obelisk79 @MisterMakerNL ping

**Comment by MisterMakerNL** [comment]
Seems to be caused by the check mark, that is hidden/not used in classic.
Not sure why this is removed tho, maybe not even on purpose. But is checks the active function.

**Comment by chennes** [comment]
@MisterMakerNL good find -- obviously the checkmark is superfluous in this case. Let me see about turning it off.

**Comment by chennes** [comment]
OK, @maxwxyz, take three. Does *this* do anything for your case?

**Comment by maxwxyz** [comment]
@chennes no, sorry. Looks still the same:
OpenDark
grafik

Darker:
grafik

Classic:grafik

<details><summary>Windows 11 0.22dev #12859</summary>
<p>

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.11.8, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.2
  * CurvedShapes 1.0.5
  * Curves 0.6.24
  * Defeaturing 1.2.2
  * fasteners 0.5.14
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.3

``` 

</p>
</details>

**Comment by maxwxyz** [comment]
Also with a translated version the box appears wider but has still the `...`:

grafik

**Comment by maxwxyz** [comment]
@chennes any news on this or any idea who to ping for this? Commenting also as a reminder for the upcoming feature freeze on 2024-06-03.

**Comment by chennes** [comment]
I was unable to reproduce on my systems, so I don't have a good way of testing fixes. @MisterMakerNL is probably the most knowledgable in this area, but I'm sure there are others around as well.

**Comment by obelisk79** [comment]
My guess is the list isn't being responsive to account for padding/margins of the stylesheet in the case of OpenDark/OpenLight. Are those parameters pre-defined in the code for this? Or maybe some kind of strange limitation of using PySide?

**Comment by maxwxyz** [comment]
@chennes is this PR still relevant?

**Comment by chennes** [comment]
Since this didn't work I'm just going to close it. The bug remains open.

**Pull request closed without merging**
