### PR TITLE
[MeshPart] clean

### PR DESCRIPTION
**Pull request by mosfet80**
removed old commented code.

### CODE REVIEW

**Comment by FEA-eng** [comment]
That's quite a lot of unused code, looks good to me.

**Comment by yorikvanhavre** [comment]
Could you have a look @wwmayer if that's safe to remove or if it's better to keep for some reason

**Comment by wwmayer** [comment]
The comments in `src/Mod/MeshPart/App/MeshFlatteningLscmRelax.cpp` shouldn't be removed, the rest is OK.

**Review by wwmayer — CHANGES_REQUESTED** [review]
See comment

**Comment by FEA-eng** [comment]
@mosfet80 Can you update the PR with Werner's suggestion?

**Pull request merged**
