### PR TITLE
BIM: NativeIFC 2D support

### PR DESCRIPTION
**Pull request by yorikvanhavre**
This is support for 2D objects in NativeIFC. Corresponds to item 6.A from https://github.com/yorikvanhavre/FreeCAD-NativeIFC/blob/main/doc/roadmap2024.md

With this, one is now able to embed 2D objects (linework, texts, dimensions) inside IFC files, as well as handle such entities produced by other BIM apps (Basically BlenderBIM/Bonsai), and define "Drawings", which are basically a section plane inside a group, which can contain other 2D entities too that compose the drawing.

One can now create groups inside IFC documents and place section planes inside, and these are interpreted correctly by BlenderBIM/Bonsai too.

- [x] Basic import/export structure
- [x] Support for linework
- [x] Support for texts
- [x] Support for dimensions
- [x] Support for hatches
- [x] Support for section planes (drawings)
- [x] Support for axes (needs some refactor of the Axis VP later on)
- [x] 2D elements grouped into a group with ObjectType == "DRAWING" should be imported as one (expandable) drawing object
- [x] 2D elements under root: A new Drawing object should be created

### CODE REVIEW

**Comment by marcuspollio** [comment]
Hi !
I'd like to test and provide feedback in the coming days.
Mind waiting a bit before merging ? Thanks =D

**Comment by maxwxyz** [comment]
@yorikvanhavre still has a conflict.
@marcuspollio until when will you be able to test?

**Comment by yorikvanhavre** [comment]
Conflict solved!

**Comment by maxwxyz** [comment]
@yorikvanhavre new conflicts again :)
@marcuspollio FYI

**Comment by yorikvanhavre** [comment]
Hopefully fixed again :sweat_smile:

**Comment by yorikvanhavre** [comment]
Will fix the lint :)

**Pull request merged**
