### PR TITLE
Core: Property Manager

### LINKED ISSUE #13038: Limited GUI support for adding custom data elements
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This issue should be seen in the light of #12120, but it is a general problem of properties as well: In general it is quite difficult to add properties to document objects. The current workflow in the GUI is: 
- select the document object to which you want to add a property,
- go to the property view,
- right-click somewhere in the property view,
- enable the "Show all" checkbox,
- right-click somewhere in the property view again,
- choose "Add property",
- choose a type (the dialog remembers the last chosen type which is convenient),
- optionally type a group (the dialog remembers the last group which is convenient),
- type the name for the property,
- press OK,
- find the property you've just added in the property view,
- click on the value field of the property, and
- type your value.

For Variable Sets that aims to move to a property-based workflow instead of a spreadsheet-based this is an inconvenient way to add properties.

Noteworthy is the following:
- Creating a property and setting a value is separate: it is not possible to define the name and set the value in the same dialog.
- Looking at FreeCAD's implementation it would be possible to add a value input box to the dialog, but it would be difficult to support expressions in that case. This is probably the reason why the steps are separated. See the remarks on Dynamic Data below.

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36330 +30 (Git)
Build type: DEBUG
Branch: add-property
Hash: d010ebf6b226f44951d6880a5a636fb6364a07db
Python 3.11.6, Qt 5.15.12, Coin 4.0.2, Vtk , OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
  * Ondsel-Lens 2024.1.22.01
  * backup 0.2.3
  * BIM 2021.12.0
  * Assembly3 0.12.2
  * Manipulator 1.5.7
  * fasteners 0.5.10
  * Assembly4 0.50.7
  * DynamicData 2.60.0
```

### Subproject(s) affected?

None

### Anything else?

Context:
- #12120
- [Ondsel's Blog Post](https://ondsel.com/blog/build-system-for-custom-data-elements/) touches on this topic
- #12837

Related Work:
- Assembly 4 Variables
- Path (or CAM) PropertyBag
- Dynamic Data

All of these workbenches have GUI support for adding properties. Assembly 4 and Path don't have support for expressions. Dynamic Data has support for expressions but different from what is available in Core. The input box supports `=<<file>>#DocObj.Property` syntax (which is very cool by the way), but it is not the same expression editor that is available elsewhere in FreeCAD. For example, there is no completion support for expressions. This has to do FreeCAD's custom expression editors that are not exposed in Python and they need to know the binding beforehand.

I will create a PR that aims to address this issue in the near future.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pieterhijma**
This adds a Property Manager dialog to FreeCAD with "named scopes" that allows the user to filter the properties to enable the user to conveniently add properties. 

The screenshot below shows the named scope "all" that shows all documents, document objects, and properties. At the top you can select various filters to filter the properties you're interested in. 
screenshot-scope-all

In the screenshot below we filtered the properties such that a single document object is selected. We named the scope "myparams" and it filters on the object name "VarSet" and the group "Params". This opens a panel in which we can add properties and their values conveniently:
screenshot-scope-myparams

A video explaining the functionality will follow later.

Closes #13038

### CODE REVIEW

**Comment by pieterhijma** [comment]
I tried to reuse as much as possible code from `src/Gui/propertyeditor`. However, there were some things there that needed to be adjusted. Before merging we should discuss how to reconcile the small differences in similar files in `src/Gui/propertymanager` and `src/Gui/propertyeditor`. 

Instead of changing the files in `propertyeditor`, for now, I copied the files from `propertyeditor` and suffixed them with a 2, so for example `propertymanager/PropertyModel2.cpp` is virtually the same as `propertymanager/PropertyModel.cpp`. The former is a bit more general than the latter, so it would be a good choice to change the one in `propertyeditor`, but this should be discussed.

**Comment by pieterhijma** [comment]
Note that this PR builds on #12531, so it is currently effectively only the last commit.

**Comment by NomAnor** [comment]
The dialog with all its filters and the long list of objects feels a bit intimidating. I will wait for your video to get a better understanding of the intended use.

What I like is the tabular approach to editing user parameters in the second screenshot. The current "add property" dialog is cumbersome when you want do add properties. And editing existing properties feels even more complicated.

You should add a trash can icon at the end of each line to delete the user property.

Depending of your intended workflow, it might be useful to extract the user parameter editing area into a standalone UI. If I want to edit the user properties of a single object, I could open the editor with a menu entry and only get the tabular list for this object. This might be easier to understand for casual users than a big dialog.

The UI can then be embedded in your manager to be able to edit properties across the application as shown in the first screenshot.

**Comment by pieterhijma** [comment]
Sorry, it took a while but attached you find a small video that explains the way it operates. By the way, I'm also working on another solution to #13038 that is less intrusive than the property manager.

https://github.com/FreeCAD/FreeCAD/assets/5336482/0e97e016-158a-4f5c-bc60-a3fa060e11d5

**Comment by maxwxyz** [comment]
@pieterhijma also here the heads up for the upcoming feature freeze for 1.0 on 2024-06-03. Is this already a piece of a the splitted VarSet PR?

**Comment by maxwxyz** [comment]
@pieterhijma is this PR still relevant?

**Comment by pieterhijma** [comment]
I think it's better to close it.

**Pull request closed without merging**
