### PR TITLE
Path: Respect meshing tolerance settings for 3d surfaces

### PR DESCRIPTION
**Pull request by gwicke**
Meshing tolerance settings for 3d surface operations were ignored since
switching to directly using facets from the view tesselation. On complex
3d shapes, this could cause serious meshing artifacts in the generated
paths, serious enough to show up even in path previews.

Additionally, there were occasionally segfaults when a model was not
viewed and thus implicitly tessellated before starting an OCL operation.

This patch switches from using view tessellations to explicitly calling
`tessellate()`. While this is usually more expensive than using the
existing view tessellation, recent changes to parallelize tessellation
have reduced this additional cost significantly.

Note that this diff only restores the use of LinearDeflection, since
that is the main thing we care about in OCL use cases. Angular
deflection is still ignored, but I think this is a good thing for this
case since a highly refined mesh in tiny but heavily curved areas below
the linear deflection threshold just adds unnecessary cost. If there is
agreement on this point, then we can remove the preference for
AngularDeflection from the UI in a follow-up.

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by gwicke** [comment]
Example of artifacts: High res path (with this diff applied), vs. a model with default meshing settings.
image

Extreme example with a sphere & manually reduced view mesh resolution. Path is still smooth, as mesh resolution on path's model is increased by the code added in this diff: 
image

**Comment by adrianinsaval** [comment]
There is a tessellate function mentioned in https://wiki.freecadweb.org/TopoShape_API
Maybe that is what you want?

**Comment by gwicke** [comment]
@adrianinsaval, I know, that was used in an earlier version of this code. I believe the reason for switching to using facets directly was the desire to avoid repeated re-meshing when regenerating paths, since this re-meshing can be rather expensive. By using facets, that prices is only paid once per session, rather than once per path operation generation.

**Comment by gwicke** [comment]
That said, using `tesselate()` also refines the mesh for subsequent `Part.getFacets()` calls. The lack of angular resolution support should not matter here, but we would need to find a way to avoid re-computing the mesh every time, even when there is already an existing mesh of at least the requested resolution.

Interestingly, the number of facets returned does not actually change when dropping the resolution at a later point, so it seems that the highest resolution is cached, but lower resolution requests are still re-computed.

**Comment by gwicke** [comment]
I am still not completely happy with this PR. One issue I saw in practice is that permanently ramping up view resolution on complex models can make opening such files later super slow if the internal model is not marked as hidden.

The alternative, bringing back a plain tessellate(linearDeflection) call works fine, but is very slow since that call is single threaded (while view tessellation allows multi threading). Allowing multi threading with a small CPP change improves things, and should benefit other users of tessellate() as well. Still not perfect, but probably the best we can do unless we can figure out a way to cache / share tessellations of sufficient resolution across path generations. I'll put up a new version with that change in a bit, probably after #3506 is decided.

**Comment by gwicke** [comment]
Quick update: I parallelized the TopoShape tessellate() call in #3511, and have since tested a version of this diff that uses tessellate() exclusively. That seems to perform okay even with large models, so I am going to update this diff with those changes.

**Comment by gwicke** [comment]
This is now ready. Tested this manually on a few surface test cases.

**Pull request merged**
