### PR TITLE
Fem: Add option to use old Netgen mesher implementation

### PR DESCRIPTION
**Pull request by marioalexis84**
Add preference page to select between old and new Netgen mesh implementations.

@FEA-eng

### CODE REVIEW

**Comment by FEA-eng** [comment]
Some FEM test are failing:

```
FAIL: test_femobjects_make (femtest.app.test_object.TestObjectCreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Fem/femtest/app/test_object.py", line 86, in test_femobjects_make
    self.assertEqual(len(doc.Analysis.Group), count_defmake - 19)
AssertionError: 45 != 46

======================================================================
FAIL: test_femobjects_derivedfromfem (femtest.app.test_object.TestObjectType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Fem/femtest/app/test_object.py", line 859, in test_femobjects_derivedfromfem
    self.assertEqual(len(doc.Objects), testtools.get_defmake_count(False))
AssertionError: 58 != 59

======================================================================
FAIL: test_femobjects_derivedfromstd (femtest.app.test_object.TestObjectType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Fem/femtest/app/test_object.py", line 1033, in test_femobjects_derivedfromstd
    self.assertEqual(len(doc.Objects), testtools.get_defmake_count(False))
AssertionError: 58 != 59

======================================================================
FAIL: test_femobjects_isoftype (femtest.app.test_object.TestObjectType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Fem/femtest/app/test_object.py", line 472, in test_femobjects_isoftype
    self.assertEqual(len(doc.Objects), testtools.get_defmake_count(False))
AssertionError: 58 != 59

======================================================================
FAIL: test_femobjects_type (femtest.app.test_object.TestObjectType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Fem/femtest/app/test_object.py", line 294, in test_femobjects_type
    self.assertEqual(len(doc.Objects), testtools.get_defmake_count(False))
AssertionError: 58 != 59
```

**Comment by marioalexis84** [comment]
> Some FEM test are failing:

Fixed

**Review by FEA-eng — APPROVED** [review]

**Comment by adrianinsaval** [comment]
is there an issue related to this? what is the new implementation missing that would make us want to have two implementations?

**Comment by FEA-eng** [comment]
> is there an issue related to this? what is the new implementation missing that would make us want to have two implementations?

There is a new implementation already but its dependencies might be problematic to install in some cases (on old computers) so this PR adds an option to switch back to old implementation (which didn’t work on Linux). Related issue: #16759

**Comment by marioalexis84** [comment]
The idea is to provide the package for Windows, Appimage and macOS versions since the netgen-mesher package from pip is not supported by older processors. see https://forum.ngsolve.org/t/problems-with-netgen-pip-package/3078.
I was planning to write to @looooo and you @adrianinsaval about this.
Basically we need to compile netgen with the Cmake flags `USE_PYTHON=ON`, `USE_OCC=ON` (which happens by default) and `USE_NATIVE_ARCH=OFF` (to build for generic CPU).
I don't see a problem in offering an option to select between the old and the new implementation. Once we are sure that there are no problems with the package, we can deprecate the old implementation completely.

**Comment by adrianinsaval** [comment]
I believe we don't currently ship with netgen and as I understand it the old implementation requires netgen at compile time so I don't know how useful it'll be for users if we don't ship it.
If we're going to add it ourselves to the bundles we can control with what options we compile netgen so that should not be a problem. @chennes is netgen included in libpack 3?

**Comment by FEA-eng** [comment]
> I believe we don't currently ship with netgen

We do on Windows. Not on Linux because, as I said, it wasn’t working there and hence the new implementation.

**Comment by adrianinsaval** [comment]
> > I believe we don't currently ship with netgen
> 
> We do on Windows. Not on Linux because, as I said, it wasn’t working there and hence the new implementation.

is it included in rc2? the libpack will not be used for the 1.0 release

**Comment by chennes** [comment]
(LibPack 3 includes Netgen v6.2.2403, but it is compiled with `USE_PYTHON=Off` there)

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
