### PR TITLE
[GUI] attempt to fix number display issue of gradients

### PR DESCRIPTION
**Pull request by donovaly**
Forum thread: https://forum.freecadweb.org/viewtopic.php?p=598019#p598019
- depending on the length of label numbers and the main window size you cannot see the numbers
- this PR improves the situation a bit since it adds more space for longer numbers

a proper solution would however be to take the width of the number label and perform the calculation with this result since one is then also independent on the window size

Here is the behavior with the PR:
FreeCAD_jUh8CnvjKI

As one can see not optimal. yet.

I put it on the milestone for 0.20 because I realized that on small laptop screens there is even with just  2 decimals there is not enough space to see the numbers. But then the gradient is useless. Since for Elmer simulations we don't provide another result visualization, we make the whole Elmer simulation feature rather useless for users with small screens (<= 15 inch).

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6925">pipeline status</a> for feature branch [PR_6925](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6925). Pipeline [550159958](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/550159958) was triggered at [dd36dba](https://github.com/FreeCAD/FreeCAD/pull/6925/commits/dd36dba70cdfeee59552d48387d075659c5a1a89). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6925">pipeline status</a> for feature branch [PR_6925](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6925). Pipeline [550166755](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/550166755) was triggered at [0daa85c](https://github.com/FreeCAD/FreeCAD/pull/6925/commits/0daa85cd53fd873bfa537999105c408a96178c70). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
See #6927

**Comment by donovaly** [comment]
Closing since this was just a try and #6927 is the proper intended fix

**Pull request closed without merging**
