### PR TITLE
PATH: Fix tool shapes for zero dimension bugs

### PR DESCRIPTION
**Pull request by J-Dunn**
Current V-bit totally hangs FC when _cutting edge height_ is zero. _Tip diameter_ of zero also causes errors. 
These two tool shapes add 1um offsets to various dimensions to prevent user entered parameters from inducing zero dimensions which make the solver barf.  
The rotational geometry has also been simplified. 
Some are non critical but _tip diameter_ increment is a work around. To be rigorous, the fixed value such ideally be relative to some dimension of the job, not an arbitrary constant. Hopefully 1um will be small enough to not affect the workpeice dimensions and be suitable for most FC applications unless someone is doing UV lithography masks ;) 

https://forum.freecadweb.org/viewtopic.php?f=15&t=54880&p=479739#p479739
This replaces earlier PR where these file upload was not included. 
https://github.com/FreeCAD/FreeCAD/pull/4491

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6536">pipeline status</a> for feature branch [PR_6536](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6536). Pipeline [488398035](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/488398035) was triggered at [d425a55](https://github.com/FreeCAD/FreeCAD/pull/6536/commits/d425a5562b923893fe3ca0897f494d1d55e5e516). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> Can you please have a look and maybe make a PR just for this file?

OK, I could resolve it by renaming the file.

**Comment by J-Dunn** [comment]
Apologies, it looks like I had to rename it to check the contents as an editable FC file and forgot to change it back before uploading. 
Does this still require attention?

**Comment by donovaly** [comment]
No, everything is fine now

**Comment by J-Dunn** [comment]
OK, thanks.  Sorry for the slip up. It would be handy if FreeCAD could open fsstd as well as FCStd now it is used and is infact an identical file format.

**Pull request merged**
