### PR TITLE
[PD] Fix Pad uptoface with custom direction

### LINKED ISSUE #16274: PartDesign: Error with Pad up to face along custom direction
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The error message: "SketchBased: Up to face: Must not be parallel to extrusion direction!" displays when making a Pad feature with a custom direction.
This seems to be a regression from 0.21.2. Seemingly related issues: #7879 #7880 

Steps to reproduce:
1. Create a closed profile on the XY-plane that is entirely left of the Y-axis.
2. Create a sketch on the XZ-plane containing a line that has a positive slope (not vertical).
3. Create a Pad using the sketch from step 1.
3.1 Set Type to "Up to face" and select the YZ-plane.
3.2 Set Direction/edge to "Select reference..." and select the line created in step 2.
4. Error "SketchBased: Up to face: Must not be parallel to extrusion direction!" takes place.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38622 (Git)
Build type: Release
Branch: main
Hash: ed97f3c4591303ee3b54906768f8f4eba5211265
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * Ondsel-Lens 2024.7.5.02
  * OpenTheme 2024.8.17
```

### Subproject(s) affected?

PartDesign

### Anything else?

[Pad up to face error.zip](https://github.com/user-attachments/files/16857884/Pad.up.to.face.error.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix #16274

### CODE REVIEW

**Comment by maxwxyz** [comment]
Might this also fix https://github.com/FreeCAD/FreeCAD/issues/14663 ?

**Comment by FlachyJoe** [comment]
@maxwxyz #16030 will fix #14663

**Comment by chennes** [comment]
@AjinkyaDahale is going to record a macro that demonstrates the failure and fix.

**Comment by AjinkyaDahale** [comment]
Do we also need a macro for #14663? It seems to be a more particular case.

**Comment by AjinkyaDahale** [comment]
(Macro added in issue)

**Comment by chennes** [comment]
I am still working on getting a working test.

**Comment by chennes** [comment]
I didn't, thank you!

**Pull request merged**
