### PR TITLE
[TechDraw] Remove BaseGeom

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---
https://forum.freecad.org/viewtopic.php?t=77616

### CODE REVIEW

**Comment by benj5378** [comment]
Can only say, that this is very labour intensive
Screenshot from 2023-04-29 21-37-57

**Comment by benj5378** [comment]
@WandererFan Are you still sure this is a good idea? Please look through and let me know if this was what were in your thoughts. It's only a draft.

**Comment by WandererFan** [comment]
Still a good idea.  I was looking at your original commit and moved the geometry->QPainterPath stuff to a separate file: https://github.com/WandererFan/FreeCAD/tree/PR9441 

Still an issue with face outlines.  

I will look at your newest commit tomorrow. We probably want to do this in small chunks instead of one big PR.

There will be a feature freeze coming soon, so this likely won't make it into the v0.21 release.

**Comment by benj5378** [comment]
> I will look at your newest commit tomorrow. We probably want to do this in small chunks instead of one big PR.

This probably won't be possible because it is so intervened. I can split up VertexGeom, FaceGeom and EdgeGeom. But I can't split up EdgeGeom by itself. Though it is very far from over and I might move and merge the code around A LOT.

**Comment by benj5378** [comment]
@WandererFan I think this PR is beginning to get over our heads. I have used about 12 hours now fixing compiler error and I can only imagine at least as many fixing bugs. I suggest that we start skinnying down BaseGeom before removing it completely.

**Comment by WandererFan** [comment]
OK.  Bin this and we'll move to Plan B.

**Pull request closed without merging**
