### PR TITLE
[PD] Use `PropertyLinkSubList` for loft and sweep sections

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
This change is necessary since we restrict part-design features to only use
other features from the same body.

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
Unfortunately, it seems even with fc 0.19 it is possible to use sketches/faces from other bodies. Steps to reproduce: 

1. In attached file, open sweep dialog with `Body001` active.
2. Set `Body001.Sketch004` as path and `Body.SketchBase` as profile.

This goes through and no dialogs are raised that ask to make shapebinders, say. On the other hand, if we select `Body.SketchBase` and `Body001.Sketch004` first and then run sweep the dialog is raised.

This behavior is consistent with the following versions:

**Comment by Roy-043** [comment]
> Unfortunately, it seems even with fc 0.19 it is possible to use sketches/faces from other bodies. Steps to reproduce:
> 
>     1. In attached file, open sweep dialog with `Body001` active.
> 
>     2. Set `Body001.Sketch004` as path and `Body.SketchBase` as profile.

When I do this I get a 'Links go out of the allowed scope' warning in the Report view in V0.19 and V0.20. In V0.20 there is also an 'Unsupported sub-shape type' warning.
```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Dutch/Netherlands (nl_NL)
```
```
OS: Windows 8.1 (6.3)
Word size of FreeCAD: 64-bit
Version: 0.20.26375 (Git)
Build type: Release
Python version: 3.8.12
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Dutch/Netherlands (nl_NL)
```

**Comment by AjinkyaDahale** [comment]
@wwmayer could you take a look at this? I will need to make changes in PR #5170 once this is merged to use the methods that are in `PropertyLinkSubList` there as well.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5176">pipeline status</a> for feature branch [PR_5176](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5176). Pipeline [411472374](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/411472374) was triggered at [8ec2549](https://github.com/FreeCAD/FreeCAD/pull/5176/commits/8ec254957743fd22145d0a256db263f590846b1a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
