### PR TITLE
[0.17] FEM: fix in elmer solver

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

https://forum.freecadweb.org/viewtopic.php?f=18&t=22576&start=180#p208992

### CODE REVIEW

**Comment by wwmayer** [comment]
Please note the build failure. One of the unit tests doesn't work because it cannot access a file.

**Comment by wwmayer** [comment]
Ping @berndhahnebach

**Comment by berndhahnebach** [comment]
I missed this. Thanks for the reminder. I'm on the way. I will have a look at this tomorrow. 
bernd

**Comment by berndhahnebach** [comment]
I'm on the way ... Seams a Python3 issue.

Checking FEM Elmer solver for solver frame work... 
Machine testmode: True 
Prepare testmode: True
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Mod/Fem/femsolver/task.py", line 115, in protector
    self.run()
  File "/usr/local/Mod/Fem/femsolver/elmer/tasks.py", line 76, in run
    w.write()
  File "/usr/local/Mod/Fem/femsolver/elmer/writer.py", line 115, in write
    self._writeSif()
  File "/usr/local/Mod/Fem/femsolver/elmer/writer.py", line 740, in _writeSif
    sif.write(fstream)
  File "/usr/local/Mod/Fem/femsolver/elmer/sifio.py", line 213, in write
    writeSections(self.sections, stream)
  File "/usr/local/Mod/Fem/femsolver/elmer/sifio.py", line 93, in writeSections
    _Writer(ids, sections, stream).write()
  File "/usr/local/Mod/Fem/femsolver/elmer/sifio.py", line 287, in write
    self._writeSection(s)
  File "/usr/local/Mod/Fem/femsolver/elmer/sifio.py", line 292, in _writeSection
    self._writeSectionBody(s)
  File "/usr/local/Mod/Fem/femsolver/elmer/sifio.py", line 308, in _writeSectionBody
    self._writeAttribute(key, s[key])
  File "/usr/local/Mod/Fem/femsolver/elmer/sifio.py", line 327, in _writeAttribute
    self._writeScalarAttr(key, data)
  File "/usr/local/Mod/Fem/femsolver/elmer/sifio.py", line 359, in _writeScalarAttr
    self._stream.write(self._preprocess(data, type(data)))
  File "/usr/local/Mod/Fem/femsolver/elmer/sifio.py", line 404, in _preprocess
    if issubclass(dataType, str) or issubclass(dataType, unicode):
NameError: name 'unicode' is not defined

Test writing STARTINFO file 
Comparing /usr/local/Mod/Fem/femtest/testfiles/elmer/ELMERSOLVER_STARTINFO to /tmp/FEM_unittests/FEM_solverframework/ELMERSOLVER_STARTINFO 
ERROR

**Comment by berndhahnebach** [comment]
Mhh still not fixed ...

**Comment by berndhahnebach** [comment]
ready to merge, IMHO

**Comment by yorikvanhavre** [comment]
merged

**Pull request closed without merging**
