### PR TITLE
Use qOverload macro instead of QOverload

### PR DESCRIPTION
**Pull request by 0penBrain**

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9128">pipeline status</a> for feature branch [PR_9128](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9128). Pipeline [823457087](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/823457087) was triggered at [7706e6f](https://github.com/FreeCAD/FreeCAD/pull/9128/commits/7706e6f110e649dc346ee78a1122d77d22be2ec1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@donovaly @PaddleStroke May one of you test it compiles fine on Windows too please ? Thx

**Comment by PaddleStroke** [comment]
Yes it compiles.
Was that what you wanted me to try in previous PR? If so I misread and missed that the q was not a cap, I tried QOverload and not qOverload when you told me.

**Comment by 0penBrain** [comment]
> Yes it compiles. Was that what you wanted me to try in previous PR? If so I misread and missed that the q was not a cap, I tried QOverload and not qOverload when you told me.

Yes it was. Indeed there a subtile difference in the `q` capitalization. :)

Now you know. ;)

**Pull request merged**
