### PR TITLE
Sketcher: add TypeId checking helpers

### PR DESCRIPTION
**Pull request by FlachyJoe**
in order to replace
```cpp
geo->getTypeId() == Part::GeomEllipse::getClassTypeId()
```

with
```
Sketcher::isEllipse(*geo)
```

### CODE REVIEW

**Comment by 0penBrain** [comment]
Would be better to use reference rather than pointer as argument. Methods aren't supposed to handle null pointer (and actually fail to do). 😉

**Comment by FlachyJoe** [comment]
>  use reference rather than pointer as argument.

Notice that the replaced lines don't check for null pointer but I'll follow your advise so the usage could be extend.

Some other functions in Utils.cpp should be changed too, for example:
```cpp
bool SketcherGui::isBsplinePole(const Sketcher::SketchObject* Obj, int GeoId)
{

    auto geom = Obj->getGeometry(GeoId);

    return isBsplinePole(geom);
}
```

**Comment by 0penBrain** [comment]
Maybe I was unclear. You can keep the references as const. 😉

**Comment by FlachyJoe** [comment]
Fixed + Rebased + Squashed

**Comment by chennes** [comment]
@wwmayer what are your thoughts on this? It's not quite the solution you proposed, but at least the methods are base class members now.

**Comment by wwmayer** [comment]
> what are your thoughts on this?

As a first step this is totally fine. 

> It's not quite the solution you proposed

I have offered some more alternatives but this one is fine, too.

**Pull request merged**
