### PR TITLE
(GUI) Delete dark behave.

### PR DESCRIPTION
**Pull request by MisterMakerNL**
So reason for deleting the Dark behave:

- Not uniform to Freecad style.
- Dark name is confusing towards user.
- There isn't really the need to add another dark style since users can just install them true the addon browser.
- If we want to include other styles we should include them as addons.

This is also requested by @maxwxyz @kadet1090 and I think everyone from the @FreeCAD/design-working-group agrees on this.

Tagging @Syres916.

### CODE REVIEW

**Comment by Syres916** [comment]
I was under the impression that the Maintainers had given their ruling on this only weeks ago with specific mention from @chennes that if a stylesheet is community maintained then there is no justification to just delete it. Has it suddenly become unmaintained, the following links would suggest otherwise:


https://github.com/FreeCAD/FreeCAD/commit/245e66ed3a7eaf6e315947f33596f6f3c729e1ff
https://github.com/FreeCAD/FreeCAD/compare/main...Syres916:FreeCAD:Behave_Dark_Improvements


If the Maintainers are now going to reverse their decision so soon and regarding a stylesheet that has been in core since September 2020 based on the excellent work by @Chrismettal which was encouraged by @luzpaz on the forum to be brought into core and was merged by @yorik, do they regret that and now want it expelled from core?

Will the DWG be dealing with all the annoyed user base on the forum who upgrade from 0.20 or 0.21 to find their screen colors have changed without even the slightest explanation on startup or will that just be left for the forum regulars to answer?

As it's been part of both the 0.20 and 0.21 releases and used by a significant minority of the community then IMHO it's time for escalation to the FPA. If the FPA no longer support community maintained stylesheets in core and believe that it should be dumped on the shoulders of one person then I believe it's only correct for them to create an Announcement on the forum to that effect. All this should be taken into account when bearing in mind the following quote of the FPA Annual Report:

"In 2024 the FPA is determined to taking special care of the places where the FreeCAD community meets, and put more effort to make sure everybody feels welcome and safe, and that communication flows nicely among everybody."

This feels very close to the opposite of that mantra from my side of the screen.

**Comment by chennes** [comment]
We are going to keep all of the stylesheets that were once in the main repo -- they are going to be moved to a (still to-be-created) FreeCAD-themes repo. I just haven't had a chance to actually make that change yet. I'm sorry for the delay on getting that done.

**Comment by chwt163** [comment]
Sorry I saw this post a bit late, I hope no final decision has been made yet, I would like to keep the dark behaved theme. In my Manjaro Plasma6 system, Dark Behavior is almost the only dark theme that works. It looks the same as on Windows, and other themes have more or less problems on Linux.

This is the dark-blue theme：


This is the prodark theme：


This is the dark-behave theme, it looks good, it's just that the color is too dark：


Here's my modified dark-behave, which basically just changed some colors, and some other details:

**Comment by MisterMakerNL** [comment]
I kinda don't understand what you get with having it in the main repro, like you can update stylesheets as an addon. You cannot really do this if it's in main. I even have an addon for built-in-stylesheets exactly for this.
Only reason to include the 2 that are in now, is so there is a basis too work with.
That's also why the new stylesheets are copies of no-stylesheet they are not my design, it's the basis and nothing fancy. If you want fancy get it in he addon browser.

**Comment by kadet1090** [comment]
The intention is not remove remove or restrict access to themes - only to move them out of core. Themes in core should be maintained collectively not by one person. I've created issue about theme discoverability that I intend to solve that week, which should improve things a bit and ease transition:
- https://github.com/FreeCAD/FreeCAD/issues/14929

**Comment by MisterMakerNL** [comment]
If the reason for having it in core because so users will find it we definitely should fix that.
By removing almost all the stylesheets in main I hopefully push the user towards the addon browser so every theme maker has his own chance to get his theme used.
One of the strong points of Blender is the addons, the Addon economy can be a big thing and I think even bigger in Freecad.
Freecad main shouldn't stop users for discovering these addons. Like if you got 5 dark theme's most of them not the best looking, your not really motivated to go to the addon browser try to find more.
If you got one or 2 basic theme's and you see everyone using other fancy theme's then you have to go too the addon browser.

**Comment by maxwxyz** [comment]
The possibility to update the theme independently from the FreeCAD install is a huge plus and also discoverability for new themes. Otherwise anyone can change one color of a default theme and want to merge it in main which leads to the current situation, 4 dark themes, none working 100% - just confusion.

**Comment by chennes** [comment]
See also https://github.com/FreeCAD/FreeCAD-themes

**Comment by MisterMakerNL** [comment]
Please don't be personal, I got multiple requests to delete Behave. I got other things to do then debate this, to be honest.
And I know there is some debate, that is why I didn't try to sneak it in a PR.
I also only made this PR after people kept asking it. I kinda didn't want to go down this rabbit hole I am in now.
I also tagged @Syres916 multiple times for a reaction on below questions if it can be removed.  But no reply.
https://github.com/FreeCAD/FreeCAD/issues/14745#issuecomment-2174942839
https://github.com/FreeCAD/FreeCAD/pull/13772#issuecomment-2174682494

I btw read this: https://github.com/Chrismettal/FreeCAD-Behave-dark/issues/1
And it clearly states that it is in because we couldn't install it true the addon browser.

**Comment by Chrismettal** [comment]
Not taking any if this personal. Just saying that, if requested to move Behave out if Core and into the Preference Pack, I need to be aware to do so.

**Comment by chwt163** [comment]
It's okay to remove the core and put it in add-ons, but I just want to optimize the theme on the Linux system

**Comment by Syres916** [comment]
@MisterMakerNL with the improvements in https://github.com/FreeCAD/FreeCAD/pull/15051#issuecomment-2198600487 , the FreeCAD-themes addition and assuming the CI tests pass I'm happy with this PR.

**Pull request merged**
