### PR TITLE
Gui: improve performance of macro execution and fix time measurement

### PR DESCRIPTION
**Pull request by bdieterm**
This commit improves the performance of Python code from FreeCAD macros by:
* using the chrono C++ stdlib header instead of QTime
* checking for the elapsed time ONLY every 1000th Python opcode execution

And this commit fixes time measurement by using a monotonic time source instead of a normal one.
The previous implementation using QTime would give a negative time duration if the start time is 23:59:59 and the end time is 00:00:01.

related commit: e78f74b01a44bce0853a847252ec5f33294e1c36

### CODE REVIEW

**Comment by maxwxyz** [comment]
@chennes could this be considered as a fix for 1.0 or should it be post 1.0?

**Comment by Jolbas** [comment]
Could it be ok to just check every 100_000th python opcode instead? Then the python execution time is hardly affected at all. At least my system still feels fully responsive while python code is running. Even 10_000_000 is ok at my system.

**Comment by Jolbas** [comment]
It works very well with every 1000th too. I must have missed something at my first tests. Your fix makes the test script in #15846 run in 0.12s instead of 0.05s with Python profiler interval set to 0. I actually don't get faster times increasing the skip count.

**Comment by 3x380V** [comment]
@bdieterm, you might as well modify `TimeElapsed` class to fit your needs.

**Comment by bdieterm** [comment]
> you might as well modify TimeElapsed class to fit your needs.

Thanks for the hint. I even considered that when writing the commit for this PR.

There are some things I did not like about using the `TimeElapsed` class in file TimeInfo.h.
`TimeElapsed` is only a very thin wrapper to a basic class from the C++ standard library.
In my opinion it does not bring any benefit but only confusion. It even lacks assignment and move operator.

For this task it would be necessary to create two `TimeElapsed` instances and then call static method `diffTimeF` with two `TimeElapsed` arguments. This is not only difficult to read (you don't know if it is `a - b` or `b - a`) but it makes also no sense to me. Calculating the difference between two TimePOINTs and obtaining a TimeDIFFERENCE object would be more logical IMHO.
The `TimeElapsed::diffTime` method (without the "F") is also strange. It returns the time difference as a string.

I think the current code of this PR which uses the C++ libs directly, is easy enough to understand.

**Comment by 3x380V** [comment]
I agree with all your points. When rewriting internals of this class I didn't touch its interface too much. So if there is a chance to improve it now, it can be improved. As it is marked post 1.0 material, there is plenty of time.

**Comment by maxwxyz** [comment]
@bdieterm are you planning on changing the PR or is this good to go?

**Comment by bdieterm** [comment]
Actually I would prefer to not need this mitigation of the slow-down caused by #10587 and have back the old behavior from FreeCAD v21.2.
But now that we have this GUI-freezing prevention, we should at least not slow down script execution too much.

So, this is good to go.

**Pull request merged**
