### PR TITLE
Translate Techdraw ISO templates into Catalan

### PR DESCRIPTION
**Pull request by dplanella**
Based on https://github.com/FreeCAD/FreeCAD/pull/13368, this PR adds the Catalan translation for the Techdraw ISO templates. As such, https://github.com/FreeCAD/FreeCAD/pull/13368 would need to be reviewed and merged first.

### CODE REVIEW

**Comment by WandererFan** [comment]
"Merge attempt failed This branch can't be rebased"

Not sure why I get this message.  Updating the branch from main.

**Comment by dplanella** [comment]
I could not easily rebase either. I noticed the conflicts attempting to rebase, but I do not know where they come from. To keep it simple and to reduce the risk of breaking something, I did a new merge from main to keep the branch up-to-date for now. If it keeps getting outdated before being merged, I might as well resubmit it as a new branch rather than spending time on figuring out the rebase conflicts.

**Comment by WandererFan** [comment]
Some of these commits are already in main?

We'll see if #13500 works.

**Comment by WandererFan** [comment]
#13500 adds the Catalan directory and templates.  

@dplanella please check main.  I think all of the changes in this PR are now in main.

**Comment by dplanella** [comment]
@WandererFan they are now, thanks! Closing this PR as superseded by https://github.com/FreeCAD/FreeCAD/pull/13500

**Pull request closed without merging**
