### PR TITLE
Draft_Layer_Override

### PR DESCRIPTION
**Pull request by JeromeL63**
Separate Line color and shape color override

### CODE REVIEW

**Comment by vocx-fc** [comment]
Just for reference: this pull request includes several changes in style to the source code; namely, a space is added after each comma. This is a good thing, and it improves compatibility with Python's PEP8 guidelines.

**Comment by berndhahnebach** [comment]
But it is a poor git history to make code changes and format changes in one commit. It is very difficault to fine what has changed in the code and what is just formating change ...

What happens if a file is loaded which has layers with "OverrideChildren" property? Does this make problems?

**Comment by vocx-fc** [comment]
I agree. Maybe Jerome can once more break the pull request into two commits. One introducing the new functionality, and the other one with the formatting improvement.

**Comment by JeromeL63** [comment]
> Yes this is a good thing, but it is a poor git history to make code changes and format changes in one commit. It is very difficault to fine what has changed in the code and what is just formating change ...
> 
> What happens if a file is loaded which has layers with "OverrideChildren" property? Does this make problems?

It simply do nothing, no crash. But layer have to be re created to have feature.
About code formating, i didn't know that i formated it ! Pycharm IDE automatically format code.
I'm sorry for the work you do for just one feature

**Comment by berndhahnebach** [comment]
Would it be possible to just solve the conflicts?

**Comment by berndhahnebach** [comment]
here is how I would merge it into master. Any comments on this? https://github.com/berndhahnebach/FreeCAD_bhb/commits/bhbdev231

bernd

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/2811  (this one was merged)

**Pull request closed without merging**
