### PR TITLE
Draft: Fix and clean up ToDo helper class

### PR DESCRIPTION
**Pull request by matthijskooijman**
This PR fixes an issue with the Draft ToDo class where it would add multiple timers and, when the ToDo items would take long, could cause them to be executed twice, leading to a crash. See the commit messages and [this forum thread](https://forum.freecadweb.org/viewtopic.php?f=23&t=59373) for more details.

In addition to fixing the issue, this PR also cleans up the ToDo class, removing duplicate code, generalizing the code, cleaning up comments and improving the interface. The actual bugfix is in the first commit, so if this is merged, that commit should probably be backported to 0.19 (maybe also the second commit, though I'm not sure if that situation can actually occur, so maybe not needed).

All fixes and cleanups are separated in a small commits, to simplify review and history viewing later. Reviewing this PR is probably best done commit by commit, though because the total change is not too big and mostly contained to the ToDo class, you could also just look at the total diff and see if the resulting code is ok :-)

This PR is still a draft because:
 - I still have to do a proper review myself (but ran out of time for now and did want to share my progress so far).
 - It has been rebased on master, but I have only tested it on a few weeks old version (need some time to compile master again).
 - There is a change that breaks compatibility that probably needs to be fixed first (see below).
 - I still have to do some more thorough testing.

Wrt compatibility, commit abdd48f4e331feeb27500ade852feef2de61563b modifies the interface of the `ToDo.delay` and `ToDo.delayAfter` functions. Previously, you would pass a function and an argument to them, and that function would be called with that argument. If the function does not accept an argument, you could pass any falsey value (e.g. `ToDo.delay(func, None)`) which was handled specially by calling the function with arguments (with one exception: if you passed `False`, it *would* be passed on as-is).

I do not really like this interface, since it is not really clear and predictable (also, you can not pass e.g. `None` to a delayed function now). Also, Python offers better mechanisms for this (variable argument handling), so I changed `ToDo.delay` and `Todo.delayAfter` to accept a function followed by any number of arguments to be passed to that function. This means you could simply pass no arguments if your function needs no arguments (e.g. `ToDo.delay(func)`, but also pass multiple (e.g. `ToDo.delay(func, 1, 2)`), which is nicer and more flexible.

However, this means that existing code that passes a `None` (or `[]` is also used it seems) will now break: `ToDo.delay(func, None)` will end up calling `func(None)` instead of `func()`.

I can think of a few ways to fix this:
 1. Keep the special handling of a single argument that is falsey (but not `False`) and if so, drop that argument. However, this would mean that the surprising handling is kept around (i.e. you cannot pass `None` to a delayed function). Some of this suprise could maybe be avoided by introspecting the function and only applying this special handling if the function accepts no arguments, but that probably makes things even more complex.
 2. Rename these two functions, applying the new interface to the new name and keeping the old interface for the old names. Would be easy without needing to duplicate code, but does require coming up with new names and changing a lot of code (though that could be an opportunity to change `todo` to `ToDo` everywhere as well maybe).
 3. Keep the old interface for e.g. `todo.delay()` and the new interface for `ToDo.delay()`. This would still break existing third-party code that uses `ToDo.delay()`, but that code could then at least be updated to switch back to `todo.delay()` if they need to support 0.19 and before, or use the new interface with `ToDo.delay()` if they're ok with supporting only 0.20 and above.

I think option 2. would be the cleanest, if we can come up with some reasonable alternative names :-)

 -  [X]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [X]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [X]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  ~~Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`~~

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Excellent effort, and highly welcome! Will give it a test too ASAP

**Comment by matthijskooijman** [comment]
@yorikvanhavre Thanks!

One thing that came up in the thread, is why is this ToDo class needed at all? @carlopav suggested that it is unique to Draft and that e.g. Arch does not actually use it (at least not for committing changes). From what I've seen, it looks like the problem is that when inside a coin event handler, changing the document (which probably changes the coin datastructure as well) causes coin to crash (I've seen a case where coin is looping over a list to emit events and it looks like the list is changed or deleted, causing a crash, see the forum topic for details). That would make sense, but then I wonder: Why is this only a problem in Draft? Do Arch and other WBs solve this problem differently? If so, should draft be changed to do the same, instead of cleaning up the ToDo class like I did here?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by donovaly** [comment]
@Roy-043 can you please have review this PR?

**Comment by berndhahnebach** [comment]
BTW: for the CI to run this needs to be rebased

**Comment by luzpaz** [comment]
@matthijskooijman please rebase

**Comment by matthijskooijman** [comment]
I don't currently have a working FreeCAD environment here and am quite busy, so it might take me a while to rebase this.

In the meanwhile, I'd welcome a response to https://github.com/FreeCAD/FreeCAD/pull/4859#issuecomment-861535305 since depending on the answer, maybe a different refactoring might be a better approach...

**Comment by luzpaz** [comment]
This PR is rotting. Any possibility we can resurrect it?

**Comment by carlopav** [comment]
Well, i'm Sorry, but i'm in a crazy working time since more than one year, and i'm completely out of spare time.
The tool is available as "Tweak" command in Design456 workbench, if anyone wants to test or use It.
If you find useful to have It inside Draft as It Is now I can Plan a weekend rush to complete the integration in a new command or as a option in Draft_Move. But we can also close the PR...
@yorikvanhavre what do you think?

**Comment by matthijskooijman** [comment]
I needed FreeCAD again for something this week, so I took the opportunity to set up my dev environment again and have rebased this PR on top of master. I have also tested the testcase from [the forum thread](https://forum.freecadweb.org/viewtopic.php?f=23&t=59373) again and noticed that with the current (unpatched) master, it no longer crashes, but it does still apply the move twice and shows this error:

    41.6214 <App> Document.cpp(3451): Recursive calling of recompute for document Window_copy_crash

With this PR applied, the move is done correctly (once), and the error message is not shown.

I have not done any other testing yet, but will be running with these changes applied for my upcoming work.

Also, there are still unanswered questions, see the original post and https://github.com/FreeCAD/FreeCAD/pull/4859#issuecomment-861535305

> Well, i'm Sorry, but i'm in a crazy working time since more than one year, and i'm completely out of spare time.
The tool is available as "Tweak" command in Design456 workbench, if anyone wants to test or use It.
If you find useful to have It inside Draft as It Is now I can Plan a weekend rush to complete the integration in a new command or as a option in Draft_Move. But we can also close the PR...
@yorikvanhavre what do you think?

@carlopav I'm not sure what you are saying here? This PR is about fixing the ToDo utility class in draft, not adding or fixing a specific tool. Are you sure you commented about the right PR?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_4859">pipeline status</a> for feature branch [PR_4859](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_4859). Pipeline [496539290](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/496539290) was triggered at [22ff172](https://github.com/FreeCAD/FreeCAD/pull/4859/commits/22ff1722c0857b094ee7843eb439fed4d9c5341a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@matthijskooijman , when you have time to work on this, please finish the PR and then reopen it.

Closing for now.

**Comment by matthijskooijman** [comment]
> @matthijskooijman , when you have time to work on this, please finish the PR and then reopen it.

I am still waiting on responses to questions to move forward, this is not blocked on available time on my end currently.

**Comment by donovaly** [comment]
> I am still waiting on responses

Where did you post them? Maybe just report them in the developers forum.

**Comment by matthijskooijman** [comment]
https://github.com/FreeCAD/FreeCAD/pull/4859#issuecomment-861535305 (with a reminder in https://github.com/FreeCAD/FreeCAD/pull/4859#issuecomment-1013338095 and https://github.com/FreeCAD/FreeCAD/pull/4859#issuecomment-1073254489).

Posting in the forum is a reasonable idea, but I won't have time for that at least this week (and after that, I might forget...).

**Comment by donovaly** [comment]
I see. However, posting in PRs is not that effective for questions like these. The PRs get closed and then people forget about it.

Therefore please open a new thread here: https://forum.freecadweb.org/viewforum.php?f=10
this assures that several people see it and it is properly documented.

**Pull request closed without merging**
