### PR TITLE
Format Dxf Group Codes as 3 chars

### PR DESCRIPTION
**Pull request by WandererFan**
This PR formats Dxf Group Codes as 3 characters as required by newer versions of Dxf.  Please merge. 
Thanks,
wf

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by WandererFan** [comment]
Boost not found errors in 2x Linux builds on Travis

 Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:603 (find_package)
CMake Error at CMakeLists.txt:612 (MESSAGE):
  ========================================
  boost not found, install the components:
   * filesystem
   * program_options
   * regex
   * signals
   * system
   * thread
  ========================================

**Comment by yorikvanhavre** [comment]
The "boost not found" problems happens from time to time on travis... Usually it's just a matter of restarting the job. Let's wait for this one to finish...

**Comment by WandererFan** [comment]
All checks passed this time!

**Comment by yorikvanhavre** [comment]
merged!

**Pull request closed without merging**
