### PR TITLE
Step

### PR DESCRIPTION
**Pull request by vejmarie**
This patch is taking care of STEP Assembly within our Step Import reader and create the associated tree within our UI

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I'll let this one for you @wwmayer if you dont mind

**Comment by vejmarie** [comment]
Hi Yorik, no problem. What looks like complex to you in this code ? If i can help do not hesitate. easywfc tested the code on linux and it did worked, he was the bug reporter on the forum.

**Comment by yorikvanhavre** [comment]
@vejmarie your code looks perfect to me, but since my knowledge of C++ is ridiculous (of STEP too actually), I prefer to let Werner look at it before commit. It already happened too many times that I commit pretty huge mistakes, one becomes careful :)

**Comment by vejmarie** [comment]
@yorikvanhavre the code is not perfect unfortunatly, this is a step forward to improve the STEP reader ;). I still have some homework to improve color rendering and export feature, but I am trying to make it happen in a step by step approach ;). Variable naming is not good at all either. But I will impove that later on.Let's wait for @wwmayer  feedback !

**Comment by wwmayer** [comment]
Functionality-wise the code looks good to me. However, I will have to beautify the git history and do some clean-up work in the code.

**Comment by wwmayer** [comment]
Merged.

Is it intended to added eventually a null pointer to lValue?

`
            if (pcCompound)
                pcCompound->Links.setValues(localValue);

            lValue.push_back(pcCompound);
`

If not you can fix this in a future PR.

**Comment by vejmarie** [comment]
Yep it was, I don't remember why unfortunatly. I will rerun my test bench on top of master to see if I got a crash somewhere. Thanks for the integration.

**Pull request closed without merging**
