### PR TITLE
[TD] fix balloon and dimension dialog rejection

### PR DESCRIPTION
**Pull request by donovaly**
the balloon and the Dimension dialog did not restore the previous settings when the user press Cancel

The PR also adds a missing recompute, reported as bug B. in https://forum.freecadweb.org/viewtopic.php?p=474482#p472939

### CODE REVIEW

**Comment by wwmayer** [comment]
This is not the correct way to handle the restoring of properties when rejecting the changes. And it's error-prone as you always need to adjust the code when a new property have been added.

The way to work with transactions is:
For Accept:
```
openTransaction("Change object");
# change the various properties
...
commitTransaction();
```

For Revert:
```
openTransaction("Change object");
# change the various properties
...
abortTransaction();
```

**Comment by donovaly** [comment]
> The way to work with transactions is:...

Thanks for having a look. I'll try to fix this.
I took the method I used here from other TD dialogs so there are more dialogs to be fixed.

(That's why I often wrote we should taking a breath to take care to fix such long-standing issues in a feature freeze. Now I cannot promise I will have the time to do this work in the remaining 9 days. The feature freeze is too short and still not al pending PRs are in to be tested by the crowd.)

By the way, can you please look at the long-standing PR #3893  that one fixes annoying things I see frequently when working with FC.

**Comment by wwmayer** [comment]
> Thanks for having a look. I'll try to fix this.

No need. I am working on it right now. There are a few more issues to fix.

**Comment by wwmayer** [comment]
bb0d75b6cc fixes of the balloon feature

**Comment by wwmayer** [comment]
3288c02eba fixes of the dimension feature

**Comment by wwmayer** [comment]
So this PR has become obsolete.

**Comment by donovaly** [comment]
Thanks. However, with your commits I cannot undo changes and also pressing Cancel in the dialog is not respected, see https://github.com/FreeCAD/FreeCAD/commit/bb0d75b6cc29dcc722b6596b180fd8d205f5073b#commitcomment-47057145 for a recipe how to reproduce.

**Pull request closed without merging**
