### PR TITLE
[FEM] pressure constraint overhaul

### PR DESCRIPTION
**Pull request by donovaly**
- add missing binding to pressure value in dialog
- make pressure a property with unit to get rid of hacks

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9097">pipeline status</a> for feature branch [PR_9097](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9097). Pipeline [819834466](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/819834466) was triggered at [a9fc2d7](https://github.com/FreeCAD/FreeCAD/pull/9097/commits/a9fc2d7be675b9f46c2e9ee3253e795cf487ce99). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
same as #9096

Because this changes many file IMHO it should be splitted into multiple commits for a better overview and better review

- implementation 
- update of the examples with unit tests and the unit tests
- update of the examples without unit tests

BTW great addition 👍

**Comment by FEA-eng** [comment]
> I think there is nothing preventing to merge this... @FEA-eng @donovaly any of you would mind looking at the conflicts?

I can build and test this on Ubuntu but I'm not familiar with the source code so I won't be able to help if there are coding issues.

**Comment by luzpaz** [comment]
@marioalexis84 can you rebase this PR so testers can test it ?

**Comment by marioalexis84** [comment]
On the weekend I can do the rebase and split into several commits

**Comment by sliptonic** [comment]
Thanks @marioalexis84.   I'm moving this to draft until you're ready.

**Comment by marioalexis84** [comment]
@sliptonic this is ready.  Should I create a new pull request with the changes?
Note that the examples work even though the materials are broken, since the values are set manually in the test files.

**Comment by sliptonic** [comment]
Not necessary.  When ready, you just click the 'Ready for review' button and it will convert to a regular PR.  I'm doing that now.

**Comment by sliptonic** [comment]
But Github is still showing conflicting files

**Comment by sliptonic** [comment]
> I haven't pushed the changes yet. How I perform a force push to the donovaly branch? I do not have write permissions to that repository.

Oh, yeah.  That you can't do.   You'll have to create a new PR.   I'm closing this one with this comment.

**Pull request closed without merging**
