### PR TITLE
[Build system] Fix CMake warning

### PR DESCRIPTION
**Pull request by f3nix**
qt5_make_output_file is not part of the official API, and might be removed in Qt 6.

Only tested with:
- Qt 5.15.2
- CMake 3.18.4
- Debian Linux

Cheers,
Mateusz

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Although the Windows builds says it succeeded it failed with this error:
`C:\Users\travis\build\FreeCAD\FreeCAD\src\Gui\GraphvizView.cpp(574): fatal error C1083: Cannot open include file: 'moc_GraphvizView.cpp': No such file or directory [C:\Users\travis\build\FreeCAD\FreeCAD\build\src\Gui\FreeCADGui.vcxproj]`

The Linux builds stops when it fails to generate 'moc_GraphvizView.cpp

**Comment by f3nix** [comment]
Hi.
I have to create a VM with older CMake / Qt.

Will get back to it soon.

Cheers,
Mateusz

**Comment by wwmayer** [comment]
I guess the PR is ready for review?

**Comment by f3nix** [comment]
Hello @wwmayer .

It should be ready for review / testing now.

I've managed to test it on Linux only.

Cheers,
Mateusz

P.S. After some testing it seems this adds only about 9 second to build time on my system.

**Comment by wwmayer** [comment]
> P.S. After some testing it seems this adds only about 9 second to build time on my system.

That's acceptable I think. But nevertheless it would be good to exclude targets that will never need to be moc'ed. It looks like setting `set(CMAKE_AUTOMOC FALSE)` in the corresponding CMake files does the trick.

If have tested the PR on Linux and Windows and it works fine as long as you start with a clean build. However, for existing builds the copied mtextedit.h to the output directory causes automoc to generate linking errors because it compiles both headers from both locations.

I found a hack by removing mtextedit.h from the output directory and touching the file of the source directory. This seems to heal the automoc failure.

**Comment by wwmayer** [comment]
See ee98ed5bafab4a2

**Comment by f3nix** [comment]
Thanks @wwmayer ! :)

**Comment by f3nix** [comment]
> See [ee98ed5](https://github.com/FreeCAD/FreeCAD/commit/ee98ed5bafab4a2f83f2f5e51b3f20259594bf92)

I think it can be removed in the near future when all interested people have rebuilt their sources with this fix.
Thanks for your work.

I will keep an eye on it.

Cheers,
Mateusz

**Pull request merged**
