### PR TITLE
Migrate Suzzane Soy's `SearchBar` to FreeCAD

### PR DESCRIPTION
**Pull request by ToddG**
**WHAT**
Per request by .. on FC forum and [#8290](https://github.com/FreeCAD/FreeCAD/issues/8290), migrate Suzzane Soy's `SearchBar` into FC.

**WHY**
See #8290 

**HOW**
Follow instructions here:

https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

```
cd path/to/project-a
git checkout some-branch

cd path/to/project-b
git remote add project-a /path/to/project-a
git fetch project-a --tags
git merge --allow-unrelated-histories project-a/some-branch
git remote remove project-a
```

**VERIFICATION**
Tool seems to work as advertised. I created these artifacts using the search bar.
search-bar-enabled

### CODE REVIEW

**Comment by luzpaz** [comment]
what the heck is going on here? lol   
It looks like you just copied the whole addon into core...like everything even the package.xml file...

**Comment by ToddG** [comment]
1. @luzpaz Yes, I literally just merged in Suzzane's repo. While I'm a developer, I know nothing about the FC codebase or Qt.
2. Per @pierreporte 's comments in the forum, I've moved this to Draft.
3. Unfortunately, I had thought I had this building and working locally, but then realized that FC loads config and installed tools from a common directory. So, while I've ported the code into this branch, I'll need some help getting it to launch at startup, as well as configuring a hotkey to put focus in this widget.

**Comment by pierreporte** [comment]
Do you plan to open a new PR later? I've seen you have an other branch for this in your repository.

**Comment by ToddG** [comment]
@pierreporte I just opened a draft for this same work here: https://github.com/FreeCAD/FreeCAD/pull/16160

**Pull request closed without merging**
