### PR TITLE
Path | RRF (RepRapFirmware | Duet Boards) PP 

### PR DESCRIPTION
**Pull request by P-C-R**
###  A Postprocessor for boards running RRF

Some users (including me) are running CNC machines with [https://www.duet3d.com](https://www.duet3d.com)
The boards are running RRF ([https://github.com/Duet3D/RepRapFirmware](https://github.com/Duet3D/RepRapFirmware)). Which has slightly different gcode syntaxes and rules than marlin or smoothiware. Full list here [https://duet3d.dozuki.com/Wiki/Gcode](https://duet3d.dozuki.com/Wiki/Gcode).

So i adjusted the marlin_post.py to fit the RRF Code

some changes with the help of the freecad forum

* RRF wants mm/min
* RRF wants toolchanges with only the toolnumber  in full integer `M6 T1.0` becomes `T1`
* Includes some info about using RRF in cnc mode.

Its no big PR. Mostly some Quality of Life imrpovements that not everbody has to modify the marlin PP

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5228">pipeline status</a> for feature branch [PR_5228](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5228). Pipeline [423702799](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/423702799) was triggered at [9f9709c](https://github.com/FreeCAD/FreeCAD/pull/5228/commits/9f9709c7a320f1d0d5560dc127c8793111ae8d7d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@P-C-R have you connected with the Path devs about this PR?

**Comment by P-C-R** [comment]
Not yet. After my last PR was closed I made this one with more detailed
description ;)

luzpaz ***@***.***> schrieb am Fr., 31. Dez. 2021, 04:49:

**Comment by Syres916** [comment]
Each of the three hyperlinks in the description of this PR don't actually point at the address shown, could this please be corrected.

**Comment by P-C-R** [comment]
> Each of the three hyperlinks in the description of this PR don't actually point at the address shown, could this please be corrected.

done

**Comment by luzpaz** [comment]
Oh OK, so @P-C-R what is left with this PR then?

**Comment by P-C-R** [comment]
Nothing. Just waiting for feedback from freeCAD devs..

luzpaz ***@***.***> schrieb am Mo., 3. Jan. 2022, 21:11:

**Pull request merged**
