### PR TITLE
CMake: Add inter-module dependency of Part on Material

### PR DESCRIPTION
**Pull request by cjmayo**
Building with -DBUILD_PART=ON and -DBUILD_MATERIAL=no fails with:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lMaterials: No such file or directory
collect2: error: ld returned 1 exit status
```

### CODE REVIEW

**Comment by chennes** [comment]
@maxwxyz actually this probably needs to go in 1.0 -- and if we merge @davesrocketshop 's latest PR, we will also then have a dependency in PartDesign as well.

**Comment by davesrocketshop** [comment]
I still have no idea why that flag exists. It's was never intended to be possible to build without materials.

**Comment by chennes** [comment]
Well, it's basically the same as with Part itself: who builds FreeCAD without Part?! But every individual module gets the flag.

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
