### PR TITLE
[0.18] FEM: Py3 fix in result reader

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

without this fix constraint nonlinear material and temperature does not work at all with calculix because results could not be read at all if these constraints are used.

It seams today I was the first ever on Python 3 who used these constraints ...

on 0.19 this commit is included in another PR from myself

### CODE REVIEW

**Comment by berndhahnebach** [comment]
to test load the 3D FEM cantilever beam, add a nonlinear material and run an analysis ...

**Comment by wwmayer** [comment]
These changes were part of a previous PR. See 7dfeb801a1265dd8

**Comment by berndhahnebach** [comment]
Werner I know ... This PR is for version 0.18 !  There is a Python 3 problem which makes it impossible to read result data. I consider this a but we should fix in 0.18.

**Comment by wwmayer** [comment]
OK, I see. Here I have a list of commits that should be back ported: https://forum.freecadweb.org/viewtopic.php?f=10&t=34981&p=294265#p294265
Maybe I should split this post and move it to its own topic

**Comment by wwmayer** [comment]
New location: https://forum.freecadweb.org/viewtopic.php?f=10&t=35350

**Pull request closed without merging**
