### PR TITLE
Toponaming card 2

### LINKED ISSUE #10354: [Issue] TopoNaming Phase 3 (card 2 of 35) - Add History Support/Part Workbench/PartFeature
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Part

### Problem description

This is a card for Toponaming fix Phase 3 (add naming) Part 1 (history expansion).

Please see TN issue https://github.com/FreeCAD/FreeCAD/issues/8432 for overall discussion.

Also see project https://github.com/orgs/FreeCAD/projects/2/views/1 for tracking.

Phase 3 does not USE the naming yet, that is Phase 4.

# Specifics

Naming is based on history. Add the RealThunder changes to history to expand it's support.

RealThunder reference branch: https://github.com/FreeCAD/FreeCAD/tree/development/toponaming

Do this for the files mentioned in the issue title. The few cards are generic and the remaining ones are for specific `Feature` elements in the related workbench.

Please add one or more unit tests.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Pesc0**
fixes #10354 

Right now it does not compile: it complains about the removed functions 
- `buildHistory`
- `joinHistory`

But from what I understand those should be addressed in other cards

### CODE REVIEW

**Comment by Pesc0** [comment]
Please check commits individually one by one!

**Comment by JohnAD** [comment]
Hmmm. Looks like I'll be meandering through the `toponaming` branch's commit history this weekend to learn more about how `buildHistory` was all refactored.

**Comment by Pesc0** [comment]
Missing functions in `Part::TopoShape`:
- `getSubTopoShape`
- `findAncestors`
- `setElementComboName`
- `decodeElementComboName`
- `setShape`
- `getElementHistory`
- `traceElement`
- `searchSubShape`
- `getRelatedElementsCached`
- `cacheRelatedElements`
- `TopoShape(long int&, App::StringHasherRef&, TopoDS_Shape&)`
- `makETransform`
- `indexPostfix`
- `makECompound`
- `mapSubElement`
- `Part::TopoShape Part::PropertyPartShape::_Shape` is private within this context

Missing functions in `App::LinkBaseExtension`:
- `getHiddenSubnames` 


`PartParams` has not been declared 
`PropertyShapeCache` has not been declared
Missing definition of `struct HistoryItem;`
`App::StringHasherRef` has no member `reset()`
`getElementReferences` is not a member of `App::PropertyLinkBase`

**Comment by chennes** [comment]
All of these cards are going to depend on TopoShape, aren't they? Which in turn needs the Base64 stuff in the PR I have open.

**Comment by Pesc0** [comment]
I have no clue how the freecad class inheritance tree is structured. If the classes in all next cards inherit/extend toposhape then the answer to your question is yes I think. 

On that topic, is there some kind of map / tree that shows how the classes inherit from each other, and explains what each class does? the other day I got lost in 7 (seven) layers of inheritance before giving up the chase for the base class

**Comment by Pesc0** [comment]
Looks like `PartParams` is an auto-generated file. 
1) why are there auto generated files in the codebase
2) how should i handle that?

**Comment by chennes** [comment]
Let's just directly access the needed parameters, instead of applying the cog-based refactor. IMO that refactor is out of scope for the toponaming project.

**Pull request closed without merging**
