### PR TITLE
[Core] Add possibility to set color with tuple of integers, fixes #8344

### LINKED ISSUE #8344: [Bug] App::PropertyColor erroneous behavior
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?t=75287

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 10
Word size of FreeCAD: 64-bit
Version: 0.21.0.31432 (Git)
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3

and

OS: Debian GNU/Linux 11 (bullseye) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.21.0.31599 (Git)
Python 3.9.2, Qt 5.15.2, Coin 4.0.0, Vtk 9.0.1, OCC 7.6.3
```

### Subproject(s) affected?

None

### Issue description

When setting the color, it is set not accurately. Let's say the user sets the color through the dialog: (r=50, g=100, b= 200). But FreeCAD will set the color as: (r=51, g=99, b=198).

Bug is confirmed in Windows and Linux operated systems.

More information on forum topic.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0penBrain**
Could have been solved by increasing decimal count to arbitrary number, but I thought it's better to add support for tuple of integers, so does this PR.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8438">pipeline status</a> for feature branch [PR_8438](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8438). Pipeline [774861350](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/774861350) was triggered at [a85e738](https://github.com/FreeCAD/FreeCAD/pull/8438/commits/a85e738fad65a5ee82c05759ecf2d56546fc6470). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
@donovaly does this need backporting ?

**Comment by donovaly** [comment]
> @donovaly does this need backporting ?

If possible, yes, please backport.

**Comment by 0penBrain** [comment]
> If possible, yes, please backport.

Done

**Comment by donovaly** [comment]
> Done

Merci beaucoup!
For information: We collect the backports in the initial post of this thread: https://forum.freecad.org/viewtopic.php?t=69437 You can edit this when you backported something (I already added this now).

**Pull request merged**
