### PR TITLE
[TD]Remove BOM in exported Svg

### PR DESCRIPTION
**Pull request by WandererFan**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
The following SVG files cannot be displayed by GitHub. It says the files are "invalid". Maybe it's worth checking the files to make sure they work before adding them.
* `ConcentricityFrame.svg`
* `CylindricityFrame.svg`
* `FlatnessFrame.svg `
* `ParallelismFrame.svg`
* `RoundnessFrame.svg`
* `SquarenessFrame.svg `

**Comment by WandererFan** [comment]
They all load and save in TD and Inkscape.  Not sure what Github's issue
is.

Thanks for pointing this out.

**Comment by WandererFan** [comment]
Travis status reporting seems to be down again. 
[CI builds completed](https://travis-ci.org/github/FreeCAD/FreeCAD/builds/670377845?utm_medium=notification&utm_source=github_status)

**Comment by donovaly** [comment]
> They all load and save in TD and Inkscape.

Not here on Windows. GitHub is correct because the SVG violates the specifications. Also Firefox and  cannot display them. So every drawing with these SVGs included won't be displayed by the browsers.

The reason is the unbound <text> statement:
firefox_nL0Ou8brM0

I'll try to fix this later today.
In general, we should assure we only use plain SVG files. Some Inkscape specials never made it to the official SVG specifications and thus other programs than Inkscape cannot display them.

**Comment by donovaly** [comment]
Something is wrong with this commit because the SVGs are in the wrong folder:
 src/Mod/TechDraw/Symbols/gd-and-t/gd-and-t/
instead of
 src/Mod/TechDraw/Symbols/gd-and-t/

The new SVGs therefore don#t appear in the build folder. Can they be just moved one folder up please?

**Comment by donovaly** [comment]
Here is the PR: https://github.com/FreeCAD/FreeCAD/pull/3307

It fixes the SVGs and make them plain SVGs. It also moves them back tho the correct folder. The files deleted in the PR are already in the correct folder.

**Pull request merged**
