### PR TITLE
Gui: Improve localization support in VarSet dialog

### LINKED ISSUE #17472: VarSet: Dialog cannot be fully translated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The method uses a std::string to create the window title and assigns it to a QString. This way it's impossible for the i18n tools to pick up the string literal.

https://github.com/FreeCAD/FreeCAD/blob/499d192393d6ba71a7b04b0a0813a2c4789126c6/src/Gui/DlgAddPropertyVarSet.cpp#L174

The part `""Add a property to"` must be moved into `tr()`. And in order for the i18n tools to get the correct context this liine must be added (before the constructor): `/* TRANSLATOR Gui::Dialog::DlgAddPropertyVarSet */`

### Full version info

```shell
FreeCAD 1.1.0, Libs: 1.1.0devR39035 (Git)
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pieterhijma**
Closes #17472

### CODE REVIEW

**Comment by pieterhijma** [comment]
@wwmayer, I tried to test by changing the .ts file manually, but somehow the change isn't processed. This is the patch I used to test:

``` diff
diff --git a/src/Gui/Language/FreeCAD.ts b/src/Gui/Language/FreeCAD.ts
index 48f184090f..96f990eb07 100644
--- a/src/Gui/Language/FreeCAD.ts
+++ b/src/Gui/Language/FreeCAD.ts
@@ -8555,6 +8555,11 @@ underscore, and must not start with a digit.</source>
         <source>Add property</source>
         <translation type="unfinished"></translation>
     </message>
+    <message>
+      <location filename="../DlgAddPropertyVarSet.cpp" line="190"/>
+      <source>Add a property to %1</source>
+      <translation type="unfinished"></translation>
+    </message>
     <message>
         <location filename="../DlgAddProperty.cpp" line="151"/>
         <location filename="../DlgAddPropertyVarSet.cpp" line="272"/>
diff --git a/src/Gui/Language/FreeCAD_nl.ts b/src/Gui/Language/FreeCAD_nl.ts
index 7a31b4cefe..0fff3078d1 100644
--- a/src/Gui/Language/FreeCAD_nl.ts
+++ b/src/Gui/Language/FreeCAD_nl.ts
@@ -8623,6 +8623,11 @@ underscore bevatten en mag niet beginnen met een cijfer.</translation>
       <source>Add property</source>
       <translation>Voeg eigenschap toe</translation>
     </message>
+    <message>
+      <location filename="../DlgAddPropertyVarSet.cpp" line="190"/>
+      <source>Add a property to %1</source>
+      <translation>Voeg een eigenschap toe aan %1</translation>
+    </message>
     <message>
       <location filename="../DlgAddProperty.cpp" line="151"/>
       <location filename="../DlgAddPropertyVarSet.cpp" line="272"/>
```

I verified that the string is in the generated .qm file. I don't understand why this doesn't work, perhaps the change of context?

**Comment by wwmayer** [comment]
> I don't understand why this doesn't work, perhaps the change of context?

Yes, it's the wrong context. And also all the strings that are already inside the .ts files have the wrong context, too. It's `QObject` instead of `Gui::Dialog::DlgAddPropertyVarSet`. This happens because everywhere in your code you use `QObject::tr()` instead of simply `tr()`.

Whenever possible it should be avoided to use `QObject` as context because for translators it's not clear where a string comes from. Instead all classes that inherit from `QObject` should use the `Q_OBJECT` in the class declaration and use `tr()` to mark string literals.

If a class doesn't inherit from `QObject` but you still want a specific context you can use:
`QCoreApplication::translate("MyContext", "My string literal"); `

**Comment by pieterhijma** [comment]
@wwmayer: Right, got it. Now it works as expected. 

The inspiration for this dialog was `DlgAddProperty` that makes use of `QObject::tr`, so I simply did this as well. 

From your answer, I understand that you would prefer to have a separate context for `DlgAddProperty` as well. In that light, given how close we are to a release, I can basically do two things:

- In `DlgAddPropertyVarSet` use `QObject::tr` consistently everywhere to make it similar to `DlgAddProperty`. Perhaps file an issue to fix this later in both dialogs.
- Use the correct context for `DlgAddPropertyVarSet` immediately and file an issue for `DlgAddProperty`.

I cannot overlook how much of an issue it is for translators if there are context changes.

**Comment by wwmayer** [comment]
For now you can leave `QObject::tr()` but open a ticket to fix this for post-1.0.

**Comment by wwmayer** [comment]
I think the code is ready to be merged.

**Comment by pieterhijma** [comment]
I removed the context comment and explicitly used `QObject::tr` to make it conforming the rest of the dialog and `DlgAddProperty`. I filed https://github.com/FreeCAD/FreeCAD/issues/17510 for post 1.0 to fix it after the release.

I made the change in a separate commit to allow inspecting the change but feel free to squash.

So, I think the code in this state is currently better to merge but feel free to drop the last commit.

**Pull request merged**
