### PR TITLE
[Path] set PathArea section tolerance to 1e-07.

### PR DESCRIPTION
**Pull request by sliptonic**
Section tolerance defaults to 1e-06.  This is the same as FreeCAD tolerance but means sectioned heights can give wonky results.

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7187">pipeline status</a> for feature branch [PR_7187](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7187). Pipeline [588042624](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/588042624) was triggered at [acf2a18](https://github.com/FreeCAD/FreeCAD/pull/7187/commits/acf2a186e5597e9014885ae4778ea90554becba7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by Russ4262** [comment]
If I may, I propose an alternate solution, extend the shape envelopes and translate the envelopes down to avoid the internal rounding issue.  On PocketShape and Profile ops, this will not cause any problem.  We and can ignore this solution for 3D Pocket ops since they are 3D and the nanometer error will likely not be a problem very often.  On the other hand, if we think it should be addressed in 3D Pocket also, we can also apply the extension and negative translation to those envelopes, using the geometry tolerance as the extension and translation values.

**Comment by Russ4262** [comment]
Or, another solution is to add a translation on the last section slice of the solid envelope, to ensure the height is exactly equal to the final depth requested.

**Comment by Russ4262** [comment]
Or, another alternative is to expose the SectionTolerance value to the user in the Path Preferences.

**Comment by sliptonic** [comment]
I don't see any benefit to the user.

**Pull request merged**
