### PR TITLE
Code cleanup& 3rd party library update

### PR DESCRIPTION
**Pull request by mosfet80**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by chennes** [comment]
Are you still working on this PR, or are you ready for some review comments?

**Review by mosfet80 — COMMENTED** [review]
Remove old library with 2 cve vulnerability

**Comment by luzpaz** [comment]
Make sure you're not context switching. Large PRs are hard to review (https://webchick.net/please-stop-eating-baby-kittens)

**Comment by mosfet80** [comment]
> If you are just working on some new code, and it's not ready for anyone to look at yet, you don't need to submit a PR -- just work off on your own branch, and submit a pull request when you're ready for others to look over your code.

for the moment I have only recompiled with processor optimizations, using the latest libraries, compiler and interpreter.
This was enough to obtain an excellent result.
During the various compilations I have come across obsolete libraries with known or no longer used vulnerabilities.
I found other code in the makefile that can be removed developed for Windows 98 (no longer supported), but it is not part of this block

**Comment by adrianinsaval** [comment]
what you said doesn't really address chennes' point... do you feel your changes are ready to be merged and want someone to have a look and consider merging or do you want to keep working until you achieve X objective then get reviewed? If the later mark your PR as draft or straight up close the PR and open again when your changes are ready for review. If it's ready, state so.

**Comment by mosfet80** [comment]
> what you said doesn't really address chennes' point... do you feel your changes are ready to be merged and want someone to have a look and consider merging or do you want to keep working until you achieve X objective then get reviewed? If the later mark your PR as draft or straight up close the PR and open again when your changes are ready for review. If it's ready, state so.

Before committing, I compiled and tested the program and it works. The Windows related parts of cmake are not testable by me and therefore have not been added to the commit. I know of this commit which started from a code cleanup and later a library update was added. Unfortunately I have encountered some vulnerabilities, which is why I believe they need to be updated as soon as possible. I would suggest doing the same on version 0.19 as well.

**Comment by luzpaz** [comment]
I suggest splitting the PR up if possible. Starting with making the CVE commit it's own separate PR. Is it easy enough to cherrypick ?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6383">pipeline status</a> for feature branch [PR_6383](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6383). Pipeline [472748076](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/472748076) was triggered at [a1c6079](https://github.com/FreeCAD/FreeCAD/pull/6383/commits/a1c6079af5ba57c896af616b0f259f0157e2e09b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@mosfet80 don't get us wrong. we appreciate the impulse and enthusiasm behind your intention. But for the sake of clarity and everyone's time in the review process...it's good to break these efforts up. Also probably a good idea to open a forum thread. I know it's tedious but it actually saves more time than you think, from experience :wink:

**Pull request closed without merging**
