### PR TITLE
MacOSX: When using Qt4 installed by MacPorts, give the cmake finder a…

### PR DESCRIPTION
**Pull request by marco-m**
As the commit comment says, if using Qt4 installed by MacPorts, the cmake Qt4 finder _needs_ this help in order to find Qt4 (have a look at the source code of the Qt4 finder shipped with cmake). The path for QTDIR is the standard installation path for MacPorts, not 100% reliable (user might have customized MacPorts) but a lot better than just failing :-)

### CODE REVIEW

**Comment by ianrrees** [comment]
This issue with MacPorts and Qt4 came about several months ago when there was some movement in MacPorts to support Qt4 and Qt5.  I haven't followed the situation, but from memory there should be some other way to help cmake find the appropriate qmake.

It seems to me that unconditionally modifying external environment variables (which could easily have been set intentionally) to get cmake to work is a much less flexible approach than passing in a command line argument.  The real problem here though is that MacPorts has broken qmake's typical build process...

**Comment by wwmayer** [comment]
@ianrrees so should we reject this PR?

**Comment by ianrrees** [comment]
I think so, at least in the current form.  If I understand the situation correctly, we should be OK with just locating qmake, based on the value of MACPORTS_PREFIX in the MacPorts case.

**Comment by ianrrees** [comment]
@marco-m - Was there a reason you set the QTDIR environment variable, rather than QT_QMAKE_EXECUTABLE like in the wiki CompileOnMac page?

**Comment by marco-m** [comment]
Hello,

regarding the situation with MacPorts and Qt4/Qt5, they finally fixed it, in the sense that now you can install side to side both Qt4 and Qt5 with MacPorts (previously you had to choose only one).

Regarding why I set QTDIR instead than QT_QMAKE_EXECUTABLE, I missed the QT_QMAKE_EXECUTABLE mention in the wiki :-) But, I think the rationale still holds:

if the user is using MacPorts (and this is detected by the cmakefile with MACPORTS_PREFIX being set), then 99.9% of the MacPorts installation prefix is /opt/local/libexec/qt4. So, the same thinking can be used for QT_QMAKE_EXECUTABLE, something like this pseudocode:

if MACPORTS_PREFIX and not QT_QMAKE_EXECUTABLE, then set QT_QMAKE_EXECUTABLE to /opt/local/libexec/qt4/bin/qmake.

This would allow to find a default installation of Qt4 done by MacPorts without user intervention. Would that make sense?

If yes, I can make these modifications (and test if setting QT_QMAKE_EXECUTABLE works, since I don't remember seeing that variable being used by the Qt4 finder).

**Comment by ianrrees** [comment]
Yes, "if MACPORTS_PREFIX and not QT_QMAKE_EXECUTABLE, then set QT_QMAKE_EXECUTABLE relative to MACPORTS_PREFIX" seems like a good way to handle the situation.  If you look around in the cmake source a little, you'll probably find some prior art.

**Comment by marco-m** [comment]
Updated PR according to discussion, it is a lot better now, thanks!

**Comment by ianrrees** [comment]
Looking good, thanks!  Just one more little change - we need to have the if() and endif() statements use the same "argument".  Older cmake versions will issue warnings if they don't match.

**Comment by marco-m** [comment]
I know about the old cmake style for endif(), but I saw that already some places in FreeCAD cmakefiles use an empty endif(), so I though that the remaining places with nonempty endif() where just leftovers. Actually I think it is better just to bump up the minumum cmake version required. 2.8.0 is pretty old, it is from 2009! (https://cmake.org/Wiki/CMake_Released_Versions). Backward compatibility is good, but in this case it just clutters things up in my opinion.

**Comment by wwmayer** [comment]
IIRC we already make use of some more recent cmake features which requires 2.8.6 or higher. The optional argument in endif() is available since 2.8.0. So, I would just leave the empty endif's.

@ianrrees am I right that you agree with the updated PR? So, it can be merged now?

**Comment by ianrrees** [comment]
Sure, it's fine as far as I'm concerned.  Sorry I hadn't realised we had bumped the minimum cmake version.

**Pull request merged**
