### PR TITLE
Horizontal and Vertical Constraint creation modes

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
In continuation to the constraint creation modes feature discussed [here](http://forum.freecadweb.org/viewtopic.php?f=8&t=18175).

### CODE REVIEW

**Comment by luzpaz** [comment]
FYI @AjinkyaDahale is this related to a ticket on the tracker ?

**Comment by AjinkyaDahale** [comment]
@luzpaz No ticket on tracker AFAIK. But there is a discussion on the forum.

**Comment by wwmayer** [comment]
Merged.

**Comment by sasobadovinac** [comment]
@wwmayer appveyor had some problems with servers yesterday https://appveyor.statuspage.io/incidents/k06ydx9hkhbt so our builds were hanging, to move forward we have canceled some of the older builds in the queue...

**Pull request closed without merging**
