### PR TITLE
Rename superPlacement property to AttachmentOffset

### PR DESCRIPTION
**Pull request by peterlama**
The name Attachment Offset gives a better picture of what the
property does.

As discussed on the forum: https://forum.freecadweb.org/viewtopic.php?f=8&t=24466&start=40#p192457

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Ok for me, and it looks from the forum that most agree, and both DeepSOIC and ickby agree too. But since it touches Part, I prefer to leave it for you @wwmayer if you don't mind...

**Comment by plgarcia** [comment]
What consequences this change can have on existing documents? As the SuperPlacement seems to have been introduced in version 0.17 not released, it is acceptable not to convert superPlacement in exiting 0.17 files, but one can open both files with and without superplacement not to loose their job.

**Comment by yorikvanhavre** [comment]
This PR contains code that will handle the opening of old files (SuperPlacement properties will be automatically renamed to AttachmentOffset). But once files have been converted like that, the AttachmentOffset won't be handled anymore when opening the file on an earlier 0.17 version. But it doesn't seem a big problem, it is very unlikely that users will willingly keep an older 0.17 version as their "work version". And it won't affect 0.16 either, where SuperPlacement didn't exist yet.

**Comment by plgarcia** [comment]
Nice !

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
