### PR TITLE
Eugene's branch pls don't judge

### PR DESCRIPTION
**Pull request by Rahul-Sharma-1234**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by luzpaz** [comment]
5K files changed? uhmmm.... ?

**Review by hyarion — CHANGES_REQUESTED** [review]
Thanks for the pull request.

However, this pull request includes a lot of changes, which makes it difficult to review. Some of the changes also seem to change things that shouldn't be changed.

I've skimmed through some part of it and I don't think this is ready for review in this state.
In order to make it reviewable it needs to be split up in logical commits with good commit messages and only contain changes that you want to include in freecad.

I am clearly missing what the meaning of this branch is and the PR doesn't give me a context either, so maybe someone could please explain it to me?

**Comment by hyarion** [comment]
Upon further investigation:

@Rahul-Sharma-1234 I see that you guys seem to have great fun hacking around with freecad's source and tailored it to your needs and liking. After all, isn't that's what opensource is all about? 😃 👍

However, to me, it seems like:
 * you don't fully understand what to commit into the git repository and what should be kept outside of it. I would recommend you to read up on how git should be used, what to commit into a repository and what to avoid commit.
 * you should read up on how to write commit messages to make it easier to review
 * you need to take it slower and read up on how freecad works before creating changes, otherwise it will be perceived like a hack. For example how new documents are auto created and the user gets thrown into sketcher
 * you also need to think what will benefit the freecad project and what should be kept as a local change in your fork. For example - I'm sure your new splashscreen is perfect for you and your friends but I don't see how it will be a great fit for the freecad project

I cannot see how this could be reviewed and merged in its current form.
Therefore I think this PR can be closed.

**Comment by wwmayer** [comment]
> I cannot see how this could be reviewed and merged in its current form.
Therefore I think this PR can be closed.

+1

**Pull request closed without merging**
