### PR TITLE
[test] add definition HAVE_SNPRINTF

### PR DESCRIPTION
**Pull request by looooo**
only a test if this also works with older version of boost/python

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by looooo** [comment]
@wwmayer can we merge this one? It's needed for boost 1.70 to prevent double declaration (python). (At least this is how I understood the issue)

**Comment by wwmayer** [comment]
The actual issue is that with VS2015 or newer the function _snprintf was replaced with snprintf.
Now the Python header pyerrors.h sets a define to set snprintf back to _snprintf
`
#if defined(MS_WIN32) && !defined(HAVE_SNPRINTF)
# define HAVE_SNPRINTF
# define snprintf _snprintf
# define vsnprintf _vsnprintf
#endif
`

Since boost 1.69 this causes a build failure with VS2015 or above. See:
https://github.com/boostorg/system/issues/32 and the commits where it starts to fail
https://github.com/boostorg/system/commit/7b401cef930b3d1576524c8496e2231e7b9136f0#diff-a73c21ed2d8b377ccb91dd921499d57f
https://github.com/boostorg/system/commit/73de31c5416ad5efc7ec91912427f839ceeb7425#diff-a73c21ed2d8b377ccb91dd921499d57f

So far this is a Windows-only problem and only affects VS2015+ (i.e. _MSC_VER >= 1900) and apparently MinGW64.
Although setting HAVE_SNPRINTF seems to work for all platforms I would limit it to VS2015+ and MinGW compilers.

**Comment by wwmayer** [comment]
9873ec6d5

**Comment by looooo** [comment]
Thanks, somehow I missed this one.

**Pull request closed without merging**
