### PR TITLE
[Path] remove Python.h and Xerces

### PR DESCRIPTION
**Pull request by donovaly**
they are not needed anymore

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6627">pipeline status</a> for feature branch [PR_6627](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6627). Pipeline [496776702](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/496776702) was triggered at [407615f](https://github.com/FreeCAD/FreeCAD/pull/6627/commits/407615f49cf8b45f09ace102bfdb8499eb4443df). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by adrianinsaval** [comment]
Is xerces used somewhere else or does this mean it would no longer be a dependency of FreeCAD?

**Comment by donovaly** [comment]
> Is xerces used somewhere else or does this mean it would no longer be a dependency of FreeCAD?

Xerces is the XML reader library. It is used in the base classes but apparently not needed in the WBs.

**Comment by donovaly** [comment]
The CI succeeded, I tested also with precompiled headers and similar commits today for the other WBs worked. Thus merging.

**Pull request merged**
