### PR TITLE
[Arch ExportIFC] Bug-fix Consecutive Face Touch at Corner

### PR DESCRIPTION
**Pull request by paullee0**
Bug-fix Consecutive face (Wall segment) touch at corner.

Forum Discussion : https://forum.freecad.org/viewtopic.php?p=771954#p771954

### CODE REVIEW

**Comment by maxwxyz** [comment]
Does this fix https://github.com/FreeCAD/FreeCAD/issues/14564 ?

**Comment by paullee0** [comment]
> Does this fix #14564 ?

Thanks, related, but this is part of the bigger problem -

https://github.com/FreeCAD/FreeCAD/pull/15350 fix #14564, related to shape creation Part/OCC-wise

The underlying problem in #14564 in fact resulted in problem in IFC generation which is fixed here :)

**Comment by yorikvanhavre** [comment]
There is still an open PR ( #11957 ) attached to this issue. Should it be reopened @paullee0 ?

**Comment by paullee0** [comment]
> There is still an open PR ( #11957 ) attached to this issue. Should it be reopened @paullee0 ?

A bit complicated, but in short no need to reopen this issue IMHO.

This PR is in fact a 'sequel' to issue #11957  and #14564 (the latter 2 are similar )  -  the latter fix the Arch/BIM shape output in FreeCAD, the former make the output of the same to IFC works :)

**Comment by yorikvanhavre** [comment]
Ok, thanks!

**Pull request merged**
