### PR TITLE
CI: Enable GitHub Problem Matchers for compiler warnings.

### PR DESCRIPTION
**Pull request by oursland**

### CODE REVIEW

**Comment by oursland** [comment]
This PR is not the source of the build failures, but the build failures demonstrate the functionality: https://github.com/FreeCAD/FreeCAD/pull/18489/files#file-src-gui-view3dinventor-cpp-L791

**Comment by kadet1090** [comment]
Would be good to merge it as soon as possible as this is immense help both in development and reviewing given that we usually do work on one platform and compile over multiple.

**Comment by maxwxyz** [comment]
@chennes please click the button 😄

**Comment by chennes** [comment]
Yeah, would have been nice to have this Friday morning! Thanks for setting this up, @oursland. We'll probably have to fine-tune our compiler warning settings for a while here to make sure it's warning on all the things we want it to, but this is a great first step.

**Pull request merged**
