### PR TITLE
[TD][Part] Extensions 05, solving issues

### PR DESCRIPTION
**Pull request by edi271**
The four commits do the following:
1. [TD] Include new tool: circle 3 points. Description see in the wiki.
2. [Part] Solving issue: add accuracy to getCircleCenter method. (Sorry, this touches the PART workbench)
3. [TD] Include new tool: remove prefix character. Description see in the wiki.
4. [TD] Solving issue: y-position of dim labels shifted.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Review by WandererFan — CHANGES_REQUESTED** [review]
Where did 0.01 come from?  If you want to check that something is close to zero, the usual option is Precision::Confusion().

**Comment by edi271** [comment]
> Where did 0.01 come from? If you want to check that something is close to zero, the usual option is Precision::Confusion().

Please can you help me. How shall the code line look like ?
The message "Two points are coincident" is not correct. It is tested, whether the three points defining the circle are (nearly) positioned on one line. That leads to an infinite radius of the circle.
But I  think the value better should be 0.001, that means the circle has radius 1000.

**Comment by WandererFan** [comment]
"How shall the code line look like ?"

If it is really a check for a floating point number being zero, it would be this: 
if (abs(uu * vv * ww) < Precision::Confusion())

If the values of uu, vv and ww are approximations, and you expect the error to be larger than Precision::Confusion (1.e-7) then you could use DrawUtil::fpCompare(float1, float2, tolerance).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5468">pipeline status</a> for feature branch [PR_5468](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5468). Pipeline [460324305](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/460324305) was triggered at [5ae5152](https://github.com/FreeCAD/FreeCAD/pull/5468/commits/5ae515268b6b29bd7b113294f34f30bb1f9290aa). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5468">pipeline status</a> for feature branch [PR_5468](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5468). Pipeline [461151131](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/461151131) was triggered at [75ca3a5](https://github.com/FreeCAD/FreeCAD/pull/5468/commits/75ca3a5fc3269877fff366196a2583c64bd3dda6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
