### PR TITLE
[PartDesign] Pad/pocket/revolution/groove fix symmetrical…

### PR DESCRIPTION
**Pull request by Syres916**
…checkbox visibility/availability

Fixes https://github.com/FreeCAD/FreeCAD/issues/16072

### CODE REVIEW

**Review by maxwxyz — CHANGES_REQUESTED** [review]
@Syres916 @yorikvanhavre unfortunately, this PR does not fix the issue.
Demo:

https://github.com/user-attachments/assets/299fad77-b4f3-49be-9785-af4fdaf3b36c

**Comment by Syres916** [comment]
@maxwxyz you're now diverting away from what works in Part and how I personally would expect to work, so if I say I want a Pad two dimensions 0mm to 80mm with Symmetrical ticked, it would be -40mm to 40mm and with a Revolution 0deg to 300deg with Symmetrical ticked would be -150deg to 150deg.

@yorikvanhavre I can change it but I'd really like a second opinion before doing so.

It's one thing to change what checkboxes are visible in the UI but to actively change from _checked_ to _unchecked_ and the user not be able to set it back because it's been disabled seems high risk. I'm seriously conscious of introducing a regression regarding users opening 0.21.x and earlier Part Design files with these very frequently used features at this really late stage before Release.

**Comment by maxwxyz** [comment]
@Syres916 yes symmetrical should work as it is now and IMO symmetrical makes only sense with one dimension (the same in both directions) but when it is checked and you change the the type to two dimensions, changing either of the two results in an outcome which is not one of both input lengths. IMO symmetrical should be unchecked, when two dimensions is used.

**Comment by yorikvanhavre** [comment]
Looking at this right after M3

**Comment by yorikvanhavre** [comment]
So IIUC this boils down to these two questions: 

1. If you want to extrude symmetrically of 40mm, does the 40mm represent the total extrusion (2x20mm) or 40mm on each side, total 80mm?
2. If someone picks the "two ways" option, isn't it similar or redundant to symmetrical? If yes, then I think this PR seems appropriate to me, as it disables the symmetry checkbox. But indeed there is the problem of someone having checked it *before* switching to "two ways". In that case, the checkbox will stay checked in two ways mode, and since it's disabled, the user can't uncheck it.

Does "two ways" + symmetrical give unwanted result? I understand it just does not have effect. If that's the case, then I guess this PR is good anyway, there is maybe a cosmetic problem left, but not sure I would uncheck the box automatically.

**Comment by yorikvanhavre** [comment]
Any idea there, @FreeCAD/cad-advisory-group ?

**Comment by pierreporte** [comment]
If I want to extrude symmetrically of 40 mm, I would expect −20 mm in one direction and +20 mm in the other one. It feels more natural and FreeCAD already works like this.

Two-way extrusion and symmetrical extrusion are mutually exclusive. It doesn’t make sense to specify the two values if you want to center the resulting length around the base plane. If the user really wants to specify two values, they can input 20 mm + 20 mm.

**Comment by chennes** [comment]
So the if I am understanding correctly, the path forward here is that when "two dimensions" is chosen, the "symmetric" checkbox should be disabled. Is that a separate PR, or @Syres916 are you going to adjust this one to include that?

**Comment by maxwxyz** [comment]
@chennes IMO not only the checkbox should be disabled. Currently you can change any of the two lengths and the result is not one of them symmetrically but any arbitrary length. So either the calculation is wrong if two lengths and symmetrical is enabled or the property symmetrical needs to be set to false when changing to two lengths.

**Comment by Syres916** [comment]
I'm still far from convinced that the request made by @maxwxyz won't cause regressions on existing models and with so many far more important segfaults/errors (I've found four just today while trying to do some real work) to be fixed I'm going to close this concentrating my efforts on the existing regressions. If someone wants to revisit/run with it they can reference it.

**Pull request closed without merging**
