### PR TITLE
Support for OpenSCAD offset command added

### PR DESCRIPTION
**Pull request by KeithSloan**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by wwmayer** [comment]
Please make sure that your branch is based on latest master when creating a PR. This branch has conflicts and thus can't be merged.

**Comment by KeithSloan** [comment]
As far as I can see git SUCK's

Following your email I thought I would start again.

Took a copy of importCSG.py
deleted the directory.
Did a fresh clone of https://github.com/KeithSloan/FreeCAD_sf_master.git
tried
git remote add official https://github.com/FreeCAD/FreeCAD.git
git remote -v

git checkout master
# Get latest master from official FreeCAD repository
git pull official master

And now I get

Already on 'master'
Your branch is up-to-date with 'origin/master'.
family@Desktop:~/FreeCAD/git-src/FreeCAD_sf_master$ git pull official master
remote: Counting objects: 183, done.
remote: Compressing objects: 100% (169/169), done.
remote: Total 183 (delta 63), reused 14 (delta 14), pack-reused 0
Receiving objects: 100% (183/183), 501.77 KiB | 0 bytes/s, done.
Resolving deltas: 100% (63/63), completed with 7 local objects.
 From https://github.com/FreeCAD/FreeCAD
  * branch            master     -> FETCH_HEAD
  * [new branch]      master     -> official/master
Auto-merging src/Mod/OpenSCAD/importCSG.py
CONFLICT (content): Merge conflict in src/Mod/OpenSCAD/importCSG.py
Automatic merge failed; fix conflicts and then commit the result.

Obviously my FreeCAD repro and the official got out of sync. How I have 
no idea.
Also no idea on how to resolve

**Comment by ianrrees** [comment]
@KeithSloan - the easiest way to get back to a good state is probably to rename "master" on your local repo to something else: `git branch -m master old-master`.  The problem is that you're asking git to combine two branches with different history (your master is not the same as FreeCAD's master).  master is just a branch name used by convention.

Feel free to use https://gitter.im/FreeCAD/FreeCAD to follow up - that way folks that are following this repo won't get an email for every message exchange.

**Comment by KeithSloan** [comment]
Hi Ian

Tried renaming master but get the following

family@Desktop:~/FreeCAD/git-src/FreeCAD_sf_master$ git pull official master
remote: Counting objects: 183, done.
remote: Compressing objects: 100% (169/169), done.
remote: Total 183 (delta 63), reused 14 (delta 14), pack-reused 0
Receiving objects: 100% (183/183), 501.77 KiB | 0 bytes/s, done.
Resolving deltas: 100% (63/63), completed with 7 local objects.
 From https://github.com/FreeCAD/FreeCAD
  * branch            master     -> FETCH_HEAD
  * [new branch]      master     -> official/master
Auto-merging src/Mod/OpenSCAD/importCSG.py
CONFLICT (content): Merge conflict in src/Mod/OpenSCAD/importCSG.py
Automatic merge failed; fix conflicts and then commit the result.

Do I have to checkout old_master before I do the official pull

Keith

**Comment by luzpaz** [comment]
@KeithSloan FYI if you want to automagically link this commit to the open bugtracker ticket the add the following to your git commit:
`issue 0002360`
If you want to close said ticket:
`fixes 002360`
Reference: 
https://freecadweb.org/tracker/view.php?id=2360
https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT

**Comment by wwmayer** [comment]
Is the file src/Mod/OpenSCAD/parsetab.py supposed to be part of the repo or is this some rubbish on your disk? I can't find any Python code where this module would be imported so I guess it's the latter.

**Comment by KeithSloan** [comment]
Its a python script that is used to check that ply parser is working 
correctly.
Run separatly

**Comment by wwmayer** [comment]
Manually merged.

**Comment by KeithSloan** [comment]
Thanks for sorting it

**Pull request closed without merging**
