### PR TITLE
[Cam Simulator][1.0] Limit anti alias samples for better compatibility. 

### PR DESCRIPTION
**Pull request by shaise**
Probably solves: [This problem](https://forum.freecad.org/viewtopic.php?p=778342#p778342)
Might also solve Wayland problem, issue #15665 

EDIT: instead of hard coded number of samples,  Anti Alias samples is now taken from Display preferences.

### CODE REVIEW

**Comment by xtemp09** [comment]
Is there a preliminary checking to find optimal value? Would it be better to take the value from _Preferences_ or somehow [test it](https://github.com/FreeCAD/FreeCAD/blob/5785cb589bbb5f498f7f7de405f1fa521f9691d2/src/Gui/Multisample.cpp#L61)?

**Comment by shaise** [comment]
Perhaps I should use the main anti aliasing preference.

**Review by chennes — APPROVED** [review]
This looks good to me -- @sliptonic any reason to hold this?

**Comment by sliptonic** [comment]
Nope. Proceed.

**Pull request merged**
