### PR TITLE
ArchWall_DraftGeomUtils Multi-Width support added

### PR DESCRIPTION
**Pull request by paullee0**
Discussion:- https://forum.freecadweb.org/viewtopic.php?f=23&t=36772&p=319829#p319829

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I would like to change the name of WidthOfWall to something that confuses less the user, for ex. OverrideWidth or OverrideWidths, so users would see more clearly that 1) this is something you normally don't need to use, only if you specifically want it, and 2) that it will take over the value of Width. Ok for you?

**Comment by paullee0** [comment]
Of course!  OverrideWidths ? ('s' to signify a list of them) :)

A few ideas come to my mind, not really know its implication ... :-

1.  Thinking to have a getWidth() in Base object (DraftWire / SketchPython) which also return 'a list of widths' in future ?

2. or have a getExtrusionData() in the Base object ?

**Comment by yorikvanhavre** [comment]
I would go for OverrideWidth so users know exactly what will happen if they use it (and you explain more in the description string), but I have no strong opinion on this, OverrideWidths is fine too
About the base object, it's complicated, because it could be just about anything, even object types that don't exist yet today. So it's safer to implement all that you need in the Arch object, not the base...

**Comment by paullee0** [comment]
OK done following your comments :)

Will think about Base object matters later too.

Thanks.

**Comment by yorikvanhavre** [comment]
Okay, merged! Can you write something on the forum to announce/explain how to use it?

**Pull request merged**
