### PR TITLE
Wire undo, Extrude script, Test

### PR DESCRIPTION
**Pull request by iHateInventNames**

### CODE REVIEW

**Comment by iHateInventNames** [comment]
Up

**Comment by wood-galaxy** [comment]
Hi @iHateInventNames, we usually discuss pull request on the freecad forum (http://forum.freecadweb.org/viewforum.php?f=17). Github pull request is just using as an easy tool for main dev to merge.
Best regards

**Comment by iHateInventNames** [comment]
Hi Jonathan, thank you. I like github tools for its minimalistic and systematic design. Also issues tool is great. I've seen you use Mantis bug tracker and found the bug which for I started work on this changelist. It is the one about cancelling polyline nodes. Also as I started working with master branch, I fixed couple exception was there by the road. I also suggested a rename first but I have removed it for now to make the changelist review as simple as possible. It is ready for review. Could someone, please, consider it? Thanks again and thank you for working for such a great&useful project.

**Comment by wwmayer** [comment]
Hi @iHateInventNames,
>I've seen you use Mantis bug tracker and found the bug which for I started work on this changelist. 

Can you point us to the number of the bug report you are referring to, please?

> I also suggested a rename first but I have removed it for now to make the changelist review as simple as possible.

The new method getObject() in PropertyContainer is a complete new thing and shouldn't be bundled with a bug fix. Also, this change is not unproblematic because now you never know if it returns a valid object or null. And it's not obvious to me what exactly it attempts to simplify.

**Comment by iHateInventNames** [comment]
Hi @wwmayer,

As for now I was unable to find any with requests 'wire undo' or 'polyline undo' there http://www.freecadweb.org/tracker 
The purpose of the new getObject method (getDocumentObject after rename) is to work well for Gui::ViewProviderDocumentObject and its derivatives slightly in same way as for DocumentObject derivatives. 
screenshot_2016-03-07_22-44-52
PropertyContainer is common ancestor class for DocumentObject and ViewProviderDocumentObject classes.
When the PropertyContainer pointer pointing to a ViewProvider child class object is tried to be casted to DocumentObject pointer through freecad_cast or dynamic_cast it casted to null. 
This causes special type tests for ViewProviderDocumentObject hierarchy to make custom casting calls. These are unnecessary. The patch allows to reduce some copypaste and resolves some related crashes.

**Comment by bblacey** [comment]
@iHateInventNames, you did notice that commit 0fc040c of this pull request broke the [Linux build](https://travis-ci.org/FreeCAD/FreeCAD/jobs/121516209) right?  The OS X build passed so most likely it is a gcc versus clang compiler issue.  You can add commits to a pull request to resolve the build problem and you probably want to rebase your pull request at the same time so it is in't out of date with master.  Thanks.

**Comment by bblacey** [comment]
@iHateInventNames, two follow-up points.  First, while my last comment was with respect to the pull-request process, Werner is the authoritative voice on pull-request scope, architectural compliance, best-practices, conventions, suitability, etc. so you will still need to address his concerns before this pull request will progress.  Second, we just committed a new travis config on master that moves the pull builds from precise with gcc to trusty with clang and I tested your pull request on my fork using the new configuration and it builds successfully hence if you rebase your pull request with master at some point, your pull request will be rebuilt with the new config.

**Comment by yorikvanhavre** [comment]
I cherry-picked two of these commits: c69b6a5 (Added Crank drawing test code and fcstd) and  00e6391 (fixed makeWire face parameter treating). 19384e7 and 1f1bdd5 we fail to see what they are fixing (no build error and wire undo works correctly as far as I tested), and d1c7b4d brings in some problems. I'll close this pull request since we have currently no intent to merge the 3 other commits. Feel free to reopen or post another pull request if needed.

**Pull request closed without merging**
