### PR TITLE
[Preference Packs] Add Keyboard Shortcuts Template

### PR DESCRIPTION
**Pull request by howie-j**
An attempt to solve issue #9179

I don't know if i understand pref packs correctly, but it seems like there needs to be a tag for every keyboard shortcut for pref packs to save modified shortcuts?

What i did was export all commands from a clean/unmodified freecad setup, with all default WB's enabled and loaded, and added those with its corresponding shortcut to an xml (.cfg) file.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [X ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9180">pipeline status</a> for feature branch [PR_9180](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9180). Pipeline [827887396](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/827887396) was triggered at [81fdac8](https://github.com/FreeCAD/FreeCAD/pull/9180/commits/81fdac808e2ac6285624a841f3cfe8db967396b9). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Yes, it looks like this is correct. I will try to give it a test later today or tomorrow to be sure.

**Comment by howie-j** [comment]
Thanks a lot @chennes!

Just a follow up question; Doesn't this approach with xml templates means that only "default" parameters can be saved in preference packs, not custom parameters such as custom toolbars for example?

So if i want to "export" custom toolbars, i have to do that outside of the pref pack manager using a separate macro/function (or manually copying from my user.cfg), and only importing would work via the pref pack gui?

**Comment by chennes** [comment]
Yep. Exactly right. Future work might be to have the pref pack system also be able to run scripts to generate parts of the saved file.

**Pull request merged**
