### PR TITLE
CAM: Fix CW/CCW to Climb/Conventional rename

### LINKED ISSUE #15009: CAM: Unable to change cut direction on a profile cut
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In a profile toolpath tried to change from Climb to Conventional. 

```
Report view:
06:59:13  Traceback (most recent call last):
06:59:13    File "C:\FreeCadBeta\Mod\CAM\Path\Op\Gui\Base.py", line 251, in pageGetFields
06:59:13      self.getFields(self.obj)
06:59:13    File "C:\FreeCadBeta\Mod\CAM\Path\Op\Gui\Profile.py", line 78, in getFields
06:59:13      obj.Direction = str(self.form.direction.currentData())
06:59:13      ^^^^^^^^^^^^^
06:59:13  ValueError: {'sclassname': 'class Base::ValueError', 'sErrMsg': "'Conventional' 
          is not part of the enumeration in Back#Profile001.Direction", 'sfile': 'C:\\bld\\freecad_1719273226893\\work\\src\\App\\PropertyStandard.cpp', 'iline': 466, 'sfunction': 'void __cdecl App::PropertyEnumeration::setPyObject(struct _object *)', 'swhat': 
          "'Conventional' is not part of the enumeration in Back#Profile001.Direction", 'btranslatable': False, 'breported': False}
```

### Full version info

```shell
OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * btl 0.9.9
  * Curves 0.6.39
  * lattice2 1.0.0
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #15206: CAM: Helix and inside Profile cutting direction wrong
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When using Helix or Profile to cut a hole and selecting cutting direction "Climb" the cutter moves clockwise (should be counter-clockwise) with a "Forward" rotating tool. Outside Profile moves in the same direction which is correct in this case.

The attached file shows from left to right a Helix, an inside Profile (with ramp dressup for better visualization) and an outside Profile. All have cutting direction "Climb" selected.

[cut_direction_issue.zip](https://github.com/user-attachments/files/16107471/cut_direction_issue.zip)

grafik

### Full version info

```shell
OS: Arch Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37927 (Git)
Build type: Release
Branch: makepkg
Hash: 4d6b738062fd29d7c6098a7197551bc291b13b1a
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Installed mods: 
  * kicadStepUpMod 11.1.7
  * dodo 1.0.1
  * sheetmetal 0.4.16
  * fcgear 1.0.0
  * fasteners 0.5.21
  * Assembly4 0.50.12
  * Curves 0.6.37
  * lattice2 1.0.0
```

### Subproject(s) affected?

CAM/Path

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #15643: CAM: Helix operation is broken: "Helix: Invalid value for parameter 'direction'"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Any Helix operations are currently broken in 0.22:

Steps to reproduce:
- Open any file with a helix operation that has direction set to CW or CCW.
- Try to edit the operation.
- Note the error on the Helix operation and the traceback in the logs.

Probably caused by #14314.
#15206 may also be related.

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38334 (Git) AppImage
Build type: Release
Branch: main
Hash: 61c964caa9a7e5bbc7a8d5f7d8914505d365113e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * DynamicData 2.62.0
  * btl 0.9.9
  * WebTools
  * toSketch
  * fasteners 0.4.62
  * lattice2 1.0.0
  * freecad.gears 1.2.0
  * sheetmetal 0.4.23
  * CycloidGearBox
  * parts_library
  * Assembly4 0.12.3
```

### Subproject(s) affected?

CAM/Path

### Anything else?

```
14:41:10  Traceback (most recent call last):
14:41:10    File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Gui/Base.py", line 251, in pageGetFields
14:41:10      self.getFields(self.obj)
14:41:10    File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Gui/Helix.py", line 66, in getFields
14:41:10      obj.Direction = str(self.form.direction.currentData())
14:41:10      ^^^^^^^^^^^^^
14:41:10  ValueError: {'sclassname': 'N4Base10ValueErrorE', 'sErrMsg': "'Conventional' is not part of the enumeration in ebox_sandwich_v2_3_1#Helix.Direction", 'sfile': '/home/conda/feedstock_root/build_artifacts/freecad_1722018560151/work/src/App/PropertyStandard.cpp', 'iline': 464, 'sfunction': 'virtual void App::PropertyEnumeration::setPyObject(PyObject*)', 'swhat': "'Conventional' is not part of the enumeration in ebox_sandwich_v2_3_1#Helix.Direction", 'btranslatable': False, 'breported': False}
14:41:17  Traceback (most recent call last):
14:41:17    File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Gui/Base.py", line 251, in pageGetFields
14:41:17      self.getFields(self.obj)
14:41:17    File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Gui/Helix.py", line 66, in getFields
14:41:17      obj.Direction = str(self.form.direction.currentData())
14:41:17      ^^^^^^^^^^^^^
14:41:17  ValueError: {'sclassname': 'N4Base10ValueErrorE', 'sErrMsg': "'Climb' is not part of the enumeration in ebox_sandwich_v2_3_1#Helix.Direction", 'sfile': '/home/conda/feedstock_root/build_artifacts/freecad_1722018560151/work/src/App/PropertyStandard.cpp', 'iline': 464, 'sfunction': 'virtual void App::PropertyEnumeration::setPyObject(PyObject*)', 'swhat': "'Climb' is not part of the enumeration in ebox_sandwich_v2_3_1#Helix.Direction", 'btranslatable': False, 'breported': False}
14:41:37  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/PathScripts/PathUtils.py", line 70, in new_function
    res = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Base.py", line 826, in execute
    result = self.opExecute(obj)
             ^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/CircularHoleBase.py", line 194, in opExecute
    self.circularHoleExecute(obj, holes)
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Helix.py", line 221, in circularHoleExecute
    results = helix.generate(**args)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Base/Generator/helix.py", line 100, in generate
    raise ValueError("Invalid value for parameter 'direction'")
<class 'ValueError'>: Invalid value for parameter 'direction'
14:41:37  Helix: Invalid value for parameter 'direction'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jbaehr**
With #14364 a fairly large search/replace PR was merged in order to address #14314.
Unfortunately, this resulted in quite some collateral damage (e.g. #15643 and #15009) and misunderstandings (e.g. #15206 -- just renaming things does not mean the feature got implemented).

With this PR I try to fix the above mentioned bugs, address the critics on #14364 from @Connor9220 and @jffmichi and actually implement #14314.

It's still incomplete and I know that it's quite late for v1.0, but let's hope for the best. I just don't want to see a v1.0 released that's unable to open my old documents.

**Current State** (for details please refer to the comments below)
- The original #14364 is reverted, meaning
  - The bugs fixes #15643 and fixes #15009...
  - ... at the cost of some ui strings changed back again, breaking translations. Personally, I value functional bugs more severe than translation issues so I consider this an acceptable tradeoff.
- For the Helix operation, #14314 is implemented
  - using the ui strings from #14364, so no translation issues there (again at the cost of some tooltips not matching; the ui strings need revision *after v1.0* to not break even more translations)
  - fixes #15206
  - including backward compatibility and unit tests
- For the Profile and Deburr operations, #14314 is still open

Frankly, I haven't originally planned to work on this. However, I was personally affected by the bugs introduced with #14364, I stepped in with this last-minute rescue attempt.

### CODE REVIEW

**Comment by jbaehr** [comment]
@sliptonic do you still remember why you disabled the helix tests in 56875b21375?

**Comment by chennes** [comment]
@jbaehr I see this is marked "draft" -- if it is not ready for review by Monday, it will not make it into 1.0.

**Comment by jbaehr** [comment]
@chennes I could split the work and set this one ready. The current state is:
- There are tests demonstrating the issue that files from previous FreeCAD got broken (96fa7efee57c9e262a4239b31961ac4d7ed14aff)
- The previously existing helix tests got reenabled again (and a broken test is now fixed as well) (2df29a80f4e94dd3ee42593cb739e2c0f62a2702)
- #14364 is reverted (and adapted to changed happening in the meantime) (509fef68774160945bc40a42a08ff44941cf2218). This means
  - the open issues resulting from this PR are gone and older files work again
  - #14314 is open again (well it was never implemented, but closed anyway)
  - a few translations got broken due to changed (reverted) ui strings

What I originally planned with this PR was to properly implement #14314 but I'm facing some challenges making it unlikely that I can finish this by Tomorrow. Especially the "Profile" operation has several modes, where also some changes in the internal logic seem necessary (For holes the direction is already inverted, but you don't want the cutting mode to be inverted, so there is no drop-in replacement).
Maybe I manage to get the "Helix" operation ready in time, but "Profile" looks too hot to touch that close to a release. I propose to do this in dedicated PRs instead.

We're now in the dilemma of either having working features and backward compatibility, but some broken UI strings. Or keep the UI strings (which suggest features we actually don't have) at the cost of broken v0.21 files and other bugs. I would prefer the first poison. In addition, if we release with #14364 in place, we end up with *two* compatibility issues when trying to actually implement #14314: The one from the missing v0.21 implementation, and the one from the wrong v.1.0 implementation.

**Comment by jbaehr** [comment]
I managed to get #14314 implemented for Helix, reusing the ui strings from #14364 -- so here we should not have broken translations due to the fix. I also implemented backward compatibility for helix operations created with pre-releases of 1.0 since June when #14364 was merged.

Since I'm running out of time I'm setting this PR to *ready* now. Note that Profile and Deburr do not yet have #14314 implemented, but at least the bugs are gone and files created with v0.21 can be loaded and edited again.
I suggest to review each commit separately -- the changes are logically grouped and have more detailed descriptions each. So please to not squash when merging!

I'm now looking at Deburr -- there is still a litte chance that I get #14314 done for this as well.

**Comment by jbaehr** [comment]
Do you have a specific example? I thought that I took care about the files created with the inconsistent state between the merge of #14364 and this PR as well; not only the pre-#14364 ones. But maybe I missed something.

**Comment by duub** [comment]
Sorry, I was anxious to move on and overwrote the file, I've downloaded the 1.0.0RC2 and tried to recreate the situation but didn't get the same error... now I'm getting this, but it seems another issue:

```
**<class 'AttributeError'>: 'NoneType' object has no attribute 'setOrigin'
19:16:29  pyException: Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 1.0\Mod\CAM\Path\Main\Gui\Job.py", line 1659, in addSelection
    self.updateSelection()
  File "C:\Program Files\FreeCAD 1.0\Mod\CAM\Path\Main\Gui\Job.py", line 1438, in updateSelection
    self.form.setOrigin.setEnabled(False)
    ^^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'NoneType' object has no attribute 'setOrigin'**
```

**Comment by duub** [comment]
Here it is the file
[test.zip](https://github.com/user-attachments/files/17951342/test.zip)

**Comment by jbaehr** [comment]
What is the problem with this file? What are the steps to reproduce? The stacktrace from above looks pretty unrelated to this PR.

**Comment by duub** [comment]
Yes, i should open a new issue when i can issolate the problem

El dj., 28 de nov. 2024, 21:29, jbaehr ***@***.***> va
escriure:

**Pull request merged**
