### PR TITLE
Part: reversed -- fix so it works with App::Links and App::Parts

### PR DESCRIPTION
**Pull request by mwganson**
Followup to https://github.com/FreeCAD/FreeCAD/pull/6478 where accidentally the Reversed function was not added.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6755">pipeline status</a> for feature branch [PR_6755](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6755). Pipeline [517833030](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/517833030) was triggered at [0091467](https://github.com/FreeCAD/FreeCAD/pull/6755/commits/0091467cf905070157b58923689e2e0de70f7e50). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@realthunder another one to be reviewed since it affects Link

**Comment by realthunder** [comment]
Looks good.

**Comment by donovaly** [comment]
Thanks. merging then.

**Pull request merged**
