### PR TITLE
[PATH]: Refactor/path module naming cleanup

### PR DESCRIPTION
**Pull request by mlampert**
Restructure the source code to bring some order into the python modules and make the code more digestible. It does away with most of the naming redundancy and clearly separates business logic from UI dependent code.

This also combines the C++ and python backed object classes in a single namespace. From the python side `Log` and `Geom` are pulled into the top level `Path` namespace due to their universal usage. All other modules are in sub-modules.

Going forward it should be noticeable if a module violates the dependency tree, introduces cyclic references or tries to pull UI logic into the backend business logic. Also, the new structure should be extensible in the future.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [630601568](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/630601568) was triggered at [9b58e67](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/9b58e678ddf9241a129bbc431655520517e399d4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [631723654](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/631723654) was triggered at [0a436c9](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/0a436c96decf637d5918db8642e24e354b963b19). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by GeneGH — COMMENTED** [review]
Quick initial look seems to work correctly, with a couple of exceptions.

Attempts at 3D Surface and 3D Waterline give error messages.

_SurfaceSupport.ERROR: PSF._isReady() no "Op.Surface" method.
Surface.ERROR: Failed to pre-process model and/or selected face(s)._


_SurfaceSupport.ERROR: PSF._isReady() no "Op.Waterline" method.
Waterline.ERROR: Unable to pre-process obj.Base._

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [636513408](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/636513408) was triggered at [93112e6](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/93112e67c0050e299eace55c20eb23d8539ac1dd). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
Shall I build a snap for testers of this PR ?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [637146634](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/637146634) was triggered at [c83a9a8](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/c83a9a8ec8638eec5a633893aeb4caa038902a71). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [641904430](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/641904430) was triggered at [b759d47](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/b759d477c27b623c07abcd3550825e49625ca47d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [644924193](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/644924193) was triggered at [b3b3403](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/b3b3403f4d8b82e223e0ed4c618b0ddd23fc95e6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [649502278](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/649502278) was triggered at [304ed0b](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/304ed0b9bc17de3d0dad973688ffcb97a4de5032). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [649511076](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/649511076) was triggered at [351e3ad](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/351e3ad88d7c3174432c5096bbb506424d60775a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [649530520](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/649530520) was triggered at [005b0d3](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/005b0d3d79753d69220e82b5ee6ac6c75307e619). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [649558764](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/649558764) was triggered at [cc19425](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/cc194256052370de6786fdfae9260b730d3601ac). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [649996458](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/649996458) was triggered at [780699d](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/780699dcde0581bdcc70043d07681cc6bf2b63b7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
@Floriansimmer  Is it possible to get any more information about why the github CI is failing?  These unit tests pass locally on multiple platforms.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [654669506](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/654669506) was triggered at [d07cb93](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/d07cb9342abe247c616a0c4e37bf41407bb4a3fa). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656041787](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656041787) was triggered at [f3f2c76](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/f3f2c76d37ed8665449f391cd458bd10a299348f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656475209](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656475209) was triggered at [085c81b](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/085c81b79579f2ea3a3366ade8599561c93becd4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656506748](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656506748) was triggered at [1742dfc](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/1742dfcc82c9c4102e83df8b7ac3914833c1cb79). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656516154](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656516154) was triggered at [4fb38ba](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/4fb38ba11e24f95a27a8c6a3fc7657be2e04e5ef). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
> @Floriansimmer Is it possible to get any more information about why the github CI is failing? These unit tests pass locally on multiple platforms.

Also our own CI fails:
https://gitlab.com/freecad/FreeCAD-CI/-/jobs/3116513286
The info the CI outputs is more suitable to find/fix the problem I think. @sliptonic , @mlampert , can you please have a look?

**Comment by donovaly** [comment]
OK, with the last force push, the CI succeeded for the first time: https://gitlab.com/freecad/FreeCAD-CI/-/jobs/3116549490

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656534594](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656534594) was triggered at [c556fa3](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/c556fa35b0988463db174667ff0e630861e9b0f6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by mlampert** [comment]
> OK, with the last force push, the CI succeeded for the first time: https://gitlab.com/freecad/FreeCAD-CI/-/jobs/3116549490

Yes - I disabled the offending test to see what else fails - do not merge

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656548794](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656548794) was triggered at [f8dd6e2](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/f8dd6e261cced73a4778510b761288ba4ca4d25d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656553698](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656553698) was triggered at [bf520a1](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/bf520a1ede48c1c705a848f0f4bce52119cdf3c5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656561902](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656561902) was triggered at [17ec80b](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/17ec80b634a9a2abaf80fb8ba9ba1265acf2bdff). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656576048](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656576048) was triggered at [047734e](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/047734e30f901e78f3379e39e5d76ed8289f6857). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656589360](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656589360) was triggered at [e0349a3](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/e0349a32fb415696e1cfcd203b2f2924c0b46524). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [656614300](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/656614300) was triggered at [9998958](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/9998958a8fee8eab3e2fb7120b7ad867f7f9d57e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [661855201](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/661855201) was triggered at [afdcb25](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/afdcb25d32b6607c267d872a8210fd1611f1b843). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [663216964](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/663216964) was triggered at [dc44fce](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/dc44fce84c4b94aee75a2666b7f0df54fb7d4240). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440">pipeline status</a> for feature branch [PR_7440](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7440). Pipeline [664431748](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/664431748) was triggered at [c74a0ad](https://github.com/FreeCAD/FreeCAD/pull/7440/commits/c74a0ad3e55cd853668c6ae183a05daa2ec5df16). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by wwmayer** [comment]
Since this PR is merged I get this error message when starting FreeCAD:
> Path WB not found

In the combo box the Path workbench is still listed and when I try to activate this error is raised:
```
module 'Path.Tool' has no attribute 'Controller'
Traceback (most recent call last):
  File "<string>", line 82, in Initialize
  File "/home/user/Projects/build_clang/Mod/Path/Path/Main/Gui/JobCmd.py", line 29, in <module>
    import Path.Main.Gui.JobDlg as PathJobDlg
  File "/home/user/Projects/build_clang/Mod/Path/Path/Main/Gui/JobDlg.py", line 29, in <module>
    import Path.Main.Job as PathJob
  File "/home/user/Projects/build_clang/Mod/Path/Path/Main/Job.py", line 31, in <module>
    import Path.Tool.Controller as PathToolController
  File "/home/user/Projects/build_clang/Mod/Path/Path/Tool/Controller.py", line 351, in <module>
    from Path.Tool.Gui.Controller import ViewProvider
  File "/home/user/Projects/build_clang/Mod/Path/Path/Tool/Gui/Controller.py", line 30, in <module>
    import Path.Tool.Controller as PathToolController
```

**Comment by mlampert** [comment]
Thanks for letting me know - I'll check it out tonight.

**Comment by wwmayer** [comment]
I was able to solve the issue. Previously I've only deleted Mod/Path of my build directory but after realizing that another build works fine I now have deleted src/Mod/Path as well and after rebuilding it the issue is gone.

**Comment by luzpaz** [comment]
Did this PR create this regression? https://forum.freecadweb.org/viewtopic.php?p=639162#p639162

**Comment by dresco** [comment]
> Did this PR create this regression? https://forum.freecadweb.org/viewtopic.php?p=639162#p639162

Fwiw, appears to have happened in [this](https://github.com/FreeCAD/FreeCAD/commit/a5a284b1481c5cdeeb95418c0a5237dbbe7b776d) commit

**Comment by mlampert** [comment]
It seems I messed up a rebase - will fix it tonight - sorry about that.

**Pull request merged**
