### PR TITLE
Best practises: replacing inkscape svg by plain svg

### PR DESCRIPTION
**Pull request by mdkus**

### CODE REVIEW

**Comment by mdkus** [comment]
This PR only refers to today's commit, not to the older ones. If the older commits disturb, please let me know.

**Comment by donovaly** [comment]
It is not clear what the goal of the PR is. Can you please describe it, rebase and make a single commit?

**Comment by mdkus** [comment]
Ok, i'll try to rebase and create a single commit.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5366">pipeline status</a> for feature branch [PR_5366](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5366). Pipeline [444253332](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/444253332) was triggered at [ce2f4f6](https://github.com/FreeCAD/FreeCAD/pull/5366/commits/ce2f4f6d5a01200ec0cab392f133b4b9f93a26c4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
For future reference, you'll make your life easier if you always work on a branch, instead of master -- especially in this case, where'd you'd like to just pull out the single commit as a PR, since pull requests function on whole branches, not on single commits.

**Comment by mdkus** [comment]
Ok, I see.

**Comment by mdkus** [comment]
I'll create a new PR on with a single commit an a new branch.

**Comment by luzpaz** [comment]
JFYI, @mdkus, more tips at https://wiki.freecad.org/Github

**Pull request closed without merging**
