### PR TITLE
Spreadsheet: use 'text' instead of 'foreground' in tooltip

### LINKED ISSUE #18013: Spreadsheet: Inconsistent tooltip information
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The tooltip of the cell text color is ''Set cell(s) text color''
tooltip

Which is inconsistent with the naming in the properties of the cell:
properties-spreadsheet

**Proposed solution:**
Change the tooltip of the button to 'Set cell(s) text color'

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

Spreadsheet

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by luzpaz**
Fixes #18013

### CODE REVIEW

**Comment by chennes** [comment]
Is the "cell(s)" stuff actually useful here? It would be quite a bit less cumbersome if we dropped that word/punctuation blob.

**Comment by semhustej** [comment]
> Is the "cell(s)" stuff actually useful here? It would be quite a bit less cumbersome if we dropped that word/punctuation blob.

I took a look at LibreOffice and they use just 'Font Color' and 'Background Color'. 
But in case of FreeCAD, I would leave the 'cell' there, because user can have Spreadsheet WB open with 3D view and than changing 'Background Color' would have different meaning and 'cell' gives a correct context to the tool.

If I was to change something, I would drop the 's' , so there would be 'cell' instead of 'cell(s)'. But that is just a minor thing.

**Comment by luzpaz** [comment]
Verdict ?

**Comment by hyarion** [comment]
I agree with @chennes, but I don't see it as a required change to get this merged.

**Pull request merged**
