### PR TITLE
[0.17] FEM: fix in material task panel, unit test for tetra10 export

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by berndhahnebach** [comment]
IMHO it is a cache problem. The failure is fixed ...

**Comment by berndhahnebach** [comment]
there was another problem with print output format on lin and win. Should be fixed too. bernd

**Comment by berndhahnebach** [comment]
fixed another Python3 issue

**Comment by berndhahnebach** [comment]
the osx fails ... someone an idea why?

**Comment by berndhahnebach** [comment]
``
[  0%] Building CXX object plugins/CMakeFiles/uiplugin.dir/customwidget.cpp.o

cd /tmp/pyside2-20180326-26717-1j3j8dn/pyside-setup-b09fde6/macbuild3.6/plugins && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DQT_CORE_LIB -DQT_STATICPLUGIN -F/usr/local/opt/qt/lib -I/usr/local/opt/qt/lib/QtDesigner.framework/Headers -I/usr/local/opt/qt/lib/QtWidgets.framework/Headers -I/usr/local/opt/qt/lib/QtGui.framework/Headers -I/usr/local/opt/qt/lib/QtCore.framework/Headers -I/usr/local/opt/qt/./mkspecs/macx-clang -I/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/qt/lib/QtXml.framework/Headers -I/usr/local/Cellar/shiboken/2.0.0-e11fa17/include/shiboken2 -I/usr/include/python2.7  -Wall -fvisibility=hidden -Wno-strict-aliasing -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/uiplugin.dir/customwidget.cpp.o -c /tmp/pyside2-20180326-26717-1j3j8dn/pyside-setup-b09fde6/sources/pyside2/plugins/customwidget.cpp

In file included from /tmp/pyside2-20180326-26717-1j3j8dn/pyside-setup-b09fde6/sources/pyside2/plugins/customwidget.cpp:41:

/tmp/pyside2-20180326-26717-1j3j8dn/pyside-setup-b09fde6/sources/pyside2/plugins/customwidget.h:43:10: fatal error: 'shiboken.h' file not found

#include <shiboken.h>

         ^

1 error generated.

make[2]: *** [plugins/CMakeFiles/uiplugin.dir/customwidgets.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....

1 error generated.

make[2]: *** [plugins/CMakeFiles/uiplugin.dir/customwidget.cpp.o] Error 1

make[1]: *** [plugins/CMakeFiles/uiplugin.dir/all] Error 2

make: *** [all] Error 2




AFAIKT OSX failure has nothing to do with my changes, but why does it fail than ...

**Comment by berndhahnebach** [comment]
Just realized, it fails on FreeCAD master too ...

**Comment by yorikvanhavre** [comment]
Yes apparently something with specific OSX stuff, the error is not in FreeCAD source code... In any case your PR passes on all other platforms so I'm merging now

**Pull request closed without merging**
