### PR TITLE
[Sketcher] Give knot information in insert knot command

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Gives some context to where the knot is going to be inserted w.r.t. other knots in the b-spline.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5420">pipeline status</a> for feature branch [PR_5420](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5420). Pipeline [454093403](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/454093403) was triggered at [ca875e7](https://github.com/FreeCAD/FreeCAD/pull/5420/commits/ca875e7e354e0e5d1c2234a73c797583af363c44). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5420">pipeline status</a> for feature branch [PR_5420](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5420). Pipeline [454094519](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/454094519) was triggered at [bee1093](https://github.com/FreeCAD/FreeCAD/pull/5420/commits/bee10934c46c165c4586ef41e5d311d85a985d40). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by abdullahtahiriyo** [comment]
@AjinkyaDahale 

Could you take a look to this?
https://forum.freecadweb.org/viewtopic.php?p=568723#p568723

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale
> 
> Could you take a look to this? https://forum.freecadweb.org/viewtopic.php?p=568723#p568723

@abdullahtahiriyo thanks for bringing it to my notice. I'll take a look if I can at least find where this happens. Meanwhile, could you create a bug report if you haven't already?

**Comment by luzpaz** [comment]
Bugtracker migration to GH happens tomorrow. Perhaps wait a day till that is done and then file new ticket?

**Comment by AjinkyaDahale** [comment]
> Bugtracker migration to GH happens tomorrow. Perhaps wait a day till that is done and then file new ticket?

so be it

**Comment by AjinkyaDahale** [comment]
> Bugtracker migration to GH happens tomorrow. Perhaps wait a day till that is done and then file new ticket?

@luzpaz what's the ETA? If it's going to take time, I'll move on to other things for the time being.

**Pull request merged**
