### PR TITLE
AddonManager: Add DesignSPHysics workbench icon

### PR DESCRIPTION
**Pull request by luzpaz**
Closes https://github.com/DualSPHysics/DesignSPHysics/issues/14  
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/37

### CODE REVIEW

**Comment by luzpaz** [comment]
Just one thing, the .svg is 648K which is unnecessary. It's already 'minified' but we should compress it further, any ideas ?

**Comment by vocx-fc** [comment]
What does it mean it is "minified"?

The SVG icon is way too big. It should be 64x64 px max. This thing has a native size of 1024x1024 px. Also, one of the elements, the blue-redish waves, is in fact a bitmap embedded in the file. Without this bitmap, the file size reduces to 5 KB.

I don't think this should be included in the Addon Manager like this. The waves should be re-drawn in Inkscape as vector elements (paths). They should also be simpler; right now they have way too many details (many small colored circles), that these details won't be noticeable at the normal resolutions at which the icons would be displayed, from 64x64 px to 16x16 px.

Said in another way. The image is fine as a splash screen, but not as an icon.

**Comment by luzpaz** [comment]
I'll post it to the UI/UX forum and ask if someone can scale this down then.

**Comment by vocx-fc** [comment]
It's not just about scaling. After all, it is an SVG already, it can be scaled indefinitely. But the bitmap image should be re-drawn to be a vector graphic or "path" in Inkscape terms.

**Comment by luzpaz** [comment]
> What does it mean it is "minified"?

I thought it was something that had to do with compression, but it's actually just taking whitespace out of .svg markup, like you would minify a .js file, if you will. So not very helpful actually.

**Comment by luzpaz** [comment]
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=34&t=40136

**Comment by luzpaz** [comment]
Thanks @vocx for modifying the SVG to an appropriate size. Note: @zlotny please check out https://forum.freecadweb.org/viewtopic.php?f=34&t=40136 just so you know what we've done. If you want to change this feel free to submit a PR. 

This PR is ready for merge

**Pull request merged**
