### PR TITLE
[0.17] FEM: fixes in import and export of VTK data

### PR DESCRIPTION
**Pull request by berndhahnebach**
- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

https://forum.freecadweb.org/viewtopic.php?f=18&t=27105
https://forum.freecadweb.org/viewtopic.php?f=18&t=21571&start=70#p221591

### CODE REVIEW

**Comment by berndhahnebach** [comment]
compileerror here https://github.com/FreeCAD/FreeCAD/pull/1368/commits/bf0e7144ac056f2ff177f6f3b7d5f30af5638fd7 ... It does compiles flawless on my Debian Stretch .

Does someone has an idea, or should I remove the commit ?

**Comment by sgrogan** [comment]
> > Does someone has an idea

Travis uses Ubuntu 14.04 that has a too old version of VTK so Pipeline post processing is disabled at compile time. VTK >= 6.2 is required.

**Comment by berndhahnebach** [comment]
ahh ... thanks, will fix it as soon as I'm on my computer ...

**Comment by sgrogan** [comment]
Fails do this commit in master https://github.com/FreeCAD/FreeCAD/commit/dbad77bd7955e6eaa0f5feba7b2ff27c2cd878e8
I am on it.

**Comment by yorikvanhavre** [comment]
It might be because cmake wasn't triggered... I wonder if the execute_process instructions shouldn't be changed by something more cmakish...

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
