### PR TITLE
PartDesign: Fix uptolast ends too soon

### LINKED ISSUE #7189: [Bug] Pad "Up to Last" can end too soon
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

TODO

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Manjaro Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.29506 +1 (Git)
Build type: Release
Branch: pd-more-revol-options (No changes to pad)
Hash: 197797fc76cb77dff296d694844ce8e4dcb366fc
Python 3.10.5, Qt 5.15.5, Coin 4.0.1, Vtk , OCC 7.5.3
Locale: English/United States (en_US)
Installed mods: 
  * Curves 0.4.4
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

PartDesign

### Issue description

If a looping face intersects a pad twice in a single direction, once as the last intersection, it only goes till the first instance instead of all the way.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix #7189 in many cases but still fails if the sketch has a hole at it center of gravity.
image

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by FlachyJoe** [comment]
The problem with the central hole come from OCCT, only one curve located at base center is used to look for intersection.

https://github.com/Open-Cascade-SAS/OCCT/blob/8748042259f22d72b3b076bc5433a54ca42734e4/src/BRepFeat/BRepFeat_MakePrism.cxx#LL478C1-L487C1
```cpp
  else {    // case until support -> topological operation
    MajMap(myPbase,thePrism,myMap,myFShape,myLShape);    
    TColGeom_SequenceOfCurve scur;
    scur.Clear();    
    scur.Append(C); // C = TestCurve(myPbase,myDir)
    LocOpe_CSIntersector ASI1(mySUntil);
    LocOpe_CSIntersector ASI2(mySFrom);
    ASI1.Perform(scur);
    ASI2.Perform(scur);
    TopAbs_Orientation OrU, OrF;
```

**Comment by adrianinsaval** [comment]
This is somewhat of an improvement but the problem with the center hole is a big one, does it also happen if for example you pad two symmetric rectangles with some separation in the middle? It also does not seam to deal with surfaces with more than two intersection (and has code repetition).

curiously however such a case has the opposite problem (this was tested in master, not the PR):
image
it works exactly as desired with up to last, but when using up to face IMO it should have stopped in the first intersection

**Comment by FlachyJoe** [comment]
@adrianinsaval No problem with more prism even without material at the sum's COG.
image
[test_up2last.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11703062/test_up2last.FCStd.zip)


> It also does not seam to deal with surfaces with more than two intersection (and has code repetition).

The two prism creation are needed for each sketch part, which are all treated by the for loop. I removed one duplicate line.

> such a case has the opposite problem

I agree but it needs another issue/fix

**Comment by adrianinsaval** [comment]
It might be possible to fix the bug when there's a center hole by detecting the last face again after the first extrusion

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9743">pipeline status</a> for feature branch [PR_9743](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9743). Pipeline [903575472](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903575472) was triggered at [e361ffd](https://github.com/FreeCAD/FreeCAD/pull/9743/commits/e361ffd35b32b44d7dbe58f8422d5d59221c7d36). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by sliptonic** [comment]
@adrianinsaval @FlachyJoe   Can we get an update on this issue?  Trying to decide whether to merge for 0.21 or hold for 1.0

**Comment by adrianinsaval** [comment]
I will be testing if this has any significant impact on performance for a large number of profiles. If there's no impact I'll merge, if it degrades performance I think we need to check if the double extrude is required before performing it.

**Pull request merged**
