### PR TITLE
modify test dir structure and fix linking gtest with project

### PR DESCRIPTION
**Pull request by berniev**
**** MERGEABLE AFTER CMAKE VERSION BUMP ****

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---
A second baby step to unit testing.

Changes the way google test is installed. Now sourced from GitHub and stored in build files. Apparently this is the recommended method and ensures everything is built with the same settings.

Fixes an issue where google unit tests were not linking to the project (qt ones were).

Changes the structure to provide a shadow of the project src to organise the expected thousands of unit tests.

Qt unit tests are currently in their own folder as they use a different setup. 

To add a google unit test firstly ensure the correct folder exists. If not add it and record it in the parent CMakeLists.txt. Also create a new CMakeLists.txt in this new folder.

Add the test file (.cpp) and add it as a target_sources in the CMakeLists.txt in its folder.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8078">pipeline status</a> for feature branch [PR_8078](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8078). Pipeline [730498026](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/730498026) was triggered at [c6e7683](https://github.com/FreeCAD/FreeCAD/pull/8078/commits/c6e7683a5304a21d8285314e2513e090f34906a8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berniev** [comment]
It seems @wwmayer found another way and committed, so this PR is redundant.

**Comment by wwmayer** [comment]
Do you mean this change? a89d7b7355

**Comment by berniev** [comment]
Yes. I have another nearly ready which to bring back the structure previously proposed, but relies on pending cmake version bump.

To get App AND Base working I had to link to FreeCADApp instead of FreeCADBase. Huh?

I have fmt installed (#8077) into App, Gui and Base (might be hacky?).

How to add fmt to the whole system at once? What to do about Mod etc?

I am finding it necessary to link fmt::fmt to tests, even though already linked to App etc. Seems strange.

**Comment by berniev** [comment]
I'm using lib folder as you did. Much better than my original PR.

**Comment by berniev** [comment]
See #8125 for second attempt

**Comment by berniev** [comment]
> The proper place is src/3rdParty

But ... I abandoned the idea of having fmt source or header files in FC and used external package (fmt seems very widely available) and then just find_package(fmt) and then linked it into App, Base, Gui. Much simpler.

**Comment by wwmayer** [comment]
> But ... I abandoned the idea of having fmt source or header files in FC and used external package (fmt seems very widely available) and then just find_package(fmt) and then linked it into App, Base, Gui. Much simpler.

I basically prefer to use available system packages too but on Windows this will cause some trouble because the LibPacks don't have this library included, yet.

**Pull request closed without merging**
