### PR TITLE
Arch/Draft: Fix transparency vs. alpha issues

### LINKED ISSUE #18295: BIM: opening BIMExample on latest weekly crashes FreeCAD
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:
1. Open BIMExample from Start page
2. FreeCAD crashes without notice

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39416 (Git) Conda
Build type: Release
Branch: main
Hash: f6268ffd2877dadb4440ade541e12c388a517d6e
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * CfdOF 1.29.1
  * Curves 0.6.51
  * dodo 1.0.1
  * fasteners 0.5.31
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.26
  * Rocket 4.0.1
  * sheetmetal 0.5.6
  * Silk 0.1.5
```

### Subproject(s) affected?

BIM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wwmayer**
Fix #18295

### CODE REVIEW

**Comment by wwmayer** [comment]
Yes.

In the past `a` was incorrectly used for the transparency but it should be the alpha channel which is the "inverse" of the transparency: `alpha = 1.0 - transparency`

**Comment by yorikvanhavre** [comment]
Okay, thanks!

We *could* choose to work with rgbt instead of rgba, though, several applications use rgbt, but that's less of a standard...

**Comment by wwmayer** [comment]
If you want RGBT you can add the methods getPackedRGBT/setPackedRGBT to the Color class.

**Comment by yorikvanhavre** [comment]
It was just a theorical question, I don't really have a need for it...  But if someone needs it, then we have an answer :)

**Pull request merged**
