### PR TITLE
Sketcher: bugfixes and improvements in backside edit and section view

### PR DESCRIPTION
**Pull request by 0penBrain**
Fix some bugs in Sketcher backside edit
 * 1st commit: bug in section view not correctly changing side. Was here since feature introduction
 * 2nd commit: bug in vertex selection from backside. Was introduced by a6adfc5 (@abdullahtahiriyo , not a reproach, just you know next time :smile: )
 * 3rd commit: improvement coping with specific cases where cross section may be not correctly behaving

https://forum.freecad.org/viewtopic.php?p=688843#p688843

### CODE REVIEW

**Comment by FEA-eng** [comment]
@luzpaz Can this be marked to be merged for 0.21?

**Comment by luzpaz** [comment]
I know @abdullahtahiriyo is AFK so not sure who would should review it ?

**Comment by Syres916** [comment]
For what it's worth I will be testing this PR for the rest of the week in an effort to at least give some constructive feedback and hopefully assist in getting it merged.

**Comment by chennes** [comment]
I don't see any code problems, so if @Syres916 agrees that the code is now behaving as expected I think we can merge for 0.21. I'll mark it as such.

**Pull request merged**
