### PR TITLE
Gui: refactor navigation cube

### PR DESCRIPTION
**Pull request by realthunder**
Fixing #6689 

@donovaly This is not a small PR, which is why I didn't submitted earlier, although the scope is quite limited. The fix for the anti-alias problem is part of the refactoring. It's not so easy to split out. Anyway, it's up to you whether to merge it now or later.

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6827">pipeline status</a> for feature branch [PR_6827](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6827). Pipeline [530040955](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/530040955) was triggered at [b730616](https://github.com/FreeCAD/FreeCAD/pull/6827/commits/b7306161d1b7c1d7ad8711f8de22b6972356797b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6827">pipeline status</a> for feature branch [PR_6827](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6827). Pipeline [530044059](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/530044059) was triggered at [88363de](https://github.com/FreeCAD/FreeCAD/pull/6827/commits/88363de7f9df7a5587be01ee22451868b4c0a6af). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks!

I would like to have when you could make a very simple PR that only addresses the OpenGL/rendering issue. Things like automatic flipping of the face labels, exposing settings to the UI etc. is stuff for 0.21/1.0.
I think that is doable by taking out this part of the PR here. Can you please create such a PR?

I see that @wwmayer recently pushed some fixes for NaviCube. @realthunder , when you made your PR that only addresses the rendering issue, can you please request a review by @wwmayer ?
(I am still away and have almost no time until mid of next week.)

**Comment by realthunder** [comment]
Just submitted a stripped down PR #6839

**Comment by yorikvanhavre** [comment]
Does it mean this PR is to be closed in favor of #6839, @realthunder ? Or are both still to be merged?

**Comment by donovaly** [comment]
My proposal:
- #6848 will go in for 0.20 (I am back home and can test and merge)
- #6839 is something for 0.21. Since it changes the appearance, I would like to discuss this with the community
- #6827 can in my opinion be closed, since part of it will be committed and another part maybe adapted, depending on the outcome of the discussion. The further parts should then, after #6839 is handled be submitted in a fresh PR.
OK?

**Comment by chennes** [comment]
I think that sounds like a good plan, @donovaly.

**Pull request closed without merging**
