### PR TITLE
CI: Add Ubuntu 24.04 Conda Qt6 to CI.

### PR DESCRIPTION
**Pull request by pinkavaj**

### CODE REVIEW

**Comment by oursland** [comment]
In general, the subset of builds in CI are minimized to utilize cache and CI minutes efficiently.  As the distribution uses `conda` to manage the build dependencies, there isn't any benefit in Ubuntu 24.04 over the existing Ubuntu 22.04.

**Comment by pinkavaj** [comment]
> In general, the subset of builds in CI are minimized to utilize cache and CI minutes efficiently. As the distribution uses `conda` to manage the build dependencies, there isn't any benefit in Ubuntu 24.04 over the existing Ubuntu 22.04.

Right, not much sense to keep it for both 22.04 and 24.04. Not really a pressure to upgrade either, but lets keep up with latest bugs, not with the old ones :) (changed to upgrade to Ubuntu 24.04). I would guess at some point the upgrade should be done anyway, but no hurry ...

**Comment by adrianinsaval** [comment]
probably we can just use ubuntu-latest and rename the workflow to just Linux_Conda. It should not matter much what specific distro and version are being used for this

**Comment by pinkavaj** [comment]
> probably we can just use ubuntu-latest and rename the workflow to just Linux_Conda. It should not matter much what specific distro and version are being used for this

Seems like nice idea to me. If there is no opposition I will (one day) update the MR to follow the suggestion. Anybody any idea why not to go this way?

**Pull request closed without merging**
