### PR TITLE
CI: GitHub workflow release

### PR DESCRIPTION
**Pull request by 0penBrain**
This PR proposes a tentative implementation of building+testing FreeCAD with GH Actions.

### CODE REVIEW

**Comment by 0penBrain** [comment]
https://forum.freecadweb.org/viewtopic.php?f=10&t=52422&p=571972#p571972

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6385">pipeline status</a> for feature branch [PR_6385](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6385). Pipeline [472747351](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/472747351) was triggered at [5372bd0](https://github.com/FreeCAD/FreeCAD/pull/6385/commits/5372bd078e4b6ece60d21e4b223a945df2c56462). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6385">pipeline status</a> for feature branch [PR_6385](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6385). Pipeline [472748465](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/472748465) was triggered at [efdfd66](https://github.com/FreeCAD/FreeCAD/pull/6385/commits/efdfd66fa0a292633de3dfff2e0d979b90472645). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
where is the 3rd party dependency list?

**Comment by 0penBrain** [comment]
@luzpaz No. It's in the Dockerfile used to build the dedicated Docker image used by the workflow.
You can see it here : https://github.com/0penBrain/CItest/blob/master/Dockerfile

If at one time FreeCAD makes use of this PR, Dockerfile should also be pushed somewhere in the repo. ;)

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6385">pipeline status</a> for feature branch [PR_6385](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6385). Pipeline [472992784](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/472992784) was triggered at [f725a60](https://github.com/FreeCAD/FreeCAD/pull/6385/commits/f725a60af54ab9d473feb9b5b1d6bbfd669a7d40). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by 0penBrain** [comment]
Closing this because I see that my workflows are cluttering mainstream repo actions. Don't know why

**Comment by luzpaz** [comment]
How so?

**Comment by 0penBrain** [comment]
> How so?

Not so easy. Have had to move backwards regarding Ninja because it's inefficient in such situation where sources are pulled at each run through Git. Now using Ccache+Make, that overall  should be more efficient. 
My problem ATM is that Ccache is absolutely caching nothing... Will try to find why.

**Comment by luzpaz** [comment]
@0penBrain if you have an spare moments, would you mind reporting some of your findings at https://wiki.freecadweb.org/Ccache ?

**Comment by 0penBrain** [comment]
@luzpaz : my findings are more related to specifics regarding using Ccache in Docker environments, so most probably not helpful for users. ;)
I think I'm close to success. :) Will drop a post about that soon (hopefully).

**Pull request closed without merging**
