### PR TITLE
TechDraw - Add edge midpoint cosmetic vertex fix

### PR DESCRIPTION
**Pull request by pavltom**
This pull request aims to fix evident misplacement of edge midpoint cosmetic vertex when used with Bezier curves.

### CODE REVIEW

**Comment by pavltom** [comment]
For more details please see the TechDraw forum topic [Edge midpoint fix](https://forum.freecadweb.org/viewtopic.php?f=35&t=59582)

**Comment by luzpaz** [comment]
@donovaly would you have a moment to take a look at this ?

**Comment by luzpaz** [comment]
Thanks for the comments :smile:

**Review by donovaly — APPROVED** [review]
it fixes the bug properly and the code is well documented

**Pull request merged**
