### PR TITLE
[TD] geometric Hatch dialog

### PR DESCRIPTION
**Pull request by donovaly**
- use Gui::QuantitySpinBox
- some UI file size policy adjustments

### CODE REVIEW

**Comment by WandererFan** [comment]
why does Scale need to be a Quantity?  isn't scale a dimensionless number?

**Comment by donovaly** [comment]
It is a dimensionless number and therefore I have not set a unit. In the discussion about the decimal point you stated that changing QDoubleSpinBox is not a big thing and can be done also for dimensionless values. Therefore I did this for all dialogs.

**Comment by WandererFan** [comment]
I think that was about [Gui::DoubleSpinBox rather than Gui::QuantitySpinBox](https://forum.freecadweb.org/viewtopic.php?t=35927&start=40#p380159), but I guess if QSB doesn't have a unit type assigned it is OK.

**Comment by WandererFan** [comment]
merged.

**Comment by donovaly** [comment]
> I think that was about [Gui::DoubleSpinBox rather than Gui::QuantitySpinBox]

Yes. Sorry. I'll change that.

**Comment by donovaly** [comment]
Hmm, there is no Gui::DoubleSpinBox available ton the Qt designer plugin and no ui file uses it.

**Pull request merged**
