### PR TITLE
Don't prompt for recompute on toolbit files

### LINKED ISSUE #16765: [CAM] ToolBit default shapes require recompute/save AGAIN.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It seems this  #16540, or related work now causes CAM WB to trigger this message in a variety of situations related to creating/edit or even adding ToolBits to a Job, for example:

Default endmill (may) require recomputation

Due to these being "system" files in install directories, or within appimage/temp dirs proposed solution above is probably best way to move forward with this.

However while I understand the need for the recompute dialog, I do not understand the actual trigger in this case, when it is only than ONE MONTH since those files were updated and released via fix for issue #15902.

Also wondering if other areas of FreeCAD may be negatively affected.

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git) AppImage
Build type: Release
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/Australia (en_AU)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
  * CamScripts
  * Plot 2022.4.17


**DOES NOT OCCUR IN the very recent:

OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git) AppImage
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/Australia (en_AU)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
  * CamScripts
  * Plot 2022.4.17
```

### Subproject(s) affected?

CAM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bgbsww**
Possible fix #16765.

Have not duplicated, can't confirm fix.

Can confirm works correctly on user .FCStd files.

### CODE REVIEW

**Comment by hyarion** [comment]
Isn't there a risk that this creates other issues down the line if we have different codepaths depending on lower vs upper case file extensions?

Is this the only way to see if a file is a toolbit file?
Wouldn't it be better if `Gui::Application::checkForRecomputes` is changed to fix it instead or that the CAM workspace should handle the migration of the files it tries to load.

**Comment by bgbsww** [comment]
There is a risk, although pretty slight.  It is an ugly approach, but short of parameterizing Application::Open the only other alternative is to correct the files.  Gui::Application::checkForRecomputes doesn't know what you are trying to do, it just knows that the file in question isn't up to date.  In any case, this is thrown up as clarity on the bug report, where there is still an open question as to what to do.

**Comment by hyarion** [comment]
I just wrote a comment in the issue this PR tries to fix.

Short story: it looks like you've fixed it already with [this commit](https://github.com/FreeCAD/FreeCAD/pull/16647/commits/bd06567d25dfcf2382806f8a31203c5ba6b109e5) and it was reported with older versions.

**Comment by bgbsww** [comment]
Thanks!  And I did appreciate the comments, although I'll be really happy to throw this in the trash if warranted.

**Comment by bgbsww** [comment]
Not relevant.  Bug did not actually exist.

**Comment by spanner888** [comment]
@bgbsww  I am very puzzled about your statement: " Bug did not actually exist."

Yes it was only present in one or a very few FreeCAD weekly releases, but it surely had a major impact on my FreeCAD use causing those modal dialogs to appear 100s of times. Yes hundreds!

**Comment by bgbsww** [comment]
The current version of the code base does not have the bug.  Thus the
report came in after the bug was already nonexistent.  Yes, that's annoying
for you, but that's what the pre-releases are for - to be tested, not to do
real work with.

**Pull request closed without merging**
