### PR TITLE
[TechDraw] Add new Insert Repetition Count command

### PR DESCRIPTION
**Pull request by pavltom**
This pull request adds a new Dimension Extensions command named "TechDraw_ExtensionInsertRepetition". When the toolbar button is pressed, the user is prompted to enter the repeated feature count and after pressing OK, the dimension is prefixed with the text entered and "× " (multiplicaton sign + space) appended. This comes very handy when describing repeated features like holes, inner threads, etc. The Repeat Count is not limited to numbers, it may be any text up to 31 characters. The limit is rather arbitrary, it can be raised or lowered by changing a constant in the code.

If the prefix is no longer desired, it can be removed by applying the "Remove Prefix" command.

I believe the code should work as expected, however there can be still some problems to be fixed or changes to be made. In any case, please let me know.

### CODE REVIEW

**Comment by luzpaz** [comment]
Any chance you can provide a short screencast of this feature in action ?

**Comment by pavltom** [comment]
@luzpaz Here you go:
[TechDraw_Insert_Repetition_Prefix.webm](https://github.com/FreeCAD/FreeCAD/assets/25648708/fc6707c6-4e9b-4142-9c7a-d3ce8455bf6a)

**Comment by WandererFan** [comment]
Helix test fails in Conda CI are due to recent change in PartDesign.  Not related to this change.

**Comment by WandererFan** [comment]
I would just edit the dimension format spec to say "6x %.3w".

**Comment by pavltom** [comment]
Hi @WandererFan, thank You for merging the pull request. Prepending the "6x" is for sure intelligible, but the ISO standard requires the multiplication sign, which I do not even have on my keyboard. Finding the **×** character in the charmap and keeping it in the clipboard is kind of tedious, so I hope this will make the workflow smoother.

**Pull request merged**
