### PR TITLE
Sketcher: Trim tool, hold click and move. Fixes #6152

### LINKED ISSUE #6152: Sketcher: Add new method for trim sketch
Issue imported from https://tracker.freecad.org/view.php?id=4544

* **Reporter:** Jee-Bee
* **Date submitted:** 1/25/2021
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** sketcher, trim

# Original report text

Add a new method for trimming multiple sketch lines at once.
Description of work flow
- Model a shape that needs a trim
- start trim tool
- click at some point and while clicking move the mouse
- All lines that are crossed remove them till nearest intersection(s)
See images for simple example

# Additional information

image
image

see: https://forum.freecadweb.org/viewtopic.php?f=10&t=54441#p468692

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

### PR DESCRIPTION
**Pull request by PaddleStroke**
Sketcher: Trim tool, hold click and move. Fixes #6152

https://github.com/FreeCAD/FreeCAD/assets/19984177/a0677d48-e11a-4936-8a1e-d6636397d69a

### CODE REVIEW

**Comment by prokoudine** [comment]
The new behavior is vulnerable to fast movements. You need to move the mouse pointer slowly, otherwise the tool will skip some lines on its way. Sometimes those skipped lines would be in the middle and sometimes it would be the last line it crosses.

https://github.com/FreeCAD/FreeCAD/assets/57467/621b3eec-3c73-4142-9c77-26abb50e195a

**Comment by PaddleStroke** [comment]
Yes there's not much way around this, it's because mouseMove triggers only so often. So if mouse goes too fast it won't catch all

**Comment by FEA-eng** [comment]
I tested this, works really well. It's a handy feature. @PaddleStroke Can you undraft it if it's ready?

**Comment by rola22** [comment]
Hello.
What if this tool instead of trimming edges directly would draw polyline, and then edges which cross this polyline would be trimmed?
It can solve mouseMove triggering problem.

**Comment by PaddleStroke** [comment]
Hi and thanks for your suggestion.
I see what you're suggesting. It's how it works in fusion if I recall correctly.
Drawing a line is not a problem. The problem is more how do you know which edge is crossed. And it needs quite a rework of the tool. While this PR was simpler to do as it was modifying the current tool only a little bit. Making as you suggest is a much larger work that I can't do right now.
But if someone wants a project to tackle, feel free to grab this :)

**Pull request merged**
