### PR TITLE
Improved Python style in importOCA code

### PR DESCRIPTION
**Pull request by vocx-fc**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---
Improved the Pythonic style of the code, particularly the spacing and adding docstring to the public functions.

The code was inspected with
```flake8 --ignore=E226,E266,E401,W503 importOCA.py```

The OCA file format is used by the GCAD3D software (http://www.gcad3d.org/) but it's not very popular.

This module isn't maintained but some small improvements were made to have a better style, including printing to the console and possibility of translating the messages.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
Just some hint. It does not make sense to make the formating work on importIFC module. After such a reformating work rebasing does not work anymore. Since we inside refactoreing work for importIFC it does not make sense to break rebaseing. ATM

We should consider to open a forum topic in Arch, BIM, Draft part of the forum to discuss such code formating changes.

cheers bernd

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=23&t=38360

**Comment by yorikvanhavre** [comment]
Agree with @berndhahnebach the IFC importer needs much deeper refactor first...

**Comment by vocx-fc** [comment]
Understood. I won't touch the ImportIFC code, as long as it's being re-worked by others. At most I would add some docstrings, but I'll look into that another time, first I'll look into Draft.

**Pull request merged**
