### PR TITLE
Draft: Introduce mouse delay

### LINKED ISSUE #11807: [Problem] mouse overrides inputs in draft
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Various tools in draft allow both mouse and keyboard input, which is really nice. Keyboard input is preferred when precision is required, but then every move of the mouse above 3D view can reset values entered via keyboard, which can be really frustrating.

Some gifs illustrating the problem:

### Full version info

```shell
FreeCAD 0.22
```

### Subproject(s) affected?

Draft

### Anything else?

Mentioned by ProjectBP: https://forum.freecad.org/viewtopic.php?p=717666#p717666 - on discord we agreed that I'll create the issue on his behalf.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yorikvanhavre**
This PR introduces a new "Mouse delay" preferences located under Edit -> Preferences -> Draft -> Grid and Snapping

* When mouse delay is set to 0, nothing happens, same as how it works now
* When it's set to a value, ex. 1 second, after you enter a number in one of the coordinate fields in Draft/Arch, the mouse will not change the value anymore during 1 second. After that, it resumes normal working.
* If you set the value to something very high, for ex. 3600 (one hour), mouse movement will be disabled after you start entering numeric values, until the command is finished.

This fixes #11807

### CODE REVIEW

**Comment by 4a3** [comment]
and why the difficulties? I pressed the hotkey. activated the input field. I liked it - I introduced the enter. no - escape.. and then catching the direction does not overlap with data entry. why are these risks "not in time"?

**Comment by yorikvanhavre** [comment]
> and why the difficulties? I pressed the hotkey. activated the input field. I liked it - I entered enter. no - escape.. and then the interception of the direction does not intersect with the data entry. why are these risks "untimely"?

Could you explain better? I don't understand what is happening

**Comment by kaiwas** [comment]
> "Mouse delay" preferences located under Edit -> Preferences -> Draft -> Grid and Snapping

How can I play with this?
I did not find the specified settings in the weekly build dated March 1st.
Or should we just wait some more?

**Comment by kaiwas** [comment]
I didn’t immediately realize that this change needed to be compiled independently. 
This is too hard for me. I'll wait for this change in the main branch.

**Comment by yorikvanhavre** [comment]
I will change the default to be something else than 0 so people notice the feature

**Comment by kaiwas** [comment]
> I will change the default to be something else than 0 so people notice the feature

Can you make these changes into the weekly build?

**Comment by yorikvanhavre** [comment]
As soon as they are merged they'll be in the next weekly build

For next M3: This should be good to go!

**Comment by kaiwas** [comment]
I tested the algorithm a little in the weekly build dated March 11th.
It seems this only works in the draft workbench.
for example, when adding walls (as one of the possible examples) - it does not work (((

Uploading simplescreenrecorder-2024-03-12_11.55.56.mp4…

**Comment by kaiwas** [comment]
How long will you have to wait for "feedback"? What if it doesn’t exist (simply because no one uses the draft)?
Today is kind of a bad news day.
I give up.

**Comment by kaiwas** [comment]
Another difficulty arises.
At first, for a very long time I could not understand why the same things work differently in different workbenches.
Somewhere the selection is added with Shift, somewhere with Ctrl, somewhere just by clicking. There “it” works like this, here it works “differently”.

The proposed test will simply add to the heterogeneity.

Maybe make this change for sure and ask as many people as possible to test it on the forum. This will make it clear pretty quickly whether this is good or not.

In addition, the setting is easy to disable. And she doesn't break anything.

It seems to me it's time to take a break from FreeCAD out for a while.

**Comment by yorikvanhavre** [comment]
I can ´t see your video...
But I think what you are describing refers to the two other issues you linked, and not this one?

**Comment by kaiwas** [comment]
> I can ´t see your video...

For some reason the video was broken.
I wrote it down again.
A way to reproduce.
1) Enter data into the input fields to move
2) slightly move the cursor in the 3D window (the object disappears).
3) Confirm the data with the "Enter point" button (the object appears)


https://github.com/FreeCAD/FreeCAD/assets/32273833/948611da-2f21-4640-8968-cdad011814f2

**Comment by yorikvanhavre** [comment]
Ok I could reproduce the problem. Indeed some tools (Move and Rotate basically) switch their ghosts off and on at each mouse move, and they aren't turned back on if the mouse delay is active. I'll work on a fix

**Comment by kaiwas** [comment]
@yorikvanhavre  Hello.
It seems that the Trimex tool cannot be applied if you enter data into the fields. There is no "OK" or "Apply" button. But clicking the mouse does not lead to any result.

This problem may occur in all tools where there is only a “close” button/


https://github.com/FreeCAD/FreeCAD/assets/32273833/7b7a8be8-34e0-437e-8c34-094d054ebe3d

**Comment by yorikvanhavre** [comment]
@kaiwas that's a separate problem... Could you open a new issue? This one has been closed already.

**Pull request merged**
