### PR TITLE
Material cards: add missing properties and add some polymers

### PR DESCRIPTION
**Pull request by donovaly**
This is a PR requested by Bernd: https://forum.freecadweb.org/viewtopic.php?f=38&t=34341#p288053
it adds missing properties for some base material and also ads few more base polymer materials

Since I don't have rights to upload the changed FCMat files for a PR, I attached the full patch containing all changed FCMat files to the forum thread:
https://forum.freecadweb.org/viewtopic.php?f=38&t=34341&p=288225#p288225

### CODE REVIEW

**Comment by berndhahnebach** [comment]
uwe you should start using github. This would make it much more easier to merge your code for werner and yorik.

I will provide a branch to merge for this PR.

BTW: if you use git you will be a FreeCAD developer :-)

**Comment by berndhahnebach** [comment]
this should be fairly easy to archive with git too ...

I will provide a branch to merge for this PR including all cards ...

**Comment by berndhahnebach** [comment]
something went wrong on creation of the cards uwe ... See my branch https://github.com/berndhahnebach/FreeCAD_bhb/commits/materialcardsuwe commits https://github.com/berndhahnebach/FreeCAD_bhb/commit/0352e42fe284806526e209c0cf53461abb2c8410 and https://github.com/berndhahnebach/FreeCAD_bhb/commit/99556a3b2c455f1e7c1647335bbee1868c9bf553

**Comment by berndhahnebach** [comment]
I am able to fix it with not much afford. I will provide an branch to merge ...

**Comment by berndhahnebach** [comment]
@donovaly (uwe): 

would you check if this branch changes what you would like to change ... https://github.com/berndhahnebach/FreeCAD_bhb/commits/materialcardsuwe2

**Comment by berndhahnebach** [comment]
found the culprit. You did run the script without the existing cards. Best is to run the script in source directory. Thus it takes the card meta informations from the existing cards.

Added your data to PR https://github.com/FreeCAD/FreeCAD/pull/1982 and fixed card names and licence.

Bernd

**Comment by berndhahnebach** [comment]
PR could be closed IMHO

**Comment by donovaly** [comment]
> found the culprit. You did run the script without the existing cards. Best is to run the script in source directory. Thus it takes the card meta informations from the existing cards.

Then this should be corrected. I purposely used an empty folder to generate the cards from scratch by avoiding any interferences.
I think there must be a way to generate the cards from scratch.

However, since you included my changes to your PR, I am closing this now.

**Comment by berndhahnebach** [comment]
FULLACK and a way to create them with windows too. This means switcht to Python, IMHO. I started some dev in this regard as well as in the regard of duplicate mat card parser code already. But this will not go into 0.18 version.

**Comment by PrzemoF** [comment]
Can we continue here: https://forum.freecadweb.org/viewtopic.php?f=38&t=34374 ?

**Pull request closed without merging**
