### PR TITLE
[Icons]Reducing the File Size of Core Icons

### PR DESCRIPTION
**Pull request by Reqrefusion**
While messing around with technical drawing icons, I discovered a very effective way to somehow make the files smaller. In this PR, I applied this method to core icons. I don't know if it is necessary to say, but no icons have been changed visually, only the file sizes have been reduced. So the abundance of icons is not a problem because they are all the same. I also replaced unused icons. Complete deletion of these is not the subject of this PR. I only made changes to files that might make sense. So I won't be adding any more icons.

### CODE REVIEW

**Comment by Reqrefusion** [comment]
> What was the trick to make them smaller?

I found the icon used to have the smallest file size. I adjusted its size to be smaller. I copied the things from the old file verbatim and copied them verbatim into the clean file. So nothing fancy. It has been tested and checked that it is working properly.

**Comment by marcuspollio** [comment]
Do not remove metadata (license, author, identifier, relation, description, etc.)
All Inkscape/Sodipodi specific stuff can be removed.

To do a safe cleanup, use in Inkscape: File > Cleanup Document, and then save as Plain SVG.

**Comment by Reqrefusion** [comment]
> Do not remove metadata (license, author, identifier, relation, description, etc.) All Inkscape/Sodipodi specific stuff can be removed.
> 
> To do a safe cleanup, use in Inkscape: File > Cleanup Document, and then save as Plain SVG.

It was redone to look like this.

**Comment by hyarion** [comment]
Be careful here. SVG is also our source format when using inkscape. This removes inkscape specific data. The equivalent for source code would be to remove all comments in the source code.

If we really want to optimize the file sizes, then I think it would be better to add a build step which does this when copying the files to the build directory.

**Comment by maxwxyz** [comment]
IMO should be on hold for all the new icons

**Comment by Reqrefusion** [comment]
https://github.com/FreeCAD/FPA-grant-proposals/issues/19 It was closed accordingly.

**Pull request closed without merging**
