### PR TITLE
BSpline Curve and Surface approximate

### PR DESCRIPTION
**Pull request by tomate44**
- fixes BSplineCurve approximate sometime failing with smoothing algorithm
- adds Parametrization and smoothing algorithm to BSplineSurface approximate

### CODE REVIEW

**Comment by wwmayer** [comment]
Your build fails on all test platforms with:

> /home/travis/build/FreeCAD/FreeCAD/src/Mod/Part/App/GeometryCurvePyImp.cpp:611:28: error: out-of-line definition of 'toNurbs' does not match any declaration in 'Part::GeometryCurvePy'
PyObject* GeometryCurvePy::toNurbs(PyObject * args)
                           ^~~~~~~
1 error generated.

**Comment by luzpaz** [comment]
why does this commit change 528 files?

**Comment by tomate44** [comment]
Because I made something wrong obviously ;D
I'll try to find what went wrong.
Thanks

**Comment by Patola** [comment]
Seems a lot of files have 0 lines of difference, isn't that something to do with end-of-line characters? (CR - LF - CR+LF)

**Comment by luzpaz** [comment]
yea, makes sense, i recently submit a commit that did something similar. I think it has to do with https://freecadweb.org/tracker/view.php?id=1352

**Comment by bblacey** [comment]
`git config --global core.autocrlf input`

**Comment by tomate44** [comment]
I choosed the raw way.
I deleted my repo and restart from scratch.
Newbie-certified ;-)

**Pull request closed without merging**
