### PR TITLE
[Sketcher] Improve angle & radius constraint rendering

### PR DESCRIPTION
**Pull request by PaddleStroke**
This PR improve the rendering of the (2lines) angle and radius SoDatumLabel
image
image

### CODE REVIEW

**Comment by PaddleStroke** [comment]
@FlachyJoe please check here, I have added arc helpers for radius constraints. This would be the best for arc - something distances. What is the status on those btw?

**Comment by obelisk79** [comment]
This is quite interesting. Seems like an improvement based off what I see in the screenshots.

**Comment by PaddleStroke** [comment]
@wwmayer this is touching SoDatumLabel which you know so perhaps you would be willing to review this PR please ?

**Comment by wwmayer** [comment]
The changes in SoDatumLabel are OK.

**Comment by PaddleStroke** [comment]
@adrianinsaval care to check this one out? Werner already reviewed changes in SoDatumLabel

**Comment by FlachyJoe** [comment]
> This would be the best for arc - something distances

Certainly yes ! But in fact arc helper is needed for all the constraints, see floating icons for tangencies in https://github.com/FreeCAD/FreeCAD/pull/9166#issuecomment-1493435856

**Comment by PaddleStroke** [comment]
Do those floating icons actually happen in real life work ? I am not sure there are so many tangencies to arcs in random positions that would end up floating.
If it does happen and is a real issue, then a possibility would be to draw arc helpers for geometric constraints when needed as well. But this may be much more work as geometric constraints do not have soDatumLabels (afaik).

**Comment by FlachyJoe** [comment]
@PaddleStroke we understand the left tangent only with the right part of the sketch 
image

**Comment by PaddleStroke** [comment]
I see.
But in these cases, do you think the user is going to toggle arc helpers ? It's likely that if you don't understand the sketch you will select associated geometries instead. I'm not sure the arc helpers would help much to understand in the sketch you screenshoted.

**Comment by PaddleStroke** [comment]
But yes arc helpers similar to the one I made for radius in this PR would probably help I guess.

**Comment by maxwxyz** [comment]
@FlachyJoe it is still present, shall I create an issue?
grafik

**Comment by FlachyJoe** [comment]
@maxwxyz Not sure why but 2 commits was lost.

**Pull request merged**
