### PR TITLE
[Gui] FreeCADGuiInit.py: address some GH action reports

### PR DESCRIPTION
**Pull request by donovaly**
- superfluous parens and loo long lines reported [here](https://github.com/FreeCAD/FreeCAD/pull/8260/commits/19712db498843950a8cd1f9daa09fd785915246d#diff-fe1bd12fc229253965f0c5fc201fcb834f679a42b5d4836813595b8e0a50b4ca)

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8261">pipeline status</a> for feature branch [PR_8261](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8261). Pipeline [761016508](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/761016508) was triggered at [edadcb5](https://github.com/FreeCAD/FreeCAD/pull/8261/commits/edadcb5be995f0ccffdc3caf2b05d19463a71c29). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
I wonder if we can achieve consensus on using Black on the Python, at least in Core. Then we could just run it as a recommit hook and never worry about it again. I'm going to merge this as-is, but I think it might be worth a forums discussion.

**Comment by donovaly** [comment]
> I wonder if we can achieve consensus on using Black on the Python, at least in Core

Would be fine with me because then we save debates and can focus on the coding. Can you please discuss this at the FOSDEM meeting?

**Comment by chennes** [comment]
If there is interest in the topic, I'll start a discussion about it.

**Comment by donovaly** [comment]
> If there is interest in the topic, I'll start a discussion about it.

Thanks.

**Pull request merged**
