### PR TITLE
Task panel for balloons

### PR DESCRIPTION
**Pull request by fjullien**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by fjullien** [comment]
@WandererFan it now looks like what you did for Leader lines.

**Comment by WandererFan** [comment]
Did some quick testing this morning.  Seems to be some glitches:
if balloon already in document, 
  - Balloon create function active on document load?
  - Ballon cursor active outside of QGView
Cursor stuck in Page tab.  Can not access other apps (ex ScreenGrabber)Balloon create function active on document load
Can't escape balloon creation?
No dialog appears

**Comment by fjullien** [comment]
> Did some quick testing this morning. Seems to be some glitches:

Is this some new glitches ? Related to this new Task panel ?

> --if balloon already in document,
> 
>     * Balloon create function active on document load?
> 

Can you elaborate please ?

>     * Ballon cursor active outside of QGView

You mean you click on ballon command then, you don't click on a View ?

>       -- Cursor stuck in Page tab.  Can not access other apps (ex ScreenGrabber)

It was supposed to force user to place a balloon once the command is active.

>       -- Balloon cursor active on document load

??

>       -- Can't escape balloon creation?

No, and it's not good.

>       -- No dialog appears

Dialog appears in Task panel when double clicking on balloon label. We could make it appears when the command is active.

https://pasteboard.co/Ieg2w6u.gif

**Comment by WandererFan** [comment]
Discussion continues on FC Forum PMs

**Pull request closed without merging**
