### PR TITLE
[For v0.19]Linux spacenav

### PR DESCRIPTION
**Pull request by tsadowski**
3D-Mice now also work under Wayland/XWayland when FreeCAD is built to use the libspacenav polling interface. The X11 interface is still supported but polling works under X11 as well.

The changed Implementation for Spacenav/3Dconnexion devices compiles on all platforms. All Linux combinations have been tested.
See also:
https://forum.freecadweb.org/viewtopic.php?style=4&f=3&t=29766

Cheers,
Torsten

### CODE REVIEW

**Comment by tsadowski** [comment]
The reason for the failure must be somewhere else. Windows tries to include GuiNativeEventLinux.h

I will setup a windows build.

**Comment by wwmayer** [comment]
OK, you're right, the build failure is not caused by including the header inside the class declaration. But still I think this should be done in a proper C++ way, also because I am not sure how Qt's moc handles all this.

In order to make the changes build on Windows the following changes must be done:
GuiNativeEventLinux.h: Replace slots with Q_SLOTS. It's probably not mandatory to fix this issue but due to possible conflicting macros we don't use the short form of Qt macros but the long form like Q_SIGNALS, Q:SLOTS, Q_EMIT and so on

GuiNativeEventWin32.cpp:
Replace GuiNativeEventLinux.h with GuiNativeEventWin32.h
Replace the argument of initSpaceball to QMainWindow *mainWindow
Replace the argument of postMotionEvent with mainApp->postMotionEvent(motionDataArray);

GuiNativeEventWin32.h:
Replace #include<QAbstractNativeEventFilter> with 
#if QT_VERSION >= 0x050000
#include "GuiRawInputEventFilter.h"
#endif
Remove the class declaration of RawInputEventFilter because it's already declared and implemented in GuiRawInputEventFilter.h

GuiRawInputEventFilter.h:
Add #include <QAbstractNativeEventFilter>

**Comment by tsadowski** [comment]
FreeCAD now builds for me on all platforms. Unluckily it does not start on Windows. It exits immediately without error. I will try to debug this.

**Comment by tsadowski** [comment]
I am still fighting with the Windows build system. FreeCAD did compile and link with an old Libpack from Sourceforge but the Python initialization failed. With the new Libpack from sgrogan's github repo I get missing symbol link errors against the OpenCASCADE libs. Otherwise it seems to compile cleanly and works as far as I can test it. The Travis Mac build fails because the Homebrew setup exceeds the log length even before it starts on FreeCAD.

**Comment by skoulik** [comment]
Good day guys,
I've started following recently and I am keen to wrestle with the Windows build (mainly because I want to use FreeCAD on Windows and I face problems that I want to try to debug: rendering issues on 18_pre; crash on creating a sketch on 17). Is there anywhere published an up-to-date list of dependencies required to build FreeCAD? Or at least a maintained windows build of LibPack for starters. Thank you.

**Comment by wwmayer** [comment]
@skoulik Here you will find a libpack https://github.com/sgrogan/FreeCAD/releases but don't know if this already uses Qt5.

**Comment by wwmayer** [comment]
> FreeCAD now builds for me on all platforms. Unluckily it does not start on Windows. It exits immediately without error. I will try to debug this.

Inside "bin" of your build directory you have to create the sub-directory "platforms" and there you must put in qwindows.dll or qwindowsd.dll, respectively.

**Comment by wwmayer** [comment]
It seems this bug has disappeared now: https://freecadweb.org/tracker/view.php?id=3685

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
