### PR TITLE
Fem: Add partial support for hexahedral elements

### LINKED ISSUE #5698: FEM, mesh, support for meshing quads and hexa element for FEM
Issue imported from https://tracker.freecad.org/view.php?id=3049

* **Reporter:** berndhahnebach
* **Date submitted:** 5/26/2017
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** confirmed
* **Tags:** 

# Original report text

At the moment the mesher in FEM only supports Tetraeder volume elements and triangle face elements. Both the SMESH netgen and GMSH mesher support meshing quad and hexa elements. Thus it would be great if FreeCAD would do too. 

https://forum.freecadweb.org/viewtopic.php?f=18&t=20796
https://forum.freecadweb.org/viewtopic.php?f=22&t=20351

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by berndhahnebach 2018-11-26 02:40
https://forum.freecadweb.org/viewtopic.php?f=18&t=32106&start=10#p269334

### PR DESCRIPTION
**Pull request by marioalexis84**
As discussed with @FEA-eng, this gives partial support for hexahedral elements meshing.

### CODE REVIEW

**Comment by FEA-eng** [comment]
A few notes:
- one test has to be updated because the checks are failing
- can you unlink the issue so that it's not closed automatically (since only a small part of it will be completed) ? In such cases, I just mention the issue without using keywords like "fixes"
- it seems that second-order quad and hex elements can't be created this way even though Gmsh should be able to handle this. Can you check it ? Those elements should be S8 and C3D20, respectively (Gmsh may name them differently, one has to be careful).

**Comment by marioalexis84** [comment]
> can you unlink the issue so that it's not closed automatically (since only a small part of it will be completed) ? In such cases, I just mention the issue without using keywords like "fixes"

Of course, I just thought the problem would be replaced by another one.

>it seems that second-order quad and hex elements can't be created this way even though Gmsh should be able to handle this

What parameters for gmsh are you using? I can create `S8` and `C3D20`.

**Comment by FEA-eng** [comment]
> What parameters for gmsh are you using? I can create `S8` and `C3D20`.

I test it with all defaults:

gmsh

Including 2nd order but linear elements are generated:

gmsh 2

**Comment by marioalexis84** [comment]
Please, set `SecondOrderIncomplete` to `true`.
For `S8` set `SubidvisionAlgorithm` to `All Quadrangles`

**Comment by FEA-eng** [comment]
> Please, set `SecondOrderIncomplete` to `true`. For `S8` set `SubidvisionAlgorithm` to `All Quadrangles`

All right, it works now, thanks.

**Comment by marioalexis84** [comment]
I think it's better to force `SecondOrderIncomplete` to `1` if `SubdivisionAlgorithm` is `All Quadrangles` or `All Hexahedra`.
Currently the internal workflow is as follows:
* Create the mesh with gmsh and export it as a .unv file.
* Create `FemMesh` object and read the .unv file using Salome Mesh.
* Export to .inp file (if selected solver is CalculiX).

After some study of gmsh and Salome Mesh source code, I found some limitations when working with .unv files:
With second order elements, `SubdivisionAlgorithm` equal to `All Hexahedrons` and `SsecondOrderIncomplete` equal to `0`, gmsh creates a 27-node element, but  Salome Mesh only reads 8 nodes and creates an 8-node hexahedron.
By setting `SecondOrderIncomplete` to 1, gmsh creates a 20-node hexahedron which Salome Mesh can correctly read.
The same goes for quadrangles: without `SecondOrderIncomplete`, gmesh creates a 9-node quadrangle that Salome cannot fully read, so `SecondOrderIncomplete` is needed to create the 8-node quadrangle.

In addition, we must take into account the possible limitations on the solver side when working with this variety of elements.

**Comment by marioalexis84** [comment]
>If you decide to add more ways to create hex elements in the future, let me know and we’ll try to figure this out. I have some ideas but they might be more difficult to implement.

It is necessary to take into account not only gmsh's capabilities, but also those of Salome.

**Comment by chennes** [comment]
@marioalexis84 is this good to merge now?

**Comment by FEA-eng** [comment]
> I think it's better to force `SecondOrderIncomplete` to `1` if `SubdivisionAlgorithm` is `All Quadrangles` or `All Hexahedra`. 

Right, this would definitely make sense.

> It is necessary to take into account not only gmsh's capabilities, but also those of Salome.

Yes, but it seems that Gmsh is somewhat superior (especially with extruded/revolved meshes) and might be easier to integrate in this regard. But of course we could also utilize some strengths of Salome, if possible.

**Comment by FEA-eng** [comment]
> The same goes for quadrangles: without `SecondOrderIncomplete`, gmesh creates a 9-node quadrangle that Salome cannot fully read, so `SecondOrderIncomplete` is needed to create the 8-node quadrangle.

Great, thanks to that this PR can also fix #12526

Thus, I think that `SecondOrderIncomplete` should be enabled by default also when `RecombineAll` is set to true.

**Comment by marioalexis84** [comment]
`SecondOrderIncomplete` property is removed and set internally according to the values of `SubdivisionAlgorithm` and `RecombineAll`properties.

**Comment by marioalexis84** [comment]
> @marioalexis84 is this good to merge now?

Ready. Just waiting for @FEA-eng  testing.

**Comment by FEA-eng** [comment]
> Ready. Just waiting for @FEA-eng testing.

I tested it after the newest change, It's working as expected.

**Pull request merged**
