### PR TITLE
TechDraw - SVG handling changes

### PR DESCRIPTION
**Pull request by pavltom**
Hello,

there are 2 commits in this PR:

1) Replacing all SVG handling via Regexes to proper XML DOM manipulation
In TechDraw code there were still residues of SVG manipulation via Regexes. Unfortunately, SVG is a type of XML document and as such it can not be handled by plain regular expressions safely. For example when "<" or ">" character is typed into an editable symbol, the symbol SVG rendering breaks and the symbol itself disappears, because the SVG source is invalid.

2) Insert BOM on the beginning of the exported SVG
At least with combination Windows - Libre Office, if some non-ASCII characters are used in TechDraw page (degree character in angular dimension is enough), Libre Office won't show the imported SVG. With BOM on the beginning of SVG file it works flawlessly.

### CODE REVIEW

**Comment by pavltom** [comment]
Travis build on Windows ends with
:
cp: cannot create regular file 'bin/zlibd.dll': No space left on device
tee: runlog.txt: No space left on device
Assertion failed!

**Comment by vocx-fc** [comment]
That out of space error is unfortunate. I guess as long as it works in your computer it's fine. See, [Travis build failure](https://forum.freecadweb.org/viewtopic.php?p=338444#p338444).

**Comment by WandererFan** [comment]
Time out on gcc builds.

**Comment by WandererFan** [comment]
Merged.  Thanks Tomas!

**Pull request merged**
