### PR TITLE
Toponaming: Add a plane matching based heuristic to TNP mitigation

### PR DESCRIPTION
**Pull request by bgbsww**
If we're about to tag a reference with a ? missing prefix, look to see if the plane of the referenced element matches one and only one plane of the elements in the shape.  If so, substitute the name of that element into the reference.

Also roughed out to work with edges ( like you would find in a sketch external reference ), but only if they are completely unchanged.  A future version of the code can explore if collinear edges should be supported, which would tend to match the user expectation.  But we need a collinear utility method first.

This should address the common remaining TNPs arising from edge changes in a sketch.

This needs a good amount of human testing.

### CODE REVIEW

**Comment by shaise** [comment]
@bgbsww ,
Can you attach a file that works with the new heuristic but not with the standard tnp?

**Comment by chennes** [comment]
@CalligaroV are you currently testing this? It would be a nice thing to include in 1.0 since I think users will expect this case to work, and the "classic" name-based toponaming mitigation can't handle it.

**Comment by CalligaroV** [comment]
Hi @chennes!

Yes, I started looking at this last night, trying to figure out if this can fix #17041.
Unfortunately ATM it doesn't look so, at least in my local tests.

As I said during yesterday's biweekly developers meeting, now I have again a full time job and therefor I can focus on FC only during evenings and weekends and this may slow down my feedback.

Regardless for that, as I said in https://github.com/FreeCAD/FreeCAD/issues/17041#issuecomment-2395543845, this PR will be my main focus for this week.

I don't want to slow down the merge of this PR, so considering that it also have a unit test I have nothing against merging it as is, in the worst case scenario it will be a valid base for future PRs / refinements.

**Comment by CalligaroV** [comment]
Brief update: haven't yet figured out why it's not working in the specific case of my previous comment but I think I'm tracking this down.

ATM one thing that I think may be the reason why this PR isn't working correctly is that in https://github.com/FreeCAD/FreeCAD/blob/41f1d362c840533299be0e22f03b615fb6f44fb3/src/Mod/Part/App/PartFeature.cpp#L327 `shape` and `searchShape` have been swapped (the signature of this method is https://github.com/FreeCAD/FreeCAD/blob/41f1d362c840533299be0e22f03b615fb6f44fb3/src/Mod/Part/App/TopoShapeExpansion.cpp#L5819)

I'm trying to prove I'm wrong/right but it will take me more time.

About that, @chennes do you want me to give daily updates?
I plan to add another comment in a couple of days, then during the weekend I'll have more time to do research and give feedback

**Comment by chennes** [comment]
@CalligaroV thanks for picking this one up -- no need for daily updates, we're not going to try to merge it into 1.0 now that @bgbsww can't help fight any fires that crop up.

**Comment by CalligaroV** [comment]
Yes.

I was really sad when I heard what happened to him at the last biweekly developers meeting.
Can't do anything about that beside joining the chorus of "Thank you very much Brad for all you did and the person you were, we'll miss you a lot"

And obviously carry on the work he did as much as I can, knowing that I'm not even 1% as skilled as he was.

So, again, thank you very much @bgbsww we'll miss you a lot :cry:

**Comment by CalligaroV** [comment]
Good news (I think).

After quite some tests/study/modifications probably I managed to improve this PR to fix some of the cases of #17041.

Tested modified version of
```ruby
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38946 +3 (Git)
Build type: Debug
Branch: bgbsww-toponamingAdditionalTNPCorrectionHeuristic
Hash: f438ecea82daa979fdeee75dc2d34d0266ee9154
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.8.1
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * Assembly4 0.50.15
  * freecad.gears 1.2.0
  * Beltrami 1.1.0
  * sheetmetal 0.4.24
  * Curves 0.6.44
  * fasteners 0.5.26
  * kicadStepUpMod 11.2.7
  * OpenTheme 2024.8.10
  * Render 2024.8.4
  * Ondsel-Lens 2024.7.5.02
``` 
Against some of the examples provided by the users in the issue.
The outcomes are the following:

 - @7th-fret example:
7th-fret

 - @kkeonline example 1:
kkeonline-1

 - @kkeonline example 2:
kkeonline-2

 - @kkeonline example 3:
kkeonline-3

If the outcomes are acceptable then I'll be happy to publish the modifications needed.

However, as the modifications touch more lines of this PR (and adds modifications also to `src/App/ElementMap.cpp`), I'd like to ask @chennes's opinion (or any maintainer's opinion) about how to publish them.

TIA to everyone!

**Comment by kkeonline** [comment]
> Good news (I think).
> 
> After quite some tests/study/modifications probably I managed to improve this PR to fix some of the cases of #17041.
> 
> Tested modified version of
> 
> ```ruby
> OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
> Word size of FreeCAD: 64-bit
> Version: 1.1.0dev.38946 +3 (Git)
> Build type: Debug
> Branch: bgbsww-toponamingAdditionalTNPCorrectionHeuristic
> Hash: f438ecea82daa979fdeee75dc2d34d0266ee9154
> Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.8.1
> Locale: Italian/Italy (it_IT)
> Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
> Installed mods: 
>   * Assembly4 0.50.15
>   * freecad.gears 1.2.0
>   * Beltrami 1.1.0
>   * sheetmetal 0.4.24
>   * Curves 0.6.44
>   * fasteners 0.5.26
>   * kicadStepUpMod 11.2.7
>   * OpenTheme 2024.8.10
>   * Render 2024.8.4
>   * Ondsel-Lens 2024.7.5.02
> ```
> 
> Against some of the examples provided by the users in the issue. The outcomes are the following:
> 
> * @7th-fret example:
>   7th-fret
>         
>           [
>             
>           
>               7th-fret
>             ](https://private-user-images.githubusercontent.com/144716783/375989786-b3a7516d-9d3e-4649-98c5-0152dbec107e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjU3MzIsIm5iZiI6MTczMTc2NTQzMiwicGF0aCI6Ii8xNDQ3MTY3ODMvMzc1OTg5Nzg2LWIzYTc1MTZkLTlkM2UtNDY0OS05OGM1LTAxNTJkYmVjMTA3ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2I1OGVhZWQ4YmNkZmIyMzY3ZWEzNzNhNTI1NGI5NDFlYWI0MmVmOWJlN2MyYTRiNTIyNWJlMWNlOWZmYTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E_fpWVkx3xSWYmkUCo3yGKC9kZVABu1W-6hAD9EASlY)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://private-user-images.githubusercontent.com/144716783/375989786-b3a7516d-9d3e-4649-98c5-0152dbec107e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjU3MzIsIm5iZiI6MTczMTc2NTQzMiwicGF0aCI6Ii8xNDQ3MTY3ODMvMzc1OTg5Nzg2LWIzYTc1MTZkLTlkM2UtNDY0OS05OGM1LTAxNTJkYmVjMTA3ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2I1OGVhZWQ4YmNkZmIyMzY3ZWEzNzNhNTI1NGI5NDFlYWI0MmVmOWJlN2MyYTRiNTIyNWJlMWNlOWZmYTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E_fpWVkx3xSWYmkUCo3yGKC9kZVABu1W-6hAD9EASlY)
> * @kkeonline example 1:
>   kkeonline-1
>         
>           [
>             
>           
>               kkeonline-1
>             ](https://private-user-images.githubusercontent.com/144716783/375989812-410dfa58-b0cc-4c38-9013-c4c6c178acfd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjU3MzIsIm5iZiI6MTczMTc2NTQzMiwicGF0aCI6Ii8xNDQ3MTY3ODMvMzc1OTg5ODEyLTQxMGRmYTU4LWIwY2MtNGMzOC05MDEzLWM0YzZjMTc4YWNmZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjZlNzFlMTQwNmE5MWUzZGY4ZGY3YzE2NTRhYTIxMTI2YmZjZTYyMTNjYjkzY2FiYjY5Yjg1OGFkY2I4YzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.29VCCD03wACdKEp0wjE1hrOY6mAoAvrW0RuHg2hsPck)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://private-user-images.githubusercontent.com/144716783/375989812-410dfa58-b0cc-4c38-9013-c4c6c178acfd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjU3MzIsIm5iZiI6MTczMTc2NTQzMiwicGF0aCI6Ii8xNDQ3MTY3ODMvMzc1OTg5ODEyLTQxMGRmYTU4LWIwY2MtNGMzOC05MDEzLWM0YzZjMTc4YWNmZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjZlNzFlMTQwNmE5MWUzZGY4ZGY3YzE2NTRhYTIxMTI2YmZjZTYyMTNjYjkzY2FiYjY5Yjg1OGFkY2I4YzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.29VCCD03wACdKEp0wjE1hrOY6mAoAvrW0RuHg2hsPck)
> * @kkeonline example 2:
>   kkeonline-2
>         
>           [
>             
>           
>               kkeonline-2
>             ](https://private-user-images.githubusercontent.com/144716783/375989878-fd6d5ba0-7713-4f69-8bbf-446b0e9ac70c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjU3MzIsIm5iZiI6MTczMTc2NTQzMiwicGF0aCI6Ii8xNDQ3MTY3ODMvMzc1OTg5ODc4LWZkNmQ1YmEwLTc3MTMtNGY2OS04YmJmLTQ0NmIwZTlhYzcwYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDBiYWRiOWZmYTk5ODI1YTM2YjYyMjg3NjFhZTQzMGVkZDE2YmQwZDZhOWRkZjYzMmQwZGMzMDJlYTk1N2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.am-I9SswFEiPM_EfY7r1rTk6hc9GovIvMOt8MHSeOqI)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://private-user-images.githubusercontent.com/144716783/375989878-fd6d5ba0-7713-4f69-8bbf-446b0e9ac70c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjU3MzIsIm5iZiI6MTczMTc2NTQzMiwicGF0aCI6Ii8xNDQ3MTY3ODMvMzc1OTg5ODc4LWZkNmQ1YmEwLTc3MTMtNGY2OS04YmJmLTQ0NmIwZTlhYzcwYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDBiYWRiOWZmYTk5ODI1YTM2YjYyMjg3NjFhZTQzMGVkZDE2YmQwZDZhOWRkZjYzMmQwZGMzMDJlYTk1N2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.am-I9SswFEiPM_EfY7r1rTk6hc9GovIvMOt8MHSeOqI)
> * @kkeonline example 3:
>   kkeonline-3
>         
>           [
>             
>           
>               kkeonline-3
>             ](https://private-user-images.githubusercontent.com/144716783/375989913-fa446e3a-5a50-4ad2-a19e-ff7c120169b7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjU3MzIsIm5iZiI6MTczMTc2NTQzMiwicGF0aCI6Ii8xNDQ3MTY3ODMvMzc1OTg5OTEzLWZhNDQ2ZTNhLTVhNTAtNGFkMi1hMTllLWZmN2MxMjAxNjliNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWQ4NjA3MTU3M2UyMDJlMTIzYjJhMjE0MTc4OTJlYjZjZDFlNDQxMzk1NTBhZDk0ZjYyYzlhZmE5NWQwYzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.42Slq2Z9GP8bKqf4eq9gS0BIC7oa0cFlqaWKSKe1ooQ)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://private-user-images.githubusercontent.com/144716783/375989913-fa446e3a-5a50-4ad2-a19e-ff7c120169b7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjU3MzIsIm5iZiI6MTczMTc2NTQzMiwicGF0aCI6Ii8xNDQ3MTY3ODMvMzc1OTg5OTEzLWZhNDQ2ZTNhLTVhNTAtNGFkMi1hMTllLWZmN2MxMjAxNjliNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMzU3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWQ4NjA3MTU3M2UyMDJlMTIzYjJhMjE0MTc4OTJlYjZjZDFlNDQxMzk1NTBhZDk0ZjYyYzlhZmE5NWQwYzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.42Slq2Z9GP8bKqf4eq9gS0BIC7oa0cFlqaWKSKe1ooQ)
> 
> If the outcomes are acceptable then I'll be happy to publish the modifications needed.
> 
> However, as the modifications touch more lines of this PR (and adds modifications also to `src/App/ElementMap.cpp`), I'd like to ask @chennes's opinion (or any maintainer's opinion) about how to publish them.
> 
> TIA to everyone!

any update on this ?

**Comment by chennes** [comment]
I will take another look at this this upcoming week.

**Comment by maxwxyz** [comment]
@chennes did you already look at this?

**Comment by 3x380V** [comment]
This one causes SEGFAULT:
```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f6cfce5b050]
#1  0x7f6,cc0,fad,926 in TopoDS_Shape::ShapeType() const from /home/ladis/src/FreeCAD-build-qt5/Mod/Measure/Measure.so+0x18
#2  0x7f6,c93,88f,d4d in Part::Feature::getExportElementName(Part::TopoShape, char const*) const from /home/ladis/src/FreeCAD-build-qt5/Mod/Part/Part.so+0xbd9
#3  0x7f6,c93,88f,0f4 in Part::Feature::getElementName(char const*, App::GeoFeature::ElementNameType) const from /home/ladis/src/FreeCAD-build-qt5/Mod/Part/Part.so+0xf4
#4  0x7f6,d00,167,4d3 in App::GeoFeature::resolveElement(App::DocumentObject*, char const*, App::ElementNamePair&, bool, App::GeoFeature::ElementNameType, App::DocumentObject const*, char const**, App::GeoFeature**) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x3f9
#5  0x7f6,d00,222,b41 in App::PropertyLinkBase::_registerElementReference(App::DocumentObject*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, App::ElementNamePair&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x11d
#6  0x7f6,d00,237,adc in App::PropertyXLink::onContainerRestored() from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0xc2
#7  0x7f6,d00,235,d89 in App::PropertyXLink::setSubValues(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&, std::vector<App::ElementNamePair, std::allocator<App::ElementNamePair> >&&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0xb3
#8  0x7f6,d00,236,944 in App::PropertyXLink::setValue(App::DocumentObject*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&, std::vector<App::ElementNamePair, std::allocator<App::ElementNamePair> >&&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x780
#9  0x7f6,d00,239,9bd in App::PropertyXLink::Restore(Base::XMLReader&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0xbc7
#10  0x7f6,d00,1f9,be6 in App::PropertyContainer::Restore(Base::XMLReader&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x758
#11  0x7f6,d00,062,1a4 in App::ExtensionContainer::Restore(Base::XMLReader&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x36
#12  0x7f6,cff,f6d,1df in App::Document::readObjects(Base::XMLReader&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0xf8b
#13  0x7f6,cff,f6a,376 in App::Document::Restore(Base::XMLReader&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x658
#14  0x7f6,cff,f6f,8de in App::Document::restore(char const*, bool, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x49c
#15  0x7f6,d00,2cf,85e in App::Application::openDocumentPrivate(char const*, char const*, char const*, bool, bool, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x6b8
#16  0x7f6,d00,2cd,e4a in App::Application::openDocuments(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, bool) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0x56c
#17  0x7f6,d00,2cc,f67 in App::Application::openDocument(char const*, bool) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0xc5
```

**Comment by maxwxyz** [comment]
@CalligaroV ^

**Comment by CalligaroV** [comment]
@3x380V your https://github.com/FreeCAD/FreeCAD/pull/16803#issuecomment-2536801387 `SEGFAULT` looks happening during the opening of an already existing file

>```
> #17  0x7f6,d00,2cc,f67 in App::Application::openDocument(char const*, bool) from /home/ladis/src/FreeCAD-build-qt5/lib/libFreeCADApp.so+0xc5
> ```

If so can you please share the file that causes the `SEGFAULT` or a similar file with the same issue?

TIA!

**Comment by 3x380V** [comment]
@CalligaroV, attaching [file](https://github.com/user-attachments/files/18140087/katoda.zip) backtrace comes from.

**Comment by CalligaroV** [comment]
Thanks @3x380V for sharing the file.

ATM all I can do is confirm your issue.

Tested [Weekly Build](https://github.com/FreeCAD/FreeCAD-AppImage/releases/tag/weekly-builds)

```ruby
OS: Linux Mint 22 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.39642 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: c80bb958f377e4d43c6a4075da173a79d153db68
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Fusion
Installed mods: 
  * sheetmetal 0.5.5
  * Beltrami 1.1.0
  * kicadStepUpMod 11.4.1
  * OpenTheme 2024.9.1
  * fasteners 0.5.30
  * Assembly4 0.50.15
  * Render 2024.9.25
  * Curves 0.6.51
  * freecad.gears 1.3.0
``` 

Now I'm compiling https://github.com/FreeCAD/FreeCAD/commit/aa228f2b329793326589b760767e48f49cb7eb1c for debug (I was on another branch)

I'll keep you updated

**Comment by CalligaroV** [comment]
@3x380V I have both good news and bad news.

Good news:
If I add `&& !getDocument()->testStatus(App::Document::Status::Restoring)` after `names.empty()` in https://github.com/FreeCAD/FreeCAD/blob/aa228f2b329793326589b760767e48f49cb7eb1c/src/Mod/Part/App/PartFeature.cpp#L363 then the model loads without `SEGFAULT`

Bad news:
after the first recompute the assembly gets messed up
katodaWithOpeningFix

At this point I don't know how to move on:
If the main focus is to fix the `SEGFAULT` on opening then I'll open a PR with the quick fix wrote above
If we also want, IMHO rightfully, that the assembly doesn't get messed up then I'll need more time to figure out how to fix that issue too.

**Comment by CalligaroV** [comment]
@3x380V thanks for your feedback!

A couple of questions/observations, to avoid misunderstandings:


> I was commenting away whole block 

Do you mean the entire `if` that starts from https://github.com/FreeCAD/FreeCAD/blob/aa228f2b329793326589b760767e48f49cb7eb1c/src/Mod/Part/App/PartFeature.cpp#L363

or have you commented out something else?

About the other issues I'll try to reproduce them in the next weeks.

Regardless for that

> if you are able to play with it for a while you'll find them quickly

If these issues are consequence of the code you commented out then please confirm/tell what you commented out, otherwise for me (and other developers) may not be so simple to figure out the cause of the issues.

Also a list of steps to follow to reproduce the various issues may be useful.

> I'd like to avoid opening issues I cannot react in reasonable time.

Well, IMHO an issue should be raised so that someone with more experience on a specific topic can analyze it and suggest a possible fix.
Obviously it's all up to you: if you need to keep working on your model right now then it would make more sense to stick on the current stable version.
Otherwise if you want (and you can wait) the issue to be fixed than it would make sense to open one/more issues for the problems you're facing.

**Comment by 3x380V** [comment]
@CalligaroV, yes, the entire `if`. I needed a few drawings for manufacturing, so it was obvious choice. Now I'm using your fix.

I'm usually trying to fix issues I found myself or at least find a root cause unless I'm short of time. To me opening issue has some sense only in case people here get bored as all already opened issues become closed :). Anyway, I was able to fix model again. To me it is unclear whenever I should report bugs found by using development version of FreeCAD. Again, this particular file is a playground, many version of FreeCAD were used to create it. Basically, each time I needed to change something, I let my computer build at that time current git version while drinking morning coffee and that version was used to modify model.

So fixing that SEGFAULT is good enough to me and thanks in advance for opening PR for that.

**Comment by 3x380V** [comment]
> Bad news: after the first recompute the assembly gets messed up

That seems to be caused by LCS migration, it even warns about that:
_This file was created with an older version of FreeCAD. Origin axes had incorrect placements, which have now been corrected._
I remember I had to add some strange rotations while assembling model, so perhaps I got this wrong. For the reference, [fixed file](https://github.com/user-attachments/files/18142261/katoda.zip) attached.

**Comment by 3x380V** [comment]
@CalligaroV, problem fixed by #18548 as mentioned above.

**Pull request merged**
