### PR TITLE
Add FREEECAD_USE_CCACHE cmake option

### PR DESCRIPTION
**Pull request by adrianinsaval**
Defaults to ON except for conda compilation on windows, automatic ccache detection has caused me problems in conda compilations using github actions, therefore I add an option to disable it.

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by adrianinsaval** [comment]
merging since it's harmless and helps with packaging

**Comment by adrianinsaval** [comment]
Ok, this was not harmless and I should not have merged this myself. CI now has no caching and takes almost 2h every time, the if statement happens before the option is set so it's always false. I will try to fix this asap but could use some help.

**Comment by adrianinsaval** [comment]
@wwmayer do you know if it's required to find ccache so early in cmake or can I move this to `cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake`?

**Comment by wwmayer** [comment]
> do you know if it's required to find ccache so early in cmake

Yes, it is: https://crascit.com/2016/04/09/using-ccache-with-cmake/

**Pull request merged**
