### PR TITLE
[Icons]Revision of TechDraw Icons(posChain)

### PR DESCRIPTION
**Pull request by Reqrefusion**
#14145

### CODE REVIEW

**Review by kadet1090 — CHANGES_REQUESTED** [review]
Looks fine but needs a bit of technical work with pixel alignment.

For lines to look crisp on as many sizes as possible you must align paths to pixel grid. In order to achieve best possible results try to aim for even pixel values and use odd pixel coordinates only when it is necessary due to for example ensuring even spacing.

**Review by kadet1090 — APPROVED** [review]

**Review by maxwxyz — APPROVED** [review]
complex but still an improvement.

**Comment by Reqrefusion** [comment]
> complex but still an improvement.

It doesn't appear by default anyway. It can be merged like any other.

**Comment by Reqrefusion** [comment]
@chennes It can be merged. It needs to be merged today.

**Pull request merged**
