### PR TITLE
[Part] Preserve pcurves in TopoShapeEdge.split

### PR DESCRIPTION
**Pull request by tomate44**
Edge split() function currently don't transmit the pcurves of the original edge to the split edges.
This can prevent successful build of faces from theses split edges.
Example script : 
```
coords2d = [(0.5, -0.5), (1.0, -0.5), (1.0, 0.5), (0.5, 0.5)]
pts2d = [FreeCAD.Base.Vector2d(u, v) for u, v in coords2d]
pts2d.append(pts2d[0])

sphere = Part.Sphere()

edges = []
for i in range(1, len(pts2d)):
    ls = Part.Geom2d.Line2dSegment(pts2d[i - 1], pts2d[i])
    edges.append(ls.toShape(sphere))

wire = Part.Wire(edges)
face = Part.Face(wire, "Part::FaceMakerSimple")
# Part.show(face)
# Face was successfully built because FaceMaker found a common surface in the edge pcurves.

e0 = face.Edge1
split = e0.split(0.25)

new_edges = split.Edges + edges[1:]
new_wire = Part.Wire(new_edges)
try:
    new_face = Part.Face(new_wire, "Part::FaceMakerSimple")
    Part.show(new_face)
except Part.OCCError:
    print("Failed to make new face")

```

Furthermore, it also prevents the split edges to successfully replace the original edge in a shape : 
```
cyl = Part.makeCylinder(2, 5)
e1 = cyl.Edge1
split = e1.split([1.0, 2.0])
newcyl = cyl.replaceShape([(e1, split)])
fix = Part.ShapeFix.Shape(newcyl)
fix.perform()
new_cyl = fix.shape()
try:
    new_cyl.check()
    Part.show(new_cyl)
except Exception as exc:
    print(exc)

```

I still need to write a unit test for this fix, but I don't know in which file I should do it.
Maybe BRep_tests.py ?

### CODE REVIEW

**Comment by wwmayer** [comment]
> Maybe BRep_tests.py ?

For future PR that would be good. I will prepare a new PR now with your test code.

**Comment by tomate44** [comment]
I was proposing to do it. You have been kind enough to clean up behind my PRs several times already.

**Comment by wwmayer** [comment]
Oh wait! The integration tests of the CI fail with this error now:
```
======================================================================
ERROR: test_get_extended_wire (drafttests.test_draftgeomutils.TestDraftGeomUtils)
Test the DraftGeomUtils.get_extended_wire function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Mod/Draft/drafttests/test_draftgeomutils.py", line 123, in test_get_extended_wire
    extended = DraftGeomUtils.get_extended_wire(wire, offset_start, offset_end)
  File "/usr/local/Mod/Draft/draftgeoutils/wires.py", line 464, in get_extended_wire
    wire = Part.Wire(out_edges)
Part.OCCError: BRep_API: command not done
```

**Comment by tomate44** [comment]
Oh. Sorry for the burden.
I'll look at this.

**Comment by wwmayer** [comment]
Hmm, the test code in test_get_extended_wire and the function get_extended_wire is a mess. I think it's best to first clean up the test code and remove the code duplications.

**Comment by tomate44** [comment]
I had deleted my previous comment.
Tests are still failing.
Thanks for the tip about git.
I still need to work on this.
Sorry for the wasted time.

**Comment by wwmayer** [comment]
Here is a reduced example:
```
import DraftGeomUtils
from DraftGeomUtils import geomType, precision

points = [FreeCAD.Vector(0.0, 0.0, 0.0),
          FreeCAD.Vector(1500.0, 2000.0, 0.0),
          FreeCAD.Vector(4500.0, 2000.0, 0.0),
          FreeCAD.Vector(4500.0, 2000.0, 2500.0)]

edges = []
for start, end in zip(points[:-1], points[1:]):
    edge = Part.makeLine(end, start)
    edge.Orientation = "Reversed"
    edges.append(edge)


wire = Part.Wire(edges)

offset_start = 2000
offset_end = 1000

first_edge = wire.OrderedEdges[0]
start, end = first_edge.LastParameter, first_edge.FirstParameter
vec = -first_edge.tangentAt(start).multiply(offset_start)

new_edge = Part.LineSegment(first_edge.valueAt(start).sub(vec), first_edge.valueAt(end)).toShape()
wire1 = Part.Wire([new_edge] + wire.OrderedEdges[1:])

out_edges = []
order = wire1.OrderedEdges

new_edge = order[2].split(order[2].getParameterByLength(offset_end)).OrderedEdges[1]
new_edge.Placement = order[2].Placement
new_edge.Orientation = order[2].Orientation
out_edges.insert(0, new_edge)
out_edges.insert(0, order[1])
out_edges.insert(0, order[0])

wire2 = Part.Wire(out_edges)
Part.show(wire2)
```

The actual problem is caused by this line:
`new_edge = order[2].split(order[2].getParameterByLength(offset_end)).OrderedEdges[1]`
because it returns the wrong part of the wire. And because the three edges are not connected the creation of the wire fails.

**Comment by tomate44** [comment]
Thanks for your involvement.
So, the part that adds the pcurves is OK.
However, even if the Draft function gets a fix, my changes the the orientation of the split wire may also break 3d party workbenches and macros that use Edge.split().
I made several tests with the orientation of the split wire, and the split edges order or orientation, but none of them did produce a valid replaceShape out-of-the-box (it always needed a ShapeFix anyway)
Wouldn't it be more secure to leave the split wire's orientation unchanged, and let the users of replaceShape take care of the orientation of the replacing wire ?

**Comment by wwmayer** [comment]
> However, even if the Draft function gets a fix, my changes to the orientation of the split wire may also break 3d party workbenches and macros that use Edge.split().

Yes, this could happen.

> Wouldn't it be more secure to leave the split wire's orientation unchanged, and let the users of replaceShape take care of the orientation of the replacing wire ?

That's probably the best of all options.

**Comment by tomate44** [comment]
OK. Thanks.
I'll revert the orientation commit tomorrow, and add a unit test.

**Comment by wwmayer** [comment]
These are the two additional test functions:
```

    def testEdgeSplitFace(self):
        coords2d = [(0.5, -0.5), (1.0, -0.5), (1.0, 0.5), (0.5, 0.5)]
        pts2d = [Base.Vector2d(u, v) for u, v in coords2d]
        pts2d.append(pts2d[0])

        sphere = Part.Sphere()

        edges = []
        for i in range(1, len(pts2d)):
            ls = Part.Geom2d.Line2dSegment(pts2d[i - 1], pts2d[i])
            edges.append(ls.toShape(sphere))

        wire = Part.Wire(edges)
        face = Part.Face(wire, "Part::FaceMakerSimple")

        e0 = face.Edge1
        split = e0.split(0.25)

        new_edges = split.Edges + edges[1:]
        new_wire = Part.Wire(new_edges)

        new_face = Part.Face(new_wire, "Part::FaceMakerSimple")
        self.assertTrue(new_face.isValid())

    def testEdgeSplitReplace(self):
        cyl = Part.makeCylinder(2, 5)
        e1 = cyl.Edge1
        split = e1.split([1.0, 2.0])
        newcyl = cyl.replaceShape([(e1, split)])
        fix = Part.ShapeFix.Shape(newcyl)
        fix.perform()
        new_cyl = fix.shape()
        self.assertTrue(new_cyl.isValid())
```
You only have to adjust the code of testEdgeSplitReplace

**Comment by tomate44** [comment]
I have reverted the orientation change and added the unit test.
By the way, I read a couple of discussions on the OCC forum, and I now have a better understanding of the replaceShape algo.
When replacing an edge inside a shape, it is also necessary to replace the connecting vertexes.
Then, no ShapeFix is needed anymore, and the shape is valid out-of-the-box. (see second unit test)

**Comment by wwmayer** [comment]
Thanks! Everything works as expected now.

**Pull request merged**
