### PR TITLE
Exception improvements 4

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
@wwmayer 
@DeepSOIC 

For your consideration.

### CODE REVIEW

**Comment by wwmayer** [comment]
Merged.

**Comment by DeepSOIC** [comment]
I just tried using THROWM macro on all exceptins in Container.cpp. I get compile errors.

Code:

```
bool Container::canAccept(DocumentObject* obj, bool b_throw) const
{
    try {
        if (!obj){
            THROWM(Base::ValueError, "Null object!");
        }
        if (isNull()){
            THROWM(NullContainerError, "Null container can't take any objects");
        }
    ....
}
```

Error message:

> T:\_vt\dev\PC\Qt\FreeCAD\FreeCAD-ellipse\src\App\Containers\Container.cpp:106: error: C2065: '__PRETTY_FUNCTION__' : undeclared identifier

**Comment by abdullahtahiriyo** [comment]
@DeepSOIC 
@wwmayer 

I thought __PRETTY_FUNCTION__ was supported by VC.

Would you try for me substituting in the macro __PRETTY_FUNCTION__ with:
__FUNCDNAME__
__FUNCTION__
__func__

The first I think is VC++ 7.x+ specific
The second should be working with VC, but undecorated.
Somewhere I read that they have to be activated in the settings of VC.

The third should work with any C99 compiler and is part of c++11 standard.

If several work. Do you have any preference for the amount of decoration?

It should be possible to provide different macros with conditional compilation.
```
#ifdef _MSC_VER
#define THROW(exception) {exception myexcp; myexcp.setDebugInformation(__FILE__,__LINE__,__FUNCTION__); throw myexcp;}
#define THROWM(exception, message) {exception myexcp(message); myexcp.setDebugInformation(__FILE__,__LINE__,__FUNCTION__); throw myexcp;}

#define THROWMF_FILEEXCEPTION(message,filenameorfileinfo) {FileException myexcp(message, filenameorfileinfo); myexcp.setDebugInformation(__FILE__,__LINE__,__FUNCTION__); throw myexcp;}
#elif defined(__GNUC__)
#define THROW(exception) {exception myexcp; myexcp.setDebugInformation(__FILE__,__LINE__,__PRETTY_FUNCTION__); throw myexcp;}
#define THROWM(exception, message) {exception myexcp(message); myexcp.setDebugInformation(__FILE__,__LINE__,__PRETTY_FUNCTION__); throw myexcp;}

#define THROWMF_FILEEXCEPTION(message,filenameorfileinfo) {FileException myexcp(message, filenameorfileinfo); myexcp.setDebugInformation(__FILE__,__LINE__,__PRETTY_FUNCTION__); throw myexcp;}
#else
#define THROW(exception) {exception myexcp; myexcp.setDebugInformation(__FILE__,__LINE__,__func__); throw myexcp;}
#define THROWM(exception, message) {exception myexcp(message); myexcp.setDebugInformation(__FILE__,__LINE__,__func__); throw myexcp;}

#define THROWMF_FILEEXCEPTION(message,filenameorfileinfo) {FileException myexcp(message, filenameorfileinfo); myexcp.setDebugInformation(__FILE__,__LINE__,__func__); throw myexcp;}
#endif
```

I can not test VC++. Sorry for that!

**Comment by DeepSOIC** [comment]
Tested by adding console prints to constructor App::Application::Application()
```
__FUNCDNAME__: ??0Application@App@@AEAA@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@@Z
__FUNCTION__: App::Application::Application
__func__: not defined
```

**Comment by abdullahtahiriyo** [comment]
I thought __FUNCDNAME__ would be prettier...

@DeepSOIC 

Could you try __FUNCSIG__?

This I found it in a non-official documentation site...

**Pull request closed without merging**
