### PR TITLE
[App] PropertyPythonObject Python 3.11 fix

### PR DESCRIPTION
**Pull request by Syres916**
Fixes https://github.com/FreeCAD/FreeCAD/issues/10460

Tested on both Debian 12 (Python 3.11.2) and Linux Mint (Python 3.8.10)

### CODE REVIEW

**Comment by Syres916** [comment]
@wwmayer In my testing on Py3.11 versus Py3.8, on Py3.11 the `__getstate__` condition was being tripped but on Py3.8 with exactly the same data neither `__getstate__` nor `__dict__` were found. If you feel that in itself needs further investigation then let me know but the `Py::Callable method(pickle.getAttr(std::string("dumps")));` is proving difficult for me to evaluate, getting out of comfort zone.

**Comment by wwmayer** [comment]
> Tested on both Debian 12 (Python 3.11.2)

I have a Debian 12 running too and when I ran the self-tests the last time all of them has succeeded. But I am not sure whether there is a specific unit test to check the `__getstate__/__setstate__` stuff. If not then one must be written.

I am very skeptical that with Py3.11 passing the object directly works reliably because there exists data types (like Coin3D nodes) that cannot be made persistent (at least with < Py3.11) and that's one of the reason of having `__getstate__/__setstate__`

So, here some more tests are required to see what works and what not.

**Comment by Syres916** [comment]
I found this quote `Changed in version 3.11: Added the default implementation of the __getstate__() method in the [object](https://docs.python.org/3/library/functions.html#object) class.` taken from https://docs.python.org/3/library/pickle.html#pickle-inst

**Comment by wwmayer** [comment]
Our first version to serialize Python objects was indeed based on pickle, hence the method names `__getstate__/__setstate__.` Because it's considered unsafe (you can execute arbitrary Python code when restoring an object) we switched to json but we left these two function names untouched.

**Comment by wwmayer** [comment]
The problem is that since Py3.11 the very base class `object` now has the method `__getstate__` and that's why PropertyPythonObject uses this method when it shouldn't. I think the best what we can do is to rename our `__getstate__/__setstate__` to `__get_state__/__set_state__`

**Comment by wwmayer** [comment]
This PR fixes the issue: https://github.com/FreeCAD/FreeCAD/pull/10769

**Pull request closed without merging**
