### PR TITLE
[Sketcher] Allow driving constraint on construction geometry

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Fixes issue #7442.

There appears to be no reason to not allow construction points to be constrained. I may be wrong here though.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443">pipeline status</a> for feature branch [PR_7443](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443). Pipeline [630718837](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/630718837) was triggered at [c3f1e9a](https://github.com/FreeCAD/FreeCAD/pull/7443/commits/c3f1e9ac81544b0205801f0cece6917c2f702d70). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443">pipeline status</a> for feature branch [PR_7443](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443). Pipeline [630789192](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/630789192) was triggered at [ed8e5e6](https://github.com/FreeCAD/FreeCAD/pull/7443/commits/ed8e5e6e949e108d966fceb524bfaccbc2742b8d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Review by 0penBrain — CHANGES_REQUESTED** [review]
Not an optimal solution IMO.
The remaining checks are basically already made in `testDrivingChange`, that is already called by `setDriving`, that roughly made same implementation as `toggleDriving`.
As said in the forum thread, the best solution to me is that `toggleDriving` just wraps to `setDriving`.

**Comment by AjinkyaDahale** [comment]
> Not an optimal solution IMO. The remaining checks are basically already made in `testDrivingChange`, that is already called by `setDriving`, that roughly made same implementation as `toggleDriving`. As said in the forum thread, the best solution to me is that `toggleDriving` just wraps to `setDriving`.

I propose we make this a separate commit within this same PR, so we can merge whatever combination is needed.

**Comment by 0penBrain** [comment]
@AjinkyaDahale let's discuss in only one place. ;) I'd say the forum. My changes proposal would totally erase the current one, so adding another commit seems weird to me.

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale let's discuss in only one place. ;) I'd say the forum. My changes proposal would totally erase the current one, so adding another commit seems weird to me.

OK. I've just fixed up the suggested split commits. Let's discuss in forum once I can confirm they compile.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443">pipeline status</a> for feature branch [PR_7443](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443). Pipeline [631691465](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/631691465) was triggered at [9dfe099](https://github.com/FreeCAD/FreeCAD/pull/7443/commits/9dfe0990c953ff6965121e3e79b96290885d0d3d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by chennes** [comment]
Is the discussion on this one resolved? (That is, is it ready for review?)

**Comment by AjinkyaDahale** [comment]
> Is the discussion on this one resolved? (That is, is it ready for review?)

The discussion had ended at https://forum.freecadweb.org/viewtopic.php?f=19&t=71614&start=10#p623922

> I'm still gonna leave this as such till final review if you don't mind.

However, I said that under the impression that only Abdullah used to approve and merge sketcher changes. If @0penBrain is able to make the final approval there's nothing stopping us from merging.

**Comment by 0penBrain** [comment]
> If @0penBrain is able to make the final approval there's nothing stopping us from merging.

I did already with GH "Approve changes". :)
As I said int he forum, I'd just like that commits 1/3/4 be squashed before merging. ;)

**Comment by AjinkyaDahale** [comment]
> As I said int he forum, I'd just like that commits 1/3/4 be squashed before merging. ;)

Sorry for the misunderstanding. Squashed now. The typo fix was separately done in #7485.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443">pipeline status</a> for feature branch [PR_7443](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443). Pipeline [639993676](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/639993676) was triggered at [01bad11](https://github.com/FreeCAD/FreeCAD/pull/7443/commits/01bad11fcf6c1d6bc109d73735f22c53b6332d21). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443">pipeline status</a> for feature branch [PR_7443](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7443). Pipeline [649794312](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/649794312) was triggered at [4bcd900](https://github.com/FreeCAD/FreeCAD/pull/7443/commits/4bcd9001d1ddcfdd2610a729eb6153c3d8c01468). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
