### PR TITLE
TechDraw: Update templates to new FreeCAD icon.

### PR DESCRIPTION
**Pull request by maxwxyz**
Based on new icon https://github.com/FreeCAD/FreeCAD/pull/14284 the icons were replaced in the TechDraw page templates.
@WandererFan FYI

### CODE REVIEW

**Comment by WandererFan** [comment]
Do we have an official black and white or grey scale version of the logo?  It looks a bit "blobish" with all the fills set to black.

**Comment by maxwxyz** [comment]
@WandererFan yes this is using the official version from https://github.com/FreeCAD/FPA/pull/192 
We can also use the color version but I though a neutral one would fit better. I could also decrease the size if it is too prominent?

**Comment by Roy-043** [comment]
I think this PR has broken the editable texts in the templates. I have tested with A3_Landscape_TD.svg.
OK:
FreeCAD_0.22_37543\data\Mod\TechDraw\Templates\A3_Landscape_TD.svg
Bad:
FreeCAD_0.22_37573\data\Mod\TechDraw\Templates\A3_Landscape_TD.svg

**Comment by maxwxyz** [comment]
Just the logo was replaced, no other item was touched.

**Comment by Roy-043** [comment]
In 18 templates `freecad:editable` has become `index:editable`. I think that is not correct.

**Comment by maxwxyz** [comment]
ok that is weird that Inkscape overwrites other elements. Will have a look

**Comment by maxwxyz** [comment]
So on some of them when opening them in a text editor it is correct but opening them in Inkscape changes freecad to index which is weird, maybe because all these file have no namespace freecad included. I've updated them in this PR, also added the autofill tags: https://github.com/FreeCAD/FreeCAD/pull/14871

**Pull request merged**
