### PR TITLE
[PD] Fix button behavior in Pad up-to-face

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
The previous behavior was somewhat erratic when trying to change the end face.

File used for testing attached (needs to be extracted first).
[base-model.zip](https://github.com/FreeCAD/FreeCAD/files/9118068/base-model.zip)

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7191">pipeline status</a> for feature branch [PR_7191](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7191). Pipeline [588572947](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/588572947) was triggered at [3b2a85e](https://github.com/FreeCAD/FreeCAD/pull/7191/commits/3b2a85e8f309f8c500915bb802b69a71a9ad7a25). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Is there a forum thread? If not, can you please describe what the problem is/was?

Should this be backported for FC 0.20.1?

**Comment by AjinkyaDahale** [comment]
> Is there a forum thread? If not, can you please describe what the problem is/was?

No forum thread yet, but I can create one if needed. Steps to reproduce:
1. When in Pad/Pocket task, set to up-to-face.
2. Try pressing the "Face" button to change the face.
Expected: The button toggles to "pressed" state and when a face is selected, the textbox is updated and the button is "released". While the button stays pressed, the base feature is visible instead of the result feature, so that the correct face can be selected.
Observed: The button shows pressed, but only the result feature is shown. Clicking any face does not update anything in the text box.
 
> Should this be backported for FC 0.20.1?

It appears to be safe to backport.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7191">pipeline status</a> for feature branch [PR_7191](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7191). Pipeline [589674053](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589674053) was triggered at [7af7249](https://github.com/FreeCAD/FreeCAD/pull/7191/commits/7af7249cb9ad699f5d1570709899729e549b9cf7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks for the description. i see now the problem. However, I think your solution is incomplete because of the UI logic:

- the user changes to "up to face" and the realizes he has to select a face. however the Ui does not show him how. As new user I would click on the button to start the selection but this ends the selection.

Therefore I extended your PR, see #7201 and https://forum.freecadweb.org/viewtopic.php?f=3&t=70327

**Comment by donovaly** [comment]
Closing since the extended #7201 was merged.

**Pull request closed without merging**
