### PR TITLE
[Sketcher] Improve ToggleActiveConstraint icon (disambiguation)

### PR DESCRIPTION
**Pull request by 0penBrain**
- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

Just check compiling OK and render because no regression risk

Forum discussion : [Icons hard to distinguish](https://forum.freecadweb.org/viewtopic.php?f=34&t=42136)

### CODE REVIEW

**Comment by vocx-fc** [comment]
At least you should link to the conversation in the forum where this is discussed: [Icons hard to distinguish](https://forum.freecadweb.org/viewtopic.php?f=34&t=42136).

Please notice that I don't like your current icon, but I still think it's a good idea, so I think a better icon can be designed.

**Comment by 0penBrain** [comment]
> At least you should link to the conversation in the forum where this is discussed: [Icons hard to distinguish](https://forum.freecadweb.org/viewtopic.php?f=34&t=42136).
Good point. I forgot. Added to the PR description.
> Please notice that I don't like your current icon, but I still think it's a good idea, so I think a better icon can be designed.
Actually I don't care your lone personal opinion, but I like to have it as part of the FC community. ;) Though did you read the [forum thread](https://forum.freecadweb.org/viewtopic.php?f=34&t=42136#p357573) ?

**Comment by vocx-fc** [comment]
I like the new icon.

**Comment by vocx-fc** [comment]
By the way, @0penBrain for this particular pull request, once you added the second commit, you should have squashed the two commits into one (see Squashing in [Source_code_management](https://www.freecadweb.org/wiki/Source_code_management#Squashing_commits)).

Because right now it seems you made two commits, but in reality there was only one change: the first one was completely overwritten by the second one, so the first one was unnecessary. This isn't a huge problem but it is better to squash commits when possible to avoid polluting the commit history with "partial" commits. A smaller commit history is also good for the size of the Git database.

**Pull request merged**
