### PR TITLE
[TD]Fix transparent area in pdf (fix #18443)

### LINKED ISSUE #18443: Techdraw: Balloon Bubble Shapes are filled when exported to PDF
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When exporting a Techdraw Page via File -> Export -> PDF, the Balloon Bubble Shapes are filled instead of outlines.
Bug Balloon shape filled when exported to PDF
Exporting to svg or dxf via the buttons in the Techdraw workbench works fine.

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.60n
  * Curves 0.6.12
  * Defeaturing 1.2.0
  * fasteners 0.5.14
  * freecad.gears 1.0.0
  * lattice2 1.0.0
  * LCInterlocking
```

### Subproject(s) affected?

TechDraw

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for #18443.  It also restores the use of PDF/A-1b format for pdf in TechDraw which was removed due to issues in Qt which now appear to be fixed,

### CODE REVIEW

**Comment by adrianinsaval** [comment]
backported 149b64e8ef040c68bc527e44847be327d178cfd9

**Comment by gazzatav** [comment]
Something like this problem is happening again in 1.0.1.  See https://github.com/FreeCAD/FreeCAD/issues/18811 where I reported it before seeing it was a duplicate.  Now the balloons are shaded grey.  With default settings I had faces and holes filled grey too but switching off face detection and setting monochrome removed that.  Balloons still shaded though - see image on link.

**Comment by gazzatav** [comment]
@WandererFan I can't find any 'face color' setting in the TechDraw wb preferences or any.  I have Transparent faces checked:

image

Do you mean 'label text color' in Display? That looks grey. I shall try that anyway.

**Comment by WandererFan** [comment]
needs a label but it the one with the red box around it.
'faceColour

**Comment by gazzatav** [comment]
@WandererFan, I set the colour white and unchecked transparent faces.  Did a test print but it made no difference. Labels are still shaded grey. As a contrast with the same settings on **FC 1.0.0** I see what I expect to see when printed to pdf.

image

And the same with **FC 1.0.1**

image

If I export to SVG from 1.0.1 I get the same shaded labels but at least I can clear the fill with inkscape and print to pdf. A bit long winded when there are over a hundred labels though!

**Comment by WandererFan** [comment]
@gazzatav:  Your config for colors looks ok in the Preferences page, but looking at the config file itself, the Colors section has some suspect values.   The relevant one is PageColor being light grey.  If I update your color preferences so PageColor is white,  I get the correct appearance.
BalloonFillInPdf_postadjust

I'll have to keep looking for why the preference page doesn't match the config file, but if you update PageColor and re-save the preferences, you should get white fill on the bubbles again.

**Comment by WandererFan** [comment]
op config:
    <FCParamGroup Name="Colors">
      <FCUInt Name="Hatch" Value="255"/>
      <FCUInt Name="Background" Value="556083711"/>
      <FCUInt Name="PreSelectColor" Value="4240710143"/>
      <FCUInt Name="HiddenColor" Value="255"/>
      <FCUInt Name="SelectColor" Value="1958221567"/>
      <FCUInt Name="NormalColor" Value="255"/>
      <FCUInt Name="CutSurfaceColor" Value="3470056191"/>
      <FCUInt Name="GeomHatch" Value="255"/>
      <FCUInt Name="FaceColor" Value="4294967295"/>  <<<< FFFFFFFF    white OK
      <FCBool Name="ClearFace" Value="0"/>
      <FCUInt Name="gridColor" Value="556083711"/>
      <FCUInt Name="PageColor" Value="4059297279"/>  <<<< F1F3F5FF    grey  ??
      <FCBool Name="LightOnDark" Value="0"/>         
      <FCBool Name="Monochrome" Value="1"/>          <<<< should be 0  ??
      <FCUInt Name="LightTextColor" Value="33686271"/>
      <FCUInt Name="TemplateUnderlineColor" Value="995875839"/>
    </FCParamGroup>

**Comment by gazzatav** [comment]
@WandererFan It might also be of interest that when I change the page colour and apply, the label colour updates immediately but I have to scroll the page (in TechDraw) to see the background change.

**Pull request merged**
