### PR TITLE
[For testing] Sketcher: optionally merge 'coincident' within 'point-on-object' constraint

### PR DESCRIPTION
**Pull request by 0penBrain**
The merge is activated with `User parameter:BaseApp/Preferences/Mod/Sketcher/General/MergePointOnObjectWithCoincident` boolean switch

The PR is essentially done to have a test between 2 flavors (merged or not) and decide what is to be kept.

The "feature" is only the last commit. 3 first commits are independent fixes and improvements.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7478">pipeline status</a> for feature branch [PR_7478](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7478). Pipeline [637873179](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/637873179) was triggered at [c674aaa](https://github.com/FreeCAD/FreeCAD/pull/7478/commits/c674aaa283a39d179ae5616665c66f5f8478ad28). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks.
However, can you please split the PR into at least two. The new feature should become its own PR so that one can test it better and once it is merged we can reference it in the release notes as reference.

To be precise, what are the issues fixed by the first commits?
What is the feature of the 4th commit?

**Comment by 0penBrain** [comment]
@donovaly This PR was intended mainly for testing. Was not clear, I clarified in title and set to draft.
I will comment the 3 first commits on a new PR with only these 3 ones. To be clear, I'll let this PR as is, then latter rebase if/when 3 first commits are merged into master so this one will only be the last commit.

The last commit allows (with parameter switch in the description) to merge Sketcher 'coincident constraint' into 'point-on-object' constraint. It means that 'coincident' is no more present in the default menu/toolbar, and you can apply a coincident constraint by selecting 2 or more vertices and clicking 'point-on-object'.

**Comment by luzpaz** [comment]
@0penBrain do you want an experimental snap build for testers to test this PR ?

**Comment by 0penBrain** [comment]
> @0penBrain do you want an experimental snap build for testers to test this PR ?

For myself I have a build. :) Maybe better ask in the forum discussion ;)

**Comment by luzpaz** [comment]
Sure! Link to forum discussion?

**Comment by 0penBrain** [comment]
> Sure! Link to forum discussion?

Arf. Silly me. Was sure it was on the description : https://forum.freecadweb.org/viewtopic.php?f=8&t=71793

**Comment by adrianinsaval** [comment]
I myself also had a build but would appreciate if there is a snap and more testers, hopefully some of the detractors can give it a chance too.

**Comment by luzpaz** [comment]
Snap build triggered at https://github.com/FreeCAD/FreeCAD-snap/pull/62 (x-posting to thread as well)

**Comment by abdullahtahiriyo** [comment]
@0penBrain 

Are you pursuing this? Do you want me to take a look?

**Comment by 0penBrain** [comment]
@abdullahtahiriyo This was for community testing and feedback. AFAIK there's no agreement from community to move forward to this. I plan nothing for this ATM. ;)

**Comment by abdullahtahiriyo** [comment]
OK. Thanks.

**Comment by adrianinsaval** [comment]
Now that coincidence can work by selecting circle edges I think this is no longer viable, that is a very useful functionality so it's not worth loosing it for this IMO (and I was a big supporter of this).

**Comment by abdullahtahiriyo** [comment]
If I understood it correctly, could then we perhaps close the PR?

**Comment by 0penBrain** [comment]
Yes I close. No need to let it queued. We can reopen another (clean) PR in the future if we have a need for this. ;)

**Pull request closed without merging**
