### PR TITLE
sketcher icon deconfusion:  new Constraint-Parallel icon and small icon

### PR DESCRIPTION
**Pull request by J-Dunn**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
This icon is already proposed in #2536.

The discussion thread is [Sketch icon deconfusion : // vs =](https://forum.freecadweb.org/viewtopic.php?f=34&t=39127).

**Comment by yorikvanhavre** [comment]
#2536 is merged already. Should we close this one?

**Comment by vocx-fc** [comment]
I think yes, it's fine to close this one.

**Comment by yorikvanhavre** [comment]
Ok closing it then! Please reopen if needed!

**Pull request closed without merging**
