### PR TITLE
[v0.20]Update Libpack to 12.4.3

### PR DESCRIPTION
**Pull request by sgrogan**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by sgrogan** [comment]
Forum thread https://forum.freecadweb.org/viewtopic.php?f=10&t=54561#p468923

**Comment by yorikvanhavre** [comment]
The windows build failed with an error likely due to this new libpack (shiboken python module not found I think)

**Comment by sgrogan** [comment]
I'll look, thanks

**Comment by wwmayer** [comment]
It's rather unlikely that shiboken is the culprit. Due to its hook scripts to handle importing modules its name appears in error messages and thus may confuse users to think it's related to it.
The real error is: ImportError: DLL load failed while importing Fem: The specified module could not be found.

It's probably best to test the libpack locally and running it with the debugger of VS. This may tell you which DLL exactly causes the trouble.

**Comment by sgrogan** [comment]
I don't have the problem locally with a clean build.
I will try with a scratch build and make sure I copy the dependencies the same as on Travis.

Good tip though, in debug mode I get some FEM test errors that mention shiboken.

**Comment by wwmayer** [comment]
Since Py3.8 a pyd file does not any longer respect the PATH system environment variable to load DLLs it depends on. Instead os.add_dll_directory() must be used to add all needed DLL search paths.

What may happen here is that not all DLLs are copied over from the Libpack and thus the Fem.pyd file cannot be loaded. One way to fix this is by setting the environment variable FREECAD_LIBPACK_BIN that points to the bin directory of the LibPack.
The other way is to find out which DLL isn't copied over.

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/4363 is a test to check if setting the environment variable FREECAD_LIBPACK_BIN fixes the problem.

**Comment by wwmayer** [comment]
This is the log of my tested PR https://travis-ci.org/github/FreeCAD/FreeCAD/jobs/757531103 and it even fails to load three modules.
Yesterday I downloaded this LibPack and built FreeCAD locally. Everything  was working fine after defining the env. variable FREECAD_LIBPACK_BIN.

**Comment by wwmayer** [comment]
Not sure how to fix this one. So, I will postpone it for v0.20

**Comment by sgrogan** [comment]
OK
It works for me locally without setting the env variable. I will post a test build in the forum and see if my build is somehow not portable.

**Comment by wwmayer** [comment]
> It works for me locally without setting the env variable.

I looked at the script and it moves the content of the LibPack's bin folder to the build folder. That's why it works w/o the env. variable.

**Comment by wwmayer** [comment]
With fcf5a13eab7 LP 12.5 is used which now makes this PR obsolete.

**Pull request closed without merging**
