### PR TITLE
FEM Pipe beam section fix

### LINKED ISSUE #12320: [Problem] Pipe beam section cannot be used in FEM due to wrong element type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

[Beam section](https://wiki.freecad.org/FEM_ElementGeometry1D) of the type Pipe is currently unusable because the following error appears:

```
 *ERROR reading *BEAM SECTION:
        *BEAM SECTION of type PIPE can
        only be used for B32R elements.
        Element            1  is not a B32R element.
```

A workaround is to manually change the element type when editing the input file (just add R to B32). 

On this occasion, the Reduced Integration option (B31 --> B31R and B32 --> B32R) could be added for beam elements since it's crucial when plasticity is involved: https://forum.freecad.org/viewtopic.php?t=61233

Also, once there's a fix for that, the obsolete `*BEAM GENERAL SECTION` keyword used by FreeCAD FEM should be replaced with `*BEAM SECTION`:

```
 *WARNING in calinput
          *BEAM GENERAL SECTION is obsolete
          please use *BEAM SECTION
```

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35691 (Git)
Build type: Release
Branch: main
Hash: cc45b58dadae53d7a99be1ed7db25f6c93bb13d5
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FEA-eng**
An attempt to fix #12320

I set it as Draft because it doesn't work yet but I'm pretty sure that it's very close to a working solution. It should be just a matter of correcting this line (occurring twice because one is for split input writing):

```
if ccxwriter.member.geos_beamsection.SectionType == "Pipe":
...
```

there's still an error when trying to use it in modified AppImage:

`'list' object has no attribute 'SectionType'`

See forum discussion: https://forum.freecad.org/viewtopic.php?t=85277

@chennes Could you take a look at this ? It's probably just a small dumb mistake since I'm really inexperienced when it comes to coding and FreeCAD source code. But fixing this issue would be an important step.

### CODE REVIEW

**Comment by chennes** [comment]
I'm guessing based on context, but the creation of `geos_beamsection` looks like this:
```
        self.geos_beamsection = self.get_several_member(
            "Fem::ElementGeometry1D"
        )
```
The error you are getting, and the use of `get_several_member`, seems to indicate that geos_beamsection  is not a single thing, but a list of `ElementGeometry1D` objects. So it's probably not the member you are looking for.

**Comment by FEA-eng** [comment]
@chennes Thanks for the reply. I just got this almost working. I changed the line in the write_mesh.py file to:

```
if ccxwriter.member.geos_beamsection:
            beamsec_obj = ccxwriter.member.geos_beamsection[0]["Object"]
            if beamsec_obj.SectionType == "Pipe":
            ...
```

Now it works as it should except for the fact that it works only when the first beam section definition is Pipe. It should do its thing whenever any of the beam sections (multiple can be defined in a single analysis) are Pipe (so if the second one is Pipe and/or the third one and so on). Any ideas on what to put instead of [0] to achieve this? I've tried a for loop like this:

```
if ccxwriter.member.geos_beamsection:
          for i in ccxwriter.member.geos_beamsection:
            	beamsec_obj = ccxwriter.member.geos_beamsection[i]
            	if beamsec_obj.SectionType == "Pipe":
                ...
```

But I still get some errors related to syntax and maybe it's not the right way to go.

**Comment by chennes** [comment]
In Python that's now quite how you'd write that: probably the best way is to use a "list comprehension" like this (in place of your entire chunk of code):
```
if [True for s in ccxwriter.member.geos_beamsection if s.SectionType == "Pipe"]:
    # Do whatever you want to do if any beamsection is a pipe...
```
There are a couple of other Pythonic approaches, but I think this one will get the job done for you.

**Comment by FEA-eng** [comment]
> if [True for s in ccxwriter.member.geos_beamsection if s.SectionType == "Pipe"]:
>     # Do whatever you want to do if any beamsection is a pipe...

Thanks, I've tried that but it still shows an error:

`AttributeError: 'dict' object has no attribute 'SectionType'`

In my almost working code:

```
if ccxwriter.member.geos_beamsection:
            beamsec_obj = ccxwriter.member.geos_beamsection[0]["Object"]
            if beamsec_obj.SectionType == "Pipe":
```

[0] is the first object (first beam section). If I use [1] instead, the code works when the second section is Pipe. So I guess that the loop should change the number in the bracket. So I've tried this:

```
if [True for s in ccxwriter.member.geos_beamsection[s]["Object"] if ccxwriter.member.geos_beamsection[s]["Object"].SectionType == "Pipe"]:
...
```

but it fails with: `NameError: name 's' is not defined`

**Comment by FEA-eng** [comment]
I'll try to add an option to change the beam element type to reduced integration (B31 --> B31R, B32 --> B32R). This seems to be a better solution for 2 reasons:
- changing this can be useful not only because of the requirement for Pipe elements but also [to get accurate results in some cases](https://forum.freecad.org/viewtopic.php?t=61233) - maybe R elements should even be the default ones
- this way there will be no need to loop through all the beam sections and check if they are Pipe so the issue with the element name being overwritten multiple times will be gone

**Pull request closed without merging**
