### PR TITLE
[Draft] Fix Draft Edit AddPoint with BSpline

### PR DESCRIPTION
**Pull request by carlopav**
ref. https://forum.freecadweb.org/viewtopic.php?p=613622#p613622

Fix Bug when adding point to a BSpline.

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7295">pipeline status</a> for feature branch [PR_7295](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7295). Pipeline [602166096](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/602166096) was triggered at [8510729](https://github.com/FreeCAD/FreeCAD/pull/7295/commits/8510729b025d28c7cd487139d113f3fce0036586). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7295">pipeline status</a> for feature branch [PR_7295](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7295). Pipeline [602167978](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/602167978) was triggered at [d37a1a2](https://github.com/FreeCAD/FreeCAD/pull/7295/commits/d37a1a2440d60d6379cf1182d5ce8a441774ce4d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
@yorikvanhavre , @carlopav wants to have this in for FC 0.20.1. Could you therefore please have a look this week if possible?

**Comment by yorikvanhavre** [comment]
Ok looks good!

**Comment by donovaly** [comment]
backported

**Pull request merged**
