### PR TITLE
Cmake adjust

### PR DESCRIPTION
**Pull request by midgetfc**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x ] Branch rebased on latest master `git pull --rebase upstream master`
- [x ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---
these changes should allow to use CMake's imported targets mechanism (introduced in 3.5)

### CODE REVIEW

**Comment by vocx-fc** [comment]
Forum thread: [Followup on "cleaning up CMakeLists.txt"](https://forum.freecadweb.org/viewtopic.php?f=10&t=45339)

**Comment by yorikvanhavre** [comment]
Ok with this change, although there is older stuff than Ubuntu out there, it's important to still support everything possible.
I just had a look at slackware, it uses cmake 3.5.1... I guess we can consider that as the oldest cmake version used out there ;)

**Comment by boehms** [comment]
Out of curiosity, what are the systems we are looking to support?

Looking at the build system I am wondering if removing support for python2 and Qt4 is another cleanup item to consider?

**Comment by vocx-fc** [comment]
I don't think we will be removing Python 2 and Qt4 support explicitly at this moment, but we will definitely stop testing our code against them. So the codebase will de facto be incompatible with Python 2 after the release of 0.19.

**Comment by boehms** [comment]
@vocx-fc So why not remove the support for them in the build system? If it is needed at some point in the future, it will be in git.
Removing it from the build system will make it much cleaner.

**Comment by vocx-fc** [comment]
I agree with you in general, and it's something people have been mentioning in the past; why does FreeCAD compile against Py2/Qt4 by default? Just inertia, I guess.

However, removing support, I don't feel like doing this at the moment because there may be some systems that can still be compiled with Python 2 and Qt4. A notable example that I can think of is the Raspberry Pi. In the forum there is a thread about compiling FreeCAD in Raspbian. It works with Py2/Qt4, and I think the weird combination Py3/Q4, but it doesn't work with the normal combination Py3/Qt5. It's possible there are other systems in that same situation. So, for these systems it's still nice that Py2/Qt4 works, although maybe not perfectly.

I would favor removing Py2/Qt4 completely only after the next version, say, 0.20. By then I imagine most Linux distributions will have completely migrated to Python 3, and I hope in that time Raspbian has also fixed its issues with Qt5.

**Comment by sgrogan** [comment]
I agree with @vocx-fc. **I think** 0.19 will have PY2/QT4 support where possible. In 0.20_pre it will be deprecated and unsupported. A decision will need to be made when to start removing it.

**Comment by yorikvanhavre** [comment]
I think indeed we can start deprecating Py2/Qt4 after 0.19 is out, I guess there will be virtually no more platform that don't support Py3 or Qt5. But I would leave starting to actually remove stuff for the next release, so we can detect if anyone screams or still wants to do the work to maintain compatibility for one more release... (ie we won't do it, but won't make it impossible yet for someone to do it)

**Pull request merged**
