### PR TITLE
Draft: disable the Toolbar mode of Gui commands

### PR DESCRIPTION
**Pull request by vocx-fc**
The `Toolbar` mode of Gui commands doesn't really work well with modern Draft tools, and it causes confusion with new users. Therefore, this mode is disabled.

See thread, [0.19pre win64 Draft Toolbar mode cannot display numeric input fully](https://forum.freecadweb.org/viewtopic.php?f=34&t=42782)

The `Taskview` mode (value 1) is set fixed in `DraftGui.py` even if the widget shows the other value `Toolbar` (value 0). At the same time, clarify the behavior with a new tooltip.

If this is merged after #2965, it may cause a conflict. In this case, this pull request may have to be rebased.

---

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by carlopav** [comment]
I didnt get if you removed the option from prefereces or just make it not effective. I think we should go for removing the option completely if we decide so.

**Comment by vocx-fc** [comment]
I just made it not effective, as it has a fixed value of `1` now. The preference is still there if your system already had it. But in a new system, I'm not sure if the preference will appear.

Also, to completely remove this, we would have to modify the `.ui` file further. We would have to remove any indication of the `Draft interface` and the combobox that allows you to select the different modes.

Moreover, to really remove the associated code, we would have to delete everything in `DraftGui.py` which uses the `Toolbar` mode, as there would be no way of accessing that code.

**Comment by carlopav** [comment]
well, we could also just remove the preference line in the UI, and leave the code, commenting it to make clear that. I tried to commit a proposal to you branch, but i don't know if it worked.

**Comment by vocx-fc** [comment]
I don't see any request from you. I believe you have to make a pull request against my branch.

**Comment by vocx-fc** [comment]
Carlo, I just realized that I have a pull request in my personal branch. I didn't notice it before. I think it's fine, but you have to make the pull request not against my `master` branch, but against the branch called `Draft_taskview`.

**Comment by vocx-fc** [comment]
Hey Carlo, it seems it works. I got your branch, cherry-picked your commit, and then pushed in my own branch.

**Comment by yorikvanhavre** [comment]
Agree with the above!

**Pull request merged**
