### PR TITLE
fem: fixes

### PR DESCRIPTION
**Pull request by looooo**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by looooo** [comment]
@berndhahnebach

**Comment by luzpaz** [comment]
@berndhahnebach ping

**Comment by berndhahnebach** [comment]
a9c19ca6d42c6bf31eac194c936c215b0dc382f3 and b4a310020967a31961a07c6a51e3a80e2a2b260d should fix the problem. @looooo  Would you give feedback if it fixes it for you too?

**Comment by looooo** [comment]
Thanks, I will test after next weekend when a new build is available.
reminder for my self: 
https://forum.freecadweb.org/viewtopic.php?f=18&t=40286&start=10#p343099

**Comment by looooo** [comment]
solved, thanks

**Pull request closed without merging**
