### PR TITLE
[read.me] clarify digitalocean sponsorship

### PR DESCRIPTION
**Pull request by sgrogan**
todo better 'This project receives support from:'

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by looooo** [comment]
We need to distinguish between content and the infrastructure. Content is done by the community (source, wiki, forum). Only some infrastructure is used from digital-ocean.

So something like:
`Services from digital-ocean are used to provide the freecad-forum and the freecad-wiki.`

**Comment by yorikvanhavre** [comment]
Much better! I would even make the logo smaller than 201px.. :grin:

**Comment by triplus** [comment]
Just wondering, what sort of support do we get from DigitalOcean?

**Comment by sgrogan** [comment]
@triplus see here: https://github.com/FreeCAD/FreeCAD/commit/8deed98acec8f31ec946c95d0aa0c2767223baa3

How about?
"DigitalOcean generously provides support for FreeCAD's Web infrastructure"
I'll also shrink the logo to be more in line with the other badges

**Comment by looooo** [comment]
Still I don't like an advertisement in the source. If we let the digital ocean advertisement in the source, I want to have also the company I am working with to be placed here, as the sponsored my contributions and so on. You can imagine where we would end up. Looking like these football/F1 slaves with all their commercial masters all over their clothes...

The source is too much worth to let such advertisement happen. Please find another way to get the donations for the web services. For me, this is really an issue! Don't mess the source by commercializing our vision!

**Comment by sgrogan** [comment]
I understand your concern. 
I checked Python https://github.com/python/cpython
that is also sponsored by DigitalOcean. I don't know the nature of the sponsorship.
Python doesn't have a badge in the source repo, I found it here: https://www.python.org/psf/sponsorship/sponsors/ "Bronze Level Sponsors"
They do have some commercial badges in the read.me Azure for example. We have Travis-CI

I don't know how to proceed. Should I tweak the pull request to better explain the nature of the sponsorship? Or close it and make a ticket on Mantis and further discuss on the forum?

**Comment by looooo** [comment]
I would prefer a seperate site where such logos can be shared (like python does). @kkremitzki @yorikvanhavre is this possible?

**Comment by looooo** [comment]
> I don't know how to proceed. Should I tweak the pull request to better explain the nature of the sponsorship? Or close it and make a ticket on Mantis and further discuss on the forum?

Imo they should have made this privious of merging the commit. For sure it's nice to have such sponsorship, but it is not related to the source at all.

**Comment by yorikvanhavre** [comment]
Yeah I also find having their logo in the source annoying. On our website is okay, but this is invasive. Maybe we could just add them to the credits page (both on the wiki and why not, in the about dialog)? After all, it would still be in the source code.

**Comment by triplus** [comment]
@sgrogan 

Thanks for the explanation. 

P.S. I am rather indifferent. I guess it makes sense to mention all the service we use somewhere, especially if there is some level of "sponsorship" involved. For example a while back i took a look at the Travis CI prices and they are substantial. Likely the same for GitHub but i haven't investigate that yet. I guess an additional page on the FreeCAD home page would do. If we ever do it i would mention things like MediaWiki, phpBB, MantisBT too. As they have been providing a vital infrastructure for our needs.

**Comment by sgrogan** [comment]
https://opensource.nyc3.cdn.digitaloceanspaces.com/attribution/index.html
IINAL but we're asked not compelled.

Maybe the Homepage is more appropriate? I think we're all appreciative of the support, the question is how to acknowledge it.

I agree with @yorikvanhavre it should be included in the about dialog, perhaps in a sponsor catagory?

**Comment by triplus** [comment]
Other FOSS projects usually have a central page and all sponsors are listed on it. Usually that is done on the home page.

**Comment by kkremitzki** [comment]
I wanted to wait some time before responding to this issue because my initial reaction was to be incredibly annoyed, but I need to chime in at some point so here goes.

I've talked before about the problems with the existing infrastructure and how things are unsustainable as they are, so I won't repeat the details for that point here.

While your point is completely valid looooo it's at the same time rather unhelpful. There is no F1 car, it's a rusted Trabant sitting in a field and since the wheels haven't fallen off yet I'm trying to put in a working engine yet getting drawn into an argument about the aesthetics of a sticker.

Yorik, I don't see how putting an actual image in the source compared to hyperlink text in the readme is any improvement in integrity.

sgrogan, with your use of "I am not a lawyer", and "asked and not compelled", I'd say if we are thinking of the legalistic side of the agreement versus the spirit of it, then things are already off the rails.

Ultimately keeping the infrastructure the way it is now cannot continue. It's like I've inherited a house that's about to fall down but the Code of Hammurabi is still in effect. By that I mean that as things are now, complete infrastructure pwnage is not a matter of if, but a matter of when, or really, how long ago, and my name would probably come up if something were to happen.

So it doesn't need to forever be the current solution. But given that there's a totally reasonable project desire to host infrastructure in Germany there's only so much I can do. For example there's the [Oregon State University Open Source Lab](https://osuosl.org/) which could provide what we need, but we need a German or European counterpart to that, and I don't think I should be the driver for that, and nobody has stepped up yet to help either, so hopefully someone who is a native German speaker could help with that.

We could also say thanks, no thanks, and set aside the amount they're providing us for infrastructure and pay it ourselves from existing funds without needing to advertise their support, but again I don't have such a shortage of things to do as to want to try to drive that discussion.

I just wish some of this energy was available to work on the infrastructure problems I mentioned so I could actually work on FreeCAD instead.

**Comment by looooo** [comment]
I understand your annoyance with this issue @kkremitzki. But the problem is that a lot of people contributed to freecad. And now this work is "powered by digital ocean" which simple feels totally wrong. At least I and the things I contributed were never "powered by digital ocean".

I would vote for keeping the logo in (but moving it away from the github front-page and maybe add some more information to make this more transparent, what this PR is about) as long as we have not found another solution. We need to actively look for an alternative place to put such "sponsor stickers". I guess it's not a big deal for "digital ocean" to have these stickers placed on the website (similar to the python example). If there is really no other solution, we need to think about another way to donate the 250$/year for the infrastructure.

**Comment by triplus** [comment]
For the next 3 days i have like 0 free time. As for quick response. From the point of view, where people step up and are then are more or less left alone i agree that this PR should be sufficient and lets merge it.

As for the future. There is a thread on FreeCAD forum, dedicated to FreeCAD home page. People have steped up in the pest and helped, when asked. If nobody else beats me to it i will ask for help there in around 4 days time. If and once we have a dedicated page on home page, that will likely be a better place for such sponsorship mentions. Until then indeed this will have to do.

**Comment by sgrogan** [comment]
First I'd like to thank @kkremitzki for investing the effort to secure the sponsorship.
FreeCAD needs this kind of support!
I apologize for the IANAL reference. My intention was not to de-rail the discussion. I think we are all trying to find some common ground. I am truly appreciative of the sponsorships the project receives. I opened the pull request with a hope of consensus. We're not there yet, but that's OK.

I am happy to refine the pull request to remove "powered by" and reduce the icon to be in line with the others. See the Travis icon.

In my opinion crediting sponsors in the credits is different than the read.me I don't have a strong opinion on this though.

I support @triplus in that a prominent place on the Homepage is a good compromise, supported by the Python example.

I emphasize that I appreciate @kkremitzki here, and as the "stepped up" person you should voice your opinion.

**Comment by sgrogan** [comment]
I've updated the pull request. I suggest this is an acceptable compromise until we have a more universally accepted solution.
If this is unacceptable still, then we should probably close the pull request.

**Comment by looooo** [comment]
Thanks @sgrogan. This is a lot better. As said we still should look for an alternative way (keeping commercial stuff away from the source) but doing it in this  (transparent) way is the right direction.

**Comment by triplus** [comment]
Hi.

Quick note. In the past few days i was working on a project and i had 0 time for other things. The project will be done till Monday. Then i will have more time again to look into this and to start a discussion on the forum (regarding the home page).

**Comment by yorikvanhavre** [comment]
This seems to me a perfect and elegant solution, thanks @sgrogan 

I understand fully your point @kkremitzki , and they really solve a big problem for us, but it also seems to me that digitalocean's "drop-in codelet" was a bit invasive. They are not powering anything on github itself so it seems like a weird requirement to me. But I liked this solution here.

If nobody has anything against it, I'll merge

**Comment by triplus** [comment]
As discussed i asked for some help here:

https://forum.freecadweb.org/viewtopic.php?f=34&t=29615&p=400004#p400004

Basically, we currently use a lot of services, that offer FOSS projects some benefits. Hence if we would have a dedicated page somewhere on a FreeCAD home page, that would likely work good as a general solution.

P.S. Regarding this PR i am OK with whatever happens next.

**Pull request merged**
