### PR TITLE
Displaying internal names in the tree view

### PR DESCRIPTION
**Pull request by Kuzma30**
Rework of https://github.com/FreeCAD/FreeCAD/pull/14081 PR.

By default this option non active
"After" screenshots
Знімок екрана з 2024-05-23 13-44-59

Знімок екрана з 2024-05-23 13-45-42
Also add checkbox in Preferences menu
Знімок екрана з 2024-05-23 13-47-27

### CODE REVIEW

**Comment by NomAnor** [comment]
This could be useful if non-unique names are allowed, because I need to use the internal names in expressions.
I often forget that the internal names are shown in the status bar when you hover over a tree item.

**Comment by Kuzma30** [comment]
@yorikvanhavre please rewiev (its final version)

**Comment by Kuzma30** [comment]
@yorikvanhavre I hope you haven't forgotten about this commit :)

**Comment by yorikvanhavre** [comment]
Sorry I hadn't time to test yet :/ Will do ASAP

**Comment by yorikvanhavre** [comment]
Ok I just gave it a test and it works nicely! Well done!

There is still an issue that the header does not stretch out to the right side of the tree view, but that problem is there also for the "Description" column. Something to fix later on (IIRC in QDesigner there is some sort of "stretch last column" option that probably needs to be used here).

**Review by yorikvanhavre — APPROVED** [review]

**Comment by Kuzma30** [comment]
@yorikvanhavre I change description. For stretch last column problem I think better separate PR.

**Comment by yorikvanhavre** [comment]
Perfect, thanks!

**Comment by Kuzma30** [comment]
@yorikvanhavre can you merge or you have any other idea related to this PR?

**Comment by maxwxyz** [comment]
@Kuzma30 @yorikvanhavre 
can anyone confirm, on my fresh install this extra column is visible by default, which should not be the case.

**Comment by yorikvanhavre** [comment]
It's not visible by default for me (debian, fresh compilation, fresh config)

**Comment by maxwxyz** [comment]
@yorikvanhavre could you try if it becomes visible if you reset the preferences page with the reset button?
@Kuzma30 on my system it becomes visible by default when clicking on reset. It temporarily hides but clicking ok or apply on the preferences displays these columns again by default.
@kadet1090 FYI

**Comment by NomAnor** [comment]
This is probably the same problem as in #15244

**Comment by yorikvanhavre** [comment]
> @yorikvanhavre could you try if it becomes visible if you reset the preferences page with the reset button?

I tried that, still not visible...

**Comment by maxwxyz** [comment]
I still get wrong preference settings when resetting the thew Display>UI page. On latest Windows and macOS version and there was the same issue reported for the AppImage version: https://github.com/FreeCAD/FreeCAD/issues/15244

**Pull request merged**
