### PR TITLE
[TechDraw] Clean up precompile in Gui

### PR DESCRIPTION
**Pull request by benj5378**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313">pipeline status</a> for feature branch [PR_7313](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313). Pipeline [605286847](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/605286847) was triggered at [b6a2af9](https://github.com/FreeCAD/FreeCAD/pull/7313/commits/b6a2af962a70597409f2b80ae211af9ac8334572). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by WandererFan** [comment]
I could be wrong, but I don't think PreCompiled.h is supposed to appear in *.h files, only *.cpp.  If I look at Part/App or Part/Gui, none of the *.h files have it.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313">pipeline status</a> for feature branch [PR_7313](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313). Pipeline [605629230](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/605629230) was triggered at [8a7b2c8](https://github.com/FreeCAD/FreeCAD/pull/7313/commits/8a7b2c86a14a1c90ec3d101c5409652a68888e99). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313">pipeline status</a> for feature branch [PR_7313](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313). Pipeline [605632284](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/605632284) was triggered at [28b8d34](https://github.com/FreeCAD/FreeCAD/pull/7313/commits/28b8d34567109b3f5b33e0aebeae7b6e9bd31760). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313">pipeline status</a> for feature branch [PR_7313](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313). Pipeline [606007300](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/606007300) was triggered at [7fcafd6](https://github.com/FreeCAD/FreeCAD/pull/7313/commits/7fcafd6fc3cab7a4fb33a7380c36266cced96dad). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313">pipeline status</a> for feature branch [PR_7313](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313). Pipeline [606013582](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/606013582) was triggered at [bdd4b36](https://github.com/FreeCAD/FreeCAD/pull/7313/commits/bdd4b36e06b2684367f057cfac9ba1cb24aba54b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by benj5378** [comment]
This PR is assuming that I understood https://forum.freecadweb.org/viewtopic.php?f=10&t=70796 correctly.
> I could be wrong, but I don't think PreCompiled.h is supposed to appear in *.h files, only *.cpp. If I look at Part/App or Part/Gui, none of the *.h files have it.

@wwmayer, do you know anything about this? I'd be very happy if you were able to skim the PR.

I have tested that it compiles on Ubuntu with PCH turned off
@The-EG has tested, that it compiles on Windows in Visual Studio with PCH turned on
Do we need any additional compiler tests?

**Comment by wwmayer** [comment]
> do you know anything about this? I'd be very happy if you were able to skim the PR.

wandererfan brought up the relevant points. Adding anything about PCH into headers must be avoided. If use a type in a header you can check if a forward declaration is enough but if not then you must include the appropriate header there.

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313">pipeline status</a> for feature branch [PR_7313](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313). Pipeline [612824754](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/612824754) was triggered at [2ffe626](https://github.com/FreeCAD/FreeCAD/pull/7313/commits/2ffe6262a251cb073af65f1963d80b68683a4064). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313">pipeline status</a> for feature branch [PR_7313](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313). Pipeline [612901004](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/612901004) was triggered at [e3f670d](https://github.com/FreeCAD/FreeCAD/pull/7313/commits/e3f670d45d68dba88f1a71c41ed47f70068afe6e). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313">pipeline status</a> for feature branch [PR_7313](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7313). Pipeline [612913987](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/612913987) was triggered at [e450300](https://github.com/FreeCAD/FreeCAD/pull/7313/commits/e45030044aaad83ff0e927b6724f67df2b863632). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Pull request merged**
