### PR TITLE
Spreadsheet: fix range selection

### PR DESCRIPTION
**Pull request by realthunder**
Forum post https://forum.freecadweb.org/viewtopic.php?p=601316#p601316

@donovaly

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7009">pipeline status</a> for feature branch [PR_7009](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7009). Pipeline [561689643](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/561689643) was triggered at [78a397b](https://github.com/FreeCAD/FreeCAD/pull/7009/commits/78a397b36bd544f7c9a831d9113623aabfda1fda). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7009">pipeline status</a> for feature branch [PR_7009](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7009). Pipeline [561690113](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/561690113) was triggered at [c7ea294](https://github.com/FreeCAD/FreeCAD/pull/7009/commits/c7ea294e62b037eb67b54f1d2c6a9f4628096635). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks!

**Comment by donovaly** [comment]
I see still an issue: https://forum.freecadweb.org/viewtopic.php?p=601612#p601612

**Pull request merged**
