### PR TITLE
[TechDraw] Simplify return logic, part 1

### PR DESCRIPTION
**Pull request by benj5378**
Easy warmup

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by benj5378** [comment]
@WandererFan Easy warmup

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9221">pipeline status</a> for feature branch [PR_9221](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9221). Pipeline [832168310](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/832168310) was triggered at [0470303](https://github.com/FreeCAD/FreeCAD/pull/9221/commits/0470303d01a64f292bc09b396ac6fb5eb52ad2ff). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by xtemp09** [comment]
src/Mod/TechDraw/App/LandmarkDimension.cpp#L169
unused variable 'result'

Why did you rewrite this
```c++
QRectF result(0, 0,1, 1);
return result;
```
into this:
```c++
return QRectF(0, 0,1, 1);
```

while this:
```c++
double w = 64.0;//must default to something
double h = 64.0;
return (QRectF(0, 0, w, h));
```

into this:
```c++
double w = 64.0;//must default to something
double h = 64.0;
return QRectF(0, 0, w, h);
```
?

Would not it be better to rewrite the latter into just
```c++
return QRectF(0, 0, 64, 64);    //must default to something
```
?

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9221">pipeline status</a> for feature branch [PR_9221](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9221). Pipeline [833133232](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/833133232) was triggered at [51614d0](https://github.com/FreeCAD/FreeCAD/pull/9221/commits/51614d0f7aa8da8d040613fe24f1e0b5c0e23534). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9221">pipeline status</a> for feature branch [PR_9221](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9221). Pipeline [833821912](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/833821912) was triggered at [256fcb1](https://github.com/FreeCAD/FreeCAD/pull/9221/commits/256fcb1153d15b7105bbf28222a539ad90a56ca4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by benj5378** [comment]
@xtemp09 Sorry, that I never got to look on your comment. I appreciate the feedback and knowing that someone took their time to read through my changes!

**Pull request merged**
