### PR TITLE
Update all line-endings to LF (unix-style).

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
The motivation for this is that the proper git settings should be used
so that native file endings are visible in the working directory while
only LF is writen to the actual git database. This makes diffs easier to
read as well as making merging easier as well.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- n/a Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by vocx-fc** [comment]
Wow. I understand your motivation, but... I would be wary of merging a pull request that modifies 2000 files. If I were in charge, I would ask you to break the pull request into 100 smaller requests, maybe by workbench, or so on.

**Comment by ezzieyguywuf** [comment]
100% understand - and I agree.

Honestly, I didn’t think anyone would be interested in this, so I just
“threw it out there”.

If you’ll check the corresponding thread in the freecad forum you can see
that’s there’s a healthy discussion around the best way to do this.

To address your point directly, I can see myself redoing this as follow:

One commit per workbench for all c++ files

One commit for all the various qt config and resource files.

Total of maybe 10 or so commits.

This will likely not touch 100% of the non-binary files, but is very likely
to hit all the files likely to change in the future

**Comment by berndhahnebach** [comment]
As this will never be merged this way, I vote for closing the PR and continue disscusion on how this could be archived and come up with new smaller PRs lager on. 

bernd

**Comment by ezzieyguywuf** [comment]
+1 I’ll close it now

**Pull request closed without merging**
