### PR TITLE
[Bugfix]Sketcher: some user colors aren't taken into account

### PR DESCRIPTION
**Pull request by 0penBrain**
https://forum.freecadweb.org/viewtopic.php?f=3&t=53617

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7429">pipeline status</a> for feature branch [PR_7429](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7429). Pipeline [629527121](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/629527121) was triggered at [2040d51](https://github.com/FreeCAD/FreeCAD/pull/7429/commits/2040d514d1ca3ec3bd429faec84fe12367335b09). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by luzpaz** [comment]
@0penBrain would it be too much to ask to `git commit --amend` this PR and substitute `took` for `taken` in the title?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7429">pipeline status</a> for feature branch [PR_7429](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7429). Pipeline [634290221](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/634290221) was triggered at [c2ad9e6](https://github.com/FreeCAD/FreeCAD/pull/7429/commits/c2ad9e67146e4d797924d1fb33254907f4e47b1f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7429">pipeline status</a> for feature branch [PR_7429](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7429). Pipeline [636513407](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/636513407) was triggered at [c261247](https://github.com/FreeCAD/FreeCAD/pull/7429/commits/c2612479827ad419d03d568b4220191eeb6b1fe8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
many thanks!
(I see I once reported the issue about 2 years ago but forgot to add it to my ToDo list, sorry.)

**Pull request merged**
