### PR TITLE
FEM: Translate Solver Calculix

### PR DESCRIPTION
**Pull request by chennes**
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/94

---

- [X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

### CODE REVIEW

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9349">pipeline status</a> for feature branch [PR_9349](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9349). Pipeline [845061122](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/845061122) was triggered at [e925068](https://github.com/FreeCAD/FreeCAD/pull/9349/commits/e9250684db0a80813b0ba43c0f993fc23a792a5d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by marioalexis84** [comment]
@chennes in `src/Mod/Fem/Gui/Workbench.cpp` the command is called `FEM_SolverCalculiX` with upper case  "X"

**Comment by chennes** [comment]
Good catch, thanks -- I had to pick one thing or the other to change, guess I should have changed the translation call instead! I'll issue another PR to fix it.

**Comment by marioalexis84** [comment]
The official name uses uppercase X, so I guess it's better to change the translation.

**Comment by chennes** [comment]
Everywhere? We also have "FEM_SolverCalculixCxxtools" (lowercase X there).

**Comment by marioalexis84** [comment]
With official I mean [this.](http://www.calculix.de/)
There are some inconsistencies with names related to the CalculiX solver tools, maybe inherited from CalculiX being the unique solver available in the system.
For instance, the name of the CalculiX pixmap is "FEM_SolverStandard". I did a pull request some weeks ago on this topic to change the name to "FEM_SolverCalculiX" but it was rejected.
I'm working on other request to dynamically detect solvers on the system and  this topic comes up again.

**Pull request merged**
