### PR TITLE
Organize TechDraw template translations into locale folders

### PR DESCRIPTION
**Pull request by dplanella**
Currently translations of TechDraw templates lay intermixed with the original English templates, or in folders that do not follow a specific naming structure –e.g. country codes mixed with regional tech drawing standards, language codes, etc.

The purpose of this PR is to create a structure for translators to easily be able to submit their translations, in a standard manner. As such, what this PR does is to:

- Create a `locale` subfolder and move all translations there. Under `locale`, each language has its own subfolder. The naming is based on [IETF BCP 47 language tags](https://en.wikipedia.org/wiki/IETF_language_tag).
- Rename all existing translation subfolders to adhere to IETF BCP 47 language tags. 
- Add a [`README.md`](https://github.com/FreeCAD/FreeCAD/blob/c288df29a8159233675ee59f63706f6870824685/src/Mod/TechDraw/Templates/locale/README.md) file describing the structure above and containing instructions on how to translate TechDraw templates.
- Rename a couple of templates to follow the `SizeStandard_{Portrait|Landscape}_{minimal|advanced}.svg` naming convention from the current template files. These are the files with the `_TD` and `_m52` suffixes (which I do not quite follow what they stand for).

A follow-up PR (https://github.com/FreeCAD/FreeCAD/pull/13369) also adds Catalan translations for the templates.

### CODE REVIEW

**Comment by luzpaz** [comment]
cc @kaktusus

**Comment by PaddleStroke** [comment]
Current situation is indeed a bit messy.
Ideally we could have only english templates and have the application translate them on page creation based on software language. If needed we could also have a language property in the template, so if you freecad is in french and you want to create a spanish page you could still do it.

@WandererFan thoughts on that?

**Comment by kaktusus** [comment]
Subject pertains to the localization of template content used in the TechDraw workbench.
I appreciate the effort, but was this discussed on the forum? You've put in a lot of work :relaxed:, but is this the best possible solution :grey_question:
For me, a reasonable solution is PaddleStroke's proposal to create a universal template that can be localized depending on the FreeCAD GUI language.
When translating GUI, the following rule is applied:

https://doc.qt.io/qt-6/linguist-translating-strings.html#changing-the-target-locale

   >This requires that the translation files adhere to the following file name convention: appname_language[_country].ts, where:

```
    language is an ISO 639 language code in lowercase.
    country is an ISO 3166 two-letter country code in uppercase.
```
    
This is not in doubt. I'm not familiar with the norms used in technical documentation drafting.
I've posted the link on the forum in the translators' section. Perhaps someone else will also want to share their opinion.

**Comment by dplanella** [comment]
Thanks for everyone's replies.

> Current situation is indeed a bit messy. Ideally we could have only english templates and have the application translate them on page creation based on software language. If needed we could also have a language property in the template, so if you freecad is in french and you want to create a spanish page you could still do it.

That would indeed be the ideal situation. In my view there are a few additional points to take into account:

1. This PR is essentially an incremental improvement to ease translation work. It does not preclude a subsequent iteration to automate string extraction, localization, translation building and loading. However, that would be a significant effort that would be beyond the scope of this initial PR. More below.
2. How much development effort is it worth putting in template internationalization of the existing ISO and ANSI standard templates? My assumption is that in a professional environment, an organization will have their own custom templates in the language they use to conduct business. They can just drop their templates in the appropriate folder then.
3. If we really want to be inclusive, other regional standards for those countries which use standardization bodies other than ISO or ANSI should also be provided.
4. How much demand is there from translators and users for improving and using translated TechDraw templates?

In summary, this proposal takes the pragmatic approach of making a self-contained change to ease translations today.

Expanding on point 1. above, the ideal solution would require, among other changes that I'm most probably overseeing:

1. Additional build rules and probably scripts to extract translatable strings from the .svg files and aggregate them per language into a format that can be loaded into Crowdin. Most probably .po or the .ts formats. My assumption is that this would not be extremely complex, as there are probably existing scripts to do the extraction and conversion –it's been a while since I've worked with those tools.
2. Upload to Crowdin and translation. This is already an existing workflow in FreeCAD and I also assume it would not be complex to adopt for templates.
3. Crowdin download. Same as the above
4. Translation building and loading. Building could mean either creating translated .ts files (I guess Crowdin can already provide those) or writing them into localized .svg files. In the first case, then FreeCAD would have to load the translations. In the second case, it would simply read the localized .svg files.

Regardless of the approach, I would guess that this might be an effort that could take months of voluntary work. While I'd be happy to explore it, I wouldn't be able to commit to take it to the finish line.

> I appreciate the effort, but was this discussed on the forum?

Thanks. I did not discuss it on the forum. Neither on Discord. My assumption from how small the changes are and my perception that in most PRs there is not a preliminary forum discussion unless the changes are significant, was that it was not required. In any case, thanks for creating the forum thread.

> You've put in a lot of work ☺️, but is this the best possible solution? For me, a reasonable solution is PaddleStroke's proposal to create a universal template that can be localized depending on the FreeCAD GUI language.

It was not a lot of work. It was mostly providing some minimal structure to the current approach for the scratch-your-own-itch need that I had to submit my own translations :-)

I agree that it is not the most optimal solution, but a pragmatic incremental improvement. See the points above.

> When translating GUI, the following rule is applied: https://doc.qt.io/qt-6/linguist-translating-strings.html#changing-the-target-locale

I'm familiar with both Qt's and Gettext localization. However, the templates are not currently .ts translatable files that Qt picks up for translation. As a Linux user I also recognise them as most common in Linux platforms, whereas in other platforms (FreeCAD being multiplatform) translators might not be as familiar with them. At the end of the day, they are currently just folder names.

Happy to change them to `ll_CC` Qt format, but my thought was that IETF BCP 47 language tags are superior in the sense that they are platform-agnostic and overcome some of the limitations of those other formats.

> This is not in doubt. I'm not familiar with the norms used in technical documentation drafting.

I'm not sure I understand this point. Could you please ellaborate?

> I've posted the link on the [forum](https://forum.freecad.org/viewtopic.php?style=4&t=86792) in the translators' section. Perhaps someone else will also want to share their opinion.

Thank you.

**Comment by FlachyJoe** [comment]
FYI the **_m52** suffix was created by @Mario52 [forum user](https://forum.freecad.org/memberlist.php?mode=viewprofile&u=1058)

**Comment by dplanella** [comment]
> FYI the **_m52** suffix was created by @Mario52 [forum user](https://forum.freecad.org/memberlist.php?mode=viewprofile&u=1058)

Indeed, thanks! It had me scratching my head for a while trying to find out which standard this `m52` was. It turns out to be a user name, but I still don't understand the purpose of shipping it as one of the default templates. A quick search returned this: https://forum.freecad.org/viewtopic.php?p=550563#p550563

**Comment by WandererFan** [comment]
<<These are the files with the _TD and _m52 suffixes (which I do not quite follow what they stand for).>>

Some of the ones with the TD suffix are templates from the old DrawingWB, but I can't remember what was changed.  These are the ones with large file sizes.

The ones with the M52 suffix are improved versions created by @mario52.

Can't remember who created the Pep ones.

**Comment by WandererFan** [comment]
I like the idea of organizing the the templates.   We could put the various non-standard and/or user contributed in separate subdirectory.

I don't know how to translate an svg file.   Is there the an equivalent to tr() and/or QT_TRANSLATE_NOOP for svg?

**Comment by PaddleStroke** [comment]
From what I can see some of the text in the templates can be modified by freecad (name of author for example).

So what we can do is to create a SVG with keys for each sentence. So for example : 
#AuthorName
#ScaleName

Then in freecad cpp, when the svg is loaded into a template object, the key strings are replaced by translated text. So : 
```
if (keyText == "#AuthorName"){
     newText = QT_TRANSLATE_NOOP("Author Name");
}
replaceTextInTemplate(keyText, newText);
```

**Comment by dplanella** [comment]
> Can't remember who created the Pep ones.

After some quick research:

1. The Pep templates were reportedly created by user Peppino: https://forum.freecad.org/viewtopic.php?t=31265&start=20
2. Those Pep templates were removed with PR https://github.com/FreeCAD/FreeCAD/pull/12736
3. The TD templates were also removed with the PR above, but there are still some leftovers

@WandererFan are you happy with the scope and changes in this PR, as a first iteration for more structured templates and translations?

**Comment by WandererFan** [comment]
There is lots of text in a typical template that is never touched by our code and the fields that are touched (freecad:editable and freecad:autofill fields like author-name) really should not be translated.

We could invent a new tag (freecad:translatable?) to mark text in the template, but we would need to also invent something to extract the text and send it to the translators.   Then we would use a similar process to freecad:autofill to change the template text at time of use. 

This is a significant chunk of work, and as @dplanella said, out of scope for this PR.

**Comment by WandererFan** [comment]
<<@WandererFan are you happy with the scope and changes in this PR, as a first iteration for more structured templates and translations?>>

Generally, yes, but I'm not sure that we need a directory for every language variation.   All the en_XX could go into one directory. 

We have some directories (like GOST) that are a combination of language and standards organization.  Will we then need ru_RU/GOST and ru_RU/ISO?  

Maybe we should only include a minimal subset of templates in the distribution and people who need something different could keep local templates.  Probably need a template maker tool for this to be viable.

**Comment by tobiasfalk** [comment]
The main Problem with Translation that I see, is that the Translation it self from the dependent from the style/template is.
The "Author" field can also be called "Created by", and there is no one way to translate then correctly.
So a solution where the Translation is embedded in to the SVG would be the best,  I think.
Maybe placing the text in to a Group with the attribute "translatable" and on child is the text and then there other children "translation" with the attributes of a language and the translated text.

**Comment by tobiasfalk** [comment]
What I mean:
```
<g freeecad:translatable="yes">
    <text .....>Dummy Text that gets replaced</text>
    <translation language="de_de"> Erstellt bei: </translation>
    <translation language="de_at"> Erstellt durch: </translation>
    <translation language="en_uk"> Created by: </translation>
    <translation language="en_us"> Author: </translation>
</g>
```

**Comment by kaktusus** [comment]
> The main Problem with Translation that I see, is that the Translation it self is dependent from the style/template. The "Author" field can also be called "Created by", and there is no one way to translate then correctly. So a solution where the Translation is embedded in to the SVG would be the best, I think. Maybe placing the text in to a Group with the attribute "translatable" and on child is the text and then there other children "translation" with the attributes of a language and the translated text.

_Very reasonable suggestions._

Perhaps now is a good time to systematize everything so that all templates are built according to established rules. Let this also apply to the template (rules) for file names.

**Comment by tobiasfalk** [comment]
Just out of interest, why is this not yet Merged or Closed?
For now until a translation system is put in place I think organising the templates is a good thing.

**Comment by mario52a** [comment]
Hi

good idea for organization and automatic translation of the template

my files **A3_Landscape_EN_m52.svg, A3_Landscape_IT_m52.svg, A3_Landscape_FR_m52.svg**  (English, Italian and French)

work with TechDraw the difference with the standard FreeCAD templates is that all fields are editable _(even the copyright)_

all my other templates and macros only work on the old Draw workBench

**PS:** the name **@Mario52** does not belong to me _( the name had already been used when i registered on GitHub)_

on gist.github i am [https://gist.github.com/mario52a](url)  (mario52a) and on github [https://github.com/mario52a](url) (mario52a)

@Mario52 sorry for the inconvenience and welcome to all Mario ... 52 ... xxx

mario

**Comment by dplanella** [comment]
For the sake of completeness, adding some notes to address @WandererFan's points. Thanks again for the review and for merging this.

> Generally, yes, but I'm not sure that we need a directory for every language variation. All the en_XX could go into one directory.

The one-folder-per-language-variant approach adopted for this PR simply to follow the gettext convention. I believe Qt does this slightly differently, but in both cases variants are independent files or folders. Not that it makes much of a difference in this case, as we're just organizing localized files into folders, but not actually loading translations.

However, a minor practical advantage of following this practice is that the user will not have to transverse so many folders (i.e. less clicks) to load the templates in their language they are after.

> We have some directories (like GOST) that are a combination of language and standards organization. Will we then need ru_RU/GOST and ru_RU/ISO?

I would think so, yes. Perhaps another way of thinking might be to consider that the structure under the `locale/ll-CC` folders is not defined. That is, it is up to the translators to decide which and if to translate the original English templates. More on this on the comment below.

> Maybe we should only include a minimal subset of templates in the distribution and people who need something different could keep local templates. Probably need a template maker tool for this to be viable.

Agreed. If I'm not mistaken, currently the main English-only source templates cover only standard sizes from ISO and ANSI, which might not even apply to some countries. In that regard, translators from those countries would not localize them and ship the templates of their relevant regional standard bodies instead.

**Pull request merged**
