### PR TITLE
Path: sort shapes in multi-object operations like face profiles

### PR DESCRIPTION
**Pull request by m0n5t3r**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

a bit of a writeup with pictures is here: https://forum.freecadweb.org/viewtopic.php?f=15&t=34597&sid=95c8693eddcea2d11d3a1b237b4ea35c&start=10#p293886 (probably wrong thread, because I misunderstood the subject)

I'm not sure `PathAreaOp` is the right place to do the change, but since it impacts the order of operations and not the operations themselves I guess it should be safe

### CODE REVIEW

**Comment by wwmayer** [comment]
@sliptonic or others please check if this change can be merged. Thanks!

**Comment by sliptonic** [comment]
Looks good.  please merge

**Comment by m0n5t3r** [comment]
Does this need anything else?

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
