### PR TITLE
macOS+win+qt6.4+: Hide classic and auto choose light or dark mode depending on os setting

### PR DESCRIPTION
**Pull request by hyarion**
This is a workaround for the broken default style "classic" on macOS when in dark mode (system settings).

When using dark mode on macOS FreeCAD, in classic, looks like this:
image

While it would be nice with a working classic theme, as a last resort for 1.0 this might be a solution to give new users a good first impression.

The issue has been reported on windows 11 as well.

The workaround does the following (if running on macOS, Windows, or has qt 6.4+):
* hides classic button in the start welcome screen (can still change to it in preferences)
* if the user has never selected a style, it auto-selects light or dark depending on system dark/light mode setting - default to light mode if it can't auto detect system setting (only works on macOS and qt6.4+).

https://github.com/user-attachments/assets/b232caab-789c-4292-919a-ca7265f3073a

Verification (help needed):
 - [x] Qt 5 macOS
 - [ ] Qt 5 windows
 - [ ] Qt 6.4 macOS
 - [ ] Qt 6.4 windows
 - [ ] Qt 6.4 linux
 - [ ] Qt 6.5+ any system

To test this:
1. Set system to light mode 
2. Restart freecad in safe mode
3. Light mode should now be used for gui
4. mac & win & other with qt6.4: classic should be hidden (only show light and dark options)
5. Set system to dark mode
6. Restart freecad into safe mode
7. mac & qt6.4+: dark mode should now be used for gui (light mode will be used for other systems)
8. mac & win & other with qt6.4+: classic should still be hidden (only show light and dark options)

### CODE REVIEW

**Comment by maxwxyz** [comment]
@FreeCAD/design-working-group FYI

**Comment by hyarion** [comment]
I hate to say it but I think this might be as important as https://github.com/FreeCAD/FreeCAD/issues/15756

FreeCAD on macOS in dark mode is in a really bad state with default settings (no theme selected). White text on light backgrounds, black text on dark backgrounds (see screenshot)

**Comment by maxwxyz** [comment]
I know, I've created a lot of issues for classic theme also on Mac. Just wait for feedback on the Pr as touching classic or even hiding it was not well recieved on the past, even by DWG.

**Comment by MisterMakerNL** [comment]
Would recommend this for windows too, especially with the broken Windows 11.

**Comment by pierreporte** [comment]
Classic theme is going to be deprecated at some point anyway. If we want a classic-like theme we can still create it using light theme as a base.

**Comment by kadet1090** [comment]
This probably should be merged for 1.0, I was initially (very) skeptical about such change but given the sheer amount of problems that we experience now on newer platforms with untested QStyles (Windows11, OS X, multiple Linux ones) and problems with dark palettes that were never tested to work with classic this seems like only logical option. 

We should also enable this at least on Windows 11 as it causes a lot of other issues as well. I'd even argue that for consistency sake we should do that on all platforms - if someone wants to go back to classic it is possible from literally the first page that anyone sees. 

@maxwxyz @FreeCAD/maintainers I think that this should at least be discussed on merge next merge meeting as without it we will get a lot of bad press because of critical UI issues like mentioned in this PR.

**Comment by maxwxyz** [comment]
@hyarion does this also fix:
- https://github.com/FreeCAD/FreeCAD/issues/16263

**Comment by FEA-eng** [comment]
I'm using FreeCAD mostly on Windows 10 and I haven't noticed any issues with the Classic style. One of my computers has Windows 11 and I haven't encountered any problems there either but I use that OS less frequently.

I don't mind one of the new themes being set as default, it might also give a good impression as it brings a little bit of freshness to the GUI for 1.0. I'm just a bit hesitant about removing Classic from the theme selection list on the first start setup page. On macOS it might make sense if Classic is so severely broken there but I'm not sure I would do it on Windows. Still, I won't complain as long as Classic can be enabled in the Preferences.

In the long run, I agree that Classic should be replaced by something more modern. The new styles were introduced quite recently and still have some issues but they could be further improved to serve as new defaults replacing the outdated Classic style's look. Personally, I would prefer something more revolutionary, making FreeCAD look much more modern in the near future. Open themes are really awesome in this regard - I'd love them to be built-in and default at some point.

**Comment by hyarion** [comment]
I've changed this to be enabled on macOS and Qt 6.4.
I'm not able to auto-detect if the system is in dark mode on anything else (I don't have any linux or windows computer)

I can remove classic on all platforms from the selector, but that would force light mode on everyone (exce3pt mac and qt6.4). Would that be preferred for consistency in this view?

**Comment by maxwxyz** [comment]
I'd be in favor of removing Classic in the selector on the systems where it has issues (Windows + macOS).

**Comment by hyarion** [comment]
I've updated the description now with the new behavior:
* hides classic button in the start welcome screen (can still change to it in preferences)
* if the user has never selected a style, it auto-selects light or dark depending on system dark/light mode setting - default to light mode if it can't auto detect system setting (only works on macOS and qt6.4+).

**Comment by chennes** [comment]
Is this marked "draft" purely because it needs more testing? Or is there still work to be done?

**Comment by chennes** [comment]
FYI, according to StackOverflow:

> Since Qt 6.5 the official way of detecting dark or light theme is getting QGuiApplication::styleHints() and then calling QStyleHints::colorScheme() and testing whether the returned value is either Qt::ColorScheme::Dark or Qt::ColorScheme::Light. For detecting the theme change event event, I am catching QEvent::ThemeChange in the main window's changeEvent() handler.

**Comment by hyarion** [comment]
> Is this marked "draft" purely because it needs more testing? Or is there still work to be done?

Yes, it is because it needs testing. But I can promote it to ready for review.

> FYI, according to StackOverflow:

Yes, but I figured it would be better to simplify the change by doing the 6.4 way. That way we don't need to test on all platforms for 6.5 too.

**Comment by MisterMakerNL** [comment]
Shared this link a gazzilion times but here again :)
https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5

**Comment by hyarion** [comment]
> Shared this link a gazzilion times but here again :) https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5

It's even in a comment in the code as a reference:
https://github.com/FreeCAD/FreeCAD/pull/17410/files#diff-b79c7beb692b7669e36692fe2b97ff9c92e2046a891f4dbcb9afe3c72d8dad29R51

But again, I wanted to simplify the PR. I will have enough problems getting everything tested as is :)

If you want, I will add the 6.5+ way, but that will add 2 more systems to test.

**Comment by chennes** [comment]
For the record, I can only test on Windows with the LibPack, which is Qt 6.7. So I can't test 6.4 or 6.5 directly.

**Comment by hyarion** [comment]
@chennes 6.7 should work too (I've updated 6.5 to 6.5+ in the description now)

**Comment by chennes** [comment]
OK, but testing Qt 6.7/Windows 11, only the first half of the process works -- Classic mode is hidden. But regardless of what my system theme is set to, Light mode is chosen. This is still actually an improvement because Classic is literally unusable in Qt6/Windows Dark Mode, but it is not the expected behavior, so at some point we really do need to add proper Qt 6.5+ Dark Mode detection. Honestly, I'd drop all the special coding for MacOS dark mode detection, and rely entirely on Qt6.5+ detection.

**Comment by hyarion** [comment]
@chennes thanks for testing. I'll add the 6.5 code path.

The only detection that has been verified is the macOS code path. Why do you want to remove that?

**Comment by chennes** [comment]
At this point the Windows 11 Qt 6.7 build should autoselect dark mode if the system in using a dark mode, right? (I ask because it doesn't).

**Comment by hyarion** [comment]
@chennes yes it should 😞 

This isn't going as I hoped... But as the alternative is to always start in light mode, which is the current fallback, so maybe it's ok that it doesn't work? At least there's a framework that someone else can add a working detection to.

**Comment by chennes** [comment]
> This isn't going as I hoped... But as the alternative is to always start in light mode, which is the current fallback, so maybe it's ok that it doesn't work?

Right -- I will poke at it for a few minutes tonight, but if the solution isn't obvious I think we should just merge this as-is (since it is an improvement) and file an Issue for the Qt6.5+ darkmode detection problem.

**Comment by chennes** [comment]
OK, I don't know what I was testing earlier, but it was clearly not the latest version of this PR (I know this because the latest version didn't compile with MSVC/PCH enabled, hence the added commit!). Anyway, it does in fact work correctly on Windows 11/Qt 6.7.

**Comment by hyarion** [comment]
(this fixes https://github.com/FreeCAD/FreeCAD/issues/17126 )

**Comment by yorikvanhavre** [comment]
backported

**Pull request merged**
