### PR TITLE
py3/py2: use exec as function

### PR DESCRIPTION
**Pull request by looooo**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
forum topic:
https://forum.freecadweb.org/viewtopic.php?f=10&t=36186

**Comment by berndhahnebach** [comment]
very strange ... if I cherry-pick your commit this line gets not changed for me. But the commit surely changes the line. I never had such problems ... https://github.com/looooo/FreeCAD/commit/61ebb0b3589cac9c19e94336c2751103115e8783#diff-df05731fe2a8f1f74d9318c3988ce35aL694

**Comment by looooo** [comment]
oh, ci's are failing... I guess the python2 version in use is too old to support exec as function...

**Comment by berndhahnebach** [comment]
somehow it still does the old one see my last forum post. Very, very strange. Would it be possible to you to test your PR on BOLTS, if you get around the problem.
bernd

**Comment by looooo** [comment]
This is a really awful thing. Threre is already a conditional for qt4/qt5. Now we need to add another one for py2/py3. Is it somehow possible to use a newer python2.7. locally I have python2.7.15rc1 which allows to use exec as function.

**Comment by wwmayer** [comment]
See cd74f2e92

**Pull request closed without merging**
