### PR TITLE
Gui: improve PropertyEditor refresh

### PR DESCRIPTION
**Pull request by realthunder**
Forum post: https://forum.freecadweb.org/viewtopic.php?f=10&t=46388&p=403983#p403983

### CODE REVIEW

**Comment by vocx-fc** [comment]
This has nothing to do with your pull request, but I was wondering, is `obj.setPropertyStatus(prop, "ReadOnly")` equivalent to `obj.setEditorMode(prop, 1)`. Or what is the difference? EditorMode sounds like it only affects the property editor, while PropertyStatus sounds like it affects the object itself. But in both cases, they seem to work the same. Also for other status, like Hidden. Is it better to use PropertyStatus now?

**Comment by realthunder** [comment]
The original `setEditMode()` only supports 'Hidden' and 'ReadOnly' by manipulating the property status bits internally. The new `setPropertyStatus()` exposed more status bits. For `Hidden` and `ReadOnly`, they are the same. You can call `obj.getPropertyStatus()` to list all the supported status bits. Maybe we can add some document to explain this bits. Meanwhile, the definition of the bits can be found [here](https://github.com/FreeCAD/FreeCAD/blob/2330eef823b32ac412d839031cc174353a76b013/src/App/Property.h#L63), not all of them are accessible.

**Comment by vocx-fc** [comment]
Yes, I saw the list recently while testing hiding and showing some properties with `onChanged`, as in that thread about PartDesign fillets.

I did some tests and I saw that with `getPropertyStatus` I was able to get a list, but not all bits were listed. Then I set one, I think `Hidden`, and then after `getPropertyStatus` it appeared on the list this time.

**Comment by vocx-fc** [comment]
Oh, since we are talking about the property editor, I noticed something. It seems that if we add an `App::PropertyPlacement` to an object, the property editor will show as tooltip the Axis, Angle and Position. But the tooltip that one manually enters with `addProperty` is discarded.
```py
addProperty(App::PropertyPlacement, ExtraPlacement, Group, "This documentation string is discarded")
```

Would it be possible to concatenate the current tooltip (the Axis, Angle, and Position) to the custom documentation string? I would like to write a tooltip for the user explaining what this additional placement does. In my case I would use it to introduce an additional displacement and rotation on the position of array elements.

I'm not sure how many properties behave like this, that is, they don't display the defined documentation string, and instead show their own tooltip.

**Comment by realthunder** [comment]
> I did some tests and I saw that with `getPropertyStatus` I was able to get a list, but not all bits were listed. Then I set one, I think `Hidden`, and then after `getPropertyStatus` it appeared on the list this time.

If you call `getPropertyStatus()` without argument, it will list all exposed status bits, instead of the current status bits of the requested property.


> I'm not sure how many properties behave like this, that is, that don't display the user defined documentation string, and instead show their own tooltip.

There are quite a few types of property items behave like this. I just pushed a new commit to fix it. The first column tooltip will show the documentation, while the second column tooltip remain unchanged.

**Comment by vocx-fc** [comment]
About your latest commit, is this going to be displayed at all times? Or only when you select `Show all`? I ask because the tooltip is more complete when you select this option, as it includes the type information. Ideally the behavior I am talking about is displayed without having to choose `Show all`.

**Comment by vocx-fc** [comment]
Okay, I tested your branch, and it compiles fine. Now the name and type of the property are shown all the time, without having to choose `Show all`. I like this behavior. Also the collapsible groups are nice.

However, with the particular placement property, the behavior that is see is this. If the property doesn't have a user defined tooltip, it will show the values of `Axis`, `Angle`, and `Position` in the tooltip. If there is a user defined tooltip, it will show this user definition, and won't show `Axis`, `Angle`, and `Position` any more. I think the ideal case is to show both, the `Axis`, `Angle`, and `Position`, and the user defined text.

I also tested your script in the forum and it seems to work.

**Comment by realthunder** [comment]
> However, with the particular placement property, the behavior that is see is this. If the property doesn't have a user defined tooltip, it will show the values of `Axis`, `Angle`, and `Position` in the tooltip. If there is a user defined tooltip

The tooltip is different for each column. The first column, i.e. the property name column, will show the property type, name and documentation. The second column may show either the detail value or documentation depending on the property type.

**Comment by vocx-fc** [comment]
Okay, I see what you mean. I think previously it was a single message in both columns. So, yes, I guess this solves the issue.

**Comment by vocx-fc** [comment]
Hey realthunder, a question. I see that `PropertyVectorList` isn't displayed in the property editor, unless `Show all` is checked. Is there a reason for this?

Even if I use `obj.setEditorMode("MyProperty", 0)` or `obj.setPropertyStatus("MyProperty", "-Hidden")`, it is not displayed.

Are there other properties like that, that are really hidden unless using `Show all`?

**Comment by realthunder** [comment]
> Are there other properties like that, that are really hidden unless using `Show all`?

Each property has a function `getEditorName()` to return the class name for its editor. Only those properties that have an editor will be shown in the property view. `PropertyVectorList` does not have one. When `Show all` is active, the property view will create a read only item for those that have no editor, to show the Python content of the property.

**Comment by vocx-fc** [comment]
Hey, realthunder, another question. Would it be possible to set the format of a property that is read only to, say, italics or another style? This would improve the amount of information that the property editor provides at a glance, similar to when the hidden properties are shown in yellow, or the link properties in green.

Actually, a bigger improvement is described in this thread, [Feature Request: Standing out icons.](https://forum.freecadweb.org/viewtopic.php?t=44031#p375521). Essentially, it would be interesting to be able to highlight those properties that were changed from their default value. However, DeepSOIC is right in that it may be difficult to indicate a default value because essentially every object modifies the properties on creation. Maybe there could be a mechanism for registering the default values of a particular class and property.

**Comment by chennes** [comment]
It looks to me that based on the above conversation this is ready for merging -- @realthunder when you have a few minutes can you resolve the listed conflicts?

**Comment by berndhahnebach** [comment]
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

**Comment by donovaly** [comment]
can you please rebase?

approved by @yorikvanhavre and @chennes so when it is rebased, it can be merged.

**Comment by donovaly** [comment]
@realthunder , please rebase that it can be merged.

**Comment by freecadci** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_3535">pipeline status</a> for feature branch [PR_3535](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_3535). Pipeline [475472440](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/475472440) was triggered at [7a5d846](https://github.com/FreeCAD/FreeCAD/pull/3535/commits/7a5d84615c3013ece6cc9e48094ace573a84a134). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks for rebasing.

**Comment by marioalexis84** [comment]
Regression reported https://forum.freecadweb.org/viewtopic.php?f=23&t=66992

**Pull request merged**
