### PR TITLE
Update libs into  .pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by mosfet80**
https://github.com/psf/black/releases/tag/24.10.0
https://github.com/pre-commit/pre-commit-hooks/releases/tag/v5.0.0

### CODE REVIEW

**Comment by chennes** [comment]
How many lines will this formatting update impact?

**Comment by maxwxyz** [comment]
@mosfet80 waiting for feedback

**Comment by maxwxyz** [comment]
bump

**Comment by chennes** [comment]
I can answer my own question: none. It is not a mistake that there is no pre-commit CI commit attached to this PR, neither of these changes result in any formatting changes to our codebase. As such, I am going to merge this.

**Pull request merged**
