### PR TITLE
Sketcher hidding constraints

### PR DESCRIPTION
**Pull request by abdullahtahiriyo**
Another mini-feature. Ability to independently show/hide driving/reference constraints.

### CODE REVIEW

**Comment by abdullahtahiriyo** [comment]
Thread:
https://forum.freecadweb.org/viewtopic.php?f=10&t=21878&p=170204#p170204

**Comment by wwmayer** [comment]
This PR doesn't work. As soon as a sketch is created and edit mode is entered it crashes somewhere in ViewProviderSketch::draw because the index passed to SoGroup::getChild() is out of range.

**Comment by abdullahtahiriyo** [comment]
Surprising! isn't it? This happens when you test all your functionality with an existing sketch and never creating a new one. Now it works. Thanks for reporting!

**Comment by wwmayer** [comment]
Merged.

**Pull request closed without merging**
