### PR TITLE
[Draft] Layers override

### PR DESCRIPTION
**Pull request by JeromeL63**
Separate line and shape colors override

### CODE REVIEW

**Comment by vocx-fc** [comment]
I strongly suggest you split your single pull request into two pull requests, because you are introducing two separate things. One is the new Arch_CutLine in the Arch Workbench, and the other is a change to the Draft Layer behavior in the Draft Workbench.

You should also reference a thread in the forum where the changes are discussed.

See the forum thread: [draft layer separate line and shape color override](https://forum.freecadweb.org/viewtopic.php?p=348640#p348640)

**Comment by berndhahnebach** [comment]
If you would make a separate PR for the layer changing I would merge it immediately but mergeing a new tool in Draft or Arch needs to pass Yoriks eyes.

**Comment by JeromeL63** [comment]
Hello, I have no time this week to do that, it's a mistake. I haven't separated layer override and the new cut with line feature.
I'll try to separate them next week if I can, and make 2 PR separated :'(

**Comment by JeromeL63** [comment]
Ok. Done:
[](https://github.com/FreeCAD/FreeCAD/pull/2749)

**Pull request closed without merging**
